### ISSUE TITLE
[SCRetentionCompliancePolicy]: The policy is not created and no error is thrown

### ISSUE THREAD

**Issue by robertreems** [microsoft/Microsoft365DSC#1004]
## ISSUE DESCRIPTION 
This might be related to https://github.com/microsoft/Microsoft365DSC/issues/1003. 

I'm having issues with creating a compliance centre retention policy. The DSC-configuration enacts just fine but doesn't create an actual policy. 

#### Verbose logs showing the problem
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer rvrWin10 with user sid S-1-5-21-2664334036-1954401872-4188792512-500.
VERBOSE: The -Force option was specified with the Stop operation. The current configuration has been successfully cancelled.
VERBOSE: An LCM method call arrived from computer rvrWin10 with user sid S-1-5-21-2664334036-1954401872-4188792512-500.
VERBOSE: [rvrWin10]: LCM:  [ Start  Set      ]
VERBOSE: [rvrWin10]: LCM:  [ Start  Resource ]  [[SCRetentionCompliancePolicy]SCRetentionCompliancePolicy_XXX.onmicrosoft.com::[Compliance]test_configuration]
VERBOSE: [rvrWin10]: LCM:  [ Start  Test     ]  [[SCRetentionCompliancePolicy]SCRetentionCompliancePolicy_XXX.onmicrosoft.com::[Compliance]test_configuration]
VERBOSE: [rvrWin10]:                            [[SCRetentionCompliancePolicy]SCRetentionCompliancePolicy_XXX.onmicrosoft.com::[Compliance]test_configuration] Testing configuration of RetentionCompliancePolicy for RVR2021test7Year
VERBOSE: [rvrWin10]:                            [[SCRetentionCompliancePolicy]SCRetentionCompliancePolicy_XXX.onmicrosoft.com::[Compliance]test_configuration] Getting configuration of RetentionCompliancePolicy for RVR2021test7Year
WARNING: [rvrWin10]:                            [[SCRetentionCompliancePolicy]SCRetentionCompliancePolicy_XXX.onmicrosoft.com::[Compliance]test_configuration] Your connection has been redirected to the following URI: "https://eur05b.ps.compliance.pro
tection.outlook.com/Powershell-LiveId?BasicAuthToOAuthConversion=true;PSVersion=5.1.17763.1490
VERBOSE: [rvrWin10]:                            [[SCRetentionCompliancePolicy]SCRetentionCompliancePolicy_XXX.onmicrosoft.com::[Compliance]test_configuration] RetentionCompliancePolicy RVR2021test7Year does not exist.
VERBOSE: [rvrWin10]:                            [[SCRetentionCompliancePolicy]SCRetentionCompliancePolicy_XXX.onmicrosoft.com::[Compliance]test_configuration] Current Values: Enabled=True; Ensure=Absent; ExchangeLocation=(All); GlobalAdminAccount=Sys
tem.Management.Automation.PSCredential; Name=RVR2021test7Year; Verbose=True
VERBOSE: [rvrWin10]:                            [[SCRetentionCompliancePolicy]SCRetentionCompliancePolicy_XXX.onmicrosoft.com::[Compliance]test_configuration] Target Values: Enabled=True; ExchangeLocation=(All); GlobalAdminAccount=System.Management.A
utomation.PSCredential; Name=RVR2021test7Year; Verbose=True
VERBOSE: [rvrWin10]:                            [[SCRetentionCompliancePolicy]SCRetentionCompliancePolicy_XXX.onmicrosoft.com::[Compliance]test_configuration] Test-TargetResource returned True
VERBOSE: [rvrWin10]: LCM:  [ End    Test     ]  [[SCRetentionCompliancePolicy]SCRetentionCompliancePolicy_XXX.onmicrosoft.com::[Compliance]test_configuration]  in 11.7150 seconds.
VERBOSE: [rvrWin10]: LCM:  [ Skip   Set      ]  [[SCRetentionCompliancePolicy]SCRetentionCompliancePolicy_XXX.onmicrosoft.com::[Compliance]test_configuration]
VERBOSE: [rvrWin10]: LCM:  [ End    Resource ]  [[SCRetentionCompliancePolicy]SCRetentionCompliancePolicy_XXX.onmicrosoft.com::[Compliance]test_configuration]
VERBOSE: [rvrWin10]: LCM:  [ Start  Resource ]  [[SCRetentionComplianceRule]SCRetentionComplianceRule__XXX.onmicrosoft.com::[Compliance]test_configuration]
VERBOSE: [rvrWin10]: LCM:  [ Start  Test     ]  [[SCRetentionComplianceRule]SCRetentionComplianceRule__XXX.onmicrosoft.com::[Compliance]test_configuration]
VERBOSE: [rvrWin10]:                            [[SCRetentionComplianceRule]SCRetentionComplianceRule__XXX.onmicrosoft.com::[Compliance]test_configuration] Testing configuration of RetentionComplianceRule for RVR2021test7YearRule
VERBOSE: [rvrWin10]:                            [[SCRetentionComplianceRule]SCRetentionComplianceRule__XXX.onmicrosoft.com::[Compliance]test_configuration] Getting configuration of RetentionComplianceRule for RVR2021test7YearRule
WARNING: [rvrWin10]:                            [[SCRetentionComplianceRule]SCRetentionComplianceRule__XXX.onmicrosoft.com::[Compliance]test_configuration] Your connection has been redirected to the following URI: "https://eur05b.ps.compliance.protec
tion.outlook.com/Powershell-LiveId?BasicAuthToOAuthConversion=true;PSVersion=5.1.17763.1490
VERBOSE: [rvrWin10]:                            [[SCRetentionComplianceRule]SCRetentionComplianceRule__XXX.onmicrosoft.com::[Compliance]test_configuration] RetentionComplianceRule RVR2021test7YearRule does not exist.
VERBOSE: [rvrWin10]:                            [[SCRetentionComplianceRule]SCRetentionComplianceRule__XXX.onmicrosoft.com::[Compliance]test_configuration] Target Values: GlobalAdminAccount=System.Management.Automation.PSCredential; Name=RVR2021test7
YearRule; Policy=RVR2021test7Year; RetentionDuration=2492; RetentionDurationDisplayHint=Years; Verbose=True
VERBOSE: [rvrWin10]:                            [[SCRetentionComplianceRule]SCRetentionComplianceRule__XXX.onmicrosoft.com::[Compliance]test_configuration] Test-TargetResource returned True
VERBOSE: [rvrWin10]: LCM:  [ End    Test     ]  [[SCRetentionComplianceRule]SCRetentionComplianceRule__XXX.onmicrosoft.com::[Compliance]test_configuration]  in 8.4920 seconds.
VERBOSE: [rvrWin10]: LCM:  [ Skip   Set      ]  [[SCRetentionComplianceRule]SCRetentionComplianceRule__XXX.onmicrosoft.com::[Compliance]test_configuration]
VERBOSE: [rvrWin10]: LCM:  [ End    Resource ]  [[SCRetentionComplianceRule]SCRetentionComplianceRule__XXX.onmicrosoft.com::[Compliance]test_configuration]
VERBOSE: [rvrWin10]: LCM:  [ End    Set      ]
VERBOSE: [rvrWin10]: LCM:  [ End    Set      ]    in  21.0070 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 21.754 seconds

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
I'm using the following composit configuration:

```powershell
Configuration Compliance
{
    param(
        
        [Parameter(Mandatory)]
        [PsCredential]
        $credsGlobalAdmin
    )
    
    Import-DscResource -ModuleName Microsoft365DSC -ModuleVersion 1.20.1209.1

    # Get the org domain
    $tenantOrganisation = ($credsGlobalAdmin.UserName -split '@')[1]
    
    SCRetentionCompliancePolicy "SCRetentionCompliancePolicy_$tenantOrganisation"
    {
        GlobalAdminAccount              = $credsGlobalAdmin

        Name                            = 'RVR2021test7Year'
        Enabled                         = $true

        ExchangeLocation                = 'All'

    }

    SCRetentionComplianceRule "SCRetentionComplianceRule__$tenantOrganisation"
    {
        
        GlobalAdminAccount              = $credsGlobalAdmin
        
        Name                            = 'RVR2021test7YearRule'
        Policy                          = 'RVR2021test7Year'
        RetentionDuration               = '2492' # Days

        # The RetentionDurationDisplayHint parameter specifies the units that are used to display the 
        # retention duration in the Security and Compliance Center. Valid values are: Days, Months or Years.	
        RetentionDurationDisplayHint    = 'Years'

    }
}

```

#### The operating system the target node is running

The computer information:
```
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

The PowerShell version:
```
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.20.1209.1

**Comment by NikCharlebois** [comment]
@desmay same goes for this one if you have cycles to have a look. Thanks

**Comment by NikCharlebois** [comment]
Looks like you are missing the:
    Ensure = "Present"
Parameter for both the policy and the rule
