### ISSUE TITLE
Error while Compiling  the M365TenantConfig.ps1 into MOF file format

### ISSUE THREAD

**Issue by kigsandrew** [microsoft/Microsoft365DSC#1007]
I get the error below when i try to compile the M365TenantConfig.ps1 into MOF file format

![error](https://user-images.githubusercontent.com/69600611/103825971-e6ca9880-5043-11eb-95eb-dbfa1c4dee9f.PNG)

Any help is highly appreciated.

**Comment by NikCharlebois** [comment]
@kigsandrew any chances you could post the code snippets you are using in your configuration for AADRoleDefinition? Thanks

**Comment by kigsandrew** [comment]
Thanks NikCkarlebois, this the screenshot of the AADRoleDefinition that have errors i got from VsCode. 
![NewVS](https://user-images.githubusercontent.com/69600611/104030434-661db080-5199-11eb-8cc3-c924c6a18679.PNG)

**Comment by kigsandrew** [comment]
The description is always: Deprecated-Do not use. I dont know the source of the error, i just followed your video on Export-M365DSCConfiguration followed by compile the configuration to MOF, which cannot do bse of the errors.

**Comment by kigsandrew** [comment]
For each of these errors, the property "Role Permissions" is missing, hence no string Array input. i don't know how to fix this.

**Comment by NikCharlebois** [comment]
I am submitting a PR that will filter out definitions without RolePermissions from the export. Since that parameter is mandatory, that is our only option.

**Comment by kigsandrew** [comment]
Thanks , so i try again to do the export?

**Comment by NikCharlebois** [comment]
You can either grab the Dev branch from GitHub or wait until next wednesday for release 1.21.113.1 to be published to the PowerShell Gallery before doing it. Thanks

**Comment by kigsandrew** [comment]
Ok thanks, how do i locate The dev branch!

**Comment by kigsandrew** [comment]
i managed to download the dev branch:Microsoft365DSC-Dev.zip, but i dont know what to run, after download.

**Comment by desmay** [comment]
You can use the Install-M365DSCDevBranch to install Dev code

**Comment by kigsandrew** [comment]
Thanks Desmay

**Comment by kigsandrew** [comment]
i run the install-M365DSCDevBranch to install the Dev code but i still get the errors after exporting 
![dev](https://user-images.githubusercontent.com/69600611/104109981-3f4aa180-52a1-11eb-835f-b079c4c6e670.PNG)

**Comment by kigsandrew** [comment]
This is the error i get at the end,  when i run Install-M365DSCDevBranch command
![error2](https://user-images.githubusercontent.com/69600611/104135154-3a96f380-535c-11eb-8bf1-03ba415644a7.PNG)

**Comment by kigsandrew** [comment]
@NikCharlebois, am double checking if Microsoft DSC version 1.21.113.1 was published today, i cannot seem to find it in the powershell gallery.
