### ISSUE TITLE
NewResourceName: Named Locations

### ISSUE THREAD

**Issue by RVAHaver01** [microsoft/Microsoft365DSC#1014]
### Description
 You are currently pulling AAD Conditional Access Policies but are not pulling Named Locations.  This could cause a failure if the Named Location you wish to use is not there.
### Proposed properties
 Please add Named Locations to the DSC so that they can be added for GEO Fencing reasons.  We typically exclude all outside of US for the vast majority of our customers.  We typically have one that is US Only also.  We would like to be able to use this tool to add Named Locations.

**Comment by RVAHaver01** [comment]
PowerShell was recently updated (10/2020) to allow you to get this information so this is the next logical step.

**Comment by NikCharlebois** [comment]
@peterabele is this something you can look into? Thanks

**Comment by peterabele** [comment]
Yes, I will develop the named location resource soon. Having named locations in the CA policies won't cause any failure, it is supported now, too. You can use named locations in location conditions when defining CA policies through DSC, and CA policy DSC export will contain the named locations configured under location conditions. 
As soon as we'll have the named location resource, you will also be able to manage and export the list of named locations. 
Will keep you posted...

**Comment by peterabele** [comment]
Named Location DSC resource code is ready, will write the example and test module early next week, and do a PR.

**Comment by RVAHaver01** [comment]
Great work.

David Haver
Manager, Infrastructure Services – Digital
Cherry Bekaert LLP
(O) 804-794-3491 | (D) 804-673-5762 | (C) 804-690-7669  <= The best number to reach me during COVID-19 times

**Comment by peterabele** [comment]
Now finished with the  PR prerreqs, and sent the PR.

**Comment by RVAHaver01** [comment]
Peter,

Great, Thanks for the quick turnaround. We really appreciate it.

Regards,
David Haver
Manager, Infrastructure Services – Digital
Cherry Bekaert LLP
(O) 804-794-3491 | (D) 804-673-5762 | (C) 804-690-7669  <= The best number to reach me during COVID-19 times

**Comment by RVAHaver01** [comment]
Peter and Company,

I was just introduced to the Microsoft Compliance Configuration Analyzer (Microsoft Compliance Configuration Analyzer for Compliance Manager - Microsoft 365 Compliance | Microsoft Docs<https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-mcca?view=o365-worldwide>) tool yesterday.  It appears to me that this tool along with the Microsoft365DSC tool could work hand in hand.  Would you all consider reviewing this tool and adding additional items to the M365DSC tool to allow you to configure items found in the MCCA tool?  There may be overlap already there I have not checked but this seems to make sense to me.

Regards,
David Haver
Manager, Infrastructure Services – Digital
Cherry Bekaert LLP
(O) 804-794-3491 | (D) 804-673-5762 | (C) 804-690-7669  <= The best number to reach me during COVID-19 times

From: David Haver
Sent: Tuesday, January 19, 2021 8:51 AM
To: 'microsoft/Microsoft365DSC' <reply@reply.github.com>; microsoft/Microsoft365DSC <Microsoft365DSC@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [EXTERNAL] Re: [microsoft/Microsoft365DSC] NewResourceName: Named Locations (#1014)

Peter,

Great, Thanks for the quick turnaround. We really appreciate it.

Regards,
David Haver
Manager, Infrastructure Services – Digital
Cherry Bekaert LLP
(O) 804-794-3491 | (D) 804-673-5762 | (C) 804-690-7669  <= The best number to reach me during COVID-19 times
