### ISSUE TITLE
[MSFT_EXOAntiPhishPolicy] Deprecated parameters

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#1018]
#### Details of the scenario you tried and the problem that is occurring

Checking values of the parameters

- TargetedDomainProtectionAction
- EnableAntispoofEnforcement

returns $null in DSC (in MSFT_EXOAntiPhishPolicy). Requesting their values in PS returns nothing. Maybe these have been deprecated.

#### Verbose logs showing the problem
```
PS C:\Windows\system32> Get-AntiPhishPolicy -Spoof | Format-Table EnableAntiSpoofEnforcement

EnableAntiSpoofEnforcement
--------------------------
```
which should work according to https://docs.microsoft.com/en-us/powershell/module/exchange/get-antiphishpolicy?view=exchange-ps .

#### Suggested solution to the issue
Update https://github.com/microsoft/Microsoft365DSC/wiki/EXOAntiPhishPolicy (remove the two properties).
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell

**Comment by SebastianGoers** [comment]
@NikCharlebois : We believe this is related to https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3713 It seems that more parameters are affected by this. We have noted changes at least for:

- EnableAntispoofEnforcement
- PhishThresholdLevel
- TargetedDomainProtectionAction
- TargetedUserProtectionAction

**Comment by NikCharlebois** [comment]
Based on the documentation for the New- cmdlet (https://docs.microsoft.com/en-us/powershell/module/exchange/new-antiphishpolicy?view=exchange-ps) the EnableAntispoofEnforcement parameter seem to have indeed been deprecated. The other 3 however are still available in the cmdlet (New-AntiphishPolicy -?)

 I will try to track down more information on this deprecation as we were not made aware, and will push a PR to address this in parallel. Thanks

**Comment by NikCharlebois** [comment]
UPDATE: It appears that you are right. Even though the cmdlet's help specifies PhishThresholdLevel, TargetedDomainProtectionAction and TargetedUserProtectionAction that these are not officially supported by the cmdlet. We will be marking them as deprecated in the next release and will remove them from the splatted parameters when calling the New/Set
