### ISSUE TITLE
Error running initial export command

### ISSUE THREAD

**Issue by pvinn** [microsoft/Microsoft365DSC#1031]
#### Details of the scenario you tried and the problem that is occurring
 'Export-M365DSCConfiguration: Export command fails with error '
Installed new Powershell 7.1.1 
Ran Install-Module Microsoft365DSC -Force -AllowClobber
Ran Install-M365DSCDevBranch

Receiving error below ..
PowerShell 7.1.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Program Files\PowerShell\7> Export-M365DSCConfiguration
WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.Administration.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Add-M365DSCTelemetryEvent: C:\Users\adm-pnaccarato\Documents\PowerShell\Modules\Microsoft365DSC\1.21.120.1\modules\M365DSCUtil.psm1:849
Line |
 849 |      Add-M365DSCTelemetryEvent -Data $data
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

#### Verbose logs showing the problem

N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.

#### Version of the DSC module that was used ('dev' if using current dev branch)
Microsoft365DSC 1.0.4.39

**Comment by pvinn** [comment]
Microsoft365DSC
1.21.120.1

**Comment by rvahaver** [comment]
Team,
I determined last night that if you deselect SharePoint and OneDrive then the script runs to completion.  So it must have something to do with the pnp.powershell install.

**Comment by desmay** [comment]
Please review this article on how grant permissions with new PNP Core https://dev.to/svarukala/introducing-the-new-pnp-powershell-based-on-net-core-3-1-and-learn-how-it-s-authentication-works-pn7

**Comment by pvinn** [comment]
Thanks for the feedback, just to clarify a bit more, I get this error right after running Export-M365DSCConfiguration, and before the GUI shows up

**Comment by rvahaver** [comment]
No it was happening after the GUI and when it got to "Extracting [ODSettings]".  I granted the permissions that @desmay suggested above and now when I get to "Extracting [ODSettings]" it is just sitting there.  I did download the latest version of the Microsoft365DSC today also after granting the permissions.

**Comment by ararag** [comment]
I seem to be having somewhat similar problems. Whenever trying to extract OneDrive or SharePoint settings it just hangs indefinitely at "[1/1] Extracting [ODSettings]..." or "[1/22] Extracting [SPOAccessControlSettings]...".
I just discovered M365DSC, so I let it run overnight (not knowing how long it should take), but still no progress. After that I tried both user based authentication and aad app, but same behavior with both.

**Comment by NikCharlebois** [comment]
We believe this is related to the way the new PnP.Powershell module interacts with parallel threads. We are working on a fix for this. In the meantime, doing an unattended export (use the -Quiet) switch will work.

**Comment by rvahaver** [comment]
Nik,

Great thank you for letting me know.

Regards,
David Haver
Manager, Infrastructure Services – Digital
Cherry Bekaert LLP
(O) 804-794-3491 | (D) 804-673-5762 | (C) 804-690-7669  <= The best number to reach me during COVID-19 times

**Comment by pvinn** [comment]
Did not know that, thanks for the workaround ~!

**Comment by ararag** [comment]
Yes, it works with the quiet switch! Thank you!
