### ISSUE TITLE
Suggestion: Include Resource GUID in Eventlog

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#1032]
We are using the Windows Eventlog entries to track down configuration drifts on our M365 tenants. Some resources allow multiple settings or policies in the DSC config, e.g. Conditional Access policies. In order for us to track down which policy causes a drift, it would be beneficial if we could have the GUID that’s being used for each configuration block in the eventlog. This would allow us to track down the issues in our configuration at no time.

**Comment by NikCharlebois** [comment]
While we can see how useful this would be for users, it is not an easy task to be able to obtain the information about the current DSC context from within a resource being executed. Also, with PowerShell 7 the process of executing a DSC resource may be different and therefore even if we were to be able to gather this info within the PoSh 5 flavor, it would have to be changed whenever we make a move to version 7.0. I will leave the issue open for a few days to see if anyone else has input on this, but at this point, I would leave this as a good to have with Version 7.0+
