### ISSUE TITLE
Execute Command seems to hang right after PNP.PowerShell 1.2 warning message

### ISSUE THREAD

**Issue by rvahaver** [microsoft/Microsoft365DSC#1033]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by desmay** [comment]
@rvahaver  Did you grant permissions to PNP Core in your tenant ? - Please review this article on how grant permissions with new PNP Core https://dev.to/svarukala/introducing-the-new-pnp-powershell-based-on-net-core-3-1-and-learn-how-it-s-authentication-works-pn7

**Comment by jeff29922** [comment]
Great info guys, this is helpful for a tenant extraction I am doing for a customer.
