### ISSUE TITLE
[AADConditionalAccessPolicy] Incorrect error handling.

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#1054]
#### Details of the scenario you tried and the problem that is occurring
I have tested the module with an incomplete configuration (missing or empty includeUsers parameter). The logs show that the creation of the conditional access policy failes, but the error is not being reportet back to Start-DscConfiguration. This makes propper error handling rather difficult. I am using a try-catch for Start-DscConfiguration to see whether applying a config has been successful.
#### Verbose logs showing the problem
```
Code: BadRequest
Message: The server could not process the request because it is malformed or incorrect.
InnerError:
Message: 1010: At least one include rule in 'users' condition is required. Try 'includeUsers' = ['none'] to start with. For examples, please see API documentation at https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta.
RequestId: d697d9ca-c05a-  ... 
DateTimeStamp: Thu, 11 Feb 2021 09:44:47 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
```
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by Swampen** [comment]
The `Start-DscConfiguration` cmdlet actually starts a new job to push the configuration, so the errors are not actually in your current PowerShell session.
I have worked around this by checking the `$error.Count` variable before and after pushing the configuration
> Example
```powershell
$OldErrorCount = $error.Count
Start-DscConfiguration .\M365TenantConfig\ -Wait -Force -Verbose
if ($error.Count -gt $OldErrorCount )
{
    throw "Configuration did not succeed"
}
```
