### ISSUE TITLE
Errors not terminating?

### ISSUE THREAD

**Issue by tiwood** [microsoft/Microsoft365DSC#1056]
I'm currently testing `Microsoft365DSC` and one of the first resources I've tried is `AADConditionalAccessPolicy`.
The `Start-DSCConfiguration` cmdlet completed successfully without errors but no CA policy was created. Running the command with `-Verbose` showed me the following errors:

![image](https://user-images.githubusercontent.com/6249819/107681622-92988100-6c9f-11eb-9db0-3f7874aa13e9.png)

So I'm wondering
- If the API return errors, why is Start-DSCConfiguration not throwing?
- Is there no validation on the input at all?

**Comment by tiwood** [comment]
Related: https://github.com/microsoft/Microsoft365DSC/issues/1054

**Comment by Swampen** [comment]
See my comment here for a workaround https://github.com/microsoft/Microsoft365DSC/issues/1054#issuecomment-832173326

**Comment by NikCharlebois** [comment]
Also related to #1057
