### ISSUE TITLE
microsoft365dsc.com has an invalid SSL certificate

### ISSUE THREAD

**Issue by KenBenjamin** [microsoft/Microsoft365DSC#1063]
The certificate is for *.azurewebsites.net, not microsoft365dsc.com so you get a browser warning. You should install a valid certificate so users aren't concerned about the site integrity.

**Comment by DeanGross** [comment]
I am seeing the same issue (👎

**Comment by KenBenjamin** [comment]
My associate had his malware app alert on it so it's more than an inconvenience.

**Comment by DeanGross** [comment]
I was telling my customer what a great resource this was and describing how I was going to use it to help them solve some of their multi-tenant management issues. Any idea how much longer it will take to get fixed?

**Comment by jeff29922** [comment]
@NikCharlebois let me know if you need help with this.

**Comment by ykuijs** [comment]
Just received a new certificate and applied it to the site. The issue is now resolved!
