### ISSUE TITLE
Export-M365DSCConfiguration: Display font scaling causes rendering issues

### ISSUE THREAD

**Issue by KenBenjamin** [microsoft/Microsoft365DSC#1069]
#### Details of the scenario you tried and the problem that is occurring
If you have font scaling set to other than 100%, fields overlap in the GUI.

#### Suggested solution to the issue
Only temporary workaround is to go to 100% font scaling and adjust your display resolution downward to improve readability.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2004
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.217.1

**Comment by ykuijs** [comment]
Unfortunately this is correct. The UI is created using PowerShell code, which means we cannot use any GUI editor. That makes developing a proper UI really difficult. Right now the only workaround is to switch back to 100% scaling.

We are looking at a ways to solve this issue.

**Comment by NikCharlebois** [comment]
@KenBenjamin we are starting the work on decoupling the GUI from the main M365DSC project. The plan is to have it converted into a WebApp and hosted on the official Microsoft365DSC.com. You can take part in the discussions at:
https://github.com/microsoft/Microsoft365DSC/discussions/1111

cc @sebastienlevert @andikrueger

**Comment by NikCharlebois** [comment]
We will be moving to a web based GUI over the next few months which will handle this issue.
