### ISSUE TITLE
New-M365DSCReportFromConfiguration: Export to each object type to a separate sheet in Excel

### ISSUE THREAD

**Issue by edmund-davis** [microsoft/Microsoft365DSC#1071]
### Description
It would be very helpful to be able to export each object type to a separate Excel sheet with each property as a column.

**Comment by NikCharlebois** [comment]
@edmund-davis just want to make sure we understand the ask. Is it to have resources grouped by workloads? For example, one tab for all the Exchange Online resources, one tabs for all the Intune workload, etc.?

**Comment by edmund-davis** [comment]
Hi Nik.  
Well, it's a bit fiddly to create separate Excel workbook tabs from PowerShell but an option to create separate tables / csv files per object type would be valuable, with columns for each attribute instead of separate rows.

**Comment by NikCharlebois** [comment]
We've decided not to implement this as a feature in the solution. However, if you take a look at the New-M365DSCReportFromConfiguration function it should be very straight forward for you to write such a function that would split the resources type by tabs.
