### ISSUE TITLE
When Export-M365DSCConfiguration via GUI and it always stuck on something.. 

### ISSUE THREAD

**Issue by limjianan-camelody** [microsoft/Microsoft365DSC#1074]
#### Details of the scenario you tried and the problem that is occurring
Weird issue.
I spined up a new server in Azure and try to run Export-M365DSCConfiguration using password options. 
When i hit start export, it always stuck at some where. and it is quite confusing what happen.

I managed to finish this by only picking one workload (like Exchange), but not Lite or Default. 

#### Verbose logs showing the problem
Not sure how to get this. 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```
![Screenshot 2021-02-24 202328](https://user-images.githubusercontent.com/71110375/108979547-e0b97580-76de-11eb-94cf-bc3d47c02c73.png)

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.21.217.1 Microsoft365DSC                     {Assert-M365DSCBlueprint, Assert-M365DSCTemplate, Compare-...

**Comment by ararag** [comment]
Did you try running it with the -quiet parameter? I seem to remember having the same problem a while back and the quiet parameter worked for me.

**Comment by limjianan-camelody** [comment]
Release 1.21.224.1 fix the issues. not sure what have changed.
