### ISSUE TITLE
New-M365DSCDeltaReport hangs indefinitely

### ISSUE THREAD

**Issue by ararag** [microsoft/Microsoft365DSC#1075]
#### Details of the scenario you tried and the problem that is occurring
Running the following command will never complete:

New-M365DSCDeltaReport -Source "C:\M365DSC\source.ps1" -Destination "C:\M365DSC\Destination.ps1" -OutputPath "C:\M365DSC\Delta.html" -Verbose
VERBOSE: Obtaining Delta between the source and destination configurations

But nothing else happens.

#### Verbose logs showing the problem
Not sure how to get these?
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Seems to apply to any configuration I try

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.217.1

**Comment by desmay** [comment]
Take a look at the Microsoft 365 module version number of between source and destination and make sure they are identical. I had report hang when not the same.

**Comment by mikespolk** [comment]
Is there any progress on this issue? 
I am facing same problem, the New-M365DSCDeltaReport seems to hang indefinitely, with CPU varying between 20% and 25% and memory consumption varying around 400 MB. Both of the source and destination PS1 files are having similar M365 module version number 1.21.317.1 and they have been collected with the following command:

**Export-M365DSCConfiguration `
    -Quiet `
    -Workloads @("AAD","OD","PP","SPO") `
    -CertificateThumbprint xxxxxxxxxxxxxxxxxxxxxxxxxx `
    -ApplicationId $strApplicationID `
    -TenantId $strTenantName `
    -Path $strFile1Folder `
    -FileName $strFile1Name**

and both having about 420 kilobytes in size.

When trying to generate delta report with command

**New-M365DSCDeltaReport -Source $strListfile1 `
    -WarningAction SilentlyContinue `
    -Destination $strListfile2 `
    -OutputPath ($strResultFolder + "`\" +  $strDeltaResultFilename)**

only this text appears on PowerShell console

_WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.Administration.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb._

and command seems to hang, as described above. 

Windows info is here:
_OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2004
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}_

Hope someone could find correction to this.

**Comment by Kikaider** [comment]
It's not just that the _text_ of the M365DSC version must match between the source and destination configurations, but each config file must be compliable, which means you must have the corresponding version on the M365DSC module _installed_ on the machine running the cmdlet.
