### ISSUE TITLE
Command was found in module 'Microsoft365DSC' but the module could not be loaded

### ISSUE THREAD

**Issue by shammyowens** [microsoft/Microsoft365DSC#1081]
#### Details of the scenario you tried and the problem that is occurring

I have a DevOps VM agent and build/release pipeline configured as per this instruction guide.  https://microsoft365dsc.com/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf

Everything was working fine, but when I tried to amend/change the configurationdata.ps1 file more 365 settings, I get an error on the build pipeline which states for various Microsoft365DSC commands "The XXXXX command was found in module 'Microsoft365DSC', but the module could be loaded.  

#### Verbose logs showing the problem

2021-02-26T08:47:10.5714940Z VERBOSE: [DevOpsAgent01]: LCM:  [ Start  Resource ]  [[TeamsCallingPolicy]c765dd14-a0c1-489e-aff2-e4c4567cb418]
2021-02-26T08:47:10.5735786Z VERBOSE: [DevOpsAgent01]: LCM:  [ Start  Test     ]  [[TeamsCallingPolicy]c765dd14-a0c1-489e-aff2-e4c4567cb418]
**2021-02-26T08:47:10.8905561Z ##[error]The 'Add-M365DSCTelemetryEvent' command was found in the module 'Microsoft365DSC', but the module could not be loaded. 
For more information, run 'Import-Module Microsoft365DSC'.
    + CategoryInfo          : ObjectNotFound: (Add-M365DSCTelemetryEvent:) [], CimException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
    + PSComputerName        : localhost**

[log.txt](https://github.com/microsoft/Microsoft365DSC/files/6048610/log.txt)

#### Suggested solution to the issue

I had this once and I reverted all my config and then it appeared to work again.  I have reverted my config once again but the problem still persists.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

[PS.txt](https://github.com/microsoft/Microsoft365DSC/files/6048607/PS.txt)

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.224.1

**Comment by ykuijs** [comment]
Hi @shammyowens What happens if you log onto the machine and run ```Import-Module Microsoft365Dsc``` manually?

**Comment by shammyowens** [comment]
Hi @ykuijs that would work fine and I could use things like  Export-M365DSCConfiguration directly on the agent.

I have done some more testing I noticed that duplicates modules were installed some in my "Documents" folder and some in "Program Files".  After removing all of from both locations, it appears to work again now.  I will keep an eye on it to see if it occurs again.

**Comment by ykuijs** [comment]
Good to hear. This usually is the case of this error message. PowerShell should tell you this when you run Import-Module manually 😉 

Closing the issue now.

**Comment by cfizz34** [comment]
I had to enable remote signed in my PS policy
