### ISSUE TITLE
Connecting to tenant as a guest admin

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#1093]
If we are invited as a guest to a clients tenant and they have added us to the global admin role, how can connect and run this tool?

**Comment by jeff29922** [comment]
@DeanGross this is an untested scenario.  I will follow up with the core team to see if this is supported.

**Comment by jeff29922** [comment]
@NikCharlebois please provide feedback on wither this scenario is supported?

**Comment by NikCharlebois** [comment]
You would need to use Service Principal to do so. By default, the tool uses the credential's domain. In you case, the user would be coming from an external domain and the tool would not be able to properly authenticate against all workload. Using a service principal would solve this issue for workloads that support it.
