### ISSUE TITLE
Extracting the Security and compliance configration - without Global admin user ID. 

### ISSUE THREAD

**Issue by rajukiranlr** [microsoft/Microsoft365DSC#1099]
Hi Team, 

i am trying to extract the security and compliance configuration using the below command, but it is asking for Global admin user ID and password, I am providing the App Registration ID and Certificate details. 

Export-M365DSCConfiguration -Quiet -ApplicationId 11ef1234-dddd-4edf-3456-a10b0111f337 -CertificateThumbprint 00F22C541F698137A8880808E078C11B55BD60AC -TenantId teant.onmicrosoft.com -**ComponentsToExtract @("SCCaseHoldPolicy")**

or **-Workloads @("SC")** 

Application ID had Global Administrator Role, 

could you please confirm is that anything wrong in the way i am trying or any limitation in the tool. 

Thanks
Raju R

**Comment by desmay** [comment]
@rajukiranlr  Security & Compliance resources only support user id and password.

**Comment by rajukiranlr** [comment]
Thanks for the quick reply, is there anything in the Roadmap to include it ?

**Comment by rajukiranlr** [comment]
can we get the list, which all Components requires Global Admin to extract the data ?

**Comment by desmay** [comment]
@rajukiranlr As soon as SCC underlying PowerShell cmdlets support service principals we'll add support to M365DSC. Here is breakdown of workloads and authentication

![image](https://user-images.githubusercontent.com/43035577/111308547-32478700-8631-11eb-97bf-279461033daa.png)

**Comment by rajukiranlr** [comment]
Thanks for the info, 

i was getting the below error not sure what level of permission should my App Registration ID should be having to extract the Exchange online configuration, could you please guide me. 

PS C:\Users\rajukiranlr> Export-M365DSCConfiguration -Quiet -TenantId tenant.onmicrosoft.com -ApplicationId 83ef5
058-aaaa-4edf-1111-a10b0878f607 -CertificateThumbprint 74F22C541F698137A111111E078C00B55BD60AC -ComponentsToExtract @("EXOAntiPhishPolicy")
[1/1] Extracting [EXOAntiPhishPolicy]...New-ExoPSSession : Connecting to remote server outlook.office365.com failed with
 the following error message : Access
is denied. For more information, see the about_Remote_Troubleshooting Help topic.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.3\ExchangeOnlineManagement.psm1:426 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-ExoPSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Exchang
   e.Management.ExoPowershellSnapin.NewExoPSSession

i have create the App Registration ID in Azure Active directory, , my requirement is to only Extract the data so it should be minimal rights given to this application, 

could you please suggest.

**Comment by desmay** [comment]
Please review this article on docs site - https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps

**Comment by rajukiranlr** [comment]
Hi All, Any one please help, i am got stuck in the below issue, not able to continue . 

seeing error while running below command also, not sure what wrong i am doing. 


PS C:\Users\rajukiranlr\ConfigureLCM> Get-DscConfigurationStatus

```
Status     StartDate                 Type            Mode  RebootRequested      NumberOfResources
              
Failure    3/19/2021 1:55:19 PM      Consistency     Pull  False

```

**Comment by NikCharlebois** [comment]
@rajukiranlr You should be able to get additional information on the issue by looking at the event logs under the M365DSC journal on the machine where the DSC is being executed.

Also, from that machine, you could also manually trigger the configuration which would tell you what the error is:

Start-DSCConfiguration -UseExisting -Verbose -Wait -Force
