### ISSUE TITLE
Export-M365DSCConfiguration hanging during run

### ISSUE THREAD

**Issue by alisalih1** [microsoft/Microsoft365DSC#1101]
#### Details of the scenario you tried and the problem that is occurring
Export-M365DSCConfiguration configuration is hanging and not progressing while exporting simple OneDrive configuration. The authentication is done through App Registration and Certificate Auth as shown in the picture below. 
![image](https://user-images.githubusercontent.com/21177498/111339502-303ff100-864e-11eb-9df1-3df5fb09fa56.png)
![image](https://user-images.githubusercontent.com/21177498/111340493-10f59380-864f-11eb-825c-c2912681121f.png)

#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/21177498/111340684-3e424180-864f-11eb-92b7-d1fe919cdd9e.png)

#### Suggested solution to the issue
N/A
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A
#### The operating system the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.224.1

**Comment by desmay** [comment]
@alisalih1 There is an issue with GUI and it hangs with new version of PNP so you must use run using the command line. In you case it would be the following: 

`Export-M365DSCConfiguration -Quiet -ComponentsToExtract @('ODSettings') -ApplicationId XXXXXXX  -TenantId contoso.onmicrosoft.com -CertificateThumbprint XXXXXX -path "c\DSC"`

We are looking into solutions with the GUI hanging bug.

**Comment by jeff29922** [comment]
We recommend running a tenant extraction with the -Quiet switch for the time being.  The core team is investigating a long term solution for the GUI hang.  We will keep everyone informed on progress.

**Comment by alisalih1** [comment]
Understoood -  I did convert everything to -quiet and was performing as should. thanks.

**Comment by ykuijs** [comment]
Check out this article in the Wiki for more info: https://github.com/microsoft/Microsoft365DSC/wiki/Known-Issues#export-m365dscconfiguration-hangs-when-using-gui-to-export-sharepoint-online-and-onedrive-resources
