### ISSUE TITLE
Unable to run with MFA account - get prompted a few times and manage to authenticate but the error below appears

### ISSUE THREAD

**Issue by j16uk** [microsoft/Microsoft365DSC#1102]
Unable to finish this - I have run the  below:

$creds = Get-Credential
Export-M365DSCConfiguration -Quiet -Path C:\TEMP -FileName test1.ps1 -GlobalAdminAccount $creds

[102/120] Extracting [TeamsCallingPolicy]...Connect-MSCloudLoginSkypeForBusiness : One or more errors occurred.: AADSTS50076: Due to a configuration change made
by your administrator, or because you moved to a new location, you must use multi-factor authentication to access
'00000002-0000-0000-c000-000000000000'.
Trace ID: d84d9b33-3356-4668-a7f9-
Correlation ID: 73bea523-e7ac-418e-abcf-
Timestamp: 2021-03-16 20:11:44Z
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.48\MSCloudLoginAssistant.psm1:177 char:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness

New-CsOnlineSession : One or more errors occurred.: AADSTS50076: Due to a configuration change made by your
administrator, or because you moved to a new location, you must use multi-factor authentication to access
'00000002-0000-0000-c000-000000000000'.
Trace ID: d84d9b33-3356-4668-a7f9-
Correlation ID: 73bea523-e7ac-418e-abcf-
Timestamp: 2021-03-16 20:11:44Z
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.48\Workloads\SkypeForBusiness.psm1:29 char:36
+ ... ypeSession = New-CsOnlineSession -Credential $Global:o365Credential `
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [New-CsOnlineSession], CmdletInvocationException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession

**Comment by Swampen** [comment]
This is fixed in the newest release of MSCloudLoginAssistant. 
The version just have to be updated for this module. Probably for the next release

As a workaround you can login to with `Connect-MSCloudLoginSkypeForBusiness` and enter your credentials **before** starting the export

**Comment by Swampen** [comment]
I can confirm that this is fixed in the newest release (1.21.317.1)

**Comment by j16uk** [comment]
Apologies for the delayed response, I can confirm the workaround has worked, thank you.
@jeff29922
