### ISSUE TITLE
Azure App ID, Tenant ID and CertificateThumbprint ID not getting added to ps1 or Mof file

### ISSUE THREAD

**Issue by rajukiranlr** [microsoft/Microsoft365DSC#1114]
Hi Team, 
I am using the Azure App ID and Certificate Thumbprint for Authentication, using same i able to extract the EXO data to Ps1 file, 

ConfigurationData.psd1 ( shows my Azure App ID, Tenant ID and certificate Thumbprint details. 

M365TenantConfig.ps1 show the configuration, without anything Azure App ID and tenant ID or certificate thumbprint details. )

after running M365Tenantconfig.ps1 file, MOF is getting genrated,   

**my question is do i need to manually add the Application ID, Tenant ID and Thumbprint details in the M365TenantConfig.ps1?**

**Comment by desmay** [comment]
The compiled MOF file should have everything you need. If you need to push config to another tenant then you can update the configutationdata.ps1 with new values and compile

**Comment by rajukiranlr** [comment]
@ Desmay, 

Thanks for the reply, 

my required is to monitor any configuration drift in EXO and check the event ID for changes. 

my setup 
Authentication = Azure Apps ID, Certificate Thumbprint and Tenant ID. 

able to extract the configuration, 
Export-M365DSCConfiguration -Quiet -TenantId tenant.onmicrosoft.com -ApplicationId 11ef5058-cdfb-4edf-1111-a10b1111f607 -CertificateThumbprint 74F11C542F698137A1120808E078C11B11BD60AC -ComponentsToExtract @("EXOAntiPhishPolicy") -Path C:\Users\rajukiranlr\EXOAntiphishpolicy

able to see 3 files, 
ConfigurationData.psd1
M365DSC.cer
M365TenantConfig.ps1

**My question is after getting the configuration to file, what will be next steps so that i can only monitor for anychanges and see the event created in EventID.** 

pls help to fix this

**Comment by desmay** [comment]
We have several videos on our [YouTube](https://www.youtube.com/channel/UCveScabVT6pxzqYgGRu17iw) channel that can help you.  You could also use Azure DevOps pipeline we published a [white paper](https://microsoft365dsc.com/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf) on this solution.
