### ISSUE TITLE
TeamsChannel Throw error if Channel used to exist

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#112]
#### Details of the scenario you tried and the problem that is occurring
1 - Create a new TeamsChannel using O365DSC;

2 - Manually delete that channel from the Web interface;

3 - Re-run the DSC in an attempt to recreate the teams. You will get error: 
Error occurred while executing
Code: NameAlreadyExists
Message: Channel name already existed, please use other nameFailed to execute Skype backend request
CreateThreadRequest.
InnerError:
  RequestId: 477ee23b-6da7-43d0-8708-d98a5ca32bb3
  DateTimeStamp: 2019-05-23T16:21:18
HttpStatusCode: NameAlreadyExists
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdle
   ts.PowerShell.Custom.NewTeamChannel
    + PSComputerName        : localhost

#### Verbose logs showing the problem
Error occurred while executing
Code: NameAlreadyExists
Message: Channel name already existed, please use other nameFailed to execute Skype backend request
CreateThreadRequest.
InnerError:
  RequestId: 477ee23b-6da7-43d0-8708-d98a5ca32bb3
  DateTimeStamp: 2019-05-23T16:21:18
HttpStatusCode: NameAlreadyExists
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.TeamsCmdlets.PowerShell.Custom.ErrorHandling.ApiException,Microsoft.TeamsCmdle
   ts.PowerShell.Custom.NewTeamChannel
    + PSComputerName        : localhost

#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
TeamsTeam WeeklyMeetings
        {
            DisplayName             = "WeeklyMeetings"
            AllowGiphy              = $true
            AllowUserDeleteMessages = $true
            GlobalAdminAccount      = $Creds
            Ensure                  = "Present"
        }

        TeamsChannel Reviews
        {
            TeamName           = "WeeklyMeetings"
            DisplayName        = "Team Reviews"
            GlobalAdminAccount = $Creds
            DependsOn          = "[TeamsTeam]WeeklyMeetings"
            Ensure             = "Present"
        }

        TeamsChannel LT
        {
            TeamName           = "WeeklyMeetings"
            DisplayName        = "Leadership Team"
            GlobalAdminAccount = $Creds
            DependsOn          = "[TeamsTeam]WeeklyMeetings"
            Ensure             = "Present"
        }

**Comment by desmay** [comment]
Will take a look. Deleting a channel is a soft delete need to see how to handle this better. https://docs.microsoft.com/en-us/powershell/module/teams/remove-teamchannel?view=teams-ps

**Comment by NikCharlebois** [comment]
@desmay any updates on this? Looks like this is the same behavior via the GUI if you delete a channel and try to recreate it. I believe the waiting period is 30 days before the initial channel gets cleared. Maybe we should look at having the resource restore the deleted channel if it already exists in the "Deleted Channel" bin? We are currently doing something similar for SPODeletedSite inside the SPOSite resource.

**Comment by desmay** [comment]
@NikCharlebois I took a peek this morning and I don't see anything from Teams cmdlets to restore deleted channel and nothing via Graph. We may need to reach out to see if there is anything in works to do this via Teams cmdlets

**Comment by NikCharlebois** [comment]
@jeff29922 and Team, are you aware of any ways to restore a deleted Teams Channel from the API?

**Comment by NikCharlebois** [comment]
CC @ndambrosio in case you know what the answer to this would be.

**Comment by andikrueger** [comment]
Is there any update on this issue available?

**Comment by NikCharlebois** [comment]
There really aren't much option here. At least now the execution doesn't fail when the team is in the deleted queue, allowing users to restore it from the Teams console.
