### ISSUE TITLE
SCSensitiveInformationType

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#1124]
### Description
If a Data Loss Prevention Policy uses a custom sensitive information type (SIT) in an existing tenant, it is not possible to create the DLP policy in a new tenant until the custom SIT exists. In order to have a complete solution we need to be able to extract and recreate custom SITs.

### Proposed properties
Name, description, matching requirements (content contains values, confidence level, character proximity)

### Special considerations or limitations
this should be helpful https://docs.microsoft.com/en-us/powershell/module/exchange/new-dlpsensitiveinformationtype?view=exchange-ps

**Comment by NikCharlebois** [comment]
@desmay would this also be addressed by the PR you submitted earlier?

**Comment by desmay** [comment]
@NikCharlebois Unfortunately not it only handles the built in SIT from MSFT. We would need to develop new resource to handle custom SIT
