### ISSUE TITLE
Running configuration in pipeline with verbose output succeeds even if it fails

### ISSUE THREAD

**Issue by jensotto** [microsoft/Microsoft365DSC#1127]
#### Details of the scenario you tried and the problem that is occurring
I have a configuration that fails to remove an existing theme. I try to turn on verbose output by adding the -Verbose flag to the Start-DSCConfiguration command. When executing the release pipeline the deployment completes without reporting any error in the PowerShell task that executes the configuration. Examining the verbose log in the task reveales that the configuration still fails with the exact same problem.

Basically this is the scenario.

Execurtion of the configuration **without** -Verbose results in failure reported in the pipeline.

Execurtion of the configuration **with** -Verbose results in no failure reported in the pipeline, but the resource stil reports failure in the log.

It seems that using -Verbose hides any reported errors in the pipeline.

#### Verbose logs showing the problem
2021-03-26T19:05:40.8367998Z The SPOTheme  does not exist and for that cannot be removed.
2021-03-26T19:05:40.8369019Z     + CategoryInfo          : NotSpecified: (:) [], CimException
2021-03-26T19:05:40.8370815Z     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-TargetResource
2021-03-26T19:05:40.8371690Z     + PSComputerName        : localhost

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
            SPOTheme "Theme-1"
            {
                Ensure                = 'Absent';
                Name                  = 'Name of the theme';
                ApplicationId         = $ApplicationId;
                TenantId              = $TenantId;
                CertificateThumbprint = $CertificateThumbprint;
            }

```

#### The operating system the target node is running
Azure DevOps Hosted Agent
vs2017-win2016

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.317.1

**Comment by Swampen** [comment]
I think this is more related to the `Start-DSCConfiguration` cmdlet.
Seems like it actually do not throw on completion with errors.
https://stackoverflow.com/questions/27201314/start-dscconfiguration-doesnt-throw-exceptions/27202470

As a workaround you can check the count in the `$error` variable
> example code:
```powershell
Start-DscConfiguration .\M365TenantConfig\ -Wait -Force -Verbose
if ($error.Count -gt 0)
{
    throw "Configuration did not succeed"
}

**Comment by NikCharlebois** [comment]
@jensotto are you still facing this issue? Thanks
