### ISSUE TITLE
Setting Teams Meeting Policy settings when AllowCloudRecording is False returns error

### ISSUE THREAD

**Issue by acauret** [microsoft/Microsoft365DSC#1134]
ISSUE TITLE:
Setting Teams Meeting Policy settings when AllowCloudRecording is False returns error

ISSUE DESCRIPTION (this template):
Changing any settings when AllowCloudRecording  is set to False (including setting AllowCloudRecording to False) returns error below:

##[error]Updating the recording storage is not allowed when AllowCloudRecording is set to false.
    + CategoryInfo          : OperationStopped: (:) [], CimException
    + FullyQualifiedErrorId : AggregateException,Microsoft.Rtc.Management.Internal.SetTeamsMeetingPolicyCmdlet
    + PSComputerName        : localhost

#### The operating system the target node is running
Windows Server 2019

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.331.1

**Comment by Swampen** [comment]
Does the configuration works if you remove the `RecordingStorageMode` and `AllowRecordingStorageOutsideRegion` from your configuration?

**Comment by acauret** [comment]
Yes - Thanks. that worked! Although I am not sure on the Logic being applied by the cmdlet as my client has the combination AllowIPVideo: True and AllowIPAudio: False in their tenant. When doing further testing in mine tenant, trying to set that config using the DSC config .. I get : "Invalid value combination AllowIPVideo: True and AllowIPAudio: False. When AllowIPAudio is set to False, AllowIPVideo must not be True"

**Comment by Swampen** [comment]
I will make a pull request later to fix it, so in the next release you don't have to remove those parameters from the configuration.
