### ISSUE TITLE
TeamsTeam: Wrong Owner reference when using ServicePrincipal

### ISSUE THREAD

**Issue by Tiemooowh** [microsoft/Microsoft365DSC#1143]
Hi,

When applying a Teams Team with Service Principal following logic is executed on line 417.
`([array]$Owner[0]).ToString()`

This will always result in: "System.Object[]"

Correct syntax would be:
`[array](($Owner[0]).ToString())`

Ref:
https://github.com/microsoft/Microsoft365DSC/blob/5e26b7779a06077e8dbb63189f917cd65785beb1/Modules/Microsoft3
65DSC/DSCResources/MSFT_TeamsTeam/MSFT_TeamsTeam.psm1#L417

**Comment by NikCharlebois** [comment]
Thanks for spotting this @Tiemooowh. Want to submit a PR to correct this? 😃

**Comment by desmay** [comment]
@Tiemooowh Thanks for reporting, I just submitted a PR for fix

**Comment by desmay** [comment]
Should be resolved with PR above
