### ISSUE TITLE
Microsoft365DSC: Import-Module : The required module 'Microsoft.Graph.Authentication' with version '1.4.2' is not loaded.

### ISSUE THREAD

**Issue by EricHindrichsen** [microsoft/Microsoft365DSC#1152]
#### Details of the scenario you tried and the problem that is occurring
We are running Microsoft365 in an Azure DevOps release pipeline. Just a few minutes ago we started our Start-DscConfiguration process, which installs the latest M365DSC version on a clean machine using "Install-Module" and then "Import-Module". This works fine with M365DSC version 1.21.407.1, but it fails with version 1.21.414.1.
#### Verbose logs showing the problem
Import-Module : The required module 'Microsoft.Graph.Authentication' with version '1.4.2' is not loaded. Load the 
module or remove the module from 'RequiredModules' in the file 'C:\Program 
Files\WindowsPowerShell\Modules\Microsoft.Graph.Planner\1.4.2\Microsoft.Graph.Planner.psd1'.
#### Suggested solution to the issue
Is a dependency for M365DSC missing or outdated in the module definition?
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
We don't get to the point where config would be applied.

#### The operating system the target node is running

Azure DevOps release agent
#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.414.1

**Comment by NikCharlebois** [comment]
@EricHindrichsen thanks for flagging this. A new emergency release (v1.21.414.2) was just published which will fix this. Version 1.4.2 had somehow already been deployed onto the build box, which prevented our tests from catching the issue during the testing cycle. Apologies for any inconvenient.

**Comment by EricHindrichsen** [comment]
Thanks for the quick fix @NikCharlebois!
