### ISSUE TITLE
test-DSCConfiguration reports config change when there is none

### ISSUE THREAD

**Issue by ararag** [microsoft/Microsoft365DSC#1165]
Hi,
When running test-DSCConfiguration against a recently made reference config it always returns a difference in EXOHostedContentFilterPolicy and EXOOutboundConnector even though there has been no changes.
The event logs show these kind of config drifts:
`<ParametersNotInDesiredState>
            <Param Name="BlockedSenders"><CurrentValue>user1@domain.com user2@domain.com</CurrentValue><DesiredValue>user1@domain.com user2@domain.com</DesiredValue></Param>
            <Param Name="AllowedSenders"><CurrentValue>user3@domain.com user4@domain.com user5@domain.com</CurrentValue><DesiredValue>user3@domain.com user4@domain.com user5@domain.com</DesiredValue></Param>
        </ParametersNotInDesiredState>
    </ConfigurationDrift>`

I can't see any difference between the current value and desired value. Please advice.

**Comment by EricHindrichsen** [comment]
@NikCharlebois I still see this issue in EXOHostedContentFilterPolicy for BlockedSender, AllowedSenderDomain, AllowedSenders and BlockedSenderDomains if they are set to `$null` or `@()` in the DSC config and are currently not configured in the tenant (reported back as `$null` when getting current values). From my understanding there should be no config drift reported then.

I've tested this with Release 1.21.707.1. Version 1.21.630.1 worked fine in this regard.
