### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#1166]
When I do a get-module -listavailable I see that I have 1.21.331.1 but this version is not listed on the change log. Can someone help me understand how versioning is managed for this project?

**Comment by DeanGross** [comment]
When I do a get-module -listavailable I see that I have 1.21.331.1 but this version is not listed on the change log. Can someone help me understand how versioning is managed for this project?

**Comment by EricHindrichsen** [comment]
Hi,

this version is listed in the change log right beneath version 1.21.407.1. It's just not formatted as a header and thus easily missed. @NikCharlebois maybe you want to fix this formatting error to prevent confusion?
