### ISSUE TITLE
Powershell V7

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#1179]
Is this supposed to work with Powershell V7?

**Comment by RuudGijsbers** [comment]
No, version 7 is not supported yet. The powershell modules used in the background still have requirements that version 7 cannot meet.

**Comment by DeanGross** [comment]
Ok, thanks for the confirmation. I was getting some weird error messages and was wondering if this could have been the cause. 
Is it possible to run these commands on a computer that has V7, if so, how?

**Comment by fsch** [comment]
On Win10 this shouldnt be a problem, just open "Windows PowerShell." that should still give you V5. 
https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-70?view=powershell-7.1 states:
"PowerShell 7 installs to a directory seperately from Windows PowerShell. This enables you to run PowerShell 7 side-by-side with Windows PowerShell 5.1. For PowerShell Core 6.x, PowerShell 7 is an in-place upgrade that removes PowerShell Core 6.x."

**Comment by haneef95** [comment]
Is this still the case?

Do we know which modules won't work on PS Core 7?

P.S.: Looking to Containerise this.

Thanks,

**Comment by scamaramsft** [comment]
@haneef95 at least Microsoft.PowerApps.Administration.PowerShell requires Powershell 5.1 (https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
![image](https://user-images.githubusercontent.com/94856850/143210803-52e0af97-e287-4e44-84db-99267c7f7a51.png)

**Comment by haneef95** [comment]
Would be good to have a table of official Microsoft modules with their versions and the required/tested PS Version.
