### ISSUE TITLE
EXOSafeLinksPolicy/EXOSafeLinksRule won't get applied to target tenant

### ISSUE THREAD

**Issue by kenczo** [microsoft/Microsoft365DSC#1183]
ISSUE TITLE: EXOSafeLinksPolicy/EXOSafeLinksRule won't get applied to target tenant
    Please prefix the issue title with the resource name, e.g.
    'EXOSafeLinksPolicy/EXOSafeLinksRule: 

    

    PLEASE KEEP THE HEADERS.

-->
#### Details of the scenario you tried and the problem that is occurring
Extracted Safe-Links rule/Safe-links policy from source tenant and trying to apply it to a target tenant in 365. I get the following errors. In addition to errors, the Safe-Links policy does not get applied to target tenant

#### Verbose logs showing the problem

The PowerShell DSC resource '[EXOSafeLinksPolicy]d2e1733b-fc82-4433-a5bd-f2942f146a20' with SourceInfo                  'C:\users\ken\Documents\DSC\OutPut Folder\BornOrangeExtractEXO.ps1::33::9::EXOSafeLinksPolicy' threw one or more        non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel   called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
-----------------------------------------------------------------------
Policy "ATP Safe Link" not found.
    + CategoryInfo          : ObjectNotFound: (ATP Safe Link:) [], CimException
    + FullyQualifiedErrorId : [Server=BYAPR11MB3095,RequestId=eaec5359-256f-48a8-bf88-ef387a66c978,TimeStamp=4/28/2021
    5:05:45 PM] [FailureCategory=Cmdlet-ManagementObjectNotFoundException] 8D8A39C0,Microsoft.Exchange.Management.Sys
  temConfigurationTasks.NewSafeLinksRule
    + PSComputerName        : localhost
----------------------------------------------------------------------

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# 
$creds = Get-Credential 

Export-M365DSCConfiguration -Quiet -ComponentsToExtract @( "EXOSafeLinksPolicy", "EXOSafeLinksRule" ) -GlobalAdminAccount $creds -Path "C:\Users\ken\Documents\DSC\OutPut Folder" -fileName "BornOrangeExtractEXO.ps1"** 
---------------------------------------

Start-DscConfiguration BornOrangeExtractEXO -Wait –Verbose -force

#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

OsName               : Microsoft Windows 10 Enterprise Evaluation
OsOperatingSystemSKU : 72
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
-->

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.428.1 (current version)

**Comment by RuudGijsbers** [comment]
Does the target tenant have appropriate licenses for the SafeLinksRule? If I'm not mistaken I've seen this before in our test tenant
