### ISSUE TITLE
SPO & OD Exports not working 401 unauthorised when using Global Admin account

### ISSUE THREAD

**Issue by SharePointPete** [microsoft/Microsoft365DSC#1194]
Can someone please help me resolve an issue that I am now facing with all SPO & OD exports in that I just receive a message stating that the remote server returned an error 401 unauthorised.

[1/5] Extracting [SPOBrowserIdleSignout]...An error has occurred The remote server returned an error: (401) Unauthorized.
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.50\Workloads\PnP.psm1:203 char:13
+             throw $message
+             ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (An error has oc...) Unauthorized.:String) [], RuntimeException
    + FullyQualifiedErrorId : An error has occurred The remote server returned an error: (401) Unauthorized.

**Comment by SharePointPete** [comment]
These exports worked fine a week ago but, now they are not working.

**Comment by SharePointPete** [comment]
The App registration approach has resolved the issue for me. Interesting that Globaladmin account used to work but now does not though.

**Comment by SharePointPete** [comment]
How do I apply this config to a new tenant however, previously I was prompted for credentials when I created the mof file. Now I am not prompted for credentials (I guess because I have used the app registration approach) so I am wondering how to define the tenant I want to apply to?

When I run the Start-M365DSCConfiguration cmdlet I get an error stating

PowerShell DSC resource MSFT_SPOBrowserIdleSignout  failed to execute Test-TargetResource functionality with error message: An error has occurred Cannot find certificate with this thumbprint in the certificate store. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

**Comment by desmay** [comment]
@SharePointPete You would need to create new app registration in your target tenant then update the configdata.psd1 file with new values then recompile mof file. 

As for the issue with Global admin can you confirm that PNP Core has access to tenant.  - https://dev.to/svarukala/introducing-the-new-pnp-powershell-based-on-net-core-3-1-and-learn-how-it-s-authentication-works-pn7

**Comment by desmay** [comment]
@SharePointPete  Can we close this issue ? I believe it was an issue where certificate wasn't installed in local system.

**Comment by SharePointPete** [comment]
Yes we can guys, thank you

**Comment by desmay** [comment]
Items resolved following steps detailed in https://github.com/microsoft/Microsoft365DSC/wiki/ODSP-Permissions
