### ISSUE TITLE
Install and MFA

### ISSUE THREAD

**Issue by NGseb** [microsoft/Microsoft365DSC#1195]

**Comment by NGseb** [comment]
I installed the module and try to launch the export command but it blocked.
We use MFA (OKTA) and i could not see the option to log in with MFA.


PS C:\Windows\system32> Install-Module -Name Microsoft365DSC -Force -AllowClobber

PS C:\Windows\system32> Export-M365DSCConfiguration$PipelineStoppedException/   à System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   à System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   à System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   à System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   à System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   à System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   à System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesT
oDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   à System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   à System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   à System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, 
Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   à System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptTh
is, Object[] args)
   à System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(ScriptBlock sb, Boolean useNewScope, PipelineResultTypes writeToPipeline, IList input, Object[] args)
   à Microsoft.Graph.PowerShell.Runtime.PowerShell.PsHelpers.RunScript[T](CommandInvocationIntrinsics cii, String script)
   à Microsoft.Graph.PowerShell.Runtime.PowerShell.PsHelpers.GetScriptCmdlets(PSCmdlet cmdlet, String scriptFolder)
   à Microsoft.Graph.PowerShell.Runtime.PowerShell.GetScriptCmdlet.ProcessRecord()

AVERTISSEMENT : Les noms de certaines commandes importées du module « Microsoft.PowerApps.Administration.PowerShell » contiennent des verbes non approuvés qui peuvent les rendre moin
s détectables. Pour trouver les commandes comportant des verbes non approuvés, réexécutez la commande Import-Module avec le paramètre Verbose. Pour obtenir la liste des verbes approu
vés, tapez Get-Verb.
[INFO] You can perform an equivalent unattended Export operation by running the following command:
Export-M365DSCConfiguration -Quiet -ComponentsToExtract @('ODSettings','PPPowerAppsEnvironment','PlannerTask','SPOAccessControlSettings','SPOApp','SPOBrowserIdleSignout','SPOHomeSite
','SPOHubSite','SPOOrgAssetsLibrary','SPOSearchManagedProperty','SPOSearchResultSource','SPOSharingSettings','SPOSiteDesign','SPOSiteDesignRights','SPOSiteScript','SPOStorageEntity',
'SPOTenantCdnEnabled','SPOTenantCdnPolicy','SPOTenantSettings','SPOTheme') -GlobalAdminAccount (Get-Credential)
[1/20] Extracting [ODSettings]...

**Comment by RuudGijsbers** [comment]
That's expected behavior. MFA won't work in quiet mode. Can you try the interactive method, by just using Export-M365DSCConfiguration ?
