### ISSUE TITLE
Error while compiling and applying M365TenantConfig_Lite-without-EXOAcceptedDomain.ps1 on a demo tenant

### ISSUE THREAD

**Issue by Simon-Charest** [microsoft/Microsoft365DSC#1198]
Hi,

I was able to export the Lite version (without EXOAcceptedDomain, that keeps hanging, for some reason) of our "demo" and "prod" tenants, using the following command, generated by the UI:

Export-M365DSCConfiguration -Quiet -ComponentsToExtract @('O365AdminAuditLogConfig','O365OrgCustomizationSetting','EXOActiveSyncDeviceAccessRule','EXOAddressBookPolicy','EXOAddressList','EXOAntiPhishPolicy','EXOAntiPhishRule','EXOApplicationAccessPolicy','EXOAtpPolicyForO365','EXOAvailabilityAddressSpace','EXOAvailabilityConfig','EXOCASMailboxPlan','EXOClientAccessRule','EXODkimSigningConfig','EXOEmailAddressPolicy','EXOGlobalAddressList','EXOHostedConnectionFilterPolicy','EXOHostedContentFilterPolicy','EXOHostedContentFilterRule','EXOHostedOutboundSpamFilterPolicy','EXOInboundConnector','EXOIntraOrganizationConnector','EXOMailTips','EXOMalwareFilterPolicy','EXOMalwareFilterRule','EXOMobileDeviceMailboxPolicy','EXOOfflineAddressBook','EXOOnPremisesOrganization','EXOOrganizationConfig','EXOOrganizationRelationship','EXOOutboundConnector','EXOOwaMailboxPolicy','EXOPartnerApplication','EXOPolicyTipConfig','EXORemoteDomain','EXORoleAssignmentPolicy','EXOSafeAttachmentPolicy','EXOSafeAttachmentRule','EXOSafeLinksPolicy','EXOSafeLinksRule','EXOSharedMailbox','EXOSharingPolicy','EXOTransportRule','IntuneAppConfigurationPolicy','IntuneAppProtectionPolicyiOS','IntuneDeviceCategory','IntuneDeviceCompliancePolicyAndroid','IntuneDeviceCompliancePolicyAndroidWorkProfile','IntuneDeviceCompliancePolicyiOs','IntuneDeviceConfigurationPolicyiOS','IntuneDeviceEnrollmentLimitRestriction','IntuneDeviceEnrollmentPlatformRestriction','ODSettings','SPOAccessControlSettings','SPOBrowserIdleSignout','SPOHomeSite','SPOHubSite','SPOOrgAssetsLibrary','SPOSearchManagedProperty','SPOSearchResultSource','SPOSharingSettings','SPOSiteDesignRights','SPOSiteScript','SPOStorageEntity','SPOTenantCdnEnabled','SPOTenantCdnPolicy','SPOTenantSettings','SPOTheme','SCAuditConfigurationPolicy','SCCaseHoldPolicy','SCCaseHoldRule','SCComplianceCase','SCComplianceSearch','SCComplianceSearchAction','SCComplianceTag','SCDeviceConditionalAccessPolicy','SCDeviceConfigurationPolicy','SCDLPCompliancePolicy','SCDLPComplianceRule','SCFilePlanPropertyAuthority','SCFilePlanPropertyCategory','SCFilePlanPropertyCitation','SCFilePlanPropertyDepartment','SCFilePlanPropertyReferenceId','SCFilePlanPropertySubCategory','SCLabelPolicy','SCRetentionCompliancePolicy','SCRetentionComplianceRule','SCRetentionEventType','SCSensitivityLabel','SCSupervisoryReviewPolicy','SCSupervisoryReviewRule','TeamsCallingPolicy','TeamsChannelsPolicy','TeamsClientConfiguration','TeamsEmergencyCallingPolicy','TeamsEmergencyCallRoutingPolicy','TeamsGuestCallingConfiguration','TeamsGuestMeetingConfiguration','TeamsGuestMessagingConfiguration','TeamsMeetingBroadcastConfiguration','TeamsMeetingBroadcastPolicy','TeamsMeetingConfiguration','TeamsMeetingPolicy','TeamsMessagingPolicy','TeamsPstnUsage','TeamsTenantDialPlan','TeamsUpgradeConfiguration','TeamsUpgradePolicy','TeamsVoiceRoute','TeamsVoiceRoutingPolicy','AADApplication','AADConditionalAccessPolicy','AADGroupsNamingPolicy','AADGroupsSettings','AADMSGroupLifecyclePolicy','AADNamedLocationPolicy','AADPolicy','AADRoleDefinition','AADTenantDetails') -GlobalAdminAccount (Get-Credential)

Then, I tried compiling and reapplying these newly configs using the following commands:

cd C:\src\Microsoft365DSC\DEMO_TENANT\
.\M365TenantConfig_Lite-without-EXOAcceptedDomain.ps1

and

cd C:\src\Microsoft365DSC\PROD_TENANT\
.\M365TenantConfig_Lite-without-EXOAcceptedDomain.ps1

While the prod config worked perfectly, I got errors compiling the demo one on the two following configs / lines:

EXOTransportRule ca586b1b-91b4-44de-8c85-5109647e82f7
{
	IncidentReportContent				= @("Sender","Recipients","Subject","Cc","Bcc","Severity","Override","RuleDetections","FalsePositive","DataClassifications","IdMatch","AttachOriginalMail");
	MessageContainsDataClassifications	= @("{id:"Credit Card Number", guid:"50842eb7-edc8-4019-85dd-5a5c1f2bb085", displayName:"Credit Card Number", minCount:1, maxCount:Infinity, minConfidence:Recommended, maxConfidence:100}");
}

Error message:
Write-NodeMOFFile : Invalid MOF definition for node 'localhost': Exception calling "ValidateInstanceText" with "1"
argument(s): "Convert property 'IncidentReportContent' value from type 'STRING[]' to type 'STRING' failed

I commented both lines and then it worked perfectly.

Regards,

Simon

**Comment by stvnmbr1** [comment]
you are sending an array string, try comma separated values in a string. The string array type can get confusing sometimes
try "Sender,Recipients,Subject,..." instead of ["Sender","Recipients","Subject",..]

hope it helps!
