### ISSUE TITLE
DSC Export of Azure Tenant does not complete and always hangs in the middle

### ISSUE THREAD

**Issue by pkatanov** [microsoft/Microsoft365DSC#1199]
I have been trying to export my Tenants config but it always hangs in the middle of the steps.
Is there anything I can do to get MSDSC to export fully successfully?
[11/139] Extracting [AADTenantDetails]...✅
[12/139] Extracting [EXOAcceptedDomain]...  Hangs at this step almost all the time.

Thanks,
Peter

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by NikCharlebois** [comment]
Reference #1101

Please use the **-Quiet** switch when doing the export. The GUI based export is currently experiencing issues as described in the yellow warning message at the top of the GUI. Thanks

**Comment by NikCharlebois** [comment]
Let me know if it works for you

**Comment by pkatanov** [comment]
I have tried that and this is what I am getting.  Can you please give me the full command?
***@***.***D7471E.A705DFD0]

Thanks,

Peter Katanov
Sr. Systems Engineer
P 212-903-8447 | M 646-285-2867
E ***@***.******@***.***> | www.amanet.org<http://www.amanet.org/>
1601 Broadway | New York, NY | 10019, USA
[American Management Association]<https://www.amanet.org/>    [Facebook] <https://www.facebook.com/AmericanManagementAssn/>  [Twitter] <https://twitter.com/amanet>  [LinkedIn] <https://www.linkedin.com/groups/35475/>  [Instagram] <https://www.instagram.com/americanmanagementassociation/>  [YouTube] <https://www.youtube.com/user/AmericanManagement>  [Blog] <https://playbook.amanet.org/>

**Comment by mikepet1** [comment]
I have the same issue running -quiet doing an export.  It get towards the end and never finishes.  If I use the GUI and uncheck everything but AD that hangs on Extracting 0365Auditlogconfig.

**Comment by NikCharlebois** [comment]
Try the following command:

```
$creds = Get-Credential
Export-M365DSCConfiguration -Quiet -GlobalAdminAccount $creds
```

**Comment by pkatanov** [comment]
Tried that many times with same results.


Peter Katanov
Sr. Systems Engineer
P 212-903-8447 | M 646-285-2867
E ***@***.******@***.***> | www.amanet.org<http://www.amanet.org/>
1601 Broadway | New York, NY | 10019, USA
[American Management Association]<https://www.amanet.org/>    [Facebook] <https://www.facebook.com/AmericanManagementAssn/>  [Twitter] <https://twitter.com/amanet>  [LinkedIn] <https://www.linkedin.com/groups/35475/>  [Instagram] <https://www.instagram.com/americanmanagementassociation/>  [YouTube] <https://www.youtube.com/user/AmericanManagement>  [Blog] <https://playbook.amanet.org/>

**Comment by NikCharlebois** [comment]
What error are you getting when using it? Is it still complaining that you need to provide GlobalAdminAccount or ServicePrincipal?

**Comment by pkatanov** [comment]
It just hangs in the middle at different steps.

Any help would be greatly appreciated.

Thanks,
Peter

Peter Katanov
Sr. Systems Engineer
P 212-903-8447 | M 646-285-2867
E ***@***.******@***.***> | www.amanet.org<http://www.amanet.org/>
1601 Broadway | New York, NY | 10019, USA
[American Management Association]<https://www.amanet.org/>    [Facebook] <https://www.facebook.com/AmericanManagementAssn/>  [Twitter] <https://twitter.com/amanet>  [LinkedIn] <https://www.linkedin.com/groups/35475/>  [Instagram] <https://www.instagram.com/americanmanagementassociation/>  [YouTube] <https://www.youtube.com/user/AmericanManagement>  [Blog] <https://playbook.amanet.org/>

**Comment by NikCharlebois** [comment]
What resource does it hang on when running the command above?

**Comment by pkatanov** [comment]
I am running it again now, will send you a screenshot when it hangs again.

Thanks,
Peter

Peter Katanov
Sr. Systems Engineer
P 212-903-8447 | M 646-285-2867
E ***@***.******@***.***> | www.amanet.org<http://www.amanet.org/>
1601 Broadway | New York, NY | 10019, USA
[American Management Association]<https://www.amanet.org/>    [Facebook] <https://www.facebook.com/AmericanManagementAssn/>  [Twitter] <https://twitter.com/amanet>  [LinkedIn] <https://www.linkedin.com/groups/35475/>  [Instagram] <https://www.instagram.com/americanmanagementassociation/>  [YouTube] <https://www.youtube.com/user/AmericanManagement>  [Blog] <https://playbook.amanet.org/>

**Comment by pkatanov** [comment]
Got stuck in step below.
***@***.***D772B3.FB29C4D0]

Thanks,
Peter

Peter Katanov
Sr. Systems Engineer
P 212-903-8447 | M 646-285-2867
E ***@***.******@***.***> | www.amanet.org<http://www.amanet.org/>
1601 Broadway | New York, NY | 10019, USA
[American Management Association]<https://www.amanet.org/>    [Facebook] <https://www.facebook.com/AmericanManagementAssn/>  [Twitter] <https://twitter.com/amanet>  [LinkedIn] <https://www.linkedin.com/groups/35475/>  [Instagram] <https://www.instagram.com/americanmanagementassociation/>  [YouTube] <https://www.youtube.com/user/AmericanManagement>  [Blog] <https://playbook.amanet.org/>

**Comment by NikCharlebois** [comment]
Sorry, doesn't look like any screenshots were included in the reply

**Comment by pkatanov** [comment]
***@***.***D7734A.747F4170]

Peter Katanov
Sr. Systems Engineer
P 212-903-8447 | M 646-285-2867
E ***@***.******@***.***> | www.amanet.org<http://www.amanet.org/>
1601 Broadway | New York, NY | 10019, USA
[American Management Association]<https://www.amanet.org/>    [Facebook] <https://www.facebook.com/AmericanManagementAssn/>  [Twitter] <https://twitter.com/amanet>  [LinkedIn] <https://www.linkedin.com/groups/35475/>  [Instagram] <https://www.instagram.com/americanmanagementassociation/>  [YouTube] <https://www.youtube.com/user/AmericanManagement>  [Blog] <https://playbook.amanet.org/>

**Comment by NikCharlebois** [comment]
@pkatanov any chances you can use the GitHub Web interface to post the screenshot? Thanks

**Comment by pkatanov** [comment]
Yes I will do that as soon as I get a chance.

Thanks,
Peter

Peter Katanov
Sr. Systems Engineer
P 212-903-8447 | M 646-285-2867
E ***@***.******@***.***> | www.amanet.org<http://www.amanet.org/>
1601 Broadway | New York, NY | 10019, USA
[American Management Association]<https://www.amanet.org/>    [Facebook] <https://www.facebook.com/AmericanManagementAssn/>  [Twitter] <https://twitter.com/amanet>  [LinkedIn] <https://www.linkedin.com/groups/35475/>  [Instagram] <https://www.instagram.com/americanmanagementassociation/>  [YouTube] <https://www.youtube.com/user/AmericanManagement>  [Blog] <https://playbook.amanet.org/>
