### ISSUE TITLE
Support for Multi Geo M365 tenants

### ISSUE THREAD

**Issue by ninjarish** [microsoft/Microsoft365DSC#1207]
Can M365 DSC solution support a tenant which has multi geo enabled for data residency/gdpr needs? When i checked a few months ago, multi geo support was not available. Can this be added as a roadmap item please?

https://docs.microsoft.com/en-us/microsoft-365/enterprise/multi-geo-capabilities-in-onedrive-and-sharepoint-online-in-microsoft-365?view=o365-worldwide

**Comment by NikCharlebois** [comment]
@desmay thoughts on how we could add support for Multi-Geo? Not sure we have any APIs to support this on the backend.

**Comment by NikCharlebois** [comment]
Will be added to backlog when PowerShell support becomes available.
