### ISSUE TITLE
Microsoft Teams Powershell issue , the remote server returned an error 404 not found

### ISSUE THREAD

**Issue by kareemamr5** [microsoft/Microsoft365DSC#1214]
I have this error for over a week now and i have no idea why but here are the steps that i did so you can understand and maybe someone can help me
1) I had a Microsoft problem with Teams on office 365 , i couldn't message external contacts as it kept showing me "Due to org policy changes , some chat and calling features are not longer available"
2) I tried to change the team settings but nothing worked , especially the option to change from Island to Teams only mode , it gave me the error "Please see the unsaved sections highlighted in red" 
3) I searched around abit till i found these codes
Disable-csonlinesipdomain - Domain (domain name)
Grant-CsTeamsUpgradePolicy -PolicyName UpgradeToTems -Global
all was done 
I tried then to access my teams admin center but it kept giving me
Error code: FAILED_TO_AUTO_DISCOVER_DOMAIN Organization ID: 69338fa0-0d2b-4b9f-bd2f-648ae583c40f Correlation ID: d437ffa1-f8c4-4a4d-9e82-a21ad91e60c3 Time stamp: 2021-0

I tried to enable it again and do other things but it kept giving me these errors
![MicrosoftTeams-image](https://user-images.githubusercontent.com/84399539/118680859-642ac480-b7ff-11eb-97c8-b9815e533477.png)
I have no idea what do i need to do now , i even verified the Skype records just in case but nothing worked
If anyone has any info please let me know

**Comment by NikCharlebois** [comment]
Are you able to reproduce with the latest versions? 1.21.630.1 or above
