### ISSUE TITLE
MSFT_SPOBrowserIdleSignout: Set-PnPTenant : A parameter cannot be found that matches parameter name 'Enabled'.

### ISSUE THREAD

**Issue by HaloX69** [microsoft/Microsoft365DSC#1221]
Module Version: 1.21.421.2

When trying to enforce browser sign-out with the properties SignOutAfter, and WarnAfter and the resource throws and exception.  The reason for this exception is that the **Enabled** property supported by the **Set-PnPTenant** cmdlet, but then the cmdlet doesn't accept parameters SignOutAfter, and WarnAfter.  TO fix the issue we need to call the cmdlet Set-PnPBrowserIdleSignout, replace line 188 in the Set-TargetResource.

#Set-PnPTenant @CurrentParameters | Out-Null
 Set-PnPBrowserIdleSignout @CurrentParameters | Out-Null

The issue also exists in the most current version 1.21.519.1

**Comment by Swampen** [comment]
I have added a PR for this. Thanks for spotting the error 👍
