### ISSUE TITLE
FEATURE REQUEST:  Add resource DesiredValue and CurrentValue to the App Insights telemetry 

### ISSUE THREAD

**Issue by HaloX69** [microsoft/Microsoft365DSC#1222]
We leverage the App Insights telemetry to our own Azure tenant.  We have custom alerts for DriftInfo events.  We would like to include the DesiredValue/CurrentValue in the Event data for ops notifications.  I understand you don't want to receive this info if users don't change the instrumentation key so the below code is what I am asking to be added.

Module:      M365DSCUtil.psm1
Function:    Test-M365DSCParameterState
Line:            749
Snippet:

`if($env:M365DSCTelemetryInstrumentationKey -ne "bc5aa204-0b1e-4499-a955-d6a639bdb4fa"){`
`     $driftedData.Add("CurrentValue",[string]($CurrentValues[$key]));`
`     $driftedData.Add("DesiredValue",[string]($DesiredValues[$key]));`
`}`

**Comment by NikCharlebois** [comment]
We need to be extremely careful when making changes to the data being reported by our telemetry. I personally don't see any privacy or technical concerns with your recommended change above, but want to get feedback from additional folks on my team before making any changes:
@ykuijs @desmay @ThorstenLoeschmann thoughts?

**Comment by HaloX69** [comment]
Again the change recommendations checks if the hard coded instrument key is not used don’t add the values. The desired/actual values are important for our alerting to ops. Each O366 service is managed by different teams and changes is values may define the priority of the ops work.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
