### ISSUE TITLE
EXOAcceptedDomain hanging when pushing configuration to target tenant

### ISSUE THREAD

**Issue by ChristopheLux** [microsoft/Microsoft365DSC#1228]
#### Details of the scenario you tried and the problem that is occurring
Exported Defaut Production Tenant
Push to new tenant Hanging on ExoAcceptedDomain
#### Verbose logs showing the problem
VERBOSE: [DESKTOP-RG8A0ID]: LCM:  [ Start  Resource ]  [[AADTenantDetails]a288214d-70e7-42a7-b31b-0d9693383130]
VERBOSE: [DESKTOP-RG8A0ID]: LCM:  [ Start  Test     ]  [[AADTenantDetails]a288214d-70e7-42a7-b31b-0d9693383130]
VERBOSE: [DESKTOP-RG8A0ID]:                            [[AADTenantDetails]a288214d-70e7-42a7-b31b-0d9693383130] Testing
 configuration of AzureAD Tenant Details
VERBOSE: [DESKTOP-RG8A0ID]:                            [[AADTenantDetails]a288214d-70e7-42a7-b31b-0d9693383130] Getting
 configuration of AzureAD Tenant Details
VERBOSE: [DESKTOP-RG8A0ID]:                            [[AADTenantDetails]a288214d-70e7-42a7-b31b-0d9693383130] Found
existing AzureAD Tenant Details
VERBOSE: [DESKTOP-RG8A0ID]:                            [[AADTenantDetails]a288214d-70e7-42a7-b31b-0d9693383130]
Get-TargetResource Result:
 ApplicationId=; CertificateThumbprint=; GlobalAdminAccount=System.Management.Automation.PSCredential;
IsSingleInstance=Yes; MarketingNotificationEmails=; SecurityComplianceNotificationMails=;
SecurityComplianceNotificationPhones=; TechnicalNotificationMails=d.belpassi@bcee.lu; TenantId=
VERBOSE: [DESKTOP-RG8A0ID]:                            [[AADTenantDetails]a288214d-70e7-42a7-b31b-0d9693383130]
Target-Values: GlobalAdminAccount=System.Management.Automation.PSCredential; IsSingleInstance=Yes;
MarketingNotificationEmails=(); SecurityComplianceNotificationMails=(); SecurityComplianceNotificationPhones=();
TechnicalNotificationMails=(charles.schwartz@bcee.lu); Verbose=True
VERBOSE: [DESKTOP-RG8A0ID]:                            [[AADTenantDetails]a288214d-70e7-42a7-b31b-0d9693383130]
Test-TargetResource returned False
VERBOSE: [DESKTOP-RG8A0ID]: LCM:  [ End    Test     ]  [[AADTenantDetails]a288214d-70e7-42a7-b31b-0d9693383130]  in
3.9420 seconds.
VERBOSE: [DESKTOP-RG8A0ID]: LCM:  [ Start  Set      ]  [[AADTenantDetails]a288214d-70e7-42a7-b31b-0d9693383130]
VERBOSE: [DESKTOP-RG8A0ID]:                            [[AADTenantDetails]a288214d-70e7-42a7-b31b-0d9693383130] Setting
 configuration of AzureAD Tenant Details
VERBOSE: [DESKTOP-RG8A0ID]: LCM:  [ End    Set      ]  [[AADTenantDetails]a288214d-70e7-42a7-b31b-0d9693383130]  in
0.9950 seconds.
VERBOSE: [DESKTOP-RG8A0ID]: LCM:  [ End    Resource ]  [[AADTenantDetails]a288214d-70e7-42a7-b31b-0d9693383130]
VERBOSE: [DESKTOP-RG8A0ID]: LCM:  [ Start  Resource ]  [[EXOAcceptedDomain]2f917ce3-76b3-48dc-9a10-df2889e8bc02]
VERBOSE: [DESKTOP-RG8A0ID]: LCM:  [ Start  Test     ]  [[EXOAcceptedDomain]2f917ce3-76b3-48dc-9a10-df2889e8bc02]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here


#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

    Get-ComputerInfo -Property @(
        'OsName',
        'OsOperatingSystemSKU',
        'OSArchitecture',
        'WindowsVersion',
        'WindowsBuildLabEx',
        'OsLanguage',
        'OsMuiLanguages')
-->

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.512.1 Microsoft365DSC

**Comment by NikCharlebois** [comment]
Can you please confirm that this is still happening with the latest version 1.21.630.1? Thanks
