### ISSUE TITLE
New-M365DSCDeltaReport doesnt report difference to ExcludedFileExtensions

### ISSUE THREAD

**Issue by nlangsto** [microsoft/Microsoft365DSC#1249]
Hello,
Im running 1.21.526.2
When performing delta report it doesn't detect difference for ExcludedFileExtensions

![image](https://user-images.githubusercontent.com/34170392/119985676-df883500-bfba-11eb-8679-6055ba117120.png)

**Comment by andikrueger** [comment]
This issue is related to #1178.
