### ISSUE TITLE
First "Full" run of "Export-M365DSCConfiguration"

### ISSUE THREAD

**Issue by beerhoff** [microsoft/Microsoft365DSC#1267]
It sticks on 12th task when I run "Export-M365DSCConfiguration" after clean installation.
"Full" config has been chosen via GUI.
Tested with two different tenants located in Canada East DC (MFA enabled)
For both cases, script sticks on the same 12th task [12/141] Extracting [EXOAcceptedDomain]..., see my screenshot attached. Tried 3 times, but w/o progress.
Waited for few hours, but w/o any progress or error message.

#### The operating system the target node is running
OsName                          : Microsoft Windows 10 Pro
OsOperatingSystemSKU  : 48
OsArchitecture                : 64-bit
WindowsVersion             : 2009
WindowsBuildLabEx        : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage                    : en-US
OsMuiLanguages          
![m365_screept_error](https://user-images.githubusercontent.com/33883261/121977231-827ad600-cd53-11eb-9d00-d6cd62f216d4.png)
   : {en-US, ru-RU, uk-UA}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Current Dev branch

**Comment by Swampen** [comment]
If you saw the yellow warning message in the GUI, there are currently issues with using the GUI where the export freezes.
Use the this command instead until the issue is fixed:
```powershell
Export-M365DSCConfiguration -Quiet -Mode Full -GlobalAdminAccount (Get-Credential)
```

**Comment by NikCharlebois** [comment]
As mentioned by @swampen this is related to the GUI. We are working on a revamped GUI which be web based. The first version is planned for the end of July and then will be rolled in the first October release as per our breaking change policy. Thanks
