### ISSUE TITLE
Management of Compliance Manager assessments, improvement actions and general updates

### ISSUE THREAD

**Issue by iSmkp** [microsoft/Microsoft365DSC#1270]
Hello!

I am curious if M365DSC supports the ability to manage and make updates to items in Compliance Manager, like assessments or improvement actions. I believe the answer to this questions is "no", based on the research I've done thus far, but I just wanted to make sure that this isn't a current feature.

Is there even a feasible way to do this in PowerShell? Preferably one that is supported by Microsoft, of course. I am not seeing any PowerShell cmdlets that would allow this functionality, but again I just want to make sure I am not missing something.

If this capability does not exist at all, is it planned? I realize that's not easy to answer, but many other compliance tools support the ability to bulk extract/modify/import control implementation and testing details. I believe this capability would be a powerful addition to the tool and very well received.

Thanks for any guidance or discussion you can provide!

**Comment by NikCharlebois** [comment]
Hi @iSmkp, you are correct M365DSC doesn't currently offer support for the Compliance Manager. However, we are in touch with the Compliance Manager team and have it on our backlog to add support for it once the PowerShell support becomes available. Thanks
