### ISSUE TITLE
Error with importing DLP settings (rules)

### ISSUE THREAD

**Issue by jhcontoso** [microsoft/Microsoft365DSC#1279]
#### Details of the scenario you tried and the problem that is occurring

Trying to import DLP with two DLP rules. Did a new config on tenant A, exported and trying to import but keeps failing on the DLP Rules

#### Verbose logs showing the problem

The PowerShell DSC resource '[SCDLPComplianceRule]bb6666e6-d086-4019-bc7c-60e2f5bc58e9' with SourceInfo 
'C:\agent\_work\2\s\rubiconcontoso\SC\M365ConfigurationSC.ps1::455::9::SCDLPComplianceRule' threw one or more 
non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel 
called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
The value specified in sensitive information is invalid.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : [Server=DB5EUR01WS123,RequestId=2b553ae8-3a57-4efc-a032-689e1abb0abc,TimeStamp=6/25/2021 
    11:18:41 AM] [FailureCategory=Cmdlet-InvalidContentContainsSensitiveInformationException] CC79A77C,Microsoft.Offi  
  ce.CompliancePolicy.Tasks.NewDlpComplianceRule
    + PSComputerName        : localhost
 
The PowerShell DSC resource '[SCDLPComplianceRule]faa1b345-4b60-410d-90c5-13a34bb51d72' with SourceInfo 
'C:\agent\_work\2\s\rubiconcontoso\SC\M365ConfigurationSC.ps1::340::9::SCDLPComplianceRule' threw one or more 
non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel 
called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
The value specified in sensitive information is invalid.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : [Server=DB5EUR01WS123,RequestId=768f5e6d-08ee-45c5-baec-277bd40aa1ae,TimeStamp=6/25/2021 
    11:18:11 AM] [FailureCategory=Cmdlet-InvalidContentContainsSensitiveInformationException] CC79A77C,Microsoft.Offi  
  ce.CompliancePolicy.Tasks.NewDlpComplianceRule
    + PSComputerName        : localhost
 

The value specified in sensitive information is invalid.
At C:\agent\_work\_temp\042c0ea2-7d8b-449e-b701-968299403750.ps1:8 char:1
+ throw $error[-1];
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : [Server=DB5EUR01WS123,RequestId=768f5e6d-08ee-45c5-baec-277bd40aa1ae,TimeStamp=6/25/2021 
    11:18:11 AM] [FailureCategory=Cmdlet-InvalidContentContainsSensitiveInformationException] CC79A77C,Microsoft.Offi  
  ce.CompliancePolicy.Tasks.NewDlpComplianceRule
    + PSComputerName        : localhost
 

#### Suggested solution to the issue

I dont know

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here

        SCDLPCompliancePolicy 239f176d-25c9-4b1c-8f7a-c6e0acfa2836
        {
            Comment                         = "Helps detect the presence of personal information for individuals inside the European Union (EU) to assist in meeting GDPR privacy obligations.";
            Ensure                          = "Present";
            ExchangeLocation                = "All";
            ExchangeSenderMemberOf          = @();
            ExchangeSenderMemberOfException = @();
            GlobalAdminAccount              = $Credsglobaladmin;
            Mode                            = "Enable";
            Name                            = "M365 DLP Baseline";
            OneDriveLocation                = "All";
            OneDriveLocationException       = @();
            Priority                        = 0;
            SharePointLocation              = "All";
            SharePointLocationException     = @();
            TeamsLocation                   = "All";
            TeamsLocationException          = @();
        }
        SCDLPComplianceRule faa1b345-4b60-410d-90c5-13a34bb51d72
        {
            BlockAccess                         = $False;
            ContentContainsSensitiveInformation = @(MSFT_SCDLPSensitiveInformation
            {
                name = 'Debetkaartnummer EU'
                id = '0e9b3178-9678-47dd-a509-37222ca96b42'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '9'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU Driver''s License Number'
                id = 'b8fe86d1-c056-453b-bfaa-9fe698699ecc'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '9'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU National Identification Number'
                id = '419f449f-6d9d-4be1-a154-b531f7a91b41'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '9'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU Passport Number'
                id = '21883626-6245-4f3d-9b61-5cbb43e625ee'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '9'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU Social Security Number (SSN) or Equivalent ID'
                id = 'd24e32a4-c0bb-4ba8-899d-6303b95742d9'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '9'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Netherlands Citizen''s Service (BSN) Number'
                id = 'c5f54253-ef7e-44f6-a578-440ed67e946d'
                maxconfidence = '100'
                minconfidence = '85'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Netherlands Driver''s License Number'
                id = '6247fbea-ab80-4be5-8233-308b7c031401'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Netherlands Passport Number'
                id = '61786727-bafd-45f6-94d9-888d815e228e'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Creditcardnummer'
                id = '50842eb7-edc8-4019-85dd-5a5c1f2bb085'
                maxconfidence = '100'
                minconfidence = '85'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
);
            Disabled                            = $False;
            DocumentIsPasswordProtected         = $False;
            DocumentIsUnsupported               = $False;
            Ensure                              = "Present";
            ExceptIfDocumentIsPasswordProtected = $False;
            ExceptIfDocumentIsUnsupported       = $False;
            ExceptIfHasSenderOverride           = $False;
            ExceptIfProcessingLimitExceeded     = $False;
            GenerateIncidentReport              = @("SiteAdmin");
            GlobalAdminAccount                  = $Credsglobaladmin;
            HasSenderOverride                   = $False;
            IncidentReportContent               = @("DocumentLastModifier","Detections","Severity","DetectionDetails","OriginalContent");
            Name                                = "Low volume of DLP content detected";
            NotifyAllowOverride                 = @("FalsePositive","WithJustification");
            NotifyUser                          = @("LastModifier","SiteAdmin","Owner");
            Policy                              = "M365 DLP Baseline";
            ProcessingLimitExceeded             = $False;
            RemoveRMSTemplate                   = $False;
            ReportSeverityLevel                 = "Low";
            StopPolicyProcessing                = $False;
        }
        SCDLPComplianceRule bb6666e6-d086-4019-bc7c-60e2f5bc58e9
        {
            BlockAccess                         = $False;
            ContentContainsSensitiveInformation = @(MSFT_SCDLPSensitiveInformation
            {
                name = 'Debetkaartnummer EU'
                id = '0e9b3178-9678-47dd-a509-37222ca96b42'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '10'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU Driver''s License Number'
                id = 'b8fe86d1-c056-453b-bfaa-9fe698699ecc'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '10'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU National Identification Number'
                id = '419f449f-6d9d-4be1-a154-b531f7a91b41'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '10'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU Passport Number'
                id = '21883626-6245-4f3d-9b61-5cbb43e625ee'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '10'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU Social Security Number (SSN) or Equivalent ID'
                id = 'd24e32a4-c0bb-4ba8-899d-6303b95742d9'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '10'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Netherlands Citizen''s Service (BSN) Number'
                id = 'c5f54253-ef7e-44f6-a578-440ed67e946d'
                maxconfidence = '100'
                minconfidence = '85'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Netherlands Driver''s License Number'
                id = '6247fbea-ab80-4be5-8233-308b7c031401'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Netherlands Passport Number'
                id = '61786727-bafd-45f6-94d9-888d815e228e'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Creditcardnummer'
                id = '50842eb7-edc8-4019-85dd-5a5c1f2bb085'
                maxconfidence = '100'
                minconfidence = '85'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
);
            Disabled                            = $False;
            DocumentIsPasswordProtected         = $False;
            DocumentIsUnsupported               = $False;
            Ensure                              = "Present";
            ExceptIfDocumentIsPasswordProtected = $False;
            ExceptIfDocumentIsUnsupported       = $False;
            ExceptIfHasSenderOverride           = $False;
            ExceptIfProcessingLimitExceeded     = $False;
            GenerateIncidentReport              = @("SiteAdmin");
            GlobalAdminAccount                  = $Credsglobaladmin;
            HasSenderOverride                   = $False;
            IncidentReportContent               = @("DocumentLastModifier","Detections","Severity","DetectionDetails","OriginalContent");
            Name                                = "High volume of  DLP content detected";
            NotifyAllowOverride                 = @("FalsePositive","WithJustification");
            NotifyUser                          = @("SiteAdmin","LastModifier","Owner");
            Policy                              = "M365 DLP Baseline";
            ProcessingLimitExceeded             = $False;
            RemoveRMSTemplate                   = $False;
            ReportSeverityLevel                 = "Medium";
            StopPolicyProcessing                = $False;
        }

#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

  
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
-->

#### Version of the DSC module that was used ('dev' if using current dev branch)

Current latest version 
1.21.616.1 (current version)

**Comment by ckuever** [comment]
we have the same error

**Comment by desmay** [comment]
We are working on several bug fixes for this resource, appreciate reporting this bugs and providing details.

**Comment by jhcontoso** [comment]
Also got some issues with retention policies, is this also known?

**Comment by ckuever** [comment]
receive those errors on SCDLPCompliancePolicy (to provide more details).

the account beeing used is ecluded from all MFA policys so that can't be the case, exchange sharepoint configurations are working fine with same acocunt beeing used. 

PowerShell DSC resource MSFT_SCDLPCompliancePolicy  failed to execute Test-TargetResource functionality with error 
message: Processing data from remote server deu01b.ps.compliance.protection.outlook.com failed with the following 
error message: The request for the Windows Remote Shell with ShellId 8691CEBF-EF74-4D8E-9169-21F2B27FEE61 failed 
because the shell was not found on the server. Possible causes are: the specified ShellId is incorrect or the shell no 
longer exists on the server. Provide the correct ShellId or create a new shell and retry the operation. For more 
information, see the about_Remote_Troubleshooting Help topic.

**Comment by desmay** [comment]
We have a release coming this and hopefully resolves issue.

**Comment by jhcontoso** [comment]
Hi Guys,

It's still not fixed with the latest release, see below:

------------------------------------------------------------------------------------------------------------------------------------

The value specified in sensitive information is invalid.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : [Server=DB5EUR01WS032,RequestId=d4115182-5407-49bc-b177-a601f6231a6f,TimeStamp=7/28/2021 
    12:01:35 PM] [FailureCategory=Cmdlet-InvalidContentContainsSensitiveInformationException] CD5C39C0,Microsoft.Offi  
  ce.CompliancePolicy.Tasks.NewDlpComplianceRule
    + PSComputerName        : localhost
 
The PowerShell DSC resource '[SCDLPComplianceRule]366aafd0-be4e-4394-9329-469d7278a8e1' with SourceInfo 
'C:\agent\_work\2\s\rubiconcontoso\SC\M365ConfigurationSC.ps1::353::9::SCDLPComplianceRule' threw one or more 
non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel 
called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
The value specified in sensitive information is invalid.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : [Server=DB5EUR01WS032,RequestId=4960f5eb-8411-4eec-af68-1f10b2e2ec52,TimeStamp=7/28/2021 
    12:01:05 PM] [FailureCategory=Cmdlet-InvalidContentContainsSensitiveInformationException] CD5C39C0,Microsoft.Offi  
  ce.CompliancePolicy.Tasks.NewDlpComplianceRule
    + PSComputerName        : localhost
 

The value specified in sensitive information is invalid.
At C:\agent\_work\_temp\f435e27b-bf8e-452a-9deb-a069b4c6487c.ps1:8 char:1
+ throw $error[-1];
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : [Server=DB5EUR01WS032,RequestId=4960f5eb-8411-4eec-af68-1f10b2e2ec52,TimeStamp=7/28/2021 
    12:01:05 PM] [FailureCategory=Cmdlet-InvalidContentContainsSensitiveInformationException] CD5C39C0,Microsoft.Offi  
  ce.CompliancePolicy.Tasks.NewDlpComplianceRule
    + PSComputerName        : localhost

**Comment by jhcontoso** [comment]
Did a fresh export and tried to import which failed (see comment above) the following config as shown below:

----------------------------------------------------------------------------------------------------------------------------------


    {
        SCComplianceTag d8102e72-f243-4273-bca4-c4873d3e0d9a
        {
            Comment              = "";
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            IsRecordLabel        = $False;
            Name                 = "M365 Baseline Retention Label";
            Notes                = "";
            Regulatory           = $False;
            RetentionAction      = "KeepAndDelete";
            RetentionDuration    = "2555";
            RetentionType        = "ModificationAgeInDays";
        }
        SCDLPCompliancePolicy 351b638f-e893-4a9d-a6df-757e4e6f6758
        {
            Comment                         = "Helps detect the presence of personal information for individuals inside the European Union (EU) to assist in meeting GDPR privacy obligations.";
            Ensure                          = "Present";
            ExchangeLocation                = "All";
            ExchangeSenderMemberOf          = @();
            ExchangeSenderMemberOfException = @();
            GlobalAdminAccount              = $Credsglobaladmin;
            Mode                            = "Enable";
            Name                            = "M365 DLP Baseline";
            OneDriveLocation                = "All";
            OneDriveLocationException       = @();
            Priority                        = 0;
            SharePointLocation              = "All";
            SharePointLocationException     = @();
            TeamsLocation                   = "All";
            TeamsLocationException          = @();
        }
        SCDLPComplianceRule 366aafd0-be4e-4394-9329-469d7278a8e1
        {
            BlockAccess                         = $False;
            ContentContainsSensitiveInformation = MSFT_SCDLPContainsSensitiveInformation
            {
                SensitiveInformation = @(
MSFT_SCDLPSensitiveInformation
            {
                name = 'Debetkaartnummer EU'
                id = '0e9b3178-9678-47dd-a509-37222ca96b42'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '9'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU Driver''s License Number'
                id = 'b8fe86d1-c056-453b-bfaa-9fe698699ecc'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '9'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU National Identification Number'
                id = '419f449f-6d9d-4be1-a154-b531f7a91b41'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '9'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU Passport Number'
                id = '21883626-6245-4f3d-9b61-5cbb43e625ee'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '9'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU Social Security Number (SSN) or Equivalent ID'
                id = 'd24e32a4-c0bb-4ba8-899d-6303b95742d9'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '9'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Netherlands Citizen''s Service (BSN) Number'
                id = 'c5f54253-ef7e-44f6-a578-440ed67e946d'
                maxconfidence = '100'
                minconfidence = '85'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Netherlands Driver''s License Number'
                id = '6247fbea-ab80-4be5-8233-308b7c031401'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Netherlands Passport Number'
                id = '61786727-bafd-45f6-94d9-888d815e228e'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Creditcardnummer'
                id = '50842eb7-edc8-4019-85dd-5a5c1f2bb085'
                maxconfidence = '100'
                minconfidence = '85'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
            )            }
;
            Disabled                            = $False;
            DocumentIsPasswordProtected         = $False;
            DocumentIsUnsupported               = $False;
            Ensure                              = "Present";
            ExceptIfDocumentIsPasswordProtected = $False;
            ExceptIfDocumentIsUnsupported       = $False;
            ExceptIfHasSenderOverride           = $False;
            ExceptIfProcessingLimitExceeded     = $False;
            GenerateIncidentReport              = @("SiteAdmin");
            GlobalAdminAccount                  = $Credsglobaladmin;
            HasSenderOverride                   = $False;
            IncidentReportContent               = @("DocumentLastModifier","Detections","Severity","DetectionDetails","OriginalContent");
            Name                                = "Low volume of DLP content detected";
            NotifyAllowOverride                 = @("FalsePositive","WithJustification");
            NotifyUser                          = @("LastModifier","SiteAdmin","Owner");
            Policy                              = "M365 DLP Baseline";
            ProcessingLimitExceeded             = $False;
            RemoveRMSTemplate                   = $False;
            ReportSeverityLevel                 = "Low";
            StopPolicyProcessing                = $False;
        }
        SCDLPComplianceRule 0604e747-bb1a-4f42-a60a-cbbe3daf1149
        {
            BlockAccess                         = $False;
            ContentContainsSensitiveInformation = MSFT_SCDLPContainsSensitiveInformation
            {
                SensitiveInformation = @(
MSFT_SCDLPSensitiveInformation
            {
                name = 'Debetkaartnummer EU'
                id = '0e9b3178-9678-47dd-a509-37222ca96b42'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '10'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU Driver''s License Number'
                id = 'b8fe86d1-c056-453b-bfaa-9fe698699ecc'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '10'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU National Identification Number'
                id = '419f449f-6d9d-4be1-a154-b531f7a91b41'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '10'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU Passport Number'
                id = '21883626-6245-4f3d-9b61-5cbb43e625ee'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '10'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'EU Social Security Number (SSN) or Equivalent ID'
                id = 'd24e32a4-c0bb-4ba8-899d-6303b95742d9'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '10'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Netherlands Citizen''s Service (BSN) Number'
                id = 'c5f54253-ef7e-44f6-a578-440ed67e946d'
                maxconfidence = '100'
                minconfidence = '85'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Netherlands Driver''s License Number'
                id = '6247fbea-ab80-4be5-8233-308b7c031401'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Netherlands Passport Number'
                id = '61786727-bafd-45f6-94d9-888d815e228e'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Creditcardnummer'
                id = '50842eb7-edc8-4019-85dd-5a5c1f2bb085'
                maxconfidence = '100'
                minconfidence = '85'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
            )            }
;
            Disabled                            = $False;
            DocumentIsPasswordProtected         = $False;
            DocumentIsUnsupported               = $False;
            Ensure                              = "Present";
            ExceptIfDocumentIsPasswordProtected = $False;
            ExceptIfDocumentIsUnsupported       = $False;
            ExceptIfHasSenderOverride           = $False;
            ExceptIfProcessingLimitExceeded     = $False;
            GenerateIncidentReport              = @("SiteAdmin");
            GlobalAdminAccount                  = $Credsglobaladmin;
            HasSenderOverride                   = $False;
            IncidentReportContent               = @("DocumentLastModifier","Detections","Severity","DetectionDetails","OriginalContent");
            Name                                = "High volume of  DLP content detected";
            NotifyAllowOverride                 = @("FalsePositive","WithJustification");
            NotifyUser                          = @("SiteAdmin","LastModifier","Owner");
            Policy                              = "M365 DLP Baseline";
            ProcessingLimitExceeded             = $False;
            RemoveRMSTemplate                   = $False;
            ReportSeverityLevel                 = "Medium";
            StopPolicyProcessing                = $False;
        }
        SCRetentionCompliancePolicy 8c6dd1ba-92b2-4b01-879a-28c9f82aa4df
        {
            Comment                       = "";
            Enabled                       = $True;
            Ensure                        = "Present";
            GlobalAdminAccount            = $Credsglobaladmin;
            Name                          = "M365 Baseline Teams Retention";
            RestrictiveRetention          = $False;
            TeamsChannelLocation          = @();
            TeamsChannelLocationException = @();
            TeamsChatLocation             = @();
            TeamsChatLocationException    = @();
        }
        SCRetentionCompliancePolicy 7d9bb202-453d-4206-9a27-42df1ac5a4d1
        {
            Comment                      = "Used for publishing retention labels";
            Enabled                      = $True;
            Ensure                       = "Present";
            ExchangeLocation             = @();
            ExchangeLocationException    = @();
            GlobalAdminAccount           = $Credsglobaladmin;
            ModernGroupLocation          = @();
            ModernGroupLocationException = @();
            Name                         = "M365 Baseline Rentention Policy";
            OneDriveLocation             = @();
            OneDriveLocationException    = @();
            PublicFolderLocation         = @();
            RestrictiveRetention         = $False;
            SharePointLocation           = @();
            SharePointLocationException  = @();
            SkypeLocation                = @();
            SkypeLocationException       = @();
        }
        SCRetentionComplianceRule ac56e3ee-d220-4278-80a4-de735dee2ccc
        {
            Comment                      = "";
            ContentMatchQuery            = "";
            Ensure                       = "Present";
            ExcludedItemClasses          = @();
            ExpirationDateOption         = "CreationAgeInDays";
            GlobalAdminAccount           = $Credsglobaladmin;
            Name                         = "M365 Baseline Teams Retention";
            Policy                       = "M365 Baseline Teams Retention";
            RetentionComplianceAction    = "KeepAndDelete";
            RetentionDuration            = "2555";
            RetentionDurationDisplayHint = "Days";
        }
        SCRetentionComplianceRule ed44a7e6-e64f-4f89-a0e7-6969ec19c030
        {
            Comment                      = "";
            ContentMatchQuery            = "";
            Ensure                       = "Present";
            ExcludedItemClasses          = @();
            GlobalAdminAccount           = $Credsglobaladmin;
            Name                         = "ctptr-0a94cdac-c91a-44dc-bf1c-6fbd32f9b3f5";
            Policy                       = "M365 Baseline Rentention Policy";
            RetentionComplianceAction    = "KeepAndDelete";
            RetentionDurationDisplayHint = "Days";
        }

**Comment by desmay** [comment]
Are there any sensitivity label defined in DLP rules ? Are you using any custom SIT within your policies ? I'm working on adding support for sensitivity labels with rules.

**Comment by jhcontoso** [comment]
No there are nog Custom options or whatever in the DLP Rules, juist EU/Dutch things to trigger on

**Comment by jhcontoso** [comment]
Here are the errors with the 728.1 version of the module:

-----------------------------------------------------------------------------------------------------------------------------------
VERBOSE: [M365DSCAgent]: LCM:  [ End    Set      ]  [[SCRetentionComplianceRule]ed44a7e6-e64f-4f89-a0e7-6969ec19c030]  
in 21.1560 seconds.
The PowerShell DSC resource '[SCRetentionComplianceRule]ed44a7e6-e64f-4f89-a0e7-6969ec19c030' with SourceInfo 
'C:\agent\_work\2\s\rubiconcontoso\SC\M365ConfigurationSC.ps1::638::9::SCRetentionComplianceRule' threw one or more 
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
The value specified in sensitive information is invalid.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : [Server=DB5EUR01WS008,RequestId=a5d8242f-c40e-4ec4-bd10-452e73bc0e1b,TimeStamp=8/3/2021  
   8:26:48 AM] [FailureCategory=Cmdlet-InvalidContentContainsSensitiveInformationException] CCD766DF,Microsoft.Office  
  .CompliancePolicy.Tasks.NewDlpComplianceRule
    + PSComputerName        : localhost
 
The PowerShell DSC resource '[SCDLPComplianceRule]366aafd0-be4e-4394-9329-469d7278a8e1' with SourceInfo 
'C:\agent\_work\2\s\rubiconcontoso\SC\M365ConfigurationSC.ps1::353::9::SCDLPComplianceRule' threw one or more 
non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel 
called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
The value specified in sensitive information is invalid.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : [Server=DB5EUR01WS008,RequestId=130b1f38-5aaa-426f-80e5-acf76c51eb96,TimeStamp=8/3/2021  
   8:26:15 AM] [FailureCategory=Cmdlet-InvalidContentContainsSensitiveInformationException] CCD766DF,Microsoft.Office  
  .CompliancePolicy.Tasks.NewDlpComplianceRule
    + PSComputerName        : localhost
 

The value specified in sensitive information is invalid.
At C:\agent\_work\_temp\e6ac6159-7024-4781-ba6e-eb586fb0f05f.ps1:8 char:1
+ throw $error[-1];
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : [Server=DB5EUR01WS008,RequestId=130b1f38-5aaa-426f-80e5-acf76c51eb96,TimeStamp=8/3/2021  
   8:26:15 AM] [FailureCategory=Cmdlet-InvalidContentContainsSensitiveInformationException] CCD766DF,Microsoft.Office  
  .CompliancePolicy.Tasks.NewDlpComplianceRule
    + PSComputerName        : localhost
 
##[error]PowerShell exited with code '1'.
Finishing: Deploy SC Config

**Comment by jhcontoso** [comment]
Any updates? @desmay

**Comment by desmay** [comment]
@jhcontoso  Does export work with latest ? If so can you attach file here for me to test/debug ?

**Comment by hansze** [comment]
I have also hit problems with TransportRules where there is a MessageContainsDataClassifications set. The object is not deserialized in a format that can be easily converted back into the needed type (HashTable[]). 

What the deserialized object is a String[] with the format (Not quite JSON as keys are not in quotes) Below is a sample

{id="ABA Routing Number"; guid="cb353f78-2b72-4c3c-8827-92ebe4f69fdf"; displayName="ABA Routing Number"; minCount=1; maxCount="Infinity"; minConfidence="Recommended"; maxConfidence=100}

New-TransportRule and Set-TransportRUle expect an array of HashTables as an argument for the parameter MessageContainsDataClassifications. Also, the key property is Name and not displayName but Get-TransportRule does not supply this ..should be identical, however.
