### ISSUE TITLE
SCDLPComplianceRule: Export-M365DSCConfiguration bombs out if it hits a rule with condition looking for Sensitivity labels

### ISSUE THREAD

**Issue by HardingChris** [microsoft/Microsoft365DSC#1286]
#### Details of the scenario you tried and the problem that is occurring

Running the following to try to export the DLP Compliance Rules:
Export-M365DSCConfiguration -Quiet -GlobalAdminAccount $creds -ComponentsToExtract @("SCDLPComplianceRule")

Results from console:

[1/1] Extracting [SCDLPComplianceRule]...
    |---[1/10] DLP Rule 1✅
    |---[2/10] DLP Rule 2✅
    |---[3/10] DLP Rule 3✅
    |---[4/10] DLP Rule 4✅
    |---[5/10] Notify for Internal Only to external recipients⌛ Export took {74 seconds}

The fifth rule above has a condition that checks for specific Sensitivity labels. When it reaches this rule, it stops processing further rules and doesn't return a result for inclusion in the output file.

If I change the condition on this rule to look for a Sensitive Info Type, rather than a Sensitivity label, then it runs to completion:

[1/1] Extracting [SCDLPComplianceRule]...
    |---[1/10] DLP Rule 1✅
    |---[2/10] DLP Rule 2✅
    |---[3/10] DLP Rule 3✅
    |---[4/10] DLP Rule 4✅
    |---[5/10] Notify for Internal Only to external recipients✅
    |---[6/10] DLP Rule 6✅
    |---[7/10] DLP Rule 7✅
    |---[8/10] DLP Rule 8✅
    |---[9/10] DLP Rule 9✅
    |---[10/10] DLP Rule 10✅
⌛ Export took {72 seconds}

Problem rule with condition looking for Sensitivity labels from compliance console:
![image](https://user-images.githubusercontent.com/73641141/124345918-c2570f80-dbd3-11eb-8690-581a8694c70d.png)

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
I'm guessing some changes needed to the functions that are processing $Results.ContentContainsSensitiveInformation

I've exported to JSON, and the structure of the data is quite different when a Sensitivity label is used in the condition, rather than a Sensitive info type:

_**Condition looking for Sensitive Info Type (exports OK):**_
"ContentContainsSensitiveInformation":  [
                                                {
                                                    "maxconfidence":  "100",
                                                    "confidencelevel":  "Medium",
                                                    "id":  "cb353f78-2b72-4c3c-8827-92ebe4f69fdf",
                                                    "minconfidence":  "75",
                                                    "rulePackId":  "00000000-0000-0000-0000-000000000000",
                                                    "classifiertype":  "Content",
                                                    "name":  "ABA Routing Number",
                                                    "mincount":  "1",
                                                    "maxcount":  "-1"
                                                }
                                            ],

_**Condition looking for Sensitivity Label (fails to export):**_
"ContentContainsSensitiveInformation":  [
                                                {
                                                    "groups":  [
                                                                   {
                                                                       "operator":  "Or",
                                                                       "labels":  [
                                                                                      {
                                                                                          "name":  "Internal Only",
                                                                                          "id":  "8beaea1a-50c1-44c0-931c-e9a068c1c085",
                                                                                          "type":  "Sensitivity"
                                                                                      }
                                                                                  ],
                                                                       "name":  "Default"
                                                                   }
                                                               ],
                                                    "operator":  "And"
                                                }
                                            ],

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

Export-M365DSCConfiguration -Quiet -GlobalAdminAccount $creds -ComponentsToExtract @("SCDLPComplianceRule")

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Microsoft365DSC version 1.21.630.1

**Comment by HardingChris** [comment]
It looks as though the problem lies within the function ConvertTo-SCDLPSensitiveInformationString:

This line in the function tries to call the Replace method, but where the rule includes a condition checking for Sensitivity label, it generates the error below:

$StringContent += "                name = '$($SensitiveInformationHash.name.Replace("'", "''"))'`r`n"

Error "You cannot call a method on a null-valued expression."

**Comment by desmay** [comment]
@HardingChris  Can you try again with latest release ?  I've added logic for sensitivity labels in DLP and tested various labels.

**Comment by HardingChris** [comment]
Hi @desmay - this looks to have worked - thanks!

**Comment by desmay** [comment]
Awesome closing this issue.
