### ISSUE TITLE
export Azure AD policy and import with .mof file with error

### ISSUE THREAD

**Issue by Maggie3430** [microsoft/Microsoft365DSC#1299]
'ResourceName: AADPolicy import .mof file (originally exported configuration) failed

    ISSUE DESCRIPTION (this template):
    We're trying to use 365DSC for the management of Azure AD, we have an service account which has global reader access. and we are able to export the AADPolicy, TenantDetails, etc. but when we tried to import the configure ps1 file we exported(using start-dscconfiguration -path xxx cmd), but got error here: 
Error occurred while executing SetPolicy
Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.
InnerError:
RequestId:
DateTimeStamp:
HttpStatusCode: Forbidden
HttpStatusDescription: Forbidden
HttpResponseStatus: Completed
    CategoryInfo: NotSpecified:(:)[], CimException
    FullyQualifiedErrorId: Microsoft.Open.MSGraphBeta.Client.ApiException, Microsoft.Open.MSGraphBeta.PowerShellPolicy
    PSComputerName: localhost

    PLEASE KEEP THE HEADERS.

    You may remove this comment block, and the other comment blocks,
    but please keep the headers.
-->
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here

# Generated with Microsoft365DSC version 1.21.224.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $GlobalAdminAccount
)

Configuration M365TenantConfig
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $GlobalAdminAccount
    )

    if ($null -eq $GlobalAdminAccount)
    {
        <# Credentials #>
        $Credsglobaladmin = Get-Credential -Message "Global Admin credentials"

    }
    else
    {
        $Credsglobaladmin = $GlobalAdminAccount
    }

    $OrganizationName = $Credsglobaladmin.UserName.Split('@')[1]
    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.21.224.1'

    Node localhost
    {
        AADPolicy xxxxx
        {
            Definition            = @("{`"B2BManagementPolicy`":{`"InvitationsAllowedAndBlockedDomainsPolicy`":{`"BlockedDomains`":[]},`"AutoRedeemPolicy`":{`"AdminConsentedForUsersIntoTenantIds`":[],`"NoAADConsentForUsersFromTenantsIds`":[]}}}");
            DisplayName           = "B2BManagementPolicy";
            Ensure                = "Present";
            GlobalAdminAccount    = $Credsglobaladmin;
            Id                    = "xxxxx";
            IsOrganizationDefault = $True;
            Type                  = "B2BManagementPolicy";
            PsDscRunAsCredential = $Credsglobaladmin;
        }
        AADPolicy xxxxx
        {
            Definition            = @("{`"TokenLifetimePolicy`":{`"Version`":1,`"AccessTokenLifetime`":`"00.00:30:00`"}}");
            DisplayName           = "OrganizationDefaultPolicy";
            Ensure                = "Present";
            GlobalAdminAccount    = $Credsglobaladmin;
            Id                    = "xxxxx";
            IsOrganizationDefault = $True;
            Type                  = "TokenLifetimePolicy";
            PsDscRunAsCredential = $Credsglobaladmin;
        }
        AADPolicy xxxxx
        {
            Definition            = @("{
  `"TokenIssuancePolicy`": {
    `"Version`": 1,
    `"SigningAlgorithm`": `"http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`",
    `"TokenResponseSigningPolicy`": `"ResponseAndToken`",
    `"SamlTokenVersion`": `"2.0`"
  }
}");
            DisplayName           = "TokenIssuancePolicy";
            Ensure                = "Present";
            GlobalAdminAccount    = $Credsglobaladmin;
            Id                    = "xxxxx";
            IsOrganizationDefault = $False;
            Type                  = "TokenIssuancePolicy";
            PsDscRunAsCredential = $Credsglobaladmin;
        }
        AADPolicy xxxxx
        {
            Definition            = @("{
	`"CrossTenantAccessPolicy`": {
		`"Version`": 1,
		`"LastModified`": `"2020-07-23 00:00:00Z`",
		`"TenantGroup`": [
			{
				`"DisplayName`": `"xxxxx`",
				`"Tenants`": [
					`"xxxxx`",
					`"xxxxx`"
				],
				`"FromMyTenancy`": [
					{
						`"AllowAccess`": false
					}
				],
				`"ToMyTenancy`": [
					{
						`"AllowAccess`": true,
						`"AcceptMFA`": true,
						`"AcceptCompliantDevice`": true,
						`"AcceptHybridAzureADJoinedDevice`": true
					}
				]
			}
		]
	}
}
");
            DisplayName           = "Cross Tenant Access Policy";
            Ensure                = "Present";
            GlobalAdminAccount    = $Credsglobaladmin;
            Id                    = "xxxxx";
            IsOrganizationDefault = $True;
            Type                  = "CrossTenantAccessPolicy";
            PsDscRunAsCredential = $Credsglobaladmin;
        }
    }
}
M365TenantConfig -ConfigurationData .\ConfigurationData.psd1 -GlobalAdminAccount $GlobalAdminAccount


#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

    Get-ComputerInfo -Property @(
        'OsName',
        'OsOperatingSystemSKU',
        'OSArchitecture',
        'WindowsVersion',
        'WindowsBuildLabEx',
        'OsLanguage',
        'OsMuiLanguages')
-->

#### Version of the DSC module that was used ('dev' if using current dev branch)

**Comment by NikCharlebois** [comment]
Thanks @Maggie3430, just to confirm, what account are you using when compiling the .mof file?

Normally, you would use Global Reader to export the config into a .ps1 file, but before you try applying it back to an environment, you need to execute the .ps1 (effectively compiling it into a mof file). When executing the exported .ps1 file you will be prompted for credentials and at this point you will need to provide credentials for a user that has more than Global Reader privileges since it will need to configure components. Thanks

**Comment by Maggie3430** [comment]
Hi Nik,

Thanks for your reply, I use admin in the windows server host to compile the ps1 to .mof file, and for the import of .mof file, I use the same account as export the ps1 configure file which has global reader access, do you think this role does not have enough privileges for the .mof file import operation?
We tried actually with export AADTenantDetails ps1 configure file, compile it to .mof file and then tried to import, but got the different error of:
PowerShell DSC resource MSFT__AADTenantDetails failed to execute Test-TargetResource functionality with error message: Could not retrieve AzureAD Tenant Details.
In this case, it does not looks like credential issue.
So we’re not sure if GR role is enough or not for the import of .mof file related to AAD resources.

Looking forward to your clarification.
Thanks,
Maggie

**Comment by NikCharlebois** [comment]
Hi @Maggie3430, Global Reader is ok when doing the export, but when applying a configuration using the Start-DSCConfiguration, the account will require admin permissions on the workloads affected (e.g. SharePoint Online Admin, Exchange Admin, Global Admin, etc.). Thanks
