### ISSUE TITLE
Export-M365DSCConfiguration continually fails in GCC-High environment

### ISSUE THREAD

**Issue by mthom15** [microsoft/Microsoft365DSC#1339]
Export-M365DSCConfiguration -Quiet -Workloads @('SC') -GlobalAdminAccount $NewCredential
[1/24] Extracting [SCAuditConfigurationPolicy]...
[2/24] Extracting [SCCaseHoldPolicy]...
[3/24] Extracting [SCCaseHoldRule]...
[4/24] Extracting [SCComplianceCase]...Processing data from remote server ps.compliance.protection.office365.us failed with the following error message: Fail to create a runspace because you have exceeded the maximum number of connections allowed : 3. Please close existing runspace and try again. For more information, see the about_Remote_Troubleshooting Help topic.

I have also downgraded to 1.20.930.1 as I saw in a previous post but that fails as well with a lot more errors.

I have also tried just downgrading my ExchangeOnlineManagement module to 2.0.1 but the export still fails with that as well.

**Comment by mthom15** [comment]
I can get it to work just fine in commercial environments but it always fails in GCC-High environments.

**Comment by desmay** [comment]
Can you check what version of  MSCloudLoginAssistant you have installed? What happens if you run the following `Test-MSCloudLogin -Platform SecurityComplianceCenter -CloudCredential admin@contoso.com`.

**Comment by mthom15** [comment]
The version I am running is 1.0.54. 
When I run that command it asks me for my password, I give it, then it loads a couple of implicit remoting modules and seems to log in just fine.

**Comment by mthom15** [comment]
![image](https://user-images.githubusercontent.com/25484516/127211858-5b4b0dea-4d74-4326-b3f9-0d9a7eba968e.png)

**Comment by desmay** [comment]
I was able to repro the error in GCCH. I'll look into bug.

**Comment by mthom15** [comment]
Thank you

**Comment by mthom15** [comment]
Hey @desmay, were you able to figure out anything on this issue yet? Is there any kind of work around in the mean time?

**Comment by mthom15** [comment]
I installed the latest modules today. Now I am getting the error below when trying to do an export.
cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
[1/24] Extracting [SCAuditConfigurationPolicy]...Error Acquiring Token:
AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000007-0000-0ff1-ce00-000000000000'.
Trace ID: bea0f41a-0b37-4448-9e30-62193ff89d00
Correlation ID: 96dcecb3-1fe1-4506-8439-428213435ac4
Timestamp: 2021-08-09 17:46:44Z
A parameter cannot be found that matches parameter name 'CloudCredential'.
Partial Export file was saved at: C:\Users\MICHAE~1.THO\AppData\Local\Temp\6c4be7df-d96a-4a92-851b-72e3a12736a2.partial.ps1.ps1.partial

I ran the Test-MSCloudLogin again that you sent 13 days ago and I get the error below.
Error Acquiring Token:
AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000007-0000-0ff1-ce00-000000000000'.
Trace ID: 2f5ee191-59b3-4ccc-ae49-db5ee825eb00
Correlation ID: 70a41b00-bead-4c10-a7bd-12f9f847bae6
Timestamp: 2021-08-09 17:48:43Z
Connect-MSCloudLoginSecurityComplianceMFA : A parameter cannot be found that matches parameter name 'CloudCredential'.
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.62\Workloads\SecurityCompliance.psm1:114
char:55
+ ...    Connect-MSCloudLoginSecurityComplianceMFA -CloudCredential $Global ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-MSCloud...tyComplianceMFA], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Connect-MSCloudLoginSecurityComplianceMFA

**Comment by chaospheremk** [comment]
For GCC High I think you have to authenticate with a registered application in Azure AD and a certificate on your machine. Haven't tested this yet but those are my first thoughts.

**Comment by desmay** [comment]
@mthom15  Sorry for delay I just ran an export using your command in GCCH with latest version and had no issues:

Export-M365DSCConfiguration -Quiet -Workloads @('SC') -GlobalAdminAccount $NewCredential

If you have multiple versions of MSCloudLoginAssistant in PowerShell folder delete all old versions the latest should 1.0.62

![image](https://user-images.githubusercontent.com/43035577/129078086-a239b996-a922-4569-b08d-f75a4e198425.png)

**Comment by desmay** [comment]
Also this was using latest release of Microsoft365DSC version 1.21.804.1

**Comment by mthom15** [comment]
@desmay I have completely cleaned out all modules in my powershell and restarted from scratch and then installed the Microsoft365DSC modules. The newest version of Microsoft365DSC is the only one I have as well as all of the modules within. I'm still getting the same error unless I use a non-mfa enabled account.

**Comment by desmay** [comment]
@mthom15  I have a fix for the issue if you want to test you can grab the file from my repro and replace the existing file in this directory "C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.62\Workloads\" .  It maybe a week before fix is checked into M365DSC repro. 

Here is fix - https://github.com/desmay/MSCloudLoginAssistant/blob/SCCMFA/Modules/MSCloudLoginAssistant/Workloads/SecurityCompliance.psm1

**Comment by mthom15** [comment]
@desmay that did the trick. MSCloudLoginAssistant works now. It's still broken when I try to do an export but if I call the Test-MSCloudLogin -Platform SecurityComplianceCenter it works there.

**Comment by desmay** [comment]
@mthom15 Is the error on export any different ? Microsoft365DSC uses MSCloudLoginAssistant so it should have resolved your issue. I don't have a MFA enabled account I can test with at the moment in GCCH

**Comment by mthom15** [comment]
@desmay Sorry about that. I was still trying to do an Intune export. The Security and Compliance center export is working correctly now. I'm guessing the same fix will have to be applied to all of the workloads in that module so that everything else works correctly again as well?

**Comment by desmay** [comment]
Every service has its own way to connect. We haven't had any issues reported with other workloads but let us know if you run into issues.  I'll leave this issue open until changes are merged into release

**Comment by mthom15** [comment]
I'll get started testing the other workloads but I can tell you it doesn't work with Intune for sure.

[1/11] Extracting [IntuneAppConfigurationPolicy]...AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.
Trace ID: 06c63f82-3fa6-427f-b71f-208d99932800
Correlation ID: 50e94087-84ac-49c7-ae96-f9c48324f787
Timestamp: 2021-08-13 17:39:35Z

**Comment by mthom15** [comment]
I've tested Exchange, O365, SC, Azure and Intune. Intune seems to be the only one that doesn't work right now.

**Comment by mthom15** [comment]
Not sure how or why but Intune is now working too! Thanks @desmay you rock!

**Comment by mthom15** [comment]
@desmay Exporting anything for Teams doesn't seem to be working but everything else is still good.

Export-M365DSCConfiguration -Quiet -ComponentsToExtract @("TeamsCallingPolicy", "TeamsChannel", "TeamsChannelsPolicy", "TeamsClientConfiguration", "TeamsEmergencyCallingPolicy", "TeamsEmergencyCallRoutingPolicy", "TeamsGuestCallingConfiguration", "TeamsGuestMeetingConfiguration", "TeamsGuestMessagingConfiguration", "TeamsMeetingBroadcastConfiguration", "TeamsMeetingBroadcastPolicy", "TeamsMeetingConfiguration", "TeamsMeetingPolicy", "TeamsMessagingPolicy", "TeamsPstnUsage", "TeamsTenantDialPlan", "TeamsUpgradeConfiguration", "TeamsUpgradePolicy", "TeamsVoiceRoute", "TeamsVoiceRoutingPolicy") -GlobalAdminAccount $Credentials -Path 'C:\m365dsc\EcoGCCHigh\GCCHigh Teams'

[1/20] Extracting [TeamsCallingPolicy]...One or more errors occurred.
Partial Export file was saved at: C:\Users\MICHAE~1.THO\AppData\Local\Temp\2384ea99-07d6-4779-b3d6-07e45482026b.partial.ps1.ps1.partia
l

**Comment by NikCharlebois** [comment]
This has been fixed in a recent release of the MSCloudLoginAssistant module
