### ISSUE TITLE
Export stuck on EXOAcceptedDomains

### ISSUE THREAD

**Issue by ChristianVerhoeven** [microsoft/Microsoft365DSC#1340]
When I run the Show-M365DSCGUI and do an export using the default selection with an non MFA Global admin account it gets stuck on the 'Extracting EXOAcceptedDomains' step. Tried this from 3 different VM's (one completely clean install) and two different tenants (both with there own accounts in AAD (no guests)).

Using Microsoft365DSC version 1.21.721.1 installed it an hour ago on the brand new clean VM. No conditional access policies are blocking these attempts (verified this in the Sign-In logging and excluded account from all policies)

**Comment by NikCharlebois** [comment]
As indicated in the GUI, there is an issue with the underlying PowerShell modules that Microsoft365DSC depends on that is causing the export to get stuck on Exchange, SPO and other workloads when using the GUI. The way to get around this is to use the new web version at: https://export-preview.microsoft365dsc.com

Which will let you generate the unattended command to run, and then to execute that command back into the PowerShell console. Thanks
