### ISSUE TITLE
SPOApp not working with Service Principal

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#1351]
#### Details of the scenario you tried and the problem that is occurring
The SPOApp resource is not working with a Service Principal (AppSecret or Certificate). This is due to a lack of App-Only permission for AppCatalog.ReadWrite.All

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Do nothing and wait for when support to interact with app catalog as Application only is available or drop the resource all together.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.728.1

**Comment by andikrueger** [comment]
The permission scope AppCatalog.ReadWrite.All is available for app-only auth: https://docs.microsoft.com/en-us/graph/permissions-reference#application-permissions-3

Do we need to check anything further?
