### ISSUE TITLE
Problem when loading module Microsoft365DSC and MsOnline

### ISSUE THREAD

**Issue by T630Dev** [microsoft/Microsoft365DSC#1352]
ISSUE TITLE:
    Cannot load module (by using import-module, after the module was successfully installed) 
![LoadingIssue](https://user-images.githubusercontent.com/88185985/127627075-2b1f8c2e-0555-4cfb-ad60-269e6ae605fd.png)
MsOnline in version 1.1.183.57 (as of now latest) when having loaded Microsoft365DSC module before 
    with version 1.21.728.1.

Only happens with PS 7.x, not with PS 5.1

    ISSUE DESCRIPTION (this template):
    Assemblies are loaded into the currentDomain for the AppDomain which then causes an assembly conflict.

**Comment by NikCharlebois** [comment]
@T630Dev due to some dependencies not being supported on PowerShell Core, Microsoft365DSC only supports PowerShell 5.1 at the moment. Thanks
