### ISSUE TITLE
MOF Compile fails after export of Intune policies

### ISSUE THREAD

**Issue by beejay31** [microsoft/Microsoft365DSC#1353]
ISSUE TITLE: MOF Compile: Error executing M365TenantConfig.ps1 containing Intune policies immediately after export of tenant configuration
 
    ISSUE DESCRIPTION 

Ran this command to export Intune policies:

# Exporting resources using credentials
Export-M365DSCConfiguration -Quiet -ComponentsToExtract @("IntuneAppConfigurationPolicy", "IntuneAppProtectionPolicyiOS", "IntuneDeviceCompliancePolicyAndroid", "IntuneDeviceCompliancePolicyiOs", "IntuneDeviceConfigurationPolicyiOS", "IntuneDeviceEnrollmentLimitRestriction", "IntuneDeviceEnrollmentPlatformRestriction") -GlobalAdminAccount $Credentials
    

Export completed successfully.

[M365TenantConfig.zip](https://github.com/microsoft/Microsoft365DSC/files/6907022/M365TenantConfig.zip)
 
Executed the exported ps1 file and receive following output:

PS C:\temp\Baseline\Intune> .\M365TenantConfig.ps1
PSDesiredStateConfiguration\Node : The term 'allAllowed' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At C:\temp\Baseline\Intune\M365TenantConfig.ps1:31 char:5
+     Node localhost
+     ~~~~
    + CategoryInfo          : ObjectNotFound: (allAllowed:String) [PSDesiredStateConfiguration\node], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException,PSDesiredStateConfiguration\node

Compilation errors occurred while processing configuration 'M365TenantConfig'. Please review the errors reported in error stream and modify your configuration code appropriately.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (M365TenantConfig:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration

#### Version of the DSC module that was used ('dev' if using current dev branch): 

Microsoft365dsc: 1.21.728.1
Windows 10: 19041.1110
Powershell: 5.1.19041.1023

**Comment by NikCharlebois** [comment]
@RuudGijsbers Can you also have a look at this one as well? Thanks

**Comment by RuudGijsbers** [comment]
I'll look into it and let you know when I have an update

**Comment by RuudGijsbers** [comment]
I found that it's the iOs configuration policy which causes the error. I haven't been able to fix it yet.

**Comment by NikCharlebois** [comment]
This has been fixed with the revamp done in October to leverage Microsoft Graph under the cover. Closing issue.
