### ISSUE TITLE
Typo in MSFT_EXOSafeLinksPolicy breaks export

### ISSUE THREAD

**Issue by ralish** [microsoft/Microsoft365DSC#1367]
Looks to have been introduced a week ago by a clean-up commit. There's an errant `g` character at the end of the closing brace: https://github.com/microsoft/Microsoft365DSC/blob/5752aad5dfc4e4f9dd037d72a81e956d9f7a4b04/Modules/Microsoft365DSC/DSCResources/MSFT_EXOSafeLinksPolicy/MSFT_EXOSafeLinksPolicy.psm1#L473

**Comment by NikCharlebois** [comment]
This has been fixed. Thanks
