### ISSUE TITLE
Export-M365DSCConfiguration does not work with an MFA enable Global Admin Account

### ISSUE THREAD

**Issue by berchouinard** [microsoft/Microsoft365DSC#1371]
Being asked for credentials but MFA does not work.
Using version 1.21.804.1
One or more errors occurred.
Partial Export file was saved at: C:\Users\\AppData\Local\Temp\4e06aa18-e1fe-41c7-bb99-90cc7749c78d.parti
al.ps1.ps1.partial and no file gets saved.

**Comment by desmay** [comment]
@berchouinard What type of tenant is this ? GCC, Commercial etc .

**Comment by berchouinard** [comment]
Commercial.

**Comment by berchouinard** [comment]
This can be closed, misconfiguration with some of the powershell module required by M365DSC.
