### ISSUE TITLE
Error - Start-DSCConfiguration M365TenantConfig -Wait -Verbose -Force

### ISSUE THREAD

**Issue by Perrinw** [microsoft/Microsoft365DSC#1376]
#### Details of the scenario you tried and the problem that is occurring
 running Start-DSCConfiguration M365TenantConfig -Wait -Verbose -Force

#### Verbose logs showing the problem
Start-DSCConfiguration M365TenantConfig -Wait -Verbose -Force
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the destination, 
most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the destination to analyze and configure the WinRM service: "winrm quickconfig".
    + CategoryInfo          : ConnectionError: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : HRESULT 0x80338012
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 9.206 seconds

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by desmay** [comment]
@Perrinw Did you run winrm quickconfig on workstation ?

**Comment by NikCharlebois** [comment]
As mentioned by Derek above, the solution is to do a quick config on WinRM. I will close the issue for the moment, if the problem persists, please re-open it. Thanks
