### ISSUE TITLE
AADConditionalAccessPolicy: Add "All" setting for IncludeRoles and ExcludeRoles

### ISSUE THREAD

**Issue by EricHindrichsen** [microsoft/Microsoft365DSC#1381]
We have several conditional access policies that we want to apply to all Azure AD roles (e.g. to enforce MFA on all privileged accounts) or from which we want to exclude all AAD roles. Currently, this means manually entering all 60-70 roles into the DSC configuration file. And whenever a role gets added or renamed in Azure AD, we need to update the config again.

Now, imagine we could just enter "All" as a value for IncludeRoles and ExcludeRoles in the config. It would always be up to date, regardless of roles being added or renamed. It would always make sure all currently existing AAD roles are set for that config option. And it's the same mechanism already being used for other settings in the same resource.

What do you think?

**Comment by NikCharlebois** [comment]
After further consideration, the implications of M365DSC managing what the ALL list should be is too risky. While we understand it is cumbersome and requires regular check to make sure all values are included, DSC is a representation of how configuration are currently defined, and today that means a list of individual roles to include/exclude.
