### ISSUE TITLE
IntuneDeviceCompliancePolicyWindows10: DefenderEnabled property not implemented in Test-TargetResource

### ISSUE THREAD

**Issue by michaeltlombardi** [microsoft/Microsoft365DSC#1383]
#### Details of the scenario you tried and the problem that is occurring

While attempting to Puppetize the Microsoft365DSC module, I noticed a bug in the `IntuneDeviceCompliancePolicyWindows10` resource; namely that one of the properties marked as `Write` in the schema file is not implemented for `Test-TargetResource` in the accompanying PSM1.

#### Verbose logs showing the problem

> `Microsoft.Management.Infrastructure.CimException`: The command `Test-TargetResource` of the PS module `MSFT_IntuneDeviceCompliancePolicyWindows10` does not implement the write property `DefenderEnabled` mentioned in the corresponding MOF schema file `C:\Users\vagrant\import\microsoft365dsc\lib\puppet_x\microsoft365dsc\dsc_resources\Microsoft365DSC\Dsc Resources\MSFT_IntuneDeviceCompliancePolicyWindows10\MSFT_IntuneDeviceCompliancePolicyWindows10.schema.mof`. All write paramenters mentioned in the schema file must be implemented by the command `Test-TargetResource`.

#### Suggested solution to the issue

Ensure all properties marked `write` in the schema files are implemented in the `Test-TargetResource` and `Set-TargetResource` functions.

#### The operating system the target node is running

```
OsName               : Microsoft Windows Server 2019 Standard Evaluation
OsOperatingSystemSKU : 79
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US
```

#### Version of the DSC module that was used ('dev' if using current dev branch)

`1.21.804.1`

**Comment by NikCharlebois** [comment]
@RuudGijsbers Can you have a look please? Thanks

**Comment by RuudGijsbers** [comment]
@michaeltlombardi I'm looking into it and will update you when I know more
