### ISSUE TITLE
Microsoft-M365DSC: In GCCHigh tenant we are not able to utilize MFA and Authentication for multiple workload doesnt work as expected

### ISSUE THREAD

**Issue by VikramHarshil** [microsoft/Microsoft365DSC#1393]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
While running the export command to extract the configs, we found that GCCHigh tenant 
1. When MFA is enabled the command doesn't work as expected.
 Export-M365DSCConfiguration -Quiet -GlobalAdminAccount $Cred 

2. Authentication with multiple workloads doesn't work, infact it keeps prompting for creds everytime.
 While running the above command someone needs to sit in front of the laptop and keep allowing the concerns and credentials.
```

**Comment by NikCharlebois** [comment]
This has been fixed with today's release (v1.21.908.1). Thanks

**Comment by VikramHarshil** [comment]
Thank you!!

**Comment by VikramHarshil** [comment]
Hello

Below is the update from Microsoft about Microsoft365DSC and it’s fix.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by VikramHarshil** [comment]
***@***.*** Abubakar ***@***.***>

Cheers,

Chidera Idowu | Senior Consultant | Modern Workplace
Ernst & Young LLP
Direct:+1 949 437 0749| ***@***.******@***.***>
From: Chidera Idowu
Sent: Thursday, September 9, 2021 8:09 AM
To: Vikram R Solanki ***@***.***>; Vikram Solanki ***@***.***>; microsoft/Microsoft365DSC ***@***.***>; Denney Packulath ***@***.***>
Subject: RE: [microsoft/Microsoft365DSC] Microsoft-M365DSC: In GCCHigh tenant we are not able to utilize MFA and Authentication for multiple workload doesnt work as expected (#1393)

Hi Vikram,

Thank you for the update. From our last discussion with Nik, the MFA issue was resolved for exports of configurations. Still, they will not be able to resolve the issue when importing configurations for several more months.


Cheers,

Chidera Idowu | Senior Consultant | Modern Workplace
Ernst & Young LLP
Direct:+1 949 437 0749| ***@***.******@***.***>
