### ISSUE TITLE
EXOTransportRule: Add Enabled parameter

### ISSUE THREAD

**Issue by nightshifty** [microsoft/Microsoft365DSC#1396]
### Description
There is no way to check whether a the state Rule is activated, it can only be checked whether the rule exists or not.

### Proposed properties
Boolean Enabled

### Special considerations or limitations
None

**Comment by Swampen** [comment]
The transport rule can be enabled/disabled through different cmdlets: [Enable-TransportRule](https://docs.microsoft.com/en-us/powershell/module/exchange/enable-transportrule?view=exchange-ps) and [Disable-TransportRule](https://docs.microsoft.com/en-us/powershell/module/exchange/disable-transportrule?view=exchange-ps). 
It can probably be implemented into the existing resource.
