### ISSUE TITLE
Add Certificate Thumbprint to Intune (and all other) modules

### ISSUE THREAD

**Issue by AlexJPawlak** [microsoft/Microsoft365DSC#1398]
#### Details of the scenario you tried and the problem that is occurring

Intune modules should support certificate thumbprint authentication

#### Suggested solution to the issue

[MSFT_IntuneDeviceCompliancePolicyWindows10.zip](https://github.com/microsoft/Microsoft365DSC/files/7076166/MSFT_IntuneDeviceCompliancePolicyWindows10.zip)

Attached proposed configuration change to schema and psm1 for Compliance Policy. Contributing guidelines aren't clear - instructions stop at creating .mof I'm unsure though how to compile them to some new test module and test to see if they work. I'm not sure if the changes are good to enable cert authentication, however I looked up different modules to see if they are available, and they are.  

#### Version of the DSC module that was used ('dev' if using current dev branch)

dev

**Comment by RuudGijsbers** [comment]
@AlexJPawlak IThanks. I'll look into it

**Comment by NikCharlebois** [comment]
Done with the standardization of the Intune Workload to leverage Microsoft Graph back in October.
