### ISSUE TITLE
Install-Module MicrosoftDSC : Unable to find dependent module(s) (MicrosoftTeams)

### ISSUE THREAD

**Issue by Stokkies** [microsoft/Microsoft365DSC#1401]
Install-Module Microsoft365DSC -Force -Allowclobber

Error: 
PackageManagement\Install-Package : Unable to find dependent module(s) (MicrosoftTeams)
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MicrosoftTeams:String) [Install-Package], Exception
    + FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by Laskewitz** [comment]
@NikCharlebois I believe 2.5.0 has been pulled. It should be 2.5.1 now.

**Comment by NajNaushahi** [comment]
I have version 2.5.1 MicrosoftTeams module already installed but still getting the same error. Any help would be appreciated.

**Comment by Perrinw** [comment]
I'm having same issue as above.  Tried on two different newly installed W10 vms.  first test was immediately after install- no updates,   2004, b19041.264.  
ive ran Install-Module -Name MicrosoftTeams -requiredversion 2.5.1 and is showing installed

**Comment by MichielBouman** [comment]
I have the same issue. Teams module 2.5.1 is installed but have the error:
PackageManagement\Install-Package : Unable to find dependent module(s) (MicrosoftTeams)
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MicrosoftTeams:String) [Install-Package], Exception
    + FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPack
   age

**Comment by NikCharlebois** [comment]
This was fixed with release 1.21.901.1. Thanks
