### ISSUE TITLE
SCSensitivityLabel Issues with Locales

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#1403]
#### Details of the scenario you tried and the problem that is occurring
All LocaleSettings for the SCSensitivity label need to define the same localizations, however, there are cases where the settings in the setting doesn't define them all. For example, in the following configuration:

```
MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'DisplayName'
                    Settings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'en-us'
                            Value = 'English Display Names'
                        }
                        MSFT_SCLabelSetting
                        {
                            Key   = 'fr-fr'
                            Value = 'Nom da''ffichage francais'
                        }
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Demo label'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'StopColor'
                    Settings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'en-us'
                            Value = 'RedGreen'
                        }
                        MSFT_SCLabelSetting
                        {
                            Key   = 'fr-fr'
                            Value = 'Rouge'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    Settings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Demo tool tip'
                        }
                    )
                }
```

The tooltip setting should also define en-us and fr-fr and the StopColor setting should also define default

#### Verbose logs showing the problem
All locale settings must contain  the same list of localizations but they do not. Localizations detected for each setting: displayname: en-us, default.         tooltip: default           

#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'DisplayName'
                    Settings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'en-us'
                            Value = 'English Display Names'
                        }
                        MSFT_SCLabelSetting
                        {
                            Key   = 'fr-fr'
                            Value = 'Nom da''ffichage francais'
                        }
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Demo label'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'StopColor'
                    Settings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'en-us'
                            Value = 'RedGreen'
                        }
                        MSFT_SCLabelSetting
                        {
                            Key   = 'fr-fr'
                            Value = 'Rouge'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    Settings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Demo tool tip'
                        }
                    )
                }

**Comment by NikCharlebois** [comment]
@desmay any updates on this one. I'm still hitting this on random tenants every now and then.

**Comment by andikrueger** [comment]
@desmay Are there any news on this issue?

**Comment by desmay** [comment]
Sorry Andy keep forgetting about this. Let me try to knock this out this week time permitting

**Comment by NikCharlebois** [comment]
Let's close this one for now. I just ran additional tests, and this is not a situation the tenant should end up in when doing an extract. It would take someone to manually write the config and omit some locales for this to happen.
