### ISSUE TITLE
[ODSettings] Export does not work with MFA enabled Global Admin account

### ISSUE THREAD

**Issue by BChaloupka** [microsoft/Microsoft365DSC#1405]
When using the MFA enabled Global Admin account the Connect-PnPOnline uses parameter, which does not pass credentials and hangs with error "Unable to connect using provided arguments". There is also message provided with advice to use -Interractive parameter for the Connect-PnPOnline. Looks like the connection script was written for older version of PnP module.

**Comment by desmay** [comment]
@BChaloupka  What version are you running. I just tested this with a MFA enabled account version 1.21.804.1 and it worked

**Comment by BChaloupka** [comment]
@desmay I had older version, so that was the problem. Thank you. How did you manage to install the latest version? I'm getting error on two different machines when using Update-Module or Install-Module. In both cases it cannot find the dependent module "MicrosoftTeams". Looks like a bug in the installation script.

**Comment by desmay** [comment]
The MicrosoftTeams 2.5 version was pulled so it caused issues in latest release. Try installing previous release 
`Install-Module -Name Microsoft365DSC -RequiredVersion 1.21.804.1 `

We should have a new release next week to fix issue with MicrosoftTeams issue,

**Comment by BChaloupka** [comment]
@desmay Yeap. That seems to work for now. ;) Thank you.
