### ISSUE TITLE
[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted:  TeamsChannelTab

### ISSUE THREAD

**Issue by Perrinw** [microsoft/Microsoft365DSC#1410]
#### Details of the scenario you tried and the problem that is occurring
Trying to run  Export-M365DSCConfiguration -Quiet -ComponentsToExtract @("TeamsCallingPolicy", "TeamsChannel", "TeamsChannelsPolicy", "TeamsChannelTab", "TeamsClientConfiguration", "TeamsEmergencyCallingPolicy", "TeamsEmergencyCallRoutingPolicy", "TeamsGuestCallingConfiguration", "TeamsGuestMeetingConfiguration", "TeamsGuestMessagingConfiguration", "TeamsMeetingBroadcastConfiguration", "TeamsMeetingBroadcastPolicy", "TeamsMeetingConfiguration", "TeamsMeetingPolicy", "TeamsMessagingPolicy", "TeamsPstnUsage", "TeamsTeam", "TeamsTenantDialPlan", "TeamsUpgradeConfiguration", "TeamsUpgradePolicy", "TeamsUser", "TeamsVoiceRoute", "TeamsVoiceRoutingPolicy") -GlobalAdminAccount $Credentials

Gets error
[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted: 
TeamsChannelTab

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.804.1

**Comment by NikCharlebois** [comment]
TeamsTab is leveraging the Microsoft Graph under the cover, which only supports Service Principal Auth. In order to use it, you will need to provide ApplicationID, TenantId and CertificateThumbprint. Thanks
