### ISSUE TITLE
Session keeps holds of previous Credentials for extraction

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#144]
#### Details of the scenario you tried and the problem that is occurring
logging under Office365DSC but really belongs to MSCloudLoginAssistant. I have two Tenant Admins in the same Tenant. One who doesn't use MFA, the second one who does. If I open a brand new PowerShell Session and do a Tenant Extraction with Extract-O365Configuration (which succeeds), then do a second extraction for the same tenant, within the same PoSh session, but using the credentials of the user with MFA, I never get prompted for MFA auth and the extraction proceeds successfully, most likely using the credentials from the previous Tenant Admin.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Would needs to check for a Hash of the credentials somehow and have MSCloudAssistant figure out that a new set of credentials were provided so that we can clear any cache creds and prompt the new user for MFA Auth.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
N/A

**Comment by NikCharlebois** [comment]
@brianlala FYI

**Comment by brianlala** [comment]
Ugh, new PoSh session, always! But yeah a check would be nice.

**Comment by NikCharlebois** [comment]
Not to be pursued.
