### ISSUE TITLE
IntuneDeviceConfigurationPolicyAndroidWorkProfile

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#1445]
Android enterprise

**Comment by aslan-im** [comment]
Hi Nik! I have added new pull request with IntuneDeviceConfigurationPolicyAndroidWorkProfile resource. Please review it.

**Comment by RuudGijsbers** [comment]
Hi @aslan-im, if you want to create more resources for the Intune part, I think it's good to have a chat somewhere in the coming weeks. I can tell you about the project and its vision and tell something on the way of working.

**Comment by aslan-im** [comment]
HI @RuudGijsbers! Yes, it makes sense. Let me know when it will be convenient for you.
