### ISSUE TITLE
AADApplications: Only the first 100 applications are exported using DSC

### ISSUE THREAD

**Issue by AzizGS** [microsoft/Microsoft365DSC#1446]
#### Details of the scenario you tried and the problem that is occurring
I'm tried to export AAD Applications from my tenant using the command below, I have more than 800 applications:
Export-M365DSCConfiguration -Quiet -ComponentsToExtract @("AADApplication") -GlobalAdminAccount $Credentials

The command will export only the first 100 applications. I didn't find any switch to set the number of apps. 

#### Version of the DSC module that was used ('dev' if using current dev branch)
Tested using : 

+ 1.21.825.1 and 1.21.908.1 (current version) with same results.

**Comment by desmay** [comment]
I have submitted a PR to resolve this issue should be in the next release
