### ISSUE TITLE
MFA support for Export-M365DSCConfiguration 

### ISSUE THREAD

**Issue by micromega-prog** [microsoft/Microsoft365DSC#1456]
Is MFA supported when running Export-M365DSCConfiguration? When I use the -GlobalAdminAccount parameter it only appears to use basic username/password authentication. I end up with the following error:

_Connecting to {AzureAD}...
Connecting to {ExchangeOnline}...Error Acquiring Token:
AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000002-0000-0ff1-ce00-000000000000'.
Trace ID: 287c9b7c-5a1f-4435-a790-a0e691373400
Correlation ID: cf1bf29d-89b3-46d3-8911-b7689f70cb06_

**Comment by desmay** [comment]
@micromega-prog  What type of tenant are you connecting to ? Commercial, GCC etc.

**Comment by micromega-prog** [comment]
commercial.

**Comment by c-s-w** [comment]
The computer I tried MicrosoftDSC to run on is part of an old Active Directory (not linked with M365). Without specifying any user or domain, Export-M365DSCConfiguration tries to query to AD-domain of the PC (which will fail without asking for any other user account).

The solution is to get the credentials for the specific M365 domain:

`$c = Get-Credential -credential admin@tenant123.onmicrosoft.com`

Then run Export-M365DSCConfiguration:

`Export-M365DSCConfiguration -Credential $c`

The MFA will be done later on while the export is running. It's still failing at some later point, but limiting the Workloads works.

**Comment by NikCharlebois** [comment]
@micromega-prog can you confirm that this is still an issue? We've recently released major updates to the module which should have addressed this issue. Thanks
