### ISSUE TITLE
Export to markdown

### ISSUE THREAD

**Issue by martincaddick** [microsoft/Microsoft365DSC#1472]
Is it possible to export the configuration to markdown tables?

Ideally a new function along the lines of New-M365DSCConfigurationToMarkdown where instead of html tables we get markdown tables. Maybe make use of ConvertTo-Markdown from PSScriptTools ?

**Comment by martincaddick** [comment]
I was hoping for something like:
# $templatename
## $resource.resourcename
foreach ($resource in $parsedContent)
  {
   ### $resource.displayname
  |Configuration Item | Configuration Value|
  |:---------------------|:----------------------|
  |  $property              | ($resource.$property).ToString()|
 }

Cheers

**Comment by martincaddick** [comment]
This kinda does it. Definitely not optimised.
--------------

Function PolicyToMarkdownTable
{
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory = $true)]
        [System.String]
        $ConfigurationPath,

        [Parameter(Mandatory = $true)]
        [System.String]
        $Policy,

        [Parameter(Mandatory = $true)]
        [System.String]
        $OutputPath
    )
    $TemplateFile = Get-Item $ConfigurationPath
    $parsedContent = ConvertTo-DSCObject -Path $ConfigurationPath
    $TemplateName = $TemplateFile.Name.Split('.')[0]
    $policyTable = $parsedContent | Where-Object {$_.ResourceName -eq $Policy}

    $text = "## " + $Policy + "`r`n"
    foreach ($tablevalue in $policyTable)
    {
        if($tablevalue.DisplayName){$tableName = $tablevalue.DisplayName}else{$tableName = $tablevalue.Identity}
        $text += "### " + $tableName + "`r`n"
        $text += "|Item|Value|`r`n"
        $text += "|:---|:---|`r`n"
        foreach ($entry in $tablevalue.Keys)
        {
            $text += "|${entry}| $($tablevalue.item($entry))|`r`n"
        }
        $text += "`r`n"
    }
    $text += "`r`n"
    $text | Add-Content -Path $OutputPath
}
rm .\P365Demo.md

$policies = Get-M365DSCAllResources
foreach ($policy in $policies)
{
    PolicyToMarkdownTable -ConfigurationPath .\P365Demo.ps1.txt -Policy $policy -OutputPath .\P365Demo.md
}
-----------

**Comment by NikCharlebois** [comment]
You could implement this very easily by leveraging the DSCParser module. Under the cover, Microsoft365DSC uses the ConvertTo-DSCObject command to convert any .ps1 configuration into a PowerShell Object. We will not be proceeding with implementing this feature directly as part of M365DSC but it should be very straightforward to do. If you are interested in contributing this feature back to the project, we are more than happy to assist. Thanks
