### ISSUE TITLE
IntuneDeviceConfigurationWindows10: Issue with DefenderDetectedMalwareActions property export

### ISSUE THREAD

**Issue by aslan-im** [microsoft/Microsoft365DSC#1479]
#### Details of the scenario you tried and the problem that is occurring
The property DefenderDetectedMalwareActions exports wrong. 
#1413 

#### Verbose logs showing the problem
That's what has been exported to the file
DefenderDetectedMalwareActions  = System.Collections.Generic.Dictionary`2[System.String,System.Object];
#### Suggested solution to the issue
Edit Export-TargetResource function in IntuneDeviceConfigurationWindows resource
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
#Export-M365DSCConfiguration -Quiet -GlobalAdminAccount $Credentials -Path .\ -FileName Intune.ps1 -ComponentsToExtract  @("IntuneDeviceConfigurationPolicyWindows10")
```
That's what should be exported:
```powershell
$policy.AdditionalProperties.defenderDetectedMalwareActions

Key              Value
---              -----
lowSeverity      quarantine
moderateSeverity quarantine
highSeverity     remove
severeSeverity   remove
```
#### The operating system the target node is running
OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
 1.21.922.1

**Comment by aslan-im** [comment]
Hello @MySimpleCode! Could you please look at this?

**Comment by andikrueger** [comment]
@aslan-im Is this still an issue?
