### ISSUE TITLE
ApplicationSecret is not being passed

### ISSUE THREAD

**Issue by austinkschmitz** [microsoft/Microsoft365DSC#1480]
#### Details of the scenario you tried and the problem that is occurring
Ran Export-M365DSCConfiguration on a new shell - receive unexpected error
Ran Export-M365DSCConfiguration on a shell with me logged in as GA - same error.

#### Verbose logs showing the problem
$InboundParameters output missing "ApplicationSecret" key
In Shell with -Verbose:
VERBOSE:
Name               Value
' ----                     ------ '
TenantID            <tenant>.onmicrosoft.com
ApplicationId      <GUID>

#### Suggested solution to the issue
Breadcrumbs show that New-M365DSCConnection function is not receiving ApplicationSecret in the hashtable.
If I hardcode my ApplicationSecret into line: 1056 then I will not get error "Unexpected error getting the Authentication Method."
The return is an empty configuration. I do not know if this is related to the export or issue with API settings. But With Credentials returns full configuration. 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Export-M365DSCConfiguration -Quiet -ComponentsToExtract @("AADConditionalAccessPolicy") -ApplicationId $ApplicationId -ApplicationSecret $ApplicationSecret -TenantId $TenantId
```

#### The operating system the target node is running

MS Windows 10 Ent
EnterpriseEdition
64-bit
WindowsVS: 2009
19041.1.amd64fre.vb_release.191206-1406
en-US

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.922.1

**Comment by RuudGijsbers** [comment]
Hi @austinkschmitz, can you check which version you have of the MSCloudLoginAssistant module? That module had that in the past, which was fixed in a later version. 

If you use Install-Module Microsoft365DSC -Force -AllowClobber, it will automatically try to update al related modules to the requires versions
