### ISSUE TITLE
Power Apps logo for Power Platform resources is missing

### ISSUE THREAD

**Issue by Laskewitz** [microsoft/Microsoft365DSC#1481]
![image](https://user-images.githubusercontent.com/3766843/135721942-f3631732-74d8-4bea-ba2f-fdfb66560dcb.png)

It points to the following link, http://microsoft365dsc.com/Images/PowerApps.jpg, which is indeed missing.

@NikCharlebois if you need the new icon - let me know.

**Comment by NikCharlebois** [comment]
@Laskewitz Can you look into this and add the icon back to the package? Thanks
