### ISSUE TITLE
Import certificate into store error incorrect parameter

### ISSUE THREAD

**Issue by platfo106** [microsoft/Microsoft365DSC#1497]
Hi,

Has anyone encountered this previously while importing certificate? 

Microsoft365DSC version: 1.21.1006.3

2021-10-12T02:08:55.0806343Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\agent\vsts-agent-win-x64-2.193.0\_work\_temp\8c8d864f-8b75-4f27-99f0-7a5e1fe6e51d.ps1'"
2021-10-12T02:08:55.5237399Z 2021-10-12 02:08:55 - Import certificate into store
2021-10-12T02:08:55.8033305Z ##[error]Exception calling "Import" with "3" argument(s): "The parameter is incorrect.
"
At C:\agent\vsts-agent-win-x64-2.193.0\_work\r2\a\_Microsoft365DSC (1)\deploypackage\deploy_cert.ps1:17 char:1
+ $certCollection.Import($kvSecretBytes, $null, [System.Security.Crypto ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CryptographicException
2021-10-12T02:08:55.8083223Z ##[error]PowerShell exited with code '1'.

Just started with the Azure DevOps, so likely I might have missed something, please let me know if I can provide any further information or if this is expected bug?

I have followed the instruction via the [whitepaper](https://microsoft365dsc.com/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf):

**Comment by andikrueger** [comment]
@ykuijs Could you help with this error?

**Comment by NikCharlebois** [comment]
This error happens after executing what command exactly? Sorry it's not clear to me based on the log what command is causing the issue and if it's even related to Microsoft365DSC. Thanks

**Comment by NunoFilipeMota** [comment]
Hi @NikCharlebois. Yes, this is related to Microsoft365DSC. I am having the exact same error. This happens when the release pipeline runs "deploy_cert.ps1"

**Comment by DEppersonMSE** [comment]
I am also getting this error in the same place.  Has their been any traction or has anyone been able to figure this out?

**Comment by andikrueger** [comment]
Actually not. Could you create a new issue with this topic and additional details? Are you using the latest whitepaper?

**Comment by DEppersonMSE** [comment]
I am using the latest.  For some reason my certs didn't get put in my keyvault but the passwords did.  I think that's my challenge for this error.
