### ISSUE TITLE
MicrosoftGraph: PowerShell 5.1 CertificatePassword argument transformation fails

### ISSUE THREAD

**Issue by pl4nty** [microsoft/Microsoft365DSC#1500]
### Details of the scenario you tried and the problem that is occurring
`Export-M365DSCConfiguration` fails in PowerShell 5.1 with an argument transformation error when using `CertificatePassword` authentication.

### Verbose logs showing the problem
```PowerShell
Export-M365DSCConfiguration
    -TenantId <TenantId>
    -ApplicationId <ApplicationId>
    -CertificatePath <CertificatePath>
    -CertificatePassword <CertificatePassword:System.Management.Automation.PSCredential>
    -Components @("IntuneAppConfigurationPolicy")
```
```
Connecting to {MicrosoftGraph}...❌
Cannot process argument transformation on parameter 'CertificatePassword'. Cannot convert the "System.Management.Automation.PSCredential" value of type "System.Management.Automation.PSCredential" to type "System.Security.SecureString".
```

### Suggested solution to the issue
Microsoft365DSC passes a PSCredential here: 
https://github.com/microsoft/Microsoft365DSC/blob/3a76cb8b46747ef8081ecf8f56bd0036790172d1/Modules/Microsoft365DSC/Modules/M365DSCReverse.psm1#L68-L70
https://github.com/microsoft/Microsoft365DSC/blob/3a76cb8b46747ef8081ecf8f56bd0036790172d1/Modules/Microsoft365DSC/Modules/M365DSCReverse.psm1#L440-L450
https://github.com/microsoft/Microsoft365DSC/blob/e2c3ebc7abeab0f9a36089d56f5d9129da3d1b83/Modules/Microsoft365DSC/Modules/M365DSCReverse.psm1#L453

`Connect-M365Tenant` in MSCloudLoginAssistant consumes a SecureString here: 
https://github.com/microsoft/MSCloudLoginAssistant/blob/4430909f6b61ef44b342e35346781168c9ad3257/Modules/MSCloudLoginAssistant/MSCloudLoginAssistant.psm1#L128-L130

```PowerShell
[Parameter()]
[SecureString]
$CertificatePassword,
```

Microsoft365DSC should accept and pass a SecureString, as the username component of PSCredential is unused.

### The DSC configuration that is used to reproduce the issue (as detailed as possible)
See logs above.

### The operating system the target node is running

OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB}

### Version of the DSC module that was used ('dev' if using current dev branch)
Latest prod (Release 1.21.1006.3)

**Comment by NikCharlebois** [comment]
Currently, CertificatePassword is being handled as a PSCredential. It is a bit overkill since all we really need is the password piece of the PScredential object and that the username could be anything really. Changing this would however result in a breaking change. 

In summary, yes, CertificatePassword should be a SecureString instead of a PSCredential object, but we need to wait for a major release in order to make this change happen. In the meantime, please ensure to use a PSCredential object.
https://github.com/microsoft/Microsoft365DSC/wiki/Breaking-Changes-Policy

**Comment by pl4nty** [comment]
Should MSCloudLoginAssistant be updated to consume a PSCredential instead?

**Comment by NikCharlebois** [comment]
Yes, we will also have to update it.
