### ISSUE TITLE
The remote server returned an error: (404) Not Found

### ISSUE THREAD

**Issue by ranabanerjee15** [microsoft/Microsoft365DSC#1508]
I am Trying to Extract the config as follows, but it fails with error. I am also not getting prompted for MFA (my account has MFA)

Am I missing any instructions?

The remote server returned an error: (404) Not Found

```PowerShell

$workloads = @(
    'EXO'
    'O365'
    'OD'
    'PP'
    'SC'
    'SPO'
    'Teams'
)

Export-M365DSCConfiguration -Workloads $workloads -TenantId '617d181f-95d9-4010-b7f1-25430f5fe369'

```

**Comment by raband-cdw** [comment]
I am receiving a similar issue just attempting to run "Export-M365DSCConfiguration" using the Module that I installed this morning.  Screenshot attached for your review.

I had this issue on 2 separate machines.

![Capture11-26](https://user-images.githubusercontent.com/62358395/143619274-a67e0ba1-3055-4846-88a8-3c6fbc1c3b3e.PNG)

Any recommendations on how to proceed?

**Comment by NikCharlebois** [comment]
I would recommend you always pass in the -Credential parameter to Export-M365DSCConfiguration.

`$creds = Get-Credential
Export-M365DSCConfiguration -Credentil $creds`
