### ISSUE TITLE
AADGroupSettings: Add support for "GroupCreationAllowedGroupId"

### ISSUE THREAD

**Issue by andikrueger** [microsoft/Microsoft365DSC#1509]
### Discussed in https://github.com/microsoft/Microsoft365DSC/discussions/1336

<div type='discussions-op-text'>

<sup>Originally posted by **Shima-MSP** July 23, 2021</sup>

2. We also restrict who can create Office 365 Groups, so that only certain people are allowed to create Sharepoint sites, Teams etc

We do this by running the following script, will these be included in the export, and if so what kind of checkbox does these adhere to?

$GroupName = "M365_Groupcontrol_User"
$AllowGroupCreation = $False

Connect-AzureAD

$settingsObjectID = (Get-AzureADDirectorySetting | Where-object -Property Displayname -Value "Group.Unified" -EQ).id
if(!$settingsObjectID)
{
    $template = Get-AzureADDirectorySettingTemplate | Where-object {$_.displayname -eq "group.unified"}
    $settingsCopy = $template.CreateDirectorySetting()
    New-AzureADDirectorySetting -DirectorySetting $settingsCopy
    $settingsObjectID = (Get-AzureADDirectorySetting | Where-object -Property Displayname -Value "Group.Unified" -EQ).id
}

$settingsCopy = Get-AzureADDirectorySetting -Id $settingsObjectID
$settingsCopy["EnableGroupCreation"] = $AllowGroupCreation

if($GroupName)
{
  $settingsCopy["GroupCreationAllowedGroupId"] = (Get-AzureADGroup -SearchString $GroupName).objectid
}
 else {
$settingsCopy["GroupCreationAllowedGroupId"] = $GroupName
}
Set-AzureADDirectorySetting -Id $settingsObjectID -DirectorySetting $settingsCopy

(Get-AzureADDirectorySetting -Id $settingsObjectID).Values
</div>

Currently `AADGroupSettings` does not expose the property `GroupCreationAllowedGroupId`. This property is needed to restrict group creation to only certain members for the tenant.

**Comment by NikCharlebois** [comment]
@andikrueger we actually expose a property called GroupCreationAllowedGroupName instead which maps to the name of the group instead of the ID. This is in order for us to support cloning tenants. I will close for the moment but let me know if this is not sufficient for your scenario. Thanks
