### ISSUE TITLE
MSFT_IntuneDeviceCompliancePolicyWindows10: Property name conversion to Graph API error 

### ISSUE THREAD

**Issue by daniel-huf** [microsoft/Microsoft365DSC#1510]
#### Details of the scenario you tried and the problem that is occurring
Tried to configure intune device compliance policy using Microsoft Graph beta version. Unable to set properties "rtpEnabled" and "tpmRequired". 
We modified the DSC Resource to access Graph beta version by following the suggestion on discussion #1506
#### Verbose logs showing the problem

["The property 'tPMRequired' does not exist on type 'microsoft.management.services.api.windows10CompliancePolicy'. Make sure to only use property names that are defined by the type.", [...]

#### Suggested solution to the issue

Rename variables: TPMRequired -> tpmRequired/TpmRequired

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
IntuneDeviceCompliancePolicyWindows10 TestPolicy
{
            DisplayName    = "Windows 10 DSC Policy";
            Description       = "Test policy";
            TPMRequired    = $True;
            RTPEnabled       = $True;
}
```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : de-DE
OsMuiLanguages       : {de-DE, en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.1013.1 with modification as mentioned above

**Comment by NikCharlebois** [comment]
@daniel-huf can you confirm if you are still getting this isse with the latest versions of the module? We released a major version back in November and completely refactored the Intune workload. Thanks
