### ISSUE TITLE
Beta MgProfile commandlets testing

### ISSUE THREAD

**Issue by aslan-im** [microsoft/Microsoft365DSC#1515]
Hello everyone! Is there a way to test DSC resources that use commandlets from beta MgProfile?
I have  noticed that some commandlets from Graph module are not available without Select-MgProfile Beta. The main thing is that if you add Select-MgProfile to the BeforeAll in tests, beta commandlets are not available. They will be available only after the second iteration of the tests.
Tests output example:
1st run:
[-] Describe DSC Resource 'AADWindowsAutopilotDeploymentProfile' failed
 CommandNotFoundException: Could not find Command New-MgDeviceManagementWindowAutopilotDeploymentProfile
Tests Passed: 0, Failed: 11, Skipped: 0 NotRun: 0
BeforeAll \ AfterAll failed: 1
  - DSC Resource 'AADWindowsAutopilotDeploymentProfile'

2nd run:
[+] Microsoft365DSC.AADWindowsAutopilotDeploymentProfile.Tests.ps1 22.47s (20.32s|358ms)
Tests completed in 22.48s
Tests Passed: 11, Failed: 0, Skipped: 0 NotRun: 0
I have tried to add it to BeforeAll, before BeforeAll - didn't help.

**Comment by NikCharlebois** [comment]
Stubs generator only generates stubs for cmdlets that are used in code. It has been updated to include the beta endpoints.
