### ISSUE TITLE
SPO authentication issue with username/password method

### ISSUE THREAD

**Issue by anpiskai** [microsoft/Microsoft365DSC#1522]
Testing after the 10/27 M365 DSC build, I receive two error patterns for all SPO resources I've tried.

The first is like the one below during the Get step:

> Device code terminal timed-out after 120 seconds. Please try again.
> 2021-11-01T13:15:13.6383378Z     + CategoryInfo          : NotSpecified: (:) [], CimException
> 2021-11-01T13:15:13.6427209Z     + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectMgGraph
> 2021-11-01T13:15:13.6428359Z     + PSComputerName        : localhost
> 2021-11-01T13:15:13.6428975Z  
> 2021-11-01T13:15:13.6429526Z Authentication needed, call Connect-MgGraph.
> 2021-11-01T13:15:13.6430377Z     + CategoryInfo          : NotSpecified: (:) [], CimException
> 2021-11-01T13:15:13.6431382Z     + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgDomain_List1
> 2021-11-01T13:15:13.6432200Z     + PSComputerName        : localhost
> 2021-11-01T13:15:13.6432786Z  
> 2021-11-01T13:15:13.9000020Z Exception setting "Connect": "Cannot set the Value property for PSMemberInfo object of type 
> 2021-11-01T13:15:13.9000701Z "System.Management.Automation.PSMethod"."
> 2021-11-01T13:15:13.9001087Z     + CategoryInfo          : NotSpecified: (:) [], CimException
> 2021-11-01T13:15:13.9001496Z     + FullyQualifiedErrorId : ExceptionWhenSetting,Connect-MSCloudLoginPnP
> 2021-11-01T13:15:13.9001880Z     + PSComputerName        : localhost
> 2021-11-01T13:15:13.9002131Z  
> 2021-11-01T13:15:15.1412423Z VERBOSE: [fv-az122-319]:                            [[SPOAccessControlSettings]8d2cbe86-8e49-4d75-ac7f-e2edaef6eba0] 
> 2021-11-01T13:15:15.1413182Z There is currently no connection yet. Use Connect-PnPOnline to connect.

It does appear to retrieve the current values somehow, but then the Test-TargetResource command fails with this second error:

> The PowerShell DSC resource '[SPOAccessControlSettings]8d2cbe86-8e49-4d75-ac7f-e2edaef6eba0' with SourceInfo 
2021-11-01T13:15:15.8171242Z 'D:\a\1\s\SPOM365DSC.ps1::33::9::SPOAccessControlSettings' threw one or more non-terminating errors while running the 
2021-11-01T13:15:15.8171870Z Test-TargetResource functionality. These errors are logged to the ETW channel called 
2021-11-01T13:15:15.8172417Z Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
2021-11-01T13:15:15.8172916Z     + CategoryInfo          : InvalidOperation: (:) [], CimException
2021-11-01T13:15:15.8173427Z     + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
2021-11-01T13:15:15.8173927Z     + PSComputerName        : localhost

**Comment by anpiskai** [comment]
I'm still seeing issues with connections to SPO since at least the 10/27 build

**Comment by NikCharlebois** [comment]
@anpiskai this should be fixed in one of the recent versions. Can you please confirm that it is now working if you upgrade to the latest build? Thanks
