### ISSUE TITLE
Examples missing for resources

### ISSUE THREAD

**Issue by ykuijs** [microsoft/Microsoft365DSC#1530]
The following resource do not have examples:
- EXOActiveSyncDeviceAccessRule
- EXOAddressBookPolicy
- EXOApplicationAccessPolicy
- EXOAvailabilityAddressSpace
- EXOAvailabilityConfig
- EXOGlobalAddressList
- EXOHostedContentFilterRule
- EXOHostedOutboundSpamFilterRule
- EXOInboundConnector
- EXOIntraOrganizationConnector
- EXOMalwareFilterRule
~~- EXOOfflineAddressBook~~
- EXOOnPremisesOrganization
- EXOOrganizationRelationship
- EXOOutboundConnector
- EXOPartnerApplication
- EXOPolicyTipConfig
- EXOSafeAttachmentPolicy
- EXOSafeAttachmentRule
- EXOSafeLinksPolicy
- EXOSafeLinksRule
- EXOTransportRule
- SCDeviceConditionalAccessPolicy
- SCDeviceConfigurationPolicy
- SPOSiteScript

We need to add examples for these resource, so they can be automatically tested via the integration test

**Comment by NikCharlebois** [comment]
@ykuijs Let's brainstorm together and try to see how we can automatically generate those instead of always having to create them or keep them in sync with changes to the resource. Maybe this is a great opportunity to leverage our new Dynamic Resource Generator?

**Comment by andikrueger** [comment]
Wouldn't it be an option to auto-generate these examples by using the Export-Microsoft365DSC cmdLet? 

The challenge with the dynamic resource generator would be to have sample data for the configuration available. If we would get sample data through any graph endpoint, we could make this happen. @peombwa do you have a idea on how we could obtain sample data from the graph sdk?

**Comment by peombwa** [comment]
@andikrueger, you can try https://developer.microsoft.com/en-us/microsoft-365/dev-program. With the dev program, you get a free Microsoft 365 E5 developer subscription sandbox with pre-provisioned data for users, mail & events, Teams, and SharePoint. I'm not aware of any other sample data source other than the dev program.

**Comment by andikrueger** [comment]
Good idea. It could be worth to run a test.
From my experience these tenants have a basic configuration - the resources above are very specific and are mostly used in complex scenarios.

**Comment by ykuijs** [comment]
PR #1927 added examples for EXOManagementRole, EXOMobileDeviceMailboxPolicy and EXOOfflineAddressBook

**Comment by ykuijs** [comment]
Just submitted PR that adds all missing examples and a cmdlet that is able to generate missing examples: `New-M365DSCMissingResourcesExample`
