### ISSUE TITLE
[AADConditionalAccessPolicy]: Cannot export AAD Conditional Access policies using a Registered APP 

### ISSUE THREAD

**Issue by AzizGS** [microsoft/Microsoft365DSC#1531]
#### Details of the scenario you tried and the problem that is occurring

I'm trying to export my tenant configuration using M365DSC and a registered application for authentication. 

#### Verbose logs showing the problem

> VERBOSE: ApplicationId, TenantId, ApplicationSecret were specified. Connecting via Service Principal
Get-MgIdentityConditionalAccessPolicy : Applications without a signed-in user are not allowed access to this report or data.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.21.1013.1\DSCResources\MSFT_AADConditionalAccessPolicy\MSFT_AADConditionalAccessPolicy.psm1:1909 char:9
 [array] $Policies = Get-MgIdentityConditionalAccessPolicy
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType3`8) [Get-MgIdentityC...essPolicy_List1], RestException`1
     FullyQualifiedErrorId : AccessDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgIdentityConditionalAccessPolicy_List1


#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# # Generated by Microsoft365DSC from https://export-preview.microsoft365dsc.com on 11/4/2021, 8:28:37 PM
# Visit https://microsoft365dsc.com for more information

# Getting application information for Application + Secret authentication
$ApplicationId = Read-Host -Prompt 'Application Id'
$ApplicationSecret = Read-Host -Prompt 'Application Secret'
$TenantId = Read-Host -Prompt 'Tenant Id'

# Exporting resources using application
Export-M365DSCConfiguration -Components @("AADApplication", "AADConditionalAccessPolicy", "AADGroup", "AADGroupLifecyclePolicy", "AADGroupsNamingPolicy", "AADGroupsSettings", "AADNamedLocationPolicy", "AADRoleDefinition", "AADServicePrincipal", "AADTenantDetails", "AADTokenLifetimePolicy") -ApplicationId $ApplicationId -ApplicationSecret $ApplicationSecret -TenantId $TenantId
```


#### Version of the DSC module that was used ('dev' if using current dev branch)

Latest 1.21.1103.1

**Comment by aflopex** [comment]
I have the exact same issue with the same module version

**Comment by MattWhite-personal** [comment]
Have you made sure that you have granted admin consent for your App Registration using the consent defined here - https://github.com/microsoft/Microsoft365DSC/wiki/AADConditionalAccessPolicy#azure-ad-permissions

**Comment by NikCharlebois** [comment]
As @MattWhite-personal mentioned, make sure you granted your App the required permissions. You can identify the required permission for any resource by running the following:

Get-M365DSCCompiledPermissionList -ResourceNameList AADConditionalAccessPolicy

**Comment by AzizGS** [comment]
Thank you all for the answers. 

The issue persists event after assigning all the listed permissions to the application. 

![image](https://user-images.githubusercontent.com/18143019/147884100-6f76416a-5d17-4bc5-9437-4f8ebc7d00c0.png)

![image](https://user-images.githubusercontent.com/18143019/147884147-9700b3af-5403-4670-9ad0-111f9104780b.png)
