### ISSUE TITLE
Consent for MgGraphPowerShell

### ISSUE THREAD

**Issue by nromyn** [microsoft/Microsoft365DSC#1532]
I'm in the very early stages of playing around with this. Looks like a great tool.

If the tenant has not consented to the MGPowershell Service Principal in their tenant, Export-M365DSCConfiguration fails in a fairly ungraceful manner:
![image](https://user-images.githubusercontent.com/13968908/140419520-c10b4541-4aad-43dc-9dd2-4750427ce8ab.png)

I ran Connect-MgGraph -scopes Directory.Read.All and it continued; evidently there's another scope for Conditional Access, and I expect some more. I took a quick look at the code but I can't find anything obvious.

**Comment by MattWhite-personal** [comment]
Have a look at the docs pages for the Export and Automate Conditional Access it will show you what you need to add into your scopes for connect-mggraph

I have noticed that the Automate permissions fail when using the Admin Creds but I too took some time to get this right

https://github.com/microsoft/Microsoft365DSC/wiki/AADConditionalAccessPolicy#azure-ad-permissions

**Comment by NikCharlebois** [comment]
As @MattWhite-personal points out, the documentation for the resources should indicate what scopes are required. Please let us know if granting access to these scopes solves your issue. Thanks
