### ISSUE TITLE
TransportRule Test-TargetResource error with "Enabled" parameter missing

### ISSUE THREAD

**Issue by anpiskai** [microsoft/Microsoft365DSC#1539]
When I try to run a command to apply an Exchange Online Transport Rule, I receive an error that says that Test-TargetResource has not implemented the "Enabled" parameter and is required. Looking in the resource definition, I can confirm Enabled is present for Set-TargetResource, but not for Test-Target Resource.

![image](https://user-images.githubusercontent.com/48796638/140774638-72e1eb16-5bec-4507-8bca-e1fe02aab1bd.png)

![image](https://user-images.githubusercontent.com/48796638/140774718-ecdfbda0-556f-4b06-a622-d2d687e30008.png)

**Comment by anpiskai** [comment]
This is the full error:

> 
> The command Test-TargetResource of the PS module MSFT_EXOTransportRule does not implement the write property Enabled
> mentioned in the corresponding MOF schema file C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.21.1027.1\D
> scResources\MSFT_EXOTransportRule\MSFT_EXOTransportRule.schema.mof. All write paramenters mentioned in the schema file
> must be implemented by the command Test-TargetResource.
>     + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
>     + FullyQualifiedErrorId : WriteParameterNotImplemented
>     + PSComputerName        : localhost

**Comment by NikCharlebois** [comment]
Fixed in a recent release
