### ISSUE TITLE
404 on the public homepage

### ISSUE THREAD

**Issue by ArgonPulse** [microsoft/Microsoft365DSC#1549]
http://microsoft365dsc.com/ is showing a 404. Seems like the Github connected page is not there anymore.

![image](https://user-images.githubusercontent.com/93916639/141284569-5765bc52-c35e-4714-aa10-f1f7e7883f8e.png)

**Comment by NikCharlebois** [comment]
There was an erronous GitHub Action clearing the CNAME when deploying to master. This has now been fixed. Thanks
