### ISSUE TITLE
Website Navigation menu too narrow

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#1552]
@Laskewitz @RickVanRousselt @stephanbisser 
Some of our resources' names are very long as you know. This is causing the navigation menu of the resource section not to show the entire resource name and makes it very hard to find information for the resource we want (see screenshot)
![image](https://user-images.githubusercontent.com/2547149/141319422-e7c47c50-21be-4245-99b1-baa5a0a34682.png)
How can we address this? Thanks

**Comment by Markus-Hanisch** [comment]
@NikCharlebois @Laskewitz @RickVanRousselt @stephanbisser
The material theme offers the possibility to customize the [content area width](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#content-area-width) by means of css and add this stylesheet to the yaml pipeline.
Unanswered question is if the same possibilities are available for the navigation area width.

**Comment by NikCharlebois** [comment]
@Laskewitz would this be something you would have time to look into?

**Comment by Laskewitz** [comment]
Sure! I'll look into it this weekend.
