### ISSUE TITLE
New-M365DSCDeltaReport Not Responding and Failing

### ISSUE THREAD

**Issue by aflopex** [microsoft/Microsoft365DSC#1558]
#### Details of the scenario you tried and the problem that is occurring
Running New-M365DSCDeltaReport to compare two configuration files does not work. The PowerShell windows just freezes executing the script and does not respond at all. I have tried this on two separate machines with the same result. There is no time-out or error message. PS just simply sits there executing the commands indefinitely, i left it running and had to kill the process after 4 hours of unresponsiveness. I have restarted both of the different machines in which this is being run. This was working fine before I updated to ver 1.21.1103.1 of the module.
#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/50927492/142069632-4da5e03e-2703-4fb7-98ca-fb101c672588.png)
![image](https://user-images.githubusercontent.com/50927492/142069682-c3b7df9b-6db7-47e2-bf3e-435a7046981b.png)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
New-M365DSCDeltaReport -Source .\PL_TenantBaseAzureAD_20210715.ps1 -Destination .\PL_TenantBaseAzureAD_20211004.ps1 -OutputPath Q3AAD.htm

#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

    Get-ComputerInfo -Property @(
        'OsName',
        'OsOperatingSystemSKU',
        'OSArchitecture',
        'WindowsVersion',
        'WindowsBuildLabEx',
        'OsLanguage',
        'OsMuiLanguages')
-->
![image](https://user-images.githubusercontent.com/50927492/142069911-c0bee7f8-e0c3-4aca-bea8-8157912ca341.png)


#### Version of the DSC module that was used ('dev' if using current dev branch)
Version           : 1.21.1103.1

**Comment by NikCharlebois** [comment]
You need to make sure that the version specified in BOTH configuration file by the Import-DSCResource command is the same, and is installed on the machine doing the delta analysis. To be on the safe side, you can always make both configurations version agnostic be removing the ModuleVersion parameter.

E.g.

Convert them from:
Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.21.1124.2'

To:
Import-DscResource -ModuleName 'Microsoft365DSC'

**Comment by aflopex** [comment]
HI Nik, I tried what you suggested with two files. I updated all of them to match my currently installed module version 1.21.1103.1 as you can see below however I need to understand what will happen every time that the module is updated on my DSC machine, will i have to go back to each single config file and update the version? I know you suggested making them agnostic by removing the ModuleVersion parameter however if i do that wouldn't I still have the ModuleVersion parameter on every new config file going forward and still have to edit config files manually? Is there a way to have the Export-M365DSCConfiguration omit the -ModuileVersion when creating config files?
![image](https://user-images.githubusercontent.com/50927492/144290945-23e81079-24e0-4b2c-9ad7-33789caabd12.png)
