### ISSUE TITLE
Export-M365DSCConfiguration in Windows Agent

### ISSUE THREAD

**Issue by adispoerri** [microsoft/Microsoft365DSC#1559]
#### Code-Example:

$SPPComponents          = @("SPOAccessControlSettings")

Export-M365DSCConfiguration -Credential $cliCreds -Components $SPPComponents -Filename $strExportFileName -Path $RootReports

... runs fine on a local Machine, but not in a Windows Agent (Azure Devops Pipeline). Other Components (AAD-Stuff) works without any Problems and I run the command with the same Account.

**DevOps-Output:**

*Connecting to {PnP}...*

--> and nothing happens

#### Version of the DSC module that was used 

1.21.1110.1

**Comment by NikCharlebois** [comment]
What seems to be the error? Do you have any error text you can share? Tagging @ykuijs along to help out.

**Comment by adispoerri** [comment]
aber consenting the "PnP Management Shell" it seems to work now
