### ISSUE TITLE
Managing Microsoft 365 in true DevOps style with Microsoft365Dsc and Azure DevOps

### ISSUE THREAD

**Issue by aslan-im** [microsoft/Microsoft365DSC#1560]
Hello everyone! 
Before the microsoft365dsc.com site design update, there was available the article with instructions how to configure Azure DevOps to use it with M365DSC. Seems it disappeared after the update. 
Could you please clarify, where I can find the article?

**Comment by RuudGijsbers** [comment]
Hi Aslan, you can find it [here](https://microsoft365dsc.com/about/community-resources/)

**Comment by aslan-im** [comment]
Thank you @RuudGijsbers!
