### ISSUE TITLE
AADNamedLocationPolicy : 1042: Unexpected type: namedLocationType for NamedLocations. Supported types are IpNamedLocation, CountryNamedLocation and PrivateLinkNamedLocation

### ISSUE THREAD

**Issue by LeroyJDS** [microsoft/Microsoft365DSC#1561]
Hello Guys,

Got some problems with importing some configuration.
I use the tool https://export.microsoft365dsc.com to create a template for exporting a existent to a new Tenant.
After troubelshooting the Export is working now but got some problems with importing.

Try to make a AADNamedLocationPolicy but get error and don't know how to solve this one:

1042: Unexpected type: namedLocationType for NamedLocations. Supported types are IpNamedLocation, CountryNamedLocation
and PrivateLinkNamedLocation. For examples, please see API documentation at https://docs.microsoft.com/en-us/graph/api/
conditionalaccessroot-post-namedlocations?view=graph-rest-1.0.
    + CategoryInfo          : InvalidOperation: ({ body = Micros...NamedLocation }:) [], CimException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Graph.PowerShell.Cmdlets.NewMgIdentityConditionalAccessNamedLocatio
   n_CreateExpanded1
    + PSComputerName        : localhost

And

The PowerShell DSC resource '[AADNamedLocationPolicy]Block Country' with SourceInfo 'C:\Export\AD - kopie\M365TenantC
onfig.ps1::34::9::AADNamedLocationPolicy' threw one or more non-terminating errors while running the Set-TargetResource
 functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this chan
nel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

This is the code i use to create a .mof

```
# Generated with Microsoft365DSC version 1.21.1110.1
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $Credential
)

Configuration M365TenantConfig
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $Credential
    )

    if ($null -eq $Credential)
    {
        <# Credentials #>
        $Credscredential = Get-Credential -Message "Credentials"

    }
    else
    {
        $CredsCredential = $Credential
    }

    $OrganizationName = $CredsCredential.UserName.Split('@')[1]
    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.21.1110.1'

    Node localhost
    {
        
        AADNamedLocationPolicy 'Block Country'
        {
            CountriesAndRegions               = @("RU","KP","CN","BY","AF");
            Credential                        = $Credscredential;
            DisplayName                       = "Block Country";
            Ensure                            = "Present";
            IncludeUnknownCountriesAndRegions = $False;
            OdataType                         = "#microsoft.graph.countryNamedLocation";
        }
        
        AADNamedLocationPolicy 'AllowedCountries'
        {
            CountriesAndRegions               = @("GH", "AX", "DZ", "AI", "AM")
            DisplayName                       = "Allowed Countries"
            IncludeUnknownCountriesAndRegions = $False
            OdataType                         = "#microsoft.graph.countryNamedLocation"
            Ensure                            = "Present"
            Credential                        = $Credscredential;
        }

    }
}
M365TenantConfig -ConfigurationData .\ConfigurationData.psd1 -Credential $Credential
```

**Comment by NikCharlebois** [comment]
Fixed in a recent release. Please update to the latest version of the solution.
