### ISSUE TITLE
Security and Compliance settings - SCLabelPolicy workload

### ISSUE THREAD

**Issue by mike-pshell** [microsoft/Microsoft365DSC#1573]
Wondering if there are any plans to include the "Auto-labelling" policies as part of this tool?
![image](https://user-images.githubusercontent.com/78377887/142685800-a48b15fb-8e7c-4e15-9dac-a802c9c70602.png)

**Comment by desmay** [comment]
@NikCharlebois I started this months ago your welcome to use it as starting point, just don't have cycles to finish it up. There is a label policy and label rule that is needed. https://github.com/desmay/Microsoft365DSC/tree/SCAutoLabelPolicy/Modules/Microsoft365DSC/DSCResources
