### ISSUE TITLE
Relationship to Compliance Configuration Analyzer

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#1603]
How does the functionality provided by M365 DSC compare to that provided by the Compliance Analyzer at https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-mcca?view=o365-worldwide? would it make sense to  get that tools functionality added to M365 DSC?

**Comment by NikCharlebois** [comment]
M365DSC can be used to assess tenants against another configure. Not sure how we could be adding the MCCA to M365DSC however. Did you have anything specific in mind with regards to the integration?

**Comment by DeanGross** [comment]
I was thinking that since M365 DSC provides a very comprehensive report of the configuration settings that it might be helpful if there was an option to include the data that the Compliance Analyzer generates so that all of the data was in one file.  For example DSC does not include anything about Insider Risk which is a gap that could be filled by the MCCA code base.

**Comment by NikCharlebois** [comment]
I honestly love the idea. Unfortunately, this is not something I believe M365DSC should implement as part of its code base. I see this as being a separate project all together where someone could build a report generator that would combine information from multiple sources with M365DSC's content using the DSCParser features. I will label with Enhancement/Backlog and close this for the moment. Hopefully someone in the community will seize this opportunity ;) Thanks @DeanGross
