### ISSUE TITLE
Export-M365DSCConfiguration issue | 1.21.1124.2

### ISSUE THREAD

**Issue by aslan-im** [microsoft/Microsoft365DSC#1604]
#### Details of the scenario you tried and the problem that is occurring
Trying to export whole configuration available in the tenant. Running:
`Export-M365DSCConfiguration -Components @(<list of components>) -Credential $Credential`

What I see in the output:
```
Connecting to {ExchangeOnline}
Connecting to {MicrosoftGraph}
Connecting to {MicrosoftTeams}
Connecting to {PnP}...
Exception setting "Connect": "Cannot set the value property for PSMemberInfo object of the type "System.Management.Automation.PSMethod"."
```

#### The operating system the target node is running
        OsName: Microsoft Windows Server 2019 Datacenter
        OsOperatingSystemSKU: DatacenterServerEduition
        OSArchitecture: 64-bit
        WindowsVersion: 1809
        WindowsBuildLabEx: 17763.1.amdfre.rs5_release.180914-1434
        OsLanguage: en-US
        OsMuiLanguages: {en-US}
#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.1124.2

**Comment by aslan-im** [comment]
Seems it was because of the permissions. Do we have somewhere the list of the minimal graph permissions for configurations extraction?

**Comment by NikCharlebois** [comment]
You can get the list by running:

Get-M365DSCCompiledPermissionList -ResourceNameList (Get-M365DSCAllResources)

You can also automatically grant these permissions by running:

Update-M365DSCAllowedGraphScopes -All -Type Update
