### ISSUE TITLE
Connecting to {PnP} Error - TenantId must be in format contoso.onmicrosoft.com

### ISSUE THREAD

**Issue by johnc-risual** [microsoft/Microsoft365DSC#1605]
#### Details of the scenario you tried and the problem that is occurring

- Created Azure AD App Registration in the Azure portal.
- Created a certificate.

    Reference:

    https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-self-signed-certificate

    ``` PowerShell
    $CertificateName = "<CERTIFICATE NAME>"
    $Certificate = New-SelfSignedCertificate -Subject "CN=$CertificateName" -CertStoreLocation "Cert:\CurrentUser\My" -KeyExportPolicy Exportable -KeySpec Signature -KeyLength 2048 -KeyAlgorithm RSA -HashAlgorithm SHA256
    ```

- Added public key of certificate to Azure AD App Registration.
- Added API permissions for all Microsoft Graph services.
- Granted Admin rights to all new permissions.
- Connect using the Azure AD App Registration and certificate thumbprint:

    ``` PowerShell
    Connect-MgGraph -ClientID "<APP ID GUID>" -TenantId "<TENANT ID GUID>" -CertificateThumbprint "<CERTIFICATE THUMBPRINT>"
    ```

- Export:

    ``` PowerShell
    Export-M365DSCConfiguration
    ```

- Result:

    ```
    Connecting to {ExchangeOnline}...Creating a new session for implicit remoting of "Get-AcceptedDomain" command...
    ✅
    Connecting to {MicrosoftGraph}...✅
    Connecting to {MicrosoftTeams}...✅
    Connecting to {PnP}...❌
    TenantId must be in format contoso.onmicrosoft.com
    ```

- Verify Connection:

    ``` PowerShell
    Get-MgContext
    ```

    Result:

    ```
    ClientId              : <APP ID GUID>
    TenantId              : <TENANT ID GUID>
    CertificateThumbprint : <CERTIFICATE THUMBPRINT>
    Scopes                : {Agreement.ReadWrite.All, TeamSettings.ReadWrite.All, TeamMember.Read.All, Place.Read.All...}
    AuthType              : AppOnly
    AuthProviderType      : ClientCredentialProvider
    CertificateName       :
    Account               :
    AppName               : <APP NAME>
    ContextScope          : Process
    Certificate           :
    PSHostVersion         : 5.1.19041.1320
    ```

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
# <PLEASE ADVISE HOW I OBTAIN THIS>
```

#### The operating system the target node is running
```
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}
```

#### Version of the DSC module that was used ('dev' if using current dev branch)

```
Name                       : Microsoft365DSC
Version                    : 1.21.1124.2
```

**Comment by pgeislerkpmg** [comment]
Hi,
as far as I know and like the error is showing you shouldn't use the "TENANT ID GUID" but provide the tenant id in the form of the onmicrosoft-domain like "contoso.onmicrosoft.com".

So you would have something like:
Connect-MgGraph -ClientID "<APP ID GUID>" -TenantId "YOURTENANT.onmicrosoft.com" -CertificateThumbprint "<CERTIFICATE THUMBPRINT>"

**Comment by johnc-risual** [comment]
Hi,

Thanks for responding.

This is the response when using the tenant `onmicrosoft.com` domain for the TenantId parameter:

```
Connecting to {ExchangeOnline}...✅
Connecting to {MicrosoftGraph}...❌
The remote server returned an error: (404) Not Found.
```

**Comment by pgeislerkpmg** [comment]
Hi,
interesting.
I use the following to export the tenant config:
Export-M365DSCConfiguration -Components @(<WHAT TO EXPORT>) -ApplicationId <APP-ID> -TenantId <TENANT>.onmicrosoft.com -CertificateThumbprint <CERT-THUMBPRINT> -FileName "config.ps1"
This works for me without any problem.
I do not use "Connect-MgGraph" explicitly in my "code".

**Comment by johnc-risual** [comment]
Hi,

Thanks for following up.

I've just tried the command in your note but this time it's refusing to connect to Exchange Online whereas previously it was able to connect to that service.

```
Connecting to {ExchangeOnline}...❌
```

**Comment by NikCharlebois** [comment]
TenantID should be the FQDN of your tenant, with the onmicrosoft.com in it. For example

Export-M365DSCConfiguration  -Application id 12345-12345-12345-12345-12345 -TenantId Contoso.onmicrosoft.com -CertificateThumbprint XXXXXXXXXXXXXXXXXXXXX

**Comment by johnc-risual** [comment]
Hi @NikCharlebois,

Thanks for the response.

We tried using the FQDN for the tenant previously:
https://github.com/microsoft/Microsoft365DSC/issues/1605#issuecomment-984547503

We got past this error by using an Azure AD App secret (rather than certificate) and adding the following API Permissions to the Azure AD App:
SharePoint.Sites.FullControl.All
SharePoint.TermStore.Read.All
SharePoint.User.Read.All
