### ISSUE TITLE
CouldNotAutoloadMatchingModule

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#1608]
#### Details of the scenario you tried and the problem that is occurring
I am currently transitioning our Azure DevOps pipeline from using M365DSC version 1.21.922.1 to the most recent version. I have carefully reviewed the breaking changes introduced by version and made the required adjustments in our code and config base. I am using username and password to connect to the tenant.

It appear that certain functions cannot be found during the execution of Test-DscConfiguration (they have been loaded before).

#### Verbose logs showing the problem
```
##[error]The 'Add-M365DSCTelemetryEvent' command was found in the module 'Microsoft365DSC', but the module could not be loaded. 
For more information, run 'Import-Module Microsoft365DSC'.
    + CategoryInfo          : ObjectNotFound: (Add-M365DSCTelemetryEvent:) [], CimException
 ##[error]+ FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
    + PSComputerName        : localhost
```
There are many more messages similar to this one.
#### Suggested solution to the issue
none, yet.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by NikCharlebois** [comment]
What do you get if you run:

Import-Module Microsoft365DSC -Verbose

It should tell you what the exact error is.

**Comment by SebastianGoers** [comment]
Just in case someone is having the same issue: Using the new method of importing the dependencies solved the issue for me.
