### ISSUE TITLE
Resources not using username / password credentials

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#1609]
#### Details of the scenario you tried and the problem that is occurring
I am currently transitioning our Azure DevOps pipeline from using M365DSC version 1.21.922.1 to the most recent version. I have carefully reviewed the breaking changes introduced by version and made the required adjustments in our code and config base. I am using username and password to connect to the tenant.

It appears that some resources do not use username / password credentials to connect to the tenant. It seems to work if I only use one M365DSC module, but as soon as I use more modules, all sorts of different issues occur. Some indicate that interactive login is used, other indicate that an Azure login is being tried from MSCloudLoginAssistant.

I have tried to narrow down the issue, but I am not seeing any of the verbose logs from MSCloudLoginAssistant.

#### Verbose logs showing the problem
```
This event indicates that a non-terminating error was thrown when DSCEngine was executing Test-TargetResource on MSFT_AADGroupsSettings DSC resource. FullyQualifiedErrorId is PropertyNotFound. Error Message is The property 'Credentials' cannot be found on this object. Verify that the property exists and can be set..Job {73AFF3BE-5430-11EC-BC6C-00155D000446} : 
MIResult: 1
Error Message: Exception calling ".ctor" with "0" argument(s): "Exception setting "Azure": "Cannot convert the "Azure" value of type "Azure" to type "Azure".""
Message ID: ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
Error Category: 7
Error Code: 7
```
#### Suggested solution to the issue
It is propably a permission issue, but I couldn't find which permissions I need to grant to be able to use the new MS Graph modules. I have already checked https://microsoft365dsc.com/concepts/consent-flow/ .
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by NikCharlebois** [comment]
@SebastianGoers we will need more info on this one. So you are using, say version 1.21.1208.1 of the module, from an Azure DevOPS pipeline and when running Start-DSCConfiguration is fails on the second resource? Is that it?

**Comment by SebastianGoers** [comment]
The problem still persists. I'm running Start-DscConfiguration in an Azure pipeline, this is correct.
