### ISSUE TITLE
Functions are being imported multiple times

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#1610]
#### Details of the scenario you tried and the problem that is occurring
It appears that functions / cmdlets are being imported several times, which results in errors.
#### Verbose logs showing the problem
```
##[error]Function Update-MgUserOutlookTaskGroup cannot be created because function capacity 4096 has been exceeded for this
##[error]scope.
```
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by NikCharlebois** [comment]
@SebastianGoers with this week's release (1.21.1208.1) this issue should be addressed. Thanks for confirming.
