### ISSUE TITLE
The Community Script Package M365Automation.zip download link is broken

### ISSUE THREAD

**Issue by 16Rookie16** [microsoft/Microsoft365DSC#1619]
Hi Community,
Can someone upload or fix the download link for M365Automation.zip what is mentioned in the DevOps Whitepaper. 
Many Thanks!

**Comment by NikCharlebois** [comment]
@ykuijs can you please take a look at this one? Thanks

**Comment by VNDCK** [comment]
Also vouching for this one. The download is still not available.

**Comment by ykuijs** [comment]
Am updating the whitepaper as we speak. In the meantime, the correct URL is https://office365dsc.azurewebsites.net/Pages/Resources/Whitepapers/M365Automation.zip

**Comment by VNDCK** [comment]
> Am updating the whitepaper as we speak. In the meantime, the correct URL is https://office365dsc.azurewebsites.net/Pages/Resources/Whitepapers/M365Automation.zip

Thank you! Got it.

**Comment by ykuijs** [comment]
The whitepaper has been updated as well. It now contains the correct link. I also created an aka.ms link, so maintaining the link is much easier: https://aka.ms/M365DSCWhitepaper/Scripts
