### ISSUE TITLE
UI is not displaying when running Export-M365DSCConfiguration

### ISSUE THREAD

**Issue by rayakajamon** [microsoft/Microsoft365DSC#1625]
The UI/ wizard never comes up when the export command is run.  Script will run and proceeds to just extract everything.

Any help would be greatly appreciated.  

Thank you

**Comment by rayakajamon** [comment]
> @rayakajamon The UI was deprecated, and we now use the website help assist in generating the script. https://export.microsoft365dsc.com/

Thank you so much.  Well, there goes a few wasted hours trying to troubleshoot.  ;)

**Comment by NikCharlebois** [comment]
As @desmay points out, the website is now the way to go. Other option is to use:

Export-M365DSCConfiguration **-LaunchWebUI**

**Comment by rayakajamon** [comment]
Thank you very much.

-Ray
"Where your treasure is, there your heart will be also" (Luke 12:34)

________________________________
