### ISSUE TITLE
Extracting [EXOAcceptedDomain]...Could not determine authentication method

### ISSUE THREAD

**Issue by johnc-risual** [microsoft/Microsoft365DSC#1629]
#### Details of the scenario you tried and the problem that is occurring

- Created Azure AD App Registration in the Azure portal.
- Added a secret.
- Added all Microsoft Graph API permissions to Azure AD App.
- Added all Office 365 Exchange Online API permissions to Azure AD App.
- Added all Office 365 Management API permissions to Azure AD App.
- Granted Admin rights to all new permissions.
- Export using the Azure AD App Registration and secret:

    ``` PowerShell
    $ApplicationId = "<APP_ID>"
    $ApplicationSecret = "<APP_SECRET>"
    $TenantId = "<TENANT_FQDN>"

    Export-M365DSCConfiguration -Components @("EXOAcceptedDomain") -ApplicationId $ApplicationId -ApplicationSecret $ApplicationSecret -TenantId $TenantId
    ```

- Result:

    ```
    Connecting to {ExchangeOnline}...✅
    [1/1] Extracting [EXOAcceptedDomain]...Could not determine authentication method
    ```

This occurs for all EXO components.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell
# <PLEASE ADVISE HOW I OBTAIN THIS>
```

#### The operating system the target node is running
```
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}
```

#### Version of the DSC module that was used ('dev' if using current dev branch)

```
Name                       : Microsoft365DSC
Version                    : 1.21.1124.2
```

**Comment by NikCharlebois** [comment]
Application Secret is unfortunately not supported for Exchange Online. See https://docs.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps for additional details.

Our next release will include a proper message at extraction time to advise user that this authentication method is not supported.
