### ISSUE TITLE
EXOAntiPhishPolicy MakeDefault Test problem

### ISSUE THREAD

**Issue by T630Dev** [microsoft/Microsoft365DSC#1634]
#### Details of the scenario you tried and the problem that is occurring
When I want to modify the default Anti Phish Policy 'Office365 AntiPhish Default' and provide the MakeDefault = true attribute in the DSC configuration, it applies the changes correctly.

![AntiPhish](https://user-images.githubusercontent.com/88185985/146526279-f8b8c82f-de65-441b-8f24-39a2b9ea1b42.png)

When I then run a Test-DscConfiguration, it tells me that this resource is not in the desired state.
I then removed the MakeDefault attribute from the DSC configuration, applied and tested it again and then the resource was in the desired state.

It hence seems that the test method for this resource does not correctly determine whether the policy is the default or not.

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.1103.1

**Comment by NikCharlebois** [comment]
This has been fixed in the latest versions. Please ensure you update to 1.21.1215.1 or greater and confirm that it works for you. Thanks

**Comment by T630Dev** [comment]
ok thanks. Will retest with the latest version and let you know.

**Comment by atdheekurteshi** [comment]
The Issues was tested with the newest version of the DSC and its working.

Version of the DSC module that was used ('dev' if using current dev branch)

1.21.1222.1
