### ISSUE TITLE
EXOHostedContentFilterPolicy MakeDefault does not test correctly

### ISSUE THREAD

**Issue by T630Dev** [microsoft/Microsoft365DSC#1635]
#### Details of the scenario you tried and the problem that is occurring

When I modify the default EXOHostedContentFilterPolicy 'Default' and provide the MakeDefault = true attribute in the DSC configuration and the policy is already the default, the Test method returns false stating that this resource is not in the desired state.

![EXO](https://user-images.githubusercontent.com/88185985/146527042-9e995595-5ca6-4468-ae78-b2571ad8ba89.png)

When I remove the MakeDefault Parameter from the DSC configuration, apply the configuration and test the config again, the resource is in the desired state.

Hence, it needs to be checked and corrected that the test method returns false when the policy is already the default.

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.1103.1

**Comment by atdheekurteshi** [comment]
The Issues was tested with the newest version of the DSC and its working.

Version of the DSC module that was used ('dev' if using current dev branch)

1.21.1222.1
