### ISSUE TITLE
[EXO] Cannot export Exchange Online configuration using App registration

### ISSUE THREAD

**Issue by AzizGS** [microsoft/Microsoft365DSC#1662]
#### Details of the scenario you tried and the problem that is occurring

Trying to export EXO configuration using a registered application and the following script: 

```
$ApplicationId = Read-Host -Prompt 'Application Id'
$ApplicationSecret = Read-Host -Prompt 'Application Secret'
$TenantId = Read-Host -Prompt 'Tenant Id'


Export-M365DSCConfiguration -Components @("EXOAcceptedDomain", "EXOActiveSyncDeviceAccessRule", "EXOAddressBookPolicy", "EXOAddressList", "EXOAntiPhishPolicy", "EXOAntiPhishRule", "EXOApplicationAccessPolicy", "EXOAtpPolicyForO365", "EXOAvailabilityAddressSpace", "EXOAvailabilityConfig", "EXOCASMailboxPlan", "EXOClientAccessRule", "EXODkimSigningConfig", "EXOEmailAddressPolicy", "EXOGlobalAddressList", "EXOHostedConnectionFilterPolicy", "EXOHostedContentFilterPolicy", "EXOHostedContentFilterRule", "EXOHostedOutboundSpamFilterPolicy", "EXOHostedOutboundSpamFilterRule", "EXOInboundConnector", "EXOIntraOrganizationConnector", "EXOJournalRule", "EXOMailboxSettings", "EXOMailTips", "EXOMalwareFilterPolicy", "EXOMalwareFilterRule", "EXOManagementRole", "EXOMobileDeviceMailboxPolicy", "EXOOfflineAddressBook", "EXOOnPremisesOrganization", "EXOOrganizationConfig", "EXOOrganizationRelationship", "EXOOutboundConnector", "EXOOwaMailboxPolicy", "EXOPartnerApplication", "EXOPolicyTipConfig", "EXORemoteDomain", "EXORoleAssignmentPolicy", "EXOSafeAttachmentPolicy", "EXOSafeAttachmentRule", "EXOSafeLinksPolicy", "EXOSafeLinksRule", "EXOSharedMailbox", "EXOSharingPolicy", "EXOTransportRule") -ApplicationId $ApplicationId -ApplicationSecret $ApplicationSecret -TenantId $TenantId
```

#### Verbose logs showing the problem

> [WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted:

> EXOAcceptedDomain EXOActiveSyncDeviceAccessRule EXOAddressBookPolicy EXOAddressList EXOAntiPhishPolicy EXOAntiPhishRule EXOApplicationAccessPolicy EXOAtpPolicyForO365 EXOAvailabilityAddressSpace EXOAvailabilityConfig EXOCASMailboxPlan EXOClientAccessRule EXODkimSigningConfig EXOEmailAddressPolicy EXOGlobalAddressList EXOHostedConnectionFilterPolicy EXOHostedContentFilterPolicy EXOHostedContentFilterRule EXOHostedOutboundSpamFilterPolicy EXOHostedOutboundSpamFilterRule EXOInboundConnector E
XOIntraOrganizationConnector EXOJournalRule EXOMailboxSettings EXOMailTips EXOMalwareFilterPolicy EXOMalwareFilterRule EXOManagementRole EXOMobileDeviceMailboxPolicy EXOOfflineAddressBook EXOOnPremisesOrganization EXOOrganizationConfig EXOOrganiza
tionRelationship EXOOutboundConnector EXOOwaMailboxPolicy EXOPartnerApplication EXOPolicyTipConfig EXORemoteDomain EXORoleAssignmentPolicy EXOSafeAttachmentPolicy EXOSafeAttachmentRule EXOSafeLinksPolicy EXOSafeLinksRule EXOSharedMailbox EXOSharin
gPolicy EXOTransportRule
⌛ Export took {8 seconds}

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running

Windows Server 2016
#### Version of the DSC module that was used ('dev' if using current dev branch)
1.21.1229.1

**Comment by AzizGS** [comment]
PS : This is working in same environment when using the certificate authentication. 

> $ApplicationId = Read-Host -Prompt 'Application Id'
$CertificateThumbprint = Read-Host -Prompt 'Certificate Thumbprint'
$TenantId = Read-Host -Prompt 'Tenant Id'


> Export-M365DSCConfiguration -Components @("EXOAcceptedDomain", "EXOActiveSyncDeviceAccessRule", "EXOAddressBookPolicy", "EXOAddressList", "EXOAntiPhishPolicy", "EXOAntiPhishRule", "EXOApplicationAccessPolicy", "EXOAtpPolicyForO365", "EXOAvailabilityAddressSpace", "EXOAvailabilityConfig", "EXOCASMailboxPlan", "EXOClientAccessRule", "EXODkimSigningConfig", "EXOEmailAddressPolicy", "EXOGlobalAddressList", "EXOHostedConnectionFilterPolicy", "EXOHostedContentFilterPolicy", "EXOHostedContentFilterRule", "EXOHostedOutboundSpamFilterPolicy", "EXOHostedOutboundSpamFilterRule", "EXOInboundConnector", "EXOIntraOrganizationConnector", "EXOJournalRule", "EXOMailboxSettings", "EXOMailTips", "EXOMalwareFilterPolicy", "EXOMalwareFilterRule", "EXOManagementRole", "EXOMobileDeviceMailboxPolicy", "EXOOfflineAddressBook", "EXOOnPremisesOrganization", "EXOOrganizationConfig", "EXOOrganizationRelationship", "EXOOutboundConnector", "EXOOwaMailboxPolicy", "EXOPartnerApplication", "EXOPolicyTipConfig", "EXORemoteDomain", "EXORoleAssignmentPolicy", "EXOSafeAttachmentPolicy", "EXOSafeAttachmentRule", "EXOSafeLinksPolicy", "EXOSafeLinksRule", "EXOSharedMailbox", "EXOSharingPolicy", "EXOTransportRule") -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId

**Comment by NikCharlebois** [comment]
Hi, ApplicationSecret is not supported to authenticate against EXO resources. Please ensure you use CertificateThumbprint when trying to export EXO.
