### ISSUE TITLE
[MSFT_IntuneAppProtectionPolicyiOS] Export fails

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#1688]
#### Details of the scenario you tried and the problem that is occurring
Export device app protection policy for iOS devices failes with stating that there is no argument 'method',
#### Suggested solution to the issue
In https://github.com/microsoft/Microsoft365DSC/blob/9a7f2f44ca53b7edc6789b1d9d691210bced4ebf/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneAppProtectionPolicyiOS/MSFT_IntuneAppProtectionPolicyiOS.psm1#L736

Change 

```
$response = Invoke-MgGraphRequest Method Get `
            -Uri $Url
```

to

```
$response = Invoke-MgGraphRequest -Method Get `
            -Uri $Url
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by andikrueger** [comment]
Fix is merged into dev.
