### ISSUE TITLE
[MSFT_EXOOrganizationConfig] does not implement the write property  SendFromEmailAliasEnabled

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#1689]
#### Details of the scenario you tried and the problem that is occurring
Test-TargetResource of the PS module MSFT_EXOOrganizationConfig does not implement the write property 
SendFromEmailAliasEnabled
#### Verbose logs showing the problem
```
The command Test-TargetResource of the PS module MSFT_EXOOrganizationConfig does not implement the write property 
SendFromEmailAliasEnabled mentioned in the corresponding MOF schema file C:\Program Files\WindowsPowerShell\Modules\Mic
rosoft365DSC\1.22.119.1\DscResources\MSFT_EXOOrganizationConfig\MSFT_EXOOrganizationConfig.schema.mof. All write 
paramenters mentioned in the schema file must be implemented by the command Test-TargetResource.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : WriteParameterNotImplemented
    + PSComputerName        : localhost
```
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.119.1

**Comment by andikrueger** [comment]
Good catch. The variable name within the class description did not match the parameter name.
