### ISSUE TITLE
Filtering within specific exports

### ISSUE THREAD

**Issue by briankronberg** [microsoft/Microsoft365DSC#1691]
### Description
I have used Microsoft365DSC so far on two projects to dump the configuration prior to importing it into a new tenant.  Both of these projects were divestitures, so I was only interested in a sub-set of the source tenant.  I would like a way to filter inside some of the configuration items.  For example:
- AADConditionalAccessPolicy:  Filter: {DisplayName -like "SubCompany*"}
- O365Group: Filter: {PrimarySMTPAddress -match "domainname.com"}

### Special considerations or limitations
I understand this would take a lot of work but it would be essential for getting to a no-code way of exporting and importing it without having to filter through the files manually.

**Comment by andikrueger** [comment]
You could use DSCParser to generate an object representation of your configuration. This object can be filtered and you should be able to extract the resources. Generating a new configuration would still be tricky though.

https://nikcharlebois.com/dscparser-analyze-your-powershell-dsc-scripts/

**Comment by briankronberg** [comment]
> 

This is a great start!  Thanks for sharing.  This will at least allow me to quickly filter out what I need.  What it doesn't solve though is when I need only 100 groups out of 100,000.  Run time will still be horrific but I can at least filter afterwards.

My main goal with the filter was to reduce run time of the source query against really large tenants.

**Comment by andikrueger** [comment]
Just a few thoughts on this topic on how we could add this functionality: Basically, we would need a further parameter for `Export-M365DSCConfiguration`. This parameter could be named `Filter` and would allow a hashtable of FilterScripts:

```powershell
@{
   AADConditionalAccessPolicy = 'DisplayName -like "SubCompany*""'
   O365Group = 'PrimarySMTPAddress -match "domainname.com"'
}
```

We would need to pass this parameter to `Start-M365DSCConfigurationExtract`. In this function we could elaborate, if a resource allows filters for exporting the data. This could be very similar to the already available checks:
https://github.com/microsoft/Microsoft365DSC/blob/0c00b6f0668a4fea1f45e3cedfac4ea57a6459c7/Modules/Microsoft365DSC/Modules/M365DSCReverse.psm1#L417-L426

If the resource allows filtered exports, we could pick the matching object out of the hash table and then generate a limited export of this resource.

This would not be a breaking change. @NikCharlebois Do you see any obstacles with this idea?
