### ISSUE TITLE
[MSFT_TeamsTenantDialPlan] Does not export multiple Normalization rules

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#1695]
#### Details of the scenario you tried and the problem that is occurring
I tried exporting a tenant dial plan for Teams which has multiple normalization rules. Only the first rule is being exported, the rest is being ommitted.
#### Suggested solution to the issue
I believe the issue is in https://github.com/microsoft/Microsoft365DSC/blob/ccb52e536b12c7a28285bf24bb59504928e0fbc8/Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantDialPlan/MSFT_TeamsTenantDialPlan.psm1#L442

I have checked the type of the return value for normalization rules:
```
$p = Get-CsTenantDialPlan
$p[0].NormalizationRules.gettype()


IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     ArrayList                                System.Object
```

The code is checking for a hashtable. Thus, it defaults to the else section where it only picks the first rule. The type needs to be corrected.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by NikCharlebois** [comment]
Great catch @SebastianGoers , PR is on its way. Thanks for all your help!
