### ISSUE TITLE
1.22.119.2 Doesn't install dependent components 

### ISSUE THREAD

**Issue by hmank** [microsoft/Microsoft365DSC#1708]
#### Details of the scenario you tried and the problem that is occurring
I'm trying to install the latest version of the DSC module on a new machine, it only installs the DSC module it doesn't install any of the required dependancies.

I tried running export-m365dscconfiguration and then it began installing the dependant components

PS C:\WINDOWS\system32> Export-M365DSCConfiguration
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\microsoft365dsc\1.22.119.2\modules\M365DSCUtil.psm1:951 char:9
+         $tenant = $Credential.UserName.Split('@')[1]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Updating dependency {DSCParser} to version {1.3.0.2}...✅
Updating dependency {ExchangeOnlineManagement} to version {2.0.5}...✅
Updating dependency {Microsoft.Graph.Applications} to version {1.9.1}...✅
Updating dependency {Microsoft.Graph.Authentication} to version {1.9.1}...✅
Updating dependency {Microsoft.Graph.DeviceManagement} to version {1.9.1}...✅
Updating dependency {Microsoft.Graph.DeviceManagement.Administration} to version {1.9.1}...✅
Updating dependency {Microsoft.Graph.DeviceManagement.Enrolment} to version {1.9.1}...✅
Updating dependency {Microsoft.Graph.Devices.CorporateManagement} to version {1.9.1}...✅
Updating dependency {Microsoft.Graph.Groups} to version {1.9.1}...✅
Updating dependency {Microsoft.Graph.Identity.DirectoryManagement} to version {1.9.1}...
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
Install-Module Microsoft365DSC -Force

**Comment by NikCharlebois** [comment]
For performance reason (and to prevent future issues) we no longer force the dependencies in the Module's manifest. The error you are reporting above will be fixed in an upcoming PR. Thanks!

**Comment by hmank** [comment]
Thanks Nik, do you have the recommendations on how to install the dependencies before hand?

**Comment by NikCharlebois** [comment]
Update-M365DSCDependencies is the way to go here.
