### ISSUE TITLE
M365TenantConfig -

### ISSUE THREAD

**Issue by RVAHaver01** [microsoft/Microsoft365DSC#1717]
#### Details of the scenario you tried and the problem that is occurring
This is my first time trying to use M365DSC and when trying to compile the config file I get this:

PS C:\Users\david.haver\OneDrive - Cherry Bekaert LLP\Desktop\DSC\DSC - AAD> .\M365TenantConfig.ps1 -Credential $creds
M365TenantConfig: C:\Users\david.haver\OneDrive - Cherry Bekaert LLP\Desktop\DSC\DSC - AAD\M365TenantConfig.ps1:7422
Line |
7422 |  M365TenantConfig -ConfigurationData .\ConfigurationData.psd1 -Credent …
     |  ~~~~~~~~~~~~~~~~
     | The term 'M365TenantConfig' is not recognized as a name of a cmdlet, function, script file, or
     | executable program. Check the spelling of the name, or if a path was included, verify that the path is
     | correct and try again.

This is the last line in the M365TenantConfig.ps1 file that was generated originally and I have not modified it.

I tried commenting out the code but then it does not generate an output.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

# insert configuration here
```
[M365TenantConfig.txt](https://github.com/microsoft/Microsoft365DSC/files/7945358/M365TenantConfig.txt)

#### The operating system the target node is running

OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22000.1.amd64fre.co_release.210604-1628
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
#### Version of the DSC module that was used ('dev' if using current dev branch)
ModuleBase                                                            Version   
----------                                                            -------   
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.119.2 1.22.119.2
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.21.505.1 1.21.505.1
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.21.428.1 1.21.428.1
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.21.421.2 1.21.421.2
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.21.414.2 1.21.414.2
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.21.407.1 1.21.407.1
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.21.331.1 1.21.331.1

**Comment by robchillg** [comment]
Hi, I might suggest you move your files locally and not run from OneDrive and then test again.

**Comment by RVAHaver01** [comment]
That is the ticket.  Thanks.
