### ISSUE TITLE
Resource IntuneDeviceCompliancePolicyiOs page.

### ISSUE THREAD

**Issue by RVAHaver01** [microsoft/Microsoft365DSC#1721]
There are missing values in the table.  Specifically PasscodeRequiredType and DeviceThreatProtectionRequiredSecurityLevel.

**Comment by NikCharlebois** [comment]
We are migrating our documentation over to the official website. Please refer to this page for the latest details on the resource:
https://microsoft365dsc.com/resources/intune/IntuneDeviceCompliancePolicyiOs/
