### ISSUE TITLE
Resource IntuneDeviceConfigurationPolicyAndroidWorkProfile Page

### ISSUE THREAD

**Issue by RVAHaver01** [microsoft/Microsoft365DSC#1722]
On this page it there is a GlobalAdminAccount parameter and I believe that should be Credential.  Visual Studio Code is showing an error on that parameter.

**Comment by andikrueger** [comment]
Within the example section there is an parameter GlobalAdminAccount --> This should be Credential. 

![image](https://user-images.githubusercontent.com/15608729/151817742-634547b5-31bb-4d35-a14d-fd98f63f6aca.png)

https://microsoft365dsc.com/resources/intune/IntuneDeviceConfigurationPolicyAndroidWorkProfile/#example-1
