### ISSUE TITLE
.mof file creation fails - creates localhost.mof.error or nothing at all

### ISSUE THREAD

**Issue by robchillg** [microsoft/Microsoft365DSC#1724]
#### Details of the scenario you tried and the problem that is occurring

Execution of simple commands in ISE using credential as follows:

PS C:\Source\dsc-test> $Credential = Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:

PS C:\Source\dsc-test> Export-M365DSCConfiguration -Workloads @(“O365”) -Credential $Credential
Connecting to {MicrosoftGraph}...✅
[1/2] Extracting [O365AdminAuditLogConfig]...✅
[2/2] Extracting [O365OrgCustomizationSetting]...✅
⌛ Export took {60 seconds}

Destination Path: .\

PS C:\Source\dsc-test> dir

    Directory: C:\Source\dsc-test

Mode                 LastWriteTime         Length Name                                                                                    
----                 -------------         ------ ----                                                                                    
d-----         1/28/2022  11:58 AM                Save                                                                                    
-a----         1/28/2022  12:42 PM           1034 ConfigurationData.psd1                                                                  
-a----         1/28/2022  12:42 PM           2902 M365TenantConfig.ps1                                                                    

PS C:\Source\dsc-test> .\M365TenantConfig.ps1 -Credential $Credential
ConvertTo-MOFInstance : System.ArgumentException error processing property 'Password' OF TYPE 'MSFT_Credential': Cannot load encryption 
certificate. The certificate setting 'M365DSC.cer' does not represent a valid base-64 encoded certificate, nor does it represent a valid 
certificate by file, directory, thumbprint, or subject name.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:310 char:13
+             ConvertTo-MOFInstance MSFT_Credential $newValue
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessProperty,ConvertTo-MOFInstance
ConvertTo-MOFInstance : System.ArgumentException error processing property 'Password' OF TYPE 'MSFT_Credential': Cannot load encryption 
certificate. The certificate setting 'M365DSC.cer' does not represent a valid base-64 encoded certificate, nor does it represent a valid 
certificate by file, directory, thumbprint, or subject name.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:310 char:13
+             ConvertTo-MOFInstance MSFT_Credential $newValue
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessProperty,ConvertTo-MOFInstance
Write-NodeMOFFile : Invalid MOF definition for node 'localhost': Exception calling "ValidateInstanceText" with "1" argument(s): "Syntax 
error: 
 At line:11, char:1
 Buffer:
T_Credential1ref
{
}^;
in
"
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2369 char:21
+ ...             Write-NodeMOFFile $Name $mofNode $Script:NodeInstanceAlia ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile

    Directory: C:\Source\dsc-test\M365TenantConfig

Mode                 LastWriteTime         Length Name                                                                                    
----                 -------------         ------ ----                                                                                    
-a----         1/28/2022  12:43 PM           3612 localhost.mof.error                                                                     
Compilation errors occurred while processing configuration 'M365TenantConfig'. Please review the errors reported in error stream and 
modify your configuration code appropriately.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (M365TenantConfig:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration

#### Suggested solution to the issue
Appears to be something related to the certificate used to encrypt the password for the account.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```# Generated with Microsoft365DSC version 1.22.126.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $Credential
)

Configuration M365TenantConfig
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $Credential
    )

    if ($null -eq $Credential)
    {
        <# Credentials #>
        $Credscredential = Get-Credential -Message "Credentials"

    }
    else
    {
        $CredsCredential = $Credential
    }

    $OrganizationName = $CredsCredential.UserName.Split('@')[1]
    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.22.126.1'

    Node localhost
    {
        O365AdminAuditLogConfig db528267-cd31-4187-8d50-5e1b7e49f17b
        {
            Credential                      = $Credscredential;
            Ensure                          = "Present";
            IsSingleInstance                = "Yes";
            UnifiedAuditLogIngestionEnabled = "Disabled";
        }
        O365OrgCustomizationSetting 01e166e5-6afa-43f6-8637-64a14a5baf87
        {
            Credential           = $Credscredential;
            Ensure               = "Present";
            IsSingleInstance     = "Yes";
        }
    }
}
M365TenantConfig -ConfigurationData .\ConfigurationData.psd1 -Credential $Credential

#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.

Running DSC from Win10 Pro Build 19043

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.22.126.1

**Comment by NikCharlebois** [comment]
Along with the exported configuration, there will be a ConfigurationData.psd1 file. Can you share the content of that file here as well for us to have a look? Thanks

**Comment by robchillg** [comment]
Here is the info you requested.

It appears that newer rev. automatically enabled the encryption of the credential password by default using below mentioned cert  "M365DSC.cer" for inclusion in the .mof file creation process.

ConfigurationData.psd1

****@{
    AllNodes = @(
        @{
            NodeName                    = "localhost"
            PSDscAllowPlainTextPassword = $true;
            PSDscAllowDomainUser**        = $true;
            #region Parameters
            # Path of the certificate used to encrypt credentials in the file.
            CertificateFile = "M365DSC.cer"

            # Default Value Used to Ensure a Configuration Data File is Generated
            ServerNumber = "0"

        }
    )
    NonNodeData = @(
    )
}**

We have not enabled this function as we don't require this feature at this time, so there is no certificate being created.  

Can you add a parameter such as -NonEncrypt so that this can be disabled during .mof creation?

**Comment by NikCharlebois** [comment]
Looks like this is clearly a regression bug. We will work on submitting a Pull Request to have this fix in next release (scheduled for Wednesday February 9th).
