### ISSUE TITLE
Configuration Policies

### ISSUE THREAD

**Issue by RVAHaver01** [microsoft/Microsoft365DSC#1732]
I am working on a DSC configuration for Intune and noticed that there are only 3 configuration policies (Android Work Profile, Win10, and IOS).  Are there some policies missing (i.e. MacOS, Android Enterprise, etc.) or do you just duplicate the IOS one and change the settings for Mac and similar for the Android Profiles?

**Comment by NikCharlebois** [comment]
Adding @RuudGijsbers who leads the Intune workload to the discussions

**Comment by RuudGijsbers** [comment]
@RVAHaver01 I've been working on the dynamic resource generator to be able to create the Intune resources automatically. If we would create them by hand, we would need to add 100+ parameters per configuration (resource). Last night i had a small break through and it looks like I managed to get the resource generator working for the Intune policies. Once the changes have been checked and the pull request has been approved, it will be a lot easier to create the missing policy / configuration types in Intune. I'll keep you updated on the progress.

Are there any specific configuration policies you're looking for that I should address first?

**Comment by RVAHaver01** [comment]
No not really, I work for an MSP and we are looking to use M365DSC to set a baseline set of configurations based off of security and best practices so that we do not have to spend hours doing it all manually.  This will truly add value to our organization.  Thanks for working on this.

Respectfully,
David B. Haver
Manager – DTS – Management Services & Transactions

804.673.5700  office
804.673.5762 direct
804.690.7669 cell
***@***.******@***.***>
cbh.com/digital<https://urldefense.proofpoint.com/v2/url?u=https-3A__u6119851.ct.sendgrid.net_ls_click-3Fupn-3DVb-2D2Bz-2D2FbBoJJFUmPJ1llIKlhS74Hel6CFJzYsIIwt3lAFpZ2HQSXVsC3NqlAJ8p5AaIzPFZjJO7BF-2D2BvRewUnDAaA-2D3D-2D3DRo5t-5FYxCxpoge33FNHhRVcK23d6Uw5M-2D2FPjC6kNlGhewgVONqFUbstBGbGwUbIZPP2G6rbnB6aGxCJSxucO2c28-2D2BdMOjrv-2D2B-2D2Bt14PqcF-2D2FUxuwwoXZeRzoqZpf-2D2BudPnvcGA5uLS-2D2BCtQaJOutDbBbscSywV8LhKBReo4bSfjSRRT-2D2BCKlaN-2D2FkBSUhY6yOegbmsEVIuTzQAYENIBITOGFgs3LwQg8ZxHw7FK4S8t7YTGpPNKZW4Ps2A5vWZBlvdAgDIBLMHsC29&d=DwMFAg&c=1POd4JaUGl-PtcKc5LZDvQ&r=D0VRENT3y4ndqL35V74EJSOji7WmKCoTTrYtzUEwhI8&m=h1XGOsuwu90DstjospX8zdYGmgwxXJtqKhZnFihmdLQ&s=PiJFR-PybR_gls_V01jJxBjTVXBbXsMqQwLIDvFQWHM&e=>


From: Ruud Gijsbers - Rademakers ***@***.***>
Sent: Friday, February 11, 2022 12:44 AM
To: microsoft/Microsoft365DSC ***@***.***>
Cc: David Haver ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/Microsoft365DSC] Configuration Policies (Issue #1732)


Caution: This email is from outside of the organization.

@RVAHaver01<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_RVAHaver01&d=DwMCaQ&c=1POd4JaUGl-PtcKc5LZDvQ&r=D0VRENT3y4ndqL35V74EJSOji7WmKCoTTrYtzUEwhI8&m=MrE1fWo7ZA70gPYzmi21D0DDuFKunLsMdMtsM80oqmJhESKMz_wXQLxTtv7S7aL7&s=iYH6CiP27-nugekf-9Uz1iwCKloJ0KtrIAYMpYsWQDI&e=> I've been working on the dynamic resource generator to be able to create the Intune resources automatically. If we would create them by hand, we would need to add 100+ parameters per configuration (resource). Last night i had a small break through and it looks like I managed to get the resource generator working for the Intune policies. Once the changes have been checked and the pull request has been approved, it will be a lot easier to create the missing policy / configuration types in Intune. I'll keep you updated on the progress.

Are there any specific configuration policies you're looking for that I should address first?

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_Microsoft365DSC_issues_1732-23issuecomment-2D1035900183&d=DwMCaQ&c=1POd4JaUGl-PtcKc5LZDvQ&r=D0VRENT3y4ndqL35V74EJSOji7WmKCoTTrYtzUEwhI8&m=MrE1fWo7ZA70gPYzmi21D0DDuFKunLsMdMtsM80oqmJhESKMz_wXQLxTtv7S7aL7&s=fXsuw0t1hqo2xVrFes-on4ZpCp_TkzY0radHsueYpKw&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ASMWG3TNCFKQHHGYXRGNAVDU2SOZ7ANCNFSM5NJ5OD4A&d=DwMCaQ&c=1POd4JaUGl-PtcKc5LZDvQ&r=D0VRENT3y4ndqL35V74EJSOji7WmKCoTTrYtzUEwhI8&m=MrE1fWo7ZA70gPYzmi21D0DDuFKunLsMdMtsM80oqmJhESKMz_wXQLxTtv7S7aL7&s=vow0zM9ZGRxFVgN_X5HcjYixOEtDjqLTDpRc3R-TxWo&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=1POd4JaUGl-PtcKc5LZDvQ&r=D0VRENT3y4ndqL35V74EJSOji7WmKCoTTrYtzUEwhI8&m=MrE1fWo7ZA70gPYzmi21D0DDuFKunLsMdMtsM80oqmJhESKMz_wXQLxTtv7S7aL7&s=c_ILOmqkaVmb2TBSCoXHNwWM_5p1bdT_M6mfFhikqLE&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=1POd4JaUGl-PtcKc5LZDvQ&r=D0VRENT3y4ndqL35V74EJSOji7WmKCoTTrYtzUEwhI8&m=MrE1fWo7ZA70gPYzmi21D0DDuFKunLsMdMtsM80oqmJhESKMz_wXQLxTtv7S7aL7&s=H5uVYt6M4XCO8XvzziuMH4dK0Bgos7tlcBXZvMo7hKM&e=>.

**Comment by aexlz** [comment]
Hello Everyone

Is there an ETA for the macOS-Policies? 

Best Axel

**Comment by NikCharlebois** [comment]
@William-Francillette would this be something you'd have cycles to look at next?

**Comment by William-Francillette** [comment]
Sure, no problem - Will be working on it next 👍🏽

**Comment by William-Francillette** [comment]
> @William-Francillette would this be something you'd have cycles to look at next?

Hey @NikCharlebois 

I did some work on the DRG and was able to generate IntuneDeviceConfigurationPolicyMacOS without any input other than the readme and settings files
I posted both PRs (DRG + resource), let me know what you think - 
I tested it with 2 different types of Intune policies, when those PRs are approved I'll generate some more resources and see if the DRG requires more tweaking
