### ISSUE TITLE
Issue Authenticating to Specific Components within Given Workload when running Export-M365DSCConfiguration

### ISSUE THREAD

**Issue by tmcomeau** [microsoft/Microsoft365DSC#1743]
Hello,

When I run `Export-M365DSCConfiguration` on just the Teams workload for example, I get the "X" indicating it is unable to authenticate to all of the various components within that specific workload. A few notes:

- Using an account (simple credential auth) with Global Admin role within tenant (DEV tenant via Developer Program)
- Ran the following before attempting: `Update-M365DSCAllowedGraphScopes -All -Type Read`
- Ran `Update-M365Dependencies` 
- Can login to Teams manually using same account and `Connect-MicrosoftTeams` without any issues
- The account with Global Admin has the Azure Security Defaults set within AAD which includes MFA

I do get the MFA prompt when the script kicks off, and it is able to both connect to Microsoft Teams as well as extract the Teams channels but

Are there logs or errors anywhere that I can review to attempt root cause determination?

Command utilized is attached
[TeamsTestScriptUsed.txt](https://github.com/microsoft/Microsoft365DSC/files/8017129/TeamsTestScriptUsed.txt)
`# Generated by Microsoft365DSC from https://export.microsoft365dsc.com on 2/7/2022, 10:54:48 AM
# Visit https://microsoft365dsc.com for more information

# Getting client credential
$Credential = Get-Credential

# Exporting resources using credentials
Export-M365DSCConfiguration -FileName TeamsTest.ps1 -path C:\Users\TCOMEAU\Desktop\365DSC -Components @("TeamsCallingPolicy", "TeamsChannel", "TeamsChannelsPolicy", "TeamsChannelTab", "TeamsClientConfiguration", "TeamsEmergencyCallingPolicy", "TeamsEmergencyCallRoutingPolicy", "TeamsGuestCallingConfiguration", "TeamsGuestMeetingConfiguration", "TeamsGuestMessagingConfiguration", "TeamsMeetingBroadcastConfiguration", "TeamsMeetingBroadcastPolicy", "TeamsMeetingConfiguration", "TeamsMeetingPolicy", "TeamsMessagingPolicy", "TeamsPstnUsage", "TeamsTeam", "TeamsTenantDialPlan", "TeamsUpgradeConfiguration", "TeamsUpgradePolicy", "TeamsUser", "TeamsVoiceRoute", "TeamsVoiceRoutingPolicy") -Credential $Credential`

Output from terminal after running command
`[WARNING]Based on the provided Authentication parameters, the following resources cannot be extracted: 
TeamsChannelTab`

Additional output attached via screenshot as PowerShell froze on me after command finished and unable to copy or export.

![Export-M365DSCConfiguration Output](https://user-images.githubusercontent.com/99191841/152839469-312e6d1e-dc58-4e23-aee9-290e70239bc2.jpg)

Thank you kindly for anything you can do to assist!

**Comment by NikCharlebois** [comment]
You are doing everything right. The access denied error is not related to Microsoft 365 but to the PowerShell Service running on the machine (called the Local Configuration Manager). Make sure you are running the PowerShell ISE as an administrator (run as Admin) and that you are able to call into the Get-DSCLocalConfigurationManager cmdlet without any issues first.

**Comment by tmcomeau** [comment]
Thank you kindly for your help.

What I sent was indeed run within ISE being run as admin.

What follows are what is returned by the Get-DSCLocalConfigurationManager cmdlet. Beyond that will continue testing to see if I can provide more context. 

I am currently running the module on a laptop that is running on a corporate VPN. Will next try disabling the VPN and re-running to see if anything changes.

`PS C:\WINDOWS\system32> Get-DSCLocalConfigurationManager


ActionAfterReboot              : ContinueConfiguration
AgentId                        : 5D2F1CA3-8305-11EC-B3F2-E454E8FE5BE1
AllowModuleOverWrite           : False
CertificateID                  : 
ConfigurationDownloadManagers  : {}
ConfigurationID                : 
ConfigurationMode              : ApplyAndMonitor
ConfigurationModeFrequencyMins : 15
Credential                     : 
DebugMode                      : {NONE}
DownloadManagerCustomData      : 
DownloadManagerName            : 
LCMCompatibleVersions          : {1.0, 2.0}
LCMState                       : Idle
LCMStateDetail                 : 
LCMVersion                     : 2.0
StatusRetentionTimeInDays      : 10
SignatureValidationPolicy      : NONE
SignatureValidations           : {}
MaximumDownloadSizeMB          : 500
PartialConfigurations          : 
RebootNodeIfNeeded             : False
RefreshFrequencyMins           : 30
RefreshMode                    : PUSH
ReportManagers                 : {}
ResourceModuleManagers         : {}
PSComputerName                 :`

**Comment by tmcomeau** [comment]
Export attempt completed. While I don't expect this particular "issues" mechanism to be able to help me troubleshoot every aspect of the tool's use, I am back to my original question. 

Are there logs or errors sent anywhere that I can review to determine why it is connecting to successfully to Teams as a whole, as well as certain components (TeamsChannel, TeamsTeam) but unable to connect to all other components? 

Also wondering does the documentation tell us which underlying module M365DSC uses to connect to each component? If so I can go through and perform basic connectivity tests on each component using whichever underlying module is being abstracted by M365DSC.

Curious if there is any relationship between which components I am having trouble with and which are legacy Skype for Business.

Connecting to {MicrosoftTeams}...✅
[1/22] Extracting [TeamsCallingPolicy]...❌
[2/22] Extracting [TeamsChannel]...
    |---[1/5] Team {Digital Initiative Public Relations}
        |---[1/1] General✅
    |---[2/5] Team {U.S. Sales}
        |---[1/3] Sales West✅
        |---[2/3] Sales East✅
        |---[3/3] General✅
    |---[3/5] Team {Mark 8 Project Team}
        |---[1/4] Research and Development✅
        |---[2/4] Digital Assets Web✅
        |---[3/4] Design✅
        |---[4/4] General✅
    |---[4/5] Team {Sales and Marketing}
        |---[1/2] General✅
        |---[2/2] Monthly Reports✅
    |---[5/5] Team {Retail}
        |---[1/1] General✅
[3/22] Extracting [TeamsChannelsPolicy]...❌
[4/22] Extracting [TeamsClientConfiguration]...❌
[5/22] Extracting [TeamsEmergencyCallingPolicy]...❌
[6/22] Extracting [TeamsEmergencyCallRoutingPolicy]...❌
[7/22] Extracting [TeamsGuestCallingConfiguration]...❌
[8/22] Extracting [TeamsGuestMeetingConfiguration]...❌
[9/22] Extracting [TeamsGuestMessagingConfiguration]...❌
[10/22] Extracting [TeamsMeetingBroadcastConfiguration]...❌
[11/22] Extracting [TeamsMeetingBroadcastPolicy]...❌
[12/22] Extracting [TeamsMeetingConfiguration]...❌
[13/22] Extracting [TeamsMeetingPolicy]...❌
[14/22] Extracting [TeamsMessagingPolicy]...❌
[15/22] Extracting [TeamsPstnUsage]...❌
[16/22] Extracting [TeamsTeam]...
    |---[1/5] Digital Initiative Public Relations✅
    |---[2/5] U.S. Sales✅
    |---[3/5] Mark 8 Project Team✅
    |---[4/5] Sales and Marketing✅
    |---[5/5] Retail✅
[17/22] Extracting [TeamsTenantDialPlan]...❌
[18/22] Extracting [TeamsUpgradeConfiguration]...❌
[19/22] Extracting [TeamsUpgradePolicy]...❌
[20/22] Extracting [TeamsUser]...    
Broke extraction process down into {5} jobs of {1} item(s) each✅
[21/22] Extracting [TeamsVoiceRoute]...❌
[22/22] Extracting [TeamsVoiceRoutingPolicy]...❌
⌛ Export took {1482 seconds}

**Comment by tmcomeau** [comment]
In manually testing with the MicrosoftTeams module I am receiving the below error regarding basic authentication being disabled. I will investigate this next.

PS C:\WINDOWS\system32> Connect-MicrosoftTeams

Account                       Environment Tenant                               TenantId                            
-------                       ----------- ------                               --------                            
tcomeau@y2zj1.onmicrosoft.com AzureCloud  ca08493a-c9c8-4db0-a9e8-d3b4bafac269 ca08493a-c9c8-4db0-a9e8-d3b4bafac269



PS C:\WINDOWS\system32> Get-CsMeetingConfiguration
Get-CsMeetingConfiguration : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : **_**_The 
**_WinRM client cannot process the request. Basic authentication is currently disabled in the client configuration._**_** Change the client configuration_** and 
try the request again. For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ Get-CsMeetingConfiguration
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-CsMeetingConfiguration], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Teams.ConfigApi.Cmdlets.GetCsMeetingCon 
   figuration

**Comment by tmcomeau** [comment]
This issue appears to have been resolved by addressing the WinRM error:

Enabling Basic Authentication for WinRM Client
To fix the WinRM client error, launch the registry and navigate to the following key:
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WinRM\Client

From here, locate the DWORD named Allow Basic and double-click on it. The value is likely set to 0 at the moment. Change this value to 1, which will enable basic authentication. Click Ok.

Source: https://supertekboy.com/2020/06/13/hybrid-configuration-wizard-fails-winrm-client-cannot-process-the-request/#:~:text=Change%20the%20client%20configuration%20and%20try%20the%20request,to%20security%20being%20hardened%20in%20the%20operating%20system.

Successful Export:

Connecting to {MicrosoftTeams}...✅
[1/22] Extracting [TeamsCallingPolicy]...
    |---[1/5] Global✅
    |---[2/5] Tag:AllowCalling✅
    |---[3/5] Tag:AllowCallingPreventTollBypass✅
    |---[4/5] Tag:AllowCallingPreventForwardingtoPhone✅
    |---[5/5] Tag:DisallowCalling✅
[2/22] Extracting [TeamsChannel]...
    |---[1/5] Team {Sales and Marketing}
        |---[1/2] General✅
        |---[2/2] Monthly Reports✅
    |---[2/5] Team {U.S. Sales}
        |---[1/3] Sales West✅
        |---[2/3] Sales East✅
        |---[3/3] General✅
    |---[3/5] Team {Retail}
        |---[1/1] General✅
    |---[4/5] Team {Digital Initiative Public Relations}
        |---[1/1] General✅
    |---[5/5] Team {Mark 8 Project Team}
        |---[1/4] Research and Development✅
        |---[2/4] Digital Assets Web✅
        |---[3/4] Design✅
        |---[4/4] General✅
[3/22] Extracting [TeamsChannelsPolicy]...
    |---[1/2] Global✅
    |---[2/2] Tag:Default✅
[4/22] Extracting [TeamsClientConfiguration]...✅
[5/22] Extracting [TeamsEmergencyCallingPolicy]...
    |---[1/1] Global✅
[6/22] Extracting [TeamsEmergencyCallRoutingPolicy]...
    |---[1/1] Global✅
[7/22] Extracting [TeamsGuestCallingConfiguration]...✅
[8/22] Extracting [TeamsGuestMeetingConfiguration]...✅
[9/22] Extracting [TeamsGuestMessagingConfiguration]...✅
[10/22] Extracting [TeamsMeetingBroadcastConfiguration]...✅
[11/22] Extracting [TeamsMeetingBroadcastPolicy]...
    |---[1/2] Global✅
    |---[2/2] Tag:Default✅
[12/22] Extracting [TeamsMeetingConfiguration]...✅
[13/22] Extracting [TeamsMeetingPolicy]...
    |---[1/8] Global✅
    |---[2/8] Tag:Test Draft Teams Minimum Viable Secure Configuration Baseline✅
    |---[3/8] Tag:AllOn✅
    |---[4/8] Tag:RestrictedAnonymousAccess✅
    |---[5/8] Tag:AllOff✅
    |---[6/8] Tag:RestrictedAnonymousNoRecording✅
    |---[7/8] Tag:Default✅
    |---[8/8] Tag:Kiosk✅
[14/22] Extracting [TeamsMessagingPolicy]...
    |---[1/4] Global✅
    |---[2/4] Tag:Default✅
    |---[3/4] Tag:EduFaculty✅
    |---[4/4] Tag:EduStudent✅
[15/22] Extracting [TeamsPstnUsage]...✅
[16/22] Extracting [TeamsTeam]...
    |---[1/5] Sales and Marketing✅
    |---[2/5] U.S. Sales✅
    |---[3/5] Digital Initiative Public Relations✅
    |---[4/5] Retail✅
    |---[5/5] Mark 8 Project Team✅
[17/22] Extracting [TeamsTenantDialPlan]...
    |---[1/1] Global✅
[18/22] Extracting [TeamsUpgradeConfiguration]...✅
[19/22] Extracting [TeamsUpgradePolicy]...
    |---[1/10] Global✅
    |---[2/10] UpgradeToTeams✅
    |---[3/10] Islands✅
    |---[4/10] IslandsWithNotify✅
    |---[5/10] SfBOnly✅
    |---[6/10] SfBOnlyWithNotify✅
    |---[7/10] SfBWithTeamsCollab✅
    |---[8/10] SfBWithTeamsCollabWithNotify✅
    |---[9/10] SfBWithTeamsCollabAndMeetings✅
    |---[10/10] SfBWithTeamsCollabAndMeetingsWithNotify✅
[20/22] Extracting [TeamsUser]...    
Broke extraction process down into {5} jobs of {1} item(s) each✅
[21/22] Extracting [TeamsVoiceRoute]...
    |---[1/1] LocalRoute✅
[22/22] Extracting [TeamsVoiceRoutingPolicy]...
    |---[1/1] Global✅
⌛ Export took {1700 seconds}
