### ISSUE TITLE
Version of the Module Compatible with Linux

### ISSUE THREAD

**Issue by shurick81** [microsoft/Microsoft365DSC#1744]
### Description

It would be great to be able to be able to use this module on Linux containers. This would allow a better module distribution via Docker Hub.

### Proposed properties

It could be the same module or a separate module just for Linux.

**Comment by andikrueger** [comment]
There is already a discussion about this topic. Currently, there are restrictions due to the Teams PowerShell Module. This one need Windows to be run. See: https://github.com/microsoft/Microsoft365DSC/discussions/1703
