### ISSUE TITLE
TeamsChannel: Resource uniqueness for exports - New key is needed

### ISSUE THREAD

**Issue by andikrueger** [microsoft/Microsoft365DSC#1746]
Extraction works on my end with M365DSC V 1.22.119.2. 

![image](https://user-images.githubusercontent.com/15608729/150585736-3019d985-866f-49cb-9cda-78de30c506ae.png)

The extraction looks good but the configuration can not be compiled as we do have duplicate elements within the configuration - The mof file is named accordingly: `localhost.mof.error`

```powershell
       TeamsChannel 7f8d78b7-4d6a-4898-ae3b-13527be9e831
        {
            Credential           = $Credscredential;
            DisplayName          = "General";
            Ensure               = "Absent";
            TeamName             = "IT";
        }
        .....
        TeamsChannel e7bdd703-d005-4ae2-9dd4-fc644a7e3db7
        {
            Credential           = $Credscredential;
            DisplayName          = "General";
            Ensure               = "Absent";
            TeamName             = "IT";
        }
``` 

The TeamsTeam resources do have `GroupID` so that we can differentiate the teams. The `TeamsTeam` has handling for that in place: https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTeam/MSFT_TeamsTeam.psm1#L148-L173

Either we should introduce this for `TeamsChannel` too, or we need some other key. This would not need to be a breaking change, as we would only need to add the `groupId` to this resource.

_Originally posted by @andikrueger in https://github.com/microsoft/Microsoft365DSC/issues/1579#issuecomment-1018789279_

**Comment by NikCharlebois** [comment]
The challenge is that simply adding GroupID as a parameter won't do it. It would need to be added as a Key parameter, which means it would become mandatory. We can't expect users writing a configuration for a new tenant to provide a group id because that group doesn't exist. This will almost always be an issue when we have multiple Teams with the same name.

**Comment by andikrueger** [comment]
Woudnät it be more sufficient to add the TeamsChannel Resource as a paramter- sub set to the TeamsTeams resource then? There can't be a TeamsChannel without the TeamsTeam then.

This would also solve a problem of dependencies between resources.

**Comment by andikrueger** [comment]
Your PR looks good and makes it easier in the export and validate scenario. Setting up a new Tenant based on the export would still be an issue.
