### ISSUE TITLE
microsoft365dsc.com display issue on portrait displays

### ISSUE THREAD

**Issue by p-bojkowski** [microsoft/Microsoft365DSC#1747]
![image](https://user-images.githubusercontent.com/74313141/153027231-72655f58-b448-4122-87e8-ace39b6465ac.png)

![image](https://user-images.githubusercontent.com/74313141/153027265-f71850a6-d32c-4b26-a079-1e4a5860234a.png)

![image](https://user-images.githubusercontent.com/74313141/153027379-dec75386-bbeb-43f1-bc5e-ca4b5526de8e.png)

**Comment by andikrueger** [comment]
@Laskewitz could you take a look this?

**Comment by andikrueger** [comment]
@p-bojkowski Last time I checked, this issue was resolved. Can you confirm?

**Comment by p-bojkowski** [comment]
@andikrueger is working! thx!
