### ISSUE TITLE
Generated export command excludes resources

### ISSUE THREAD

**Issue by ykuijs** [microsoft/Microsoft365DSC#1759]
When I generate an export on the export.microsoft365dsc.com website, select all resources and select Application as Authentication method, running the command gives me this prompt:
<img width="923" alt="image" src="https://user-images.githubusercontent.com/15103891/153609201-ababfe6f-7d02-402b-b822-5c11ecb2c2f7.png">

Wouldn't it make sense to disable all resources that don't support the selected authentication method on the Export page?

**Comment by andikrueger** [comment]
This would make a lot of sense. We would need this information somewhere for the website. Maybe we could add this information to the settings files too (see  #1751)

**Comment by ykuijs** [comment]
I am working on an update of the Export functionality that will add support for specifying multiple authentication method. When you do, the code will use the most secure method that is the greatest denominator between what is provided on the command line and what is supported by the resource. It is using the following order (from most secure to less secure): **Certificate Thumbprint, Certificate Path, Application Secret, Credential**

For example:
- The resource supports Credential and CertificatePath
- For the Export-M365DSCConfiguration Credential, CertificatePath and CertificateThumbprint are specified.

Since the resource does not support CertificateThumbprint, the code is then using CertificatePath to export the resource.
