### ISSUE TITLE
EXOOrganizationConfig: Attribute AllowPlusAddressInRecipients  not configureable

### ISSUE THREAD

**Issue by T630Dev** [microsoft/Microsoft365DSC#1766]
#### Details of the scenario you tried and the problem that is occurring
Set-OrganizationConfig -AllowPlusAddressInRecipients 
is no valid attribute in the EXOOrganizationConfig DSC res.

#### Suggested solution to the issue
Please add this to the existing res.

**Comment by malauter** [comment]
AllowPlusAddressInRecipients attribute was added in PR #1770
