### ISSUE TITLE
Microsoft365DSC Drift Report

### ISSUE THREAD

**Issue by datanet76** [microsoft/Microsoft365DSC#1768]

**Comment by NikCharlebois** [comment]
Can you provide additional details as to what the issue at hand is?

**Comment by NikCharlebois** [comment]
What errors are you getting when running it from a Scheduled Task?

**Comment by datanet76** [comment]
It runs but doesn’t do what’s supposed to do - that’s not a priority now.
I’d like to fix the second issue first and come back to #1.

Sent from Yahoo Mail for iPhone


On Thursday, February 17, 2022, 2:03 PM, Nik Charlebois ***@***.***> wrote:




What errors are you getting when running it from a Scheduled Task?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by datanet76** [comment]
Would like to go about how to add the conditional script to send email if there is any drift situation

**Comment by Kirikou974** [comment]
Hello,

Every -CliXml command uses data protection API to encrypt data using current user information.
So my guess is that you have some sort of secure string in your creddev.xml file.
The secure string was encrypted using a key tied to a specific account on a specific machine hence the error message you get.
You need to create a key and store it somewhere your scheduled task account has access to.
Have a look at this discussion: https://stackoverflow.com/questions/54923903/powershell-script-not-working-using-import-clixml-command
And this article : https://www.altaro.com/msp-dojo/encrypt-password-powershell/
This doesn't have much to do with M365DSC IMHO.

**Comment by ykuijs** [comment]
This is about a custom script, but the script itself isn't provided. This makes troubleshooting or providing pointers very difficult.

Also, as mentioned by Kirikou974, this issue isn't related to M365DSC specific, but is about the DPAPI. That is why I am closing the issue now.

If you have any more questions, please reopen the issue and provide a little more information, preferably the script you are having issues with.

**Comment by Nilas1994** [comment]
i precisely got this problem too when the script is at startup it looks like it is relying on some services that aren't fully initialized at startup so i implemented a event based check until all  services are running and delay the script for some time. try to implement at retry mechanism in your script could help.
