### ISSUE TITLE
SPOStorageEntity Getting Access Denied on Tenant wide Entity Creation

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#177]
#### Details of the scenario you tried and the problem that is occurring
The Set-PnPStorageEntity call within the Set-TargetResource method of the SPOStorageEntity resource throws an access denied error, even when the GlobalAdminAccount is used.

Same goes with the Set-SPOStorageEntity cmdlet using the SharePointOnline platform.

#### Verbose logs showing the problem
Set-PnPStorageEntity : Access denied. You do not have permission to perform this action or
access this resource.

#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
SPOStorageEntity TenantEntity1
{
            Key                = "TenantEntity1"
            Value              = "Tenant Value"
            Description        = "Entity for Tenant"
            EntityScope        = "Tenant"
            SiteUrl            = "https://o365dsc-admin.sharepoint.com/"
            GlobalAdminAccount = $GlobalAdmin
            Ensure             = "Present"
}
```

#### The operating system the target node is running
Windows 10

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.0.0.776

**Comment by heinrich-ulbricht** [comment]
One of our customers currently has the same problem. 

Using Tenant Admin we get the error: 
```
Set-PnPStorageEntity : Access denied. You do not have permission to perform this action or access this resource.
In Zeile:1 Zeichen:1
+ Set-PnPStorageEntity -Key LanguageConfig -Value $languageJsonString - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPStorageEntity], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.SetPnPStorageEntity

```

**Comment by heinrich-ulbricht** [comment]
@NikCharlebois Could you try again after making the user running `Set-PnPStorageEntity` site collection administrator of the app catalog site?

**Comment by NikCharlebois** [comment]
It appears that being Tenant Admin doesn't cut it, and that you indeed need to be a site owner on top of it. Thanks @heinrich-ulbricht . Will update accordingly with a proper error message if user doesn't have proper permissions.

**Comment by heinrich-ulbricht** [comment]
@NikCharlebois Cool, you're welcome. When writing "site owner" - do you mean site collection administrator or indeed member of the Owners group? Didn't test the last one.

**Comment by heinrich-ulbricht** [comment]
Just checked, membership in the Owners group is enough. No need to be site collection admin.

**Comment by NikCharlebois** [comment]
Will implement a meaningful verbose error message in the logic first and then will close. Thanks again

**Comment by heinrich-ulbricht** [comment]
@NikCharlebois Just as a heads-up: you might also run into issues when provisioning site collection app catalog properties on no-script sites. Same error message, different cause. PR for the documentation is pending: https://github.com/SharePoint/sp-dev-docs/pull/4428

**Comment by NikCharlebois** [comment]
Thanks @heinrich-ulbricht the team really appreciates you helping out and providing your feedback and expertise!
