### ISSUE TITLE
EXOAtpPolicyForO365: Attribute EnableSafeLinksForWebAccessCompanion not configureable

### ISSUE THREAD

**Issue by 3348163** [microsoft/Microsoft365DSC#1777]
#### Details of the scenario you tried and the problem that is occurring
Set-AtpPolicyForO365 -EnableSafeLinksForWebAccessCompanion $true 
is no valid attribute in the EXOAtpPolicyForO365 DSC res.
#### Suggested solution to the issue
Please add this to the existing res.

**Comment by malauter** [comment]
In the documentation this attribute is marked as reserved for internal Microsoft use. Why is this attribute needed?

https://docs.microsoft.com/en-us/powershell/module/exchange/set-atppolicyforo365?view=exchange-ps#parameters

**Comment by 3348163** [comment]
I've talked with the collegue who wanted me to canfigure this setting and he could not give any reason. So the issue can be closed.
