### ISSUE TITLE
sharepoint online content deleted by system account

### ISSUE THREAD

**Issue by soundd2** [microsoft/Microsoft365DSC#1788]
We have noticed sharepoint online content deleted by system account
It's available in recycle bin but before restoring we want to know how it's deleted and I believe it might have done by retention policy settings.

How do we make sure sharepoint style library and assets library which are holding of CSS and JS files are exception from this retention policy, is there any way to do that with the help of Sharepoint online DSC script and CI CD pipeline? If yes please help

Also first of all how do we figure out whether retention policy applied to these assets and style libraries and also for other sharepoint sites as well , do we have any method using sharepoint DSC script and CI/CD?

Please assist on this. Thank you.

**Comment by andikrueger** [comment]
Please refer to the official Microsoft Documentation for this topic to get a better overview on the underlying concept of retention and how it works in SharePoint and OneDrive: https://docs.microsoft.com/en-us/microsoft-365/compliance/retention-policies-sharepoint?view=o365-worldwide

With Microsoft 365 DSC there are a few options on how to manage labels - But they are not that granular as that it would be possible to manage retention on objects within site collections.

**Comment by ykuijs** [comment]
As @andikrueger mentions: This sounds like an issue with configuring and managing default Microsoft 365 features.

Microsoft365DSC is able to create policies programmatically, just like you are able to do manually using the Admin Portal. If a created policy does something unexpected, you have to make sure you check the policy settings to see if they are really what you wanted. Within this project we are able to support you with questions about Microsoft365DSC, but don't have the resources to support generic Microsoft 365 questions unfortunately. There are other channels for that, like Microsoft support and support forums: https://docs.microsoft.com/en-us/answers/index.html

Closing this issue now.
