### ISSUE TITLE
Issue exporting microsoft365dsc configuration via powershell

### ISSUE THREAD

**Issue by yingying96** [microsoft/Microsoft365DSC#1791]
Hi Team,

I was trying to export the configurations but failed. 
Could it be related to the authentication credential? Should i use my test admin account xxx@company.onmicrosoft.com OR should i use my company domain account for the credential prompt?

![image](https://user-images.githubusercontent.com/19566726/156131694-a68071fb-e193-4de0-b6c7-9af888c35ead.png)

**Comment by ykuijs** [comment]
Looks like the PackageManagement module you have installed is very old, v1.0.0.1. I have v.1.4.7 on my machine.

Can you please check to run the following commands:
```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 
Install-Module PowerShellGet -RequiredVersion 2.2.4 -SkipPublisherCheck
```
And then try to run the `Update-M365DSCDependencies` cmdlet to install all required modules?

**Comment by yingying96** [comment]
Yes that works now. I think now it manage to reach till the token part?
Seems like it is having issues connecting. 

![image](https://user-images.githubusercontent.com/19566726/156149310-ccef24b1-9ff2-4130-830f-9f12319408eb.png)

**Comment by andikrueger** [comment]
Did you install the dependencies for Microsoft365DSC? `Update-M365DSCDependencies` is required to install all modules in the required version for Microsoft 365 DSC.

**Comment by yingying96** [comment]
Yup that's right. I installed the dependencies using the command.

**Comment by andikrueger** [comment]
Could you run `Get-Command Get-MgProfile` and post the outcome?

**Comment by yingying96** [comment]
Here you go!
![image](https://user-images.githubusercontent.com/19566726/156159593-0d0cf892-3df1-4449-bb3d-506303bffb6c.png)

**Comment by andikrueger** [comment]
![image](https://user-images.githubusercontent.com/15608729/156159893-f56d457d-c88b-4499-9500-02a7c5052e8b.png)
The outcome should look like this. Please review the command. Something is not correct.

**Comment by yingying96** [comment]
Hmm I'm thinking if i'm missing modules?


![image](https://user-images.githubusercontent.com/19566726/156160359-e2e4c908-011b-40f0-93f7-075ce86031aa.png)

**Comment by andikrueger** [comment]
Could you test it in an new ps session?

**Comment by yingying96** [comment]
![image](https://user-images.githubusercontent.com/19566726/156162031-42981c6f-0fa8-43d2-829d-7eb0e0310ccd.png)

**Comment by andikrueger** [comment]
Could you run the following command too `Get-InstalledModule Microsoft.Graph*`

**Comment by yingying96** [comment]
![image](https://user-images.githubusercontent.com/19566726/156169326-14ffc4f3-94f1-44d0-8627-a90ad554b9f2.png)

**Comment by andikrueger** [comment]
First look, it's okay. Would you be able the update to the latest version of Micorosft365DSC and run the following commands? These should update all modules to the latest versions and then uninstall all previous version of the module itself and all outdated dependencies.

```powershell
Update-Module microsoft365dsc
Update-M365DSCDependencies
Uninstall-M365DSCOutdatedDependencies
Update-M365DSCAllowedGraphScopes -All -Type Read
```

This should make sure your system is having all the latest parts needed for a successful export and have the needed permissions within aad.

**Comment by yingying96** [comment]
Works now! Thank you!
