### ISSUE TITLE
DevOps Pipeline Release issue

### ISSUE THREAD

**Issue by BurgerhoutJ** [microsoft/Microsoft365DSC#1794]
Hi,

I build the DevOps Part via the manual as provided via the website.
The Repo and the Pipeline part is working fine, but the Release part is not working, as you can see in the screenshot below,

![image](https://user-images.githubusercontent.com/25769575/156162820-bfb89473-829a-4e4c-b7c8-4385ce559be5.png)

So I opened the generated MOF-file, and I see that the value of Credential = NULL.
![image](https://user-images.githubusercontent.com/25769575/156163020-d41eb6a5-055e-4fe6-81a9-5dbe780d4866.png)

Is it possible that the issue is, that the pipeline can't connect to Azure Key vault? Or the wrong credentials retrieved?

PDF -> [Managing Microsoft 365 with Microsoft365Dsc and Azure DevOps.pdf](https://github.com/microsoft/Microsoft365DSC/files/8161234/Managing.Microsoft.365.with.Microsoft365Dsc.and.Azure.DevOps.pdf)

**Comment by Kirikou974** [comment]
Hello, 

Can you share some details regarding the PS1 you use to generated the MOF file ? 
I might be able to help as I am using azure devops as well with M365DSC.

**Comment by Kirikou974** [comment]
Pretty extensively if I may say so :P
![image](https://user-images.githubusercontent.com/21690437/158560036-0d01b858-bd21-4b80-8298-89771c33c8bf.png)

**Comment by BurgerhoutJ** [comment]
Hi @Kirikou974, The build.ps1 script is as follows:

function Write-Log
{
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [System.String]
        $Message
    )

    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    Write-Host "$timestamp - $Message"
}

Write-Log -Message 'Checking for presence of Microsoft365Dsc module and all required modules'
Write-Log -Message ' '

$modules = Import-PowerShellDataFile -Path '.\DscResources.psd1'

$workingDirectory = $PSScriptRoot

if ($modules.ContainsKey("Microsoft365Dsc"))
{
    Write-Log -Message 'Checking Microsoft365Dsc version'
    $psGalleryVersion = $modules.Microsoft365Dsc
    $localModule = Get-Module 'Microsoft365Dsc' -ListAvailable

    Write-Log -Message "- Required version: $psGalleryVersion"
    Write-Log -Message "- Installed version: $($localModule.Version)"
    Write-Log -Message ' '

    if ($localModule.Version -ne $psGalleryVersion)
    {
        Write-Log -Message 'Incorrect version installed. Removing current module.'
        foreach ($requiredModule in $localModule.RequiredModules)
        {
            $requiredModulePath = Join-Path -Path 'C:\Program Files\WindowsPowerShell\Modules' -ChildPath $requiredModule.Name
            Remove-Item -Path $requiredModulePath -Force -Recurse -ErrorAction 'SilentlyContinue'
        }

        Write-Log -Message 'Installing Microsoft365Dsc and required modules'
        Set-PSRepository -Name 'PSGallery' -InstallationPolicy 'Trusted'
        # Install-Module -Name 'Microsoft365Dsc' -RequiredVersion $psGalleryVersion -AllowClobber
        Update-Module -Name 'Microsoft365Dsc' -RequiredVersion $psGalleryVersion -AllowClobber

        Write-Log -Message 'Modules installed successfully!'
        Write-Log -Message ' '
    }
    else
    {
        Write-Log -Message 'Correct version installed, continuing.'
        Write-Log -Message ' '
    }
}
else
{
    Write-Log "[ERROR] Unable to find Microsoft365Dsc in DscResources.psd1. Cancelling!"
    exit
}

Write-Log -Message 'Compiling configuration to MOF'

$outputFolder = Join-Path -Path $workingDirectory -ChildPath 'Output'

Write-Log -Message 'Loading configuration'
. .\M365Configuration.ps1

$password = ConvertTo-SecureString -String $env:SAPW -AsPlainText -Force
$username = "DscConfigAdmin@tenant.onmicrosoft.com"
$cred = New-Object System.Management.Automation.PSCredential($username, $password)

if (-not (Test-Path -Path $outputFolder))
{
    $null = New-Item -Path $outputFolder -ItemType 'Directory'
}

Write-Log -Message 'Start compilation'
$null = ConfigureMicrosoft365 -credsGlobalAdmin $cred -ConfigurationData .\M365ConfigurationData.psd1 -OutputPath $outputFolder

Copy-Item -Path 'DscResources.psd1' -Destination $outputFolder
Copy-Item -Path 'deploy.ps1' -Destination $outputFolder

**Comment by ykuijs** [comment]
@BurgerhoutJ Can you share a little more logging from DevOps?

**Comment by BurgerhoutJ** [comment]
@ykuijs Don't know what exactly you want to see, but this is what I see.
![image](https://user-images.githubusercontent.com/25769575/168226560-d85deba3-b975-4dfc-931c-e56cacebbb02.png)

**Comment by BurgerhoutJ** [comment]
@ykuijs Found the logs files. You can download it from https://theorange.cat/devops/ReleaseLogs_3.zip

**Comment by ykuijs** [comment]
Hi @BurgerhoutJ, sorry for the late reply. I kind of lost track of your issue.

The release pipeline tries to deploy the MOF file generated in the Build step. The screenshot you shared shows that the Credentials in the MOF file are NULL, which means that the Build pipeline does not generate a correct MOF file. Could you please share the log file from the Build pipeline, so I can check what is going on there?

**Comment by BurgerhoutJ** [comment]
Hi @ykuijs, Didn't had the time to check this out. Please leave it for now. Don't have the time to further investigate it. Maybe I need to start from scratch. But not now. So I will close this one.
