### ISSUE TITLE
New-M365DSCReportFromConfiguration -Type HTM does not include retention policies from SC

### ISSUE THREAD

**Issue by Chabango** [microsoft/Microsoft365DSC#1801]
#### Details of the scenario you tried and the problem that is occurring

When running  `New-M365DSCReportFromConfiguration -Type HTML -Configurationpath C:\Microsoft365DSC-test\2022-03-03_TestTenantConfig.ps1 -OutputPath C:\Microsoft365DSC-test\Test_Report.html`   I am not seeing any of the Retention polices that are configured in the Compliance center. The test one I am trying to validate against shows up in the 2022-03-03_TestTenantConfig.ps1 file but is not listed in the HTML output file, Test_Report.html or in excel. it doe snto list any of the SCRetentionCompliancePolicy settings, only the SCDLPCompliancePolicy and no other setting within SC.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell - using the 

Name                           Value                                                                                                                                                              
----                           -----                                                                                                                                                              
PSVersion                      5.1.17763.2268                                                                                                                                                     
PSEdition                      Desktop                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                            
BuildVersion                   10.0.17763.2268                                                                                                                                                    
CLRVersion                     4.0.30319.42000                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                
SerializationVersion           1.1.0.1 
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.209.1

**Comment by Chabango** [comment]
@andikrueger , do you know if this has been updated? It is still not working for me. Thank you

**Comment by NikCharlebois** [comment]
We cannot replicate, can you please confirm that this is still an issue with the latest versions and provide additional context about the issue if it is. Thanks

**Comment by thacold1** [comment]
I'm not having the exact same issue as ChaBango, but when I run that cmdlet, it generates a blank Html file or an empty excel file. I running the latest version of DSC.

**Comment by andikrueger** [comment]
Todays version?

**Comment by thacold1** [comment]
I only have 720.1...I provided the sample cmdlet I ran. The HTML is blank, and the excel file only has three headings with no content. 

PS C:\Users\seadoo> Get-InstalledModule Microsoft365DSC

Version    Name                                Repository           Description                                                                
-------    ----                                ----------           -----------                                                                
1.22.720.1 Microsoft365DSC                     PSGallery            This DSC module is used to configure and monitor Microsoft tenants, incl...

PS C:\Users\seadoo> New-M365DSCReportFromConfiguration -Type Html -ConfigurationPath C:\JetskiNation\DSC\Intune\Intune_ConfigsP1.ps1 -OutputPath C:\JetskiNation\DSC\Intune\Report.html 

Loading file 'C:\JetskiNation\DSC\Intune\Intune_ConfigsP1.ps1'
Generating HTML report
Saving HTML report
Completed generating HTML report

PS C:\Users\seadoo> New-M365DSCReportFromConfiguration -Type Excel -ConfigurationPath C:\JetskiNation\DSC\Intune\Intune_ConfigsP1.ps1 -OutputPath C:\JetskiNation\DSC\Intune\Report1.xlsx

(Excel Results sample)
Component   Name | Property | Value |   |  
-- | -- | -- | -- | --

**Comment by thacold1** [comment]
I run an update and 727.1 didn't install.

**Comment by andikrueger** [comment]
There are a few improvements in regards to reporting in this release. 

Could you try to run 

Uninstall-M365DSCOutdatedDependencies

to make sure there are no older versions of the module and resources on your system.

**Comment by thacold1** [comment]
That worked perfectly. So it didn't update to 727.1, but I was able to generate the reports after running the "Uninstall" cmdlet. Thanks!!!

**Comment by andikrueger** [comment]
Awesome. This issue would be fixed with the 727 version, as there is a warning message, if there are older versions of the module or its dependencies.

**Comment by Chabango** [comment]
I will update and test now.


***@***.***<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fsecure-web.cisco.com%2F1q8Mf1w_9vN5jtppFYG6_NSY4hjTGb4D9pjmEZ7gNus0rwB4wGEGSkL86SrRZ7e9WBZYyWzW0ArjzmDW08tecrn_PpZRmJeQGJRRYRI0B3mun52VFFWs8scgltvcTnB_6IjvPKTxHLDrW1cWEBFfmkzff2pnaXPVc0Dh3yM7vsXy0FG7rOjtakrgAinLQv20RNusf98FMIc0R9NR8QRAXrg%2Fhttp%253A%252F%252Fwww.ecstech.com%252F&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7C8581b87e2e904b44f90908da60dd4889%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637928800765043752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7mw3fCk0p5zjR4UIwRbnwADrlUTMjbLO1riMd%2F3u5SI%3D&reserved=0>
Chuck Bost
ODT / OIMT
Microsoft 365 EaaS /  Microsoft 365 Integration
Mobile:  240.460.7124
https://ecstech.com/<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fecstech.com%2F&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7Cb6683d3020ff44f2715e08da60f3749b%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637928895988668782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cnoc6C6B1BZk4sP11jf2Dpj9XbfnaDOKWFPML2bbS5M%3D&reserved=0>


From: thacold1 ***@***.***>
Sent: Wednesday, July 27, 2022 2:06 PM
To: microsoft/Microsoft365DSC ***@***.***>
Cc: Bost, Charles * ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/Microsoft365DSC] New-M365DSCReportFromConfiguration -Type HTM does not include retention policies from SC (Issue #1801)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


I only have 720.1...I provided the sample cmdlet I ran. The HTML is blank, and the excel file only has three headings with no content.

PS C:\Users\seadoo> Get-InstalledModule Microsoft365DSC

Version Name Repository Description

________________________________

1.22.720.1 Microsoft365DSC PSGallery This DSC module is used to configure and monitor Microsoft tenants, incl...

PS C:\Users\seadoo> New-M365DSCReportFromConfiguration -Type Html -ConfigurationPath C:\JetskiNation\DSC\Intune\Intune_ConfigsP1.ps1 -OutputPath C:\JetskiNation\DSC\Intune\Report.html

Loading file 'C:\JetskiNation\DSC\Intune\Intune_ConfigsP1.ps1'
Generating HTML report
Saving HTML report
Completed generating HTML report

PS C:\Users\seadoo> New-M365DSCReportFromConfiguration -Type Excel -ConfigurationPath C:\JetskiNation\DSC\Intune\Intune_ConfigsP1.ps1 -OutputPath C:\JetskiNation\DSC\Intune\Report1.xlsx

(Excel Results sample)
Component Name
Property
Value



-

**Comment by Chabango** [comment]
Where is the 727 version?
I just updates and it is 720


***@***.***<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fsecure-web.cisco.com%2F1q8Mf1w_9vN5jtppFYG6_NSY4hjTGb4D9pjmEZ7gNus0rwB4wGEGSkL86SrRZ7e9WBZYyWzW0ArjzmDW08tecrn_PpZRmJeQGJRRYRI0B3mun52VFFWs8scgltvcTnB_6IjvPKTxHLDrW1cWEBFfmkzff2pnaXPVc0Dh3yM7vsXy0FG7rOjtakrgAinLQv20RNusf98FMIc0R9NR8QRAXrg%2Fhttp%253A%252F%252Fwww.ecstech.com%252F&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7C8581b87e2e904b44f90908da60dd4889%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637928800765043752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7mw3fCk0p5zjR4UIwRbnwADrlUTMjbLO1riMd%2F3u5SI%3D&reserved=0>
Chuck Bost
ODT / OIMT
Microsoft 365 EaaS /  Microsoft 365 Integration
Mobile:  240.460.7124
https://ecstech.com/<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fecstech.com%2F&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7Cb6683d3020ff44f2715e08da60f3749b%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637928895988668782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cnoc6C6B1BZk4sP11jf2Dpj9XbfnaDOKWFPML2bbS5M%3D&reserved=0>


From: Andi Krüger ***@***.***>
Sent: Wednesday, July 27, 2022 2:21 PM
To: microsoft/Microsoft365DSC ***@***.***>
Cc: Bost, Charles * ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/Microsoft365DSC] New-M365DSCReportFromConfiguration -Type HTM does not include retention policies from SC (Issue #1801)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Awesome. This issue would be fixed with the 727 version, as there is a warning message, if there are older versions of the module or its dependencies.

-

**Comment by thacold1** [comment]
@Chabango you have to run the uninstall outdated dependencies cmdlet

**Comment by Chabango** [comment]
Did that first.
The ran Update-Module Microsoft365DSC
When running:
Get-Module Microsoft365DSC -ListAvailable | select ModuleBase, Version
I see:

ModuleBase                                                            Version
----------                                                            -------
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.720.1 1.22.720.1

***@***.***<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fsecure-web.cisco.com%2F1q8Mf1w_9vN5jtppFYG6_NSY4hjTGb4D9pjmEZ7gNus0rwB4wGEGSkL86SrRZ7e9WBZYyWzW0ArjzmDW08tecrn_PpZRmJeQGJRRYRI0B3mun52VFFWs8scgltvcTnB_6IjvPKTxHLDrW1cWEBFfmkzff2pnaXPVc0Dh3yM7vsXy0FG7rOjtakrgAinLQv20RNusf98FMIc0R9NR8QRAXrg%2Fhttp%253A%252F%252Fwww.ecstech.com%252F&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7C8581b87e2e904b44f90908da60dd4889%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637928800765043752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7mw3fCk0p5zjR4UIwRbnwADrlUTMjbLO1riMd%2F3u5SI%3D&reserved=0>
Chuck Bost
ODT / OIMT
Microsoft 365 EaaS /  Microsoft 365 Integration
Mobile:  240.460.7124
https://ecstech.com/<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fecstech.com%2F&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7Cb6683d3020ff44f2715e08da60f3749b%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637928895988668782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cnoc6C6B1BZk4sP11jf2Dpj9XbfnaDOKWFPML2bbS5M%3D&reserved=0>


From: thacold1 ***@***.***>
Sent: Wednesday, July 27, 2022 3:07 PM
To: microsoft/Microsoft365DSC ***@***.***>
Cc: Bost, Charles * ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/Microsoft365DSC] New-M365DSCReportFromConfiguration -Type HTM does not include retention policies from SC (Issue #1801)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@Chabango<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsecure-web.cisco.com%2F1QWYbk5EI843ZmGE4j5aADvipIuQYo1CmipRYtcPJJYxZDIPXbCxK0C3QkCnGaukN62nE3t189hCxNpYknjWKg82mR_5u9PwOkm_2RRb1ylKbsVcr_xL0KxrQnMzdr2WkxUyS5oF12KpdzTMHuhrUgF1iJiIKtuOtyoGL3_UhDOYPLNFzViaGqVSPXvqGopL0YTulBrhr8B7xWiOmshNCwA%2Fhttps%253A%252F%252Fgithub.com%252FChabango&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7C29d7ae58095249f551e508da700339f7%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637945456402414997%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LmB5JEEOAFhev2VYIWUg7GhL%2FLsqMxQFdchYPX0Ovhk%3D&reserved=0> you have to run the uninstall outdated dependencies cmdlet

-

**Comment by andikrueger** [comment]
It might be possible, that the 727 version is not published to the powershell gallery yet. https://github.com/microsoft/Microsoft365DSC/releases/tag/1.22.727.1
It’s just 4 hours old.

**Comment by NikCharlebois** [comment]
We are trying to troubleshoot an issue with the PowerShell Gallery team where we are currently getting a 500 Server Unavailable error trying to publish the release.

**Comment by Chabango** [comment]
Still not able to install the 727 version even after uninstalling all versions.
The Install-Module Microsoft365DSC -Force is only installing the 720 version.


***@***.***<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fsecure-web.cisco.com%2F1q8Mf1w_9vN5jtppFYG6_NSY4hjTGb4D9pjmEZ7gNus0rwB4wGEGSkL86SrRZ7e9WBZYyWzW0ArjzmDW08tecrn_PpZRmJeQGJRRYRI0B3mun52VFFWs8scgltvcTnB_6IjvPKTxHLDrW1cWEBFfmkzff2pnaXPVc0Dh3yM7vsXy0FG7rOjtakrgAinLQv20RNusf98FMIc0R9NR8QRAXrg%2Fhttp%253A%252F%252Fwww.ecstech.com%252F&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7C8581b87e2e904b44f90908da60dd4889%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637928800765043752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7mw3fCk0p5zjR4UIwRbnwADrlUTMjbLO1riMd%2F3u5SI%3D&reserved=0>
Chuck Bost
ODT / OIMT
Microsoft 365 EaaS /  Microsoft 365 Integration
Mobile:  240.460.7124
https://ecstech.com/<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fecstech.com%2F&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7Cb6683d3020ff44f2715e08da60f3749b%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637928895988668782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cnoc6C6B1BZk4sP11jf2Dpj9XbfnaDOKWFPML2bbS5M%3D&reserved=0>


From: Nik Charlebois ***@***.***>
Sent: Friday, July 29, 2022 9:08 AM
To: microsoft/Microsoft365DSC ***@***.***>
Cc: Bost, Charles * ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/Microsoft365DSC] New-M365DSCReportFromConfiguration -Type HTM does not include retention policies from SC (Issue #1801)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


We are trying to troubleshoot an issue with the PowerShell Gallery team where we are currently getting a 500 Server Unavailable error trying to publish the release.

-

**Comment by andikrueger** [comment]
We are still facing an issue with PSGallery.

**Comment by Chabango** [comment]
Is this issue still occurring? Not able to update to the latest 727 version.


***@***.***<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fsecure-web.cisco.com%2F1q8Mf1w_9vN5jtppFYG6_NSY4hjTGb4D9pjmEZ7gNus0rwB4wGEGSkL86SrRZ7e9WBZYyWzW0ArjzmDW08tecrn_PpZRmJeQGJRRYRI0B3mun52VFFWs8scgltvcTnB_6IjvPKTxHLDrW1cWEBFfmkzff2pnaXPVc0Dh3yM7vsXy0FG7rOjtakrgAinLQv20RNusf98FMIc0R9NR8QRAXrg%2Fhttp%253A%252F%252Fwww.ecstech.com%252F&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7C8581b87e2e904b44f90908da60dd4889%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637928800765043752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7mw3fCk0p5zjR4UIwRbnwADrlUTMjbLO1riMd%2F3u5SI%3D&reserved=0>
Chuck Bost
ODT / OIMT
Microsoft 365 EaaS /  Microsoft 365 Integration
Mobile:  240.460.7124
https://ecstech.com/<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fecstech.com%2F&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7Cb6683d3020ff44f2715e08da60f3749b%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637928895988668782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cnoc6C6B1BZk4sP11jf2Dpj9XbfnaDOKWFPML2bbS5M%3D&reserved=0>


From: Andi Krüger ***@***.***>
Sent: Tuesday, August 2, 2022 1:49 PM
To: microsoft/Microsoft365DSC ***@***.***>
Cc: Bost, Charles * ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/Microsoft365DSC] New-M365DSCReportFromConfiguration -Type HTM does not include retention policies from SC (Issue #1801)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


We are still facing an issue with PSGallery.

-

**Comment by andikrueger** [comment]
Still an issue with PSGallery. You could download the latest version here: https://github.com/microsoft/Microsoft365DSC/releases/tag/1.22.727.1

**Comment by Chabango** [comment]
Do you have a doc on how to manually install?


***@***.***<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fsecure-web.cisco.com%2F1q8Mf1w_9vN5jtppFYG6_NSY4hjTGb4D9pjmEZ7gNus0rwB4wGEGSkL86SrRZ7e9WBZYyWzW0ArjzmDW08tecrn_PpZRmJeQGJRRYRI0B3mun52VFFWs8scgltvcTnB_6IjvPKTxHLDrW1cWEBFfmkzff2pnaXPVc0Dh3yM7vsXy0FG7rOjtakrgAinLQv20RNusf98FMIc0R9NR8QRAXrg%2Fhttp%253A%252F%252Fwww.ecstech.com%252F&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7C8581b87e2e904b44f90908da60dd4889%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637928800765043752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7mw3fCk0p5zjR4UIwRbnwADrlUTMjbLO1riMd%2F3u5SI%3D&reserved=0>
Chuck Bost
ODT / OIMT
Microsoft 365 EaaS /  Microsoft 365 Integration
Mobile:  240.460.7124
https://ecstech.com/<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fecstech.com%2F&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7Cb6683d3020ff44f2715e08da60f3749b%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637928895988668782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cnoc6C6B1BZk4sP11jf2Dpj9XbfnaDOKWFPML2bbS5M%3D&reserved=0>


From: Andi Krüger ***@***.***>
Sent: Monday, August 8, 2022 9:14 AM
To: microsoft/Microsoft365DSC ***@***.***>
Cc: Bost, Charles * ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/Microsoft365DSC] New-M365DSCReportFromConfiguration -Type HTM does not include retention policies from SC (Issue #1801)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Still an issue with PSGallery. You could download the latest version here: https://github.com/microsoft/Microsoft365DSC/releases/tag/1.22.727.1<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsecure-web.cisco.com%2F1aDED1-yZFXs0LqWDBkuSgeKho-nH_wzbrDmhfOm0643luoyz1yq2OGi6I6qdyVebP1Ayxhg783imTFVVgWn0zLkHoOPWtSICZYCuKrGfKJjVZBEf9mRDMWl68PWFVcEepKFXzqchlvcVta5Tirm6KRevwfWcPEYkHYYBGEUCBKQ6a3_CwcygiDGqz8I-zGNABj9Ex7zEcvhnuCHh2hS5ftfQPRGhpnX_M-wnTb4S-Rw%2Fhttps%253A%252F%252Fgithub.com%252Fmicrosoft%252FMicrosoft365DSC%252Freleases%252Ftag%252F1.22.727.1&data=05%7C01%7CCharles.Bost%40fda.hhs.gov%7Cdd0c1ba6387d4a31e99f08da793fe5bb%7C7d2fdb41339c425787f2a665730b31fc%7C0%7C0%7C637955612582641155%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nIAXsMk85DrhG4iy0uA6PdE9urKs7NWrhSpWOxTn2FQ%3D&reserved=0>

-
