### ISSUE TITLE
Feature request: Create and manage distribution list groups

### ISSUE THREAD

**Issue by lucvandewall** [microsoft/Microsoft365DSC#1802]
At the moment it is not possible to create a mail-enabled security group and/or a distribution list
If gives an Invalid Operation exception. 

It would really be nice if this could be included in Microsoft365DSC and do CRUD operations on this set of functionality of the MailExchange Online

**Comment by NikCharlebois** [comment]
Pull Request submitted for the new EXODistributionGroup resource. #2107
