### ISSUE TITLE
Cloning Tenants - Missing Docs & Script

### ISSUE THREAD

**Issue by arpsga** [microsoft/Microsoft365DSC#1805]
Does anyone have a working script or documentation about cloning tenants? 
Can't find any ressources. Video below has no links... 
[(https://www.youtube.com/watch?v=jNJuGyX7WzE)](https://www.youtube.com/watch?v=jNJuGyX7WzE)

**Comment by andikrueger** [comment]
Did you check this documentation on how to get started with Microsoft365DSC: https://microsoft365dsc.com/user-guide/get-started/complete-story/

Basically to clone a tenant you need to do the following three steps:

1. Export your source tenant by running `Export-M365DSCConfiguration` - You can generate the parameters using this website: https://export.microsoft365dsc.com/
2. Compile the configuration with your target tenants credentials
3. Run `Start-DSCConfiguration` with the required parameters.

**Comment by andikrueger** [comment]
There is another issue in regards to documentation. #1836  

Closing this one due to inactivity.
