### ISSUE TITLE
New-M365DSCDeltaReport: Report is seeing items as different because of different ResourceID

### ISSUE THREAD

**Issue by MattBrowne1** [microsoft/Microsoft365DSC#1815]
#### Details of the scenario you tried and the problem that is occurring
The test I have run is using Teams as an example but the same happens with AAD Groups.

I am extracting the list of TeamsTeams using.....
Export-M365DSCConfiguration -Components @("TeamsTeam")  -Credential $Credential -Path $path -FileName $fileName
Then adding a new Team and running the Export again.

Then I run the Delta Report using.....
New-M365DSCDeltaReport -Source .\file1.ps1 -Destination .\file2.ps1 -OutputPath .\DeltaReport.html -DriftOnly $true

The delta report is produced but it lists all the Teams and not just the new Team.  It looks like it is seeing that the items are different because the ResourceID is different for each Team.

Am I misunderstanding something or is it really flagging resourceIDs as different.

#### Suggested solution to the issue
It would be good to ignore the resource ID, if that is kthe issue, or the delta report is always going to list almost everything that has a resourceID

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
As above

#### The operating system the target node is running
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22000.1.amd64fre.co_release.210604-1628
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
PSDesiredStateConfiguration = v1.1

**Comment by andikrueger** [comment]
Could you share parts of your configuration so that we can investigate a bit further?

Could you also run the following command and post the output:

```powershell
Get-Module microsoft365dsc -ListAvailable
```

**Comment by MattBrowne1** [comment]
Hi @andikrueger This is the output. Thanks.....

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.22.309.1 Microsoft365DSC                     {Assert-M365DSCBlueprint, Assert-M365DSCTemplate, Compare-...

**Comment by andikrueger** [comment]
Thank you. This is the latest version.

Would you be able to share two sample configurations that cause the issue?

**Comment by magnusatteamsrocks** [comment]
I have the same issue after upgrading from 1.22.216.1 to 1.22.309.1.

**Comment by MattBrowne1** [comment]
@andikrueger Sure.  The example I am using to test (but isn't just limited to this example) is for the component "IntuneDeviceCompliancePolicyWindows10".  I have setup one vanilla policy called "MattTest001", and this is the only policy that exists for this.

The lines I use to export the configs are:

$Credential = Get-Credential
Export-M365DSCConfiguration -Components @("IntuneDeviceCompliancePolicyWindows10")  -Credential $Credential -Path $path -FileName $fileName

I run this twice without making any changes to the existing policy, and point the output into two different directories.  Therefore I have 2 files that are pretty much exactly the same.
Examples - [output.zip](https://github.com/microsoft/Microsoft365DSC/files/8231199/output.zip)

From these two files I am doing a Delta comparison, which I was expecting to be empty as there have been no changes to the policies between the configs.  The line I am using to do the Delta is : 

New-M365DSCDeltaReport -Source .\output\11-03-22-101537\DSCConfig.ps1 -Destination .\output\11-03-22-101537\DSCConfig.ps1 -OutputPath .\DeltaOutput.html

This produces a report that looks like this....
![image](https://user-images.githubusercontent.com/26323872/157852101-d62d20eb-f3cf-43cf-9a7f-33bb5eb16358.png)

It appears to be seeing the policy as different each time because the 'ResourceID' is different.  These resourceIDs match the IntuneDeviceCompliancePolicyWindows10 object in the export files, but they are different across the 2 exports.

This is one example but I get the same result if I run through the same process for the 'AADGroup' component.

PSVersion is 5.1.22000.282
microsoft365dsc module version is as above.
I've run 'Update-M365DSCDependencies' so that should be fully up to date.
I'm running this all on a Windows11 machine.

**Comment by MattBrowne1** [comment]
I've just run through the export a few more times and tried 'Assert-M365DSCBlueprint'.  It looks like the value it gets for the 'Tenant's Current Value' is different each time you run it.  ie each Export see's a different ResourceID for the same resource.

**Comment by andikrueger** [comment]
Exactly. The resourceID is a new guid and gets generated during the export. This is why it changes with every export. 

There is no added value of having this information within the report. However there might be cases, that someone would compare two manually created and edited configuration. Then a change of the resource name should be included within the report.

**Comment by MattBrowne1** [comment]
As @magnusatteamsrocks says, version '1.22.216.1' works fine, so I've downgraded to that for now

**Comment by MaciejZZZ** [comment]
Hi Guys
I noticed the same issue after upgrade of my production setup of M365 from 1.21.1006.3 to 1.22.323.1 version of Microsoft365DSC. 
It's really confusing to see this ResourceID changes in drifts reports - which for EXO are rather long.

@andikrueger  @NikCharlebois  Can you give it a priority and fix this in incoming versions somewhere soon or should I downgrade (I'd prefer not to).

**Comment by MaciejZZZ** [comment]
Hi Guys
I just downgraded from 1.22.323.1 to 1.22.216.1 - and now - when running New-M365DSCDeltaReport the ResourceIDs are gone but I see empty lines marked as different for identical resources :(
Can you please fix this ? :)

**Comment by MaciejZZZ** [comment]
Any news here?

**Comment by Orwell482** [comment]
Hi all,
any news when this will be fixed? It`s a nice feature to compare two reports of a tenant. Is there any workaround for it? The downgrade is not working for me.

**Comment by ykuijs** [comment]
I have fixed this issue and am about to submit a PR. The fix will be included in next weeks release!

**Comment by NunoFilipeMota** [comment]
Hi everyone. I am currently running version 1.22.518.1. When running the module with PowerShell v5.1, I don't get this issue. However, when running PowerShell v7.2.4 I do...

When running _New-M365DSCDeltaReport_ with PS 5, the _ResourceID_ property is not included in the report, but PS 7 does include it and marks all resources as being configured differently...    :(

@ykuijs: you marked this as fixed. In what version was that please? I assume this different behaviour is not expected?

Thank you.
