### ISSUE TITLE
M365DSC - No green Check Marks but Question Marks

### ISSUE THREAD

**Issue by MarcoEberle** [microsoft/Microsoft365DSC#1821]
#### Details of the scenario you tried and the problem that is occurring
When I do Export-M365DSCConfiguration or Assert-M365DSCBlueprint, Check Marks are not shown but Question Marks.
I haven't tried it on others like Report. Otherwise everything works fine as a I can see.
```powershell
Assert-M365DSCBlueprint -BluePrintUrl "C:\Users\XYZ\Desktop\assestest.ps1" -OutputReportPath "C:\Users\XYZ\Desktop\assesReport.html"
```
#### Verbose logs showing the problem
I am not sure if this is a/the problem because everything works fine but maybe this is the problem I don't see the Check Marks?

VERBOSE: {DSCParser} version 1.3.0.2                            
VERBOSE: Populating RepositorySourceLocation property for module DSCParser.                                             
VERBOSE: Loading module from path 'C:\Program                                                                           Files\WindowsPowerShell\Modules\DSCParser\1.3.0.2\modules\DSCParser.psm1'.
VERBOSE: {ExchangeOnlineManagement} version 2.0.5
VERBOSE: Populating RepositorySourceLocation property for module ExchangeOnlineManagement.
VERBOSE: Loading module from path 'C:\Program                                                                           Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\.\netFramework\ExchangeOnlineManagement.psm1'.           VERBOSE: {Microsoft.Graph.Applications} version 1.9.2
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted   versions.                                                                                                               VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Applications.                          
VERBOSE: Loading module from path 'C:\Program                                                                           Files\WindowsPowerShell\Modules\Microsoft.Graph.Applications\1.9.3\./Microsoft.Graph.Applications.psm1'.               
 VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted   versions.                                                                                                               VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Applications.                          
VERBOSE: Loading module from path 'C:\Program                                                                           Files\WindowsPowerShell\Modules\Microsoft.Graph.Applications\1.9.2\./Microsoft.Graph.Applications.psm1'.                
VERBOSE: {Microsoft.Graph.Authentication} version 1.9.2                                                                 VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted   versions.                                                                                                               VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Authentication.                        
VERBOSE: Loading module from path 'C:\Program                                                                           Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.9.3\./Microsoft.Graph.Authentication.psm1'.            
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted   versions.                                                                                                               VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Authentication.                        
VERBOSE: Loading module from path 'C:\Program
.....
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration Example
{
    param(
        [Parameter(Mandatory = $true)]
        [PSCredential]
        $credsGlobalAdmin
    )
    Import-DscResource -ModuleName Microsoft365DSC

    node localhost
    {
        TeamsGuestCallingConfiguration GuestCallingConfig
        {
            Identity            = "Global";
            AllowPrivateCalling = $True;
            Credential          = $credsGlobalAdmin;
        }
        TeamsGuestMeetingConfiguration TeamsGuestMeetingConfiguration
        {
            AllowIPVideo       = $True;
            AllowMeetNow       = $False;
            Credential         = $credsGlobalAdmin;
            Identity           = "Global";
            ScreenSharingMode  = "EntireScreen";
        }
        TeamsGuestMessagingConfiguration TeamsGuestMessagingConfig
        {
            AllowGiphy             = $True;
            AllowImmersiveReader   = $False;
            AllowMemes             = $True;
            AllowStickers          = $False;
            AllowUserChat          = $True;
            AllowUserDeleteMessage = $False;
            AllowUserEditMessage   = $True;
            GiphyRatingType        = "Moderate";
            Credential             = $credsglobaladmin;
            Identity               = "Global";
        }
    }
}
```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.22.216.1 Microsoft365DSC                     PSGallery            This DSC module is used to configure and monitor...

**Comment by MarcoEberle** [comment]
Also I get this error sometimes:
```
Exception calling "IndexOf" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size
of the collection.
Parameter name: startIndex"
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.309.1\modules\M365DSCUtil.psm1:2189 char:9
+         $endPosition = $fileContent.IndexOf("`r", $startPosition)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException

Exception calling "Remove" with "2" argument(s): "StartIndex cannot be less than zero.
Parameter name: startIndex"
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.309.1\modules\M365DSCUtil.psm1:2190 char:9
+         $fileContent = $fileContent.Remove($startPosition, $endPositi ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException

Selected BluePrint contains (0) components to assess.
Initiating the Export of those (0) components from the tenant...
```
I think it has to do something with signing in to my account.

**Comment by MarcoEberle** [comment]
![image](https://user-images.githubusercontent.com/38832691/158366097-08decae8-9a09-4f35-822a-dbb6646e88d3.png)

**Comment by Kirikou974** [comment]
Look like an encoding issue.
The checkmarks icons are created from unicode (UTF32) : 
$Global:M365DSCEmojiGreenCheckmark = [char]::ConvertFromUtf32(0x2705)
$Global:M365DSCEmojiRedX = [char]::ConvertFromUtf32(0x274C)

How/where is your PowerShell host created ?

**Comment by MarcoEberle** [comment]
My Powershell host is a Virtual Machine created by a Microsoft Dev Account in portal.azure.com.
I launched two VMs but the encoding error is still appearing.

Do I need a nerd font or is it another problem? If so how can I fix it? Thanks.

**Comment by Kirikou974** [comment]
Did you try this in ISE or even better VSCode ?
PowerShell console doesn't know how to render theses chars (it doesn't "know" much about font rendering).
So what you see is pretty normal. You could try to change the font of your powershell console to something like SimSun-ExtB : 
![image](https://user-images.githubusercontent.com/21690437/158611898-ad22be5d-0f63-4d4b-b214-392731d053d2.png)

But unless you have a strong requirement to use powershell console I'd go for an actual editor.

**Comment by MarcoEberle** [comment]
In ISE I get the Icons so what is wrong in the normal PowerShell?
I also get this error:
![grafik](https://user-images.githubusercontent.com/38832691/158614457-758d9014-ecbd-446b-8116-70d27fc41838.png)

![grafik](https://user-images.githubusercontent.com/38832691/158614364-492d5cdd-744b-43a6-b763-9f00a556d1f6.png)

So maybe something is crashing before.
I installed everything like stated this tutorial: https://microsoft365dsc.com/user-guide/get-started/complete-story/

**Comment by MarcoEberle** [comment]
I did create the assesTest.ps1 manually by copying a Resource from the official Github into VSCode/Editor and saving it to .ps1 format.
Now I exported a config file with: 
```powershell
Export-M365DSCConfiguration -Components @("TeamsGuestCallingConfiguration", "TeamsGuestMeetingConfiguration", "TeamsGuestMessagingConfiguration") -Credential $Credentia
```

and did then 

```powershell
Assert-M365DSCBlueprint -BluePrintUrl C:\Users\ebse\Desktop\assesTest.ps1 -OutputReportPath C:\Users\ebse\Desktop\assesReport.html```

The Error is not coming back. I tried it multiple times. I think this fixed the error! Thank you very much.

Is this how you should create a config file or is the way I was doing it just wrong? 

But, I still cannot see the Emojis in Powershell any help for this?
