### ISSUE TITLE
Need help to understand how to format New-M365DSCReportFromConfiguration content

### ISSUE THREAD

**Issue by yingying96** [microsoft/Microsoft365DSC#1824]
Hi Team,

Wanted to understand how to format it such that i will get data directly from M365DSC?
Instead of us hardcoding the values here. Would that be possible? Thanks!

<img width="605" alt="image" src="https://user-images.githubusercontent.com/19566726/158423458-37aaa3ae-1f39-4e68-a977-a6095231ebbb.png">

**Comment by andikrueger** [comment]
Usually you would run an export and then create a new report.

**Comment by yingying96** [comment]
Apologies i don't quite get what you mean? Am i running the commands wrongly? Thanks!

**Comment by ykuijs** [comment]
Hi @yingying96, you can export the current configuration from an Microsoft 365 tenant by running the Export-M365Configuration cmdlet. That will generate a PS1 file with the current configuration.

You can then run the New-M365DSCReportFromConfiguration and specify this created PS1 file, resulting in a documentation generated from the actual M365 configuration.

More info:
- Taking a snapshot of an existing tenant: https://microsoft365dsc.com/user-guide/get-started/complete-story/#taking-a-snapshot-of-existing-tenant
- Creating documentation: https://microsoft365dsc.com/user-guide/get-started/complete-story/#generating-reports-from-configurations

**Comment by yingying96** [comment]
Thank you for your explanation. Yes i understand now!
