### ISSUE TITLE
EXOOwaMailboxPolicy property 'SMimeEnabled' & 'SMimeSuppressNameChecksEnabled' are not supported / included

### ISSUE THREAD

**Issue by atdheekurteshi** [microsoft/Microsoft365DSC#1833]
ISSUE TITLE:
 
EXOOwaMailboxPolicy property 'SMimeEnabled' & 'SMimeSuppressNameChecksEnabled' are not supported / included

ISSUE DESCRIPTION (this template):

**EXOOwaMailboxPolicy**:
Property **'SMimeEnabled'** is not supported on class **EXOOwaMailboxPolicy**
Property **'SMimeSuppressNameChecksEnabled'** is not supported on class **EXOOwaMailboxPolicy**
   
On class **OwaMailboxPolicy** properties **SMimeEnabled** and* *SMimeSuppressNameChecksEnabled** are momentary not supported in **Microsoft365DSC** **https://github.com/microsoft/Microsoft365DSC/wiki/EXOOwaMailboxPolicy** but they are supported in PowerShell **https://docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps**

The Set Function in PowerShell that I tested its working but in DSC its not working .

```powershell
PS C:\Windows\system32> Set-OwaMailboxPolicy -Identity Default -SMimeEnabled $false
PS C:\Windows\system32> Set-OwaMailboxPolicy -Identity Default -SMimeSuppressNameChecksEnabled $true
``` 

#### Suggested solution to the issue
The internally PowerShell Method described in this link **https://docs.microsoft.com/en-us/powershell/module/exchange/set-owamailboxpolicy?view=exchange-ps** its working.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```
#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}

-->

#### Version of the DSC module that was used ('dev' if using current dev branch)
 1.22.309.1

**Comment by malauter** [comment]
For SMimeEnabled the Docs article states: 

> This parameter is functional only in Exchange Server 2010. [...] In Exchange 2013 or later, use the Get-SmimeConfig and Set-SmimeConfig cmdlets to configure the S/MIME settings in Outlook on the web.

And for SMimeSuppressNameChecksEnabled: 

> This parameter is reserved for internal Microsoft use.

This is why I did not add these attributes to the DSC resource in the past. Do you see any use case to integrate them anyway?

**Comment by atdheekurteshi** [comment]
Even though SMIMEEnabled is no longer used for the newer Exchange Server versions, we need this attribute for the automation solution as we want to change the default value for EXOOrganizationConfig: SMIMEEnabled for our environment.

For the other attribute I agree, since this parameter is used internally by Microsoft, we don't need the extension.

**Comment by malauter** [comment]
Sorry for my late response. Did you check if it is possible to configure this via Set-SmimeConfig like mentioned in the Docs article?  For me the use case is still not clear, because the docs article states that this attribute is no longer supported.

**Comment by atdheekurteshi** [comment]
**SMimeSuppressNameChecksEnabled** we are not interested cause it used for Microsoft internally.
Regarding the **SMimeEnabled** this Attribute is what we want to include in the **DSC** because we are going to use it for our customers and that is the reason what we need it.

Yes there is a Set-SmimeConfig in the docs but we are not interested on the Set-SmimeConfig or PowerShell but we need it for DSC.

**Comment by malauter** [comment]
Just tested this in several tenants, but the parameter SMimeEnabled is no longer available for Set-OwaMailboxPolicy cmdlet (screenshot attached). Therefore, it is not possible to add this to the DSC resource.

![image](https://user-images.githubusercontent.com/37979749/162153754-0d5e2c63-06d7-4a54-9dd9-a724e034f98e.png)

**Comment by malauter** [comment]
Closed, because requested parameters are no longer available in cmdlet.
