### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by Bender1983** [microsoft/Microsoft365DSC#1836]
A little bit more documentation would be helpfull. Of course you have a lot a youtube videos but text documentation would be much more easier. It will take less time to search.
Its just a personal point of view but i looks like the permission thing is currently not realy clear. By example: When do I need an App and when not an permissions a enough.
Why not providing an tutorial for that?

**Comment by andikrueger** [comment]
Thanks for the feedback. There is for sure room for improvement. Could you elaborate on this part of the documentation a little, bit, where we should be more precise? 

https://microsoft365dsc.com/user-guide/get-started/complete-story/#authentication

**Comment by Bender1983** [comment]
Hi Andi

From a perspective of a developer its god and enough but from a point of a sysadmin (which I'am) there could be more examples. By example: How do I create an app to use with Microsoft365DSC. For people who do this a lot its very clear but for new ones it is a lot of information and a little bit confusing. By example: In which case does an app make sense, why should I use one, whats all that stuff about Graph and  why its important, etc...
Make more chapters on your page. By example: Installation, Set-Permissions, Create-Reports/Diff, Using with apps, etc..
This wil help the people for a fast start with Microsoft365DSC.
I found your project because I was looking for an method to create backups of our tenant config. Do not understand me wrong its a great project because now we are able to track changes we made on our tenant. I found nothing else which has the same functions for free.

regards
Andreas

ps: sorry for my poor english

**Comment by qx-775** [comment]
I totally agree,

Even using the documentation, example code snippets and github issues I just don't know how to to start. Where do I put my application permission credentials in the script? What command is necessary to run the scripts (I have to guess just use powershell)? What are DO's and DON'TS (hardcode credentials for example and how to overcome it). The installation process is documented well, but the examples are lacking step by step instructions IMO.

The examples online (youtube videos) are too complicated for me, a new user.

**Comment by andikrueger** [comment]
Referencing this discussion, as there is additional valuable feedback https://github.com/microsoft/Microsoft365DSC/discussions/1846

**Comment by andikrueger** [comment]
That is very valuable feedback! We are too familiar with the technology and the module itself and miss major parts within the story for a new user to get started. We need your feedback on this matter. It's our goal to enable you the best way possible. Some questions to get you started in regards to documentation:- What are you missing?
- Where are you stuck?
- Are you looking for step-by-step guides/snippets/tooling support/...?
- What kind of information should examples provide?

## resource examples

>It is not meant to use as a production baseline.

The example configurations for every resource are used within the build pipelines of this module to test and verify the code. They contain data that should not necessarily end up in a real world production tenant as the settings might differ to what you like to see within a controlled environment.

The examples are just outlining on what parameters are available and how these would look within a configuration. In a real world scenario you would either start with an exported baseline obtained from your tenant or modify these examples to meet your needs.

## Overall guidance to various practices

In regards to more guidance, there is a good whitepaper available that outlines the whole setup of Microsoft 365 DSC in a true DevOps way: https://microsoft365dsc.com/about/community-resources/


We need to provide more content for less complex scenarios.

**Comment by p-bojkowski** [comment]
Some confusions also in the screenshots (Key Vault Names)

![image](https://user-images.githubusercontent.com/74313141/161610866-52d05ab1-dd14-4556-9e86-9c8ed3125c05.png)

Some one from the core Team should take the "Microsoft365Dsc and Azure DevOps" doc and try to reproduce the settings with:

![image](https://user-images.githubusercontent.com/74313141/161611087-026ba5c1-ef7f-4305-97cd-429a2308f5d1.png)

It's really confusions!

And when you put something like this in the doc:

![image](https://user-images.githubusercontent.com/74313141/161611574-2239f7bf-aad0-4ccd-bf73-01c6bef6d764.png)

and

![image](https://user-images.githubusercontent.com/74313141/161611629-341cedfd-4192-4cf2-909a-9af120eed256.png)

and

![image](https://user-images.githubusercontent.com/74313141/161611733-c815738a-ca66-4311-b74e-2695393fd084.png)

Then you must mention in the top paragraphs UNCONDITIONALLY (every time!) that if you have "Security Enhancements" the setting is different and you should jump to point x.x.x first.

**Comment by ykuijs** [comment]
Hello @Bender1983 @qx-775 @p-bojkowski and everyone else!

Over the past weeks I have been working on making the documentation more readable and adding information that was missing. This new version of the website was just published: https://microsoft365dsc.com/user-guide/get-started/introduction/

It would be really great if you can have a look on what is currently in there and provide your feedback:
- Are the current pages missing important details that you wish you knew when you started with Microsoft365DSC?
- Are there any topics missing?
- Etc, etc.

Please help us making the documentation better! Keep the feedback coming!

FYI: I know that some of the information mentioned earlier in this thread are not yet in there. Right now I focused on getting the already existing content more readable.

**Comment by p-bojkowski** [comment]
@ykuijs thank you so much!
Looks good!

One thing I am missing in the "Cloning Tenant Configurations" part -> A sample PowerShell script which someone has also tried before :)

I think @NikCharlebois posted something on YouTube in the comments: https://www.youtube.com/watch?v=jNJuGyX7WzE&ab_channel=Microsoft365DSC
but this isn't really working and need to be as a sample in the documentation here.

**Comment by ykuijs** [comment]
@p-bojkowski, I am working on another documentation update which will include this example!
For the whitepaper: I am working on a big update for the whitepaper, which will also include your feedback! Just have to find some time to complete this update 😉 

@informatik-bks, good to hear! Thanks for the feedback. Let us know if you have any more suggestions / idea for improvements!

**Comment by ykuijs** [comment]
@Bender1983, @qx-775: The documentation update I refer to in the above post will also include some starter information and links to other articles (don't want to reinvent the wheel 😄). Will let you know once the update has been published and it would be great if you could review it and let me know if that helps getting started with Microsoft365DSC!

**Comment by ykuijs** [comment]
PR #1948 has been submitted. Please review the updated documentation at [microsoft365dsc.com](https://microsoft365dsc.com/user-guide/get-started/introduction/) when merged!

**Comment by ykuijs** [comment]
PR has been merged and the website has been updated. Really interested in what you all are thinking and what information might be useful to be added as well!

**Comment by ykuijs** [comment]
Linking another documentation update issue to this issue: #1912

**Comment by andikrueger** [comment]
Link another discussion to this issue: #1958 @KuotingChiu

> While Get-M365DSCCompiledPermissionList can be used to get the list of delegated permissions, there is no equivalent cmdlet to get the list of permission of "application permission" to be used for client id/certificate (or secret) authentication. Also, there are no good documentation of what the needed application permissions are. Please note that needed application permissions may not be the same as the needed delegated permissions used for credential authentication. I am having hard time to find out the needed application permissions for the PP (Power Platform) workload using the client id/certificate authentication. Anybody knows ?


@ykuijs Could you take this information into account?

**Comment by p-bojkowski** [comment]
@ykuijs 

https://microsoft365dsc.com/home/what-is-M365DSC/

![image](https://user-images.githubusercontent.com/74313141/169535811-680c4db7-ffe4-44a5-aef9-8156d7d66866.png)

**Comment by p-bojkowski** [comment]
@ykuijs everthing under [LINK](https://microsoft365dsc.com/user-guide/get-started/complete-story/) is buggy

**Comment by p-bojkowski** [comment]
@ykuijs can you please add a link to: https://microsoft365dsc.com/user-guide/get-started/cloning-tenants/

![image](https://user-images.githubusercontent.com/74313141/169537751-a0280ddb-b52e-405b-9f9c-c59208cb9635.png)

**Comment by p-bojkowski** [comment]
@ykuijs URL to the "official Blueprints"?

![image](https://user-images.githubusercontent.com/74313141/169538259-aab9268a-f35b-44b7-83cc-bcfa257508f7.png)

**Comment by p-bojkowski** [comment]
@ykuijs more buggy links:

https://microsoft365dsc.com/user-guide/get-started
https://microsoft365dsc.com/user-guide

**Comment by p-bojkowski** [comment]
@ykuijs CSS issues:

![image](https://user-images.githubusercontent.com/74313141/169539042-17d26086-b560-4dbe-bfd4-b1498d1c0f41.png)

**Comment by andikrueger** [comment]
Just checking, if we need this issue for more documentation updates or if we could close it. I would go for anew one, if there is the need to further improve the docs.

cc/ @p-bojkowski @ykuijs @Bender1983

**Comment by Bender1983** [comment]
Hi Andi

For me the issue is solved, thanks for your work and the work of all team members of the project

**Comment by andikrueger** [comment]
Thanks for the feedback. I'll close this issue for now.
