### ISSUE TITLE
[MSFT_TeamsVoiceRoutingPolicy] type mis-match results in false positives

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#1840]
#### Details of the scenario you tried and the problem that is occurring
Running Test-TargetResource against a Teams voice routing policy reports a configuration drift even though the configuration is correct. 
#### Verbose logs showing the problem
```
[[TeamsVoiceRoutingPolicy]***] 
Current Values: Credential=***; Description=***; Ensure=Present; 
Identity=***; OnlinePstnUsages=Mobile Festnetz International 0800er PREMIUM
[[TeamsVoiceRoutingPolicy]***] 
Target Values: Credential=***; Description=***; Ensure=Present; 
Identity=***; OnlinePstnUsages=(Mobile,Festnetz,International,0800,PREMIUM); Verbose=True
```
#### Suggested solution to the issue
I believe there is a type mis-match in the code. 

While Get-CsOnlineVoiceRoutingPolicy returns an array of objects, Test-TargetResource takes a string array. Thus, a type conversion happens and the comparison returns false. 

```
$policy.OnlinePstnUsages.getType()


IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array
```

The cause I believe is in:
https://github.com/microsoft/Microsoft365DSC/blob/6125986a4af52353496dcf90cf7b9532d3d9a2b6/Modules/Microsoft365DSC/DSCResources/MSFT_TeamsVoiceRoutingPolicy/MSFT_TeamsVoiceRoutingPolicy.psm1#L197

Also, I believe the parameter $OnlinePstnUsages in Get-TargetResource is never used / set.

```
[Parameter()]
        [System.String[]]
        $OnlinePstnUsages,

```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by malauter** [comment]
@SebastianGoers Can you please share more details and the DSC configuration for TeamsVoiceRoutingPolicy? I cannot repro this issue. Test-TargetResource returns True in my test (no configuration drift) if I test my current configuration with this configuration: 

`TeamsVoiceRoutingPolicy 0283e115-92b8-4a60-8045-5220732c1083
        {
            Credential           = $Credscredential;
            Ensure               = "Present";
            Identity             = "Global";
            OnlinePstnUsages     = @("Local","Mobile");
        }`

**Comment by SebastianGoers** [comment]
Hi @malauter , the configuration is as follows:

```
TeamsVoiceRoutingPolicy 02e49217
	    {
		Identity           = "ABC";
		OnlinePstnUsages   = @('Mobile','Festnetz','International','0800','PREMIUM');
		Description        = "XYZ";
		Ensure             = "Present";
        Credential = $myCredential;
        }
```

**Comment by malauter** [comment]
Hi @SebastianGoers, thanks for your configuration. I just tested with your config in my lab, but I still cannot repro a configuration drift after I applied the configuration for the first time.

![image](https://user-images.githubusercontent.com/37979749/159904381-0823d2da-4180-4985-bc7b-d037aff9617d.png)

Are you using the latest version of Microsoft365DSC and all dependencies?

**Comment by SebastianGoers** [comment]
I am using the latest production build: ` Downloading module 'Microsoft365DSC' with version '1.22.323.1' from the repository ` I am running DSC in an Azure DevOps pipelines, so it should be downloading the most up-to-date software versions for all components. In the screenshot you provided it also shows the string vs. object output for OnlinePstnUsages

**Comment by malauter** [comment]
The output in the screenshot is in different format, but the Test-TargetResource function is working as expected and does not detect a configuration drift in my test.

**Comment by SebastianGoers** [comment]
@malauter , my bad. I spotted my error just now: the current setting is slightly different from the desired setting: 

Mobile Festnetz International 0800**er** PREMIUM  vs. Mobile Festnetz International 0800 PREMIUM

I'm sorry, I will close the issue.
