### ISSUE TITLE
Additional dependency for HTML output?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [microsoft/Microsoft365DSC#1847]
I'm wondering whether you would be interested in taking a dependency on the [PSWriteHTML](https://github.com/EvotecIT/PSWriteHTML) project for HTML purposes to improve visual output. Creating an HTML report doesn't require any HTML/CSS/JS knowledge and with just a few lines of PowerShell delivers quite an amazing HTML output.

Here are a couple of blog posts that show what could be done:

- https://evotec.xyz/advanced-html-reporting-using-powershell/
- https://evotec.xyz/creating-office-365-migration-diagram-with-powershell/
- https://evotec.xyz/nested-tabs-diagram-updates-diagram-events-calendar-object-and-more-in-pswritehtml/

**Comment by NikCharlebois** [comment]
Thanks for the suggestion. At the moment however we are trying to reduce the number of dependencies we have for the project. It is however an interesting proposal and everyone can leverage PSWriteHTML with minimal work, without having us include dependencies inside of M365DSC. Thanks
