### ISSUE TITLE
EXOMalwareFilterPolicy property 'QuarantineTag' is not supported / included

### ISSUE THREAD

**Issue by atdheekurteshi** [microsoft/Microsoft365DSC#1850]
ISSUE TITLE:
 
EXOMalwareFilterPolicy property 'QuarantineTag' is not supported / included

ISSUE DESCRIPTION (this template):

**EXOMalwareFilterPolicy**:
Property **'QuarantineTag'** is not supported on class **EXOMalwareFilterPolicy**
   
On class **MalwareFilterPolicy** property **QuarantineTag** is momentary not supported in **Microsoft365DSC** please could you add as a new property.

**Comment by atdheekurteshi** [comment]
When we are going to have a new release since we are waiting for the new resource and could you give some information when you are going to include the EXOMalwareFilterPolicy > QuarantineTag with a new attribute in WIKI in M365DSC.

**Comment by malauter** [comment]
@atdheekurteshi Usually there is a new release every Wednesday. This PR is included since version 1.22.406.1, published on April 6th. See changelog also.
