### ISSUE TITLE
Add / Support EXOQuarantinePolicy Resource in Microsoft365DSC

### ISSUE THREAD

**Issue by atdheekurteshi** [microsoft/Microsoft365DSC#1851]
ISSUE TITLE:
 
Add / Support **EXOQuarantinePolicy** Resource in **Microsoft365DSC**
**EXOQuarantinePolicy** is not supported / included in **Microsoft365DSC**

ISSUE DESCRIPTION (this template):

**EXOQuarantinePolicy**:
Property **'QuarantinePolicy'** should be added in class **EXOQuarantinePolicy** and should reference the **EXOMalwareFilterPolicy** property **'QuarantineTag'** as a Policy it should be nested with this policy to work as a **Required** property

**EXOQuarantinePolicy**  is momentary not supported please could you add as a new **Microsoft365DSC Resource**.

On class **EXOQuarantinePolicy** property **QuarantinePolicy** is momentary not supported could you add it as a new property.

**Comment by atdheekurteshi** [comment]
When we are going to have a new release since we are waiting for the new resource and could you give some information when you are going to include the EXOQuarantinePolicy  with a new attributes in WIKI in M365DSC.

**Comment by malauter** [comment]
@atdheekurteshi Usually there is a new release every Wednesday. This PR is included since version 1.22.413.1, published on April 13rd. See changelog also.
