### ISSUE TITLE
Blocked word list

### ISSUE THREAD

**Issue by anpiskai** [microsoft/Microsoft365DSC#1857]
When I use the blocked word list in the unified group naming policy object, upon initial application, it applies fine. However, when I modify the word list it fails to apply the new set. Setting through PowerShell seems to work fine with the same set of words though, so I'm not sure of the cause yet.

The error is not very helpful

<img width="403" alt="image" src="https://user-images.githubusercontent.com/48796638/161845079-a00b3211-509f-4c9e-8163-0839d54aae31.png">

**Comment by andikrueger** [comment]
Could you share a bit of your configuration? The error is thrown within the Test-Method. looks like there is some issue with either reading the values or comparing these.

**Comment by anpiskai** [comment]
Sure, I'm trying to pass in a list of blocked words in-line with the DSC
<img width="752" alt="image" src="https://user-images.githubusercontent.com/48796638/161974492-41e7ecd8-087d-4566-a5b0-cf99ba0da6d2.png">
I've also tried it without the -join portion. 

The CSV has a single column of values under the heading title "Word."

During the initial upload (without the -join portion at the end), it uploaded the list fine, but subsequent updates cause errors.

**Comment by anpiskai** [comment]
I haven't done that as the list is ~1300 words long, but I tried the same code on my locally machine and it worked fine as you'd expect so I can't reproduce it there. The only real difference was that the pipeline uses cert thumbprint, while the local version used credentials.

**Comment by anpiskai** [comment]
I approached setting thos values a different way due to some urgency by the customer, so closing the issue out
