### ISSUE TITLE
Versionnumber Webpage not equal Versionnumber in Module

### ISSUE THREAD

**Issue by Fuerst2718** [microsoft/Microsoft365DSC#1858]
The versionnumber shown on the webpage 
https://microsoft365dsc.com/
differs from the versionnumber in the file ...
Modules/Microsoft365DSC)/Microsoft365DSC.psd1

![image](https://user-images.githubusercontent.com/70098906/161902856-36bfe4f9-095c-454f-a8a3-5b28c95d2fe4.png)

**Comment by andikrueger** [comment]
Thanks for reporting.

The website uses the version information available within this repo: https://github.com/microsoft/Microsoft365DSC/releases This matches. There is a difference between the repo and PowerShell Gallery. It looks like the release did not complete to 100%. The new version got pushed to PowerShell gallery, but was not updated within the releases.

**Comment by Fuerst2718** [comment]
OK at the time the versionnumbers are equal -> 1.22.406.1
