### ISSUE TITLE
DLP poliy tip

### ISSUE THREAD

**Issue by ACK00** [microsoft/Microsoft365DSC#1866]
@helenclu @simonxjx  Referring to document: https://docs.microsoft.com/en-us/outlook/troubleshoot/security/can't-display-dlp-policytip

What are the steps to: verify that the Policy Nudge Rule for minRequiredVersion has a value that's not greater than the client-installed version of mso20win32client.dll. 

Thank you!

**Comment by malauter** [comment]
Can you please provide more information how this issue is related to Microsoft 365 DSC? Thx

**Comment by ACK00** [comment]
It is an issue in M365. The client is using a QA environment which in OWA the DLP policy tips are showing and in Outlook Desktop they are not. The documentation link states this is an issue and has a resolution, just wanting clarificaiton on how to perform the resolution steps.

**Comment by malauter** [comment]
Got it. But this repository is not about Microsoft 365 in general, it is about Microsoft 365 DSC, a solution to automate M365 configuration with PowerShell DSC.
So, I am not sure somebody here will be able to answer your question. Maybe it is better to ask this question in the Microsoft 365 support forums or to create a support ticket in the admin portal.

**Comment by andikrueger** [comment]
As @malauter, this repo is for Microsoft365DSC. You could try to raise this issue within the docs repo: https://github.com/MicrosoftDocs/OfficeDocs-Support/blob/public/Outlook/Client/security/can%27t-display-dlp-policytip.md
or create an support ticket. The latter would be the one with the highest chance to get support in regards to this matter.

**Comment by ACK00** [comment]
Gotcha, thanks for the clarification. The last time I used this was for a migration automation with DLP so just came back here.

No worries, thanks.
