### ISSUE TITLE
Planner - using credential authentication, PlannerBucket and PlannerPlan cannot be extracted

### ISSUE THREAD

**Issue by GeorgeChiuTheHartford** [microsoft/Microsoft365DSC#1872]
#### Details of the scenario you tried and the problem that is occurring
Planner - using credential authentication, PlannerBucket and PlannerPlan cannot be extracted which is different than the table in the documentation says .
![image](https://user-images.githubusercontent.com/63079269/162433857-0fece1df-5cd5-4350-885f-8345c9d39c0c.png)
#### Verbose logs showing the problem
```PowerShell
$DscResources = Get-M365DSCAllResources | ?{$_ -like "Planner*"}
foreach($resource in $DscResources)
{
    $FileName = "$resource.ps1"
    Export-M365DSCConfiguration -Path $Path -FileName $FileName -Credential $Credential -Components $resource
}
```
[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted:
PlannerBucket
⌛ Export took {2 seconds}
[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted:
PlannerPlan
⌛ Export took {1 seconds}
#### Suggested solution to the issue
Fix the problem or update documentation with the correct authentication type to use.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running

Windows 10
#### Version of the DSC module that was used ('dev' if using current dev branch)
 1.22.323.1

**Comment by andikrueger** [comment]
Thanks for reporting. This is indeed a limitation of these resource. @ykuijs Could you include this information within the table?

**Comment by ykuijs** [comment]
Great spot! Thanks for the feedback @GeorgeChiuTheHartford

Will submit a PR for this change shortly. Already updated the table based on your feedback during our call. See the updated doc here: https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/
The table on this page will be updated via my PR.

**Comment by KuotingChiu** [comment]
Thanks @ykuijs and @andikrueger ; so with credential authentication, PlannerBucket and PlannerPlan indeeded cannot be exported, correct?  Sorry just want to be clear because the table still show credential authentication is supported for the Planner workload as of 06/04/2011.

**Comment by andikrueger** [comment]
That is very correct. You need to export those workloads with application authentication. 

The PR isn’t merged yet.

**Comment by KuotingChiu** [comment]
I just tried the latest DSC modules and with Certificate Thumbprint authentication and found it prompted for user credential while working on exporting PlannerBucket resources.   The 2nd issue is while there are output on the screen, there is nothing being written to the result ps1 file.   The 3rd issue is it displayed the following warning and I am attaching my script below.  Note the script works well with SPO workload

[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted:
PlannerTask


$Path = "c:\M365DSC\DEV\Application"
$ApplicationId = "appIDnot to display"
$CertificateThumbprint = "thumbprintnottodisplay" 
$TenantId = "hfsgdev.onmicrosoft.com"

$DscResources = Get-M365DSCAllResources | ?{$_ -like "Planner*"}
foreach($resource in $DscResources)
{
    $FileName = "$resource.ps1"
    Export-M365DSCConfiguration -Path $Path -FileName $FileName  -Components $resource -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId
}

**Comment by andikrueger** [comment]
The PR isn’t completed yet. There are various additional fixes on their way that improve authentication and unattended scenarios. See #1990 and #1989 and #1958 for more information. We will keep them updated about the status.
