### ISSUE TITLE
Replace the Use of MSOL by Azure AD

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#19]
The Office365DC module makes use of the MSOL module to create Users and Security Groups. The new recommended approach is to use Azure AD. We need to change references to MSOL to Azure AD in the Util module, the O365User and O365Group Resources.

**Comment by poiriersimon** [comment]
We will need to update function Get-UsersLicences which also rely on the module.

**Comment by brianlala** [comment]
Getting licenses using Get-AzureADUser or even Get-AzADUser could be tricky as neither of these has the IsLicensed or Licences properties.

**Comment by NikCharlebois** [comment]
@brianlala if you have a chance, can you look at O365User and O365Group. The changes in Test-O365ServiceConnection t use AzureAD somehow introduced a bug, because the resources still use MSOL and now the session is no longer connected. Let me know if you prefer I have a look instead. Cheers!

**Comment by brianlala** [comment]
Will do!

**Comment by NikCharlebois** [comment]
@brianlala any updates? HEre are the resources I've identified that still use it:
* O365User
* SPOHubSite

**Comment by andikrueger** [comment]
I just had a quick peek into this issue .

The object returned by `Get-AzureADUser` doesn't come with all attributes, that are available from the user object returned by using `Get-MSLOUser`. 

The following property is missing on the `Microsoft.DirectoryServices.User`object returned by `Get-AzureADUser`
- Fax

As far as I was able to tell, there are no further differences. 

@NikCharlebois any idea on how to proceed?

**Comment by poiriersimon** [comment]
We would need to update the remaining resource to remove the reference. I would rather drop Fax than maintain MSOL. It's in my to do list, but feel free to update the O365User if you have time @andikrueger

**Comment by NikCharlebois** [comment]
Well Fax would have to be maintained. But there's gotta be other ways to obtain that value for sure.

**Comment by andikrueger** [comment]
I will look for other options  to get the fax properly. Deleting Fax would be a breaking change.

**Comment by andikrueger** [comment]
I found a potential way to obtain the `faxNumber`. This can be done by using the Microsoft Graph. 

This request
`
https://graph.microsoft.com/v1.0/users/MeganB@M365x00000.OnMicrosoft.com/?$select=faxNumber
`
returns
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users(faxNumber)/$entity",
    "faxNumber": "+00123456789"
}
```

Currently there is no functionality in place to connect to Microsoft Graph. Connecting to the Microsoft Graph could be done by using the PnPPowerShell. This process would prompt for credentials. Which means, this won't work in an automation scenario (Please, correct me if I'm wrong).

As an alternative we could use an Azure AD Application and provide the app ID and secret to the resources to automate the login. 

@NikCharlebois What is your opinion on this.

**Comment by NikCharlebois** [comment]
@andikrueger We should be able to integrate the connectivity to the Graph and reduce the number of prompts in case of MFA. CC'ing my Auth experts, but Graph should be a problem, and I would actually like for us to start leveraging the graph as much as possible whenever we can.
@poiriersimon @brianlala
