### ISSUE TITLE
PPTenantIsolationSettings: Export not working

### ISSUE THREAD

**Issue by Kirikou974** [microsoft/Microsoft365DSC#1902]
#### Details of the scenario you tried and the problem that is occurring
Export of PPTenantIsolationSettings is not working properly.
It's failing with the following authentication issue.
```
You must specify either the Credential or ApplicationId, TenantId and CertificateThumbprint parameters.
Au caractère C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.413.1\modules\M365DSCUtil.psm1:1407 : 9
+         throw $errorText
+         ~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (You must specif...int parameters.:String) [], RuntimeException
    + FullyQualifiedErrorId : You must specify either the Credential or ApplicationId, TenantId and CertificateThumbprint parameters.

```
#### Verbose logs showing the problem
```
Attempting connection to {PowerPlatforms} with:

Name                           Value                                                                                                                            
----                           -----                                                                                                                            
IsSingleInstance               Yes                                                                                                                              



Dependencies were already successfully validated.
**No Authentication method was provided**

```
#### Suggested solution to the issue
1 fix in the Export-TargetResource function (line 594): 
```
        $Params = @{
            IsSingleInstance = 'Yes'
            Credential = $Credential
        }
```
1 fix in the Get-TargetResource function (line 65) : 
```
$tenantid = $Credential.UserName.Split('@')[1]
```

This is how it is done in PPTenantSettings at least. 

Instead of 
```
$tenantid = (Get-MgContext).TenantId
```

Probably needs some checks in the Set and Test-TargetResource as well.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Export-M365DSCConfiguration -Components @("PPTenantIsolationSettings") -Credential (get-credential)
```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Entreprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64 bits
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : fr-FR
OsMuiLanguages       : {fr-FR, en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.420.1

**Comment by desmay** [comment]
This was resolved with latest release of 1.22.518.1
