### ISSUE TITLE
New-M365DSCReportfromConfiguration - request to save and close

### ISSUE THREAD

**Issue by krugerd** [microsoft/Microsoft365DSC#1904]
#### Details of the scenario you tried and the problem that is occurring
related to issue #1845, now the report does seem to work, but the report stays open on screen.  We are able to provide a -outputpath which gives us a copy of the file, we don't need the file to stay open on screen.  This would be helpful as we want to script this report and not have to find the instance of excel, save and close it or kill it ungracefully.

#### Suggested solution to the issue
close open instance of excel on screen

#### The operating system the target node is running
OsName : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture : 64-bit
WindowsVersion : 2009
WindowsBuildLabEx : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage : en-US
OsMuiLanguages : {en-US, en-GB, fr-CA, fr-FR}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.420.1

**Comment by ykuijs** [comment]
The line that was supposed to close Excel was commented out. Reverted this change and submitted a PR. Will be included in the release of next week.

**Comment by krugerd** [comment]
Thanks kindly @ykuijs !!
