### ISSUE TITLE
Export-M365DSCConfiguration error AADConditionalAccessPolicy (AAD Components)

### ISSUE THREAD

**Issue by krugerd** [microsoft/Microsoft365DSC#1910]
#### Details of the scenario you tried and the problem that is occurring
Errors now using Export-M365DSCConfiguration on the AAD workload components.  This was working in previous versions.

$Components = @("AADConditionalAccessPolicy", "AADGroupLifecyclePolicy")
Export-M365DSCConfiguration -Components $Components -path $path -filename "export_$date.ps1" -Credential $m365creds

#### Verbose logs showing the problem

[1/4] Extracting [AADConditionalAccessPolicy]...Get-MgIdentityConditionalAccessPolicy : You cannot perform the requested operation, required scopes are missing in the token.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.420.1\DSCResources\MSFT_AADConditionalAccessPolicy\M
SFT_AADConditionalAccessPolicy.psm1:1965 char:9
+         [array] $Policies = Get-MgIdentityConditionalAccessPolicy
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType3`8) [Get-MgIdent
   ityC...cessPolicy_List], RestException`1
    + FullyQualifiedErrorId : AccessDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgIdentityConditionalAccessPolicy_Lis   t

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB, fr-CA, fr-FR}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.420.1  (note this worked in previous versions)

**Comment by andikrueger** [comment]
Please make sure to set the graph permissions correctly. See https://microsoft365dsc.com/user-guide/get-started/complete-story/#microsoft-graph-permissions

**Comment by krugerd** [comment]
Thanks Andi.  I did that and it is working once again!  Much appreciated.
