### ISSUE TITLE
Initialize-PnPPowerShellAuthentication obsolet

### ISSUE THREAD

**Issue by informatik-bks** [microsoft/Microsoft365DSC#1912]
Dear Microsoft365 Team

Could you please update the documentation because the part with Initialize-PnPPowerShellAuthentication is now obsolet (https://microsoft365dsc.com/concepts/odsp-permissions/).
See here https://github.com/pnp/powershell/issues/76 now its Register-PnPAzureADApp

Regards Andreas

**Comment by andikrueger** [comment]
@ykuijs Could you add this to the documentation updates?

**Comment by ykuijs** [comment]
Will do! Thanks for the feedback @informatik-bks!
