### ISSUE TITLE
Script completes successfully but does not update config

### ISSUE THREAD

**Issue by yingying96** [microsoft/Microsoft365DSC#1914]
I'm trying to run the script locally first but it does not update my config

The script ended successfully but when i export the config again, the values were not changed (from $False to $True) as highlighted below.

![image](https://user-images.githubusercontent.com/19566726/165910259-aa81450d-1ff5-491f-86f5-46200ffea969.png)

![image](https://user-images.githubusercontent.com/19566726/165910400-b457bf31-2a73-498b-ad69-228ed883a6e6.png)

**Comment by andikrueger** [comment]
Is this still an issue? Some settings are not changed immediately.

**Comment by yingying96** [comment]
I see. Yes. The BlockMacSync is still $False instead of $True.

**Comment by malauter** [comment]
I just tried to reproduce this issue in my lab, but in my case the value of BlockMacSync changes immediately after deploying the configuration.
Could you please check if this still happens after updating M365 DSC, all dependencies and removing outdated dependencies?

`Install-Module Microsoft365DSC -Force`
`Update-M365DSCDependencies`
`Uninstall-M365DSCOutdatedObjects`

**Comment by malauter** [comment]
The Uninstall-M365DSCOutdatedObjects command does not only remove outdated M365 DSC versions, but it also removes outdated dependencies. Can you repeat the test with only having installed the most current versions of the dependencies and no older dependency versions?

**Comment by yingying96** [comment]
Hi guys, thanks for helping to check. I'm still unable to remove the outdated dependencies. Not sure if i'm missing some other imports?

![image](https://user-images.githubusercontent.com/19566726/171075323-fa120116-f7c3-42ce-bcbd-da56d4bac913.png)

**Comment by yingying96** [comment]
Also tried to Get-Module microsoft365dsc | fl but i'm not sure how to see if the uninstall function exist?

![image](https://user-images.githubusercontent.com/19566726/171078675-a6d9e409-e640-4aba-998b-f4b23ba3c217.png)

**Comment by malauter** [comment]
@yingying96 The cmdlet is Uninstall-M365DSCOutdatedDependencies, not Uninstall-M365DSCOutdatedObjects. This is a mistake in our documentation, sorry for that.

**Comment by andikrueger** [comment]
related PR #1977

**Comment by yingying96** [comment]
Thanks! Yes it's still an issue after removing the outdated dependencies.

**Comment by andikrueger** [comment]
Could you try to set this value manually and do an export afterwards? We are not able to reproduce this issue at the moment.
See: https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenantsyncclientrestriction?view=sharepoint-ps

Could you past the verbose of this cmdlet

```powershell

Start-DSCConfiguration -wait -verbose -force -Path <PATH TO YOUR FOLDER HOLDING THE MOF FILE>
```

**Comment by andikrueger** [comment]
Is this happening with any resource within Microsoft 365 DSC? Did you verify the permissions within the tenant? https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/

**Comment by yingying96** [comment]
Yes i tried about 4-5 resource (OneDrive, SharePoint, Power Platform and etc). I'm trying out with credentials first. The account is a global admin.

**Comment by andikrueger** [comment]
Do the applications PnP and Graph have appropriate permissions?

**Comment by yingying96** [comment]
![image](https://user-images.githubusercontent.com/19566726/171191840-2d37aa85-9d6c-43b1-af9a-0808cf29ad8d.png)

Would this be sufficient?

**Comment by andikrueger** [comment]
This will only list the permissions needed. To get these within M365 you would need to run the following command: https://microsoft365dsc.com/user-guide/cmdlets/Update-M365DSCAllowedGraphScopes/

See example 2.

**Comment by yingying96** [comment]
Yup also ran the command to update environment 'global' and received the result "Allowed Graph scopes updated"

**Comment by yingying96** [comment]
Btw may i know if there is a sample on how we can update config/settings (E.g. OneDrive settings) manually using credential? I'm trying to re-setup m365dsc on another device to see if it works on that device.

**Comment by yingying96** [comment]
Here's the full script

```
Configuration ConfigureMicrosoft365
{
    param
    (
        [Parameter(Mandatory = $true)]
        [PSCredential]
        $credsGlobalAdmin
    )

    Import-DscResource -ModuleName Microsoft365DSC
    
    $password = ConvertTo-SecureString -String "PASSWORD HERE" -AsPlainText -Force
    $username = "USERNAMEHERE@gicspo.onmicrosoft.com"
    $cred = New-Object System.Management.Automation.PSCredential($username, $password)

    node localhost
    {
        PPTenantSettings 'PowerPlatformTenantSettings'
        {
            DisableBingVideoSearch                         = $False;
            DisableCapacityAllocationByEnvironmentAdmins   = $False;
            DisableCommunitySearch                         = $False;
            DisableDocsSearch                              = $False;
            DisableEnvironmentCreationByNonAdminUsers      = $True;
            DisableNewsletterSendout                       = $False;
            DisableNPSCommentsReachout                     = $False;
            DisablePortalsCreationByNonAdminUsers          = $False;
            DisableShareWithEveryone                       = $False;
            DisableSupportTicketsVisibleByAllUsers         = $False;
            DisableSurveyFeedback                          = $True;
            DisableTrialEnvironmentCreationByNonAdminUsers = $True;
            EnableGuestsToMake                             = $False;
            IsSingleInstance                               = "Yes";
            ShareWithColleaguesUserLimit                   = 9000;
            WalkMeOptOut                                   = $False;
            Credential                                     = $cred;
        }
    }
}

ConfigureMicrosoft365 -credsGlobalAdmin $cred -ConfigurationData .\M365ConfigurationData.psd1

Start-DscConfiguration -wait -verbose -force -Path D:\Git\Microsoft365Config\ConfigureMicrosoft365
```


![image](https://user-images.githubusercontent.com/19566726/171411021-e5423fac-6681-4878-90df-a771283a7a03.png)

**Comment by yingying96** [comment]
Can i check if the script works for anyone else? Just wondering if my script is wrong or it's a setup issue.

**Comment by zeekoo999** [comment]
@yingying96  Have you managed to solve this issue ? i am having the same problem here. WOuld be really helpfull if you could tell me wht you exactly did to get the changes to be affected.
