### ISSUE TITLE
AADConditionalAccessPolicy: Couldn't find role

### ISSUE THREAD

**Issue by grabery** [microsoft/Microsoft365DSC#1919]
#### Details of the scenario you tried and the problem that is occurring
Tried to deploy an AADConditionalAccessPolicy Resource using M365DSC using v1.22.420.1.
Getting the error in event viewer, that AAD roles are not found, even though they do exist (like Global administrator). Error occurs with every role, no matter which one. Example:
_Couldn't find role Global administrator , couldn't add to policy xyz_

Using the same configuration with _IncludeUsers = @("All")_
instead of _IncludeRoles = @("Global administrator")_
does work perfectly fine...

#### Verbose logs showing the problem
N/A
#### Suggested solution to the issue
N/A
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
v 1.22.420.1

**Comment by rezabj** [comment]
This is fixed in next version. See  #1487.
