### ISSUE TITLE
Columns on microsoft365dsc.com small, lots of white space

### ISSUE THREAD

**Issue by ykuijs** [microsoft/Microsoft365DSC#1923]
Currently the columns on microsoft365dsc.com in which content is displayed is very small, causing the content to be small but long and contain a lot of white space (left and right to the content):
<img width="1905" alt="image" src="https://user-images.githubusercontent.com/15103891/166931193-406815dc-e4b2-4639-b8c3-2c8a1e015314.png">

Could the colums be made a little wider, removing some white space and using more screen real estate for the content?

**NOTE:** I am working on a documentation update as we speak. If you let me know what to change, I will include it in the PR.

**Comment by ykuijs** [comment]
@Laskewitz Could you share what has to be changed to make the center column a bit wider?

**Comment by andikrueger** [comment]
I think this could be solved by modifying the extra.css to include something like mentioned here: https://github.com/squidfunk/mkdocs-material/issues/619

**Comment by andikrueger** [comment]
Tagging #1718 - this one addresses the issue within the resource pages. The tables are to wide to fit into the center area.

**Comment by ykuijs** [comment]
Will be included in my next PR
