### ISSUE TITLE
Cant run Export-M365DSCConfiguration successfully with current set of instructions

### ISSUE THREAD

**Issue by mtaylor1989** [microsoft/Microsoft365DSC#1929]
[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted:
IntuneAppProtectionPolicyAndroid PlannerBucket PlannerPlan TeamsChannelTab
Connecting to {ExchangeOnline}...❌
Cannot find type [MSCloudLoginConnectionProfile]: verify that the assembly containing this type is loaded.
Partial Export file was saved at: C:\Users\SITH~1.MTA\AppData\Local\Temp\2ab116ad-22ae-43c5-b195-2a6ea0a4eb24.partial.ps1

![image](https://user-images.githubusercontent.com/105072677/167182527-b01d14a2-1528-4619-affe-f84a793c96bf.png)

**Comment by desmay** [comment]
Can you try running Update-M365DSCDependencies then rerun the export script.

**Comment by mtaylor1989** [comment]
No Change - thanks for the quick response

![image](https://user-images.githubusercontent.com/105072677/167187911-44d8fa37-22f7-4894-9272-1fd05ebc0ab2.png)

**Comment by andikrueger** [comment]
Could you please try to delete the older versions of M365DSC. There is a cmdLet available to do so: `Uninstall-M365DSCOutdatedDependencies`

Please make sure to close the PS Session afterwards and reopen a new one.

**Comment by SebastianGoers** [comment]
@mtaylor1989 Try updating to the most recent version. For me this has solved the issue.

**Comment by mtaylor1989** [comment]
Installed on a brand new system - mixed results with installing dependencies/updating on PS5 vs PS7. However I am able to run
