### ISSUE TITLE
The member 'GlobalAdminAccount' is not valid.

### ISSUE THREAD

**Issue by chield** [microsoft/Microsoft365DSC#1930]
Hi,

I'm trying to run the first artifacts pipeline and it's giving the following error:

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/33653504/167310663-c319cad0-e26f-488c-9952-eb6a16507776.png">

Any tips how to get this working correctly?

**Comment by chield** [comment]
I've got the pipeline working correctly, changed value GlobalAdminAccount to Credential in M365Configuration.ps1

**Comment by andikrueger** [comment]
Thanks for the feedback. I'll close this issue then.
