### ISSUE TITLE
EXO: Cannot connect to tenant using app/certificate

### ISSUE THREAD

**Issue by wcnitz** [microsoft/Microsoft365DSC#1931]
Cannot connect to EXO with certificate in test tenant environment. Certificate configured the same way in a dev tenant works correctly. We are using the same app and cert to run the AAD workstream in the test tenant - and it connects and operates perfectly. This is occurring in ADO, but I can reproduce this on my own machine using the certificate thumbprint. This appears to only be happening to EXO and only on this tenant despite the configuration - as far as we can tell - being the same. And FYI - the cert is RSA 2048.

When trying to run Start-DSCConfiguration EXO, it errors out with each module (the only error shown for each is below):
2022-05-05T19:35:47.3669987Z VERBOSE: [fv-az377-329]: LCM:  [ End    Test     ]  [[EXOSharingPolicy]91561d4b-8a07-4921-882a-9dc9dd278ed5]  in
2022-05-05T19:35:47.3671452Z 16.0880 seconds.
2022-05-05T19:35:47.4152868Z PowerShell DSC resource MSFT_EXOSharingPolicy  failed to execute Test-TargetResource functionality with error message:
2022-05-05T19:35:47.4159337Z One or more errors occurred.
2022-05-05T19:35:47.4219146Z     + CategoryInfo          : InvalidOperation: (:) [], CimException
2022-05-05T19:35:47.4223864Z     + FullyQualifiedErrorId : ProviderOperationExecutionFailure
2022-05-05T19:35:47.4224557Z VERBOSE: [fv-az377-329]: LCM:  [ Start  Resource ]  [[EXOOrganizationConfig]03bdaf66-1b0e-494d-b8fe-a4a0334dc8c6]

The error when just testing with Connect-M365Tenant:
Connect-M365Tenant -Workload ExchangeOnline -ApplicationId "ourappID" -CertificateThumbprint $output.Thumbprint -TenantId "ourtenantID" -Verbose
Error Acquiring Token:
Could not use the certificate for signing. See inner exception for details. Possible cause: this may be a known issue with apps build against .NET Desktop 4.6 or lower. Either target a higher version of .NET deskt
op - 4.6.1 and above, or use a different certificate type (non-CNG) or sign your own assertion as described at https://aka.ms/msal-net-signed-assertion.
New-ExoPSSession : One or more errors occurred.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\netFramework\ExchangeOnlineManagement.psm1:475 char:30
 ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [New-ExoPSSession], AggregateException
     FullyQualifiedErrorId : System.AggregateException,Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession

**Comment by andikrueger** [comment]
Could you compare the app registrations in the test and dev tenant to verify if there are any differences?

**Comment by wcnitz** [comment]
Both have the same API permissions (including Exchange.ManageAsApp). Both are in the Exchange administrators role in Azure. That's why this is so confusing - the certs were made the same way, the application is configured the same, the certificate works against AAD in the test tenant. That's what makes me think it's something in the tenant configuration, but I'm at a loss as to what to look at.

**Comment by andikrueger** [comment]
Looks like a needle in a haystack...

Did you check your configuration and data file to hold the proper information about certificates and app id?

**Comment by wcnitz** [comment]
It absolutely is, which is why I'm asking here :)

So: the AAD script that runs against Test is identical in terms of the app and configuration. Both pull the cert, PFX password, app id, etc. from the vault (TestCertPassword,TestCERTAUTH,TestAppID,TestTenantDomain, the refernces are the same) and both construct the thumbprint the same because it's done via inline code in the release, and that section is the same across all our workloads (I just re-verified this was the case).

This is the inline script for EXO:
$kvSecretBytes = [System.Convert]::FromBase64String("$(TESTCERTAUTH)")
$certCollection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection
$certCollection.Import($kvSecretBytes, $null, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)

$protectedCertificateBytes = $certCollection.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12, "$(TestCertPassword)")
$pfxPath = [Environment]::GetFolderPath("Desktop") + "\MyCert.pfx"
[System.IO.File]::WriteAllBytes($pfxPath, $protectedCertificateBytes)

$originalDirectory=(Get-Location).path
write-host "$originalDirectory"
Set-Location Cert:\LocalMachine\My\
$pwd = ConvertTo-SecureString -String "$(TestCertPassword)" -Force -AsPlainText
$output=Import-PfxCertificate -FilePath $pfxPath -Password $pwd
write-host "Thumbprint: $($output.Thumbprint)"
cd $originalDirectory

winrm quickconfig -force
Install-Module Microsoft365DSC -Force -AllowClobber
Update-M365DSCDependencies
cd '_EXOBuild\Combo-EXO'
.\EXOM365DSC.ps1 -ApplicationId $(TestAppId) -CertificateThumbprint $output.Thumbprint -Domain $(TestTenantDomain)
Start-DSCConfiguration EXO -Wait -Verbose -Force

This is the inline script for AAD:
$kvSecretBytes = [System.Convert]::FromBase64String("$(TESTCERTAUTH)")
$certCollection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection
$certCollection.Import($kvSecretBytes, $null, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)

$protectedCertificateBytes = $certCollection.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12, "$(TestCertPassword)")
$pfxPath = [Environment]::GetFolderPath("Desktop") + "\MyCert.pfx"
[System.IO.File]::WriteAllBytes($pfxPath, $protectedCertificateBytes)

$originalDirectory=(Get-Location).path
write-host "$originalDirectory"
Set-Location Cert:\LocalMachine\My\
$pwd = ConvertTo-SecureString -String "$(TestCertPassword)" -Force -AsPlainText
$output=Import-PfxCertificate -FilePath $pfxPath -Password $pwd
write-host "Thumbprint: $($output.Thumbprint)"
cd $originalDirectory

winrm quickconfig -force
Install-Module Microsoft365DSC -Force -AllowClobber
Update-M365DSCDependencies
cd '_AADBuild\Combo-AAD'
.\AADM365DSC.ps1 -ApplicationId $(TestAppId) -CertificateThumbprint $output.Thumbprint -Domain $(TestTenantDomain)
Start-DSCConfiguration AAD -Wait -Verbose -Force

Ran compare-object against both just as a sanity check, and the only differences are the folders and command lines for PS1 and DSC (which are expected, but are otherwise the same).  This is why I keep going back to something being off on the tenant side.

**Comment by andikrueger** [comment]
Could you verify that you are able to connect to EXO without M365DSC? Something like that:

`Connect-ExchangeOnline -CertificateFilePath "C:\Users\johndoe\Desktop\automation-cert.pfx" -CertificatePassword (ConvertTo-SecureString -String "<MyPassword>" -AsPlainText -Force) -AppID "36ee4c6c-0812-40a2-b820-b22ebd02bce3" -Organization "contosoelectronics.onmicrosoft.com"`

Maybe this helps to get a better error message or a pointer, where the issue occurs.

**Comment by wcnitz** [comment]
Same issue I get with connect-M365Tenant (and this is from my local machine, not ADO):
Error Acquiring Token:
Could not use the certificate for signing. See inner exception for details. Possible cause: this may be a known issue with apps build against .NET Desktop 4.6 or lower. Either target a higher version of .NET desktop - 4.6.1 and above, or use a different certificate type (non-CNG) or sign your own assertion as described at https://aka.ms/msal-net-signed-assertion.
New-ExoPSSession : One or more errors occurred.
At C:\Program
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\netFramework\ExchangeOnlineManagement.psm1:475 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ExoPSSession], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSess
   ion

**Comment by wcnitz** [comment]
Also, FWIW - we also just deployed this same app/cert configuration against that tenant for SPO/OD as well, which works correctly.

**Comment by wcnitz** [comment]
That was the first thing I checked because that's what came up in search results - it's RSA, not CNG. It's essentially the same properties as the one we use in the other tenant:
![image](https://user-images.githubusercontent.com/105226553/167724963-e43ee91d-13f7-4b27-b97b-231db7cd31fc.png)
Both have the same key usage, etc. And the cert works fine against AAD, SPO, etc.
I'm going to try a self-signed certificate next.

**Comment by LeonJansen** [comment]
It looks like your algorithm is sha265RSA on the left and sha1RSA on the right. 

The Microsoft documentation has an example where also a SHA1 cert is used for the authentication. So i think your problem is in that area. See the [Microsoft Docs](https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps#step-3-generate-a-self-signed-certificate)

**Comment by wcnitz** [comment]
Except we have this one:
![image](https://user-images.githubusercontent.com/105226553/167835593-fcdd3af7-bb4c-43da-b62b-853b5291f6b7.png)
This works 100% correctly against the 'dev' tenant EXO. Yes, the documentation says sha1, but MS doesn't even officially support sha1 anymore and it shouldn't be used.
I don't think it's the use of sha256, because then the dev tenant certificate wouldn't work, either.

**Comment by smaddock** [comment]
Does the EXU on the non-working cert contain Client Authentication? It’s truncated in the screenshot.

**Comment by wcnitz** [comment]
Yep, client and server (both the dev and test certs match in this regard).
They are both:
Server Authentication (1.3.6.1.5.5.7.3.1)
Client Authentication (1.3.6.1.5.5.7.3.2)

**Comment by andikrueger** [comment]
@wcnitz Did you succeed to get around this issue?

**Comment by wcnitz** [comment]
> @wcnitz Did you succeed to get around this issue?

Nope. We've opened a Premier ticket. Saw the same issue with the certificate we acquired for the production tenant.

**Comment by andikrueger** [comment]
Please let us know, what was causing the issue. Would be great to have some more insights on this.

I would close this issue for now, as it does look like an issue, that is not entirely M365DSC related.

**Comment by martincaddick** [comment]
Please re-open. I'm seeing this issue with 1.23.222.1 using appID, certThumb and tenantID
Certificate works for AAD, SPO, TEAMS, PP.
Fails on EXO and SC. I'll do more testing on the other workloads.
If I run Connect-ExchangeOnline from within that PS session and then auth with global reader perms then the script works ok

**Comment by andikrueger** [comment]
@martincaddick Could you create a new issue for that and reference this one? Looks like there is something going not as expected and needs more investigation.

**Comment by ds-brandao** [comment]
Aye All, 

Not sure if this has been solved yet. I just wanted to leave a comment here since I had the exact same issue, but I was able to figure it out. 

In my case, I was attempting to import a cert into my local machine to allow a svc acc to use it when connecting to an azure app. After importing the cert with the private key into the 'personal' store, you still need to authorize the acc to be able to use it, otherwise, it gives the issue: 

```powershell
Could not use the certificate for signing. See inner exception for details. Possible cause: this may be a known issue with apps build against .NET Desktop 4.6 or lower. Either target a higher version of .NET desktop - 4.6.1 and above, or use a different certificate type (non-CNG) or sign your own assertion as described at https://aka.ms/msal-net-signed-assertion. 
```

To allow users to have access to the cert, you need to: right-click on the cert > All tasks > Manage private keys > add > search for the acc in the domain (give it full control) and bag it worked. 

This is just a test that I made for an automated task that needs to connect to EXO.

**Comment by satyajit321** [comment]
> Aye All,
> 
> Not sure if this has been solved yet. I just wanted to leave a comment here since I had the exact same issue, but I was able to figure it out.
> 
> In my case, I was attempting to import a cert into my local machine to allow a svc acc to use it when connecting to an azure app. After importing the cert with the private key into the 'personal' store, you still need to authorize the acc to be able to use it, otherwise, it gives the issue:
> 
> ```powershell
> Could not use the certificate for signing. See inner exception for details. Possible cause: this may be a known issue with apps build against .NET Desktop 4.6 or lower. Either target a higher version of .NET desktop - 4.6.1 and above, or use a different certificate type (non-CNG) or sign your own assertion as described at https://aka.ms/msal-net-signed-assertion. 
> ```
> 
> To allow users to have access to the cert, you need to: right-click on the cert > All tasks > Manage private keys > add > search for the acc in the domain (give it full control) and bag it worked.
> 
> This is just a test that I made for an automated task that needs to connect to EXO.

Fantastic, you made my day today!  Who thought importing a certificate on a new laptop can be so tricky.

**Comment by philpre** [comment]
I know this is pretty old, but I experienced the same problem as being described here. The way I resolved it was by creating an Exchange Certificate from an install of Exchange Server, using New-ExchangeCertificate, and applying no services to it. That, exported to Azure, worked with EXO.

**Comment by Briggidy** [comment]
In my case, I switched from a Self-Signed cert to domain cert and my error went away.
