### ISSUE TITLE
Applications without a signed-in user are not allowed access to this report or data

### ISSUE THREAD

**Issue by myacaman** [microsoft/Microsoft365DSC#1937]
Hello, I am getting the following error message below when I run the export DSC for conditional access. I read in another thread that the app needs to be assigned to an enterprise application but mine is already an enterprise application in AAD. Any further troubleshooting or resolution ideas?

Connecting to {MicrosoftGraph}...✅
[1/1] Extracting [AADConditionalAccessPolicy]...Get-MgIdentityConditionalAccessPolicy : Applications without a signed-in user are not allowed access to this report or data.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.420.1\DSCResources\MSFT_AADConditionalAccessPolicy\MSFT_AADConditionalAccessPolicy.psm1:1965 char:9
+ [array] $Policies = Get-MgIdentityConditionalAccessPolicy
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidOperation: ({ Top = , Skip ...ndProperty = }:<>f__AnonymousType3`8) [Get-MgIdentityC...cessPolicy_List], RestException`1
+ FullyQualifiedErrorId : AccessDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgIdentityConditionalAccessPolicy_List

**Comment by andikrueger** [comment]
Did you assign your app the required permissions? This guide might be helpful to get around this issue> https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/#microsoft-graph-permissions

**Comment by myacaman** [comment]
Yes, thank you. It was indeed an oauth permission issue.
