### ISSUE TITLE
Creating Documentation is Empty

### ISSUE THREAD

**Issue by mtaylor1989** [microsoft/Microsoft365DSC#1940]
After getting everything installed
1. when running with credential (as a global admin) I get several errors for not having permissions
2. when running with app id & secret - I see this error for AADGroupLifecyclePolicy - TenantID must be in format contosto.microsoft.com
3. Once completed from 2 - I run New-M365DSCReportFromConfiguration -type html -ConfigurationPath D:\Microsoft365DSC\AAD1.ps1 -OutputPath D:\Microsoft365DSC\Reports\aad.html and it loads and creates the html file but its only 1kb and no content in the file.

Am I missing something or a bug?

**Comment by andikrueger** [comment]
I did a quick test on this matter and was able to generate a proper report by using Microsoft365DSC Version 1.22.518.1. Could you update your module and retry?

This should be of help to make sure, you are having the latest resources available:

```powershell
Update-Module Microsoft365DSC
Update-M365DSCDependencies
Uninstall-M365DSCOutdatedDependencies
```

**Comment by hilocz** [comment]
I had same problem, but running Uninstall-M365DSCOutdatedDependencies fixed the issue.

**Comment by andikrueger** [comment]
@mtaylor1989 Is the issue still present?

**Comment by andikrueger** [comment]
Thanks for the quick reply. I'll close this issue.
