### ISSUE TITLE
Compare-M365DSCConfigurations not recognized

### ISSUE THREAD

**Issue by myacaman** [microsoft/Microsoft365DSC#1966]
Hello all, we are trying to run the Compare-M365DSCConfigurations command and we are getting that it is not recognized. We have installed the DSC module  and updated it several times but it does not seem to recognize this command. Please see the error message below. Can anyone provide some guidance onto what is going on? We are able to successfully run the compare command  in our test tenant instance. Thank you in advance for your help.

-------------------------
Compare-M365DSCConfigurations : The term 'Compare-M365DSCConfigurations' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:28
+ $aadcaPoliciesComparison = Compare-M365DSCConfigurations -Source $dsc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (Compare-M365DSCConfigurations:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

**Comment by myacaman** [comment]
We are able to run the command with version 1.22.105.1. The second we update to 1.22.511.1 or 1.22.518.1 we get the error message that it cannot be recognized.

Output
ModuleType Version Name ExportedCommands
---------- ------- ---- ----------------
Manifest 1.22.518.1 Microsoft365DSC {Assert-M365DSCBlueprint, Assert-M365DSCTemplate, Compare-M365DSCConfigurations, Confirm-M365DSCDependencies...

Manifest 1.22.511.1 Microsoft365DSC {Assert-M365DSCBlueprint, Assert-M365DSCTemplate, Compare-M365DSCConfigurations, Confirm-M365DSCDependencies...

Manifest 1.22.105.1 Microsoft365DSC {Assert-M365DSCBlueprint, Assert-M365DSCTemplate, Compare-M365DSCConfigurations, Confirm-M365DSCDependencies...

**Comment by andikrueger** [comment]
Could you run the following commands

Update-Module Microsoft365DSC
Update-M365DSCDependencies
Uninstall-M365DSCOutdatedDependencies

This should remove all old versions of the module and outdated dependencies too. There will be an error during the uninstall. Please close the powershell session and rerun the third command afterwards.

**Comment by myacaman** [comment]
I ran the commands as you said and indeed got some errors. Then I rerun the uninstall as you suggested and I get the errors below.

PS C:\Windows\system32> Uninstall-M365DSCOutdatedDependencies
Uninstalling Microsoft.Graph.Authentication version {1.9.5}
PackageManagement\Uninstall-Package : The module 'Microsoft.Graph.Authentication' of version '1.9.5' in module base folder 'C:\ProgramFiles\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.9.5' cannot be uninstalled, because one or more other modules 'Microsoft.Graph.Applications,Microsoft.Graph.DeviceManagement,Microsoft.Graph.DeviceManagement.Administration,Microsoft.Graph.DeviceManagement.Enrolment,Microsoft.Graph.Devices.CorporateManagement,Microsoft.Gra
ph.Groups,Microsoft.Graph.Identity.DirectoryManagement,Microsoft.Graph.Identity.Governance,Microsoft.Graph.Identity.SignIns,Microsoft.Graph.Planner,Microsoft.Graph.Teams,Microsoft.Graph.Users' are dependent on this module. Uninstall the modules that depend on this module before uninstalling module 'Microsoft.Graph.Authentication'.



At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:12733 char:21
+ ... $null = PackageManagement\Uninstall-Package @PSBoundParameters
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidOperation: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Package], Exception
+ FullyQualifiedErrorId : UnableToUninstallAsOtherModulesNeedThisModule,Uninstall-Package,Microsoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage

Uninstalling Microsoft.Graph.Authentication version {1.9.1}
PackageManagement\Uninstall-Package : The module 'Microsoft.Graph.Authentication' of version '1.9.1' in module base folder 'C:\ProgramFiles\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.9.1' cannot be uninstalled, because one or more other modules 'Microsoft.Graph.Applications,Microsoft.Gr
aph.DeviceManagement,Microsoft.Graph.DeviceManagement.Administration,Microsoft.Graph.DeviceManagement.Enrolment,Microsoft.Graph.Devices.CorporateManagement,Microsoft.Graph.Groups,Microsoft.Graph.Identity.DirectoryManagement,Microsoft.Graph.Identity.Governance,Microsoft.Graph.Identity.SignIns,Microsoft.Graph.Planner,Microsoft.Graph.Teams,Microsoft.Graph.Users' are dependent on this module. Uninstall the modules that depend on this module before uninstalling module 'Microsoft.Graph.Authentication'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:12733 char:21
+ ... $null = PackageManagement\Uninstall-Package @PSBoundParameters
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidOperation: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Package], Exception
+ FullyQualifiedErrorId : UnableToUninstallAsOtherModulesNeedThisModule,Uninstall-Package,Microsoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage

**Comment by andikrueger** [comment]
There was a new release a few minutes ago. This should include a fix for the error messages above.

**Comment by myacaman** [comment]
Thanks. I just reran the update commands as you suggested above and although we do get the newest version, 1.22.525.1 we are still getting the same error.

Compare-M365DSCConfigurations : The term 'Compare-M365DSCConfigurations' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:28
+ $aadcaPoliciesComparison = Compare-M365DSCConfigurations -Source $dsc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (Compare-M365DSCConfigurations:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

**Comment by andikrueger** [comment]
Could you run the following to see, if the module is loaded correctly:

Get-Module Microsoft365DSC | fl

This should show all exported functions.

**Comment by myacaman** [comment]
This is what we get.

Name : Microsoft365DSC
Path : C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.525.1\Microsoft365DSC.psd1
Description : This DSC module is used to configure and monitor Microsoft tenants, including SharePoint Online, Exchange, Teams, etc.
ModuleType : Manifest
Version : 1.22.525.1
NestedModules : {M365DSCAgent, M365DSCErrorHandler, M365DSCLogEngine, M365DSCPermissions...}
ExportedFunctions : {Add-M365DSCEvent, Add-M365DSCTelemetryEvent, Assert-M365DSCBlueprint, Confirm-ImportedCmdletIsAvailable...}
ExportedCmdlets :
ExportedVariables :
ExportedAliases :


I then expand the exported functions and I get this.

Set-M365DSCAgentCertificateConfiguration Set-M365DSCAgentCertificateConfiguration
Test-M365DSCAgent Test-M365DSCAgent
Save-M365DSCPartialExport Save-M365DSCPartialExport
Add-M365DSCEvent Add-M365DSCEvent
Export-M365DSCDiagnosticData Export-M365DSCDiagnosticData
New-M365DSCLogEntry New-M365DSCLogEntry
Get-M365DSCCompiledPermissionList Get-M365DSCCompiledPermissionList
Update-M365DSCAllowedGraphScopes Update-M365DSCAllowedGraphScopes
Update-M365DSCResourcesSettingsJSON Update-M365DSCResourcesSettingsJSON
New-M365DSCDeltaReport New-M365DSCDeltaReport
New-M365DSCReportFromConfiguration New-M365DSCReportFromConfiguration
Start-M365DSCConfigurationExtract Start-M365DSCConfigurationExtract
New-M365DSCStubFiles New-M365DSCStubFiles
Add-M365DSCTelemetryEvent Add-M365DSCTelemetryEvent
Format-M365DSCTelemetryParameters Format-M365DSCTelemetryParameters
Get-M365DSCTelemetryOption Get-M365DSCTelemetryOption
Set-M365DSCTelemetryOption Set-M365DSCTelemetryOption
Assert-M365DSCBlueprint Assert-M365DSCBlueprint
Confirm-ImportedCmdletIsAvailable Confirm-ImportedCmdletIsAvailable
Confirm-M365DSCDependencies Confirm-M365DSCDependencies
Convert-M365DscHashtableToString Convert-M365DscHashtableToString
ConvertTo-SPOUserProfilePropertyInstanceString ConvertTo-SPOUserProfilePropertyInstanceString
Export-M365DSCConfiguration Export-M365DSCConfiguration
Get-AllSPOPackages Get-AllSPOPackages
Get-M365DSCAllResources Get-M365DSCAllResources
Get-M365DSCAuthenticationMode Get-M365DSCAuthenticationMode
Get-M365DSCComponentsForAuthenticationType Get-M365DSCComponentsForAuthenticationType
Get-M365DSCExportContentForResource Get-M365DSCExportContentForResource
Get-M365DSCOrganization Get-M365DSCOrganization
Get-M365DSCTenantDomain Get-M365DSCTenantDomain
Get-M365DSCWorkloadsListFromResourceNames Get-M365DSCWorkloadsListFromResourceNames
Get-M365TenantName Get-M365TenantName
Get-SPOAdministrationUrl Get-SPOAdministrationUrl
Get-SPOUserProfilePropertyInstance Get-SPOUserProfilePropertyInstance
Get-TeamByName Get-TeamByName
Import-M365DSCDependencies Import-M365DSCDependencies
Install-M365DSCDevBranch Install-M365DSCDevBranch
Invoke-M365DSCCommand Invoke-M365DSCCommand
New-EXOSafeAttachmentRule New-EXOSafeAttachmentRule
New-EXOSafeLinksRule New-EXOSafeLinksRule
New-M365DSCCmdletDocumentation New-M365DSCCmdletDocumentation
New-M365DSCConnection New-M365DSCConnection
New-M365DSCMissingResourcesExample New-M365DSCMissingResourcesExample
Remove-EmptyValue Remove-EmptyValue
Remove-NullEntriesFromHashtable Remove-NullEntriesFromHashtable
Set-EXOSafeAttachmentRule Set-EXOSafeAttachmentRule
Set-EXOSafeLinksRule Set-EXOSafeLinksRule
Split-ArrayByParts Split-ArrayByParts
Test-M365DSCDependenciesForNewVersions Test-M365DSCDependenciesForNewVersions
Test-M365DSCNewVersionAvailable Test-M365DSCNewVersionAvailable
Test-M365DSCParameterState Test-M365DSCParameterState
Uninstall-M365DSCOutdatedDependencies Uninstall-M365DSCOutdatedDependencies
Update-M365DSCDependencies Update-M365DSCDependencies
Update-M365DSCExportAuthenticationResults Update-M365DSCExportAuthenticationResults
Format-M365DSCString Format-M365DSCString

I dont seem to see the compare one.

**Comment by myacaman** [comment]
@andikrueger We tried using the delta module instead, but it is not working from us because it only allows exporting the report in excel of html format. The compare module instead, allowed us to export the report as PS object so we can use it later to add additional data. is there a way we can leverage the delta report module to output a PS object? What do you recommend?

**Comment by andikrueger** [comment]
As a short term solution you could modify the file \modules\M365DSCReport.psm1 To export compare-m365dscconfigurations. 

To do so you need to add the function to the array in lines 1050-1053.

**Comment by ykuijs** [comment]
@andikrueger Yes, I will remove this from the module manifest!
