### ISSUE TITLE
Multiple matching items

### ISSUE THREAD

**Issue by martynstar** [microsoft/Microsoft365DSC#1971]
Hi there
If we are doing a DSC against a policy which potentially could be a different name, or has multiple policies, how does the blueprint assessment or comparison work?

For example we have a compliancy policy for PCs and one for Laptops.
They both need bitlocker, but we want to know the difference against our blueprint for each compliance policy.
For example someone created policy 1 with no firewall requirements, and the blueprint says it should be on.
It seems to ignore any policy with a different name?

**Comment by andikrueger** [comment]
This is a very specific use-case and currently not supported. The comparison of two configurations uses the keys of the resources. For this resource, the display name is the key property. As soon as there is a difference, the resource will be handled as a unique resource within the configuration. 

I see the use-case. At the moment, your only chance would be to either use a naming convention on those display names and run a search/replace within the configuration to have a match with the blueprint requirements.

**Comment by martynstar** [comment]
Is it completed or just closed?
