### ISSUE TITLE
The permissions needed for using application id/certificate authentication on Export-M365DSCConfiguration with Power Platform workload is unknown

### ISSUE THREAD

**Issue by KuotingChiu** [microsoft/Microsoft365DSC#1979]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by andikrueger** [comment]
Please follow this article about permissions and authentication methods to determine the needed permissions for power platform. 

https://microsoft.github.io/Microsoft365DSC/user-guide/get-started/authentication-and-permissions/

If there is something missing, provide more details about the Szenario you are trying to realise.

**Comment by KuotingChiu** [comment]
The latest M365DSC module returns error with "Certificate Thumbprint" authentication.   Will the authentication table be updated ?

PS C:\WINDOWS\system32>    Export-M365DSCConfiguration -Path $Path -FileName $FileName  -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId -Workload PP
[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted:
PPTenantIsolationSettings
⌛ Export took {11 seconds}

**Comment by ykuijs** [comment]
This was also reported in issue #2032. As it turns out, the Planner APIs currently only support credentials authentication.

I am working on an update of the Planner resource to fix this issue and to switch to Credentials authentication. This PR will be submitted asap. Currently testing some last items.

**Comment by KuotingChiu** [comment]
How about Power Platform?  What types of authentication is supported?

**Comment by ykuijs** [comment]
That should support Credential, Certificate Thumbprint and Application Secret.

**Comment by KuotingChiu** [comment]
Please see the result of using certificate thumbprint authentication.    PPTenantIsolationSettings cannot be extracted with it.


PS C:\WINDOWS\system32>    Export-M365DSCConfiguration -Path $Path -FileName $FileName  -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId -Workload "PP"
[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted:
PPTenantIsolationSettings
⌛ Export took {12 seconds}

**Comment by NikCharlebois** [comment]
After further investigation, while the PowerApps module accepts ApplicationId/TenantId/Thumbprint/secret, it does not support authenticating with it. Please ensure you connect using Credentials for the Power Platform resources. We will be updating documentation and removing the parameters.
