### ISSUE TITLE
Install-NuGetClientBinaries does not allow Runbook to export configuration 

### ISSUE THREAD

**Issue by aexlz** [microsoft/Microsoft365DSC#1983]
#### Details of the scenario you tried and the problem that is occurring
We tried to run the script as a AzureRunbook. 
We also made use of this source (https://o365eh.com/2020/10/27/episode-74-using-microsoft-dsc-as-a-runbook-in-azure-automation/) 
We run the command leveragring an EnterpriseApplication with Certificate as follows:
`Export-M365DSCConfiguration  -Components @("IntuneAppConfigurationPolicy", "IntuneAppProtectionPolicyAndroid", "IntuneAppProtectionPolicyiOS", "IntuneDeviceCompliancePolicyAndroid", "IntuneDeviceCompliancePolicyAndroidDeviceOwner", "IntuneDeviceCompliancePolicyAndroidWorkProfile", "IntuneDeviceCompliancePolicyiOs", "IntuneDeviceCompliancePolicyMacOS", "IntuneDeviceCompliancePolicyWindows10") -ApplicationId $enterpriseApplicationClientId -CertificateThumbprint $certificate.thumprint -TenantId $directoryTenantId -path $path -filename "runbook_$date.ps1" *>&1 | out-null`

The same script runs perfectly fine locally. 

#### Verbose logs showing the problem
```
Install-NuGetClientBinaries : Exception calling "ShouldContinue" with "2" argument(s): "A command that prompts the user 
failed because the host program or the command type does not support user interaction. The host was attempting to 
request confirmation with the following message: PowerShellGet requires NuGet provider version '2.8.5.201' or newer to 
interact with NuGet-based repositories. The NuGet provider must be available in 'C:\Program 
Files\PackageManagement\ProviderAssemblies' or 'C:\Users\Client\AppData\Roaming\PackageManagement\ProviderAssemblies'. 
You can also install the NuGet provider by running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 
-Force'. Do you want PowerShellGet to install and import the NuGet provider now?"
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1762 char:9
+         Install-NuGetClientBinaries -CallerPSCmdlet $PSCmdlet -Proxy  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-NuGetClientBinaries], MethodInvocationException
    + FullyQualifiedErrorId : HostException,Install-NuGetClientBinaries

```
#### Suggested solution to the issue
No idea yet. 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Unfortunately we are not even able to pull the configuration.

#### Version of the DSC module that was used ('dev' if using current dev branch)
Microsoft365dsc existing: v1.22.601.1, required: v1.22.601.1

**Comment by andikrueger** [comment]
Thanks for reporting.
The source is a few years old and there was a change in Microsoft365DSC on the handling of dependencies. We do no longer have the dependencies within the module manifest. They are within a separate file. Therefor the script Get-Dependency will not find all information needed. Please make sure to have a look at this PowerShell Data File:

https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Dependencies/Manifest.psd1

and make sure, that these modules are available within your runbook.

**Comment by aexlz** [comment]
Hi Andi,
thanks a lot for your comment. That actually solved the problem .
It would be a huge advantage if there might be an example on [](https://microsoft365dsc.com/) about how to run this script within a Azure Runbook. Running this script locally is going to be legacy in 1-2 years. 
Best
Axel

**Comment by andikrueger** [comment]
Thanks for the feedback. Currently, we are working on the documentation. We are tracking additions to the documentation and changes within this issue: #1836

**Comment by Kikaider** [comment]
FYI: See issue #2050 for additional information.
