### ISSUE TITLE
Export-M365DSCConfiguration AADGroupLifecyclePolicy

### ISSUE THREAD

**Issue by duber3** [microsoft/Microsoft365DSC#1985]
#### Details of the scenario you tried and the problem that is occurring
Export-M365DSCConfiguration AADGroupLifecyclePolicy with ApplicationID and CertificateThumbprint, there is no data
    [2/7] Extracting [AADGroupLifecyclePolicy]...❌
    everything else is OK, I've try with the module version 1.22.525.1 and 1.22.601.1 same result
    If I use an globalAdmin account it works
#### Verbose logs showing the problem
Connecting to {MicrosoftGraph}...✅
[1/1] Extracting [AADGroupLifecyclePolicy]...VERBOSE: Attempting connection to {MicrosoftGraph} with:
VERBOSE: 
Name                           Value                                                                                                                                              
----                           -----                                                                                                                                              
CertificateThumbprint          xxxxxxx                                                                                                          
TenantId                       xxxxxxx                                                                                                               
ApplicationId                  xxxxxxx                                                                                                               

VERBOSE: Dependencies were already successfully validated.
VERBOSE: ApplicationId, TenantId, CertificateThumbprint were specified. Connecting via Service Principal
VERBOSE: Dependencies were already successfully validated.
❌
⌛ Export took {6 seconds}

**Comment by andikrueger** [comment]
Thanks for reporting. 

Is this only happening with AADGroupLifecyclePolicy or with other resources as well?

**Comment by duber3** [comment]
only AADGroupLifecyclePolicy

**Comment by NikCharlebois** [comment]
We are not able to replicate. Please ensure your app registration has been granted the required Directory.Read.All permission and try exporting again. Thanks

**Comment by duber3** [comment]
Yes my App Registration have the Directory.All permission
