### ISSUE TITLE
Tenant Clone will not work

### ISSUE THREAD

**Issue by KlaBier** [microsoft/Microsoft365DSC#1986]
Hi,

I had exports from my source and target tenant, only with components  AADConditionalAccessPolicy. I can compare both, everything is fine with that

But when I try to compile with " M365TenantConfig" with the target tenant credential, I get the error
  "At least one of the values '' is not supported or valid for property 'DeviceFilterMode' on class
 'AADConditionalAccessPolicy'. Please specify only supported values:"  

Can you let me know where my error is?

Thanks 
Klaus

**Comment by andikrueger** [comment]
What version of microsoft365dsc are you using? 

This issue hot resolved a while ago and there is a change implemented to remove DeviceFilterMode from the export if it's null or empty. 

DeviceFilterMode has a validate set to only allow include and exclude as values. 

To update your m365dsc module you could run the following lines of code:

Update-Module Microsoft365DSC
Update-M365DSCDependencies
Uninstall-M365DSCOutdatedDependencies

This will install the latest version and uninstall all older versions and dependencies.

**Comment by KlaBier** [comment]
Hi Andi,
this solves my problem. Works perfect for me :-) Thanks a lot
