### ISSUE TITLE
Code that updates the Graph permissions in the settings.json does not work correctly

### ISSUE THREAD

**Issue by ykuijs** [microsoft/Microsoft365DSC#1989]
#### Details of the scenario you tried and the problem that is occurring
M365DSC has a function to update the settings.json based on the used Graph cmdlets in a resource. This code first grabs all used Graph cmdlets in a resource and then uses Find-MgGraphCommand to retrieve the permissions required these cmdlets.

Unfortunately the Find-MgGraphCommand cmdlet doesn't work as expected. The ordering of the returned permissions seem to be alphabetical, where the documentation has a different order:

**Get-MgTeamChannel permissions, ordered alphabetically (Directory before Group)**
![image](https://user-images.githubusercontent.com/15103891/171826008-f5ee8faf-cf33-4739-b934-85fdae2325e3.png)

**Graph API documentation, using a different order (Group before Directory)**
![image](https://user-images.githubusercontent.com/15103891/171826022-448d6c72-82e2-4336-b6ab-b0041920212c.png)
[Source](https://docs.microsoft.com/en-us/graph/api/channel-list)

#### Suggested solution to the issue
Needs to get fixed by the Graph team. Created issue for documentation and tracking purposes.

**Comment by ykuijs** [comment]
Difference in Group cmdlet

**Output of Get-MgGroup cmdlet**
<img width="854" alt="image" src="https://user-images.githubusercontent.com/15103891/171826658-91042e7f-3181-421c-b12d-a89e44e356b8.png">

**Graph API documentation (different order and missing Directory.AccessAsUser.All)**
<img width="593" alt="image" src="https://user-images.githubusercontent.com/15103891/171827153-c581d65a-980a-4b0f-ae8f-d10fbbe5ea22.png">
[Source](https://docs.microsoft.com/en-us/graph/api/group-get)

**Comment by ykuijs** [comment]
Difference for Agreement

**Output for Get-MgAgreement (no permissions required)**
![image](https://user-images.githubusercontent.com/15103891/171827670-339fcab5-dbe2-4f2c-ad54-20ad762c793d.png)

**Graph API documentation (requires a single permission)**
<img width="588" alt="image" src="https://user-images.githubusercontent.com/15103891/171827866-452c6825-01f0-455d-8611-a1079a9c6bc2.png">
[Source](https://docs.microsoft.com/en-us/graph/api/agreement-get)

**Comment by ykuijs** [comment]
Looks like the Graph Explorer is using the same ordering (alphabetical) as the Find-MgGraphCommand.

**Example for getting Team Channel, same ordering as the cmdlet:**
<img width="848" alt="image" src="https://user-images.githubusercontent.com/15103891/171828811-6c72d65e-efa0-41cf-a790-b2a55497ad7b.png">

**Example for getting Groups, same ordering as the cmdlet:**
<img width="848" alt="image" src="https://user-images.githubusercontent.com/15103891/171828642-25d31f37-66c1-4b47-8d64-e67700cc35a9.png">

**Comment by NikCharlebois** [comment]
My understanding is that this has been fixed in recent version of the Microsoft Graph SDK. @ykuijs can you please confirm?
