### ISSUE TITLE
Export-M365DSCConfiguration All Teams configuration with App registration

### ISSUE THREAD

**Issue by duber3** [microsoft/Microsoft365DSC#1992]
#### Details of the scenario you tried and the problem that is occurring
Base on the authenticated methods that are supported, I should be able to extract the configuration of Teams with a service Principal and Certificate Thumbprint
![image](https://user-images.githubusercontent.com/38050244/171855836-c5e4af94-8603-4252-997c-87694ebd8d1f.png)

but I think the connect-MicrosoftTeams is not supported with and AppID and certificate Thumprint,
https://docs.microsoft.com/en-us/microsoftteams/teams-powershell-release-notes
<html>
<body>

July 2021 | 2.4.1-preview | Grant cmdlets changes now available.New Voice related cmdlets are released.Removal of certificate thumbprint authentication for -Cs* cmdlets.Logging fix for logging files of all cmdlets.Fixes issues with *TeamChannelUser cmdlets.
-- | -- | --

</body>
</html>

[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted: 
TeamsCallingPolicy TeamsChannelsPolicy TeamsClientConfiguration TeamsEmergencyCallingPolicy TeamsEmergencyCallRoutingPolicy TeamsFederationConfiguration TeamsGuestCallingConfigura
tion TeamsGuestMeetingConfiguration TeamsGuestMessagingConfiguration TeamsMeetingBroadcastConfiguration TeamsMeetingBroadcastPolicy TeamsMeetingConfiguration TeamsMeetingPolicy Te
amsMessagingPolicy TeamsPstnUsage TeamsTenantDialPlan TeamsUpgradeConfiguration TeamsUpgradePolicy TeamsVoiceRoute TeamsVoiceRoutingPolicy
⌛ Export took {6 seconds}

#### Verbose logs showing the problem
[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted: 
TeamsCallingPolicy TeamsChannelsPolicy TeamsClientConfiguration TeamsEmergencyCallingPolicy TeamsEmergencyCallRoutingPolicy TeamsFederationConfiguration TeamsGuestCallingConfigura
tion TeamsGuestMeetingConfiguration TeamsGuestMessagingConfiguration TeamsMeetingBroadcastConfiguration TeamsMeetingBroadcastPolicy TeamsMeetingConfiguration TeamsMeetingPolicy Te
amsMessagingPolicy TeamsPstnUsage TeamsTenantDialPlan TeamsUpgradeConfiguration TeamsUpgradePolicy TeamsVoiceRoute TeamsVoiceRoutingPolicy
⌛ Export took {6 seconds}

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```
module version M365DSC 1.22.601.1
MicrosoftTeams 4.4.1

**Comment by andikrueger** [comment]
Please see #1990 and #1989 and #1958 for more information in regards to the various authentication use-cases and the current state of it. There is work going on to improve the authentication across all workloads.
