### ISSUE TITLE
The authentication method for Teams workload

### ISSUE THREAD

**Issue by KuotingChiu** [microsoft/Microsoft365DSC#1996]
#### Details of the scenario you tried and the problem that is occurring
According to the documentation authentication table, both credential authenticate and certificate thumbprint authentication should work but it does not seems so
#### Verbose logs showing the problem

PS C:\WINDOWS\system32> Export-M365DSCConfiguration -Path $Path -FileName $FileName  -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId -Workload "Teams"
[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted:
TeamsCallingPolicy TeamsChannelsPolicy TeamsClientConfiguration TeamsEmergencyCallingPolicy TeamsEmergencyCallRoutingPolicy TeamsFederationConfiguration TeamsGuestCallingConfiguration TeamsGuestMeetingConfiguration TeamsGuestMessagingConfiguration TeamsMeetingBroadcastConfiguration TeamsMeetingBroadcastPolicy TeamsMeetingConfiguration TeamsMeetingPolicy TeamsMessagingPolicy TeamsPstnUsage TeamsTenantDialPlan TeamsUpdateManagementPolicy TeamsUpgradeConfiguration TeamsUpgradePolicy TeamsVoiceRoute TeamsVoiceRoutingPolicy
#### Suggested solution to the issue
Verified which authentication methods really work and update the documentation.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
latest 1.22.601.1, I did not see this issue before with the earlier module

**Comment by ykuijs** [comment]
Recently issue #1992 was reported, in which the removal of the Certificate/Service Principal for the Teams module was shared. Unfortunately this is not yet fully documented in Microsoft365DSC. I am working on that as we speak.

So at the moment, Teams resources only support Credentials.

**Comment by ykuijs** [comment]
Closing this issue, since this is "as-designed"
