### ISSUE TITLE
EXOTransportRule: General topic of dependencies in M365DSC - Feature Request

### ISSUE THREAD

**Issue by T630Dev** [microsoft/Microsoft365DSC#1997]
ISSUE DESCRIPTION (this template):

We encountered several occasions where either  a dependency between M365DSC ressources is required or in case of the EXOTransportRule, an order would be required for n instances of the same DSC res.
The goal should be that the first run of the LCM is successful. Of course, if I run the start-dscConfiguration n times, the dependant resources were created so that the second time the LCM runs, less errors occur.
Our goal is, however, to execute M365DSC in Azure DevOps pipelines and hence we need the first run to work correctly and handle dependencies accordingly.

#### Details of the scenario you tried and the problem that is occurring

Example 1: Before the LCM can execute and correctly create a SCRetentionComplianceRule, the SCRetentionCompliancePolicy needs to be created before so that it can reference it correctly.
The similar principle also applies for EXOQuarantinePolicy and the EXOMalwareFilterPolicy (QuarantaineTag attribute).

Example 2: When I define ExoTransportRules and I require a certain order, I provide the Priority attribute. However, since M365DSC does not ensure that prio 1 is created before prio 2, all Transport Rule creations fail, except for the first one. So if I have 10 transport rules (prio 1-10), it requires 10 runs of the DSC config to ensure that all rules are in place correctly.

#### Suggested solution to the issue

1. Include a dependency management between DSC resources.
2. Include an execution order management for n instances of the same DSC res. (like the EXOTransportRule)

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.601.1

**Comment by T630Dev** [comment]
ok thanks. We will have a look at this option. Another one might be to have the DSC configuration and hence the resulting MOF file already in the correct order so that the LCM will then implicitly execute the items in the correct order.

Please do not close the issue, yet, as I agreed with Nik to have all open issues registered in GitHub, even though there might not be an immediate solution at our fingertips.

**Comment by T630Dev** [comment]
> I already tagged this one as on-hold.
> 
> this issue is a great example on what can cause cloning tenants or reapplying configurations to fail and what needs to be done to have a better user experience.

ok, no worries, on hold is no problem.

That's true. You only come to realize after some time of using M365DSC what might be potential issues that you would not have by using a classical sequential PS script. It's great to have the opportunity to try to improve the experience going forward.

**Comment by NikCharlebois** [comment]
Linking to #597

**Comment by NikCharlebois** [comment]
Closing this one and keeping #597
