### ISSUE TITLE
SCSensitivityLabel - DisplayName can be duplicated which causes issues in Delta reports

### ISSUE THREAD

**Issue by rayakajamon** [microsoft/Microsoft365DSC#2008]

**Comment by rayakajamon** [comment]
Hi Andi, here is what I am trying to convey....

For example, we can have a label Highly Confidential with DisplayName 'Contains Personal Information' and we can have another label ‘Confidential’ with same DisplayName ‘Contains Personal Information'

Delta reports treat these two different labels as the same, due to the DisplayName value and generates incorrect output in the reports.

Does that help any?

Thank you

-Ray
"Where your treasure is, there your heart will be also" (Luke 12:34)
________________________________

**Comment by andikrueger** [comment]
Thanks a lot. This is a good examples and shows a further challenge we do have with exports.

There are various resources that use the (display) name as key parameter. I raised another issue #2006 that mentions this behavior.

**Comment by rayakajamon** [comment]
Really appreciate the feedback and help, Andi.

Thanks for the support!

-Ray
"Where your treasure is, there your heart will be also" (Luke 12:34)
________________________________

**Comment by NikCharlebois** [comment]
@rayakajamon can you provide additional information on how to replicate the scenario? We are unable to create two labels at the same hierarchy level with the same name. Thanks
![image](https://user-images.githubusercontent.com/2547149/180518382-bc84a997-91a5-4ceb-ab11-6c87592d2ec6.png)

**Comment by rayakajamon** [comment]
My apologies Nik for the delay, I have missed some time to covid.

I got the below back from the customer

In Microsoft Information Protection / Sensitivity Labels, you can create sub-labels to the main labels.  For instance:


  *   Public
  *   General
  *   Confidential
     *   Contains Personal Information
     *   Does not Contain Personal Information
  *   Highly Confidential
     *   Contains Personal Information
     *   Does not Contain Personal Information
Note the two sets of sub-labels have the same display name.  The DSC tool should be looking at the GUID’s of the labels, which will be unique, and not the physical display names, which can be identical.

We have a longstanding DCR with Microsoft to make multi-labeling a real thing, vs. having redundant sub-labels, but this is not in the product as of yet.

-Ray Gonzalez
***@***.***
________________________________

**Comment by andikrueger** [comment]
https://github.com/microsoft/Microsoft365DSC/blob/6d83ac929003ece7b8f916592077da05d668a08b/Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.schema.mof#L14-L17

This resource does only define one key parameter. This key needs to be unique. As you pointed out, the label name can be reused at different levels. these levels are handled, but are not part of the set key parameters.

Adding the `ParentId` as a secondary key could solve this problem, but would raise another issue on how to add a top level label, as `$null`or an empty string would not be a valid value for this key.
https://github.com/microsoft/Microsoft365DSC/blob/6d83ac929003ece7b8f916592077da05d668a08b/Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.schema.mof#L22


Using the Id of the label is no option either, as we do not know this Id during creation time. (see: #2006)

**Comment by NikCharlebois** [comment]
Still, I don't know how to reproduce this scenario. Trying to replicate your scenario, I get the following error when using the same name/display name for two sub-labels with a different parent id:
![image](https://user-images.githubusercontent.com/2547149/195926896-b297a76f-a6e4-4bb1-acce-318bec99ae8d.png)

Just giving it a different displayname doesn't work, the Name property is the key. So I append a '2' at the end of the Name portion and it gets created. Doing that, I end up with the following:
![image](https://user-images.githubusercontent.com/2547149/195927153-0b3f3b52-4b27-47a4-9f97-eab6c17d3d1e.png)

Through PowerShell, here is what I am getting:
![image](https://user-images.githubusercontent.com/2547149/195927265-697f98bc-9978-4f29-98e4-d32507238a13.png)

The Get-TargetResource uses the Name property and not the DisplayName, therefore this ensures we don't ever have a naming conflict even for sub-labels

**Comment by NikCharlebois** [comment]
I am however able to reproduce the issue with Delta report. It's as if the function thinks DisplayName is the primary key. Stay tuned

**Comment by NikCharlebois** [comment]
Problem comes from here: https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Modules/M365DSCReport.psm1#L691

Will be looking at making this more dynamic

**Comment by NikCharlebois** [comment]
Will also work on adding support for ParentId as a separate PR
