### ISSUE TITLE
SharePoint framework code release pipeline is failing 

### ISSUE THREAD

**Issue by soundd2** [microsoft/Microsoft365DSC#2012]
SharePoint framework code release pipeline is failing ,  I have used following MS blog but failing 
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops 

build pipeline is succeeded, release pipeline is failing:

**Release pipeline flow:** 
 
![image](https://user-images.githubusercontent.com/94822959/174009784-8bb56dd1-626d-437b-abda-fff9b4839a6a.png)

**Error:**
![image](https://user-images.githubusercontent.com/94822959/174009869-7686ab23-5d7d-4326-8ba2-ec81a501a338.png)

**Logs:**
[ReleaseLogs_24 (2).zip](https://github.com/microsoft/Microsoft365DSC/files/8918649/ReleaseLogs_24.2.zip)

**Comment by NikCharlebois** [comment]
I would recommend opening an issue in one of the SPfx repositorie: https://github.com/topics/sharepoint-framework. Unfortunately this is not something this group can help with since it is not related to Microsoft365DSC

**Comment by soundd2** [comment]
Hi Nik,

Could you please transfer to that community as I am unable to create new issue in the community you gave
