### ISSUE TITLE
Microsoft365DSC in a Script and its throwing error about msGraph

### ISSUE THREAD

**Issue by veeranagarajan** [microsoft/Microsoft365DSC#2027]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
PowerShell Ver 5.1

**Comment by NikCharlebois** [comment]
Can you please provide additional information on how to replicate your issue? Thanks

**Comment by veeranagarajan** [comment]
@NikCharlebois - Thanks I have removed the Microsoft365DSC outdated dependencies and removed the legacy version
