### ISSUE TITLE
New-M365DSCDeltaReport has parameter $OutputPath marked as mandatory

### ISSUE THREAD

**Issue by alexlehto** [microsoft/Microsoft365DSC#2029]
Hi, I have run into a issue. the New-M365DSCDeltaReport always open the browser to show the delta report. Looking at the source it seems like there was a option to get the output as a string to use for instance in a email. Unfortunately I have not found a way to get that.

#### Details of the scenario you tried and the problem that is occurring
Since the parameter $OutputPath is marked as mandatory, the cmdlet New-M365DSCDeltaReport will always invoke the HTML file and the option of getting that data returned as a string is never reached.
https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Modules/M365DSCReport.psm1
```powershell
    if (-not [System.String]::IsNullOrEmpty($OutputPath))
    {
        $reportSB.ToString() | Out-File $OutputPath
        Invoke-Item $OutputPath
    }
    else
    {
        return $reportSB.ToString()
    }
```

#### Suggested solution to the issue
Change:
```powershell
      [Parameter(Mandatory = $true)]
        [System.String]
        $OutputPath,
```
to not require the parameter to be mandatory

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.22.622.1 Microsoft365DSC

**Comment by andikrueger** [comment]
Thanks for reporting. This looks like a unreachable code.
