### ISSUE TITLE
SPOSharingSettings: DefaultLinkPermission has wrong ValidateSet

### ISSUE THREAD

**Issue by andikrueger** [microsoft/Microsoft365DSC#2034]
#### Details of the scenario you tried and the problem that is occurring
Setting the SPOSharingSettings Perameter `DefaultLinkPermission` to `None` will result in an error. Currently, there is only View or Edit supported.

#### Verbose logs showing the problem

```
Default link permission value must be Edit or View 
+ CategoryInfo : WriteError: (:) [], CimException 
+ FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Admin.SetTenant + PSComputerName : localhost
```

#### Suggested solution to the issue
Fix the Validate Set to only allow Edit or View.

**Comment by desmay** [comment]
@andikrueger It looks like if you never set this value it comes back as none via PNP and you can set it to None. Once set to View or Edit then you can no longer set back to None. 

<img width="523" alt="image" src="https://user-images.githubusercontent.com/43035577/176267305-a426f60b-6728-43b2-ac45-17221edf01d7.png">

Created a trial tenant and it looks like the default value is set to Edit 
<img width="239" alt="image" src="https://user-images.githubusercontent.com/43035577/176268897-5a8cd777-79c8-4fc0-8523-e6152f67ee17.png">

and PNP returns None
<img width="317" alt="image" src="https://user-images.githubusercontent.com/43035577/176269082-59ca8d9d-b30b-463b-9cc9-36d48170869f.png">

**Comment by desmay** [comment]
Interesting latest SharePoint Online module returns save value None.  I'm open to suggestions on how to handle this issue.

**Comment by andikrueger** [comment]
I would go with this description and overwrite the value `None` to be replaced with the actual default of `Edit`

![image](https://user-images.githubusercontent.com/15608729/176380770-cae38973-8159-49ec-94b5-cbbeededee55.png)

**Comment by andikrueger** [comment]
Additional Note on this one. The actual enum `SharingPermissionType` within the `Microsoft.Online.SharePoint.Client.Tenant` class has the three values: https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/mt813308(v=office.15)

I would still go with the two settable values of Edit and View.
