### ISSUE TITLE
Export-M365DSCConfiguration fails in a not elevated PowerShell session.

### ISSUE THREAD

**Issue by andikrueger** [microsoft/Microsoft365DSC#2037]
#### Details of the scenario you tried and the problem that is occurring
Running an export of a confugiration fails within a not elevated PowerShell session with the following error:

<img width="900" alt="image" src="https://user-images.githubusercontent.com/15608729/176177171-a5d41469-1201-4543-b889-0153080e9c45.png">

The reuqest to the local configuration manager should be optional and not made as long as the user is not an admin.

**Comment by ykuijs** [comment]
Am working on an update to the export functionality as we speak. Will include this issue right away.
