### ISSUE TITLE
Assert Blueprint detects no resources to assess

### ISSUE THREAD

**Issue by martynstar** [microsoft/Microsoft365DSC#2048]
#### Details of the scenario you tried and the problem that is occurring
Trying to run a Blueprint
This pop up shows no items to assess
Selected BluePrint contains (0) components to assess.
Initiating the Export of those (0) components from the tenant...
i have a blueprint as submitted on issue #2007 

This then goes about trying to extract the whole of the m365 settings.
I am only trying to sort Endpoint/intune at the moment, but i get 186 options being downloaded.
I have tried a straight export with the intune settings, and then running it back as a blueprint (incase versions have changed it) but it doesnt detect anything to assess.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# Generated by Microsoft365DSC from https://export.microsoft365dsc.com on 6/30/2022, 12:37:47 PM
# Visit https://microsoft365dsc.com for more information

# Getting client credential
$Credential = Get-Credential

# Exporting resources using credentials
Export-M365DSCConfiguration -Components @("IntuneAppConfigurationPolicy", "IntuneApplicationControlPolicyWindows10", "IntuneAppProtectionPolicyAndroid", "IntuneAppProtectionPolicyiOS", "IntuneASRRulesPolicyWindows10", "IntuneDeviceCategory", "IntuneDeviceCompliancePolicyAndroid", "IntuneDeviceCompliancePolicyAndroidDeviceOwner", "IntuneDeviceCompliancePolicyAndroidWorkProfile", "IntuneDeviceCompliancePolicyiOs", "IntuneDeviceCompliancePolicyMacOS", "IntuneDeviceCompliancePolicyWindows10", "IntuneDeviceConfigurationPolicyAndroidDeviceOwner", "IntuneDeviceConfigurationPolicyAndroidWorkProfile", "IntuneDeviceConfigurationPolicyiOS", "IntuneDeviceConfigurationPolicyWindows10", "IntuneDeviceEnrollmentLimitRestriction", "IntuneDeviceEnrollmentPlatformRestriction", "IntuneSettingCatalogASRRulesPolicyWindows10") -Credential $Credential
```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2022 Datacenter Azure Edition
OsOperatingSystemSKU : 407
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.1.amd64fre.fe_release.210507-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
#### Version of the DSC module that was used ('dev' if using current dev branch)
Generated with Microsoft365DSC version 1.22.629.1

**Comment by martynstar** [comment]
Also seems just doing an export and then compare is not working either.

New-M365DSCDeltaReport
With totally different settings, reports no difference.
Even if i strip out intune and place teams - no difference!

**Comment by martynstar** [comment]
Oh no! so the DSC portion of this is effectively broken!

We can import and export but not actually check what state its at!

**Comment by ykuijs** [comment]
This only applies to the SCSensitivityResource, all other resources should be fine.

Also, you should still be able to do a Test-DscConfiguration to see if your tenant is still in the Desired State or not.
Just the Delta report and documentation generation do not work as expected. They both use the DSCParser module.

**Comment by ykuijs** [comment]
Settings keyword is using to create Meta Configurations / LCM Configuration, for example:

```PowerShell
[DSCLocalConfigurationManager()]
configuration LCMConfig
{
    Node localhost
    {
        Settings
        {
            RefreshMode = 'Push'
        }
    }
}
```

**Comment by andikrueger** [comment]
You can test your configuration like this:

```powershell
Test-DscConfiguration -Path "C:\Dsc\Configurations"
```

This requires you to have .mof file within the folder specified.

**Comment by martynstar** [comment]
OK so this command is not in the scope of m365dsc
Its the same DSC setup but totally different ways of working, so just running 
Test-DscConfiguration -Path "C:\Dsc\Configurations"
Will not work.
I'll have to spend some time actually changing files to MOF as they aren't natively done and the documentation for this is not clear

**Comment by ykuijs** [comment]
Performing a Test-DscConfiguration is default PowerShell Desired State Configuration functionality. In order to do this, you:
1. Create a DSC Configuration (PS1 and potentially a PSD1 file), either manually or by running the export
2. Compile this configuration into a MOF file
3. Run the Test-DscConfiguration command to have the Local Configuration Manager test the Microsoft 365 tenant against the baseline you created in step 1
4. The output of the Test-DscConfiguration cmdlet is a list of resources that are in and a list of resource that are not in the desired state.

More information can be found here: https://microsoft365dsc.com/user-guide/get-started/deploying-configurations/

**Comment by ykuijs** [comment]
To learn more about the basic of DSC, I highly recommend watching this training: [Getting Started with PowerShell Desired State Configuration](https://docs.microsoft.com/en-us/shows/getting-started-with-powershell-dsc/)!

**Comment by martynstar** [comment]
It did actually create a report this time, I'll grab the blueprint and share it here, but I'm sure I just did an export and then tested it again.
Before the last update, any blueprint was not able to see any items to check again and we basically just check every single item against nothing from the blueprint.

**Comment by NikCharlebois** [comment]
Ok, then would you consider this issue fixed? Thanks

**Comment by martynstar** [comment]
I'm not sure if it's working correctly or not, I didn't get a chance to do it yet today but will share blueprint shortly
