### ISSUE TITLE
CICD Microsoft365dsc

### ISSUE THREAD

**Issue by Brijeshoo7** [microsoft/Microsoft365DSC#2051]
HI,

i have created pipeline in Azure devops for office365DSC and also the build and release pipeline give me success signs but it done not taking any effect on tenant of office365.

i have attached complete log of pipeline as zip file. also adding error snap.

[ReleaseLogs_45.zip](https://github.com/microsoft/Microsoft365DSC/files/9020275/ReleaseLogs_45.zip)

![image](https://user-images.githubusercontent.com/88958817/176693393-450f9fc8-fa75-48af-8c1f-6e62eae6ab2a.png)

please let me know if anything else required.

Thanks,
Brijesh.

**Comment by ykuijs** [comment]
Hi @Brijeshoo7, does the service account you used for the DevOps Agent have local admin permissions?

**Comment by Brijeshoo7** [comment]
Hi Yorick,

i am using 365Dsc as service connection.

![image](https://user-images.githubusercontent.com/88958817/176845684-3ae77dd0-e332-41c4-ad38-6f0d164bdad5.png)

and i have checked in IAM it has owner permission.

![image](https://user-images.githubusercontent.com/88958817/176845855-103ba642-869a-4e52-ba16-0b8a465f7e8b.png)

yet the same issue, let me know if i am missing at some point to check.

**Comment by SebastianGoers** [comment]
This service connection grants access to Azure but not to Microsoft 365 if I am not fully mistaken.

**Comment by andikrueger** [comment]
The error message indicates, that you do not have access to Local Configuration Manager on the agent executing the configuration. What kind of Agent are you using to run the apply the configuration?

**Comment by Brijeshoo7** [comment]
i was using self-hosted agent.

**Comment by Brijeshoo7** [comment]
Configuration O365
{
    Import-DscResource -ModuleName Microsoft365DSC
    $password = ConvertTo-SecureString 'password' -AsPlainText -Force
    $GlobalAdmin = New-object System.Management.Automation.PSCredential ('brijesh@sainath94907gmail.onmicrosoft.com', $password)
    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine

    Node windows
    {
        # Add code changes
        TeamsTeam 'ConfigureTeam'
        {
            DisplayName                       = "Sample3"
            Description                       = "Sample"
            Visibility                        = "Private"
            MailNickName                      = "DSCTeam2"
            AllowUserEditMessages             = $false
            AllowUserDeleteMessages           = $false
            AllowOwnerDeleteMessages          = $false
            AllowTeamMentions                 = $false
            AllowChannelMentions              = $false
            allowCreateUpdateChannels         = $false
            AllowDeleteChannels               = $false
            AllowAddRemoveApps                = $false
            AllowCreateUpdateRemoveTabs       = $false
            AllowCreateUpdateRemoveConnectors = $false
            AllowGiphy                        = $True
            GiphyContentRating                = "strict"
            AllowStickersAndMemes             = $True
            AllowCustomMemes                  = $True
            AllowGuestCreateUpdateChannels    = $true
            AllowGuestDeleteChannels          = $true
            Ensure                            = "Present"
            Credential                        = $GlobalAdmin
        }
    
    }
}

$ConfigData = @{
    AllNodes = @(
        @{
            NodeName                    = "windows"
            PsDSCAllowPlaintextPassword = $true
            PSDscAllowDomainUser = $true
        }
    )
}

#$ConfigData = @{...}
O365 -ConfigurationData $ConfigData
Start-DscConfiguration O365 -Wait -Verbose -Force

**Comment by Brijeshoo7** [comment]
i am using above script. even in local machine its not working for me. can you check if the script is missing something.? 

and thank you very much all for your reply.

**Comment by andikrueger** [comment]
@Brijeshoo7 please make sure your user that runs the script is local admin on the self hosted system. Otherwise the command will fail. 


Additionally: please make sure to have the right password within your script. If it is password (as pasted above) please make sure to change it to a more secure one as its now exposed.

**Comment by Brijeshoo7** [comment]
@andikrueger
 thanks that is not the correct password in the above script i am keeping it secure.

i am getting below errors in local.

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'class
Name' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'class
Name' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
The WinRM client cannot process the request. If the authentication scheme is different from Kerberos, or if the 
client computer is not joined to a domain, then HTTPS transport must be used or the destination machine must be 
added to the TrustedHosts configuration setting. Use winrm.cmd to configure TrustedHosts. Note that computers in the 
TrustedHosts list might not be authenticated. You can get more information about that by running the following 
command: winrm help config.
    + CategoryInfo          : NotEnabled: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : HRESULT 0x803380e4
    + PSComputerName        : windows
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: An LCM method call arrived from computer INSTANCE-2 with user sid S-1-5-21-3467950567-2264422270-1698932121-5
00.
VERBOSE: [INSTANCE-2]: LCM:  [ Start  Set      ]
VERBOSE: [INSTANCE-2]: LCM:  [ Start  Resource ]  [[TeamsTeam]ConfigureTeam]
VERBOSE: [INSTANCE-2]: LCM:  [ Start  Test     ]  [[TeamsTeam]ConfigureTeam]
VERBOSE: [INSTANCE-2]:                            [[TeamsTeam]ConfigureTeam] Testing configuration of Team Sample3
VERBOSE: [INSTANCE-2]:                            [[TeamsTeam]ConfigureTeam] Getting configuration of Team Sample3
VERBOSE: [INSTANCE-2]: LCM:  [ End    Test     ]  [[TeamsTeam]ConfigureTeam]  in 19.7520 seconds.
PowerShell DSC resource MSFT_TeamsTeam  failed to execute Test-TargetResource functionality with error message: One 
or more errors occurred. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
VERBOSE: [INSTANCE-2]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 20.455 seconds

**Comment by Brijeshoo7** [comment]
If this script will success in local than i will figure out the way to use in Azure DevOps. and for local i am already running this script in administrator user.

**Comment by andikrueger** [comment]
Maybe these two line of code could be helpful to setup your local environment:

```powershell

Write-Log -Message 'Setting up WinRM'

winrm quickconfig -force -quiet

```

Please add them to your deploy scrip before calling start-dscconfiguration.

**Comment by Brijeshoo7** [comment]
#$ConfigData = @{...}
Write-Log -Message 'Setting up WinRM'
winrm quickconfig -force -quiet

O365 -ConfigurationData $ConfigData
Start-DscConfiguration O365 -Wait -Verbose -Force


I have added CMD here. as i am running the script using Powershell ISE.

still giving the errors.

**Comment by Brijeshoo7** [comment]
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'class
Name' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'class
Name' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'class
Name' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
The WinRM client cannot process the request. If the authentication scheme is different from Kerberos, or if the 
client computer is not joined to a domain, then HTTPS transport must be used or the destination machine must be 
added to the TrustedHosts configuration setting. Use winrm.cmd to configure TrustedHosts. Note that computers in the 
TrustedHosts list might not be authenticated. You can get more information about that by running the following 
command: winrm help config.
    + CategoryInfo          : NotEnabled: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : HRESULT 0x803380e4
    + PSComputerName        : windows
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: An LCM method call arrived from computer INSTANCE-2 with user sid S-1-5-21-3467950567-2264422270-1698932121-5
00.
VERBOSE: [INSTANCE-2]: LCM:  [ Start  Set      ]
VERBOSE: An LCM method call arrived from computer INSTANCE-2 with user sid S-1-5-21-3467950567-2264422270-1698932121-5
00.
VERBOSE: The -Force option was specified with the Stop operation. The current configuration has been successfully canc
elled.
VERBOSE: [INSTANCE-2]: LCM:  [ End    Set      ]
VERBOSE: An LCM method call arrived from computer INSTANCE-2 with user sid S-1-5-21-3467950567-2264422270-1698932121-5
00.
The current configuration was cancelled.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : instance-2
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: [INSTANCE-2]: LCM:  [ Start  Set      ]
VERBOSE: [INSTANCE-2]: LCM:  [ Start  Resource ]  [[TeamsTeam]ConfigureTeam]
VERBOSE: [INSTANCE-2]: LCM:  [ Start  Test     ]  [[TeamsTeam]ConfigureTeam]
VERBOSE: [INSTANCE-2]:                            [[TeamsTeam]ConfigureTeam] Testing configuration of Team Sample3
VERBOSE: [INSTANCE-2]:                            [[TeamsTeam]ConfigureTeam] Getting configuration of Team Sample3
VERBOSE: [INSTANCE-2]: LCM:  [ End    Test     ]  [[TeamsTeam]ConfigureTeam]  in 1.9880 seconds.
PowerShell DSC resource MSFT_TeamsTeam  failed to execute Test-TargetResource functionality with error message: One 
or more errors occurred. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
VERBOSE: [INSTANCE-2]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

**Comment by andikrueger** [comment]
Please switch to a locally elevated powershell (not ise) and start the configuration. ISE has known limitations in this regards.

**Comment by Brijeshoo7** [comment]
![image](https://user-images.githubusercontent.com/88958817/177112797-f9ca0baa-a02a-4bab-a71d-9ce800075c66.png)


same in normal powershell.

would you like to take remote access and check?

**Comment by andikrueger** [comment]
Thanks for configuration. Could you try to run “Test-WSMan”

**Comment by andikrueger** [comment]
Additional Test-WSMan -Authentication default

**Comment by Brijeshoo7** [comment]
i have used above script but the main changes was to use global admin user without MFA enabled and it worked.

**Comment by Brijeshoo7** [comment]
OR maybe the placement for the credential was wrong. but if the MFA enabled how to use credentials than. is there any secure way to use same with azure devops?

**Comment by andikrueger** [comment]
You could have a look at this article in regards to authentication: https://microsoft365dsc.com/user-guide/get-started/authentication-examples/
Within the whitepaper there is a separate section about security enhancements. Chapter 5. https://office365dsc.azurewebsites.net/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf

**Comment by Brijeshoo7** [comment]
Thank you very much to all of you for your time. i am closing the issue now.

**Comment by Brijeshoo7** [comment]
![image](https://user-images.githubusercontent.com/88958817/187215610-7354840c-c27b-4bcf-abcb-e1640afdcc29.png)
Hi @andikrueger 
trying in personal azure devops server getting this issue.
