### ISSUE TITLE
M365DSC: PowerShell 7.2 EventLogs

### ISSUE THREAD

**Issue by fldried** [microsoft/Microsoft365DSC#2053]
#### Details of the scenario you tried and the problem that is occurring
When running e.g the Export-M365DSCConfiguration cmdlet, using PS 7.2 will result in an errorlog being created due to *-EventLog no longer being supported: 
https://docs.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7.2#-eventlog-cmdlets

#### Verbose logs showing the problem
```powershell
[2022-07-01 10:16:59]
{ObjectNotFound}
System.Management.Automation.CommandNotFoundException: The term 'Write-EventLog' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Could not write to event log Source {Microsoft365DSC} EntryType {Error} Message {The file exists. (0x80070050)}"
at Add-M365DSCEvent, C:\Users\<omitted>\Documents\PowerShell\Modules\Microsoft365DSC\1.22.622.1\modules\M365DSCLogEngine.psm1: line 142
at Start-M365DSCConfigurationExtract, C:\Users\<omitted>\Documents\PowerShell\Modules\Microsoft365DSC\1.22.622.1\modules\M365DSCReverse.psm1: line 644
at Export-M365DSCConfiguration, C:\Users\<omitted>\Documents\PowerShell\Modules\Microsoft365DSC\1.22.622.1\modules\M365DSCUtil.psm1: line 1131
at <ScriptBlock>, C:\<omitted>.ps1: line 109
at <ScriptBlock>, <No file>: line 1
```
Error Log created at {C:\<omitted>\22072-M365DSC-ErrorLog.log}

#### Suggested solution to the issue
Remove the *-EventLog calls in favor of *-WinEvent

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# freshly installed dsc
# only ran Export-M365DSCConfiguration cmdlet in powershell 7.2
```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : de-DE
OsMuiLanguages       : {de-DE, en-GB, en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by andikrueger** [comment]
Thanks for reporting. At the moment we support PS 5.1 and 7.1.

**Comment by NikCharlebois** [comment]
PowerShell 7.2 support is on the roadmap as Andi points out. Will be closing this issue for the moment. Thanks
