### ISSUE TITLE
Removing TeamsVoiceRoutingPolicy fails due to deprecated parameter

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#2055]
#### Details of the scenario you tried and the problem that is occurring
Although mentioned in [the documentation](https://docs.microsoft.com/en-us/powershell/module/skype/remove-csonlinevoiceroutingpolicy?view=skype-ps), removing a TeamsVoiceRoutingPolicy will fail as the Confirm parameter in https://github.com/microsoft/Microsoft365DSC/blob/98ec8a940baf01a261809f7705cd0f213df1ce83/Modules/Microsoft365DSC/DSCResources/MSFT_TeamsVoiceRoutingPolicy/MSFT_TeamsVoiceRoutingPolicy.psm1#L178 is not supported.
#### Verbose logs showing the problem
```
remove-CsOnlineVoiceRoutingPolicy -identity myPolicyName -confirm:$false
remove-CsOnlineVoiceRoutingPolicy : A parameter cannot be found that matches parameter name 'Confirm'.
```
#### Suggested solution to the issue
Remove the -confirm parameter in https://github.com/microsoft/Microsoft365DSC/blob/98ec8a940baf01a261809f7705cd0f213df1ce83/Modules/Microsoft365DSC/DSCResources/MSFT_TeamsVoiceRoutingPolicy/MSFT_TeamsVoiceRoutingPolicy.psm1#L178
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by malauter** [comment]
I also requested an update of the linked documentation of the cmdlet.
