### ISSUE TITLE
I need help with M365 DSC configuration

### ISSUE THREAD

**Issue by laxmip01** [microsoft/Microsoft365DSC#2059]
Can i Raise a support case, if I want support what is the best support which is suitable for getting the required troubleshooting and guidance.

**Comment by malauter** [comment]
Microsoft365DSC is an Open-Source initiative, lead by Microsoft engineers and maintained by the community. The support is also community driven. Therefore, you cannot raise a Microsoft support case to get support. If you need guidance, please create an issue on this Github page with all the details about your issue or use the discussions section of the Github project. You can also find more resources, including a user guide, on our website https://microsoft365dsc.com/

**Comment by ykuijs** [comment]
Getting started documentation: https://microsoft365dsc.com/user-guide/get-started/introduction/
Prerequisites to get started with Microsoft365DSC: https://microsoft365dsc.com/user-guide/get-started/prerequisites/

Especially when you are new to PowerShell Desired State Configuration, I highly recommend watching this excellent training series:
https://docs.microsoft.com/en-us/shows/getting-started-with-powershell-dsc/

**Comment by ykuijs** [comment]
Closing this issue for now. Please reopen if you have any more questions about M365DSC support or open another issue if you need help with a specific issue.
