### ISSUE TITLE
Microsoft 365 DSC configuration 

### ISSUE THREAD

**Issue by laxmip01** [microsoft/Microsoft365DSC#2060]
Dear Team,
Can I use Microsoft 365 DSC configuration to apply the settings to the tenant.
For example, Can i apply SPO tenant settings. If i use exportDSC and export a certain configuration and it generates a M365TenantConfig.ps1 and ConfigurationData.psd1 
using this exported .ps1 can i modify some configuration and reapply to the tenant. 

I wish to push the configuration using Microsoft 365 DSC is it possibe, like creating groups, users etc.
please suggest, if yes where can i find end to end repository that can be modifed and used for applying configuration.

**Comment by malauter** [comment]
Hi @laxmip01, yes, it is possible to export the configuration of e.g. SPO and apply it to the same or another tenant. You can also modify the exported configuration. Please follow the user guide for more information: https://microsoft365dsc.com/user-guide/get-started/introduction/

**Comment by ykuijs** [comment]
Creating an export of an existing tenant: https://microsoft365dsc.com/user-guide/get-started/snapshot-of-existing-tenant/
Deploying Configurations: https://microsoft365dsc.com/user-guide/get-started/deploying-configurations/

Especially when you are new to PowerShell Desired State Configuration, I highly recommend watching this excellent training series:
https://docs.microsoft.com/en-us/shows/getting-started-with-powershell-dsc/

**Comment by ykuijs** [comment]
Closing this issue for now. Please reopen if you have any more questions about M365DSC documentation or open another issue if you need help with a specific issue.
