### ISSUE TITLE
TeamsUpdateManagementPolicy: Reports on irrelevant property "UpdateTimeOfDay"

### ISSUE THREAD

**Issue by magnusatteamsrocks** [microsoft/Microsoft365DSC#2062]
ISSUE DESCRIPTION (this template):
    Please provide information regarding your issue under each header below.
    Write N/A under any headers that do not apply to your issue, or if the
    information is not available.

    NOTE! Sensitive information should be obfuscated.

    PLEASE KEEP THE HEADERS.

    You may remove this comment block, and the other comment blocks,
    but please keep the headers.
-->
#### Details of the scenario you tried and the problem that is occurring

After adding the TeamsUpdateManagementPolicy the delta report will show, for every update policy, that a resource has been configured differently because the UpdateTimeOfDay property has changed. It seems this property changes every day by default, which makes it look like there is a configuration change every day, which is not the case.

#### Suggested solution to the issue

Remove the UpdateTimeOfDay property from the resource.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.22.629.1

**Comment by NikCharlebois** [comment]
As a fix, we will move from having the property be extracted as:

2022-07-13T18:00:00Z

To simply being extracted as hour:

18:00:00

This will fix the discrepancy issue.
