### ISSUE TITLE
Exported the M365DSC configuration

### ISSUE THREAD

**Issue by laxmip01** [microsoft/Microsoft365DSC#2064]
I managed to export the M365 configuration for a specific configuration. For, example I managed to export the configuration for a SPO tenant settings or Exchange transport rules. I have both M365TenantConfig.ps1 and ConfigurationData.psd1 generated. To modify and reimport back to the tenant, could you please guide.

**Comment by malauter** [comment]
This is described here: https://microsoft365dsc.com/user-guide/get-started/deploying-configurations/
Please check the Get started guide.
