### ISSUE TITLE
Get-M365DSCCompiledPermissionList cannot find parameter name "Source"

### ISSUE THREAD

**Issue by MarcoEberle** [microsoft/Microsoft365DSC#2083]
I want to get the required permissions for Exchange and tried 

`Get-M365DSCCompiledPermissionList -ResourceNameList @('EXOAcceptedDomain') -Source 'Exchange'`

The response is an error saying

Get-M365DSCCompiledPermissionList : A parameter cannot be found that matches parameter name 'Source'.

In the User Guide the above piece of Code works.
https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/#exchange-permissions

Without parameter Source all Permissions are empty.
Are the Components still up to date because not a single Exchange component from https://export.microsoft365dsc.com/ is printing permissions.

![image](https://user-images.githubusercontent.com/38832691/177962459-47e6d332-9bf6-436a-954b-6ca82f2090b0.png)

**Comment by MarcoEberle** [comment]
3 days old and still no answer?

Why are documentation and code different? 
Why is parameter "Source" and "PermissionsType" not in cmdlet anymore? -> https://microsoft365dsc.com/user-guide/cmdlets/Get-M365DSCCompiledPermissionList/

Why are all resources from Exchange returning no value when using Get-M365DSCCompiledPermissionList?

**Comment by malauter** [comment]
I am unable to reproduce this issue with the current version of M365 DSC:
![image](https://user-images.githubusercontent.com/37979749/178297692-a6564451-fd3a-4b08-8121-d40bf471f9dd.png)

Can you please provide more information about your environment and your M365 DSC version?
Please make sure that M365 DSC and all dependencies are up to date and no older versions are installed by running these cmdlets before trying to get the permissions list again:
```
Update-Module Microsoft365DSC -Force
Update-M365DSCDependencies
Uninstall-M365DSCOutdatedDependencies
```

**Comment by MarcoEberle** [comment]
I am running Windows on a Windows Server. 
I ran Update-Module Microsoft365DSC -Force and restarted the server. 
Now it works. Thanks!
