### ISSUE TITLE
MS TEAMS: Unable to Export MS Teams Resource Configuration. Processing data from remote server api.interfaces.records.teams.microsoft.com failed with the following error message: Teams PowerShell Module versions older than 4.x.x are retired

### ISSUE THREAD

**Issue by aflopex** [microsoft/Microsoft365DSC#2094]
#### Details of the scenario you tried and the problem that is occurring
Unable to Export MS Teams Resource Configuration. Processing data from remote server api.interfaces.records.teams.microsoft.com failed with the following error message: Teams PowerShell Module versions older than 4.x.x are retired

![image](https://user-images.githubusercontent.com/50927492/178793620-b5f097b3-a731-43c9-adbd-479554edc3f3.png)

#### Suggested solution to the issue
I updated to the latest M365DSC module today, ver 1.22.713.1 and allowed the MS Teams dependency to be updated as shown below

![image](https://user-images.githubusercontent.com/50927492/178793836-c98a883c-a33f-4493-ba28-1404a9872f61.png)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by NikCharlebois** [comment]
Can you post a screenshot of what you get if you run the following command?
```
Get-Module MicrosoftTeams -ListAvailable
```

**Comment by aflopex** [comment]
![image](https://user-images.githubusercontent.com/50927492/178807981-36aea650-5ec6-4adf-9dae-625bee8f8a98.png)
