### ISSUE TITLE
New-M365DSCReportFromConfiguration does not generate Teams Voice Report Output

### ISSUE THREAD

**Issue by dinocaputo** [microsoft/Microsoft365DSC#2096]
Report missing all but Teams PSTN Usages.  Configuration Items validated to be present in file but never get put into either HTML or EXCEL reports.  Can report multiple times.

**Comment by NikCharlebois** [comment]
Nik.Charlebois at Microsoft.com

**Comment by dinocaputo** [comment]
Sent the config and report.

**Comment by NikCharlebois** [comment]
I somehow never got the files.

**Comment by dinocaputo** [comment]
resent as txt file.  let me know if you got it.

**Comment by NikCharlebois** [comment]
Got it. Investigating as we speak

**Comment by NikCharlebois** [comment]
Look like this is a bug in the way we handle single quotes inside of the VoiceNormalizationRules
![image](https://user-images.githubusercontent.com/2547149/179272220-f2885527-753d-4960-a560-19d80c56277b.png)
The config is invalid and therefore don't get included in the report. Will look at a fix.
