### ISSUE TITLE
Error running  New-M365DSCReportFromConfiguration 

### ISSUE THREAD

**Issue by krugerd** [microsoft/Microsoft365DSC#2097]
#### Details of the scenario you tried and the problem that is occurring
Having an issue with New-M365DSCReportFromConfiguration in 1.22.713.1 (not seeing the issue in 1.22.706.1) - I have an  exported .ps1 file that was created with an export on a Win 2016 server that did not have Office/Excel installed.  I have copied the .ps1 file to my workstation that does have Office and Excel.  I can type the .ps1 fine, and when I run the New-M365DSCReportFromConfiguration I get the following error:

PS C:\ps\dsc> New-M365DSCReportFromConfiguration -type Excel -ConfigurationPath "C:\ps\dsc\export.ps1" -OutputPath "C:\ps\dsc\export.xlsx" -Verbose
VERBOSE: The object written to the pipeline is an instance of the type
"Microsoft.Office.Interop.Excel.ApplicationClass" from the component's primary interoperability assembly. If this type
exposes different members than the IDispatch members, scripts that are written to work with this object might not work
if the primary interoperability assembly is not installed.

Excel does open, but none of the export gets put in the report.  I have tried it with -type HTML but it also just generates an empty HTML.

#### Verbose logs showing the problem
S C:\ps\dsc> New-M365DSCReportFromConfiguration -type Excel -ConfigurationPath "C:\ps\dsc\export.ps1" -OutputPath "C:\ps\dsc\export.xlsx" -Verbose
VERBOSE: The object written to the pipeline is an instance of the type
"Microsoft.Office.Interop.Excel.ApplicationClass" from the component's primary interoperability assembly. If this type
exposes different members than the IDispatch members, scripts that are written to work with this object might not work
if the primary interoperability assembly is not installed.
Exception calling "IndexOf" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size
of the collection.
Parameter name: startIndex"
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.713.1\modules\M365DSCReport.psm1:278 char:5
+     $endPosition = $fileContent.IndexOf("`r", $startPosition)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException

Exception calling "Remove" with "2" argument(s): "StartIndex cannot be less than zero.
Parameter name: startIndex"
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.713.1\modules\M365DSCReport.psm1:279 char:5
+     $fileContent = $fileContent.Remove($startPosition, $endPosition - ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException

#### Suggested solution to the issue
I get the excel to populate by changing line 278 of M365DSCReport.psm to:
   $endPosition = $fileContent.IndexOf('r', $startPosition)
However, I still get the "object written to the pipeline" error AND note the excel file does not automatically save and close like it did previously again in the same directory...

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Export was created on Win2016Server, PowerShell 5.1 with Microsoft365DSC 1.22.713.1
I'm running the New-M365DSCReportFromConfiguration on Win10, PowerShell 5.1, Microsoft365DSC 1.22.713.1

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB, fr-CA, fr-FR}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.713.1  --- note I could create a new report with 1.22.706.1

**Comment by krugerd** [comment]
a coworker is also getting the same error message on their machine.  As well, I get the same error on another export that was created on my laptop (Win 10 with Excel) so I dont think where the export was created is a concern

**Comment by NikCharlebois** [comment]
Any chances you could share your configuration here for us to try? Thanks

**Comment by NikCharlebois** [comment]
The code referenced above removed the version dependencies from the text blob to parse. Changing it would result in the parser not being able to parse a configuration that doesn't have the associated configuration associated with it. Since we cannot replicate, will be closing for the moment. Feel free to send me the blue print by email at Nik.Charlebois AT Microsoft.com for us to investigate further and maybe re-open.
