### ISSUE TITLE
IntuneASRRulesPolicyWindows10: MgDeviceManagementIntent cmdlet fault 

### ISSUE THREAD

**Issue by William-Francillette** [microsoft/Microsoft365DSC#2098]
#### Details of the scenario you tried and the problem that is occurring
The resource is not working anymore due to MgDeviceManagementIntent cmdlets not working

Get-MgDeviceManagementIntent returns:
```
Get-MgDeviceManagementIntent : One or more errors occurred.
At line:1 char:1
+ Get-MgDeviceManagementIntent
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgDeviceManagementIntent_List], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Graph.PowerShell.Cmdlets.GetMgDeviceManagementIntent_List
```
#### Suggested solution to the issue
I could replace Get-MgDeviceManagementIntent and the different calls to MgDeviceManagementIntent cmdlets with a call to the corresponding REST query 

I have tested it and works fine 

MgDeviceManagementIntent is part of the Beta API

I would also like  to rename this resource as IntuneAttackSurfaceReductionRulesPolicyWindows10

Thanks,
William
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by NikCharlebois** [comment]
Somehow the cmdlet stills works for me under the beta profile with 1.10.0. Can you please confirm that the issue still happens on your end? Thanks

**Comment by William-Francillette** [comment]
Hi Nik,

Sorry my bad, it's working now - not sure why it wasn't the other day

Thanks 
Will
