### ISSUE TITLE
Problem with Start-DscConfiguration

### ISSUE THREAD

**Issue by gitti19288** [microsoft/Microsoft365DSC#2109]
I have made an export from a tenant. With the export data I created the MOF file. 

I wanted to mirror the configuration to another tenant. I encountered the following errors at the following:

Start-DscConfiguration -Path C:\dsc\M365TenantConfig  -Verbose -Wait

_"The WinRM client sent a request to the remote WS-Management service and was notified that the request size exceeded the maximum size configured in the "MaxEnvelopeSize" quota"
has exceeded the maximum size configured in the "MaxEnvelopeSize" quota."_

Does anyone else happen to have this problem as well?

I am grateful for any help.

**Comment by NikCharlebois** [comment]
This is a limitation of WinRM because your configuration is larger than the default allowed. To increase the MaxEnvelopeSize, run the following command:

Set-Item -Path WSMan:\localhost\MaxEnvelopeSizekb -Value 6000
