### ISSUE TITLE
New-M365DSCReportFromConfiguration - Empty report

### ISSUE THREAD

**Issue by bmauras** [microsoft/Microsoft365DSC#2119]
ISSUE DESCRIPTION:
     I recently made an export of our Exchange Online configuration and when I try to generate either an Excel or HTML report, this one 
     is emptly or partially filled.
     I checked the configuration file and I can see a lot of information in it. When I run the command "New-M 
     365DSCReportFromConfiguration" I have no error but the progress bar only showed up  when I set the verbose parameter.

#### The operating system the target node is running
     OsName               : Microsoft Windows 11 Pro
     OsOperatingSystemSKU : 48
     OsArchitecture       : 64-bit
     WindowsVersion       : 2009
     WindowsBuildLabEx    : 22000.1.amd64fre.co_release.210604-1628
     OsLanguage           : fr-FR
     OsMuiLanguages       : {fr-FR, en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)

ModuleType  Version      Name                              
----------        -------       ----
Manifest        1.22.713.1  Microsoft365DSC

Thank you in advance for your help.

**Comment by NikCharlebois** [comment]
Can you share the .ps1 file you are trying to generate the report for? Also, can you please make sure you run the Uninstall-M365DSCOutdatedDependencies cmdlet first in order to make sure you don't have conflicting dependencies on the machine? Thanks

**Comment by bmauras** [comment]
Hello,

I finally found out where the problem was. In fact, I had two versions of the module installed on my computer.
Anyway, thank you for your help.

Regards,
Bruno
________________________________
