### ISSUE TITLE
M365TenantConfig.ps1 not create mof file

### ISSUE THREAD

**Issue by gitti19288** [microsoft/Microsoft365DSC#2121]
Hi, I have been able to save the tenant configuration successfully. However, when I run the script (M365TenantConfig.ps1) I get no error message and unfortunately no MOF file.

The export is to the folder C:\DSC.
There are the files ConfigurationData.psd1 and M365TenantConfig.ps1.

I changed in PowerShell to the directory c:\dsc and tried the following:

**.\M365TenantConfig.ps1

$TargetCredentials = Get-Credential
.\M365TenantConfig.ps1 -Credential $TargetCredentials -Outpath C:\DSC**

How can I generate a MOF file?

**Comment by gitti19288** [comment]
Sure. No problem.
[M365TenantConfig.zip](https://github.com/microsoft/Microsoft365DSC/files/9158261/M365TenantConfig.zip)

**Comment by malauter** [comment]
I cannot reproduce the issue with your file. If I run .\M365TenantConfig.ps1 (in PS 5.1), the MOF file is created without any issues. Is there any error message?

Please try it again after updating dependencies and removing all outdated dependencies.
`Update-M365DSCDependencies
Uninstall-M365DSCOutdatedDependencies`

**Comment by NikCharlebois** [comment]
@gitti19288 any updates?

**Comment by NikCharlebois** [comment]
You can always send it over by email to Nik.Charlebois "AT" Microsoft.com

**Comment by gitti19288** [comment]
I send you an mail from my coporate mail account. Thanks for support guys.

**Comment by NikCharlebois** [comment]
For what its worth, this is normally due to conflicting resources in the file having the same key properties. AADApplication is normally the main culprit. I will await your email.

**Comment by gitti19288** [comment]
Hi Nik, do you have any news for me?

**Comment by gitti19288** [comment]
I have sent you the files again via another private mail address
