### ISSUE TITLE
The password supplied to the Desired State Configuration resource 'ResourceName' is not valid. The password cannot be null or empty.

### ISSUE THREAD

**Issue by NikolaMadzic** [microsoft/Microsoft365DSC#2122]
ISSUE TITLE:
    The password supplied to the Desired State Configuration resource 'ResourceName' is not valid. The password cannot be null or empty.

    ISSUE DESCRIPTION:
    I want to copy a configuration from tenant A to tenant B by executing the cmdlets below.
    Important note in advance: The issue occurs also with other Components. In this example I used the component 
    AADGroupsNamingPolicy.
    The credentials of the target user are correct. MFA is disabled for that user.

    # Getting client credential
    $SourceCredential = Get-Credential
    $TargetCredential = Get-Credential

    # Exporting resources using credentials
    Export-M365DSCConfiguration -Components @("AADGroupsNamingPolicy") `
                            -Credential $SourceCredential `
                            -Path "C:\Temp\Microsoft365DSC" `
                            -FileName "M365TenantConfig.ps1" `
                            -ConfigurationName "M365TenantConfig"

    # Compile the Mof File
    .\M365TenantConfig.ps1 -Credential $TargetCredential

    # Configure the tenant
    Start-DSCConfiguration -pa "C:\Temp\Microsoft365DSC\M365TenantConfig" -Wait -Verbose -Force

    #### VERBOSE LOGS SHOWING THE PROBLEM:
    AUSFÜHRLICH: Vorgang "CIM-Methode aufrufen" mit den folgenden Parametern durchführen, "'methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/
DesiredStateConfiguration".
AUSFÜHRLICH: An LCM method call arrived from computer 'ComputerName' with user sid S-1-5-21-1482476501-2139871995-682003330-627483.
AUSFÜHRLICH: [WINAP5VBMIAKSRX]: LCM:  [ Start  Set      ]
AUSFÜHRLICH: [WINAP5VBMIAKSRX]: LCM:  [ Start  Resource ]  [[AADGroupsNamingPolicy]e698c887-7d51-4943-b424-ff2bca10ae04]
AUSFÜHRLICH: [WINAP5VBMIAKSRX]: LCM:  [ Start  Test     ]  [[AADGroupsNamingPolicy]e698c887-7d51-4943-b424-ff2bca10ae04]
AUSFÜHRLICH: [WINAP5VBMIAKSRX]: LCM:  [ End    Test     ]  [[AADGroupsNamingPolicy]e698c887-7d51-4943-b424-ff2bca10ae04]  in 0.0410 seconds.
**The password supplied to the Desired State Configuration resource MSFT_AADGroupsNamingPolicy is not valid. The password cannot be null or empty.
    + CategoryInfo          : InvalidResult: (:) [], CimException
    + FullyQualifiedErrorId : InvalidPassword
    + PSComputerName        : localhost**
 
AUSFÜHRLICH: [WINAP5VBMIAKSRX]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : ObjectNotFound: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 6
    + PSComputerName        : localhost
 
AUSFÜHRLICH: Vorgang "CIM-Methode aufrufen" wurde abgeschlossen.
AUSFÜHRLICH: Die Ausführung des Konfigurationsauftrags hat 0.32 Sekunden gedauert.

OPERATING SYSTEM:

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}

**Comment by malauter** [comment]
This is because of a known issue in the Windows June 2022 CU. See this comment for more information: https://github.com/microsoft/Microsoft365DSC/issues/2024#issuecomment-1175903631

The July 2022 CU should contain a fix for this issue.

**Comment by NikCharlebois** [comment]
As Mario points out above, July CU will fix this. Closing the issue.
