### ISSUE TITLE
Conditional Access Policy - The server could not process the request because it is malformed or incorrect.

### ISSUE THREAD

**Issue by NikolaMadzic** [microsoft/Microsoft365DSC#2146]
ISSUE TITLE:
    The server could not process the request because it is malformed or incorrect.

    ISSUE DESCRIPTION (this template):
    When trying to migrate Conditional Access Policies from Tenant A to Tenant B, some policies (about half) could not be migrated due to the error message below:
    ****The server could not process the request because it is malformed or incorrect.
    + CategoryInfo          : InvalidOperation: ({ body = Micros...AccessPolicy1 }:) [], CimException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Graph.PowerShell.Cmdlets.NewMgIdentityConditionalAccessPolicy_CreateExpanded
    + PSComputerName        : localhost****

There is only one warning entry in the Event Viewer.

The affected conditional access policy that has an error does not have any members/objects in the parameters such as InludeGroups, ExcludeGroups, IncludeApplications, ExcludeApplications, etc. that do not exist in Tenant B.
I checked this manually in advance to avoid problems.

I could not find any meaningful difference between policies that could be imported successfully and non-migrated policies that ran into error.

Thank you very much in advance for your help!

**Comment by andikrueger** [comment]
What module version of M365DSC are you using and could you share some parts of your configuration without sensible data?

**Comment by NikolaMadzic** [comment]
Microsoft365DSC module version: 1.22.720.1


This is an extract from the .ps1 file created when exporting from Tenant A. The CA02 was successfully imported into Tenant B. CA03 could not be imported into Tenant B:

# Generated with Microsoft365DSC version 1.22.713.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
Configuration M365DSC_AzureAD
{
    $OrganizationName = $ConfigurationData.NonNodeData.OrganizationName
    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.22.713.1'

    Node localhost
    {
        AADConditionalAccessPolicy 86c59ee6-f7d8-4ded-90b4-ad75f46ab158
        {
            ApplicationEnforcedRestrictionsIsEnabled = $False;
            ApplicationId                            = $ConfigurationData.NonNodeData.ApplicationId;
            BuiltInControls                          = @("block");
            CertificateThumbprint                    = $ConfigurationData.NonNodeData.CertificateThumbprint;
            ClientAppTypes                           = @("exchangeActiveSync","other");
            CloudAppSecurityIsEnabled                = $False;
            CloudAppSecurityType                     = "";
            DeviceFilterRule                         = "";
            DisplayName                              = "CA02_All Cloud Apps_Block Legacy Authentication for all users";
            Ensure                                   = "Present";
            ExcludeApplications                      = @();
            ExcludeDevices                           = @();
            ExcludeGroups                            = @("Group1","Group2");
            ExcludeLocations                         = @();
            ExcludePlatforms                         = @();
            ExcludeRoles                             = @();
            ExcludeUsers                             = @();
            GrantControlOperator                     = "OR";
            Id                                       = "9fd18a83-6ecf-4104-b65e-03e7cbb4ed97";
            IncludeApplications                      = @("All");
            IncludeDevices                           = @();
            IncludeGroups                            = @();
            IncludeLocations                         = @();
            IncludePlatforms                         = @();
            IncludeRoles                             = @();
            IncludeUserActions                       = @();
            IncludeUsers                             = @("All");
            PersistentBrowserIsEnabled               = $False;
            PersistentBrowserMode                    = "";
            SignInFrequencyIsEnabled                 = $False;
            SignInFrequencyType                      = "";
            SignInRiskLevels                         = @();
            State                                    = "disabled";
            TenantId                                 = $ConfigurationData.NonNodeData.TenantId;
            UserRiskLevels                           = @();
        }
        AADConditionalAccessPolicy 472f74f0-b223-4073-86e8-519b17e834c0
        {
            ApplicationEnforcedRestrictionsIsEnabled = $False;
            ApplicationId                            = $ConfigurationData.NonNodeData.ApplicationId;
            BuiltInControls                          = @();
            CertificateThumbprint                    = $ConfigurationData.NonNodeData.CertificateThumbprint;
            ClientAppTypes                           = @("all");
            CloudAppSecurityIsEnabled                = $False;
            CloudAppSecurityType                     = "";
            DeviceFilterRule                         = "";
            DisplayName                              = "CA03_All Cloud Apps_Block Persistent Session_unmanaged devices";
            Ensure                                   = "Present";
            ExcludeApplications                      = @();
            ExcludeDevices                           = @("Compliant");
            ExcludeGroups                            = @("Group1","Group2");
            ExcludeLocations                         = @();
            ExcludePlatforms                         = @("android","iOS");
            ExcludeRoles                             = @();
            ExcludeUsers                             = @();
            Id                                       = "af6a42ed-ef90-431b-9420-9a0748a9dd0f";
            IncludeApplications                      = @("All");
            IncludeDevices                           = @("All");
            IncludeGroups                            = @();
            IncludeLocations                         = @();
            IncludePlatforms                         = @("all");
            IncludeRoles                             = @();
            IncludeUserActions                       = @();
            IncludeUsers                             = @("All");
            PersistentBrowserIsEnabled               = $True;
            PersistentBrowserMode                    = "never";
            SignInFrequencyIsEnabled                 = $False;
            SignInFrequencyType                      = "";
            SignInRiskLevels                         = @();
            State                                    = "disabled";
            TenantId                                 = $ConfigurationData.NonNodeData.TenantId;
            UserRiskLevels                           = @();
        }


This is the verbose logging from the import regarding the CA03 policy:

AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] No existing Policy with name {CA03_All Cloud Apps_Block Persistent Session_unmanaged devices} were found
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: Cleaning up parameters
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: Policy CA03_All Cloud Apps_Block Persistent Session_unmanaged devices Ensure Present
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: create Conditions object
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: create Application Condition object
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: process includeusers
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: process excludeusers
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: process includegroups
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: process excludegroups
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] adding group to ExcludeGroups
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] adding group to ExcludeGroups
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: process includeroles
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: process excluderoles
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: process platform condition
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: IncludePlatforms: all
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: ExcludePlatforms: android iOS
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: process include and exclude locations
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: process device states
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: process device filter
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: process risk levels and app types
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: UserRiskLevels:
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: SignInRiskLevels:
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: ClientAppTypes: all
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: Adding processed conditions
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: create and provision Grant Control object
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: process session controls
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: create provision Session Control object
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: Persistent Browser settings defined: PersistentBrowserIsEnabled:True, PersistentBrowserMode:Never
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Set-Targetresource: create policy CA03_All Cloud Apps_Block Persistent Session_unmanaged devices
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Create Parameters:
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0] Conditions={Applications={IncludeApplications=(All)}; ClientAppTypes=(all); Devices={ExcludeDevices=(Compliant); IncludeDevices=(A
ll)}; Platforms={ExcludePlatforms=(android,iOS); IncludePlatforms=(all)}; SignInRiskLevels=(); UserRiskLevels=(); Users={ExcludeGroups=(GroupID1,GroupID2); ExcludeRoles=(); ExcludeUsers=(); IncludeGro
ups=(); IncludeRoles=(); IncludeUsers=(All)}}; DisplayName=CA03_All Cloud Apps_Block Persistent Session_unmanaged devices; SessionControls={ApplicationEnforcedRestrictions={IsEnabled=False}; PersistentBrowser={IsEnabled=True; Mode=Never}}; State=disabled
The server could not process the request because it is malformed or incorrect.
    + CategoryInfo          : InvalidOperation: ({ body = Micros...AccessPolicy1 }:) [], CimException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Graph.PowerShell.Cmdlets.NewMgIdentityConditionalAccessPolicy_CreateExpanded
    + PSComputerName        : localhost

**Comment by andikrueger** [comment]
Just from the looks at the resource configuration, there are just a few differences, that should not cause any problems. I'll test it for one of my tenants.

Some further thoughts:

It looks like you have at least two version of M365DSC on your system and the export was generated with V1.22.713.1. This is the actual version that is going to be used to import the settings. Could change the `Import-DscResource` within your configuration and update the version string to 1.22.720.1. Please compile the configuration afterwards and try again. The version change should not make any difference. Between these two versions, there was not update for this resource.

additionally you could additionally try to remove the older versions of M365 and its dependencies: Uninstall-M365DSCOutdatedDependencies

**Comment by andikrueger** [comment]
Did you change the configuration for the second resource anyhow or is this 1:1 the exported one. Could you share some screenshots for the settings within the azure portal?

I can confirm, that this configuration only creates the first policy. The second one fails.

```powershell
The PowerShell DSC resource '[AADConditionalAccessPolicy]472f74f0-b223-4073-86e8-519b17e834c0' with SourceInfo 'C:\temp\m365dscissue2146\aadcondaccessconfig.ps1::74::5::AADConditionalAccessPolicy' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
```

```
Job {7234CE0B-0E6C-11ED-80F2-0433C2A60A08} : 
MIResult: 1
Error Message: The server could not process the request because it is malformed or incorrect.
Message ID: BadRequest,Microsoft.Graph.PowerShell.Cmdlets.NewMgIdentityConditionalAccessPolicy_CreateExpanded
Error Category: 7
Error Code: 7
Error Type: MI
```

**Comment by NikolaMadzic** [comment]
I don't know if I should be happy that you also get the same error message :)

Yes, I had to adjust the configuration parameters on some CAP's.
For example, because Tenant B does not have all the users, groups, or applications that were listed under Included/Excluded in Tenant A.
In this example, for the second resource, I have changed the following configuration parameters:
ExcludeGroups, State*
*State: For all CAPs I migrate from Tenant A to Tenant B, I set the status to "Disabled" to avoid a potential lockout in Tenant B.

ORIGINAL:

AADConditionalAccessPolicy 472f74f0-b223-4073-86e8-519b17e834c0
        {
            ApplicationEnforcedRestrictionsIsEnabled = $False;
            ApplicationId                            = $ConfigurationData.NonNodeData.ApplicationId;
            BuiltInControls                          = @();
            CertificateThumbprint                    = $ConfigurationData.NonNodeData.CertificateThumbprint;
            ClientAppTypes                           = @("all");
            CloudAppSecurityIsEnabled                = $False;
            CloudAppSecurityType                     = "";
            DeviceFilterRule                         = "";
            DisplayName                              = "CA03_All Cloud Apps_Block Persistent Session_unmanaged devices";
            Ensure                                   = "Present";
            ExcludeApplications                      = @();
            ExcludeDevices                           = @("Compliant");
            ExcludeGroups                            = @("Group1","Group2","Group3","Group4");
            ExcludeLocations                         = @();
            ExcludePlatforms                         = @("android","iOS");
            ExcludeRoles                             = @();
            ExcludeUsers                             = @();
            Id                                       = "af6a42ed-ef90-431b-9420-9a0748a9dd0f";
            IncludeApplications                      = @("All");
            IncludeDevices                           = @("All");
            IncludeGroups                            = @();
            IncludeLocations                         = @();
            IncludePlatforms                         = @("all");
            IncludeRoles                             = @();
            IncludeUserActions                       = @();
            IncludeUsers                             = @("All");
            PersistentBrowserIsEnabled               = $True;
            PersistentBrowserMode                    = "never";
            SignInFrequencyIsEnabled                 = $False;
            SignInFrequencyType                      = "";
            SignInRiskLevels                         = @();
            State                                    = "enabled";
            TenantId                                 = $ConfigurationData.NonNodeData.TenantId;
            UserRiskLevels                           = @();
        }



MODIFIED:

AADConditionalAccessPolicy 472f74f0-b223-4073-86e8-519b17e834c0
        {
            ApplicationEnforcedRestrictionsIsEnabled = $False;
            ApplicationId                            = $ConfigurationData.NonNodeData.ApplicationId;
            BuiltInControls                          = @();
            CertificateThumbprint                    = $ConfigurationData.NonNodeData.CertificateThumbprint;
            ClientAppTypes                           = @("all");
            CloudAppSecurityIsEnabled                = $False;
            CloudAppSecurityType                     = "";
            DeviceFilterRule                         = "";
            DisplayName                              = "CA03_All Cloud Apps_Block Persistent Session_unmanaged devices";
            Ensure                                   = "Present";
            ExcludeApplications                      = @();
            ExcludeDevices                           = @("Compliant");
            ExcludeGroups                            = @("Group1","Group2");
            ExcludeLocations                         = @();
            ExcludePlatforms                         = @("android","iOS");
            ExcludeRoles                             = @();
            ExcludeUsers                             = @();
            Id                                       = "af6a42ed-ef90-431b-9420-9a0748a9dd0f";
            IncludeApplications                      = @("All");
            IncludeDevices                           = @("All");
            IncludeGroups                            = @();
            IncludeLocations                         = @();
            IncludePlatforms                         = @("all");
            IncludeRoles                             = @();
            IncludeUserActions                       = @();
            IncludeUsers                             = @("All");
            PersistentBrowserIsEnabled               = $True;
            PersistentBrowserMode                    = "never";
            SignInFrequencyIsEnabled                 = $False;
            SignInFrequencyType                      = "";
            SignInRiskLevels                         = @();
            State                                    = "disabled";
            TenantId                                 = $ConfigurationData.NonNodeData.TenantId;
            UserRiskLevels                           = @();
        }

You see, I have modified here the configuration parameters "ExcludeGroups" where I removed two groups and "State" that I changed from enabled to disabled.

Note, that "Group1" is a synonym for the original group name. I didn't want to paste here the original group names.

From which settings you would like to have the screenshots?

**Comment by andikrueger** [comment]
Sometimes it's best, that we can reproduce the issue. Otherwise it is even more challenging, to get a handle on that issue.

Screenshots of the original settings of this policy within the tenant. I'd like to create this policy from scratch within my tenant. Removing the original groups names, tenant names, and so on is fine. I'm only interested in the settings so that I can do an export/import on my own.

**Comment by NikolaMadzic** [comment]
Now I see that this CAP is using a deprecated feature in Tenant A.
I have removed the configuration parameters for the deprecated feature but I ran into the same error.

![3](https://user-images.githubusercontent.com/73350448/181514423-06b3e252-f417-4db6-b741-bc9478b85a77.JPG)
![4](https://user-images.githubusercontent.com/73350448/181514429-379a54ad-f6d8-48d1-90fb-815231b0b726.JPG)
![5](https://user-images.githubusercontent.com/73350448/181514432-682a054e-2221-4609-b5b1-f213e62d045c.JPG)
![6](https://user-images.githubusercontent.com/73350448/181514436-b673cc25-3ca1-4fee-b6ef-6c5be341b7ec.JPG)
![7](https://user-images.githubusercontent.com/73350448/181514437-75579a05-6410-4750-9ab7-fee08dc4d824.JPG)
![8](https://user-images.githubusercontent.com/73350448/181514438-9375bb65-477b-41ca-8220-fb9b84cb67a9.JPG)
![1](https://user-images.githubusercontent.com/73350448/181514440-3db306d2-b501-4eee-8cf7-3535c8e8c096.JPG)
![2](https://user-images.githubusercontent.com/73350448/181514444-82cfa9a8-ed4d-462f-882d-2ae1e6b379a5.JPG)

**Comment by andikrueger** [comment]
I rebuild the policy and was able to create an export. The export worked just fine. Import as well.

![image](https://user-images.githubusercontent.com/15608729/181524251-a0f042b2-375a-4bb9-95e0-8a400d0e98cc.png)

This is a comparison of your export (left) and mine (right). The differences are not that big - And removing DeviceFilterMode does not change the outcome.

```powershell
AADConditionalAccessPolicy c5201eb0-b998-4900-88ae-f5b1dbb45467 {
            ApplicationEnforcedRestrictionsIsEnabled = $False;
            BuiltInControls                          = @();
            ClientAppTypes                           = @("all");
            CloudAppSecurityIsEnabled                = $False;
            CloudAppSecurityType                     = "";
            Credential                               = $Credscredential;
            DeviceFilterMode                         = "exclude";
            DeviceFilterRule                         = "device.isCompliant -eq True";
            DisplayName                              = "CA03_All Cloud Apps_Block Persistent Session_unmanaged devices";
            Ensure                                   = "Present";
            ExcludeApplications                      = @();
            ExcludeDevices                           = @();
            ExcludeGroups                            = @();
            ExcludeLocations                         = @();
            ExcludePlatforms                         = @("android", "iOS");
            ExcludeRoles                             = @();
            ExcludeUsers                             = @("admin@$OrganizationName");
            Id                                       = "de47076a-02c5-4c94-9042-dfa7570d2a2c";
            IncludeApplications                      = @("All");
            IncludeDevices                           = @();
            IncludeGroups                            = @();
            IncludeLocations                         = @();
            IncludePlatforms                         = @("all");
            IncludeRoles                             = @();
            IncludeUserActions                       = @();
            IncludeUsers                             = @("All");
            PersistentBrowserIsEnabled               = $True;
            PersistentBrowserMode                    = "never";
            SignInFrequencyIsEnabled                 = $False;
            SignInFrequencyType                      = "";
            SignInRiskLevels                         = @();
            State                                    = "disabled";
            UserRiskLevels                           = @();
        }
```

You issue is caused by this paramter:

ExcludeDevices                           = @("Compliant");

As soon as I add the value "compliant", the configuration can't be applied.

**Comment by andikrueger** [comment]
Just a little addition: MSGraph holds the information and is able to export the policy.

@NikCharlebois Do you have more insights about the https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/new-mgidentityconditionalaccesspolicy?view=graph-powershell-1.0 cmdLet and the allowed set of parameters?

**Comment by NikCharlebois** [comment]
Behind the scene, the logic gets de-composed as the following:

```
$Params = @{
    Conditions=@{
        Applications=@{
            IncludeApplications=@('All')
        }; 
        ClientAppTypes=@('all'); 
        Devices=@{
            ExcludeDevices=@('Compliant'); 
            IncludeDevices=@('All')
        }; 
        Platforms=@{
            ExcludePlatforms=@('android','iOS'); 
            IncludePlatforms=@('all')
        }; 
        SignInRiskLevels=@(); 
        UserRiskLevels=@();
        Users=@{
            ExcludeGroups=@(); 
            ExcludeRoles=@(); 
            ExcludeUsers=@(); 
            IncludeGroups=@(); 
            IncludeRoles=@(); 
            IncludeUsers=@('All')
        }
    }; 
    DisplayName='CA03_All Cloud Apps_Block Persistent Session_unmanaged devices'; 
    SessionControls=@{
        ApplicationEnforcedRestrictions=@{
            IsEnabled=$false
        }; 
        PersistentBrowser=@{
            IsEnabled=$True; 
            Mode='Never'
        }
    }; 
    State='disabled'
}
New-MgIdentityConditionalAccessPolicy @Params
```

Which throws the following error:
```
New-MgIdentityConditionalAccessPolicy : 1007: Incoming ConditionalAccessPolicy object is null or does not match the schema of ConditionalAccessPolicy type. For 
examples, please see API documentation at https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-1.0.
```
I am investigating what parameter is causing the schema to be invalid and will report back on this thread shortly.

**Comment by NikCharlebois** [comment]
Looks like the 
```
        Devices=@{
            ExcludeDevices=@('Compliant'); 
            IncludeDevices=@('All')
        }; 
```

is what's causing the issue. Instead, the code should be translating this to:

```
Devices=@{
            DeviceFilter = @(
                @{
                    Mode = "exclude"
                    Rule = "device.isCompliant -eq True"
                }
            )
        }; 
```

I will work on a PR to address this ASAP.

**Comment by NikCharlebois** [comment]
@NikolaMadzic how was CA3 generated? Was it manually edited? The Export-M365DSC code should not have generated this. Can you please confirm?

**Comment by NikCharlebois** [comment]
Actually, the code handles these properly. The Device condition has been deprecated. We need to use Device Filter moving forward:
![image](https://user-images.githubusercontent.com/2547149/181632102-31e642f6-faa1-493d-b5e7-9b6ac5561b62.png)

**Comment by NikCharlebois** [comment]
As a fix, replace your CA3 by the following:
```
        AADConditionalAccessPolicy AADProtection
        {
            ApplicationEnforcedRestrictionsIsEnabled = $False;
            ApplicationId                            = $ConfigurationData.NonNodeData.ApplicationId;
            BuiltInControls                          = @();
            CertificateThumbprint                    = $ConfigurationData.NonNodeData.CertificateThumbprint;
            ClientAppTypes                           = @("all");
            CloudAppSecurityIsEnabled                = $False;
            CloudAppSecurityType                     = "";            
            DeviceFilterMode                         = "exclude"; #Added
            DeviceFilterRule                         = "device.isCompliant -eq False";#Added
            DisplayName                              = "CA03_All Cloud Apps_Block Persistent Session_unmanaged devices23sdf34";
            Ensure                                   = "Present";
            ExcludeApplications                      = @();
            ExcludeDevices                           = @(); #Changed
            ExcludeGroups                            = @("Group1","Group2");
            ExcludeLocations                         = @();
            ExcludePlatforms                         = @("android","iOS");
            ExcludeRoles                             = @();
            ExcludeUsers                             = @();
            Id                                       = "af6a42ed-ef90-431b-9420-9a0748a9dd0f";
            IncludeApplications                      = @("All");
            IncludeDevices                           = @(); #Changed
            IncludeGroups                            = @();
            IncludeLocations                         = @();
            IncludePlatforms                         = @("all");
            IncludeRoles                             = @();
            IncludeUserActions                       = @();
            IncludeUsers                             = @("All");
            PersistentBrowserIsEnabled               = $True;
            PersistentBrowserMode                    = "never";
            SignInFrequencyIsEnabled                 = $False;
            SignInFrequencyType                      = "";
            SignInRiskLevels                         = @();
            State                                    = "disabled";
            TenantId                                 = $ConfigurationData.NonNodeData.TenantId;
            UserRiskLevels                           = @();
        }
```

**Comment by NikolaMadzic** [comment]
Thank you very much.
With your solution it worked.
I have a few other CAP's that cannot be created in tenant B due to the same error message, but the cause seems to be different.
Would you like me to share these CAPs with you here?

**Comment by andikrueger** [comment]
Sure. Could you create a new issue for this one?
