### ISSUE TITLE
Export-M365DSCConfiguration: Quiet parameter not found

### ISSUE THREAD

**Issue by philippe-entringer** [microsoft/Microsoft365DSC#2147]
Manifest   1.22.720.1 Microsoft365DSC

The Quiet parameter has been removed.
**Is it possible to Export the Configuration without displaying a Popup credientials ?**

**Command Used**
Export-M365DSCConfiguration -Quiet -TenantId $TenantId -ApplicationId $ClientId -ApplicationSecret $ClienSecret -Workloads @("SPO") -Path "D:\Temp\DSCExtracts\" -ConfigurationName MyConfig -FileName MyExport.ps1

![image](https://user-images.githubusercontent.com/12797998/181475406-1fa35c63-34fb-4f99-bfdd-624c08b8ef58.png)

**Comment by malauter** [comment]
The -Quiet parameter is not needed anymore. If you pass credentials or a service principal to the Export-M365DSCConfiguration command, there should not be any credential prompt as described in the Unattended Capture section of this page: https://microsoft365dsc.com/user-guide/get-started/snapshot-of-existing-tenant/

Do you get a credential prompt if you just remove the -Quiet parameter from you command? Please make sure M365 DSC module and all dependencies are up to date.
