### ISSUE TITLE
New-M365DSCDeltaReport (No discrepancies have been found! - Although differences exist)

### ISSUE THREAD

**Issue by NikolaMadzic** [microsoft/Microsoft365DSC#2156]
ISSUE TITLE:
   New-M365DSCDeltaReport (No discrepancies have been found!)

    ISSUE DESCRIPTION:
    
I want to compare the configuration from two different tenants (Tenant A and Tenant B).

With the cmdlet Export-M365DSCConfiguration I exported the same components from both tenants to a .ps1 file:

Export-M365DSCConfiguration -Components @("EXOAuthenticationPolicy", 
                                        "EXOAuthenticationPolicyAssignment", 
                                        "EXOCASMailboxPlan", 
                                        "EXOHostedContentFilterPolicy", 
                                        "EXOHostedContentFilterRule", 
                                        "EXOHostedOutboundSpamFilterPolicy", 
                                        "EXOIRMConfiguration", 
                                        "EXOMalwareFilterPolicy", 
                                        "EXOMalwareFilterRule", 
                                        "EXOOrganizationConfig", 
                                        "EXOQuarantinePolicy", 
                                        "EXOSafeAttachmentPolicy", 
                                        "EXOSafeAttachmentRule", 
                                        "EXOSafeLinksPolicy", 
                                        "EXOSafeLinksRule", 
                                        "EXOSharingPolicy") `
                            -Path $Path `
                            -FileName $FileName `
                            -ConfigurationName "$ConfigurationName" `
                            -Credential $Credential

I took these two .ps1 configuration files for the cmdlet New-M365DSCDeltaReport in the parameters -Source and -Destination.

In the output file .html I get as result "No discrepancies have been found!".
By comparing them manually, I can see and confirm that both configuration files have several differences which are not detected by the New-M365DSCDeltaReport.

For instance, the screenshot shows that there are differences between both configuration files.

I applied the cmdlet according to the instructions https://microsoft365dsc.com/user-guide/get-started/comparing-configurations/:

New-M365DSCDeltaReport -Source "C:\Temp\Prod_M365DSC_Exchange.ps1" `
                       -Destination "C:\Temp\Dev_M365DSC_Exchange.ps1" `
                       -OutputPath "C:\Temp\DeltaReport.html"

Am I doing anything wrong?

Thanks in advance for your kind support!

![9](https://user-images.githubusercontent.com/73350448/181777664-7389b608-a95d-406a-89d1-c5199dec949d.JPG)

Microsoft365DSC PowerShell module version: 1.22.720.1

**Comment by NikCharlebois** [comment]
@NikolaMadzic can you please make sure you run the following cmdlets to make sure you don't have conflicting dependencies, which is the main reason for these reporting issues:

```
Update-M365DSCDependencies
Uninstall-M365DSCOutdatedDependencies
```

**Comment by NikolaMadzic** [comment]
Thank you.
I ran these two cmdlets one after the other and then created a new Delta Report again with New-M365DSCDeltaReport. Now the differences were displayed.

Problem solved.
