### ISSUE TITLE
Cannot process argument transformation on parameter 'RedirectAddress'.

### ISSUE THREAD

**Issue by NikolaMadzic** [microsoft/Microsoft365DSC#2170]
Your feedback and support is greatly appreciated, thanks for contributing!

    ISSUE TITLE:

When trying to copy the configuration from Tenant A to Tenant B, the resource "EXOSafeAttachmentPolicy" is causing the following error:

    **Error message:**
        Cannot process argument transformation on parameter 'RedirectAddress'. Cannot convert value "" to type "Microsoft.Exchange.Data.SmtpAddress". Error: "The email address '' isn't 
    correct. Please use this format: user name, the @ sign, followed by the domain name. For example, tonysmith@contoso.com or tony.smith@contoso.com."
        + CategoryInfo          : InvalidData: (:) [], CimException
        + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-SafeAttachmentPolicy
        + PSComputerName        : localhost

    **Resource name:** 
    EXOSafeAttachmentPolicy

    ISSUE DESCRIPTION:

    This is the Resource configuration of "EXOSafeAttachmentPolicy" that needs to be copied from Tenant A to Tenant B:

    EXOSafeAttachmentPolicy 2cb1fb6e-f161-467c-81a4-8df187ff12e8
        {
            Action                = "Block";
            ActionOnError         = $True;
            AdminDisplayName      = "";
            ApplicationId         = $ConfigurationData.NonNodeData.ApplicationId;
            CertificateThumbprint = $ConfigurationData.NonNodeData.CertificateThumbprint;
            Enable                = $True;
            Ensure                = "Present";
            Identity              = "Standard Preset Security Policy1631196340058";
            Redirect              = $False;
            RedirectAddress       = "";
            TenantId              = $ConfigurationData.NonNodeData.TenantId;
        }

As far as I understood, when the parameter Redirect is set to $False, no mail addresses need to be added into the parameter RedirectAddress.

Here are more information:
AUSFÜHRLICH: [WINAP5VBMIAKSRX]: LCM:  [ Start  Resource ]  [[EXOSafeAttachmentPolicy]2cb1fb6e-f161-467c-81a4-8df187ff12e8]
AUSFÜHRLICH: [WINAP5VBMIAKSRX]: LCM:  [ Start  Test     ]  [[EXOSafeAttachmentPolicy]2cb1fb6e-f161-467c-81a4-8df187ff12e8]
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[EXOSafeAttachmentPolicy]2cb1fb6e-f161-467c-81a4-8df187ff12e8] Testing configuration of SafeAttachmentPolicy for Stand
ard Preset Security Policy1631196340058
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[EXOSafeAttachmentPolicy]2cb1fb6e-f161-467c-81a4-8df187ff12e8] Getting configuration of SafeAttachmentPolicy for Stand
ard Preset Security Policy1631196340058
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[EXOSafeAttachmentPolicy]2cb1fb6e-f161-467c-81a4-8df187ff12e8] SafeAttachmentPolicy Standard Preset Security Policy163
1196340058 does not exist.
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[EXOSafeAttachmentPolicy]2cb1fb6e-f161-467c-81a4-8df187ff12e8] Current Values: Action=Block; ActionOnError=True; Admin
DisplayName=; ApplicationId=***; CertificateThumbprint=<scrubbed>; Enable=True; Ensure=Absent; Identity=Standard Preset Security Policy1631196340058
; Redirect=False; RedirectAddress=; TenantId=***; Verbose=True
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[EXOSafeAttachmentPolicy]2cb1fb6e-f161-467c-81a4-8df187ff12e8] Target Values: Action=Block; ActionOnError=True; AdminD
isplayName=; ApplicationId=***; CertificateThumbprint=<scrubbed>; Enable=True; Ensure=Present; Identity=Standard Preset Security Policy1631196340058
; Redirect=False; RedirectAddress=; TenantId=***; Verbose=True
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[EXOSafeAttachmentPolicy]2cb1fb6e-f161-467c-81a4-8df187ff12e8] Test-TargetResource returned False
AUSFÜHRLICH: [WINAP5VBMIAKSRX]: LCM:  [ End    Test     ]  [[EXOSafeAttachmentPolicy]2cb1fb6e-f161-467c-81a4-8df187ff12e8]  in 1.1430 seconds.
AUSFÜHRLICH: [WINAP5VBMIAKSRX]: LCM:  [ Start  Set      ]  [[EXOSafeAttachmentPolicy]2cb1fb6e-f161-467c-81a4-8df187ff12e8]
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[EXOSafeAttachmentPolicy]2cb1fb6e-f161-467c-81a4-8df187ff12e8] Setting configuration of SafeAttachmentPolicy for Stand
ard Preset Security Policy1631196340058
AUSFÜHRLICH: [WINAP5VBMIAKSRX]:                            [[EXOSafeAttachmentPolicy]2cb1fb6e-f161-467c-81a4-8df187ff12e8] Creating SafeAttachmentPolicy Standard Preset Security 
Policy1631196340058.
Cannot process argument transformation on parameter 'RedirectAddress'. Cannot convert value "" to type "Microsoft.Exchange.Data.SmtpAddress". Error: "The email address '' isn't 
correct. Please use this format: user name, the @ sign, followed by the domain name. For example, tonysmith@contoso.com or tony.smith@contoso.com."
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-SafeAttachmentPolicy
    + PSComputerName        : localhost

PowerShell module DSC version: 1.22.720.1

**Comment by malauter** [comment]
Fixed in #2171
