### ISSUE TITLE
Resource: SCRetentionCompliancePolicy - A parameter cannot be found that matches parameter name 'TeamsChannelLocationException'.

### ISSUE THREAD

**Issue by NikolaMadzic** [microsoft/Microsoft365DSC#2173]
ISSUE TITLE
Resource: SCRetentionCompliancePolicy - A parameter cannot be found that matches parameter name 'TeamsChannelLocationException'.

ISSUE DESCRIPTION

This is the output when executing the Start-DSCConfiguration cmdlet:

AUSFÜHRLICH: [<computername>]: LCM:  [ Start  Resource ]  [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b]
AUSFÜHRLICH: [<computername>]: LCM:  [ Start  Test     ]  [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b]
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Testing configuration of RetentionCompliancePolicy for 1year_allTeams
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Getting configuration of RetentionCompliancePolicy for 1year_allTeams
WARNUNG: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Your connection has been redirected to the following URI: "https://eur06b.ps.compliance.protection.outlook.com/Powershell-L
iveId?BasicAuthToOAuthConversion=true;PSVersion=5.1.19041.1682
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Found existing RetentionCompliancePolicy 1year_allTeams
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Found RetentionCompliancePolicy 1year_allTeams
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Get-TargetResource Result: 
 Comment=Retention 1 year all Teams data; Credential=***; Enabled=True; Ensure=Present; Name=1year_allTeams; RestrictiveRetention=False; TeamsChannelLocation=(); TeamsChannelLocationException=; TeamsChatLocation=(); TeamsChatLocationException
=
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Current Values: Comment=Retention 1 year all Teams data; Credential=***; Enabled=True; Ensure=Present; Name=1year_a
llTeams; RestrictiveRetention=False; TeamsChannelLocation=(); TeamsChannelLocationException=; TeamsChatLocation=(); TeamsChatLocationException=
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Target Values: Comment=Retention 1 year all Teams data; Credential=***; Enabled=False; Ensure=Present; Name=1year_a
llTeams; RestrictiveRetention=False; TeamsChannelLocation=(); TeamsChannelLocationException=(); TeamsChatLocation=(); TeamsChatLocationException=(); Verbose=True
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Test-TargetResource returned False
AUSFÜHRLICH: [<computername>]: LCM:  [ End    Test     ]  [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b]  in 17.9100 seconds.
AUSFÜHRLICH: [<computername>]: LCM:  [ Start  Set      ]  [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b]
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Setting configuration of RetentionCompliancePolicy for 1year_allTeams
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Getting configuration of RetentionCompliancePolicy for 1year_allTeams
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Found existing RetentionCompliancePolicy 1year_allTeams
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Found RetentionCompliancePolicy 1year_allTeams
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Get-TargetResource Result: 
 Comment=Retention 1 year all Teams data; Credential=***; Enabled=True; Ensure=Present; Name=1year_allTeams; RestrictiveRetention=False; TeamsChannelLocation=(); TeamsChannelLocationException=; TeamsChatLocation=(); TeamsChatLocationException
=
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Policy 1year_allTeams is a Teams Policy
AUSFÜHRLICH: [<computername>]:                            [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b] Updating Policy with values: Comment=Retention 1 year all Teams data; Enabled=False; Identity=1year_allTeams; Restr
ictiveRetention=False; TeamsChannelLocation=(); TeamsChannelLocationException=(); TeamsChatLocation=(); TeamsChatLocationException=()
A parameter cannot be found that matches parameter name 'TeamsChannelLocationException'.
    + CategoryInfo          : InvalidArgument: (:) [], CimException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-RetentionCompliancePolicy
    + PSComputerName        : localhost
 
AUSFÜHRLICH: [<computername>]: LCM:  [ End    Set      ]  [[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b]  in 4.9740 seconds.
The PowerShell DSC resource '[SCRetentionCompliancePolicy]78ba249e-6476-4adf-881b-cb23076df78b' with SourceInfo 
'C:\Users\<username>\Documents\Microsoft365DSC\SecurityCompliance\M365DSC_SecurityCompliance.ps1::33::9::SCRetentionCompliancePolicy' threw one or more non-terminating errors while running the 
Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

This is the part of the configuration file:

SCRetentionCompliancePolicy 78ba249e-6476-4adf-881b-cb23076df78b
        {
            Comment                       = "Retention 1 year all Teams data";
            Credential                    = $Credscredential;
            Enabled                       = $False;
            Ensure                        = "Present";
            Name                          = "1year_allTeams";
            RestrictiveRetention          = $False;
            TeamsChannelLocation          = @();
            TeamsChannelLocationException = @();
            TeamsChatLocation             = @();
            TeamsChatLocationException    = @();
        }

Hope you can help on this as you did in all other issues :)

**Comment by andikrueger** [comment]
The two cmdLets New-RetentionCompliancePolicy and Set-RetentionCompliancePolicy have different parameters. At the moment, the same params are used for both cases. This is the root cause of this error. 

https://github.com/microsoft/Microsoft365DSC/blob/17984cf89f4c13c591e1b935564e060f2be81273/Modules/Microsoft365DSC/DSCResources/MSFT_SCRetentionCompliancePolicy/MSFT_SCRetentionCompliancePolicy.psm1#L585-L595

For the cmdLets see:
https://docs.microsoft.com/de-de/powershell/module/exchange/new-retentioncompliancepolicy?view=exchange-ps
```powershell
New-RetentionCompliancePolicy
   [-Name] <String>
   [-Comment <String>]
   [-Confirm]
   [-Enabled <Boolean>]
   [-Force]
   [-RestrictiveRetention <Boolean>]
   [-RetainCloudAttachment <Boolean>]
   [-TeamsChannelLocation <MultiValuedProperty>]
   [-TeamsChannelLocationException <MultiValuedProperty>]
   [-TeamsChatLocation <MultiValuedProperty>]
   [-TeamsChatLocationException <MultiValuedProperty>]
   [-WhatIf]
   [<CommonParameters>]
```


https://docs.microsoft.com/de-de/powershell/module/exchange/set-retentioncompliancepolicy?view=exchange-ps
```powershell
Set-RetentionCompliancePolicy
   [-Identity] <PolicyIdParameter>
   [-AddTeamsChannelLocation <MultiValuedProperty>]
   [-AddTeamsChannelLocationException <MultiValuedProperty>]
   [-AddTeamsChatLocation <MultiValuedProperty>]
   [-AddTeamsChatLocationException <MultiValuedProperty>]
   [-Comment <String>]
   [-Confirm]
   [-Enabled <Boolean>]
   [-Force]
   [-RemoveTeamsChannelLocation <MultiValuedProperty>]
   [-RemoveTeamsChannelLocationException <MultiValuedProperty>]
   [-RemoveTeamsChatLocation <MultiValuedProperty>]
   [-RemoveTeamsChatLocationException <MultiValuedProperty>]
   [-WhatIf]
   [<CommonParameters>]
```

**Comment by NikolaMadzic** [comment]
Did I understand you correctly that the cause is that the parameter is called [TeamsChannelLocationException] in one cmdlet and in the other [AddTeamsChannelLocationException] ?
If so, where does the real problem need to be solved? In the Microsoft product team or at the M365DSC community?

**Comment by andikrueger** [comment]
This change needs to be implemented within M365DSC.

**Comment by NikCharlebois** [comment]
It somehow appears that you cannot specify individual locations for Teams. Leaving the TeamsChatLocation empty will default to all.
