### ISSUE TITLE
Export-M365DSCConfiguration - No discrepancies have been found

### ISSUE THREAD

**Issue by lpercetti** [microsoft/Microsoft365DSC#2176]
Hello,

I recently realized that latest version of Microsoft365DSC might have an issue.
It is not possible anymore to generate any Delta Report on my system.

After investigation in the source code, I realize that:
- Method Compare-M365DSCConfigurations from file Modules/M365DSCReport.psm1 (434), transforms:
`Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.22.720.1'`
to:
`Import-DscResource -ModuleName 'Microsoft365DSC'`

Then, in the same function, line 486 (source) or 500 (destination), the method ConvertTo-DSCObject is not working anymore when the ModuleVersion is missing.

Versions:
- Microsoft365DSC version 1.22.720.1
- DSCParser version {1.3.0.4}
- ExchangeOnlineManagement version {2.0.5}
- Microsoft.Graph.Applications version {1.9.6}
- Microsoft.Graph.Authentication version {1.9.6}
- Microsoft.Graph.DeviceManagement version {1.9.6}
- Microsoft.Graph.DeviceManagement.Administration version {1.9.6}
- Microsoft.Graph.DeviceManagement.Enrolment version {1.9.6}
- Microsoft.Graph.Devices.CorporateManagement version {1.9.6}
- Microsoft.Graph.Groups version {1.9.6}
- Microsoft.Graph.Identity.DirectoryManagement version {1.9.6}
- Microsoft.Graph.Identity.Governance version {1.9.6}
- Microsoft.Graph.Identity.SignIns version {1.9.6}
- Microsoft.Graph.Planner version {1.9.6}
- Microsoft.Graph.Teams version {1.9.6}
- Microsoft.Graph.Users version {1.9.6}
- Microsoft.PowerApps.Administration.PowerShell version {2.0.147}
- MicrosoftTeams version {4.4.1}
- MSCloudLoginAssistant version {1.0.84}
- PnP.PowerShell version {1.10.0}
- ReverseDSC version {2.0.0.11}

Are you able to reproduce this issue? Is there a way to fix it?
For the time being, I am using the following workaround:

Import-DscResource -ModuleName 'Microsoft365DSC' ` -ModuleVersion '1.22.720.1'
-ModuleVersion '1.22.720.1'

Thanks,

**Comment by andikrueger** [comment]
Please do the following:

```powershell
Update-M365DSCDependencies
Uninstall-M365OutdatedDependencies
```

this issues is resolved with the latest Version 1.22.727.1 an can be resolved with the script above. (this version is not available through PSGallery)

We are also tracking reporting related improvements in #2158 and are working on a PR to make it more reliable.
