### ISSUE TITLE
Issue With the sharepointDSC

### ISSUE THREAD

**Issue by Brijeshoo7** [microsoft/Microsoft365DSC#2178]
Hi, i am attaching the file of codes.

when the same code runs with Teamsteam code https://microsoft365dsc.com/resources/teams/TeamsTeam/ . it works fine in the tenant.
but when it runs with the powershell configuration https://microsoft365dsc.com/resources/sharepoint/SPOTenantSettings/ . it gives me below error message.

![image](https://user-images.githubusercontent.com/88958817/182866049-4e3c191a-52a1-41cd-a2f3-e60202ea7e0f.png)

It would be really helpful if you are able to help me on this

[O365.txt](https://github.com/microsoft/Microsoft365DSC/files/9260335/O365.txt)
[Deploy.txt](https://github.com/microsoft/Microsoft365DSC/files/9260336/Deploy.txt)
.

**Comment by andikrueger** [comment]
Please make sure you did follow this guide on how to setup the PnP Management Shell: https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/#sharepoint-pnp-powershell-permissions

The error message indicates, that either the App registration is missing, the wrong scopes are set or your user account uses 2FA.

**Comment by Brijeshoo7** [comment]
Thanks let me check and confirm all the set-up again. Will update whatever the status is by Monday EOD.
