### ISSUE TITLE
NuGet error running Export-M365DSCConfiguration from Azure Automation PowerShell Runbook

### ISSUE THREAD

**Issue by JeroenStive** [microsoft/Microsoft365DSC#2187]
Hello,

I'm trying to run Export-M365DSCConfiguration from an Azure Automation PowerShell Runbook, but it keeps giving error on missing the NuGet provider (probably wants to check on module updates).

I've installed Microsoft365DSC 1.22.720.1 and all depenencies noted in https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Dependencies/Manifest.psd1

Error is as follow
`System.Management.Automation.MethodInvocationException: Exception calling "ShouldContinue" with "2" argument(s): "A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet provider must be available in 'C:\Program Files\PackageManagement\ProviderAssemblies' or 'C:\Users\Client\AppData\Roaming\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install and import the NuGet provider now?`

My PS script looks like

```
$Tenant = 'tenant.onmicrosoft.com'

$Session = Get-AutomationConnection –Name AzureRunAsConnection

$path = "$env:TEMP"
$Date = $(Get-Date -f yyyy-MMM-dd-HHMMtt)

write-output "Pulling DSC from Tenant $Date"
Export-M365DSCConfiguration -Components @("EXOAcceptedDomain", "EXOActiveSyncDeviceAccessRule", "EXOAddressBookPolicy", "EXOAddressList", "EXOAntiPhishPolicy", "EXOAntiPhishRule", "EXOApplicationAccessPolicy", "EXOAtpPolicyForO365", "EXOAuthenticationPolicy", "EXOAuthenticationPolicyAssignment", "EXOAvailabilityAddressSpace", "EXOAvailabilityConfig", "EXOCASMailboxPlan", "EXOClientAccessRule", "EXODataEncryptionPolicy", "EXODkimSigningConfig", "EXOEmailAddressPolicy", "EXOGlobalAddressList", "EXOHostedConnectionFilterPolicy", "EXOHostedContentFilterPolicy", "EXOHostedContentFilterRule", "EXOHostedOutboundSpamFilterPolicy", "EXOHostedOutboundSpamFilterRule", "EXOInboundConnector", "EXOIntraOrganizationConnector", "EXOIRMConfiguration", "EXOJournalRule", "EXOMailboxPlan", "EXOMailTips", "EXOMalwareFilterPolicy", "EXOMalwareFilterRule", "EXOManagementRole", "EXOMessageClassification", "EXOMobileDeviceMailboxPolicy", "EXOOfflineAddressBook", "EXOOMEConfiguration", "EXOOnPremisesOrganization", "EXOOrganizationConfig", "EXOOrganizationRelationship", "EXOOutboundConnector", "EXOOwaMailboxPolicy", "EXOPartnerApplication", "EXOPerimeterConfiguration", "EXOPolicyTipConfig", "EXOQuarantinePolicy", "EXORemoteDomain", "EXOResourceConfiguration", "EXORoleAssignmentPolicy", "EXOSafeAttachmentPolicy", "EXOSafeAttachmentRule", "EXOSafeLinksPolicy", "EXOSafeLinksRule", "EXOSharingPolicy", "EXOTransportConfig", "EXOTransportRule")
 -path $path -filename "runbook_$date.ps1" -ApplicationId $Session.ApplicationID -TenantId $Tenant -CertificateThumbprint $Session.CertificateThumbprint *>&1 | out-null

```

**Comment by andikrueger** [comment]
Please have a look at this solution. You need to install a few more modules: 

https://github.com/microsoft/Microsoft365DSC/issues/2050#issuecomment-1195414547

**Comment by JeroenStive** [comment]
Thank you!

Already ran that script but the comment about also installing the PackageManagement module looks like did the trick.
