### ISSUE TITLE
Group members for dynamic group/large groups

### ISSUE THREAD

**Issue by anpiskai** [microsoft/Microsoft365DSC#2190]
My customer has several very big dynamic groups that they have created using M365 DSC. Prior to the recent changes in then 7/20 build, everything worked fine, however with the change to add in support for group members, there are new permission errors that show up. It looks as though membership is attempting to be reapplied, however since my groups are dynamic, group membership should not be applied explicitly (rather via rule). Additionally, this change has greatly increased the run-time from a few seconds for the resource to several minutes per group.

I'd recommend some kind of flag for when groups/licenses should be handled by DSC to allow for opting out of processing for those groups.

**Comment by andikrueger** [comment]
Did you remove these parameters from your resource configuration? They are not mandatory and as long as you do not need these properties managed by M365DSC, I would leave them out.

**Comment by anpiskai** [comment]
Yep, those parameters are not present in the resource, but there must be some error in the logic where its absence is treated as a present empty array.
<img width="130" alt="image" src="https://user-images.githubusercontent.com/48796638/185152835-2145b467-41b0-43f9-830d-7fb77b45205e.png">

**Comment by andikrueger** [comment]
Thanks for confirming. This need to be investigated. 

Runtime is increasing due to the get method exporting all members… this is kind of the expected behaviour. Changing the settings without this parameters being present is not.
