### ISSUE TITLE
Introduction of assigned licenses breaks existing group-based licensing

### ISSUE THREAD

**Issue by anpiskai** [microsoft/Microsoft365DSC#2191]
An existing configuration with groups did not have the AssignedLicenses parameter specified and as a result, when it ran the new build of DSC, it unlicensed the groups. This would make sense if the assignedLicenses was specified and configured to be null to avoid configuration drift, however the code shouldn't touch the AssignedLicenses on a group if that attribute is not specified. (Same for the Members attribute).

**Comment by andikrueger** [comment]
DSC will configure the parameter specified. If you do not wish to configure this parameter, please remove it completely within you configuration. 

Pseudo Code that will control optional parameter

```powershell
ResourceName DisplayName {
   KezParameter = "This is the Key"
   OptionalParameter = "Configure Something"
}
```

Pseudo Code that will not change the optional parameter

```powershell
ResourceName DisplayName {
   KezParameter = "This is the Key"
}
```

**Comment by anpiskai** [comment]
Neither is present in the attributes specified on the resource. 
<img width="130" alt="image" src="https://user-images.githubusercontent.com/48796638/185153100-5cb3fdce-e2bb-4954-aeb6-852f7df2d2f4.png">

**Comment by andikrueger** [comment]
Thanks for confirming. This need to be investigated.
