### ISSUE TITLE
IntuneDeviceConfigurationPolicyMacOS returns policies for non-MacOS

### ISSUE THREAD

**Issue by salbeck-sit** [microsoft/Microsoft365DSC#2192]
Export of workload=Intune returns a number of IntuneDeviceConfigurationPolicyMacOS resources but in my case, none of them are related to MacOS.

#### Suggested solution to the issue
The DSC-resource returns data from Get-MgDeviceManagementDeviceConfiguration without filtering on @odata.type

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# config returned from Export:
        IntuneDeviceConfigurationPolicyMacOS 43ffdc90-4721-4103-85dc-768194965e17
        {
            ApplicationId                                  = $ConfigurationData.NonNodeData.ApplicationId;
            Assignments                                    = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.allLicensedUsersAssignmentTarget'
            }
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.allDevicesAssignmentTarget'
            });
            CertificateThumbprint                          = $ConfigurationData.NonNodeData.CertificateThumbprint;
            DisplayName                                    = "XYZ Android Device restrictions";
            Ensure                                         = "Present";
            Id                                             = "c9c0cf1d-c792-455b-baba-3520532bc8ac";
            PasswordBlockFingerprintUnlock                 = $True;
            PasswordExpirationDays                         = 180;
            PasswordMinimumLength                          = 6;
            PasswordMinutesOfInactivityBeforeScreenTimeout = 1;
            PasswordPreviousPasswordBlockCount             = 10;
            PasswordRequiredType                           = "atLeastNumeric";
            TenantId                                       = $ConfigurationData.NonNodeData.TenantId;
        }

Note that PasswordRequiredType is not valid for MacOS but it is valid for an Android config
Other Intune DeviceConfiguration resources do not include Id but has DisplayName as Key/Mandatory
For this resource, the schema doesn't include any Key-param (only Write's) so applying a mof fails even though it compiles.
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.5246.amd64fre.rs1_release.220701-1744
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
'dev' (1.22.727.1)

**Comment by salbeck-sit** [comment]
Seems the real error is in the Export-TargetResource function. 
Here's the current code
       #region resource generator code
        [array]$getValue = Get-MgDeviceManagementDeviceConfiguration `
            -ErrorAction Stop | Where-Object `
            -FilterScript { `
                $_.AdditionalProperties.'@odata.type' -eq '#microsoft.graph.macOSGeneralDeviceConfiguration'  `
            }

        if (-not $getValue)
        {
            [array]$getValue = Get-MgDeviceManagementDeviceConfiguration `
                -ErrorAction Stop
        }
        #endregion
        
Ie, if there are no configurations specifically for MacOS, every configuration is returned - regardless of type.

**Comment by andikrueger** [comment]
Good find. This needs to be fixed.

**Comment by William-Francillette** [comment]
On it - This was initially setup on the DRG - It has been modified now but resources generated before that will need to be amended
