### ISSUE TITLE
EXOAcceptedDomain: Twice a domain in the list with one ending by _RELOCNF_3f303621

### ISSUE THREAD

**Issue by ViValentin** [microsoft/Microsoft365DSC#2193]
#### Details of the scenario you tried and the problem that is occurring
Hello,
I am just starting using Microsoft365DSC and it seems great.
When I ran an Export-M365DSCConfiguration just created from https://export.microsoft365dsc.com/ it stuck on  EXOAcceptedDomain as it found a duplicate with one ending by _RELOCNF_3f303621
I have tried using Graph Explorer, Azure AD custom domain names, O365 admin, Get-AzureADTenantDetail and Get-MsolDomain to have the list of domains and remove potentially the duplicate but was not able to found it.

How to have the list and remove this duplicate?

#### Verbose logs showing the problem
Connecting to {ExchangeOnline}...✅
Connecting to {MicrosoftGraph}...✅
[1/85] Extracting [EXOAcceptedDomain]...
...
  |---[34/120] news.<One of our Domain>.com✅
....
|---[72/120] news.<One of our Domain>.com_RELOCNF_3f303621
=> Script get stuck and don't progress animore
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
$Credential = Get-Credential

# Exporting resources using credentials
Export-M365DSCConfiguration -Components @("EXOAcceptedDomain")
```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1709
WindowsBuildLabEx    : 16299.15.amd64fre.rs3_release.170928-1534
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
I am using DSC 1.22.720.1 version

**Comment by andikrueger** [comment]
The resource calls the following exchange online cmdLet:

$AllAcceptedDomains = Get-AcceptedDomain -ErrorAction Stop

**Comment by ViValentin** [comment]
Hello Andi,
Thanks for feedback.
With the good commandlet I was able to reproduce the issue outside of MIcrosoft365DSC and then open a ticket to MS support.
It seems it was a sync issue between Azure AD and Exchange online. They do some action on their side that solve my issue.
I reintroduce EXOAcceptedDomain within Microsoft365DSC and was able to do the export without any issue.

Issue can be close and was not on Microsoft365DSC but on O365 side.
Thanks for help. I will continue discovering Microsoft365DSC :-)
