### ISSUE TITLE
Release issue in azure devops on premise setup

### ISSUE THREAD

**Issue by Brijeshoo7** [microsoft/Microsoft365DSC#2199]
Hi there,

i have setup the CICD in on-premise azure devops server. just small changes in yml file for build artifacts since on-premise azure devops does not support pushlish artifact.
the same code is  working fine when i use it in online azure devops portal but here it gives me error in final release. find the error screen shot below...

![error6](https://user-images.githubusercontent.com/88958817/185884697-7075aa0a-d58e-4d02-9e55-10d7634af4d1.PNG)
![error5](https://user-images.githubusercontent.com/88958817/185884711-342ec524-8cd0-48cf-8fdc-8746c64ebac9.PNG)

I have tried giving solution like. : Update-M365DSCAllowedGraphScopes -ResourceNameList @('SPOTenantSettings') -Type ‘Update. but the issue was same. 

-> i am attaching the code files below if any changes require please let me know. 
[M365-DSC.zip](https://github.com/microsoft/Microsoft365DSC/files/9392959/M365-DSC.zip)

Thanks!

**Comment by andikrueger** [comment]
This looks like an authentication issue. Do you use the same account for online and on-premises and do the same rules apply for both locations?

**Comment by Brijeshoo7** [comment]
Well for the azure tenant i am using different id and for the office365 user i have different one.

**Comment by andikrueger** [comment]
Please check if the pnp management shell has proper permissions as app and for this user.

**Comment by Brijeshoo7** [comment]
I logged into AAD of that office365 user and checked that pnp modules showing already many permission.
![image](https://user-images.githubusercontent.com/88958817/186129665-fe2eba74-25c9-4ca4-bd42-ba8cf5af5ecc.png)

still i used "Register-PnPManagementShellAccess" to grant permissions and did authentication using the office365 user.

**Comment by Brijeshoo7** [comment]
@andikrueger  
just to be clear i am using the white paper and the same configuration works fine with online azure devops service and for actual deployment i am using on-premise azure devops server.

if you want i can list out the permission let me know what to check and i'll share the details.

**Comment by andikrueger** [comment]
Are you able to run the configuration locally without using DevOps Server?

**Comment by Brijeshoo7** [comment]
Configuration O365
{
    Import-DscResource -ModuleName Microsoft365DSC
    $password = ConvertTo-SecureString 'Password' -AsPlainText -Force
    $GlobalAdmin = New-object System.Management.Automation.PSCredential ('username', $password)

    Node instance-2
    {
        # Add code changes
        SPOTenantSettings 'ConfigureTenantSettings'
        {
            IsSingleInstance                              = "Yes"
            MinCompatibilityLevel                         = 16
            MaxCompatibilityLevel                         = 16
            SearchResolveExactEmailOrUPN                  = $false
            OfficeClientADALDisabled                      = $false
            LegacyAuthProtocolsEnabled                    = $true
            SignInAccelerationDomain                      = ""
            UsePersistentCookiesForExplorerView           = $false
            UserVoiceForFeedbackEnabled                   = $true
            PublicCdnEnabled                              = $false
            PublicCdnAllowedFileTypes                     = "CSS,EOT,GIF,ICO,JPEG,JPG,JS,MAP,PNG,SVG,TTF,WOFF"
            UseFindPeopleInPeoplePicker                   = $false
            NotificationsInSharePointEnabled              = $true
            OwnerAnonymousNotification                    = $true
            ApplyAppEnforcedRestrictionsToAdHocRecipients = $true
            FilePickerExternalImageSearchEnabled          = $true
            HideDefaultThemes                             = $false
            MarkNewFilesSensitiveByDefault                = "AllowExternalSharing"
            Ensure                                        = "Present"
            Credential                                    = $credsGlobalAdmin
        }
    
    }
}

$ConfigData = @{
    AllNodes = @(
        @{
            NodeName                    = "instance-2"
            PsDSCAllowPlaintextPassword = $true
            PSDscAllowDomainUser = $true
        }
    )
}

#$ConfigData = @{...}
#Write-Log -Message 'Setting up WinRM'
#winrm quickconfig -force -quiet
O365 -ConfigurationData $ConfigData
Start-DscConfiguration O365 -Wait -Verbose -Force

**Comment by Brijeshoo7** [comment]
trying to run above script but giving me below error.

![image](https://user-images.githubusercontent.com/88958817/186607498-7e64ac9c-eedc-4ffb-a5ee-09b8e25be992.png)

**Comment by Brijeshoo7** [comment]
@andikrueger 

Configuration O365
{
    Import-DscResource -ModuleName Microsoft365DSC
    $password = ConvertTo-SecureString 'password' -AsPlainText -Force
    $credsGlobalAdmin = New-Object System.Management.Automation.PSCredential ('username', $password)
    
    Node localhost
    {
        # Add code changes
        SPOTenantSettings 'ConfigureTenantSettings'
        {
            IsSingleInstance                              = "Yes"
            MinCompatibilityLevel                         = 16
            MaxCompatibilityLevel                         = 16
            SearchResolveExactEmailOrUPN                  = $false
            OfficeClientADALDisabled                      = $false
            LegacyAuthProtocolsEnabled                    = $true
            SignInAccelerationDomain                      = ""
            UsePersistentCookiesForExplorerView           = $false
            UserVoiceForFeedbackEnabled                   = $true
            PublicCdnEnabled                              = $false
            PublicCdnAllowedFileTypes                     = "CSS,EOT,GIF,ICO,JPEG,JPG,JS,MAP,PNG,SVG,TTF,WOFF"
            UseFindPeopleInPeoplePicker                   = $false
            NotificationsInSharePointEnabled              = $true
            OwnerAnonymousNotification                    = $true
            ApplyAppEnforcedRestrictionsToAdHocRecipients = $true
            FilePickerExternalImageSearchEnabled          = $true
            HideDefaultThemes                             = $true
            MarkNewFilesSensitiveByDefault                = "AllowExternalSharing"
            Ensure                                        = "Present"
            Credential                                    = $credsGlobalAdmin
        }
    }
}

$ConfigData = @{
    AllNodes = @(
        @{
            NodeName                    = "localhost"
            PsDSCAllowPlaintextPassword = $true
        }
    )
}

O365 -ConfigurationData $ConfigData
Start-DscConfiguration C:\Users\spadmin\Downloads\M365Automation\O365 -Wait -Verbose -Force

**Comment by Brijeshoo7** [comment]
![image](https://user-images.githubusercontent.com/88958817/186625614-cdfa862a-e99c-4efb-a168-63dc3b2f6c45.png)

the same configuration is working with teams settings but not in sharepoint tenant.

**Comment by andikrueger** [comment]
Your are facing an issue with authentication to SPO. Could you try to run the following command with the user used for the configuration:

```powershell
Connect-M365Tenant -Workload PnP -Credential (Get-Credential)
```

I would expect that there is an additional window prompting for a second factor.

**Comment by Brijeshoo7** [comment]
![image](https://user-images.githubusercontent.com/88958817/186651458-8da5e8f7-4875-4f11-aa54-c77955668c63.png)

after entering creds giving this error.

**Comment by andikrueger** [comment]
Please make sure you have this permission for the Microsoft Graph PowerShell within AAD:
![image](https://user-images.githubusercontent.com/15608729/186652915-b25fbfea-5802-4556-a031-7faee3ca9c5e.png)

**Comment by Brijeshoo7** [comment]
![image](https://user-images.githubusercontent.com/88958817/186653605-fbcc90aa-fd94-4fb6-b7a5-9eeaa4ec7aa7.png)

is this all the permission?

**Comment by andikrueger** [comment]
Are there some more in user consent? 

The permissions above are not sufficient. Please review this part of the documentation: https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/#determine-required-permissions

**Comment by Brijeshoo7** [comment]
![image](https://user-images.githubusercontent.com/88958817/186676478-82409adb-54c5-4cd4-8ab4-ecfb8cb5410f.png)

are these permissions enough? if yes still the same issue not working.

**Comment by andikrueger** [comment]
Still does not look right. For an easy fix, you could run the following command. This should set all graph permission scopes.

```powershell
Update-M365DSCAllowedGraphScopes -All -Type Update -Environment Global
```

**Comment by Brijeshoo7** [comment]
![image](https://user-images.githubusercontent.com/88958817/186681798-babebaa9-dab7-4eb8-8c04-34dbdb169357.png)

done also granted from AAD. still the same.

just make sure i have Office 365 F3 subscription. is that compatible?

**Comment by andikrueger** [comment]
Could you please try the following:

```powershell
Connect-M365Tenant -Workload MicrosoftGraph -Credential (Get-Credential)
[Array]$defaultDomain = Get-MgDomain
$defaultDomain
```

This should return a domain that can be used for the PnP Calls.

**Comment by Brijeshoo7** [comment]
![image](https://user-images.githubusercontent.com/88958817/186841690-04d641f1-2dfb-4a93-892c-591ed612a94d.png)

there is no out put or an error.

**Comment by andikrueger** [comment]
Somehow the line break is missing. Please run line by line.

**Comment by Brijeshoo7** [comment]
![image](https://user-images.githubusercontent.com/88958817/186845341-fec3dfa0-1d63-4201-8f58-2d228c46870c.png)

**Comment by andikrueger** [comment]
Please run the following cmdlet to assure, the permissions for this call are right. This should open a window for login and permission consent

```powershell
Connect-MgGraph -Scopes "Domain.Read.All"
```

**Comment by Brijeshoo7** [comment]
nope still not working. i am closing this issue from now and since its clients environment so i will try in my personal if the same issue happens i will connect here.

**Comment by andikrueger** [comment]
I'll close this issue for now. Please reference/reopen this one in case there are still errors within your personal environment.

**Comment by Brijeshoo7** [comment]
i have to reopen the issue. in my personal tenant whether it is on premise or online azure devops service its working fine. i have another production tenant where "connect-mggraph" give me JWT token error and "register-PnPManagementShellAccess" give me error that site can't be reached when i run this commands in agent machine or anywhere else.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/88958817/187696936-8a3ac83f-a2aa-4675-9ca6-a104cbf6bcf4.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/88958817/187697098-2d5561d8-e482-4047-95c0-2a814eabb853.png)

any suggestion on this? @andikrueger

**Comment by andikrueger** [comment]
What kind of application are you using? The error indicates an issue with an app that is hosted at http://localhost:54909

**Comment by Brijeshoo7** [comment]
Its totally different tenant and now we want to use it for m365dsc cicd. I tried to find the url but there's no any url set in poweshell graph api.

**Comment by Brijeshoo7** [comment]
I have checked all the available Application for URL redirect. there is no such a http://localhost:54909/ set to any of that applications.
