### ISSUE TITLE
Get-MgOauth2PermissionGrant : Insufficient privileges to complete the operation 

### ISSUE THREAD

**Issue by HennepinCrawler** [microsoft/Microsoft365DSC#2200]
Get-MgOauth2PermissionGrant : Insufficient privileges to complete the operation 

This is only happening on some azure applications.  Some work, some don't.  From what I can tell the ones that are delegated appear to be throwing this error.  

I suspect this is by design but was hoping for a workaround

**Comment by HennepinCrawler** [comment]
Sorry stack:

Get-MgOauth2PermissionGrant : Insufficient privileges to complete the operation.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.720.1\DSCResources\MSFT_AADApplication\MSFT_AADApplication.psm1:783 char:88
+ ... th2PermissionGrant -Filter "ClientId eq '$($appServicePrincipal.Id)'"
+                                                ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType3`8) [Get-MgOauth2PermissionGrant_List1], RestException`1
    + FullyQualifiedErrorId : Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgOauth2PermissionGrant_List1
Get-MgOauth2PermissionGrant : Insufficient privileges to complete the operation.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.720.1\DSCResources\MSFT_AADApplication\MSFT_AADApplication.psm1:783 char:88
+ ... th2PermissionGrant -Filter "ClientId eq '$($appServicePrincipal.Id)'"
+                                                ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType3`8) [Get-MgOauth2PermissionGrant_List1], RestException`1
    + FullyQualifiedErrorId : Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgOauth2PermissionGrant_List1
Get-MgOauth2PermissionGrant : Insufficient privileges to complete the operation.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.720.1\DSCResources\MSFT_AADApplication\MSFT_AADApplication.psm1:783 char:88
+ ... th2PermissionGrant -Filter "ClientId eq '$($appServicePrincipal.Id)'"
+                                                ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType3`8) [Get-MgOauth2PermissionGrant_List1], RestException`1
    + FullyQualifiedErrorId : Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgOauth2PermissionGrant_List1
Get-MgOauth2PermissionGrant : Insufficient privileges to complete the operation.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.720.1\DSCResources\MSFT_AADApplication\MSFT_AADApplication.psm1:783 char:88
+ ... th2PermissionGrant -Filter "ClientId eq '$($appServicePrincipal.Id)'"
+                                                ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType3`8) [Get-MgOauth2PermissionGrant_List1], RestException`1
    + FullyQualifiedErrorId : Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgOauth2PermissionGrant_List1

**Comment by yoelhor** [comment]
You should include the `DelegatedPermissionGrant.ReadWrite.All` permission. For example: 

```
 Connect-MgGraph -Scopes "Application.ReadWrite.All", "DelegatedPermissionGrant.ReadWrite.All"
```

**Comment by GruberMarkus** [comment]
It seems you found a bug here.

Please change the line
```
Connect-MgGraph -Scopes 'Application.ReadWrite.All', 'AppRoleAssignment.ReadWrite.All' -NoWelcome -ContextScope Process
```
to
```
Connect-MgGraph -Scopes 'Application.ReadWrite.All', 'AppRoleAssignment.ReadWrite.All', 'DelegatedPermissionGrant.ReadWrite.All' -NoWelcome -ContextScope Process
```
and test again.
