### ISSUE TITLE
[SCSensitivityLabel] Parameter EncryptionAipTemplateScopes isn't accepted anymore

### ISSUE THREAD

**Issue by ykuijs** [microsoft/Microsoft365DSC#2205]
#### Details of the scenario you tried and the problem that is occurring
When using the EncryptionAipTemplateScopes parameter in the SCSensitivityLabel resource, I am getting the below error. We should remove this parameter from this resource. Not sure if there is a replacement for this parameter somewhere else.

#### Verbose logs showing the problem
```PowerShell
2022-08-23T08:23:19.8861508Z ##[error]A parameter cannot be found that matches parameter name 'EncryptionAipTemplateScopes'.
    + CategoryInfo          : InvalidArgument: (:) [], CimException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-Label
    + PSComputerName        : localhost
```

#### Suggested solution to the issue
Set as deprecated and then remove parameter and potentially implement a replacement

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
I cannot replicate. @ykuijs can you provide additional details? I will be updating the code to add the -IncludeDetailedLabelActions switch to the Get-Targetresource but not sure this will fix this. I am able to view and use the EncryptionAIPTemplateScopes just fine in my environment.
