### ISSUE TITLE
The specified module 'PnP.PowerShell' was not loaded because no valid module file was found in any module directory.

### ISSUE THREAD

**Issue by etec-masterofsynapse** [microsoft/Microsoft365DSC#2208]
I freshly set up M365DSC on a new Windows 11 install with all patches and PowerShell 7.2.6 inside Windows Terminal.
I started Windows Terminal with Admin Rights and executed 'Export-M365DSCConfiguration -LaunchWebUI' to update the dependencies and generate the command necessary for export.

After copying the generated export command (Full selection), I went ahead and executed it.
I gave the script a global admin with MFA enabled, clicked through the few login prompts necessary and arrived at 'Connecting to {PnP}' where the console gave me this error and quit the script:
`The specified module 'PnP.PowerShell' was not loaded because no valid module file was found in any module directory.`

When I tried to manually load PnP with "Import-Module -Name 'PnP.PowerShell'", it just did it.
I did not restart the PowerShell before that.

The run of the script after the Import went over the 'Connecting to {PnP}' without error.

What's the cause of that behavior?

**Comment by andikrueger** [comment]
At the moment, we support M365DSC in PowerShell 5 and 7.1.

 7.2 is on our roadmap. At the moment there are few struggles to get it up to the latest PS version.

**Comment by etec-masterofsynapse** [comment]
Ok, so you speculate that this temporary error is from using PS 7.2?
I assume you have no known instance of this error for the supported versions?

**Comment by andikrueger** [comment]
Not to my knowledge. This really looks like an issue with the unsupported PS 7.2.x version. https://microsoft365dsc.com/user-guide/get-started/prerequisites/#powershell-version
