### ISSUE TITLE
WARNING: There are no modules present in the system with the given module specification

### ISSUE THREAD

**Issue by etec-masterofsynapse** [microsoft/Microsoft365DSC#2209]
I freshly set up M365DSC on a new Windows 11 install with all patches and PowerShell 7.2.6 inside Windows Terminal.
I started Windows Terminal with Admin Rights and executed 'Export-M365DSCConfiguration -LaunchWebUI' to update the dependencies and generate the command necessary for export.

After copying the generated export command (Full selection), I went ahead and executed it.
I gave the script a global admin with MFA enabled, clicked through the few login prompts necessary and it began exporting.

I however noticed that for each successful step the export script completed, at the end it says
`WARNING: There are no modules present in the system with the given module specification.`

Does that mean anything, did I forget to execute some command or is that a cosmetic error in the module?

**Comment by andikrueger** [comment]
At the moment, we support M365DSC in PowerShell 5 and 7.1. 7.2 is on our roadmap. At the moment there are few struggles to get it up to the latest PS version. 


Could you check you Event Logs and as well you $error variable, if there is more information available about this warning?

**Comment by etec-masterofsynapse** [comment]
I checked the Administrative Events in the event log and there are 145 events from "MSFT_" sources which fit the timeframe of my export.

I am attaching the export from the viewer for your consideration:
[20220823_export-errors.txt](https://github.com/microsoft/Microsoft365DSC/files/9423639/20220823_export-errors.txt)

**Comment by andikrueger** [comment]
Thanks for reporting. I'll close the issue for now, as your PS Version is not in our scope right now.
