### ISSUE TITLE
1.22.727.1 Assert-M365DSCBlueprint not recognizing blueprints

### ISSUE THREAD

**Issue by Kikaider** [microsoft/Microsoft365DSC#2216]
#### Details of the scenario you tried and the problem that is occurring
Upgraded to 1.22.727.1 from 1.22.720.1 now running _Assert-M365DSCBlueprint_ results in error "Malformed BluePrint, aborting". I tried with 2 existing blueprints and I tried with a new blueprint created from an export using the 1.22.727.1 _Export-M365DSCConfiguration_ cmdlet on a different device and a different tenant.

PS - I ran the _Assert-M365DSCBlueprint_ on my existing blueprints with both the "1.22.720.1" and "1.22.727.1" versions imprinted in the blueprints with the same error message.

#### Verbose logs showing the problem
VERBOSE: Dependencies were already successfully validated.
VERBOSE: GET file:///E:/M365DSC/M365xxxxxx/M365DSC/tmp/M365xxxxxxx-SPOSharingSettings.M365 with 0-byte payload
VERBOSE: received 33804-byte response of content type application/octet-stream
Malformed BluePrint, aborting

#### Suggested solution to the issue
TBD

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# Generated with Microsoft365DSC version 1.22.727.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $Credential
)

Configuration M365xxxxxxx-SPOSharingSettings
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $Credential
    )

    if ($null -eq $Credential)
    {
        <# Credentials #>
        $Credscredential = Get-Credential -Message "Credentials"

    }
    else
    {
        $CredsCredential = $Credential
    }

    $OrganizationName = $CredsCredential.UserName.Split('@')[1]
    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.22.727.1'

    Node localhost
    {
        SPOSharingSettings 5c4aab90-aec0-4b2c-abc7-cc7df643b4f3
        {
            BccExternalSharingInvitations              = $False;
            Credential                                 = $Credscredential;
            DefaultLinkPermission                      = "View";
            DefaultSharingLinkType                     = "Internal";
            EnableGuestSignInAcceleration              = $False;
            FileAnonymousLinkType                      = "Edit";
            FolderAnonymousLinkType                    = "Edit";
            IsSingleInstance                           = "Yes";
            MySiteSharingCapability                    = "Disabled";
            NotifyOwnersWhenItemsReshared              = $True;
            PreventExternalUsersFromResharing          = $False;
            ProvisionSharedWithEveryoneFolder          = $False;
            RequireAcceptingAccountMatchInvitedAccount = $False;
            SharingCapability                          = "Disabled";
            SharingDomainRestrictionMode               = "None";
            ShowAllUsersClaim                          = $False;
            ShowEveryoneClaim                          = $False;
            ShowEveryoneExceptExternalUsersClaim       = $True;
            ShowPeoplePickerSuggestionsForGuestUsers   = $False;
        }
    }
}
M365xxxxxxx-SPOSharingSettings -ConfigurationData .\ConfigurationData.psd1 -Credential $Credential

```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.727.1

**Comment by andikrueger** [comment]
Did you run the following cmdLets during your upgrade process too:

```powershell
Update-M365DSCDependencies
Uninstall-M365DSCOutdatedDependencies
```

I copied your config above and was able to run an assessment.
