### ISSUE TITLE
Microsoft Teams: policy export include the policy ID and not the human readable policy name

### ISSUE THREAD

**Issue by DUeffing** [microsoft/Microsoft365DSC#2218]
ISSUE TITLE:
    Microsoft Teams: policy export includes the policy ID and not the human readable policy name as outlined in the Teams Admin center

   

#### Details of the scenario you tried and the problem that is occurring
when running 
#### Verbose logs showing the problem
n / a
#### Suggested solution to the issue
instead of the policy id the name as outlined in the admin center should be included in the report in addition to the ID for better matching when more then one policy is configured.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Export-M365DSCConfiguration -Components @("TeamsCallingPolicy", "TeamsChannelsPolicy", "TeamsEmergencyCallingPolicy", "TeamsEmergencyCallRoutingPolicy", "TeamsMeetingBroadcastPolicy", "TeamsMeetingPolicy", "TeamsMessagingPolicy", "TeamsUpdateManagementPolicy", "TeamsUpgradePolicy") -Credential $credstenantadmin -path c:\temp\teams -FileName "TeamsPolicies.ps1"

# insert configuration here
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $Credential
)

Configuration TeamsPolicies
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $Credential
    )

    if ($null -eq $Credential)
    {
        <# Credentials #>
        $Credscredential = Get-Credential -Message "Credentials"

    }
    else
    {
        $CredsCredential = $Credential
    }

    $OrganizationName = $CredsCredential.UserName.Split('@')[1]
    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.22.720.1'

    Node localhost
    {
        TeamsCallingPolicy 37531d22-3200-4843-af60-e3c07e271221
        {
            AllowCallForwardingToPhone        = $True;
            AllowCallForwardingToUser         = $True;
            AllowCallGroups                   = $True;
            AllowCloudRecordingForCalls       = $False;
            AllowDelegation                   = $True;
            AllowPrivateCalling               = $True;
            AllowTranscriptionForCalling      = $False;
            AllowVoicemail                    = "UserOverride";
            AllowWebPSTNCalling               = $True;
            AutoAnswerEnabledType             = "Disabled";
            BusyOnBusyEnabledType             = "Disabled";
            Credential                        = $Credscredential;
            Ensure                            = "Present";
            Identity                          = "Global";
            LiveCaptionsEnabledTypeForCalling = "DisabledUserOverride";
            MusicOnHoldEnabledType            = "Enabled";
            PreventTollBypass                 = $False;
            SpamFilteringEnabledType          = "Enabled";
        }
        TeamsCallingPolicy a76c0fb8-4a42-4687-b416-e802e0359dbf
        {
            AllowCallForwardingToPhone        = $True;
            AllowCallForwardingToUser         = $True;
            AllowCallGroups                   = $True;
            AllowCloudRecordingForCalls       = $False;
            AllowDelegation                   = $True;
            AllowPrivateCalling               = $True;
            AllowTranscriptionForCalling      = $False;
            AllowVoicemail                    = "UserOverride";
            AllowWebPSTNCalling               = $True;
            AutoAnswerEnabledType             = "Disabled";
            BusyOnBusyEnabledType             = "Disabled";
            Credential                        = $Credscredential;
            Ensure                            = "Present";
            Identity                          = "Tag:AllowCalling";
            LiveCaptionsEnabledTypeForCalling = "DisabledUserOverride";
            MusicOnHoldEnabledType            = "Enabled";
            PreventTollBypass                 = $False;
            SpamFilteringEnabledType          = "Enabled";
        }
        TeamsCallingPolicy 1dbffcf8-e56f-448f-9c06-dbe9965435c5
        {
            AllowCallForwardingToPhone        = $False;
            AllowCallForwardingToUser         = $False;
            AllowCallGroups                   = $False;
            AllowCloudRecordingForCalls       = $False;
            AllowDelegation                   = $False;
            AllowPrivateCalling               = $False;
            AllowTranscriptionForCalling      = $False;
            AllowVoicemail                    = "AlwaysDisabled";
            AllowWebPSTNCalling               = $True;
            AutoAnswerEnabledType             = "Disabled";
            BusyOnBusyEnabledType             = "Disabled";
            Credential                        = $Credscredential;
            Ensure                            = "Present";
            Identity                          = "Tag:DisallowCalling";
            LiveCaptionsEnabledTypeForCalling = "DisabledUserOverride";
            MusicOnHoldEnabledType            = "Enabled";
            PreventTollBypass                 = $False;
            SpamFilteringEnabledType          = "Enabled";
        }
        TeamsCallingPolicy 0da46109-1765-41c2-b841-8717b15aec6a
        {
            AllowCallForwardingToPhone        = $True;
            AllowCallForwardingToUser         = $True;
            AllowCallGroups                   = $True;
            AllowCloudRecordingForCalls       = $False;
            AllowDelegation                   = $True;
            AllowPrivateCalling               = $True;
            AllowTranscriptionForCalling      = $False;
            AllowVoicemail                    = "UserOverride";
            AllowWebPSTNCalling               = $True;
            AutoAnswerEnabledType             = "Disabled";
            BusyOnBusyEnabledType             = "Disabled";
            Credential                        = $Credscredential;
            Ensure                            = "Present";
            Identity                          = "Tag:AllowCallingPreventTollBypass";
            LiveCaptionsEnabledTypeForCalling = "DisabledUserOverride";
            MusicOnHoldEnabledType            = "Enabled";
            PreventTollBypass                 = $True;
            SpamFilteringEnabledType          = "Enabled";
        }
        TeamsCallingPolicy b2154dc4-8b7a-4a2f-b828-62497fa38c55
        {
            AllowCallForwardingToPhone        = $False;
            AllowCallForwardingToUser         = $True;
            AllowCallGroups                   = $True;
            AllowCloudRecordingForCalls       = $False;
            AllowDelegation                   = $True;
            AllowPrivateCalling               = $True;
            AllowTranscriptionForCalling      = $False;
            AllowVoicemail                    = "UserOverride";
            AllowWebPSTNCalling               = $True;
            AutoAnswerEnabledType             = "Disabled";
            BusyOnBusyEnabledType             = "Disabled";
            Credential                        = $Credscredential;
            Ensure                            = "Present";
            Identity                          = "Tag:AllowCallingPreventForwardingtoPhone";
            LiveCaptionsEnabledTypeForCalling = "DisabledUserOverride";
            MusicOnHoldEnabledType            = "Enabled";
            PreventTollBypass                 = $False;
            SpamFilteringEnabledType          = "Enabled";
        }
        TeamsChannelsPolicy 4e4a6653-5485-4bb8-9b17-167387c55562
        {
            AllowChannelSharingToExternalUser             = $True;
            AllowOrgWideTeamCreation                      = $True;
            AllowPrivateChannelCreation                   = $True;
            AllowPrivateTeamDiscovery                     = $True;
            AllowSharedChannelCreation                    = $True;
            AllowUserToParticipateInExternalSharedChannel = $True;
            Credential                                    = $Credscredential;
            Ensure                                        = "Present";
            Identity                                      = "Global";
        }
        TeamsChannelsPolicy 1557dad3-a057-4e47-be4a-5dc4bfce9a60
        {
            AllowChannelSharingToExternalUser             = $True;
            AllowOrgWideTeamCreation                      = $True;
            AllowPrivateChannelCreation                   = $True;
            AllowPrivateTeamDiscovery                     = $True;
            AllowSharedChannelCreation                    = $True;
            AllowUserToParticipateInExternalSharedChannel = $True;
            Credential                                    = $Credscredential;
            Ensure                                        = "Present";
            Identity                                      = "Tag:Default";
        }
        TeamsEmergencyCallingPolicy b1bb5517-2597-473d-9d2b-252de14e9a7e
        {
            Credential           = $Credscredential;
            Ensure               = "Present";
            Identity             = "Global";

#### The operating system the target node is running
sName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
ModuleBase                                                            Version   
----------                                                            -------   
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.720.1 1.22.720.1

**Comment by andikrueger** [comment]
The Teams*Policies define a property `Identity` which is present in the export. This parameter is the same as within the admin center:

![image](https://user-images.githubusercontent.com/15608729/186651232-77b42478-1bb2-4d13-8cff-1b8b4f6c14e1.png)

**Comment by DUeffing** [comment]
HI @andikrueger , thanks for the quick reply. Indeed, I missed this value or even not read the documentation carefully enough.

**Comment by andikrueger** [comment]
No worries. I'll close this issue for now.
