### ISSUE TITLE
The SendConfigurationApply function did not succeed 

### ISSUE THREAD

**Issue by jackmurphy89** [microsoft/Microsoft365DSC#2224]
I keep getting this generic error when I go to apply a configuration. Everything runs fine until the last step. Can provide whatever details are needed! Thanks in advance!

**Comment by andikrueger** [comment]
This issue is often caused by an issue with you local configuration manager or the underlying winRM stack. 

you could test winRM

```powershell
Test-WSMan
```
if this one does not return proper values, you could try to run 

```powershell
winrm quickconfig -force
```

Additionally it could be an issue with permissions: Please run the cmdLet as a local admin on the computer and make sure to use PS 5 or 7.1.

**Comment by jackmurphy89** [comment]
Same issue after trying all above methods

**Comment by andikrueger** [comment]
Could you share a screenshot of the Start-DSCConfiguration -verbose -force -wait command?

**Comment by jackmurphy89** [comment]
Start-DSCConfiguration -Path C:\DSC\M365TenantConfig -Wait -Verbose -Force

**Comment by ykuijs** [comment]
Hi @jackmurphy89, to assist you we need a little more information. The Start-DscConfiguration command will write some output to your screen. Can you please copy that and paste it here? That will provide us more details with which we might be able to answer your question.

**Comment by jackmurphy89** [comment]
<img width="863" alt="Screen Shot 2022-08-26 at 5 33 21 PM" src="https://user-images.githubusercontent.com/53065487/186993769-5bab845e-2eda-4121-9719-3153d555f4ba.png">

**Comment by andikrueger** [comment]
Could you also share a screenshot of the error message and passages, where it might occur?

**Comment by ykuijs** [comment]
Hi @jackmurphy89, 

This output only shows yellow messages, which in this case mean everything has gone well (Verbose output only). It does not contain error red/error messages that will tell us what is going on. Please share the full verbose output.

You can do a copy/paste from the PowerShell window and paste the output here.

**Comment by jackmurphy89** [comment]
<img width="826" alt="Screen Shot 2022-08-30 at 11 42 16 AM" src="https://user-images.githubusercontent.com/53065487/187481134-abf224b4-6193-46a3-a61d-8548c4c3d828.png">
<img width="826" alt="Screen Shot 2022-08-30 at 11 41 42 AM" src="https://user-images.githubusercontent.com/53065487/187481136-c7d793af-ac37-475d-b857-3c27c71c877d.png">
<img width="826" alt="Screen Shot 2022-08-30 at 11 41 32 AM" src="https://user-images.githubusercontent.com/53065487/187481139-cfb5ab54-7812-4b7c-96af-9dbd7092d6d0.png">
<img width="826" alt="Screen Shot 2022-08-30 at 11 41 18 AM" src="https://user-images.githubusercontent.com/53065487/187481142-9c565794-0e45-4977-9e87-36399390bc5d.png">

**Comment by 229Lane** [comment]
I'm investigating the same issue on our DSC implementation. Try **Start-DscConfiguration -UseExisting -Verbose -Wait -ErrorAction Ignore** and see if it goes through. I have a resource that isn't behaving like it should and throwing an error in the middle of applying the configuration. The configuration is behaving like $ErrorActionPreference is set to "Stop" which is causing the "SendConfigurationApply function did not succeed error". Not sure why it is behaving that way yet.

**Comment by andikrueger** [comment]
@jackmurphy89 the error descriptions show that your configuration tries to configure objects, that are not available within the tenant. Please remove those resources with their configuration or make sure sure the dependencies between the resources are setup correctly.

**Comment by jackmurphy89** [comment]
So the reason I get the "The SendConfigurationApply function did not succeed." error is because it is trying to configure objects that are not within the tenant?

**Comment by 229Lane** [comment]
Sorry Jack, but we have yet to resolve our issue entirely. That said, it looks as though our two issues might only be related in the sense that we receive a similar generic error message. When we figure out our issue I'll let you know what it is but it might not have anything to do with what you are experiencing.

**Comment by andikrueger** [comment]
> So the reason I get the "The SendConfigurationApply function did not succeed." error is because it is trying to configure objects that are not within the tenant?

That is correct. Many resources would create the objects so that this error should not happen. The resource in this case is used to configure some other 'content' within the tenant. As soon as this content is missing, there will be an error.

**Comment by andikrueger** [comment]
> Sorry Jack, but we have yet to resolve our issue entirely. That said, it looks as though our two issues might only be related in the sense that we receive a similar generic error message. When we figure out our issue I'll let you know what it is but it might not have anything to do with what you are experiencing.

@229Lane  Please feel free to raise a separate issue for further investigation. Please provide as much detail as possible.

**Comment by jackmurphy89** [comment]
> > So the reason I get the "The SendConfigurationApply function did not succeed." error is because it is trying to configure objects that are not within the tenant?
> 
> That is correct. Many resources would create the objects so that this error should not happen. The resource in this case is used to configure some other 'content' within the tenant. As soon as this content is missing, there will be an error.

Is there a guide anywhere that explains what creates a resource and what doesn't so it would fail?

**Comment by andikrueger** [comment]
Not that I am aware of. If you run an export resources for all selected components will be created. There are a few resources that have dependencies. Within m365dsc we do not handle these dependencies nor check if there are any. (please have a look at https://github.com/microsoft/Microsoft365DSC/issues/597)

for now, there are two possible options available:

Check every resource for possible dependencies and

1. change the order of the resources within your configuration 
2. use the DependsOn parameter for the resources.
