### ISSUE TITLE
Export-M365DSCConfiguration - Error exporting Excel report running scrip as scheduled task

### ISSUE THREAD

**Issue by StefanDavenport** [microsoft/Microsoft365DSC#2225]
ISSUE DESCRIPTION (this template):

I'm getting the message below using Export-M365DSCConfiguration to export the configuration to an Excel workbook.  The PowerShell script runs as a scheduled task using the SYSTEM account.  The same script also uses Export-M365DSCConfiguration to export to JSON and HTML files and these complete successfully.  Also, if I run the script interactively using my account the Excel workbook exports successfully.

Unable to get the SaveAs property of the Workbook class
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.720.1\modules\M365DSCReport.psm1:349 char:5
+     $workbook.SaveAs($OutputPath)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException
Unable to get the SaveAs property of the Workbook class
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.720.1\modules\M365DSCReport.psm1:349 char:5
+     $workbook.SaveAs($OutputPath)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException#### Suggested solution to the issue

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

New-M365DSCReportFromConfiguration -ConfigurationPath <path to the exported configuration> -OutputPath <path and filename to write the report to> -Type Excel

As mentioned I have an automated script which uses some variables to sort out the path for the config export file and to write out the report.

#### The operating system the target node is running

Running on Windows Server 2019

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.22.720.1

I'll look at updating the release version and re-testing

**Comment by andikrueger** [comment]
This issue is caused by using the System Account on your system. Please review the section "Problems using server-side Automation of Office" in this article:

https://support.microsoft.com/en-us/topic/considerations-for-server-side-automation-of-office-48bcfe93-8a89-47f1-0bce-017433ad79e2

> Many services run under accounts that have no user profiles (such as the SYSTEM account or the IWAM_[servername] accounts). Therefore, Office may not initialize correctly on startup. In this situation, Office returns an error on the CreateObject function or the CoCreateInstance function. Even if the Office application can be started, other functions may not work correctly if no user profile exists.

I would suggest to use a proper user account for this scenario. Please make sure to log in with the user account prior to using it.
