### ISSUE TITLE
AADRoleSetting throws an error if there are no AAD P2 licenses in a tenant

### ISSUE THREAD

**Issue by salbeck-sit** [microsoft/Microsoft365DSC#2227]
#### Details of the scenario you tried and the problem that is occurring
Call Export-M365DSCConfiguration -Workload AAD
throws an error when attempting to export AADRoleSettings

#### Verbose logs showing the problem
[8/11] Extracting [AADRoleSetting]...
    |---[1/92] Global AdministratorGet-MgPolicyRoleManagementPolicyAssignment : The tenant needs an AAD Premium 2 licens
e.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.824.1\DSCResources\MSFT_AADRoleSetting\MSFT_AADRoleS
etting.psm1:215 char:5
+     $Policy = Get-MgPolicyRoleManagementPolicyAssignment -Filter $Fil ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType3`8) [Get-MgPolic
   yRol...ssignment_List1], RestException`1
    + FullyQualifiedErrorId : AadPremiumLicenseRequired,Microsoft.Graph.PowerShell.Cmdlets.GetMgPolicyRoleManagementPo
   licyAssignment_List1
Cannot bind argument to parameter 'UnifiedRoleManagementPolicyId' because it is an empty string.

#### Suggested solution to the issue
Fail gracefully if cmdlet throws an error

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.5246.amd64fre.rs1_release.220701-1744
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
'dev' (1.22.824.1)

**Comment by salbeck-sit** [comment]
I'd suggest that the Export-TargetResource function checks if licensing is in place to export settings before trying. It's OK to throw an error if a configuration contains the resources without having licensing in place.

**Comment by sandrola** [comment]
The Problem is that also if the P2 license is in place, PIM must be enabled, this cannot (as long i know) be checked with powershell. A solution could be to catch the error and continue without the export. Renaming the Resource is a good idea, but doesen't resolve the problem if the AAD Workload is used.

**Comment by salbeck-sit** [comment]
I think that a good first step could be to rename the resource. Then I can skip the resource during export. An additional update could be to update the export-targetresource to catch exceptions during get-targetresource. If an exception *is not* related to licensing/PIM then  it's OK to throw an error, but if it *is* caused by licensing and/or PIM then just write a warning-msg to the eventlog and move on

**Comment by sandrola** [comment]
The Pullrequest #2294 Include a try/catch during the export with a Message so the export is not interrupted if more resources are choosen or the workload AAD is defined. I have found some problems evaluating the error message in catch. Is there a doc or example for this?
