### ISSUE TITLE
EXOMailTips component in DSC is unable to export the configuration

### ISSUE THREAD

**Issue by OumaimaHmaied** [microsoft/Microsoft365DSC#2235]
#### Details of the scenario you tried and the problem that is occurring
I'm trying to export the Mailtips configuration in Exchange Online using this command: 
"Export-M365DSCConfiguration -Components @(“EXOMailTips") -ApplicationId $applicationId -TenantId $tenantId -CertificateThumbprint $applicationThumbprint -Path $filePath -FileName $fileName"
the command is running as expected (without throwing an error) but it's not exporting the configuration. In fact the exported file came out empty.
The assigned permissions for the used app are:
Microsoft Graph:
- Agreement.Read.All - Application
- Application.Read.All - Application
- AuditLog.Read.All - Application
- Directory.Read.All - Application   
- GroupMember.Read.All - Application
- Policy.Read.All - Application
- Policy.Read.ConditionalAccess - Application
- RoleManagement.Read.All - Application 
- RoleManagement.Read.Directory - Application 
- User.Read - Delegated
- User.Read.All - Application 

Office 365 Exchange Online:  
- Exchange.ManageAsApp - Application 

SharePoint:
- Sites.Read.All - Application

#### Verbose logs showing the problem

VERBOSE: {DSCParser} version 1.3.0.5
VERBOSE: Populating RepositorySourceLocation property for module DSCParser.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\DSCParser\1.3.0.5\modules\DSCParser.psm1'.
VERBOSE: {ExchangeOnlineManagement} version 2.0.5
VERBOSE: Populating RepositorySourceLocation property for module ExchangeOnlineManagement.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\.\netFramework\ExchangeOnlineManagement.psm1'.
VERBOSE: {Microsoft.Graph.Applications} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Applications.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Applications\1.10.0\./Microsoft.Graph.Applications.psm1'.
VERBOSE: {Microsoft.Graph.Authentication} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Authentication.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.10.0\./Microsoft.Graph.Authentication.psm1'.
VERBOSE: {Microsoft.Graph.DeviceManagement} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.DeviceManagement.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.DeviceManagement\1.10.0\./Microsoft.Graph.DeviceManagement.psm1'.
VERBOSE: {Microsoft.Graph.DeviceManagement.Administration} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.DeviceManagement.Administration.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.DeviceManagement.Administration\1.10.0\./Microsoft.Graph.DeviceManagement.Ad
ministration.psm1'.
VERBOSE: {Microsoft.Graph.DeviceManagement.Enrolment} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.DeviceManagement.Enrolment.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.DeviceManagement.Enrolment\1.10.0\./Microsoft.Graph.DeviceManagement.Enrolme
nt.psm1'.
VERBOSE: {Microsoft.Graph.Devices.CorporateManagement} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Devices.CorporateManagement.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Devices.CorporateManagement\1.10.0\./Microsoft.Graph.Devices.CorporateManage
ment.psm1'.
VERBOSE: {Microsoft.Graph.Groups} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Groups.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Groups\1.10.0\./Microsoft.Graph.Groups.psm1'.
VERBOSE: {Microsoft.Graph.Identity.DirectoryManagement} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Identity.DirectoryManagement.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Identity.DirectoryManagement\1.10.0\./Microsoft.Graph.Identity.DirectoryMana
gement.psm1'.
VERBOSE: {Microsoft.Graph.Identity.Governance} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Identity.Governance.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Identity.Governance\1.10.0\./Microsoft.Graph.Identity.Governance.psm1'.
VERBOSE: {Microsoft.Graph.Identity.SignIns} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Identity.SignIns.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Identity.SignIns\1.10.0\./Microsoft.Graph.Identity.SignIns.psm1'.
VERBOSE: {Microsoft.Graph.Planner} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Planner.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Planner\1.10.0\./Microsoft.Graph.Planner.psm1'.
VERBOSE: {Microsoft.Graph.Teams} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Teams.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Teams\1.10.0\./Microsoft.Graph.Teams.psm1'.
VERBOSE: {Microsoft.Graph.Users} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Users.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Users\1.10.0\./Microsoft.Graph.Users.psm1'.
VERBOSE: {Microsoft.PowerApps.Administration.PowerShell} version 2.0.150
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.PowerApps.Administration.PowerShell.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.PowerApps.Administration.PowerShell\2.0.150\Microsoft.PowerApps.Administration.Pow
ershell.psm1'.
VERBOSE: {MicrosoftTeams} version 4.5.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module MicrosoftTeams.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.5.0\./MicrosoftTeams.psm1'.
VERBOSE: {MSCloudLoginAssistant} version 1.0.87
VERBOSE: Populating RepositorySourceLocation property for module MSCloudLoginAssistant.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\ConnectionProfile.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\Azure.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\AzureAD.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\ExchangeOnline.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\Intune.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\MicrosoftGraph.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\PnP.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\PowerPlatform.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\SecurityCompliance.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\Teams.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\MSCloudLoginAssistant.psm1'.
VERBOSE: {PnP.PowerShell} version 1.11.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.6.1 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module PnP.PowerShell.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PnP.PowerShell\1.11.0\Framework\PnP.PowerShell.dll'.
VERBOSE: {ReverseDSC} version 2.0.0.11
VERBOSE: Populating RepositorySourceLocation property for module ReverseDSC.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\ReverseDSC\2.0.0.11\ReverseDSC.Core.psm1'.
VERBOSE: No existing connections to Microsoft Graph
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.720.1\DSCResources\MSFT_EXOMailTips\MSFT_EXOMailTips.psm1'.
VERBOSE: Importing function 'Export-TargetResource'.
VERBOSE: Importing function 'Get-TargetResource'.
VERBOSE: Importing function 'Set-TargetResource'.
VERBOSE: Importing function 'Test-TargetResource'.
Connecting to {ExchangeOnline}...✅
[1/1] Extracting [EXOMailTips]...VERBOSE: Attempting connection to {ExchangeOnline} with:
VERBOSE: 
Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
CertificateThumbprint          XXXX                                                                                                 
TenantId                       XXXX                                                                                                      
ApplicationId                  XXXX                                                                                                      
VERBOSE: Dependencies were not already validated.
VERBOSE: {DSCParser} version 1.3.0.5
VERBOSE: Populating RepositorySourceLocation property for module DSCParser.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\DSCParser\1.3.0.5\modules\DSCParser.psm1'.
VERBOSE: {ExchangeOnlineManagement} version 2.0.5
VERBOSE: Populating RepositorySourceLocation property for module ExchangeOnlineManagement.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.5\.\netFramework\ExchangeOnlineManagement.psm1'.
VERBOSE: {Microsoft.Graph.Applications} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Applications.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Applications\1.10.0\./Microsoft.Graph.Applications.psm1'.
VERBOSE: {Microsoft.Graph.Authentication} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Authentication.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.10.0\./Microsoft.Graph.Authentication.psm1'.
VERBOSE: {Microsoft.Graph.DeviceManagement} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.DeviceManagement.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.DeviceManagement\1.10.0\./Microsoft.Graph.DeviceManagement.psm1'.
VERBOSE: {Microsoft.Graph.DeviceManagement.Administration} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.DeviceManagement.Administration.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.DeviceManagement.Administration\1.10.0\./Microsoft.Graph.DeviceManagement.Ad
ministration.psm1'.
VERBOSE: {Microsoft.Graph.DeviceManagement.Enrolment} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.DeviceManagement.Enrolment.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.DeviceManagement.Enrolment\1.10.0\./Microsoft.Graph.DeviceManagement.Enrolme
nt.psm1'.
VERBOSE: {Microsoft.Graph.Devices.CorporateManagement} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Devices.CorporateManagement.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Devices.CorporateManagement\1.10.0\./Microsoft.Graph.Devices.CorporateManage
ment.psm1'.
VERBOSE: {Microsoft.Graph.Groups} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Groups.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Groups\1.10.0\./Microsoft.Graph.Groups.psm1'.
VERBOSE: {Microsoft.Graph.Identity.DirectoryManagement} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Identity.DirectoryManagement.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Identity.DirectoryManagement\1.10.0\./Microsoft.Graph.Identity.DirectoryMana
gement.psm1'.
VERBOSE: {Microsoft.Graph.Identity.Governance} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Identity.Governance.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Identity.Governance\1.10.0\./Microsoft.Graph.Identity.Governance.psm1'.
VERBOSE: {Microsoft.Graph.Identity.SignIns} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Identity.SignIns.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Identity.SignIns\1.10.0\./Microsoft.Graph.Identity.SignIns.psm1'.
VERBOSE: {Microsoft.Graph.Planner} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Planner.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Planner\1.10.0\./Microsoft.Graph.Planner.psm1'.
VERBOSE: {Microsoft.Graph.Teams} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Teams.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Teams\1.10.0\./Microsoft.Graph.Teams.psm1'.
VERBOSE: {Microsoft.Graph.Users} version 1.10.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.Graph.Users.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Users\1.10.0\./Microsoft.Graph.Users.psm1'.
VERBOSE: {Microsoft.PowerApps.Administration.PowerShell} version 2.0.150
VERBOSE: Populating RepositorySourceLocation property for module Microsoft.PowerApps.Administration.PowerShell.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.PowerApps.Administration.PowerShell\2.0.150\Microsoft.PowerApps.Administration.Pow
ershell.psm1'.
VERBOSE: {MicrosoftTeams} version 4.5.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.7.2 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module MicrosoftTeams.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.5.0\./MicrosoftTeams.psm1'.
VERBOSE: {MSCloudLoginAssistant} version 1.0.87
VERBOSE: Populating RepositorySourceLocation property for module MSCloudLoginAssistant.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\ConnectionProfile.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\Azure.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\AzureAD.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\ExchangeOnline.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\Intune.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\MicrosoftGraph.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\PnP.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\PowerPlatform.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\SecurityCompliance.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\Workloads\Teams.psm1'.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.87\MSCloudLoginAssistant.psm1'.
VERBOSE: {PnP.PowerShell} version 1.11.0
VERBOSE: Cannot verify the Microsoft .NET Framework version 4.6.1 because it is not included in the list of permitted versions.
VERBOSE: Populating RepositorySourceLocation property for module PnP.PowerShell.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\PnP.PowerShell\1.11.0\Framework\PnP.PowerShell.dll'.
VERBOSE: {ReverseDSC} version 2.0.0.11
VERBOSE: Populating RepositorySourceLocation property for module ReverseDSC.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\ReverseDSC\2.0.0.11\ReverseDSC.Core.psm1'.
VERBOSE: Dependencies were all successfully validated.
VERBOSE: ApplicationId, TenantId, CertificateThumbprint were specified. Connecting via Service Principal
VERBOSE: Dependencies were already successfully validated.
⌛ Export took {19 seconds}
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```
<!--
Export-M365DSCConfiguration -Components @(“EXOMailTips") -ApplicationId $applicationId -TenantId $tenantId -CertificateThumbprint $applicationThumbprint -Path $filePath -FileName $fileName

-->

#### Version of the DSC module that was used:
Microsoft365DSC v1.22.720.1

**Comment by Be-Mabdeen** [comment]
I'm encountering an issue when trying to generate an HTML report from my configuration using the following command:

New-M365DSCReportFromConfiguration -Type HTML -ConfigurationPath C:\DemoM365DSC\m365TenantConfig.pst -OutputPath C:\DemoM365DSC\Report.html

The process fails with the following error:

Error parsing configuration: At line:31057 char:9
+         EXOMailTips "EXOMailTips"
+         ~~~~~~~~~~~
Undefined DSC resource 'EXOMailTips'. Use Import-DSCResource to import the resource.
At C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.16\Modules\DSCParser.psm1:472 char:9
+         throw "$($errorPrefix)Error parsing configuration: $parseErro ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error parsing c...t the resource.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error parsing configuration: At line:31057 char:9
+         EXOMailTips "EXOMailTips"
+         ~~~~~~~~~~~
Undefined DSC resource 'EXOMailTips'. Use Import-DSCResource to import the resource.

It seems like the EXOMailTips resource is either missing or not properly imported in the configuration. Any advice on how to resolve this? Do I need to manually import this DSC resource, or is there something wrong with the generated config file?

Thanks in advance!
