### ISSUE TITLE
M365DSCLogEngine causes errors in Azure Automation Run Books

### ISSUE THREAD

**Issue by andikrueger** [microsoft/Microsoft365DSC#2236]
When running M365DSC Exports within Azure Automation Run Books there are some errors reported, that are cause by M365DSCLogEngine.

The code within the run book is run as administrator. 
```
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
$currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
true
```

Looks like there is an issue with writing to the event log.

```powershell
Write-EventLog : The registry key for the log "M365DSC" for source "MSFT_SPOAccessControlSettings" could not be opened.
At C:\Modules\User\Microsoft365DSC\modules\M365DSCLogEngine.psm1:142 char:9
+         Write-EventLog -LogName $LogName -Source $Source `
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Write-EventLog], Exception
    + FullyQualifiedErrorId : AccessDenied,Microsoft.PowerShell.Commands.WriteEventLogCommand
```

A possible solution could be to add a check, if run in Azure Automation like the fixes for #2233

**Comment by NikCharlebois** [comment]
Will simply be wrapping it in its own try/catch block instead. There are other scenarios that would require this such as when running from containers.
