### ISSUE TITLE
EXOATPPolicyForO365: Test Method returns true

### ISSUE THREAD

**Issue by AVAAPA** [microsoft/Microsoft365DSC#2247]
Good day Microsoft-Support Team

following bug was discovered by our team, would you please check whether your test() methods work correctly:

"EXOATPPolicyForO365: Test Method returns true although the actual and target values are not the same. Seems that the Get Method is not retrieving all attribute values."

we found out that two attributes were not set as desired:
1) AllowClickThrough
2) TrackClicks

PS command to query is:
Get-AtpPolicyForo | Select-Object AllowClickThrough, TrackClicks

Microsoft365DSC Version is 1.22.713.1

Best regards
Andriy

**Comment by malauter** [comment]
AllowClickThrough and TrackClicks parameters are deprecated and cannot be set anymore. They are also no longer part of an export with M365 DSC.
