### ISSUE TITLE
Delta report to show new or missing resources

### ISSUE THREAD

**Issue by micromega-prog** [microsoft/Microsoft365DSC#2261]
When I run a delta report using New-M365DSCDeltaReport (Microsoft365DSC v1.22.907.1) it only shows me differences between resources that exist in both configuration files.

New-M365DSCDeltaReport -Source C:\temp\Source\Source.ps1 -Destination C:\temp\Destination\Destination.ps1 -OutputPath C:\Temp\TestReport.html -DriftOnly:$true

If a new resource is created in the destination but doesn't exist in the source the delta report doesn't show that there are any differences between the two configurations. My destination.ps1 file shows that there are new Teams policies and SharePoint sites that don't exist in Source.ps1, but when I run New-M365DSCDeltaReport it says that there are no discrepancies detected. Is there a feature to show resources that exist in one configuration file but not the other? We're trying to track new resources that are created in our tenant based on a pre-existing snapshot created using Export-M365DSCConfiguration.

Thank you.

**Comment by andikrueger** [comment]
Please remove this parameter from the parameter list: -DriftOnly:$true. With this setting only differences in resources will be returned. New or missing resources are not going to be reported.

**Comment by micromega-prog** [comment]
If I remove the -DriftOnly parameter I still don't see the missing resources. However, if I swap the source and destination files in the command then I do see the missing resources:

With this command I don't see the missing resources:
New-M365DSCDeltaReport -Source C:\temp\Source\Source.ps1 -Destination C:\temp\Destination\Destination.ps1 -OutputPath C:\Temp\TestReport4.html
![image](https://user-images.githubusercontent.com/64819707/189159907-bd61e039-4190-4418-a430-f9a4f58f68ef.png)

With this command I do:
New-M365DSCDeltaReport -Destination C:\temp\Source\Source.ps1 -Source C:\temp\Destination\Destination.ps1 -OutputPath C:\Temp\TestReport3.html
![image](https://user-images.githubusercontent.com/64819707/189159995-0bde5542-9d99-4e2f-9b00-756a9cf02699.png)

**Comment by NikCharlebois** [comment]
@micromega-prog any chances you could share both your source and destination config (redact what needs to be removed)? This would help our team investigate your issue. Thanks

**Comment by micromega-prog** [comment]
[ForMS.zip](https://github.com/microsoft/Microsoft365DSC/files/9549546/ForMS.zip)

This is the command that I'm running:

New-M365DSCDeltaReport -Source C:\temp\Source\Source.ps1 -Destination C:\temp\Destination\Destination.ps1 -OutputPath C:\Temp\TestReport.html

The output only shows that the SharePoint resource is configured differently. It doesn't show any missing resources.

Thank you again for your help.
