### ISSUE TITLE
Issue cloning resources

### ISSUE THREAD

**Issue by davidmashworth** [microsoft/Microsoft365DSC#2262]
Hi all,

I am trying to wrap my head around this platform as we have previously explored other platforms. When it comes to cloning particular resources (I am testing to a dev tenant to see how this all works) I get errors based on the example script found [here](https://microsoft365dsc.com/user-guide/get-started/cloning-tenants/)

This is the code I am using in my test case:

![Screenshot 2022-09-08 101548](https://user-images.githubusercontent.com/77258962/189006585-7eda149c-d1ce-4919-8930-65a486c64230.png)

But I get an error after entering the target tenant credentials (no MFA)

![image](https://user-images.githubusercontent.com/77258962/189006953-06c41878-143d-4a10-9e7a-87fde917211c.png)

Any idea what I'm doing wrong? I should mention that the target tenant is a blank CDX M365 Enterprise Blank.

Thanks,
David

**Comment by andikrueger** [comment]
Could you please share your ps1 file?

**Comment by davidmashworth** [comment]
@andikrueger 

Sure, ps1 attached

Thanks,
David

[M365TenantConfig.zip](https://github.com/microsoft/Microsoft365DSC/files/9523725/M365TenantConfig.zip)

**Comment by andikrueger** [comment]
Please remove the parameter OutputPath from the script call. This param is not part of the parameter set of the file an therefor the configuration will not be compiled due to the error. This causes also the error of Start-DSCConfiguration…

**Comment by davidmashworth** [comment]
Hi @andikrueger - I removed the OutputPath and similar result. My script:

![image](https://user-images.githubusercontent.com/77258962/189047817-f7ded93e-4b74-4f48-bd0f-653bc8532df0.png)

and the result:

![image](https://user-images.githubusercontent.com/77258962/189047943-aff12416-a613-4a0a-8db3-15004dee1640.png)

Has it got anything to do with the location I am running it from? I tried running from the root C:\ and from C:\DSC etc...

**Comment by andikrueger** [comment]
Please correct the path for start-dscconfiguration to c:\dsc\m365tenantconfig

**Comment by davidmashworth** [comment]
@andikrueger 

Did that and getting closer :)

![image](https://user-images.githubusercontent.com/77258962/189061234-7c910fec-a58b-4324-9ebf-23da8fdfa2bf.png)

Do i have to do something on the target tenant in preparation? Its just a blank out of the box dev tenant

**Comment by davidmashworth** [comment]
Hi @andikrueger 

I tried that and looks like it ran OK:

![image](https://user-images.githubusercontent.com/77258962/189239953-e9a03126-d60b-46eb-8c20-86f631acddd7.png)

I then re-ran the script and got the following error:

![image](https://user-images.githubusercontent.com/77258962/189240019-1089a592-589b-4f74-9c21-d09220861a76.png)

As per this [article](https://github.com/microsoft/Microsoft365DSC/issues/940) - i ran get-dscresource -Module Microsoft365DSC | Select-Object Name, ModuleName, Version

![image](https://user-images.githubusercontent.com/77258962/189240137-8a000391-32a5-4518-9ff2-09e62fbbe447.png)

All looks OK. Further down in the article its mentioned that "PS1 config file was calling a specific module version that was no longer being installed because new versions had been released and therefore the file was calling an old module. I stripped the -ModuleVersion and it began working again. Another option would be to use -RequiredVersion or -MaximumVersion on the built agent module install so that the config file called version matches the installed version."

Would that be applicable in my case? This is my PS1 (the same as I previously shared):

![image](https://user-images.githubusercontent.com/77258962/189240287-4dc88155-5c2d-44f8-8afa-006cddcee3fd.png)

**Comment by andikrueger** [comment]
This should be fine. 

Do you have any old versions of M365dsc on your system?

get-module microsoft365dsc -listavailable

if yes:

uninstall-m365dscOutdatedDependencies

**Comment by davidmashworth** [comment]
no just the one

![image](https://user-images.githubusercontent.com/77258962/189284153-b46fdc1f-70c7-4566-b5c7-47574eda15e5.png)

**Comment by andikrueger** [comment]
How did you install this module? Please install the module using PS 5.1 and in the global scope.

**Comment by davidmashworth** [comment]
I should also mention right back in the beginning I had an error about duplicate modules on my system and what I did to fix was just rename the module folder in Program files

![image](https://user-images.githubusercontent.com/77258962/189284991-6c65c8f8-71cf-4c42-ae81-28c2c80a4dd8.png)

**Comment by davidmashworth** [comment]
I installed as per the guide direct in PowerShell
Install-Module Microsoft365DSC -Force
Update-M365DSCDependencies

**Comment by andikrueger** [comment]
This could cause serious problems. 

The module and its dependencies should only reside under c:\program files\windowspowershell\modules …

Please remove the PowerShell module and the dependencies from your OneDrive and rename the one in the modules folder.

**Comment by davidmashworth** [comment]
OK did that and now making progress. Getting this now

![image](https://user-images.githubusercontent.com/77258962/189288853-da028469-c0a1-447a-ba0d-a82c7ab42399.png)

WARNING: [CRED-5CG1520GD8]:
[[AADConditionalAccessPolicy]32121ae1-82ae-40ce-b92d-01ec18208e1f] Unable to retrieve AccessToken. Have you registered
the 'Microsoft Graph PowerShell' application already? Please run 'Connect-MgGraph -Scopes Domain.Read.All' and logon
using 'admin@M365x36270656.onmicrosoft.com'

'admin@M365x36270656.onmicrosoft.com' is my CDX blank dev tenant (target tenant)

So on the target tenant I need to first register an Azure app with permissions?

**Comment by andikrueger** [comment]
this guide summarizes the necessary steps for permissions and initial setup: https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/

**Comment by davidmashworth** [comment]
So just so I am on the same page, do these permissions need to be setup only on the source tenant or also on the target tenant?

For now I am just using a GA account on both, I may go down the service principle path once all this is figured out.

**Comment by andikrueger** [comment]
You need to set the permissions on both tenants.

**Comment by davidmashworth** [comment]
I thought this part of the script was doing that?

$SourceCredential = Get-Credential
Update-M365DSCAllowedGraphScopes -ResourceNameList @("AADNamedLocationPolicy") -Type Read

$TargetCredential = Get-Credential
Update-M365DSCAllowedGraphScopes -ResourceNameList @("AADNamedLocationPolicy") -Type Update

**Comment by andikrueger** [comment]
Yes, this part of the script should do that. There is additional information in the verbose output, what you could do to fix the authentication issue. Did you follow this message?

**Comment by davidmashworth** [comment]
I did that:

![image](https://user-images.githubusercontent.com/77258962/189295197-d6c9e98d-0111-474a-98a1-d542a72e6950.png)

I will go through the article for setup again this weekend and let you know how I get on. Thanks for all your help

**Comment by davidmashworth** [comment]
@andikrueger 

Is it normal for something like this to occur? It runs heaps of import functions and then followed by pages of remove actions

![image](https://user-images.githubusercontent.com/77258962/189454651-0de9290e-a22a-4ca4-acca-e6c2b1f82a34.png)


![image](https://user-images.githubusercontent.com/77258962/189454686-92d4eb5c-1478-4ea5-b701-9b72dbf10184.png)


![image](https://user-images.githubusercontent.com/77258962/189454785-f8541d49-0b5e-41db-ae5c-228857b8764f.png)


Do i just leave it to run or is there an issue?

**Comment by davidmashworth** [comment]
I left it running and all good now
Thanks for all your help @andikrueger

**Comment by NikCharlebois** [comment]
@andikrueger you, sir, rock! @davidmashworth  WRT to all the modules loading, we are investigating ways to prevent this from happening. It is not an issue right now, but we could definitively speed up the whole process if we could streamline the loading process. #WeReOnIt
