### ISSUE TITLE
Adding support for Defender for Cloud apps in M365 DSC

### ISSUE THREAD

**Issue by manishabajpai029** [microsoft/Microsoft365DSC#2263]
<!--
    Your feedback and support is greatly appreciated, thanks for contributing!

ISSUE TITLE: Feature request to support Defender for cloud apps.

 ISSUE DESCRIPTION (this template):

This is the feature request from one of the partners who are using this actively and want to use it to improve their Managed Service maturity around the Defender products. 

One gap we have seen is the lack of support for Defender for Cloud Apps and they are asking to raise this as a feature request and when this would be planned?

**Comment by andikrueger** [comment]
Closing due to lack of description. Please provide more information. There is another thread about feature request: #2332
