### ISSUE TITLE
SCAuditConfigurationPolicy fails with The term 'Get-AuditConfigurationPolicy' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by ajkenah** [microsoft/Microsoft365DSC#2266]
'Get-AuditConfigurationPolicy', 'Remove-AuditConfigurationPolicy' and 'New-AuditConfigurationPolicy' commands used in this component are part of the ExchangePowerShell PowerShell module and are not available unless you connect to the ExchangeOnline workload first.

**Comment by NikCharlebois** [comment]
Your statement is correct. However, M365DSC handles the connection to SC via the Exchange Online Management Shell module so this should be a non-issue. Can you confirm if and where you are getting an error? Thanks

**Comment by ajkenah** [comment]
Thanks for the quick response Nik.
I'm using module version 1.22.907.1
I get the error when running the following command:
$_Params = @{
    'Components' = 'SCAuditConfigurationPolicy'
    'Path' = "c:\testing\"
    'FileName' = "SCAuditConfigurationPolicy.ps1"
    'Credential' = $(Get-Credential)
}
Export-M365DSCConfiguration @_Params

Using Verbose Mode, I get the following error:

[1/1] Extracting [SCAuditConfigurationPolicy] using {Credentials}...VERBOSE: Attempting connection to {SecurityComplianceCenter} with:
VERBOSE: 
Name                           Value                                                                                                                                                         
----                           -----                                                                                                                                                         
Credential                     System.Management.Automation.PSCredential                                                                                                                     



VERBOSE: Dependencies were already successfully validated.
VERBOSE: Credential was specified. Connecting via User Principal
VERBOSE: Importing cmdlet 'Test-ActiveToken'.
VERBOSE: Dependencies were already successfully validated.
❌
VERBOSE: The term 'Get-AuditConfigurationPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
⌛ Export took {15 seconds}

When I run the following command prior to the above export command, it all works:
            $HashTable = @{
              'Credential' = $Credential
            }
            $ConnectionMode = New-M365DSCConnection -Workload 'ExchangeOnline' -InboundParameters $HashTable -SkipModuleReload $true

**Comment by NikCharlebois** [comment]
What role is the account you are using assigned?

**Comment by ajkenah** [comment]
The user is assigned the "Global Reader" role in Azure AD and the "Global Reader", "Security Reader" and "View-Only Organization Management" Roles in the Exchange Admin portal.

**Comment by ajkenah** [comment]
Looking through the modules, I can see that the New-M365DSCConnection (for Security Center) only calls the Connect-M365Tenant with the "SecurityComplianceCenter" switch.  This function, with this switch, only uses the Connect-IPPSSession function.  I believe (based on my limited experience) that the Connect-IPPSSession function doesn't support exposing the 'Get-AuditConfigurationPolicy', 'Remove-AuditConfigurationPolicy' and 'New-AuditConfigurationPolicy' commands.

**Comment by andikrueger** [comment]
I just checked the documentation on [`Get-AuditConfigurationPolicy`](https://docs.microsoft.com/en-us/powershell/module/exchange/get-auditconfigurationpolicy?view=exchange-ps):

>This cmdlet is functional only in Security & Compliance PowerShell. For more information, see [Security & Compliance PowerShell](https://docs.microsoft.com/en-us/powershell/exchange/scc-powershell).

This connection is established by `Connect-IPPSSession`. The above applies for [Remove-](https://docs.microsoft.com/en-us/powershell/module/exchange/Remove-auditconfigurationpolicy?view=exchange-ps) and [New-](https://docs.microsoft.com/en-us/powershell/module/exchange/New-auditconfigurationpolicy?view=exchange-ps) too.

Could you try to open a new connection to security and compliance center by using:

```powershell
$Credential= Get-Credential
$HashTable = @{
'Credential' = $Credential
}
```

either
```powershell
New-M365DSCConnection -Workload 'SecurityComplianceCenter' -InboundParameters $HashTable -SkipModuleReload
```

or

```powershell
Connect-M365Tenant -Workload 'SecurityComplianceCenter' -Credential $credential
```

and then

```powershell
Get-AuditConfigurationPolicy
```

**Comment by ajkenah** [comment]
Hi Andi, thanks for responding.  I've run the above commands (New-M365DSCConnection & Connect-M365Tenant), but for both of the options I get "Get-AuditConfigurationPolicy : The term 'Get-AuditConfigurationPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program."

However if I run either of the following it works and the command is found...
New-M365DSCConnection -Workload 'ExchangeOnline' -InboundParameters $Parameters -SkipModuleReload:$TRUE
Connect-M365Tenant -Workload 'ExchangeOnline' -Credential $credential

Get-Command Get-AuditConfigurationPolicy

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Get-AuditConfigurationPolicy                       1.0        tmp_ipoq14zz.4k2

**Comment by NikCharlebois** [comment]
Please refer to the following article for additional details on how to get access and use the cmdlet:
https://learn.microsoft.com/en-us/powershell/module/exchange/get-auditconfigurationpolicy?view=exchange-ps
