### ISSUE TITLE
IntuneDeviceConfigurationPolicyAndroidDeviceOwner: Credential Parameter as String in Export

### ISSUE THREAD

**Issue by andikrueger** [microsoft/Microsoft365DSC#2270]
#### Details of the scenario you tried and the problem that is occurring
1. Export settings
The export of the resource does not generate a well formatted configuration. This configuration cannot be applied to a tenant. The parameter Credential is of type string rather than PSCredential. This breaks the configuration.

#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/15608729/189640886-498d10cf-5d7c-47b1-b06c-3606ce3ac031.png)

#### Suggested solution to the issue
Change Credential Param in Exported configuration object.

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.831.1

**Comment by William-Francillette** [comment]
Hi @andikrueger 
Not sure how this is supposed to look but after rebuilding the resource I still get the credentials as a PSCredential
![image](https://user-images.githubusercontent.com/79221284/189992668-6fe0fae7-931a-43b7-a369-6260ecd4bd02.png)
![image](https://user-images.githubusercontent.com/79221284/189992689-7aeea8ab-d0bf-4414-a3e6-a8112d4182f6.png)

**Comment by andikrueger** [comment]
The issue are the quotation marks in the configuration part of this resource. The credentials should be the variable only and not a string…

**Comment by andikrueger** [comment]
@William-Francillette Were you able to investigate this one any further?

**Comment by William-Francillette** [comment]
@andikrueger, @NikCharlebois  
I can include that fix in my next PR if adding the space after Credential is acceptable
I'll try to get it done asap - 
My next PR is for adding the assignments attributes for Intune resources and also switching to the beta version some of the resources
