### ISSUE TITLE
IntuneDeviceConfigurationPolicyAndroidDeviceOwner - Export results in wrong configuration.

### ISSUE THREAD

**Issue by andikrueger** [microsoft/Microsoft365DSC#2272]
#### Details of the scenario you tried and the problem that is occurring
The export of MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceOwner results in a configuration that is not valid. The params:

- DeviceManagementApplicabilityRuleDeviceMode
- DeviceManagementApplicabilityRuleOsEdition
- DeviceManagementApplicabilityRuleOsVersion

Are not written properly. 

![image](https://user-images.githubusercontent.com/15608729/189647464-a64cde7c-ba5b-4929-87ff-f44d065f2638.png)

#### Suggested solution to the issue
Create proper instances of the CIM objects within the configuration.

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.831.1

**Comment by William-Francillette** [comment]
This resource was probably generated a while ago with one of the first version of the DRG as it is very different from the other one.
The applicability rules haven't been deployed to any resources yet.
I would suggest to generate that resource again and add support for assignments and descriptions.
Not sure about the credentials issue as I use certificate authentication
I'll be happy to work on that next

**Comment by andikrueger** [comment]
Yesterday I was working on the Credential issue and I was not able to find the root cause for this one. The handling of credential is done by one method and works for all other resources.

I think, we can skip this part for the moment and should focus on fixing the other params first.

Thanks for picking this up!
