### ISSUE TITLE
MSFT_AADApplication: New AADApplication fails to create due to issue with parameter Oauth2RequirePostResponse

### ISSUE THREAD

**Issue by JamieH-risual** [microsoft/Microsoft365DSC#2276]
When creating a new AADApplication it fails with the error: Resource '' does not exist or one of its queried reference-property objects are not present.

This appears to be an issue with the Oauth2RequirePostResponse parameter as removing it when running New-MGApplication manually creates the application successfully. 

It looks like this has already been recognised as an issue on the update of an app as it has been removed from the param list:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/40177254/189877432-08477835-915a-43b3-9452-882c88e22a0e.png">

#### Verbose logs showing the problem

<img width="774" alt="image" src="https://user-images.githubusercontent.com/40177254/189878382-3e38b814-d959-4f6e-93c2-74258a1744be.png">

#### Suggested solution to the issue

Remove the parameter prior to creation:

```powershell
$currentParameters.Remove("Oauth2RequirePostResponse") | Out-Null
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
AADApplication d84f590a-ca35-4bed-9745-7f1e71176a32
        {
            AppId                     = "1a172134-1330-4ead-a557-719b14c52d21";
            AvailableToOtherTenants   = $False;
            Credential                = $Credscredential;
            DisplayName               = "P2P Server";
            Ensure                    = "Present";
            IdentifierUris            = @("urn:p2p_cert");
            KnownClientApplications   = @();
            Oauth2RequirePostResponse = $False;
            ObjectId                  = "2e89d6db-fd47-4fad-81e4-b77e00186956";
            Owners                    = @();
            PublicClient              = $False;
            ReplyURLs                 = @();
        }
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
Microsoft365DSC - 1.22.907.1
Microsoft.Graph* - 1.11.1

**Comment by andikrueger** [comment]
This fix was introduced for the update scenario to fix unit test. The docs for the cmdLet outline this parameter. For me, this looks like an issue with the Microsoft.Graph.* modules and should be fixed there. Removing the parameter within M365DSC could cause configuration drifts and configurations that look like they were applied correctly, but aren't.

@NikCharlebois What's the best place to raise the issue with the Graph module.

**Comment by JamieH-risual** [comment]
Thanks for the prompt response @andikrueger. I've raised an issue on the Graph PowerShell SDK page: [https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1502](url)

**Comment by Faketology** [comment]
Kinda happy I found this, after spending way to much time looking for errors in my implementation LOL. Especially since it was frustrating that Update seemed to work, but New did not.

So thanx @JamieH-risual and @andikrueger. 

Not 100% sure how it works at the "Graph PowerShell SDK page". But the Issue now seems to be closed and at least the latest Powershell Microsoft Graph 1.16.0 does still have the same problem.

Is it working for anyone?
