### ISSUE TITLE
Update-M365DSCAzureAdApplication - A parameter cannot be found that matches parameter name 'Filter'.

### ISSUE THREAD

**Issue by ohpayk** [microsoft/Microsoft365DSC#2277]
#### Details of the scenario you tried and the problem that is occurring

Attempting to run 

`Update-M365DSCAzureAdApplication -ApplicationName 'Microsoft365DSC' -Permissions @(@{Api='SharePoint';PermissionName='Sites.FullControl.All'},@{Api='Graph';PermissionName='Group.ReadWrite.All'},@{Api='Exchange';PermissionsName='Exchange.ManageAsApp'}) -AdminConsent -Type Secret`

Resulting with an error: 

`Get-AzADApplication : A parameter cannot be found that matches parameter name 'Filter'.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.907.1\modules\M365DSCPermissions.psm1:1281 char:49`

#### Verbose logs showing the problem

`PS C:\WINDOWS\system32> Update-M365DSCAzureAdApplication -ApplicationName 'Microsoft365DSC' -Permissions @(@{Api='SharePoint';PermissionName='Sites.FullControl.All'},@{Api='Graph';PermissionName='Group.ReadWrite.All'},@{Api='Exchange';PermissionsName='Exchange.ManageAsApp'}) -AdminConsent -Type Secret
2022-09-13 11:06:22 - Checking specified parameters
2022-09-13 11:06:22 -   Using a Secret as credential
2022-09-13 11:06:37 -  
2022-09-13 11:06:37 - Checking existance of AD Application
Get-AzADApplication : A parameter cannot be found that matches parameter name 'Filter'.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.907.1\modules\M365DSCPermissions.psm1:1281 char:49
+     if (-not ($azureADApp = Get-AzADApplication -Filter "DisplayName  ...
+                                                 ~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzADApplication], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.ActiveDirectory.GetAzureADApplicationCommand`

#### Suggested solution to the issue

NA

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```

PSVersion                      5.1.22000.832                                                                                                                                   
PSEdition                      Desktop                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                         
BuildVersion                   10.0.22000.832                                                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                             
SerializationVersion           1.1.0.1    
```

#### The operating system the target node is running

OsName               : Microsoft Windows 11 Home
OsOperatingSystemSKU : WindowsHome
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22000.1.amd64fre.co_release.210604-1628
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)

Microsoft365DSC 1.22.907.1

**Comment by andikrueger** [comment]
Could you run the following commands to verify if this is an issue with M365DSC or the AZ Module?

The documentation for Get-AzADApplication specifies a parameter Filter. https://learn.microsoft.com/en-us/powershell/module/az.resources/get-azadapplication?view=azps-8.3.0


```powershell
Update-M365DSCDependencies
Uninstall-M365DSCOutdatedDependencies
```

Those commands will update the dependencies as well as uninstall all versions that do not match those currently needed for M365DSC.

**Comment by NikCharlebois** [comment]
I am not able to reproduce the issue on our end. Please confirm that you have the latest versions installed as @andikrueger mentions above. Thanks

**Comment by ohpayk** [comment]
Is it possible this is specific to GCC High? This is the tenant I'm attempting to work on. I've updated dependencies and will try to uninstall outdated. I'll share if that changes anything.

**Comment by indecline** [comment]
For anyone else with the same issue I had to run the below then relaunch PowerShell for it to work.

`Update-Module Az.Resources`

**Comment by andikrueger** [comment]
Please do not run any individual updates of modules. You could user update-m365dscdependencies and uninstall-m365dscoutdateddependencies to make sure your installed modules matches the requirements of microsoft365dsc

**Comment by indecline** [comment]
> Please do not run any individual updates of modules. You could user update-m365dscdependencies and uninstall-m365dscoutdateddependencies to make sure your installed modules matches the requirements of microsoft365dsc

I tried that but still had the same issue :(

**Comment by andikrueger** [comment]
Which version of Az.Resources is installed by now?

get-module Az.Resources -listavailable 

and for the microsoft365dsc module I would also be interested in the versions installed.

**Comment by andikrueger** [comment]
Something just crossed my mind:  https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Dependencies/Manifest.psd1

Az.Resources is not part of the dependencies and is going to be installed on a case by case basis when you run the cmdLet to update the Azure App. There is a PR pending that will change the dependencies to MS Graph and do some updates for a more reliable outcome.

**Comment by andikrueger** [comment]
Linking #2566
