### ISSUE TITLE
Problem / Unknown issue on creating Azure Security Groups

### ISSUE THREAD

**Issue by banned1996** [microsoft/Microsoft365DSC#2278]
Is it possible that only Microsoft365 Groups are able to be created?
I try to create assigned AADGroups, but unfortunately, DSC always deploys M365 (unified) Groups.
I did it with the following properties in my PS1-file:
```
AADGroup 'Name'
        {
            Credential = $Credscredential;
            Description = "Example Text";
            DisplayName = "Example DisplayName";
            MailNickName = "Example_Mailnickname";
            Members = @();
            Ensure = "Present";
            MailEnabled = $False;
            IsAssignableToRole = $False;
            SecurityEnabled = $True;
        }
```
Documentation does not state anywhere how to create assigned security groups - it only tells that "SecurityEnabled" needs to be set to $True
There is no example of it nor can I find the parameter for Security Groups in the definition of the module AADGroup.... 

The only thing I found was that "unified" is default for parameter "GroupTypes" - where can I look up the allowed values for GroupTypes? I can only find "Unified" and "DynamicMembership"
Can someone support me on that? Is there any dependent property which needs to be set?
Thx a lot

**Comment by andikrueger** [comment]
You need to set the GroupTypes parameter. This param defaults to `unified`. 

```powershell
AADGroup 'Name'
        {
            Credential = $Credscredential;
            Description = "Example Text";
            DisplayName = "Example DisplayName";
            MailNickName = "Example_Mailnickname";
            Members = @();
            Ensure = "Present";
            MailEnabled = $False;
            IsAssignableToRole = $False;
            SecurityEnabled = $True;
            GroupTypes = @();
        }
```

> Specifies the group type and its membership. If the collection contains Unified, the group is a Microsoft 365 group; otherwise, it's either a security group or distribution group. For details, see groups overview. If the collection includes DynamicMembership, the group has dynamic membership; otherwise, membership is static. Returned by default. Supports $filter (eq, not).

**Comment by banned1996** [comment]
@andikrueger I did it with the property GroupTypes, too. But unfortunately, it always creates a unified group:
![image](https://user-images.githubusercontent.com/5398999/190136415-baca28c4-1999-44c9-95da-087b8a271d39.png)

**Comment by banned1996** [comment]
OK now it started to work. I got something very weird, I forgot to make the ; at the end of the line somewhere which resulted in that. Idk why this happened, but now it works :) thanks a lot for the effort!
