### ISSUE TITLE
Creating EXO Contacts

### ISSUE THREAD

**Issue by banned1996** [microsoft/Microsoft365DSC#2279]
Is it possible to create EXO Contacts within M365DSC? I was not able to find any of it... Help very appreciated

**Comment by malauter** [comment]
Hi @banned1996, no, there is no DSC resource available yet for managing EXO mail contacts.

**Comment by banned1996** [comment]
Hi @malauter 
Thanks for the information :)

**Comment by NikCharlebois** [comment]
It will be soon :) Starting the work on it as we speak
