### ISSUE TITLE
TeamsChannel, TeamsChannelTab & TeamsTeam Support for Service Principal and Application permissions

### ISSUE THREAD

**Issue by ajkenah** [microsoft/Microsoft365DSC#2281]
When running an export for the above components with a Service Principal (with certificate Auth) and application permissions these components fail.
The Microsoft365DCS documentation for these components and the component modules themselves are all configured to enable this authentication method (I don't get the standard authentication method not allowed warning when running them).

When reviewing Microsoft documentation for permission requirements at the API level, all available information advises me that this use-case is not supported in the MicrosoftTeams module yet, and only delegated permissions via a service principal are supported.

Can you please advise if exporting these components using a Service Principal and Application permissions is supported, and if so, what permissions/roles are required?

**Comment by andikrueger** [comment]
At the moment, we do not support these authentication (Service Principal) methods for Teams, This is a limitation of the Teams PowerShell. There are a few resources though, that use the Microsoft Graph PowerShell modules too. e.g. TeamsChannelTab uses the Teams PowerShell to get the team and for the Channel information the Graph PowerShell is used. Passing credentials as well as a Service Principal could work for this module.

For now, please review this section of the documentation about the supported Authentication methods: https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/#authentication-methods

**Comment by jeff29922** [comment]
@ajkenah Please let us know the results of your testing if you decide to explore the Graph PowerShell option.

**Comment by ajkenah** [comment]
Thanks Andi and Jeff.  At this stage, I've descoped the 'TeamsChannelTab', 'TeamsTeam' & 'TeamsChannel' components as they are essentially broken for my solution.  'TeamsTeam' & 'TeamsChannel' don't return an authentication error saying that my authentication method is unsupported (like every other component) when using a service principal.  I'm using this notification to fall back to Credential based authentication.  Then with the 'TeamsChannelTab' component, I'm getting an error saying that credential isn't supported..
