### ISSUE TITLE
Publish export result or/and  drift result (Email Alert/ Teams Channel/Yammer)

### ISSUE THREAD

**Issue by Razz-L** [microsoft/Microsoft365DSC#2289]
I extracted Intune report and exported it to an html file, then I ran a Delta Drift to compare it with a baseline configuration, and I got the result in an html file. Also, I made a script out of the whole process and automate it via Task Scheduler to run it against my environment once a day. Everything is working as expected but I'm wondering if:
1) There is a way to get an email alert when these reports gets created
2) There is a way to post a Drift html file, or Export html file into a Teams channel, or at least get a message that this report got generated.
3) There is a way to post a message on Yammer when any of these reports get generated.

I think I can implement all the above scenarios via Power Automate, but I'm wondering if there is any way to do it via Powershell/DSC

**Comment by andikrueger** [comment]
This is a scenario that is not implemented within M365DSC. As there is already a script to export the data, it would be easy to add a few additional lines of code to accomplish the use cases you describe.

I would upload the result files to a SharePoint Document library and have a flow attached to this library. Trigger would be new element added. With this flow you can post to teams or just send out an email with link or attachment.

untested code blow:
```powershell
$Credential = Get-Credential
Connect-PnPOnline -Credential $Credential -Url <Site Collection URL> 
Add-PnPFile -Path <Path to your Report> -Folder "Shared Documents"
Disconnect-PnPOnline
```

For additional options: https://pnp.github.io/powershell/cmdlets/Add-PnPFile.html

**Comment by Razz-L** [comment]
> This is a scenario that is not implemented within M365DSC. As there is already a script to export the data, it would be easy to add a few additional lines of code to accomplish the use cases you describe.
> 
> I would upload the result files to a SharePoint Document library and have a flow attached to this library. Trigger would be new element added. With this flow you can post to teams or just send out an email with link or attachment.
> 
> untested code blow:
> 
> ```powershell
> $Credential = Get-Credential
> Connect-PnPOnline -Credential $Credential -Url <Site Collection URL> 
> Add-PnPFile -Path <Path to your Report> -Folder "Shared Documents"
> Disconnect-PnPOnline
> ```
> 
> For additional options: https://pnp.github.io/powershell/cmdlets/Add-PnPFile.html
