### ISSUE TITLE
unable to connect to GCCH tenant

### ISSUE THREAD

**Issue by fuentej** [microsoft/Microsoft365DSC#2307]
I was unable to tell if this was supported, so I tried to do an export of a GCC High tenant, and I get this error.

Command:

Export-M365DSCConfiguration -Components @("ODSettings", "SPOAccessControlSettings", "SPOApp", "SPOBrowserIdleSignout", "SPOHomeSite", "SPOHubSite", "SPOOrgAssetsLibrary", "SPOSearchManagedProperty", "SPOSearchResultSource", "SPOSharingSettings", "SPOSiteDesign", "SPOSiteDesignRights", "SPOSiteScript", "SPOStorageEntity", "SPOTenantCdnEnabled", "SPOTenantCdnPolicy", "SPOTenantSettings", "SPOTheme") -Credential $Credential
Exporting Microsoft 365 configuration for Components: ODSettings, SPOAccessControlSettings, SPOApp, SPOBrowserIdleSignout, SPOHomeSite, SPOHubSite, SPOOrgAssetsLibrary, SPOSearchManagedProperty, SPOSearchResultSource, SPOSharingSettings, SPOSiteDesign, SPOSiteDesignRights, SPOSiteScript, SPOStorageEntity, SPOTenantCdnEnabled, SPOTenantCdnPolicy, SPOTenantSettings, SPOTheme

Error:

Connecting to {PnP}...❌
An error has occurred There was an error parsing WS-Trust response from the endpoint. This may occur if there is an issue with your ADFS configuration. See https://aka.ms/msal-net-iwa-troubleshooting for more details. Error Message: Federated service at https://autologon.microsoft.us/gcch.o365pti.net/winauth/trust/2005/usernamemixed?client-request-id=578141ef-3895-4f96-80cc-7f7438173f6c returned error: Authentication Failure
Partial Export file was saved at: C:\Users\goadmin\AppData\Local\Temp\d0e91453-f345-467c-882e-84e15be9033c.partial.ps1

**Comment by andikrueger** [comment]
Are you able to connect to SharePoint Online using PnP PowerShell?

```powershell
Connect-PnPOnline -Url <TenantUrl>
```

**Comment by fuentej** [comment]
Ya, that seems to be a fail.

Connect-PnPOnline -Url https://***-admin.sharepoint.us/ -AzureEnvironment USGovernmentHigh

Connect-PnPOnline : AADSTS65001: The user or administrator has not consented to use the application with ID
'31359c7f-***-***' named 'PnP Management Shell'. Send an interactive authorization request for
this user and resource.

This is also hanging,  
Register-PnPManagementShellAccess -AzureEnvironment USGovernmentHigh

I assume this can be closed, I will check with the PnP repo.
