### ISSUE TITLE
failed to execute Test-TargetResource functionality with error message: One or more errors occurred.

### ISSUE THREAD

**Issue by ybouassal** [microsoft/Microsoft365DSC#2308]
Hello,

I am getting the below error when trying to deploy to a new tenant.

PowerShell DSC resource MSFT_SCDLPComplianceRule  failed to execute Test-TargetResource functionality with error        message: One or more errors occurred.                                                                                       + CategoryInfo          : InvalidOperation: (:) [], CimException                                                        + FullyQualifiedErrorId : ProviderOperationExecutionFailure                                                             + PSComputerName        : localhost 

PS: the credentials provided are for Global Admin

your help is much appreciated.
Thank you,
Yves

**Comment by sadishdit** [comment]
Hi Andikrueger,

I am facing the similar issue. I am getting the below error while deploying release pipeline. 
[](url)
Error occurred during deployment: PowerShell DSC resource MSFT_EXOOrganizationConfig  failed to execute Test-TargetResource functionality with error message: UnAuthorized
