### ISSUE TITLE
Update-M365DSCAzureAdApplication: Cannot process argument transformation on parameter 'Permissions'

### ISSUE THREAD

**Issue by Kikaider** [microsoft/Microsoft365DSC#2310]
#### Details of the scenario you tried and the problem that is occurring
The cmdlet Update-M365DSCAzureAdApplication errors with "Update-M365DSCAzureAdApplication : Cannot process argument transformation on parameter 'Permissions'. Cannot convert the "Sites.FullControl.All" value of type "System.String" to type "System.Collections.Hashtable[]".".

I tried this cmdlet:
```powershell
Update-M365DSCAzureAdApplication -ApplicationName "M365DSC Service Account" -Permissions "Domain.Read.All" -AdminConsent -Type Certificate -CreateSelfSignedCertificate -CertificatePath "E:\M365DSC\certs\M365DSC-Service-Account.cer"
```

plus a copy/paste directly from the documentation:
```powershell
Update-M365DSCAzureAdApplication -ApplicationName 'Microsoft365DSC' -Permissions 'Sites.FullControl.All' -AdminConsent -Type Certificate -CreateSelfSignedCertificate -CertificatePath 'E:\M365DSC\certs\M365DSC.cer'
```

I also tried formatting the -Permissions value as follows:
Sites.FullControl.All
'Sites.FullControl.All'
"Sites.FullControl.All"
@("Sites.FullControl.All")
@("Domain.Read.All","Sites.FullControl.All")
'Sites.FullControl.All', 'Sites.FullControl.All'

Note that is the same error, different cmdlet, as in #2260.

#### Verbose logs showing the problem
```
Update-M365DSCAzureAdApplication : Cannot process argument transformation on parameter 'Permissions'. Cannot convert the "Sites.FullControl.All" value of type "System.String" to type "System.Collections.Hashtable[]".
At line:1 char:82
+ ... onName 'Microsoft365DSC' -Permissions 'Sites.FullControl.All' -AdminC ...
+                                           ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Update-M365DSCAzureAdApplication], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Update-M365DSCAzureAdApplication
```

#### Suggested solution to the issue
TBD

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Update-M365DSCAzureAdApplication -ApplicationName 'Microsoft365DSC' -Permissions 'Sites.FullControl.All' -AdminConsent -Type Certificate -CreateSelfSignedCertificate -CertificatePath 'E:\M365DSC\certs\M365DSC.cer
```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Microsoft365DSC version 1.22.914.1

**Comment by andikrueger** [comment]
Please review the example section on the cmdLet. There were some updates to address additional api permissions. Therefore this cmdLet expects a Hashtable.

https://github.com/microsoft/Microsoft365DSC/blob/6e99962584244c97865314c4bb6cd5aaed03756e/Modules/Microsoft365DSC/Modules/M365DSCPermissions.psm1#L1104-L1111

**Comment by andikrueger** [comment]
Could you share a link to the outdated example. The docs page for this cmdLet looks is up to date: https://microsoft365dsc.com/user-guide/cmdlets/Update-M365DSCAzureAdApplication/

**Comment by Kikaider** [comment]
My bad. I didn't look at the cmdlet doc page.

**Comment by andikrueger** [comment]
No worries. Good catch about finding the outdated example.
