### ISSUE TITLE
AADRoleSetting - exported file node content is System.Object[]

### ISSUE THREAD

**Issue by sandrola** [microsoft/Microsoft365DSC#2321]
#### Details of the scenario you tried and the problem that is occurring
Exporting the Resource generate a file as expected but the node content is a System.Object[]

#### Verbose logs showing the problem
after some debugging I have found that the implicit string conversion in module M365DSCReverse.psm1 on Line 580:

$exportString.Append((Export-TargetResource @parameters)) | Out-Null

cannot convert the returned Object in String

Adding a Line :
Write-Host (Export-TargetResource @parameters) 
show that all data are there but the conversion is not working.

Of course the problem is in the resource itself because all other exports work, but I could not identify the problem in the resource Export-TargetResource or Get-TargetResource.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# $Filters = @{
    AADRoleSetting = "Id eq 'cf1c38e5-3621-4004-a7cb-879624dced7c'"
}

Export-M365DSCConfiguration -Components @("AADRoleSetting") -ApplicationId 00000000-0000-0000-0000-000000000000 -TenantId contoso.onmicrosoft.com -CertificateThumbprint 7EBSA4C500CCDCC5930A44E56B8A311C5BE54040 -Filters $Filters
```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.921.1

**Comment by mlhickey** [comment]
What does the resultant entry look like for you?  When I run this (1.22.921.1) I get:
`        AADRoleDefinition 80529992-4fc3-4e26-80b0-b4e01410b8e4
        {
            Description          = "Can create application registrations independent of the 'Users can register applications' setting.";
            DisplayName          = "Application Developer";
            Ensure               = "Present";
            Id                   = "cf1c38e5-3621-4004-a7cb-879624dced7c";
            IsEnabled            = $True;
            Managedidentity      = $True;
            ResourceScopes       = @("/");
            RolePermissions      = @("microsoft.directory/applications/createAsOwner","microsoft.directory/oAuth2PermissionGrants/createAsOwner","microsoft.directory/servicePrincipals/createAsOwner");
            TemplateId           = "cf1c38e5-3621-4004-a7cb-879624dced7c";
            TenantId             = $ConfigurationData.NonNodeData.TenantId;
            Version              = "1";
        }`

**Comment by mlhickey** [comment]
Problem is in Export-TargetResource.  The check for P2 license was putting all the return values from Get-MgPolicyRoleManagementPolicyAssignment onto the return stack so the return value was actually an object.  Fix is to append ` | Out-Null` to dump the returned values
