### ISSUE TITLE
New Microsoft.Graph Module 1.12.0 doesen't have the "All" Parameter

### ISSUE THREAD

**Issue by sandrola** [microsoft/Microsoft365DSC#2322]
#### Details of the scenario you tried and the problem that is occurring
Extracting resources that contains the "All" parameter fails. Example AADGroup
#### Verbose logs showing the problem
EventLog: A parameter cannot be found that matches parameter name 'All'.
#### Suggested solution to the issue
Set dependencies back to 1.11.1 because of the widely used "All" Paramater in the resorces
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.921.1

**Comment by andikrueger** [comment]
Looks like there is already an update for the Graph PowerShell Modules available. This Dependency update is included in #2317

**Comment by andikrueger** [comment]
Closed via #2317

https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.12.1
