### ISSUE TITLE
Update to .vscode/settings.json - AvoidUsingDoubleQuotesForConstantString

### ISSUE THREAD

**Issue by andikrueger** [microsoft/Microsoft365DSC#2326]
There is a new setting for PowerShell Formatting available, that is not configured so far. This setting has big impact on the code formatting within this project. All strings are going to be transformed from strings with double quotes to strings single quotes. This transformation happens as soon as a user has different setting configured within its environment compared to the settings.json for VSCode within the project.

```powershell
"powershell.codeFormatting.useConstantStrings": true
```

Further description and discussion can be found there:

        Good point. Looks like we need to implement this change within the .vscode settings. This was introduced with V 1.19.1 and targets the PSScriptAnalyzer Rule: https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/avoidusingdoublequotesforconstantstring?view=ps-modules

Prior to implementing this change, we need to consider the impact.

_Originally posted by @andikrueger in https://github.com/microsoft/Microsoft365DSC/issues/2306#issuecomment-1253765809_

**Comment by mlhickey** [comment]
Can ScriptAnalyzer.psd1 be updated to exclude PSAvoidUsingWriteHost (or convert all to Write-Output)?

**Comment by andikrueger** [comment]
Where are the write-host cmdLets used? It would be possible to exclude those on a per file basis.

**Comment by mlhickey** [comment]
It's used liberally in many of the core modules, e.g. 43 instances in M365DSCUtil, 30 in M365DSCReverse, etc. Only reason I considered is if we're looking at updating the workspace, why not ignore warnings that aren't currently actionable.

**Comment by andikrueger** [comment]
This would also effect all resources. Every export function has at least 2 “Write-Host” usages…

With Write-Output we would loose capabilities like

- NoNewLine
- ForegroundColor
- BackgroundColor


Feels like it would be a valid addition to ignore this warning.

**Comment by andikrueger** [comment]
We should stick with the Write-Host cmdLet in any instance, that we make use of output formatting. 

It would be grate to suppress the warnings in this instance with some justification:

https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/using-scriptanalyzer?view=ps-modules#suppressing-rules
