### ISSUE TITLE
Conditional access policies: bug with ExcludePlatforms

### ISSUE THREAD

**Issue by semangard** [microsoft/Microsoft365DSC#2337]
#### Details of the scenario you tried and the problem that is occurring
Hello,

It seems that the `ExcludePlatforms `property raises some issues:

```
# ExcludePlatforms                       = @("android", "iOS", "macOS", "linux");
# ExcludePlatforms                       = @("android");
ExcludePlatforms                         = @();
```
Only the last value (empty array) currently works.

#### Verbose logs showing the problem
```
PS C:\git\cyberforce\cloud-ms-365-dsc\tools> .\DeployAll.ps1
The server could not process the request because it is malformed or incorrect.
    + CategoryInfo          : InvalidOperation: ({ ConditionalAc...AccessPolicy1 }:) [], CimException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgIdentityConditionalAccessPolicy_UpdateExpanded
    + PSComputerName        : localhost

The PowerShell DSC resource '[AADConditionalAccessPolicy]CA11a' with SourceInfo 'C:\git\cyberforce\cloud-ms-365-dsc\config\aad\03-conditionalAccessPolicies\Config.ps1::250::9::AADConditionalAccessPolicy'
threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for
more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```
 AADConditionalAccessPolicy 'CA11a' {
            ApplicationEnforcedRestrictionsIsEnabled = $False;
            # BuiltInControls                          = @("mfa","compliantDevice");
            BuiltInControls                          = @("mfa");
            ClientAppTypes                           = @("all");
            CloudAppSecurityIsEnabled                = $False;
            CloudAppSecurityType                     = "";
            Credential                               = $CredsCredential;
            CustomAuthenticationFactors              = @();
            DeviceFilterRule                         = "";
            DisplayName                              = "TEST-DSC: CA11a - Requirements for priority accounts (allow)";
            Ensure                                   = $conditionalAccessPoliciesEnsure;
            ExcludeApplications                      = @();
            ExcludeDevices                           = @();
            ExcludeGroups                            = @($groupRescueUsersName);
            ExcludeLocations                         = @();
            # ExcludePlatforms                         = @($ExcludePlatformsWhenRequiringComplianceInReportingMode);
            # ExcludePlatforms                         = @("android", "iOS", "macOS", "linux");
            # ExcludePlatforms                         = @("android");
            ExcludePlatforms                         = @();
            ExcludeRoles                             = @();
            ExcludeUsers                             = @();
            GrantControlOperator                     = "AND";
            IncludeApplications                      = @("All");
            IncludeDevices                           = @();
            IncludeGroups                            = @($groupPriorityUsersName);
            IncludeLocations                         = @();
            IncludePlatforms                         = @();
            IncludeRoles                             = @();
            IncludeUserActions                       = @();
            IncludeUsers                             = @();
            PersistentBrowserIsEnabled               = $True;
            PersistentBrowserMode                    = "never";
            SignInFrequencyIsEnabled                 = $True;
            SignInFrequencyType                      = "hours";
            SignInFrequencyValue                     = 12;
            SignInRiskLevels                         = @();
            State                                    = $CAPoliciesState;
            UserRiskLevels                           = @();
        }
```

#### The operating system the target node is running
Office365

#### Version of the DSC module that was used ('dev' if using current dev branch)
```
PS C:\git\cyberforce\cloud-ms-365-dsc\tools> Get-Module Microsoft365DSC -ListAvailable | select ModuleBase, Version

ModuleBase                                                            Version
----------                                                            -------
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.921.1 1.22.921.1
```

**Comment by andikrueger** [comment]
Based on the current documentation these values should still be supported. Could you test to set this property manually by calling `Update-MgIdentityConditionalAccessPolicy`?


https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/update-mgidentityconditionalaccesspolicy?view=graph-powershell-1.0
```
[Platforms <IMicrosoftGraphConditionalAccessPlatforms>]: conditionalAccessPlatforms
[(Any) <Object>]: This indicates any property can be added to this object.
[ExcludePlatforms <String[]>]: Possible values are: android, iOS, windows, windowsPhone, macOS, linux, all, unknownFutureValue.
[IncludePlatforms <String[]>]: Possible values are: android, iOS, windows, windowsPhone, macOS, linux, all, unknownFutureValue.
```

**Comment by mlhickey** [comment]
I assume you were hand-editing the config file to add the ExcludePlatforms properties.  When you specify ExcludePlatforms via the portal, the default for IncludePlatforms  becomes "all" (or selected platform), sending a null entry is likely generating the error.

**Comment by andikrueger** [comment]
@semangard Could you check if you configuration is working fine by adding "all" to `IncludePlatforms`? Thanks @mlhickey for this insight!

**Comment by semangard** [comment]
Hi @andikrueger 

Not better : 

```
ExcludePlatforms                         = @("android", "iOS", "macOS", "linux");
IncludePlatforms                         = @("all");
```

does not work:

![image](https://user-images.githubusercontent.com/57065741/194724516-831dcdc9-3e64-4042-a011-2d4701526ad0.png)

**Comment by mlhickey** [comment]
I can replicate your original issue by supplying a null IncludePlatforms property and resolve by providing a correct value. Did you generate the configuration using Export-M365DSCConfiguration?  If not, it would be interesting to compare a generated configuration, i.e. use the portal to set the desired configuration and export.

**Comment by mlhickey** [comment]
I notice your configuration is also missing TenantId.  I'll fire up a test VM and add your configuration to my export.  Question - I see you're using a number of variables in your config: are you doing your own custom pre-processing or the file before compilation or are they only there for obfuscation purposes?

**Comment by mlhickey** [comment]
Curious - Using 1.22.1005.1 I was able to replicate your error with an empty entry and resolve by adding "All" using the following based on your initial config:
'        
AADConditionalAccessPolicy 57138c28-1e7a-4e5b-9f40-590a770b1df8
        {
            ApplicationEnforcedRestrictionsIsEnabled = $False;
            BuiltInControls                          = @("mfa");
            ClientAppTypes                           = @("all");
            CloudAppSecurityIsEnabled                = $False;
            CloudAppSecurityType                     = "";
            CustomAuthenticationFactors              = @();
            DeviceFilterRule                         = "";
            DisplayName                              = "TEST-DSC: CA11a - Requirements for priority accounts (allow)";
            Ensure                                   = "Present";
            ExcludeApplications                      = @();
            ExcludeDevices                           = @();
            ExcludeGroups                            = @("ExExcGroup");
            ExcludeLocations                         = @();
            ExcludePlatforms                         = @("android","iOS","macOS","linux");
            ExcludeRoles                             = @();
            ExcludeUsers                             = @();
            GrantControlOperator                     = "AND";
            Id                                       = "892c3d45-8230-459a-a948-ef2ce67a0556";
            IncludeApplications                      = @("All");
            IncludeDevices                           = @();
            IncludeGroups                            = @("ExIncGroup");
            IncludeLocations                         = @();
            IncludePlatforms                         = @("All");
            IncludeRoles                             = @();
            IncludeUserActions                       = @();
            IncludeUsers                             = @();
            Managedidentity                          = $True;
            PersistentBrowserIsEnabled               = $True;
            PersistentBrowserMode                    = "never";
            SignInFrequencyIsEnabled                 = $True;
            SignInFrequencyType                      = "hours";
            SignInFrequencyValue                     = 12;
            SignInRiskLevels                         = @();
            State                                    = "enabledForReportingButNotEnforced";
            TenantId                                 = $ConfigurationData.NonNodeData.TenantId;
            UserRiskLevels                           = @();
        }
'
I assume your preprocessing of private variables is completing correctly?

**Comment by andikrueger** [comment]
@mlhickey thank you for the support with this issue! 

@semangard please let us know, if the suggestions work. Please review the .mof file, if there are any issues with the „placeholders“ of yours.

**Comment by semangard** [comment]
@mlhickey : well, here is my last piece of code tested (in UPDATE MODE) and I think I understood my issue:

```
AADConditionalAccessPolicy '20a' {
            ApplicationEnforcedRestrictionsIsEnabled = $False;
            BuiltInControls                          = @("approvedApplication", "compliantApplication");
            ClientAppTypes                           = @("all");
            CloudAppSecurityIsEnabled                = $False;
            CloudAppSecurityType                     = "";
            Credential                               = $CredsCredential;
            CustomAuthenticationFactors              = @();
            DeviceFilterRule                         = "";
            DisplayName                              = $CAPoliciesPrefix + "CA20a - Requirements for O365 on mobiles";
            Ensure                                   = $CAPoliciesEnsure;
            ExcludeApplications                      = @();
            ExcludeDevices                           = @();
            ExcludeGroups                            = @($excludeGroups);
            ExcludeLocations                         = @();
            #------------------------
            # ExcludePlatforms                         = @();
            ExcludePlatforms                         = @("android", "iOS", "macOS", "linux");
            #------------------------
            ExcludeRoles                             = @();
            ExcludeUsers                             = @();
            GrantControlOperator                     = "AND";
            IncludeApplications                      = @("Office365");
            IncludeDevices                           = @();
            IncludeGroups                            = @();
            IncludeLocations                         = @();
            #------------------------
            # IncludePlatforms                         = @();
            IncludePlatforms                         = @("android", "iOS");
            # IncludePlatforms                         = @("all");
            #------------------------           
            IncludeRoles                             = @();
            IncludeUserActions                       = @();
            IncludeUsers                             = $includeUsersAllOrScoped
            PersistentBrowserIsEnabled               = $False;
            PersistentBrowserMode                    = "";
            SignInFrequencyIsEnabled                 = $False;
            SignInFrequencyType                      = "";
            SignInRiskLevels                         = @();
            State                                    = $CAPoliciesState;
            UserRiskLevels                           = @();
        }
```

As you can see I tested various combinations with _ExcludePlatforms_ and _IncludePlatforms_

=> Here are ONLY combinations which work:
``` ###
ExcludePlatforms                         = @();
IncludePlatforms                         = @();
```
``` ###
ExcludePlatforms                         = @();
IncludePlatforms                         = @("android", "iOS");
```
``` ###
ExcludePlatforms                         = @("android", "iOS", "macOS", "linux");
IncludePlatforms                         = @("android", "iOS");
```

=> MAM policies ( _BuiltInControls = @("approvedApplication"_) do not support includePlatforms = _"All"_ and support only devices _"android"_ and/or _"iOS"_.

==> SO, it would be great if the tool could raise for MAM policies an explicit error at the compilation:
-> If _IncludePlatforms_ are not compliant with MAM
-> If _ExcludePlatforms_ are not set to _@("android", "iOS", "macOS", "linux")_ when the CA state is _"enabledForReportingButNotEnforced"_


Note: I used variables just to factorize few things among conditional access policies and to easily switch the state from ON to OFF for ex

**Comment by mlhickey** [comment]
@semangard  - CA requires a paired set whenever doing include/exclude, it needs a defined universe from which to exclude hence the default of All if you do this via the portal.

**Comment by mlhickey** [comment]
@semangard - makes sense.  If you only specify the include set, exclude doesn't need to be evaluated.  If you specify exclude, CA needs to know what the working set is that items are being excluded from, hence the default of All if you do this via the portal.
