### ISSUE TITLE
AADTenantDetails: Can not set tenant details

### ISSUE THREAD

**Issue by mario-beeler** [microsoft/Microsoft365DSC#2340]
I tried to update the "technical contact" in "AADTenantDetails". So I exported the resource "AADTenantDetails" with application secret, which should work for AzureAD settings. The export works fine and I could also generate the MOF-Files with different ConfigurationData, so I could test the import on two different tenants. On both tenants we have the app registration with application secret with the following permissions:
![image](https://user-images.githubusercontent.com/113532428/192525968-3290b253-8270-4050-897e-0a9d79285a00.png)

So if the tenant is in desired starte, the configuration runs without an error. If it is not in desired state and should set the "TechnicalNotificationMails" I get the information "Cannot Set AzureAD Tenant Details":
![image](https://user-images.githubusercontent.com/113532428/192527068-23b9db05-004c-4e8e-965e-fd320debdece.png)

Do you know why I get this error? I checked with "Get-M365DSCCompiledPermissionList" to get the permissions which I set on the app registration.

Thank you for your help.

**Comment by mlhickey** [comment]
For perms validation you might try:

Connect-M365Tenant -Workload MicrosoftGraph {authentication parameters}
(Get-MgContext).Scopes

to see what effective perms the service is seeing.

**Comment by mario-beeler** [comment]
![image](https://user-images.githubusercontent.com/113532428/192548814-7a3f4fc3-f886-4e34-ae14-22a68cf2c2bf.png)
As I see in picture, "Organization.ReadWrite.All" is missing. Is that the point, and do I have to set the permission on the App registration and on MgGraph?

**Comment by mlhickey** [comment]
Yes - that's the require perm for updates
![image](https://user-images.githubusercontent.com/20215068/192549672-484213cf-2426-4716-b161-e65e692e175c.png)

**Comment by mario-beeler** [comment]
So I updated the AllowedGraphScopes with "Update-M365DSCAllowedGraphScopes -ResourceNameList @('AADTenantDetails') -Type 'Update'" and then the Scopes are like that:
![image](https://user-images.githubusercontent.com/113532428/192551032-1725b7d1-3c17-4abb-8b3b-c68f45636d74.png)
(It is another tenant, thats why other permission than in Screenshot 1)

I have now "Organization.Read.All" and "Organization.ReadWrite.All" but still have the same error:
![image](https://user-images.githubusercontent.com/113532428/192551306-eb373545-9f35-467e-8fc5-393d1e587a1c.png)

**Comment by andikrueger** [comment]
Just had a look through the issue list and it looks like we had a similar issue with this resource #1799. There was another issue too, in regards to certificate based auth. 

I was able to use this resource recently using credentials. Could you check if this is possible for you as well?

**Comment by mario-beeler** [comment]
I tried it now using Credentials. The problem is, I just have Users configured with MFA which I can use to set this AADTenantDetail. When I tried now just to Test it, I get this error. But you see I checked the Graph Scopes:

![image](https://user-images.githubusercontent.com/113532428/192701987-68823ab5-deda-4d55-8bed-b4856ff18f5a.png)

Tried it again on two different Tenants and get the same error. But on both tenant I have just users with MFA.

**Comment by mario-beeler** [comment]
I first tried it with the credential authentication, worked:
![image](https://user-images.githubusercontent.com/113532428/192718742-6d4cda45-c46b-4fba-90ae-3c8a5724889b.png)

Then i tried it with the app authentication and set the TechnicalNotificationMails with Update-MgOrganization, also worked fine:
![image](https://user-images.githubusercontent.com/113532428/192721266-1c418581-a85f-4802-bf7a-2b5ddcd81a2c.png)

**Comment by andikrueger** [comment]
This is interesting and now even more complex to figure out, what causes the issue. 
would you be able to run the configuration again ad check if it is working now too?

**Comment by mario-beeler** [comment]
I tried it. I disconnected graph, and connected it again with using the app authentication, exactly the same like I tested with "Update-MgOrganization". After export and test the configuration I started the DSCConfiguration but still have the same error.

![image](https://user-images.githubusercontent.com/113532428/192728888-1d6b09bc-1a4c-40f0-8524-c737df624296.png)

**Comment by andikrueger** [comment]
This very unfortunate. Did you close the PowerShell Session or reused to prior one?

**Comment by mario-beeler** [comment]
The only difference: Connect-MgGraph is with ID of TenantID and Export-M365DSCConfiguration is with FQDN of TenantID.

I reused the same Session where I was trying with Update-MgOrganization, before that I closed it. I can retry it with a complete new session.

**Comment by mario-beeler** [comment]
I have now done a completly new PowerShell Session, used FQDN of TenantID to Connect-MgGraph with AppSecret and tried it again. It is still the same.

M365DSC is very new for me, not to be ruled out that I missed something. But I rechecked the configuration many times, thats why I came here. So thank you for your Inputs!

**Comment by andikrueger** [comment]
Did you grant admin consent for the app's permissions within the other tenants?

**Comment by mario-beeler** [comment]
Yes I have a app registration with both Permissions, Organization.Read.All and Organization.ReadWrite.All and grant admin consent on both tenants.

**Comment by andikrueger** [comment]
Could you please modify this line and add `$_` to the End of the message I add a new line for the detailed error. 

The file is located within your PowerShell modules folder, Microsoft365DSC,…

https://github.com/microsoft/Microsoft365DSC/blob/7a8192e3cc7a3d79546059aa47d6964fb8ddd149/Modules/Microsoft365DSC/DSCResources/MSFT_AADTenantDetails/MSFT_AADTenantDetails.psm1#L222

this should help to better understand the issue. 

The test method succeeds and for this part authentication is working fine.

**Comment by mario-beeler** [comment]
I tried this:
![image](https://user-images.githubusercontent.com/113532428/193028473-39c7aa52-35be-4f1e-8755-eccbd7e24a84.png)

**Comment by andikrueger** [comment]
Thanks for the screenshot. This clears it up. There is an issue with the parameter application secret. 

Will look into it.

**Comment by mario-beeler** [comment]
Thank you very much andikrueger! I will be away from computer the next days, so I will be online again on monday.
