### ISSUE TITLE
Assert-M365DSCBlueprint: export to json and switch to open browser after run

### ISSUE THREAD

**Issue by yeti1305group** [microsoft/Microsoft365DSC#2345]
### Description
I would like to use Microsoft 365 DSC in Azure Automation for reporting on deviations. Is it possible to incorporate 2 additional features:

- option to export the result to json instead of html
- have a switch to open browser with result. In Azure Automation I would like to switch of opening the file after running the command.

### Proposed properties

- option to export the result to json instead of html
- have a switch to open browser with result. In Azure Automation I would like to switch of opening the file after running the command.

**Comment by andikrueger** [comment]
The json switch sounds interesting.

Could you elaborate a bit more about the switch and the use case? AFAIK, Opening something from within Azure Automation is not possible.

**Comment by yeti1305group** [comment]
> The json switch sounds interesting.
> 
> Could you elaborate a bit more about the switch and the use case? AFAIK, Opening something from within Azure Automation is not possible.

Some additional information about our case.

**JSON export:**
We are trying to setup TSCM with M365DSC first before complete DSC. Working with JSON is easier when passing data between services and also easier to retrieve the relevant data. For the assert, but also for the compare it would be helpful to only export the relevant changes without all the HTML layout.

**Opening HTML after Assert:**
At this moment after the assert the HTML file is opened automatically. When running the assert in Azure Automation this gives an error (which of course can be suppressed). It would be nice when there is a switch like LaunchWebUI in the Export cmdlet.
![afbeelding](https://user-images.githubusercontent.com/114399219/192789429-03450f19-5115-43f1-b6f4-ebd46988c1aa.png)

This is a highlevel overview what we want to accomplish.
![afbeelding](https://user-images.githubusercontent.com/114399219/192787648-26ee1f1e-b318-462d-8b0c-a6c911bb1a12.png)

**Comment by yeti1305group** [comment]
Thanks for your quick reply!
Would be great to have this switch and hopefully the json export is also something which is not to complicated. Now I'm looking into a (hopefully temporary) workaroud to strip the html in a runbook or Logic App.

**Comment by NikCharlebois** [comment]
Changed the default behavior not to open the files by default. This is to align it with the New-M365DSCReportFromConfiguration cmdlet. Also added the -Type switch to Assert-M365DSCBlueprint and New-M365DSCDeltaReport to support specifying HTML or JSON

**Comment by yeti1305group** [comment]
Thanks for the quick action. Works great!
