### ISSUE TITLE
Odd behavior with AADAuthorizationPolicy in Azure Automation DSC environment

### ISSUE THREAD

**Issue by mlhickey** [microsoft/Microsoft365DSC#2346]
#### Details of the scenario you tried and the problem that is occurring
Dedicated VMs are configured via Azure Automation DSC, DSCLocalConfigurationManager setting:

![dsclocalconfig](https://user-images.githubusercontent.com/20215068/192801120-19925ebe-70a5-4277-9a3e-614e79518cc3.jpg)

All resources function, but the AADAuthorizationPolicy is yielding odd behavior.  It executes correctly on the 15, but incorrectly shows non-compliant on the 30:

![DSC-Automation-View](https://user-images.githubusercontent.com/20215068/192801398-3f2010bc-b033-4929-ade9-c9927f1367aa.jpg)

Looking at the ConfigStatus logs shows that execution on the 30 results in a null entry for PermissionGrantPolicyIdsAssignedToDefaultUserRole.  Below are log excerpts showing the success/failure
#### Verbose logs showing the problem
(remove the normal three asterisks used for blanking to avoid annoying bolding)

Success:

{"time": "2022-09-28T13:46:16.039+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [] Starting consistency engine."},
{"time": "2022-09-28T13:46:16.476+00:00", "type": "verbose", "message": "[DSC-BLD-01]: LCM:  [ Start  Resource ]  [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1]  "},
{"time": "2022-09-28T13:46:16.476+00:00", "type": "verbose", "message": "[DSC-BLD-01]: LCM:  [ Start  Test     ]  [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1]  "},
{"time": "2022-09-28T13:46:16.476+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] Testing configuration of AzureAD Authorization Policy"},
{"time": "2022-09-28T13:46:16.476+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] Getting configuration of AzureAD Authorization Policy"},
{"time": "2022-09-28T13:46:16.914+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] Get-TargetResource: Found existing authorization policy"},
{"time": "2022-09-28T13:46:16.929+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] \tRoleName matching GuestUserRoleId is Guest"},
{"time": "2022-09-28T13:46:16.929+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] return Guest"},
{"time": "2022-09-28T13:46:16.929+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] Get-TargetResource Result: \n AllowedToSignUpEmailBasedSubscriptions=True; AllowedToUseSSPR=True; AllowEmailVerifiedUsersToJoinOrganization=True; AllowInvitesFrom=adminsAndGuestInviters; ApplicationId=*; ApplicationSecret=*; BlockMsolPowerShell=False; CertificateThumbprint=; Credential=$null; DefaultUserRoleAllowedToCreateApps=True; DefaultUserRoleAllowedToCreateSecurityGroups=True; DefaultUserRoleAllowedToReadOtherUsers=True; Description=Used to manage authorization related settings across the company.; DisplayName=Authorization Policy; Ensure=Present; GuestUserRole=Guest; IsSingleInstance=Yes; Managedidentity=True; PermissionGrantPolicyIdsAssignedToDefaultUserRole=(); TenantId=*"}
{"time": "2022-09-28T13:46:16.929+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] Target Values: AllowedToSignUpEmailBasedSubscriptions=True; AllowedToUseSSPR=True; AllowEmailVerifiedUsersToJoinOrganization=True; AllowInvitesFrom=AdminsAndGuestInviters; BlockMsolPowerShell=False; DefaultUserRoleAllowedToCreateApps=True; DefaultUserRoleAllowedToCreateSecurityGroups=True; DefaultUserRoleAllowedToReadOtherUsers=True; Description=Used to manage authorization related settings across the company.; DisplayName=Authorization Policy; Ensure=Present; GuestUserRole=Guest; IsSingleInstance=Yes; ManagedIdentity=True; **PermissionGrantPolicyIdsAssignedToDefaultUserRole=()**; TenantId=*; Verbose=True"}
{"time": "2022-09-28T13:46:17.007+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] Test-TargetResource returned True"},
{"time": "2022-09-28T13:46:17.007+00:00", "type": "verbose", "message": "[DSC-BLD-01]: LCM:  [ End    Test     ]  [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] True in 0.5310 seconds."},
{"time": "2022-09-28T13:46:17.007+00:00", "type": "verbose", "message": "[DSC-BLD-01]: LCM:  [ End    Resource ]  [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1]  "},

Failure:

{"time": "2022-09-28T13:39:22.488+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [] Executing Get-Action with configuration (null)'s checksum: 4C65C83C0EDD27FF3351D4ADCA7C2EB1E3FCFEF5E5C607073EF6790A536A9473."},
{"time": "2022-09-28T13:39:22.550+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [] Executing Get-Action with configuration 's checksum returned result status: Ok."},
{"time": "2022-09-28T13:39:22.550+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [] Updated configuration not found on pull server so no action taken. Ensure that a configuration with a different checksum exists on the pull server for target node."},
{"time": "2022-09-28T13:39:22.566+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [] Starting consistency engine."},
{"time": "2022-09-28T13:39:23.003+00:00", "type": "verbose", "message": "[DSC-BLD-01]: LCM:  [ Start  Resource ]  [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1]  "},
{"time": "2022-09-28T13:39:23.003+00:00", "type": "verbose", "message": "[DSC-BLD-01]: LCM:  [ Start  Test     ]  [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1]  "},
{"time": "2022-09-28T13:39:23.019+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] Testing configuration of AzureAD Authorization Policy"},
{"time": "2022-09-28T13:39:23.019+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] Getting configuration of AzureAD Authorization Policy"},
{"time": "2022-09-28T13:39:23.613+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] Get-TargetResource: Found existing authorization policy"},
{"time": "2022-09-28T13:39:23.644+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] \tRoleName matching GuestUserRoleId is Guest"},
{"time": "2022-09-28T13:39:23.644+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] return Guest"},
{"time": "2022-09-28T13:39:23.644+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] Get-TargetResource Result: \n AllowedToSignUpEmailBasedSubscriptions=True; AllowedToUseSSPR=True; AllowEmailVerifiedUsersToJoinOrganization=True; AllowInvitesFrom=adminsAndGuestInviters; ApplicationId=*; ApplicationSecret=*; BlockMsolPowerShell=False; CertificateThumbprint=; Credential=$null; DefaultUserRoleAllowedToCreateApps=True; DefaultUserRoleAllowedToCreateSecurityGroups=True; DefaultUserRoleAllowedToReadOtherUsers=True; Description=Used to manage authorization related settings across the company.; DisplayName=Authorization Policy; Ensure=Present; GuestUserRole=Guest; IsSingleInstance=Yes; Managedidentity=True; **PermissionGrantPolicyIdsAssignedToDefaultUserRole=$null;** TenantId=*"}
{"time": "2022-09-28T13:39:23.644+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] Target Values: AllowedToSignUpEmailBasedSubscriptions=True; AllowedToUseSSPR=True; AllowEmailVerifiedUsersToJoinOrganization=True; AllowInvitesFrom=AdminsAndGuestInviters; BlockMsolPowerShell=False; DefaultUserRoleAllowedToCreateApps=True; DefaultUserRoleAllowedToCreateSecurityGroups=True; DefaultUserRoleAllowedToReadOtherUsers=True; Description=Used to manage authorization related settings across the company.; DisplayName=Authorization Policy; Ensure=Present; GuestUserRole=Guest; IsSingleInstance=Yes; ManagedIdentity=True; PermissionGrantPolicyIdsAssignedToDefaultUserRole=(); TenantId=*; Verbose=True"}
{"time": "2022-09-28T13:39:23.878+00:00", "type": "verbose", "message": "[DSC-BLD-01]:                            [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] Test-TargetResource returned False"},
{"time": "2022-09-28T13:39:23.878+00:00", "type": "verbose", "message": "[DSC-BLD-01]: LCM:  [ End    Test     ]  [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1] False in 0.8750 seconds."},
{"time": "2022-09-28T13:39:23.878+00:00", "type": "verbose", "message": "[DSC-BLD-01]: LCM:  [ End    Resource ]  [[AADAuthorizationPolicy]94bd0cf2-db65-46fa-afb8-83584d4a2ca1]  "},
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2022 Datacenter Azure Edition
OsOperatingSystemSKU : 407
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.1.amd64fre.fe_release.210507-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev - 1.22.921.1

**Comment by andikrueger** [comment]
Please check the parameter within the configuration: PermissionGrantPolicyIdsAssignedToDefaultUserRole should be @() or $null. At the moment the target values shows ().

**Comment by mlhickey** [comment]
Additionally, this is not an issue in 1.22.914.1

**Comment by mlhickey** [comment]
This is true whether the property is an empty array or populated.  This does not appear to be an issue in 1.22.914.1

**Comment by andikrueger** [comment]
Would it be possible to update the other tenants to the latest version too?

**Comment by mlhickey** [comment]
The two running 921 are dev & pre-prod. The one running 914 is prod so I'm hesitant to potentially break that one.

**Comment by mlhickey** [comment]
Results from testing.

Created new VM in test tenant, assigned **only** authorizationpolicy (AP) - pass
Add additional resource to new VM configuration - fail
Returned configuration to **only** AP - pass

The pattern I'm seeing from the MOF files in ConfigurationStats, reflected in reporting blade, is order of execution - successful runs have AP as **first**, failed runs have AP as **last**

Success:
![success](https://user-images.githubusercontent.com/20215068/193055284-9b3a8488-a629-4ca9-9237-585a7e4e6607.jpg)

Failure:
![failure](https://user-images.githubusercontent.com/20215068/193055335-bc16b252-9382-4500-a484-2ade1857c5b3.jpg)

**Comment by mlhickey** [comment]
Playing around with new VM.  If AADAuthorizationPolicy is the **only** entry in the configuration there are no issues.  Have a couple profiles working now for positional results - first/middle/last entry in configuration.  Final will be based on configuration size with multiple resrouces, i.e.
$managedResources = @(
    'AADAuthorizationPolicy'
    'AADConditionalAccessPolicy'
    'AADGroupLifecyclePolicy'
    'AADGroupsNamingPolicy'
    'AADGroupsSettings'
    'AADNamedLocationPolicy'
    'AADSecurityDefaults'
    'AADTokenLifetimePolicy'
    'AADRoleSetting'
)

**Comment by andikrueger** [comment]
What is your solution in the end?

**Comment by mlhickey** [comment]
Spent 5 hours working through variants and it just stopped failing with no real or config changes, just shuffling things around within the configuration file.    Since I'm unable to repro I have no path forward so closing for now.
