### ISSUE TITLE
ExoManagementRoleAssignment property 'SecurityGroup' and 'Role' is not supported

### ISSUE THREAD

**Issue by atdheekurteshi** [microsoft/Microsoft365DSC#2355]
ISSUE TITLE:
 
**ExoManagementRoleAssignment** property '**SecurityGroup**' and '**Role**' is not supported

ISSUE DESCRIPTION (this template):

**ExoManagementRoleAssignment**:
Property **'SecurityGroup'** and **'Role'** should be added in class **ExoManagementRoleAssignment**

On class **ExoManagementRoleAssignment** property **'SecurityGroup'** and **'Role'**  is momentary not supported could you add it as a new property.

#### Suggested solution to the issue

**Comment by NikCharlebois** [comment]
Link #2356
