### ISSUE TITLE
Customizing the Microsoft0365DSC tool

### ISSUE THREAD

**Issue by Chabango** [microsoft/Microsoft365DSC#2364]
Has anyone customized the Microsoft0365DSC tool? Is it possible to take the source file and customize it to our needs? If so, woudl i just use the source files from GitHub?
Thank you

**Comment by ykuijs** [comment]
Hi @Chabango, you can always create your own fork of this repository and implement your changes there. 

However, it is very much appreciated if you then submit a pull request to share the things you added back to this repository so we can all benefit from your work :wink:
