### ISSUE TITLE
Delta report is not comparing accurately

### ISSUE THREAD

**Issue by nathanpinotti** [microsoft/Microsoft365DSC#2368]
#### Details of the scenario you tried and the problem that is occurring

I'm testing the comparing configuration resource but it seems to be not working.

I've got a initial snapshot from my tenant test, did some change on it (fyi: change group settings and add  remote-domain on EXO) and took another snapshot. 

Using the cmdlet New-M365DeltaReport should point me this changes but, instead, it shows me configurations that were not modified.

#### Verbose logs showing the problem

Source RemoteDomain config:

`EXORemoteDomain 76e3160c-746f-4440-90b1-fb231ef1c45f
        {
            AllowedOOFType                       = "External";
            AutoForwardEnabled                   = $True;
            AutoReplyEnabled                     = $True;
            ByteEncoderTypeFor7BitCharsets       = "Undefined";
            CharacterSet                         = "iso-8859-1";
            ContentType                          = "MimeHtmlText";
            Credential                           = $Credscredential;
            DeliveryReportEnabled                = $True;
            DisplaySenderName                    = $True;
            DomainName                           = "*";
            Ensure                               = "Present";
            Identity                             = "Default";
            IsInternal                           = $False;
            LineWrapSize                         = "Unlimited";
            MeetingForwardNotificationEnabled    = $False;
            Name                                 = "Default";
            NonMimeCharacterSet                  = "iso-8859-1";
            PreferredInternetCodePageForShiftJis = "Undefined";
            TargetDeliveryDomain                 = $False;
            TrustedMailInboundEnabled            = $False;
            TrustedMailOutboundEnabled           = $False;
            UseSimpleDisplayName                 = $False;`

**"Destination" (new config);**

`       EXORemoteDomain 51e656fa-f6e8-4f68-a74c-ca17a444ab4d
        {
            AllowedOOFType                       = "External";
            AutoForwardEnabled                   = $True;
            AutoReplyEnabled                     = $True;
            ByteEncoderTypeFor7BitCharsets       = "Undefined";
            CharacterSet                         = "";
            ContentType                          = "MimeHtmlText";
            Credential                           = $Credscredential;
            DeliveryReportEnabled                = $True;
            DisplaySenderName                    = $True;
            DomainName                           = "newdomaindsc.com";
            Ensure                               = "Present";
            Identity                             = "RemoteDomain-DSC";
            IsInternal                           = $False;
            LineWrapSize                         = "Unlimited";
            MeetingForwardNotificationEnabled    = $False;
            Name                                 = "RemoteDomain-DSC";
            NonMimeCharacterSet                  = "";
            PreferredInternetCodePageForShiftJis = "Undefined";
            TargetDeliveryDomain                 = $False;
            TrustedMailInboundEnabled            = $False;
            TrustedMailOutboundEnabled           = $False;
            UseSimpleDisplayName                 = $False;
        }`

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
# insert configuration here
Export-M365DSCConfiguration -Components @("AADApplication", "AADAuthorizationPolicy", "AADConditionalAccessPolicy", "AADGroupLifecyclePolicy", "AADGroupsNamingPolicy", "AADGroupsSettings", "AADNamedLocationPolicy", "AADRoleDefinition", "AADRoleSetting", "AADTenantDetails", "AADTokenLifetimePolicy", "EXOAcceptedDomain", "EXOActiveSyncDeviceAccessRule", "EXOAddressBookPolicy", "EXOAddressList", "EXOAntiPhishPolicy", "EXOAntiPhishRule", "EXOApplicationAccessPolicy", "EXOAtpPolicyForO365", "EXOAuthenticationPolicy", "EXOAuthenticationPolicyAssignment", "EXOAvailabilityAddressSpace", "EXOAvailabilityConfig", "EXOCASMailboxPlan", "EXOCASMailboxSettings", "EXOClientAccessRule", "EXODataClassification", "EXODataEncryptionPolicy", "EXODkimSigningConfig", "EXOEmailAddressPolicy", "EXOHostedConnectionFilterPolicy", "EXOHostedContentFilterPolicy", "EXOHostedContentFilterRule", "EXOHostedOutboundSpamFilterPolicy", "EXOHostedOutboundSpamFilterRule", "EXOInboundConnector", "EXOIntraOrganizationConnector", "EXOIRMConfiguration", "EXOJournalRule", "EXOMailboxPlan", "EXOMailTips", "EXOMalwareFilterPolicy", "EXOMalwareFilterRule", "EXOMessageClassification", "EXOMobileDeviceMailboxPolicy", "EXOOfflineAddressBook", "EXOOMEConfiguration", "EXOOnPremisesOrganization", "EXOOrganizationConfig", "EXOOrganizationRelationship", "EXOOutboundConnector", "EXOOwaMailboxPolicy", "EXOPartnerApplication", "EXOPerimeterConfiguration", "EXOPolicyTipConfig", "EXOQuarantinePolicy", "EXORemoteDomain", "EXOResourceConfiguration", "EXORoleAssignmentPolicy", "EXOSafeAttachmentPolicy", "EXOSafeAttachmentRule", "EXOSafeLinksPolicy", "EXOSafeLinksRule", "EXOSharingPolicy", "EXOTransportConfig", "EXOTransportRule", "O365AdminAuditLogConfig", "O365OrgCustomizationSetting", "SCAuditConfigurationPolicy", "SCAutoSensitivityLabelPolicy", "SCAutoSensitivityLabelRule", "SCCaseHoldPolicy", "SCCaseHoldRule", "SCComplianceCase", "SCComplianceSearch", "SCComplianceSearchAction", "SCComplianceTag", "SCDeviceConditionalAccessPolicy", "SCDeviceConfigurationPolicy", "SCDLPCompliancePolicy", "SCDLPComplianceRule", "SCFilePlanPropertyAuthority", "SCFilePlanPropertyCategory", "SCFilePlanPropertyCitation", "SCFilePlanPropertyDepartment", "SCFilePlanPropertyReferenceId", "SCFilePlanPropertySubCategory", "SCLabelPolicy", "SCRetentionCompliancePolicy", "SCRetentionComplianceRule", "SCRetentionEventType", "SCSensitivityLabel", "SCSupervisoryReviewPolicy", "SCSupervisoryReviewRule", "TeamsCallingPolicy", "TeamsChannel", "TeamsChannelsPolicy", "TeamsClientConfiguration", "TeamsEmergencyCallingPolicy", "TeamsEmergencyCallRoutingPolicy", "TeamsEventsPolicy", "TeamsFederationConfiguration", "TeamsGuestCallingConfiguration", "TeamsGuestMeetingConfiguration", "TeamsGuestMessagingConfiguration", "TeamsMeetingBroadcastConfiguration", "TeamsMeetingBroadcastPolicy", "TeamsMeetingConfiguration", "TeamsMeetingPolicy", "TeamsMessagingPolicy", "TeamsPstnUsage", "TeamsTenantDialPlan", "TeamsUpdateManagementPolicy", "TeamsUpgradeConfiguration", "TeamsUpgradePolicy", "TeamsVoiceRoute", "TeamsVoiceRoutingPolicy") -Credential $Credential -Path c:\temps\dsc

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

**Comment by andikrueger** [comment]
Could you elaborate a bit more on this issue. The two configs above are differently. Do they not come up as different?

**Comment by nathanpinotti** [comment]
> Could you elaborate a bit more on this issue. The two configs above are differently. Do they not come up as different?

Exactly. When I run the delta report I don't get this config listed in the report. Instead of that the html file shows me some Security configurations that I didn't touch.

**Comment by andikrueger** [comment]
Just had another look at the resource settings. 

The first one defines `Identity = "Default"` where as the second one defines `Identity = "RemoteDomain-DSC"`. Basically these are two different configurations. `Identity` must be identical so that the delta report would pick up changes.

**Comment by nathanpinotti** [comment]
Andi, thanks for you answer!
These code I got from the two .ps1 files generated by the 365MSC.

**First Snapshot** = 0310.ps1
**SecondSnapshot** = M365TenantConfig.ps1

**Query**: If the "Identity" is the same, we wouldn't have a change, it's going to be the same configuration.

The "issue" I found is that.

0310.ps1 = RemoteDomain Exchange was the default One.
M365TenantConfig.ps1 = RemoteDomain Exchange added like "RemoteDomain-DSC".

The Delta report should show me this difference, right? Is there any limitation because of the amount of configuration selected?

I'll try to generate the reports by Workload (One for EXO; One for Teams).

**Comment by andikrueger** [comment]
You should be able to see the difference between two configurations. 
For changes within a resource (same key property) it should outline the changes within the object. 

In your case (change of key property) it should show, that a new resource is found. 

Please try to change the paths for Source and Destination parameters for New-M365DSCDeltaReport. 

Please share your finding.

**Comment by nathanpinotti** [comment]
Hi andi.
Did another test with no success. 

1. Took a new snapshot
2. Included a Transport Rule on Exchange Online
3. Took another snapshot
4. Compared them using New-M365DSCDeltaReport
5. Result = No discrepancies have been found!

Is there any suggestion to make it work. Or, the configs I've been testing are no supported in the DeltaReport?

**Comment by andikrueger** [comment]
We aim to support all configurations and provide proper comparisons of those. Could you share both configs for our testing?

**Comment by nathanpinotti** [comment]
Search for EXOTransportConfig

**Source**
https://pastebin.com/FNA4jQqm

**Dest**
https://pastebin.com/v2Ky9qUj

**Comment by andikrueger** [comment]
I do get 403 errors with the paste bin links. You can drag files into the comment area of this issue. This way we should be able to obtain them.

**Comment by andikrueger** [comment]
Could you update to the latest version of M365DSC? There was an issue with DSC Parser that could have caused your issue.

**Comment by Chabango** [comment]
I am also seeing an issue with New-M365DSCDeltaReport.
Running: 
`New-M365DSCDeltaReport -source C:\test\Microsoft365DSC\EXOTransportRule -Destination C:\test\Microsoft365DSC\EXOTransportRule2 -OutputPath C:\test\Microsoft365DSC\TransportRule-DeltaConfig.html`

The Source file snip it:

`        EXOTransportRule 40f8f1a4-a9f4-426a-b616-b30e5986d891
        {
            ApplyOME                                  = $False;
            ApplyRightsProtectionTemplate             = "**Do Not Forward**";
            AttachmentHasExecutableContent            = $False;
            AttachmentIsPasswordProtected             = $False;
            AttachmentIsUnsupported                   = $False;
            AttachmentProcessingLimitExceeded         = $False;
            Comments                                  = "Testing applying encryption to emails from a particular mailbox. Testing for sending client secrets in automated email.
";
            Credential                                = $Credscredential;
            DeleteMessage                             = $False;
            Ensure                                    = "Present";
            ExceptIfAttachmentHasExecutableContent    = $False;
            ExceptIfAttachmentIsPasswordProtected     = $False;
            ExceptIfAttachmentIsUnsupported           = $False;
            ExceptIfAttachmentProcessingLimitExceeded = $False;
            ExceptIfHasNoClassification               = $False;
            ExceptIfHasSenderOverride                 = $False;
            From                                      = @("MailboxTest13@XXX.YYY.gov","User1@XXX.YYY.gov");
            HasNoClassification                       = $False;
            HasSenderOverride                         = $False;
            Managedidentity                           = $False;
            Mode                                      = "Enforce";
            ModerateMessageByManager                  = $False;
            Name                                      = "**Test - Mail Encrypt**";  
            Priority                                  = 16;
            RemoveOME                                 = $False;
            RemoveOMEv2                               = $False;
            RouteMessageOutboundRequireTls            = $False;
            RuleErrorAction                           = "Ignore";
            RuleSubType                               = "None";
            SenderAddressLocation                     = "Header";
            SetAuditSeverity                          = "DoNotAudit";
            StopRuleProcessing                        = $False;
        }`

The Destination file with changes:

`       EXOTransportRule 40f8f1a4-a9f4-426a-b616-b30e5986d891
        {
            ApplyOME                                  = $False;
            ApplyRightsProtectionTemplate             = "**Encrypt**";   **<-- THIS Changed**
            AttachmentHasExecutableContent            = $False;
            AttachmentIsPasswordProtected             = $False;
            AttachmentIsUnsupported                   = $False;
            AttachmentProcessingLimitExceeded         = $False;
            Comments                                  = "Testing applying encryption to emails from a particular mailbox. Testing for sending client secrets in automated email.
";
            Credential                                = $Credscredential;
            DeleteMessage                             = $False;
            Ensure                                    = "Present";
            ExceptIfAttachmentHasExecutableContent    = $False;
            ExceptIfAttachmentIsPasswordProtected     = $False;
            ExceptIfAttachmentIsUnsupported           = $False;
            ExceptIfAttachmentProcessingLimitExceeded = $False;
            ExceptIfHasNoClassification               = $False;
            ExceptIfHasSenderOverride                 = $False;
            From                                      = @("MailboxTest13@XXX.YYY.gov","User1@XXX.yyy.gov");
            HasNoClassification                       = $False;
            HasSenderOverride                         = $False;
            Managedidentity                           = $False;
            Mode                                      = "Enforce";
            ModerateMessageByManager                  = $False;
            Name                                      = "Mail Encrypt";  <**-- This Changed**
            Priority                                  = 16;
            RemoveOME                                 = $False;
            RemoveOMEv2                               = $False;
            RouteMessageOutboundRequireTls            = $False;
            RuleErrorAction                           = "Ignore";
            RuleSubType                               = "None";
            SenderAddressLocation                     = "Header";
            SetAuditSeverity                          = "DoNotAudit";
            StopRuleProcessing                        = $False;
        }`

When reviewing the Delta COnfig HTML, I can see that it does see the name change form Test - Mail Encrypt to Mail Encrypt, but it does not list the change in the ApplyRightsProtectionTemplate form Do Not forward to Encrypt.

**Comment by Chabango** [comment]
![Delta](https://user-images.githubusercontent.com/100866228/197001110-5d15638f-cf88-422d-9d59-067046c4221f.png)

**Comment by andikrueger** [comment]
Just did some testing and changed the name of the resource to be equal to the first one:

![image](https://user-images.githubusercontent.com/15608729/197139861-094c0e5e-6a57-4428-b3e0-f8b5931bbed8.png)

**Comment by Chabango** [comment]
Hi Andi, How did you repro that? I re-ran on my end and am still getting the same results. It is not showing the ApplyRightsProtectionTemplate change.

**Comment by andikrueger** [comment]
You named your resources differently. The key element differs. Please try to use the two attached files of mine.

**Comment by Chabango** [comment]
I re-ran and kept the name the same and it does now report the ApplyRightsProtectionTemplate change. So if the name changes, it will capture the name change, but it does not report any other changes in that configuration? What do you do in the situation where the name does change and a configuration within that changes as well like my original situation?

**Comment by Chabango** [comment]
Makes sense. thank you.
