### ISSUE TITLE
Dependencies need updating solved by downgrading 

### ISSUE THREAD

**Issue by Aldriss** [microsoft/Microsoft365DSC#2369]
In my context i'm not admin of my workstation, and i need to install all powershell module in the Scope "CurrentUser", so i download/install module from powershell galery.

May you add a parameter scope to  **Update-M365DSCDependencies -scope user** ?

Actually the last MSCloudLoginAssistant version is 1.0.94
i installed this version, and i couldnt run m365dsc anymore with the error message : 

```powershell
The following dependencies need updating:
    * MSCloudLoginAssistant
Please run Update-M365DSCDependencies.
Au caractère C:\Users\XXXXXX\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.22.921.1\modules\M365DSCUtil.psm1:1274 : 13
+             throw $ErrorMessage
+             ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The following d...SCDependencies.:String) [], RuntimeException
    + FullyQualifiedErrorId : The following dependencies need updating:
    * MSCloudLoginAssistant
Please run Update-M365DSCDependencies.
```

i ran :  **Uninstall-M365DSCOutdatedDependencies** for avoid any problem and MSCloudLoginAssistant ("1.0.94") got removed 

i found the RequiredVersion for MSCloudLoginAssistant ("1.0.89")  in the \dependencies\Manifest.psd1 and after installation, it works. 

So I solved my Issue by downgrading the MSCloudLoginAssistant version, funny  :)
Maybe the error message could be more explicit ? 
**Uninstall-M365DSCOutdatedDependencies** shouldn't unistall newer version

Regards

**Comment by andikrueger** [comment]
We are aware of this issue. DSC relies on the modules being installed as administrator. In cases that you just want to export configurations, this is not always possible.

You can install the dependencies manually by changing this function:

https://github.com/microsoft/Microsoft365DSC/blob/6b086f6d22e1f95a662336ee2932e885d85324a7/Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1#L2573-L2616
