### ISSUE TITLE
Start-M365DSCConfigurationExtract broken for Service Principal with thumbprint

### ISSUE THREAD

**Issue by ajkenah** [microsoft/Microsoft365DSC#2374]
#### Details of the scenario you tried and the problem that is occurring

In the latest version of the module (1.22.1005.1) when running the Export-M365DSCConfiguration function with an Application ID and Certificate Thumbprint it fails.

I've chased the issue to a section of code in the "Start-M365DSCConfigurationExtract" function.
On line 231 (Get Tenant Info) the function calls the "Get-M365DSCTenantDomain" function **without specifying the $CertificateThumbprint or $ApplicationSecret variables.**

This function (Get-M365DSCTenantDomain) then attempts to create a connection to MSGraph, using the New-M365DSCConnection function and $PSBoundParameters parameters, but since the $CertificateThumbprint or $ApplicationSecret variables weren't defined the connection fails with "Could not determine authentication method"

#### Suggested solution to the issue
Add the $CertificateThumbprint and $ApplicationSecret variables to the "Get-M365DSCTenantDomain" command on line 237

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.1005.1

**Comment by zmart83** [comment]
Sorry, but it's still not fixed properly. Especially when exporting single components like 'O365SearchAndIntelligenceConfigurations' the authentication fails. The reason for this is that the authentication is checked in the Start-M365DSCConfigurationExtract function:

```
if (-not [System.String]::IsNullOrEmpty($CertificateThumbprint))
        {
            Write-Host -Object '- Service Principal with Certificate Thumbprint'
            $AuthMethods += 'CertificateThumbprint'
        }
```
Then the method 
```
Get-M365DSCComponentsWithMostSecureAuthenticationType -AuthenticationMethod $AuthMethods `
            -Resources $selectedResources 
```
is called.  In this case, the check is performed in this way:
```
if ($AuthenticationMethod.Contains('CertificateThumbprint') -and `
                    $parameters.Contains('ApplicationId') -and `
                    $parameters.Contains('CertificateThumbprint') -and `
                    $parameters.Contains('TenantId'))
```
However, this does not work, as only CertificateThumbprint is transferred from the previous method.
