### ISSUE TITLE
Feature Request: Entitlement Management

### ISSUE THREAD

**Issue by MatthewWhiteMoJ** [microsoft/Microsoft365DSC#2407]
### Description
Ability to template and manage Identity Governance packages so they can be checked off against blueprint and detect for modifications
#### Catalogs
 - name of catalog
 - list of resources available to be put into access packages
 - list of roles and administrator objects who can assign and review access in catalog
#### Access Packages
 - name of access package
 - Roles allocated and access levels
 - Policies assigned to the access package (ability to define policies and repeat their usage ++)
 - Separtion of duties (access package A is mutually exclusive from access package B)
#### External Organisations
 - External domain/tenant name
 - internal sponsors within home tenant
 - external sponsor in remote tenant
#### Core Settings
 - External user lifecycle

### Special considerations or limitations

Unsure about integration of objects that require object ids to be passed in or for configuration that can only be submitted at the time the code runs against the tenant?

**Comment by andikrueger** [comment]
Could you share some more details about the currently existing PowerShell modules or GraphAPi endpoints that could be used to provide these features?

**Comment by MatthewWhiteMoJ** [comment]
link to the Learn pages on Entitlement Management and MS Graph - https://learn.microsoft.com/en-us/graph/api/resources/entitlementmanagement-overview?view=graph-rest-1.0

link to MSGraph PS Module doing similar things with entitlement Management - https://learn.microsoft.com/en-us/powershell/microsoftgraph/tutorial-entitlement-management?view=graph-powershell-1.0

**Comment by andikrueger** [comment]
Thanks for the additional information. At the moment, M365DSC has no dependency on **Microsoft.Graph.Identity.Governance** This should be the first thing to add.

From a resource perspective, the creation should be possible by using the dynamic resource generator.

**Comment by William-Francillette** [comment]
There's a fair amount of work to cover everything within Entitlement Management but I'll be happy to start working on it
I will probably work on this order: general settings, catalog, access package, external orgs

**Comment by andikrueger** [comment]
@William-Francillette thanks for picking this up!

**Comment by MatthewWhiteMoJ** [comment]
Thanks - was going to start looking at DRG but very much starting out again looking at DSC and what may need to be done :)

**Comment by William-Francillette** [comment]
Quick update

Working on AADEntitlementManagementAccessPackageAssignmentPolicy

Issue with the Graph SDK module and some of the update commands:
Was told to not use Update-MgEntitlementManagementAccessPackageAssignmentPolicy  as it is/will be removed and replaced by Set-MgEntitlementManagementAccessPackageAssignmentPolicy 
but this later still have issues https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1683

Waiting for a fix (I don't want to use the REST API ) - hopefully soon

**Comment by William-Francillette** [comment]
I've just posted AADEntitlementManagementAccessPackageAssignmentPolicy and looking at the next step for the entitlement management feature:
I will be developing:
- AADEntitlementManagementConnectedOrganization
- AADEntitlementManagementAccessPackageCustomWorkflowExtension

@NikCharlebois @andikrueger @ykuijs What do you think about the access package assignments? Should I create a resource for those knowing that they may change overtime and not really a constant?

https://learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta
https://learn.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta

**Comment by NikCharlebois** [comment]
I would personally wait for thing to stabilize before releasing the resource.

**Comment by NikCharlebois** [comment]
@William-Francillette what would be needed to move forward with this? Thanks

**Comment by William-Francillette** [comment]
Yes that should be complete now - Connected Organization was the final one - Just updated the PR #2716 
AADEntitlementManagementAccessPackageCustomWorkflowExtension was not required as integrated to a previous PR (for the Access Package resource)
