### ISSUE TITLE
Delta Report ExoTransportRule - SenderDomainIs is ignored

### ISSUE THREAD

**Issue by AlMargoi** [microsoft/Microsoft365DSC#2410]
#### Details of the scenario you tried and the problem that is occurring: 
- I have implemented Microsoft365DSC quite some time ago, to monitor the changes performed against the EXO environment that I am administering. 
- I am having a reference blueprint export in a Git repo and each time a change is made, the new config of the environment is being exported and then compared with the blueprint, resulting in a Delta Report. 
- I noticed that if I edit a Transport Rules SenderDomainIs parameter, by adding/removing few more domains to/from the list, the Delta Report is not noticing these changes, even if the fresh config export that is being compared against the blueprint has those changes in it.

#### Verbose logs showing the problem
- Unable to share

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
- Unable to share

#### Version of the DSC module that was used ('dev' if using current dev branch)
- 1.22.511.1

**Comment by andikrueger** [comment]
Did you also remove the old modules during the update? Otherwise run Update-M365DSCModule

**Comment by NikCharlebois** [comment]
We are not able to replicate on our end. Has @andikrueger recommends, please make sure you also remove the old versions of the dependencies and try again.

**Comment by AlMargoi** [comment]
@andikrueger @NikCharlebois you were right. Yesterday I have updated the module but it was updated just for my local admin account. The account that was running the DSC Automation was still using the old version of the module. After properly updating the module, the Delta Report works as expected. Thank you very much for your quick help!
