### ISSUE TITLE
AADUser - Roles & Authentication info

### ISSUE THREAD

**Issue by MatthewWhiteMoJ** [microsoft/Microsoft365DSC#2411]
Started to use M365DSC to create user accounts for some admin tasks in a test tenant and noticed the following:

1. Whilst I can define Roles as a string array of roles these appear to be Active Assignments - in my tenant i would largely want the roles to be eligible and potentially timebound as part of some PIM elevation request - looking through the resources i couldnt work out where to set this
2. When creating the new users I prefer that the generic password is set and the users use the built in password reset functionality of AzureAD. I couldn't see an object in the AADUser definition that lets me set AuthenticationMethods against the user account so that SSPR is enabled and they pick a password only they know.

Link - AAD Authentication Method - https://learn.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0

**Comment by NikCharlebois** [comment]
Linking with #2887

**Comment by NikCharlebois** [comment]
Not sure how we could implement PIM as DSC. These would normally be one time operations for a specific time period. We don't want DSC to start treating these as drifts the moment the time period is over. I don't believe PIM is a good scenario for DSC unfortunately.

With regards to item #2, let's take the discussions over to #2887 instead

**Comment by NikCharlebois** [comment]
Closing since PIM resources have been released.
