### ISSUE TITLE
AADGroup: Only possible to create Dynamic and Unified Groups

### ISSUE THREAD

**Issue by afloca** [microsoft/Microsoft365DSC#2427]
#### Details of the scenario you tried and the problem that is occurring
With the current resource it is not possible to create (simple) Azure Security Groups because if the GroupTypes Parameter is not set in the configuration it would be set in the resource:
if (-not $GroupTypes -and $currentParameters.GroupTypes -eq $null)
    {
        $currentParameters.Add('GroupTypes', @('Unified'))
    }
#### Suggested solution to the issue
Do not set GroupType parameter if not specified in the configuration
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
AADGroup "AllowCreation-User"
        {
            ApplicationId                          = $Cd.NonNodeData.ApplicationId;
            CertificateThumbprint                  = $Cd.NonNodeData.CertificateThumbprint;
            Description                            = "Just a Security Group";
            DisplayName                            = "AADSecGroup";
            Ensure                                 = "Present";
            MailNickname                           = "AADSecGroup";
            MailEnabled                            = $false;
            SecurityEnabled                        = $True;
            TenantId                               = $TenantId;
            PsDscRunAsCredential                   = $PSDSCcred;
        }
```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : de-DE
OsMuiLanguages       : {de-DE, en-US, fr-FR, it-IT}

**Comment by andikrueger** [comment]
Have you tried to define group types like this:


```powershell
AADGroup "AllowCreation-User"
        {
            ApplicationId                          = $Cd.NonNodeData.ApplicationId;
            CertificateThumbprint                  = $Cd.NonNodeData.CertificateThumbprint;
            Description                            = "Just a Security Group";
            DisplayName                            = "AADSecGroup";
            Ensure                                 = "Present";


            GroupTypes                        = @()



            MailNickname                           = "AADSecGroup";
            MailEnabled                            = $false;
            SecurityEnabled                        = $True;
            TenantId                               = $TenantId;
            PsDscRunAsCredential                   = $PSDSCcred;
        }
```

**Comment by afloca** [comment]
Ok, defining the parameter as empty array does the trick and the group is correctly created as a simple security group. Perhaps a better description of the Parameter would help for this use case, expectation normally is that if the parameter is not mandatory and not specified it would not be defaulted
