### ISSUE TITLE
Update comments at the top of each examples

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#243]
The examples currently have a generic comments block at the top of each file. We would like to update all of those to better describe what the example is actually doing.

**Comment by Markus-Hanisch** [comment]
@NikCharlebois I like to Office365DSC project and would like to contribute.
How can I help in here? Do you want to add a [comment-based help](https://docs.microsoft.com/en-us/powershell/scripting/developer/help/examples-of-comment-based-help?view=powershell-7) part in each of the Configuration examples? Most probably based on the related wiki article?

For example:
.../[1-ConfigureMailtips.ps1](https://github.com/microsoft/Office365DSC/blob/Dev/Modules/Office365DSC/Examples/Resources/EXOMailTips/1-ConfigureMailtips.ps1)
based on wiki article:
.../wiki/[EXOMailTips](https://github.com/microsoft/Office365DSC/wiki/EXOMailTips)

**Comment by NikCharlebois** [comment]
@Markus-Hanisch the idea would simply be to provide more context as to what each example does. For example:

The following example will create a new Teams Calling Policy with value.

It doesn't have to be more than this, just a bit more specific than what we currently have. There are also a lot of missing examples. Every resource should have at least one associated example to keep the Wiki consistent.

**Comment by NikCharlebois** [comment]
Will be automated when we roll out the Dynamic Resource Generator
