### ISSUE TITLE
Duplicate code error in M365DSCUtil::New-M365DSCConnection

### ISSUE THREAD

**Issue by mlhickey** [microsoft/Microsoft365DSC#2439]
While troubleshooting aspects of CredentialsWithApplicationId authentication, found what appears to be a large chunk of code duplication in M365DSCUtil : lines 1525 through 1687 appear to be old code which is partially replicated/replaced in 1712 through 1777

#### Verbose logs showing the problem
N/A
#### Suggested solution to the issue
Remove duplicate/unnecessary code

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running

N/A
#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.1019.1

**Comment by andikrueger** [comment]
I have the same impression. What I can't tell, which code is the duplicate...
![image](https://user-images.githubusercontent.com/15608729/197843761-ed760b9d-9671-4b74-b3da-68da7709a18a.png)

**Comment by mlhickey** [comment]
It looks to me like there were some changes made in evaluation strategy, but the original code was not removed, e.g. look at repeated blocks at 1556/1742 (no change, replicated) and 1687/1834 (changed eval, same execution/assignment).  When the changes were made a large block copy was performed but not cleaned up, resulting in nested elseifs with new code.

**Comment by andikrueger** [comment]
I tried to figure out which PR or change caused the duplication. No luck so far. GitHub blame is no help at all. The file history was not as helpful as I hoped it would be. 

I’ll try to figure it out from the change perspective. Maybe this helps to understand the duplication a bit better. 

Looking forward to your insight from a testing perspective.

**Comment by mlhickey** [comment]
So far passed tests with:

- Credential/AppId
- ManagedIdentity
- Application/Thumbprint
- Application/Secret

Did identity additional bug with ApplicationSecret where it was still a System.String in core engine.  Resolving that as well by assignment as PSCredential to match resources.

**Comment by mlhickey** [comment]
Apologies for open/close - some intervening PRs had negative impact so had to revert

**Comment by mlhickey** [comment]
Closing this for now since it's a cleanliness issue and not a bug
