### ISSUE TITLE
Every Report contains $OrganizationName instead of the real organization name

### ISSUE THREAD

**Issue by HCRitter** [microsoft/Microsoft365DSC#2443]
for every section: Exchange, SPO, Team etc. there is always $OrganizationName in the report instead of the the real organizationname.
Sometimes in the report itself its also showing with which code the organizationname should be generated in that context.
For example the hub url:
`https://$($OrganizationName.Split('.')[0]).sharepoint.com/sites/ContosoWorks`

I am using the credentialbased exporting method, Version: 1.22.1019.1, running on windows 10, PowerShell Version 5.1 and I have updated all the dependencies to the newest version.
Calling function looked like this:
`$Credential = Get-Credential
Export-M365DSCConfiguration -Components @("EXOAcceptedDomain", "EXOActiveSyncDeviceAccessRule", "EXOAddressBookPolicy", "EXOAddressList", "EXOAntiPhishPolicy", "EXOAntiPhishRule", "EXOApplicationAccessPolicy", "EXOAtpPolicyForO365", "EXOAuthenticationPolicy", "EXOAuthenticationPolicyAssignment", "EXOAvailabilityAddressSpace", "EXOAvailabilityConfig", "EXOCASMailboxPlan", "EXOCASMailboxSettings", "EXOClientAccessRule", "EXODataClassification", "EXODataEncryptionPolicy", "EXODistributionGroup", "EXODkimSigningConfig", "EXOEmailAddressPolicy", "EXOGlobalAddressList", "EXOHostedConnectionFilterPolicy", "EXOHostedContentFilterPolicy", "EXOHostedContentFilterRule", "EXOHostedOutboundSpamFilterPolicy", "EXOHostedOutboundSpamFilterRule", "EXOInboundConnector", "EXOIntraOrganizationConnector", "EXOIRMConfiguration", "EXOJournalRule", "EXOMailboxPlan", "EXOMailboxSettings", "EXOMailContact", "EXOMailTips", "EXOMalwareFilterPolicy", "EXOMalwareFilterRule", "EXOManagementRole", "EXOManagementRoleAssignment", "EXOMessageClassification", "EXOMobileDeviceMailboxPolicy", "EXOOfflineAddressBook", "EXOOMEConfiguration", "EXOOnPremisesOrganization", "EXOOrganizationConfig", "EXOOrganizationRelationship", "EXOOutboundConnector", "EXOOwaMailboxPolicy", "EXOPartnerApplication", "EXOPerimeterConfiguration", "EXOPolicyTipConfig", "EXOQuarantinePolicy", "EXORemoteDomain", "EXOResourceConfiguration", "EXORoleAssignmentPolicy", "EXOSafeAttachmentPolicy", "EXOSafeAttachmentRule", "EXOSafeLinksPolicy", "EXOSafeLinksRule", "EXOSharedMailbox", "EXOSharingPolicy", "EXOTransportConfig", "EXOTransportRule") -Credential $Credential`

Other results like the name of a user in the report is totally fine.
BR
Christian

**Comment by andikrueger** [comment]
This is by design. The org name is replaces in all resources during the export. This allows to apply the configuration on every tenant. The organization name is going to be replaced during the compilation of the configuration.

**Comment by HCRitter** [comment]
aaaah got it, sorry, that makes so much sense now. Thank you!
