### ISSUE TITLE
Ignore certain properties in Assert-M365DSCBlueprint

### ISSUE THREAD

**Issue by cstaubli** [microsoft/Microsoft365DSC#2444]
We're using Assert-M365DSCBlueprint to assert and monitor configuration drift for a number of tenants. Therefore we created a blueprint which is not specific for one tenant, but contains settings which we would assert on many tenants. For example, we assert the following named location must be present:

```JSON
AADNamedLocationPolicy 'Trusted Countries for Administrative Access' {
    CountriesAndRegions               = @("CH");
    Credential                        = $Credscredential;
    DisplayName                       = "Trusted Countries for Administrative Access";
    Ensure                            = "Present";
    IncludeUnknownCountriesAndRegions = $False;
    OdataType                         = "#microsoft.graph.countryNamedLocation";
    Managedidentity                   = $False;
    Id                                = "";
}
```

The problem is the property 'Id' will differ in every tenant. I've tried '*' and '%' as wildcard to accept any value, and even exclude this property, but still every time this is reported as configuration drift. 

I've noted [here](https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Modules/M365DSCReport.psm1#L519) that some properties are excluded from reporting, is there a way to exclude others as well (apart from a fork and adjust this line)?

This happens with other resources as well, it is not specific to AADNamedLocationPolicy. I know one obvious solution would be having a blueprint for each tenant with correct Id, but with many tenants this is a cumbersome task.

Thanks in advance
Christian

**Comment by andikrueger** [comment]
The current exclusion helps to disable noise in the reports. It will exclude resource names like AADNamedLocation or the authentication parameters. 

In your case:

the ID is part of the resource and the configuration. Any change to the ID would be reported as a drift. Even no configuration is a drift, as this would be a different configuration from the one with the id. 

I totally agree on this being not optimal. Is it always the parameter ID causing issues or are there other parameters as well? 

maybe we could add a new Parameter to all reporting functions: -ExcludeParameter @(“ID”)

if this array is set, the exclusion list would be extended with the string array provided.

**Comment by cstaubli** [comment]
Yeah, that would be perfect having an exclude parameter. Most of the time it is ID, but could be others as well. This would really help us build generic blueprints and report configuration drifts for many tenants based on this blueprint
