### ISSUE TITLE
PowerShell DSC resource MSFT_SCDLPCompliancePolicy  failed to execute Test-TargetResource functionality with error      message:

### ISSUE THREAD

**Issue by upaneshpatel** [microsoft/Microsoft365DSC#2450]
I'm trying to "export" a DLP policy from a "Source" tenant and trying to use DSC to "Import/create" the DLP policy in the "Destination" tenant.

My export is successful from "Source" tenant.

After I compile the config file with the "destination" tenant credentials and create the localhost.mof file, I run the 
Start-DSCConfiguration command and I receive the below error -

--Error--
PowerShell DSC resource MSFT_SCDLPCompliancePolicy  failed to execute Test-TargetResource functionality with error      message: Showing a modal dialog box or form when the application is not running in UserInteractive mode is not a valid  operation. Specify the ServiceNotification or DefaultDesktopOnly style to display a notification from a service application

____

I've tried to create multiple object in the "Destination" tenant but receive the same error.

**Comment by andikrueger** [comment]
This looks like your account Süd- ti Apple the configuration has MFA enabled. Please make sure to use an account without mfa

**Comment by upaneshpatel** [comment]
Yes that was actually it... I disabled the MFA and it resolved that issue. Thank you.
