### ISSUE TITLE
IntuneAppProtectionPolicyAndroid/iOS - Errors when pushing test policies

### ISSUE THREAD

**Issue by MichealKennard** [microsoft/Microsoft365DSC#2453]
#### Details of the scenario you tried and the problem that is occurring
Performing testing of Microsoft365DSC, able to export components referenced in subject, compile and create .mof file without much issue. However, when pushing the configuration most of the push seems to run fine until the end which generates several errors. The end result is neither policy is being configured. Given my relatively new experience level, may be simple issue but wanted to post for support.

#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/116776712/198177377-0ca76d24-ee05-44fa-b717-985ba301bd7e.png)
VERBOSE: [...-6143KL3]:                            [[IntuneAppProtectionPolicyiOS]da4bdc60-9c8a-4e86-8a35-fd48eaa9fb6d] POST https://graph.microsoft.com/beta/deviceAppManagement/managedAppPolicies
HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: d6af9341-8c33-4c8e-b37b-0bc45766feee
client-request-id: d6af9341-8c33-4c8e-b37b-0bc45766feee
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"South Central US","Slice":"E","Ring":"5","ScaleUnit":"000","RoleInstance":"SN1PEPF000051D0"}}
Date: Thu, 27 Oct 2022 02:15:38 GMT
Content-Encoding: gzip
Content-Type: application/json

{"error":{"code":"BadRequest","message":"Unable to read JSON request payload. Please ensure Content-Type header is set and payload is of valid JSON format.","innerError":{"date":"2022-10-27T02:15:38","request-id":"d6af9341-8c33-4c8e-b37b-0bc45766feee","clien
t-request-id":"d6af9341-8c33-4c8e-b37b-0bc45766feee"}}}

VERBOSE: [...-6143KL3]:                            [[IntuneAppProtectionPolicyiOS]da4bdc60-9c8a-4e86-8a35-fd48eaa9fb6d] Found Policy with Id {}
Cannot bind argument to parameter 'PolicyId' because it is an empty string.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Set-M365DSCIntuneAppProtectionPolicyiOSAssignment
    + PSComputerName        : localhost
 
VERBOSE: [...-6143KL3]: LCM:  [ End    Set      ]  [[IntuneAppProtectionPolicyiOS]da4bdc60-9c8a-4e86-8a35-fd48eaa9fb6d]  in 15.6690 seconds.
The PowerShell DSC resource '[IntuneAppProtectionPolicyiOS]da4bdc60-9c8a-4e86-8a35-fd48eaa9fb6d' with SourceInfo 'C:\...\M365DSC\Test2ConfigFolder\Compiled_Pushed\M365TenantConfig.ps1::74::9::IntuneAppProtectionPolicyiOS' threw one or more non-terminating 
errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
VERBOSE: [...-6143KL3]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Local Windows 10 laptop via PowerShell

# insert configuration here
Attached .ps1, .psd1 and .mof files for reference
[M365TenantConfig.zip](https://github.com/microsoft/Microsoft365DSC/files/9875446/M365TenantConfig.zip)

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Name                       : Microsoft365DSC
Version                    : 1.22.1019.1
Type                       : Module
Description                : This DSC module is used to configure and monitor Microsoft tenants, including SharePoint Online, Exchange, Teams, etc.
Author                     : Microsoft Corporation
CompanyName                : NikCharleboisPFE DerekSmay
Copyright                  : (c) 2022 Microsoft Corporation. All rights reserved.
PublishedDate              : 10/19/2022 5:56:49 PM
InstalledDate              : 10/26/2022 8:00:32 PM
UpdatedDate                : 
LicenseUri                 : https://github.com/Microsoft/Microsoft365DSC/blob/master/LICENSE
ProjectUri                 : https://github.com/Microsoft/Microsoft365DSC
IconUri                    : https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Dependencies/Images/Logo.png?raw=true

**Comment by andikrueger** [comment]
@William-Francillette could you have a look at this one. Looks like some of the graph requests are failing due to missing header information.

**Comment by William-Francillette** [comment]
Sure, will do

**Comment by William-Francillette** [comment]
I had a quick look and haven't worked on those 2 before - They are built very differently from other resources (lots of JSON in there)
I will complete the resource I am working on at the moment (entitlement management) and will start working on them -They are using the v1.0 API so it will probably be a good candidate for a rework and breaking change - I'll post 2 PRs again: the first one non-breaking and 2nd one breaking including embedded cim and so forth

**Comment by William-Francillette** [comment]
I will be looking at this next sorry for the delay (will get started tomorrow after works)
