### ISSUE TITLE
Importing the newer version failed: Azure Automation

### ISSUE THREAD

**Issue by yeti1305group** [microsoft/Microsoft365DSC#2454]
#### Details of the scenario you tried and the problem that is occurring
Importing the newer version failed: While running runbooks in Azure Automation the import of new module which is part of the command is giving an error. Can there be a switch to choice for importing a newer version when just running the export,, assert and New_M365DSC commands in Azure Automation?

#### Verbose logs showing the problem
Importing of newer version failed.

Error importing the module Microsoft365DSC. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: While importing the module, an error occurred while processing the module content. Internal error message: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.. at Orchestrator.Activities.SetModuleVersion.ExecuteInternal(CodeActivityContext context, String moduleName, ModuleLanguage moduleLanguage, String pythonModuleVersion, String modulePath, Guid accountId, Guid moduleVersionId, Int64 moduleContentByteSize, String storageUri, Int32 moduleVersion) at Orchestrator.Activities.SetModuleVersion.Execute(CodeActivityContext context) at System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager) at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)

![image](https://user-images.githubusercontent.com/114399219/198223300-08570c2d-879a-45e1-9663-80acd2d29e5f.png)

#### Suggested solution to the issue
Switch in command to not update module while running the commands

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Powershell in Azure Automation Runbooks

# insert configuration here
```runbooks in Azure Automation

#### The operating system the target node is running
Azure Automation is used

#### Version of the DSC module that was used ('dev' if using current dev branch)
Module version: 1.22.1019.1

**Comment by andikrueger** [comment]
Is this still an issue with V1.22.1026.1?
