### ISSUE TITLE
Exporting with Global Reader Account with MFA Enabled

### ISSUE THREAD

**Issue by MichealKennard** [microsoft/Microsoft365DSC#2461]
We reached out to Microsoft, however they are often very delayed in responding so wanted to post here to see if anyone had thoughts.

We are looking to test pulling against an older, already established tenant, and I have created an account with Global Reader assignment that is excluded from any listed Conditional Access & MFA policies. 

Attempting to use it gives these screens, next through gets me to the last one:
![image](https://user-images.githubusercontent.com/116776712/198380774-d8be1efe-019d-4bbd-96f1-f6beb6aad334.png)
![image](https://user-images.githubusercontent.com/116776712/198380819-a456645d-cc67-4e3b-b2c3-9ce2a9786052.png)

Our only reason for not using MFA is because the M365 documentation didnt list it as being fully supported across all workloads we would want to pull & push to. If that is wrong and I am misunderstanding, could someone provide some more context behind that.

Best I could find was the following article, which I checked and don't see an issue there:
https://learn.microsoft.com/en-us/azure/active-directory/authentication/howto-registration-mfa-sspr-combined

Been loving the solution, just trying to work through little things like this so I can have a solid process to follow. Thanks!

**Comment by JonesMikael** [comment]
@MichealKennard I suspect you have SSPR (Self Service Password Reset) enabled in your tenant and you require all users to register for SSPR. So even though you don’t require user to MFA, they are still forced to register for SSPR and it looks the same as register for MFA. Easiest method would be just to register methods and once done it will not ask for MFA when signing in.

**Comment by MichealKennard** [comment]
@JonesMikael They do, didnt even think about that. I will review and test again, thank you for the response!

**Comment by andikrueger** [comment]
In some cases the same happens as soon as the AD security defaults are enabled.

**Comment by MichealKennard** [comment]
Issue was the SSPR, once we went through that, was able to move forward. Thanks everyone!
