### ISSUE TITLE
Several modules have Managedidentity instead of ManagedIdentity

### ISSUE THREAD

**Issue by fxlite** [microsoft/Microsoft365DSC#2464]
#### Details of the scenario you tried and the problem that is occurring

E.g. EXOOrganizationConfig, but this occurs in several of the EXO resources.

#### Suggested solution to the issue
For example,  Line 1184 in MSFT_EXOOrganizationConfig.psm1 contains:

`$SetValues.Remove('Managedidentity') | Out-Null`

Which should be:

`$SetValues.Remove('ManagedIdentity') | Out-Null`

Due to hashtable keys being case sensitive, this does not remove ManagedIdentity from the splat on Line 1196, and the Set-TargetResource fails with "A parameter cannot be found that matches parameter name 'ManagedIdentity'."

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Start-DSCConfiguration -Path <pathToCompilledEXOOrganizationConfigMOF> -Wait -Force
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.1026.1

**Comment by mlhickey** [comment]
Hashtable keys are case-insensitive:

$currentParameters.Add('UPPER',$true)
$currentParameters['UPPER']
True
$currentParameters['upper']
True
$currentParameters = @{}
$currentParameters.Add('UPPER',$true)
$currentParameters['upper']
True
$currentParameters['UPPER']
True
$currentParameters.Remove('upper')
$currentParameters

The issue is more likely that it's not being correctly passed to begin with.

**Comment by andikrueger** [comment]
@mlhickey thanks for the further investigation.

**Comment by fxlite** [comment]
Thanks for the input. [This](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/rules/useliteralinitializerforhashtable?view=ps-modules) is a good resource regarding case sensitivity in hashtables, depending on how they're initialized. I figured this was relevant, as when I altered the module myself, the parameter error disappeared...

**Comment by mlhickey** [comment]
Sounds like something else is going on since:

![image](https://user-images.githubusercontent.com/20215068/198838079-340213a7-0fa1-4093-b3ed-cb52b2421caf.png)

**Comment by fxlite** [comment]
Yeah, but the hashtable isn't getting initialized literally like you have the module unless I'm mistaken. For example:

![image](https://user-images.githubusercontent.com/23617062/198838403-98b9eb03-792b-43e8-bbc9-1cab853e3ee4.png)

**Comment by mlhickey** [comment]
I agree if they were being created that way, but here we they are not.  In this case it's being copied from $PSBoundParameters:
` $ValuesToCheck.Remove('Credential') | Out-Null`

so

![image](https://user-images.githubusercontent.com/20215068/198838697-5154b643-ff6d-4c6f-b687-c2a0f56491b8.png)

Regardless, it was a typo in my part and should be rationalized regardless for sake of good coding
