### ISSUE TITLE
[SPOTenantCdnEnabled] False does not provide any export results

### ISSUE THREAD

**Issue by ykuijs** [microsoft/Microsoft365DSC#2466]
#### Details of the scenario you tried and the problem that is occurring
When this setting is disabled, the export does not include the resource because Enabled=False is filtered out here:
https://github.com/microsoft/Microsoft365DSC/blob/d3e1ad0a21568e1777584b62fdcc121080b60c4c/Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantCdnEnabled/MSFT_SPOTenantCdnEnabled.psm1#L372-L384

But this can be False because of either the Get-TargetResource returned False or nothing (because Get-PnPTenantCdnEnabled threw an exception.

Question now is: Should the resource be filtered when the setting is False?

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by andikrueger** [comment]
I would add this information to the export of the resource. This could cause errors in export/import scenarios across various "stages". I someone would have enable the setting, it would not be disabled in other cases. Disabled is the default state, isn't it?

**Comment by ykuijs** [comment]
I believe it is indeed.

Right now the code returns an empty string when an exception occurs:
https://github.com/microsoft/Microsoft365DSC/blob/d3e1ad0a21568e1777584b62fdcc121080b60c4c/Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantCdnEnabled/MSFT_SPOTenantCdnEnabled.psm1#L118
This is the Export code to filter the resource.

Maybe it would be better to return Ensure=Absent and filter on the Ensure instead of the Enabled parameter.
