### ISSUE TITLE
Export UI does not show longer resource names properly

### ISSUE THREAD

**Issue by ykuijs** [microsoft/Microsoft365DSC#2470]
The Export UI does not show longer resource names in a nice way. This is especially visible with the Intune resources:
<img width="787" alt="image" src="https://user-images.githubusercontent.com/15103891/198987718-a5474dae-614b-48fc-a443-1110b783eea1.png">

We should update the website in such a way that the names are either wrapped or displayed nicely in a different way.

**Comment by NikCharlebois** [comment]
Fixed
