### ISSUE TITLE
Running Export-M365DSCConfiguration on Azure Automation Runbook does not export files

### ISSUE THREAD

**Issue by yoinuma** [microsoft/Microsoft365DSC#2475]
I am testing running Export-M365DSCConfiguration on Azure Automation Runbook.
However, running Export-M365DSCConfiguration does not output any files.

`
$Date = $(Get-Date -f yyyy-MMM-dd-HHMMtt)
$applicationId = "<ApplicationId>"
$tenantId = "contoso.onmicrosoft.com"
$certificateThumbprint = "<Thumbprint>"

$tempPath = "$env:TEMP"
$initialConfigurationFileName = "InitialM365TenantConfig.ps1"
$adminUrl = "https://contoso-admin.sharepoint.com"

write-output "Pulling DSC from Tenant $Date"
Export-M365DSCConfiguration -Workloads @("OD", "SPO") -Path $tempPath -ApplicationId $applicationId -TenantId $tenantId -CertificateThumbprint $certificateThumbprint -FileName $initialConfigurationFileName

Get-ChildItem $tempPath
`
![image](https://user-images.githubusercontent.com/31690455/199178228-a7876e69-0eaa-493d-8974-8822f17e3e66.png)

I believe that InitialM365TenantConfig.ps1 should be created under "$env:TEMP", but it is not.
Also, the InitialM365TenantConfig.ps1 file is successfully output when this script is run locally, not on Azure Automation. Therefore, I believe that running it on Azure Automation Runbook is related to the event.
Does anyone have any ideas for a solution?

**Comment by andikrueger** [comment]
Did you use this guide to setup your runbook? https://o365eh.com/2020/10/27/episode-74-using-microsoft-dsc-as-a-runbook-in-azure-automation/

There were some issues related to this guide: https://github.com/microsoft/Microsoft365DSC/issues?q=runbook Please have a look at them as well.

**Comment by yoinuma** [comment]
Thanks for the response @andikrueger , 
Yes, I had this article confirmed. Just to be sure, I ran the M365DSCRunBookInstall part again and then ran Export-M365DSCConfiguration, but still nothing was output.
Any other ideas?

**Comment by NikCharlebois** [comment]
@yoinuma did the link that Andi shared above help?

**Comment by yoinuma** [comment]
@andikrueger , @NikCharlebois 
Thanks for the advice.
I have confirmed that we can successfully run Export-M365DSCConfiguration on Azure Automation by running the script https://github.com/microsoft/Microsoft365DSC/issues/2050#issuecomment-1195414547 that you taught me.
The issue has been resolved and can be closed.
Thanks again!
