### ISSUE TITLE
Whitepaper DevOps: MOF files should be secured with a certificate

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#2478]
After following steps in the whitepaper to create a DevOps solution around M365DSC I noticed that after compiling the tenant configuration the MOF file had the admin password in cleartext, locally I didn't notice that issue after using Set-M365DSCAgentCertificateConfiguration.

The issue is that the DSC scripts package, mentioned in page 30 of the pdf that are meant to be downloaded into the DevOps repo, include file M365ConfigurationData.psd1 without line 'CertificateFile = "DSCCertificate.cer"', the steps on how to generate this specific certificate are mentioned in page 27 (maybe those steps could also be updated to call Set-M365DSCAgentCertificateConfiguration instead?)

**Comment by andikrueger** [comment]
The white paper contains a section on how to secure the passwords properly. See section 3.7.

**Comment by ricmestre** [comment]
I'm referring exactly to section 3.7, those steps were followed but if M365ConfigurationData.psd1, which is included in the zip, doesn't point to that self-signed generate certificate (by adding line 'CertificateFile = "DSCCertificate.cer"' as previously mentioned) then the passwords won't be encrypted in the compiled MOF file.

Please check zip file at https://aka.ms/M365DSCWhitepaper/Scripts

**Comment by andikrueger** [comment]
Are you using the build_cert.ps1 and deploy_cert.ps1?

**Comment by ricmestre** [comment]
No, I'm using {build,deploy}.ps1 since I'm using credentials based auth, not certificates. In this case the certificate is only required to secure the password.

**Comment by andikrueger** [comment]
You are right. This is for using the cert vased authentication. 

What needs to be done:

1. You need to create a certificate that will be used to encrypt the credentials within the mof files.
2. This certificate needs to be made avilable for the compilation of the coinfiguration
3. This certificate needs to be available within the machine that runs the configuration.


Please see this article for the detailed steps: https://learn.microsoft.com/en-us/powershell/dsc/pull-server/securemof?view=dsc-1.1

**Comment by ricmestre** [comment]
Hi Andi, I'm well aware of how to do this, in fact I solved it before reporting the problem, I'm just pointing out that someone following the whitepaper might not know it or at least like myself will not notice it at first since it's actually not mentioned there.

I'd say it's a documentation bug/omission in the whitepaper, not a problem with M365DSC itself.

**Comment by andikrueger** [comment]
Now I get it. I’ll change the label to enhancement and we will consider it the next time we update the whitepaper 👍

**Comment by ricmestre** [comment]
Great! Thank you very much for having a look into it!

**Comment by MatthewWhiteMoJ** [comment]
@ricmestre do you need to add CertificateFile or can you reference CertificateID as is defined in 3.7 of the document? Just noticed this and pulling the changes into the config i am testing with

**Comment by ricmestre** [comment]
@MatthewWhiteMoJ hi, both ways work so yes you can use the thumbprint of the certificate instead of referencing it by name.

**Comment by NikCharlebois** [comment]
//cc @ykuijs

**Comment by ykuijs** [comment]
All, I am in the final stages of a major update of the whitepaper. The old version was mostly written to demonstrate how you could use Azure DevOps to manage Microsoft 365 using Microsoft365DSC, the DSC configuration itself and the scripts were very basic.

This new version has a more extended setup: The scripts are more robust and are now using Composite resources to combine all resources of a specific workload into its own composite resource. And it is definitely securing the MOF files (though this was also the case in the old version).

Keep an eye on our Microsoft365DSC Twitter feed for news when this whitepaper is released!
