### ISSUE TITLE
AADGroup members being stripped off for manual group

### ISSUE THREAD

**Issue by anpiskai** [microsoft/Microsoft365DSC#2481]
While the changes that fixed issue #2190 (https://github.com/microsoft/Microsoft365DSC/issues/2190) seem to have resolved the attempted removal of members for dynamic groups, the problem still appears to exist for manual groups where the Members attribute is absent from the resource. Instead, the resource Members attribute is treated as present and blank resulting in DSC trying to remove all members.

These are the attributes specified on the affected resource:
<img width="134" alt="image" src="https://user-images.githubusercontent.com/48796638/199531871-ec3da932-d67d-4ac5-a5af-6be2c54a0f9f.png">

and the output from the log (avoiding specifying internal data)
<img width="77" alt="image" src="https://user-images.githubusercontent.com/48796638/199532138-d73b2d58-8249-4ae9-af85-af2f24b0e3ee.png">

**Comment by andikrueger** [comment]
Thanks for reporting. The code does not check if the parameter is set or not. It treats the missing parameters as a drift and removes the members therefore.
