### ISSUE TITLE
MSFT_EXODataClassification Powershell interactive issue

### ISSUE THREAD

**Issue by upaneshpatel** [microsoft/Microsoft365DSC#2487]
Hi All -
When I'm importing MSFT_EXODataClassification to target tenant, I'm getting below error... What am I missing?

**PowerShell Desired State Configuration does not support execution of commands in an interactive mode. Please ensure     that the underlying command is not prompting for user input, such as missing mandatory parameter, confirmation prompt   etc.**

**Comment by andikrueger** [comment]
Please make sure you did disable MFA for your account.

**Comment by upaneshpatel** [comment]
Andi - I have a "personal" test tenant where I'm performing a pilot of DSC functionality. I'm trying to replicate the ENTIRE "Exchange" workload to this personal tenant and I get different errors depending on the work load. 

For MSFT_EXODataClassification I get the "interactive mode" but I don't in any other workload which would indicate to me that there is NO MFA enabled.

**Comment by upaneshpatel** [comment]
I believe the other possible issue can be "Missing parameter" as indicated but looking at your code 

Please ensure that the underlying command is not prompting for user input, such as missing mandatory parameter, confirmation prompt etc.

Looking at the "DataClassifiction", I do not see another mandatory parameter but I maybe missing something
