### ISSUE TITLE
MSFT_EXOHostedOutboundSpamFilterRule  creation error

### ISSUE THREAD

**Issue by upaneshpatel** [microsoft/Microsoft365DSC#2488]
Hi All,

When I try to "create a new" spam filter rule, I get below error of "Outbound policy doesn't exists". Shouldn't it create one if it doesn't exists?

**PowerShell DSC resource MSFT_EXOHostedOutboundSpamFilterRule  failed to execute Set-TargetResource functionality with   error message: Error attempting to create EXOHostedOutboundSpamFilterRule {Outbound SPAM max}. The specified            HostedOutboundSpamFilterPolicy {Outbound SPAM max} doesn't exist. Make sure you either create it first or specify a     valid policy.**

**Comment by malauter** [comment]
Before you can create a outbound spam filter rule, you have to create the filter policy first. The policy is required to create a new rule in EXO.

**Comment by upaneshpatel** [comment]
Thaks you... Yes can't divide up the workloads unless you get the pre-req of policy for rule.
