### ISSUE TITLE
Export-M365DSCConfiguration: With credential authentication parameter still prompts for credential

### ISSUE THREAD

**Issue by dominicbuehrer** [microsoft/Microsoft365DSC#2490]
#### Details of the scenario you tried and the problem that is occurring
When i call the Export-M365DSCConfiguration command with provided (and correct) credentials, I still get the login prompt from Microsoft. it looks like the module does not know, where connect to.+

Export-M365DSCConfiguration -Components @("O365OrgCustomizationSetting", "ODSettings", "SPOTenantSettings", "SPOTheme") -Credential $AdminCreds

#### Verbose logs showing the problem
There is no error showing up in the verbose logs.

The Login prompt appears, when the following command ist run from the "MSCloundLoginAssistant" on line 217
$Global:MSCloudLoginConnectionProfile.MicrosoftGraph.Connect()

This are the properties of "$Global:MSCloudLoginConnectionProfile.MicrosoftGraph" bevor the connect() call. 
AccessToken               : 
GraphEnvironment          : Global
ProfileName               : v1.0
ResourceUrl               : 
Scope                     : 
TokenUrl                  : 
UserTokenUrl              : 
AuthenticationType        : 
Connected                 : False
ConnectedDateTime         : 
Credentials               : System.Management.Automation.PSCredential
EnvironmentName           : 
MultiFactorAuthentication : False
ApplicationId             : 
ApplicationSecret         : 
TenantId                  : 
CertificatePassword       : 
CertificatePath           : 
CertificateThumbprint     : 
Identity                  : False

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
There is no special configuration. 
```powershell
$AdminCreds = Get-Credential
Export-M365DSCConfiguration -Components @("O365OrgCustomizationSetting", "ODSettings", "SPOTenantSettings", "SPOTheme") -Credential $AdminCreds
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.5427.amd64fre.rs1_release.220929-2054
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.1102.1       

All otther dependencies are uptodate

**Comment by andikrueger** [comment]
Did you assign the right permissions for the access to the tenant? https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/#determine-required-permissions

**Comment by dominicbuehrer** [comment]
Yes, I did that and I thought it was enough to enter the login data when I run the Export command. I have now configured this with an Application Regestration and now it works.

Thank you!

**Comment by andikrueger** [comment]
Thanks for the feedback. I'll close this issue for now.
