### ISSUE TITLE
ModifyResourceName: EXODataClassification - Provide Filter option

### ISSUE THREAD

**Issue by upaneshpatel** [microsoft/Microsoft365DSC#2494]
### Description
EXODataClassification needs a filter option because there are many Out of the box classification which do not need to be replicated to PROD.

### Proposed properties

"-Filter" option

### Special considerations or limitations

NONE

**Comment by malauter** [comment]
The Get-DataClassification itself does not provide a filter parameter. I am not sure which filter criteria we should use for a custom filter, and I think it does not make sense in all use cases to filter all built-in classifications. 
Of course, you can remove the built-in classifications from your script before importing it into another tenant.

**Comment by upaneshpatel** [comment]
@maluter - ok thank you.. I will be removing "Built-in" classification before importing into another tenant.
