### ISSUE TITLE
Assert-M365DSCBlueprint: The runbook job failed due to a job stream being larger than 1MB

### ISSUE THREAD

**Issue by yeti1305group** [microsoft/Microsoft365DSC#2501]
#### Details of the scenario you tried and the problem that is occurring
Running Assert-M365DSCBlueprint for Exchange Online blueprint is giving errors in Azure Automation. I do receive the error: "The runbook job failed due to a job stream being larger than 1MB, the limit that is supported by an Azure Automation sandbox. See some common ways to resolve this at https://aka.ms/AAjobstreamlimit". It looks like this error is generated at the beginning of the assert cmdlet.

#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/114399219/200404342-5d17c04e-5e90-4b56-b018-36b52efc225c.png)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
 Assert-M365DSCBlueprint -BluePrintUrl "$path\$filenameBlueprint" -OutputReportPath "$path\$filenameVerify" -Type JSON -Credential $Global:credential | Out-Null
```

#### The operating system the target node is running
Azure Automation PowerShell version 5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
Module version: 1.22.1026.2

**Comment by andikrueger** [comment]
Could you try to put this part of the script into a try-catch block to get an error message (if there is any)?

**Comment by yeti1305group** [comment]
It is in a try catch and even when I add ErrorAction:stop it is not going to catch and keeps running. So, in the end the job is finished, but is giving these errors during the start of the assert for Exchange components. In the other runbooks for the other services, I don't encounter this error. Maybe it is the number of components for exchange selected? I will try with less Exchange components.

**Comment by andikrueger** [comment]
I just found the solution to this issue. You need to redirect toe output of the command to the proper stream:

Assert-M365DSCBlueprint -BluePrintUrl "$path\$filenameBlueprint" -OutputReportPath "$path\$filenameVerify" -Type JSON -Credential $Global:credential ***>&1 | Out-Null**

**Comment by yeti1305group** [comment]
I will try this. I was using the out-null, but without *>&1. Will let you know!

**Comment by yeti1305group** [comment]
This seems to suppress the error indeed. Thanks!

**Comment by ykuijs** [comment]
Closing this issue, since it is resolved.
