### ISSUE TITLE
MSFT_TeamsChannelsPolicy: Non-compliance reported at midnight across multiple tenants

### ISSUE THREAD

**Issue by HaloX69** [microsoft/Microsoft365DSC#2502]
ISSUE DESCRIPTION: At midnight we began getting App Insights monitoring alerts that this resource was non-compliant because the property AllowPrivateTeamDiscovery returns a null when we have a value set, which has been compliant for nearly 2yrs. 

I have explicitly ran cmdlet Get-CsTeamsChannelsPolicy and in the results the property AllowPrivateTeamDiscovery was blank (null).

This apparently is at the service level since it's across multiple tenants, with the DSC running on different machines, and running the cmdlet on a non-related machine against a non-related tenant results in the same behavior. 

 (this template):
    Please provide information regarding your issue under each header below.
    Write N/A under any headers that do not apply to your issue, or if the
    information is not available.

    NOTE! Sensitive information should be obfuscated.

    PLEASE KEEP THE HEADERS.

    You may remove this comment block, and the other comment blocks,
    but please keep the headers.
-->
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module 1.22.420.1

**Comment by malauter** [comment]
Could you please provide more details on this issue? I cannot reproduce it. Get-CsTeamsChannelsPolicy returns True or False for this property in my tenant. If I do an export with M365 DSC, the value is also not blank.
What is the desired value in your configuration? 
You should also update the M365 DSC module and all dependencies. The version you are using is quite old.

**Comment by andikrueger** [comment]
@HaloX69 Is this still an issue?

You are using the April 2022 version. I would highly recommend to run an update.
