### ISSUE TITLE
Export-M365DSCConfiguration using certificate thumbprint not authenticating to all SharePoint components

### ISSUE THREAD

**Issue by Chabango** [microsoft/Microsoft365DSC#2506]
ISSUE TITLE:
   
  ResourceName: Export-M365DSCConfiguration using certificate thumbprint not authenticating to all SharePoint components

    ISSUE DESCRIPTION:
While running export-m365dsccpnfiguration for the SharePoint components using certificate thumbprint, some of the componnets are not authenticating and returning an X:

![2022-11-08_13-28-59](https://user-images.githubusercontent.com/100866228/200646246-12585989-607a-4c09-b73d-a7f9cf54392e.png)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell

`Export-M365DSCConfiguration -Components @("SPOAccessControlSettings", "SPOApp", "SPOBrowserIdleSignout", "SPOHomeSite", "SPOHubSite", "SPOOrgAssetsLibrary", "SPOPropertyBag", "SPOSearchManagedProperty", "SPOSearchResultSource", "SPOSharingSettings", "SPOSite", "SPOSiteAuditSettings", "SPOSiteDesign", "SPOSiteDesignRights", "SPOSiteGroup", "SPOSiteScript", "SPOStorageEntity", "SPOTenantCdnEnabled", "SPOTenantCdnPolicy", "SPOTenantSettings", "SPOTheme", "SPOUserProfileProperty") -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId -FileName $Name -ConfigurationName "XYZ" -Path $Path -MaxProcesses 100`
```

Retrieving a list of permissions returns the following:

`$permissions = Get-M365DSCCompiledPermissionList -ResourceNameList @("SPOAccessControlSettings", "SPOApp", "SPOBrowserIdleSignout", "SPOHomeSite", "SPOHubSite", "SPOOrgAssetsLibrary", "SPOPropertyBag", "SPOSearchManagedProperty", "SPOSearchResultSource", "SPOSharingSettings", "SPOSite", "SPOSiteAuditSettings", "SPOSiteDesign", "SPOSiteDesignRights", "SPOSiteGroup", "SPOSiteScript", "SPOStorageEntity", "SPOTenantCdnEnabled", "SPOTenantCdnPolicy", "SPOTenantSettings", "SPOTheme", "SPOUserProfileProperty")
$permissions.ReadPermissions`

Domain.Read.All
DeviceManagementServiceConfig.Read.All
Group.Read.All
Application.Read.All

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

-->

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.22.914.1

**Comment by andikrueger** [comment]
Please make sure to register the app that is used for the export within the various site collection with read permissions. Otherwise there will be the no outcome.

```powershell
Grant-PnPAzureADAppSitePermission
```

could help you in this process.

**Comment by Chabango** [comment]
Running the Grant-PnPAzureADAppSitePermission is seems to apply the read permissions, but when running Get-PnPAzureADAppSitePermission it doesn't show the Read permnissions.
What am I missing??

![2022-11-09_10-37-27](https://user-images.githubusercontent.com/100866228/200874393-b3bfb404-8717-4c2a-aa39-3ade3aaaf48f.png)

**Comment by Chabango** [comment]
Any suggestions on where to go from here? Thanks

**Comment by Chabango** [comment]
@andikrueger I am still having issue with the SPO authentication using a certificate thumbprint.
When running the Set-PnPAzureADAppSitePermission I am able to add the Read permissions, but when running Get-PnPAzureADAppSitePermission, the role is still empty.
Am I missing naything here?
THanks

![2022-11-23_8-39-30](https://user-images.githubusercontent.com/100866228/203561394-2358e9c4-668c-4f7a-8fdb-7716b26b6a74.png)

**Comment by Chabango** [comment]
Can I please get some direction on this issue? Is anyone else seeing the same?
THank you

**Comment by NikCharlebois** [comment]
Can you please try granting your app registration permission to Sites.FullControl.All and try again? Thanks
![image](https://user-images.githubusercontent.com/2547149/206193017-e2c929e3-5f0b-4063-8dcd-52e5d13aba81.png)

**Comment by Chabango** [comment]
That App already has Sites.FullControl.All with admin consent, but I am not able to authenticate to some of the modules as described above.

**Comment by NikCharlebois** [comment]
The Sites.FullControl.All permission you need is under the SharePoint API, not Microsoft Graph. That is the issue

**Comment by Chabango** [comment]
Thank you. Adding the SharePoint API, Sites.FullControl.All, wokred
