### ISSUE TITLE
How to connect to custom Sharepoint admin URL

### ISSUE THREAD

**Issue by GotTuna** [microsoft/Microsoft365DSC#2511]
Hello,
We use a custom URL for the SPO admin portal.  By default, the SPO modules in M365DSC uses PnP to connect to the standard yyyyy-admin.sharepoint.com portal.  How do I force it to use a different URL?

I have tried to connect to the admin portal first using Connect-M365Tenant but the Export-M365DSCConfiguration still attempts to log into the default admin portal.

![pnp_error](https://user-images.githubusercontent.com/111378086/200689503-24c2eaca-0c4a-40c4-8781-fb2a358e1afa.png)

**Comment by andikrueger** [comment]
Where is the tenant hosted that you try to connect to and what kind of tenant is it?

**Comment by GotTuna** [comment]
We have a normal M365 tenant.  It was allowed at the time to have a custom URL for all Sharepoint sites so ours uses our domain name.  Now I believe you can only have sharepoint.com or onmicrosoft.com as your SPO domain.

**Comment by NikCharlebois** [comment]
Are you still able to replicate with the latest version? We have been investigating this issue a few days back and cannot replicate it.

**Comment by GotTuna** [comment]
Updating to 1.22.1116.1 seems to have fixed issue with our custom URL.  Thanks!

**Comment by andikrueger** [comment]
Thanks for the confirmation. I’ll close this issue for now. Please feel free to reopen, if the issue would come up again.
