### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by jackmurphy89** [microsoft/Microsoft365DSC#2513]
I was wondering if, is there any reason we have to leave the DSC server on 24/7 or if we could schedule it to come online twice a day to do checks?

Second, can you have multiple configs for multiple clients running off of one server or do they each need their own?

Thanks!

**Comment by andikrueger** [comment]
1. There is real need to run the server 24/7 if you do not want to use the monitoring functionality of microsoft365dsc. Powershell DSC runs a check every 15 minutes to see if your configuration is still present. If not, there will be a message within the server’s event log. 

2. This can be done with the same impact, that you can not monitor these various tenants with DSC at the same time. Prior to applying a new configuration it would be recommended to retract the current one.

**Comment by andikrueger** [comment]
@jackmurphy89 Do you need further input on this one?

**Comment by jackmurphy89** [comment]
I am golden

**Comment by jackmurphy89** [comment]
I am good, thank you
