### ISSUE TITLE
Test-M365DSCDependenciesForNewVersions generates errors in some environments

### ISSUE THREAD

**Issue by menswearUK** [microsoft/Microsoft365DSC#2519]
#### Details of the scenario you tried and the problem that is occurring
When applying a DSC configuration the function Test-M365DSCDependenciesForNewVersions in M365DSCUtil.psm1 generates errors in environments where the system context does not have access to the PSGallery.
The error occurs when the command:
$moduleInGallery = Find-Module $dependency.ModuleName
is run

The command does not generate errors when run by a user with access to the external resource but the Start-DSCConfiguration runs as system and in some environments this is unable to connect to the repository and generates an error

#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/98314167/200876703-80a17090-ccde-4639-8d94-63818dd33b93.png)

#### Suggested solution to the issue
Changing the line to: 
$moduleInGallery = Find-Module $dependency.ModuleName -ErrorAction SilentlyContinue
 appears to prevent the error and still generates the correct output when run under the user context - but I'm not sure what the further impact might be (is it bypassing the whole purpose of the try/catch?).
 I've not looked at it in detail yet to see if it still correctly checks the dependencies in manifest.psd1 with the amended line.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```
This issue occurs before any settings have been applied or checked when the configuration runs the command:
confirm-M365DSCDependencies
I was running a IntuneAppProtectionPolicyAndroid configuration but most configurations run this at the very start of their Test-TargetResource function and I would expect them to return the same error in this environment

#### The operating system the target node is running
Target was the M365 cloud, run from system running OS:
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB}

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by archeedev** [comment]
Exactly the same problem here - upvote!
