### ISSUE TITLE
Request size exceeded

### ISSUE THREAD

**Issue by upaneshpatel** [microsoft/Microsoft365DSC#2520]
So when I export all of "Exchange" data from SOURCE and try to import (eg. Start-dscconfig), I get below error of "Exceeded size". As we have a lot of metadata in our PROD (source) tenant and would like to replicate in a single shot or keep both "SOURCE" & "TARGET" in sync, I would need the ability to have a single file rather than dividing up the files into Many (reduce administration).

### **What parameter can I use to increase the "Request size" on the destination? 

One Caveat: The destination (TARGET) tenant is personal trial tenant for testing - would this affect this error vs having a Corporate tenant?**

![image](https://user-images.githubusercontent.com/116754276/200899459-51c8a2ca-76b6-4ff5-b243-276a9cd1b51b.png)

**Comment by malauter** [comment]
Please try to increase the MaxEnvelopeSize:
`Set-Item -Path WSMan:\localhost\MaxEnvelopeSizeKb -Value 2048`

More information: https://github.com/dsccommunity/SharePointDsc/wiki/Error-Exceeded-the-configured-MaxEnvelopeSize-quota

**Comment by upaneshpatel** [comment]
Thank you so much.
