### ISSUE TITLE
Start-DSCConfiguration - IntuneASRRulesPolicyWindows10 & IntuneDeviceConfigurationPolicyWindows10 Errors

### ISSUE THREAD

**Issue by MichealKennard** [microsoft/Microsoft365DSC#2527]
#### Details of the scenario you tried and the problem that is occurring
Exported Intune settings from test tenant, compiled and now pushing to another test tenant. Errors generated when it hits components specified, looks to cause a break and nothing gets created.

#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/116776712/201170348-602e8b5a-1201-4774-9978-813dc41ac976.png)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Powershell ISE
# insert configuration here
IntuneASRRulesPolicyWindows10 a27c5111-0b37-45c9-8c82-20b455ba5d5d
        {
            AdobeReaderLaunchChildProcess                   = "auditMode";
            AdvancedRansomewareProtectionType               = "enable";
            Assignments                                     = @();
            AttackSurfaceReductionExcludedPaths             = @("c:\Novo");
            BlockPersistenceThroughWmiType                  = "userDefined";
            Credential                                      = $Credscredential;
            DisplayName                                     = "test";
            EmailContentExecutionType                       = "auditMode";
            Ensure                                          = "Present";
            GuardMyFoldersType                              = "enable";
            Identity                                        = "6d211fc3-b145-4767-b9e7-32e87ef89399";
            OfficeAppsExecutableContentCreationOrLaunchType = "block";
            OfficeAppsLaunchChildProcessType                = "auditMode";
            OfficeAppsOtherProcessInjectionType             = "block";
            OfficeCommunicationAppsLaunchChildProcess       = "auditMode";
            OfficeMacroCodeAllowWin32ImportsType            = "block";
            PreventCredentialStealingType                   = "enable";
            ProcessCreationType                             = "block";
            ScriptDownloadedPayloadExecutionType            = "block";
            ScriptObfuscatedMacroCodeType                   = "block";
            UntrustedExecutableType                         = "block";
            UntrustedUSBProcessType                         = "block";
        }

IntuneDeviceConfigurationPolicyWindows10 5665de44-01bd-4a40-a72c-fe5cdfe315fe
        {
            AccountsBlockAddingNonMicrosoftAccountEmail          = $True;
            AntiTheftModeBlocked                                 = $False;
            AppsAllowTrustedAppsSideloading                      = "blocked";
            AppsBlockWindowsStoreOriginatedApps                  = $False;
            Assignments                                          = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.allLicensedUsersAssignmentTarget'
                });
            BluetoothAllowedServices                             = @();
            BluetoothBlockAdvertising                            = $False;
            BluetoothBlockDiscoverableMode                       = $False;
            BluetoothBlocked                                     = $False;
            BluetoothBlockPrePairing                             = $False;
            CameraBlocked                                        = $False;
            CellularBlockDataWhenRoaming                         = $False;
            CellularBlockVpn                                     = $False;
            CellularBlockVpnWhenRoaming                          = $False;
            CertificatesBlockManualRootCertificateInstallation   = $False;
            ConnectedDevicesServiceBlocked                       = $False;
            CopyPasteBlocked                                     = $False;
            CortanaBlocked                                       = $False;
            Credential                                           = $Credscredential;
            DefenderBlockEndUserAccess                           = $False;
            DefenderCloudBlockLevel                              = "highPlus";
            DefenderDaysBeforeDeletingQuarantinedMalware         = 0;
            DefenderDetectedMalwareActions                       = MSFT_IntuneDefenderDetectedMalwareActions {
                LowSeverity       = 'remove'
                ModerateSeverity  = 'remove'
                HighSeverity      = 'remove'
                SevereSeverity    = 'remove'
            }
;
            DefenderFileExtensionsToExclude                      = @();
            DefenderFilesAndFoldersToExclude                     = @();
            DefenderMonitorFileActivity                          = "userDefined";
            DefenderProcessesToExclude                           = @();
            DefenderPromptForSampleSubmission                    = "sendAllDataWithoutPrompting";
            DefenderRequireBehaviorMonitoring                    = $True;
            DefenderRequireCloudProtection                       = $True;
            DefenderRequireNetworkInspectionSystem               = $True;
            DefenderRequireRealTimeMonitoring                    = $True;
            DefenderScanArchiveFiles                             = $True;
            DefenderScanDownloads                                = $True;
            DefenderScanIncomingMail                             = $True;
            DefenderScanMappedNetworkDrivesDuringFullScan        = $False;
            DefenderScanMaxCpu                                   = 40;
            DefenderScanNetworkFiles                             = $True;
            DefenderScanRemovableDrivesDuringFullScan            = $True;
            DefenderScanScriptsLoadedInInternetExplorer          = $True;
            DefenderScanType                                     = "userDefined";
            DefenderScheduledQuickScanTime                       = "12:00:00.0000000";
            DefenderSignatureUpdateIntervalInHours               = 12;
            DefenderSystemScanSchedule                           = "userDefined";
            DeveloperUnlockSetting                               = "blocked";
            DeviceManagementBlockFactoryResetOnMobile            = $False;
            DeviceManagementBlockManualUnenroll                  = $True;
            DiagnosticsDataSubmissionMode                        = "userDefined";
            DisplayName                                          = "Win 10 Device Restrictions";
            EdgeAllowStartPagesModification                      = $False;
            EdgeBlockAccessToAboutFlags                          = $False;
            EdgeBlockAddressBarDropdown                          = $False;
            EdgeBlockAutofill                                    = $False;
            EdgeBlockCompatibilityList                           = $False;
            EdgeBlockDeveloperTools                              = $False;
            EdgeBlocked                                          = $False;
            EdgeBlockExtensions                                  = $False;
            EdgeBlockInPrivateBrowsing                           = $False;
            EdgeBlockJavaScript                                  = $False;
            EdgeBlockLiveTileDataCollection                      = $False;
            EdgeBlockPasswordManager                             = $False;
            EdgeBlockPopups                                      = $False;
            EdgeBlockSearchSuggestions                           = $False;
            EdgeBlockSendingDoNotTrackHeader                     = $False;
            EdgeBlockSendingIntranetTrafficToInternetExplorer    = $False;
            EdgeClearBrowsingDataOnExit                          = $False;
            EdgeCookiePolicy                                     = "userDefined";
            EdgeDisableFirstRunPage                              = $False;
            EdgeHomepageUrls                                     = @();
            EdgeRequireSmartScreen                               = $True;
            EdgeSendIntranetTrafficToInternetExplorer            = $False;
            EdgeSyncFavoritesWithInternetExplorer                = $False;
            Ensure                                               = "Present";
            ExperienceBlockDeviceDiscovery                       = $False;
            ExperienceBlockErrorDialogWhenNoSIM                  = $False;
            ExperienceBlockTaskSwitcher                          = $False;
            GameDvrBlocked                                       = $True;
            InternetSharingBlocked                               = $True;
            LocationServicesBlocked                              = $False;
            LockScreenAllowTimeoutConfiguration                  = $False;
            LockScreenBlockActionCenterNotifications             = $False;
            LockScreenBlockCortana                               = $True;
            LockScreenBlockToastNotifications                    = $True;
            LogonBlockFastUserSwitching                          = $False;
            MicrosoftAccountBlocked                              = $False;
            MicrosoftAccountBlockSettingsSync                    = $False;
            NetworkProxyApplySettingsDeviceWide                  = $False;
            NetworkProxyDisableAutoDetect                        = $False;
            NfcBlocked                                           = $True;
            OneDriveDisableFileSync                              = $False;
            PasswordBlockSimple                                  = $False;
            PasswordRequired                                     = $False;
            PasswordRequiredType                                 = "deviceDefault";
            PasswordRequireWhenResumeFromIdleState               = $False;
            PrivacyAdvertisingId                                 = "notConfigured";
            PrivacyAutoAcceptPairingAndConsentPrompts            = $False;
            PrivacyBlockInputPersonalization                     = $False;
            ResetProtectionModeBlocked                           = $False;
            SafeSearchFilter                                     = "userDefined";
            ScreenCaptureBlocked                                 = $True;
            SearchBlockDiacritics                                = $False;
            SearchDisableAutoLanguageDetection                   = $False;
            SearchDisableIndexerBackoff                          = $False;
            SearchDisableIndexingEncryptedItems                  = $False;
            SearchDisableIndexingRemovableDrive                  = $True;
            SearchEnableAutomaticIndexSizeManangement            = $False;
            SearchEnableRemoteQueries                            = $False;
            SettingsBlockAccountsPage                            = $False;
            SettingsBlockAddProvisioningPackage                  = $True;
            SettingsBlockAppsPage                                = $False;
            SettingsBlockChangeLanguage                          = $False;
            SettingsBlockChangePowerSleep                        = $False;
            SettingsBlockChangeRegion                            = $False;
            SettingsBlockChangeSystemTime                        = $False;
            SettingsBlockDevicesPage                             = $False;
            SettingsBlockEaseOfAccessPage                        = $False;
            SettingsBlockEditDeviceName                          = $False;
            SettingsBlockGamingPage                              = $True;
            SettingsBlockNetworkInternetPage                     = $False;
            SettingsBlockPersonalizationPage                     = $False;
            SettingsBlockPrivacyPage                             = $True;
            SettingsBlockRemoveProvisioningPackage               = $True;
            SettingsBlockSettingsApp                             = $False;
            SettingsBlockSystemPage                              = $False;
            SettingsBlockTimeLanguagePage                        = $False;
            SettingsBlockUpdateSecurityPage                      = $False;
            SharedUserAppDataAllowed                             = $False;
            SmartScreenBlockPromptOverride                       = $True;
            SmartScreenBlockPromptOverrideForFiles               = $True;
            SmartScreenEnableAppInstallControl                   = $False;
            StartBlockUnpinningAppsFromTaskbar                   = $False;
            StartMenuAppListVisibility                           = "userDefined";
            StartMenuHideChangeAccountSettings                   = $False;
            StartMenuHideFrequentlyUsedApps                      = $False;
            StartMenuHideHibernate                               = $False;
            StartMenuHideLock                                    = $False;
            StartMenuHidePowerButton                             = $False;
            StartMenuHideRecentJumpLists                         = $False;
            StartMenuHideRecentlyAddedApps                       = $False;
            StartMenuHideRestartOptions                          = $False;
            StartMenuHideShutDown                                = $False;
            StartMenuHideSignOut                                 = $False;
            StartMenuHideSleep                                   = $False;
            StartMenuHideSwitchAccount                           = $False;
            StartMenuHideUserTile                                = $False;
            StartMenuMode                                        = "userDefined";
            StartMenuPinnedFolderDocuments                       = "notConfigured";
            StartMenuPinnedFolderDownloads                       = "notConfigured";
            StartMenuPinnedFolderFileExplorer                    = "notConfigured";
            StartMenuPinnedFolderHomeGroup                       = "notConfigured";
            StartMenuPinnedFolderMusic                           = "notConfigured";
            StartMenuPinnedFolderNetwork                         = "notConfigured";
            StartMenuPinnedFolderPersonalFolder                  = "notConfigured";
            StartMenuPinnedFolderPictures                        = "notConfigured";
            StartMenuPinnedFolderSettings                        = "notConfigured";
            StartMenuPinnedFolderVideos                          = "notConfigured";
            StorageBlockRemovableStorage                         = $False;
            StorageRequireMobileDeviceEncryption                 = $False;
            StorageRestrictAppDataToSystemVolume                 = $False;
            StorageRestrictAppInstallToSystemVolume              = $False;
            TenantLockdownRequireNetworkDuringOutOfBoxExperience = $True;
            UsbBlocked                                           = $False;
            VoiceRecordingBlocked                                = $False;
            WebRtcBlockLocalhostIpAddress                        = $False;
            WiFiBlockAutomaticConnectHotspots                    = $False;
            WiFiBlocked                                          = $False;
            WiFiBlockManualConfiguration                         = $False;
            WindowsSpotlightBlockConsumerSpecificFeatures        = $False;
            WindowsSpotlightBlocked                              = $True;
            WindowsSpotlightBlockOnActionCenter                  = $False;
            WindowsSpotlightBlockTailoredExperiences             = $False;
            WindowsSpotlightBlockThirdPartyNotifications         = $False;
            WindowsSpotlightBlockWelcomeExperience               = $False;
            WindowsSpotlightBlockWindowsTips                     = $False;
            WindowsSpotlightConfigureOnLockScreen                = "notConfigured";
            WindowsStoreBlockAutoUpdate                          = $False;
            WindowsStoreBlocked                                  = $False;
            WindowsStoreEnablePrivateStoreOnly                   = $True;
            WirelessDisplayBlockProjectionToThisDevice           = $True;
            WirelessDisplayBlockUserInputFromReceiver            = $False;
            WirelessDisplayRequirePinForPairing                  = $False;
        }

#### The operating system the target node is running
![image](https://user-images.githubusercontent.com/116776712/201170985-d9550b28-1708-46bd-88b8-1f4a1980b0a6.png)

#### Version of the DSC module that was used ('dev' if using current dev branch)
version 1.22.1102.1

**Comment by NikCharlebois** [comment]
@William-Francillette can you have a look? Thanks

**Comment by William-Francillette** [comment]
Sure will do

**Comment by William-Francillette** [comment]
I was able to trace the issue for IntuneASRRulesPolicyWindows10: all parameters need to be added when creating a new policy however when the policy was exported null parameters were not exported and thus failing during creation - also an issue with an array with a single element being converted to a string and thus failing during creation

I will fix this resource in my next PR

As for IntuneDeviceConfigurationPolicyWindows10, @MichealKennard could you share the error message for that one please
