### ISSUE TITLE
Start-DSCConfiguration - SCDLPCompliancePolicy & SCDLPComplianceRule

### ISSUE THREAD

**Issue by MichealKennard** [microsoft/Microsoft365DSC#2530]
#### Details of the scenario you tried and the problem that is occurring
Attempting push of configuration to test tenant, SC config continues to fail and break due to missing CMDLETS New-DLPCompliancePolicy and New-DLPComplianceRule (I imagine others as well)

#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/116776712/201210805-0bb4e4f9-5f35-4b10-a5c3-ce0280a0ce44.png)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Powershell ISE

# insert configuration here

[SecurityComplianceExport.zip](https://github.com/microsoft/Microsoft365DSC/files/9984813/SecurityComplianceExport.zip)

#### The operating system the target node is running
![image](https://user-images.githubusercontent.com/116776712/201211201-0fb012f5-2a81-4153-98de-983606178485.png)

#### Version of the DSC module that was used ('dev' if using current dev branch)
Version 1.22.1102.1

**Comment by NikCharlebois** [comment]
This is a permission or license related issue on the destination tenant. Please refer to the following article for additional details on the requirements to get access to these cmdlets.

https://learn.microsoft.com/en-us/powershell/module/exchange/get-dlpcompliancepolicy?view=exchange-ps
