### ISSUE TITLE
The Permission required for Security & Compliance Workload is empty.

### ISSUE THREAD

**Issue by NaveenRamakrish** [microsoft/Microsoft365DSC#2533]
The Permission required for Security & Compliance Workload is empty.  Using the command Get-M365DSCCompiledPermissionList -ResourceNameList to find all the required permission for the account to export the setting for Security Compliance, It does not return the permission required. 

Can you Check and let me know on this. 

-Naveen

**Comment by NikCharlebois** [comment]
This is because it doesn't support granular permissions but roles and only support credential base auth at the moment (release for app based is scheduled later this month). You are required to assign your account the security and compliance administrator roles. Thanks
