### ISSUE TITLE
If O365OrgCustomizationSetting can deploy O365-Orgsettings-Office Installation options

### ISSUE THREAD

**Issue by batehurry** [microsoft/Microsoft365DSC#2536]
Dear,

May I ask If Office365->O365OrgCustomizationSetting setting can support to deploy **O365 Admin Center->Org settings->Office Installation options**.
If it is support, what is the Parameters. 
Thanks.

**Comment by mlhickey** [comment]
MSFT_O365OrgCustomizationSetting only focuses on [**enabling** customization](https://learn.microsoft.com/en-us/powershell/module/exchange/enable-organizationcustomization?view=exchange-ps).

**Comment by batehurry** [comment]
> MSFT_O365OrgCustomizationSetting only focuses on [**enabling** customization](https://learn.microsoft.com/en-us/powershell/module/exchange/enable-organizationcustomization?view=exchange-ps), something that is a one-time-only action.

Thanks.
