### ISSUE TITLE
Export-M365DSCConfiguration : cannot extract information - "The term 'Save-Credentials' is not recognized..."

### ISSUE THREAD

**Issue by satakea1** [microsoft/Microsoft365DSC#2544]
#### Details of the scenario you tried and the problem that is occurring
I want to get the current tenant configuration, so I tried to run "Export-M365DSCConfiguration".
But cmdlet said "The term 'Save-Credentials' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again." and cannot get the result. 

#### Verbose logs showing the problem
Export-M365DSCConfiguration

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Cannot index into a null array.
New version of {DSCParser} is available
New version of {ExchangeOnlineManagement} is available {3.0.0}
New version of {Microsoft.Graph.Applications} is available {1.16.0}
New version of {Microsoft.Graph.Authentication} is available {1.16.0}
New version of {Microsoft.Graph.DeviceManagement} is available {1.16.0}
New version of {Microsoft.Graph.DeviceManagement.Administration} is available {1.16.0}
New version of {Microsoft.Graph.DeviceManagement.Enrolment} is available {1.16.0}
New version of {Microsoft.Graph.Devices.CorporateManagement} is available {1.16.0}
New version of {Microsoft.Graph.Groups} is available {1.16.0}
New version of {Microsoft.Graph.Identity.DirectoryManagement} is available {1.16.0}
New version of {Microsoft.Graph.Identity.Governance} is available {1.16.0}
New version of {Microsoft.Graph.Identity.SignIns} is available {1.16.0}
New version of {Microsoft.Graph.Planner} is available {1.16.0}
New version of {Microsoft.Graph.Teams} is available {1.16.0}
New version of {Microsoft.Graph.Users} is available {1.16.0}
New version of {Microsoft.Graph.Users.Actions} is available {1.16.0}
New version of {Microsoft.PowerApps.Administration.PowerShell} is available {2.0.154}
New version of {MicrosoftTeams} is available {4.9.1}
New version of {ReverseDSC} is available {2.0.0.13}
Exporting Microsoft 365 configuration for Mode: Default

Authentication methods specified:
- Credentials

The term 'Save-Credentials' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by mlhickey** [comment]
@satakea1 - that cmdlet is in the ReverseDSC module:

![image](https://user-images.githubusercontent.com/20215068/201973779-8a551ff3-c8b2-4261-beea-dfdca183aad6.png)

What happens if you try to load it directly:
Import-Module -Name ReverseDSC -Verbose -Force

**Comment by satakea1** [comment]
I can solve to update the DSC Module.　Update-M365DSCDependencies　　Thank you.
