### ISSUE TITLE
Enhancement: Test-M365DSCModuleValidity - add output

### ISSUE THREAD

**Issue by bstets1** [microsoft/Microsoft365DSC#2549]
#### Details of the scenario you tried and the problem that is occurring
When calling the Test-M365DSCModuleValidity module if there are updates present it write to console but you can not assign that module to a variable and use it in a script as it has no output. 

Example scenario, I want to use it in a unattended script that exports the config of a tenant once a month. If I can assign the output to a variable then I could use that variable to see check if not null then run Update-Module Microsoft365DSC and Update-M365DSCDependencies. 
Currently there is no output so even if this module writes to the console thee are updates available I can not do anything with it in an unattended script.

#### Verbose logs showing the problem
<img width="307" alt="image" src="https://user-images.githubusercontent.com/52285717/202256772-6c6842df-9280-4c79-bcf9-48c9bf310ca5.png">

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by andikrueger** [comment]
With the latest version of M365DSC there is a new function added: Update-M365DSCModule. This will update the Module itself, the dependencies and remove the updated stuff. Would this work in your scenario?

**Comment by bstets1** [comment]
yes it can, instead of doing a check to see if an update is available, then doing the update if it is, this function would do all of it in one, is what your saying. so in that case, this would do what I am looking for. Thanks.

**Comment by andikrueger** [comment]
Yes. That is the purpose of this function. 

Check if there is an update. If there is: run the full update and clean up.

**Comment by bstets1** [comment]
Awesome, thanks.
