### ISSUE TITLE
How to set Exchange permission using Service Principal

### ISSUE THREAD

**Issue by batehurry** [microsoft/Microsoft365DSC#2550]
Dear,

In the Exchange Permissions section of KB User Guide, "make sure your service account is a member of the specified Role Group or has been granted the required roles.".
Many time we use Service Principal to take snapshot of Exchange configurations. So, May I know how to set the Exchange Permissions when using Service Principal.

Thanks.

**Comment by NikCharlebois** [comment]
You will need to create a custom Exchange Role and assign it the required permissions. You can get a list of these permissions by running the following command:

```
Get-M365DSCCompiledPermissionList -ResourceNameList (Get-M365DSCAllResources | Where-Object -FilterScript {$_.StartsWith('EXO')}) -Source 'Exchange'
```
