### ISSUE TITLE
The License will get import on the target tenant or not 

### ISSUE THREAD

**Issue by rakeshsujan** [microsoft/Microsoft365DSC#2556]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by andikrueger** [comment]
Could elaborate a bit more, what this question is about? Thanks!

**Comment by rakeshsujan** [comment]
I want to import the configuration from source tenant to target tenant in that situation for user the License, user attributes, user member group also will get import or not?

**Comment by andikrueger** [comment]
There won’t be any licenses transferred from your source Tenant to the target tenant. 

The objects within the tenant depend on what you did export and therefore this will also determine what is going to be created/updated within your target tenant.

**Comment by rakeshsujan** [comment]
If i exported the Azure AD from source tenant and same thing i am importing into target tenant for user the License, user attributes, user member group will get assign or not. 

Because when i check the export configuration of source tenant i can see the user License details, user attributes etc., but when i try to import the same configuration in target tenant only the user it's get creating. 

Can you help me on this.  I have attached screenshot for your reference. 

![image](https://user-images.githubusercontent.com/50227412/202962604-a85a17da-2634-4c7f-9d46-3d5f381ac58a.png)

**Comment by andikrueger** [comment]
If you do have the same SKUs within your target tenant, M365 would try to assign the licenses to the user. If M365DSC is not able to find any licenses within the target tenant, no license assignment will happen.

This is the code, that would look for license:

```powershell
 #region Licenses
        if ($LicenseAssignment -ne $null)
        {
            [Array] $currentLicenses = $user.LicenseAssignment
            if ($null -eq $currentLicenses)
            {
                $currentLicenses = @()
            }
            $licenseDifferences  = Compare-Object -ReferenceObject $LicenseAssignment -DifferenceObject $currentLicenses
            if ($licensesDifferences.Length -gt 0)
            {
                $licenses = @{AddLicenses = @(); RemoveLicenses = @();}

                $SubscribedSku = Get-MgSubscribedSku
                foreach ($licenseSkuPart in $LicenseAssignment)
                {
                    Write-Verbose -Message "Adding License {$licenseSkuPart} to the Queue"
                    $license = @{
                        SkuId = ($SubscribedSku | Where-Object -Property SkuPartNumber -Value $licenseSkuPart -EQ).SkuID
                    }

                    # Set the Office license as the license we want to add in the $licenses object
                    $licenses.AddLicenses += $license
                }

                foreach ($currentLicense in $user.LicenseAssignment)
                {
                    if ($LicenseAssignment -and -not $LicenseAssignment.Contains($currentLicense))
                    {
                        Write-Verbose -Message "Removing {$currentLicense} from user {$UserPrincipalName}"
                        $license = @{
                            SkuId = ($SubscribedSku | Where-Object -Property SkuPartNumber -Value $currentLicense -EQ).SkuID
                        }
                        $licenses.RemoveLicenses += $license
                    }
                }
            }
        }
        #endregion
```

**Comment by rakeshsujan** [comment]
I replaced the SKU that is available in target tenant to assign to the user.

![image](https://user-images.githubusercontent.com/50227412/203057675-f12b380d-70d9-44d8-b9c6-a8af6e7df190.png)

Exported source configuration screenshot is as below.

![image](https://user-images.githubusercontent.com/50227412/203057926-a6c34867-cf67-4eb3-b75e-6e10589a2a99.png)

Modified in MOF file the screenshot is below.(replaced the SKU that existing in target tenant)

![image](https://user-images.githubusercontent.com/50227412/203058138-7748d646-38a7-44e8-a6b2-e30b826463e2.png)


Still the license is not getting assigned on the target tenant. 

Also noticed the licensed assignment function is getting pushed before getting the user. (logically it's not possible)

Manually i can modify for 1 or 2 users and also can add delay/wait in between creating user and license assignment but what if there are bulk users?

**Comment by andikrueger** [comment]
I just checked the code and the order of the operations is correct. Could you have a look at your event log to see, if something is reported there?

The user is created in line 484-501. License assignment will take place in lines 504-535.

**Comment by rakeshsujan** [comment]
But in the event log file i could not find anything wrong or it's marked as error or warning.

The below mentioned screenshot says that License assignment is empty even if i mark the correct license details in MOF file. 

![image](https://user-images.githubusercontent.com/50227412/203301337-34b3003f-52ae-4d5b-8e2a-506c0bf2abb7.png)
