### ISSUE TITLE
PnP.PowerShell required module?

### ISSUE THREAD

**Issue by William-Francillette** [microsoft/Microsoft365DSC#2563]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
Hi,

When trying to connect, I am requested to update, in my case install PnP.Powershell module 
When a resource check for dependencies it also reports a new version of PnP.Powershell is available 
![image](https://user-images.githubusercontent.com/79221284/202784121-26cabf1d-f2c8-473f-ab1a-3eb4bff5960c.png)

**Comment by andikrueger** [comment]
Are you running the Dev branch of the module? @NikCharlebois did see this message as well. This has to do with PR #2559. Obviously there is still an issue with the check being done. 

Could you run Get-Module PnP.PowerShell -listavailable ?

**Comment by William-Francillette** [comment]
Yes, that was from the Dev branch - I've installed the module to resolve the issue but didn't need PnP before

**Comment by William-Francillette** [comment]
I've also noticed that the dependencies check has increased the time for Start-DSCConfiguration to complete (especially when going through test-targetresource)

**Comment by andikrueger** [comment]
This check should have happen before. The code was somehow never run…

you would need all dependencies of M365DSC to run the module properly.
