### ISSUE TITLE
Microsoft365DSC @ YT and other things

### ISSUE THREAD

**Issue by archeedev** [microsoft/Microsoft365DSC#2573]
hi,
after longer break from M365 DSC (things worked well for me before) 
now I seem to struggle a bit with M365 DSC
Please point me in the correct direction if those have been answered 
or if those are valid issues, I'd appreciate some advice.

- Brand new WS2019, latest and up to date M365 DSC, no other modules.
- I use cert/thumbprint - no issues with that
- I have two AAD tenants, both have AAD App registered with the same cert
- OAuth permissions are ok
 

My questions / issues:
(I wish I could paste or attach screenshot here)

1. **YT: Episode 020 - Clone your Tenants**

That example does not seem to be valid anymore for the following reasons:

a. incorrect parameters for Export-M365DSCConfiguration (eg. GlobalAdminAccount does not exist, instead it is Credential now)

b. **O365User** - does not seem to exist

2. Is: AADUser <=> O365User ?
if it is then the cloning example does not work, 
I get errors - the DSC is unable to substitute source domain part of the UPN with the target domain.

Let's say I have following tenants:
source: src123.onmicrosoft.com
destination: dst123.onmicrosoft.com

`Creating new user with values: AccountEnabled=True; DisplayName=TestUser2; MailNickName=TestUser2; PasswordPolicies=None;
PasswordProfile={Password=TempP@ss}; UsageLocation=CH; UserPrincipalName=TestUser2@src123.onmicrosoft.com; UserType=Member
The domain portion of the userPrincipalName property is invalid. You must use one of the verified domain names in your organization.
    + CategoryInfo          : InvalidOperation: ({ body = Micros...softGraphUser }:) [], CimException
    + FullyQualifiedErrorId : Request_BadRequest,Microsoft.Graph.PowerShell.Cmdlets.NewMgUser_CreateExpanded1
    + PSComputerName        : localhost`

`The domain portion of the userPrincipalName property is invalid. You must use one of the verified domain names in your organization.`

3. **Export - errors**
`Export-M365DSCConfiguration -Components @("AADUser") -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId -Path .\_AADUser`

- the output is created all right but I get errors - why is that?:

`|---[21/21] TestUser2@src123.onmicrosoft.comGet-MgRoleManagementDirectoryRoleAssignment : Insufficient privileges to complete the operation.`
`At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1116.1\DSCResources\MSFT_AADUser\MSFT_AADUser.psm1:187 char:97`
`+ ... agementDirectoryRoleAssignment -Filter "PrincipalId eq '$($user.Id)'"`
`+                                                               ~~~~~~~~`
`    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType2`8) [Get-MgRoleManag...ssignment_List1], RestException`1`
`    + FullyQualifiedErrorId : Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgRoleManagementDirectoryRoleAssignment_List1`

My modules (all the above issues with ver. 1.16 as well - which is the default version currently):
`Version     Name												`
`-------     ----												`
`1.3.0.6     DSCParser											`
`3.0.0       ExchangeOnlineManagement							`
`1.17.0      Microsoft.Graph.Applications						`
`1.17.0      Microsoft.Graph.Authentication						`
`1.17.0      Microsoft.Graph.DeviceManagement					`
`1.17.0      Microsoft.Graph.DeviceManagement.Administration	`
`1.17.0      Microsoft.Graph.DeviceManagement.Enrolment			`
`1.17.0      Microsoft.Graph.Devices.CorporateManagement		`
`1.17.0      Microsoft.Graph.Groups								`
`1.17.0      Microsoft.Graph.Identity.DirectoryManagement		`
`1.17.0      Microsoft.Graph.Identity.Governance				`
`1.17.0      Microsoft.Graph.Identity.SignIns					`
`1.17.0      Microsoft.Graph.Planner							`
`1.17.0      Microsoft.Graph.Teams								`
`1.17.0      Microsoft.Graph.Users								`
`1.17.0      Microsoft.Graph.Users.Actions						`
`2.0.154     Microsoft.PowerApps.Administration.PowerShell		`
`1.22.1116.1 Microsoft365DSC									`
`4.9.1       MicrosoftTeams										`
`1.0.97      MSCloudLoginAssistant								`
`1.12.0      PnP.PowerShell										`
`2.0.0.13    ReverseDSC											`

**Comment by andikrueger** [comment]
At the moment, the website holds all guides and is the one, that would reflect the changes we made over the last versions.

www.microsoft365dsc.com

In regards to the videos: @NikCharlebois Could you update the description to "warn" the users about the changes...

Could you raise a separate issue for the AADUser Resource? This looks somehow familiar and I think, there was work done in regard to fixing this issue: #2489

**Comment by archeedev** [comment]
Thanks

**Comment by NikCharlebois** [comment]
1 - Videos were recorded before the October 2021 Major release so yes, the parameter names have changed I did add a mention in the video's description, but at this stage, we cannot go an update all videos and it is expected that some of the content will be subject to change every 6 months when we have a major release. For additional information on our major release policy, please refer to: https://microsoft365dsc.com/concepts/breaking-changes/

2 - O365User was renamed to AADUser in the October 2022 major release. More details here: https://microsoft365dsc.com/blog/october-2022-major-release/

3 - In order to extract AADUser your app registration needs to be granted the **User.Read.All** application permission. Can you confirm that this permission has been granted? Thanks

**Comment by archeedev** [comment]
1 - thanks, np, PS builtin intellisense to the rescue ;)
2 - ok it seemed so, in that case it is either me or as @andikrueger mentioned - something to do with the UPN conversion
3 - src: User.ReadWrite.All, dest: User.Read.All, User.ReadWrite.All

Will redo and update here.

**Comment by archeedev** [comment]
Sure thing, 
not a lot to redact - original version as it is, 
it is my test (standard free M365 Developer) tenant, with prepopulated users

[M365TenantConfig.zip](https://github.com/microsoft/Microsoft365DSC/files/10069569/M365TenantConfig.zip)

**Comment by NikCharlebois** [comment]
Is 371scx.onmicrosoft.com the source or destination tenant?

**Comment by archeedev** [comment]
I think **we close this**.
The RC and the challenge was to realize and identify correct Graph permissions.
Once set accounts got created.

This time I exported the config not by Components=AADUser (perhaps that would work too) 
but as 
`Export-M365DSCConfiguration -Credential $Global:Source -Workloads AAD`

Then I imported the resultant MOF, after compiling it with destination credentials.

Solution was that I had to specify permissions.


Since that is my test tenant I gave up looking for exact set of permissions and took all of them for AAD, which you can identify by running something like (here all workloads):
`Get-M365DSCCompiledPermissionList -ResourceNameList @("AADAdministrativeUnit", "AADApplication", "AADAuthorizationPolicy", "AADConditionalAccessPolicy", "AADEntitlementManagementAccessPackage", "AADEntitlementManagementAccessPackageCatalog", "AADEntitlementManagementAccessPackageCatalogResource", "AADGroup", "AADGroupLifecyclePolicy", "AADGroupsNamingPolicy", "AADGroupsSettings", "AADNamedLocationPolicy", "AADRoleDefinition", "AADRoleSetting", "AADSecurityDefaults", "AADServicePrincipal", "AADTenantDetails", "AADTokenLifetimePolicy", "AADUser") -Source 'Graph' -PermissionsType 'Delegated'`

So I connected to my tenant like this:

`Connect-MgGraph -Scopes AdministrativeUnit.ReadWrite.All, Directory.ReadWrite.All, RoleManagement.ReadWrite.Directory, Application.Read.All, Application.ReadWrite.All, Policy.ReadWrite.Authorization, Agreement.Read.All, Group.Read.All, Policy.Read.All, Policy.ReadWrite.ConditionalAccess, RoleManagement.Read.Directory, User.Read.All, EntitlementManagement.ReadWrite.All, Group.ReadWrite.All, Directory.Read.All, Organization.Read.All, Organization.ReadWrite.All, Policy.ReadWrite.ApplicationConfiguration, User.ReadWrite.All`

Consented for org.

Accounts got created.

I still got some errors during Start-DSC... but those did not break the account import and are probably related to licensing - which is ok.
![image](https://user-images.githubusercontent.com/25514862/204287558-b286345a-b3dd-430f-a46e-8e1b16fda6d2.png)

thanks!

**Comment by archeedev** [comment]
For completeness.
Pretty sure it has to do with licensing - which btw is a good thing because it may help identify expired or other problematic licensing situations.

![image](https://user-images.githubusercontent.com/25514862/204288908-d831c270-53b1-4645-8393-d1cd238b4601.png)

(Closing, I hope you do not mind)
