### ISSUE TITLE
Install fails when using linux docker container

### ISSUE THREAD

**Issue by leitzler** [microsoft/Microsoft365DSC#2575]
#### Details of the scenario you tried and the problem that is occurring
As per the getting started documentation I ran `Install-Module -Name Microsoft365DSC -Force` which seems to succeed (no output produced).

Then `Update-M365DSCDependencies` which doesn't work:
```Powershell
PS /> Update-M365DSCDependencies
Update-M365DSCDependencies: The 'Update-M365DSCDependencies' command was found in the module 'Microsoft365DSC', but the module could not be loaded. For more information, run 'Import-Module Microsoft365DSC'.
```

Trying the suggested command gives:
```Powershell
PS /> Import-Module Microsoft365DSC
Import-Module: The given assembly name or codebase was invalid. (0x80131047)
```

#### Verbose logs showing the problem
See above.

#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running
I've tried with both `mcr.microsoft.com/powershell:latest` (which is, at the time of writing, `PowerShell 7.2.7`) as well as a specific tag, `mcr.microsoft.com/powershell:7.1.5-alpine-3.13-20211021`. According to: https://github.com/microsoft/Microsoft365DSC/blob/ba583e60a6bfbfc0c3d086dff0612d36c31a29b3/docs/docs/user-guide/get-started/prerequisites.md?plain=1#L5 it should work with 7.1. Are there any other limitations?

#### Version of the DSC module that was used ('dev' if using current dev branch)
N/A

**Comment by andikrueger** [comment]
Could you try to use an windows based container?

**Comment by NikCharlebois** [comment]
As @andikrueger mentions above, Linux based containers are not supported, only windows at the moment. This is unfortunately a restriction we have due to some dependencies that still required DLLs.
