### ISSUE TITLE
Using DSC to read parameters from a file and apply new configs

### ISSUE THREAD

**Issue by nathanpinotti** [microsoft/Microsoft365DSC#2578]

**Comment by andikrueger** [comment]
Please provide a meaningful description for this issue.

**Comment by nathanpinotti** [comment]
Hi Andi. My bad

A simple example:
I'm a service provider. Let's supose I have a project where I need to create groups and Conditional Access on AzureAD.

Considering that each company has different naming convention, the ideia is collect the name of groups and details about ConditionalAccess in a file (CSV, XML, TXT...) and after that make DSC read this file and populate the infos needed, as variables (GroupName, MemberOf, etc). Is that possible?

Is there any other suggestion to achieve this goal?

**Comment by andikrueger** [comment]
You could more or less create this logic within DSC itself and use the capabilities of the configuration data file. Usually you would go through this configuration file and dynamically create the resources based on variables. 

This is a good resource to get started: 
https://learn.microsoft.com/en-us/powershell/dsc/configurations/configdata

**Comment by nathanpinotti** [comment]
Thanks Andi!
