### ISSUE TITLE
Error with AzureAD extract Module

### ISSUE THREAD

**Issue by nathanpinotti** [microsoft/Microsoft365DSC#2579]
#### Details of the scenario you tried and the problem that is occurring

Ran the below CmdLet as Global Admin to collect configration from AzureAD. The Generated file is basically blank and also got the errors showed in the follow sections

**File Resulted from the extract**
`# Generated with Microsoft365DSC version 1.22.1005.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $Credential
)

Configuration M365TenantConfig
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $Credential
    )

    if ($null -eq $Credential)
    {
        <# Credentials #>
        $Credscredential = Get-Credential -Message "Credentials"

    }
    else
    {
        $CredsCredential = $Credential
    }

    $OrganizationName = $CredsCredential.UserName.Split('@')[1]

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.22.1005.1'

    Node localhost
    {
        AADGroupsSettings 78d7de3e-c46b-4bcd-885b-59d7c9330967
        {
            Credential           = $Credscredential;
            Ensure               = "Absent";
            IsSingleInstance     = "Yes";
            ManagedIdentity      = False;
        }
        AADSecurityDefaults 90996206-6485-4ec0-a0bd-b9f2771f119a
        {
            Credential           = $Credscredential;
            IsSingleInstance     = "Yes";
            Managedidentity      = $False;
        }
    }
}

M365TenantConfig -ConfigurationData .\ConfigurationData.psd1 -Credential $Credential
`

#### Verbose logs showing the problem

[6/15] Extracting [AADGroupsNamingPolicy] using {Credentials}...Get-MgDirectorySetting : Insufficient privileges to complete the operation.
No C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1005.1\DSCResources\MSFT_AADGroupsNamingPolicy\MSFT_AADGroupsNamingPolicy.psm1:72
caractere:9
+         $Policy = Get-MgDirectorySetting | Where-Object -FilterScript ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType32`8) [Get-MgDirectorySetting_List], RestException`1
    + FullyQualifiedErrorId : Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgDirectorySetting_List
✅
[7/15] Extracting [AADGroupsSettings] using {Credentials}...Get-MgDirectorySetting : Insufficient privileges to complete the operation.
No C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1005.1\DSCResources\MSFT_AADGroupsSettings\MSFT_AADGroupsSettings.psm1:93 caractere:9
+         $Policy = Get-MgDirectorySetting | Where-Object -FilterScript ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType32`8) [Get-MgDirectorySetting_List], RestException`1
    + FullyQualifiedErrorId : Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgDirectorySetting_List
✅
[8/15] Extracting [AADNamedLocationPolicy] using {Credentials}...❌
[9/15] Extracting [AADRoleDefinition] using {Credentials}...❌
[10/15] Extracting [AADRoleSetting] using {Credentials}...Insufficient privileges to complete the operation.
❌
[11/15] Extracting [AADSecurityDefaults] using {Credentials}...Get-MgPolicyIdentitySecurityDefaultEnforcementPolicy : You cannot perform the requested operation, required scopes are missing in the token.
No C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1005.1\DSCResources\MSFT_AADSecurityDefaults\MSFT_AADSecurityDefaults.psm1:74
caractere:9
+         $defaults = Get-MgPolicyIdentitySecurityDefaultEnforcementPol ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Property = , ExpandProperty =  }:<>f__AnonymousType4`2) [Get-MgPolicyIde...mentPolicy_Get1], RestExcept
   ion`1
    + FullyQualifiedErrorId : AccessDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgPolicyIdentitySecurityDefaultEnforcementPolicy_Get1
✅
[12/15] Extracting [AADServicePrincipal] using {Credentials}...
❌
[13/15] Extracting [AADTenantDetails] using {Credentials}...❌
[14/15] Extracting [AADTokenLifetimePolicy] using {Credentials}...❌
[15/15] Extracting [AADUser] using {Credentials}...⌛ Export took {387 seconds}

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here

`# Generated by Microsoft365DSC from https://export.microsoft365dsc.com on 22/11/2022 17:23:36
# Visit https://microsoft365dsc.com for more information

# Getting client credential
$Credential = Get-Credential

# Exporting resources using credentials
Export-M365DSCConfiguration -Components @("AADAdministrativeUnit", "AADApplication", "AADAuthorizationPolicy", "AADConditionalAccessPolicy", "AADEntitlementManagementAccessPackage", "AADEntitlementManagementAccessPackageCatalog", "AADEntitlementManagementAccessPackageCatalogResource", "AADGroup", "AADGroupLifecyclePolicy", "AADGroupsNamingPolicy", "AADGroupsSettings", "AADNamedLocationPolicy", "AADRoleDefinition", "AADRoleSetting", "AADSecurityDefaults", "AADServicePrincipal", "AADTenantDetails", "AADTokenLifetimePolicy", "AADUser") -Credential $Credential`

```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Home Single Language
OsOperatingSystemSKU : 100
OsArchitecture       : 64 bits
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : pt-BR
OsMuiLanguages       : {pt-BR}

#### Version of the DSC module that was used ('dev' if using current dev branch)

`PS C:\temp> Get-Module Microsoft365DSC -ListAvailable | select ModuleBase, Version

ModuleBase                                                             Version
----------                                                             -------
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1116.1 1.22.1116.1
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1005.1 1.22.1005.1
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.921.1  1.22.921.1`

**Comment by andikrueger** [comment]
Please make sure to remove the outdated versions and dependencies:

uninstall-m365outdateddependencies

**Comment by nathanpinotti** [comment]
Tested trying to get just Conditional Access infos withou success

Take a look:
`PS C:\Windows\system32> Uninstall-M365DSCOutdatedDependencies
Uninstalling Microsoft365DSC Version {1.22.921.1}
Uninstalling ExchangeOnlineManagement Version {2.0.5}
Uninstalling Microsoft.Graph.Applications Version {1.11.1}
Uninstalling Microsoft.Graph.DeviceManagement Version {1.11.1}
Uninstalling Microsoft.Graph.DeviceManagement.Administration Version {1.11.1}
Uninstalling Microsoft.Graph.DeviceManagement.Enrolment Version {1.11.1}
Uninstalling Microsoft.Graph.Devices.CorporateManagement Version {1.11.1}
Uninstalling Microsoft.Graph.Groups Version {1.11.1}
Uninstalling Microsoft.Graph.Identity.DirectoryManagement Version {1.11.1}
Uninstalling Microsoft.Graph.Identity.Governance Version {1.11.1}
Uninstalling Microsoft.Graph.Identity.SignIns Version {1.11.1}
Uninstalling Microsoft.Graph.Planner Version {1.11.1}
Uninstalling Microsoft.Graph.Teams Version {1.11.1}
Uninstalling Microsoft.Graph.Users Version {1.11.1}
Uninstalling Microsoft.PowerApps.Administration.PowerShell Version {2.0.150}
Uninstalling MicrosoftTeams Version {4.7.0}
Uninstalling MSCloudLoginAssistant Version {1.0.89}
Uninstalling PnP.PowerShell Version {1.11.0}
Uninstalling ReverseDSC Version {2.0.0.12}
Checking Microsoft.Graph.Authentication
Uninstalling Microsoft.Graph.Authentication version {1.12.2}
Uninstalling Microsoft.Graph.Authentication version {1.11.1}

PS C:\Windows\system32> Update-M365DSCDependencies

PS C:\Windows\system32> Export-M365DSCConfiguration -Components @("AADConditionalAccessPolicy") -Credential $Credential
New version of {Microsoft.Graph.Applications} is available {1.17.0}
New version of {Microsoft.Graph.Authentication} is available {1.17.0}
New version of {Microsoft.Graph.DeviceManagement} is available {1.17.0}
New version of {Microsoft.Graph.DeviceManagement.Administration} is available {1.17.0}
New version of {Microsoft.Graph.DeviceManagement.Enrolment} is available {1.17.0}
New version of {Microsoft.Graph.Devices.CorporateManagement} is available {1.17.0}
New version of {Microsoft.Graph.Groups} is available {1.17.0}
New version of {Microsoft.Graph.Identity.DirectoryManagement} is available {1.17.0}
New version of {Microsoft.Graph.Identity.Governance} is available {1.17.0}
New version of {Microsoft.Graph.Identity.SignIns} is available {1.17.0}
New version of {Microsoft.Graph.Planner} is available {1.17.0}
New version of {Microsoft.Graph.Teams} is available {1.17.0}
New version of {Microsoft.Graph.Users} is available {1.17.0}
New version of {Microsoft.Graph.Users.Actions} is available {1.17.0}
New version of {MSCloudLoginAssistant} is available {1.0.98}
Exporting Microsoft 365 configuration for Components: AADConditionalAccessPolicy

Authentication methods specified:
- Credentials

Connecting to {MicrosoftGraph}...✅
[1/1] Extracting [AADConditionalAccessPolicy] using {Credentials}...❌
⌛ Export took {6 seconds}

Destination Path: C:\temp\M365-CA_2`

The file exported is blank. I got 3 CA configured

`# Generated with Microsoft365DSC version 1.22.1116.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $Credential
)

Configuration M365TenantConfig
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $Credential
    )

    if ($null -eq $Credential)
    {
        <# Credentials #>
        $Credscredential = Get-Credential -Message "Credentials"

    }
    else
    {
        $CredsCredential = $Credential
    }

    $OrganizationName = $CredsCredential.UserName.Split('@')[1]

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.22.1116.1'

    Node localhost
    {
    }
}

M365TenantConfig -ConfigurationData .\ConfigurationData.psd1 -Credential $Credential
`

![image](https://user-images.githubusercontent.com/16733319/203454025-ccaf6ae9-bed8-4ef2-a1df-312c83d9b098.png)

**Comment by mlhickey** [comment]
What happens when you run the underlying Microsoft Graph PowerShell cmdlet?
```
Get-MgIdentityConditionalAccessPolicy
```
If your account **and** the endpoint are correctly permissioned then you should retrieve the list of CA policies in your tenant.

**Comment by andikrueger** [comment]
As @mlhickey said: Please make sure your account has appropriate permissions. The export log shows an error for the authentication with your account. 

Could you please run the cmdLets for uninstalling the outdated dependencies again without the update afterwards. Usually you would run

update-m365dscmodule 

or

update-module microsoft365dsc 
Update-m365dscdependencies 
Uninstall-m365dscoutdateddependencies

**Comment by nathanpinotti** [comment]
Hi all
@mlhickey tried running the Graph CmdLet and, after connection to MSGraph with -Scope Policy.Read.All using the same Global Admin account I was able to get the policies;

`PS C:\Users\natha> Connect-MgGraph -Scopes 'Policy.Read.All'
Welcome To Microsoft Graph!
PS C:\Users\natha> Get-MgIdentityConditionalAccessPolicy

Id                                   CreatedDateTime     Description DisplayName                 ModifiedDateTime    State
--                                   ---------------     ----------- -----------                 ----------------    -----
2f45709e-dc3f-42f7-b535-02a285709331 14/07/2022 18:29:58             CA: Block Teams             23/11/2022 01:38:56 enabled
d8cb128a-0d93-435f-8648-f54a3420d55b 14/07/2022 19:37:40             CA: Force Registered Device 23/11/2022 01:39:03 enabledForReportingButNotEnforced
9939dd86-0a3e-470c-8f3f-062c57ca5608 22/11/2022 01:07:14             Terms of Use                22/11/2022 01:09:42 enabled
`

@andikrueger even after removing the outdate dependencies I've got some errors (find below). Now I could have a file with informations, but still getting permissions and MSGraph missed scopes using M365DSC Export cmdlet.

Not sure, but, shouldn't the module include all needed Scopes?

`PS C:\Users\natha> Export-M365DSCConfiguration -Components @("AADAdministrativeUnit", "AADApplication", "AADAuthorizationPolicy", "AADConditionalAccessPolicy", "AADEntitlementManagementAccessPackage", "AADEntitlementManagementAccessPackageCatalog", "AADEntitlementManagementAccessPackageCatalogResource", "AADGroup", "AADGroupLifecyclePolicy", "AADGroupsNamingPolicy", "AADGroupsSettings", "AADNamedLocationPolicy", "AADRoleDefinition", "AADRoleSetting", "AADSecurityDefaults", "AADServicePrincipal", "AADTenantDetails", "AADTokenLifetimePolicy", "AADUser") -Credential $Credential
New version of {Microsoft.Graph.Applications} is available {1.17.0}
New version of {Microsoft.Graph.Authentication} is available {1.17.0}
New version of {Microsoft.Graph.DeviceManagement} is available {1.17.0}
New version of {Microsoft.Graph.DeviceManagement.Administration} is available {1.17.0}
New version of {Microsoft.Graph.DeviceManagement.Enrolment} is available {1.17.0}
New version of {Microsoft.Graph.Devices.CorporateManagement} is available {1.17.0}
New version of {Microsoft.Graph.Groups} is available {1.17.0}
New version of {Microsoft.Graph.Identity.DirectoryManagement} is available {1.17.0}
New version of {Microsoft.Graph.Identity.Governance} is available {1.17.0}
New version of {Microsoft.Graph.Identity.SignIns} is available {1.17.0}
New version of {Microsoft.Graph.Planner} is available {1.17.0}
New version of {Microsoft.Graph.Teams} is available {1.17.0}
New version of {Microsoft.Graph.Users} is available {1.17.0}
New version of {Microsoft.Graph.Users.Actions} is available {1.17.0}
New version of {Microsoft.PowerApps.Administration.PowerShell} is available {2.0.154}
New version of {MicrosoftTeams} is available {4.9.1}
New version of {MSCloudLoginAssistant} is available {1.0.98}
New version of {PnP.PowerShell} is available {1.12.0}
New version of {ReverseDSC} is available {2.0.0.13}
Exporting Microsoft 365 configuration for Components: AADAdministrativeUnit, AADApplication, AADAuthorizationPolicy, AADConditionalAccessPolicy, AADEntitlementManagementAccessPackage, AADEntitlementManagementAccessPackageCatalog, AADEntitlementManagementAccessPackageCatalogResource, AADGroup, AADGroupLifecyclePolicy, AADGroupsNamingPolicy, AADGroupsSettings, AADNamedLocationPolicy, AADRoleDefinition, AADRoleSetting, AADSecurityDefaults, AADServicePrincipal, AADTenantDetails, AADTokenLifetimePolicy, AADUser

Authentication methods specified:
- Credentials

Connecting to {MicrosoftGraph}...✅
[1/19] Extracting [AADAdministrativeUnit] using {Credentials}...❌
❌
[2/19] Extracting [AADApplication] using {Credentials}...
❌
[3/19] Extracting [AADAuthorizationPolicy] using {Credentials}...
    |---[1/1] Authorization Policy✅
[4/19] Extracting [AADConditionalAccessPolicy] using {Credentials}...
    |---[1/3] CA: Block TeamsGet-MgGroup : Insufficient privileges to complete the operation.
No C:\Program
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1116.1\DSCResources\MSFT_AADConditionalAccessPolicy\MSFT_AADConditionalAccessPolicy.psm1:361
caractere:21
+ ...             $IncludeGroup = (Get-MgGroup -GroupId $IncludeGroupGUID). ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ GroupId = ebb...ndProperty =  }:<>f__AnonymousType35`3) [Get-MgGroup_Get], RestException`1
    + FullyQualifiedErrorId : Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_Get
✅
    |---[2/3] CA: Force Registered DeviceGet-MgGroup : Insufficient privileges to complete the operation.
No C:\Program
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1116.1\DSCResources\MSFT_AADConditionalAccessPolicy\MSFT_AADConditionalAccessPolicy.psm1:361
caractere:21
+ ...             $IncludeGroup = (Get-MgGroup -GroupId $IncludeGroupGUID). ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ GroupId = ebb...ndProperty =  }:<>f__AnonymousType35`3) [Get-MgGroup_Get], RestException`1
    + FullyQualifiedErrorId : Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_Get
✅
    |---[3/3] Terms of UseGet-MgAgreement : User does not have any of the required scopes: user_impersonation, Agreement.Read.All, Agreement.ReadWrite.All
No C:\Program
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1116.1\DSCResources\MSFT_AADConditionalAccessPolicy\MSFT_AADConditionalAccessPolicy.psm1:646
caractere:13
+             $termofUse = Get-MgAgreement | Where-Object -FilterScript ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Search = , Property =  }:<>f__AnonymousType26`2) [Get-MgAgreement_List], RestException`1
    + FullyQualifiedErrorId : UnauthorizedAccess,Microsoft.Graph.PowerShell.Cmdlets.GetMgAgreement_List
✅
[5/19] Extracting [AADEntitlementManagementAccessPackage] using {Credentials}...✅
❌
[6/19] Extracting [AADEntitlementManagementAccessPackageCatalog] using {Credentials}...✅
❌
[7/19] Extracting [AADEntitlementManagementAccessPackageCatalogResource] using {Credentials}...✅
❌
[8/19] Extracting [AADGroup] using {Credentials}...❌
[9/19] Extracting [AADGroupLifecyclePolicy] using {Credentials}...✅
[10/19] Extracting [AADGroupsNamingPolicy] using {Credentials}...✅
[11/19] Extracting [AADGroupsSettings] using {Credentials}...✅
[12/19] Extracting [AADNamedLocationPolicy] using {Credentials}...
    |---[1/1] TEST-NAMED-BR✅
[13/19] Extracting [AADRoleDefinition] using {Credentials}...❌
[14/19] Extracting [AADRoleSetting] using {Credentials}...Insufficient privileges to complete the operation.
❌
[15/19] Extracting [AADSecurityDefaults] using {Credentials}...✅
[16/19] Extracting [AADServicePrincipal] using {Credentials}...
❌
[17/19] Extracting [AADTenantDetails] using {Credentials}...✅
[18/19] Extracting [AADTokenLifetimePolicy] using {Credentials}...✅
[19/19] Extracting [AADUser] using {Credentials}...⌛ Export took {141 seconds}`

**Comment by nathanpinotti** [comment]
Any suggestion here, guys?

**Comment by mlhickey** [comment]
Seeing all the different Insufficient privileges makes me think the endpoint hasn't been completely consented.  If you're using the default endpoint for the Microsoft Graph PowerShell SDK (appid 14d82eec-204b-4c2f-b7e8-296a70dab67e) you may need to do additional consent work based on the desired workloads.  

You can grab all the AAD workload perms doing something like:
```
        $installedPath = @(Get-Module Microsoft365DSC -ListAvailable | Sort-Object Version -Descending).Path | Split-Path
        if ($installedPath.Count -gt 1)
        {
            $installedPath = $installedPath[0]
        }
        $resourceList = ((Get-ChildItem -Path ("$installedPath\DSCResources\") -Directory).Name -match "AAD") -replace 'MSFT_', ''
        $allPerms = Get-M365DSCCompiledPermissionList -ResourceNameList $resourceList -Source 'Graph' -PermissionsType Delegated
```

**Comment by nathanpinotti** [comment]
@mlhickey got your point but, shouldn't this be part of the M365DSC solution?

I understand that, using a Global Admin account with DSC Module up to date, it should include all pre-reqs to get the informations requested by the export cmdlet.

Regards

**Comment by mlhickey** [comment]
@nathanpinotti -  This is a snippet that I use for assigning perms for managed identities.  They do provide a cmdlet -  - [Update-M365DSCAllowedGraphScopes](https://microsoft365dsc.com/user-guide/cmdlets/Update-M365DSCAllowedGraphScopes/) for managing this, listed in Microsoft Graph , I've just never had occasion to use it.

**Comment by nathanpinotti** [comment]
@mlhickey thanks for you help! Worked like a charm.

Maybe this cmdlet should be parte of the pre-check for any "get" using M365DSC.


Thanks again
