### ISSUE TITLE
MultiTenantApp Registration

### ISSUE THREAD

**Issue by JonasCordsen** [microsoft/Microsoft365DSC#2586]
### Description

We would like to be able to using one multi tenant app registration in our tenant, then add permissions to the app in the customers tenant, and run the Microsoft365DSC from one place for more customers.

**Comment by andikrueger** [comment]
This is absolutely doable. What kind of information are you missing?

**Comment by JonasCordsen** [comment]
Great!
Just can't seem to make it work.
We use app registration with app secret
We have invited the app in.

What App id should I specify? The app ID from my tenant or should it be the App ID in the customer tenant?

When I do the deployment(with Customer App ID):
{"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '2e8528b9-d1a0-4931-8b8c-b5f7992c5f08'.\r\nTrace ID: 6cf38e82-5628-47d0-ae28-d4bff3cb5300\r\nCorrelation ID: 4d2619d2-399a-4d19-b141-375576b41f71\r\nTimestamp: 2022-11-24 10:12:51Z","error_codes":[7000215],"timestamp":"2022-11-24 10:12:51Z","trace_id":"6cf38e82-5628-47d0-ae28-d4bff3cb5300","correlation_id":"4d2619d2-399a-4d19-b141-375576b41f71","error_uri":"https://login.microsoftonline.com/error?code=7000215"}

When I do the deployment(with Our App ID):
##[error]Drifts after the DSC enforce was found in: AzureAD - refer to the report for more details
##[error]Application was not found! make sure that the applicationID: *** is correct
##[error]PowerShell exited with code '1'.

**Comment by andikrueger** [comment]
You need construct a admin consent url for your app and use this to add the app within the other tenant:

https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-admin-consent

this way your app will be properly integrated into the other AAD. 

after that you will be able to connect to the other tenant by using your app authentication method with the other tenant id.

**Comment by JonasCordsen** [comment]
Hello

I see this error:
contact site at the specified URL [https://xxx-admin.sharepoint.com/.](https://xxx-admin.sharepoint.com/) The app principal does not exist.
It should be said that it seems to only be the SPO

**Comment by andikrueger** [comment]
What kind of permissions did you grant this application? This looks like a permission issue.

**Comment by JonasCordsen** [comment]
It has Sites.FullControl.All permissions on Sharepoint

**Comment by andikrueger** [comment]
Did you grant Admin Consent for these permissions?

Within the Enterprise App it should look like this:
![image](https://user-images.githubusercontent.com/15608729/205900925-fc3bc1ef-dd19-4f6b-9d71-63bcc5ca2b5d.png)

**Comment by JonasCordsen** [comment]
Jep, that is done:

MultiTenant App:
![Screenshot 2022-12-06 at 12 36 12](https://user-images.githubusercontent.com/106592722/205901705-3c57220a-08eb-4a74-aeab-590fa636bec2.png)

Enterprise app with the customer Tenant:
![Screenshot 2022-12-06 at 12 36 57](https://user-images.githubusercontent.com/106592722/205901713-d8efbb98-f954-4e59-9d03-049135f598e0.png)

**Comment by andikrueger** [comment]
Are you using a certificate or secret for authentication? Certificate based should work...

**Comment by JonasCordsen** [comment]
We use secret, it did work before, with "normal" app reg

**Comment by andikrueger** [comment]
Any chance to test it with a certificate? You could use this cmdLet to create a certificate: https://microsoft365dsc.com/user-guide/cmdlets/Update-M365DSCAzureAdApplication/

**Comment by JonasCordsen** [comment]
Hello again, I have successfully done it with the certificate, so permissions should be good

**Comment by andikrueger** [comment]
Thanks for the feedback! I’ll close this one for now.

**Comment by JonasCordsen** [comment]
So it is be design?
It is not supposed/able to work with secret?
