### ISSUE TITLE
Group members not adding & DL group not get creating

### ISSUE THREAD

**Issue by rakeshsujan** [microsoft/Microsoft365DSC#2587]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by andikrueger** [comment]
Please share full information as outlined by the issue template. Thanks.

**Comment by rakeshsujan** [comment]
When we import the o365, Security group the groups are get creating but the owner & member of the group is not getting assigning.

Find the below screenshot for your referance.

![image](https://user-images.githubusercontent.com/50227412/203766045-10ac6716-51e6-412a-be47-a2822d2fa670.png)

As well as the DL group is not get creating and giving out with below error. 

![image](https://user-images.githubusercontent.com/50227412/203766403-4613a476-b7ec-4313-bdd0-3bfb6b8866ce.png)

**Comment by andikrueger** [comment]
Could you share your configuration. Please redact any personal information like passwords,...

**Comment by rakeshsujan** [comment]
Please find the below file has been attached

[M365TenantConfig.zip](https://github.com/microsoft/Microsoft365DSC/files/10084588/M365TenantConfig.zip)

**Comment by NikCharlebois** [comment]
Microsoft Graph cannot create DL or mail-enabled security groups. My recommendation would be to filter these out of the export process to avoid confusion. Thoughts?

**Comment by andikrueger** [comment]
Does not solve the problem, but would help to reduce confusion - As long as there are some verbose messages about these groups being not part of the export.

**Comment by NikCharlebois** [comment]
Trying to think through what other options could be. I don't think there are any, keeping in mind that Microsoft Graph is what is driving this resource under the cover.
