### ISSUE TITLE
Documentation website is confused

### ISSUE THREAD

**Issue by KlaBier** [microsoft/Microsoft365DSC#2590]
Hi everyone,
not really a problem with the tool, more with the documentation. When I navigate thru the page "What is M365DSC" and then open "monitor" or "automating" pages, each of them looks confused. Tried it on a mac and windows withe several browser.

Is this problem related here to my computer/browser? Or is there a problem with the pages

Thanks :-)

Klaus

**Comment by andikrueger** [comment]
Ups... Thanks for letting us know.

https://microsoft365dsc.com/user-guide/get-started/complete-story/#deploying-configurations
should be
https://microsoft365dsc.com/user-guide/get-started/deploying-configurations/

https://microsoft365dsc.com/user-guide/get-started/complete-story/#monitoring-for-configuration-drifts
should be 
https://microsoft365dsc.com/user-guide/get-started/monitoring-drifts/


I'll create a fix.

**Comment by KlaBier** [comment]
Thanks a lot.

I have seen that this page have the same issue:
https://microsoft365dsc.com/user-guide/get-started <https://microsoft365dsc.com/user-guide/get-started>/complete-story/#taking-a-snapshot-of-existing-tenant <https://microsoft365dsc.com/user-guide/get-started/complete-story/#taking-a-snapshot-of-existing-tenant>

Regards
Klaus

**Comment by andikrueger** [comment]
There were some more links broken. I updated all links within the file.
