### ISSUE TITLE
Installation fails on nanoserver based container

### ISSUE THREAD

**Issue by leitzler** [microsoft/Microsoft365DSC#2595]
#### Details of the scenario you tried and the problem that is occurring
I tried to install the module in a nanoserver based container. The publisher check fails, but even when bypassing it I end up with `Access is denied.`.

The default user in nanoserver should have sufficient permissions according to https://github.com/PowerShell/PowerShell/issues/17645#issuecomment-1219735817.

#### Verbose logs showing the problem
```powershell
PowerShell 7.2.2
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\> Install-Module Microsoft365DSC

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the
Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
Install-Package: The module 'Microsoft365DSC' cannot be installed or updated because the authenticode signature of the file 'Microsoft365DSC.psd1'
is not valid.

PS C:\> Install-Module Microsoft365DSC -SkipPublisherCheck

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the
Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
Install-Package: Access is denied.

PS C:\>
```
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by andikrueger** [comment]
I looked into nano server setups as well. Nano server lacks to many essential parts for M365DSC. 

At the moment, you could either use a full server image or windows server core.

As an alternative, it is worth looking into Azure Automation Accounts with Runbooks.
