### ISSUE TITLE
MSFT_AADGroup: Bug in group based licensing

### ISSUE THREAD

**Issue by andreasmarx** [microsoft/Microsoft365DSC#2597]
#### Details of the scenario you tried and the problem that is occurring
Licenses do not get assigned to the group if "Get-M365DSCCombinedLicenses" did not return any existing license.

#### Verbose logs showing the problem
"You cannot call a method on a null-valued expression"

#### Suggested solution to the issue
Update "Get-M365DSCCombinedLicenses":

old code:

 if ($DesiredLicenses.Length -gt 0)
    {
        foreach ($license in $DesiredLicenses)
        {
            if (-not $result.SkuId.Contains($license.SkuId))
            {
                $result += @{
                    SkuId         = $license.SkuId
                    DisabledPlans = $license.DisabledPlans
                }
            }
            else
            {
                #Set the Desired Disabled Plans if the sku is already added to the list
                foreach ($item in $result)
                {
                    if ($item.SkuId -eq $license.SkuId)
                    {
                        $item.DisabledPlans = $license.DisabledPlans
                    }
                }
            }
        }
    }

new code:

if ($DesiredLicenses.Length -gt 0)
    {
        foreach ($license in $DesiredLicenses)
        {
            if ($result.Length -eq 0)
            {
                $result += @{
                    SkuId         = $license.SkuId
                    DisabledPlans = $license.DisabledPlans
                }
            }
            else {
                if (-not $result.SkuId.Contains($license.SkuId))
                {
                    $result += @{
                        SkuId         = $license.SkuId
                        DisabledPlans = $license.DisabledPlans
                    }
                }
                else
                {
                    #Set the Desired Disabled Plans if the sku is already added to the list
                    foreach ($item in $result)
                    {
                        if ($item.SkuId -eq $license.SkuId)
                        {
                            $item.DisabledPlans = $license.DisabledPlans
                        }
                    }
                }
            }
        }
    } 

I tried the new code and it did work.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.1109.1 (Resource code did not change in the newer releases)

**Comment by andikrueger** [comment]
This should be fixed with the last release: #2574 

Could you please run Update-M365DSCModule to make sure, you are using the latest bits.

**Comment by andreasmarx** [comment]
Unfortunately not. The issue is within group based licencing which is not related to the msft_aaduser resource.  Msft_aadgroup last changed two month ago.
