### ISSUE TITLE
Use of GCC High Tenant for M365DSC with Azure DevOps

### ISSUE THREAD

**Issue by Brijeshoo7** [microsoft/Microsoft365DSC#2602]
Hello Folks, Saw the new release of the White Paper for M365Dsc. very well explained Thanks to @ykuijs. 

https://office365dsc.azurewebsites.net/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf

Just a Small confirmation I need on the same, It works fine in the commercial Platform of Azure but Does not work in Government cloud like GCC High Tenant. can you Please confirm that this solution is supported in Gov cloud or not? 

Even the basic command like connect-mggraph needs parameter such as Connect-MgGraph -Environment USGov if we use Azure Gov cloud. even we manage to register app manually in the Azure portal for access over SharePoint tenant it gives authentication issue in the end at release pipeline.

I have tried script manually with PowerShell ISE once it asks for global admin Creds It does not redirect to the actual Portal for authentication.

Any feedback would be really helpful.

Thanks,
Brijesh M.

**Comment by Brijeshoo7** [comment]
@andikrueger  given commands working fine, still Register-PnPManagementShellAccess cmdlt giving me below error instead of asking for Credentials.

![image](https://user-images.githubusercontent.com/88958817/204515687-ba99c708-bd65-484c-910f-dde925a7e625.png)

Anyway I have only limited time access with GCC tenant so Can not check further with IT.
Just wanted to confirm if the solution is supported or not.

Thank you @andikrueger

**Comment by andikrueger** [comment]
You could register your own application in this case. Even though pnp powershell should work in this environment. 

Register-PNPAzureAdApp

within M365 we do have an option to do so as well

https://microsoft.github.io/Microsoft365DSC/user-guide/cmdlets/Update-M365DSCAzureAdApplication/

**Comment by Brijeshoo7** [comment]
@andikrueger  Thanks In future if I get access to GCC tenant again for this setup will try this out. For now closing the ticket.
