### ISSUE TITLE
Running 'Export-M365DSCConfiguration' error "Cannot bind argument to parameter 'Name' because it is null."

### ISSUE THREAD

**Issue by micheldings** [microsoft/Microsoft365DSC#2603]
#### Details of the scenario you tried and the problem that is occurring
1)  Installed DSC
2)  Running Export-M365DSCConfiguration
3)  Entered credentials (Tried several tenants and even with credentials as parameter)
4)  Getting same error:
[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted:
TeamsChannelTab
Connecting to {ExchangeOnline}...❌
Cannot bind argument to parameter 'Name' because it is null.
Partial Export file was saved at:  C:\Users\...........
But no file was saved

#### Verbose logs showing the problem
PS C:\Windows\System32> $global:credential = Get-Credential

PowerShell credential request
Enter your credentials.
User: admin@tenant.onmicrosoft.com
Password for user admin@tenant.onmicrosoft.com: **********************

PS C:\Windows\System32> Export-M365DSCConfiguration -GenerateInfo:$true -Mode Full -Credential $global:credential -FileName "MS365DSC-Config.ps1" -Path "C:\temp\DSC"
Exporting Microsoft 365 configuration for Mode: Full

Authentication methods specified:
- Credentials

[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted:
TeamsChannelTab
Connecting to {ExchangeOnline}...❌
Cannot bind argument to parameter 'Name' because it is null.
Partial Export file was saved at: C:\Users\................

#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
Export-M365DSCConfiguration

 $global:credential = Get-Credential
 Export-M365DSCConfiguration -GenerateInfo:$true -Mode Full -Credential $global:credential -FileName "MS365DSC-Config.ps1" -Path "C:\Temp\DSC"

#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

    Get-ComputerInfo -Property @(
        'OsName',
        'OsOperatingSystemSKU',
        'OSArchitecture',
        'WindowsVersion',
        'WindowsBuildLabEx',
        'OsLanguage',
        'OsMuiLanguages')
-->
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}

PowerShell Version: 
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.1123.1

**Comment by andikrueger** [comment]
At the moment, we do not suppor PS 7.3 Please try to run M365 in a PS 5.1 or 7.1 session.

**Comment by micheldings** [comment]
That did the trick, thx
