### ISSUE TITLE
[Feature] Intune - App protection policies - Windows 10 WIP policy

### ISSUE THREAD

**Issue by hvdbrink** [microsoft/Microsoft365DSC#2604]
### Description
In Intune/Endpoint there the option to create windows 10 app protection policies, but with M365DSC there isn't an option to export and import those
### Proposed properties

- Endpoint ManagerApps - App Protection Policies - Create -Windows Information Protection

**Comment by William-Francillette** [comment]
WIP is deprecated now so I don't think we will develop the resource for the policy
https://learn.microsoft.com/en-us/windows/security/information-protection/windows-information-protection/protect-enterprise-data-using-wip

**Comment by ykuijs** [comment]
A thought:
The article states "Microsoft will continue to support WIP on supported versions of Windows. New versions of Windows won't include new capabilities for WIP, and it won't be supported in future versions of Windows." and that it has been deprecated fairly recently.

This means that current versions of Windows can still be using WIP, resulting in WIP still being used for several years. Doesn't this justify creating a resource?

**Comment by William-Francillette** [comment]
@andikrueger , I'll add this one to my list as well

**Comment by William-Francillette** [comment]
I generated the resource with the DRG version from PR #2823  and was able to export the resource and all pester tests passed - 
When the PR is approved and merged, I'll generate the resource and perform further tests
