### ISSUE TITLE
IntuneDeviceManagementWindowAutopilotDeploymentProfile: New resource proposal

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#2605]
### Description
Having this new resource would allow to export and deploy Windows Autopilot deployment profiles (both HybridAAD and AAD joined).

### Proposed properties
All

### Special considerations or limitations
None

**Comment by andikrueger** [comment]
@William-Francillette would this be something you could work on?

**Comment by William-Francillette** [comment]
Sure can do. I'm still working on entitlement management resources but will work on this next

**Comment by William-Francillette** [comment]
I have generated this resource with my latest PR for the DRG successfully #2823 
As soon as it has been approved and merged, I will raise the PR for this issue
2 resources will be created:
- IntuneWindowAutopilotDeploymentProfileHybridAzureADJoined
- IntuneWindowAutopilotDeploymentProfileAzureADJoined
