### ISSUE TITLE
While Importing the MOF file getting the error 

### ISSUE THREAD

**Issue by rakeshsujan** [microsoft/Microsoft365DSC#2606]
PS C:\Users\Lenovo\Downloads\sharepoint\p1.ps1> Start-DSCConfiguration -Path C:\Users\Lenovo\Downloads\sharepoint\p1.ps1\M365TenantConfig -Wait -Verbose -Force
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/Desi
redStateConfiguration'.
VERBOSE: An LCM method call arrived from computer DESKTOP-4LLI9BD with user sid S-1-5-21-983209565-4098291482-3482957361-1001.
VERBOSE: [DESKTOP-4LLI9BD]: LCM:  [ Start  Set      ]
VERBOSE: [DESKTOP-4LLI9BD]: LCM:  [ End    Set      ]
Importing module MSFT_SPOHomeSite failed with error - File C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1116.1\DscResources\MSFT_SPOHomeSite\MSFT_SPOHomeSite.psm1 cannot be loaded. The 
file C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1116.1\DscResources\MSFT_SPOHomeSite\MSFT_SPOHomeSite.psm1 is not digitally signed. You cannot run this script on the current system. 
For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ImportModuleFailed
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.617 seconds

**Comment by malauter** [comment]
Your execution policy does not allow to run unsigned scripts. You have to adjust your execution policy first.

`Set-ExecutionPolicy -ExecutionPolicy Unrestricted`

**Comment by rakeshsujan** [comment]
Thanks issue got fixed after executed the command 

Set-ExecutionPolicy -ExecutionPolicy Unrestricted
