### ISSUE TITLE
AAD User by default in AAD export

### ISSUE THREAD

**Issue by OlivierWaterloos** [microsoft/Microsoft365DSC#2607]
hello,

I have about 26k AAD users in my AAD. This why I do not want to have AAD user in my exporting from AAD. I have create a $AADComponent list with the component desired. There are 12.
But at the extract, the AADuser component is exported and it take ages before the exporting is finished.
I have notice that there are 17 component exported (AADUser + 4 extra)
I'm running the version 1.22.1116.1.
it there a way to not export AAD users?

if ($WorkLoad -eq "AAD")
{
    # ---------------------- wait for Enterprise App to be created
    $AADComponent = @("AADApplication","AADConditionalAccessPolicy","AADGroupLifecyclePolicy","AADGroupsNamingPolicy","AADGroupsSettings","AADNamedLocationPolicy","AADRoleDefinition","AADSecurityDefaults","AADServicePrincipal","AADTenantDetails","AADTermsOfUse","AADTokenLifetimePolicy")
    #AADGroup not allowed! to much AAD Groups

    Export-M365DSCConfiguration -Path $DSCPathWork -FileName $FilePSName -Components $AADComponent -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId
}
PS C:\windows\system32> $AADComponent.Count
12
PS C:\windows\system32> $AADComponent
AADApplication
AADConditionalAccessPolicy
AADGroupLifecyclePolicy
AADGroupsNamingPolicy
AADGroupsSettings
AADNamedLocationPolicy
AADRoleDefinition
AADSecurityDefaults
AADServicePrincipal
AADTenantDetails
AADTermsOfUse
AADTokenLifetimePolicy

![2022-11-29 15_07_45-Remote Desktop Manager  SPUCMG20 dev](https://user-images.githubusercontent.com/55983772/204555273-4539901d-351e-456f-aa12-90a2959f1db1.png)

**Comment by andikrueger** [comment]
Could you try to create the export command using the website:

https://export.microsoft365dsc.com/

I’ll look into the code later on. This should not happen.

**Comment by OlivierWaterloos** [comment]
Hello Andi,

Thanks for your fast answer.
I have export the code and it work fine. Thanks
