### ISSUE TITLE
Monitor for configuration drifts without applying changes to tenant?

### ISSUE THREAD

**Issue by tylermontneyacc** [microsoft/Microsoft365DSC#2608]
Let's assume the tenant is already in a desired state and I simply want this module to (read-only) monitor. `Start-DSCConfiguration` appears to not only start the monitoring process but make changes to the tenant. Is there any way to **monitor only** based off `Export-M365DSCConfiguration`? Perhaps `New-M365DSCDeltaReport`?

**Comment by andikrueger** [comment]
There are various ways. Easiest would be to run 

Test-DscConfiguration -ReferenceConfiguration "C:\Dsc\Configurations\M365Configuration.mof" 

Alternatively you could export the various components and create the delta afterwards. This depends on what kind of chances you want to track. 

Export-M365DSCConfiguration would export new objects and those would be visible in the report. The first option would just track the specified values within the configuration.

**Comment by tylermontneyacc** [comment]
That'll work, thanks!
