### ISSUE TITLE
SCComplianceCase Status is incorrect

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Microsoft365DSC#261]
#### Details of the scenario you tried and the problem that is occurring
I was trying out compliance case extraction and the test compliance case for some reason (me breaking it) went into ClosedWithErorr status. Office365DSC shows it as Active. 
As far as i can tell only Active and Closed are supported.
I also had a problem with the Closing status of a case staying as Closing forever. The current behavior is to show it as Closed when extracted.

#### Suggested solution to the issue
Not sure if there is a solution, just pointing out what's happening. I understand that these two values do not really fit into DSC. But for purposes of documenting and comparing i would like to know that a case changed state because somebody tried to close it (and failed).
So maybe the solution could be to add the two state values, but in Set-TargetResource do nothing when they show up (which might already be the case).
#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
WIll review with the team. I agree that extracting the 'transitional' statuses would be valuable when using the extraction to document the environment. However, as you pointed out, those do not represent a "State" which is what DSC is all about. I like your suggestion to have the Set-TargetResource throw a message (or error in this case) when trying to apply a transitional state to the resource.

**Comment by andikrueger** [comment]
@vinkobedek Is this issue resolved?

**Comment by NikCharlebois** [comment]
Can't really repro and has pointed above, transitional states are not something we wish to handle with DSC. Closing the issue
