### ISSUE TITLE
TeamsChannelTab not pulled with Credentials | working fine with Cert Based Auth

### ISSUE THREAD

**Issue by maheshdalavi** [microsoft/Microsoft365DSC#2618]
#### Details of the scenario you tried and the problem that is occurring
-  "TeamsChannelTab" component is not under Teams PS.
- "Teamschanneltab" details are available in "MgTeamChannelTab".
- Hence, while extracting the "Teams" workload we are missing on TeamsChannelTab while using Credentials as shown in documents.
- And getting the below warning msg
"[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted: TeamsChannelTab"
- But this is working fine if I use a SPN with proper Graph permissions.

#### Verbose logs showing the problem
- Warning msg

<img width="796" alt="image" src="https://user-images.githubusercontent.com/22946692/205467171-52c502d1-85f3-4d03-be32-f0a3c4e60511.png">

- As said, we do not have any parameter like TeamsChanneltab in Teams PS.
<img width="671" alt="image" src="https://user-images.githubusercontent.com/22946692/205467523-fe7b1215-964d-4162-bd17-0abbd417cb20.png">

- **But we do have it in MSgraph.**

<img width="857" alt="image" src="https://user-images.githubusercontent.com/22946692/205467248-e1f3550b-a525-4038-a1cd-1d766a72ea8b.png">

- Working fine with SPN with Proper Graph permission.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/22946692/205468384-894a8e57-353a-47b5-ab96-e9ce04e48a60.png">

#### Suggested solution to the issue
- Change in document or way to pull it with Credentials.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

<img width="389" alt="image" src="https://user-images.githubusercontent.com/22946692/205467567-ab0223ab-93fc-4d85-b770-cc0f29934312.png">

# insert configuration here
```

#### The operating system the target node is running
OsName               : Microsoft Windows 11 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Microsoft365DSC version 1.22.1130.1
PowerShell : 5.1.22621.608
MicrosoftTeams 4.6.1

**Comment by NikCharlebois** [comment]
Fixed in 1.22.1207
