### ISSUE TITLE
Problem creating localhost.mof file with component SPOSiteAuditSettings, SPOBrowserIdleSignout, SPOSite  

### ISSUE THREAD

**Issue by maheshdalavi** [microsoft/Microsoft365DSC#2619]
#### Details of the scenario you tried and the problem that is occurring
- Pulled SharePoint workload.
- While creating the localhost.mof file got the below error.
<img width="563" alt="image" src="https://user-images.githubusercontent.com/22946692/205483300-0f17485a-f3a6-4d5c-9e34-727ad404afc7.png">

- Issue is with SPOSiteAuditSettings, SPOBrowserIdleSignout, SPOSite  components.
- "Ensure" key/member value is correct in M365Tenantconfig.ps1 (either present or absent).
<img width="307" alt="image" src="https://user-images.githubusercontent.com/22946692/205483673-154cf82a-7f51-4035-82a1-b3ba9f622bfe.png">

- But while creating "localhost.mof" it is looking for incorrect values like 'ApplicationId', 'ApplicationSecret', 'CertificatePassword', 'CertificatePath', 'CertificateThumbprint', '............
- commenting the error lines will allow to create Localhost.mof.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/22946692/205483796-61fab403-9f5f-4072-a3ac-8bf0d5e949be.png">
- Localhost.mof created 
-
<img width="271" alt="image" src="https://user-images.githubusercontent.com/22946692/205483880-42de0bf4-e7b3-4347-abe5-7cca946f0c20.png">

#### Verbose logs showing the problem
- NA
<img width="568" alt="image" src="https://user-images.githubusercontent.com/22946692/205483939-03c3fa1b-818b-4ba0-8ee1-794aa4347ec5.png">

#### Suggested solution to the issue
- Proper parsing while creating localhost.mof

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
> Export-M365DSCConfiguration -Components @("SPOBrowserIdleSignout", "SPOSite", "SPOSiteAuditSettings") -Credential (Get-Credential) -Path D:\Microsoft365DSC\SPO
> cd D:\Microsoft365DSC\SPO
>.\M365TenantConfig.ps1

# insert configuration here
```

#### The operating system the target node is running
OsName               : Microsoft Windows 11 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Version : 1.22.1130.1
Name    : Microsoft365DSC

**Comment by ykuijs** [comment]
I see the issue being there with SPOSiteAuditSettings and SPOBrowserIdleSignout, but not with SPOSite. This last one actually has the Ensure parameter.

Are you sure this is also the case with the SPOSite?
