### ISSUE TITLE
integration of o365essentials

### ISSUE THREAD

**Issue by andreasmarx** [microsoft/Microsoft365DSC#2620]
Because M365DSC is a great module with already a lot of settings included and features to set, compare and extract, I would like to extend it regarding all the M365 Tenant settings under “Org settings” in the admin.microsoft.com portal. There is a module “[o365essentials](https://github.com/EvotecIT/O365Essentials)” which covers most of the settings. Mostly, no other way is possible today changing these settings. The module uses undocumented and unsupported APIs. But it works and I use it during Tenant setups. My question is, would you be willing to support that module? I am faced with the question of whether I should integrate it into M365DSC and provide my first contribution or create my own script outside of M365DSC.

**Comment by NikCharlebois** [comment]
We are currently not in a place where we can start leveraging these private APIs. We want to make sure Microsoft365DSC only leverages supported APIs. We are aware of the O365Essentials module, but as you stated, it is using unsupported APIs, which we can't do.

**Comment by andreasmarx** [comment]
OK. Totally understand. I will find another use case to contribute ;-)
