### ISSUE TITLE
One Question regarding 'EXOManagementRole'

### ISSUE THREAD

**Issue by EttaMa** [microsoft/Microsoft365DSC#2621]
Hi Team, 

When I tried to run following command: Export-M365DSCConfiguration -Components @("EXOManagementRole") -Path C:\Users\... -Credential $Credential -Mode Full

It didn't return the full list of management roles:
<img width="920" alt="image" src="https://user-images.githubusercontent.com/119832333/205552007-80510cea-1adb-4c98-b363-3d1344f24f82.png">

<img width="920" alt="image" src="https://user-images.githubusercontent.com/119832333/205552066-154f4d4d-cc04-494c-9d84-91946f89974d.png">

Here's returned by Exchange Online PowerShell command "Get-ManagementRole".

<img width="924" alt="image" src="https://user-images.githubusercontent.com/119832333/205552130-6b138750-b881-4cd7-95ab-b33405921d3b.png">

May I know if it's expected, or did I miss some settings?

Best Regards.

**Comment by malauter** [comment]
@EttaMa M365 DSC only exports management roles where the Parent attribute is not null. The assumption is that all roles without a parent value are default roles.
