### ISSUE TITLE
Drift Report Contains Ensure Attribute

### ISSUE THREAD

**Issue by NaveenRamakrish** [microsoft/Microsoft365DSC#2626]
Hello Team, 

We are seeing a attribute named Ensure in all the backup, When ever we are creating a drift report we see this Attribute got changed 
Ensure = Absent / Present, even though there were no changes done to the configuration. The drift reports say this attribute value got changed. 

![image](https://user-images.githubusercontent.com/117987376/206134239-797ca1c0-1095-43e2-98b2-7a1ec61b9e38.png)

Can you explain what is this value and why this is showing up as a change even though no permission/settings are changed? And how to get rid of this attribute in the Drift Report

-Naveen

**Comment by andikrueger** [comment]
Which resources do show this change?

Usually this would mean, the resource not present in the source or should be removed...

**Comment by NaveenRamakrish** [comment]
The report is from Exchange, 

The setting was already available and there were no recent changes, but in the Delta Report, I can see this Ensure attribute has been changed for a lot of settings. And there is no attribute value name "Ensure" for those settings.

**Comment by NaveenRamakrish** [comment]
> Which resources do show this change?
> 
> Usually this would mean, the resource not present in the source or should be removed...

The report is from Exchange,

The setting was already available and there were no recent changes, but in the Delta Report, I can see this Ensure attribute has been changed for a lot of settings. And there is no attribute value name "Ensure" for those settings.

While compiling the report, I am getting a warning as below. "Unexpected Token : Present"

![image](https://user-images.githubusercontent.com/117987376/206167704-137de994-ff85-47ef-8c92-728bba80cff6.png)

**Comment by NikCharlebois** [comment]
I am guessing that based on the partial screenshot, that this is coming from the EXOTransportRule resource. As @andikrueger points out, this means that on the source tenant, the "Block' in expressions or statement" Transport rule doesn't exist, but it does on the destination tenant.

**Comment by NaveenRamakrish** [comment]
> I am guessing that based on the partial screenshot, that this is coming from the EXOTransportRule resource. As @andikrueger points out, this means that on the source tenant, the "Block' in expressions or statement" Transport rule doesn't exist, but it does on the destination tenant.

I am creating the Delta Report from the Configuration file taken from the same tenant, 

I have built a script to back up the configuration daily and create a delta report for the configuration file taken yesterday and today, in the report i get this attribute Ensure = Absent/Present value as changes, where actual settings are not changed.

The goal is to find the changes that are happening in the environment.
