### ISSUE TITLE
AADAdministrativeUnit: No MembershipRule declaration in the module causes error on use

### ISSUE THREAD

**Issue by Borgquite** [microsoft/Microsoft365DSC#2633]
#### Details of the scenario you tried and the problem that is occurring

Trying to use new AADAdministrativeUnit module fails when running Test-TargetResource (and possibly others too)

#### Verbose logs showing the problem

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = TestConfiguration,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = 
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer <redacted> with user sid <redacted>.
VERBOSE: [<redacted>]: LCM:  [ Start  Compare  ]
VERBOSE: [<redacted>]: LCM:  [ *FAILED*Compare  ]     Completed processing compare operation. The operation returned False.
**The command Test-TargetResource of the PS module MSFT_AADAdministrativeUnit does not implement the write property MembershipRule mentioned in the corresponding MOF schema file 
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\DscResources\MSFT_AADAdministrativeUnit\MSFT_AADAdministrativeUnit.schema.mof. All write paramenters
mentioned in the schema file must be implemented by the command Test-TargetResource.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : WriteParameterNotImplemented
    + PSComputerName        : <redacted>**

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 3.895 seconds

#### Suggested solution to the issue

Checking under Modules/Microsoft365DSC/DSCResources/MSFT_AADAdministrativeUnit/MSFT_AADAdministrativeUnit.psm1, for some reason the MembershipRule parameter does not exist in the function declarations for Get-TargetResource, Set-TargetResource, or Test-TargetResource

I am tagging @NikCharlebois and @salbeck-sit based on their involvement in #2469 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration Example
{
    param(
        [Parameter(Mandatory = $true)]
        [PSCredential]
        $credsCredential
    )
    Import-DscResource -ModuleName Microsoft365DSC

    node localhost
    {
        AADAdministrativeUnit 'TestUnit'
        {
            Credential                    = $credsCredential;
            DisplayName                   = "Test-Unit";
            Ensure                        = "Present";
            MembershipRule                = "(user.country -eq `"Canada`")";
            MembershipRuleProcessingState = "On";
            MembershipType                = "Dynamic";
        }
    }
}
```

#### The operating system the target node is running
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.1207.1

**Comment by NikCharlebois** [comment]
@salbeck-sit is this something you'd have time to look at. It looks like there has been a conflict in the resource after merging your changes and the schema.mof file no longer aligns with the .psm1 parameters. Thanks

**Comment by salbeck-sit** [comment]
Got it. PR #2655 created
