### ISSUE TITLE
Get-MgOrganization : Insufficient privileges to complete the operation

### ISSUE THREAD

**Issue by ashmsport** [microsoft/Microsoft365DSC#2646]
I'm trying to run M365DSC with Service Principal using certificate for authentication. But I'm getting the following error:
Get-MgOrganization : Insufficient privileges to complete the operation

Before running it I checked the permissions required for each resource and gave Application permissions to the app in Azure AD.
Get-M365DSCCompiledPermissionList -ResourceNameList (Get-M365DSCAllResources)

Name              Value                                                                     
----              -----                                                                                         
ReadPermissions   {AdministrativeUnit.Read.All, Directory.Read.All, RoleManagement.Read.Directory, Member.Read.Hidden, Application.Read.All, Policy.Read.All, Agreement.Read.All, Group.Read.All, User.Read.All, EntitlementManagement.Read.All, EntitlementManagement.ReadWrite.All, Organization.Read.All, DeviceManagementConfiguration.Read.All, DeviceManagementApps.Read.All, DeviceManagementManagedDevices.Read.All, DeviceManagementServiceConfig.Read.All, DeviceManagementRBAC.Read.All, DeviceManagementRBAC.ReadWrite.All, DeviceManagementConfiguration.ReadWrite.All, Domain.Read.All, Tasks.Read.All, ChannelSettings.Read.All} 

Please let me know what am I missing here.

![image](https://user-images.githubusercontent.com/33230123/206740464-6941e96a-dfbe-4d59-83e7-e3d48fe63dab.png)

**Comment by NikCharlebois** [comment]
Can you try adding Organization.Read.All to see if it works? Thanks

**Comment by ashmsport** [comment]
> Can you try adding Organization.Read.All to see if it works? Thanks
Already added.
![image](https://user-images.githubusercontent.com/33230123/206746913-c91e42e7-1a59-4ebf-a344-088f680a4066.png)

**Comment by ashmsport** [comment]
I missed that 🤦‍♂️ Thank you.
