### ISSUE TITLE
New-M365DSCDeltaReport

### ISSUE THREAD

**Issue by upaneshpatel** [microsoft/Microsoft365DSC#2650]
Hi Team - 

The "New-M365DSCDeltaReport" reports a discrepancy in a value but both values are blank per report. Is this a bug?

![image](https://user-images.githubusercontent.com/116754276/206787255-f4d65b39-ac3c-482e-89e6-64a911f3f0e8.png)

**Comment by NikCharlebois** [comment]
Could you share the source and destination configuration by any chance? Thanks

**Comment by upaneshpatel** [comment]
Nik - Yeah here is the snip of the config for this specific policy. The source does not have "AllowedStreamingMediaInput" and destination has "AllowedStreamingMediaInput" but value of ""... I created the destination based on the source so not sure why the difference.

The other 2 policies that were created does not have that attribute.

[Destination.txt](https://github.com/microsoft/Microsoft365DSC/files/10198276/Destination.txt)
[Source.txt](https://github.com/microsoft/Microsoft365DSC/files/10198277/Source.txt)

**Comment by NikCharlebois** [comment]
Can You make sure you have the latest version of the module installed by running:

```
Update-M365DSCModule
```

We are not able to reproduce your error on our end. Thanks
