### ISSUE TITLE
Enhancement: Documentation improvement “Cloning tenants”

### ISSUE THREAD

**Issue by BDBARB** [microsoft/Microsoft365DSC#2662]
#### Details of the scenario you tried and the problem that is occurring
I am running the clone script with module version 1.22.1207.1, but the part of the script to run Start-DscConfiguration doesn't seem to do anything. To make this easy I am specifically targeting TeamsGuestMessagingConfiguration as I can disable/enable as needed to test. I am testing both from tenant to tenant and as a backup and restoring settings to the same tenant and either way the script seems to fly past the restore part. 

I can see it successfully makes the file M365TenantConfig.ps1 and all the correct settings are saved. 

    Node localhost
    {
        TeamsGuestMessagingConfiguration 975b64d0-5840-47c2-870f-cc3dd23db0a3
        {
            AllowGiphy             = $True;
            AllowImmersiveReader   = $True;
            AllowMemes             = $True;
            AllowStickers          = $True;
            AllowUserChat          = $True;
            AllowUserDeleteMessage = $True;
            AllowUserEditMessage   = $True;
            Credential             = $Credscredential;
            GiphyRatingType        = "Moderate";
            Identity               = "Global";
        }
    }

Here's what the Powershell ISE window looks like.
PS C:\WINDOWS\system32> Update-M365DSCAllowedGraphScopes -ResourceNameList @("TeamsGuestMessagingConfiguration") -Type Read

Export-M365DSCConfiguration -Components @("TeamsGuestMessagingConfiguration") -Credential $SourceCredential -Path C:\Dsc
Allowed Graph scopes updated!
Exporting Microsoft 365 configuration for Components: TeamsGuestMessagingConfiguration
 
Authentication methods specified:
- Credentials
 
Connecting to {MicrosoftTeams}...✅
[1/1] Extracting [TeamsGuestMessagingConfiguration] using {Credentials}...✅
⌛ Export took {4 seconds}

PS C:\WINDOWS\system32> $TargetCredential = Get-Credential

Update-M365DSCAllowedGraphScopes -ResourceNameList @("TeamsGuestMessagingConfiguration") -Type Update

C:\Dsc\M365TenantConfig.ps1 -Credential $TargetCredential
cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Allowed Graph scopes updated!

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running

Edition	Windows 10 Pro
Version	22H2
Installed on	‎7/‎23/‎2020
OS build	19045.2311
Experience	Windows Feature Experience Pack 120.2212.4190.0

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.1207.1

**Comment by andikrueger** [comment]
Could you check if a .mof file gets created and run `Start-DSCConfiguration -wait -verbose -force` with the matching path to your .mof file. This should show some more detailed output about what is going wrong.

**Comment by andikrueger** [comment]
Please try to use an admin powershell session (not ISE). Usually this will help.

**Comment by BDBARB** [comment]
Same thing, it skips right on through. Here's what it looks like below and nothing has changed on the target. 

PS C:\WINDOWS\system32> $TargetCredential = Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
PS C:\WINDOWS\system32> Update-M365DSCAllowedGraphScopes -ResourceNameList @("TeamsGuestMessagingConfiguration") -Type Update
Allowed Graph scopes updated!
PS C:\WINDOWS\system32> C:\Dsc\M365TenantConfig.ps1 -Credential $TargetCredential
PS C:\WINDOWS\system32> Start-DscConfiguration -Path C:\Dsc -Wait -Verbose
PS C:\WINDOWS\system32>

**Comment by BDBARB** [comment]
I did not see it a requirement in the clone tool page to manually set up a .MOF file. But is it required for it to work? https://microsoft365dsc.com/user-guide/get-started/securing-configurations/

I can see in the ConfigurationData.Ps1 the following:

@{
    AllNodes = @(
        @{
            NodeName                    = "localhost"
            PSDscAllowPlainTextPassword = $true;
            PSDscAllowDomainUser        = $true;
            #region Parameters
            # Default Value Used to Ensure a Configuration Data File is Generated
            ServerNumber = "0"

        }
    )
    NonNodeData = @(
    )
}

**Comment by andikrueger** [comment]
The mof ( managed object format file) is the outcome of compiling the configuration. By creating an export of a tenant all necessary files are going to be created. 

The PS1 file contains the configuration and the needed commands to compile the configuration. The psd1 file contains some songs that are used during process of compiling the configuration. 

Within the ps1 file the last line contains the command to compile the configuration that is defined above. 

If those is not happening, there is something wrong. Could you open the ps1 file and run the various commands one after another in a powershell session and share and error.

**Comment by BDBARB** [comment]
No error:

# Generated with Microsoft365DSC version 1.22.1207.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $Credential
)

Configuration M365TenantConfig
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $Credential
    )

    if ($null -eq $Credential)
    {
        <# Credentials #>
        $Credscredential = Get-Credential -Message "Credentials"

    }
    else
    {
        $CredsCredential = $Credential
    }

    $OrganizationName = $CredsCredential.UserName.Split('@')[1]

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.22.1207.1'

    Node localhost
    {
        TeamsGuestMessagingConfiguration c9b6393e-5308-4f5f-b23a-26aaec9dc6b5
        {
            AllowGiphy             = $False;
            AllowImmersiveReader   = $True;
            AllowMemes             = $True;
            AllowStickers          = $True;
            AllowUserChat          = $True;
            AllowUserDeleteMessage = $False;
            AllowUserEditMessage   = $True;
            Credential             = $Credscredential;
            GiphyRatingType        = "Moderate";
            Identity               = "Global";
        }
    }
}

M365TenantConfig -ConfigurationData .\ConfigurationData.psd1 -Credential $Credential

**Comment by BDBARB** [comment]
Should this be moving and shaking something at this last line? 

PS C:\WINDOWS\system32> M365TenantConfig -ConfigurationData .\ConfigurationData.psd1 -Credential $Credential

PS C:\WINDOWS\system32>

**Comment by andikrueger** [comment]
Yes. The last line should put a file in your current working directory. Please check if there’s a localhost.mof (within a M365TenantConfig folder).

**Comment by BDBARB** [comment]
I have searched the C drive for a "M365TenantConfig" folder but only turn up the location in the original script C:\Dsc.

When running the script I was expecting to see some kind of verification in the window that it's pushing changes similar to how  it extracts them when it connects and is "[1/1]Extracting". I have tried running this on 2 separate machines and on two separate tenants. No change is made. 

Can you please see if this is working for you on your end?

**Comment by BDBARB** [comment]
What is the last step that I am missing?

**Comment by andikrueger** [comment]
C:\Dsc\M365TenantConfig.ps1 -Credential $TargetCredential

Start-DscConfiguration -Path C:\Dsc -Wait -Verbose

**Comment by BDBARB** [comment]
I have ran that part just now. It does not do any changes to the tenant. I do get a new ps2 and psd1 files created but no .mof. However you can see below it says "Allowed Graph scopes updated!" but it does not actually update anything. 

PS C:\WINDOWS\system32> $TargetCredential = Get-Credential
cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:

PS C:\WINDOWS\system32> Update-M365DSCAllowedGraphScopes -ResourceNameList @("AADGroupsNamingPolicy") -Type Update

C:\Dsc\M365TenantConfig.ps1 -Credential $TargetCredential

Start-DscConfiguration -Path C:\Dsc -Wait -Verbose
Allowed Graph scopes updated!

PS C:\WINDOWS\system32>

**Comment by andikrueger** [comment]
Please set your working directory to c:\dsc. The example code assumes you are running your powershell session in c:\dsc. 

If you are using any other directory, you would need to match the paths accordingly.

**Comment by BDBARB** [comment]
I got the .MOF file!!! However the tenant was not updated. I'll look over your recommendations above and see if I can get to the next step.

**Comment by andikrueger** [comment]
Now you need to run Start-DSCConfiguration… (PowerShell as local admin 😉)

**Comment by BDBARB** [comment]
Here's the outcome when it gets ran, it simply skips to the next prompt.  (Yes running PowerShell as local admin)
PS C:\DSC> Start-DscConfiguration -Path C:\Dsc -Wait -Verbose

PS C:\DSC>

**Comment by andikrueger** [comment]
You could check the event log to get Information about what is going on. Alternatively you could add the -force switch to the command

**Comment by BDBARB** [comment]
As we have been conversing on this, an update has been released. I have updated to 1.22.1214.1 but it still does not push the changes to the tenant configuration. The source runs and the .mof file is created, but the target does not run. See the results from the PowerShell below. 

PS C:\WINDOWS\system32> $SourceCredential = Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> Update-M365DSCAllowedGraphScopes -ResourceNameList @("TeamsGuestMessagingConfiguration") -Type Read
Allowed Graph scopes updated!
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> Export-M365DSCConfiguration -Components @("TeamsGuestMessagingConfiguration") -Credential $SourceCredential -Path C:\Dsc
Exporting Microsoft 365 configuration for Components: TeamsGuestMessagingConfiguration

Authentication methods specified:
- Credentials

Connecting to {MicrosoftTeams}...✅
[1/1] Extracting [TeamsGuestMessagingConfiguration] using {Credentials}...✅
⌛ Export took {14 seconds}
PS C:\WINDOWS\system32> $TargetCredential = Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> Update-M365DSCAllowedGraphScopes -ResourceNameList @("TeamsGuestMessagingConfiguration") -Type Update
Allowed Graph scopes updated!
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> C:\Dsc\M365TenantConfig.ps1 -Credential $TargetCredential
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> Start-DscConfiguration -Path C:\Dsc -Wait -Verbose
PS C:\WINDOWS\system32>

**Comment by BDBARB** [comment]
> You could check the event log to get Information about what is going on. Alternatively you could add the -force switch to the command

It still passes right through...
PS C:\Dsc> Start-DscConfiguration -Path C:\Dsc -Wait -Verbose -force

PS C:\Dsc>

**Comment by andikrueger** [comment]
Could you share a screenshot of your directory c:\dsc

could you share the output of this cmdLet:

Get-DscConfigurationStatus -All

**Comment by BDBARB** [comment]
![image](https://user-images.githubusercontent.com/26826025/207742995-81d7bcaa-179c-4ea9-9a3a-c9d4a7ce5843.png)

**Comment by andikrueger** [comment]
Could you provide a screenshot of the contents in the M365TenantConfig folder?

**Comment by andikrueger** [comment]
This looks good - if the file has some content, it should start the configuration. 

Please run Start-DSCConfiguration -path c:\dsc\m365tenantConfig -wait -verbose -force

this should be the last step.

**Comment by BDBARB** [comment]
At first that didn't work, I got an error and it recommended to run "winrm quickconfig" which the second time finally got the changes to take on my destination! I really hope this helps someone out there! Appreciate your time and effort to help resolve this.

So what we have to do in a nutshell is:
1. Recommended to run Powershell as admin, not from ISE (although I did it anyway to see and it seems to work ok). 
2. Change directory to run the script from the path the script is creating the files C:\DSC, or else the script will not create the .mof directory folder or the file in it.
3. Change the path to the start Start-DSCConfiguration to the path of the .mof directory folder.
4. Configure the WinRM service to be running on the machine by running "winrm quickconfig" to get the last step to apply the changes on the destination.

PS C:\DSC> Start-DscConfiguration -Path C:\Dsc\M365TenantConfig -Wait -Verbose -force
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
**The client cannot connect to the destination specified in the request. Verify that the service on the destination is
running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the
destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the
destination to analyze and configure the WinRM service: "winrm quickconfig".
    + CategoryInfo          : ConnectionError: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : HRESULT 0x80338012
    + PSComputerName        : localhost**

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 8.174 seconds
PS C:\DSC> winrm quickconfig
WinRM is not set up to receive requests on this machine.
The following changes must be made:

Start the WinRM service.
Set the WinRM service type to delayed auto start.

Make these changes [y/n]? y

WinRM has been updated to receive requests.

WinRM service type changed successfully.
WinRM service started.
WSManFault
    Message
        ProviderFault
            WSManFault
                Message = WinRM firewall exception will not work since one of the network connection types on this machine is set to Public. Change the network connection type to either Domain or Private and try again.

Error number:  -2144108183 0x80338169
WinRM firewall exception will not work since one of the network connection types on this machine is set to Public. Change the network connection type to either Domain or Private and try again.

**Comment by andikrueger** [comment]
Thanks for the good summary. I’ll let this one open to improve the documentation.

**Comment by NikCharlebois** [comment]
Just want to make sure I am keeping up with the conversation, what needs to be improved in the documentation exactly? Not sure I follow. Thanks

**Comment by andikrueger** [comment]
The script at the end of the documentation and some additional remarks about the environment.
- PowerShell version
- not ISE
- Working directory 
- Path to folder containing the mof file

**Comment by NikCharlebois** [comment]
I believe these steps are all documented in the other sections on how to get started with the tool:

1 - https://microsoft365dsc.com/user-guide/get-started/prerequisites/#powershell-version
2 - ISE, PoSh console or Windows Terminal all work but it's documented here: https://microsoft365dsc.com/user-guide/get-started/prerequisites/#tooling
3 & 4 - https://microsoft365dsc.com/user-guide/get-started/deploying-configurations/
5 - WinRM is not required for all environments. If it is, the error message is very self indicative. Not convinced this is something we wish to document on the M365DSC front.

**Comment by andikrueger** [comment]
Agreed. Basically this is documented. Do we already outline in which sequence these articles should be read? I think it not an ordered list

**Comment by NikCharlebois** [comment]
The article listed about are part of the Prerequisites and How to Install pages which are appearing on top in the left navigation. I am honestly not sure what else we can do here. Documentation improvements is a constant activity in my opinion. Would you folks be ok with closing this issue?

**Comment by andikrueger** [comment]
I would be okay.

**Comment by BDBARB** [comment]
Thanks Nik. From the Cloning Tenant Configurations page https://microsoft365dsc.com/user-guide/get-started/cloning-tenants/ it is not clear to change directory in PowerShell to the C:\DSC nor is it clear to change the directory of the start command from the documentation from "Start-DscConfiguration -Path C:\Dsc -Wait -Verbose" to "Start-DscConfiguration -Path C:\Dsc\M365TenantConfig -Wait -Verbose". It's all good to know it's a requirement but to find that is a treasure hunt for those instructions by navigating away form the Cloning Tenant Configuration page. I'm glad I have this running but I also do not see the reason to not include those additional instructions from that specific page detailing how to use the cloning tool.
