### ISSUE TITLE
"SCAuditConfigurationPolicy", "SCSupervisoryReviewPolicy", "SCSupervisoryReviewRule" not working with Security Reader Account

### ISSUE THREAD

**Issue by maheshdalavi** [microsoft/Microsoft365DSC#2669]
#### Details of the scenario you tried and the problem that is occurring
- "SCAuditConfigurationPolicy", "SCSupervisoryReviewPolicy", "SCSupervisoryReviewRule" components are working fine with GA account.
- But does not work with Security reader account.
![image](https://user-images.githubusercontent.com/22946692/207707858-89223dab-71f8-4574-a1fe-79a71a0fe026.png)

#### Verbose logs showing the problem
[2022-12-15 01:51:21]
{ObjectNotFound}
System.Management.Automation.CommandNotFoundException: The term 'Get-AuditConfigurationPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Error during Export:"
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\DSCResources\MSFT_SCAuditConfigurationPolicy\MSFT_SCAuditConfigurationPolicy.psm1: line 248
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\modules\M365DSCUtil.psm1: line 1190
at <ScriptBlock>, <No file>: line 1
**secreader@maheshms365.onmicrosoft.com
TenantId: maheshms365.onmicrosoft.com**

[2022-12-15 01:51:23]
{ObjectNotFound}
System.Management.Automation.CommandNotFoundException: The term 'Get-SupervisoryReviewPolicyV2' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Error during Export:"
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\DSCResources\MSFT_SCSupervisoryReviewPolicy\MSFT_SCSupervisoryReviewPolicy.psm1: line 281
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\modules\M365DSCUtil.psm1: line 1190
at <ScriptBlock>, <No file>: line 1
**secreader@maheshms365.onmicrosoft.com
TenantId: maheshms365.onmicrosoft.com**

[2022-12-15 01:51:24]
{ObjectNotFound}
System.Management.Automation.CommandNotFoundException: The term 'Get-SupervisoryReviewRule' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Error during Export:"
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\DSCResources\MSFT_SCSupervisoryReviewRule\MSFT_SCSupervisoryReviewRule.psm1: line 265
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1207.1\modules\M365DSCUtil.psm1: line 1190
at <ScriptBlock>, <No file>: line 1
secreader@maheshms365.onmicrosoft.com
TenantId: maheshms365.onmicrosoft.com

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

PS C:\Users\gravity> Get-Module Microsoft365DSC | fl Version

Version : 1.22.1207.1

#### The operating system the target node is running
OsName               : Microsoft Windows 11 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}

**Comment by NikCharlebois** [comment]
Security and Compliance is a bit of an oddball when it comes to permissions. For these properties you will need the Compliance Administrator in order to export the values or create a custom AAD role and grant it permission to read compliance settings.
