### ISSUE TITLE
New-M365DSCDeltaReport Report is having only Ensure Values

### ISSUE THREAD

**Issue by NaveenRamakrish** [microsoft/Microsoft365DSC#2685]
Hello Team, 

I have built a script using Microsoft365DSC Module to backup all the configuration from our tenant, and perform Comparison of today's backup with yesterday's backup for any changes in the configuration. 

I am using the New-M365DSCDeltaReport commandlet to compare 2 configuration files. Everything was working fine till the last update to 1.22.1214.1. after that, the delta report is having only the Ensure Attribute value. as Absent and Present, and does not show any actual changes in the configuration. 

Sample screenshot below of the report FYR. Can you please help fixing this.

![image](https://user-images.githubusercontent.com/117987376/208442925-108a40a5-ea07-4126-bdf4-139eb2dda15c.png)

**Comment by NikCharlebois** [comment]
Can you please share the source and destination .ps1 configurations for us to investigate? Thanks
