### ISSUE TITLE
 A conflict was detected between resources

### ISSUE THREAD

**Issue by alpesh-exigotech** [microsoft/Microsoft365DSC#2689]
Getting error while creating MOF file for deployment. 

How to resolve error for conflict?

![image](https://user-images.githubusercontent.com/88418557/208548963-3795bb3a-dada-4971-b2d8-8068928f3de3.png)

**Comment by ricmestre** [comment]
@alpesh-exigotech Hi, you cannot have resources with the same key property and different non-key properties, just like it's mentioned in the error message. That being said you just need to change the name of one of those tasks, since they share the same name ("Test  1"), then try to generate MOF once again.

**Comment by alpesh-exigotech** [comment]
Thanks @ricmestre for quick response!

We are using planner as checklist for few of our process. There might be chance that we have duplicate tasks under planner with same name.

![Screenshot 2022-12-21 at 10 54 07 am](https://user-images.githubusercontent.com/88418557/208788873-f48d9bcf-701f-4293-9f9d-0b1468adf395.png)


----------------------------

We are facing same issue with Azure Application (AAD Application), please see below screenshots:
![Screenshot 2022-12-21 at 10 47 19 am](https://user-images.githubusercontent.com/88418557/208788253-9aea3457-58f6-4e3d-a70d-bfbac6859150.png)
![Screenshot 2022-12-21 at 10 51 25 am](https://user-images.githubusercontent.com/88418557/208788259-65af9386-b7b3-444e-9815-5dc8ee954a03.png)

**Comment by andikrueger** [comment]
Please have a look at #2006 which holds information about this behaviour.

**Comment by NikCharlebois** [comment]
Folks, I will be closing this issue so that we don't have duplicates. All discussions regarding this issue should now be taken back to #2006 Thanks
