### ISSUE TITLE
DRG Graph parameters description definition

### ISSUE THREAD

**Issue by William-Francillette** [microsoft/Microsoft365DSC#2720]
Do you know a way to retrieve the description of a parameter to automate the generation in the DRG?

I can retrieve it for Intune parameters using the devicemanagement/settingDefinition Graph query but can't find anything for the rest of the commands

Thanks

**Comment by andikrueger** [comment]
What kind of information are you looking for? Could you share an example?

**Comment by William-Francillette** [comment]
Sure, I'm looking at retrieving this description info if that's possible 
![image](https://user-images.githubusercontent.com/79221284/209996710-c1f98086-25db-4990-ab34-fc66839ba915.png)

for schema file
![image](https://user-images.githubusercontent.com/79221284/209996796-96712efa-60e1-42bf-973e-568a7fca9b78.png)

**Comment by andikrueger** [comment]
could you share the URL to the table above?

**Comment by William-Francillette** [comment]
https://learn.microsoft.com/en-us/graph/api/resources/customaccesspackageworkflowextension?view=graph-rest-beta

I'm after something generic I could reuse for the DRG
The master schema ("https://metadataexplorerstorage.blob.core.windows.net/`$web/$($Version).js") does not return the descriptions...

**Comment by andikrueger** [comment]
I think, that I faced this challenge while creating the first version of the DRG. Back then, we skipped this part, as this kind of information was only available through parsing the documentation. Parsing the table to get the information shouldn't be that difficult though. 

@peombwa Are there any new endpoints or tools available that could help with this matter?

**Comment by peombwa** [comment]
Assuming you know the entityType, you can either use; the [OpenAPI document](https://github.com/microsoftgraph/msgraph-metadata/blob/master/openapi/beta/openapi.yaml) or the [clean metadata with descriptions CSDL](https://github.com/microsoftgraph/msgraph-metadata/blob/master/clean_beta_metadata/cleanMetadataWithDescriptionsAndAnnotationsbeta.xml) to access property descriptions. The files are available at https://github.com/microsoftgraph/msgraph-metadata and are updated on a weekly basis whenever there are API changes.

Descriptions in the OpenAPI document:
![image](https://user-images.githubusercontent.com/7061532/210004836-9ec3a293-fae4-4508-99e6-c6cca02974e0.png)

Descriptions in the metadata:
![image](https://user-images.githubusercontent.com/7061532/210004919-18f2098a-5f56-4bc5-b4c0-f229ac876584.png)

I'm not aware of a tool that currently returns descriptions other than the two above approaches. This is what we use to provide descriptions for our SDKs as well - https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Generated/model/CustomCalloutExtension.cs#L32-L37.

**Comment by William-Francillette** [comment]
That's exactly what I was looking for 
Thanks @peombwa  and @andikrueger

**Comment by andikrueger** [comment]
Thanks @William-Francillette for bringing this up. Let me know if you need any additional assistance to get the description into the schema.

**Comment by William-Francillette** [comment]
Are you ok to use PowerShell-yaml to convert the yaml to hashtable?
https://www.powershellgallery.com/packages/powershell-yaml/0.4.0
https://github.com/cloudbase/powershell-yaml

**Comment by andikrueger** [comment]
Any chance to use the xml file instead of the yaml ones? I would go with a solution that would not require third party libraries

**Comment by William-Francillette** [comment]
Just realised the xml 🤯- no worries I'll that one instead

**Comment by ykuijs** [comment]
Fixed via #2721
