### ISSUE TITLE
TeamsMeetingPolicy: RecordingStorageMode deprecated

### ISSUE THREAD

**Issue by T630Dev** [microsoft/Microsoft365DSC#2723]
ISSUE DESCRIPTION (this template):
As per [MS](https://learn.microsoft.com/en-us/powershell/module/skype/set-csteamsmeetingpolicy?view=skype-ps), the attribute RecordingStorageMode cannot be changed any longer. If I test with PS, also I am unable to change it.
Hence, this attribute should be removed from the res.

#### Suggested solution to the issue
Remove attribute

**Comment by ykuijs** [comment]
Will submit a PR for this issue
