### ISSUE TITLE
Microsoft365DSC and managed identity

### ISSUE THREAD

**Issue by MaciejZZZ** [microsoft/Microsoft365DSC#2729]
Hi
I have a production setup of Microsoft365 setup for various workloads in Azure Automation.
Azure Automation is using the "Run us" accounts and just recently it has been announced that the "Run us" accounts are going to be retired.
_On 30 September 2023, Azure Automation Run As accounts will be retired and you'll need to migrate your runbooks to managed identities for authentication by that date.

So the question is - will M365DSC work with managed identity? (for EXO, SPO, OD,AAD)

https://learn.microsoft.com/en-us/azure/automation/automation-managed-identity-faq#how-long-will-you-support-a-run-as-account

**Comment by andikrueger** [comment]
Please review this docs article about the supported authentication methods for M365DSC:

https://microsoft.github.io/Microsoft365DSC/user-guide/get-started/authentication-and-permissions/

There is a table containing alls supported authentication methods for the various workloads.

**Comment by NikCharlebois** [comment]
+1 to what @andikrueger mentioned above. We are working on bringing Managed Identity support across the board for M365DSC, but are unfortunately relying on underlying dependencies that will need to add support for it first. For example, we recently announced the addition of managed identity within the Microsoft Graph PowerShell SDK v2 which we will start supporting once it hits GA. Other workloads will shortly follow. Thanks
https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-powershell-v2-is-now-in-public-preview-half-the-size-and-will-speed-up-your-automations/#1-managed-identity

**Comment by MaciejZZZ** [comment]
thanks a lot for quick answer :)
