### ISSUE TITLE
IntuneASRRulesPolicyWindows10 - enable property missing

### ISSUE THREAD

**Issue by hvdbrink** [microsoft/Microsoft365DSC#2730]
Description
in the resource : IntuneASRRulesPolicyWindows10 -  OfficeCommunicationAppsLaunchChildProcess it gives an error after we export and import it again : 
Microsoft365DSC\IntuneASRRulesPolicyWindows10 : At least one of the values 'enable' is not supported or valid for property 'OfficeCommunicationAppsLaunchChildProcess' on class 'IntuneASRRulesPolicyWindows10'. Please specify only supported values: 
notConfigured, userDefined, block, auditMode, warn, disable.

the property "enable" is something we get from the export.

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.1221.1

**Comment by ykuijs** [comment]
On it!
