### ISSUE TITLE
error processing property 'EdgeEnterpriseModeSiteListLocation' OF TYPE 'IntuneDeviceConfigurationPolicyWindows10'

### ISSUE THREAD

**Issue by hvdbrink** [microsoft/Microsoft365DSC#2732]
#### Details of the scenario you tried and the problem that is occurring
This happens after an export of the workload of Intune and I try to compile the file.

#### Verbose logs showing the problem
ConvertTo-MOFInstance : System.ArgumentException error processing property 'EdgeEnterpriseModeSiteListLocation' OF TYPE 'IntuneDeviceConfigurationPolicyWindows10': Cannot convert value "System.String" to type "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1 or 0.
At path\filename.ps1:1937 char:9
+   IntuneDeviceConfigurationPolicyWindows10
At line:341 char:16
+     $aliasId = ConvertTo-MOFInstance $keywordName $canonicalizedValue

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
EdgeEnterpriseModeSiteListLocation                   = "https://xxx.companyxyz.com/xxxSiteList.xml";

Item above is the output we get from the export in the file.

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.1221.1

**Comment by ykuijs** [comment]
The type is defined as Boolean in the resource schema. Will correct this.
