### ISSUE TITLE
DRG: DateTime and DateTimeOffset parameters

### ISSUE THREAD

**Issue by William-Francillette** [microsoft/Microsoft365DSC#2740]
What format do you recommend to export the dateTime and dateTimeOffset parameters with Export-TargetResource?
It can be troublesome when the cultures are different between the tenant and the client to return the correct value during Test-TargetResource

Testing the DRG with MgDeviceManagementWindowFeatureUpdateProfile and the resource returns endOfSupportDate of type DateTimeOffset 

https://learn.microsoft.com/en-us/graph/api/resources/intune-softwareupdate-windowsfeatureupdateprofile?view=graph-rest-beta

**Comment by NikCharlebois** [comment]
These have to be string. The exact format really depends on the resource. The set method should be able to deconstruct the string back into the appropriate dateTime or dateTimeOffset parameters and the export and get be able to properly convert it back to the decided upon string format.

**Comment by William-Francillette** [comment]
Do you have a preference on which Culture we should use to store the date? there's always confusion between 08/10 and 10/08 
When the dateTime type is converted to Json it returns something like Date(1234564133) format. (not sure how this is called )
Other one would be to store UTC date and enforcing that conversion during export and set

Happy to implement either

**Comment by William-Francillette** [comment]
Based on the resource doc, I've decided to use the round-trip type 
![image](https://user-images.githubusercontent.com/79221284/210784870-0cd71a76-5029-462a-8b16-f2a161d7b8ee.png)
https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings

![image](https://user-images.githubusercontent.com/79221284/210785282-7d5eae2f-85d9-40a3-afd4-0a9bead0ef88.png)
https://learn.microsoft.com/en-us/graph/api/intune-softwareupdate-windowsfeatureupdateprofile-update?view=graph-rest-beta#example
I also added the DateFormat parameter to  New-M365DSCResource: by default all DateTime / DateTimeOffset will be converted  using toString("o") but the toString format can be overwritten by DateFormat
