### ISSUE TITLE
Extend M365DSC DevOps capability

### ISSUE THREAD

**Issue by MatthewWhiteMoJ** [microsoft/Microsoft365DSC#2742]
@ykuijs  Getting my head around the new M3365 DSC DevOps whitepaper and looking at how i can extend this further with more DSC resource types do i simply need to create a new folder under DscResources for the workload i want to template (eg AzureAD)  then replicate the PSD1 and PSM1 files with the relevant changes for the relevant configuration that is per environment or common across all environments?

Is there anything else that would need to be considered?

**Comment by MatthewWhiteMoJ** [comment]
hi @ykuijs  - can you shed any light here?

**Comment by andikrueger** [comment]
Are you trying to extend the devops Whitepaper to a multi-tenant solution?

**Comment by MarcelHeek** [comment]
Is it possible to create a multi-tenant solution? I am also interested if that is the usecase for MatthewWhiteMoJ?

**Comment by andikrueger** [comment]
It would absolutely be possible to build a multi tenant solution. The limiting factors might be authentication handling, customisation and complexity.

**Comment by MatthewWhiteMoJ** [comment]
i will look at multi tenant in the future but its more around the additional custom PS module - I am looking at managing my admin users via DSC so that i can track what should be created in one place.

In the old whitepaper you could just add an [AADUser](https://microsoft365dsc.com/resources/azure-ad/AADUser/) block to the main config file but would be good to replicate the logic that the template for the user is set in the relevant AzureAD Module (M365Config) in the whitepaper 

Trying to see if its as simple as copy/edit the PSD1 files that exist for Exchange/Teams/PowerPlatform etc into a new folder with new GUIDs and then have an AzureADSchema.psm1 file that does the config iteration over multiple users defined in your environment specific datafile

**Comment by MatthewWhiteMoJ** [comment]
could be explaining this badly and maybe i just need to give it a go

**Comment by andikrueger** [comment]
This is still possible. You can add any resource to the files within the various configurations. Please keep in mind, that you are not able to manage passwords with DSC.

**Comment by MatthewWhiteMoJ** [comment]
thanks - don't want to manage passwords - very much want the account created and the user enabled for SSPR to go pick their own password. just liked the idea of setting out the templates of the account types in the M365DSC Module that comes with the whitepaper

**Comment by MatthewWhiteMoJ** [comment]
So have looked at this and the idea of adding an AzureAD folder doesn't seem to have any real change to the way that the build/deploy processes work. any guidance on extending the M365Config module included in the whitepaper to have additional resources in it would be greatly appreciated.

**Comment by MatthewWhiteMoJ** [comment]
may have realised my mistake and not amended the M365Configuration.ps1 file to reference the additional points on the workloads i want to manage. Currently running a PR on my code to see if it picks up my changes

**Comment by MatthewWhiteMoJ** [comment]
and yes - have worked out what the issue is now. Will close the Issue as i have self resolved but would be good to add to the Whitepaper documentation what needs to be done to support more workloads.

**Comment by netasher-Zot** [comment]
Hey @MatthewWhiteMoJ is it possible to use your help?
i'm to implement the DSC Devops solution but can't seem to figure out how to add AADUser or AADGroup.
i get an error saying it is not a composite resource. 
tried creating one but i can't seem to get it working.
could use your help here if possible
