### ISSUE TITLE
SPOSharingSettings: Multiple sites returned from Get-PnPTenantSite

### ISSUE THREAD

**Issue by bjoernf73** [microsoft/Microsoft365DSC#2759]
#### Details of the scenario you tried and the problem that is occurring
In MSFT_SPOShareingSettings.psm1, the function `Get-TargetResource`, from line 162: 
```powershell
$SPOSharingSettings = Get-PnPTenant -ErrorAction Stop
$MySite = Get-PnPTenantSite | Where-Object { $_.Url -match '-my.sharepoint.com/' }

        if ($null -ne $MySite)
        {
            $MySiteSharingCapability = (Get-PnPTenantSite -Identity $MySite.Url).SharingCapability
            #====> Here an exception is thrown, since $MySite in an array....
        }
```
Get-PnPTenantSite may very well return multiple sites that are redirectors (using .Template = 'RedirectSite#0'), while only one site is the actual MySite (not using .Template = 'RedirectSite#0')  

#### Suggested solution to the issue
Change the line 
```powershell
$MySite = Get-PnPTenantSite | Where-Object { $_.Url -match '-my.sharepoint.com/' }
```
to 
```powershell
$MySite = Get-PnPTenantSite | Where-Object { $_.Url -match '-my.sharepoint.com/' -and $_.Template -notmatch '^RedirectSite#' }
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
(only exporting)

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, nb-NO}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

**Comment by andikrueger** [comment]
This was already partially fixed with #2760. There was one instance left, which will be fixed with my next PR.
