### ISSUE TITLE
EXODistributionGroup: Add HiddenFromAddressListsEnabled parameter and support for other attributes

### ISSUE THREAD

**Issue by Borgquite** [microsoft/Microsoft365DSC#2761]
#### Details of the scenario you tried and the problem that is occurring

EXODistributionGroup does not support various parameters (it appears to only support those available with the New-DistributionGroup cmdlet, but there are many more under Set-DistributionGroup)

https://learn.microsoft.com/en-us/powershell/module/exchange/set-distributiongroup?view=exchange-ps

It would be really helpful to have HiddenFromAddressListsEnabled available - but other relevant fields should also be included?

- AcceptMessagesOnlyFrom
- AcceptMessagesOnlyFromDLMembers
- AcceptMessagesOnlyFromSendersOrMembers
- BypassModerationFromSendersOrMembers
- CustomAttribute1 **through** CustomAttribute15
- EmailAddresses
- ExtensionCustomAttribute1 **through** ExtensionCustomAttribute5
- GrantSendOnBehalfTo
- HiddenFromAddressListsEnabled
- MailTip
- MailTipTranslations
- RejectMessagesFrom
- RejectMessagesFromDLMembers
- RejectMessagesFromSendersOrMembers
- ReportToManagerEnabled
- ReportToOriginatorEnabled
- SendOofMessageToOriginatorEnabled
- SimpleDisplayName
- WindowsEmailAddress

#### Verbose logs showing the problem

N/A

#### Suggested solution to the issue

Implement the ability to get, set and test these attributes when distribution groups are created/updated

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration Example
{
    param
    (
        [Parameter(Mandatory = $true)]
        [PSCredential]
        $credsAdmin
    )
    Import-DscResource -ModuleName Microsoft365DSC

    node localhost
    {
        EXODistributionGroup 'DemoDG'
        {
            Alias                              = "demodg";
            Ensure                             = "Present";
            HiddenFromAddressListsEnabled       = $True;
            Name                               = "DemoDG";
            Credential                         = $credsAdmin
        }
    }
}
```

#### The operating system the target node is running

N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.23.104.1

**Comment by Borgquite** [comment]
Similar to #3089

**Comment by NikCharlebois** [comment]
The newly released EXOGroupSettings resource handles these parameters.

**Comment by Borgquite** [comment]
@nikcharlebois Let me know if you want to re-open this - or would prefer for me to create a new issue

**Comment by Borgquite** [comment]
Looks like a significant number of these attributes were added in 1.23.1004.1 - thank you!

https://github.com/microsoft/Microsoft365DSC/commit/c70ff49c09ab1697a4c47572922b32144cf70c6d#diff-b042ce020f67b2bb35e3aa69486dee3a9a8f53091d84b63164222890f9ad0554R6
