### ISSUE TITLE
SCDLPComplianceRule is not working correctly

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Microsoft365DSC#277]
#### Details of the scenario you tried and the problem that is occurring
the issue is related to ReverseDSC and Export-O365Configuration.. When creating a policy rule with a condition 'All of these' the data returned is invalid because the **ContentContainsSensitiveInformation** structure is different.
And even in the case of 'Any of these' only one condition per rule is returned.
  
#### Suggested solution to the issue
Not sure, a bit of restructuring in the DSC resource shemas could be required because apart from the conditions we would also like to know about the operator used.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Not available. 
#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
@vinkobedek can you elaborate on what you mean by 'All of these'? Can you post a screenshot of the Rule Editor (O365 Portal) for the faulty rule? Thanks

**Comment by vinkobedek** [comment]
Sure, no problem. 

Not sure if it's just me, but i find the admin portals terribly confusing :D. There is the Exchange administration, Microsoft 365 security, Office 365 Security & Compliance, Microsoft 365 compliance
and they have intersecting data.

Anyway, back to our problem:
1 go to https://protection.office.com/datalossprevention
2. select a policy, or create a new one.
3. Select a rule in policy settings, click edit rule button.
4. Under the content contains section there is a dropdown with two values (any of these, all of these)
screenshots below

![image](https://user-images.githubusercontent.com/13213802/70428271-89e26480-1a76-11ea-9847-bd64c4f7b7b8.png)
![image](https://user-images.githubusercontent.com/13213802/70428601-2573d500-1a77-11ea-8d4a-8874e0772a42.png)

**Comment by NikCharlebois** [comment]
@vinkobedek When you say the structure is invalid, is it actually throwing an error out when you try to compile it? It does appear that the actual contains block is not properly extracted, but the configuration still compiles fine:

Ex: 
SCDLPComplianceRule e8c2d626-a1df-4fad-8a26-f924bd443e9e
        {
            BlockAccess                         = $False;
            ContentContainsSensitiveInformation = MSFT_SCDLPSensitiveInformation
            {
                name = ''
            };
            Disabled                            = $False;
            Ensure                              = "Present";
            GlobalAdminAccount                  = $Credsglobaladmin;
            Name                                = "AnyOfThese Rule";
            Policy                              = "MyDLPPolicy";
            ReportSeverityLevel                 = "Low";
        }
        SCDLPComplianceRule 5087889c-2e24-49cd-9004-99046e0ceec6
        {
            BlockAccess                         = $False;
            ContentContainsSensitiveInformation = MSFT_SCDLPSensitiveInformation
            {
                name = ''
            };
            Disabled                            = $False;
            Ensure                              = "Present";
            GlobalAdminAccount                  = $Credsglobaladmin;
            Name                                = "AllOfTheseRule";
            Policy                              = "MyDLPPolicy";
            ReportSeverityLevel                 = "Low";
        }

**Comment by vinkobedek** [comment]
Yes, you are correct, when i compile it there is no error thrown. Still, would like to see the correct data extracted though :).

I also came across another issue that WILL cause a compilation error. 
``` 
name = 'Australia Driver's License Number'
```

**Comment by NikCharlebois** [comment]
@vinkobedek can you confirm that the issue is fixed. Thanks

**Comment by vinkobedek** [comment]
@NikCharlebois 
It does work better than before, but I think that there are still some issues left to iron out.
When **All of these** is set for the conditions, the conditions are extracted correctly:


```powershell
        SCDLPComplianceRule 003cf4c9-dab3-4f02-8d37-db26164ab8b8
        {
            AccessScope                         = "NotInOrganization";
            BlockAccess                         = $False;
            ContentContainsSensitiveInformation = @(MSFT_SCDLPSensitiveInformation
            {
                name = 'Australia Driver''s License Number'
                id = '1cbbc8f5-9216-4392-9eb5-5ac2298d1356'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '9'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'Australia Passport Number'
                id = '29869db6-602d-4853-ab93-3484f905df50'
                maxconfidence = '94'
                minconfidence = '71'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '8'
            }
MSFT_SCDLPSensitiveInformation
            {
                name = 'ABA Routing Number'
                id = 'cb353f78-2b72-4c3c-8827-92ebe4f69fdf'
                maxconfidence = '97'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '-1'
            }
);
            Disabled                            = $False;
            Ensure                              = "Present";
            GlobalAdminAccount                  = $Credsglobaladmin;
            Name                                = "Low volume of content detected Australia Privacy Act";
            NotifyUser                          = @("LastModifier","SiteAdmin","Owner");
            Policy                              = "Australia Privacy Act";
            ReportSeverityLevel                 = "Low";
        }
```

1. My first issue here is that there is no indication what condition type was used. Is it _Any of these_, or _All of These_? Or for us devs is it AND, or OR?
2. When _Any of These_ condition type is used, only the first condition is extracted even though in the UI all of them are visible (the same as above for the _All of These_ case):

```powershell
 SCDLPComplianceRule e176d20c-0d8c-4995-9e82-7396c905fec7
        {
            AccessScope                         = "NotInOrganization";
            BlockAccess                         = $False;
            ContentContainsSensitiveInformation = MSFT_SCDLPSensitiveInformation
            {
                name = 'Australia Driver''s License Number'
                id = '1cbbc8f5-9216-4392-9eb5-5ac2298d1356'
                maxconfidence = '100'
                minconfidence = '75'
                classifiertype = 'Content'
                mincount = '1'
                maxcount = '9'
            }
;
            Disabled                            = $False;
            Ensure                              = "Present";
            GlobalAdminAccount                  = $Credsglobaladmin;
            Name                                = "Low volume of content detected Australia Privacy Act";
            NotifyUser                          = @("LastModifier","SiteAdmin","Owner");
            Policy                              = "Australia Privacy Act";
            ReportSeverityLevel                 = "Low";
        }
```

**Comment by NikCharlebois** [comment]
This was fixed in one of our latest releases. For "All of These" we now embedded the CIMInstances inside a SCDLPContainsSensitiveInformationGroup object.
