### ISSUE TITLE
TeamsCallingPolicy : Unable to collect using certificate thumbprint

### ISSUE THREAD

**Issue by MarcelHeek** [microsoft/Microsoft365DSC#2779]
#### Details of the scenario you tried and the problem that is occurring

I use a certificate thumbprint to export the Teams configuration of a tenant. According to the documentation the use of a thumbprint is supported (perhaps even advised in comparison to the use of credentials). This is also documented specifically for the component -> https://microsoft365dsc.com/resources/teams/TeamsCallingPolicy/

#### Verbose logs showing the problem

I receive the following as STDOUT output

```text
Exporting Microsoft 365 configuration for Components: TeamsCallingPolicy
 
Authentication methods specified:
- Service Principal with Certificate Thumbprint
 
Connecting to {MicrosoftTeams}...✅
[1/1] Extracting [TeamsCallingPolicy] using {CertificateThumbprint}...❌
Error Log created at {file://D:/a/m365dsc-reporter/m365dsc-reporter/5168-M365DSC-ErrorLog.log}
⌛ Export took {24 seconds}
```

The error file has the following contents
```text
[2023/01/13 10:33:42]
{InvalidOperation}
System.Exception: [Forbidden] : Access Denied.
"Error during Export:"
at Get-CsConfiguration<Process>, C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.1\internal\Merged_internal.ps1: line 11227
at Get-CsConfigurationModern<Process>, C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.1\custom\Merged_custom_PsExt.ps1: line 363
at Get-CsConfigurationModern<Process>, C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.1\exports\ProxyCmdletDefinitionsWithHelp.ps1: line 42415
at Get-CsTeamsCallingPolicy<Process>, C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.1\exports\ProxyCmdletDefinitionsWithHelp.ps1: line 6996
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\DSCResources\MSFT_TeamsCallingPolicy\MSFT_TeamsCallingPolicy.psm1: line 547
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCUtil.psm1: line 1190
at <ScriptBlock>, D:\a\m365dsc-reporter\m365dsc-reporter\_scripts\Collect_M365DSC_Report_v0.2.ps1: line 83
at <ScriptBlock>, D:\a\_temp\7cd5137e-f83f-48a0-9173-7567bbcd5220.ps1: line 2
at <ScriptBlock>, <No file>: line 1
TenantId: <replaced>.onmicrosoft.com
```

#### Suggested solution to the issue

How can I retrieve the TeamsCallingPolicy using the certificate Thumbprint. I have granted all API permissions for permissiontype Read for all DSCResources.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
System is GitHub based runner
```text

Current runner version: '2.299.1'
Operating System
  Microsoft Windows Server 2022
  10.0.20348
  Datacenter
Runner Image
  Image: windows-2022
  Version: 20230109.1
  Included Software: https://github.com/actions/runner-images/blob/win22/20230109.1/images/win/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230109.1
```
#### Version of the DSC module that was used ('dev' if using current dev branch)

Version Microsoft DSC installed: 1.23.111.1

**Comment by sandrola** [comment]
This work for me. Perhaps your Applicaton doesen't have the right permission on the Tenant? TeamsAdmin Role? The error is related to the Teams module.

**Comment by MarcelHeek** [comment]
I have these API permission set for the SPN
![2023-01-10 13_01_35-EA-ISN-P-M365DSC - Microsoft Azure — Mozilla Firefox Private Browsing](https://user-images.githubusercontent.com/84451910/212335926-325120b6-3518-4fe6-8a4e-745626d23b76.jpg)

I am quite reluctant to add whatever admin role, as I intended to scope the SPN with the minimal right for reading the DSC resources. I know that for Exchange some role assignments are needed, but I never can across the Teams Administrator role in the documentation.

**Comment by powershellpr0mpt** [comment]
I'm running into the exact same issue here, not just on the TeamsCallingPolicy though, but all Teams cmdlets seem to run into this.
![image](https://user-images.githubusercontent.com/9294993/217261620-f48236d5-de8b-4218-af44-e3e15ea1afe5.png)

error log containing entries such as these:

```
[2023/02/07 02:36:03]
{InvalidOperation}
System.Exception: [Forbidden] : Access Denied.
"Error during Export:"
at Get-CsConfiguration<Process>, C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.3\internal\Merged_internal.ps1: line 11845
at Get-CsConfigurationModern<Process>, C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.3\custom\Merged_custom_PsExt.ps1: line 363
at Get-CsConfigurationModern<Process>, C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.3\exports\ProxyCmdletDefinitionsWithHelp.ps1: line 42391
at Get-CsTeamsComplianceRecordingPolicy<Process>, C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.3\exports\ProxyCmdletDefinitionsWithHelp.ps1: line 7506
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.201.1\DSCResources\MSFT_TeamsComplianceRecordingPolicy\MSFT_TeamsComplianceRecordingPolicy.psm1: line 375
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.201.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.201.1\modules\M365DSCUtil.psm1: line 1211
at <ScriptBlock>, <No file>: line 1
TenantId: <replaced>.onmicrosoft.com



[2023/02/07 02:36:04]
{InvalidOperation}
System.Exception: [Forbidden] : Access Denied.
"Error during Export:"
at Get-CsConfiguration<Process>, C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.3\internal\Merged_internal.ps1: line 11845
at Get-CsConfigurationModern<Process>, C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.3\custom\Merged_custom_PsExt.ps1: line 363
at Get-CsConfigurationModern<Process>, C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.3\exports\ProxyCmdletDefinitionsWithHelp.ps1: line 42391
at Get-CsTeamsCortanaPolicy<Process>, C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.3\exports\ProxyCmdletDefinitionsWithHelp.ps1: line 7570
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.201.1\DSCResources\MSFT_TeamsCortanaPolicy\MSFT_TeamsCortanaPolicy.psm1: line 339
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.201.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.201.1\modules\M365DSCUtil.psm1: line 1211
at <ScriptBlock>, <No file>: line 1
TenantId: <replaced>.onmicrosoft.com
```

**Comment by sandrola** [comment]
AS in the release notes https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication the Application need AzureAD Builtin roles.
![image](https://user-images.githubusercontent.com/104500912/217267542-7a098c6f-2c25-482e-ac02-2aa47a2bda4f.png)
One or more of them.

**Comment by powershellpr0mpt** [comment]
Makes a lot of sense, but would be handy if included in the [Authentication and Permissions](https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/) documentation.

Just for reference, this [documentation](https://learn.microsoft.com/en-us/microsoftteams/using-admin-roles) lists the difference in RBAC roles for Teams.
Thanks for the info @sandrola 👍

**Comment by martincaddick** [comment]
+1 @sandrola
@powershellpr0mpt This is similar to what I was trying to say here in #2894
I almost feel like for every green tick in the table it would be awesome to have a section of code or text that tells me exactly what I need to do to implement that.

**Comment by NikCharlebois** [comment]
We are working on improving overall documentation for authentication via SPN across all workloads.
