### ISSUE TITLE
EXOAcceptedDomain error with invalid domain

### ISSUE THREAD

**Issue by upaneshpatel** [microsoft/Microsoft365DSC#2792]
When try to import DSC into a new tenant and try to create new "EXOAcceptedDomain" for a domain, I get below error. 

**_Ex6F9304|Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException|The operation couldn't be performed because object 'DOMAINNAME.com' couldn't be
found on 'SA0P222A01DC011.NAMP222A001.PROD.OUTLOOK.COM'._**
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : [Server=LV2P222MB0656,RequestId=280e3e32-ba1a-90a6-e9ab-b6bd747b3e50,TimeStamp=Tue, 17 Jan 2023 00:06:58 GMT],Write-ErrorMessage
    + PSComputerName        : localhost

VERBOSE: [ULW5CG14397SC]: LCM:  [ End    Set      ]  [[EXOAcceptedDomain]8588b72a-94db-4727-a492-32638153649d]  in 0.8790 seconds.
The PowerShell DSC resource '[EXOAcceptedDomain]8588b72a-94db-4727-a492-32638153649d' with SourceInfo
'C:\temp\Production\Exchange\EXOAcceptedDomain.ps1::34::9::EXOAcceptedDomain' threw one or more non-terminating errors while running the Set-TargetResource
functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

**Comment by andikrueger** [comment]
Could you please share your configuration and add some more details like in which environment and/or M365DSC Version this error is happening. Thanks!

**Comment by malauter** [comment]
And can you please check if the domain you want to edit in EXO is already registered in the M365 tenant?

**Comment by upaneshpatel** [comment]
Ok I believe the domain first has to be registered in M365 before DSC can run to add accepted domain.. Thank you and I will close case.

**Comment by Cyanic-Cloud** [comment]
When you add a custom domain name in Azure it seems to now add to accepted domain names in EXO, I've not noticed this before so unless this is a new feature by Microsoft, not sure?
I am getting the same error when trying to apply a list of accepted domain names using the production.psd1 file, the error makes sense as the domains have not been added to the azure tenant.
if they are now automatically appear in EXO accepted domains by simply adding the domains to custom domain names in azure, this feature of adding accepted domains may no longer be needed? or am I missing something?
![Uploading 2023-03-08 10_56_19-.png…]()
