### ISSUE TITLE
issue while creating the LCM | localhost.mof file

### ISSUE THREAD

**Issue by maheshdalavi** [microsoft/Microsoft365DSC#2793]
#### Details of the scenario you tried and the problem that is occurring
•	Getting an error while creating the localhost.mof file.
•	Many values are not supported with properties error.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
1. create M365tenantconfig.ps1
2. afterward try to create the localhost.mof.
3. will get the below error ( error file attached)
![image](https://user-images.githubusercontent.com/22946692/212845588-a3db8972-13c1-4684-aa48-acd71e806731.png)

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Home Single Language
OsOperatingSystemSKU : 100
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

PS C:\Microsoft365DSC\SC_workload> get-module Microsoft365dsc | fl version

Version : 1.23.111.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
[error_dsc_localhost_mof.txt](https://github.com/microsoft/Microsoft365DSC/files/10432807/error_dsc_localhost_mof.txt)

**Comment by NikCharlebois** [comment]
Looks like the cmdlets support additional values that aren't documented. PR to accommodate is on its way.
