### ISSUE TITLE
Exchange Online connections not being quickly closed during Test-DSCConfiguration

### ISSUE THREAD

**Issue by anpiskai** [microsoft/Microsoft365DSC#2796]
When running Test-DSCConfiguration on Microsoft365DSC MOF files containing Exchange Online resources and connecting to multiple tenants in succession, connections to Tenant 1 are remaining open after completion of the Test-DSCConfiguration command even when specifying a different tenant ID/App ID/certificate thumbprint in the MOF file for Tenant 2. As a result, the resources in the MOF file for Tenant 2 are checked against Tenant 1, resulting in incorrect assessment of their state in Tenant 2. 

As an example, consider a setup where there are three tenants with domains mtolab1.com, mtolab2.com, and mtolab3.com verified in their respective tenants. When running the tests consecutively with no pause, the mtolab2.com and mtolab3.com domains are not accurately showing as existing because the connection to Tenant 1 is still active. (This is true even if issuing an explicit Disconnect-ExchangeOnline command between each line).
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/48796638/212913932-d2e57868-33fa-4491-b1db-198296f004e6.png">

However, if you insert a ~60 second pause between runs, it gives the connection a chance to fully close and the results run as expected. Digging into the process that appears responsible for opening the connection, it looks like the process that is key to close is named WmiPrvSE, however there can be multiple instances with this name running. Once the one in question closes though, accurate results for the other tenants seem to be reported.
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/48796638/212915453-8266b871-f067-4042-bef4-b6f380bc7a41.png">

This issue does not seem to be the case when running the underlying Exchange Online cmdlets directly and querying the same information.
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/48796638/212917154-af7e6844-3dfb-489e-954e-2ec61043cbde.png">

**Comment by andikrueger** [comment]
DId you try to run the processes in their own PowerShell session? 

From a DSC perspective you would not run multiple configurations from one host, as you would configure the host to meet be in the desired state. With M365DSC these boarders of systems are weak as there is no processor (Local configuration manager) built into M365 and you are kind of piggybacking on the local windows VM and the LCM there to configure the remote system.

**Comment by andikrueger** [comment]
Thanks for the additional context. 

M365dsc used the MSCloudLogin Module to manage the connection to a tenant. There are various global variables used to keep track of the state of the connection. 

In this scenario it is obviously not handling the tenant switch correctly. This needs to be fixed or you would need to add some cleanup of this global session indicators. 
 Having various ps sessions would not really mitigate this issue.

**Comment by anpiskai** [comment]
Yep, I tried to find/clear the $Global:MSCloudLoginConnectionProfile however it appears to already be cleared out by the time we get to the end of the loop so there is no value to remove. I've also tried doing an explicit Disconnect-ExchangeOnline, but as shown in the original post, that doesn't seem to help either since it seems to be closed out already. It seems like the LCM or WMI caches a connection (probably not expecting to switch to a different tenant) and that's what's causing the issue since it goes away on its own after a minute. Are you aware of any way to reduce how long the cache duraiton is? That seems to me like the only way to fix the behavior

**Comment by andikrueger** [comment]
Have you tried to set this one:

$Global:MSCloudLoginConnectionProfile.ExchangeOnline.Connected = $false

**Comment by anpiskai** [comment]
That prompted an error about the property not existing and being unable to set. I'll try to test out creating the parent object. I tried to pre-create the parent nodes too ($Global:MSCloudLoginConnectionProfile=@{} and $Global:MSCloudLoginConnectionProfile.ExchangeOnline=@{}), but that produced the same behavior (although didn't error).

**Comment by NikCharlebois** [comment]
Connections to Exchange Online, when using the LCM logic flow, will remain open by design for performance reason. If you wish to connect to different tenants withing the same session, you will need to explicitly close the connection to EXO and clear the MSCloudLoginConnectionProfile as @andikrueger suggested. Important to note that this needs to be done in the context of the LCM, which by default executes inside the Local System scope. The Following lines could be added inside of your configuration (DSC supports imperative code between resources declarations).

```
Disconnect-ExchangeOnline
$Global:MSCloudLoginConnectionProfile = $null
```

**Comment by anpiskai** [comment]
Within my script, I do a series of disconnects to various things at the end of each tenant configuration to try to clear anything remaining, but connections persist despite that.
***@***.***

Perhaps the piece that I'm missing is "Important to note that this needs to be done in the context of the LCM"---could you elaborate on how one would do that? Would the DevOps agent need to be changed to run as LocalSystem instead of the Local Administrator account as specified on page 29 of the whitepaper Yorick<https://office365dsc.azurewebsites.net/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf> made?
***@***.***
