### ISSUE TITLE
Security and Compliance is not working with SPN

### ISSUE THREAD

**Issue by maheshdalavi** [microsoft/Microsoft365DSC#2797]
The security and Compliance workload is not working with SPN with the new version. Is there anything extra that needs to be done ?
![image](https://user-images.githubusercontent.com/22946692/212937719-b4b1d696-fc83-4099-86e4-497a65c31e5f.png)

**Comment by andikrueger** [comment]
What M365DSC verison are you using and did you remove the old dependencies?

**Comment by maheshdalavi** [comment]
@andikrueger Please find the below details.

![image](https://user-images.githubusercontent.com/22946692/212982549-340c0096-5917-4c71-9a2e-5d84d342afa9.png)
=============
PS C:\Microsoft365DSC\SC_workload\test1> Uninstall-M365DSCOutdatedDependencies
Checking Microsoft.Graph.Authentication
PS C:\Microsoft365DSC\SC_workload\test1> Update-M365DSCDependencies
PS C:\Microsoft365DSC\SC_workload\test1> get-module Microsoft365dsc | fl version


Version : 1.23.111.1



PS C:\Microsoft365DSC\SC_workload\test1> Export-M365DSCConfiguration -Components @("SCAuditConfigurationPolicy", "SCAutoSensitivityLabelPolicy", "SCAutoSensitivityLabelRule", "SCCaseHoldPolicy", "SCCaseHoldRule", "SCComplianceCase", "SCComplianceSearch", "SCComplianceSearchAction", "SCComplianceTag", "SCDeviceConditionalAccessPolicy", "SCDeviceConfigurationPolicy", "SCDLPCompliancePolicy", "SCDLPComplianceRule", "SCFilePlanPropertyAuthority", "SCFilePlanPropertyCategory", "SCFilePlanPropertyCitation", "SCFilePlanPropertyDepartment", "SCFilePlanPropertyReferenceId", "SCFilePlanPropertySubCategory", "SCLabelPolicy", "SCProtectionAlert", "SCRetentionCompliancePolicy", "SCRetentionComplianceRule", "SCRetentionEventType", "SCSensitivityLabel", "SCSupervisoryReviewPolicy", "SCSupervisoryReviewRule") -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId
Exporting Microsoft 365 configuration for Components: SCAuditConfigurationPolicy, SCAutoSensitivityLabelPolicy, SCAutoSensitivityLabelRule, SCCaseHoldPolicy, SCCaseHoldRule, SCComplianceCase, SCComplianceSearch, SCComplianceSearchAction, SCComplianceTag, SCDeviceConditionalAccessPolicy, SCDeviceConfigurationPolicy, SCDLPCompliancePolicy, SCDLPComplianceRule, SCFilePlanPropertyAuthority, SCFilePlanPropertyCategory, SCFilePlanPropertyCitation, SCFilePlanPropertyDepartment, SCFilePlanPropertyReferenceId, SCFilePlanPropertySubCategory, SCLabelPolicy, SCProtectionAlert, SCRetentionCompliancePolicy, SCRetentionComplianceRule, SCRetentionEventType, SCSensitivityLabel, SCSupervisoryReviewPolicy, SCSupervisoryReviewRule

Authentication methods specified:
- Service Principal with Certificate Thumbprint

[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted:
SCAuditConfigurationPolicy SCAutoSensitivityLabelPolicy SCAutoSensitivityLabelRule SCCaseHoldPolicy SCCaseHoldRule SCComplianceCase SCComplianceSearch SCComplianceSearchAction SCComplianceTag SCDeviceConditionalAccessPolicy SCDeviceConfigurationPolicy SCDLPCompliancePolicy SCDLPComplianceRule SCFilePlanPropertyAuthority SCFilePlanPropertyCategory SCFilePlanPropertyCitation SCFilePlanPropertyDepartment SCFilePlanPropertyReferenceId SCFilePlanPropertySubCategory SCLabelPolicy SCProtectionAlert SCRetentionCompliancePolicy SCRetentionComplianceRule SCRetentionEventType SCSensitivityLabel SCSupervisoryReviewPolicy SCSupervisoryReviewRule
PS C:\Microsoft365DSC\SC_workload\test1>
PS C:\Microsoft365DSC\SC_workload\test1> Get-ComputerInfo -Property @(
>>         'OsName',
>>         'OsOperatingSystemSKU',
>>         'OSArchitecture',
>>         'WindowsVersion',
>>         'WindowsBuildLabEx',
>>         'OsLanguage',
>>         'OsMuiLanguages')


OsName               : Microsoft Windows 10 Home Single Language
OsOperatingSystemSKU : 100
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

**Comment by andikrueger** [comment]
This is really strange. The code and the resources above do look ok. 
could you share the output of the following command and run this in a new PSSession:

Get-Module Microsoft365DSSC -ListAvailable

**Comment by andikrueger** [comment]
… @ykuijs was able to find the root cause of the issue: your version does not contain the newly added functionality. It’ll be available with the next release or you could switch to the dev branch of m365dsc to get the SPN authentication option right away.

**Comment by maheshdalavi** [comment]
@andikrueger Thank you. I will try from the Dev branch.

**Comment by bjoernf73** [comment]
Can confirm that SC now works with SPN with the Dev branch. Probably needs Global Administrator, though.

**Comment by NikCharlebois** [comment]
@maheshdalavi can you update to the latest version of the module and confirm that this is now fixed? Thanks

**Comment by maheshdalavi** [comment]
working with the 1.23.201.1
