### ISSUE TITLE
issue with SPOUserProfileProperty | SPN | Cannot bind argument to parameter 'Properties' because it is null.

### ISSUE THREAD

**Issue by maheshdalavi** [microsoft/Microsoft365DSC#2798]
#### Details of the scenario you tried and the problem that is occurring
run the command with 
> Export-M365DSCConfiguration -Components @("SPOUserProfileProperty") -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId -Verbose
- SPN has Sharepoint = Sites.FullControl.All, Organization.Read.All and other permissions.
- All components are working fine except SPOUserProfileProperty

#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/22946692/213021952-5d3dc334-27a0-4237-8521-a8b9e10c6d9f.png)

[2023-01-18 03.25.27]
{InvalidData}
System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Properties' because it is null.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Error during Export:"
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\DSCResources\MSFT_SPOUserProfileProperty\MSFT_SPOUserProfileProperty.psm1: line 324
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.111.1\modules\M365DSCUtil.psm1: line 1190
at <ScriptBlock>, <No file>: line 1
TenantId: maheshms365.onmicrosoft.com
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Home Single Language
OsOperatingSystemSKU : 100
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

**Comment by andikrueger** [comment]
Please have a look at this thread. Within SharePoint you need to assign additional permissions to the app.

https://github.com/pnp/PnP-PowerShell/issues/2582

**Comment by jeffreykarlan** [comment]
> Please have a look at this thread. Within SharePoint you need to assign additional permissions to the app.
> 
> [pnp/PnP-PowerShell#2582](https://github.com/pnp/PnP-PowerShell/issues/2582)

Hi,
 I'm having this issue.  I'm not seeing a clear solution or fix in the suggested thread?  Only some hints at a workaround?  Is this identified as a bug in MS365DSC Required Application Permissions?  Thank you.

**Comment by NikCharlebois** [comment]
What provider are you using for the Sites.FullControl.All permissions? This needs to be the SharePoint provider, not the Microsoft Graph one:

![image](https://user-images.githubusercontent.com/2547149/216687110-cc2d12d1-b999-4e53-8ce5-18194a88307c.png)
![image](https://user-images.githubusercontent.com/2547149/216687715-f6360ae9-1054-49ef-9d31-e97686603e08.png)

**Comment by jeffreykarlan** [comment]
Hello,

I'm attempting to export only, no writing.  I have https://microsoft.sharepoint-df.com/Sites.Read.All.

Thank you

**Comment by maheshdalavi** [comment]
@NikCharlebois Application has SharePoint:Sites.fullControl.all. 
along with SPOUserProfileProperty,
Access denied for SPOSiteAuditSettings (Private site) and error in SPOHubSite.
![Screenshot 2023-02-07 003701](https://user-images.githubusercontent.com/22946692/217062411-a37d0710-7ac0-436a-8b9d-ef6dc4c7d870.png)

**Comment by NikCharlebois** [comment]
@jeffreykarlan Sites.FullControl.All is a requirement of the SPO APIs even if you are just doing an export.

**Comment by NikCharlebois** [comment]
Looks like we were missing a permission for the SPOUserProfileProperty. You will also need to grant:

SharePoint:
User.Read.All

In order of it to work. A fix is in the work to properly document this. Thanks
