### ISSUE TITLE
TeamsCallHoldPolicy - quotes causing mof-file to fail

### ISSUE THREAD

**Issue by salbeck-sit** [microsoft/Microsoft365DSC#2813]
#### Details of the scenario you tried and the problem that is occurring
DSC complains when trying to import the DSC-resource MSF_TeamsHoldPolicy. "Mof-file couldn't be deserialized"

#### Verbose logs showing the problem
(sorry, didn't capture any)

#### Suggested solution to the issue
Change "Global" in the mof-file to 'Global'
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
export-m365dscconfiguration -workload AAD 
# ie nothing related to Teams

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.5582.amd64fre.rs1_release.221130-1719
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by andikrueger** [comment]
Could you share a redacted version of your configuration?

**Comment by salbeck-sit** [comment]
The problem was fixed 3 days ago
