### ISSUE TITLE
DRG - generates schema where parameter Description-content can contain quotes

### ISSUE THREAD

**Issue by salbeck-sit** [microsoft/Microsoft365DSC#2819]
#### Details of the scenario you tried and the problem that is occurring
When I build a resource using DRG and the description for a parameter contains quotes, these are not replaced or edited meaning that the resulting mof-file is unreadable to DSC.

#### Suggested solution to the issue
Location in the DRG-module where comments are added to the mof-definition: Lines 721 and 726, $mofSchemaContent.Appendline(... $property.Description)....). Code should be added to ensure the description is edited so quotes are replaced by apostrophes or something similar.
I don't have available time to do a PR myself but thought I'd bring it up.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
New-M365DSCResource....

#### The operating system the target node is running

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by William-Francillette** [comment]
Could you share the cmdlet noun used to generate the resource please - I'll have a look

**Comment by William-Francillette** [comment]
I have updated PR #2823 to force replacing double quote in description by single quote

**Comment by salbeck-sit** [comment]
Sounds right. I came across it when testing another resource and got an error from DSC complaining about an unrelated resource-schema that turned out to have a field that contained double quotes as part of the description
