### ISSUE TITLE
Conditional Access Policy not deploying

### ISSUE THREAD

**Issue by crayon-robertelliott** [microsoft/Microsoft365DSC#2824]
So far when I've exported my base tenant and tried to import it into a new tenant 2 out of 3 conditional access policies are failing to create. One of them is this one that doesn't allow certain applications from being used by users. One of the included apps down below is Graph Explorer - de8bc8b5-d9f9-48b1-a8ad-b748da725064 which this Enterprise App also doesn't get imported (I'll leave the config for it down below as well).

CAP - 
AADConditionalAccessPolicy 46f9027d-9088-4345-8cb7-2bd541bb3d3c
        {
            ApplicationEnforcedRestrictionsIsEnabled = $False;
            BuiltInControls                          = @("block");
            ClientAppTypes                           = @("all");
            CloudAppSecurityIsEnabled                = $False;
            CloudAppSecurityType                     = "";
            Credential                               = $Credscredential;
            CustomAuthenticationFactors              = @();
            DeviceFilterRule                         = "";
            DisplayName                              = "Block Misc Azure apps for non-admin users";
            Ensure                                   = "Present";
            ExcludeApplications                      = @("db70508d-0592-4317-b6a6-983d294952ea");
            ExcludeDevices                           = @();
            ExcludeGroups                            = @();
            ExcludeLocations                         = @();
            ExcludePlatforms                         = @();
            ExcludeRoles                             = @("Global Administrator","User Administrator","Helpdesk Administrator","Service Support Administrator","Billing Administrator","Exchange Administrator","SharePoint Administrator","Skype for Business Administrator","Azure AD Joined Device Local Administrator","Compliance Administrator","Application Administrator","Security Administrator","Privileged Role Administrator","Intune Administrator","Cloud Application Administrator","Dynamics 365 Administrator","Power BI Administrator","Conditional Access Administrator","Azure Information Protection Administrator","Desktop Analytics Administrator","License Administrator","Cloud Device Administrator","Authentication Administrator","Privileged Authentication Administrator","Teams Communications Administrator","Teams Administrator","Insights Administrator","External ID User Flow Administrator","External ID User Flow Attribute Administrator","B2C IEF Keyset Administrator","B2C IEF Policy Administrator","External Identity Provider Administrator","Compliance Data Administrator","Kaizala Administrator","Search Administrator","Password Administrator","Printer Administrator","Authentication Policy Administrator","Groups Administrator","Power Platform Administrator","Azure DevOps Administrator","Hybrid Identity Administrator","Office Apps Administrator","Network Administrator","Teams Devices Administrator","Attack Simulation Administrator","Knowledge Administrator","Domain Name Administrator","Attribute Definition Administrator","Attribute Assignment Administrator","Exchange Recipient Administrator","Identity Governance Administrator","Cloud App Security Administrator","Windows Update Deployment Administrator","Windows 365 Administrator","Edge Administrator","Virtual Visits Administrator");
            ExcludeUsers                             = @();
            GrantControlOperator                     = "OR";
            Id                                       = "f5368ec3-eef0-4075-818b-205fa21f7720";
            IncludeApplications                      = @("797f4846-ba00-4fd7-ba43-dac1f8f63013","de8bc8b5-d9f9-48b1-a8ad-b748da725064");
            IncludeDevices                           = @();
            IncludeGroups                            = @();
            IncludeLocations                         = @();
            IncludePlatforms                         = @();
            IncludeRoles                             = @();
            IncludeUserActions                       = @();
            IncludeUsers                             = @("All");
            PersistentBrowserIsEnabled               = $False;
            PersistentBrowserMode                    = "";
            SignInFrequencyIsEnabled                 = $False;
            SignInFrequencyType                      = "";
            SignInRiskLevels                         = @();
            State                                    = "enabled";
            UserRiskLevels                           = @();
        }
GraphExplorerApp -
AADServicePrincipal 2c7c6702-9c5f-440e-9777-dcf047d69ca6
        {
            AccountEnabled            = $True;
            AlternativeNames          = @();
            AppId                     = "de8bc8b5-d9f9-48b1-a8ad-b748da725064";
            AppRoleAssignmentRequired = $False;
            Credential                = $Credscredential;
            DisplayName               = "Graph Explorer";
            Ensure                    = "Present";
            Homepage                  = "https://developer.microsoft.com/graph/graph-explorer";
            LogoutUrl                 = "https://developer.microsoft.com/en-us/graph/graph-explorer/logout";
            ObjectID                  = "d1cb696c-94fc-48b6-ab60-36b95c506044";
            PublisherName             = "Microsoft";
            ReplyURLs                 = @("https://developer.microsoft.com/de-de/graph/graph-explorer","https://developer.microsoft.com/de-de/graph/graph-explorer/","https://developer.microsoft.com/en-us/graph/graph-explorer","https://developer.microsoft.com/en-us/graph/graph-explorer/","https://developer.microsoft.com/en-us/graph/graph-explorer/preview","https://developer.microsoft.com/en-us/graph/graph-explorer/preview/","https://developer.microsoft.com/es-es/graph/graph-explorer","https://developer.microsoft.com/es-es/graph/graph-explorer/","https://developer.microsoft.com/fr-fr/graph/graph-explorer","https://developer.microsoft.com/fr-fr/graph/graph-explorer/","https://developer.microsoft.com/ja-jp/graph/graph-explorer","https://developer.microsoft.com/ja-jp/graph/graph-explorer/","https://developer.microsoft.com/pt-br/graph/graph-explorer","https://developer.microsoft.com/pt-br/graph/graph-explorer/","https://developer.microsoft.com/ru-ru/graph/graph-explorer","https://developer.microsoft.com/ru-ru/graph/graph-explorer/","https://developer.microsoft.com/zh-cn/graph/graph-explorer","https://developer.microsoft.com/zh-cn/graph/graph-explorer/","https://graphtryit.azurewebsites.net","https://graphtryit.azurewebsites.net/");
            ServicePrincipalNames     = @("de8bc8b5-d9f9-48b1-a8ad-b748da725064");
            ServicePrincipalType      = "Application";
            Tags                      = @("WindowsAzureActiveDirectoryIntegratedApp");
        }

I believe there's a certain issue with Graph Explorer and it just can't be imported on a new Tenant without signing into Graph and consenting to the app manually, unless there is another way. I have taken the app out of the CAP and ran this as well but running into the same issue.

All my deploys are through the most recent DevOps hosted agents.

787879f96a,a9ea8996-122f-4c74-9520-8edcd192826c,b1be1c3e-b65d-4f19-8427-f6fa0d97feb9,7495fdc4-34c4-4d15-a289-98788ce399
fd,38a96431-2bdf-4b4c-8b6e-5d3d8abac1a4,4d6ac14f-3453-41d0-bef9-a3e0c569773a,7698a772-787b-4ac8-901f-60d6b08affd2,c4e39
bd9-1100-46d3-8c65-fb160da0071f,7be44c8a-adaf-4e2a-84d6-ab2649e08a13,baf37b3a-610e-45da-9e62-d9d1e5e8914b,69091246-20e8
-4a56-aa4d-066075b2a7a8,eb1f4a8d-243a-41f0-9fbd-c7cdf6c5ef7c,6e591065-9bad-43ed-90f3-e9424366d2f0,0f971eea-41eb-4569-a7
1e-57bb8a3eff1e,aaf43236-0c0d-4d5f-883a-6955382ac081,3edaf663-341e-4475-9f94-5c398ef6c070,be2f45a1-457d-42af-a067-6ec1f
a63bc45,e6d1a23a-da11-4be4-9570-befc86d067a7,74ef975b-6605-40af-a5d2-b9539d836353,0964bb5e-9bdb-4d7b-ac29-58e794862a40,
966707d0-3269-4727-9be2-8c3a10f19b9d,644ef478-e28f-4e28-b9dc-3fdde9aa0b1f,0526716b-113d-4c15-b2c8-68e3c22b9f80,fdd7a751
-b60b-444a-984c-02652fe8fa1c,11648597-926c-4cf3-9c36-bcebb0ba8dcc,e3973bdf-4987-49ae-837a-ba8e231c7286,8ac3fc64-6eca-42
ea-9e69-59f4c7b60eb2,2b745bdf-0803-4d80-aa65-822c4493daac,d37c8bed-0711-4417-ba38-b4abe66ce4c2,3d762c5a-1b6c-493f-843e-
55a3b42923d4,c430b396-e693-46cc-96f3-db01bf8bb62a,b5a8dcf3-09d5-43a9-a639-8e29ef291470,8329153b-31d0-4727-b945-745eb3bc
5f31,8424c6f0-a189-499e-bbd0-26c1753c96d4,58a13ea3-c632-46ae-9ee0-9c0d43cd7f3d,31392ffb-586c-42d1-9346-e59415a2cc4e,45d
8d3c5-c802-45c6-b32a-1d70b5e1e86e,892c5842-a9a6-463a-8041-72aa08ca3cf6,32696413-001a-46ae-978c-ce0f6b3620d2,11451d60-ac
b2-45eb-a7d6-43d0f0125c13,3f1acade-1e04-4fbc-9b69-f0302cd84aef,e300d9e7-4a2b-4295-9eff-f1c78b36cc98); ExcludeUsers=(); 
IncludeGroups=(); IncludeRoles=(); IncludeUsers=(All)}}; DisplayName=Block Misc Azure apps for non-admin users; 
GrantControls={BuiltInControls=(block); Operator=OR}; SessionControls=$null; State=enabled
The server could not process the request because it is malformed or incorrect.
    + CategoryInfo          : InvalidOperation: ({ body = Micros...AccessPolicy1 }:) [], CimException
VERBOSE: [fv-az336-325]:                            [[AADConditionalAccessPolicy]46f9027d-9088-4345-8cb7-2bd541bb3d3c] 
    + FullyQualifiedErrorId : BadRequest,Microsoft.Graph.PowerShell.Cmdlets.NewMgIdentityConditionalAccessPolicy_Creat 
Set-Targetresource: finished processing Policy Block Misc Azure apps for non-admin users
   eExpanded
    + PSComputerName        : localhost
 
VERBOSE: [fv-az336-325]: LCM:  [ End    Set      ]  [[AADConditionalAccessPolicy]46f9027d-9088-4345-8cb7-2bd541bb3d3c] 
 in 8.8380 seconds.
The PowerShell DSC resource '[AADConditionalAccessPolicy]46f9027d-9088-4345-8cb7-2bd541bb3d3c' with SourceInfo 
'D:\a\1\s\tenant_build\m365config\M365TenantConfig.ps1::552::9::AADConditionalAccessPolicy' threw one or more 
non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel 
VERBOSE: [fv-az336-325]: LCM:  [ Start  Resource ]  [[AADGroup]aaeaa39e-e204-4ff5-a97f-976a089a1ebc]
called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
VERBOSE: [fv-az336-325]: LCM:  [ Start  Test     ]  [[AADGroup]aaeaa39e-e204-4ff5-a97f-976a089a1ebc]
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

**Comment by andikrueger** [comment]
You need to make sure the enterprise applications are there prior to the import. You cannot add these manually as those need to go through the permissions consent flow of AAD.  This is not an issue within M365DSC.

**Comment by crayon-robertelliott** [comment]
IncludeApplications = @();
I've removed all applications and it still doesn't create the CAP with the same error. Should there be anything else to modify?

**Comment by NikCharlebois** [comment]
Sory, I am not sure I am following here. Is the issue related to the fact that the ObjectID of the ServicePrincipal doesn't exist on the destination tenant?

**Comment by crayon-robertelliott** [comment]
Sorry, the issue was due to the ObjectID's of the apps not existing and would cause the CAP to not get created. Closing this out.
