### ISSUE TITLE
Information distinction

### ISSUE THREAD

**Issue by BrunoDrljanovcan** [microsoft/Microsoft365DSC#284]
Currently both successful and unsuccessful extractions of settings results are written into information stream but there is no distinction between the two, except their string.

e.g. when extracting EXOSafeAttachmentPolicy there are two outcomes even though those are both information, either result is extracted, or the tenant doesn't have the access and then there are no real results.

I would like to suggest using different tags for those two cases, so it can later be easier to programmatically determined if it is successful or not.

**Comment by NikCharlebois** [comment]
@BrunoDrljanovcan can you elaborate on what the issue at hand is. When trying to export EXOSafeAttachmentPolicy, you are right in saying that some tenants do not have access to get that info, in which case we simply print out a warning saying "The current tenant doesn't have access to Safe Attachment Policy APIs.". What do you mean by adding a tag exactyl? Thanks

**Comment by BrunoDrljanovcan** [comment]
Hi,

Yes, by the tag i mean something like "Example 2" in 

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-information?view=powershell-6

because although both cases are information, I would say they are different enough to tag them, e.g.

Write-Information -MessageData "Extracting ...." -Tags "Success" for the successful extraction and then some other tag for when it was not successful.

Also, thanks for the quick response!

**Comment by NikCharlebois** [comment]
I get it now. This is a great suggestion and fits right into our log engine improvement initiative we have going on. I will use this thread to keep you posted on our progress. Thanks for your interest in the tool Bruno!

**Comment by BrunoDrljanovcan** [comment]
Great! Thanks, and I'm looking forward to the improvements :)

**Comment by NikCharlebois** [comment]
Write-Information has been dropped in favor of Write-Host for extraction to provide visual indicators.
