### ISSUE TITLE
Compiling Configuration - Not outputting localhost.mof file

### ISSUE THREAD

**Issue by TSGareth** [microsoft/Microsoft365DSC#2845]
ISSUE TITLE: Compiling Configuration - Not outputting localhost.mof file

    ISSUE DESCRIPTION:
I have been able to successfully export the M365 tenant config using the DSC tooling, this provides me with the standard .ps1 & .psd1 file, I can generate a report from this. However when I then attempt to compile this, the .mof file doesn't get outputted. The directory is created but remains empty.

The command I run is: .\m365tenantconfig.ps1 -credential $credential
There is no output when I run this, the line is returned. I have replicated this on my laptop and an Azure VM 

The DSC export captures nearly all of the target areas. Most export to the report without any issues. 

OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
-->
branch)

Generated with Microsoft365DSC version 1.23.118.1

**Comment by andikrueger** [comment]
Did you review your event log if there are any entries? Additionally you could add -Verbose to the command.

**Comment by NikCharlebois** [comment]
Could you share your completed configuration (redacted) with us so that we can investigate? Thanks

**Comment by TSGareth** [comment]
Hi Nik, after updating & tweaking the modules I was after I was able to get the .mof file to appear, thanks for your assistance anyway


Gareth Danks
Technical Consultant
01202 800000
***@***.***
www.transparity.com
Please take a moment to fill in our customer survey
​Your opinion is important to us!

​The contents of this email and any attachments to it are confidential and are intended solely for the individual(s) and/or organisation(s) to whom this email is addressed. If you are not the intended recipient of this email any use, disclosure, forwarding, printing or copying of this email and any attachments to it by you may be unlawful. If you have received this email in error please notify us immediately by email to: ***@***.*** Registered Office: Transparity Solutions Limited, 9 Nimrod Way, East Dorset Trade Park, Wimborne, England, BH21 7UH. Registered in England No. 09420434
