### ISSUE TITLE
Individual Resource Exports timeout or crash

### ISSUE THREAD

**Issue by jeffreykarlan** [microsoft/Microsoft365DSC#2855]
My organization's daily operations heavily relies on Azure.  Just like our on-prem infrastructure, we need a backup/restoration strategy for our Azure configuration.  I've successfully configured Microsoft365DSC to export our Azure configuration using certificate thumbprint authentication.  My issue is that due to the size of my org when exporting individual resources like AADUser or AADGroup, the process runs for a couple of days and hangs.  Can anyone recommend a mitigation strategy to export for a large org?

Thank you

**Comment by NikCharlebois** [comment]
You could take a look at the -Filter parameter which would allow you to extract them in batch (e.g., 1 OU at a time).

**Comment by jeffreykarlan** [comment]
Ah ha!  Excellent suggestion like: `Export-M365DSCConfiguration -Credential $Credential -Filters @{AADUser = "DisplayName -ge 'a' -and DisplayName -le 'd'"}`?

**Comment by NikCharlebois** [comment]
Close. It's actually a Graph Filter, so the statement above would need to become:

-Filters @{AADUser = "DisplayName ge 'a' and DisplayName le 'd'"}

**Comment by jeffreykarlan** [comment]
Thanks a million!!!!
