### ISSUE TITLE
API permissions - Planner

### ISSUE THREAD

**Issue by martincaddick** [microsoft/Microsoft365DSC#2866]
I thought I was confused before, now I really am. Am I missing something?

Tasks.Read.All and Tasks.ReadWrite.All seem to be an Application Type permission not Delegated

From GraphCmdletPermissions.csv:

<img width="875" alt="TasksPermissionsCSV" src="https://user-images.githubusercontent.com/73564857/216226056-e6c55f32-0f0f-40cb-9cb2-a9935e1f726e.png">

From the MS GUI:
<img width="631" alt="TasksApplicationPerms" src="https://user-images.githubusercontent.com/73564857/216225792-040737f9-57a0-4e8b-9d08-f62b607b5b90.png">
<img width="503" alt="TasksDelegatedPerms" src="https://user-images.githubusercontent.com/73564857/216225801-70c75bb1-bd0e-4c9a-85ac-6a76025b92e4.png">

**Comment by ykuijs** [comment]
This needs updating since the API now supports application permissions. Will work on it!

**Comment by ykuijs** [comment]
Updated the required permissions and just submitted a PR. Once merged, the website documentation for the Planner resources will also be updated.
