### ISSUE TITLE
[IntuneDeviceConfigurationPolicyWindows10] EdgeSearchEngine property is handled incorrectly

### ISSUE THREAD

**Issue by ykuijs** [microsoft/Microsoft365DSC#2868]
#### Details of the scenario you tried and the problem that is occurring
There are two issues with the EdgeSearchEngine property:
1. The code is returning a sub property called edgeSearchEngineType https://github.com/microsoft/Microsoft365DSC/blob/296250b4bb8bced33f8c67f6d056b8471911e4c1/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows10/MSFT_IntuneDeviceConfigurationPolicyWindows10.psm1#L1081 However, when this property is written back to the Graph, it is not formatted properly, resulting in the below error
2. When you select the option "Custom Value" in the Admin Portal, the property '' doesn't exist, but 'edgeSearchEngineOpenSearchXmlUrl' is added with the value entered in the Admin Portal: `edgeSearchEngineOpenSearchXmlUrl https://test.nl/test.xml`

https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows10/MSFT_IntuneDeviceConfigurationPolicyWindows10.schema.mof#L181

#### Verbose logs showing the problem
```
##[error]Property edgeSearchEngine in payload has a value that does not match schema.
    + CategoryInfo          : InvalidOperation: ({ body = Micros...onfiguration1 }:) [], CimException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Graph.PowerShell.Cmdlets.NewMgDeviceManagementDeviceConfiguration_C 
   reateExpanded
    + PSComputerName        : localhost
```
#### Suggested solution to the issue
1. When writing back the config, the correct sub property needs to get selected.
2. When the provided value is an URL, the other property needs to get populated. The Get method also needs updating in this case to reflect this. As well as the description in the schema.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
IntuneDeviceConfigurationPolicyWindows10 'ConfigureDeviceConfigurationPolicyWindows10'
{
    displayName      = "CONTOSO | W10 | Device Restriction"
    edgeSearchEngine = "bing"
    Credential       = $credsGlobalAdmin
}
```

#### The operating system the target node is running
Windows 11

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by William-Francillette** [comment]
Same as #2867

**Comment by NikCharlebois** [comment]
@ykuijs @William-Francillette is this fixed? Can it be closed?

**Comment by William-Francillette** [comment]
Yes that can be closed
