### ISSUE TITLE
Update-M365DSCAllowedGraphScopes throwing error

### ISSUE THREAD

**Issue by Houdini-007** [microsoft/Microsoft365DSC#2878]
Hey all,

I'm having issues with the command: **Update-M365DSCAllowedGraphScopes**
https://microsoft365dsc.com/user-guide/cmdlets/Update-M365DSCAllowedGraphScopes/

**Running the command:**
Update-M365DSCAllowedGraphScopes -All -Type 'Read' -Environment 'Global'

**Throws error:**
Connect-MgGraph : AADSTS650053: The application 'Microsoft Graph PowerShell' asked for scope 'Tasks.Read.All' that doesn't exist on the resource '00000003
-0000-0000-c000-000000000000'. Contact the app vendor.
Trace ID: 8fc6b634-231d-452e-9ed1-750676ee9f00
Correlation ID: a2edfaae-ccd0-4b55-bced-50b2e538f67d
Timestamp: 2023-02-07 14:15:29Z
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.201.1\modules\M365DSCPermissions.psm1:392 char:15
     $result = Connect-MgGraph @params -Environment $Environment
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo          : NotSpecified: (:) [Connect-MgGraph], MsalServiceException
FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Authentication.Cmdlets.ConnectMgGraph







Any idea or suggestions are welcome.

**Comment by andikrueger** [comment]
Closed by #2874
