### ISSUE TITLE
Microsoft365DSC: Unable to run Update-M365DSCDependencies after install

### ISSUE THREAD

**Issue by 4e696e6a6121** [microsoft/Microsoft365DSC#2893]
### Issue Description
After a first time install of Microsoft365DSC and trying to run the "Update-M365DSCDependencies" cmdlet as specified within [https://microsoft365dsc.com/user-guide/get-started/how-to-install/](url) I get an error that states:

>  Update-M365DSCDependencies: The 'Update-M365DSCDependencies' command was found in the module 'Microsoft365DSC', but the module could not be loaded. For more information, run 'Import-Module Microsoft365DSC'.

### Steps to reproduce the issue

1. Download powershell-7.1.7-1.rhel.7.x86_64.rpm from PowerShell GitHub site. I understand that Microsoft365DSC still uses this version of PowerShell.
2. Install PowerShell `sudo yum install ~/Downloads/powershell-7.1.7-1.rhel.7.x86_64.rpm`
3. Run `pwsh`
4. Run `Install-Module Microsoft365DSC -Force`
5. Run `Update-M365DSCDependencies`
6. I run the `Import-Module Microsoft365DSC` as specified in the error message and get the following error message:

> Import-Module: The given assembly name or codebase was invalid. (0x80131047)

### Version Information
PowerShell Version: 7.1.7
OS Version: Fedora 37
Kernel Version: 6.1.9-200.fc37.x86_64 
Microsoft365DSC version: 1.23.208.1

The `Update-M365DSCDependencies` does not have a "verbose" switch so not sure how to grab additional logs but if you can let me know then I can certainly give it a go.

**Comment by andikrueger** [comment]
At the moment we do only support windows os.

please review this article for more information about ps7.x support. https://microsoft.github.io/Microsoft365DSC/user-guide/get-started/powershell7-support/

**Comment by kami-delaroz** [comment]
I had the same issue on Ubuntu 22.04 LTS.
Is there any ETA for supporting Linux?

**Comment by andikrueger** [comment]
At the moment, we do not have any ETA on the support of other systems than windows. This is unfortunately a restriction we have due to some dependencies that still required DLLs.

**Comment by cfizz34** [comment]
I get the same message on a windows endpoint

**Comment by dbroussa** [comment]
> I get the same message on a windows endpoint

I also am getting this same issue using Windows 11.
