### ISSUE TITLE
Extracting [AADGroup]: Your access token has expired. Please renew it before submitting the request.

### ISSUE THREAD

**Issue by Houdini-007** [microsoft/Microsoft365DSC#2915]
having timeout when running the script: [1/1] Extracting [AADGroup]

Using the Export-M365DSCConfiguration cmdlet generates the error:
Get-MgGroupMember : Your access token has expired. Please renew it before submitting the request.

The export tries to export +- 4200 group objects. Around group export number 3200 it starts to fail.
It doesn't renew the access token ... 

Any idea how to resolve this? This most likely exceeds the timeout of 1 hour? How do I renew the access token, and continue with the export without restarting? (because it can't finish the job under 1 hour)

Many thanks !

**Comment by andikrueger** [comment]
We have seen this issue in the past, but were no longer able to reproduce it. See #1668

**Comment by andikrueger** [comment]
Could you please share your M365DSC Version?

**Comment by Houdini-007** [comment]
PS C:\WINDOWS\system32> get-installedmodule Microsoft365DSC

Version    Name                                Repository           Description                                                                           
-------    ----                                ----------           -----------                                                                           
1.23.215.1 Microsoft365DSC                     PSGallery            This DSC module is used to configure and monitor Microsoft tenants, including Share...

**Comment by andikrueger** [comment]
What kind of authentication method are you using? I started a PS Session 3 hours ago and created a credential based connection. Right now I was able to get some proper results from MS Graph...

**Comment by andikrueger** [comment]
Just did some testing and I can confirm there is an issue with token expiration when application secrets are used. 

We need to investigate this further.

**Comment by andikrueger** [comment]
Just created a PR for MSCloudloginAssistant to handle the token lifetime issue that causes this error:

https://github.com/microsoft/MSCloudLoginAssistant/pull/142
