### ISSUE TITLE
Add option to add multiple App Insight instrumentation keys

### ISSUE THREAD

**Issue by ThorstenLoeschmann** [microsoft/Microsoft365DSC#292]
Add option to add multiple App Insight instrumentation keys

**Comment by NikCharlebois** [comment]
The idea here would be to allow users to still opt-in to submit telemetry back to the O365DSC team, but to also specify their own internal AppInsights key to also capture them internally.

**Comment by NikCharlebois** [comment]
@ThorstenLoeschmann just wondering if you are seeing a lot of demand from customers for this here. Not sure how high it should be ranked on the backlog items to address.

**Comment by ThorstenLoeschmann** [comment]
Haven't seen any further requests going into this direction so I would not rank it super high on the backlog.

**Comment by NikCharlebois** [comment]
After giving this further thinking, I don't think the demand is high enough for this type of hybrid scenario to risk introducing another area of troubleshooting. Let us know if this ever comes up with customers, we may review it then if we see a high demand for it.
