### ISSUE TITLE
Update-M365DSCResourceDocumentationPage cmdlet not working

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#2930]
The latest  update to 1.23.222.1 broke Update-M365DSCResourceDocumentationPage cmdlet, this is due to settings.json for resource IntuneDeviceEnrollmentConfigurationWindows10 since it contains two trailing commas that shouldn't be there and it errors out on ConvertFrom-Json.

```json
{
    "resourceName": "IntuneDeviceEnrollmentConfigurationWindows10",
    "description": "This resource configures an Intune Device Enrollment Status Page Configuration for Windows10.",
    "permissions": {
            },
            "application": {
                "read": [
                    {
                        "name": "DeviceManagementConfiguration.Read.All"
                    },
                    {
                        "name": "DeviceManagementServiceConfig.Read.All"
                    },
                ],
                "update": [
                    {
                        "name": "DeviceManagementConfiguration.ReadWrite.All"
                    },
                    {
                        "name": "DeviceManagementServiceConfig.ReadWrite.All"
                    }
                ]
            }
        }
    }
}

```

**Comment by andikrueger** [comment]
This issue does impact Update-M365DSCAllowedGraphScopes as well:

![image](https://user-images.githubusercontent.com/15608729/220874459-2e2d6a1e-92df-4c50-9e69-0d025de6e4f0.png)

We really need a check to get rid of these issues: #2912

**Comment by ykuijs** [comment]
Agree with that. I noticed this last evening as well and am already working on adding a QA check. Will fix this issue as well!
