### ISSUE TITLE
IntuneDeviceEnrollmentConfigurationWindows10: Missing properties

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#2933]
#### Details of the scenario you tried and the problem that is occurring
IntuneDeviceEnrollmentConfigurationWindows10 is missing Assignments and Priority, the latter defines which one should be chosen since there is already a default ESP configuration. Additionally the name of the resource may not be the best since there are other types of DeviceEnrollmentConfiguration, namely:

#microsoft.graph.deviceEnrollmentLimitConfiguration -> Already available through MSFT_IntuneDeviceEnrollmentLimitRestriction
#microsoft.graph.deviceEnrollmentPlatformRestrictionsConfiguration -> Already available through MSFT_IntuneDeviceEnrollmentPlatformRestriction
#microsoft.graph.deviceEnrollmentWindowsHelloForBusinessConfiguration -> There's no DSC resource available for this one yet
#microsoft.graph.windows10EnrollmentCompletionPageConfiguration -> This one, IntuneDeviceEnrollmentConfigurationWindows10

#### Suggested solution to the issue
Add missing properties and not so critical but probably change resource's name to something more specific to ESP.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        IntuneDeviceEnrollmentConfigurationWindows10 1e4aead4-af03-4d2d-9462-b7ea62cd69b4
        {
            AllowDeviceResetOnInstallFailure        = $True;
            AllowDeviceUseOnInstallFailure          = $False;
            AllowLogCollectionOnInstallFailure      = $True;
            AllowNonBlockingAppInstallation         = $False;
            BlockDeviceSetupRetryByUser             = $False;
            Credential                              = $Credscredential;
            CustomErrorMessage                      = "Installation exceeded 2 hours time limit. Try again or contact your IT Service Desk for help. ";
            Description                             = "";
            DisableUserStatusTrackingAfterFirstUser = $True;
            DisplayName                             = "Windows 10/11 - Enrollment Status Page";
            Ensure                                  = "Present";
            Id                                      = "aacbc050-fcd6-4a67-81ed-9075a30ad19c_Windows10EnrollmentCompletionPageConfiguration";
            InstallProgressTimeoutInMinutes         = 120;
            InstallQualityUpdates                   = $False;
            SelectedMobileAppIds                    = @();
            ShowInstallationProgress                = $True;
            TrackInstallProgressForAutopilotOnly    = $True;
        }
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.23.222.1

**Comment by William-Francillette** [comment]
I will look at adding the Assignment and priority to the resource
I agree with you about the resource name but renaming it would be a breaking change
@NikCharlebois Shall I rename the resource?

**Comment by NikCharlebois** [comment]
We have a small window of opportunity to rename the resource. Our next major release which can include breaking changes is on April 5th. If we can do it in time, then yes.

**Comment by William-Francillette** [comment]
@NikCharlebois I have been working on this issue - should be able to release the PR by the week end
I experienced a weird glitch with Confirm-M365DSCDependencies where when I call Get-TargetResource on its own I retrieve my policy as expected but during in the DSCConfiguration Test-TargetResource is returning false because when it calls Get-TargetResource it returns null due to the execution crashing at Confirm-M365DSCDependencies
