### ISSUE TITLE
Update-M365DSCAzureAdApplication always creates the app registration in the same tenant.

### ISSUE THREAD

**Issue by indecline** [microsoft/Microsoft365DSC#2951]
I'm sure I'm just doing something incorrectly here but I've been following the [whitepaper ](https://office365dsc.azurewebsites.net/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf) and am at the below step

`Update-M365DSCAzureAdApplication -ApplicationName Microsoft365DSC -Permissions @(@{ Api ="SharePoint";PermissionName="Sites.FullControl.All"},@{ Api ="Exchange";PermissionName="Exchange.ManageAsApp"}) -AdminConsent -Type Certificate -CertificatePath C:\M365Dsc\M365ClientCert.cer`

My issue is that I accidentally originally created this app registration in the wrong tenant and now I can't get it to create in the correct tenant. Where do you configure the tenant that this app registration should be configured in? I've tried starting from the beginning but it just recreates the app registration in the initial tenant. No authentication prompts 🤔 

Thanks for the assistance.

**Comment by andikrueger** [comment]
You need to run disconnect-azaccount and run connect-azaccount after that manually to change the tenant and get an auth prompt. I’ll look into the function code. I get the feeling there is no disconnect implemented.

**Comment by andikrueger** [comment]
@ykuijs Would you mind adding a Disconnect-AzAccount the get rid of this issue. At the moment the code does reuse any existing connection without making sure, that it is the proper tenant.

https://github.com/microsoft/Microsoft365DSC/blob/9bdbf3405d9784e1bca5e9b8335d9ff585dbe32d/Modules/Microsoft365DSC/Modules/M365DSCPermissions.psm1#L1357-L1362


I see two options

1. We would always run Disocnnect-AzAccount prior to running any further code
2. We would disconnect at the end of the function execution.

**Comment by indecline** [comment]
> You need to run disconnect-azaccount and run connect-azaccount after that manually to change the tenant and get an auth prompt. I’ll look into the function code. I get the feeling there is no disconnect implemented.

Thanks @andikrueger, just confirming that sorted it.

**Comment by ykuijs** [comment]
@andikrueger I would prefer that when you are connected we output the current tenant name to the screen and ask for confirmation if that is the correct tenant. What do you think about that idea?

Forcing a disconnect can cause another prompt for credentials or MFA, etc.

**Comment by andikrueger** [comment]
this sounds like a good compromise. I would very much like that.
