### ISSUE TITLE
Authentication: Can't connect to Microsoft Graph

### ISSUE THREAD

**Issue by TSGareth** [microsoft/Microsoft365DSC#2952]
Hello, I'm attempting to run Export-M365DSCConfiguration however I'm unable to get further than the MicrosoftGraph authentication

#### Details of the scenario you tried and the problem that is occurring
Running Export-M365DSCConfiguration on multiple different tenants returns the same error below: 
Connecting to {ExchangeOnline}...✅
Connecting to {MicrosoftGraph}...❌
The remote server returned an error: (404) Not Found.

I was able to complete an export over the last few weeks but this week I have updated to V1.23.222.1 and now I can't proceed past authentication. I'm able to connect-mggraph and also complete the Graph pre-reqs again through powershell but the export command doesn't get that far.

#### Verbose logs showing the problem

Only reference to Microsoft Graph is the below:
VERBOSE: No existing connections to Microsoft Graph

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

Export-M365DSCConfiguration -Components @("AADSecurityDefaults", "AADTenantDetails") -Credential $Credential -verbose

#### The operating system the target node is running

OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22000.1.amd64fre.co_release.210604-1628
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.23.222.1

**Comment by andikrueger** [comment]
What kind of authentication method do you use and could you please run

```
Connect-M365Tenant -Workload MSGraph -<Add the additional parameters for authentication>
```

**Comment by TSGareth** [comment]
Attempting to use credentials, ran this command: Connect-M365Tenant -Workload MicrosoftGraph -credential $credential

Get the following error:
Invoke-RestMethod : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.103
\Workloads\MicrosoftGraph.psm1:97 char:29
+ ... $OAuthReq = Invoke-RestMethod -Uri
$Global:MSCloudLoginConnectionProf ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest
   :HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.Powe
   rShell.Commands.InvokeRestMethodCommand



Gareth Danks
Technical Consultant
01202 800000
***@***.***
www.transparity.com
Please take a moment to fill in our customer survey
​Your opinion is important to us!

​The contents of this email and any attachments to it are confidential and are intended solely for the individual(s) and/or organisation(s) to whom this email is addressed. If you are not the intended recipient of this email any use, disclosure, forwarding, printing or copying of this email and any attachments to it by you may be unlawful. If you have received this email in error please notify us immediately by email to: ***@***.*** Registered Office: Transparity Solutions Limited, 9 Nimrod Way, East Dorset Trade Park, Wimborne, England, BH21 7UH. Registered in England No. 09420434

**Comment by icpw** [comment]
VERBOSE: No existing connections to Microsoft Graph  - this does not mean anything, it is just telling you that the existing connections have been closed or there are no connections before it proceeds to open them with the supplied credentials.

I find it useful to add these parameters to any command that does not work as expected:
 -ErrorVariable errvar -verbose -ErrorAction Inquire
then check the output in the console and the variable $errvar
