### ISSUE TITLE
Exporting resource "IntuneDeviceConfigurationPolicyWindows10" not including all data

### ISSUE THREAD

**Issue by icpw** [microsoft/Microsoft365DSC#2976]
DEVICE (running scripts)

OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, en-US}

Microsoft365DSC version:
ModuleBase                                                            Version   
----------                                                            -------   
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.301.1 1.23.301.1

    ISSUE TITLE:
    Exporting resource "IntuneDeviceConfigurationPolicyWindows10" not exporting all data.

 ISSUE DESCRIPTION
    I have more than 20 policies defined and only 3 are exported

I have successfully exported ALL the policies using deviceconfiguration-get.ps1 from Microsoft Intune samples

Command:

Export-M365DSCConfiguration -Components @($c) -CertificateThumbprint $Thumbprint -TenantId $TenantID -ApplicationId $AppID -Path $outpath -FileName $outfile -ConfigurationName $C -ErrorVariable err -verbose -ErrorAction Continue
VERBOSE: No existing connections to Microsoft Graph
Exporting Microsoft 365 configuration for Components: IntuneDeviceConfigurationPolicyWindows10
 
Authentication methods specified:
- Service Principal with Certificate Thumbprint

VERBOSE: Dependencies were already successfully validated.
VERBOSE: ApplicationId, TenantId, CertificateThumbprint were specified. Connecting via Service Principal
VERBOSE: Dependencies were already successfully validated.

Connecting to {MicrosoftGraph}...✅
[1/1] Extracting [IntuneDeviceConfigurationPolicyWindows10] using {CertificateThumbprint}...VERBOSE: Attempting connection to {MicrosoftGraph} with:
Certificate
Tenantid
ApplicationID

    |---[1/3] ACSC - Device RestrictionsVERBOSE: Attempting connection to {MicrosoftGraph} with:
VERBOSE: 
Name                           Value                                                                                                                                                                     
----                           -----                                                                                                                                                                     
ApplicationSecret                                                                                                                                                                                        
ApplicationId                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                     
ManagedIdentity                False                                                                                                                                                                     
Ensure                         Present                                                                                                                                                                   
Credential                                                                                                                                                                                               
TenantId                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                      
CertificateThumbprint          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                  
DisplayName                    ACSC - Device Restrictions      

    |---[2/3] Custom - Device RestrictionsVERBOSE: Attempting connection to {MicrosoftGraph} with:
VERBOSE: 
Name                           Value                                                                                                                                                                     
----                           -----                                                                                                                                                                     
ApplicationSecret                                                                                                                                                                                        
ApplicationId                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                      
ManagedIdentity                False                                                                                                                                                                     
Ensure                         Present                                                                                                                                                                   
Credential                                                                                                                                                                                               
TenantId                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                      
CertificateThumbprint         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                  
DisplayName                    Custom - Device Restrictions                                                                                                                                              

VERBOSE: Dependencies were already successfully validated.
VERBOSE: ApplicationId, TenantId, CertificateThumbprint were specified. Connecting via Service Principal
VERBOSE: Dependencies were already successfully validated.

    |---[3/3] Windows 10 Device ConfigVERBOSE: Attempting connection to {MicrosoftGraph} with:
VERBOSE: 
Name                           Value                                                                                                                                                                     
----                           -----                                                                                                                                                                     
ApplicationSecret                                                                                                                                                                                        
ApplicationId                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                   
ManagedIdentity                False                                                                                                                                                                     
Ensure                         Present                                                                                                                                                                   
Credential                                                                                                                                                                                               
TenantId                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                     
CertificateThumbprint          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                                                                  
DisplayName                    Windows 10 Device Config                                                                                                                                                  

VERBOSE: Dependencies were already successfully validated.
VERBOSE: ApplicationId, TenantId, CertificateThumbprint were specified. Connecting via Service Principal
VERBOSE: Dependencies were already successfully validated.

⌛ Export took {37 seconds}

Is there a filter being applied when querying the resource?
NOTE: The policies being exported are all of type "Device Restrictions".
I have other policy types like "Delivery Optimization","Administrative Templates", "Custom", "Endpoint Protection", "Network Boundary" and "Device Features"  - all policies copied from the Australian Government Blueprint (desktop.gov.au)
These policy types are not being exported.

Thanks for all your effort for developing and supporting this great resource.

**Comment by William-Francillette** [comment]
This resource only retrieve the general device restriction and thus only retrieving 3 of your policies
if you could send us a screenshot of your policy types, I will be able to tell you what is available at present 

Thanks

**Comment by icpw** [comment]
I have other policy types like "Delivery Optimization", "Administrative Templates", "Custom", "Endpoint Protection", "Network Boundary" and "Device Features"

**Comment by William-Francillette** [comment]
@icpw some of those will be releases in the next upgrade like delivery optimisation and endpoint protection some under development like administrative template and the others will be added as feature request and developed asap.

thanks

**Comment by icpw** [comment]
Thank you for your response William-Francillette.  I am looking forward to the release of all policy types whenever they are available.  I was surprised that they were missing because I could not see that in the documentation.  Are you going to cover the custom type with the OMA-URI configuration?

**Comment by William-Francillette** [comment]
Yep, I was working on it yesterday - should be released soon

**Comment by icpw** [comment]
Everyone's efforts are much appreciated. This is a great tool.

**Comment by William-Francillette** [comment]
All Setting Template (Device Configuration) have been implemented - this issue can be closed after this week update @andikrueger
