### ISSUE TITLE
Logging improvement request

### ISSUE THREAD

**Issue by anpiskai** [microsoft/Microsoft365DSC#2981]
In order to correlate events more easily between drifted and non-drifted resources for reporting purposes, is it possible to **_include either one_** of the following?

- Include the **_InstanceName_** value (as visible from the output of the Test-DSCConfiguration command) within the logged M365DSC drift events that are created
- Create informational events for **_non-drifted_** M365DSC events to complement the drifted M365DSC events already being created with the desired attribute list (similar to current drift events).

Either of these approaches would permit a common attribute to be referenced regardless of drifted/not-drifted status for any given resource.

**Comment by anpiskai** [comment]
It looks like the second option (logging non-drifted events to event logs) would be more easily implemented because the event generation is centralized in the M365DSCUtil.psm1 file. (By contrast, the first option seems like it would require modifying each DSC resource to pass in an instance identity attribute in the Test step into Test-M365DSCParameterState).

In that file, we could add an else to complement the if($returnValue -eq $false) section in the Test-M365DSCParameterState command to handle and generate events for when $returnValue -eq $true. 

Perhaps adding something like:

```
elseif($returnValue -eq $true)
    {
        $EventMessage = "<M365DSCEvent>`r`n"
        $EventMessage += "    <ConfigurationDrift Source=`"$Source`">`r`n"
        $EventMessage += "        <ParametersNotInDesiredState>`r`n"
        $EventMessage += "        </ParametersNotInDesiredState>`r`n"
        $EventMessage += "    </ConfigurationDrift>`r`n"
        $EventMessage += "    <DesiredValues>`r`n"
        foreach ($Key in $DesiredValues.Keys)
        {
            $Value = $DesiredValues.$Key
            if ([System.String]::IsNullOrEmpty($Value))
            {
                $Value = "`$null"
            }
            $EventMessage += "        <Param Name =`"$key`">$Value</Param>`r`n"
        }
        $EventMessage += "    </DesiredValues>`r`n"
        $EventMessage += '</M365DSCEvent>'

        Add-M365DSCEvent -Message $EventMessage -EventType 'NoDrift' -EntryType 'Information' `
            -EventID 1 -Source $Source
    }
```

**Comment by ykuijs** [comment]
The InstanceName is not available inside of the resource code, so that option is not possible unfortunately.
Adding an entry for each non-drifted resource will add a huge amount of additional logging data to the event log.

Currently we are outputting the Desired State to the event log as well. That should contain all the information you need to determine what resource it is all about. Isn't that what you are looking for?

**Comment by ykuijs** [comment]
Ah ok, I understand what you are looking for here. Let us think if this would be feasible and what would be the best way to implement this.

As a workaround: You could use the value of the Key parameter(s) in the instance name, so you are able to match the results.

**Comment by anpiskai** [comment]
Are you saying to specify the instance name within the DSC configuration to match what the value being used from the event log output?

If so, that could be a workaround, but it is subject to mistakes if people don't comply since it's a different attribute. They could be set to the same value, but it requires compliance by all the code authors to get correct.
