### ISSUE TITLE
Issue while configuring The DSC node for TeamsDialInConferencingTenantSettings, PPTenantSettings and PPTenantIsolationSettings. 

### ISSUE THREAD

**Issue by maheshdalavi** [microsoft/Microsoft365DSC#2984]
####   ISSUE TITLE:
-> Issue while configuring The DSC node for TeamsDialInConferencingTenantSettings, PPTenantSettings and PPTenantIsolationSettings. 
-> Credential Based process is working fine.

####   ISSUE DESCRIPTION (this template):
Below Error are encountered while configuring the DSC node
->TeamsDialInConferencingTenantSettings: 
	_**_Error: “SourceInfo C:\Microsoft365DSC\configcertbsed\Error\M365TenantConfig.ps1::63::9::TeamsDialInConferencingTenantSettings' threw one or more non-terminating errors while running the Test-TargetResource functionality.”_**_

-> PPTenantSettings and PPTenantIsolationSettings:  
**_Error: in DSC configuration “PowerShell DSC resource MSFT_PPTenantIsolationSettings failed to execute Test-TargetResource functionality with error”_**

#### Details of the scenario you tried and the problem that is occurring
Run the below command. 
```
Export-M365DSCConfiguration -Components @("PPTenantIsolationSettings", "PPTenantSettings", "O365AdminAuditLogConfig", "SPOHomeSite", "TeamsDialInConferencingTenantSettings") -credential $credentials
-ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId 

```
Successfully configured the Localhost.mof 
Tried configuring the DSC node and got the error.
```
Start-DscConfiguration -Path C:\Microsoft365DSC\config2\M365TenantConfig -Wait -Verbose -Force
```
Error file: Transcript_error.log file attached

#### Verbose logs showing the problem
Transcript_error.log file attached.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
M365config.ps1 attached.
#### The operating system the target node is running

OsName               : Microsoft Windows 11 Home Single Language
OsOperatingSystemSKU : 100
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}-->

#### Version of the DSC module that was used ('dev' if using current dev branch)
[transcript_error.log](https://github.com/microsoft/Microsoft365DSC/files/10923596/transcript_error.log)
[M365TenantConfig.txt](https://github.com/microsoft/Microsoft365DSC/files/10923602/M365TenantConfig.txt)
[localhost.mof.txt](https://github.com/microsoft/Microsoft365DSC/files/10923606/localhost.mof.txt)

**Comment by icpw** [comment]
You have a certificate that cannot be found and licencing that may not be present or features disabled for tenant.
I would try not using the -path parameter, or if you do, use C:\Microsoft365DSC\config2 to see if that makes a difference.
I prefer to compile the script and then use just the resource name in start-dscconfiguration, but that is just me. The wider community may do it differently. 

The thing that would help you the most is to try one component at a time, so that you can narrow down the issue to a single component.

**Comment by maheshdalavi** [comment]
@icpw
1. No default settings were pulled for these DSC resources (Properties)
   I have some settings in Power Platform. No matter what I changed on GUI was not tracked in ("PPTenantIsolationSettings", "PPTenantSettings"). With PS i made some specific changes to the tenant setting and then ( S_et-TenantSettings -RequestBody $requestBody
$requestBody = @{
   disableSurveyFeedback = $true
   walkMeOptOut = $true_)

and then Details were pulled( sort of trigger )

2. Though the details were Pulled tried to configure the DSC node and same error ( error logs attached)

**Would like to know if it is working for you ?**

============
- Licenses are not the issue, because it is happing with more than One tenant ( in Org Dev as well)
- features are not disabled for tenants. Actively using it.
-  Certificate is in place and working fine for other modules/components ( only PowerPlatform is affected)
- Tried without "-path" no gain.
>Start-DscConfiguration -path .\ -Wait -Verbose -Force
==============================


>PS C:\Microsoft365DSC\Policy> get-tenantsettings
walkMeOptOut                                   : False
disableNPSCommentsReachout                     : False
disableNewsletterSendout                       : False
disableEnvironmentCreationByNonAdminUsers      : False
disablePortalsCreationByNonAdminUsers          : False
disableSurveyFeedback                          : False
disableTrialEnvironmentCreationByNonAdminUsers : False
disableCapacityAllocationByEnvironmentAdmins   : False
disableSupportTicketsVisibleByAllUsers         : False
powerPlatform                                  : @{search=; teamsIntegration=; powerApps=; environments=; governance=; licensing=; powerPages=; champions=}


>PS C:\Microsoft365DSC\Policy> $requestBody = @{
   disableSurveyFeedback = $true
   walkMeOptOut = $true}

>PS C:\Microsoft365DSC\Policy> Set-TenantSettings -RequestBody $requestBody
walkMeOptOut                                   : True
disableNPSCommentsReachout                     : False
disableNewsletterSendout                       : False
disableEnvironmentCreationByNonAdminUsers      : False
disablePortalsCreationByNonAdminUsers          : False
disableSurveyFeedback                          : True
disableTrialEnvironmentCreationByNonAdminUsers : False
disableCapacityAllocationByEnvironmentAdmins   : False
disableSupportTicketsVisibleByAllUsers         : False
powerPlatform                                  : @{search=; teamsIntegration=; powerApps=; environments=; governance=; licensing=; powerPages=; champions=}
[error.log](https://github.com/microsoft/Microsoft365DSC/files/10934510/error.log)

**Comment by icpw** [comment]
You still have this error in the error logs
Cannot find path 'Cert:\CurrentUser\My\921ACF3B3D0489ECCCEF1416E599F00E5FE28BB6' because it does not exist.

**Comment by maheshdalavi** [comment]
@icpw As is said in the previous comment "Certificate is in place and working fine for other modules/components ( only PowerPlatform is affected)"

I would like to know if you tried it and if it is working for you ?

**Comment by NikCharlebois** [comment]
The problem here is that when running Start-DSCConfiguration, the process is started in the context of the LocalSystem user and the certificate isn't in the personal store of that user. Try adding it to the LocalSystem store and that should fix the error.

**Comment by NikCharlebois** [comment]
Related issue with solution:
https://github.com/microsoft/Microsoft365DSC/issues/1602

**Comment by maheshdalavi** [comment]
@NikCharlebois 
- Not sure why not working for me. M I doing something wrong?
- Installed/Added the cert using PsExec in Localsystem. And by double click on cert as we (Gui)
> certutil -addstore -f "LocalSystem" "C:\Microsoft365DSC\Certs\M365ClientCert.cer"
- Confirmed that cert is present at all expected locations ( Help me if i am missing any )

> C:\Windows\System32>certutil -store LocalSystem | findstr 921acf3b3d0489ecccef1416e599f00e5fe28bb6
> Cert Hash(sha1): 921acf3b3d0489ecccef1416e599f00e5fe28bb6
> C:\Windows\System32>certutil -store root | findstr 921acf3b3d0489ecccef1416e599f00e5fe28bb6
> Cert Hash(sha1): 921acf3b3d0489ecccef1416e599f00e5fe28bb6
> C:\Windows\System32>certutil -store my | findstr 921acf3b3d0489ecccef1416e599f00e5fe28bb6
> Cert Hash(sha1): 921acf3b3d0489ecccef1416e599f00e5fe28bb6

- Ran Start-DSCConfiguration command and failed with the same error( file Attached with command error and cert details)

Cert has been installed at all the below Locations...
 gci Cert:\CurrentUser\root
 gci Cert:\CurrentUser\My
 gci Cert:\Localmachine\root
 gci Cert:\Localmachine\LocalSystem  
 gci Cert:\Localmachine\my
[certerror.log](https://github.com/microsoft/Microsoft365DSC/files/10998570/certerror.log)

**Comment by maheshdalavi** [comment]
@NikCharlebois Thanks a lot !!!
- After following your steps, the issue was resolved.
- Few thoughts,,,,These steps should be documented under "User Guide" documentation for the PowerPlatform workload. Though they are in the Concept tab, but no instructions to use them for PowerPlatform. [ https://microsoft365dsc.com/concepts/odsp-permissions/ ]
