### ISSUE TITLE
IntuneASRRulesPolicyWindows10 - unable to create new policy without Identity

### ISSUE THREAD

**Issue by powershellpr0mpt** [microsoft/Microsoft365DSC#2985]
#### Details of the scenario you tried and the problem that is occurring
When wanting to create a new Intune ASR Policy for Windows 10, you are unable to do so because the `Identity` key is required
![image](https://user-images.githubusercontent.com/9294993/223995269-1480cfdf-d52f-43a3-8bc6-e4497cf716ca.png)

However when looking at the code, in case an ASR rule is defined but not present, [DSC will create a new one for you](https://github.com/microsoft/Microsoft365DSC/blob/aa6ac61d2ed2b4bcc8d990f59f1613cb31a7d685/Modules/Microsoft365DSC/DSCResources/MSFT_IntuneASRRulesPolicyWindows10/MSFT_IntuneASRRulesPolicyWindows10.psm1#L415).
#### Suggested solution to the issue
Would it be so simple as to remove the `Mandatory` requirement for the `Identity` parameter?
Or is there something I'm missing?

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        IntuneASRRulesPolicyWindows10 "Test ASR" {
            Assignments                                     = @();
            AdobeReaderLaunchChildProcess                   = "auditMode";
            AdvancedRansomewareProtectionType               = "auditMode";
            BlockPersistenceThroughWmiType                  = "userDefined";
            DisplayName                                     = "Test ASR";
            EmailContentExecutionType                       = "auditMode";
            GuardMyFoldersType                              = "auditMode";
            # Identity                                        = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
            OfficeAppsExecutableContentCreationOrLaunchType = "auditMode";
            OfficeAppsLaunchChildProcessType                = "auditMode";
            OfficeAppsOtherProcessInjectionType             = "auditMode";
            OfficeCommunicationAppsLaunchChildProcess       = "auditMode";
            OfficeMacroCodeAllowWin32ImportsType            = "auditMode";
            PreventCredentialStealingType                   = "enable";
            ProcessCreationType                             = "auditMode";
            ScriptDownloadedPayloadExecutionType            = "auditMode";
            ScriptObfuscatedMacroCodeType                   = "auditMode";
            UntrustedExecutableType                         = "auditMode";
            UntrustedUSBProcessType                         = "auditMode";
            ApplicationId                                   = $ConfigurationData.NonNodeData.ApplicationId
            TenantId                                        = $ConfigurationData.NonNodeData.TenantId
            CertificateThumbprint                           = $ConfigurationData.NonNodeData.CertificateThumbprint
            Ensure                                          = 'Present'
        }

```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2022 Datacenter Azure Edition
OsOperatingSystemSKU : 407
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.1.amd64fre.fe_release.210507-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

**Comment by powershellpr0mpt** [comment]
Ok, so if I understand correctly this is related to the whole "perhaps we need a M365DSC GUID as key" discussion again (as mentioned here #2947 and here #2006 ), as a key entry is required, so I can't simply remove the Identity as mandatory

**Comment by William-Francillette** [comment]
@powershellpr0mpt, you can create a new policy by adding any string in Identity which will initiate the create action as the id and displayName won't be found.
The next time, the DSC engine runs, it will be able to retrieve your resource using the displayName even though the id is incorrect.

**Comment by andikrueger** [comment]
@William-Francillette  the current implementation will not work properly. The identity is the key of the resource and it is obviously drifting. The next time you would run this configuration, a drift will be detected (missing resource) and this should lead to a new element being created.

**Comment by William-Francillette** [comment]
After reading the related threads I think i understand better the issue, even if we disregard the id, there will always be potentially a resource with a duplicated name.
I need to test the behaviour of key as I'm not sure I fully understand how the LCM interpret it 
I always assumed the drift will be detected in Test-TargetResource so skipping or overwriting the id/key would have worked, I only recently added a key to the schema I was using write for all the parameters before

Ill revert back asap

**Comment by William-Francillette** [comment]
It is a challenging one indeed
Id cannot be added during a new object creation
DisplayName cannot either be a key as it is not unique and can be changed 
I second your idea of M365DSCUniqueId in #2006  as it would basically mimic what is the immutableId in AAD connect and hybrid exchange mailboxes 
However generating the uniqueId for creating a new resource from the export will still be a challenge

**Comment by ykuijs** [comment]
PR #2968 is updating all Intune resources, making the Identity parameter Key and mandatory and the DisplayName parameter mandatory.

When you are provisioning a new environment, you can specify a dummy value for the Identity. The code will ignore this parameter and use the DisplayName to create and check the policy for Drift.
