### ISSUE TITLE
Inconsistency in Security and Compliance workload for CertBased Authentication and Credential based Authentication.

### ISSUE THREAD

**Issue by maheshdalavi** [microsoft/Microsoft365DSC#2990]
####   ISSUE TITLE:
•	Inconsistency in Security and Compliance workload for CertBased Authentication and Credential based Authentication.

####   ISSUE DESCRIPTION (this template):
•	Pull SC workload with Cert and Credential based authentication.
•	Many SCComplianceSearchresults and SecurityComplianceCenter were not pulled properly.
•	Both M365tenanConfig.txt attached.
•	Compliance Admin role is assigned to Application.

#### Details of the scenario you tried and the problem that is occurring
•	Run the below command. 
```
PS C:\Microsoft365DSC\SC_cretificate_based> Export-M365DSCConfiguration -Components @("SCComplianceCase", "SCComplianceSearch") -Credential $cred
Exporting Microsoft 365 configuration for Components: SCComplianceCase, SCComplianceSearch

Authentication methods specified:
- Credentials

Connecting to {SecurityComplianceCenter}...✅
[1/2] Extracting [SCComplianceCase] using {Credentials}...
    eDiscovery: [1/8] mahesh Gmail✅
    eDiscovery: [2/8] GDPR✅
    eDiscovery: [3/8] Mahesh_15122021✅
    eDiscovery: [4/8] User data Search✅
    eDiscovery: [5/8] Mahesh_Gmail_2✅
    eDiscovery: [6/8] mahesh ediscovery✅
    eDiscovery: [7/8] DSR✅
    eDiscovery: [8/8] Info protection ediscovery case✅
    GDPR: [1/1] sonika1✅
[2/2] Extracting [SCComplianceSearch] using {Credentials}...
* Searches not assigned to an eDiscovery Case
        |---[1/1] New content Search ✅
    * [1/8] Searches assigned to case mahesh Gmail
    * [2/8] Searches assigned to case GDPR
    * [3/8] Searches assigned to case Mahesh_15122021
        |---[1/1] Core Search Dec15122021✅
    * [4/8] Searches assigned to case User data Search
    * [5/8] Searches assigned to case Mahesh_Gmail_2
    * [6/8] Searches assigned to case mahesh ediscovery
        |---[1/2] ediscovery search mahesh✅
        |---[2/2] ediscovery Search✅
    * [7/8] Searches assigned to case DSR
    * [8/8] Searches assigned to case Info protection ediscovery case
        |---[1/1] check for labels✅
⌛ Export took {106 seconds}

Destination Path: C:\Microsoft365DSC\SC_Credentials_Based
```
**And for CertBased Auth below are the details pulled.**
```
PS C:\Users\MSUSERSL123> Export-M365DSCConfiguration -Components @("SCComplianceCase", "SCComplianceSearch") -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId
Exporting Microsoft 365 configuration for Components: SCComplianceCase, SCComplianceSearch

Authentication methods specified:
- Service Principal with Certificate Thumbprint

Connecting to {SecurityComplianceCenter}...✅
[1/2] Extracting [SCComplianceCase] using {CertificateThumbprint}...✅
[2/2] Extracting [SCComplianceSearch] using {CertificateThumbprint}...
* Searches not assigned to an eDiscovery Case
        |---[1/1] New content Search ✅
⌛ Export took {87 seconds}```
Export-M365DSCConfiguration -Workloads SC -Mode full -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId -path C:\Microsoft365DSC\SC_CertBased_all
```

#### Verbose logs showing the problem
Config attached.
#### The operating system the target node is running

OsName               : Microsoft Windows 11 Home Single Language
OsOperatingSystemSKU : 100
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}-->
[M365TenantConfig_credentialBased.txt]

#### Version of the DSC module that was used ('dev' if using current dev branch)
[M365TenantConfig_certBased.txt](https://github.com/microsoft/Microsoft365DSC/files/10939773/M365TenantConfig_certBased.txt)
(https://github.com/microsoft/Microsoft365DSC/files/10939778/M365TenantConfig_credentialBased.txt)
[M365TenantConfig_credentialBased.txt](https://github.com/microsoft/Microsoft365DSC/files/10939782/M365TenantConfig_credentialBased.txt)

**Comment by NikCharlebois** [comment]
I am following up with the engineering team responsible for this one. I am able to replicate in my environment where:

```
Connect-IPPSSession -Credential <xxx>
Get-ComplianceCase
```

Returns results and where:

```
Connect-IPPSSession -AppId <xxx> -Organization <xxx> -CertificateThumbprint <xxx>
Get-ComplianceCase
```

Doesn't return anything even though Global Admin has been granted to the Service Principal. I will circle back here once I hear back.

**Comment by NikCharlebois** [comment]
We have confirmed with the product group that this is a known issue with the Security and Compliance PowerShell module and that a fix has been committed and should be available shortly. We will keep this thread updated once the fix has been rolled out.

**Comment by andikrueger** [comment]
@NikCharlebois is there any update from the PG?

**Comment by NikCharlebois** [comment]
Latest version 3.2.0, was released yesterday and still has the issue. Will circle back again with PG.

**Comment by NikCharlebois** [comment]
There are a couple additional things that need to be configured first. I've updated the documentation on how to proceed here:
https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/#security-and-compliance-center-permissions
