### ISSUE TITLE
EXOApplicationAccessPolicy “Object couldn’t be found on the child domain.”

### ISSUE THREAD

**Issue by icpw** [microsoft/Microsoft365DSC#2998]
Microsoft365DSC version 1.23.308.1
OsName : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture : 64-bit
WindowsVersion : 2009
WindowsBuildLabEx : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage : en-GB
OsMuiLanguages : {en-GB, en-US}

$c="EXOApplicationAccessPolicy"
Export-M365DSCConfiguration -Components @($c) -ApplicationId $applicationid -TenantId $tenantid -CertificateThumbprint $thumbprint -Path $outpath -FileName $outfile -ConfigurationName $C -ErrorVariable err -ErrorAction Inquire

Invoke-WebRequest : {"error":{"code":"NotFound","message":"Error executing cmdlet","details":[{"code":"Context","target":"","message":"Ex6F9304|Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException|The operation couldn't be performed because object 
'OU=abc.onmicrosoft.com,OU=Microsoft Exchange Hosted Organizations,DC=AUSPxxxx005,DC=PROD,DC=OUTLOOK,DC=COM\\*' couldn't be found on 'SYYP282A05DC002.AUSPxxxx005.PROD.OUTLOOK.COM'."}],"innererror":{"message":"Error executing 
cmdlet","type":"Microsoft.Exchange.Admin.OData.Core.ODataServiceException","stacktrace":"   at Microsoft.Exchange.AdminApi.CommandInvocation.CommandInvocation.InvokeCommand(QueryContext queryContext, CmdletInvokeInputType cmdletInvokeInputType)\r\n   at 
Microsoft.Exchange.Admin.OData.Core.PathSegmentToExpressionTranslator.Translate(OperationImportSegment segment)\r\n   at Microsoft.Exchange.Admin.OData.Core.QueryContext.ResolveQuery(ODataContext context, Int32 level)\r\n   at 
Microsoft.Exchange.Admin.OData.Core.Handlers.OperationHandler.Process(IODataRequestMessage requestMessage, IODataResponseMessage responseMessage)\r\n   at Microsoft.Exchange.Admin.OData.Core.Handlers.RequestHandler.Process(Stream 
requestStream)","internalexception":{"message":"Exception of type 'Microsoft.Exchange.Management.PSDirectInvoke.DirectInvokeCmdletExecutionException' was thrown.","type":"Microsoft.Exchange.Management.PSDirectInvoke.DirectInvokeCmdletExecutionException","stacktrace":"   
at Microsoft.Exchange.Management.PSDirectInvoke.PSDirectInvokeCmdletFactory.InvokeCmdletInternal[TCmdlet,TResult](Func`1 createCmdlet, Action`1 setParameterDelegate, List`1 captureAdditionalIO, List`1 directInvokeExceptions, Boolean 
shouldAllowProactiveProxyToReturnRoutingHint)"}}}}

[EXOApplicationAccessPolicy.ps1.txt](https://github.com/microsoft/Microsoft365DSC/files/10964551/EXOApplicationAccessPolicy.ps1.txt)

**Comment by icpw** [comment]
[error1.txt](https://github.com/microsoft/Microsoft365DSC/files/11144618/error1.txt)
Not sure if this is related or whether I should create a new issue.
EXOCASMailboxSettings
{"error":{"code":"NotFound","message":"Error executing cmdlet","details":[{"code":"Context","target":"","message":"Ex6F9304|Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException|The operation couldn't be performed because object 
'ITServices@itg.com' couldn't be found on 'SY2PxxxxxxxxxxxxxxxxxxxxxA006.PROD.OUTLOOK.COM'."}],"innererror":{"message":"Error executing cmdlet","type":"Microsoft.Exchange.Admin.OData.Core.ODataServiceException","stacktrace":"   at 
Microsoft.Exchange.AdminApi.CommandInvocation.CommandInvocation.InvokeCommand(QueryContext queryContext, CmdletInvokeInputType cmdletInvokeInputType)\r\n   at Microsoft.Exchange.Admin.OData.Core.PathSegmentToExpressionTranslator.Translate(OperationImportSegment 
segment)\r\n   at Microsoft.Exchange.Admin.OData.Core.QueryContext.ResolveQuery(ODataContext context, Int32 level)\r\n   at Microsoft.Exchange.Admin.OData.Core.Handlers.OperationHandler.Process(IODataRequestMessage requestMessage, IODataResponseMessage 
responseMessage)\r\n   at Microsoft.Exchange.Admin.OData.Core.Handlers.RequestHandler.Process(Stream requestStream)","internalexception":{"message":"Exception of type 'Microsoft.Exchange.Management.PSDirectInvoke.DirectInvokeCmdletExecutionException' was 
thrown.","type":"Microsoft.Exchange.Management.PSDirectInvoke.DirectInvokeCmdletExecutionException","stacktrace":"   at Microsoft.Exchange.Management.PSDirectInvoke.PSDirectInvokeCmdletFactory.InvokeCmdletInternal[TCmdlet,TResult](Func`1 createCmdlet, Action`1 
setParameterDelegate, List`1 captureAdditionalIO, List`1 directInvokeExceptions, Boolean shouldAllowProactiveProxyToReturnRoutingHint)"}}}}
Invoke-WebRequest : {"error":{"code":"NotFound","message":"Error executing cmdlet","details":[{"code":"Context","target":"","message":"Ex6F9304|Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException|The operation couldn't be performed because object 
'ITServices@itg.com' couldn't be found on 'SY2PxxxxxxxxxxxxxxxxxxxxxA006.PROD.OUTLOOK.COM'."}],"innererror":{"message":"Error executing cmdlet","type":"Microsoft.Exchange.Admin.OData.Core.ODataServiceException","stacktrace":"   at 
Microsoft.Exchange.AdminApi.CommandInvocation.CommandInvocation.InvokeCommand(QueryContext queryContext, CmdletInvokeInputType cmdletInvokeInputType)\r\n   at Microsoft.Exchange.Admin.OData.Core.PathSegmentToExpressionTranslator.Translate(OperationImportSegment 
segment)\r\n   at Microsoft.Exchange.Admin.OData.Core.QueryContext.ResolveQuery(ODataContext context, Int32 level)\r\n   at Microsoft.Exchange.Admin.OData.Core.Handlers.OperationHandler.Process(IODataRequestMessage requestMessage, IODataResponseMessage 
responseMessage)\r\n   at Microsoft.Exchange.Admin.OData.Core.Handlers.RequestHandler.Process(Stream requestStream)","internalexception":{"message":"Exception of type 'Microsoft.Exchange.Management.PSDirectInvoke.DirectInvokeCmdletExecutionException' was 
thrown.","type":"Microsoft.Exchange.Management.PSDirectInvoke.DirectInvokeCmdletExecutionException","stacktrace":"   at Microsoft.Exchange.Management.PSDirectInvoke.PSDirectInvokeCmdletFactory.InvokeCmdletInternal[TCmdlet,TResult](Func`1 createCmdlet, Action`1 
setParameterDelegate, List`1 captureAdditionalIO, List`1 directInvokeExceptions, Boolean shouldAllowProactiveProxyToReturnRoutingHint)"}}}}
At C:\Users\icadmin\AppData\Local\Temp\tmpEXO_mzro3fct.pix\tmpEXO_mzro3fct.pix.psm1:1414 char:31

**Comment by NikCharlebois** [comment]
Very strange. I am able to replicate on every single one of our tenants by using the out of the box EXO module:

```powershell
Connect-ExchangeOnline -Credential $creds
Get-ApplicationAccessPolicy
```

@malauter any idea what could be the root cause here?

**Comment by malauter** [comment]
I can only reproduce this error in tenants without any access policy configured. As soon as I have created an application access policy, Get-ApplicationAccessPolicy is working.
It seems that this error is the default output if no application access policy can be found in the tenant.

Application access policies will be replaced by RBAC for Applications anyway soon.

**Comment by NikCharlebois** [comment]
The resource now handles the error handling. As @malauter mentions, this will soon be replaced by RBAC.

**Comment by vijayamirtharajingit** [comment]
Hi NikCharlebois, I'm still seeing issue with creating access policy. I see the error action is still 'Stop' - https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/DSCResources/MSFT_EXOApplicationAccessPolicy/MSFT_EXOApplicationAccessPolicy.psm1#L99
