### ISSUE TITLE
Suspicious behavior Behavior:Win32/Trikombu.B while installing Microsoft365DSC

### ISSUE THREAD

**Issue by kirilvalev** [microsoft/Microsoft365DSC#3012]
After executing the following command, Defender found a suspicious behavior Behavior:Win32/Trikombu.B. Is this known, or is something else interferring?

Install-Module Microsoft365DSC -Force -Scope AllUsers
Update-M365DSCDependencies
Export-M365DSCConfiguration

**Comment by andikrueger** [comment]
Any chance you could you share the full message of MS Defender? '

There was an issue in the past about MSCloudLogin causing some false positives: #1830

**Comment by kirilvalev** [comment]
Sure, the message in Defender is:

Detected: Behavior:Win32/Trikombu.B
Status: Removed
A threat or app was removed from this device.

Date: 15.03.2023 18:58
Details: This program is dangerous and executes commands from an attacker.

Affected items:

behavior: process: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe, pid:36880:107421487672006
process: pid:36880,ProcessStart:133233759046268373

**Comment by kirilvalev** [comment]
Tried it again, this time Defender quarantined something. It happens after executing Export-M365DSCConfiguration. I am asked for credentials, then I clicked on cancel, because I need an interactive prompt. Also another alert was triggered by Microsoft 365 Defender: Suspicious sequence of exploration activities.

![image](https://user-images.githubusercontent.com/44725404/225692154-9298f638-d349-4c16-a7bc-beb2109811cc.png)


![image](https://user-images.githubusercontent.com/44725404/225691369-d22bee14-d55e-4bea-b229-460c262c0a4a.png)

**Comment by NikCharlebois** [comment]
Unfortunately there isn't much we can do on our end since this seems to be specific to that environment. We will continue to monitor to see if others report the same issue, but this is a first in 5 years. My guts feeling tell me that another suspicious module might be at play or that the tool is reporting a false positive somehow.

**Comment by jeffreycloudlife** [comment]
I am running into this issue also. Currently trying to figure out what is triggering this issue, as it sometimes (not always) interferes with my execution of policies.
