### ISSUE TITLE
M365DSCReport.psm1 Cannot index into a null array.  

### ISSUE THREAD

**Issue by icpw** [microsoft/Microsoft365DSC#3016]
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.315.1\Modules\M365DSCReport.psm1
**Line 1124**  $CIMType = $drift.ValueInSource[0].CimInstance (error : Cannot index into a null array.)

Exists at least in 1.23.308.1 and 1.23.315.1

**New-M365DSCDeltaReport** took 45minutes, at least, to load up **each** tenant configuration (i7, 32Gb Dell XPS17) and then just crashed.  I modified the code by moving the assignment inside the if statement and adjusted the if condition to also check for null, and the code ran successfully.  Someone more familiar to the code would be able to ensure the code fix was appropriate.

**Comment by NikCharlebois** [comment]
Any chances you could share the redacted configurations used so that we can try and replicate on our end? Thanks

**Comment by icpw** [comment]
[source_tenant.ps1.txt](https://github.com/microsoft/Microsoft365DSC/files/10999037/source_tenant.ps1.txt)
[destination_tenant.ps1.txt](https://github.com/microsoft/Microsoft365DSC/files/10999039/destination_tenant.ps1.txt)
I have removed a lot of sections from the files that made reference to the domain being used, even though the domains are mostly for testing purposes.  I did not want to reduce the data further in case it removed the problem.

Please note: The data is not fit for use in any real tenant.

I have tested these files and the error occurs straight after both configurations have loaded. You just have to wait a while for that to happen.


These configuration files are combined from many individual configuration files. I extract one component at a time in a loop until all have been extracted.  I want them to be done individually so that I can check each component and check data (in progress) and errors (mostly none).  I combine all of them to produce a full delta report.  I have done a visual scan of the configuration file contents and can see no obvious issues with the format.  No errors are produced during loading them.

This is the code I used to run the test.
$sourcefile="c:\abc\source_tenant.ps1"
$destination="c:\abc\destination_tenant.ps1"
$OutputPath="c:\abc\delta.html"
New-M365DSCDeltaReport -Source $sourcefile -Destination $destination -OutputPath $OutputPath

**Comment by NikCharlebois** [comment]
Will be pushing a change in the logic which based on preliminary benchmarks, speeds up the process 279 times ;) The issue was that for every component in the config we were calling into the Get-DSCResource cmdlet which is very slow in nature. Instead we now retrieve all the DSC resources for the module once, and then reuse it for each resource. PR coming shortly
