### ISSUE TITLE
O365Group Members property problem

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Microsoft365DSC#302]
#### Details of the scenario you tried and the problem that is occurring
We noticed that exporting the configuration on some of our tenants generates invalid powershell. 
```powershell
  O365Group 45724fce-76c3-4c8d-b327-d599fce5774a
        {
            Description          = "";
            DisplayName          = "Cash";
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            MailNickName         = "ash";
            ManagedBy            = @("jsmith@syskitd.onmicrosoft.com","msummers@syskitd.onmicrosoft.com","stockham.stenseth@syskitd.onmicrosoft.com","diestel.schirpke@syskitd.onmicrosoft.com","suell.shadrick@syskitd.onmicrosoft.com");
            Members              = ;
        }
```

The problem is in the members field.

After some analysis we came to the conclusion that the problem occurs because the group has another group in the members collection.
When calling Get-TargetResource for the group we get the following:
```powershell
Name                           Value
----                           -----
ManagedBy                      {jsmith@syskitd.onmicrosoft.com, msummers@syskitd.onmicrosoft.com, stockham.stenseth@...
DisplayName                    Cash
Ensure                         Present
Description
MailNickName                   ash
GlobalAdminAccount             System.Management.Automation.PSCredential
Members                        {$null, annebelle.cala_outlook.com#EXT#@syskitd.onmicrosoft.com, AdeleV_M365x887491.O...
```

The $null in the members collection then kills everything. $null is here because the object in the actual members of the group is a group and does not have the UPN property.

```
DeletionTimestamp            :
ObjectId                     : 32338f51-d3f2-48bb-9197-f70c6291985c
ObjectType                   : Group
Description                  :
DirSyncEnabled               :
DisplayName                  : Accrued Expenses
LastDirSyncTime              :
Mail                         :
MailEnabled                  : False
MailNickName                 : ccruedxpenses
OnPremisesSecurityIdentifier :
ProvisioningErrors           : {}
ProxyAddresses               : {}
SecurityEnabled              : True
```

#### Verbose logs showing the problem
```
VERBOSE: Setting configuration of Office 365 Group Cash
VERBOSE: Found Existing Instance of Group {Cash}
VERBOSE: Found Members for Group {Cash}
VERBOSE: Found Owners for Group {Cash}
VERBOSE: Retrieved the following instance of the Group:
VERBOSE: ManagedBy = jsmith@syskitd.onmicrosoft.com msummers@syskitd.onmicrosoft.com
stockham.stenseth@syskitd.onmicrosoft.com diestel.schirpke@syskitd.onmicrosoft.com
suell.shadrick@syskitd.onmicrosoft.com
VERBOSE: DisplayName = Cash
VERBOSE: Ensure = Present
VERBOSE: Description =
VERBOSE: MailNickName = ash
VERBOSE: GlobalAdminAccount = System.Management.Automation.PSCredential
VERBOSE: Members =  annebelle.cala_outlook.com#EXT#@syskitd.onmicrosoft.com
AdeleV_M365x887491.OnMicrosoft.com#EXT#@syskitd.onmicrosoft.com
AldoM_M365x887491.onmicrosoft.com#EXT#@syskitd.onmicrosoft.com albares.latzke@syskitd.onmicrosoft.com
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\ReverseDSC\2.0.0.0\ReverseDSC.Core.psm1:276 char:17
+ ...         if ($array.Length -gt 0 -and ($array[0].GetType().Name -eq "S ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

#### Suggested solution to the issue
Add support for groups as members of groups. Or, filter out the groups if only users are to be supported. In any case, i believe that some changes to the setter logic will also be required.
 
#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by vinkobedek** [comment]
@NikCharlebois I took a look inside Azure Active Directory on this tenant. 
The group in question is not an Office group but a Security Group. Adding other (security) groups is supported.

**Comment by NikCharlebois** [comment]
Got it. Will be fixed with a PR shortly.

**Comment by NikCharlebois** [comment]
@vinkobedek do you know if that group was added as a member via the Azure Portal, O365 or PoSh? Trying via the Admin portal to add a security group simply adds the users within it as individual permissions.Thanks

**Comment by vinkobedek** [comment]
@NikCharlebois groups as group members can be added through the AAD portal. I think that PowerShell should also work.
1. go to https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/GroupsManagementMenuBlade/AllGroups
2. there is a New Group button in the menu
3. Make sure to select Security as the Group Type
4. select another security group as a member of this one, or if there are no existing ones, create another and add afterwards

![image](https://user-images.githubusercontent.com/13213802/71074680-fea65480-2182-11ea-8bf9-7d0045ef77dd.png)

**Comment by NikCharlebois** [comment]
@vinkobedek I am still having a hard time replicating your scenario. The O365Group resource only deals with Unified Groups, not Security groups. Therefore I am unclear on how your extract would even list a security group in the first place. Can you confirm  that group Cash in your case is a Security Group?

**Comment by vinkobedek** [comment]
Sorry for the late reply, @NikCharlebois. Yes, Cash is a security group
![image](https://user-images.githubusercontent.com/13213802/72347565-c5f19080-36d8-11ea-96b2-155e5ab292a4.png).
While the intention of the resource may be to pick up only Office groups, it seems that the following snipper from ReverseDSC also picks up the Cash group
```powershell
Get-AzureADGroup | Where-Object -FilterScript {
            $_.MailNickName -ne "00000000-0000-0000-0000-000000000000"
        }
```
so I guess that this is actually where the problem lies, the group has a mailnickname set:
![image](https://user-images.githubusercontent.com/13213802/72347871-62b42e00-36d9-11ea-867e-eadf9244be44.png)

**Comment by andikrueger** [comment]
@vinkobedek Is this still an issue with the latest M365DSC version?
