### ISSUE TITLE
Exporting AADRoleSettings with cert thumbprint and appid does not include cert and appid 

### ISSUE THREAD

**Issue by martincaddick** [microsoft/Microsoft365DSC#3048]
ModuleVersion '1.23.315.1'

Exporting AADRoleSettings using Appd, TenantId and CertThumbprint exports all information _except_ the certificate thumbprint and the AppID.

Manually adding the AppId and CertThumbprint to each of the roles that have been exported then allows correct import.

            ApplicationId         = $ConfigurationData.NonNodeData.ApplicationId;
            CertificateThumbprint = $ConfigurationData.NonNodeData.CertificateThumbprint;

**Comment by ykuijs** [comment]
Hi @martincaddick, thanks for letting us know. I will fix this issue.
