### ISSUE TITLE
 No plan found for identifier xxxx-xxxx. Creating pipeline from DSC whitepaper

### ISSUE THREAD

**Issue by digitalpapercut** [microsoft/Microsoft365DSC#3055]
I have been working through the Managing Microsoft 365 in true DevOps style with Microsoft365DSC and Azure DevOps whitepaper, and I'm to the point where you need to create the pipeline. When I do this, I get the error that no plan was found for the identifier for that pipeline (or so i believe that's what that GUID number is for). Every step prior to this one has gone just fine, so I'm not sure where the errors are coming from. 

I am also receiving an additional error at the bottom of the screen: 

There was a resource authorization issue: "The pipeline is not valid. Job CompileConfiguration: Step AzurePowerShell input ConnectedServiceNameARM references service connection KeyVaultConnection which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

When I click on authorize resources, it doesn't change anything that I can tell, and the pipeline still fails. 

Additionally, I don't seem to have any logs available to review for the issue either. 

Can someone shed some light on what might be the issue? Am I missing a specific type of subscription plan?

**Comment by jbacic2** [comment]
Was there a solution to this? I'm getting the same behavior

**Comment by EricAvelar** [comment]
Can you guys please post solution i am getting the same behavior.
