### ISSUE TITLE
IntuneDeviceCompliancePolicyAndroidWorkProfile - problems with Get-MgDeviceManagementDeviceCompliancePolicyAssignment and Policy Sets

### ISSUE THREAD

**Issue by menswearUK** [microsoft/Microsoft365DSC#3058]
#### Details of the scenario you tried and the problem that is occurring
This configuration generates errors or incorrect configurations when handling docs where the assignments value includes a group linked via a policy set.  These assignments are present in an exported config but are not labelled as such and do not import or compare correctly when applying the configuration.

If There is a policy set which uses the same access role groups as are already assigned in the configuration profile (this might not be a desired configuration but it is possible to do this) an error is generated when applying the configuration.

If the groups specified are different no error is generated when creating a duplicate policy but the script does not identify that the group is assigned via a policy set and applies it direct to the policy being configured.
Manually omitting the group from the configuration document will lead to a drift detection in an existing policy as the count of groups assignments will differ from the get-TargetResource object.

The error seems to stem from the handling of Get-MgDeviceManagementDeviceCompliancePolicyAssignment - Other configs display issues when handling these values too.  IntuneDeviceCompliancePolicyiOS does not produce any errors when run, but when using a config with a duplication of the same group it fails to configure any groups on the policy.  When a non duplicated PolicySet group is on the config doc it is applied direct to the policy.

#### Verbose logs showing the problem
I've limited this section to just the errors as a lot of the detail isn't really useful.

error when 2 identical groups are present:
Cannot process argument transformation on parameter 'Source'. Cannot convert the "System.Object[]" value of type
"System.Object[]" to type "System.Collections.Hashtable".
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Compare-M365DSCComplexObject
    + PSComputerName        : localhost

Cannot process argument transformation on parameter 'Source'. Cannot convert the "System.Object[]" value of type
"System.Object[]" to type "System.Collections.Hashtable".
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Compare-M365DSCComplexObject
    + PSComputerName        : localhost

#### Suggested solution to the issue

The easiest way would probably be to simply ignore anything which is part of a policy set, the results returned from Get-MgDeviceManagementDeviceCompliancePolicyAssignment have a Source value which would allow us to do this quite easily.  I don't believe there is currently a configuration for Policy Sets in the module but If/When this is created then it could take care of all memberships.  The downside of this is it will mean there will be a difference between the policy being exported and the one potentially applied elsewhere or recreated.

Here is an example of the objects returned by get-MgDeviceManagementDeviceCompliancePolicyAssignment - It's the same group in the policy set in this example, to match the example config I've provided :

Id                   : 0367529a-6fa5-4f18-b158-75df4ad1dc93_31db4dab-ce8c-40a0-9c89-54dc71dfceda
Source               : direct
SourceId             : 0367529a-6fa5-4f18-b158-75df4ad1dc93
Target               : Microsoft.Graph.PowerShell.Models.MicrosoftGraphDeviceAndAppManagementAssignmentTarget1
AdditionalProperties : {}

Id                   : 0367529a-6fa5-4f18-b158-75df4ad1dc93_31db4dab-ce8c-40a0-9c89-54dc71dfceda_23589c18-a624-4435-9143-0554f5fc3eca
Source               : policySets
SourceId             : 23589c18-a624-4435-9143-0554f5fc3eca
Target               : Microsoft.Graph.PowerShell.Models.MicrosoftGraphDeviceAndAppManagementAssignmentTarget1
AdditionalProperties : {}

There are a number of configurations using Get-MgDeviceManagementDeviceCompliancePolicyAssignment and the output is processed internally as part of the configuration - leading to slightly different behaviour.  I think it could be appropriate to have a function in M365DSCUtil.psm1 which all the configurations would use.  That would lead to consistency of behaviour.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# Generated with Microsoft365DSC version 1.23.308.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
)

Configuration M365TenantConfig
{
    param (
    )

    $OrganizationName = $ConfigurationData.NonNodeData.OrganizationName

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.23.308.1'

    Node localhost
    {
        IntuneDeviceCompliancePolicyAndroidWorkProfile faa7db7a-da2e-4190-bc7f-54b4b7f9be5b
        {
            AdvancedThreatProtectionRequiredSecurityLevel      = "unavailable";
            ApplicationId                                      = $ConfigurationData.NonNodeData.ApplicationId;
            ApplicationSecret                                  = New-Object System.Management.Automation.PSCredential ('ApplicationSecret', (ConvertTo-SecureString $ConfigurationData.NonNodeData.ApplicationSecret -AsPlainText -Force));
            Assignments                                        = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    groupId = '31db4dab-ce8c-40a0-9c89-54dc71dfceda'
            }
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    groupId = '31db4dab-ce8c-40a0-9c89-54dc71dfceda'
            });
            Description                                        = "test android work profile";
            DeviceThreatProtectionEnabled                      = $False;
            DeviceThreatProtectionRequiredSecurityLevel        = "unavailable";
            DisplayName                                        = "test android work profile";
            Ensure                                             = "Present";
            PasswordRequired                                   = $False;
            PasswordRequiredType                               = "deviceDefault";
            SecurityBlockJailbrokenDevices                     = $False;
            SecurityDisableUsbDebugging                        = $False;
            SecurityPreventInstallAppsFromUnknownSources       = $False;
            SecurityRequireCompanyPortalAppIntegrity           = $False;
            SecurityRequiredAndroidSafetyNetEvaluationType     = "basic";
            SecurityRequireGooglePlayServices                  = $False;
            SecurityRequireSafetyNetAttestationBasicIntegrity  = $False;
            SecurityRequireSafetyNetAttestationCertifiedDevice = $False;
            SecurityRequireUpToDateSecurityProviders           = $False;
            SecurityRequireVerifyApps                          = $False;
            StorageRequireEncryption                           = $False;
            TenantId                                           = $ConfigurationData.NonNodeData.TenantId;
        }
    }
}

M365TenantConfig -ConfigurationData .\ConfigurationData.psd1

```

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

**Comment by William-Francillette** [comment]
The reason it fails to update is because a group should be unique in an assignment set.
Not sure if it's worth updating all resources with the assignments parameter as this is a error in the config file.
An export will never return a duplicate group. I see it more like an incorrect query rather than a resource issue
@ykuijs @andikrueger what do you think?

**Comment by NikCharlebois** [comment]
Agreed. We need to evaluate the impact of making a change across all resource which could have unwanted effect vs fixing it at the config level. @menswearUK what is the business rational to have the same group listed twice? Thanks

**Comment by menswearUK** [comment]
@NikCharlebois @William-Francillette 
There's no particular reason for having the group listed twice, The config came from a test tenant so it probably got set up like this as a test where the same group was applied to both the policy and the policySet.  It probably isn't a particularly desirable way to configure things but it isn't prevented, I'm pretty sure it would have been set up this way via the web interface.

The config I'm testing was from a file I'd exported from the same tenant - The configuration was pulling back the same group from the policy and the PolicySet and interpreting them as both belonging to the policy itself, and then adding the duplicate entries in the file.  I was using the dev version of the module but I've not had a chance to test the most recent updates - I'll check tomorrow and see if it's still doing the same thing.

**Comment by menswearUK** [comment]
I've pulled an export today using the latest dev code and the duplicate entries under assignments are still present and still generates the same error when I use if for test-dscconfiguration

**Comment by NikCharlebois** [comment]
We have added a new -Validate switch to the Export-M365DSCConfiguration cmdlet which will analyze the exported configuration and tell you about potential conflicts. It is not ideal, but it will help in this situation. To be honest, there isn't much more we can due from a tool's perspective to prevent this.
