### ISSUE TITLE
Unable to fetch output for EXOAddressList

### ISSUE THREAD

**Issue by ashrafuddinsyed** [microsoft/Microsoft365DSC#3065]
Hi Team,

It seems like EXOAddressList is broken as it is not able to fetch the output from the tenant.

However, when I use a similar command on exchange online connected powershell i.e get-addresslist, it provides me with an output.

Kindly let me know what information do I need to provide in order to fix this issue.

Thanks.

**Comment by NikCharlebois** [comment]
What seems to be the issue? Any error message? We are not able to replicate. Thanks

**Comment by ashrafuddinsyed** [comment]
Hi Nik,

I've ran the EXOAddressList command and found it is able to provide the output now.

Kindly go ahead and close this case.

Thanks.

Regards,
[Atos logo]
Syed Ashrafuddin
Lead Consultant - Architect - PRA DWP ENG COE IN-2
M: +91 9885135182
atos.net<https://atos.net/>

Upcoming Vacation : April 7th - 23rd
