### ISSUE TITLE
AADGroup: Add Exchange Online Microsoft 365 Group parameters e.g. UnifiedGroupWelcomeMessageEnabled

### ISSUE THREAD

**Issue by Borgquite** [microsoft/Microsoft365DSC#3089]
#### Details of the scenario you tried and the problem that is occurring

AADGroup is the resource that allows creation of Microsoft 365 Groups (using GroupType = 'Unified')

For these group types there are a lot of of Exchange-related attributes that an administrator would need to get/set/test.

https://learn.microsoft.com/en-us/powershell/module/exchange/set-unifiedgroup?view=exchange-ps

It would be especially helpful to have AutoSubscribeNewMembers, HiddenFromAddressListsEnabled, HiddenFromExchangeClientsEnabled, PrimarySmtpAddress and UnifiedGroupWelcomeMessageEnabled.

- AcceptMessagesOnlyFromSendersOrMembers
- AlwaysSubscribeMembersToCalendarEvents
- AuditLogAgeLimit
- AutoSubscribeNewMembers
- CalendarMemberReadOnly
- Classification
- ConnectorsEnabled
- CustomAttribute1 **through** CustomAttribute15
- DataEncryptionPolicy
- EmailAddresses
- ExtensionCustomAttribute1 **through** ExtensionCustomAttribute5
- GrantSendOnBehalfTo
- HiddenFromAddressListsEnabled
- HiddenFromExchangeClientsEnabled
- InformationBarrierMode
- IsMemberAllowedToEditContent
- Language
- MailboxRegion
- MailTip
- MailTipTranslations
- MaxReceiveSize
- MaxSendSize
- ModeratedBy
- ModerationEnabled
- Notes
- PrimarySmtpAddress
- RejectMessagesFromSendersOrMembers
- RequireSenderAuthenticationEnabled
- SensitivityLabelId
- SubscriptionEnabled
- UnifiedGroupWelcomeMessageEnabled

#### Verbose logs showing the problem

N/A

#### Suggested solution to the issue

Implement the ability to get, set and test these attributes when groups are created/updated withg GroupType = 'Unified'

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration Example
{
    param
    (
        [Parameter(Mandatory = $true)]
        [PSCredential]
        $credsAdmin
    )
    Import-DscResource -ModuleName Microsoft365DSC

    node localhost
    {
        AADGroup 'MyGroups'
        {
            DisplayName                       = "DSCGroup"
            Description                       = "Microsoft DSC Group"
            SecurityEnabled                   = $True
            MailEnabled                       = $True
            GroupTypes                        = @("Unified")
            MailNickname                      = "M365DSC"
            Visibility                        = "Private"
            UnifiedGroupWelcomeMessageEnabled = $False
            Ensure                            = "Present"
            Credential                        = $credsGlobalAdmin
        }
    }
}
```

#### The operating system the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.23.322.1

**Comment by Borgquite** [comment]
Similar to #2761

**Comment by NikCharlebois** [comment]
Would it make sense to create a separate resource named EXOGroupSettings for this instead? AADGroup is leveraging the Get-MgGroup cmdlet under the cover, which doesn't support these properties.

**Comment by Borgquite** [comment]
If that's easier to implement. It will make configurations larger but I can see why 'under the covers' this makes more sense.

**Comment by NikCharlebois** [comment]
Small gift before the week-end:
https://github.com/microsoft/Microsoft365DSC/pull/3112 
:)
