### ISSUE TITLE
DSC SCLabelPolicy export error

### ISSUE THREAD

**Issue by Thz4UQgy** [microsoft/Microsoft365DSC#3104]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# At the end in pictures


```
#### Version of the DSC module that was used ('dev' if using current dev branch)
Newest version from 03.28.23

#### Pictures
![ErrorInPS](https://user-images.githubusercontent.com/103027860/229065687-c35a7e92-3749-4164-954b-be497b88af74.PNG)
![ErrorlogOutput](https://user-images.githubusercontent.com/103027860/229065765-39e2fdf8-f1f0-47d7-b38d-3384266ab161.PNG)

**Comment by NikCharlebois** [comment]
Can you provide additional details around the policy that is throwing the error? Screenshots that would allow us to recreate in our environment to help troubleshooting the issue would be very useful. Thanks

**Comment by Thz4UQgy** [comment]
Hi Nik, sure. 
![OverviewPolicyMPIP](https://user-images.githubusercontent.com/103027860/229442052-2abb47ae-e0a5-4a3a-a3eb-f5f52036ee5d.PNG)
![SettingsPolicyMPIP1](https://user-images.githubusercontent.com/103027860/229442059-22e15de1-4c9e-4520-afa5-0fc99493517d.PNG)
![SettingsPolicyMPIP2](https://user-images.githubusercontent.com/103027860/229442062-965996db-ec36-4399-9ad1-2d8d802faa16.PNG)
![SettingsPolicyMPIP3](https://user-images.githubusercontent.com/103027860/229442063-595a1af9-70aa-44cc-b941-22476cb8af51.PNG)
![SettingsPolicyMPIP4](https://user-images.githubusercontent.com/103027860/229442066-02708691-5ed5-46c1-8083-de564f192a05.PNG)
![SettingsPolicyMPIP5](https://user-images.githubusercontent.com/103027860/229442069-5f4db6da-a154-4711-a5b2-ae5054f3879e.PNG)
![SettingsPolicyMPIP6](https://user-images.githubusercontent.com/103027860/229442070-37a4d0a9-ffc3-479c-a8e3-cf1ab6cecca9.PNG)

**Comment by NikCharlebois** [comment]
Thanks for the screenshots. We are not able to replicate on our end.
![image](https://user-images.githubusercontent.com/2547149/229787156-51b847c5-3dd2-4c6f-9f91-5284ec7aada4.png)
Could you please try the following and see if you get the same error? This is the internal logic of the resource.

```powershell
$creds = Get-Credential
Connect-IPPSSession -Credential $creds
$policy = Get-LabelPolicy -Identity UMobi_all
$settings = $policy.Settings
foreach ($setting in $settings)
{
    $settingString = $setting.Replace('[', '').Replace(']', '')
    $settingKey = $settingString.Split(',')[0]
    $startPos = $settingString.IndexOf(',', 0) + 1
    $valueString = $settingString.Substring($startPos, $settingString.Length - $startPos).Trim()
    if ($valueString -like '*,*')
    {
        $values = $valueString -split ','
    }
    else
    {
        $values = $valueString
    }
    if ($settingKey -like '*defaultlabel*')
    {
        $label = Get-Label -Identity $values
        Write-Host $label.DisplayName
    }
}
```

**Comment by Thz4UQgy** [comment]
Hi Nik,

Same error:

PS C:\WINDOWS\system32> Connect-IPPSSession -Credential $creds
$policy = Get-LabelPolicy -Identity UMobi_all
$settings = $policy.Settings
foreach ($setting in $settings)
{
    $settingString = $setting.Replace('[', '').Replace(']', '')
    $settingKey = $settingString.Split(',')[0]
    $startPos = $settingString.IndexOf(',', 0) + 1
    $valueString = $settingString.Substring($startPos, $settingString.Length - $startPos).Trim()
    if ($valueString -like '*,*')
    {
        $values = $valueString -split ','
    }
    else
    {
        $values = $valueString
    }
    if ($settingKey -like '*defaultlabel*')
    {
        $label = Get-Label -Identity $values
        Write-Host $label.DisplayName
    }
}
The operation couldn't be performed because object 'None' couldn't be found on 'FfoConfigurationSession'.
    + CategoryInfo          : NotSpecified: (:) [Get-Label], ManagementObjectNotFoundException
    + FullyQualifiedErrorId : [Server=DM6NAM11WS032,RequestId=4c2e6269-fe1e-472a-9a9c-a1b6dc2b5da5,TimeStamp=05.04.2023 09:03:44] [FailureCategory=Cmdlet-ManagementObje 
   ctNotFoundException] EB231B2F,Microsoft.Office.CompliancePolicy.Tasks.GetLabel
    + PSComputerName        : nam11b.ps.compliance.protection.outlook.com

**Comment by andikrueger** [comment]
Could you please extend the output of the script a bit:

```powershell
Connect-IPPSSession -Credential $creds
$policy = Get-LabelPolicy -Identity UMobi_all
$settings = $policy.Settings
foreach ($setting in $settings)
{
try{
    $settingString = $setting.Replace('[', '').Replace(']', '')
    $settingKey = $settingString.Split(',')[0]
    $startPos = $settingString.IndexOf(',', 0) + 1
    $valueString = $settingString.Substring($startPos, $settingString.Length - $startPos).Trim()
Write-Host "valueString: $($valuestring)"
    if ($valueString -like '*,*')
    {
        $values = $valueString -split ','
    }
    else
    {
        $values = $valueString
    }

    if ($settingKey -like '*defaultlabel*')
    {
        Write-Host "Getting Label for value: $($values)"
        $label = Get-Label -Identity $values
        Write-Host $label.DisplayName
    }
}
catch
{
Write-Host $_
}
}

```

**Comment by Thz4UQgy** [comment]
Hi Andi,

Sure:

```Powershell

PS C:\WINDOWS\system32> $policy = Get-LabelPolicy -Identity Umobi_all
$settings = $policy.Settings
foreach ($setting in $settings)
{
try{
    $settingString = $setting.Replace('[', '').Replace(']', '')
    $settingKey = $settingString.Split(',')[0]
    $startPos = $settingString.IndexOf(',', 0) + 1
    $valueString = $settingString.Substring($startPos, $settingString.Length - $startPos).Trim()
Write-Host "valueString: $($valuestring)"
    if ($valueString -like '*,*')
    {
        $values = $valueString -split ','
    }
    else
    {
        $values = $valueString
    }

    if ($settingKey -like '*defaultlabel*')
    {
        Write-Host "Getting Label for value: $($values)"
        $label = Get-Label -Identity $values
        Write-Host $label.DisplayName
    }
}
catch
{
Write-Host $_
}
}
valueString: false
valueString: true
valueString: true
valueString: false
valueString: false
valueString: false
valueString: false
valueString: true
valueString: None
Getting Label for value: None
The operation couldn't be performed because object 'None' couldn't be found on 'FfoConfigurationSession'.
    + CategoryInfo          : NotSpecified: (:) [Get-Label], ManagementObjectNotFoundException
    + FullyQualifiedErrorId : [Server=DM6NAM11WS032,RequestId=9790444a-4548-454c-a8f3-eabe66857a93,TimeStamp=05.04.2023 09:23:04] [FailureCategory=Cmdlet-ManagementObje 
   ctNotFoundException] EB231B2F,Microsoft.Office.CompliancePolicy.Tasks.GetLabel
    + PSComputerName        : nam11b.ps.compliance.protection.outlook.com
 

valueString: false
```

**Comment by andikrueger** [comment]
Why is there a 'None'. Would you mind outputting the setting as well and the policy?

**Comment by Thz4UQgy** [comment]
No problem Andi. Which command should I do that you can get all your information that you need?

**Comment by Thz4UQgy** [comment]
I think I got the error. The advanced label policy setting for "outlookdefaultlabel" is set to none not false or true. I will check that and inform you.

**Comment by Thz4UQgy** [comment]
Ok for the advanced settings is not allowed to set it to false or true.

```Powershell

PS C:\Company\Scripts\M365DSC> Set-LabelPolicy -Identity Umobi_all -AdvancedSettings @{outlookdefaultlabel="false"}

WARNING: Encountered exception: Microsoft.Exchange.Management.UnifiedPolicy.ErrorResolvingMipLabelIdException: Error resolving MIP label ID 'false' to a Guid.
   at Microsoft.Office.CompliancePolicy.Tasks.MipLabelContentTypeUtils.ValidateDefaultLabelContentType(String defaultLabelId, MipLabelContentType expectedContentType, Lis
t`1 labels)
   at Microsoft.Office.CompliancePolicy.Tasks.MipLabelUtilities.ValidateDefaultLabel(List`1 labelStorages, List`1 settings, OrganizationId orgId, UnifiedPolicyCmdletLogge
r cmdletLogger, MipLabelsSnapshot tenantSnapshot)
   at Microsoft.Office.CompliancePolicy.Tasks.SetLabelPolicy.InternalValidate()
Error resolving MIP label ID 'false' to a Guid.
    + CategoryInfo          : NotSpecified: (:) [Set-LabelPolicy], ErrorResolvingMipLabelIdException
    + FullyQualifiedErrorId : [Server=DM6NAM11WS032,RequestId=676c3478-db03-4b1d-bdfa-117e6cf1caab,TimeStamp=05.04.2023 10:37:24] [FailureCategory=Cmdlet-ErrorResolving 
   MipLabelIdException] 3F4C9378,Microsoft.Office.CompliancePolicy.Tasks.SetLabelPolicy
    + PSComputerName        : nam11b.ps.compliance.protection.outlook.com

```

**Comment by andikrueger** [comment]
How does the advanced label differ? We need to add an additional condition to this statement:

 if ($settingKey -like '*defaultlabel*')

**Comment by Thz4UQgy** [comment]
I checked the advanced setting and in the UI it is possible to set "None" for this setting.

**Comment by andikrueger** [comment]
Could you try to set it to $null

> Specify this parameter with the identity (name or GUID) of the policy, with key/value pairs in a [hash table](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_hash_tables). To remove an advanced setting, use the same AdvancedSettings parameter syntax, but specify a null string value.
https://learn.microsoft.com/en-us/powershell/module/exchange/set-labelpolicy?view=exchange-ps#-advancedsettings

**Comment by Thz4UQgy** [comment]
Yes like this: 

OutlookDefaultLabel: Outlook apps that support this setting apply a default label, or no label. Example: Set-LabelPolicy -Identity Global -AdvancedSettings @{OutlookDefaultLabel="None"}. For more information about this configuration choice, see [Outlook-specific options for default label and mandatory labeling](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps#outlook-specific-options-for-default-label-and-mandatory-labeling).

Output:

```Powershell

PS C:\Company\Scripts\M365DSC> (Get-Labelpolicy -Identity Umobi_all).settings
[powerbimandatory, false]
[requiredowngradejustification, true]
[mandatory, true]
[disablemandatoryinoutlook, false]
[enablecustompermissions, false]
[hidebarbydefault, false]
[siteandgroupmandatory, false]
[enablepdfv2protection, true]
[teamworkmandatory, false]
[outlookdefaultlabel, None]

```

**Comment by andikrueger** [comment]
I don’t get it. I’ve read this passage as well. Either the documentation is wrong or the code 😬

**Comment by Thz4UQgy** [comment]
I thing the DSC Module can't handle this setting because "None" is set. You can test ist by your own. Now is my second policy also not working as well ;)

**Comment by Thz4UQgy** [comment]
![Outlookdefault label](https://user-images.githubusercontent.com/103027860/230061985-f34fc3b4-aba9-4db8-9a73-04b572ece9d4.PNG)

**Comment by andikrueger** [comment]
I think, we are closer to the solution. At the moment, in M365DSC there is an issue with NONE values. On the other hand, you were not able to run this command with success:

```
Set-LabelPolicy -Identity Umobi_all -AdvancedSettings @{outlookdefaultlabel="false"}
```

Would be good to know, if we can set it like this:

```
Set-LabelPolicy -Identity Umobi_all -AdvancedSettings @{outlookdefaultlabel="null"}
```

or

```
Set-LabelPolicy -Identity Umobi_all -AdvancedSettings @{outlookdefaultlabel=$null}
```

Any chance you could run the both commands above? I don't a have a test environment for labels ATM.

**Comment by Thz4UQgy** [comment]
Sure:

```Powershell

PS C:\Company\Scripts\M365DSC> Set-LabelPolicy -Identity Umobi_all -AdvancedSettings @{outlookdefaultlabel="null"}
Set-LabelPolicy : The term 'Set-LabelPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Set-LabelPolicy -Identity Umobi_all -AdvancedSettings @{outlookdefaul ...
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-LabelPolicy:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

PS C:\Company\Scripts\M365DSC> Set-LabelPolicy -Identity Umobi_all -AdvancedSettings @{outlookdefaultlabel=$null}
Set-LabelPolicy : The term 'Set-LabelPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Set-LabelPolicy -Identity Umobi_all -AdvancedSettings @{outlookdefaul ...
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-LabelPolicy:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

PS C:\Company\Scripts\M365DSC> 

```

Not able

**Comment by Thz4UQgy** [comment]
First command not possible second command no error occurs.

```Powershell

PS C:\Company\Scripts\MIP> Set-LabelPolicy -Identity Umobi_all -AdvancedSettings @{outlookdefaultlabel="null"}
WARNING: Encountered exception: Microsoft.Exchange.Management.UnifiedPolicy.ErrorResolvingMipLabelIdException: Error resolving MIP label ID 'null' to a Guid.
   at Microsoft.Office.CompliancePolicy.Tasks.MipLabelContentTypeUtils.ValidateDefaultLabelContentType(String defaultLabelId, MipLabelContentType expectedContentType, Lis
t`1 labels)
   at Microsoft.Office.CompliancePolicy.Tasks.MipLabelUtilities.ValidateDefaultLabel(List`1 labelStorages, List`1 settings, OrganizationId orgId, UnifiedPolicyCmdletLogge
r cmdletLogger, MipLabelsSnapshot tenantSnapshot)
   at Microsoft.Office.CompliancePolicy.Tasks.SetLabelPolicy.InternalValidate()
Error resolving MIP label ID 'null' to a Guid.
    + CategoryInfo          : NotSpecified: (:) [Set-LabelPolicy], ErrorResolvingMipLabelIdException
    + FullyQualifiedErrorId : [Server=DM6NAM11WS025,RequestId=82d90740-7287-477a-9ee2-94b3d0f609ac,TimeStamp=05.04.2023 11:32:13] [FailureCategory=Cmdlet-ErrorResolving 
   MipLabelIdException] C1898350,Microsoft.Office.CompliancePolicy.Tasks.SetLabelPolicy
    + PSComputerName        : nam11b.ps.compliance.protection.outlook.com
 

PS C:\Company\Scripts\MIP> Set-LabelPolicy -Identity Umobi_all -AdvancedSettings @{outlookdefaultlabel=$null}

PS C:\Company\Scripts\MIP> 

```

**Comment by Thz4UQgy** [comment]
But now the setting in the UI is changed to "same as document" that would be false.

**Comment by andikrueger** [comment]
I was about to celebrate...

What do we know so far:

- Setting the label to 'None' with this command `Set-LabelPolicy -Identity Umobi_all -AdvancedSettings @{outlookdefaultlabel=$null}` results in "same as document" in the UI
- We need to treat values of "None" differently in M365DSC. The current implementation needs to check, if the value is none. If yes, we cannot query for this label.

**Comment by Thz4UQgy** [comment]
Can I confirm ;)

**Comment by Thz4UQgy** [comment]
So what is going on next?

**Comment by andikrueger** [comment]
We need to find a fix for this issue. Right now, there is the challenge on how to set the object to be none.

**Comment by ricmestre** [comment]
@andikrueger Hi, setting outlookdefaultlabel to None works, in fact this is documented in https://learn.microsoft.com/en-us/powershell/module/exchange/set-labelpolicy?view=exchange-ps :

OutlookDefaultLabel: Outlook apps that support this setting apply a default label, or no label. Example: Set-LabelPolicy -Identity Global -AdvancedSettings @{OutlookDefaultLabel="None"}. For more information about this configuration choice, see [Outlook-specific options for default label and mandatory labeling.](https://learn.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps#outlook-specific-options-for-default-label-and-mandatory-labeling)

```powershell
C:\> $Policy = Get-LabelPolicy

C:\> $Policy.Settings
[mandatory, false]
[powerbimandatory, false]
[outlookdefaultlabel, defa4170-0d19-0005-0004-bc88714345d2] # Here is set to "All Employees (unrestricted)"
[requiredowngradejustification, true]
[defaultlabelid, defa4170-0d19-0005-0004-bc88714345d2]
[disablemandatoryinoutlook, true]

PS C:\> Set-LabelPolicy -Identity $Policy.Identity -AdvancedSettings @{ outlookdefaultlabel = "None" }

PS C:\> $Policy = Get-LabelPolicy

PS C:\> $Policy.Settings
[mandatory, false]
[powerbimandatory, false]
[outlookdefaultlabel, None] # Here is correctly set to None after changing it
[requiredowngradejustification, true]
[defaultlabelid, defa4170-0d19-0005-0004-bc88714345d2]
[disablemandatoryinoutlook, true]
```

I have a quick fix to handle "None" which just bypasses `Get-Label' cmdlet since it's not required and I was able to export/test with M365Dsc. I'll send a PR for this.

**Comment by ricmestre** [comment]
Well, setting the label policy to null, has seen in this discussion, also works but removes it from the settings list. Is this something that should be checked too? It's easy too add a check for null.

```powershell
PS C:\> $Policy = Get-LabelPolicy

PS C:\> $Policy.Settings
[mandatory, false]
[powerbimandatory, false]
[requiredowngradejustification, true]
[defaultlabelid, defa4170-0d19-0005-0004-bc88714345d2]
[disablemandatoryinoutlook, true]
[outlookdefaultlabel, None]

PS C:\> Set-LabelPolicy -Identity $Policy.Identity -AdvancedSettings @{ outlookdefaultlabel = $null }

PS C:\> (Get-LabelPolicy).Settings
[mandatory, false]
[powerbimandatory, false]
[requiredowngradejustification, true]
[defaultlabelid, defa4170-0d19-0005-0004-bc88714345d2]
[disablemandatoryinoutlook, true]
```
