### ISSUE TITLE
Issue with inverted comma in Name parameter in MSFT_MicrosoftGraphapplistitem in IntuneDeviceConfigurationPolicy

### ISSUE THREAD

**Issue by maheshdalavi** [microsoft/Microsoft365DSC#3117]
#### Details of the scenario you tried and the problem that is occurring
-	If we have a name in “MSFT_MicrosoftGraphapplistitem” with in "IntuneDeviceConfigurationPolicy" an inverted comma in it will result in LCM failure.
 
![image](https://user-images.githubusercontent.com/22946692/229296175-32a3e3b1-ac5e-41bc-bb78-829bb328f426.png)

#### Verbose logs showing the problem
While configuring the LCM gives the below error.
 
![image](https://user-images.githubusercontent.com/22946692/229296181-1e598b8e-d649-4b2e-9f49-c62e7a666994.png)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```
```

#### The operating system the target node is running

    Get-ComputerInfo -Property @(
        'OsName',
        'OsOperatingSystemSKU',
        'OSArchitecture',
        'WindowsVersion',
        'WindowsBuildLabEx',
        'OsLanguage',
        'OsMuiLanguages')

**Comment by andikrueger** [comment]
Just to be sure: The configuration you are using is the result of an export?
