### ISSUE TITLE
Generating an Excel report from a configuration does not work automatically through Azure Automation Runbook

### ISSUE THREAD

**Issue by dwani1** [microsoft/Microsoft365DSC#3122]
Currently the -type Excel on New-M365DSCReportFromConfiguration cmdlet don't work with a Azure Automation Runbook. 

The export fails, cause (of course) you can't open or work in Excel, like you do with a normal PowerShell Script running on a desktop client. Not just "New-Object -ComObject excel.application" won't work, almost everything withing the "New-M365DSCConfigurationToExcel" won't run within a Runbook. 
Editing the "M365DSCReport" module shouldn't be a solution, because it won't stand new updates. Is there any solution to get Excel reports in Azure Autmation without modifying the module itself and risking, to not get new updates anymore, because we have to upload a custom module?

**Comment by andikrueger** [comment]
Actually there is not. This function relies on Excel being available on the system on which the command is executed. 

Please have a look at this related issue: https://github.com/microsoft/Microsoft365DSC/issues/2225
