### ISSUE TITLE
EXO-AtpPolicyForO365 closed Nov3 2019 still an issue

### ISSUE THREAD

**Issue by icpw** [microsoft/Microsoft365DSC#3131]
As per previous issue:

Get-Command : The term 'Get-AtpPolicyForO365' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.322.1\modules\M365DSCUtil.psm1:332 char:31
+ ... vailable = (Get-Command -Name $CmdletName -ErrorAction SilentlyContin ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AtpPolicyForO365:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

[NikCharlebois](https://github.com/NikCharlebois) commented [on Nov 3, 2019](https://github.com/microsoft/Microsoft365DSC/issues/137#issuecomment-549066670)
This should now be handled via the EXOOrganizationConfig resource

**Comment by icpw** [comment]
PLUS similar error when not licensed for certain features

Get-Command : The term 'Get-SafeAttachmentPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.322.1\modules\M365DSCUtil.psm1:332 char:31
+ ... vailable = (Get-Command -Name $CmdletName -ErrorAction SilentlyContin ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-SafeAttachmentPolicy:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

**Comment by icpw** [comment]
Get-AtpPolicyForO365, EXOSafeAttachmentPolicy, EXOSafeAttachmentRule, EXOSafeLinksPolicy, EXOSafeLinksRule

all experience similar issue

**Comment by andikrueger** [comment]
Just to confirm: Would these cmdlets be available, if there is a suitable licensing in place?

**Comment by NikCharlebois** [comment]
Yes, this is a licensing issue. You are required to have the proper license to be able to get these cmdlets. My understanding is that the user is required to have an E5 license for the cmdlet to be made available.
