### ISSUE TITLE
PowerShell 7 Linux (RHEL 9.1) - not able to load module microsoft365dsc

### ISSUE THREAD

**Issue by William-Francillette** [microsoft/Microsoft365DSC#3144]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
I was trying to install M365DSC on powershell 7.3.3 and RHEL 9.1 but couldn't load the module:
Import-Module: The given assembly name was invalid

(I was able to install the module without issue)

![image](https://user-images.githubusercontent.com/79221284/230649287-805cdf43-7dde-4508-b943-28f41da11dce.png)

**Comment by andikrueger** [comment]
M365DSC does not support a linux sub-system at the moment. Not all dependencies do work on a linux system. Even on windows sub systems, there are still some challenges with PS 7.x: https://microsoft365dsc.com/user-guide/get-started/powershell7-support/

**Comment by William-Francillette** [comment]
Thanks Andi - I was playing around with PS7 and DSC and wanted to try if M365DSC would work on Linux

**Comment by andikrueger** [comment]
Are you ok with closing this issue? It would be great to overcome the platform requirements....

**Comment by William-Francillette** [comment]
Sure, please close this one
