### ISSUE TITLE
Not getting new update

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#3146]
#### Details of the scenario you tried and the problem that is occurring
I ran Install-Module Microsoft365DSC -Force then Get-Module Microsoft365DSC -ListAvailable | select ModuleBase, Version
the most recent version shown is 1.23.322.1 I am expecting to see 1.23.405

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)

**Comment by andikrueger** [comment]
It looks like there was an issue with the deployment to powershell gallery. Well look into this issue. 

@NikCharlebois or @ykuijs could you have a look at the release pipeline of the latest release. Right now we see the previous version in PSGallery.

**Comment by DeanGross** [comment]
I also tried the update-module cmdlet with the same result

**Comment by andikrueger** [comment]
@ykuijs was able to fix this issue. The latest version is now available through PowerShellGallery! #3152

**Comment by martincaddick** [comment]
Something weird going on with Update-M365Dependencies.
<img width="855" alt="image" src="https://user-images.githubusercontent.com/73564857/231101808-d7ee3008-607f-43a2-a2ff-3f1e2419fe04.png">

**Comment by andikrueger** [comment]
Which would indicate, that you are already using the latest version of the dependencies.
