### ISSUE TITLE
ImportCimAndScriptKeywordsFromModule problem

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#3147]
#### Details of the scenario you tried and the problem that is occurring
I am trying to document azure ad and getting the following error. 

#### Verbose logs showing the problem
ImportCimAndScriptKeywordsFromModule : A second CIM class definition for 'MSFT_TeamsVoiceRoutingPolicy' was found while processing the schema file 'C:\Program Files 
(x86)\WindowsPowerShell\Modules\Microsoft365DSC\1.23.322.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof'. This class was already defined in the file(s) 'C:\Program 
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.208.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Program 
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.1019.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Program 
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.504.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Program 
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.420.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Program 
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.316.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.23.322.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.23.301.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.23.208.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.22.622.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.22.608.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.22.504.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.22.420.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.22.413.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.22.316.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.22.119.2\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.21.1215.1\DSCResources\MSFT_TeamsVoiceRoutingPolicy\MSFT_TeamsVoiceRoutingPolicy.Schema.mof'. Remove the redundant definition, and then try again.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4143 char:29
+ ...     $null = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], PSInvalidOperationException
    + FullyQualifiedErrorId : System.Management.Automation.PSInvalidOperationException,ImportCimAndScriptKeywordsFromModule
 
ImportCimAndScriptKeywordsFromModule : A second CIM class definition for 'MSFT_TeamsWorkloadPolicy' was found while processing the schema file 'C:\Program Files 
(x86)\WindowsPowerShell\Modules\Microsoft365DSC\1.23.322.1\DSCResources\MSFT_TeamsWorkloadPolicy\MSFT_TeamsWorkloadPolicy.Schema.mof'. This class was already defined in the file(s) 'C:\Program 
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.208.1\DSCResources\MSFT_TeamsWorkloadPolicy\MSFT_TeamsWorkloadPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.23.322.1\DSCResources\MSFT_TeamsWorkloadPolicy\MSFT_TeamsWorkloadPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.23.301.1\DSCResources\MSFT_TeamsWorkloadPolicy\MSFT_TeamsWorkloadPolicy.Schema.mof,C:\Users\dgross\OneDrive - 
Insight\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.23.208.1\DSCResources\MSFT_TeamsWorkloadPolicy\MSFT_TeamsWorkloadPolicy.Schema.mof'. Remove the redundant definition, and then try again.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4143 char:29
+ ...     $null = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], PSInvalidOperationException
    + FullyQualifiedErrorId : System.Management.Automation.PSInvalidOperationException,ImportCimAndScriptKeywordsFromModule
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```

#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

    Get-ComputerInfo -Property @(
        'OsName',
        'OsOperatingSystemSKU',
        'OSArchitecture',
        'WindowsVersion',
        'WindowsBuildLabEx',
        'OsLanguage',
        'OsMuiLanguages')
-->

#### Version of the DSC module that was used ('dev' if using current dev branch)

**Comment by andikrueger** [comment]
Please uninstall the previous M365DSC versions and run Uninstall-M365DSCoutdatedDependencies

**Comment by DeanGross** [comment]
I ran Uninstall-M365DSCOutdatedDependencies and this problem stopped occurring
