### ISSUE TITLE
Intune - Windows 10 Configuration Profiles missing

### ISSUE THREAD

**Issue by bitdeft** [microsoft/Microsoft365DSC#3156]
#### Details of the scenario you tried and the problem that is occurring
When using Intune components such as:
```Export-M365DSCConfiguration -workloads @("intune") ```
there are configuration profiles that are not being exported. 

#### Verbose logs showing the problem
Here we can see that I have 4 different configuration policies, containing Settings catalouge and administrative templates, with assignements and no assignments.
![image](https://user-images.githubusercontent.com/6373174/231243527-fa012cff-5633-4b0f-947b-3f9ee296b10e.png)

However, inside the resulting DSC config file, there is no ConfigurationPolicyWindows10 
![image](https://user-images.githubusercontent.com/6373174/231244192-5290452b-972a-4045-b602-cf6bf90d6f4d.png)

Is this because "configuration Policy" is actually different than "configuration Profile"? Either way, I can't find the name of my configuration profiles in the file either. So it seems that these profiles are not being saved, which is worrying. 

#### The operating system the target node is running
Win10, Powershell 5.1
#### Version of the DSC module that was used ('dev' if using current dev branch)
1.23.322.1

**Comment by ricmestre** [comment]
@bitdeft  Hi, just to let you know that not all resources, which also includes policies, are available to be used with M365Dsc module. In your specific case administrative templates should become available through #3145 whereas settings catalog is still not done and I requested it through #3070. Device restrictions or compliance policies should be exported without issues as you already noted initially, hope this clarifies your query.

**Comment by ricmestre** [comment]
@William-Francillette any word on this since it would also benefit us? Thanks in advance!

**Comment by bitdeft** [comment]
How difficult is it to contribute to this code base here? This is the current contributor guideline but it seems to point to sharepointDSC which may be a bit out of date?

Also, I would say dynamically would be nice, since Intune/"MEM" has had rapid changes in configuration parameters, and doesn't seem to have any sign of stopping changes....
