### ISSUE TITLE
AADConditionalAccessPolicy: Re-open #2974 (Couldn't find Location 00000000-0000-0000-0000-000000000000)

### ISSUE THREAD

**Issue by GruberMarkus** [microsoft/Microsoft365DSC#3174]
This issue #2974 is still relevant for release 1.23.412.

I get the exact same error message for two conditional access policies. Both are configured to include all locations and to exclude "Multifactor authentication trusted IPs".

```
[2023.04.17 07:42:39]
"Couldn't find Location 00000000-0000-0000-0000-000000000000 , couldn't add to policy <name of policy A>"
TenantId: <tenant name>



[2023.04.17 07:42:57]
"Couldn't find Location 00000000-0000-0000-0000-000000000000 , couldn't add to policy <name of policy B>"
TenantId: <tenant name>
```

**Comment by GruberMarkus** [comment]
Hi @andikrueger and @NikCharlebois,

if there is anything I can do to help you solve this issue, just let me know.

**Comment by andikrueger** [comment]
Were you able to retest this issue with releases later than: https://github.com/microsoft/Microsoft365DSC/pull/3229 - Release 1.23.426.1
