### ISSUE TITLE
Export-M365DSCConfiguration: Mode "Full" doesn't include TeamsUserCallingSettings

### ISSUE THREAD

**Issue by leitzler** [microsoft/Microsoft365DSC#3180]
#### Details of the scenario you tried and the problem that is occurring
I compared output from resources extracted during:
```
Export-M365DSCConfiguration -CertificateThumbprint $Cert.Thumbprint -TenantId <redacted>.onmicrosoft.com -ApplicationId 01234567-890a-bcde-f012-34567890abcd -Path Output -Mode Full -MaxProcesses 64
```
and:
```
Get-M365DSCAllResources
```

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Use `Get-M365DSCAllResources` as source for `Full` to ensure `TeamsUserCallingSettings` is exported.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Using Windows Server Core container, mcr.microsoft.com/windows/servercore:1809-amd64.

```powershell
Install-PackageProvider -Name NuGet -Force
Install-Module Microsoft365DSC -Force
Update-M365DSCDependencies
```

#### The operating system the target node is running
```
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```
#### Version of the DSC module that was used ('dev' if using current dev branch)
```
1.23.412.1 Microsoft365DSC                     PSGallery            This DSC module is used to configure and monitor Microsoft tenants, including SharePoint Online, Exchange, Teams, etc.
```

**Comment by andikrueger** [comment]
This looks like an issue with the configuration within M365DSC. We should be able to get all information with the authentication method chosen.

**Comment by andikrueger** [comment]
Found the source of the issue. The TeamUserCallingSettings Resource does not have the proper set of authentication params.

**Comment by NikCharlebois** [comment]
TeamsUserCallingSettings is the ONLY Teams resource not supporting ServicePrincipal yet. The Teams product group is working on adding support for its associated cmdlet but we do no yet have any ETA.

**Comment by NikCharlebois** [comment]
I will try to get the latest ETA on this and will report back.

**Comment by leitzler** [comment]
Thank you, that makes sense! If it is far into the future it could be helpful to update the messages to tell the user that `TeamsUserCallingSettings` doesn't support `ServicePricipal`.

**Comment by NikCharlebois** [comment]
Still no ETA. Keeping this opened.

**Comment by andikrueger** [comment]
Looks like `Set-CsUserCallingSettings` is no longer in the list of not supported cmdLets for Application-based Authentication. https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication#cmdlets-supported

@NikCharlebois Can you confirm?

**Comment by dave1996** [comment]
I'm having the same issue here. 
Seems the TeamsUserCallingSettings component still can not be exported with certificate thumbprint, it will ignore all the certificate auth parameters and ask me to input my username and password.

**Comment by ricmestre** [comment]
It seems to work now, I'll send a PR shortly. I really don't like the domain to appear in the export instead of being replaced by $OrganizationName but that's going to be for another day.

```
        TeamsUserCallingSettings "TeamsUserCallingSettings-AdeleV@REDACTED"
        {
            ApplicationId         = $ConfigurationData.NonNodeData.ApplicationId;
            CallGroupOrder        = "Simultaneous";
            CallGroupTargets      = @();
            CertificateThumbprint = $ConfigurationData.NonNodeData.CertificateThumbprint;
            Ensure                = "Present";
            Identity              = "AdeleV@REDACTED";
            TenantId              = $OrganizationName;
            UnansweredDelay       = "00:00:20";
        }
```
