### ISSUE TITLE
Unable to run comparisons - Results in string of errors and exit from PS

### ISSUE THREAD

**Issue by digitalpapercut** [microsoft/Microsoft365DSC#3196]
When running a comparison with two exports, I am getting a long list of errors before PowerShell exits completely. The following error was what I was able to catch before the window exited. 

Cim deserializer threw an error when deserializing file. From what I could tell, it just repeated this error over and over until it crashed and exited. 

The script ran was:  New-M365DSCDeltaReport -Source C:\Tenant1DSCExport.ps1 -Destination C:\Tenant2DSCExport.ps1 -OutputPath C:\Compare\Exports.html

Any suggestions on a fix or is this a bug?

**Comment by NikCharlebois** [comment]
Any chances you could share a redacted version of your configs for us to try and replicate? Thanks

**Comment by digitalpapercut** [comment]
How much do you need? The entire config file for one of the tenants? Trying to determine the best way to do that, so open to suggestions.

**Comment by NikCharlebois** [comment]
Ideally the full config. Feel free to reach out by email at Nik.Charlebois<at>Microsoft.com
