### ISSUE TITLE
Test-DscConfiguration fails for Distribution lists

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#321]
**Steps to reproduce**
- Configure the O365 tenant to have at least one Distribution List
- Create the DSC files and compile the mof file
- run a Test-DscConfiguration against the mof file

**Details**
The Test-DscConfiguration will return that a non-complaint setup was found as it expects the DL members property to by non-empty:

```
Current Values: Description=; DisplayName=DL_o365test; Ensure=Present; GlobalAdminAccount=System.Management.Automation.PSCredential; MailNickName=dl_o365test; ManagedBy=(); **Members=$null**
Target Values: Description=; DisplayName=DL_o365test; Ensure=Present; GlobalAdminAccount=System.Management.Automation.PSCredential; MailNickName=dl_o365test; ManagedBy=(); **Members=()**; Verbose=True
Expected to find an array value for property Members in the current values, but it was either not present or was null. This has caused the test method to return false.
Detected Drifted Parameter [MSFT_O365Group]Members
```

No changes have been made to the tenant btw. pulling the reference configuration and running the Test-DscConfiguration command.

**Comment by NikCharlebois** [comment]
@SebastianGoers in reference to the other issue that was incorrectly calling Test-DSCConfiguration, can you elaborate on the steps to replicate the current issue at hand, along with the exact PowerShell command you are using for Test-DSCConfiguration? Thanks
