### ISSUE TITLE
Error applying @("SCSensitivityLabel") Components from one tenant to another tenant

### ISSUE THREAD

**Issue by sadishdit** [microsoft/Microsoft365DSC#3222]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by sadishdit** [comment]
ISSUE TITLE:
Error applying @("SCSensitivityLabel") Components from one tenant to another tenant

    ISSUE DESCRIPTION 
    I have extracted SCSensitivityLabel configuration from one tenant via GA credential authentication and tried to import same configuration to another tenant by running Start-DscConfiguration .\M365TenantConfig -Wait -Verbose -Force command. It throwing below error 


VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root
/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer IESK4931 with user sid S-1-12-1-1744493552-1306810162-56578998-461199266.
VERBOSE: [IESK4931]: LCM:  [ Start  Set      ]
VERBOSE: [IESK4931]: LCM:  [ End    Set      ]
The command Test-TargetResource of the PS module MSFT_SCSensitivityLabel does not implement the write property Disabled mentioned in the corresponding MOF schema file C:\Program 
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.419.1\DscResources\MSFT_SCSensitivityLabel\MSFT_SCSensitivityLabel.schema.mof. All write paramenters mentioned in the schema 
file must be implemented by the command Test-TargetResource.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : WriteParameterNotImplemented
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.637 seconds

**Comment by andikrueger** [comment]
This does not look right.

Would you be able to share the configuration for the Sensitivity Label? Please make sure to remove any sensitive information.

**Comment by sadishdit** [comment]
Below is the configuration 

# Generated with Microsoft365DSC version 1.23.419.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $Credential
)

Configuration M365TenantConfig
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $Credential
    )

    if ($null -eq $Credential)
    {
        <# Credentials #>
        $Credscredential = Get-Credential -Message "Credentials"

    }
    else
    {
        $CredsCredential = $Credential
    }

    $OrganizationName = $CredsCredential.UserName.Split('@')[1]

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.23.419.1'

    Node localhost
    {
        SCSensitivityLabel "SCSensitivityLabel-Public label"
        {
            AdvancedSettings     = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'isparent'
                    Value = 'False'
                }
            );
            Comment              = "";
            ContentType          = @("File, Email","Teamwork");
            Credential           = $Credscredential;
            DisplayName          = "Public label";
            Ensure               = "Present";
            LocaleSettings       = @(
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'displayName'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Public label'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'you can send docs to anyone'
                        }
                    )
                }
            );
            Name                 = "Public";
            Priority             = 0;
            Tooltip              = "you can send docs to anyone";
        }
        SCSensitivityLabel "SCSensitivityLabel-Private label"
        {
            AdvancedSettings                   = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'isparent'
                    Value = 'False'
                }
            );
            ApplyContentMarkingFooterAlignment = "Left";
            ApplyContentMarkingFooterEnabled   = $True;
            ApplyContentMarkingFooterFontColor = "#000000";
            ApplyContentMarkingFooterFontSize  = "10";
            ApplyContentMarkingFooterMargin    = "5";
            ApplyContentMarkingFooterText      = "Inspira";
            ApplyContentMarkingHeaderAlignment = "Left";
            ApplyContentMarkingHeaderEnabled   = $True;
            ApplyContentMarkingHeaderFontColor = "#000000";
            ApplyContentMarkingHeaderFontSize  = "10";
            ApplyContentMarkingHeaderMargin    = "5";
            ApplyContentMarkingHeaderText      = "Inspira";
            ApplyWaterMarkingEnabled           = $True;
            ApplyWaterMarkingFontColor         = "#000000";
            ApplyWaterMarkingFontSize          = "10";
            ApplyWaterMarkingLayout            = "Diagonal";
            ApplyWaterMarkingText              = "Inspira Private";
            Comment                            = "";
            ContentType                        = @("File, Email","Teamwork");
            Credential                         = $Credscredential;
            DisplayName                        = "Private label";
            EncryptionDoNotForward             = $False;
            EncryptionEnabled                  = $True;
            EncryptionEncryptOnly              = $True;
            EncryptionPromptUser               = $True;
            EncryptionProtectionType           = "userdefined";
            Ensure                             = "Present";
            LocaleSettings                     = @(
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'displayName'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Private label'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'you can choose restrictions'
                        }
                    )
                }
            );
            Name                               = "Private";
            Priority                           = 1;
            Tooltip                            = "you can choose restrictions";
        }
        SCSensitivityLabel "SCSensitivityLabel-Confidential label"
        {
            AdvancedSettings                            = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'isparent'
                    Value = 'False'
                }
            );
            ApplyContentMarkingFooterAlignment          = "Left";
            ApplyContentMarkingFooterEnabled            = $True;
            ApplyContentMarkingFooterFontColor          = "#000000";
            ApplyContentMarkingFooterFontSize           = "10";
            ApplyContentMarkingFooterMargin             = "5";
            ApplyContentMarkingFooterText               = "Inspira";
            ApplyContentMarkingHeaderAlignment          = "Left";
            ApplyContentMarkingHeaderEnabled            = $True;
            ApplyContentMarkingHeaderFontColor          = "#000000";
            ApplyContentMarkingHeaderFontSize           = "10";
            ApplyContentMarkingHeaderMargin             = "5";
            ApplyContentMarkingHeaderText               = "Inspira";
            ApplyWaterMarkingEnabled                    = $True;
            ApplyWaterMarkingFontColor                  = "#000000";
            ApplyWaterMarkingFontSize                   = "10";
            ApplyWaterMarkingLayout                     = "Diagonal";
            ApplyWaterMarkingText                       = "Inspira Confidential";
            Comment                                     = "";
            ContentType                                 = @("File, Email","Teamwork");
            Credential                                  = $Credscredential;
            DisplayName                                 = "Confidential label";
            EncryptionContentExpiredOnDateInDaysOrNever = "Never";
            EncryptionEnabled                           = $True;
            EncryptionOfflineAccessDays                 = "-1";
            EncryptionProtectionType                    = "template";
            EncryptionRightsDefinitions                 = "AuthenticatedUsers:VIEW,VIEWRIGHTSDATA;TL@$($OrganizationName):VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,OBJMODEL;CF@$($OrganizationName):VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,OBJMODEL;hg@$($OrganizationName):VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,OBJMODEL";
            Ensure                                      = "Present";
            LocaleSettings                              = @(
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'displayName'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Confidential label'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'send confidential documents within the organization'
                        }
                    )
                }
            );
            Name                                        = "Confidential";
            Priority                                    = 2;
            Tooltip                                     = "send confidential documents within the organization";
        }
        SCSensitivityLabel "SCSensitivityLabel-Internal label"
        {
            AdvancedSettings                            = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'isparent'
                    Value = 'False'
                }
            );
            ApplyContentMarkingFooterAlignment          = "Left";
            ApplyContentMarkingFooterEnabled            = $True;
            ApplyContentMarkingFooterFontColor          = "#000000";
            ApplyContentMarkingFooterFontSize           = "10";
            ApplyContentMarkingFooterMargin             = "5";
            ApplyContentMarkingFooterText               = "Inspira";
            ApplyContentMarkingHeaderAlignment          = "Left";
            ApplyContentMarkingHeaderEnabled            = $True;
            ApplyContentMarkingHeaderFontColor          = "#000000";
            ApplyContentMarkingHeaderFontSize           = "10";
            ApplyContentMarkingHeaderMargin             = "5";
            ApplyContentMarkingHeaderText               = "Inspira";
            ApplyWaterMarkingEnabled                    = $True;
            ApplyWaterMarkingFontColor                  = "#000000";
            ApplyWaterMarkingFontSize                   = "10";
            ApplyWaterMarkingLayout                     = "Diagonal";
            ApplyWaterMarkingText                       = "Inspira Enterprise";
            Comment                                     = "";
            ContentType                                 = @("File, Email","Teamwork");
            Credential                                  = $Credscredential;
            DisplayName                                 = "Internal label";
            EncryptionContentExpiredOnDateInDaysOrNever = "Never";
            EncryptionEnabled                           = $True;
            EncryptionOfflineAccessDays                 = "-1";
            EncryptionProtectionType                    = "template";
            EncryptionRightsDefinitions                 = "CF@$($OrganizationName):VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,EDITRIGHTSDATA,EXPORT,OBJMODEL,OWNER;TL@$($OrganizationName):VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,EDITRIGHTSDATA,EXPORT,OBJMODEL,OWNER;hg@$($OrganizationName):VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,EDITRIGHTSDATA,EXPORT,OBJMODEL,OWNER";
            Ensure                                      = "Present";
            LocaleSettings                              = @(
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'displayName'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Internal label'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Send documents within the organization'
                        }
                    )
                }
            );
            Name                                        = "INTERNAL";
            Priority                                    = 3;
            Tooltip                                     = "Send documents within the organization";
        }
        SCSensitivityLabel "SCSensitivityLabel-DSCPublic"
        {
            AdvancedSettings                            = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'aiplabelversion'
                    Value = '6930dbde-8212-4d76-bd97-1d8f0411f27b'
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'color'
                    Value = '#317100'
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'isparent'
                    Value = 'False'
                }
            );
            Comment                                     = "";
            ContentType                                 = @("File, Email");
            Credential                                  = $Credscredential;
            DisplayName                                 = "DSCPublic";
            EncryptionContentExpiredOnDateInDaysOrNever = "Never";
            EncryptionEnabled                           = $False;
            EncryptionOfflineAccessDays                 = "0";
            EncryptionProtectionType                    = "template";
            Ensure                                      = "Present";
            LocaleSettings                              = @(
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'displayName'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'DSCPublic'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Approved information for public disclosure'
                        }
                    )
                }
            );
            Name                                        = "7039522b-ce94-44a0-92fb-0481c418a4e6";
            Priority                                    = 4;
            Tooltip                                     = "Approved information for public disclosure";
        }
        SCSensitivityLabel "SCSensitivityLabel-Internal"
        {
            AdvancedSettings                            = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'aiplabelversion'
                    Value = '36d61235-7151-4448-b9ad-03ce5dc5493c'
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'color'
                    Value = '#0078D7'
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'isparent'
                    Value = 'False'
                }
            );
            ApplyContentMarkingFooterAlignment          = "Left";
            ApplyContentMarkingFooterEnabled            = $False;
            ApplyContentMarkingFooterFontColor          = "#000000";
            ApplyContentMarkingFooterFontSize           = "8";
            ApplyContentMarkingFooterMargin             = "15";
            ApplyContentMarkingFooterText               = "Sensitivity: Internal";
            Comment                                     = "";
            ContentType                                 = @("File, Email");
            Credential                                  = $Credscredential;
            DisplayName                                 = "Internal";
            EncryptionContentExpiredOnDateInDaysOrNever = "Never";
            EncryptionEnabled                           = $False;
            EncryptionOfflineAccessDays                 = "0";
            EncryptionProtectionType                    = "template";
            Ensure                                      = "Present";
            LocaleSettings                              = @(
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'displayName'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Internal'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Company information intended for use by all colleagues on a need to know basis when conducting company business'
                        }
                    )
                }
            );
            Name                                        = "c525c408-17aa-4d15-8054-eee39715993e";
            Priority                                    = 5;
            Tooltip                                     = "Company information intended for use by all colleagues on a need to know basis when conducting company business";
        }
        SCSensitivityLabel "SCSensitivityLabel-DSCConfidential"
        {
            AdvancedSettings                            = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'aiplabelversion'
                    Value = 'e03259b7-4b5b-430b-9815-de92822cb5c8'
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'color'
                    Value = '#FF8C00'
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'isparent'
                    Value = 'False'
                }
            );
            ApplyContentMarkingFooterAlignment          = "Left";
            ApplyContentMarkingFooterEnabled            = $False;
            ApplyContentMarkingFooterFontColor          = "#000000";
            ApplyContentMarkingFooterFontSize           = "8";
            ApplyContentMarkingFooterMargin             = "15";
            ApplyContentMarkingFooterText               = "Sensitivity: Confidential";
            Comment                                     = "";
            ContentType                                 = @("File, Email");
            Credential                                  = $Credscredential;
            DisplayName                                 = "DSCConfidential";
            EncryptionContentExpiredOnDateInDaysOrNever = "Never";
            EncryptionEnabled                           = $False;
            EncryptionOfflineAccessDays                 = "0";
            EncryptionProtectionType                    = "template";
            Ensure                                      = "Present";
            LocaleSettings                              = @(
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'displayName'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'DSCConfidential'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Information that is sensitive and intended for restricted specific business groups of colleagues on a need to know basis'
                        }
                    )
                }
            );
            Name                                        = "42455fcb-65d9-4933-afb7-0da26de1c595";
            Priority                                    = 6;
            Tooltip                                     = "Information that is sensitive and intended for restricted specific business groups of colleagues on a need to know basis";
        }
        SCSensitivityLabel "SCSensitivityLabel-PAN Auto Label"
        {
            AdvancedSettings                            = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'isparent'
                    Value = 'False'
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'defaultcontentlabel'
                    Value = '0c63041a-7482-4d71-81cc-d89d89f84e59'
                }
            );
            ApplyContentMarkingHeaderAlignment          = "Left";
            ApplyContentMarkingHeaderEnabled            = $False;
            ApplyContentMarkingHeaderFontColor          = "#000000";
            ApplyContentMarkingHeaderFontSize           = "10";
            ApplyContentMarkingHeaderMargin             = "5";
            ApplyContentMarkingHeaderText               = "Confidential Auto Apply ";
            ApplyWaterMarkingEnabled                    = $False;
            ApplyWaterMarkingFontColor                  = "#000000";
            ApplyWaterMarkingFontSize                   = "10";
            ApplyWaterMarkingLayout                     = "Diagonal";
            ApplyWaterMarkingText                       = "Auto-Labelling Detected ";
            Comment                                     = "General Label Auto Apply for Higher Mgmt";
            ContentType                                 = @("File, Email","Site, UnifiedGroup","Teamwork");
            Credential                                  = $Credscredential;
            DisplayName                                 = "PAN Auto Label";
            EncryptionContentExpiredOnDateInDaysOrNever = "Never";
            EncryptionEnabled                           = $True;
            EncryptionOfflineAccessDays                 = "0";
            EncryptionProtectionType                    = "template";
            EncryptionRightsDefinitions                 = "hg@$($OrganizationName):VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,OBJMODEL";
            Ensure                                      = "Present";
            LocaleSettings                              = @(
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'displayName'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'PAN Auto Label'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'General Label Auto Apply'
                        }
                    )
                }
            );
            Name                                        = "General Label";
            Priority                                    = 7;
            SiteAndGroupExternalSharingControlType      = "Disabled";
            SiteAndGroupProtectionAllowFullAccess       = $False;
            SiteAndGroupProtectionAllowLimitedAccess    = $False;
            SiteAndGroupProtectionBlockAccess           = $False;
            Tooltip                                     = "General Label Auto Apply";
        }
        SCSensitivityLabel "SCSensitivityLabel-Credit Auto Label"
        {
            AdvancedSettings                            = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'isparent'
                    Value = 'False'
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'defaultcontentlabel'
                    Value = 'e8ca7d43-80af-4edc-93ba-4d3209717e14'
                }
            );
            Comment                                     = "";
            ContentType                                 = @("File, Email","Site, UnifiedGroup","Teamwork");
            Credential                                  = $Credscredential;
            DisplayName                                 = "Credit Auto Label";
            EncryptionContentExpiredOnDateInDaysOrNever = "Never";
            EncryptionEnabled                           = $True;
            EncryptionOfflineAccessDays                 = "0";
            EncryptionProtectionType                    = "template";
            EncryptionRightsDefinitions                 = "hg@$($OrganizationName):VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,OBJMODEL";
            Ensure                                      = "Present";
            LocaleSettings                              = @(
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'displayName'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Credit Auto Label'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'auto applies label when credit card no is prsen in doc'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'autotooltip'
                    LabelSettings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Your document is labelled'
                        }
                    )
                }
            );
            Name                                        = "Auto Label for PCI DSS";
            Priority                                    = 8;
            Tooltip                                     = "auto applies label when credit card no is prsen in doc";
        }
    }
}

M365TenantConfig -ConfigurationData .\ConfigurationData.psd1 -Credential $Credential

**Comment by andikrueger** [comment]
This is already resolved by https://github.com/microsoft/Microsoft365DSC/pull/3195. Will be included in this week's release
