### ISSUE TITLE
PSDesiredStateConfiguration\Node : The term 'System.Collections.Hashtable' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### ISSUE THREAD

**Issue by gipy87** [microsoft/Microsoft365DSC#3254]
#### Details of the scenario you tried and the problem that is occurring
I tried to export Azure AD using the Export-M365DSCConfiguration cmdlet using service principal with certificate thumbprint.

#### Verbose logs showing the problem
PSDesiredStateConfiguration\Node : The term 'System.Collections.Hashtable' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\Backups\AAD\TenantConfiguration\M365TenantConfig.ps1:15 char:5
+     Node localhost
+     ~~~~
    + CategoryInfo          : ObjectNotFound: (System.Collections.Hashtable:String) [PSDesiredStateConfiguration\node], ParentContainsErrorRecordExcept
   ion
    + FullyQualifiedErrorId : CommandNotFoundException,PSDesiredStateConfiguration\node

Compilation errors occurred while processing configuration 'M365TenantConfig'. Please review the errors reported in error stream and modify your
configuration code appropriately.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5
+     throw $ErrorRecord
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (M365TenantConfig:String) [], InvalidOperationException
    + FullyQualifiedErrorId : FailToProcessConfiguration
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
@{
    AllNodes = @(
        @{
            NodeName                    = "localhost"
            PSDscAllowPlainTextPassword = $true;
            PSDscAllowDomainUser        = $true;
            #region Parameters
            # Path of the certificate used to encrypt credentials in the file.
            CertificateFile = "M365DSC.cer"

            # Default Value Used to Ensure a Configuration Data File is Generated
            ServerNumber = "0"

        }
    )
    NonNodeData = @(
        @{
            # Tenant's default verified domain name
            OrganizationName = "test*****.onmicrosoft.com"

            # Azure AD Application Id for Authentication
            ApplicationId = "68a78ea2-*************"

            # The Id or Name of the tenant to authenticate against
            TenantId = "test*******.onmicrosoft.com"

            # Thumbprint of the certificate to use for authentication
            CertificateThumbprint = "3A71C***********************"

        }
    )
}


```

**Comment by andikrueger** [comment]
Closing this one in favor of #3255. Looks to be a duplicate
