### ISSUE TITLE
The term 'System.Collections.Hashtable' is not recognized as a name of a cmdlet, function, script file, or executable program.

### ISSUE THREAD

**Issue by gipy87** [microsoft/Microsoft365DSC#3255]
ISSUE TITLE:

    'The term 'System.Collections.Hashtable' is not recognized as a name of a cmdlet, function, script file, or executable program.'

    ISSUE DESCRIPTION (this template):
When I tried to compile the extracted AAD config file without any parameter (because I using Service Principal with Certificate Thumbprint to export the AAD config), I got below error.

PSDesiredStateConfiguration\node: D:\Backups\AAD\TenantConfiguration\M365TenantConfig.ps1:15
Line |
  15 |      Node localhost
     |      ~~~~
     | The term 'System.Collections.Hashtable' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the
     | spelling of the name, or if a path was included, verify that the path is correct and try again.
InvalidOperation: Errors occurred while processing configuration 'M365TenantConfig'.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
@{
    AllNodes = @(
        @{
            NodeName                    = "localhost"
            PSDscAllowPlainTextPassword = $true;
            PSDscAllowDomainUser        = $true;
            #region Parameters
            # Path of the certificate used to encrypt credentials in the file.
            CertificateFile = "M365DSC.cer"

            # Default Value Used to Ensure a Configuration Data File is Generated
            ServerNumber = "0"

        }
    )
    NonNodeData = @(
        @{
            # Tenant's default verified domain name
            OrganizationName = "************.onmicrosoft.com"

            # Azure AD Application Id for Authentication
            ApplicationId = "****************************"

            # The Id or Name of the tenant to authenticate against
            TenantId = "**********.onmicrosoft.com"

            # Thumbprint of the certificate to use for authentication
            CertificateThumbprint = "3A71CB***********************"

        }
    )
}

```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2022 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.1.amd64fre.fe_release.210507-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.2.5

**Comment by NikCharlebois** [comment]
Can you share a redacted copy of the M365TenantConfig.ps1 configuration file? Thanks

**Comment by andikrueger** [comment]
> Reviewers = @(System.Collections.Hashtable)

looks like some data is not properly returned within the export.
