### ISSUE TITLE
Resource 'SPOSite' requires that a value of type 'UInt32' be provided for property 'TimeZoneId'.

### ISSUE THREAD

**Issue by gipy87** [microsoft/Microsoft365DSC#3272]
ISSUE TITLE:
Resource 'SPOSite' requires that a value of type 'UInt32' be provided for property 'TimeZoneId'.

    ISSUE DESCRIPTION (this template):
When I try to compile the exported SharePoint config powershell file (M365TenantConfig.ps1), I got the following error "Resource 'SPOSite' requires that a value of type 'UInt32' be provided for property 'TimeZoneId'."
![image](https://user-images.githubusercontent.com/26708285/236309303-d5b97a0f-1e40-4de4-9998-5abf3cf0c1dd.png)

Then, I checked my DSC configuration file and noticed there's no "TimeZoneId" property extracted out.
But, when I login to that SPO Site and check the timezone does selected the Pacific TimeZone -8:00:00 UTC
![image](https://user-images.githubusercontent.com/26708285/236310468-4249469c-80f3-4b05-89bb-0efa02811df5.png)

I'm not sure whether this is a bug in Export-M365DSCConfiguration Cmdlet or missing necessary SPO permission.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# Generated with Microsoft365DSC version 1.23.503.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
)

Configuration M365TenantConfig
{
    param (
    )

    $OrganizationName = $ConfigurationData.NonNodeData.OrganizationName

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.23.503.1'

    Node localhost
    {
        SPOSite "SPOSite-Communication site"
        {
            AllowSelfServiceUpgrade                     = $True;
            AnonymousLinkExpirationInDays               = 0;
            ApplicationId                               = $ConfigurationData.NonNodeData.ApplicationId;
            CertificateThumbprint                       = $ConfigurationData.NonNodeData.CertificateThumbprint;
            CommentsOnSitePagesDisabled                 = $False;
            DefaultLinkPermission                       = "None";
            DefaultSharingLinkType                      = "None";
            DenyAddAndCustomizePages                    = $True;
            DisableAppViews                             = "NotDisabled";
            DisableCompanyWideSharingLinks              = "NotDisabled";
            DisableFlows                                = $False;
            Ensure                                      = "Present";
            LocaleId                                    = 1033;
            OverrideTenantAnonymousLinkExpirationPolicy = $False;
            Owner                                       = "02c3e9ed-0eb4-4e80-8eb3-520d32******";
            SharingCapability                           = "ExternalUserAndGuestSharing";
            ShowPeoplePickerSuggestionsForGuestUsers    = $False;
            SocialBarOnSitePagesDisabled                = $False;
            StorageMaximumLevel                         = 26214400;
            StorageWarningLevel                         = 25574400;
            Template                                    = "SITEPAGEPUBLISHING#0";
            TenantId                                    = $OrganizationName;
            Title                                       = "Communication site";
            Url                                         = "https://$($OrganizationName.Split('.')[0]).sharepoint.com/";
        }
}

M365TenantConfig -ConfigurationData .\ConfigurationData.psd1
```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2022 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.1.amd64fre.fe_release.210507-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.23.503.1

**Comment by desmay** [comment]
Can you make sure there is only 1 version of PNP installed and its 1.12.0.  I just ran a test with latest build and my extract of communication site had TimeZoneId.

**Comment by gipy87** [comment]
> Can you make sure there is only 1 version of PNP installed and its 1.12.0. I just ran a test with latest build and my extract of communication site had TimeZoneId.

Hi desmay,

Yes - the installed version of PNP only 1 version - 1.12.0 and still I'm getting this same error.

**Comment by gipy87** [comment]
> Can you make sure there is only 1 version of PNP installed and its 1.12.0. I just ran a test with latest build and my extract of communication site had TimeZoneId.

I just realized that whenever I try to execute the Export PSCmdlet  using Certificate thumbprint on PowerShell 7 console, after export finished - PSCmdlet tend to import the 1.0.0 version PnP.PowerShell module even though I have explicitly imported the PnP.PowerShell module version 1.12.0 upfront.
![image](https://github.com/microsoft/Microsoft365DSC/assets/26708285/c61524d7-a4be-4297-aa49-7fd9c81eb579)

Why Microsoft365DSC cmdlet tend to use PnP.PowerShell version 1.0.0 instead of the imported PnP.PowerShell 1.12.0 version?

My machine has 2 different PowerShell console installed (PowerShell 5.1 & PowerShell 7).

**Comment by gipy87** [comment]
> Can you make sure there is only 1 version of PNP installed and its 1.12.0. I just ran a test with latest build and my extract of communication site had TimeZoneId.

I managed to fix the problem by re-install the PnP.PowerShell module using PowerShell 5.1 , run the Export cmdlet and able to extract the TimeZoneId properly. It seems like having 2 different PowerShell version installed in same machine will cause some problem on using the PnP.PowerShell module in PowerShell 7 console.

By using PowerShell 5.1 , I can see the TimeZoneId value extracted properly.
![image](https://github.com/microsoft/Microsoft365DSC/assets/26708285/a616adbc-56e0-4d70-b298-9b1df525fa64)

Checking the imported PnP.PowerShell module , only 1.12.0 version is returned.
![image](https://github.com/microsoft/Microsoft365DSC/assets/26708285/d6260bb9-3696-4a28-97cf-5550e56d1f63)

I'm not sure whether is this a bug on PowerShell 5.1 or 7, or whether they can't co-exist together in same machine. But anyway, my problem is resolved by re-install the PnP.PowerShell with required version 1.12.0 using PowerShell 5.1 console and everything works smoothly.

**Comment by andikrueger** [comment]
Thank you for the feedback and glad you were able to resolve this issue!
