### ISSUE TITLE
Release 1.23.503.1 not yet tagged

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#3275]
Any reason why release 1.23.503.1 is still not tagged?

In our solution I'm relying on checking out specific tags, especially the latest version but not Dev, nevertheless since this one is not tagged yet I'm using the Dev branch which already includes unreleased resources.

**Comment by andikrueger** [comment]
Good catch and thanks for bringing this to our attention. The module got pushed to PSGallery, but is missing within our release section.

**Comment by ykuijs** [comment]
This has just been fixed. Thanks for reporting this!
