### ISSUE TITLE
Get-M365DSCCompiledPermissionList doesn't give back permission list with Teams resources

### ISSUE THREAD

**Issue by meggenberger** [microsoft/Microsoft365DSC#3291]
#### Details of the scenario you tried and the problem that is occurring
Trying to get the required permissions list for some Teams resources to update my application registration. But it comes back empty.

#### Verbose logs showing the problem
```powershell
Get-M365DSCCompiledPermissionList -ResourceNameList @("TeamsFederationConfiguration", "TeamsFilesPolicy", "TeamsGroupPolicyAssignment", "TeamsMeetingConfiguration", "TeamsMeetingPolicy", "TeamsTranslationRule")

Name                           Value
----                           -----
RequiredRoles                  {}
Read                           {}
RequiredRoleGroups             {}
Update                         {}
```
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
no configuration as I'm trying to get the needed permissions only.

#### The operating system the target node is running
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.23.503.1 Microsoft365DSC

**Comment by NikCharlebois** [comment]
Linking to #2653
