### ISSUE TITLE
Including Org Setting in Microsoft365DSC

### ISSUE THREAD

**Issue by maheshdalavi** [microsoft/Microsoft365DSC#3297]
‎### Description
- Org setting has below Privacy related settings.
(https://admin.microsoft.com/Adminportal/Home#/Settings/Services)
- These are very much important for managing the Tenant's security.
- Changes in it can be considered a major security threat.
- These settings are very much useful for Drift monitoring
- Request you to consider it and check if it can be incorporated in Microsoft365DSC

### Special considerations or limitations

Account Linking‎
Choose to allow users to connect their ‎Azure AD‎ and ‎Account Linking‎ accounts.

‎Calendar‎
Allow users to share their calendars with people outside of your organization.

‎Cortana‎
Manage ‎Cortana‎ data access for ‎Windows‎ versions 1909 and earlier and ‎Cortana‎ app on ‎iOS‎ and ‎Android‎.

‎Microsoft 365‎ installation options
Choose how often users get feature updates and the ‎Microsoft 365‎ apps that users can install.

‎Microsoft 365‎ on the web
Let users open files stored in third-party storage services in ‎Microsoft 365‎.

‎Microsoft‎ communication to users
Let people in your organization receive email from ‎Microsoft‎ about training and new features.

‎Microsoft Forms‎
Manage external sharing and record the names of people in your org who fill out forms.

‎Microsoft Graph Data Connect‎
Manage and update your ‎Microsoft Graph Data Connect‎ settings.

‎Microsoft Search in Bing‎ homepage
Customize ‎‎Bing‎.com page for your signed-in users.

‎Microsoft Teams‎
Manage and update your ‎Microsoft Teams‎ settings.

‎Microsoft 365‎ Groups
Manage external sharing and ownerless groups.

‎Modern authentication‎
Change ‎Exchange Online‎ authentication‎ settings for your entire organization.

Multi-factor authentication
Manage multi-factor authentication settings for your users.

‎Office Scripts‎
Let users automate their tasks in ‎Microsoft 365‎ on the web.

Reports
Manage data privacy controls for Admin Center reports.

‎SharePoint‎
Control external sharing.

‎Sway‎
Manage sharing and content sources allowed for ‎Sway‎.

User consent to apps
Choose whether users can consent to allow apps to access your organization's data.

User owned apps and services
Allow users to access the ‎Office Store‎ and ‎Microsoft 365‎ trials.

‎Viva Learning‎
Choose the content providers users can search through when using the ‎Viva Learning‎ in ‎Microsoft Teams‎.
‎Viva Sales‎
Manage and update ‎Viva Sales‎ settings.


‎Bing‎ data collection
Choose whether ‎Bing‎ can learn from your organization’s search behavior to better its results.

Customer lockbox
Set requirements for data access.

Idle session timeout
Automatically sign users out of the ‎Microsoft 365‎ web apps after a period of inactivity.

‎Microsoft Graph Data Connect‎ applications
Approve and deny requests from apps to access your organization's ‎Microsoft 365‎ data.

Password expiration policy
Set the password policy for all users in your organization.

Privacy profile
Set the privacy statement of your organization.

Privileged access
Set scoped access for privilege tasks and data access within your organization.

Pronouns
Allow all users in your organization to set their pronouns across ‎Microsoft 365‎.

Self-service password reset
Let users reset their own forgotten passwords rather than contacting your organization's IT for help.

Sharing
Control access for people outside your organization.

Data location
See where ‎Microsoft‎ stores your data for each service you use.

Help desk information
Streamline user support by adding customized contact info to the ‎Microsoft 365‎ help pane.

Keyboard shortcuts
Perform many common tasks using the keyboard. You can also see the full list of supported shortcuts by pressing Shift+? (question mark).

Organization information
Update your organization’s contact info, such as your address, phone number, and technical contact.

Release preferences
Choose how your organization gets new features and service updates from ‎Microsoft 365‎.

Send email notifications from your domain
Let ‎Microsoft‎ send notification messages from an email address within your organization instead of ‎Microsoft‎'s default external email address.

Support integration
Integrate your internal support tools with ‎Microsoft 365‎.

**Comment by andikrueger** [comment]
Do you know, which PowerShell commands could be used to configure these settings? We need function to get and set/update/create these settings. If you are aware of any, please share those with the documentation.

**Comment by maheshdalavi** [comment]
@andikrueger 
 I was not able to locate any PowerShell command.  But API can track it,...for how long ???? not sure. 
Example:
For "Bing Data Collection" we can query the below API.
("https://admin.microsoft.com/admin/api/settings/security/bingdatacollection"). 
Likewise, some automation was tried.

**Comment by NikCharlebois** [comment]
There are no APIs available for these settings and unfortunately cannot be automated via M365DSC. We are aware of this unfortunate situation. I am aware of some teams working on APIs for **some** of the settings you listed above. We will make sure those get integrated as part of M365DSC as they become available.

**Comment by andikrueger** [comment]
linking #2332 to keep track of these feature requests.
