### ISSUE TITLE
Unable to run unit-tests

### ISSUE THREAD

**Issue by salbeck-sit** [microsoft/Microsoft365DSC#3308]
I've been busy elsewhere and haven't been running unit-tests for a while, so I wanted to see what it looks like today.
I'm running the Dev-version of Microsoft365DSC and have forked the repo to my own and cloned that to a machine where I run tests.
When running 'Invoke-TestHarness', I got an exception for each and every resource just like this:

ImportCimAndScriptKeywordsFromModule : A second CIM class definition for 'MSFT_AADAdministrativeUnit' was found while p
rocessing the schema file 'C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.510.1\DSCResources\MSFT_AADA
dministrativeUnit\MSFT_AADAdministrativeUnit.Schema.mof'. This class was already defined in the file(s) 'C:\Users\MYACCOUNT\Documents\Github\Microsoft365DSC\modules\Microsoft365DSC\DSCResources\MSFT_AADAdministrativeUnit\MSFT_AADAdministrativeUnit.Schema.mof'. Remove the redundant definition, and then try again.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4143
 char:29
+ ...     $null = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], PSInvalidOperationException
    + FullyQualifiedErrorId : System.Management.Automation.PSInvalidOperationException,ImportCimAndScriptKeywordsFromM
   odule
   
So I started to play wih $env:PSModulePath. It made no difference if I switched the order so make the test-repo the first or last. Tests did start to work when the test-repo is the only folder in PSModulePath (Everything still works because I start out by manually importing dependency-modules before modifying PSModulePath). But the TestHarness.psm1 file hasn't been touch recently so this change shouldn't be necessary all of a sudden.

Version of module: Dev.
Machine: Windows 2019 Server, PS 5.1
 
I don't accept this as expected behavior and I'm sure that I'm doing something wrong. Any hints ?

**Comment by NikCharlebois** [comment]
This means you probably have another version of the M365DSC module hanging somewhere. Make sure you only ever have 1 version and that you don't have it installed in any other location.

**Comment by salbeck-sit** [comment]
Strange, this is not the first time I've run unit-tests while at the same time having the module 'installed' on the same machine.
I'll try to dig deeper and post results

**Comment by salbeck-sit** [comment]
Sorry, haven't had time to look into it further. I'll close the issue for now
