### ISSUE TITLE
Get-MgOrganizationSettingPersonInsight : User.Read or User.ReadWrite access scope required

### ISSUE THREAD

**Issue by titlerequired** [microsoft/Microsoft365DSC#3322]
#### Details of the scenario you tried and the problem that is occurring
Export-M365DSCConfiguration -Components @("O365AdminAuditLogConfig", "O365OrgCustomizationSetting", "O365OrgSettings", "O365SearchAndIntelligenceConfigurations") -ApplicationId $appId -TenantId $tenantID -CertificateThumbprint $thumbprint -ConfigurationName "Microsoft365" -Path "C:\DSC\Source\M365" -FileName ("Microsoft365",$fileName -join "-") -verbose

#### Verbose logs showing the problem
Get-MgOrganizationSettingPersonInsight : User.Read or User.ReadWrite access scope required.
At C:\Program Files\WindowsPowerShell\Modules\microsoft365dsc\1.23.517.1\DSCResources\MSFT_O365SearchAndIntelligenceCon
figurations\MSFT_O365SearchAndIntelligenceConfigurations.psm1:88 char:9
+         $PersonInsights = Get-MgOrganizationSettingPersonInsight -Org ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ OrganizationI...ndProperty =  }:<>f__AnonymousType81`3) [Get-MgOrga
   nizat...rsonInsight_Get], RestException`1
    + FullyQualifiedErrorId : Forbidden,Microsoft.Graph.PowerShell.Cmdlets.GetMgOrganizationSettingPersonInsight_Get

#### Suggested solution to the issue
Appears to be an issue when using Service Principal as scopes are not being set with connect-mggraph
"Get-MgOrganizationSettingPersonInsight -OrganizationId <org name>" command works fine if connecting using credentials.

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
ModuleType Version    Name                             
Manifest   1.23.517.1 microsoft365dsc

**Comment by NikCharlebois** [comment]
Related to #3382. Merging threads.
