### ISSUE TITLE
All TeamsResources + App Authentication: Export not possible

### ISSUE THREAD

**Issue by andikrueger** [microsoft/Microsoft365DSC#3327]
With V 1.23.517.1 we introduced Teams PowerShell in Version 5.2. This module version breaks to ability to export teams components with  application authentication.

Possible Solution:

Downgrade to Teams 5.1 or wait for a fix of the Teams PowerShell Module.

**Comment by NikCharlebois** [comment]
@andikrueger not sure this is really broken....the export works just fine and we haven't received any report of this module (which has been published 20+ days ago) breaking SPN auth. Can you please confirm whether or not you are still getting the error? Thanks

**Comment by andikrueger** [comment]
Will run a new export. Last time I tried, it failed.

**Comment by NikCharlebois** [comment]
@andikrueger any updates? Thanks

**Comment by andikrueger** [comment]
Actually not. Haven’t had time yet. I would close the issue for now and reopen if this is a real issue.
