### ISSUE TITLE
Does the Microsoft365DSC works in china

### ISSUE THREAD

**Issue by RicarPereira** [microsoft/Microsoft365DSC#3334]
Hi there,
I am considering the Microsoft365DSC to "Taking a Snapshot of Existing Tenant", however i will need to use it also in China, but i cannot find any answer or subject regarding if it works there or is viable.
Can you guys help me?
Thanks.

**Comment by desmay** [comment]
There is logic built into authentication module that should handle tenants hosted in China. If you encounter an error while testing please posted in the issues list.

**Comment by NikCharlebois** [comment]
It does handle the 21ViaNet China cloud. where features don't exist, it should print out a warning letting the user know about the sovereign cloud's limitation. (e.g., Teams today).
