### ISSUE TITLE
SCProtectionAlert enforces Threshold param

### ISSUE THREAD

**Issue by martincaddick** [microsoft/Microsoft365DSC#3347]
DevBranch
SCProtectionAlert enforces a validation for a number between 3 and 2147483647.

<img width="601" alt="image" src="https://github.com/microsoft/Microsoft365DSC/assets/73564857/d7fd5b3f-3e0c-45e6-92a1-83c45100f66d">

Not all alerts have the threshold.
<img width="836" alt="image" src="https://github.com/microsoft/Microsoft365DSC/assets/73564857/5392fa08-0304-4374-981f-bd727892023a">

Job {6CE0040D-FE06-11ED-B9CE-6CA10054F074} : 
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x1. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [SCProtectionAlert]SCProtectionAlert-MIP AutoLabel simulation completed and Source Info is C:\Working\Target\MyComponent.ps1::17::9::SCProtectionAlert. Error Message is The PowerShell DSC resource '[SCProtectionAlert]SCProtectionAlert-MIP AutoLabel simulation completed' with SourceInfo 'C:\Working\Target\MyComponent.ps1::17::9::SCProtectionAlert' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details..

**Comment by NikCharlebois** [comment]
Could you provide additional information about the encountered issue? The Threshold parameter is not mandatory and can be omitted for alerts that don't define them. Thanks

**Comment by martincaddick** [comment]
related to #3224

**Comment by NikCharlebois** [comment]
Can this be closed then since we've had a fix pushed for 3224? Thanks

**Comment by martincaddick** [comment]
Close please
