### ISSUE TITLE
NewResourceName: Microsoft Intune - Endpoint Detection & Response

### ISSUE THREAD

**Issue by Ruthhl3ss** [microsoft/Microsoft365DSC#3349]
### Description

Hi,

Could you add the Endpoint Detection & Response as an option to export and import in the Microsoft 365 DSC module?

These are the policies that are not available in the module at the moment:
![chrome_rflDQIHVkm](https://github.com/microsoft/Microsoft365DSC/assets/47400512/e248024b-6f52-48c1-abff-34c9997c0ef0)

### Proposed properties

You can create multiple types of policies, and having them all exported would be nice.

**Comment by FabienTschanz** [comment]
@NikCharlebois 
If it's okay I'll take a look and try to implement it. Seems pretty straightforward, but no promises.
