### ISSUE TITLE
Teams Export is failing

### ISSUE THREAD

**Issue by NaveenRamakrish** [microsoft/Microsoft365DSC#3369]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by NaveenRamakrish** [comment]
Module Version: 1.23.517.1
![image](https://github.com/microsoft/Microsoft365DSC/assets/117987376/82fb82be-d60a-4e03-b44c-67d5cb9353b4)

**Comment by NikCharlebois** [comment]
We would need additional details here. Can you share the error in the log? Also, are you using Credentials to authenticate or a Service Principal? Thanks

**Comment by NaveenRamakrish** [comment]
> We would need additional details here. Can you share the error in the log? Also, are you using Credentials to authenticate or a Service Principal? Thanks

I am using credentials, Attaching the error logs 
[LogFile_09June2023.log](https://github.com/microsoft/Microsoft365DSC/files/11704556/LogFile_09June2023.log)

**Comment by NikCharlebois** [comment]
Looks like a licensing issue. Can you try the following and post the output?

``` powershell
$creds = Get-Credential -Message "Your credentials"
Connect-M365Tenant -Credential $creds -Workload SecurityComplianceCenter

Get-Command 'Get-AuditConfigurationPolicy'
```

Thanks

**Comment by NaveenRamakrish** [comment]
> ```powershell
> $creds = Get-Credential -Message "Your credentials"
> Connect-M365Tenant -Credential $creds -Workload SecurityComplianceCenter
> 
> Get-Command 'Get-AuditConfigurationPolicy'
> ```

Below is the result. 

![image](https://github.com/microsoft/Microsoft365DSC/assets/117987376/5293b491-a766-49ee-9086-4a1e3aa30028)

**Comment by NaveenRamakrish** [comment]
> Definitively looks like a licensing issue. What roles/licenses is the user you are connecting with assigned? Thanks

It has Global Reader Permission, I am using this module for the last 5 months and everything was working fine. It stopped working after May 18th, 2023. 

Can you let me know what has changed and what changes need to be done on our end?

-Naveen

**Comment by NikCharlebois** [comment]
Nothing has changed in the underlying module for the past 2 months. The error is not coming from M365DSC but from its underlying Exchange Online Management PowerShell module. The only other recommendation I would have would be for you to run Update-M365DSCModule and make sure you only have 1 instance of the ExchangeOnlineManagement module installed on the machine, or try the tool from another machine to see if you get different results.

**Comment by NaveenRamakrish** [comment]
> Nothing has changed in the underlying module for the past 2 months. The error is not coming from M365DSC but from its underlying Exchange Online Management PowerShell module. The only other recommendation I would have would be for you to run Update-M365DSCModule and make sure you only have 1 instance of the ExchangeOnlineManagement module installed on the machine, or try the tool from another machine to see if you get different results.

I understand, But the issue is only with Teams Services, the remaining services are getting exported without any issues. And in Teams Service I do see some components are getting exported without any issues and stop in the mid and not proceeding.

-Naveen

**Comment by NikCharlebois** [comment]
Got it, sorry I was looking at the wrong entry in the error log. Let's dive into the authentication stack here. Can you try the following two set of commands, each in separate PowerShell consoles and let me know if you get any errors?

#1
```powershell
$creds = get-Credential
Connect-M365Tenant -Workload MicrosoftTeams -Credential $creds
Get-CsTeamsAppPermissionPolicy
```

#2
```powershell
$creds = get-Credential
Connect-MicrosoftTeams -Credential $Creds
Get-CsTeamsAppPermissionPolicy
```

**Comment by NaveenRamakrish** [comment]
> ```powershell
> ```powershell
> $creds = get-Credential
> Connect-M365Tenant -Workload MicrosoftTeams -Credential $creds
> Get-CsTeamsAppPermissionPolicy
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> #2
> ```powershell
> $creds = get-Credential
> Connect-MicrosoftTeams -Credential $Creds
> Get-CsTeamsAppPermissionPolicy
> ```
> ```

I didnt get any error, I was able to execute the command successfully.  When I execute any export configuration command it gives the errors mentioned in the screenshot.

Export-M365DSCConfiguration -ConfigurationName SPOTenantSettings -Credential $Credential -FileName C:\temp\SPO_Test.ps1 -Verbose

![image](https://github.com/microsoft/Microsoft365DSC/assets/117987376/2acbc257-5e51-422a-9f20-3961626d38b4)

**Comment by NaveenRamakrish** [comment]
Please close this issue, Issue got resolved after reinstall the module.
