### ISSUE TITLE
Exporting failed on developer account

### ISSUE THREAD

**Issue by kami-delaroz** [microsoft/Microsoft365DSC#3372]
I'm new with Microsoft365DSC. I created a Microsoft developer account and wand to export some configurations.
I followed the [How to Install](https://microsoft365dsc.com/user-guide/get-started/how-to-install/) guide, but when trying to export configuration I receive various errors in various stages, depends on the configurations I'm trying to export.
When trying to export only AzureADUsers for example, I got the error
Microsoft.Graph.PowerShell.Runtime.RestException`1[Microsoft.Graph.PowerShell.Models.IMicrosoftGraphODataErrorsOdataError]: Insufficient privileges to complete the operation
I guess it's somehow related to missing steps in [Authentication and Permissions](https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/), but I couldn't figure out what

**Comment by NikCharlebois** [comment]
Skipping a few steps, but try running the following commands:

``` powershell
Connect-MGGraph -Scopes ((Get-M365DSCCompiledPermissionList -ResourceNameList (Get-M365DSCAllResources)
 -PermissionType Application -AccessType Update) | Where-Object -FilterScript {$_.API -eq 'Graph'}).PermissionName
```

**Comment by NikCharlebois** [comment]
This will:

1 - Retrieve all resources in the project
2 - Retrieve the associated permissions for it
3 - Keep only the Graph related permissions
4 - Grant the permissions to the Microsoft Graph PowerShell SDK

It will prompt you to connect and to grant consent, but once done, try running the export again in a new PowerShell console.

**Comment by kami-delaroz** [comment]
Thanks! it did work, and now I'm getting another exception on the next step. 
while trying to export the first user, I've got:
`System.Management.Automation.CommandNotFoundException: The term 'Get-DscResource' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`
I'm not sure if it's related, but I also got a warning at the beginning of the run:
`MethodInvocationException: Exception calling "LoadFile" with "1" argument(s): "Could not load file or
assembly
'/Users/<user-name>/.local/share/powershell/Modules/Microsoft365DSC/1.23.517.1/modules
\..\Dependencies\Microsoft.ApplicationInsights.dll'. The system cannot find the
file specified."`
and copying the dependencies directory also into the modules directory didn't help. The path is broken, could be related to the fact I'm running on a macOS (?)

**Comment by andikrueger** [comment]
At the moment, M365DSC runs best in a Windows PowerShell 5 Session. We are working on support for PowerShell 7 and other sub-systems. Still, there are dependencies due to the other modules used in M365DSC that are not 100% cross-platform ready.

**Comment by NikCharlebois** [comment]
For details on how to run it with PowerShell 7, please refer to:

https://microsoft365dsc.com/user-guide/get-started/powershell7-support/
