### ISSUE TITLE
O365SearchAndIntelligenceConfigurations component permissions

### ISSUE THREAD

**Issue by PierreColyn** [microsoft/Microsoft365DSC#3382]
When I try to run the O365SearchAndIntelligenceConfigurations component with a certificate thumbprint I get the following error:

_"The role assigned to application <app id>  isn't supported in this scenario. Please check
online documentation for assigning correct Directory Roles to Azure AD Application for EXO App-Only Authentication.
At C:\Program
Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\3.1.0\netFramework\ExchangeOnlineManagement.psm1:733 char:21;"_

The online documentation does not state any permissions to add to the app registration:
https://microsoft365dsc.com/resources/office365/O365SearchAndIntelligenceConfigurations/#permissions

When using the Get-M365DSCCompiledPermissionList command, the following permissions are returned:

Graph      -read  - Application  - User.Read.All
Exchange   -read  - Application  - Exchange.ManageAsApp
(No EXO roles specified)

Please confirm what application permissions and roles are required for this component.

**Comment by NikCharlebois** [comment]
Looks like I am also able to repro. Interestingly enough, the only listed permission for it on the official documentation, based on the underlying API, is User.Read.All:

https://learn.microsoft.com/en-us/graph/api/organizationsettings-list-iteminsights?view=graph-rest-beta&tabs=http

I will investigate this further.

**Comment by NikCharlebois** [comment]
Looks like the issue is related to App-Only permissions not supported in this case. The API would require Credentials to work. We will bring this up with the team internally. In the meantime, the unfortunate workaround is to use Credentials instead of SPN.

**Comment by raandree** [comment]
I am not sure if this case really does not support service principals. We use managed identities and creating a connection to Exchange Online always worked. We faced other issues when trying to write transport configs, I will create a separate issues for that.

While troubleshooting our issue we deleted the managed identity in the Dev environment and created a new one. Since the we get the same problem as above:

```powershell
New-M365DSCConnection -Workload 'ExchangeOnline' -InboundParameters @{ ManagedIdentity = $true; TenantId = 'dev.onmicrosoft.com' }
```

```
The role assigned to application 0c9a65e2-e72d-4cc6-80a1-9d2d34bb48d8 isn't supported in this scenario. Please check online documentation for assigning correct Directory Roles to Azure AD Application for EXO App-Only Authentication.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\3.1.0\netFramework\ExchangeOnlineManagement.psm1:733 char:21
+                     throw $_.Exception;
+                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], SystemException
    + FullyQualifiedErrorId : The role assigned to application 0c9a65e2-e72d-4cc6-80a1-9d2d34bb48d8 isn't supported in this scenario. Please check online documentation for assigning correct Directory Roles to Azure AD Application for EXO App-Only Authentication.
```

In the Test environment we still have the managed identity that we created about a month ago. There the connection works

```powershell
New-M365DSCConnection -Workload 'ExchangeOnline' -InboundParameters @{ ManagedIdentity = $true; TenantId = 'test.onmicrosoft.com' }
```

```
ManagedIdentity
```

Reading the transport config works as expected.

What has changed that a newly created managed identity with the same permissions does not work at all anymore?

**Comment by ykuijs** [comment]
Updating required permissions in documentation via PR #3636

**Comment by Laul0** [comment]
Hi,
I tried this super blog post and it works: https://blog.icewolf.ch/archive/2023/01/19/exchange-online-custom-rbac-role-with-app-authentication-oauth2/

The deal: Create an Exchange Service Principal based on your AzApp
