### ISSUE TITLE
PowerShell DSC resource MSFT_TeamsGuestMeetingConfiguration  failed to execute Test-TargetResource functionality with   error message

### ISSUE THREAD

**Issue by awsayad** [microsoft/Microsoft365DSC#3405]
The Meeting Settings in our Teams Admin center were changed recently and we tried to revert the changes back by calling the .MOF file from a week before using the DSC CmdLet `Start-DscConfiguration -Path C:\DSC\M365TenantConfig -Wait -Verbose -force` but we're getting the following error:

`PowerShell DSC resource MSFT_TeamsGuestMeetingConfiguration  failed to execute Test-TargetResource functionality with   error message: One or more errors occurred.                                                                                 + CategoryInfo          : InvalidOperation: (:) [], CimException                                                        + FullyQualifiedErrorId : ProviderOperationExecutionFailure                                                             + PSComputerName        : localhost`

Modules and Dependies are up to date and Winrm is already running and set up for remote management.

![DSC error page1](https://github.com/microsoft/Microsoft365DSC/assets/49615118/f5abc403-be63-4d9f-85a1-5f2d933f6ebf)
![DSC error page2](https://github.com/microsoft/Microsoft365DSC/assets/49615118/daa940d3-09e3-4deb-8225-8926315b78b4)

**Comment by andikrueger** [comment]
Could you share the exception that is logged into the m365dsc event log?

**Comment by awsayad** [comment]
@andikrueger I can't find anything in Event Viewer for M365DSC! I looked under al these folders to no avail

![Event viewer](https://github.com/microsoft/Microsoft365DSC/assets/49615118/d9d23f2c-a6d4-46ef-b52e-f0007d750505)

**Comment by NikCharlebois** [comment]
Could you share the redacted configuration file you are using for this test? Thanks

**Comment by NikCharlebois** [comment]
Thanks for providing your config. We are not able to replicate this on our end as the configuration deploys successfully. Could you send a screenshot of how the Guest Configuration settings are **currently** configured on your environment, before you attempt to run the file and get the error? Thanks

**Comment by andikrueger** [comment]
@awsayad  any chance to provide the further requested information ? Thanks!

**Comment by awsayad** [comment]
This issue was resolved by reinstalling all PowerShell modules. Having two different DSC modules was most likely the cause of the issue!
Thank you for your response.
