### ISSUE TITLE
IntuneApplicationControlPolicyWindows10: Cannot deploy if Assignments property is not empty

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#3437]
#### Details of the scenario you tried and the problem that is occurring

After exporting a resource of type IntuneApplicationControlPolicyWindows10 from my tenant which has Assignments (inclusion and exclusion) it then fails to deploy to another tenant. The MOF file looks perfectly normal and the Assignments property is generated correctly, but it just fails for some reason during deployment unless Assignments is not defined.

Note that redeploying to the same tenant doesn't fail since *Test-TargetResource returned True*

#### Verbose logs showing the problem

```powershell
Cannot process argument transformation on parameter 'Target'. Cannot convert the "MSFT_DeviceManagementConfigurationPolicyAssignments" value of type
"Microsoft.Management.Infrastructure.CimInstance#MSFT_DeviceManagementConfigurationPolicyAssignments" to type "System.Collections.Hashtable".
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Compare-M365DSCComplexObject
    + PSComputerName        : localhost
```

#### Suggested solution to the issue

None at the moment, the schema is correct so most likely the issue is triggered from one of the sub-functions included in the module that handle complex properties

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# Generated with Microsoft365DSC version 1.23.628.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $Credential
)

Configuration AppControl
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $Credential
    )

    if ($null -eq $Credential)
    {
        <# Credentials #>
        $Credscredential = Get-Credential -Message "Credentials"

    }
    else
    {
        $CredsCredential = $Credential
    }

    $OrganizationName = $CredsCredential.UserName.Split('@')[1]

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.23.628.1'

    Node localhost
    {
        IntuneApplicationControlPolicyWindows10 "IntuneApplicationControlPolicyWindows10-REDACTED"
        {
            AppLockerApplicationControl      = "auditComponentsStoreAppsAndSmartlocker";
            Assignments                      = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    groupId = 'REDACTED'
                }
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.exclusionGroupAssignmentTarget'
                    groupId = 'REDACTED'
                }
            );
            Credential                       = $Credscredential;
            DisplayName                      = "REDACTED";
            Ensure                           = "Present";
            SmartScreenBlockOverrideForFiles = $False;
            SmartScreenEnableInShell         = $True;
        }
    }
}

AppControl -ConfigurationData .\ConfigurationData.psd1 -Credential $Credential
```

#### The operating system the target node is running

Win10

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.23.628.1

**Comment by William-Francillette** [comment]
@ricmestre, are you using the latest version using Graph SDK v2.0? If yes I've noticed a few issues when merging my PR with the latest versions

Please be patient with me and I will correct those issues very soon

**Comment by ricmestre** [comment]
@William-Francillette The module reaches beta endpoint but I'm actually using Graph v1.28 pinned to latest M365DSC release 1.23.628.1.

**Comment by William-Francillette** [comment]
ok thanks I check that asap

**Comment by ricmestre** [comment]
Please update label to V1.23.705.1 since it also fails with latest version, tested it locally (not DevOps) with cert-based auth and credentials.

**Comment by andikrueger** [comment]
@ricmestre Is this still an issue? @William-Francillette Could you have a look at this one, if this still occurs.

**Comment by ricmestre** [comment]
I'm running on latest version and now it seems to be working! thanks!
