### ISSUE TITLE
M365DSC Report seems to be incomplete in HTMP,  Excel and JSON

### ISSUE THREAD

**Issue by MartinWeberSwitzerland** [microsoft/Microsoft365DSC#3443]
#### Details of the scenario you tried and the problem that is occurring
When I'm exporting the (full) config  into a report, there seems  to be a lot of thins missing.
This is the case with all reports (Excel, HTML, json). The Reports got created, but many things are missing...! 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell

$Path = "C:\Users\TheBoss\Desktop\M365DSC-Testing"
$Credentials = Get-Credential

Install-Module -Name Microsoft365DSC -AllowPreRelease -Force -AllowClobber
Import-Module Microsoft365DSC -Force

Update-M365DSCDependencies

Get-Module Microsoft365DSC -ListAvailable | select ModuleBase, Version

#MS Teams Only
Export-M365DSCConfiguration -Credential $Credentials -Path $Path -FileName "M365DSC-ITi4U-Export-MSTeamsONLY.ps1" -MaxProcesses 64 -Components @("TeamsAppPermissionPolicy", "TeamsAppSetupPolicy", "TeamsAudioConferencingPolicy", "TeamsCallHoldPolicy", "TeamsCallingPolicy", "TeamsCallParkPolicy", "TeamsCallQueue", "TeamsChannel", "TeamsChannelsPolicy", "TeamsChannelTab", "TeamsClientConfiguration", "TeamsComplianceRecordingPolicy", "TeamsCortanaPolicy", "TeamsDialInConferencingTenantSettings", "TeamsEmergencyCallingPolicy", "TeamsEmergencyCallRoutingPolicy", "TeamsEnhancedEncryptionPolicy", "TeamsEventsPolicy", "TeamsFederationConfiguration", "TeamsFeedbackPolicy", "TeamsFilesPolicy", "TeamsGroupPolicyAssignment", "TeamsGuestCallingConfiguration", "TeamsGuestMeetingConfiguration", "TeamsGuestMessagingConfiguration", "TeamsIPPhonePolicy", "TeamsMeetingBroadcastConfiguration", "TeamsMeetingBroadcastPolicy", "TeamsMeetingConfiguration", "TeamsMeetingPolicy", "TeamsMessagingPolicy", "TeamsMobilityPolicy", "TeamsNetworkRoamingPolicy", "TeamsOnlineVoicemailPolicy", "TeamsOnlineVoicemailUserSettings", "TeamsOnlineVoiceUser", "TeamsOrgWideAppSettings", "TeamsPstnUsage", "TeamsShiftsPolicy", "TeamsTeam", "TeamsTenantDialPlan", "TeamsTenantNetworkRegion", "TeamsTenantNetworkSite", "TeamsTenantNetworkSubnet", "TeamsTenantTrustedIPAddress", "TeamsTranslationRule", "TeamsUnassignedNumberTreatment", "TeamsUpdateManagementPolicy", "TeamsUpgradeConfiguration", "TeamsUpgradePolicy", "TeamsUser", "TeamsUserCallingSettings", "TeamsVdiPolicy", "TeamsVoiceRoute", "TeamsVoiceRoutingPolicy", "TeamsWorkloadPolicy")

#MS Teams Only
New-M365DSCReportFromConfiguration -Type HTML  -ConfigurationPath $Path\M365DSC-ITi4U-Export-MSTeamsONLY.ps1 -OutputPath $Path\ITi4U-Export-MSTeamsOnly.html
```

#### The operating system the target node is running
<!--
    Please provide as much as possible about the target node, for example
    edition, version, build and language.
    On OS with WMF 5.1 the following command can help get this information.

OsName               : Microsoft Windows 11 Pro for Workstations
OsOperatingSystemSKU : 161
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}

#### Version of the DSC module that was used ('dev' if using current dev branch)
ModuleBase                                                            Version   
----------                                                            -------   
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.628.1 1.23.628.1
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.615.1 1.22.615.1

```[tasklist]
### Tasks
```

**Comment by NikCharlebois** [comment]
Can you share the redacted configuration you are using for us to investigate? Thanks

**Comment by andikrueger** [comment]
Thanks for the additional information. I'll do some testing and will get back to you. Could you please delete the html file and the configuration file as they hold plenty of user information of your tenant.

**Comment by andikrueger** [comment]
Right now, there about 4293 parameters that can be managed by Microsoft 365 DSC. Any setting, that can be managed by M365DSC, needs to be available through an official API offering - best case within the Microsoft Graph PowerShell module. There are many improvements happening and we try to support any available setting within these modules. 

I’ll run a test with your configuration and let you know.

**Comment by andikrueger** [comment]
Just ran a test with the latest dev-branche version. I was able to generate a complete report. If there was an issue with V1.23.628.1, it's going to be fixed with the next release.

Top: Your html file, 
Bottom: mine

![image](https://github.com/microsoft/Microsoft365DSC/assets/15608729/0827ca59-5fe2-4681-a081-165c7f533f59)

Below a screenshot for the generated html.

![image](https://github.com/microsoft/Microsoft365DSC/assets/15608729/b4f4bbdf-66bc-4e6b-9c5e-bba34c274093)


Could you try to run 

```
Update-M365DSCDependencies
Uninstall-M365DSCOutdatedDependencies
```

to make sure there are no version conflicts within your system? Maybe this solves the issue for V1.23.628.1

**Comment by andikrueger** [comment]
Just reviewed the release notes and there were noch changes to the reporting function included with today’s release:

https://github.com/microsoft/Microsoft365DSC/releases/tag/1.23.705.1

Please run the cmdLet above or if you want to use the new release: Update-M365DSCModule

**Comment by MartinWeberSwitzerland** [comment]
Hi there Andy & Team,

Thanks for the hints and help. 
Maximum Kudos to You and the Team...!! :-)

I've been running the "MS Teams Only M365DSC Export Report" successfully using the two lines (as you mentioned) in the script:
Update-M365DSCDependencies
Uninstall-M365DSCOutdatedDependencies

Right now, I'm running the "Full AAD Config Export Report" and hopefully, that runs smooth as well...! :-)
It's still throwing a few errors around AAD, but for now, this is ok for me.

Thanks again for your support & help and have a great Week-End...
Martin
