### ISSUE TITLE
WARNING: Falling back to the previous MOF file or system defaults because the meta configuration mof does not exist or has either been corrupted or an invalid mof property has been set.

### ISSUE THREAD

**Issue by peterjameson11** [microsoft/Microsoft365DSC#3466]
I'm hoping someone can help me with this. I'm trying to pull a configuration with Export-M365DSCConfiguration, which seems to work. However, once I compile the ps1 file and then try to push the same configuration I receive the "WARNING: Falling back to the previous MOF file or system defaults because the meta configuration mof does not exist or has either been corrupted or an invalid mof property has been set." message. I've tried this on two separate machines and two separate tenants. Im sure I'm doing something incorrectly put I don't know what what. It doesn't matter which config I try I get the same results. 

1.23.621.1 Microsoft365DSC 

Please find the MOF file below. 

/*
@TargetNode='localhost'
@GeneratedBy=PJameson
@GenerationDate=07/12/2023 08:00:15
@GenerationHost=UKGU-00372
*/

instance of MSFT_AADTenantDetails as $MSFT_AADTenantDetails1ref
{
ResourceID = "[AADTenantDetails]AADTenantDetails";
 MarketingNotificationEmails = {
    "test.account@primvigilance.com"
};
 CertificateThumbprint = "EX9D1D2D390CA5CFAB60C4CA98AD31A721DEBB3X";
 ApplicationId = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
 SecurityComplianceNotificationMails = {
    "test.account@primvigilance.com"
};
 TechnicalNotificationMails = {
    "test.account@primvigilance.com"
};
 SourceInfo = "C:\\M365DSC\\M365TenantConfig.ps1::17::9::AADTenantDetails";
 TenantId = "ErgmedDevTest.onmicrosoft.com";
 IsSingleInstance = "Yes";
 ModuleName = "Microsoft365DSC";
 SecurityComplianceNotificationPhones = {
    "07904624442"
};
 ModuleVersion = "1.23.621.1";
 ConfigurationName = "M365TenantConfig";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";
 
                        MinimumCompatibleVersion = "1.0.0";
 
                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
 
                        Author="PJameson";
 
                        GenerationDate="07/12/2023 08:00:15";
 
                        GenerationHost="UKGU-00372";
 
                        Name="M365TenantConfig";

                    };

**Comment by andikrueger** [comment]
This is more likely, that there is an issue with the LCM configuration. The LCM depends on a meta.mof file.

Could you run 

```powershell

Get-DscLocalConfigurationManager

```

and share the output?

If there are any issues with this command you need to create localhost.meta.mof file to setup your machine.

Please have a look at this article: https://learn.microsoft.com/en-us/powershell/dsc/managing-nodes/metaconfig?view=dsc-1.1

**Comment by peterjameson11** [comment]
Thanks, I'll have read through this. In the meantime here is the output from Get-DscLocalConfigurationManager

ActionAfterReboot              : ContinueConfiguration
AgentId                        : 7ACCCA46-F3D5-11ED-BE50-B4B5B6A44262
AllowModuleOverWrite           : False
CertificateID                  : 
ConfigurationDownloadManagers  : {}
ConfigurationID                : 
ConfigurationMode              : ApplyAndMonitor
ConfigurationModeFrequencyMins : 15
Credential                     : 
DebugMode                      : {NONE}
DownloadManagerCustomData      : 
DownloadManagerName            : 
LCMCompatibleVersions          : {1.0, 2.0}
LCMState                       : PendingConfiguration
LCMStateDetail                 : 
LCMVersion                     : 2.0
StatusRetentionTimeInDays      : 10
SignatureValidationPolicy      : NONE
SignatureValidations           : {}
MaximumDownloadSizeMB          : 500
PartialConfigurations          : 
RebootNodeIfNeeded             : False
RefreshFrequencyMins           : 30
RefreshMode                    : PUSH
ReportManagers                 : {}
ResourceModuleManagers         : {}
PSComputerName                 :

**Comment by andikrueger** [comment]
You could also try to run this cmdLet: `Remove-DscConfigurationDocument -Stage Pending`

**Comment by peterjameson11** [comment]
Thanks so much for the help. Once I created and applied a MOF file for my LCM configuration I no longer receive this error. :)

**Comment by peterjameson11** [comment]
Thanks so much for the help. Once I created and applied a MOF file for my LCM configuration I no longer receive this error. :)
