### ISSUE TITLE
Update-M365DSCAzureAdApplication: either the  documentation or the command are broken

### ISSUE THREAD

**Issue by apcsb** [microsoft/Microsoft365DSC#3487]
The docs page "Authentication and Permissions"
https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/

shows an example:

`Update-M365DSCAzureAdApplication -ApplicationName 'Microsoft365DSC' -Permissions @(@{Api='SharePoint';PermissionName='Sites.FullControl.All'}) -AdminConsent -Type Certificate -CreateSelfSignedCertificate -CertificatePath c:\Temp\M365DSC.cer`

Running this command yields
```
You must specify either the Credential or ApplicationId, TenantId and CertificateThumbprint parameters.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.712.1\modules\M365DSCUtil.psm1:1730 char:9
+         throw $errorText
+         ~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (You must specif...int parameters.:String) [], RuntimeException
    + FullyQualifiedErrorId : You must specify either the Credential or ApplicationId, TenantId and CertificateThumbpr
   int parameters.

```

Reading the docs on the CMDlet shows different examples
https://microsoft365dsc.com/user-guide/cmdlets/Update-M365DSCAzureAdApplication/

But those examples do not show many possible scenarios (thumbprint?), do not explain that TenantID is actually Tenant Name (??!! why isn't it called TenantName or TenantDomain then?), and the "Description" column for the parameters is empty.

Furthermore, when I got this CMDlet to run (by giving it a Global Admin account credential using Get-Credential) I got prompted for auth second time (why?), consented to permissions for the Graph Command Line Tools AAD app  and then got a bunch or errors, indicating that the required Graph permissions were not requested

```
Get-MgServicePrincipal : Insufficient privileges to complete the operation.
Status: 403 (Forbidden)
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.712.1\modules\M365DSCPermissions.psm1:1398 char:5
+     $graphSvcprincipal = Get-MgServicePrincipal -Filter "AppId eq '$r ...
```

```
Get-MgServicePrincipal : Insufficient privileges to complete the operation.
Status: 403 (Forbidden)
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.712.1\modules\M365DSCPermissions.psm1:1399 char:5
+     $spSvcprincipal = Get-MgServicePrincipal -Filter "AppId eq '$reso ...
```

```
Get-MgServicePrincipal : Insufficient privileges to complete the operation.
Status: 403 (Forbidden)
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.712.1\modules\M365DSCPermissions.psm1:1400 char:5
+     $exSvcprincipal = Get-MgServicePrincipal -Filter "AppId eq '$reso ...
```

```
**New-MgApplication** : Insufficient privileges to complete the operation.
Status: 403 (Forbidden)
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.712.1\modules\M365DSCPermissions.psm1:1406 char:9
+         $azureADApp = New-MgApplication -DisplayName $ApplicationName
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ body = Micros...phApplication }:<>f__AnonymousType1`1) [New-MgAppli
   cation_CreateExpanded], Exception
    + FullyQualifiedErrorId : Authorization_RequestDenied,Microsoft.Graph.PowerShell.Cmdlets.NewMgApplication_CreateEx
   panded

```
I could work around this by manually issuing Connect-MgGraph -Scopes 'Application.ReadWrite.All' in the same PowerShell session before running the Update-M365DSCAzureAdApplication.

I could not find anywhere in the docs that I need to run this command for an app registration. I see that there is Update-M365DSCAllowedGraphScopes, but it is only listed in the "Delegated Permissions" section, whereas I am following the Application Permissions path.

I'll be happy to submit a pull request for the docs, but first I'd like to know which of the above is a bug, and which is a feature.

Also, It is essential that you specify the Certificate parameters right in the docs (or link to the AAD page for Certificate-Based auth for service principals). Nice to have them in PowerShell CMDlet and learn of restrictions *after* having created the certificate.
Here are good Docs pages candidates to refer to that I have found so far:
* https://learn.microsoft.com/en-us/graph/applications-how-to-add-certificate?tabs=http#step-2-add-the-certificate-details-using-microsoft-graph
* https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-authenticate-service-principal-powershell

BTW, the Tutorial to Integrate with Azure DevOps has all the same issues (and even more - it misses totally critical steps, but I will create a separate issue on this and/or a Pull Request with fixes once I figure it out).

Cheers.

**Comment by andikrueger** [comment]
The docs refer to the previous implementation of the cmdlet which used the AZ module back then. With V1.23.614.1 the cmdLet got  moved to Graph modules.

Creating an App for M365DSC is fairly simple now:

```powershell

$ApplicationName = ""
$CertificatePath = "" 
$Credential = Get-Credential 

 $allResources = Get-M365DSCAllResources

    $allPermissions = Get-M365DSCCompiledPermissionList -ResourceNameList $allResources -PermissionType Application -AccessType Read

    Update-M365DSCAzureAdApplication -ApplicationName $ApplicationName `
        -Permissions $allPermissions `
        -Type Certificate `
        -CreateSelfSignedCertificate `
        -AdminConsent `
        -CertificatePath $CertificatePath `
        -MonthsValid 12 `
        -Credential $Credential

```

**Comment by apcsb** [comment]
@andikrueger

OK, so after a while here's what I could figure out. Here is what I am using.
```
$ApplicationName = "DSCtest"
$CertificatePath = (Resolve-Path -Path ".").ToString() + "\" + $ApplicationName + ".cer"

$Credential = Get-Credential 
$allResources = Get-M365DSCAllResources
$allPermissions = Get-M365DSCCompiledPermissionList -ResourceNameList (Get-M365DSCAllResources) -AccessType Update -PermissionType Application
```

First time I run the Update-M365DSCAzureAdApplication just like you provided (BTW, you don't need **-MonthsValid 12**, it is the default value), it works.

Then if I do **Disconnect-MgGraph** and try the command again - I get all those 403 errors I have described.
It's almost as if the connection to Graph is skipped.
Try it.
The only solution I see for now is to end the PowerShell session. 

 
2. In case of **-CreateSelfSignedCert** the cert lands in User Store instead of machine store (PowerShell ran as admin, of course). As far as I understand, if DSC runs under a service account, this store will not be accessible, right? Or doesn't matter?

3. My use case requires using an existing cert anyway. So I do this:

```
$Cert = New-SelfSignedCertificate -CertStoreLocation 'Cert:\CurrentUser\My' `
                            -Subject "CN=$ApplicationName" `
                            -KeySpec Signature `
                            -NotAfter (Get-Date).AddMonths(12) `
                            -KeyLength 2048 `
                            -KeyAlgorithm RSA `
                            -HashAlgorithm SHA256

Export-Certificate -Cert $Cert -Type CERT -FilePath $CertificatePath

 Update-M365DSCAzureAdApplication -ApplicationName $ApplicationName `
        -Permissions $allPermissions `
        -Type Certificate `
        -AdminConsent `
        -CertificatePath $CertificatePath `
        -Credential $Credential
```
Here's what I get then (trimmed)
```
2023-07-19 22:56:13 - Checking app credentials
2023-07-19 22:56:13 -   Uploading App Certificate
2023-07-19 22:56:13 -     Certificate details: CN=DSCtest2 (EAA27B06A8FEE80B05311361FAEC692C8B55B030)
Update-MgApplication : Key credential end date is invalid.
Status: 400 (BadRequest)
ErrorCode: KeyCredentialsInvalidEndDate
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.712.1\modules\M365DSCPermissions.psm1:1677 char:29
+ ...             $appCred = Update-MgApplication -ApplicationId $azureAdAp ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```


I suspect it may be because in M365DSCPermissions.psm1 on line 1666 when you create the params hash for cert auth you have
```
EndDateTime = $endDate
```
And the $endDate is defined previously as **$endDate = (Get-Date).AddMonths($MonthsValid)** [Line 1566]

Thus, when later this is called [Line 1677]
```
$appCred = Update-MgApplication -ApplicationId $azureAdApp.Id -KeyCredentials $params
```
instead of submitting the end date from the cert, you are submitting the current date (which will definitely be > 1 year from the Cert NotBefore date for obvious reasons :) )

I fixed it by changing the line 1666 to
```
EndDateTime = $cerCert.NotAfter
```

This way it works fine.

Looks like we deal with multiple issues here?

**Comment by andikrueger** [comment]
Yes, there are multiple issues. I updated the docs and would investigate the issues you mentioned. 

Very good point about the first run scenario in a new tenant and about certificate processing.

**Comment by apcsb** [comment]
I think I've figured it out for the permissions issues. It required some tracing
The **Update-M365DSCAzureAdApplication** CMDlet uses the **New-M365DSCConnection** function, which in turn uses the **Connect-M365Tenant** function, which is part of the **MSCloudLoginAssistant** module (written by Nick).

There we see:
```
# Only validate the parameters if we are not already connected
    elseif ( $Global:MSCloudLoginConnectionProfile.$workloadInternalName.Connected `
            -and (Compare-InputParametersForChange -CurrentParamSet $PSBoundParameters))
    {
        Write-Verbose -Message 'Resetting connection profile'
        $Global:MSCloudLoginConnectionProfile.$workloadInternalName.Connected = $false
    }

```

So basically, the decision to skip connection is based not on the actual status of the connection to the workload is based not on a real-time check, but a cached (static) variable. One can disconnect/timeout etc, but the scripts will not know.
This may be a bug or a conscious design decision - I don't have enough data to judge, but if it's how it should be - please include a note in the docs somewhere. It will help, I believe.

Some other notes:
1. I've found it confusing (w/o reading the source code) to understand that **CertificateThumbprint** is about a thumb of an already uploaded cert that **you are using to authenticate right now**, while **CertificatePath** is about a certificate that **you will use later**.  
2. The TenantId (which is tenant name) has a check for ".onmicrosoft." in the source code and will throw errors otherwise. Would be nice to document that too.
3. When using **-CreateSelfSignedCertificate** the **-CertificatePath** must leard to a **non-existent** file (which will be created), whereas when not using this option, it must lead to an **existing** file (to be uploaded). I understand how and why this happened, but this case of a "parameter overload" with a 180 degree flip is counter-intuitive, unless explicitly called out in the docs. Or, better, just completely drop this parameter when creating a self-signed cert and use a file name generated from CN or ApplicationName (stripped down from special characters/spaces/etc).
4. This is probably more along the feature request, but would be nice for this CMDlet to return the application ID / objectID (as well as the cert file name if it was created, which may be a more elegant solution to No 3). I am currently trying to streamline the Azure DevOps guide by scripting most of the manual steps, and have to manually look up the application (not that it's a huge deal, but nevertheless).

Thanks for enduring me :)

**Comment by andikrueger** [comment]
Your feedback is greatly appreciated. 

Have you had a chance to look into #3488 ?

I’ll add your further feedback into the documentation.

**Comment by apcsb** [comment]
I looked into it and left some comments/suggestions. Sorry if messy - I don't have much experience with GitHub, Markdown and the whole OpenSource process (yet) :)
