### ISSUE TITLE
AzureDevOps integration error inside deploy.ps1

### ISSUE THREAD

**Issue by michaelbaltes** [microsoft/Microsoft365DSC#3494]
Hello
I  follow the instruction of your whitepaper to integrate M365Dsc in azuredevops (https://office365dsc.azurewebsites.net/Pages/Resources/Whitepapers/Managing%20Microsoft%20365%20with%20Microsoft365Dsc%20and%20Azure%20DevOps.pdf)

Now - It will be finish, but I get this error when I deploy the Release pipeline first time:

The term 'Set-AtpPolicyForO365' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Set-AtpPolicyForO365:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost
The PowerShell DSC resource '[EXOAtpPolicyForO365]ATPPolicy::[Exchange]Exchange_Configuration' with SourceInfo 
'D:\a\1\s\M365Config\0.0.1\DSCResources\Exchange\Exchange.schema.psm1::158::5::EXOAtpPolicyForO365' threw one or more 
non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel 
called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
The private key could not be acquired.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

**Comment by andikrueger** [comment]
Could you please make sure that your authentication is working properly:

```
The private key could not be acquired
```

Looks like an certificate issue. The certificate needs to be available with the private key.

**Comment by michaelbaltes** [comment]
All Certs are in my Local Cert-Store and M365ClientCert.pfx located on c:\ of Agent Host VM.
Is the another location to store the certificate? The first settings I got.

![image](https://github.com/microsoft/Microsoft365DSC/assets/34088306/0dde7b8c-e478-49b9-b78e-4344fb9169b2)

**Comment by JordyBlommaert95** [comment]
> All Certs are in my Local Cert-Store and M365ClientCert.pfx located on c:\ of Agent Host VM. Is the another location to store the certificate? The first settings I got.
> 
> ![image](https://user-images.githubusercontent.com/34088306/256480346-0dde7b8c-e478-49b9-b78e-4344fb9169b2.png)

Can you verify if the Private Key is present in your Local Cert Store? 
In my example the Private Key is present for all my DSC Certs (You can see this by the Key logo)
My jordyinthecloud-JITC-CA-CA is without private key as it does not contain a logo
<img width="276" alt="image of Certificate Store" src="https://github.com/microsoft/Microsoft365DSC/assets/89204158/b45a1502-2ee2-432c-851e-85869d2e1215">

**Comment by michaelbaltes** [comment]
Thanks i will check it all - but unfortunately only in a few days

**Comment by michaelbaltes** [comment]
I  rebuild all and after a while I find out that the dsc-admin account which added to prdoduction.psd1 have to add permission to subscription.  at least, it seems so. But now I get another error. 
<img width="729" alt="image" src="https://github.com/microsoft/Microsoft365DSC/assets/34088306/b5a4bf73-8453-40d9-a152-51ade0922b0f">

**Comment by JordyBlommaert95** [comment]
Can you review if the Dependencies were correctly installed?
Also can you verify which Microsoft 365 DSC version you are running?

**Comment by michaelbaltes** [comment]
Ok, I have tried it, but get this error:
##[error]The module 'SecurityCompliance' could not be loaded. For more information, run 'Import-Module SecurityCompliance'

Thanks

**Comment by michaelbaltes** [comment]
can I delete this section inside production.psd1
@{
                Workload       = 'SecurityCompliance'
                ApplicationId  = 
                CertThumbprint = 
            }

**Comment by JordyBlommaert95** [comment]
Is this during the MOF file creation? After you run the Pipeline?
If so this means there is a possible Syntax error in your SecurityCompliance Schema file under the DscResources. You need to check if there not any deprecated parameters.
If you don't want to deploy SecurityCompliance functionalities you can remove everything related towards SecurityCompliance in the production datafile. Remove the SecurityCompliance folder under DscResources and remove Security and compliance in the M365Configuration.ps1 file

**Comment by michaelbaltes** [comment]
Last question please. You are right - the comes from psm1 files. How can I create it by myself without write all manually? 
I will close the issue

**Comment by michaelbaltes** [comment]
Great job many thanks
