### ISSUE TITLE
AADGroup: Set MemberOf not working

### ISSUE THREAD

**Issue by malauter** [microsoft/Microsoft365DSC#3496]
### Description of the issue

The MemberOf property of the Set method is not working. I think the reason is that in line 416 the MemberOf parameter is removed, so the later check is always $false:

`  $currentParameters = $PSBoundParameters
    $currentParameters.Remove('Owners') | Out-Null
    $currentParameters.Remove('Members') | Out-Null
    $currentParameters.Remove('MemberOf') | Out-Null
    $currentParameters.Remove('AssignedToRole') | Out-Null`

`if ($PSBoundParameters.ContainsKey('MemberOf'))` in line 674 is always $false.

This issue applies also to Owners, Members and AssignedToRole attribute.

### Microsoft 365 DSC Version

V1.23.719.1

### Workload

- [X] Azure Active Directory
- [ ] Exchange Online
- [ ] Office 365 Admin
- [ ] OneDrive for Business
- [ ] Planner
- [ ] Power Platform
- [ ] Security & Compliance Center
- [ ] SharePoint Online
- [ ] Teams
- [ ] other

### The DSC configuration

`AADGroup 'MyGroup'
        {
            DisplayName        = "MyTestGroup"
            Description        = "Test"
            SecurityEnabled    = $True
            MailEnabled        = $False
            GroupTypes         = @()
            MailNickname       = "MyTestGroup"
            Ensure             = "Present"
            MemberOf = @("MyOtherTestGroup")
            Credential = $creds
    }`

**Comment by ricmestre** [comment]
@malauter Those properties are backed up into new variables just right above so they are actually not lost.

```powershell
$backCurrentOwners = $currentGroup.Owners
$backCurrentMembers = $currentGroup.Members
$backCurrentMemberOf = $currentGroup.MemberOf
$backCurrentAssignedToRole = $currentGroup.AssignedToRole
```

Additionally $PSBoundParameters also still contains its initial keys (parameters), what has been removed is from $currentParameters instead.

What exactly is the error message you're getting during deployment?

**Comment by malauter** [comment]
@ricmestre No error message, it is just no set. Reason is, that $currentParameters = $PSBoundParameters does not clone the hashtable. If you remove a key from $currentParameters it is also removed from $PSBoundParameters and the if statement can be never true. My linked fix creates a new instance of the object to prevent this issue.

**Comment by ricmestre** [comment]
Oh yeah, hashtables are always a pain so your diff makes sense... But maybe be explicit and not only cast it but also call clone like this? 

```powershell
([Hashtable]$PSBoundParameters).Clone()
```

And tests seem to be failing due to calling Invoke-WebRequest on a non-existent domain... @andikrueger @NikCharlebois any clues about this?

```powershell
Error: [-] Describe Successfully validate all used permissions in Settings.json files failed
Message
  SocketException: No such host is known.
  HttpRequestException: No such host is known. (graphpermissions.azurewebsites.net:443)
  at <ScriptBlock>, D:\a\Microsoft365DSC\Microsoft365DSC\Tests\QA\Microsoft365DSC.SettingsJson.Tests.ps1:20
```

**Comment by ricmestre** [comment]
There may be other resources that potentially have the same problem.

https://github.com/search?q=repo%3Amicrosoft%2FMicrosoft365DSC+%24currentParameters+%3D+%24PSBoundParameters&type=code
