### ISSUE TITLE
The argument "Preview" does not belong to the set "Export,Purge,Retention"

### ISSUE THREAD

**Issue by 808d1** [microsoft/Microsoft365DSC#3498]
### Description of the issue

When exporting the Security And Compliance workload, I am receiving a lot of errors referencing a missing ValidateSet attribute in MSFT_SCComplianceSearchAction.psm1 for every call to the "Get-CurrentAction" function.

...

### Microsoft 365 DSC Version

1.23.719.1

### Workload

- [ ] Azure Active Directory
- [ ] Exchange Online
- [ ] Office 365 Admin
- [ ] OneDrive for Business
- [ ] Planner
- [ ] Power Platform
- [X] Security & Compliance Center
- [ ] SharePoint Online
- [ ] Teams
- [ ] other

### The DSC configuration

Extracting SCComplianceSearchAction using CertificateThumbprint

### Verbose logs showing the problem

Cannot validate argument on parameter 'Action'.  The argument "Preview" does not belong to the set "Export,Purge,Retention" specified by the ValidateSet attribute.
"Error retrieving data:"
at Get-TargetResource, C:\.....\Modules\Microsoft365DSC\1.23.719.1\DSCResources\MSFT_SCComplianceSearchAction.psm1:line 105

### Environment Information + PowerShell Version

```powershell
Microsoft Windows 10 Enterprise
EnterpriseEdition
64-bit
2009
19041.1.amd64fre.vb_release.191206-1406
en-US
{en-US}

PSVersion 5.1.19041.3031
```

**Comment by NikCharlebois** [comment]
The solution does support the Preview value. What version of Microsoft365DSC are you using? It may be worth updating to the latest version with update-M365dscmodule,

**Comment by ricmestre** [comment]
@nikcharlebois The resource supports Preview but the problem exists in the ancillary function *Get-CurrentAction* which is missing it from the ValidateSet

https://github.com/microsoft/Microsoft365DSC/blob/dca7e57e8ca78c8fbe0400cd0ebb6f8f39d89b9e/Modules/Microsoft365DSC/DSCResources/MSFT_SCComplianceSearchAction/MSFT_SCComplianceSearchAction.psm1#L678

**Comment by NikCharlebois** [comment]
Got it. Get-CurrentAction should not have enforced a ValidateSet.  Out of curiosity, are you able to use the -Preview on the New-ComplianceSearchAction cmdlet for your tenant? That parameter seems to exist in the documentation, but isn't exposed by the cmdlet. Do you know how these Preview actions were created in the first place on the tenant?

**Comment by 808d1** [comment]
> Got it. Get-CurrentAction should not have enforced a ValidateSet. Out of curiosity, are you able to use the -Preview on the New-ComplianceSearchAction cmdlet for your tenant? That parameter seems to exist in the documentation, but isn't exposed by the cmdlet. Do you know how these Preview actions were created in the first place on the tenant?

I'm not sure how these were created in my company, they were created before I started.  I am able to use the -Preview but only after assigning myself eDiscovery Manager and Admin.  Here's a sample script I successfully ran in my personal sandbox tenant:

Import-Module ExchangeOnlineManagement
Connect-IPPSSession

# Create a search query specifying a name, where to look, and the search parameters
New-ComplianceSearch -Name "Test4Nick" -ExchangeLocation 'All' -ContentMatchQuery "(c:c)(Subject: 'Urgent Request') "

# Start the search query created above
Start-ComplianceSearch -Identity 'Test4Nick'

# Check status of the search query
Get-ComplianceSearch  -Identity 'Test4Nick'

# Preview the results to compare with the web-results,
New-ComplianceSearchAction -SearchName 'Test4Nick' -Preview
