### ISSUE TITLE
Microsoft365Dsc behind a web proxy

### ISSUE THREAD

**Issue by jeremyhagan** [microsoft/Microsoft365DSC#3501]
Hi,

I'm having issues with running test on a machine which is behind a corporate proxy. I have the winhttp proxy set via NETSH and I have used [System.Net.WebRequest]::DefaultWebProxy to set a proxy.

When I use Invoke-WebRequest or Connect-ExchangeOnline everything is seamless. However when I run a Start-DscConfiguration I just get an error "Unable to connect to the remote server"

When using all the same commands and script on a machine that is directly Internet connected everything works fine (same service principal and certificate).

I've searched and searched but have found nothing on resolving this issue.

Can anyone help?

**Comment by andikrueger** [comment]
You need to configure LCM to use a proxy: https://learn.microsoft.com/en-us/powershell/dsc/managing-nodes/metaconfig?view=dsc-1.1#configuration-server-blocks

**Comment by jeremyhagan** [comment]
> You need to configure LCM to use a proxy: https://learn.microsoft.com/en-us/powershell/dsc/managing-nodes/metaconfig?view=dsc-1.1#configuration-server-blocks

Thank you so much. Not sure why my googling didn't turn this up.

**Comment by jeremyhagan** [comment]
.

**Comment by jeremyhagan** [comment]
This did not end up being the answer to the question. The solution linked is correct in defining a proxy server to get to a specific web-based configuration repository, however this is not relevant to the DSC resources for M365Dsc being able to perform their Test/Get/Set operations.

At some point I remembered .NET proxy config. The solution was to put an appropriate block in the machine.config folder of the machines .NET framework settings as per
https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings

**Comment by jeremyhagan** [comment]
.

**Comment by andikrueger** [comment]
Thank you for sharing the solution. This might help others in the future.
