### ISSUE TITLE
Graph Beta is defined in the Manifest

### ISSUE THREAD

**Issue by 808d1** [microsoft/Microsoft365DSC#3506]
The latest version 1.23.719.1 (and previous version 1.23.712.1) now define using Graph Beta as the required dependencies. Was this intentional?

Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
RequiredVersion                1.3.0.10                                                                                                                                  
ModuleName                     DSCParser                                                                                                                                 
RequiredVersion                3.2.0                                                                                                                                     
ModuleName                     ExchangeOnlineManagement                                                                                                                  
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.Applications                                                                                                              
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.Authentication                                                                                                            
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.**Beta**.DeviceManagement                                                                                                     
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.**Beta**.Devices.CorporateManagement                                                                                          
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.**Beta**.DeviceManagement.Administration                                                                                      
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.**Beta**.DeviceManagement.Enrollment                                                                                          
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.**Beta**.Identity.DirectoryManagement                                                                                         
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.**Beta**.Identity.Governance                                                                                                  
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.**Beta**.Identity.SignIns                                                                                                     
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.**Beta**.Teams                                                                                                                
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.DeviceManagement.Administration                                                                                           
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.**Beta**.DirectoryObjects                                                                                                     
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.Groups                                                                                                                    
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.Planner                                                                                                                   
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.Users                                                                                                                     
RequiredVersion                2.1.0                                                                                                                                     
ModuleName                     Microsoft.Graph.Users.Actions                                                                                                             
RequiredVersion                2.0.168                                                                                                                                   
ModuleName                     Microsoft.PowerApps.Administration.PowerShell                                                                                             
RequiredVersion                5.4.0                                                                                                                                     
ModuleName                     MicrosoftTeams                                                                                                                            
RequiredVersion                1.0.117                                                                                                                                   
ModuleName                     MSCloudLoginAssistant                                                                                                                     
RequiredVersion                1.12.0                                                                                                                                    
ModuleName                     PnP.PowerShell                                                                                                                            
RequiredVersion                2.0.0.16                                                                                                                                  
ModuleName                     ReverseDSC

**Comment by NikCharlebois** [comment]
We were always using beta endpoints in multiple locations in the past. Prior to version 2 of the Graph PowerShell module, this was done in code via a *select-mgprofile beta* call. With the way Graph SDK 2.0 changed its packaging, we now need to implicitly load these via the manifest.

**Comment by jeremyhagan** [comment]
Seems that the install/upgrade is broken as I am getting
"Installing MSCloudLoginAssistant version {1.0.118}
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'MSCloudLoginAssistant'"

When I run the upgrade process, which doesn't stop on the error and proceed to uninstall the current version. Then on the install of version 1.23.719.1, the error above occurs,

When I run Find-Package MSCloudLoginAssistant -AllVersions 10.0117 is the latest version available

**Comment by andikrueger** [comment]
It looks like the publishing of the MSCloudLoginAssistant module has gone wrong. @NikCharlebois could you please push the latest version to PSGallery?

**Comment by andikrueger** [comment]
linking #3511 to track the MSCloudLoginAssistant issue.
