### ISSUE TITLE
Creation of EXOQuarantinePolicy fails with 'The term 'New-QuarantinePolicy' is not recognized as the name of a cmdlet, function, script file, or operable program.'

### ISSUE THREAD

**Issue by jeremyhagan** [microsoft/Microsoft365DSC#3510]
### Description of the issue

Creation of a new quarantine policy doesn't work.

I created the policy manually, exported the policy into a config and then deleted it.

I compiled the config containing the resource, then ran start-dscconfiguration and when it tried to create the policy the error was thrown and the resource was not created.

I can't test with the latest version as the installer tries to install a version of the MSCloudLoginAssistant that doesn't exist.

### Microsoft 365 DSC Version

V.1.23.719.1

### Which workloads are affected

Exchange Online

### The DSC configuration

param (
)

Configuration EXOConfig
{
    param (
    )

    $OrganizationName = $ConfigurationData.NonNodeData.OrganizationName

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.23.719.1'

    Node localhost
    {
        EXOQuarantinePolicy "EXOQuarantinePolicy-FullAccess: Notification"
        {
            ApplicationId                     = $ConfigurationData.NonNodeData.ApplicationId;
            CertificateThumbprint             = $ConfigurationData.NonNodeData.CertificateThumbprint;
            EndUserQuarantinePermissionsValue = 23;
            Ensure                            = "Present";
            ESNEnabled                        = $True;
            Identity                          = "FullAccess: Notification";
            TenantId                          = $OrganizationName;
        }
        EXOQuarantinePolicy "EXOQuarantinePolicy-Request Release: Notification"
        {
            ApplicationId                     = $ConfigurationData.NonNodeData.ApplicationId;
            CertificateThumbprint             = $ConfigurationData.NonNodeData.CertificateThumbprint;
            EndUserQuarantinePermissionsValue = 27;
            Ensure                            = "Present";
            ESNEnabled                        = $True;
            Identity                          = "Request Release: Notification";
            TenantId                          = $OrganizationName;
        }
}

### Verbose logs showing the problem

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer computernamewith user sid 
VERBOSE: [computername]: LCM:  [ Start  Set      ]
VERBOSE: [computername]: LCM:  [ Start  Resource ]  [[EXOQuarantinePolicy]EXOQuarantinePolicy-FullAccess: Notification]
VERBOSE: [computername]: LCM:  [ Start  Test     ]  [[EXOQuarantinePolicy]EXOQuarantinePolicy-FullAccess: Notification]
VERBOSE: [computername]:                            [[EXOQuarantinePolicy]EXOQuarantinePolicy-FullAccess: Notification] Testing configuration of QuarantinePolicy for FullAccess: Notification
VERBOSE: [computername]:                            [[EXOQuarantinePolicy]EXOQuarantinePolicy-FullAccess: Notification] Getting configuration of QuarantinePolicy for FullAccess: Notification
VERBOSE: [computername]:                            [[EXOQuarantinePolicy]EXOQuarantinePolicy-FullAccess: Notification] QuarantinePolicy FullAccess: Notification does not exist.
VERBOSE: [computername]:                            [[EXOQuarantinePolicy]EXOQuarantinePolicy-FullAccess: Notification] Current Values: ApplicationId=***
CertificateThumbprint=***
EndUserQuarantinePermissionsValue=23
Ensure=Absent
ESNEnabled=True
Identity=FullAccess: Notification
TenantId=***
Verbose=True
VERBOSE: [computername]:                            [[EXOQuarantinePolicy]EXOQuarantinePolicy-FullAccess: Notification] Target Values: ApplicationId=***
CertificateThumbprint=***
EndUserQuarantinePermissionsValue=23
Ensure=Present
ESNEnabled=True
Identity=FullAccess: Notification
TenantId=***
Verbose=True
VERBOSE: [computername]:                            [[EXOQuarantinePolicy]EXOQuarantinePolicy-FullAccess: Notification] Test-TargetResource returned False
VERBOSE: [computername]: LCM:  [ End    Test     ]  [[EXOQuarantinePolicy]EXOQuarantinePolicy-FullAccess: Notification]  in 15.7590 seconds.
VERBOSE: [computername]: LCM:  [ Start  Set      ]  [[EXOQuarantinePolicy]EXOQuarantinePolicy-FullAccess: Notification]
VERBOSE: [computername]:                            [[EXOQuarantinePolicy]EXOQuarantinePolicy-FullAccess: Notification] Setting configuration of QuarantinePolicy for FullAccess: Notification
VERBOSE: [computername]:                            [[EXOQuarantinePolicy]EXOQuarantinePolicy-FullAccess: Notification] Creating QuarantinePolicy FullAccess: Notification.
The term 'New-QuarantinePolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
    + CategoryInfo          : ObjectNotFound: (New-QuarantinePolicy:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost

### Environment Information + PowerShell Version

```powershell
sName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Name                           Value
----                           -----
PSVersion                      5.1.17763.4644
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.4644
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by NikCharlebois** [comment]
If you are getting an error that an EXO related cmdlet doesn't exist, then it's permission related. Di you compile the configuration with the same account you used to extract it? WRT MSCloudAssistant, there was a TLS issue during the publish process which caused the error. This is now fixed. Sorry for the troubles.

**Comment by jeremyhagan** [comment]
Thanks Nik. I added Exchange Administrator to my App Registration and it worked.
