### ISSUE TITLE
Update-M365DSCDependencies  MSCloudLoginAssistant failed

### ISSUE THREAD

**Issue by michaelbaltes** [microsoft/Microsoft365DSC#3511]
### Description of the issue

Hello 
I cannot update dependencies to latest version because I don't find Version 1.0.118 of module MSCloudLoginAssistant. Only find Version 1.0.117
Output:
Update-M365DSCDependencies
Installing MSCloudLoginAssistant version {1.0.118}
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'MSCloudLoginAssistant'. Try
Get-PSRepository to see all available registered module repositories.
In C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 Zeichen:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

Searching manully:

Find-Module -Name MSCloudLoginAssistant -AllVersions

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.0.117    MSCloudLoginAssistant               PSGallery            Checks the current status of connections to (and as required, prompt...
1.0.116    MSCloudLoginAssistant               PSGallery            Checks the current status of connections to (and as required, prompt...
1.0.115    MSCloudLoginAssistant               PSGallery

### Microsoft 365 DSC Version

1.23.726.1

### Which workloads are affected

other

### The DSC configuration

Update-M365DSCDependencies
Installing MSCloudLoginAssistant version {1.0.118}
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'MSCloudLoginAssistant'. Try
Get-PSRepository to see all available registered module repositories.
In C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 Zeichen:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

### Verbose logs showing the problem

install-module MSCloudLoginAssistant -MinimumVersion 1.0.118
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'MSCloudLoginAssistant'. Try
Get-PSRepository to see all available registered module repositories.
In C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 Zeichen:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

### Environment Information + PowerShell Version

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by andikrueger** [comment]
Thank you for reporting. We are aware of this issue. There was a glitch with the publishing of MSCloudLoginAssistant.

**Comment by DominicBoettger** [comment]
Is there a workaround as I am currently unable to do a export.
Can I downgrade?

The following dependencies need updating:
    * MSCloudLoginAssistant
Please run Update-M365DSCDependencies as Administrator.Please run Uninstall-M365DSCOutdatedDependencies.

**Comment by michaelbaltes** [comment]
In my opion, you can uninstall the current release of M365dsc and install prev. version
Install-Module -Name Microsoft365Dsc -MaximumVersion 1.23.719.1

**Comment by JordyBlommaert95** [comment]
Issue is now resolved.
`[2023-07-27 09:48:37] -   Checking Microsoft365Dsc version
[2023-07-27 09:48:37] -     Required version: 1.23.726.1
[2023-07-27 09:48:37] -     Installed version: 1.23.726.1
[2023-07-27 09:48:37] -       Correct version installed, continuing.
[2023-07-27 09:48:37] -   Checking Module Dependencies
Installing MSCloudLoginAssistant version {1.0.118}
[2023-07-27 09:48:59] -   Removing Outdated Module Dependencies
Uninstalling MSCloudLoginAssistant Version {1.0.117}
Checking Microsoft.Graph.Authentication
[2023-07-27 09:49:02] - Modules installed successfully!`

**Comment by michaelbaltes** [comment]
Great 
Thanks guys

find-module -Name MSCloudLoginAssistant gets now the right version
**1.0.118**
