### ISSUE TITLE
Update-M365DSCDependencies - unable to update dependencies to latest version

### ISSUE THREAD

**Issue by shilpaCM** [microsoft/Microsoft365DSC#3512]
### Description of the issue

Hi,

trying to update Update-M365DSCDependencies in the Azure runbook. but we are unable to run Uninstall-M365DSCOutdatedDependencies command to uninstall old versions as part of azure runbook. which keeps showing error like 'run Update-M365DSCDependencies as Administrator' & it does not update the dependencies.

### Microsoft 365 DSC Version

V1.23.123

### Which workloads are affected

other

### The DSC configuration

running part of runbook via managed system identity

### Verbose logs showing the problem

Failed

The following dependencies need updating:

    * DSCParser

    * ExchangeOnlineManagement

    * Microsoft.Graph.Applications

    * Microsoft.Graph.Authentication

    * Microsoft.Graph.Beta.DeviceManagement

    * Microsoft.Graph.Beta.Devices.CorporateManagement

    * Microsoft.Graph.Beta.DeviceManagement.Administration

    * Microsoft.Graph.Beta.DeviceManagement.Enrollment

    * Microsoft.Graph.Beta.Identity.DirectoryManagement

    * Microsoft.Graph.Beta.Identity.Governance

    * Microsoft.Graph.Beta.Identity.SignIns

    * Microsoft.Graph.Beta.Teams

    * Microsoft.Graph.DeviceManagement.Administration

    * Microsoft.Graph.Beta.DirectoryObjects

    * Microsoft.Graph.Groups

    * Microsoft.Graph.Planner

    * Microsoft.Graph.Users

    * Microsoft.Graph.Users.Actions

    * Microsoft.PowerApps.Administration.PowerShell

    * MicrosoftTeams

    * MSCloudLoginAssistant

    * PnP.PowerShell

    * ReverseDSC

Please run Update-M365DSCDependencies as Administrator.Please run Uninstall-M365DSCOutdatedDependencies.

### Environment Information + PowerShell Version

```powershell
Powershell 5.1
```

**Comment by JamieWilsonCC** [comment]
`Install-Module -Name MSCloudLoginAssistant -MinimumVersion 1.0.118`

No match was found for the specified search criteria and module name 'MSCloudLoginAssistant'

`Install-Module -Name MSCloudLoginAssistant installs 1.0.117`

**Comment by NikCharlebois** [comment]
There was a TLS issue publishing MSCloudLoginAssistant from our automated flow. This has been fixed and the version is now available in the gallery. Sorry for the troubles.

**Comment by shilpaCM** [comment]
Hi @NikCharlebois & @JamieWilsonCC,  Even after updating MSCloudLoginAssistant  to 1.0.118, it shows same error.

**Comment by shenukaf69** [comment]
any fix for this ?
