### ISSUE TITLE
DSCResourceInfo: Cannot bind argument to parameter 'DSCResourceInfo' because it is null.

### ISSUE THREAD

**Issue by NunoFilipeMota** [microsoft/Microsoft365DSC#3514]
### Description of the issue

Hi everyone,

Using PowerShell v7.3.6, I've just installed Microsoft365DSC (v1.23.719.1) on a "clean" server without any other PowerShell modules. I've installed this version because of the bug with the latest version where it requires MSCloudLoginAssistant v1.0.118 when the latest is actually v1.0.117.

I am able to export configurations from different resources without any issues. However, I am unable to compare exports and generate a delta report:

`PS D:\ScheduledScripts\DSC-Production> New-M365DSCDeltaReport -Source $prev -Destination $cur -OutputPath "D:\ScheduledScripts\DSC-Production\diff.html"
Find-Package: No match was found for the specified search criteria and module name 'Microsoft365DSC'. Try Get-PSRepository to see all available registered module repositories.
WARNING: There are no modules present in the system with the given module specification.
Error: Cannot bind argument to parameter 'DSCResourceInfo' because it is null.`

I had a look at the _M365DSCReport.psm1_ module and found the following:

`$dscResourceInfo = Get-DSCResource -Module 'Microsoft365DSC'
(...)
[array]$key = Get-M365DSCResourceKey -Resource $sourceResource -DSCResourceInfo $dscResourceInfo`

And I think this is where the problem resides. On this machine, there doesn't seem to be any M365DSC resources:

`PS D:\> Get-DSCResource -Module 'Microsoft365DSC'
WARNING: There are no modules present in the system with the given module specification.`

On another server, with a slightly older version of Microsoft365DSC, I get 279 resources for the Microsoft365DSC module.

Any idea why this could be? Thank you!

### Microsoft 365 DSC Version

1.23.719.1

### Which workloads are affected

other

### Verbose logs showing the problem

PS D:\> Get-DSCResource -Module 'Microsoft365DSC'
WARNING: There are no modules present in the system with the given module specification.

PS D:\> New-M365DSCDeltaReport -Source $prev -Destination $cur -OutputPath "D:\ScheduledScripts\DSC-Production\diff.html" -Verbose
Find-Package: No match was found for the specified search criteria and module name 'Microsoft365DSC'. Try Get-PSRepository to see all available registered module repositories.
VERBOSE: Obtaining Delta between the source and destination configurations
VERBOSE: Loading file 'D:\ScheduledScripts\DSC-Production\DSCReports\M365DSC-LSEG-ExchangeOnline_20230325T0602.ps1'
VERBOSE: Loading file 'D:\ScheduledScripts\DSC-Production\DSCReports\M365DSC-LSEG-ExchangeOnline_20230727T1119.ps1'
WARNING: There are no modules present in the system with the given module specification.
Error: Cannot bind argument to parameter 'DSCResourceInfo' because it is null.
Error: Cannot bind argument to parameter 'DSCResourceInfo' because it is null.
(…)
Error: Cannot bind argument to parameter 'DSCResourceInfo' because it is null.
Error: Cannot bind argument to parameter 'DSCResourceInfo' because it is null.
VERBOSE: Error: Cannot bind argument to parameter 'DSCResourceInfo' because it is null.
VERBOSE: Error: Cannot bind argument to parameter 'DSCResourceInfo' because it is null.
(...)
VERBOSE: Error: Cannot bind argument to parameter 'DSCResourceInfo' because it is null.
VERBOSE: Error: Cannot bind argument to parameter 'DSCResourceInfo' because it is null.
PS D:\>

### Environment Information + PowerShell Version

```powershell
PS D:\> Get-ComputerInfo -Property @(...)

OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}


PS D:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by NikCharlebois** [comment]
MSCloudLoginAssistant 1.0.118 is now available on the Gallery. I would recommend you update to the latest M365DSC version and see if you are still getting that error.

**Comment by NunoFilipeMota** [comment]
OMG, I literally checked 3h ago and it still wasn't there   :)

I've just updated the Microsoft365DSC module to the latest version, removed the old version, and updated all the dependencies (there were no updates to be made), but the issue remains unfortunately:

![NoResources](https://github.com/microsoft/Microsoft365DSC/assets/18609093/eed0fa5e-5444-43cb-bdef-fc237b4e4124)

**Comment by NikCharlebois** [comment]
Did you try the PoSh 7 troubleshooting guide?
https://microsoft365dsc.com/user-guide/get-started/powershell7-support/#common-issues-when-the-modules-are-not-in-the-right-folder

My guts feeling tells me you haven't installed the module and dependencies using Windows PowerShell. I'd recommend re-installing the Module using Windows PoSh (5.1) or manually moving them under :\Program FIles\WindowsPowerShell\Modules and trying again.

**Comment by NunoFilipeMota** [comment]
Apologies, you are absolutely correct! I did that on my other server, but not on this one (I installed everything using PoSh 7)...   :(
Thank you so much for the prompt help and apologies for wasting your time!
