### ISSUE TITLE
Service principal API permissions

### ISSUE THREAD

**Issue by cpc-alruba** [microsoft/Microsoft365DSC#3522]
Hello - are there any Read-only alternatives to the required API permissions when the scope/access type is Read only? we noticed while exporting configs from Teams, SharePoint and Azure AD that we need to add API with write permission such as "Channel.Delete.All" to the service principal for the script to work while all we are doing is reading the config!

Any chance we can use Read-only API permissions to read the same configs without the need to grant the service principal access permission like "Channel.Delete.All", TeamSettings.ReadWrite.All or Policy.ReadWrite.AuthenticationMethod

----                           -----
These are the current required permission by Teams components when the access type is Read only

![TeamsAPIPermission](https://github.com/microsoft/Microsoft365DSC/assets/127355191/13a9966c-7412-4c93-be16-3dbe2de92abf)

This one for Azure AD components:

![AAD API Permission](https://github.com/microsoft/Microsoft365DSC/assets/127355191/c059e394-b61b-40f2-a025-c3e38aa4eef0)
:

**Comment by andikrueger** [comment]
Thanks for reporting. We are aware of this issue. 

Please refer to the MS Teams documentation about the permissions. There is work going on to implement a more specific set of scopes for these workloads.

https://learn.microsoft.com/en-us/microsoftteams/teams-powershell-application-authentication#setup-application-based-authentication

Closing this one in favor of #3404
