### ISSUE TITLE
Update-M365DSCDependencies - unable to update dependencies to latest version

### ISSUE THREAD

**Issue by shilpaCM** [microsoft/Microsoft365DSC#3523]
### Description of the issue

Hi,

trying to update Update-M365DSCDependencies in the Azure runbook. but we are unable to run Uninstall-M365DSCOutdatedDependencies command to uninstall old versions as part of azure runbook. which keeps showing error like 'run Update-M365DSCDependencies as Administrator' & it does not update the dependencies.

 Even after updating MSCloudLoginAssistant to 1.0.118, it shows same error.

error has below
The following dependencies need updating:

* DSCParser

* ExchangeOnlineManagement

* Microsoft.Graph.Applications

* Microsoft.Graph.Authentication

* Microsoft.Graph.Beta.DeviceManagement

* Microsoft.Graph.Beta.Devices.CorporateManagement

* Microsoft.Graph.Beta.DeviceManagement.Administration

* Microsoft.Graph.Beta.DeviceManagement.Enrollment

* Microsoft.Graph.Beta.Identity.DirectoryManagement

* Microsoft.Graph.Beta.Identity.Governance

* Microsoft.Graph.Beta.Identity.SignIns

* Microsoft.Graph.Beta.Teams

* Microsoft.Graph.DeviceManagement.Administration

* Microsoft.Graph.Beta.DirectoryObjects

* Microsoft.Graph.Groups

* Microsoft.Graph.Planner

* Microsoft.Graph.Users

* Microsoft.Graph.Users.Actions

* Microsoft.PowerApps.Administration.PowerShell

* MicrosoftTeams

* MSCloudLoginAssistant

* PnP.PowerShell

* ReverseDSC
Please run Update-M365DSCDependencies as Administrator.Please run Uninstall-M365DSCOutdatedDependencies.

### Microsoft 365 DSC Version

V1.23.123

### Which workloads are affected

other

### The DSC configuration

running part of runbook via managed system identity

### Verbose logs showing the problem

Failed

### Environment Information + PowerShell Version

```powershell
Powershell 5.1
```

**Comment by andikrueger** [comment]
You cannot use these commands in Azure Runbooks. Runbooks use the modules that are provided for the runbook. Please make sure to upload all modules, that are needed to run M365DSC.

Within this comment, there is a script that helps you to do so:

https://github.com/microsoft/Microsoft365DSC/issues/2050#issuecomment-1195414547

**Comment by andikrueger** [comment]
linking #2050

**Comment by shilpaCM** [comment]
i am uploading all modules from gallery, but unable to add PNP.PowerShell(with PowerShell version 5.1) shows error as 'Error importing the module PnP.PowerShell. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: While importing the module, an error occurred while processing the module content. Internal error message: Could not load file or assembly 'System.Management.Automation, Version=7.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.. at Orchestrator.Activities.SetModuleVersion.ExecuteInternal(CodeActivityContext context, String moduleName, ModuleLanguage moduleLanguage, String pythonModuleVersion, String modulePath, Guid accountId, Guid moduleVersionId, Int64 moduleContentByteSize, String storageUri, Int32 moduleVersion) at Orchestrator.Activities.SetModuleVersion.Execute(CodeActivityContext context) at System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager) at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)' 
Any suggestions.

**Comment by andikrueger** [comment]
You need to install this module by using PowerShell to be able to select the 1.12.0 version.

**Comment by shilpaCM** [comment]
I keep getting this error, even though all required permission are provided, also i am trying to check with basic authentication. 'Unable to retrieve SPO Admin URL. Please check connectivity and if you have the Sites.Read.All permission. (Unable to retrieve SPO Admin URL. Please check connectivity and if you have the Sites.Read.All permission.)'

**Comment by shilpaCM** [comment]
I am able to solve all issues, but below issue is keeps coming back. Kindly help

Failed
Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly 'Microsoft.Graph.Core, Version=1.25.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. (Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly 'Microsoft.Graph.Core, Version=1.25.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.)

**Comment by shilpaCM** [comment]
Thank you for the response. Able to solve that issue.
