### ISSUE TITLE
IntuneDeviceCompliancePolicy

### ISSUE THREAD

**Issue by secustor** [microsoft/Microsoft365DSC#353]
### Description
We want to fully setup new O365 tenants using DSC and as Intune is part of O365 we would like to see it include here too.     
The DevicePolicy should be seen here as the biggest pain point in a bigger effort to enable Intune configurations.

### Proposed properties
```

- description
- displayName
- passwordRequired
- passwordBlockSimple
- passwordRequiredToUnlockFromIdle
- passwordMinutesOfInactivityBeforeLock
- passwordExpirationDays
- passwordMinimumLength
- passwordMinimumCharacterSetCount
- passwordRequiredType
- passwordPreviousPasswordBlockCount
- requireHealthyDeviceReport
- osMinimumVersion
- osMaximumVersion
- mobileOsMaximumVersion
- mobileOsMaximumVersion
- earlyLaunchAntiMalwareDriverEnabled
- bitLockerEnabled
- secureBootEnabled
- codeIntegrityEnabled
- storageRequireEncryption
- activeFirewallRequired
- defenderEnabled
- defenderVersion
- signatureOutOfDate
- rtpEnabled
- antivirusRequired
- antiSpywareRequired
- deviceThreatProtectionEnabled
- deviceThreatProtectionRequiredSecurityLevel
- configurationManagerComplianceRequired
- tpmRequired
- validOperatingSystemBuildRanges
```

**Comment by RobinDadswell** [comment]
Is it worth getting it to do more than just the Device Policies - e.g. application protection etc. as just the one is not much help on it's own as it is a larger set of policies that can be a part of a device.

**Comment by dcaddick** [comment]
My focus is on Security from M365, and more than happy to help with any testing for Intune to start with, so please let me know how I can help with testing in multiple tenants

**Comment by NikCharlebois** [comment]
Thanks for the offer to help out folks. Let me follow-up with our team in Japan who is responsible for the Intune work and I will update this thread once I get more information on the progress.

**Comment by NikCharlebois** [comment]
@luigilink here's one for you 😄 !

**Comment by luigilink** [comment]
@NikCharlebois you can assign to me. ;)
