### ISSUE TITLE
Error Running: Export-M365DSCConfiguration ERROR when connecting to PNP

### ISSUE THREAD

**Issue by jpcapone** [microsoft/Microsoft365DSC#3530]
### Description of the issue

![image](https://github.com/microsoft/Microsoft365DSC/assets/47680328/c1a7f22b-b5d7-4f54-96bb-49847e0e6a30)

`Update-Module Microsoft365DSC

Update-M365DSCDependencies`

used the aforementioned commands to attempt to remediate the issue per other issues reported.  This did not work and the issue persists.

### Microsoft 365 DSC Version

1.23.726.1

### Which workloads are affected

SharePoint Online

### The DSC configuration

Export-M365DSCConfiguration -Credential $creds

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 11 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.22621.1778
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.22621.1778
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by jpcapone** [comment]
Can anyone shed some light on how I might be able to work through this error?

**Comment by jpcapone** [comment]
> Please try to use your tenant.onmicrosoft.com UPN for accessing the tenant. This should resolve the issue.

I can confirm with 100 % certainty that I have been using the default domain name when logging in.  Is there anything else I can try?  Maybe I am not performing all of the required steps.  Do you have a concise list of the steps you can share with me here?

**Comment by andikrueger** [comment]
Is this a non-standard tenant like one within a government cloud or similar?

**Comment by jpcapone** [comment]
I installed the Microsoft365DSC after deploying a fresh copy of windows server 2022 into a VM and the script ran as expected.  Just wanted to share this with people who may be in the same boat.
