### ISSUE TITLE
O365Group: Get-MgGroup : Your access token has expired. Please renew it before submitting the request.

### ISSUE THREAD

**Issue by skghq** [microsoft/Microsoft365DSC#3531]
### Description of the issue

This is fairly straightforward -- It starts failing right at ~70 minutes. I have tested this on a second server with an older version of Microsoft365DSC and experienced the same failure as well. We are using credential authentication.

Failing command:
`Export-M365DSCConfiguration -Components @("O365Group") -Credential $Credential -Path $FilePath -FileName $FileName`

Failure message snippet:
`Get-MgGroup : Your access token has expired. Please renew it before submitting the request.`

Failure message complete:
[failure.txt](https://github.com/microsoft/Microsoft365DSC/files/12218184/failure.txt)

### Microsoft 365 DSC Version

1.23.726.1

### Which workloads are affected

Office 365 Admin

### Verbose logs showing the problem

✅
    |---[462/3228] <<<REDACTED>>>
✅
    |---[463/3228] <<<REDACTED>>>
✅
    |---[464/3228] <<<REDACTED>>>
✅
    |---[465/3228] <<<REDACTED>>>
Get-MgGroup : Your access token has expired. Please renew it before submitting the request.

Status: 401 (Unauthorized)
ErrorCode: Authentication_ExpiredToken
Date: 2023-07-31T13:47:40

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : <<<REDACTED>>>
client-request-id             : <<<REDACTED>>>
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"South Central 
US","Slice":"E","Ring":"5","ScaleUnit":"003","RoleInstance":"<<<REDACTED>>>"}}
Date                          : Mon, 31 Jul 2023 13:47:39 GMT
WWW-Authenticate              : Bearer realm="", 
authorization_uri="https://login.microsoftonline.com/common/oauth2/authorize", 
client_id="<<<REDACTED>>>"

At C:\Program 
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.726.1\DSCResources\MSFT_O365Group\MSFT_O365Group.psm1:79 char:9
+         [array]$ADGroup = Get-MgGroup -All:$true | Where-Object -Filt ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ConsistencyLe...ndProperty =  }:<>f__AnonymousType84`9) 
[Get-MgGroup_List], Exception
    + FullyQualifiedErrorId : Authentication_ExpiredToken,Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List
Get-MgGroup : Your access token has expired. Please renew it before submitting the request.

Status: 401 (Unauthorized)
ErrorCode: Authentication_ExpiredToken
Date: 2023-07-31T13:47:40

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : <<<REDACTED>>>
client-request-id             : <<<REDACTED>>>
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"South Central US","Slice":"E","Ring":"5","ScaleUnit":"003","RoleInstance":"<<<REDACTED>>>"}}
Date                          : Mon, 31 Jul 2023 13:47:39 GMT
WWW-Authenticate              : Bearer realm="", authorization_uri="https://login.microsoftonline.com/common/oauth2/authorize", client_id="<<<REDACTED>>>"

At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.726.1\DSCResources\MSFT_O365Group\MSFT_O365Group.psm1:79 char:9
+         [array]$ADGroup = Get-MgGroup -All:$true | Where-Object -Filt ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ConsistencyLe...ndProperty =  }:<>f__AnonymousType84`9) [Get-MgGroup_List], Exception
    + FullyQualifiedErrorId : Authentication_ExpiredToken,Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List
Get-MgGroup : Your access token has expired. Please renew it before submitting the request.

Status: 401 (Unauthorized)
ErrorCode: Authentication_ExpiredToken
Date: 2023-07-31T13:47:40

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : <<<REDACTED>>>
client-request-id             : <<<REDACTED>>>
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"South Central 
US","Slice":"E","Ring":"5","ScaleUnit":"003","RoleInstance":"<<<REDACTED>>>"}}
Date                          : Mon, 31 Jul 2023 13:47:39 GMT
WWW-Authenticate              : Bearer realm="", 
authorization_uri="https://login.microsoftonline.com/common/oauth2/authorize", 
client_id="<<<REDACTED>>>"

At C:\Program 
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.726.1\DSCResources\MSFT_O365Group\MSFT_O365Group.psm1:83 char:13
+             [array]$ADGroup = Get-MgGroup -All:$true | Where-Object - ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ConsistencyLe...ndProperty =  }:<>f__AnonymousType84`9) 
[Get-MgGroup_List], Exception
    + FullyQualifiedErrorId : Authentication_ExpiredToken,Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List
Get-MgGroup : Your access token has expired. Please renew it before submitting the request.

Status: 401 (Unauthorized)
ErrorCode: Authentication_ExpiredToken
Date: 2023-07-31T13:47:40

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : <<<REDACTED>>>
client-request-id             : <<<REDACTED>>>
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"South Central US","Slice":"E","Ring":"5","ScaleUnit":"003","RoleInstance":"<<<REDACTED>>>"}}
Date                          : Mon, 31 Jul 2023 13:47:39 GMT
WWW-Authenticate              : Bearer realm="", authorization_uri="https://login.microsoftonline.com/common/oauth2/authorize", client_id="<<<REDACTED>>>"

At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.726.1\DSCResources\MSFT_O365Group\MSFT_O365Group.psm1:83 char:13
+             [array]$ADGroup = Get-MgGroup -All:$true | Where-Object - ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ConsistencyLe...ndProperty =  }:<>f__AnonymousType84`9) [Get-MgGroup_List], Exception
    + FullyQualifiedErrorId : Authentication_ExpiredToken,Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List
✅
    |---[466/3228] MC Members
Get-MgGroup : Access token has expired or is not yet valid.

Status: 401 (Unauthorized)
ErrorCode: InvalidAuthenticationToken
Date: 2023-07-31T13:47:41

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.17763.4644
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.17763.4644
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by andikrueger** [comment]
Is this still an issue with the latest version of M365DSC?

**Comment by skghq** [comment]
Fixed. Thanks!

**Comment by skghq** [comment]
Fixed. Thanks!
