### ISSUE TITLE
Authorization Policy Fails to deploy

### ISSUE THREAD

**Issue by JordyBlommaert95** [microsoft/Microsoft365DSC#3537]
### Description of the issue

The parameters are not accepted by the module Microsoft.Graph.Beta.Identity.SignIns

In the earlier MSGraph version, parameter can be a single hashtable:
[Parameter(ParameterSetName='
Update1
', Mandatory, ValueFromPipeline)]
    [Microsoft.Graph.PowerShell.Category('Body')]
    [Microsoft.Graph.PowerShell.Models.IMicrosoftGraphAuthorizationPolicy]
    # authorizationPolicy
    # To construct, please use Get-Help -Online and see NOTES section for BODYPARAMETER properties and create a hash table.
    ${BodyParameter}

In the new module it requires an additional parameter:
[Parameter(ParameterSetName='Update', Mandatory)]
    [Parameter(ParameterSetName='UpdateExpanded', Mandatory)]
    [Microsoft.Graph.Beta.PowerShell.Category('Path')]
    [System.String]
# The unique identifier of authorizationPolicy
    ${AuthorizationPolicyId},

 

    [Parameter(ParameterSetName='Update', Mandatory, ValueFromPipeline)]
    [Parameter(ParameterSetName='UpdateViaIdentity', Mandatory, ValueFromPipeline)]
    [Microsoft.Graph.Beta.PowerShell.Category('Body')]
    [Microsoft.Graph.Beta.PowerShell.Models.IMicrosoftGraphAuthorizationPolicy]
    # authorizationPolicy
    # To construct, see NOTES section for BODYPARAMETER properties and create a hash table.
    ${BodyParameter},

However, the DSC module only passes a single hashtable.

### Microsoft 365 DSC Version

1.23.726.1

### Which workloads are affected

Azure Active Directory

### The DSC configuration

Azure AD Schema file:
```
AADAuthorizationPolicy 'AADAuthPol'{
        IsSingleInstance                                  = 'Yes'
        DisplayName                                       = 'Authorization Policy'
        Description                                       = 'Used to manage authorization related settings across the company.'
        AllowEmailVerifiedUsersToJoinOrganization         = $true
        AllowInvitesFrom                                  = 'everyone'
        AllowedToSignUpEmailBasedSubscriptions            = $false
        AllowedToUseSspr                                  = $true
        BlockMsolPowerShell                               = $false
        DefaultUserRoleAllowedToCreateApps                = $false
        DefaultUserRoleAllowedToCreateSecurityGroups      = $true
        DefaultUserRoleAllowedToReadOtherUsers            = $false
        GuestUserRole                                     = 'Guest'
        PermissionGrantPolicyIdsAssignedToDefaultUserRole = @()
        Ensure                                            = 'Present'
        ApplicationId           = $ApplicationId
        TenantId                = $TenantId
        CertificateThumbprint   = $Thumbprint
    }
```

**Comment by ykuijs** [comment]
Have been testing with @JordyBlommaert95. Looks like this issue has been fixed in v1.23.809.1.
