### ISSUE TITLE
MSFT_MicrosoftGraphwindowsFirewallRule At least one of the values 'System.Object[]' is not  supported or valid for property

### ISSUE THREAD

**Issue by ChrisJay77** [microsoft/Microsoft365DSC#3546]
<!--
    Your feedback and support is greatly appreciated, thanks for contributing!

    ISSUE TITLE:
   Details of the scenario you tried and the problem that is occurring
i export the config using:
Export-M365DSCConfiguration -ApplicationId 0791df04-ee1a-4931-9995-XXXXX -TenantId XXXX.onmicrosoft.com -CertificateThumbprint XXXXXXXXXXXXXXXXXXX -Workloads @("intune") -Path C:\t1\july2023

After manually adding " to all the erros generated within the displayname of theMM365TenantConfig.ps1 the localhost.mof is genreated as localhost.mof.error

Verbose logs showing the problem

Microsoft365DSC\MSFT_MicrosoftGraphwindowsFirewallRule : At least one of the values 'System.Object[]' is not 
supported or valid for property 'Action' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify only 
supported values: 
notConfigured, blocked, allowed.
At C:\SIT\365Aug_Cert\M365TenantConfig.ps1:22011 char:17
+                 MSFT_MicrosoftGraphwindowsFirewallRule{
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,Microsoft365DSC\MSFT_MicrosoftGraphWindowsFirewallRule
 
Microsoft365DSC\MSFT_MicrosoftGraphwindowsFirewallRule : At least one of the values 'System.Object[]' is not 
supported or valid for property 'EdgeTraversal' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify 
only supported values: 
notConfigured, blocked, allowed.
At C:\SIT\365Aug_Cert\M365TenantConfig.ps1:22011 char:17
+                 MSFT_MicrosoftGraphwindowsFirewallRule{
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,Microsoft365DSC\MSFT_MicrosoftGraphWindowsFirewallRule
 
Microsoft365DSC\MSFT_MicrosoftGraphwindowsFirewallRule : At least one of the values 'System.Object[]' is not 
supported or valid for property 'InterfaceTypes' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify 
only supported values: 
notConfigured, remoteAccess, wireless, lan.
At C:\SIT\365Aug_Cert\M365TenantConfig.ps1:22011 char:17
+                 MSFT_MicrosoftGraphwindowsFirewallRule{
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,Microsoft365DSC\MSFT_MicrosoftGraphWindowsFirewallRule
 
Microsoft365DSC\MSFT_MicrosoftGraphwindowsFirewallRule : At least one of the values 'System.Object[]' is not 
supported or valid for property 'ProfileTypes' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify only 
supported values: 
notConfigured, domain, private, public.
At C:\SIT\365Aug_Cert\M365TenantConfig.ps1:22011 char:17
+                 MSFT_MicrosoftGraphwindowsFirewallRule{
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,Microsoft365DSC\MSFT_MicrosoftGraphWindowsFirewallRule
 
Microsoft365DSC\MSFT_MicrosoftGraphwindowsFirewallRule : At least one of the values 'System.Object[]' is not 
supported or valid for property 'TrafficDirection' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify 
only supported values: 
notConfigured, out, in.
At C:\SIT\365Aug_Cert\M365TenantConfig.ps1:22011 char:17
+                 MSFT_MicrosoftGraphwindowsFirewallRule{
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,Microsoft365DSC\MSFT_MicrosoftGraphWindowsFirewallRule
 
Microsoft365DSC\MSFT_MicrosoftGraphwindowsFirewallRule : At least one of the values 'System.Object[]' is not 
supported or valid for property 'Action' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify only 
supported values: 
notConfigured, blocked, allowed.
At C:\SIT\365Aug_Cert\M365TenantConfig.ps1:22035 char:17
+                 MSFT_MicrosoftGraphwindowsFirewallRule{
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,Microsoft365DSC\MSFT_MicrosoftGraphWindowsFirewallRule
 
Microsoft365DSC\MSFT_MicrosoftGraphwindowsFirewallRule : At least one of the values 'System.Object[]' is not 
supported or valid for property 'EdgeTraversal' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify 
only supported values: 
notConfigured, blocked, allowed.
At C:\SIT\365Aug_Cert\M365TenantConfig.ps1:22035 char:17
+                 MSFT_MicrosoftGraphwindowsFirewallRule{
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,Microsoft365DSC\MSFT_MicrosoftGraphWindowsFirewallRule
 
Microsoft365DSC\MSFT_MicrosoftGraphwindowsFirewallRule : At least one of the values 'System.Object[]' is not 
supported or valid for property 'InterfaceTypes' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify 
only supported values: 
notConfigured, remoteAccess, wireless, lan.
At C:\SIT\365Aug_Cert\M365TenantConfig.ps1:22035 char:17
+                 MSFT_MicrosoftGraphwindowsFirewallRule{
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,Microsoft365DSC\MSFT_MicrosoftGraphWindowsFirewallRule
 
Microsoft365DSC\MSFT_MicrosoftGraphwindowsFirewallRule : At least one of the values 'System.Object[]' is not 
supported or valid for property 'ProfileTypes' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify only 
supported values: 
notConfigured, domain, private, public.
At C:\SIT\365Aug_Cert\M365TenantConfig.ps1:22035 char:17
+                 MSFT_MicrosoftGraphwindowsFirewallRule{
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,Microsoft365DSC\MSFT_MicrosoftGraphWindowsFirewallRule
 
Microsoft365DSC\MSFT_MicrosoftGraphwindowsFirewallRule : At least one of the values 'System.Object[]' is not 
supported or valid for property 'TrafficDirection' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify 
only supported values: 
notConfigured, out, in.
At C:\SIT\365Aug_Cert\M365TenantConfig.ps1:22035 char:17
+                 MSFT_MicrosoftGraphwindowsFirewallRule{
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,Microsoft365DSC\MSFT_MicrosoftGraphWindowsFirewallRule
 
Write-NodeMOFFile : Invalid MOF definition for node 'localhost': Exception calling "ValidateInstanceText" with "1" 
argument(s): "Convert property 'Protocol' value from type 'SINT64[]' to type 'UINT32' failed
 At line:30727, char:2
 Buffer:
llow RemotePS"
};
};^
ins
"
At 
C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2369 
char:21
+ ...             Write-NodeMOFFile $Name $mofNode $Script:NodeInstanceAlia ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile

    Directory: C:\SIT\365Aug_Cert\M365TenantConfig

Mode                 LastWriteTime         Length Name                                                                
----                 -------------         ------ ----                                                                
-a----        03/08/2023     08:53        3984776 localhost.mof.error    

Suggested solution to the issue
t

The DSC configuration that is used to reproduce the issue (as detailed as possible)
# insert configuration here
The operating system the target node is running
Win10

Version of the DSC module that was used ('dev' if using current dev branch)
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.712.1

**Comment by andikrueger** [comment]
Closing due to missing description?
