### ISSUE TITLE
Problem with signature of MicrosoftTeams module version 5.4.0

### ISSUE THREAD

**Issue by BostjanGspan** [microsoft/Microsoft365DSC#3548]
### Description of the issue

PS C:\WINDOWS\system32> Update-M365DSCDependencies
Installing MicrosoftTeams version {5.4.0}
PackageManagement\Install-Package : The module 'MicrosoftTeams' cannot be installed or updated because the authenticode
 signature of the file 'MicrosoftTeams.psd1' is not valid.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.P
   ackageManagement.Cmdlets.InstallPackage

There new MicrosoftTeams module current version in PSgallery which is 5.5.0

### Microsoft 365 DSC Version

V1.23.726.1

### Which workloads are affected

Teams

### The DSC configuration

N/A

### Verbose logs showing the problem

PS C:\WINDOWS\system32> Update-M365DSCDependencies
Installing MicrosoftTeams version {5.4.0}
PackageManagement\Install-Package : The module 'MicrosoftTeams' cannot be installed or updated because the authenticode
 signature of the file 'MicrosoftTeams.psd1' is not valid.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.P
   ackageManagement.Cmdlets.InstallPackage

### Environment Information + PowerShell Version

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.22621.1830
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1830
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Rayyanbaig1243** [comment]
I have updated this file

**Comment by BostjanGspan** [comment]
[heart]         Bostjan Gspan reacted to your message:
________________________________

**Comment by BostjanGspan** [comment]
> I have updated this file

I see MicrosoftTeams module v.5.5.0 as being current, which is great.
I must be doing something wrong because Update-M365DSCDependencies still looks for version 5.4.0.

**Comment by BostjanGspan** [comment]
Update-M365DSCDependencies still looks for version 5.4.0.

**Comment by andikrueger** [comment]
This should be fixed with today's release. #3571

**Comment by BostjanGspan** [comment]
I can confirm that it works for me now. Thank you
