### ISSUE TITLE
Connecting to PnP fails

### ISSUE THREAD

**Issue by dt-flo** [microsoft/Microsoft365DSC#3558]
### Description of the issue

Hello,

I'm trying to export certain configurations with the following command:
```
[pscredential]$Credential = New-Object System.Management.Automation.PSCredential ($userName, $secStringPassword)
Export-M365DSCConfiguration -Components @("O365AdminAuditLogConfig", "O365OrgCustomizationSetting", "O365OrgSettings", "O365SearchAndIntelligenceConfigurations", "ODSettings") -Credential $Credential
```
This fails with the following errors:
```
PS >.\export-m365dsc.ps1
Exporting Microsoft 365 configuration for Components: O365AdminAuditLogConfig, O365OrgCustomizationSetting, O365OrgSettings, O365SearchAndIntelligenceConfigurations, ODSettings

Authentication methods specified:
- Credentials

Connecting to {ExchangeOnline}...✅
Connecting to {PnP}...WARNING:
A newer version of PnP PowerShell is available: 2.2.0.

Use 'Update-Module -Name PnP.PowerShell' to update.
Use 'Get-PnPChangeLog -Release 2.2.0' to list changes.

You can turn this check off by setting the 'PNPPOWERSHELL_UPDATECHECK' environment variable to 'Off'.

✅
[1/5] Extracting [O365AdminAuditLogConfig] using {Credentials}... Error Log created at {file://H:/...tmp/23912-M365DSC-ErrorLog.log}
Partial Export file was saved at: C:\...\AppData\Local\Temp\d943dbfe-0a06-4f3f-a4a6-41e35d97cd9c.partial.ps1
Exception: The following dependencies need updating:     * MSCloudLoginAssistant     * PnP.PowerShell Please run
Update-M365DSCDependencies as Administrator.Please run Uninstall-M365DSCOutdatedDependencies.
PS >
```
Those are my modules in PS7:
[modules_ps7_json.txt](https://github.com/microsoft/Microsoft365DSC/files/12290889/modules_ps7_json.txt)

In ps5 I have those modules:
[modules_ps5_json.txt](https://github.com/microsoft/Microsoft365DSC/files/12290947/modules_ps5_json.txt)

"Update-M365DSCDependencies" doesn't do anything useful, since it only downgrades MSCloudLoginAssistant which breaks loggin in as a SP and downgrades PnP.PowerShell in PS7 which doesnt make sense because from what I understood, PnP.PowerShell isnt used from the PS7 Module directory, it uses the module from the PS5 directory. 

Even if i DID run "Update-M365DSCDependencies" the packages would be installed but some other error would occur that the process failed.

Can someone from the team please try to use the Microsoft365DSC tool with PS 7.3.6 and and all up-to-date modules and tell me what I need to do to get it to run.

### Microsoft 365 DSC Version

1.23.726.1

### Which workloads are affected

Office 365 Admin

**Comment by dt-flo** [comment]
For the record, after I ran "Update-M365DSCDependencies" I got those errors:
```
PS >.\export-m365dsc.ps1
Exporting Microsoft 365 configuration for Components: O365AdminAuditLogConfig, O365OrgCustomizationSetting, O365OrgSettings, O365SearchAndIntelligenceConfigurations, ODSettings

Authentication methods specified:
- Credentials

Connecting to {ExchangeOnline}...✅
Connecting to {PnP}...WARNING:
A newer version of PnP PowerShell is available: 2.2.0.

Use 'Update-Module -Name PnP.PowerShell' to update.
Use 'Get-PnPChangeLog -Release 2.2.0' to list changes.

You can turn this check off by setting the 'PNPPOWERSHELL_UPDATECHECK' environment variable to 'Off'.

✅
[1/5] Extracting [O365AdminAuditLogConfig] using {Credentials}...✅
[2/5] Extracting [O365OrgCustomizationSetting] using {Credentials}...✅
[3/5] Extracting [O365OrgSettings] using {Credentials}... Error Log created at {file://H:/Users/.../20148-M365DSC-ErrorLog.log}
✅
[4/5] Extracting [O365SearchAndIntelligenceConfigurations] using {Credentials}... Error Log created at {file://.../tmp/20148-M365DSC-ErrorLog.log}
✅
[5/5] Extracting [ODSettings] using {Credentials}... Error Log created at {file://H:/.../tmp/20148-M365DSC-ErrorLog.log}
✅
⌛ Export took {41 seconds}

Destination Path:
PS >
```

**Comment by andikrueger** [comment]
Please review this article for PS 7.x : https://microsoft365dsc.com/user-guide/get-started/powershell7-support/

Right now, there are still some limitations with PS7. In general: Please make sure to only have the M365DSC supported versions of the dependent modules installed. For PnP PowerShell, we currently require the pre V2 version.

**Comment by dt-flo** [comment]
> Please review this article for PS 7.x : https://microsoft365dsc.com/user-guide/get-started/powershell7-support/
> 
> Right now, there are still some limitations with PS7. In general: Please make sure to only have the M365DSC supported versions of the dependent modules installed. For PnP PowerShell, we currently require the pre V2 version.

Yes, as I said, I also ran "Update-M365DSCDependencies" which installed the requires versions, however, it still did not work. Can you please try it out yourself and report to me if it works for you?

**Comment by dt-flo** [comment]
> > Please review this article for PS 7.x : https://microsoft365dsc.com/user-guide/get-started/powershell7-support/
> > Right now, there are still some limitations with PS7. In general: Please make sure to only have the M365DSC supported versions of the dependent modules installed. For PnP PowerShell, we currently require the pre V2 version.
> 
> Yes, as I said, I also ran "Update-M365DSCDependencies" which installed the required versions, however, it still did not work. Can you please try it out yourself and report to me if it works for you?

And please provide a list of the installed modules and the versions for which the export works.

**Comment by andikrueger** [comment]
Could you share the output of run in PS 5 and PS 7?

Get-Module -ListAvailable

**Comment by dt-flo** [comment]
[ps7-get-module.txt](https://github.com/microsoft/Microsoft365DSC/files/12367201/ps7-get-module.txt)
[ps5-get-module.txt](https://github.com/microsoft/Microsoft365DSC/files/12367202/ps5-get-module.txt)

**Comment by dt-flo** [comment]
> Could you share the output of run in PS 5 and PS 7?
> 
> Get-Module -ListAvailable

Hello, i havent heard from you for a while. Are my installed packages correct?

**Comment by andikrueger** [comment]
@dt-flo Are you still struggling the with setup of Microsoft 365 DSC? 

Please make sure to update to the latest version of Microsoft 365 DSC and install the dependencies in the required version with `Update-M365DSCDependencies` and `Uninstall-M365DSCOutdatedDependencies`
