### ISSUE TITLE
DEVOPS  'AzureAD\AzureAD' is not recognized

### ISSUE THREAD

**Issue by stvnmbr1** [microsoft/Microsoft365DSC#3566]
### Description of the issue

followed the devops whitepaper

i would like to add conditional access but i am unable to get the azuread module working.

##[error]The term 'AzureAD\AzureAD' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Microsoft 365 DSC Version

1.22.1019.1

### Which workloads are affected

Azure Active Directory, other

### The DSC configuration

AzureAD.ps1

@{
    RootModule           = 'AzureAD.schema.psm1'

    ModuleVersion        = '0.0.1'

    GUID                 = '59330cae-baea-49af-97f1-fdb1faf6307b'

    Author               = 'Yorick Kuijs'

    CompanyName          = 'Microsoft'

    Copyright            = 'Copyright to Microsoft Corporation. All rights reserved.'

    #RequiredModules      = @(
    #    @{ ModuleName = 'xPSDesiredStateConfiguration'; ModuleVersion = '8.4.0.0' }
    #)

    DscResourcesToExport = @('AzureAD')
}

**AzureAD.schema.psm1**

Configuration AzureAD
{
    param
    (
        [Parameter()]
        [PSCredential]
        $Credential,

        [Parameter()]
        [System.String]
        $ApplicationId,

        [Parameter()]
        [System.String]
        $TenantId,

        [Parameter()]
        [System.String]
        $Thumbprint
    )

    Import-DscResource -ModuleName Microsoft365DSC

    $paramCount = ($PSBoundParameters.GetEnumerator() | Where-Object -FilterScript { $_.Key -in 'ApplicationId', 'TenantId', 'Thumbprint' }).Count
    if ($paramCount -gt 0 -and $paramCount -lt 3)
    {
        throw "Please specify ApplicationId, TenantId and Thumbprint"
    }

    AADConditionalAccessPolicy "AADConditionalAccessPolicy-CA001 | Security Defaults | Block legacy authentication"
    {
        ApplicationEnforcedRestrictionsIsEnabled = $False;
        BuiltInControls                          = @("block");
        ClientAppTypes                           = @("exchangeActiveSync","other");
        CloudAppSecurityIsEnabled                = $False;
        CloudAppSecurityType                     = "";
        Credential                               = $Credential;
        CustomAuthenticationFactors              = @();
        DeviceFilterRule                         = "";
        DisplayName                              = "CA001 | Security Defaults | Block legacy authentication";
        Ensure                                   = "Present";
        ExcludeApplications                      = @();
        ExcludeExternalTenantsMembers            = @();
        ExcludeExternalTenantsMembershipKind     = "";
        ExcludeGroups                            = @();
        ExcludeLocations                         = @();
        ExcludePlatforms                         = @();
        ExcludeRoles                             = @();
        ExcludeUsers                             = @();
        GrantControlOperator                     = "OR";
        Id                                       = "d87c9e06-99d5-4dc6-a8de-abde7d3f384e";
        IncludeApplications                      = @("All");
        IncludeExternalTenantsMembers            = @();
        IncludeExternalTenantsMembershipKind     = "";
        IncludeGroups                            = @();
        IncludeLocations                         = @();
        IncludePlatforms                         = @();
        IncludeRoles                             = @();
        IncludeUserActions                       = @();
        IncludeUsers                             = @("All");
        PersistentBrowserIsEnabled               = $False;
        PersistentBrowserMode                    = "";
        SignInFrequencyIsEnabled                 = $False;
        SignInFrequencyType                      = "";
        SignInRiskLevels                         = @();
        State                                    = "enabled";
        UserRiskLevels                           = @();
    }

}

**M365Configuration**

Configuration M365Configuration
{
    param
    (
        [Parameter(Mandatory = $true)]
        [System.Collections.Hashtable]
        $Credentials
    )

    Import-DscResource -ModuleName M365Config

    node localhost
    {
        $azureadAppCreds = $ConfigurationData.NonNodeData.AppCredentials | Where-Object -FilterScript { $_.Workload -eq 'AzureAD' }
        $exchangeAppCreds = $ConfigurationData.NonNodeData.AppCredentials | Where-Object -FilterScript { $_.Workload -eq 'Exchange' }
        $officeAppCreds = $ConfigurationData.NonNodeData.AppCredentials | Where-Object -FilterScript { $_.Workload -eq 'Office365' }
        $powerplatformAppCreds = $ConfigurationData.NonNodeData.AppCredentials | Where-Object -FilterScript { $_.Workload -eq 'PowerPlatform' }
        $securitycomplianceAppCreds = $ConfigurationData.NonNodeData.AppCredentials | Where-Object -FilterScript { $_.Workload -eq 'SecurityCompliance' }
        $sharepointAppCreds = $ConfigurationData.NonNodeData.AppCredentials | Where-Object -FilterScript { $_.Workload -eq 'SharePoint' }
        $teamsAppCreds = $ConfigurationData.NonNodeData.AppCredentials | Where-Object -FilterScript { $_.Workload -eq 'Teams' }

        AzureAD 'AzureAD_Configuration'
        {
            Credential    = $Credentials.AzureAD
            ApplicationId = $azureadAppCreds.ApplicationId
            TenantId      = $ConfigurationData.NonNodeData.Environment.TenantId
            Thumbprint    = $azureadAppCreds.CertThumbprint
        }

 
        Exchange 'Exchange_Configuration'
        {
            Credential    = $Credentials.Exchange
            ApplicationId = $exchangeAppCreds.ApplicationId
            TenantId      = $ConfigurationData.NonNodeData.Environment.TenantId
            Thumbprint    = $exchangeAppCreds.CertThumbprint
        }

        Office365 'Office365_Configuration'
        {
            Credential    = $Credentials.Office365
            ApplicationId = $officeAppCreds.ApplicationId
            TenantId      = $ConfigurationData.NonNodeData.Environment.TenantId
            Thumbprint    = $officeAppCreds.CertThumbprint
        }

        PowerPlatform 'PowerPlatform_Configuration'
        {
            Credential    = $Credentials.PowerPlatform
            ApplicationId = $powerplatformAppCreds.ApplicationId
            TenantId      = $ConfigurationData.NonNodeData.Environment.TenantId
            Thumbprint    = $powerplatformAppCreds.CertThumbprint
        }

        SecurityCompliance 'SecurityCompliance_Configuration'
        {
            Credential    = $Credentials.SecurityCompliance
            ApplicationId = $securitycomplianceAppCreds.ApplicationId
            TenantId      = $ConfigurationData.NonNodeData.Environment.TenantId
            Thumbprint    = $securitycomplianceAppCreds.CertThumbprint
        }

        SharePoint 'SharePoint_Configuration'
        {
            Credential    = $Credentials.SharePoint
            ApplicationId = $sharepointAppCreds.ApplicationId
            TenantId      = $ConfigurationData.NonNodeData.Environment.TenantId
            Thumbprint    = $sharepointAppCreds.CertThumbprint
        }

        Teams 'Teams_Configuration'
        {
            Credential    = $Credentials.Teams
            ApplicationId = $teamsAppCreds.ApplicationId
            TenantId      = $ConfigurationData.NonNodeData.Environment.TenantId
            Thumbprint    = $teamsAppCreds.CertThumbprint
        }
    }
}

### Verbose logs showing the problem

##[error]The term 'AzureAD\AzureAD' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Environment Information + PowerShell Version

```powershell
Latest powershell version

selfhosted agent
```

**Comment by stvnmbr1** [comment]
similar issue to https://github.com/microsoft/Microsoft365DSC/issues/3214

**Comment by stvnmbr1** [comment]
i already saw https://github.com/microsoft/Microsoft365DSC/issues/2742
But no extra info provided

**Comment by JordyBlommaert95** [comment]
Hello Can you first try to use a more recent version of DSC.
The whitepaper uses an older DSC version.

**Comment by stvnmbr1** [comment]
> Hello Can you first try to use a more recent version of DSC. The whitepaper uses an older DSC version.

thanks! we got a bit further now, don't know how i missed the version... now i get this on version 1.23.726.1
##[error]The module 'Teams' could not be loaded. For more information, run 'Import-Module Teams'.

checking further

**Comment by stvnmbr1** [comment]
> > > Hello Can you first try to use a more recent version of DSC. The whitepaper uses an older DSC version.
> > 
> > 
> > thanks! we got a bit further now, don't know how i missed the version... now i get this on version 1.23.726.1 ##[error]The module 'Teams' could not be loaded. For more information, run 'Import-Module Teams'.
> > checking further
> 
> Hello, it can be possible that there in the meantime some deprecated parameters in Teams that you need to remove. What I recommend is to review the release notes: https://github.com/microsoft/Microsoft365DSC/releases Check the release notes between the current version and the version you were using to see if there are any depreacted parameters mentioned in the release notes.

thanks! seems like RecordingStorageMode was deprecated, remove it and seems to run succesful now.

**Comment by stvnmbr1** [comment]
closing this as i have resolved the issue. Thanks again for the advice!

whitepaper docs/scripts are bit outdated and could use an extra guidelines to add more workloads
