### ISSUE TITLE
Test-TargetResource. Error message: The following dependencies need updating:

### ISSUE THREAD

**Issue by fsecchia** [microsoft/Microsoft365DSC#3574]
#### Details of the scenario you tried and the problem that is occurring
Start-DSCConfiguration -Path "$($mof_path)\M365TenantConfig" -Wait -Verbose -Force

#### Verbose logs showing the problem
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =                                SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =                                root/Microsoft/Windows/DesiredStateConfiguration'.                                                                      VERBOSE: Chiamata di metodo LCM attivata dal computer LAPDLP01-PILOT con SID utente                                     S-1-12-1-3666433436-1150239269-1000545691-4220511640.                                                                   VERBOSE: [LAPDLP01-PILOT]: LCM:  [ Inizio Imposta  ]                                                                    VERBOSE: [LAPDLP01-PILOT]: LCM:  [ Inizio Risorsa  ]                                                                    [[AADAuthenticationMethodPolicy]AADAuthenticationMethodPolicy-Authentication Methods Policy]                            VERBOSE: [LAPDLP01-PILOT]: LCM:  [ Inizio Prova    ]                                                                    [[AADAuthenticationMethodPolicy]AADAuthenticationMethodPolicy-Authentication Methods Policy]                            VERBOSE: [LAPDLP01-PILOT]: LCM:  [ Fine   Prova    ]                                                                    [[AADAuthenticationMethodPolicy]AADAuthenticationMethodPolicy-Authentication Methods Policy]  in 11.1230 secondi.       La risorsa PowerShell DSC MSFT_AADAuthenticationMethodPolicy non è in grado di eseguire la funzionalità                 Test-TargetResource. Messaggio di errore: The following dependencies need updating:                                         * Microsoft.Graph.Applications                                                                                          * Microsoft.Graph.Authentication                                                                                        * Microsoft.Graph.DeviceManagement.Administration                                                                       * Microsoft.Graph.Groups                                                                                                * Microsoft.Graph.Planner                                                                                               * Microsoft.Graph.Users                                                                                                 * Microsoft.Graph.Users.Actions                                                                                         * PnP.PowerShell                                                                                                    Please run Update-M365DSCDependencies as Administrator.Please run Uninstall-M365DSCOutdatedDependencies.                    + CategoryInfo          : InvalidOperation: (:) [], CimException                                                        + FullyQualifiedErrorId : ProviderOperationExecutionFailure                                                             + PSComputerName        : localhost           
#### Suggested solution to the issue
Update-M365DSCDependencies --> No Dependencies to update
Uninstall-M365DSCOutdatedDependencies --> Checking Microsoft.Graph.Authentication (result)
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Both 5 and 7 versions 
PS C:\Users\Admin-FS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3031
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3031
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PowerShell 7.3.6
PS C:\Users\Admin-FS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

# insert configuration here
```
@{
    AllNodes = @(
        @{
            NodeName                    = "localhost"
            PSDscAllowPlainTextPassword = $true;
            PSDscAllowDomainUser        = $true;
            #region Parameters
            # Default Value Used to Ensure a Configuration Data File is Generated
            ServerNumber = "0"

        }
    )
    NonNodeData = @(
        @{
            # Tenant's default verified domain name
            OrganizationName = "rsrj.onmicrosoft.com"

            # Azure AD Application Id for Authentication
            ApplicationId = "*****"

            # The Id or Name of the tenant to authenticate against
            TenantId = "rsrj.onmicrosoft.com"

            # Azure AD Application Secret for Authentication
            ApplicationSecret = "*********"

        }
    )
}

localhost.mof
/*
@TargetNode='localhost'
@GeneratedBy=Admin-FS
@GenerationDate=08/14/2023 16:09:41
@GenerationHost=LAPDLP01-PILOT
*/

instance of MSFT_MicrosoftGraphAuthenticationMethodsRegistrationCampaignIncludeTarget as $MSFT_MicrosoftGraphAuthenticationMethodsRegistrationCampaignIncludeTarget1ref
{
TargetedAuthenticationMethod = "microsoftAuthenticator";
 TargetType = "group";
 Id = "all_users";

};

instance of MSFT_MicrosoftGraphAuthenticationMethodsRegistrationCampaign as $MSFT_MicrosoftGraphAuthenticationMethodsRegistrationCampaign1ref
{
SnoozeDurationInDays = 1;
 IncludeTargets = {
    $MSFT_MicrosoftGraphAuthenticationMethodsRegistrationCampaignIncludeTarget1ref
};
 State = "default";

};

instance of MSFT_MicrosoftGraphRegistrationEnforcement as $MSFT_MicrosoftGraphRegistrationEnforcement1ref
{
AuthenticationMethodsRegistrationCampaign = $MSFT_MicrosoftGraphAuthenticationMethodsRegistrationCampaign1ref;

};

instance of MSFT_AADAuthenticationMethodPolicyIncludeTarget as $MSFT_AADAuthenticationMethodPolicyIncludeTarget1ref
{
Id = "all_users";
 TargetType = "group";

};

instance of MSFT_MicrosoftGraphSystemCredentialPreferences as $MSFT_MicrosoftGraphSystemCredentialPreferences1ref
{
State = "default";
 IncludeTargets = {
    $MSFT_AADAuthenticationMethodPolicyIncludeTarget1ref
};

};

instance of MSFT_Credential as $MSFT_Credential1ref
{
Password = "**********";
 UserName = "ApplicationSecret";

};

instance of MSFT_AADAuthenticationMethodPolicy as $MSFT_AADAuthenticationMethodPolicy1ref
{
ApplicationSecret = $MSFT_Credential1ref;
 Id = "authenticationMethodsPolicy";
 TenantId = "rsrj.onmicrosoft.com";
 DisplayName = "Authentication Methods Policy";
 SystemCredentialPreferences = $MSFT_MicrosoftGraphSystemCredentialPreferences1ref;
 PolicyMigrationState = "preMigration";
 ResourceID = "[AADAuthenticationMethodPolicy]AADAuthenticationMethodPolicy-Authentication Methods Policy";
 Ensure = "Present";
 SourceInfo = "C:\\M365DSC\\RSRJ\\aad\\test\\M365TenantConfig.ps1::17::9::AADAuthenticationMethodPolicy";
 ModuleName = "Microsoft365DSC";
 Description = "The tenant-wide policy that controls which authentication methods are allowed in the tenant, authentication method registration requirements, and self-service password reset settings";
 ModuleVersion = "1.23.809.1";
 RegistrationEnforcement = $MSFT_MicrosoftGraphRegistrationEnforcement1ref;
 PolicyVersion = "1.4";
 ApplicationId = "29e61b7f-159d-4c80-8471-c9e0618ccd57";

 ConfigurationName = "M365TenantConfig";

};
instance of MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget as $MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget1ref
{
Id = "00000000-0000-0000-0000-000000000000";
 TargetType = "group";

};

instance of MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget as $MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget2ref
{
Id = "all_users";
 TargetType = "group";

};

instance of MSFT_MicrosoftGraphAuthenticationMethodFeatureConfiguration as $MSFT_MicrosoftGraphAuthenticationMethodFeatureConfiguration1ref
{
ExcludeTarget = $MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget1ref;
 IncludeTarget = $MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget2ref;
 State = "default";

};

instance of MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget as $MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget3ref
{
Id = "00000000-0000-0000-0000-000000000000";
 TargetType = "group";

};

instance of MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget as $MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget4ref
{
Id = "all_users";
 TargetType = "group";

};

instance of MSFT_MicrosoftGraphAuthenticationMethodFeatureConfiguration as $MSFT_MicrosoftGraphAuthenticationMethodFeatureConfiguration2ref
{
ExcludeTarget = $MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget3ref;
 IncludeTarget = $MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget4ref;
 State = "default";

};

instance of MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget as $MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget5ref
{
Id = "00000000-0000-0000-0000-000000000000";
 TargetType = "group";

};

instance of MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget as $MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget6ref
{
Id = "all_users";
 TargetType = "group";

};

instance of MSFT_MicrosoftGraphAuthenticationMethodFeatureConfiguration as $MSFT_MicrosoftGraphAuthenticationMethodFeatureConfiguration3ref
{
ExcludeTarget = $MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget5ref;
 IncludeTarget = $MSFT_AADAuthenticationMethodPolicyAuthenticatorFeatureTarget6ref;
 State = "default";

};

instance of MSFT_MicrosoftGraphMicrosoftAuthenticatorFeatureSettings as $MSFT_MicrosoftGraphMicrosoftAuthenticatorFeatureSettings1ref
{
DisplayLocationInformationRequiredState = $MSFT_MicrosoftGraphAuthenticationMethodFeatureConfiguration1ref;
 CompanionAppAllowedState = $MSFT_MicrosoftGraphAuthenticationMethodFeatureConfiguration2ref;
 DisplayAppInformationRequiredState = $MSFT_MicrosoftGraphAuthenticationMethodFeatureConfiguration3ref;

};

instance of MSFT_AADAuthenticationMethodPolicyAuthenticatorIncludeTarget as $MSFT_AADAuthenticationMethodPolicyAuthenticatorIncludeTarget1ref
{
Id = "all_users";
 TargetType = "group";

};

instance of MSFT_Credential as $MSFT_Credential2ref
{
Password = "**********";
 UserName = "ApplicationSecret";

};

instance of MSFT_AADAuthenticationMethodPolicyAuthenticator as $MSFT_AADAuthenticationMethodPolicyAuthenticator1ref
{
TenantId = "rsrj.onmicrosoft.com";
 Id = "MicrosoftAuthenticator";
 IncludeTargets = {
    $MSFT_AADAuthenticationMethodPolicyAuthenticatorIncludeTarget1ref
};
 ResourceID = "[AADAuthenticationMethodPolicyAuthenticator]AADAuthenticationMethodPolicyAuthenticator-MicrosoftAuthenticator";
 Ensure = "Present";
 SourceInfo = "C:\\M365DSC\\RSRJ\\aad\\test\\M365TenantConfig.ps1::59::9::AADAuthenticationMethodPolicyAuthenticator";
 IsSoftwareOathEnabled = False;
 FeatureSettings = $MSFT_MicrosoftGraphMicrosoftAuthenticatorFeatureSettings1ref;
 ApplicationId = "**********";
 ModuleVersion = "1.23.809.1";
 ModuleName = "Microsoft365DSC";
 State = "enabled";
 ApplicationSecret = $MSFT_Credential2ref;

 ConfigurationName = "M365TenantConfig";

};
instance of MSFT_Credential as $MSFT_Credential3ref
{
Password = "*******";
 UserName = "ApplicationSecret";

};

instance of MSFT_AADAuthenticationMethodPolicyEmail as $MSFT_AADAuthenticationMethodPolicyEmail1ref
{
ResourceID = "[AADAuthenticationMethodPolicyEmail]AADAuthenticationMethodPolicyEmail-Email";
 State = "disabled";
 ApplicationSecret = $MSFT_Credential3ref;
 Id = "Email";
 Ensure = "Present";
 ApplicationId = "29e61b7f-159d-4c80-8471-c9e0618ccd57";
 SourceInfo = "C:\\M365DSC\\RSRJ\\aad\\test\\M365TenantConfig.ps1::120::9::AADAuthenticationMethodPolicyEmail";
 AllowExternalIdToUseEmailOtp = "disabled";
 TenantId = "rsrj.onmicrosoft.com";
 ModuleName = "Microsoft365DSC";
 ModuleVersion = "1.23.809.1";

 ConfigurationName = "M365TenantConfig";

};
instance of MSFT_AADAuthenticationMethodPolicyFido2IncludeTarget as $MSFT_AADAuthenticationMethodPolicyFido2IncludeTarget1ref
{
Id = "all_users";
 TargetType = "group";

};

instance of MSFT_MicrosoftGraphFido2KeyRestrictions as $MSFT_MicrosoftGraphFido2KeyRestrictions1ref
{
IsEnforced = False;
 EnforcementType = "block";
 AaGuids = {
};

};

instance of MSFT_Credential as $MSFT_Credential4ref
{
Password = "************";
 UserName = "ApplicationSecret";

};

instance of MSFT_AADAuthenticationMethodPolicyFido2 as $MSFT_AADAuthenticationMethodPolicyFido21ref
{
IsAttestationEnforced = True;
 Id = "Fido2";
 TenantId = "rsrj.onmicrosoft.com";
 Ensure = "Present";
 ApplicationSecret = $MSFT_Credential4ref;
 IncludeTargets = {
    $MSFT_AADAuthenticationMethodPolicyFido2IncludeTarget1ref
};
 ResourceID = "[AADAuthenticationMethodPolicyFido2]AADAuthenticationMethodPolicyFido2-Fido2";
 IsSelfServiceRegistrationAllowed = True;
 KeyRestrictions = $MSFT_MicrosoftGraphFido2KeyRestrictions1ref;
 SourceInfo = "C:\\M365DSC\\RSRJ\\aad\\test\\M365TenantConfig.ps1::130::9::AADAuthenticationMethodPolicyFido2";
 State = "disabled";
 ModuleVersion = "1.23.809.1";
 ModuleName = "Microsoft365DSC";
 ApplicationId = "29e61b7f-159d-4c80-8471-c9e0618ccd57";

 ConfigurationName = "M365TenantConfig";

};
instance of MSFT_AADAuthenticationMethodPolicySmsIncludeTarget as $MSFT_AADAuthenticationMethodPolicySmsIncludeTarget1ref
{
Id = "all_users";
 TargetType = "group";

};

instance of MSFT_Credential as $MSFT_Credential5ref
{
Password = "*********";
 UserName = "ApplicationSecret";

};

instance of MSFT_AADAuthenticationMethodPolicySms as $MSFT_AADAuthenticationMethodPolicySms1ref
{
ResourceID = "[AADAuthenticationMethodPolicySms]AADAuthenticationMethodPolicySms-Sms";
 State = "disabled";
 ApplicationSecret = $MSFT_Credential5ref;
 Id = "Sms";
 Ensure = "Present";
 IncludeTargets = {
    $MSFT_AADAuthenticationMethodPolicySmsIncludeTarget1ref
};
 ApplicationId = "29e61b7f-159d-4c80-8471-c9e0618ccd57";
 SourceInfo = "C:\\M365DSC\\RSRJ\\aad\\test\\M365TenantConfig.ps1::152::9::AADAuthenticationMethodPolicySms";
 TenantId = "rsrj.onmicrosoft.com";
 ModuleName = "Microsoft365DSC";
 ModuleVersion = "1.23.809.1";

 ConfigurationName = "M365TenantConfig";

};
instance of MSFT_AADAuthenticationMethodPolicySoftwareIncludeTarget as $MSFT_AADAuthenticationMethodPolicySoftwareIncludeTarget1ref
{
Id = "all_users";
 TargetType = "group";

};

instance of MSFT_Credential as $MSFT_Credential6ref
{
Password = "************";
 UserName = "ApplicationSecret";

};

instance of MSFT_AADAuthenticationMethodPolicySoftware as $MSFT_AADAuthenticationMethodPolicySoftware1ref
{
ResourceID = "[AADAuthenticationMethodPolicySoftware]AADAuthenticationMethodPolicySoftware-SoftwareOath";
 State = "disabled";
 ApplicationSecret = $MSFT_Credential6ref;
 Id = "SoftwareOath";
 Ensure = "Present";
 IncludeTargets = {
    $MSFT_AADAuthenticationMethodPolicySoftwareIncludeTarget1ref
};
 ApplicationId = "29e61b7f-159d-4c80-8471-c9e0618ccd57";
 SourceInfo = "C:\\M365DSC\\RSRJ\\aad\\test\\M365TenantConfig.ps1::167::9::AADAuthenticationMethodPolicySoftware";
 TenantId = "rsrj.onmicrosoft.com";
 ModuleName = "Microsoft365DSC";
 ModuleVersion = "1.23.809.1";

 ConfigurationName = "M365TenantConfig";

};
instance of MSFT_AADAuthenticationMethodPolicyTemporaryIncludeTarget as $MSFT_AADAuthenticationMethodPolicyTemporaryIncludeTarget1ref
{
Id = "all_users";
 TargetType = "group";

};

instance of MSFT_Credential as $MSFT_Credential7ref
{
Password = "*********";
 UserName = "ApplicationSecret";

};

instance of MSFT_AADAuthenticationMethodPolicyTemporary as $MSFT_AADAuthenticationMethodPolicyTemporary1ref
{
ApplicationSecret = $MSFT_Credential7ref;
 DefaultLength = 8;
 Id = "TemporaryAccessPass";
 TenantId = "rsrj.onmicrosoft.com";
 ResourceID = "[AADAuthenticationMethodPolicyTemporary]AADAuthenticationMethodPolicyTemporary-TemporaryAccessPass";
 MaximumLifetimeInMinutes = 480;
 MinimumLifetimeInMinutes = 60;
 Ensure = "Present";
 IncludeTargets = {
    $MSFT_AADAuthenticationMethodPolicyTemporaryIncludeTarget1ref
};
 SourceInfo = "C:\\M365DSC\\RSRJ\\aad\\test\\M365TenantConfig.ps1::182::9::AADAuthenticationMethodPolicyTemporary";
 DefaultLifetimeInMinutes = 60;
 State = "enabled";
 ModuleVersion = "1.23.809.1";
 ModuleName = "Microsoft365DSC";
 IsUsableOnce = False;
 ApplicationId = "29e61b7f-159d-4c80-8471-c9e0618ccd57";

 ConfigurationName = "M365TenantConfig";

};
instance of MSFT_AADAuthenticationMethodPolicyVoiceIncludeTarget as $MSFT_AADAuthenticationMethodPolicyVoiceIncludeTarget1ref
{
Id = "all_users";
 TargetType = "group";

};

instance of MSFT_Credential as $MSFT_Credential8ref
{
Password = "************";
 UserName = "ApplicationSecret";

};

instance of MSFT_AADAuthenticationMethodPolicyVoice as $MSFT_AADAuthenticationMethodPolicyVoice1ref
{
ResourceID = "[AADAuthenticationMethodPolicyVoice]AADAuthenticationMethodPolicyVoice-Voice";
 State = "disabled";
 ApplicationSecret = $MSFT_Credential8ref;
 Id = "Voice";
 Ensure = "Present";
 IncludeTargets = {
    $MSFT_AADAuthenticationMethodPolicyVoiceIncludeTarget1ref
};
 ApplicationId = "29e61b7f-159d-4c80-8471-c9e0618ccd57";
 IsOfficePhoneAllowed = False;
 TenantId = "rsrj.onmicrosoft.com";
 ModuleName = "Microsoft365DSC";
 SourceInfo = "C:\\M365DSC\\RSRJ\\aad\\test\\M365TenantConfig.ps1::202::9::AADAuthenticationMethodPolicyVoice";
 ModuleVersion = "1.23.809.1";

 ConfigurationName = "M365TenantConfig";

};
instance of MSFT_MicrosoftGraphX509CertificateAuthenticationModeConfiguration as $MSFT_MicrosoftGraphX509CertificateAuthenticationModeConfiguration1ref
{
Rules = {
};
 X509CertificateAuthenticationDefaultMode = "x509CertificateSingleFactor";

};

instance of MSFT_MicrosoftGraphX509CertificateUserBinding as $MSFT_MicrosoftGraphX509CertificateUserBinding1ref
{
Priority = 1;
 UserProperty = "onPremisesUserPrincipalName";
 X509CertificateField = "PrincipalName";

};

instance of MSFT_MicrosoftGraphX509CertificateUserBinding as $MSFT_MicrosoftGraphX509CertificateUserBinding2ref
{
Priority = 2;
 UserProperty = "userPrincipalName";
 X509CertificateField = "RFC822Name";

};

instance of MSFT_AADAuthenticationMethodPolicyX509IncludeTarget as $MSFT_AADAuthenticationMethodPolicyX509IncludeTarget1ref
{
Id = "all_users";
 TargetType = "group";

};

instance of MSFT_Credential as $MSFT_Credential9ref
{
Password = "****************";
 UserName = "ApplicationSecret";

};

instance of MSFT_AADAuthenticationMethodPolicyX509 as $MSFT_AADAuthenticationMethodPolicyX5091ref
{
TenantId = "rsrj.onmicrosoft.com";
 Id = "X509Certificate";
 IncludeTargets = {
    $MSFT_AADAuthenticationMethodPolicyX509IncludeTarget1ref
};
 ResourceID = "[AADAuthenticationMethodPolicyX509]AADAuthenticationMethodPolicyX509-X509Certificate";
 Ensure = "Present";
 AuthenticationModeConfiguration = $MSFT_MicrosoftGraphX509CertificateAuthenticationModeConfiguration1ref;
 SourceInfo = "C:\\M365DSC\\RSRJ\\aad\\test\\M365TenantConfig.ps1::218::9::AADAuthenticationMethodPolicyX509";
 ApplicationId = "29e61b7f-159d-4c80-8471-c9e0618ccd57";
 ModuleVersion = "1.23.809.1";
 ModuleName = "Microsoft365DSC";
 State = "disabled";
 ApplicationSecret = $MSFT_Credential9ref;
 CertificateUserBindings = {
    $MSFT_MicrosoftGraphX509CertificateUserBinding1ref,
    $MSFT_MicrosoftGraphX509CertificateUserBinding2ref
};

 ConfigurationName = "M365TenantConfig";

};
instance of MSFT_Credential as $MSFT_Credential10ref
{
Password = "****************";
 UserName = "ApplicationSecret";

};

instance of MSFT_AADAuthenticationStrengthPolicy as $MSFT_AADAuthenticationStrengthPolicy1ref
{
ResourceID = "[AADAuthenticationStrengthPolicy]AADAuthenticationStrengthPolicy-Multifactor authentication";
 Description = "Combinations of methods that satisfy strong authentication, such as a password + SMS";
 ApplicationSecret = $MSFT_Credential10ref;
 Id = "00000000-0000-0000-0000-000000000002";
 Ensure = "Present";
 ApplicationId = "29e61b7f-159d-4c80-8471-c9e0618ccd57";
 SourceInfo = "C:\\M365DSC\\RSRJ\\aad\\test\\M365TenantConfig.ps1::251::9::AADAuthenticationStrengthPolicy";
 TenantId = "rsrj.onmicrosoft.com";
 ModuleName = "Microsoft365DSC";
 AllowedCombinations = {
    "windowsHelloForBusiness",
    "fido2",
    "x509CertificateMultiFactor",
    "deviceBasedPush",
    "temporaryAccessPassOneTime",
    "temporaryAccessPassMultiUse",
    "password,microsoftAuthenticatorPush",
    "password,softwareOath",
    "password,hardwareOath",
    "password,sms",
    "password,voice",
    "federatedMultiFactor",
    "microsoftAuthenticatorPush,federatedSingleFactor",
    "softwareOath,federatedSingleFactor",
    "hardwareOath,federatedSingleFactor",
    "sms,federatedSingleFactor",
    "voice,federatedSingleFactor"
};
 ModuleVersion = "1.23.809.1";
 DisplayName = "Multifactor authentication";

 ConfigurationName = "M365TenantConfig";

};
instance of MSFT_Credential as $MSFT_Credential11ref
{
Password = "*********";
 UserName = "ApplicationSecret";

};

instance of MSFT_AADAuthenticationStrengthPolicy as $MSFT_AADAuthenticationStrengthPolicy2ref
{
ResourceID = "[AADAuthenticationStrengthPolicy]AADAuthenticationStrengthPolicy-Passwordless MFA";
 Description = "Passwordless methods that satisfy strong authentication, such as Passwordless sign-in with the Microsoft Authenticator";
 ApplicationSecret = $MSFT_Credential11ref;
 Id = "00000000-0000-0000-0000-000000000003";
 Ensure = "Present";
 ApplicationId = "29e61b7f-159d-4c80-8471-c9e0618ccd57";
 SourceInfo = "C:\\M365DSC\\RSRJ\\aad\\test\\M365TenantConfig.ps1::262::9::AADAuthenticationStrengthPolicy";
 TenantId = "rsrj.onmicrosoft.com";
 ModuleName = "Microsoft365DSC";
 AllowedCombinations = {
    "windowsHelloForBusiness",
    "fido2",
    "x509CertificateMultiFactor",
    "deviceBasedPush"
};
 ModuleVersion = "1.23.809.1";
 DisplayName = "Passwordless MFA";

 ConfigurationName = "M365TenantConfig";

};
instance of MSFT_Credential as $MSFT_Credential12ref
{
Password = "************;
 UserName = "ApplicationSecret";

};

instance of MSFT_AADAuthenticationStrengthPolicy as $MSFT_AADAuthenticationStrengthPolicy3ref
{
ResourceID = "[AADAuthenticationStrengthPolicy]AADAuthenticationStrengthPolicy-Phishing-resistant MFA";
 Description = "Phishing-resistant, Passwordless methods for the strongest authentication, such as a FIDO2 security key";
 ApplicationSecret = $MSFT_Credential12ref;
 Id = "00000000-0000-0000-0000-000000000004";
 Ensure = "Present";
 ApplicationId = "29e61b7f-159d-4c80-8471-c9e0618ccd57";
 SourceInfo = "C:\\M365DSC\\RSRJ\\aad\\test\\M365TenantConfig.ps1::273::9::AADAuthenticationStrengthPolicy";
 TenantId = "rsrj.onmicrosoft.com";
 ModuleName = "Microsoft365DSC";
 AllowedCombinations = {
    "windowsHelloForBusiness",
    "fido2",
    "x509CertificateMultiFactor"
};
 ModuleVersion = "1.23.809.1";
 DisplayName = "Phishing-resistant MFA";

 ConfigurationName = "M365TenantConfig";

};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";
 

                        MinimumCompatibleVersion = "1.0.0";
 

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};
 

                        Author="Admin-FS";
 

                        GenerationDate="08/14/2023 16:09:41";
 

                        GenerationHost="LAPDLP01-PILOT";
 

                        Name="M365TenantConfig";

                    };

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Business
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : it-IT
OsMuiLanguages       : {it-IT, en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
get-module Microsoft365DSC -ListAvailable | select ModuleBase, Version

ModuleBase                                                            Version
----------                                                            -------
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.809.1 1.23.809.1

**Comment by andikrueger** [comment]
Which PS Version did you use to install M365DSC? This looks like some issue due to the usage of PS 5 and 7. To run DSC you need to install the module and the dependencies within PS 5 (only).

**Comment by fsecchia** [comment]
> Which PS Version did you use to install M365DSC? This looks like some issue due to the usage of PS 5 and 7. To run DSC you need to install the module and the dependencies within PS 5 (only).

I used PS 5 (only) to install M365DSC. 
After several attempts and after checking the versions of the referenced modules I found a simple way to solve the issue with an Update-M365DSCDependencies **-force** 

Thanks
