### ISSUE TITLE
SPOSharingSettings: SharingCapability and AnonymousLinkType

### ISSUE THREAD

**Issue by jocassier** [microsoft/Microsoft365DSC#3575]
#### Details of the scenario you tried and the problem that is occurring

SPOSharingSettings prevents the following parameter combination  
'Set-PnPTenant -SharingCapability ExistingExternalUserSharingOnly -FileAnonymousLinkType View -FolderAnonymousLinkType View' ,  although it is possible with Set-PnPTenant.

#### Verbose logs showing the problem
N/A
#### Suggested solution to the issue

Remove or change

```powershell
    if ($SharingCapability -ne 'ExternalUserAndGuestSharing' -and ($null -ne $FileAnonymousLinkType -or $null -ne $FolderAnonymousLinkType))
    {
        Write-Verbose -Message 'If anonymous file or folder links are set, SharingCapability must be set to ExternalUserAndGuestSharing '
        $CurrentParameters.Remove('FolderAnonymousLinkType') | Out-Null
        $CurrentParameters.Remove('FileAnonymousLinkType') | Out-Null
    }
```
in Set-TargetResource.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
    SPOSharingSettings "SPOSharingSettings" {
        BccExternalSharingInvitations              = $False
        DefaultLinkPermission                      = "View"
        DefaultSharingLinkType                     = "Direct"
        EnableGuestSignInAcceleration              = $False
        Ensure                                     = "Present"
        FileAnonymousLinkType                      = "View"
        FolderAnonymousLinkType                    = "View"
        IsSingleInstance                           = "Yes"
        MySiteSharingCapability                    = "ExistingExternalUserSharingOnly"
        NotifyOwnersWhenItemsReshared              = $True
        PreventExternalUsersFromResharing          = $false
        ProvisionSharedWithEveryoneFolder          = $False
        RequireAcceptingAccountMatchInvitedAccount = $true
        SharingCapability                          = "ExistingExternalUserSharingOnly"
        SharingDomainRestrictionMode               = "None"
        ShowAllUsersClaim                          = $False
        ShowEveryoneClaim                          = $False
        ShowEveryoneExceptExternalUsersClaim       = $True
        ShowPeoplePickerSuggestionsForGuestUsers   = $False
        ApplicationId                              = $ApplicationId
        TenantId                                   = $TenantId
        CertificateThumbprint                      = $CertificateThumbprint
    }
```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.23.809.1

**Comment by jocassier** [comment]
False alarm. Did a closer look. The resource behaves as it should.  

The AnonymousLinkType settings are available in Sharepoint Admin Center only if  external sharing is set to ExternalUserAndGuestSharing. In summary, these settings are not active/relevant if external sharing is set to any other value.

**Comment by andikrueger** [comment]
Thanks for the update. I'll close this issue then

**Comment by MubSalim** [comment]
Just to clarify, if I set the following values:

 `SharingCapability = "ExternalUserSharingOnly";`

regardless of if I set the FileAnonymousLinkType and FolderAnonymousLinkType to VIEW, EDIT or just leave them out. I still get the warning:

`If anonymous file or folder links are set, SharingCapability must be set to ExternalUserAndGuestSharing`

can the warning just be ignored then, as it doesn't affect my intended tenant configuration it just confused me. :/
