### ISSUE TITLE
Transport Rules ordering is tedious. Is there a better way?

### ISSUE THREAD

**Issue by jeremyhagan** [microsoft/Microsoft365DSC#3581]
Hi,

I'm cutting my teeth managing Transport Rules and other EXO config. Each time I create a new transport rule in the config I have to renumber everything (unless it is at the end). The only way out of this mess I can think of it to manage rule precedence outside of the DSC config. In this way new rules are always created at bottom and another script or manual process would be required to put the rule in it's correct place.

Does anyone have any more elegant ideas for this?

**Comment by andikrueger** [comment]
Have you tried to use the DSC DependsOn Parameter to set the sequence of execution for these resources? This might help.

**Comment by jeremyhagan** [comment]
Thanks for the suggestion Andi.

I'm not sure this would help. It would certainly be easier to insert a new rule in the middle of the DependsOn chain, but without specifying a Priority it would still get created with the lowest priority. Unless I am missing something.

**Comment by NikCharlebois** [comment]
You could, in your config, define a variable and increase its value on each rule. For example

```PowerShell
EXOMailboxSettings 'abc'
{
   ...
}
**$i = 0**
EXOTransportRule 'RuleABC'
{
    Priority = $i++
}
EXOTransportRule 'RuleGHI'
{
    Priority = $i++
}
EXOTransportRule 'RuleDEF'
{
    Priority = $i++
}
```

**Comment by NikCharlebois** [comment]
DSC config can still use classic PowerShell logic in them and the generated value is what gets stored in the compiled file.

**Comment by jeremyhagan** [comment]
> You could, in your config, define a variable and increase its value on each rule. For example
> 
> ```powershell
> EXOMailboxSettings 'abc'
> {
>    ...
> }
> **$i = 0**
> EXOTransportRule 'RuleABC'
> {
>     Priority = $i++
> }
> EXOTransportRule 'RuleGHI'
> {
>     Priority = $i++
> }
> EXOTransportRule 'RuleDEF'
> {
>     Priority = $i++
> }
> ```

That's workable. Thanks Nik
