### ISSUE TITLE
AADAuthorizationPolicy: PermissionGrantPolicyIdsAssignedToDefaultUserRole property not working

### ISSUE THREAD

**Issue by mibarm** [microsoft/Microsoft365DSC#3594]
### Description of the issue

The parameter '**PermissionGrantPolicyIdsAssignedToDefaultUserRole**' is no longer working properly (since the change to Graph Beta 2.x cmdlets. 

Get-MgBetaPolicyAuthorizationPolicy provides the property not under 
.DefaultUserRolePermissions.PermissionGrantPoliciesAssigned but directly on PermissionGrantPolicyIdsAssignedToDefaultUserRole

### Microsoft 365 DSC Version

1.23.809.1

### Which workloads are affected

Azure Active Directory

### The DSC configuration

AADAuthorizationPolicy "AADAuthorizationPolicy"
        {
            AllowedToSignUpEmailBasedSubscriptions                  = $True;
            AllowedToUseSSPR                                        = $True;
            AllowEmailVerifiedUsersToJoinOrganization               = $False;
            AllowInvitesFrom                                        = "everyone";
            BlockMsolPowerShell                                     = $False;
            Credential                                              = $Credscredential;
            DefaultUserRoleAllowedToCreateApps                      = $True;
            DefaultUserRoleAllowedToCreateSecurityGroups            = $True;
            DefaultUserRoleAllowedToCreateTenants                   = $True;
            DefaultUserRoleAllowedToReadBitlockerKeysForOwnedDevice = $True;
            DefaultUserRoleAllowedToReadOtherUsers                  = $True;
            Description                                             = "Used to manage authorization related settings across the company.";
            DisplayName                                             = "Authorization Policy";
            Ensure                                                  = "Present";
            GuestUserRole                                           = "Guest";
            IsSingleInstance                                        = "Yes";
            PermissionGrantPolicyIdsAssignedToDefaultUserRole       = @("ManagePermissionGrantsForSelf.microsoft-user-default-legacy");
        }

**Comment by mibarm** [comment]
Pull Request: https://github.com/microsoft/Microsoft365DSC/pull/3595

**Comment by ykuijs** [comment]
Closed via PR #3595
