### ISSUE TITLE
NewResourceName: IntuneDeviceCleanupRules

### ISSUE THREAD

**Issue by michaelbaltes** [microsoft/Microsoft365DSC#3599]
### Description
Adding support for INtune Clean-up rules described here:
https://learn.microsoft.com/en-us/graph/api/resources/intune-devices-manageddevicecleanupsettings?view=graph-rest-beta

### Proposed properties
enable / disable
deleteDevices after days

**Comment by FabienTschanz** [comment]
I'm working on it, will take a little bit more time.
