### ISSUE TITLE
Exception calling "SafeGetValue" with "0" argument(s)" in datafile (psd1)

### ISSUE THREAD

**Issue by commandcom** [microsoft/Microsoft365DSC#3613]
Adding 458 _EXOAcceptedDomains_ to our datafile. Data was generated by an extract pulled from our production environment. After modifying the psd1 file, the build/run fails with the error:

![AcceptedDomainsPipelineError](https://github.com/microsoft/Microsoft365DSC/assets/9935427/192491d5-8dc5-45b9-8a78-a16d21ec7e4b)

There is no specific error line; the error message is the entire psd1 file (truncated in the screenshot above).

Visual Studio Code finds no syntactical issues with this file. The file has also been examined manually for missing or doubled-up characters and other common text file problems. None have been found.

After a lot of experimentation, triggering the error has been narrowed down to the addition or removal of a single line:

![ShowErrorDifferences](https://github.com/microsoft/Microsoft365DSC/assets/9935427/a8b3bae8-3b7e-4c0e-8818-9abc63a3dfe8)

The addition of a single line to the psd1 file causes the failure. The offending line has no syntactical issues.

It is hard to believe there's any sort of size restriction (physical or otherwise) to the psd1 files, so there must be some other explanation. Google/MSFT do not have meaningful suggestions. 

Script is run on Azure VMs with 8GB of memory (Microsoft Windows Server 2019 Datacenter; OsVersion : 10.0.17763). Memory remains at a flat 50% utilization throughout the running of the script. DSC version is 1.23.726.1

Wondering if anyone might have some insight into this issue and/or any suggestions as to how to figure out if this is a syntactical problem, a size issue, or something else entirely.

**Comment by NikCharlebois** [comment]
Thanks for the details, closing for now.
