### ISSUE TITLE
Exchange ressource also require a local certificate with private key to authenticate using using a Service Principal (Thumbprint)

### ISSUE THREAD

**Issue by levesquesamuel** [microsoft/Microsoft365DSC#3619]
This links only refer to Power Apps:

https://microsoft365dsc.com/user-guide/get-started/authentication-and-permissions/#power-apps-permissions

![image](https://github.com/microsoft/Microsoft365DSC/assets/10143287/a7c7355a-0602-4a5a-b2af-e30588007f3f)

**Comment by andikrueger** [comment]
Please make sure to install the certificate in the machines certificate store. this should resolve your issue.

**Comment by NikCharlebois** [comment]
DSC always checks for the certificate in the local machine's store since it runs as that process. Make sure the certificate is added to that store for the decryption and authentication processes to work. Thanks
