### ISSUE TITLE
Problem with URI $Vars.tostring() when $Null -eq $Var

### ISSUE THREAD

**Issue by ahohenschuh** [microsoft/Microsoft365DSC#363]
<!--
    Your feedback and support is greatly appreciated, thanks for contributing!

    ISSUE TITLE:
    Please prefix the issue title with the resource name, e.g.
    'ResourceName: Short description of my issue'

    ISSUE DESCRIPTION (this template):
Currently when we extracting $var URI's from source xx they get pulled as URI and we need to convert them with $var.tostring(). 
If $Null -eq $Var -> error. 

#### Suggested solution to the issue
Proposal to impement a conversion of URI to String into ReverseDSC

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
DEV

**Comment by andikrueger** [comment]
@ahohenschuh Could you please add more details of the scenario, where this error occurs?

**Comment by ahohenschuh** [comment]
@andikrueger: When extracting a resource containing an URI, the URI could be empty. This means that when typecasting the URI tostring(), we have to check if the URI is empty or not in each ressource where we could possibly work with an URI. So it would be simpler to do the typecasting and checking for $Null while actually extracting the data.

**Comment by NikCharlebois** [comment]
@ahohenschuh do you have one resource we could use as an example to investigate this further? Thanks

**Comment by ahohenschuh** [comment]
@NikCharlebois PLease have a look at MSFT_EXOIntraOrganizationConnector and look a line 52, Currently there is no check for $Null -eq $Urivar

**Comment by NikCharlebois** [comment]
This issue has been fixed in the latest version.
