### ISSUE TITLE
[AADEntitlementManagementAccessPackageAssignmentPolicy] Parameter ResourceId is using a reserved name

### ISSUE THREAD

**Issue by ykuijs** [microsoft/Microsoft365DSC#3639]
#### Details of the scenario you tried and the problem that is occurring
During testing I ran into an issue with the AADEntitlementManagementAccessPackageAssignmentPolicy resource. When compiling a configuration that was using the ResourceId property in the MSFT_MicrosoftGraphcustomextensionauthenticationconfiguration subclass, I got several errors. After renaming the property in the schema from ResourceId to Id, all errors disappeared.

I believe that DSC is using the ResourceId property as well, causing these issues. I ran into the same issue in the past when trying to use the Settings parameter name.

We should rename this property and update the DRG as well to prevent it from generating this parameter name.

#### Verbose logs showing the problem
`The member 'ResourceId' is not valid. Valid members are ''.""`

#### Suggested solution to the issue
Rename the ResourceId parameter to something different.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by ykuijs** [comment]
@William-Francillette Could you please have a look at this issue?

**Comment by William-Francillette** [comment]
Sure, I'll have a look

**Comment by William-Francillette** [comment]
I'll try to get that sorted in the weekend and post the PR then

**Comment by ykuijs** [comment]
Correct, formally this is a breaking change but if doesn't work now, there is no way anybody is using it and therefore won't break any existing configs.

**Comment by William-Francillette** [comment]
@ykuijs and @NikCharlebois - I have corrected the resource - the customExtensionHandler was not handled correctly - I modified the schema, resource (get-TargetResource, Set-TargetResource and Export-TargetResource) and test unit 

@NikCharlebois I have posted a PR back in July for reverseDSC (which was not merged) to remove the incorrect trailing characters during an export. I have noticed the module was updated 3 weeks ago to address this issue however there are still issues with the formatting where some return carriages are removed in a cim instance
The PR has conflict now with the latest update but could you have a look at my proposal and will resolve the conflict if that code suit as a fix.
