### ISSUE TITLE
IntuneDeviceConfigurationAdministrativeTemplatePolicyWindows10: Export produces invalid DSC Configuration File

### ISSUE THREAD

**Issue by satsuk81** [microsoft/Microsoft365DSC#3644]
### Description of the issue

Export of IntuneDeviceConfigurationAdministrativeTemplatePolicyWindows10 produces invalid DSC Configuration File.

It appears the issue might relate to the fact that the 'Enabled = ...' is not on a new line.

Example export:

                MSFT_IntuneGroupPolicyDefinitionValue{
                    ConfigurationType = 'policy'

                    Id = 'f296aeb8-fda9-40a9-996a-41c0dea62765'

                    Definition = MSFT_IntuneGroupPolicyDefinitionValueDefinition{
                        Id = '3c3b429e-03c8-4b86-ab18-24c77aace71e'
                        DisplayName = 'WDigest Authentication (disabling may require KB2871997)'
                        CategoryPath = '\MS Security Guide'
                        PolicyType = 'admxBacked'
                        SupportedOn = 'At least Windows Server 2008 R2 or Windows 7'
                        ClassType = 'machine'
                    }                    Enabled = $False
                }

### Microsoft 365 DSC Version

1.23.830.1

### Which workloads are affected

other

### The DSC configuration

Export-M365DSCConfiguration -Components @("IntuneDeviceConfigurationAdministrativeTemplatePolicyWindows10") -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId

### Verbose logs showing the problem

No errors are produced.

[16/65] Extracting [IntuneDeviceConfigurationAdministrativeTemplatePolicyWindows10] using {CertificateThumbprint}...
    |---[1/1] CIS Microsoft Intune for Windows 11 Benchmark v1.0.0 - Administrative Templates✅

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22000.1.amd64fre.co_release.210604-1628
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}

Key   : PSVersion
Value : 5.1.22000.2003
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.22000.2003
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by ricmestre** [comment]
I already reported this issue on #3634 but similar issue was also reported on #3645 by someone else.

**Comment by satsuk81** [comment]
A secondary issue exists where a Setting's DisplayName has an ` in it.

Such as "Require domain users to elevate when setting a network's location"

My suggestion would be to replace a single ' found in DisplayName with two.  Such as the example below:
"Require domain users to elevate when setting a network''s location"

**Comment by satsuk81** [comment]
Output from executing the configuration file.

![image](https://github.com/microsoft/Microsoft365DSC/assets/76114734/d3e4ee57-a03e-4bcc-80f2-79adea19de25)

**Comment by NikCharlebois** [comment]
This has been fixed.

**Comment by ricmestre** [comment]
Has this been fixed? How?
