### ISSUE TITLE
Improve the logging of the Install and Update M365DSC cmdlet.

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#3660]
### Description of the issue

Customers would like to see additional logging being thrown from the various Install-M365DSC* and Update-M365DSC* cmdlets when errors are being thrown.

### Microsoft 365 DSC Version

V1.23.906.1

### Which workloads are affected

other

**Comment by andikrueger** [comment]
This is a good improvement which would also help in regard to #3621
