### ISSUE TITLE
MSFT_IntuneDeviceEnrollmentStatusPageWindows10 does not implement the key property Id

### ISSUE THREAD

**Issue by V-Reacher** [microsoft/Microsoft365DSC#3715]
### Description of the issue

Hi,
I'm pretty new to M365-DSC and I'm encountering the following Issue, when I try to import a previously exported configuration I get the following error:
The command Get-TargetResource of the PS resource MSFT_IntuneDeviceEnrollmentStatusPageWindows10 does not implement the key property Id mentioned in the corresponding MOF schema file 
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.920.2\DscResources\MSFT_IntuneDeviceEnrollmentStatusPageWindows10\MSFT_IntuneDeviceEnrollmentStatusPageWindows10.schema.mof 
as a mandatory parameter. All key parameters mentioned in the schema file must be implemented by the command Get-TargetResource as mandatory function parameters.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : KeyParameterNotImplemented
    + PSComputerName        : localhost

The Export was done with this command:
Export-M365DSCConfiguration -Path C:\M365-DSC -FileName "COMP-365DSC.ps1" -ConfigurationName "COMP-365DSC-Default" -Mode Full -ApplicationId "removed" -TenantId "comp.onmicrosoft.com" -CertificateThumbprint "removed" -Verbose

Then I ran COMP-365DSC.ps1, deleted some stuff in Intune and Entra ID, to get them restored and test if the things I want to achieve work.

But when i run this:
Start-DSCConfiguration -Path C:\M365-DSC\COMP-365DSC-Default -Wait -Verbose -Force

I get the error mentioned above.

### Microsoft 365 DSC Version

1.23.920.2

### Which workloads are affected

other

### The DSC configuration

```powershell
Export-M365DSCConfiguration -Path C:\M365-DSC -FileName "removed-365DSC.ps1" -ConfigurationName "removed-365DSC-Default" -Mode Full -ApplicationId "removed" -TenantId "removed.onmicrosoft.com" -CertificateThumbprint "removed" -Verbose
```

### Verbose logs showing the problem

```powershell
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsof
t/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer M365-DSC with user removed.
VERBOSE: [M365-DSC]: LCM:  [ Start  Set      ]
VERBOSE: [M365-DSC]: LCM:  [ End    Set      ]
The command Get-TargetResource of the PS resource MSFT_IntuneDeviceEnrollmentStatusPageWindows10 does not implement the key property Id mentioned in the corresponding MOF schema file 
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.920.2\DscResources\MSFT_IntuneDeviceEnrollmentStatusPageWindows10\MSFT_IntuneDeviceEnrollmentStatusPageWindows10.schema.mof 
as a mandatory parameter. All key parameters mentioned in the schema file must be implemented by the command Get-TargetResource as mandatory function parameters.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : KeyParameterNotImplemented
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 11.042 seconds
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.19041.3031
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.19041.3031
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by JGDPS** [comment]
Im getting this as well, only thing i can think of is i updated to version 1.23.920.2. Rolling back module to see if that makes any difference.

**Comment by JGDPS** [comment]
Rolling back to version '1.23.906.1' seems to resolve if. Or did for me at least.

**Comment by V-Reacher** [comment]
1.23.906.1 seems to work, but I needed to make a lot of changes to the *.ps1 which was exported. To get the *.mof generated.

**Comment by V-Reacher** [comment]
Ist working with the latest Version now, needed to edit this two files:
MSFT_IntuneSettingCatalogASRRulesPolicyWindows10.psm1 and MSFT_IntuneDeviceEnrollmentStatusPageWindows10.psm1

[M365-DSC-Files.zip](https://github.com/microsoft/Microsoft365DSC/files/12727310/M365-DSC-Files.zip)

**Comment by Cyanic-Cloud** [comment]
I am running version 1.23.913.2 and still having this issue, are you saying upgrading to 1.23.920.2 resolves the issue? 
If not what changes are required to the above two files in particular ?
Thanks

**Comment by V-Reacher** [comment]
> I am running version 1.23.913.2 and still having this issue, are you saying upgrading to 1.23.920.2 resolves the issue? If not what changes are required to the above two files in particular ? Thanks

Currently you have to update to version 1.23.920.2 and then replace the files from the zip with the local ones.

Only a few lines were exchanged e.g:
[Parameter()]
        [System.String]
        $Id,

against

[Parameter(Mandatory = $true)]
        [System.String]
        $Id,

**Comment by BlueOdyssey** [comment]
Getting the same issue with v 1.23.1025.1.  Same error messages, execution steps etc.

**Comment by ricmestre** [comment]
Actually the way to solve this is to do the reverse, you must change the Id field from Required to Write in the schema file, this has been done a few weeks ago for several resources. On this one only the module was changed but the schema file was missed.

Anyway even after solving that this resource still fails to work properly on latest version, see #3442

**Comment by ykuijs** [comment]
This has been changed 5 months ago in PR #3878
Closing this issue now
