### ISSUE TITLE
Suggestion to use unused parameter in TestHarness.psm1 to target tests to  a specific configuration

### ISSUE THREAD

**Issue by menswearUK** [microsoft/Microsoft365DSC#3727]
### Description of the issue

When working on updates we are generally looking at a single configuration but running the test harness by itself will run tests on all the configurations in the module.  This can take some time to complete

There is an existing parameter on the Invoke-TestHarness command called DscTestsPath which appears to be unused.
I'm not sure if this was originally intended for this purpose but it could be used to target a specific set of tests.

I propose an amendment to the function so, when this parameter is specified, it will only run the set of tests requested.  usage would be as below:
Invoke-TestHarness -DscTestsPath .\Tests\Unit\Microsoft365DSC\Microsoft365DSC.SomeConfiguration.Tests.ps1 -IgnoreCodeCoverage

### Microsoft 365 DSC Version

dev

### Which workloads are affected

other

### The DSC configuration

```powershell
n/a
```

### Verbose logs showing the problem

```powershell
n/a - not a fault
```

### Environment Information + PowerShell Version

```powershell
n/a, target node is ms cloud
```

**Comment by salbeck-sit** [comment]
This looks as if it will be very useful
