### ISSUE TITLE
Clone tenant config with service principal authentication question

### ISSUE THREAD

**Issue by horgasz2023** [microsoft/Microsoft365DSC#3735]
Hello all,

we exported successfully an AAD tenant config by running this command:

Export-M365DSCConfiguration -Components @("AADAdministrativeUnit", "AADAuthenticationMethodPolicy", "AADAuthenticationMethodPolicyAuthenticator", "AADAuthenticationMethodPolicyEmail", "AADAuthenticationMethodPolicyFido2", "AADAuthenticationMethodPolicySms", "AADAuthenticationMethodPolicySoftware", "AADAuthenticationMethodPolicyTemporary", "AADAuthenticationMethodPolicyVoice", "AADAuthenticationMethodPolicyX509", "AADAuthenticationStrengthPolicy", "AADAuthorizationPolicy", "AADConditionalAccessPolicy", "AADCrossTenantAccessPolicy", "AADCrossTenantAccessPolicyConfigurationDefault", "AADCrossTenantAccessPolicyConfigurationPartner", "AADEntitlementManagementAccessPackage", "AADEntitlementManagementAccessPackageAssignmentPolicy", "AADEntitlementManagementAccessPackageCatalog", "AADEntitlementManagementAccessPackageCatalogResource", "AADEntitlementManagementConnectedOrganization", "AADGroupLifecyclePolicy", "AADGroupsNamingPolicy", "AADGroupsSettings", "AADNamedLocationPolicy", "AADRoleDefinition", "AADRoleEligibilityScheduleRequest", "AADRoleSetting", "AADSecurityDefaults", "AADTenantDetails", "AADTokenLifetimePolicy") -ApplicationId $ApplicationId -ApplicationSecret $ApplicationSecret -TenantId $TenantId -Path 'C:\Users\wiz\Export\exp.ps1"

We were trying to figure out what command should be used to import to a different AAD tenant when using SP as authentication.
We checked the documentation but could not figure out how do you pass the ApplicationID, ApplicationSecret and TenantID for the target tenant.
https://microsoft365dsc.com/user-guide/get-started/cloning-tenants/
Unfortunately only the user credentials scenario is presented.
Could you provide us an example how could we clone AAD tenant A config to AAD tenant B when using Service Principal as authentication scenario?

**Comment by horgasz2023** [comment]
(https://learn.microsoft.com/en-us/powershell/module/psdesiredstateconfiguration/start-dscconfiguration?view=dsc-1.1)

-Credential

Specifies a user name and password, as a PSCredential object, for the target computer. To obtain a PSCredential object, use the Get-Credential cmdlet. For more information, type Get-Help Get-Credential.

There is nothing here about passing the SP for authentication.

**Comment by andikrueger** [comment]
Please review this user guide within our documentation: https://microsoft365dsc.com/user-guide/get-started/deploying-configurations/

**Comment by horgasz2023** [comment]
So in other words if we replace the OrganizationName, ApplicationId, TenantId and ApplicationSecret(to the target tenant specific values) in the ConfigurationData file before we generate the mof file than it should be sufficient?

**Comment by andikrueger** [comment]
Yes. That’s the way to do it
