### ISSUE TITLE
NewResourceName: Driver updates for Windows 10 and later

### ISSUE THREAD

**Issue by Edocsyl** [microsoft/Microsoft365DSC#3747]
### Description
It would be Nice to have the "Driver updates for Windows 10 and later" Profiles for DSC

**Comment by AWeber78** [comment]
https://graph.microsoft.com/beta/deviceManagement/windowsDriverUpdateProfiles

(Set)-MgBetaDeviceManagementWindowsDriverUpdateProfile

**Comment by FabienTschanz** [comment]
Working on it
