### ISSUE TITLE
Errors creating MOF file

### ISSUE THREAD

**Issue by BostjanGspan** [microsoft/Microsoft365DSC#3757]
### Description of the issue

There are three types of errors we get:
**Error 1:**
"The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string."
**Question:** what is the idea about this error? Do we go into exported data and add double quotation marks? Is "M365DSCStringEncoding.psm1" expected to treat ampersand too?

**Error 2:**
There is an incomplete property assignment block in the instance definition.
At D:\o365\0410\M365TenantConfig.ps1:16 char:5
+     {
+     ~
Missing closing '}' in statement block or type definition.

**Error 3:**
At D:\o365\0410\M365TenantConfig.ps1:964634 char:37
+             Ensure               = "Present";
+                                     ~~~~~~~~~
Unexpected token 'Present";
            GroupTypes           = @("Unified");
            Id                   = "f323b989-0ea6-4349-a3e3-bc63b57e6bac";
            MailEnabled          = $True;
            MailNickname         = "Area53";
            MemberOf             = @();
            Members              = @(Szymon.KUBACKI@obfuscate.com,MICHAL.CICHOSZ@obfuscate.com,"Kordian.Ferdek@obfuscate.com",Jacek.Fudali@obfuscate.com,Krzysztof.Staszczak@obfuscate.com,KAROLINA.OBUTELEWICZ@obfuscate.com)
;
            Owners               = @(MICHAL.CICHOSZ@obfuscate.com);
            SecurityEnabled      = $False;
            TenantId             = $OrganizationName;
            Visibility           = "Private";
        }

### Microsoft 365 DSC Version

V1.23.927.1

### Which workloads are affected

Azure Active Directory, Exchange Online, Office 365 Admin, OneDrive for Business, Planner, Power Platform, Security & Compliance Center, SharePoint Online, Teams

### The DSC configuration

```powershell
Default for all workloads
```

### Verbose logs showing the problem

```powershell
I don't have them available
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.6085.amd64fre.GitEnlistment.230704-1000
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
 
 

Name                           Value
----                           -----
PSVersion                      5.1.14393.5582
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.5582
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by andikrueger** [comment]
Could you also please share the resource that is causing this behaviour.

**Comment by BostjanGspan** [comment]
Personally, I don't have access to the tenant where these errors occur. I'm waiting for the customer to report back on the results with the latest version of M365DSC (and dependencies).

Kind regards,
Boštjan
Cloud Solution Architect

**Comment by BostjanGspan** [comment]
> Could you also please share the resource that is causing this behaviour.

From the snippets of the errors which customer shared with me it looks errors are related to Microsoft Groups and their display names or descriptions which are partially in languages that use non-Latin scripts/characters.

**Comment by andikrueger** [comment]
Would be great, if you could confirm this with the customer.

**Comment by BostjanGspan** [comment]
This are the errors with updated Microsoft365DSC and dependencies configuration:
PS D:\o365\dsc\0410> .\M365TenantConfig.ps1 -Verbose -Anonymize
At D:\o365\dsc\0410\M365TenantConfig.ps1:964632 char:55
+             Description          = "Wspólna praca... „RAZEM MOŻEMY WI ...
+                                                       ~~~~~
Unexpected token 'RAZEM' in expression or statement.
At D:\o365\dsc\0410\M365TenantConfig.ps1:964632 char:55
+             Description          = "Wspólna praca... „RAZEM MOŻEMY WI ...
+                                                       ~
There is an incomplete property assignment block in the instance definition.
At D:\o365\dsc\0410\M365TenantConfig.ps1:16 char:5
+     {
+     ~
Missing closing '}' in statement block or type definition.
At D:\o365\dsc\0410\M365TenantConfig.ps1:7 char:1
+ {
+ ~
Missing closing '}' in statement block or type definition.
At D:\o365\dsc\0410\M365TenantConfig.ps1:964634 char:37
+             Ensure               = "Present";
+                                     ~~~~~~~~~
Unexpected token 'Present";
            GroupTypes           = @("Unified");
            Id                   = "f323b989-0ea6-4349-a3e3-bc63b57e6bac";
            MailEnabled          = $True;
            MailNickname         = "AreaICISB";
            MemberOf             = @();
            Members              = @("Szymon.KUBACKI@contoso.com","MICHAL.CICHOSZ@contoso.com","Kordian.Ferdek@cc
hellenic.com","Jacek.Fudali@contoso.com","Krzysztof.Staszczak@contoso.com","KAROLINA.OBUTELEWICZ@contoso.com")
;
            Owners               = @("MICHAL.CICHOSZ@contoso.com");
            SecurityEnabled      = $False;
            TenantId             = $OrganizationName;
            Visibility           = "Private";
        }
        AADGroup "AADGroup-PTG' in expression or statement.
At D:\o365\dsc\0410\M365TenantConfig.ps1:964646 char:32
+         AADGroup "AADGroup-PTG & FC"
+                                ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\o365\dsc\0410\M365TenantConfig.ps1:964650 char:41
+             Description          = "PTG & FC";
+                                         ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\o365\dsc\0410\M365TenantConfig.ps1:964651 char:41
+             DisplayName          = "PTG & FC";
+                                         ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\o365\dsc\0410\M365TenantConfig.ps1:964680 char:38
+         AADGroup "AADGroup-contoso Audit & CAP Tracking readers"
+                                      ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\o365\dsc\0410\M365TenantConfig.ps1:964684 char:81
+ ... ion          = "Provides read only access for sub contoso Audit & CAP Tra ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by BostjanGspan** [comment]
I see in the error message that ampersand sign is reserved for future use. Customer often uses "&" sign in display names.  Is there a way that export file parser can handle this gracefully?
If not, at which step of cloning the configuration to another (test) tenant should we intervene and replace "&" with something acceptable?

**Comment by BostjanGspan** [comment]
The other error I see above is:
 Ensure               = "Present";
+                                     ~~~~~~~~~
Unexpected token 'Present";
From the context it looks like that it's related to a distribution group because it's NOT security enabled.

**Comment by andikrueger** [comment]
The log does not really cover the issue in full. I assume, the issue looks something like this

```powershell
ResourceName DisplayNameUsed
{
   DisplayNameOfTheResource = "This is a fancy display name with special characters "Quotes and & Ampersand" "
}
```

Above will fail and the string would end with the second quote. After that there is the not recognized word and the & sign.

Could you share, which resource causes this issue within the exported configuration? We need to add some escaping to the display name to mitigate this issue.

**Comment by BostjanGspan** [comment]
All of the errors are within AAD Groups, so AzureAD is the resource.

**Comment by BostjanGspan** [comment]
We don't see errors with ampersand anymore after upgrading to v.1.23.1011.1 and dependencies too. 
However an error reappeared which we have seen earlier too. When creating MOF file from previous export with v.1.23.1004.1 there are several errors like this:
Missing statement body after keyword 'Sequence'.
At D:\o365\dsc\0410\M365TenantConfig.ps1:33680 char:29
+                     Sequence = 0
+                             ~

**Comment by BostjanGspan** [comment]
@andikrueger should we close this issue as resolved because we/customer doesn't see the error with ampersand anymore?
There is no sign that would tell me the remaining error is linked to Entra ID resource. I simply don't know what it's related to. Log files don't have any information on this.

**Comment by andikrueger** [comment]
Thanks for the update! I'll close this issue.
