### ISSUE TITLE
use Graph API instead of PowerShell modules

### ISSUE THREAD

**Issue by Malte-BNT** [microsoft/Microsoft365DSC#3772]
Hi,
M365DSC depends on concrete versions of various PowerShell modules. These are maintained with different speeds, so they often lacking of newly introduced or changed settings. E.g. compare Get-PnPTenant vs Get-SPOTenant - the difference is quite huge, and PnP is missing many settings.
Most of the modules are using Graph API REST calls internally. Wouldn't it therefore be a good idea to base all M365 Resources on according Graph API calls instead of relying on an intermediate layer of externally developed PowerShell modules?
This would also open access to many things not yet available as a PowerShell cmdlet (e.g. PowerBI Tenant Settings) and generally a simple and automated approach to generate M365DSC Resources based on Graph API endpoints.
Regards, Malte

**Comment by NikCharlebois** [comment]
While I agree with your point on the release frequency, the PowerShell module offers several benefits over direct Graph API calls such as the access token management, throttling handling, etc. Going with direct API calls would mean we would have to rebuild this logic somehow and duplicate efforts. We are currently aligning the M365DSC solution with the release cadence of its dependencies.

**Comment by andikrueger** [comment]
Just to add about the auto-generation of new resources: We build the dynamic resource generator a while back. This tool is capable of creating new resources based on given MS Graph PowerShell cmdLets:  https://microsoft365dsc.com/user-guide/advanced/dynamic-resource-generator/
