### ISSUE TITLE
TeamsUserPolicyAssignment

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#3777]
### Description
New resource to implement users' policy assignment in alignment with the Get-CsUserPolicyAssignment cmdlet.

**Comment by subhashvinjamuri** [comment]
@NikCharlebois - could you please provide more details, if this 'TeamsUserPolicyAssignment' is used as TeamsAppCentric policy , which is replaced for TeamsAppPermission Policies ?

This TeamsUserPolicyAssignment exports output as - each user , along with the policy that need to be assigned to. If I have 30000 users in my organization, it outputs those many entries.
But, practically it is impossible to maintain. 
for example, If I want to assign a policy to 10000 users, out of 30000, then I need to write the same policy assignment 10000 times for each user. Apply policy to a Group is correct method in that case, which can be done with single config item.

I see, we have TeamsGroupPolicyAssignment resource. But TeamsAppPermission Policies are not being exported in that somehow.
Please guide us here.
https://github.com/microsoft/Microsoft365DSC/issues/5453
