### ISSUE TITLE
MS appear to have temporarily pulled Graph SDK 2.7.0

### ISSUE THREAD

**Issue by salbeck-sit** [microsoft/Microsoft365DSC#3783]
### Description of the issue

Graph 2.7.0 has been pulled due to an error causing missing cmdlets. I assume Dependencies in the latest release will also be amended accordingly

### Microsoft 365 DSC Version

1.23.1011.1

### Which workloads are affected

other

### The DSC configuration

```powershell
na
```

### Verbose logs showing the problem

```powershell
na
```

### Environment Information + PowerShell Version

```powershell
na
```

**Comment by andikrueger** [comment]
It is still listed as a release here: https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.7.0

**Comment by salbeck-sit** [comment]
Using Find-Module I still see 2.6.1 as the latest verseion

**Comment by salbeck-sit** [comment]
See https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2350

**Comment by sdfarquhar** [comment]
I'm seeing the same issue and now stuck with Microsoft365DSC wanting the 2.7 Graph modules but those all being pulled.  See example below:

https://www.powershellgallery.com/packages/Microsoft.Graph.Applications/2.7.0

**Comment by andikrueger** [comment]
Just check and I'm able to install the latest release with the following command:

```powershell
Update-M365DSCDependencies -Force
Uninstall-M365DSCOutdatedDepenendencies
```

Even though the 2.7.0 release is unlisted, it can be installed forcefully.

**Comment by salbeck-sit** [comment]
Interesting. I concur. When I use "Find-Module microsoft.graph.applications" (or similar) I get version 2.6.1
But if I use "find-module ... -requiredversion '2.7.0' (similar to what Update-M365DSCDependencies does) then I do in fact get v2.7.0
So it seems that although 2.7.0 has been unlisted, it appears that modules are still present in the gallery after all.
I wonder what the status is on 'relisting' modules...
