### ISSUE TITLE
MSFT_TeamsGroupPolicyAssignment: multiple groups in export

### ISSUE THREAD

**Issue by heizkoerperchen** [microsoft/Microsoft365DSC#3785]
### Description of the issue

When exporting TeamsGroupPolicyAssignments I'm getting multiple group ids and displaynames back and the right group is not even contained at all. This is caused by the way the groups are queried:

            $Group = Find-CsGroup -SearchQuery $item.GroupId

It is some type of fulltext search which gets in our case up to 5 groups back. This should be changed to

            $Group = Find-CsGroup -SearchQuery $item.GroupId -ExactMatchOnly $true

This has to be corrected in line 368 for the Export-TargetResource function and also in lines 72/82 in the Get-TargetResource function.

### Microsoft 365 DSC Version

V1.23.920.2

### Which workloads are affected

Teams

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 10 Enterprise        
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}

Key   : PSVersion
Value : 5.1.19041.3031
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.19041.3031
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by ricmestre** [comment]
Issue https://github.com/microsoft/Microsoft365DSC/issues/3736 already raised to report this and PR #3737 to solve it.

**Comment by andikrueger** [comment]
Thank you for reporting. There is a fix in the making.
