### ISSUE TITLE
Enhancement - AADGroup - PIM for groups

### ISSUE THREAD

**Issue by techthoughts2** [microsoft/Microsoft365DSC#3806]
### Description of the issue

MS supports that ability to [Bring groups into Privileged Identity Management](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management/groups-discover-groups)

Presently, it appears only possible to toggle a group for PIM in the console:
![image](https://github.com/microsoft/Microsoft365DSC/assets/14536775/0ee06bab-3e6a-4638-8ea4-625fcb34cf77)

It would be ideal if we could configure a group for PIM use in the AADGroup DSC resource.

This could be further enhanced by enabling permanent eligible assignment of users to the group, enabing DSC to control who could elevate themselves to group membership through PIM.

Reference: [Assign eligibility for a group in Privileged Identity Management](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management/groups-assign-member-owner)

### Microsoft 365 DSC Version

v1.23.1011.1

### Which workloads are affected

Azure Active Directory

### The DSC configuration

```powershell
N/A - new enhancement
```

### Verbose logs showing the problem

```powershell
N/A - new enhancement
```

### Environment Information + PowerShell Version

```powershell
### Environment Information + PowerShell Version

OsName               : Microsoft Windows Server 2022 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.1.amd64fre.fe_release.210507-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Name                           Value
----                           -----
PSVersion                      5.1.20348.1850
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.1850
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by techthoughts2** [comment]
Looks related to: https://github.com/microsoft/Microsoft365DSC/issues/3786

But this enhancement is specific for enabling the Group to be PIM capable which I believe is not called out in the above.

**Comment by NikCharlebois** [comment]
Closing and keeping #3786 on the backlog
