### ISSUE TITLE
SCComplianceSearchAction 'Preview' type is not handled correctly

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Microsoft365DSC#381]
#### Details of the scenario you tried and the problem that is occurring
1. I create a new compliance case search
2. i click on save & run
3. preview results are created
4. after a while `Get-ComplianceSearchAction -Case 'SomeCase'`  will return a search action that has Action set to Preview

This causes some errors to popup during the extraction process.

#### Verbose logs showing the problem
```
xception calling "IndexOf" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex"
At C:\GitProjects\Office365DSC-SysKit\Modules\Office365DSC\DSCResources\MSFT_SCComplianceSearchAction\MSFT_SCComplianceSearchAction.psm1:463 char:5
+     $end = $ResultString.IndexOf(';', $start)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException
 
Get-TargetResource : Cannot validate argument on parameter 'Action'. The argument "Preview" does not belong to the set "Export,Purge,Retention" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command 
again.
At C:\GitProjects\Office365DSC-SysKit\Modules\Office365DSC\DSCResources\MSFT_SCComplianceSearchAction\MSFT_SCComplianceSearchAction.psm1:433 char:42
+             $result = Get-TargetResource @params
+                                          ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-TargetResource], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Get-TargetResource
```
#### Suggested solution to the issue
something like this: https://github.com/SysKitTeam/Office365DSC/pull/7/files
I would create a pull request on this repo, but we are more focused on the extraction process and could not verify that the Set-TargetResource works as it should.

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
Thanks @vinkobedek please proceed with the PR's creation. I will validate the Set logic.
