### ISSUE TITLE
Intune Workload fails to create localhost.mof IntuneDeviceConfigurationEndpointProtectionPolicyWindows10  (MSFT_MicrosoftGraphwindowsFirewallRule)

### ISSUE THREAD

**Issue by ChrisJay77** [microsoft/Microsoft365DSC#3851]
### Description of the issue

When i do a intune worklaod export:
export-m365dscconfiguration -applicationid XXXXXX-tenant XXX.onmicrosoft.com -applicationsecret XXXX -Workloads INTUNE -Path C:\Sit\Nov_Full
It cannot create and generates the following error:

Write-Error: C:\SIT\Nov_Full\M365TenantConfig.ps1:14984
 Line |
14984 |                  MSFT_MicrosoftGraphwindowsFirewallRule{
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | At least one of the values 'System.Object[]' is not supported or valid for property
      | 'Action' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify only
      | supported values: notConfigured, blocked, allowed.
the powershell line 14984 is as follows:
                MSFT_MicrosoftGraphwindowsFirewallRule{
                    InterfaceTypes = 'System.Object[]'
                    TrafficDirection = 'System.Object[]'
                    ProfileTypes = 'System.Object[]'
                    Protocol = @(
                        6
                        6
                    )
                    Action = 'System.Object[]'
                    Description = @(
                        'Allow Remote Desktop Connection'
                        'Allow Remote PowerShell'

This can be replicated in any test environment when creating a standard firewall policy please can you check as the other 65 sections of the intune workload work fine. Thanks

### Microsoft 365 DSC Version

Documents\PowerShell\Modules\Microsoft365DSC\1.23.1025.1 1.23.1025.1

### Which workloads are affected

other

### Verbose logs showing the problem

```powershell
Write-Error: C:\SIT\test_update\M365TenantConfig.ps1:14984
 Line |
14984 |                  MSFT_MicrosoftGraphwindowsFirewallRule{
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | At least one of the values 'System.Object[]' is not supported or valid for property
      | 'EdgeTraversal' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify
      | only supported values: notConfigured, blocked, allowed.
Write-Error: C:\SIT\test_update\M365TenantConfig.ps1:14984
 Line |
14984 |                  MSFT_MicrosoftGraphwindowsFirewallRule{
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | At least one of the values 'System.Object[]' is not supported or valid for property
      | 'InterfaceTypes' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify
      | only supported values: notConfigured, remoteAccess, wireless, lan.
Write-Error: C:\SIT\test_update\M365TenantConfig.ps1:14984
 Line |
14984 |                  MSFT_MicrosoftGraphwindowsFirewallRule{
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | At least one of the values 'System.Object[]' is not supported or valid for property
      | 'ProfileTypes' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify
      | only supported values: notConfigured, domain, private, public.
Write-Error: C:\SIT\test_update\M365TenantConfig.ps1:14984
 Line |
14984 |                  MSFT_MicrosoftGraphwindowsFirewallRule{
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | At least one of the values 'System.Object[]' is not supported or valid for property
      | 'TrafficDirection' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify
      | only supported values: notConfigured, out, in.
Write-Error: C:\SIT\test_update\M365TenantConfig.ps1:15008
 Line |
15008 |                  MSFT_MicrosoftGraphwindowsFirewallRule{
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | At least one of the values 'System.Object[]' is not supported or valid for property
      | 'Action' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify only
      | supported values: notConfigured, blocked, allowed.
Write-Error: C:\SIT\test_update\M365TenantConfig.ps1:15008
 Line |
15008 |                  MSFT_MicrosoftGraphwindowsFirewallRule{
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | At least one of the values 'System.Object[]' is not supported or valid for property
      | 'EdgeTraversal' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify
      | only supported values: notConfigured, blocked, allowed.
Write-Error: C:\SIT\test_update\M365TenantConfig.ps1:15008
 Line |
15008 |                  MSFT_MicrosoftGraphwindowsFirewallRule{
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | At least one of the values 'System.Object[]' is not supported or valid for property
      | 'InterfaceTypes' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify
      | only supported values: notConfigured, remoteAccess, wireless, lan.
Write-Error: C:\SIT\test_update\M365TenantConfig.ps1:15008
 Line |
15008 |                  MSFT_MicrosoftGraphwindowsFirewallRule{
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | At least one of the values 'System.Object[]' is not supported or valid for property
      | 'ProfileTypes' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify
      | only supported values: notConfigured, domain, private, public.
Write-Error: C:\SIT\test_update\M365TenantConfig.ps1:15008
 Line |
15008 |                  MSFT_MicrosoftGraphwindowsFirewallRule{
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | At least one of the values 'System.Object[]' is not supported or valid for property
      | 'TrafficDirection' on class 'MSFT_MicrosoftGraphWindowsFirewallRule'. Please specify
      | only supported values: notConfigured, out, in.
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB}
```

**Comment by ChrisJay77** [comment]
I've updated to 1.23.1108.1 and still get the same error, any update on the issue @andikrueger ? Thanks

**Comment by andikrueger** [comment]
@William-Francillette Could you have a look at this issue? This looks like the validate set and the cmdLet's parameters do not match. Thanks!

**Comment by William-Francillette** [comment]
Sure leave it with me

**Comment by ricmestre** [comment]
@william-francillette Hi, I reported another issue #3444 for this resource, it now works for deploying to another tenants but when re-deploying the tests fail and always tries to update the policies even though they are all correct as in the blueprint configuration.

Could you please ensure this is also fixed?

**Comment by William-Francillette** [comment]
Thanks @ChrisJay77  for reporting the issue, there was a problem with parsing FirewallRules 
![image](https://github.com/microsoft/Microsoft365DSC/assets/79221284/915f9ce6-2dba-4383-9b1a-5fd61d2958f8)

I was able to export, create and update the policy successfully

@ricmestre I've also resolved your issue - Test-TargetResource was evaluating the Id parameter and thus returning false when duplicating the policy to a new tenant (the Id would have been different)
