### ISSUE TITLE
Copying between GCC and GCC High

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#3875]
Can we use this tool to copy configuration settings between M365 GCC/Azure Commercial and M365 GCC High/Azure Government?

**Comment by desmay** [comment]
Yes, the MSCLoudLogin should handle the differences between endpoints in authentication but you may run into some issues with feature parity.

**Comment by andikrueger** [comment]
@DeanGross Please let us know, if you encounter any issues. 

The user guide should help to get you started with a cloning your settings from one tenant to another: https://microsoft365dsc.com/user-guide/get-started/introduction/
