### ISSUE TITLE
looking for "External collaboration settings"

### ISSUE THREAD

**Issue by OlivierWaterloos** [microsoft/Microsoft365DSC#3903]
Hello,

in which configuration/resource can I find the "External collaboration settings"?
[https://portal.azure.com/#view/Microsoft_AAD_IAM/AllowlistPolicyBlade](https://portal.azure.com/#view/Microsoft_AAD_IAM/AllowlistPolicyBlade)
Thanks

regards

Olivier

**Comment by andikrueger** [comment]
This can be done using the MSFT_AADAuthorizationPolicy resource.

**Comment by OlivierWaterloos** [comment]
Thank you for the answer. 
In that part, I do not found the list of domain "Collaboration restrictions", "Allow invitations only to the specified domains (most restrictive)". I cannot found it in the report? Is it in another resource or configuration?

**Comment by andikrueger** [comment]
Looks like these properties are not returned by Graph: https://learn.microsoft.com/en-us/graph/api/authorizationpolicy-get?view=graph-rest-beta&tabs=powershell

The mentioned parameters can only be set using the AzureADPreview cmdLets: https://learn.microsoft.com/en-us/entra/external-id/allow-deny-list#use-the-azureadpolicy-cmdlets-to-configure-the-policy

**Comment by andikrueger** [comment]
... and it looks like, that we had a resource within M365DSC in 2020 to 2021. This resource might have been able to manage the policy settings for these parameters. https://github.com/microsoft/Microsoft365DSC/pull/883

AADPolicy got replaced by AADTokenLifetimePolicy in Release 1.21.1006.1 https://github.com/microsoft/Microsoft365DSC/commit/eb255d3a3627209ed8a65db90e243d54e3efb6dd which does not offer all the previous options. 

It looks like the complex datatype of Get-MGPolicyTokenLifeTImePolicy would allow the configuration for B2B as well: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/get-mgpolicytokenlifetimepolicy?view=graph-powershell-1.0#notes
