### ISSUE TITLE
Dependency on 2.9.0 version of MS Graph instead of 2.9.1

### ISSUE THREAD

**Issue by sdfarquhar** [microsoft/Microsoft365DSC#3918]
### Description of the issue

It appears that the DSC modules are only allowing version 2.9.0 of the MS Graph modules even though 2.9.1 was just released which fixes issues with connecting while using system managed identity such as those used in Azure Automation.  

Additionally, there also appears to be dependency on the previous versions of MicrosoftTeams and PnP.PowerShell modules.  

### Microsoft 365 DSC Version

1.23.1115.1

### Which workloads are affected

Azure Active Directory, Exchange Online, Office 365 Admin, OneDrive for Business, Planner, Power Platform, Security & Compliance Center, SharePoint Online, Teams

**Comment by andikrueger** [comment]
The dependencies are updated as soon as there is a new version available. Basically every M365 release can contain a new set of dependencies. Next M365DSC release should happen on Wednesday.
