### ISSUE TITLE
When to hoist properties out of complex types?

### ISSUE THREAD

**Issue by fraserdarwent** [microsoft/Microsoft365DSC#3927]
I'm looking to contribute back by adding some missing properties to resources and am looking for some guidance one when to hoist a property out of a complex type to the top level. For example in `AADApplication` the property `KnownClientApplications` is hoisted out of the `api` type to a top level, but in `AADCrossTenantAccessPolicyConfigurationDefault` the `b2bCollaborationInbound` property is left as a complex type. Is there a preference for one over the other or how should the decision be made? Thanks.

**Comment by fraserdarwent** [comment]
Sure, so [b2bCollaborationInbound in the graph API](https://learn.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyconfigurationdefault?view=graph-rest-1.0#properties) is exposed [as a complex type in Microsoft365DSC](https://microsoft365dsc.com/resources/azure-ad/AADCrossTenantAccessPolicyConfigurationDefault/#parameters), compared to [api.knownClientApplications](https://learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0#properties) which is [exposed as a top level string array in Microsoft365DSC](https://microsoft365dsc.com/resources/azure-ad/AADApplication/#parameters). Hope that makes sense?

**Comment by andikrueger** [comment]
this aligns very much with the complexity of these objects. b2bCollabpration settings have various parameters each, whereas knowClientApplications would only be an array of GUIDs

**Comment by andikrueger** [comment]
I would expose these properties at the top level and not as complex API prop for now. Changing it to a general API parameter would result in a breaking change.

https://learn.microsoft.com/en-us/graph/api/resources/apiapplication?view=graph-rest-1.0#json-representation


```json
{
  "acceptMappedClaims": true,
  "knownClientApplications": ["Guid"],
  "oauth2PermissionScopes": [{"@odata.type": "microsoft.graph.permissionScope"}],
  "preAuthorizedApplications": [{"@odata.type": "microsoft.graph.preAuthorizedApplication"}],
  "requestedAccessTokenVersion": 2
}
```

`oauth2PermissionScopes` and `preAuthorizedApplications` look like good parameters for complex types: 
```json
{
  "id": "Guid",
  "adminConsentDisplayName": "String",
  "adminConsentDescription": "String",
  "userConsentDisplayName": "String",
  "userConsentDescription": "String",
  "value": "String",
  "type": "String",
  "isEnabled": true
}
```
