### ISSUE TITLE
AADAttributeSet: Insufficient privileges to complete the operation.

### ISSUE THREAD

**Issue by skghq** [microsoft/Microsoft365DSC#3939]
### Description of the issue

I have already ran: `Update-M365DSCAllowedGraphScopes -All -Type Read`

`
[2023/11/22 03:25:22]
{InvalidOperation}
System.Exception: [Authorization_RequestDenied] : Insufficient privileges to complete the operation.
"Error during Export:"
at Get-MgBetaDirectoryAttributeSet<Process>, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Beta.Identity.DirectoryManagement\2.9.0\exports\ProxyCmdletDefinitions.ps1: line 32592
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1115.1\DSCResources\MSFT_AADAttributeSet\MSFT_AADAttributeSet.psm1: line 318
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1115.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1115.1\modules\M365DSCUtil.psm1: line 1320
at <ScriptBlock>, C:\<<<redacted>>>\Office365_Backup_Debug.ps1: line 98
<<<redacted>>>@<<<redacted>>>.onmicrosoft.com
TenantId: <<<redacted>>>.onmicrosoft.com
`

Transcript started, output file is C:\temp\<<<redacted>>>\debug\log\AADAttributeSet.txt
Exporting Microsoft 365 configuration for Components: AADAttributeSet
 
Authentication methods specified:
- Credentials
 
Connecting to {MicrosoftGraph}...✅
[1/1] Extracting [AADAttributeSet] using {Credentials}...❌
 Error Log created at {file://C:/temp/<<<redacted>>>/debug/cwd/5112-M365DSC-ErrorLog.log}
⌛ Export took {1 seconds}
Transcript stopped, output file is C:\temp\<<<redacted>>>\debug\log\AADAttributeSet.txt

### Microsoft 365 DSC Version

1.23.1115.1

### Which workloads are affected

Azure Active Directory

### The DSC configuration

```powershell
##################  AADAttributeSet  ##################
$LogFile = "C:\temp\<<<redacted>>>\debug\log\AADAttributeSet.txt"
$FileName = "AADAttributeSet.ps1"
Start-Transcript -Path $LogFile
Export-M365DSCConfiguration -Components @("AADAttributeSet") -Credential $Credential -Path $FilePath -FileName $FileName
Stop-Transcript
```

### Verbose logs showing the problem

```powershell
[2023/11/22 03:25:22]
{InvalidOperation}
System.Exception: [Authorization_RequestDenied] : Insufficient privileges to complete the operation.
"Error during Export:"
at Get-MgBetaDirectoryAttributeSet<Process>, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Beta.Identity.DirectoryManagement\2.9.0\exports\ProxyCmdletDefinitions.ps1: line 32592
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1115.1\DSCResources\MSFT_AADAttributeSet\MSFT_AADAttributeSet.psm1: line 318
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1115.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1115.1\modules\M365DSCUtil.psm1: line 1320
at <ScriptBlock>, C:\<<<redacted>>>\Office365_Backup_Debug.ps1: line 98
<<<redacted>>>@<<<redacted>>>.onmicrosoft.com
TenantId: <<<redacted>>>.onmicrosoft.com



Transcript started, output file is C:\temp\<<<redacted>>>\debug\log\AADAttributeSet.txt
Exporting Microsoft 365 configuration for Components: AADAttributeSet
 
Authentication methods specified:
- Credentials
 
Connecting to {MicrosoftGraph}...✅
[1/1] Extracting [AADAttributeSet] using {Credentials}...❌
 Error Log created at {file://C:/temp/<<<redacted>>>/debug/cwd/5112-M365DSC-ErrorLog.log}
⌛ Export took {1 seconds}
Transcript stopped, output file is C:\temp\<<<redacted>>>\debug\log\AADAttributeSet.txt
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.17763.4974
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.17763.4974
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by skghq** [comment]
I have upgraded to 1.23.1122.1. This is still an issue.

**Comment by andikrueger** [comment]
Could you outline the permissions of the account used? Is this a global reader account?

**Comment by andikrueger** [comment]
@skghq are there any updates?

**Comment by skghq** [comment]
@andikrueger I will be picking this back over the next few days. We have recently overhauled our configuration.

**Comment by skghq** [comment]
I have upgraded to 1.24.228.1 and it's still failing, but, obviously this is a tenant configuration issue.

The account being used is a global administrator @andikrueger

**Comment by skghq** [comment]
@andikrueger Yes -- no luck. It is still failing.

**Comment by bartvermeersch** [comment]
You are aware that by default even the global admin isn't able to read custom security attributes?

[from](https://learn.microsoft.com/en-us/graph/api/resources/custom-security-attributes-overview?view=graph-rest-1.0#permissions): To manage custom security attributes, the calling principal must be assigned one of the following Microsoft Entra roles. By default, Global Administrator and other administrator roles do not have permissions to read, define, or assign custom security attributes.

[Attribute Definition Reader](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#attribute-definition-reader)
[Attribute Definition Administrator](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#attribute-definition-administrator)
[Attribute Assignment Reader](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#attribute-assignment-reader)
[Attribute Assignment Administrator](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#attribute-assignment-administrator)
Also, the calling principal must be granted the appropriate [custom security attributes permissions](https://learn.microsoft.com/en-us/graph/permissions-reference#custom-security-attributes-permissions).

**Comment by skghq** [comment]
@bartvermeersch I was not. That resolved it.

Thanks!
