### ISSUE TITLE
AADSocialIdentityProvider: [AADB2C] : The application does not have any of the required delegated permissions (IdentityProvider.Read.All, IdentityProvider.ReadWrite.All) to access the resource.  "Error during Export:"

### ISSUE THREAD

**Issue by skghq** [microsoft/Microsoft365DSC#3941]
### Description of the issue

I have already ran: `Update-M365DSCAllowedGraphScopes -All -Type Read`

Command:
`Export-M365DSCConfiguration -Components @("AADSocialIdentityProvider") -Credential $Credential -Path $FilePath -FileName $FileName`

Stack Trace;
`
[2023/11/22 03:30:23]
{InvalidOperation}
System.Exception: [AADB2C] : The application does not have any of the required delegated permissions (IdentityProvider.Read.All, IdentityProvider.ReadWrite.All) to access the resource. 
"Error during Export:"
at Get-MgBetaIdentityProvider<Process>, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Beta.Identity.SignIns\2.9.0\exports\ProxyCmdletDefinitions.ps1: line 17960
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1115.1\DSCResources\MSFT_AADSocialIdentityProvider\MSFT_AADSocialIdentityProvider.psm1: line 349
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1115.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1115.1\modules\M365DSCUtil.psm1: line 1320
at <ScriptBlock>, C:\Scripts\<<<redacted>>>\Office365_Backup_Debug.ps1: line 842
<<<redacted>>>@<<<redacted>>>.onmicrosoft.com
TenantId: <<<redacted>>>.onmicrosoft.com
`

PS Output:
Transcript started, output file is C:\temp\<<<redacted>>>\debug\log\AADSocialIdentityProvider.txt
Exporting Microsoft 365 configuration for Components: AADSocialIdentityProvider
 
Authentication methods specified:
- Credentials
 
Connecting to {MicrosoftGraph}...✅
[1/1] Extracting [AADSocialIdentityProvider] using {Credentials}...❌
 Error Log created at {file://C:/temp/<<<redacted>>>/debug/cwd/5112-M365DSC-ErrorLog.log}
⌛ Export took {2 seconds}
Transcript stopped, output file is C:\temp\<<<redacted>>>\debug\log\AADSocialIdentityProvider.txt

### Microsoft 365 DSC Version

1.23.1115.1

### Which workloads are affected

Azure Active Directory

### The DSC configuration

```powershell
Export-M365DSCConfiguration -Components @("AADSocialIdentityProvider") -Credential $Credential -Path $FilePath -FileName $FileName
```

### Verbose logs showing the problem

```powershell
[2023/11/22 03:30:23]
{InvalidOperation}
System.Exception: [AADB2C] : The application does not have any of the required delegated permissions (IdentityProvider.Read.All, IdentityProvider.ReadWrite.All) to access the resource. 
"Error during Export:"
at Get-MgBetaIdentityProvider<Process>, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Beta.Identity.SignIns\2.9.0\exports\ProxyCmdletDefinitions.ps1: line 17960
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1115.1\DSCResources\MSFT_AADSocialIdentityProvider\MSFT_AADSocialIdentityProvider.psm1: line 349
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1115.1\modules\M365DSCReverse.psm1: line 615
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1115.1\modules\M365DSCUtil.psm1: line 1320
at <ScriptBlock>, C:\Scripts\<<<redacted>>>\Office365_Backup_Debug.ps1: line 842
<<<redacted>>>@<<<redacted>>>.onmicrosoft.com
TenantId: <<<redacted>>>.onmicrosoft.com
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.17763.4974
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.17763.4974
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by andikrueger** [comment]
Please make sure to add the following permission to your application: IdentityProvider.Read.All

It looks like this permission is missing in the resource's setting.json file.

**Comment by skghq** [comment]
I have upgraded to 1.24.228.1 and it's still an issue @andikrueger. My "main" export is still running. Once it completes I will go back and manually add the permission.

`[2024/03/01 04:43:32]
{InvalidOperation}
System.Exception: [AADB2C] : The application does not have any of the required delegated permissions (IdentityProvider.Read.All, IdentityProvider.ReadWrite.All) to access the resource. 
"Error during Export:"
at Get-MgBetaIdentityProvider<Process>, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Beta.Identity.SignIns\2.14.1\exports\ProxyCmdletDefinitions.ps1: line 20299
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.228.1\DSCResources\MSFT_AADSocialIdentityProvider\MSFT_AADSocialIdentityProvider.psm1: line 350
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.228.1\Modules\M365DSCReverse.psm1: line 649
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.228.1\Modules\M365DSCUtil.psm1: line 1357
at <ScriptBlock>, C:\Scripts\username\From-server\Office365_Backup_Debug.ps1: line 850`
