### ISSUE TITLE
NewResource: Ability to control Teams Settings on client

### ISSUE THREAD

**Issue by viksrini** [microsoft/Microsoft365DSC#3969]
### Description
The following is being requested
1. Ability to control auto launch setting for teams. Currently possible via

        You can the settings in Microsoft Teams and see if that helps:
        1. Launch Microsoft Teams.
        2. Click on the Profile icon on the top right corner and click on Settings.
        3. Scroll down and clear the checkbox for Auto Start Application.
2. Ability to set default device notifications for teams
3. Ability to switch device sync options in Teams
4. Ability to toggle Optional connected experiences
### Special considerations or limitations
This is a client side setting . No sure if this is possible using DSC or GPU since the new teams client does not support GPU.

**Comment by andikrueger** [comment]
I'll close this issue for now.
