### ISSUE TITLE
Microsoft365DSC -Global admin and update the policy to new tenant

### ISSUE THREAD

**Issue by pradeepmnrecit** [microsoft/Microsoft365DSC#3974]
Dear All

I have one office 365 tenant A and target tenant B and having Global Admin User in Both.
I need to capture tenant A teams policy and apply the same in tenant B. Kindly tell What i am doing is right. 

1)export the teams policy from tenant A using export.Here i ama using Global admin of tenant A .The the filename save as M365TeamsConfig.ps1

# Generated by Microsoft365DSC from https://export.microsoft365dsc.com on 11/24/2023, 10:10:46 AM
# Visit https://microsoft365dsc.com for more information

# Getting client credential
$Credential = Get-Credential

# Exporting resources using credentials
Export-M365DSCConfiguration -Components @("TeamsAppPermissionPolicy", "TeamsAppSetupPolicy", "TeamsAudioConferencingPolicy", "TeamsCallHoldPolicy", "TeamsCallingPolicy", "TeamsCallParkPolicy", "TeamsCallQueue", "TeamsChannel", "TeamsChannelsPolicy", "TeamsChannelTab", "TeamsClientConfiguration", "TeamsComplianceRecordingPolicy", "TeamsCortanaPolicy", "TeamsDialInConferencingTenantSettings", "TeamsEmergencyCallingPolicy", "TeamsEmergencyCallRoutingPolicy", "TeamsEnhancedEncryptionPolicy", "TeamsEventsPolicy", "TeamsFederationConfiguration", "TeamsFeedbackPolicy", "TeamsFilesPolicy", "TeamsGroupPolicyAssignment", "TeamsGuestCallingConfiguration", "TeamsGuestMeetingConfiguration", "TeamsGuestMessagingConfiguration", "TeamsIPPhonePolicy", "TeamsMeetingBroadcastConfiguration", "TeamsMeetingBroadcastPolicy", "TeamsMeetingConfiguration", "TeamsMeetingPolicy", "TeamsMessagingPolicy", "TeamsMobilityPolicy", "TeamsNetworkRoamingPolicy", "TeamsOnlineVoicemailPolicy", "TeamsOnlineVoicemailUserSettings", "TeamsOnlineVoiceUser", "TeamsOrgWideAppSettings", "TeamsPstnUsage", "TeamsShiftsPolicy", "TeamsTeam", "TeamsTemplatesPolicy", "TeamsTenantDialPlan", "TeamsTenantNetworkRegion", "TeamsTenantNetworkSite", "TeamsTenantNetworkSubnet", "TeamsTenantTrustedIPAddress", "TeamsTranslationRule", "TeamsUnassignedNumberTreatment", "TeamsUpdateManagementPolicy", "TeamsUpgradeConfiguration", "TeamsUpgradePolicy", "TeamsUser", "TeamsUserCallingSettings", "TeamsUserPolicyAssignment", "TeamsVdiPolicy", "TeamsVoiceRoute", "TeamsVoiceRoutingPolicy", "TeamsWorkloadPolicy") -Credential $Credential

2) Run the PS M365TeamsConfig.ps1 in the PS  and then generate the configuration file for build MOF .This process will create configuration file and mof under the below folder

C:\DSC\M365TenantConfig

3) Then i update the taget tenant global admin credential in the MOF as  below.

![image](https://github.com/microsoft/Microsoft365DSC/assets/151814818/1c4a8f97-3aa8-4d09-8912-22b7eb42b204)

4)then i run Start-DSCConfiguration -Path C:\DSC\M365TenantConfig -Wait -Verbose -Force

My question here is what i did is correct. Kindly guide if i am wrong.
Thanks
Pradeep

**Comment by pradeepmnrecit** [comment]
Hi Anybody can advice ?

**Comment by andikrueger** [comment]
Please run the export with the Source Tenant Admin Credentials. After that compile the configuration with the target tenant admin credentials. After that you can apply the configuration.

**Comment by pradeepmnrecit** [comment]
Thanks Andi
