### ISSUE TITLE
Unable to update IntuneAntivirusPolicyWindows10SettingCatalog settings on existing policy

### ISSUE THREAD

**Issue by Cyanic-Cloud** [microsoft/Microsoft365DSC#4003]
### Description of the issue

When deploying a **New** IntuneAntivirusPolicyWindows10SettingCatalog policy the policy deploys without issue, using the below DSC configuration shown in the DSC Configuration Tab labeled "**Deployed Config**".

If I attempt to update a setting **allowarchivescanning** to "0" and re-run the deployment pipeline again using the **Updated config** DSC config the policy is not updated.  No errors are reported in the pipeline but I get the following error when I view the Event logs on the deployment agent:

{ Response status code does not indicate success: BadRequest (Bad Request). } \ at Update-IntuneDeviceConfigurationPolicy, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1129.1\DscResources\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog.psm1: line 1658
 \ at Set-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1129.1\DscResources\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog.psm1: line 898

### Microsoft 365 DSC Version

1.23.1129.1

### Which workloads are affected

Endpoint security | Antivirus

### The DSC configuration

```powershell
Deployed Config

IntuneAntivirusPolicyWindows10SettingCatalog "IntuneAntivirusPolicyWindows10SettingCatalog-Baseline - MDE - Microsoft Defender AUDIT ONLY (SERVER)"
{
    allowarchivescanning                = "1";
    allowbehaviormonitoring             = "1";
    allowcloudprotection                = "1";
    allowemailscanning                  = "1";
    allowfullscanonmappednetworkdrives  = "1";
    allowfullscanremovabledrivescanning = "1";
    allowintrusionpreventionsystem      = "1";
    allowioavprotection                 = "1";
    allowonaccessprotection             = "1";
    allowrealtimemonitoring             = "1";
    allowscanningnetworkfiles           = "1";
    allowscriptscanning                 = "1";
    allowuseruiaccess                   = "0";
    ApplicationId                       = $ApplicationId
    Assignments                         = @();
    avgcpuloadfactor                    = 32;
    CertificateThumbprint               = $Thumbprint
    checkforsignaturesbeforerunningscan = "1";
    cloudblocklevel                     = "0";
    Description                         = "Microsoft Defender AUDIT ONLY";
    disablecatchupfullscan              = "1";
    disablecatchupquickscan             = "1";
    DisplayName                         = "Baseline - MDE - Microsoft Defender AUDIT ONLY (SERVER)";
    enablelowcpupriority                = "1";
    enablenetworkprotection             = "2";
    Ensure                              = "Present";
    highseveritythreats                 = "allow";
    Identity                            = "6e00f3f4-6d64-485c-931b-4e7ac62eb4a4";
    lowseveritythreats                  = "allow";
    moderateseveritythreats             = "allow";
    puaprotection                       = "2";
    realtimescandirection               = "0";
    scanparameter                       = "2";
    severethreats                       = "allow";
    submitsamplesconsent                = "1";
    templateId                          = "804339ad-1553-4478-a742-138fb5807418_1";
    TenantId                            = $TenantId
}


Updated config:

IntuneAntivirusPolicyWindows10SettingCatalog "IntuneAntivirusPolicyWindows10SettingCatalog-Baseline - MDE - Microsoft Defender AUDIT ONLY (SERVER)"
{
    allowarchivescanning                = "0";
    allowbehaviormonitoring             = "1";
    allowcloudprotection                = "1";
    allowemailscanning                  = "1";
    allowfullscanonmappednetworkdrives  = "1";
    allowfullscanremovabledrivescanning = "1";
    allowintrusionpreventionsystem      = "1";
    allowioavprotection                 = "1";
    allowonaccessprotection             = "1";
    allowrealtimemonitoring             = "1";
    allowscanningnetworkfiles           = "1";
    allowscriptscanning                 = "1";
    allowuseruiaccess                   = "0";
    ApplicationId                       = $ApplicationId
    Assignments                         = @();
    avgcpuloadfactor                    = 32;
    CertificateThumbprint               = $Thumbprint
    checkforsignaturesbeforerunningscan = "1";
    cloudblocklevel                     = "0";
    Description                         = "Microsoft Defender AUDIT ONLY";
    disablecatchupfullscan              = "1";
    disablecatchupquickscan             = "1";
    DisplayName                         = "Baseline - MDE - Microsoft Defender AUDIT ONLY (SERVER)";
    enablelowcpupriority                = "1";
    enablenetworkprotection             = "2";
    Ensure                              = "Present";
    highseveritythreats                 = "allow";
    Identity                            = "6e00f3f4-6d64-485c-931b-4e7ac62eb4a4";
    lowseveritythreats                  = "allow";
    moderateseveritythreats             = "allow";
    puaprotection                       = "2";
    realtimescandirection               = "0";
    scanparameter                       = "2";
    severethreats                       = "allow";
    submitsamplesconsent                = "1";
    templateId                          = "804339ad-1553-4478-a742-138fb5807418_1";
    TenantId                            = $TenantId
}
```

### Verbose logs showing the problem

```powershell
{ Response status code does not indicate success: BadRequest (Bad Request). } \ at Update-IntuneDeviceConfigurationPolicy, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1129.1\DscResources\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog.psm1: line 1658
 \ at Set-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1129.1\DscResources\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog.psm1: line 898
```

**Comment by Cyanic-Cloud** [comment]
@William-Francillette have you came across this issue when testing?

**Comment by ricmestre** [comment]
I already reported other issues on #3958, but on the topic of changing properties (except Ensure) I tested it again and it seems that the policy itself actually gets changed nevertheless in the admin portal it stays the same, not sure if it's some kind of delay or just an UI problem.

**Comment by ricmestre** [comment]
@cyanic-cloud Not sure how you're getting the error message, but I don't have any.

**Comment by Cyanic-Cloud** [comment]
See below, this is where the error message is shown.

![image](https://github.com/microsoft/Microsoft365DSC/assets/104797528/6501d03b-858f-4b92-8cc6-3018592a8a69)

I have implemented the same set up as per the whitepaper docs.

https://aka.ms/m365dscwhitepaper

**Comment by ricmestre** [comment]
I know where to look for errors, what I'm trying to say is that I don't have any.

**Comment by Cyanic-Cloud** [comment]
> > @William-Francillette have you came across this issue when testing?
> 
> Nope I didn't but I'll have a look as the api is not really user friendly for those setting catalog templates In the background, some of the parameters requires a settingvaluerefence and some not and not sure how this is validated and don't know if or where it is documented. I've used the parameter definition to build the body of the query and it always returns the settingvaluereference so if not required then you often get that generic error message bad request ... The only way I found to check it, is to look at the payload in the intune portal and skip that reference if it's not present
> 
> It's a very tedious process and thus not checked all parameters Leave it with me 👍🏽


Thanks @William-Francillette, appreciate the help, I noticed the below like you mentioned :

![image](https://github.com/microsoft/Microsoft365DSC/assets/104797528/3bd5a4cf-8d76-4fb9-ac38-ced5c1533e8f)

**Comment by ricmestre** [comment]
So basically what is happening here is that some properties work and others don't, the one you're changing doesn't work and gives error, I was for example changing *allowrealtimemonitoring* and that one worked but it seems they also have different meanings of what 0 and 1 means since for that property 0 means "allow" and 1 "not allow" whereas the one you're changing *allowarchivescanning* it's the opposite.

**Comment by Cyanic-Cloud** [comment]
> So basically what is happening here is that some properties work and others don't, the one you're changing doesn't work and gives error, I was for example changing _allowrealtimemonitoring_ and that one worked but it seems they also have different meanings of what 0 and 1 means since for that property 0 means "allow" and 1 "not allow" whereas the one you're changing _allowarchivescanning_ it's the opposite.

**Having looked at a few it seems 1 is Allowed and 0 is Not allowed** 

**Allowed**
"value": "device_vendor_msft_policy_config_defender_allowarchivescanning_1",
![image](https://github.com/microsoft/Microsoft365DSC/assets/104797528/cfd9dcd4-f1a1-417e-85cb-0e49ee96238e)

**Not Allowed**
"value": "device_vendor_msft_policy_config_defender_allowarchivescanning_0",
![image](https://github.com/microsoft/Microsoft365DSC/assets/104797528/998c6144-973d-48b9-9c88-cbaf1219168c)


**Allowed**
"value": "device_vendor_msft_policy_config_defender_allowrealtimemonitoring_1"
![image](https://github.com/microsoft/Microsoft365DSC/assets/104797528/2056c86b-2ef2-4460-855f-31e579b3fe3a)

**Not Allowed**
  "value": "device_vendor_msft_policy_config_defender_allowrealtimemonitoring_0"
![image](https://github.com/microsoft/Microsoft365DSC/assets/104797528/9ea31f5d-5bc4-4b49-9349-e7ccf256d418)

**Comment by ricmestre** [comment]
@cyanic-cloud You're right, I seem to be having some delay at times dealing with this policy and it didn't update the changes I did on *allowrealtimemonitoring* through M365DSC right away in the UI, now it shows like yours as well, but *allowarchivescanning* cannot be changed only exporting, don't know about all others.

**Comment by ricmestre** [comment]
@William-Francillette I used his config too with your fixes, I only tested 2 properties and as mentioned here already at least updating allowarchivescanning fails and  allowrealtimemonitoring works, didn't go through every single parameter.

**Comment by William-Francillette** [comment]
I've tried updating both parameters using 1.23.1122.1 without issue

**Comment by ricmestre** [comment]
Im using 1129, but have you actually saw allowarchivescanning change in the admin portal? Exporting it is not an issue, either its value is 0 or 1 but if you change the value in the MOF and redeploy the policy it won't complain in the CLI but there will be an error in event viewer.

**Comment by William-Francillette** [comment]
changed the value run dsc config twice - first time it triggers set-targetresource second time test-targetresource return true

**Comment by William-Francillette** [comment]
Same after update running 1.23.1206.1 and it's all working on my side still 🤷‍♂️

**Comment by Cyanic-Cloud** [comment]
Thanks @William-Francillette I am testing now, will revert back with outcome, although I do think I rebooted the host after but could be wrong haha

**Comment by ricmestre** [comment]
@William-Francillette @Cyanic-Cloud I updated to 1.23.1206.1 and restart winmgmt service and it still didn't work, BUT after deleting the policy and recreating it again now I'm able to change several of this resource's properties and the Test-TargetResource/Test-DSCConfigurations always succeeds.

Still not sure what was the problem with the original policy though...

**Comment by ricmestre** [comment]
I shouldn't be making these tests while I'm about to sleep, this is actually not working, it seemed like it was because I had Ensure = Absent so the tests always succeeded.

I tested it creating the policy again right now, which it does without issues regardless of the values of the properties, but then trying to change any property never updates the policy and it's always in non-desired state. In fact now I tried to change *allowrealtimemonitoring* and that one is also not working! I don't know what's going on and won't have time to debug it further.

**Comment by Cyanic-Cloud** [comment]
@ricmestre I am semi glad to hear you say this as ive been trying to get it working since last night and it wasnt working so I was scratching my head trying to work out what I was doing wrong.  Like as you say it deploys the policy without issue but when new values are added to the likes of allowarchivescanning it fails to update.
I have attempted to fully uninstall every trace of DSC and reinstall using the most recent version 3 times but having read your above command I think its safe to say its still not working.
@William-Francillette I would love to compare your current set up to see how you're archiving this?

Still getting the below error shown in the Event logs:

Error updating data:

{ Response status code does not indicate success: BadRequest (Bad Request). } \ at Update-IntuneDeviceConfigurationPolicy, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1206.1\DscResources\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog.psm1: line 1658
 \ at Set-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1206.1\DscResources\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog.psm1: line 898

**Comment by Cyanic-Cloud** [comment]
I am clutching at straws here but the error above suggests an issue with line 1658 within the following file:
**C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1206.1\DscResources\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog\MSFT_IntuneAntivirusPolicyWindows10SettingCatalog.psm1**

If I look at that line it using PUT, should this not be PATCH according to the Microsoft Documentation?
https://learn.microsoft.com/en-us/graph/api/intune-deviceconfigv2-devicemanagementconfigurationpolicy-update?view=graph-rest-beta

![image](https://github.com/microsoft/Microsoft365DSC/assets/104797528/4efa2e97-c9c8-4170-a412-edb93ad0e754)

**Comment by Cyanic-Cloud** [comment]
Yeah I tested also, currently running the pipeline again and running verbose log to see that its sending in the request.

**Comment by Cyanic-Cloud** [comment]
**Some progress, if I run the following:**
Export-M365DSCConfiguration -Components @("IntuneAntivirusPolicyWindows10SettingCatalog") -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId

Edit allowarchivescanning within M365TenantConfig.ps1

Then create my mof file using  .\M365TenantConfig.ps1

Start-DSCConfiguration -Path "C:\Temp\DSC Config Exports\Exports\071223\M365TenantConfig" -Wait -Verbose -Force

The setting changes as expected.

Why its not changing during the pipeline is beyond me

**Comment by ricmestre** [comment]
Tried it today in my DevOps test harness pipeline (which creates, updates and finally deletes resources), in the first pass I had left an AV policy already created in my tenant so during create stage of the pipeline it updated that policy without issues, and the same happened during the update and deletion stages. I then tried a second pass, at this point there wasn't any AV policies left in the tenant so it created the policy again, but in the update stage it says that the policy was updated but I always run Test-DSCConfiguration at the end of each stage and this time it failed and pipeline stopped.

**Comment by William-Francillette** [comment]
The order doesn't matter unfortunately I will try as ric mentioned using absent then recreate and update settings will revert back asap

**Comment by William-Francillette** [comment]
Good news gents! Found the issue and corrected it - the Identity parameter was wrong when we retrieved the policy from displayName 
Pushing PR now

**Comment by Cyanic-Cloud** [comment]
I made the change manually for now adding $currentPolicy.Identity and it all works a treat! 
I'll be sure to update all your changes once the new release has been pushed, but for now i'll close this ticket.
Thanks :-)
