### ISSUE TITLE
Authentication through application secret fails after upgrade to version 1.23.1206.1

### ISSUE THREAD

**Issue by horgasz2023** [microsoft/Microsoft365DSC#4013]
### Description of the issue

Export for Entra ID resources fails when using Application secret authentication.
Last time checked with these 7 resources: AADAuthenticationMethodPolicy, AADEntitlementManagementAccessPackageCatalogResource, AADGroupLifecyclePolicy, AADRoleDefinition, AADRoleSetting, AADTokenLifetimePolicy

### Microsoft 365 DSC Version

1.23.1206.1

### Which workloads are affected

Azure Active Directory

### The DSC configuration

```powershell
PS C:\WINDOWS\system32> Get-Module Microsoft365DSC -ListAvailable | select ModuleBase, Version

 

 

ModuleBase                                                             Version   

----------                                                             -------   

C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1206.1 1.23.1206.1
```

### Verbose logs showing the problem

```powershell
Export-M365DSCConfiguration -Components @("AADAuthenticationMethodPolicy", "AADEntitlementManagementAccessPackageCatalogResource", "AADGroupLifecyclePolicy", "AADRoleDefinition", "AADRoleSetting", "AADTokenLifetimePolicy") -ApplicationId $ApplicationId -ApplicationSecret $ApplicationSecret -TenantId $TenantId -Path 'C:\M365DSC\Exports' -FileName "M365DSC_IssueComponentsOnly_PROD_$(get-date -f yyyy-MM-dd).ps1"

Exporting Microsoft 365 configuration for Components: AADAuthenticationMethodPolicy, AADEntitlementManagementAccessPackageCatalogResource, AADGroupLifecyclePolicy, AADRoleDefinition,

AADRoleSetting, AADTokenLifetimePolicy

Authentication methods specified:

- Service Principal with Application Secret

Partial Export file was saved at: C:\Users\AVDAdmin\AppData\Local\Temp\2d4c174d-75d1-4a82-8bba-18be67d12aec.partial.ps1

Get-MgBetaOrganization : CompactToken parsing failed with error code: 80049217

Status: 401 (Unauthorized)

ErrorCode: InvalidAuthenticationToken

Date: 2023-12-07T07:46:55

Headers:

Transfer-Encoding             : chunked

Vary                          : Accept-Encoding

Strict-Transport-Security     : max-age=31536000

request-id                    : b7e8a86e-14c4-4c5e-b6ab-98d6d3436d1f

client-request-id             : f93e9309-35d2-4f5b-9172-51c77f1fb945

x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"xxxxxxxxxx","Slice":"x","Ring":"x","ScaleUnit":"xxx","RoleInstance":"xxxxxxxxxxxxxxxxx"}}

Date                          : Thu, 07 Dec 2023 07:46:54 GMT

WWW-Authenticate              : Bearer realm="", authorization_uri=https://login.microsoftonline.com/common/oauth2/authorize, client_id="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.23.1206.1\modules\M365DSCUtil.psm1:1517 char:13

+             $tenantDetails = Get-MgBetaOrganization -ErrorAction 'Sto ...

+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidOperation: ({ Top = , Skip ...ndProperty =  }:<>f__AnonymousType34`8) [Get-MgBetaOrganization_List], Exception

    + FullyQualifiedErrorId : InvalidAuthenticationToken,Microsoft.Graph.Beta.PowerShell.Cmdlets.GetMgBetaOrganization_List
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.19041.3693
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.19041.3693
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by andikrueger** [comment]
This version contains an update of MSCloudLoginAssistant to V 1.1.2 which corrects the App Secret handling in MSCloudLoginAssistant: https://github.com/microsoft/MSCloudLoginAssistant/commit/0cb9683b51508130f626532183ab2d3a7d66fda1

Something is not right obviously.

**Comment by andikrueger** [comment]
The fix will be part of the next release of M365DSC and MSCloudLoginAssistant 1.1.3

**Comment by it-joe** [comment]
> The fix will be part of the next release of M365DSC and MSCloudLoginAssistant 1.1.3
Hey there! Thanks for addressing this. It's a bit of a roadblock for me (breaks my DevOps pipelines). Any idea when the new release will be published? Also, any workaround in the meantime? Thanks! 🚀

**Comment by it-joe** [comment]
@andikrueger, @NikCharlebois - Kindly reopen this issue or should I create a new one? It's still reproducible on all my devices after updating to the latest released modules:
`Name              : MSCloudLoginAssistant
Path              : C:\Program Files\PowerShell\Modules\MSCloudLoginAssistant\1.1.3\MSCloudLoginAssistant.psm1
Description       : Checks the current status of connections to (and as required, prompts for login to) various
                    Microsoft Cloud platforms.
ModuleType        : Script
Version           : 1.1.3

Name              : Microsoft365DSC
Path              : C:\Users\Master\Documents\PowerShell\Modules\Microsoft365DSC\1.23.1213.1\Microsoft365DSC.psd1
Description       : This DSC module is used to configure and monitor Microsoft tenants, including SharePoint Online,
                    Exchange, Teams, etc.
ModuleType        : Manifest
Version           : 1.23.1213.1
`

@horgasz2023 - Did you have more luck 🙂?

**Comment by ricmestre** [comment]
@it-joe @horgasz2023 Yep it seems it's still not solved, the module tries to convert the token to securestring twice, I'll raise a PR for this.

**Comment by ricmestre** [comment]
@NikCharlebois @andikrueger I've raised PR https://github.com/microsoft/MSCloudLoginAssistant/pull/169 to fix this, I've just tested it and it works.

```powershell
PS C:\> Connect-M365Tenant -Workload MicrosoftGraph -ApplicationId $ApplicationId -ApplicationSecret $ApplicationSecret -TenantId $TenantId
PS C:\temp\dsc> Get-MgBetaDeviceManagement

Id               AccountMoveCompletionDateTime DeviceComplianceReportSummarizationDateTime IntuneAccountId                      LastReportAggregationDateTime LegacyPcManangementEnabled MaximumDepTokens Subscrip
                                                                                                                                                                                                          tionStat
                                                                                                                                                                                                          e
--               ----------------------------- ------------------------------------------- ---------------                      ----------------------------- -------------------------- ---------------- --------
deviceManagement                               1/1/0001 12:00:00 AM                        REDACTED 1/1/0001 12:00:00 AM          False                      100
```

**Comment by horgasz2023** [comment]
Get-MgBetaOrganization : CompactToken parsing failed with error code: 80049217
Status: 401 (Unauthorized)
ErrorCode: InvalidAuthenticationToken
Date: 2023-12-15T11:53:26

**Comment by JordyHerber** [comment]
Hi Guys,

Same issue here. already updated module and dependencies. No other module version is present. When I try:

PS C:\Users\rubiadmin> Connect-M365Tenant -Workload MicrosoftGraph -ApplicationId $appIDCustomer -ApplicationSecret $appSecretCustomer -TenantId $tenantNameCustomer

PS C:\Users\rubiadmin> Get-MgBetaDeviceManagement
Get-MgBetaDeviceManagement : Could not load file or assembly 'Microsoft.Graph.Authentication, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ Get-MgBetaDeviceManagement
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgBetaDeviceManagement_Get], FileNotFoundException
    + FullyQualifiedErrorId : Microsoft.Graph.Beta.PowerShell.Cmdlets.GetMgBetaDeviceManagement_Get
 

Any ideas?
