### ISSUE TITLE
New-M365DSCDeltaReport error showing multiple AADRoleSetting - Displayname =

### ISSUE THREAD

**Issue by RotemDror** [microsoft/Microsoft365DSC#4019]
### Description of the issue

When running New-M365DSCDeltaRepor , even between identical exports, the report contains multiple "AADRoleSetting - Displayname =" 

Claiming they are missing 

Major  Minor  Build  Revision
-----  -----  -----  --------
1      23     1206   1

### Microsoft 365 DSC Version

V1.23.1206.1

### Which workloads are affected

Azure Active Directory

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US}


Name                           Value
----                           -----
PSVersion                      5.1.22621.2428
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2428
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by andikrueger** [comment]
Could you share a bit of the configurations used and how you ranNew-M365DSCDeltaReport? Thanks!

**Comment by FabienTschanz** [comment]
I'm unable to reproduce the issue with the latest version `1.24.117.1` with the following configuration:
```
Node localhost
    {
        AADRoleSetting "Test_1" {
            Displayname = "ABC"
            ActivationMaxDuration = 10
            ActivationReqJustification = $true
            ActivationReqMFA = $true
        }
    }
```

**Comment by ShawnBeckers** [comment]
> Could you share a bit of the configurations used and how you ranNew-M365DSCDeltaReport? Thanks!

I'm seeing this issue as well with v1.24.207.2.  Below are commands used to generate export and generate delta report.

$Resources = @("AADAdministrativeUnit","AADApplication","AADAuthorizationPolicy","AADGroupLifecyclePolicy","AADGroupsNamingPolicy","AADGroupsSettings","AADNamedLocationPolicy","AADRoleDefinition","AADRoleSetting","AADSecurityDefaults","AADServicePrincipal","AADTenantDetails","AADTokenLifetimePolicy")

Export-M365DSCConfiguration -TenantID $TenantID -ApplicationID $ApplicationID -CertificateThumbprint $CertThumbprint -Components $Resources -Path $Path -FileName $ExportFile

New-M365DSCDeltaReport -Source "$Path\$PreviousExportFile" -Destination "$Path\$ExportFile" -OutputPath "$Path\$ReportFile"

**Comment by FabienTschanz** [comment]
@ShawnBeckers can you provide us with a source and destination file that leads to the delta? Some sample data should be enough, because we don't know which configuration you set. Thanks!

**Comment by ShawnBeckers** [comment]
Here's some sample data I used to reproduce the issue.  Would be the same for both source and destination.
[sample.txt](https://github.com/microsoft/Microsoft365DSC/files/14271898/sample.txt)

**Comment by FabienTschanz** [comment]
@ShawnBeckers I think I found the underlying issue. In the configuration you provided to us, can you replace `DisplayName` with `Displayname` (lowercase "n") and retry the comparison?

@andikrueger It seems like `AADRoleSettings` defines the `DisplayName` property differently in the MOF and the PowerShell export.
