### ISSUE TITLE
M365DSCDRGUtil: BaseUrl is empty since MSCloudLoginAssistant removed Intune workload

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#4057]
### Description of the issue

The cmdlets mentioned at the bottom need to query Graph and to construct the endpoint URI they rely on getting the BaseUrl from MSCloudLoginAssistant, nevertheless it tries to get that URL from the Intune workload which doesn't exist in that module anymore since a couple of releases.

To fix this it needs to be changed to take the URL from the MicrosoftGraph object instead.

*New-IntuneSettingCatalogPolicy*
*Update-IntuneSettingCatalogPolicy*
*Update-DeviceConfigurationPolicyAssignment*

### Microsoft 365 DSC Version

1.23.1213.1

### Which workloads are affected

other

### The DSC configuration

```powershell
N/A
```

### Verbose logs showing the problem

```powershell
N/A
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, pt-PT}

Name                           Value
----                           -----
PSVersion                      5.1.22621.2428
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2428
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by William-Francillette** [comment]
This was introduced here but not sure of the context:
https://github.com/microsoft/Microsoft365DSC/commit/79774d2a62ca789062ca93cf366fc62822dd442e

**Comment by ricmestre** [comment]
Other clouds such as AzureUSGovernment or AzureDOD don't use https://graph.microsoft.com, instead they have https://graph.microsoft.us and https://dod-graph.microsoft.us so by hardcoding the BaseUrl to https://graph.microsoft.com your cmdlets wouldn't work on those clouds.

**Comment by William-Francillette** [comment]
Did a quick search in vscode and could find 82 occurence of graph.microsoft.com 

Would be good to use the MSCloudLoginAssistant variable everywhere

**Comment by ricmestre** [comment]
Maybe we actually shouldn't rely on any var at all, e.g. doing the below works just fine and that's why your cmdlets still work with the var being null. I'll update this PR.

```powershell
Invoke-GraphRequest -Uri "/beta/deviceAppManagement/mdmWindowsInformationProtectionPolicies"
```
