### ISSUE TITLE
eDiscovery premium: Teams chat messages are not removed 

### ISSUE THREAD

**Issue by 365ad** [microsoft/Microsoft365DSC#4060]
### Description of the issue

I followed this documentation https://learn.microsoft.com/en-us/purview/ediscovery-search-and-delete-teams-chat-messages  to remove teams chat messages by finding using eDiscovery premium
after executing  purge api successful , i still see the teams messages. is there any possible reasons for this ?  , since i can create eDiscovery case  ,collection and search i believe , i have correct License. also my  retention policies are disabled 

### Microsoft 365 DSC Version

1.23.1206.1

### Which workloads are affected

Security & Compliance Center, Teams

**Comment by sagarm365** [comment]
Maybe ediscovery premium will take to implement sometime ?
