### ISSUE TITLE
EXOMalwareFilterPolicy: missing values in validateset?

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Microsoft365DSC#412]
#### Details of the scenario you tried and the problem that is occurring
We've received `DeleteAttachmentAndUseDefaultAlertText` as a value for `EXOMalwareFilterPolicy.Action`. This is not in the list of supported values and of course it causes problems when generating the mof file.
It is also not listed at:
https://docs.microsoft.com/en-us/powershell/module/exchange/antispam-antimalware/new-malwarefilterpolicy?view=exchange-ps#parameters

but i did find the value mentioned around the web:
Ie. https://docs.microsoft.com/en-us/previous-versions/office/exchange-server-api/dn186302(v=exchg.150) and on various blogs.

#### Suggested solution to the issue
Determine the correct set of possible values.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
This has been fixed and is now converting DeleteAttachmentAndUseDefaultAlertText  into DeleteAttachmentAndUseDefaultAlert
