### ISSUE TITLE
Pipeline Execution - stops on "ConfigureLCM.ps1" script

### ISSUE THREAD

**Issue by rameshkothamasu** [microsoft/Microsoft365DSC#4135]
### Description of the issue

Planning to upgrade the env with PowerShell 7.2 or higher with DSC 2.0. During the pipeline execution on Azure DevOps, it stops at "ConfigureLCM.Ps1" file. Error is: 
Import-DSC-Resource -ModuleName PSDesiredStateConfiguration 
Regular DSC Resource Import-DSCResource is not allowed in the meta configuration, 
PowerShell exited with Code '1'

Any suggestions, appreciated.

### Microsoft 365 DSC Version

DSC 2.0 PowerShell 7.2 & higher

### Which workloads are affected

Office 365 Admin

### The DSC configuration

```powershell
DSC 2.0 PowerShell 7.2 & higher
```

### Verbose logs showing the problem

```powershell
Import-DSC-Resource -ModuleName PSDesiredStateConfiguration 
Regular DSC Resource Import-DSCResource is not allowed in the meta configuration, 
PowerShell exited with Code '1'
```
![image](https://github.com/microsoft/Microsoft365DSC/assets/115606141/b17bb88b-05dc-4c0c-bdef-dd4e2dccdc0f)

### Environment Information + PowerShell Version

```powershell
PowerShell 7.2 or higher
```

**Comment by NikCharlebois** [comment]
On the machine you are trying to execute the ConfigureLCM.ps1 file, can you run the following and share the output:

``` PowerShell
Get-Module PSDesiredStateConfiguration -ListAvailable
```

Thanks

**Comment by NikCharlebois** [comment]
Also, it's probably fine for you to just remove that line since PSDesiredStateModule should be loaded by default.

**Comment by rameshkothamasu** [comment]
![image](https://github.com/microsoft/Microsoft365DSC/assets/115606141/7a500af6-fbb3-4b78-9805-a10306af64fd)

**Comment by rameshkothamasu** [comment]
will be with you shortly by compiling again.

**Comment by NikCharlebois** [comment]
Closing as this was solved offline. The Import-DSCResource line can be safely removed from the file.
