### ISSUE TITLE
DisplayName of TeamsTeam should not be mandatory

### ISSUE THREAD

**Issue by pkernevez** [microsoft/Microsoft365DSC#4168]
### Description of the issue

Export is failing because one of the resource doesn't have a display name.
The display name is not mandatory in the M635 API and it's not mandatory in 365DSC because it's only a fallback ID if groupId is not specifiied.

For the set-team documentation:
```
-DisplayName

Team display name. Team Name Characters Limit - 256.
Type:	String
Position:	Named
Default value:	None
Required:	False
Accept pipeline input:	False
Accept wildcard characters:	False
```

### Microsoft 365 DSC Version

V 1.24.101.1

### Which workloads are affected

Teams

### Verbose logs showing the problem

```powershell
{InvalidData}
System.Management.Automation.ParameterBindingValidationException: Cannot validate argument on parameter 'DisplayName'. The character length (0) of the argument is too short. Specify an argument with a length that is greater than or equal to "1", and then try the command again.
 ---> System.Management.Automation.ValidationMetadataException: The character length (0) of the argument is too short. Specify an argument with a length that is greater than or equal to "1", and then try the command again.
   at System.Management.Automation.ValidateLengthAttribute.ValidateElement(Object element)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Error during Export:"
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\DSCResources\MSFT_TeamsTeam\MSFT_TeamsTeam.psm1: line 705
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\modules\M365DSCReverse.psm1: line 639
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\modules\M365DSCUtil.psm1: line 1312
at export_and_compile_serial, C:\ProgramData\Dsc\git\mpc_dsc_m365\export.ps1: line 78
at <ScriptBlock>, C:\ProgramData\Dsc\git\mpc_dsc_m365\export.ps1: line 208
at <ScriptBlock>, C:\ProgramData\UniversalAutomation\Repository\scripts\mpc_dsc_export.ps1: line 82
at <ScriptBlock>, <No file>: line 1
```

**Comment by malauter** [comment]
We need the display name for the creation of a new team. During the creation process, the display name is mandatory, we cannot use the group id here.

**Comment by pkernevez** [comment]
Why is it mandatory for the calls meaning for the get) ?
How can we export those resources ?

**Comment by pkernevez** [comment]
Is it possible to:
1. remove the mandatory aspect only for the set ?
or 
2. Remove it for all of them and check if it is non null in the Set-TargetResource code ?

**Comment by malauter** [comment]
We have to make sure that a exported config can be imported into a tenant again. During the import we a need a display name. What should we set as display name if this attribute is null in the export?
How did you create the Teams without a display name? Even for the native New-Team cmdlet the display name is required (https://learn.microsoft.com/en-us/powershell/module/teams/new-team?view=teams-ps).

**Comment by pkernevez** [comment]
I have to do more investigation because when calling Get-Team API directly, all resources have a DisplayName.
It may be related to encoding as several of our resources have Asian chars.

**Comment by malauter** [comment]
If you run Get-Team manually it is returning the display name but it is not in M365 DSC? Can you share one of the affected display names, so I can try to reproduce?

**Comment by pkernevez** [comment]
>If you run Get-Team manually it is returning the display name but it is not in M365 DSC? 
Yes

>Can you share one of the affected display names, so I can try to reproduce?
I'm not able to reproduce it today, so I'm going to close this issue.

I'll reopen it later if I'm able to have it again with data to reproduce it

Regards
