### ISSUE TITLE
Error during export of IntuneDeviceConfigurationCustomPolicyWindows10

### ISSUE THREAD

**Issue by heizkoerperchen** [microsoft/Microsoft365DSC#4174]
### Description of the issue

When trying the export the Intune configuration I get the following error on a specific configuration item:

_{NotSpecified}
System.Management.Automation.MethodInvocationException: Exception calling "IndexOf" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex" ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   at CallSite.Target(Closure , CallSite , String , String , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction``2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
"Error during Export:"
at Convert-DSCStringParamToVariable, C:\Program Files\WindowsPowerShell\Modules\ReverseDSC\2.0.0.18\ReverseDSC.Core.psm1: line 766
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\DSCResources\MSFT_IntuneDeviceConfigurationCustomPolicyWindows10\MSFT_IntuneDeviceConfigurationCustomPolicyWindows10.psm1: line 626
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\modules\M365DSCReverse.psm1: line 639
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.110.1\modules\M365DSCUtil.psm1: line 1312
at <ScriptBlock>, C:\Temp\Export_Intune.ps1: line 11_

A JSON representation of the configuration item looks like this:
```json
{
    "Assignments":  null,
    "CreatedDateTime":  "\/Date(1683556365370)\/",
    "Description":  null,
    "DeviceManagementApplicabilityRuleDeviceMode":  {
                                                        "DeviceMode":  null,
                                                        "Name":  null,
                                                        "RuleType":  null
                                                    },
    "DeviceManagementApplicabilityRuleOSEdition":  {
                                                       "Name":  null,
                                                       "OSEditionTypes":  null,
                                                       "RuleType":  null
                                                   },
    "DeviceManagementApplicabilityRuleOSVersion":  {
                                                       "MaxOSVersion":  null,
                                                       "MinOSVersion":  null,
                                                       "Name":  null,
                                                       "RuleType":  null
                                                   },
    "DeviceSettingStateSummaries":  null,
    "DeviceStatusOverview":  {
                                 "ConfigurationVersion":  null,
                                 "ConflictCount":  null,
                                 "ErrorCount":  null,
                                 "FailedCount":  null,
                                 "Id":  null,
                                 "LastUpdateDateTime":  null,
                                 "NotApplicableCount":  null,
                                 "NotApplicablePlatformCount":  null,
                                 "PendingCount":  null,
                                 "SuccessCount":  null
                             },
    "DeviceStatuses":  null,
    "DisplayName":  "ConfigurationProfile-WIN-SurfaceHub-LocalAdmin",
    "GroupAssignments":  null,
    "Id":  "9f07f68c-2ce8-406f-9daf-df2a31d5efdb",
    "LastModifiedDateTime":  "\/Date(1704796857251)\/",
    "RoleScopeTagIds":  [
                            "33"
                        ],
    "SupportsScopeTags":  true,
    "UserStatusOverview":  {
                               "ConfigurationVersion":  null,
                               "ConflictCount":  null,
                               "ErrorCount":  null,
                               "FailedCount":  null,
                               "Id":  null,
                               "LastUpdateDateTime":  null,
                               "NotApplicableCount":  null,
                               "PendingCount":  null,
                               "SuccessCount":  null
                           },
    "UserStatuses":  null,
    "Version":  3,
    "AdditionalProperties":  {
                                 "@odata.type":  "#microsoft.graph.windows10CustomConfiguration",
                                 "omaSettings":  [
                                                     {
                                                         "@odata.type":  "#microsoft.graph.omaSettingStringXml",
                                                         "displayName":  "SetLocalAdmins",
                                                         "description":  "Set Local Admins",
                                                         "omaUri":  "./Device/Vendor/MSFT/Policy/Config/LocalUsersAndGroups/Configure",
                                                         "secretReferenceValueId":  "74904dfe-e34e-4280-b67b-4b2b681b226c_9f07f68c-2ce8-406f-9daf-df2a31d5efdb_37bebd25-493b-431f-9f28-f8a1c91d84a8",
                                                         "isEncrypted":  true,
                                                         "fileName":  "admins.xml",
                                                         "value":  "PGEvPg=="
                                                     }
                                                 ]
                             }
}
```
Other items can be exported successfully, but I have 16 items to export and only 5 are exported, because of the occuring error.

### Microsoft 365 DSC Version

V1.24.110.1

### Which workloads are affected

other

**Comment by ricmestre** [comment]
@William-Francillette I'm able to replicate this issue, do you have time to look into it?

Take the example below, I created this policy in the portal then wrote the $DSCBlock in the CLI, in Convert-DSCStringParamToVariable from ReverseDSC module, in loop and it seems it doesn't like all those extra quotes in the *Value* property. In my case the loop starts eating characters from the word *Administrator* on *member name = Administrator* line until it's only *<member name = "/>* which then finally turns the index into -1 which of course will trip when calling *IndexOf* on that string.

```powershell
IntuneDeviceConfigurationCustomPolicyWindows10 "IntuneDeviceConfigurationCustomPolicyWindows10-test"
{
	Assignments          = @();
	Credential           = $Credscredential;
	DisplayName          = "test";
	Ensure               = "Present";
	Id                   = "d0b91521-487b-4cd5-9451-ce842bb9ae41";
	OmaSettings          = @("
		MSFT_MicrosoftGraphomaSetting{
			Description = 'test'
			FileName = 'groupmembership.xml'
			OmaUri = './Device/Vendor/MSFT/Policy/Config/RestrictedGroups/ConfigureGroupMembership'
			Value = '<groupmembership>
				<accessgroup desc = "Administrators">
				<member name = "Administrator"/>
				<member name = "S-1-5-21-1350187067-2828864506-2329879917-501"/>
				</accessgroup>
				</groupmembership>'
			odataType = '#microsoft.graph.omaSettingStringXml'
			IsEncrypted = $False
			DisplayName = 'test'
		}
	");
	SupportsScopeTags    = $True;
}
```

**Comment by William-Francillette** [comment]
Will have a look in the evening

**Comment by William-Francillette** [comment]
1. I agree with @ricmestre, there is an issue with Convert-DSCStringParamToVariable from truncating the nested cim parameter

This :
```
IntuneDeviceConfigurationCustomPolicyWindows10 "IntuneDeviceConfigurationCustomPolicyWindows10-custom"
        {
            ApplicationId         = $ConfigurationData.NonNodeData.ApplicationId;
            Assignments           = @(@{deviceAndAppManagementAssignmentFilterType='none'; dataType='#microsoft.graph.allDevicesAssignmentTarget'; deviceAndAppManagementAssignmentFilterId=$null; groupId=$null});
            CertificateThumbprint = $ConfigurationData.NonNodeData.CertificateThumbprint;
            DisplayName           = "custom";
            Ensure                = "Present";
            Id                    = "e072d616-12bc-4ea3-9171-ab080e4c120d";
            OmaSettings           = @("
                MSFT_MicrosoftGraphomaSetting{
                    Description = 'custom'
                    OmaUri = '/oma/custom3'
                    Value = 'test value'
                    odataType = '#microsoft.graph.omaSettingString'
                    IsEncrypted = $False
                    DisplayName = 'oma'
                }
            ","
                MSFT_MicrosoftGraphomaSetting{
                    Description = 'custom 2'
                    OmaUri = '/oma/custom2'
                    Value = 2
                    IsReadOnly = $False
                    odataType = '#microsoft.graph.omaSettingInteger'
                    IsEncrypted = $False
                    DisplayName = 'custom 2'
                }
            ","
                MSFT_MicrosoftGraphomaSetting{
                    Description = 'Set Local Admins'
                    FileName = 'GroupConfiguration.xml'
                    OmaUri = './Device/Vendor/MSFT/Policy/Config/LocalUsersAndGroups/Configure'
                    Value = '<GroupConfiguration>
    <accessgroup desc = "S-1-5-21-2222222222-3333333333-4444444444-500">
        <group action = "U" />
        <add member = "AzureAD\bob@contoso.com"/>
        <add member = "S-1-12-1-111111111-22222222222-3333333333-4444444444"/>
    </accessgroup>
</GroupConfiguration>'
                    odataType = '#microsoft.graph.omaSettingStringXml'
                    IsEncrypted = $False
                    DisplayName = 'SetLocalAdmins'
                }
            ");
            SupportsScopeTags     = $True;
            TenantId              = $OrganizationName;
        }
```
Became  after Convert-DSCStringParamToVariable - We can see an issue with the last oma where diplayname was truncated and a parsing error occured

```
        IntuneDeviceConfigurationCustomPolicyWindows10 "IntuneDeviceConfigurationCustomPolicyWindows10-custom"
        {
            ApplicationId         = $ConfigurationData.NonNodeData.ApplicationId;
            Assignments           = @(@{deviceAndAppManagementAssignmentFilterType='none'; dataType='#microsoft.graph.allDevicesAssignmentTarget'; deviceAndAppManagementAssignmentFilterId=$null; groupId=$null});
            CertificateThumbprint = $ConfigurationData.NonNodeData.CertificateThumbprint;
            DisplayName           = "custom";
            Ensure                = "Present";
            Id                    = "e072d616-12bc-4ea3-9171-ab080e4c120d";
            OmaSettings           = @(
                MSFT_MicrosoftGraphomaSetting{
                    Description = 'custom'
                    OmaUri = '/oma/custom3'
                    Value = 'test value'
                    odataType = '#microsoft.graph.omaSettingString'
                    IsEncrypted = $False
                    DisplayName = 'oma'
                }
                MSFT_MicrosoftGraphomaSetting{
                    Description = 'custom 2'
                    OmaUri = '/oma/custom2'
                    Value = 2
                    IsReadOnly = $False
                    odataType = '#microsoft.graph.omaSettingInteger'
                    IsEncrypted = $False
                    DisplayName = 'custom 2'
                }
                MSFT_MicrosoftGraphomaSetting{
                    Description = 'Set Local Admins'
                    FileName = 'GroupConfiguration.xml'
                    OmaUri = './Device/Vendor/MSFT/Policy/Config/LocalUsersAndGroups/Configure'
                    Value = '<GroupConfiguration>
    <accessgroup desc = "S-1-5-21-2222222222-3333333333-4444444444-500">
        <group action = " />
        <add member = "AzureAD\bob@contoso.com"/>
        <add member = "/>
    </accessgroup>
</GroupConfiguration>'
                    odataType = '#microsoft.graph.omaSettingStringXml'
                    IsEncrypted = $False
                    DisplayName = ");
            SupportsScopeTags     = $True;
            TenantId              = $OrganizationName;
        }
```

We would need Convert-DSCStringParamToVariable to be fixed 


2. The other issue will be in the Set-TargetResource the omaSettingStringXml type should be converted to base64 when using a Create or Update 

3. Lastly @ricmestre why do we change isEncrypted from true to false in Get-TargetResource? We potentially could use this variable to encrypt the value to base64 during an update or create

**Comment by ricmestre** [comment]
@William-francillette I added a function to decrypt the value inside, if encrypted, otherwise you can't apply that policy to other tenant. Without that function I cannot use that resource for our customers since they expect everything to be multi-tenant aware.

**Comment by William-Francillette** [comment]
Yeah seen the function and it's brilliant but I was talking about Get-TargetResource, when you decrypte the parameter you also change the parameter isEncrypted to false. Is that required?

**Comment by ricmestre** [comment]
I'm not in front of my machine but Im almost sure that I tried it but then it expects the secret reference property to be declared as well and it goes off the rails. Again, not 100% sure and can't test it right now

**Comment by ricmestre** [comment]
Oh right I actually raised that problem since I initially left it set to true but then it failed to apply to other tenant, can't remember how exactly it failed but it didn't work. #4083

**Comment by smithr1989** [comment]
I'm having the same issuie with a Security & Compliance component:

`
Export-M365DSCConfiguration -Components @("SCDLPComplianceRule") -Credential $Credentials -Path "$Path" -FileName "SCDLPComplianceRule.ps1"
`

My "Error during Export" is slightly different due to a different component being used:

```
"Error during Export:"
--at Get-M365DSCExportContentForResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.117.1\modules\M365DSCUtil.psm1: line 3291
-at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.117.1\DSCResources\MSFT_SCDLPComplianceRule\MSFT_SCDLPComplianceRule.psm1: line 999
--at <ScriptBlock>, <No file>: line 1
$user@$tenant_ID
TenantId: $tenant_ID
```

-Changed because of the component being different.
--All new lines that are still likely due to a different component.

While it's running it shows success on 51/76 rules, and fails on the 52nd rule which leaves the exported file empty. The SCDLPCompliancePolicy component is ran prior to this and runs just fine.

**Comment by ricmestre** [comment]
@william-francillette Do you have any updates on this?

**Comment by schmarrap** [comment]
> I'm having the same issuie with a Security & Compliance component:
> 
> `Export-M365DSCConfiguration -Components @("SCDLPComplianceRule") -Credential $Credentials -Path "$Path" -FileName "SCDLPComplianceRule.ps1"`
> 
> My "Error during Export" is slightly different due to a different component being used:
> 
> ```
> "Error during Export:"
> --at Get-M365DSCExportContentForResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.117.1\modules\M365DSCUtil.psm1: line 3291
> -at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.117.1\DSCResources\MSFT_SCDLPComplianceRule\MSFT_SCDLPComplianceRule.psm1: line 999
> --at <ScriptBlock>, <No file>: line 1
> $user@$tenant_ID
> TenantId: $tenant_ID
> ```
> 
> -Changed because of the component being different. --All new lines that are still likely due to a different component.
> 
> While it's running it shows success on 51/76 rules, and fails on the 52nd rule which leaves the exported file empty. The SCDLPCompliancePolicy component is ran prior to this and runs just fine.

I also have the same issue with "SCAutoSensitivityLabelRule" mine gets to 22 of 62 but doesn't export anything

**Comment by schmarrap** [comment]
> > I'm having the same issuie with a Security & Compliance component:
> > `Export-M365DSCConfiguration -Components @("SCDLPComplianceRule") -Credential $Credentials -Path "$Path" -FileName "SCDLPComplianceRule.ps1"`
> > My "Error during Export" is slightly different due to a different component being used:
> > ```
> > "Error during Export:"
> > --at Get-M365DSCExportContentForResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.117.1\modules\M365DSCUtil.psm1: line 3291
> > -at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.117.1\DSCResources\MSFT_SCDLPComplianceRule\MSFT_SCDLPComplianceRule.psm1: line 999
> > --at <ScriptBlock>, <No file>: line 1
> > $user@$tenant_ID
> > TenantId: $tenant_ID
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > -Changed because of the component being different. --All new lines that are still likely due to a different component.
> > While it's running it shows success on 51/76 rules, and fails on the 52nd rule which leaves the exported file empty. The SCDLPCompliancePolicy component is ran prior to this and runs just fine.
> 
> I also have the same issue with "SCAutoSensitivityLabelRule" mine gets to 22 of 62 but doesn't export anything

{NotSpecified}
System.Management.Automation.MethodInvocationException: Exception calling "IndexOf" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex" ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.IndexOf(String value, Int32 startIndex, Int32 count, StringComparison comparisonType)
   at CallSite.Target(Closure , CallSite , String , String , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Convert-DSCStringParamToVariable(Closure , FunctionContext )
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
"Error during Export:"
at Convert-DSCStringParamToVariable, C:\Program Files\WindowsPowerShell\Modules\ReverseDSC\2.0.0.18\ReverseDSC.Core.psm1: line 766
at Get-M365DSCExportContentForResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.124.1\modules\M365DSCUtil.psm1: line 3291
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.124.1\DSCResources\MSFT_SCAutoSensitivityLabelRule\MSFT_SCAutoSensitivityLabelRule.psm1: line 1191
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.124.1\modules\M365DSCReverse.psm1: line 639
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.124.1\modules\M365DSCUtil.psm1: line 1312
at <ScriptBlock>, <No file>: line 1

**Comment by schmarrap** [comment]
@schmarrap fyi

**Comment by heizkoerperchen** [comment]
@ricmestre @William-Francillette Any news on this issue? We are stuck at the moment in the onboarding process for our Intune team because of this :(

**Comment by ricmestre** [comment]
While this is not fixed you can always exclude the resource from being exported, just use the Components parameter instead of the whole Intune workload.

```powershell
$Components = Get-M365DSCAllResources | ?{ $_ -like "Intune*" -and $_ -ne "IntuneDeviceConfigurationCustomPolicyWindows10" }
Export-M365DSCConfiguration -Components $Components ...
```

**Comment by heizkoerperchen** [comment]
Yes, but the thing is that there are more than 20 "IntuneDeviceConfigurationCustomPolicyWindows10" items and the export is failing on item number 5. Our aim is to synchronize the configuration over 3 tenants, but it's not possible with so many missing items that can't be compared. Maybe it would make sense to do some error handling during export instead of stopping the whole process if only one item causes an error.

**Comment by ricmestre** [comment]
@andikrueger What can we do here? This also impacts me, maybe a quick patch to silently continue to the next policy if *Convert-DSCStringParamToVariable* fails converting the OmaSettings? At least while this is not properly fixed?

**Comment by William-Francillette** [comment]
Apologies, I have been quite busy lately and did not have time to look at the issue - I'll focus on it next week and see if I can fix the issue with Convert-DSCStringParamToVariable

**Comment by sachabruttin** [comment]
Same issue here, but for the `IntuneSettingCatalogCustomPolicyWindows10` resource.
All policies with an XML string are failing when calling `Convert-DSCStringParamToVariable` method.

This is an example of a setting that is failing for me:

```
"
	MSFT_MicrosoftGraphdeviceManagementConfigurationSetting{

		SettingInstance = MSFT_MicrosoftGraphDeviceManagementConfigurationSettingInstance{
			odataType = '#microsoft.graph.deviceManagementConfigurationSimpleSettingInstance'
			SettingDefinitionId = 'device_vendor_msft_passportforwork_deviceunlock_plugins'

			simpleSettingValue = MSFT_MicrosoftGraphDeviceManagementConfigurationSimpleSettingValue{
				StringValue = '<rule schemaVersion="1.0"> <signal type="bluetooth" scenario="Authentication" classOfDevice="512" rssiMin="-10" rssiMaxDelta="-10"/> </rule>'
				odataType = '#microsoft.graph.deviceManagementConfigurationStringSettingValue'
			}

		}

	}
"
```
