### ISSUE TITLE
Is it possible to reference id's of other resources?

### ISSUE THREAD

**Issue by bartvermeersch** [microsoft/Microsoft365DSC#4190]
I'm sorry if this already answered somewhere, I could find it.

We have Administrative Units referencing groups by their ID in the MembershipRule:

```
    AADAdministrativeUnit "AADAdministrativeUnit-Test"
    {
        Description                   = "Dynamic AU containing accounts in Test group"
        DisplayName                   = "Test"
        MembershipRule    = "user.memberof -any (group.objectId -in ['**MyGroupID**'])"
        DependsOn            = "[AADGroup]MyGroup"
        MembershipRuleProcessingState = "On"
        MembershipType                = "Dynamic"
        TenantId                      = $TenantId
        ApplicationId                 = $ApplicationId
        CertificateThumbprint         = $Thumbprint
        Ensure                        = "Present"
    }
```

Is there a way to dynamically retrieve the ID of the Group without hardcoding it (since we are targetting multiple tenants)? I assume the DSC engine won't resolve group names to ID's in these MembershipRule queries?

**Comment by andikrueger** [comment]
I would use a configuration datafile that is specific to the target environment. You can reference the id within the datafile.
