### ISSUE TITLE
TeamsCallQueue is only exporting the first 100 CallQueue

### ISSUE THREAD

**Issue by pkernevez** [microsoft/Microsoft365DSC#4191]
### Description of the issue

The Teams API that is used ( Get-CsCallQueue ) only return the first 100 instances by default.

### Microsoft 365 DSC Version

V 1.24.101.1

### Which workloads are affected

Teams

**Comment by malauter** [comment]
This is a bug in the Get-CsCallQueue cmdlet, not in M365 DSC. See this: https://techcommunity.microsoft.com/t5/microsoft-teams/get-cscallqueue-broken/m-p/1195544

I will try to implement one the workaround mentioned there.

**Comment by pkernevez** [comment]
It's not a bug, it's a feature, by default only 100 are returned.

I have a patch and will push it soon

**Comment by pkernevez** [comment]
Patch pushed
