### ISSUE TITLE
When exporting CsCallQueue (it's also right for a lot of other resources), we are doing n+1 request instaead of 1

### ISSUE THREAD

**Issue by pkernevez** [microsoft/Microsoft365DSC#4192]
### Description of the issue

The export have the following pattern:
1. Create a list of what we wan to export
2. For each of them read the detail of the row
3. export the row

For CsCalQueue (and most of the time for other resources)
part 1, does one request to retrieve the list of n resources
part2, does n request to retrieve the detail

But both part are using same API, meaning that after part1 we already have the data. part 2 is useless.

In my case n=150, it means that the export could speed by ~100 (part1 cost more than other requests ).

### Microsoft 365 DSC Version

1.23.110.1

### Which workloads are affected

Teams

**Comment by Phlphat746** [comment]
ฉันใดก็ลบคลาวเชลล์ออกไปและครับเนื่องจากประสบปัญหาจากระบบคลาวด์คราวหลังฉันจะไม่ลบแอบใดออกไปอีกและครับ
