### ISSUE TITLE
AADUser: Ensure: Absent logic seems wrong

### ISSUE THREAD

**Issue by bartvermeersch** [microsoft/Microsoft365DSC#4265]
AAD Users with **Ensure** set to **Absent** are removed and recreated every next run after removal.

The logic is correct when the resource exists, but if it doesn't it will just create it although Ensure is set to Absent

https://github.com/microsoft/Microsoft365DSC/blob/6c61af48ed9bf0ab11a8743a992e6a0e4e7c3d60/Modules/Microsoft365DSC/DSCResources/MSFT_AADUser/MSFT_AADUser.psm1#L416

A condition `if ($Ensure -eq 'Present') ` is missing on line 421

**Comment by William-Francillette** [comment]
Tested on my tenant and working ok  - Could you check your _event viewer > application and service logs > M365DSC_ if there is any error?

**Comment by andikrueger** [comment]
@William-Francillette If is read the code correctly, this really a bug.

configuration should look like this and there should not be a user with the UPN John.Smith

```powershell

AADUser 'ConfigureJohnSMith'
        {
            UserPrincipalName  = "John.Smith@$Domain"
            DisplayName        = "John J. Smith"
            Ensure             = "Absent"
            Credential         = $Credscredential
        }
}

```

In this case, the Get-Method will return Absent and therefor we will directly jump into the else block. This will result in a new user bein created, even if it should not be created.

Needs to be an 

else if( $Ensure -eq 'Present") 

then.
