### ISSUE TITLE
The following dependencies need updating 

### ISSUE THREAD

**Issue by shenukaf69** [microsoft/Microsoft365DSC#4277]
![image](https://github.com/microsoft/Microsoft365DSC/assets/45993226/6257b892-9235-4bef-81aa-15a644d0edf1)

I am getting the above error even i have tried updating M365DSCDependencies over Uninstall-M365DSCOutdatedDependencies 

below are the updated modules which are up to date , stuck in here atm without knowing what to do 

PS C:\Users\p0107821> Update-M365DSCDependencies -Scope AllUsers
Installing Microsoft.Graph.Applications version {2.12.0}
Installing Microsoft.Graph.Beta.DeviceManagement version {2.12.0}
Installing Microsoft.Graph.Beta.Devices.CorporateManagement version {2.12.0}
Installing Microsoft.Graph.Beta.DeviceManagement.Administration version {2.12.0}
Installing Microsoft.Graph.Beta.DeviceManagement.Enrollment version {2.12.0}
Installing Microsoft.Graph.Beta.Identity.DirectoryManagement version {2.12.0}
Installing Microsoft.Graph.Beta.Identity.Governance version {2.12.0}
Installing Microsoft.Graph.Beta.Identity.SignIns version {2.12.0}
Installing Microsoft.Graph.Beta.Reports version {2.12.0}
Installing Microsoft.Graph.Beta.Teams version {2.12.0}
Installing Microsoft.Graph.Beta.DirectoryObjects version {2.12.0}
Installing Microsoft.PowerApps.Administration.PowerShell version {2.0.178}
Installing MicrosoftTeams version {5.9.0}
Installing PnP.PowerShell version {1.12.0}

**Comment by shenukaf69** [comment]
only pending this now 

The following dependencies need updating:
    * PnP.PowerShell
Please run Update-M365DSCDependencies with scope "currentUser" or as Administrator.Please run 
Uninstall-M365DSCOutdatedDependencies.

have tried with latest nightly versions but still it is saying to update

**Comment by shenukaf69** [comment]
managed to install

**Comment by donky-bison** [comment]
How did you solve the problem?
