### ISSUE TITLE
Encrypting MOF file when compiling configuration question.

### ISSUE THREAD

**Issue by bjornMakeItSo** [microsoft/Microsoft365DSC#4282]
Hi,
Is there any point to encrypting the MOF files when access to read/change is given through Entra ID Application Registration with certificate thumbprint?
From what I could tell in the compiled MOF files with and without encryption, both files showed the certificate thumbprint anyway.

kinds regards

Bjørn

**Comment by andikrueger** [comment]
The thumbprint wont be secured in this case. It's still recommended to use encryption if there are any user credentials, secrets used in the future.

Please make sure to secure the certificate and the server. There are various options to limit the access to the certificate, like, marking the private key as not exportable and limiting and monitoring admin access to this server.

**Comment by bjornMakeItSo** [comment]
Thank you andikrueger!
