### ISSUE TITLE
Problem with git

### ISSUE THREAD

**Issue by salbeck-sit** [microsoft/Microsoft365DSC#4287]
This may be OT ? A commit earlier today apparently removed Modules/Microsoft365DSC/Modules/EncodingHelpers/M365DSCStringEncoding.psm1 and a later commit appeared to bring it back. At least according to my local copy. When I try to restore the file (it shows up as an untracked change) the change goes away for a second or two and then returns. Ie the file is still deleted.
I know I could wipe the local copy and pull a fresh copy but I'm working with several changes in several branches and would like a low-touch solution - if one exists. I've tried git restore, clean, checkout, reset and probably a few others. Sometimes the change goes away but it always returns.
Anybody have an idea what might be going on ?

**Comment by andikrueger** [comment]
It looks like there was change made on this file with the latest release of M365DSC https://github.com/microsoft/Microsoft365DSC/commit/107bd8623fcb5194b0ab3ee9b8ad3d985316434b#diff-2dafc4776791472907c5373d3f5f21d3c3d2b0ca0fde8649691829571a74ae3e

Any chance to stash your changes and apply those on a new branch?

**Comment by andikrueger** [comment]
Glad you found the issue.
