### ISSUE TITLE
Get-MGGroup : Unsupported or invalid query filter clause specified for property 'onPremisesSecurityIdentifier' of resource 'Group'.

### ISSUE THREAD

**Issue by ArshEXMSFT** [microsoft/Microsoft365DSC#4318]
I am trying to import on-prem Groups SID via CSV file where SIDs are in row "SID" and get corresponding Cloud Group using Get-MgGrroup command and it is failing with below error. Any help will be appreciated.

Import-Csv "C:\Users\Desktop\NOSMTPSID.csv" | Select-Object -First 1 | foreach {Get-MGGroup -Filter "onPremisesSecurityIdentifier eq '$_.SID'"  }
Get-MGGroup : Unsupported or invalid query filter clause specified for property 'onPremisesSecurityIdentifier' of
resource 'Group'.
Status: 400 (BadRequest)
ErrorCode: Request_UnsupportedQuery
Date: 2024-02-13T20:41:24
Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 08cb412f-9b71-4a56-a673-ade51e1c94b4
client-request-id             : 17195d62-7299-4a42-bfe6-b3a85a6c3acf
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"North Central
US","Slice":"E","Ring":"3","ScaleUnit":"001","RoleInstance":"CH01EPF0002CD96"}}
x-ms-resource-unit            : 1
Cache-Control                 : no-cache
Date                          : Tue, 13 Feb 2024 20:41:24 GMT
At line:1 char:91
+ ...  | foreach {Get-MGGroup -Filter "onPremisesSecurityIdentifier eq '$_. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ ConsistencyLe... , Headers =  }:<>f__AnonymousType89`10) [Get-MgGro
   up_List], Exception
    + FullyQualifiedErrorId : Request_UnsupportedQuery,Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List

**Comment by andikrueger** [comment]
Please raise further questions for this issue within the [Microsoft Graph PowerShell SDK repo](https://github.com/microsoftgraph/msgraph-sdk-powershell). This repository focusses on Microsoft 365 DSC.

As a side note: This error is specific to the Filter you set. You need to specify ConsistencyLevel as eventual and count as true. This should help with the filter clause. See: https://learn.microsoft.com/en-us/graph/aad-advanced-queries?view=graph-rest-1.0&tabs=http

```powershell
Get-MgGroup -Filter "onPremisesSecurityIdentifier eq '$_.SID'" -CountVariable CountVar  -ConsistencyLevel eventual
```
