### ISSUE TITLE
Special character escaping problems

### ISSUE THREAD

**Issue by vinkobedek** [microsoft/Microsoft365DSC#432]
There is a problem on some environments when special unicode quotes are used in the values that are exported(ie. O365Group name).
The generated powershell is invalid because of that.
The quotes in question are unicode characters 0x201C 0x201D 0x201E. These characters are regarded by PowerShell as a double quote, but not always. It depends on the environment.
Cannot say much more because it did not occur on our machines. I think it has to do with the default encoding. 
If we save the file with such values as UTF8 BOM then the problem is reproducible.
I also believe that in some instaces the $ sign can also cause problems because the parser will expect a variable.

**Comment by NikCharlebois** [comment]
Closed with #868

**Comment by NikCharlebois** [comment]
Link #908
