### ISSUE TITLE
Connecting to {PnP}...❌

### ISSUE THREAD

**Issue by shenukaf69** [microsoft/Microsoft365DSC#4336]

**Comment by shenukaf69** [comment]
i can not connect to PnP ,  have updated modules and PS , any idea what is going wrong ?
-----------------------------------------------------------------
PowerShell         Microsoft.PowerShell         7.4.1.0   winget

and PnP version 2.3.0

Authentication methods specified:
- Credentials
 
Connecting to {ExchangeOnline}...✅
Connecting to {MicrosoftGraph}...✅
Connecting to {MicrosoftTeams}...✅
Connecting to {PnP}...❌

**Comment by andikrueger** [comment]
Please review this user guide to better understand the challenges with PS and the newer PnP PowerShell: https://microsoft365dsc.com/user-guide/get-started/powershell7-support/#common-issues-when-the-modules-are-not-in-the-right-folder

**Comment by shenukaf69** [comment]
> Please review this user guide to better understand the challenges with PS and the newer PnP PowerShell: https://microsoft365dsc.com/user-guide/get-started/powershell7-support/#common-issues-when-the-modules-are-not-in-the-right-folder

hi Andi thank you for the reply is this the same for PS 5.1 ?

**Comment by andikrueger** [comment]
For PS 5.1 you need to uninstall the newer PnP PowerShell version and install the one required for M365DSC.

**Comment by shenukaf69** [comment]
got it thank you :)
