### ISSUE TITLE
Priority in Exchange Transport Rule

### ISSUE THREAD

**Issue by jagatjb** [microsoft/Microsoft365DSC#4346]
### Description of the issue

Let's say I have 100 Exchange Transport Rules. I create a new Exchange Transport Rule and make it as priority 2. And at the same time, I am running the configuration comparison delta report on daily basis. In this case, i will be receiving changes for 99 Exchange Transport Rules where the Priority has been increased by 1. These details are not useful as the delta report is already providing me that a new exchange transport rule had been created. 
So, is there any way to remove the priority checks for comparison configuration report for Exchange Transport Rules ?

### Microsoft 365 DSC Version

Release 1.24.131.2

### Which workloads are affected

Exchange Online

### The DSC configuration

```powershell
NA
```

### Verbose logs showing the problem

```powershell
NA
```

### Environment Information + PowerShell Version

```powershell
NA
```

**Comment by andikrueger** [comment]
Your configuration and your settings within the tenant need to match 100%. If you would make this change within the configuration itself, it would be required to change the priority of every resource. If you do not want to monitor this parameter, you could remove the parameter from the configuration at all. Please run a test within another environment to make sure, that the removal of this parameter is handled correctly. If implementation is correct, the parameter should not bother in the test-TargetResource function.

e.g. for testing: remove the param Priority within the configuration and run Test-DSCConfiguration afterwards.

**Comment by jagatjb** [comment]
> Your configuration and your settings within the tenant need to match 100%. If you would make this change within the configuration itself, it would be required to change the priority of every resource. If you do not want to monitor this parameter, you could remove the parameter from the configuration at all. Please run a test within another environment to make sure, that the removal of this parameter is handled correctly. If implementation is correct, the parameter should not bother in the test-TargetResource function.
> 
> e.g. for testing: remove the param Priority within the configuration and run Test-DSCConfiguration afterwards.

Thanks Andi. I will check this. I am closing this request.
