### ISSUE TITLE
AADConditionalAccessPolicy - Issues

### ISSUE THREAD

**Issue by Cyanic-Cloud** [microsoft/Microsoft365DSC#4347]
### Description of the issue

**When using Export-M365DSCConfiguration like below:**

Export-M365DSCConfiguration -Components @("AADConditionalAccessPolicy") -ApplicationId $ApplicationId -CertificateThumbprint $CertificateThumbprint -TenantId $TenantId

**The following objects are not auto populating with required values**

**IncludeExternalTenantsMembershipKind = "";
ExcludeExternalTenantsMembershipKind = "";**

![image](https://github.com/microsoft/Microsoft365DSC/assets/104797528/11fd0848-e13f-4dd5-bc72-10bfb9dfd66c)

**Is it possible to not make this a required variable or auto populate with unknownFutureValue, as currently I now get an error in my pipeline as I dont populate this variable in my base config:**

![image](https://github.com/microsoft/Microsoft365DSC/assets/104797528/2a765d81-1f85-453c-a313-af19230c7fc8)

![image](https://github.com/microsoft/Microsoft365DSC/assets/104797528/de8e2d80-3baf-4206-9f1f-711927de053e)

**If I populate both IncludeExternalTenantsMembershipKind AND ExcludeExternalTenantsMembershipKind with unknownFutureValue the compilation runs fine.**

### Microsoft 365 DSC Version

1.24.214.2

### Which workloads are affected

Azure Active Directory

**Comment by sachabruttin** [comment]
Empty string value has been removed on this PR #4322 / Commit 
https://github.com/microsoft/Microsoft365DSC/commit/32fa1cce2e7202e594d1a03bec8433c1bf9880cf

When I export my Conditional Access with 
```powershell
> $policy = Get-MgBetaIdentityConditionalAccessPolicy -Filter "DisplayName eq '$DisplayName'"
```

The value I get is empty. 
```powershell 
> $policy.Conditions.Users.ExcludeGuestsOrExternalUsers.ExternalTenants

MembershipKind
--------------

> $policy.Conditions.Users.ExcludeGuestsOrExternalUsers.ExternalTenants.MembershipKind -eq $null
True
```

Please allow the properties `IncludeExternalTenantsMembershipKind` and `
ExcludeExternalTenantsMembershipKind` the have empty value/$null value.

**Comment by ricmestre** [comment]
@ykuijs Hi, could you please look into this? According to https://learn.microsoft.com/en-us/graph/api/resources/conditionalaccessexternaltenants?view=graph-rest-beta these properties only allow *all, enumerated, unknownFutureValue* but the API still can return $null and with your diff this now makes the resource fail when this case happens.

**Comment by Cyanic-Cloud** [comment]
Thanks @NikCharlebois, much appreciated 🚀
