### ISSUE TITLE
EXOHostedOutboundSpamFilterPolicy + EXOOrgnaizationConfig: Uint type not found

### ISSUE THREAD

**Issue by T630Dev** [microsoft/Microsoft365DSC#4353]
### Description of the issue

The ressources EXOHostedOutboundSpamFilterPolicy + EXOOrgnaizationConfig do not work.
Potentially others are affected, too,  but these are confirmed.
I used Set-HostedOutboundSpamFilterPolicy -Identity Default -AutoforwardingMode On
Then, i get a similar error: unable to find type [uint]
Same happens when using cmd: set-OrganizationConfig -DisablePlusAddressInRecipients:$false

Hence, I think the error is not in M365DSC.
I tried the same with EXO Module version 3.3.0. Same error. Last moth, however, it worked without isssues on version 3.3.0.
The error when using DSC only occurs, if the Test method returns false. Get works fine.
The ExchangeOnlineManagement cmdlets seem to work with PS 7 but do not work with PS 5.1.

### Microsoft 365 DSC Version

1.24.214.3

### Which workloads are affected

Exchange Online

### The DSC configuration

```powershell
Configuration MyM365
{
    param
    (
        [Parameter(Mandatory = $false,Position=0)][ValidateNotNull()][System.Management.Automation.PSCredential]$AdminCred
    )
    Import-DscResource -ModuleName "Microsoft365DSC"
    Node localhost
    {
        EXOHostedOutboundSpamFilterPolicy MyEXOHostedOutboundSpamFilterPolicy
        {
            AutoForwardingMode="Off";
            Identity = "Default";
            CertificateThumbprint = "..";
            ApplicationId = "...";
            TenantId = "...onmicrosoft.com";
        }
        EXOOrganizationConfig MyEXOOrganizationConfig
        {
            IsSingleInstance="yes";
            DisablePlusAddressInRecipients=$false;
            CertificateThumbprint = "...";
            ApplicationId = "...";
            TenantId = "....onmicrosoft.com";   
        }
    }
}
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}

Name                           Value
----                           -----
PSVersion                      5.1.17763.5458
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.5458
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by malauter** [comment]
@T630Dev I just tried to reproduce this, but for me it is working in PS7 and PS5.1 with Exchange Online Management Shell 3.4.0.
Could you please confirm that the issue is still there?

**Comment by T630Dev** [comment]
Confirmed. Now It works again in PS 5.1. 
Since I did not change anything on the client, I assume that someone fixed this on the endpoint side...
I have not tested with M365DSC but I assume that since the underlying Set-OrganizationConfig cmdlet works fine, that also the M365DSC Res will work again as expected.

**Comment by 2PintChristianN** [comment]
Similar issue with `uint` erroring out #4905
