### ISSUE TITLE
AADGroup Character Escaping

### ISSUE THREAD

**Issue by fraserdarwent** [microsoft/Microsoft365DSC#4358]
### Description of the issue

If an AADGroup name contains `'` e.g. `Fraser's Group`, it is not escaped correctly and an error is thrown.

### Microsoft 365 DSC Version

1.24.214.3

### Which workloads are affected

Azure Active Directory

### The DSC configuration

```powershell
AADGroup "AADGroup-Fraser's Group"
        {
            ...
            DisplayName = "Fraser's Group";
            ...
        }
```

### Verbose logs showing the problem

```powershell
##[error][BadRequest] : Invalid filter clause: Syntax error at position 32 in 'DisplayName eq 'Fraser's Group''.
##[error]PowerShell exited with code '1'.
```

**Comment by ykuijs** [comment]
Never mind, already found what is causing this issue. These lines are causing the issue:
https://github.com/microsoft/Microsoft365DSC/blob/92f2907e68d82b73d42179cc0ed9de8302cd1a8c/Modules/Microsoft365DSC/DSCResources/MSFT_AADGroup/MSFT_AADGroup.psm1#L150

and 

https://github.com/microsoft/Microsoft365DSC/blob/92f2907e68d82b73d42179cc0ed9de8302cd1a8c/Modules/Microsoft365DSC/DSCResources/MSFT_AADGroup/MSFT_AADGroup.psm1#L168

If the DisplayName parameter contains a quote, the string is terminated and therefore the error is thrown. Now looking for a solution.
