### ISSUE TITLE
Link to Whitepaper resp. M365Automation.zip is down

### ISSUE THREAD

**Issue by l0newolve** [microsoft/Microsoft365DSC#4367]
Link: https://aka.ms/m365dscwhitepaper

ERR_SSL_PROTOCOL_ERROR

**Comment by ykuijs** [comment]
Works for me as well, both for the whitepaper as for the scripts download. Could you please check again?

**Comment by ayuzuf** [comment]
I'm still facing the ERR_SSL_PROTOCOL_ERROR issue and cannot access the link. Is there a workaround for this?
