### ISSUE TITLE
EXOTransportRules not showing up in HTML or JSON

### ISSUE THREAD

**Issue by jagatjb** [microsoft/Microsoft365DSC#4377]
### Description of the issue

When I am using New-M365DSCDeltaReport, some Exchange Transport rules where i know changes have happened are not showing in the html file generated. 
Same happens when I am generating report in html, it is those same exchange transport rules missing. But the ps1 file does contains those missing exchange transport rules. 
I am not sure the problem here as similar rules with similar naming conventions and parameters are being reported fine in html format. I did check in json format, the issue is the same. 
I have updated the microsoft 365 dsc module to the latest, but the problem remains the same. Now i do not see any warnings in verbose. previously i did find some warnings in verbose when i am using New-M365DSCDeltaReport.

Below are the warnings which i got previously. We need your help here and its a big issue for us.

WARNING: ConvertTo-DSCObject: "From" (line 8741): The 'from' keyword is not supported in this version of the language.
WARNING: ConvertTo-DSCObject: "type":"AdaptiveCard","originator":"[0-9a-fA-F]" (line 27174): Unexpected token 'type":"AdaptiveCard","originator":"[0-9a-fA-F]' in expression or statement.
WARNING: ConvertTo-DSCObject: "" (line 27174): Missing type name after '['.
WARNING: ConvertTo-DSCObject: "" (line 27174): You must provide a value expression following the '-' operator.
WARNING: ConvertTo-DSCObject: "" (line 27174): Missing ']' after array index expression.
WARNING: ConvertTo-DSCObject: "application/adaptivecard\+json">"" (line 27488): Unexpected token 'application/adaptivecard\+json">"' in expression or statement.
WARNING: ConvertTo-DSCObject: "}" (line 27750): Unexpected token '}' in expression or statement.
WARNING: ConvertTo-DSCObject: "EXOTransportRule" (line 4169): Resource 'EXOTransportRule' requires that a value of type 'String' be provided for property 'Name'.
WARNING: ConvertTo-DSCObject: "You've successfully logged into the _____People Yammer application”
“You've" (line 4180): Unexpected token 'You've successfully logged into the _____People Yammer application”
“You've' in expression or statement.
WARNING: ConvertTo-DSCObject: "" (line 4180): There is an incomplete property assignment block in the instance definition.

WARNING: ConvertTo-DSCObject: "From" (line 8741): The 'from' keyword is not supported in this version of the language.
WARNING: ConvertTo-DSCObject: "type":"AdaptiveCard","originator":"[0-9a-fA-F]" (line 27174): Unexpected token 'type":"AdaptiveCard","originator":"[0-9a-fA-F]' in expression or statement.
WARNING: ConvertTo-DSCObject: "" (line 27174): Missing type name after '['.
WARNING: ConvertTo-DSCObject: "" (line 27174): You must provide a value expression following the '-' operator.
WARNING: ConvertTo-DSCObject: "" (line 27174): Missing ']' after array index expression.
WARNING: ConvertTo-DSCObject: "application/adaptivecard\+json">"" (line 27488): Unexpected token 'application/adaptivecard\+json">"' in expression or statement.
WARNING: ConvertTo-DSCObject: "}" (line 27750): Unexpected token '}' in expression or statement.
WARNING: ConvertTo-DSCObject: "EXOTransportRule" (line 4169): Resource 'EXOTransportRule' requires that a value of type 'String' be provided for property 'Name'.

### Microsoft 365 DSC Version

1.24.221.1

### Which workloads are affected

Exchange Online

### The DSC configuration

```powershell
NA
```

### Verbose logs showing the problem

```powershell
WARNING: ConvertTo-DSCObject: "From" (line 8741): The 'from' keyword is not supported in this version of the language.
WARNING: ConvertTo-DSCObject: "type":"AdaptiveCard","originator":"[0-9a-fA-F]" (line 27174): Unexpected token 'type":"AdaptiveCard","originator":"[0-9a-fA-F]' in expression or statement.
WARNING: ConvertTo-DSCObject: "" (line 27174): Missing type name after '['.
WARNING: ConvertTo-DSCObject: "" (line 27174): You must provide a value expression following the '-' operator.
WARNING: ConvertTo-DSCObject: "" (line 27174): Missing ']' after array index expression.
WARNING: ConvertTo-DSCObject: "application/adaptivecard\+json">"" (line 27488): Unexpected token 'application/adaptivecard\+json">"' in expression or statement.
WARNING: ConvertTo-DSCObject: "}" (line 27750): Unexpected token '}' in expression or statement.
WARNING: ConvertTo-DSCObject: "EXOTransportRule" (line 4169): Resource 'EXOTransportRule' requires that a value of type 'String' be provided for property 'Name'.
WARNING: ConvertTo-DSCObject: "You've successfully logged into the ____ People Yammer application”
“You've" (line 4180): Unexpected token 'You've successfully logged into the ____ People Yammer application”
“You've' in expression or statement.
WARNING: ConvertTo-DSCObject: "" (line 4180): There is an incomplete property assignment block in the instance definition.


WARNING: ConvertTo-DSCObject: "From" (line 8741): The 'from' keyword is not supported in this version of the language.
WARNING: ConvertTo-DSCObject: "type":"AdaptiveCard","originator":"[0-9a-fA-F]" (line 27174): Unexpected token 'type":"AdaptiveCard","originator":"[0-9a-fA-F]' in expression or statement.
WARNING: ConvertTo-DSCObject: "" (line 27174): Missing type name after '['.
WARNING: ConvertTo-DSCObject: "" (line 27174): You must provide a value expression following the '-' operator.
WARNING: ConvertTo-DSCObject: "" (line 27174): Missing ']' after array index expression.
WARNING: ConvertTo-DSCObject: "application/adaptivecard\+json">"" (line 27488): Unexpected token 'application/adaptivecard\+json">"' in expression or statement.
WARNING: ConvertTo-DSCObject: "}" (line 27750): Unexpected token '}' in expression or statement.
WARNING: ConvertTo-DSCObject: "EXOTransportRule" (line 4169): Resource 'EXOTransportRule' requires that a value of type 'String' be provided for property 'Name'.
```

**Comment by jagatjb** [comment]
Any help on this?

**Comment by andikrueger** [comment]
Could you share the resources configuration for this case? This looks like either an issue in DSCParser or in the export method of EXOTransportRule. Thanks!

**Comment by jagatjb** [comment]
As the Resource config is a very large file with 300+ transport rules, I am sharing you snippets of the config from where I can find the errors from VS Code. The html report is totally broken.

**Comment by jagatjb** [comment]
There is an incomplete property assignment block in the instance definition.
Unexpected token 'BCC” Field. Thank You."' in expression or statement.

EXOTransportRule "EXOTransportRule-redacted"
        {
            ApplicationId                             = $ConfigurationData.NonNodeData.ApplicationId;
            ApplyOME                                  = $False;
            AttachmentHasExecutableContent            = $False;
            AttachmentIsPasswordProtected             = $False;
            AttachmentIsUnsupported                   = $False;
            AttachmentProcessingLimitExceeded         = $False;
            CertificateThumbprint                     = $ConfigurationData.NonNodeData.CertificateThumbprint;
            Comments                                  = "redacted";
            DeleteMessage                             = $False;
            Enabled                                   = $True;
            Ensure                                    = "Present";
            ExceptIfAttachmentHasExecutableContent    = $False;
            ExceptIfAttachmentIsPasswordProtected     = $False;
            ExceptIfAttachmentIsUnsupported           = $False;
            ExceptIfAttachmentProcessingLimitExceeded = $False;
            ExceptIfHasNoClassification               = $False;
            From                                      = @("redacted");
            FromScope                                 = "InOrganization";
            HasNoClassification                       = $False;
            HeaderContainsMessageHeader               = "To";
            HeaderContainsWords                       = @("redacted","redacted");
            Mode                                      = "Enforce";
            ModerateMessageByManager                  = $False;
            Name                                      = "redacted";
            Priority                                  = 124;
            Quarantine                                = $False;
            RecipientAddressType                      = "Resolved";
            RejectMessageEnhancedStatusCode           = "5.7.1";
            RejectMessageReasonText                   = "This email has been blocked as the recipient marked in the mail is not in “BCC” Field. Thank You.";
            RemoveOME                                 = $False;
            RemoveOMEv2                               = $False;
            RemoveRMSAttachmentEncryption             = $False;
            RouteMessageOutboundRequireTls            = $False;
            RuleErrorAction                           = "Ignore";
            RuleSubType                               = "None";
            SenderAddressLocation                     = "HeaderOrEnvelope";
            SentToScope                               = "InOrganization";
            SetAuditSeverity                          = "Medium";
            StopRuleProcessing                        = $True;
            TenantId                                  = $OrganizationName;
        }

The above error is same for multiple transport rules where the transport rule looks same.

The 'from' keyword is not supported in this version of the language. For this error, I am sharing few transport rules from resource config.
EXOTransportRule "EXOTransportRule-redacted"
        {
            ApplicationId                             = $ConfigurationData.NonNodeData.ApplicationId;
            ApplyOME                                  = $False;
            AttachmentHasExecutableContent            = $False;
            AttachmentIsPasswordProtected             = $False;
            AttachmentIsUnsupported                   = $False;
            AttachmentProcessingLimitExceeded         = $False;
            CertificateThumbprint                     = $ConfigurationData.NonNodeData.CertificateThumbprint;
            Comments                                  = "redacted";
            DeleteMessage                             = $False;
            Enabled                                   = $True;
            Ensure                                    = "Present";
            ExceptIfAttachmentHasExecutableContent    = $False;
            ExceptIfAttachmentIsPasswordProtected     = $False;
            ExceptIfAttachmentIsUnsupported           = $False;
            ExceptIfAttachmentProcessingLimitExceeded = $False;
            ExceptIfHasNoClassification               = $False;
            From                                      = @(redacted); # more then 50 senders
            FromScope                                 = "NotInOrganization";
            HasNoClassification                       = $False;
            Mode                                      = "Enforce";
            ModerateMessageByManager                  = $False;
            Name                                      = "redacted";
            Priority                                  = 140;
            Quarantine                                = $False;
            RecipientAddressType                      = "Resolved";
            RemoveOME                                 = $False;
            RemoveOMEv2                               = $False;
            RemoveRMSAttachmentEncryption             = $False;
            RouteMessageOutboundRequireTls            = $False;
            RuleErrorAction                           = "Ignore";
            RuleSubType                               = "None";
            SenderAddressLocation                     = "HeaderOrEnvelope";
            SetSCL                                    = "redacted";
            StopRuleProcessing                        = $True;
            TenantId                                  = $OrganizationName;
        }

![image](https://github.com/microsoft/Microsoft365DSC/assets/150674452/4493fbd3-e91b-459c-a2a3-ce2bdbff82de)


 EXOTransportRule "EXOTransportRule-redacted"
        {
            ApplicationId                             = $ConfigurationData.NonNodeData.ApplicationId;
            ApplyOME                                  = $False;
            AttachmentHasExecutableContent            = $False;
            AttachmentIsPasswordProtected             = $False;
            AttachmentIsUnsupported                   = $False;
            AttachmentProcessingLimitExceeded         = $False;
            CertificateThumbprint                     = $ConfigurationData.NonNodeData.CertificateThumbprint;
            Comments                                  = "redacted 
";
            DeleteMessage                             = $False;
            Enabled                                   = $True;
            Ensure                                    = "Present";
            ExceptIfAttachmentHasExecutableContent    = $False;
            ExceptIfAttachmentIsPasswordProtected     = $False;
            ExceptIfAttachmentIsUnsupported           = $False;
            ExceptIfAttachmentProcessingLimitExceeded = $False;
            ExceptIfHasNoClassification               = $False;
            From                                      = @("redacted");
            HasNoClassification                       = $False;
            HeaderContainsMessageHeader               = "redacted";
            HeaderContainsWords                       = @("yes");
            Mode                                      = "Enforce";
            ModerateMessageByManager                  = $False;
            Name                                      = "redacted";
            Priority                                  = 221;
            Quarantine                                = $False;
            RecipientAddressType                      = "Resolved";
            RedirectMessageTo                         = @("redacted");
            RemoveOME                                 = $False;
            RemoveOMEv2                               = $False;
            RemoveRMSAttachmentEncryption             = $False;
            RouteMessageOutboundRequireTls            = $False;
            RuleErrorAction                           = "Ignore";
            RuleSubType                               = "None";
            SenderAddressLocation                     = "Header";
            SentTo                                    = @("redacted");
            SetAuditSeverity                          = "High";
            StopRuleProcessing                        = $True;
            TenantId                                  = $OrganizationName;
        }


Unexpected token 'application/adaptivecard\+json">"' in expression or statement.
EXOTransportRule "EXOTransportRule-redacted"
        {
            ApplicationId                             = $ConfigurationData.NonNodeData.ApplicationId;
            ApplyOME                                  = $False;
            AttachmentHasExecutableContent            = $False;
            AttachmentIsPasswordProtected             = $False;
            AttachmentIsUnsupported                   = $False;
            AttachmentProcessingLimitExceeded         = $False;
            CertificateThumbprint                     = $ConfigurationData.NonNodeData.CertificateThumbprint;
            Comments                                  = "redacted";
            DeleteMessage                             = $False;
            Enabled                                   = $True;
            Ensure                                    = "Present";
            ExceptIfAttachmentHasExecutableContent    = $False;
            ExceptIfAttachmentIsPasswordProtected     = $False;
            ExceptIfAttachmentIsUnsupported           = $False;
            ExceptIfAttachmentProcessingLimitExceeded = $False;
            ExceptIfHasNoClassification               = $False;
            HasNoClassification                       = $False;
            Mode                                      = "Enforce";
            ModerateMessageByManager                  = $False;
            Name                                      = "redacted";
            Priority                                  = 280;
            Quarantine                                = $False;
            RecipientAddressType                      = "Resolved";
            RemoveOME                                 = $False;
            RemoveOMEv2                               = $False;
            RemoveRMSAttachmentEncryption             = $False;
            RouteMessageOutboundRequireTls            = $False;
            RuleErrorAction                           = "Ignore";
            RuleSubType                               = "None";
            SenderAddressLocation                     = "Header";
            SetHeaderName                             = "redacted";
            SetHeaderValue                            = "any";
            StopRuleProcessing                        = $False;
            SubjectOrBodyMatchesPatterns              = @("<script type="application/adaptivecard\+json">");
            TenantId                                  = $OrganizationName;
        }

Unexpected token '}' in expression or statement.
![image](https://github.com/microsoft/Microsoft365DSC/assets/150674452/f337171a-3909-4d53-b03a-6495c0d00862)

In the html report we are seeing like these for all the rules where the "from" error started.
![image](https://github.com/microsoft/Microsoft365DSC/assets/150674452/694e9124-5b3a-46e8-99d4-0d81cf179b46)

**Comment by jagatjb** [comment]
> Thank you for the resource snippets. There is something wrong with the escaping of quotes. Your strings contain quotes and these are breaking the resource’s configuration

These quotes are opened and closed as well. The transport rules does not contain such quotes in the comment section or any string value which are part of the transport rule. Is there anyhow you can help us with this. We have a lot of transport rules and monitoring is essential.

**Comment by andikrueger** [comment]
Just to clarify: The resources and their configurations were created using Export-M365DSCConfiguration?

**Comment by jagatjb** [comment]
> Just to clarify: The resources and their configurations were created using Export-M365DSCConfiguration?

Yes, I am working on removing the quotes"" where the errors are occurring. I will update if the issue is fixed permanently. The errors are getting reduced as of now. I am thoroughly checking the configuration.

**Comment by ricmestre** [comment]
Please write down which properties you had to modify in order to escape those extra quotes in the code.

**Comment by andikrueger** [comment]
@ricmestre Shouldn't we run escaping on all string properties regardless of the name before pushing them into the output stream

**Comment by ricmestre** [comment]
If it doesn't impact anything else sure, it's better than doing it one by one.

**Comment by jagatjb** [comment]
> Please write down which properties you had to modify in order to escape those extra quotes in the code.

I have removed the double quotes from some parameters such as comments and RejectMessageReasonText and now I do not see the error. I will test this over the weekend and coming monday to know for sure. As of now the html is also being generated fine.
Still there are few errors for 
SubjectOrBodyMatchesPatterns : {"type":"AdaptiveCard","originator":"[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}"}

I think removing the double quotes and [] can impact the transport rule.

Can we accept the double quotes, brackets in coming releases for transport rules ?

**Comment by jagatjb** [comment]
> We need to modify this function in ReverseDSC for this matter:
> 
> https://github.com/microsoft/ReverseDSC/blob/32199ce3a3a9376631b6257f23a71ee3a54362f7/ReverseDSC.Core.psm1#L90
> 
> In this function there is already some handling present for invalid string characters like `. We should extend this handling to properly escaping double quotes. In the generated DSC blocks we always use double quotes to define string.

This would be really great once done. I am a newbie to scripts, otherwise I would have done myself, still learning. Apart from quotes, it would be great if it was extended to brackets as well.

**Comment by andikrueger** [comment]
I guess we also need to look into the Array processing then for `SubjectOrBodyMatchesPatterns`. The json should still be fine with proper escaping of the quotes. As soon as the quotes are escaped the brackets will no longer matter.

**Comment by jagatjb** [comment]
> I guess we also need to look into the Array processing then for `SubjectOrBodyMatchesPatterns`. The json should still be fine with proper escaping of the quotes. As soon as the quotes are escaped the brackets will no longer matter.

@andikrueger  will the fix be available in the upcoming release ?
