### ISSUE TITLE
Error on EXOHostedContentFilterRule in v1.24.228.1 - The operation couldn't be performed because object 'contos.com' couldn't be found on

### ISSUE THREAD

**Issue by cdenders** [microsoft/Microsoft365DSC#4401]
Export-M365DSCConfiguration -Components @("EXOAntiPhishPolicy", "EXOAntiPhishRule", "EXOHostedContentFilterRule", "EXOHostedOutboundSpamFilterPolicy", "EXOHostedOutboundSpamFilterRule", "EXOTransportRule") -Credential $SourceCredential -Path C:\Dsc

System.Exception: Ex6F9304|Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException|The operation couldn't be performed because object 'contos.com' couldn't be found on 'YT3PR01A01DC008.CANPR01A001.PROD.OUTLOOK.COM'. "Error calling {Get-HostedContentFilterRule}"

Yet if I just execute Get-HostedContentFilterRule in powershell, it shows my rule.  So why does it give an error when I specify it as part of the export?

**Comment by cdenders** [comment]
If it helps, it is seeing my rule named "xxx Spam Filter rules":
 
[3/6] Extracting [EXOHostedContentFilterRule] using {Credentials}...
    |---[1/1] xxx Spam Filter rules Error Log created at {file://C:/dsc/37496-M365DSC-ErrorLog.log}
✅

**Comment by malauter** [comment]
Seems to be a bug in the get method. It is using the name of the filter policy instead of the rule. I will work on this.
