### ISSUE TITLE
New parameters needed for Exchange resource

### ISSUE THREAD

**Issue by skoley09** [microsoft/Microsoft365DSC#4424]
### Description of the issue

We have found The below attributes are not available in the TransportConfig configuration and it would be great if those are added -
AnonymousSenderToRecipientRatePerHour
ExternalDsnMaxMessageAttachSize
MaxSendSize
TLSReceiveDomainSecureList
TLSSendDomainSecureList
VerifySecureSubmitEnabled
VoicemailJournalingEnabled
Xexch50Enabled

We have found The below attributes are not available in the EXOAuthenticationPolicy configuration and it would be great if those are added -
AllowBasicAuthRest

We have found The below attributes are not available in the AdminAuditLogConfig configuration and it would be great if those are added -
AdminAuditLogEnabled
LogLevel
TestCmdletLoggingEnabled
AdminAuditLogCmdlets
AdminAuditLogParameters
AdminAuditLogExcludedCmdlets
AdminAuditLogAgeLimit
LoadBalancerCount
RefreshInterval
PartitionInfo
AdminAuditLogMailbox

We have found The below attributes are not available in the HostedContentFilterPolicy configuration and it would be great if those are added -
IntraOrgFilterState

### Microsoft 365 DSC Version

1.24.221.1

### Which workloads are affected

Exchange Online

### The DSC configuration

```powershell
NA
```

### Verbose logs showing the problem

```powershell
NA
```

### Environment Information + PowerShell Version

```powershell
NA
```

**Comment by malauter** [comment]
@skoley09 all the parameters you mentioned for TransportConfig, AuthenticationPolicy and AdminAuditLogConfig are per our documentation available in onpremise Exchange organizations only or are not documented.
But I will take care of adding IntraOrgFilterState to HostedContentFilterPolicy.

**Comment by skoley09** [comment]
Hello @malauter , we can see that the below MS article where it is mentioned as these cmdlet(s) apply to Exchange Online and some of the parameters are only applied to Exchange on-prem.
Please review from your end and add if possible to extract the results via DSC -

**TransportConfig**
https://learn.microsoft.com/en-us/powershell/module/exchange/get-transportconfig?view=exchange-ps

**AuthenticationPolicy**
https://learn.microsoft.com/en-us/powershell/module/exchange/get-authenticationpolicy?view=exchange-ps

**AdminAuditLogConfig**
https://learn.microsoft.com/en-us/powershell/module/exchange/get-adminauditlogconfig?view=exchange-ps

**Comment by malauter** [comment]
@skoley09 We can only extract what we can also apply to the tenant again. So, you should check the documentation of the Set-* cmdlets. There you will find the note "This parameter is available only in on-premises Exchange" for your requested parameters.

**Comment by skoley09** [comment]
Thank you @malauter for the clarification.
can you please check the Issue **#4423** and help us obtaining those attributes ?
