### ISSUE TITLE
Error while running Export-O365Configuration

### ISSUE THREAD

**Issue by muralmu** [microsoft/Microsoft365DSC#443]
#### Details of the scenario you tried and the problem that is occurring
I was able to install the Office365DSC module but while running the, Export-O365Configuration cmdlet, it errors out with below error message: 
"Export-O365Configuration : The 'Export-O365Configuration' command was found in the module 'Office365DSC', but the module could not be loaded. For more information, run 'Import-Module Office365DSC'.
At line:1 char:1
+ Export-O365Configuration
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Export-O365Configuration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule "

#### Verbose logs showing the problem
--Looks like the issue lies here: "Import-Module : Could not load type 'Microsoft.SharePoint.Administration.OrgAssetType' from assembly 'Microsoft.SharePoint.Client, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'."

Verbose info as below: 

Import-Module Office365DSC -Verbose
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Office365DSC\1.0.3.1723\Office365DSC.psd1'.
Import-Module : Could not load type 'Microsoft.SharePoint.Administration.OrgAssetType' from assembly 'Microsoft.SharePoint.Client, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'.
At line:1 char:1
+ Import-Module Office365DSC -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

#### Suggested solution to the issue
N/A
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
Office365DSC - 1.0.3.1723

**Comment by NikCharlebois** [comment]
We have recently encountered cases where users had to remove all existing versions of the SharePoint Online Management Shell modules on their machine, re-install the SPO Management shell binaries from the Download Center, and re-install the module using "Install-Module Office365DSC -Force". 

Please try this approach and keep us posted.
