### ISSUE TITLE
Error while extracting the Accepted Domain list

### ISSUE THREAD

**Issue by skoley09** [microsoft/Microsoft365DSC#4446]
### Description of the issue

We have more than 580 Accepted domains and while extracting the same via EXOAcceptedDomain configuration to monitor the same, we are encountering same error at a particular domain. The error message is mentioned below -

{InvalidData}
System.Management.Automation.ParameterBindingValidationException: Cannot validate argument on parameter 'Identity'. The argument "20.co.in" does not match the "(?=^.{1,254}$)(^(?:(?!\d+\.|-)[a-zA-Z0-9_\-]{1,63}(?<!-)\.?)+(?:[a-zA-Z]{2,})$)" pattern. Supply an argument that matches "(?=^.{1,254}$)(^(?:(?!\d+\.|-)[a-zA-Z0-9_\-]{1,63}(?<!-)\.?)+(?:[a-zA-Z]{2,})$)" and try the command again. ---> System.Management.Automation.ValidationMetadataException: The argument "20.co.in" does not match the "(?=^.{1,254}$)(^(?:(?!\d+\.|-)[a-zA-Z0-9_\-]{1,63}(?<!-)\.?)+(?:[a-zA-Z]{2,})$)" pattern. Supply an argument that matches "(?=^.{1,254}$)(^(?:(?!\d+\.|-)[a-zA-Z0-9_\-]{1,63}(?<!-)\.?)+(?:[a-zA-Z]{2,})$)" and try the command again.
   at System.Management.Automation.ValidatePatternAttribute.ValidateElement(Object element)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
"Error during Export:"
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.131.2\DSCResources\MSFT_EXOAcceptedDomain\MSFT_EXOAcceptedDomain.psm1: line 392
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.131.2\Modules\M365DSCReverse.psm1: line 649
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.131.2\Modules\M365DSCUtil.psm1: line 1312
at <ScriptBlock>, <No file>: line 1

Please check and help us fixing this issue, so that we can use this configuration to monitor the accepted domains.

### Microsoft 365 DSC Version

1.24.131.2

### Which workloads are affected

Exchange Online

### The DSC configuration

```powershell
NA
```

### Verbose logs showing the problem

```powershell
NA
```

### Environment Information + PowerShell Version

```powershell
NA
```

**Comment by malauter** [comment]
The number in your domain 20.co.in is not covered in the validation regex of the resource. We will update the expression.
