### ISSUE TITLE
Applying different DSC rules to different workloads 

### ISSUE THREAD

**Issue by Wopienkaatwork** [microsoft/Microsoft365DSC#4453]
I was wondering if it is possible to assign different rules to different workloads. 
For instance workload AAD - ApplyAndAutoCorrect, EXO - ApplyOnly, Intune ApplyAndMonitor

In my case I want to be as strictly as possible when a drift is detected that this change is being automatically reverted to the baseline, when I have ApplyOnly or ApplyAndMonitor I just want to detect the drift and report it to the eventlog and not revert to the baseline. 

Is this possible and if so, how can I do that?

**Comment by NikCharlebois** [comment]
It is, but it would require different Local Configuration Manager (LCM) service instances. The best way to achieve what you are describing is to leverage something like containers services where you dedicate:

1 container for AAD as ApplyAndAutocorrect
1 container for EXO as ApplyOnly
...

**Comment by Wopienkaatwork** [comment]
Is it possible to install more than one LCM on a single Windows Server VM? Currently I am using one VM in Azure. 
Or do you mean Windows Server Container which I thought is not possible because LCM is not support on Windows Server as a container.

**Comment by andikrueger** [comment]
There is only one instance of LCM on one server. 

You could implement your requirement using several servers or also by running test-dscconfiguration regularly and based on the result trigger a start-dsc configuration and revoke the configuration after a successful run.

**Comment by Wopienkaatwork** [comment]
Okay I will look into this approach :)
