### ISSUE TITLE
1.24.313.1 is missing from github releases page?

### ISSUE THREAD

**Issue by bartvermeersch** [microsoft/Microsoft365DSC#4478]
The latest release [1.24.313.1 (current version)](https://www.powershellgallery.com/packages/Microsoft365DSC/1.24.313.1) is missing from https://github.com/microsoft/Microsoft365DSC/releases
Or should I have more patience?

**Comment by adhodgson1** [comment]
I was going to open a similar issue. Usually it shows up on Github at the same time or near when it gets published to the gallery.

**Comment by ykuijs** [comment]
Sorry, this is now corrected! See here: https://github.com/microsoft/Microsoft365DSC/releases/tag/1.24.313.1
