### ISSUE TITLE
[ERROR] M365DSCReport.psm1 - New-M365DSCReportFromConfiguration function - Parsed content was null

### ISSUE THREAD

**Issue by Kierow** [microsoft/Microsoft365DSC#4505]
### Description of the issue

Hello,

It seems that during 1.24.214.2 release, the following code was introduced in the M365DSCReport.psm1 module and more particularly in New-M365DSCReportFromConfiguration function:
``
if ($null -ne $parsedContent)
{
    Code...
}
else
{
    throw "Parsed content was null."
}
``    

When I export several components, I don't face any error.
![image](https://github.com/microsoft/Microsoft365DSC/assets/122234435/44ce00e7-ac2c-4835-852d-9b30bb5a1fa2)

However, if I export only one component that is empty, I will have this error:
![image](https://github.com/microsoft/Microsoft365DSC/assets/122234435/37e5b110-8fb0-4c37-8e72-4dd6104284be)

This error comes from the code stated above. Before this release, the $parsedContent was not checked and it was possible to make a report of a component that is empty.

For more information, here is the content of AADAuthenticationContextClassReference.ps1 (used for the report where $parsedContent is null):

-------------------------------------------------
``
Generated with Microsoft365DSC version 1.24.313.1
For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
)

Configuration DEV-M365Tenant-AAD-AADAuthenticationContextClassReference
{
    param (
    )

    $OrganizationName = $ConfigurationData.NonNodeData.OrganizationName

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.24.313.1'

    Node localhost
    {

        For information on how to use this resource, please refer to:
        https://github.com/microsoft/Microsoft365DSC/wiki/AADAuthenticationContextClassReference
    }
}

DEV-M365Tenant-AAD-AADAuthenticationContextClassReference -ConfigurationData .\ConfigurationData.psd1

``
---------------------------------------------

I don't know if it's something expected... therefore I submit this issue. :)

If you need more information, don't hesitate.

### Microsoft 365 DSC Version

1.24.313.1

### Which workloads are affected

other

**Comment by andikrueger** [comment]
This is partially expected as there is no data within your configuration and therefore nothing to report... 
I guess it would still add value if we would not terminate the process like this and still generate a report stating: nothing to report.

**Comment by Kierow** [comment]
Thanks for your answer ! 
Yes, the main issue currently is that it stops the process, and in my opinion it would be better if it generates a report stating "nothing to report" as you said (or even nothing at all), but it should not stop the process (it should just go to the next instruction).
