### ISSUE TITLE
Latest version 1.24.403.1 not published to PowerShellGallery

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#4521]
### Description of the issue

The GH action to publish the latest version to PowerShellGallery failed due to the manifest file Microsoft365DSC.psd1 still having it defined as version 1.24.313.1 which is already published.

```powershell
Run Publish-Module -Path "./Modules/Microsoft365DSC/" -NugetAPIKey $env:PUBLIC_NUGETAPIKEY
Publish-Module : The module 'Microsoft365DSC' with version '1.24.313.1' cannot be published as the current version 
'1.24.313.1' is already available in the repository 'https://www.powershellgallery.com/api/v2'.
At D:\a\_temp\99d0dee2-a487-4334-b86c-404e25b3fc7a.ps1:2 char:1
+ Publish-Module -Path "./Modules/Microsoft365DSC/" -NugetAPIKey $env:P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-Module], InvalidOperationException
    + FullyQualifiedErrorId : ModuleVersionIsAlreadyAvailableInTheGallery,Publish-Module
```

### Microsoft 365 DSC Version

1.24.403.1

### Which workloads are affected

other

### The DSC configuration

```powershell
N/A
```

### Verbose logs showing the problem

```powershell
Run Publish-Module -Path "./Modules/Microsoft365DSC/" -NugetAPIKey $env:PUBLIC_NUGETAPIKEY
Publish-Module : The module 'Microsoft365DSC' with version '1.24.313.1' cannot be published as the current version 
'1.24.313.1' is already available in the repository 'https://www.powershellgallery.com/api/v2'.
At D:\a\_temp\99d0dee2-a487-4334-b86c-404e25b3fc7a.ps1:2 char:1
+ Publish-Module -Path "./Modules/Microsoft365DSC/" -NugetAPIKey $env:P ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-Module], InvalidOperationException
    + FullyQualifiedErrorId : ModuleVersionIsAlreadyAvailableInTheGallery,Publish-Module
```

### Environment Information + PowerShell Version

```powershell
N/A
```

**Comment by adhodgson1** [comment]
This is in the gallery but is broken due to a dependency issue:
Get-InstalledModule -name "microsoft365dsc" |select "version"

Version
-------
1.24.403.1

Update-M365DSCDependencies
Installing DSCParser version {2.0.0.3}
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'DSCParser'.   Try Get-PSRepository to see all available registered module repositories.
Any run then throws an error because of the missing dependency.

**Comment by ricmestre** [comment]
It is published now because Nik solved the issue I described a few minutes ago, you're describing another problem so please raise another issue, I'll close this one.
