### ISSUE TITLE
1.24.403.1: Unable to meet dependencies for DSCParser

### ISSUE THREAD

**Issue by adhodgson1** [microsoft/Microsoft365DSC#4527]
Get-InstalledModule -name "microsoft365dsc" |select "version"

Version
1.24.403.1

Update-M365DSCDependencies
Installing DSCParser version {2.0.0.3}
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'DSCParser'. Try Get-PSRepository to see all available registered module repositories.
Any run then throws an error because of the missing dependency.

**Comment by hvdbrink** [comment]
Same issue here, 
fixed this locally by changing the version in the manifest file under dependencies and running Update-M365DSCDependencies.

**Comment by Borgquite** [comment]
Same issue here

**Comment by Ben-m-s** [comment]
Same issue here as well.
Could the library [DSCParser](https://www.powershellgallery.com/packages/DSCParser/) be updated in the PS Gallery?
FYI: @NikCharlebois, @ykuijs

**Comment by ssoabx** [comment]
Looks like 2.0.0.3 has been updated now.

**Comment by ykuijs** [comment]
Correct, DscParser v2.0.0.3 has been published. Sorry for the inconvinience!
