### ISSUE TITLE
Graph SDK v2.17.0 contains a breaking change wrt removing a member from a group

### ISSUE THREAD

**Issue by salbeck-sit** [microsoft/Microsoft365DSC#4542]
### Description of the issue

In the latest Graph SDK-update, Remove-MgGroupMemberByRef has been 'augmented' in the sense that the parameter DirectoryObjectId has been removed and instead included with a new cmdlet Remove-MgGroupMemberDirectoryObjectByRef.
See https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2670#issuecomment-2044406230

It appears that the cmdlet is only being used in AADGroup and AADUser

### Microsoft 365 DSC Version

DEV

### Which workloads are affected

Azure Active Directory (Entra ID)

**Comment by andikrueger** [comment]
Thanks for finding this difference! It’s a real good catch.
