### ISSUE TITLE
New-M365DSCReportFromConfiguration: parsed content was null

### ISSUE THREAD

**Issue by febenitezc** [microsoft/Microsoft365DSC#4559]
### Description of the issue

Unable to run following script:

![PowerShell Error](https://github.com/microsoft/Microsoft365DSC/assets/16809434/64fde63b-eb8f-42e8-a152-38243f838453)
[How to Install - Microsoft365DSC - Your Cloud Configuration](https://microsoft365dsc.com/user-guide/get-started/how-to-install/)

 

Validate that the customer runs PowerShell version 5.1 and 7.3+

 

Install-Module Microsoft365DSC -Force

 

Update-M365DSCDependencies

 

Get-Module Microsoft365DSC -ListAvailable | select ModuleBase, Version

 

Update-Module Microsoft365DSC

 

Update-M365DSCDependencies

 

Export-M365DSCConfiguration -LaunchWebUI

#make sure to select all checkboxes and option from the GUI

#Planner, Power Platform, can be excluded from the selection.

### Microsoft 365 DSC Version

PROD

### Which workloads are affected

Azure Active Directory (Entra ID), Exchange Online, Intune, Office 365 Admin, Security & Compliance Center, SharePoint Online

**Comment by febenitezc** [comment]
Can someone please point me on the right direction to resolve issue above? "parsed content was null"

**Comment by andikrueger** [comment]
Can you confirm that your configuration.ps1 holds a configuration? In most cases this exception is due to an empty configuration or file.

**Comment by febenitezc** [comment]
Hi Andi,

Thanks for taking the time to answer my question. What do you mean by holding a configuration? This is the script that is available on github and makes reference to Microsoft365DSC.

Can you please elaborate on your answer? Please, check documentation on the script from the link, and let me know if I missed anything here.

Cheers

**Comment by andikrueger** [comment]
Please open the file at c:\temp\securitychecks\config.ps1 and check if there are any resources in `Node localhost {}`

**Comment by febenitezc** [comment]
What should be the correct configuration under that script? All the script that I'm running are from Github.

Can you please provide an example that what is supposed to be under that file? Node localhost {}

**Comment by andikrueger** [comment]
Depending on the selected resources the file should contain something like the first Example on this page here:

https://microsoft.github.io/Microsoft365DSC/resources/azure-ad/AADApplication/

**Comment by febenitezc** [comment]
Thanks Andi,

I was under the impression the configuration file is already filled out with that information. Do we have to manually build that file?

I read from another blog with similar error that we must run the command  Import-DscResource -ModuleName Microsoft365DSC  

Is that correct?

**Comment by Kierow** [comment]
Hello,

It might be related to this issue:
https://github.com/microsoft/Microsoft365DSC/issues/4505
