### ISSUE TITLE
Create delta report against DevOps composite resources

### ISSUE THREAD

**Issue by jadamones** [microsoft/Microsoft365DSC#4560]
Is it possible to take an export of a few resources in a tenant and create a delta report against the composite resources in a devops repo? I'm looking for a way to get a report on the exact settings that have changed vs just the resource that has changed. I'm currently parsing the output of checkdsccompliancy.ps1 and exporting just the resources that have changed, and I'm assessing that ps1 file against an automated full tenant export from the previous known good config . The is all automated and works, but it takes forever, and I'd rather run the delta against the composite resources already stored in devops vs having to take a full snapshot on each build.

**Comment by andikrueger** [comment]
DSCParser would be able to parse the composite resource but would miss the underlying partial configurations. To get around this limitation you could merge the various partial configurations into one file within your automation pipeline. This would be a simple string operation.

**Comment by jadamones** [comment]
Thank you! I tried that but had an issue with the report coming up blank; however, when troubleshooting with loading the configs into DSCParser, I discovered my configuration name on the error resources export did not start with a letter and therefore was invalid. Once I fixed that, I was able to get the report I was looking for.

**Comment by jadamones** [comment]
Hi I'm reopening this because I've discovered that when combining the composite resources, it stops after assessing the first workload. For instance, my first workload is AzureAD but if something has changed in the Teams configuration, the report is blank. You can also see in the output that it is only looking at AzureAD. It will work fine for the first workload. How should I manipulate the combined resources so that it will iterate through all workloads?

**Comment by jadamones** [comment]
I resolved this by creating a PS script and associated task in pipeline which combines the resources into a separate file that gets published as an artifact.
