### ISSUE TITLE
IntuneDeviceConfigurationWiredNetworkPolicyWindows10: Add certificate name additionally to id

### ISSUE THREAD

**Issue by FabienTschanz** [microsoft/Microsoft365DSC#4582]
### Description of the issue

When creating a wired network policy in Intune, we must specify the certificate ids used for validation etc. To make it easier for new resources to be created, it would be great to have the ability to specify a certificate name instead of only a id, so that moving the configuration between tenants is easier. 

Example: If the specified id of certificate X is not found, then search for certificate X in the Intune configuration, get the current id of it and apply it to the resource.

If this is something that's going to be accepted, I'd be glad to implement the change myself.

### Microsoft 365 DSC Version

V1.24.417.1

### Which workloads are affected

Intune

**Comment by ricmestre** [comment]
Don't have access to my machine now to check the code but it would be something similar of what I did on #4400

**Comment by FabienTschanz** [comment]
@ricmestre Exactly, that‘s the idea behind it. As it seems this might be something good to add. I will go for the implementation next week.
