### ISSUE TITLE
Multiple tenants

### ISSUE THREAD

**Issue by scandor** [microsoft/Microsoft365DSC#4606]
Hi,

in our organization we manage multiple M365 tenants. How would I go and configure Microsoft365DSC to monitor each tenant from drifting from a base configuration which we created using a reference tenant?

I have set up a dedicated server to export the baseline from the reference tenant, and have successfully created a mof file for a destination tenant. When I start the  DSCconfiguration I can see the base configuration being applied in the destination tenant. When I query the DSC configuration  using "Get-DscConfigurationStatuds | fl" I can see my configuration name in the MetaData. 
When I start the configuration for another tenant (Using a different configuration name) the configuration is being applied to this other tenant as expected. However when I query the DSC configstatus there is 1 job showing, and the MetaData tells me it's the latest configuration job I started.

Is there a way to create multiple jobs on one server to monitor all my tenants for changes?

regards,
Marco

**Comment by andikrueger** [comment]
You can use test-dscconfiguration with any mof file without applying the configuration to the tenant. This will allow you to use one system to test multiple configurations against the corresponding tenant. In the end you only need to monitor the computer’s event log for messages

**Comment by andikrueger** [comment]
Closing as stale.
