### ISSUE TITLE
AADMSGroup issue when multiple groups have same displayname

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#467]
#### Details of the scenario you tried and the problem that is occurring
When you have multiple AAD groups with the same display name, the resource fails on EXPORT and SET

#### Verbose logs showing the problem
System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.

#### Suggested solution to the issue
N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

**Comment by desmay** [comment]
Got it will review shortly
