### ISSUE TITLE
Assert-M365DSCBlueprint: Empty HTML Report

### ISSUE THREAD

**Issue by Alexprosp247** [microsoft/Microsoft365DSC#4693]
### Description of the issue

When I run the Assert-M365DSCBlueprint command all I get is an empty HTML report. However when I use JSON as the output it seems to be working fine. I don't receive any errors when running in either format. and I'm using the latest version of M365 DSC as well. Any advice on how to resolve this would be appreciated!
![Screenshot 2024-05-21 145448](https://github.com/microsoft/Microsoft365DSC/assets/159260897/ec6c6f11-84ec-4c97-bb96-6e65bd142f9f)
![image](https://github.com/microsoft/Microsoft365DSC/assets/159260897/5489d0ae-e5f4-4ce9-a925-dbcfa903b4ac)

### Microsoft 365 DSC Version

1.24.515.2

### Which workloads are affected

Teams

### The DSC configuration

```powershell
# Generated with Microsoft365DSC version 1.20.723.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $GlobalAdminAccount
)

Configuration M365TenantConfig
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $GlobalAdminAccount
    )

    if ($null -eq $GlobalAdminAccount)
    {
        <# Credentials #>
        $Credsglobaladmin = Get-Credential -Message "Global Admin credentials"
    }
    else
    {
        $Credsglobaladmin = $GlobalAdminAccount
    }

    $OrganizationName = $Credsglobaladmin.UserName.Split('@')[1]
    Import-DscResource -ModuleName Microsoft365DSC

    Node localhost
    {
        TeamsMeetingPolicy 4dd756aa-6396-4ba6-9d81-8a28cff738e8
        {
            AllowAnonymousUsersToStartMeeting          = $False; ### L1|We don't recommend external paarticipants to be able to start meeting because malicious users could lure employees in thinking that this is a formal meeting.
            AllowCloudRecording                        = $False; ### L2|We don't recommending allowing your recordings to be saved to the cloud. Set this value to <strong>false</strong>. For additional information, please refer to <a href="https://nikcharlebois.com/">this article</a>.
            AllowExternalParticipantGiveRequestControl = $True; ### L1|We don't recommend you allowing external Participant to give request control because that exposes your organization to threats.
            AllowWhiteboard                            = $True; ### L2|We recommend enabling whiteboard to improve collaboration. Set this value to <strong>true</strong>.
            Ensure                                     = "Present";
            Identity                                   = "Global";
        }
        TeamsMessagingPolicy 03c4ef23-cfb4-4801-b263-bd989c3e6177
        {
            AllowGiphy                    = $False; ### L1|We recommend disabling giphy because they can be a distraction and offensive to members of the meeting. Set this to $false.
            Ensure                        = "Present";
            Identity                      = "Global";
        }
    }
}
M365TenantConfig -ConfigurationData .\ConfigurationData.psd1 -GlobalAdminAccount $GlobalAdminAccount
```

**Comment by YenNantes** [comment]
I reported a similar issue some time ago: https://github.com/microsoft/Microsoft365DSC/issues/4100 but so far it is not fixed.

**Comment by dosLL** [comment]
Not the same issue as you guys, but also similar. I reported this some weeks ago, nothing changed yet.

#4516

**Comment by Alexprosp247** [comment]
@dosLL @YenNantes Hey guys not sure if you've had a chance to test since last time. But did an update on the module today and tried running the Assert command and seems to be working now.

**Comment by dosLL** [comment]
Seems like the new version (1.24.529.1) fixed the problems.

**Comment by YenNantes** [comment]
The issue is still there for me. The json contains the list of resources configured differently and missing resources but the HTML only contains the resources configured differently. Missing resources are not visible.
For example:
Json
![image](https://github.com/microsoft/Microsoft365DSC/assets/134401492/74e4edeb-392f-4090-abc6-4d8730b07a3e)
HTML
![image](https://github.com/microsoft/Microsoft365DSC/assets/134401492/8de3ade3-4134-49ef-817d-9e76c8eeb01e)
