### ISSUE TITLE
IDX12729: Unable to decode the header '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' as Base64Url encoded string.

### ISSUE THREAD

**Issue by KarinaxRivera** [microsoft/Microsoft365DSC#4720]
### Description of the issue

When running Export-M365DSCConfiguration using a certificate thumbprint, I get the following error message:

IDX12729: Unable to decode the header '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' as Base64Url encoded string.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\3.5.0\netFramework\ExchangeOnlineManagement.psm1:762 char:21
+                     throw $_.Exception.InnerException;
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : IDX12729: Unable to decode the header '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' 
    as Base64Url encoded string.

Any insight to this error would be helpful as I have not found anything relevant to fixing the issue.

### Microsoft 365 DSC Version

1.24.529.1

### Which workloads are affected

Exchange Online

**Comment by ricmestre** [comment]
That's a problem between Graph and EXO 3.5.0 module. Please update M365DSC to today's release which rolled back EXO to 3.4.0 and solves this issue.

**Comment by KarinaxRivera** [comment]
This solved it, thanks so much!

**Comment by reikor0x** [comment]
Same problem here again. Updated module and dependencies, not solved.
