### ISSUE TITLE
composite resource structure at component level (instead of workload level), for Devops

### ISSUE THREAD

**Issue by subhashvinjamuri** [microsoft/Microsoft365DSC#4745]
Teams.psm1
                    Teams.psd1
                     TeamsAppermissionPOlicy (folder)
                                      --- TeamsAppPermissionPOlicy.psm1
                                      ----Teams APpPermissionPOlicy.psd1
                     TeamsAppseupPOlicy (folder)
                                      --- TeamsAppsetupPOlicy.psm1
                                      ----Teams APpsetupPOlicy.psd1           
etc...
@andikrueger @ykuijs 
-->

**Comment by subhashvinjamuri** [comment]
https://github.com/ykuijs/M365DSC.CompositeResources/blob/main/source/M365DSC.CompositeResources.psd1 : Trying to mimic this and create it at component level., but seem lo luck yet Anyhelp appreciated

**Comment by ykuijs** [comment]
Replied in issue ykuijs/M365DSC.CRG#16

Closing this issue here
