### ISSUE TITLE
Partial Export was saved at...  

### ISSUE THREAD

**Issue by dinocaputo** [microsoft/Microsoft365DSC#4748]
### Description of the issue

Lately I'm noticing the following when attempting to run Exports.  Everything starts fine with no errors and you get the following

Connecting to {MicrosoftTeams}...✅
[1/21] Extracting [TeamsAudioConferencingPolicy] using {Credentials}...Partial Export file was saved at: C:\Users\dcaputo\AppData\Local\Temp\10fb7b8d-f5f3-479e-a7db-fc2b4fdaa01f.partial.ps1

There is no error log saved at that location.  Tried with both vanity domain creds and .onmicrosoft.com creds with no difference.  All modules updated and old dependencies cleared.  Happening in multiple tenants.  

### Microsoft 365 DSC Version

1.24.605.1

### Which workloads are affected

Teams

### The DSC configuration

```powershell
Export-M365DSCConfiguration -Components @("TeamsAudioConferencingPolicy", "TeamsCallHoldPolicy", "TeamsCallingPolicy", "TeamsCallParkPolicy", "TeamsCallQueue", "TeamsComplianceRecordingPolicy", "TeamsDialInConferencingTenantSettings", "TeamsEmergencyCallingPolicy", "TeamsEmergencyCallRoutingPolicy", "TeamsIPPhonePolicy", "TeamsMobilityPolicy", "TeamsOnlineVoicemailPolicy", "TeamsOnlineVoicemailUserSettings", "TeamsOnlineVoiceUser", "TeamsPstnUsage", "TeamsTenantDialPlan", "TeamsTranslationRule", "TeamsUnassignedNumberTreatment", "TeamsUserCallingSettings", "TeamsVoiceRoute", "TeamsVoiceRoutingPolicy") -Credential $Credential
```

### Verbose logs showing the problem

```powershell
Nothing logged.  

Connecting to {MicrosoftTeams}...✅
[1/21] Extracting [TeamsAudioConferencingPolicy] using {Credentials}...Partial Export file was saved at: C:\Users\dcaputo\AppData\Local\Temp\10fb7b8d-f5f3-479e-a7db-fc2b4fdaa01f.partial.ps1

This location is empty
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 11 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}

Name                           Value
----                           -----
PSVersion                      5.1.22621.3672
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.3672}
BuildVersion                   10.0.22621.3672
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by NikCharlebois** [comment]
Hey @dinocaputo is this still an ongoing issue, we unfortunately cannot replicate on our end.

**Comment by dinocaputo** [comment]
I ended up having to forcefully remove the entire M365 PS module and dependencies and then reinstall them.  After that the issue stopped. Thanks.
