### ISSUE TITLE
AADGroupOwnerConsentSettings is still a valid resource according to the website

### ISSUE THREAD

**Issue by adhodgson1** [microsoft/Microsoft365DSC#4778]
A page still exists for this resource even though the PR for this got reverted:
https://microsoft365dsc.com/resources/azure-ad/AADGroupOwnerConsentSettings/
Not sure whether this is true for other resoruces that got reverted also.

**Comment by NikCharlebois** [comment]
Thanks for highlighting this. We are looking into this.
