### ISSUE TITLE
Microsoft365DSC: Cannot bind parameter 'Certificate'.  Cannot convert value "CERTIFICATETHUMBPRINT" to type "Microsoft.TeamsCmdlets.Powershell.Connect.Utilities.CertificateParameter".

### ISSUE THREAD

**Issue by mheAC** [microsoft/Microsoft365DSC#4804]
### Description of the issue

Hi,

When I try to set the configuration with Start-DSCConfiguration -Path "C:\Users\mhe\Downloads\DSC\Test\M365TenantConfig -Wait -Verbose -Force", I get the following error: 

PowerShell DSC resource MSFT_TeamsAppPermissionPolicy  failed to execute Test-TargetResource functionality with error message: Cannot bind parameter 'Certificate'. 
Cannot convert value "CERTTHUMBPRINT" to type "Microsoft.TeamsCmdlets.Powershell.Connect.Utilities.CertificateParameter". Error: "Sequence 
contains no elements" 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

Thank you for your support and your performance.

### Microsoft 365 DSC Version

1.24.619.1

### Which workloads are affected

Teams, other

### The DSC configuration

```powershell
# Generated with Microsoft365DSC version 1.24.619.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
)

Configuration M365TenantConfig
{
    param (
    )

    $OrganizationName = $ConfigurationData.NonNodeData.OrganizationName

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.24.619.1'

    Node localhost
    {
        TeamsAppPermissionPolicy "TeamsAppPermissionPolicy-Global"
        {
            ApplicationId          = $ConfigurationData.NonNodeData.ApplicationId;
            CertificateThumbprint  = $ConfigurationData.NonNodeData.CertificateThumbprint;
            DefaultCatalogApps     = @();
            DefaultCatalogAppsType = "BlockedAppList";
            Ensure                 = "Present";
            GlobalCatalogApps      = @();
            GlobalCatalogAppsType  = "BlockedAppList";
            Identity               = "Global";
            PrivateCatalogApps     = @();
            PrivateCatalogAppsType = "BlockedAppList";
            TenantId               = $OrganizationName;
        }
    }
}

M365TenantConfig -ConfigurationData .\ConfigurationData.psd1
```

### Verbose logs showing the problem

```powershell
Start-DSCConfiguration -Path C:\Users\mhe\Downloads\DSC\Test\M365TenantConfig -Wait -Verbose -Force
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespace
Name' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer intune-w10 with user sid S-1-5-21-372150525-217125863-1866012005-500.
VERBOSE: The -Force option was specified with the Stop operation. The current configuration has been successfully cancelled.
VERBOSE: An LCM method call arrived from computer intune-w10 with user sid S-1-5-21-372150525-217125863-1866012005-500.
VERBOSE: [intune-w10]: LCM:  [ Start  Set      ]
VERBOSE: [intune-w10]: LCM:  [ Start  Resource ]  [[TeamsAppPermissionPolicy]TeamsAppPermissionPolicy-Global]
VERBOSE: [intune-w10]: LCM:  [ Start  Test     ]  [[TeamsAppPermissionPolicy]TeamsAppPermissionPolicy-Global]
VERBOSE: [intune-w10]:                            [[TeamsAppPermissionPolicy]TeamsAppPermissionPolicy-Global] Testing configuration of {Global}
VERBOSE: [intune-w10]: LCM:  [ End    Test     ]  [[TeamsAppPermissionPolicy]TeamsAppPermissionPolicy-Global]  in 29.8900 seconds.
PowerShell DSC resource MSFT_TeamsAppPermissionPolicy  failed to execute Test-TargetResource functionality with error message: Cannot bind parameter 'Certificate'. 
Cannot convert value "CERTTHUMBPRINT" to type "Microsoft.TeamsCmdlets.Powershell.Connect.Utilities.CertificateParameter". Error: "Sequence 
contains no elements" 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
VERBOSE: [intune-w10]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 31.098 seconds
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}

Key   : PSVersion
Value : 5.1.19041.4522
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.19041.4522
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by ricmestre** [comment]
The certificate must be installed in the LOCALMACHINE store, not on MY (your user account).

**Comment by mheAC** [comment]
> The certificate must be installed in the LOCALMACHINE store, not on MY (your user account).

I have installed the Certificate under Localmachine:
![image](https://github.com/microsoft/Microsoft365DSC/assets/5718517/1b4eabbe-f85f-4bec-8b73-1bb647dddaaf)

**Comment by ricmestre** [comment]
There's definitely a problem with that certificate, I can't see the key in the icon so the private key was either not imported or cannot be read for some reason.

**Comment by mheAC** [comment]
> There's definitely a problem with that certificate, I can't see the key in the icon so the private key was either not imported or cannot be read for some reason.

Then I will provide you with more informations:
Error:
![image](https://github.com/microsoft/Microsoft365DSC/assets/5718517/917234f4-e464-49f9-9167-6d47f754ee14)

ConfigurationData.ps1:
![image](https://github.com/microsoft/Microsoft365DSC/assets/5718517/4c459c52-36ca-4071-94f2-103ecf955d46)

localhost.mof:
![image](https://github.com/microsoft/Microsoft365DSC/assets/5718517/9013ebbd-68c6-4fe0-b3b2-0c8af7cf8bd7)

Certificate with Thumbprint:
![image](https://github.com/microsoft/Microsoft365DSC/assets/5718517/87dec3a1-d371-4ca8-8f39-ad0ab6a5fdb4)


I can export the settings with the existing certificate, but the import does not work.

**Comment by mheAC** [comment]
Problem solved after creating a new certificate. Thanks for your help.

**Comment by subhashvinjamuri** [comment]
@mheAC - I am facing similar issue for same TeamsAppPermisionPolicy. But my issue during Test-TargetResource is that - it is timing out. It seems to be that during Connect-MicrosoftTeams under MSFT_TeamsAppPermisionPolicy.psm1. 
However, just few lines above, I am doing an export command (as a sample to make sure connection is good )-that succeeds. Immediately after that, I am doing start-dsconfiguration against a MOF file. It keeps on timing out in the same PS session.
Just suspecting if my cert info is not getting passed on properly ? But all that is Microsoft code.
But if I specifically do connect-MicrosoftTeams with a cert thumbprint, that works in the same window. Only it timesout while running Start-DSCConfiguration.

Any suggestion on this, be appreciated.


Authentication methods specified:
- Service Principal with Certificate Thumbprint

Connecting to {MicrosoftTeams}...✅
[1/1] Extracting [TeamsUpgradeConfiguration] using {CertificateThumbprint}...✅
⌛ Export took {3 seconds} for {1 instances}
VERBOSE: removing the temporary extract from C:\Windows\Temp\Test-Teams\output\temp
VERBOSE: Applying configuration to the tenant bloombergcorpdev.onmicrosoft.com for component TeamsAppPermissionPolicy at :
C:\Windows\Temp\Test-Teams\Output\MOFFiles\TEAMS\dev\TeamsAppPermissionPolicy
VERBOSE: ...temporarily connecting to teams.....
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' =
MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer E07EFB576A09 with user sid S-1-5-93-2-1.
VERBOSE: [E07EFB576A09]: LCM:  [ Start  Set      ]
VERBOSE: [E07EFB576A09]: LCM:  [ Start  Resource ]  [[TeamsAppPermissionPolicy]TeamsAppPermissionPolicy-New Test app perm - dsc
23112::[BB_TeamsAppPermissionPolicy]AppPermPol]
VERBOSE: [E07EFB576A09]: LCM:  [ Start  Test     ]  [[TeamsAppPermissionPolicy]TeamsAppPermissionPolicy-New Test app perm - dsc
23112::[BB_TeamsAppPermissionPolicy]AppPermPol]
VERBOSE: [E07EFB576A09]:                            [[TeamsAppPermissionPolicy]TeamsAppPermissionPolicy-New Test app perm - dsc
23112::[BB_TeamsAppPermissionPolicy]AppPermPol] Testing configuration of {New Test app perm - dsc 23112}
One or more errors occurred.
    + CategoryInfo          : AuthenticationError: (:) [], CimException
    + FullyQualifiedErrorId : Connect-MicrosoftTeams,Microsoft.TeamsCmdlets.Powershell.Connect.ConnectMicrosoftTeams
    + PSComputerName        : localhost
