### ISSUE TITLE
EXOAuthenticationPolicy: Cannot change resources

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#4819]
### Description of the issue

After creating the policy it's not possible to change it, this is because ```Set-AuthenticationPolicy``` doesn't work and always fails with error message ```Object reference not set to an instance of an object```, the solution is to just remove the current policy and re-create it with the new settings.

### Microsoft 365 DSC Version

1.24.626.1

### Which workloads are affected

Exchange Online

### The DSC configuration

```powershell
EXOAuthenticationPolicy "EXOAuthenticationPolicy-EXOAuthenticationPolicy_1"
        {
            AllowBasicAuthActiveSync           = $False;
            AllowBasicAuthAutodiscover         = $False;
            AllowBasicAuthImap                 = $False;
            AllowBasicAuthMapi                 = $False;
            AllowBasicAuthOfflineAddressBook   = $False;
            AllowBasicAuthOutlookService       = $False;
            AllowBasicAuthPop                  = $False;
            AllowBasicAuthPowerShell           = $False;
            AllowBasicAuthReportingWebServices = $False;
            AllowBasicAuthRpc                  = $False;
            AllowBasicAuthSmtp                 = $False;
            AllowBasicAuthWebServices          = $False;
            Credential                         = $CredsCredential;
            Ensure                             = "Present";
            Identity                           = "EXOAuthenticationPolicy_1";
        }
```

### Verbose logs showing the problem

```powershell
Object reference not set to an instance of an object
```

### Environment Information + PowerShell Version

```powershell
Win11/PS5.1
```

**Comment by NikCharlebois** [comment]
Looping in some folks from the EXO Product Group. I would rather have us spend time fixing the Set- cmdlet than working on a workaround.

**Comment by ricmestre** [comment]
Myself included, but at least there's a workaround if it's something that it's not easily fixable.

**Comment by NikCharlebois** [comment]
Tagging @Swatyario for visibility
