### ISSUE TITLE
Intune: Assignment comparison not working for several resources

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#4830]
### Description of the issue

After upgrading to latest release I found out that at least these resources mentioned below now fail ```Test-DscConfiguration``` in my integration tests pipeline even if I'm still using the same blueprint as previous release where it was working. This seems due to changes in the way that comparisons are done in complex objects, this was changed to cope better with Intune Assignments property but clearly now creates other problems.

IntuneDeviceConfigurationCustomPolicyWindows10
IntuneDeviceConfigurationKioskPolicyWindows10
IntuneDeviceConfigurationNetworkBoundaryPolicyWindows10
IntuneDeviceConfigurationPolicyAndroidDeviceOwner
IntuneDeviceConfigurationPolicyMacOS
IntuneDeviceConfigurationVpnPolicyWindows10
IntuneDeviceEnrollmentStatusPageWindows10
IntuneSettingCatalogASRRulesPolicyWindows10
IntuneSettingCatalogCustomPolicyWindows10
IntuneWindowsAutopilotDeploymentProfileAzureADHybridJoined
IntuneWindowsAutopilotDeploymentProfileAzureADJoined

@FabienTschanz Looks like the tests I did that were successful the other day only succeeded by chance (e.g. this one is working ```IntuneDiskEncryptionMacOS```), the assignments are actually never compared as assignments or even as complex objects for that matter, that is because before even reaching that code the CIMInstance is split into ```$keys``` (M365DSCDRGUtil.psm1:L643) which are essentially the strings inside it, ```groupDisplayName```, ```groupId```, etc, so the object never matches that ```if``` block found in M365DSCDRGUtil.psm1:L683.

Another reason for failing is that not all resources in Intune return the property ```deviceAndAppManagementAssignmentFilterType``` when it's set to ```none``` so if you include it in the blueprint then it will complain that the objects are different. Same goes for returning ```deviceAndAppManagementAssignmentFilterId``` in an all 0's GUID, some that actually return the type as none not always return their Id so if you include it you will also have the same problem, or if you don't include it but the target resource in Intune expects it even if it's all 0's because the type was set to none. Important to note that this even changes every now and then, if I take an export today of the assignments of a certain Intune resource may be different of what it includes tomorrow, this is not a problem with the code but actually the API so the code must cope with this so that the same blueprint can be re-applied several times and ```Test-DscConfiguration``` always returns the same regardless.

And yet another problem, removing some comments to display the verbose statements found this on M365DSCDRGUtil.psm1:L741 ```Configuration drift - simple object key: dataType Source {#microsoft.graph.groupAssignmentTarget} Target {#microsoft.graph.exclusionGroupAssignmentTarget}``` which means it's trying to compare the assignment target with the exclusion target which shouldn't happen.

### Microsoft 365 DSC Version

1.24.626.1

### Which workloads are affected

other

### The DSC configuration

```powershell
IntuneWindowsAutopilotDeploymentProfileAzureADJoined "IntuneWindowsAutopilotDeploymentProfileAzureADJoined-IntuneWindowsAutopilotDeploymentProfileAzureADJoined_1"
        {
            Assignments                = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    groupDisplayName = 'DummyGroupExclude'
                    dataType = '#microsoft.graph.exclusionGroupAssignmentTarget'
                    groupId = '053dc89a-be83-411a-bad3-909904b7239e'
                    deviceAndAppManagementAssignmentFilterType = 'none'
                }
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    groupDisplayName = 'DummyGroupInclude'
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    groupId = 'b0b8fd3f-af2a-453b-be57-80182d599f02'
                    deviceAndAppManagementAssignmentFilterType = 'none'
                }
            );
            Credential                 = $Credscredential;
            Description                = "Windows Autopilot_Azure AD Join_Standard";
            DeviceNameTemplate         = "CMD%SERIAL%";
            DeviceType                 = "windowsPc";
            DisplayName                = "IntuneWindowsAutopilotDeploymentProfileAzureADJoined_1";
            EnableWhiteGlove           = $False;
            Ensure                     = "Present";
            ExtractHardwareHash        = $True;
            Id                         = "ef518b1f-fd62-4069-aca8-5344823b3f6d";
            Language                   = "os-default";
            OutOfBoxExperienceSettings = MSFT_MicrosoftGraphoutOfBoxExperienceSettings1{
                HideEULA = $True
                HideEscapeLink = $True
                HidePrivacySettings = $True
                DeviceUsageType = 'singleUser'
                SkipKeyboardSelectionPage = $True
                UserType = 'standard'
            };
        }
```

### Verbose logs showing the problem

```powershell
Test-DSCConfiguration returns false
```

### Environment Information + PowerShell Version

```powershell
Win11/PS5.1
```

**Comment by ricmestre** [comment]
@FabienTschanz After reverting back to 1.24.619.1 and removing property ```groupDisplayName``` from all resources that now support it (in 1.24.626.1) I was able to run all my integration tests without issues and the tests succeeded which clearly points to some issue in https://github.com/microsoft/Microsoft365DSC/pull/4767/.

EDIT: Note, the example I gave above for ```IntuneWindowsAutopilotDeploymentProfileAzureADJoined``` already supported ```groupDisplayName``` before and doesn't have issues with 1.24.619.1 as-is, if I update to 1.24.626.1 then ```Test-DscConfiguration``` returns false.

**Comment by FabienTschanz** [comment]
@ricmestre Thanks for the mentioning, I will have a look at that on Friday.
