### ISSUE TITLE
Bug: DSC cannot retrieve properly an instance of AADAplication when softly deleted. It is creating a new app each time as per timer schedule of LCM in Apply and Monitor

### ISSUE THREAD

**Issue by ghost** [microsoft/Microsoft365DSC#4840]
### Description of the issue

Bug: DSC cannot retrieve properly an instance of AADAplication when softly deleted. It is creating a new app each time as per timer schedule of LCM in Apply and Monitor mode.

![image](https://github.com/microsoft/Microsoft365DSC/assets/148461680/147f00fa-85ea-48d0-a4a5-e40e9c454218)

<img width="956" alt="image" src="https://github.com/microsoft/Microsoft365DSC/assets/148461680/6898bea5-194c-4174-9222-894ef92d859e">

### Microsoft 365 DSC Version

1.24.522.1

### Which workloads are affected

Azure Active Directory (Entra ID)

### The DSC configuration

```powershell
Configuration Mode: Apply and Monitor
```

### Verbose logs showing the problem

```powershell
{"time": "2024-07-03T15:02:54.679+02:00", "type": "verbose", "message": "[WIN-O3J3DORALCB]:                            [[AADApplication]AADApplication-Test MKA app] Trying to retrieve existing deleted Applications from soft delete by Id {c7a73cc6-bc86-4002-be71-a8790dd57cc9}."},
  {"time": "2024-07-03T15:02:59.261+02:00", "type": "verbose", "message": "[WIN-O3J3DORALCB]:                            [[AADApplication]AADApplication-Test MKA app] Trying to retrieve existing deleted Applications from soft delete by DisplayName {Test MKA app}."},
  {"time": "2024-07-03T15:02:59.570+02:00", "type": "verbose", "message": "[WIN-O3J3DORALCB]:                            [[AADApplication]AADApplication-Test MKA app] Multiple instances of a deleted application with name {Test MKA app} wehre found. Creating a new instance since we can't determine what instance to restore."},
```

**Comment by NikCharlebois** [comment]
Can you please share the config associated with this. I am not able to reproduce on my end. Thanks
