### ISSUE TITLE
The term 'Get-MgProfile' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by MarkLaa** [microsoft/Microsoft365DSC#4896]
Hello Everybody!
So i am making a configuration in azure devops based on this document: (https://aka.ms/m365dscwhitepaper).  I have the same problem in azure and in powershell, witch is: 
##[error]PowerShell DSC resource MSFT_EXOOrganizationConfig  failed to execute Test-TargetResource functionality with error mess
age: The term 'Get-MgProfile' is not recognized as the name of a cmdlet, function, script file, or operable program. Ch
eck the spelling of the name, or if a path was included, verify that the path is correct and try again. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
I read somewhere that Get-MgProfile is only in Microsoft.Graph.Beta but i am really not sure how i can fix this problem because i did not see anywhere in the documentation that i need the beta version for it to work. 
The full script is downloaded from here: https://aka.ms/M365DSCWhitepaper/Scripts . I have only changed the necessary ones ie tenant id etc.
Thank you for your help in advance!

**Comment by FabienTschanz** [comment]
The command `Get-MgProfile` is not available anymore. Microsoft365DSC installs the necessary PowerShell modules per default (with `Update-M365DSCModule` in an elevated PowerShell 5 session), so I am wondering what version of the Microsoft365DSC module you are running. Can you update to the latest version using `Update-M365DSCModule` and then try again?

If that doesn't work, please provide the output of `Get-Module Microsoft365DSC -ListAvailable` as well as `$PSVersionTable`.

**Comment by FabienTschanz** [comment]
@MarkLaa Any news on your issue? Or can it be closed?

**Comment by MarkLaa** [comment]
Hello, im sorry for the late reply. The issue can be closed as i updated to the newest version and it went away. 
Thank you!

**Comment by FabienTschanz** [comment]
@MarkLaa I personally can‘t close it, so it would be nice if you could do that. There should be a button at the bottom of this issue.
