### ISSUE TITLE
EXOMailTips/EXOOrganizationConfig: Runtime Exception When Using Set-OrganizationConfig

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#4905]
### Description of the issue

Something changed in the EXO backend and everytime ```Set-OrganizationConfig``` is used now it gives the following error message below which means ```EXOMailTips``` and ```EXOOrganizationConfig``` cannot be used for making changes to those resources.

```powershell
Unable to find type [uint].
At C:\Users\REDACTED\AppData\Local\Temp\tmpEXO_twwg4psu.sv4\tmpEXO_twwg4psu.sv4.psm1:53499 char:5
+     [uint]
+     ~~~~~~
+ CategoryInfo          : InvalidOperation: (uint:TypeName) [], RuntimeException
+ FullyQualifiedErrorId : TypeNotFound
```

### Microsoft 365 DSC Version

1.24.717.1

### Which workloads are affected

Exchange Online

### The DSC configuration

```powershell
N/A
```

### Verbose logs showing the problem

```powershell
Unable to find type [uint].
At C:\Users\REDACTED\AppData\Local\Temp\tmpEXO_twwg4psu.sv4\tmpEXO_twwg4psu.sv4.psm1:53499 char:5
+     [uint]
+     ~~~~~~
+ CategoryInfo          : InvalidOperation: (uint:TypeName) [], RuntimeException
+ FullyQualifiedErrorId : TypeNotFound
```

### Environment Information + PowerShell Version

```powershell
Win11 / PS5.1
```

**Comment by 2PintChristianN** [comment]
Confirming that this happens on default PS version https://learn.microsoft.com/en-us/answers/questions/1822123/runtime-exception-when-using-set-organizationconfi

Newer versions of PS seems to be fine.

**Comment by ricmestre** [comment]
Seems to be working now
