### ISSUE TITLE
Complete list of Graph API permissions needed to run/collect Intune configurations

### ISSUE THREAD

**Issue by gokulan-ey** [microsoft/Microsoft365DSC#4915]

**Comment by FabienTschanz** [comment]
@gokulan-ey For the Intune configurations, there are only a handful of permissions necessary. If you want to also update the configurations, these are the ones you will need (most likely): 

DeviceManagementApps.ReadWrite.All
DeviceManagementConfiguration.ReadWrite.All
DeviceManagementManagedDevices.ReadWrite.All
DeviceManagementRBAC.ReadWrite.All
DeviceManagementServiceConfig.ReadWrite.All
Organization.Read.All

You can also use the cmdlet `Get-M365DSCCompiledPermissionList` to get the permissions.

**Comment by FabienTschanz** [comment]
@gokulan-ey Does the answer help you? Are there questions left or can you close the issue?
