### ISSUE TITLE
AADTenantDetail

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#493]

**Comment by paweber8** [comment]
I would take that

**Comment by ThorstenLoeschmann** [comment]
You got it

**Comment by NikCharlebois** [comment]
@paweber8 any updates on this? If not, can we put it back in the To Do bucket for someone else to pick it up? Thanks

**Comment by paweber8** [comment]
@NikCharlebois currently i do not find enough time to really drive it. So yes, let us put it back.

**Comment by Timsto** [comment]
i would take this @ThorstenLoeschmann
