### ISSUE TITLE
All Conditional Access policies fail to be migrated with non-terminating errors during Start-DscConfiguration

### ISSUE THREAD

**Issue by rick-engle** [microsoft/Microsoft365DSC#4960]
### Description of the issue

**After having a successful collection of my AAD objects and compiling into a MOF, when the Start-DscConfiguration runs every conditional access policy fails with the errors which don't provide any useful information as to why.   I don't know how much of the logging you would like but here is a chunk from one of the failed CA policies:
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-Require MFA for B2B portal a
ccess] conditions={applications={excludeApplications=()
includeApplications=(cc15fd57-2c6c-4117-a88c-83b1d56b4bbe)}
authenticationFlows={transferMethods=}
clientAppTypes=(all)
platforms=$null
signInRiskLevels=()
userRiskLevels=()
users={excludeGroups=()
excludeRoles=()
excludeUsers=()
includeGroups=()
includeRoles=()
includeUsers=(GuestsOrExternalUsers)}}
displayName=Require MFA for B2B portal access
grantControls={builtInControls=(mfa)
operator=OR}
sessionControls=$null
state=enabledForReportingButNotEnforced
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-Require MFA for B2B portal a
ccess] POST https://graph.microsoft.com/beta/identity/conditionalAccess/policies with 570-byte payload
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-Require MFA for B2B portal a
ccess] received 552-byte response of content type application/json**
----------------------------------------------------------------------------------------------------------------------
**Set-Targetresource: Failed creating new policy
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-TargetResource
    + PSComputerName        : localhost**
----------------------------------------------------------------------------------------------------------------------

VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-Require MFA for B2B portal a
ccess] Set-Targetresource: Finished processing Policy Require MFA for B2B portal access
VERBOSE: [ULTRASBOOK6]: LCM:  [ End    Set      ]  [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-Require MFA for B2B portal a
ccess]  in 1.5150 seconds.

----------------------------------------------------------------------------------------------------------------------
**The PowerShell DSC resource '[AADConditionalAccessPolicy]AADConditionalAccessPolicy-Require MFA for B2B portal access' with 
SourceInfo 'C:\Users\ricke.REDMOND\Documents\files\My Documents\Security and Compliance\Azure 
AD\scripts\Microsoft365DSC_AAD\M365TenantConfig.ps1::75::9::AADConditionalAccessPolicy' threw one or more non-terminating errors 
while running the Set-TargetResource functionality. These errors are logged to the ETW channel called 
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost**
---------------------------------------------------------------------------------------------------------------------- 
VERBOSE: [ULTRASBOOK6]: LCM:  [ Start  Resource ]  [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot]
VERBOSE: [ULTRASBOOK6]: LCM:  [ Start  Test     ]  [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot]
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot] Testing configura
tion of AzureAD CA Policies
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot] Getting configura
tion of AzureAD Conditional Access Policy
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot] PolicyID was spec
ified
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot] Couldn't find exi
sting policy by ID {d34f688d-d28b-477e-9f49-fc42a906bd01}
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot] No existing Polic
y with name {MFA Pilot} were found
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot] Current Values: A
pplicationEnforcedRestrictionsIsEnabled=False
AuthenticationContexts=()
BuiltInControls=(mfa,compliantDevice,domainJoinedDevice)
ClientAppTypes=(exchangeActiveSync,browser,other)
CloudAppSecurityIsEnabled=False
CloudAppSecurityType=
Credential=***
CustomAuthenticationFactors=()
DeviceFilterRule=
DisplayName=MFA Pilot
Ensure=Absent
ExcludeApplications=()
ExcludeExternalTenantsMembers=()
ExcludeExternalTenantsMembershipKind=
ExcludeGroups=()
ExcludeLocations=(AllTrusted)
ExcludePlatforms=()
ExcludeRoles=()
ExcludeUsers=()
GrantControlOperator=AND
Id=d34f688d-d28b-477e-9f49-fc42a906bd01
IncludeApplications=(6202c268-9265-496f-9bc6-2b857ed3f76c,2634dd23-5e5a-431c-81ca-11710d9079f4,13afac0c-7703-4e0d-8ec4-0b0c706b9466,905
fcf26-4eb7-48a0-9ff0-8dcc7194b5ba)
IncludeExternalTenantsMembers=()
IncludeExternalTenantsMembershipKind=
IncludeGroups=(MFA Test Users Pilot)
IncludeLocations=(All)
IncludePlatforms=(windows,windowsPhone)
IncludeRoles=()
IncludeUserActions=()
IncludeUsers=()
PersistentBrowserIsEnabled=False
PersistentBrowserMode=
SignInFrequencyIsEnabled=False
SignInFrequencyType=
SignInRiskLevels=(medium)
State=enabledForReportingButNotEnforced
TransferMethods=
UserRiskLevels=(high)
Verbose=True

Can you spot anything wrong?  I don't understand why all CA policy writes to the target tenant fail.

Thanks,
 Rick

### Microsoft 365 DSC Version

1.24.731.1

### Which workloads are affected

Azure Active Directory (Entra ID)

### The DSC configuration

```powershell
Start-DscConfiguration -Path "C:\MySCPath\Microsoft365DSC_AAD\M365TenantConfig" -Wait -Verbose -Force
```

### Verbose logs showing the problem

```powershell
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-Require MFA for B2B portal a
ccess] conditions={applications={excludeApplications=()
includeApplications=(cc15fd57-2c6c-4117-a88c-83b1d56b4bbe)}
authenticationFlows={transferMethods=}
clientAppTypes=(all)
platforms=$null
signInRiskLevels=()
userRiskLevels=()
users={excludeGroups=()
excludeRoles=()
excludeUsers=()
includeGroups=()
includeRoles=()
includeUsers=(GuestsOrExternalUsers)}}
displayName=Require MFA for B2B portal access
grantControls={builtInControls=(mfa)
operator=OR}
sessionControls=$null
state=enabledForReportingButNotEnforced
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-Require MFA for B2B portal a
ccess] POST https://graph.microsoft.com/beta/identity/conditionalAccess/policies with 570-byte payload
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-Require MFA for B2B portal a
ccess] received 552-byte response of content type application/json
Set-Targetresource: Failed creating new policy
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-TargetResource
    + PSComputerName        : localhost
 
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-Require MFA for B2B portal a
ccess] Set-Targetresource: Finished processing Policy Require MFA for B2B portal access
VERBOSE: [ULTRASBOOK6]: LCM:  [ End    Set      ]  [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-Require MFA for B2B portal a
ccess]  in 1.5150 seconds.
The PowerShell DSC resource '[AADConditionalAccessPolicy]AADConditionalAccessPolicy-Require MFA for B2B portal access' with 
SourceInfo 'C:\Users\ricke.REDMOND\Documents\files\My Documents\Security and Compliance\Azure 
AD\scripts\Microsoft365DSC_AAD\M365TenantConfig.ps1::75::9::AADConditionalAccessPolicy' threw one or more non-terminating errors 
while running the Set-TargetResource functionality. These errors are logged to the ETW channel called 
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
VERBOSE: [ULTRASBOOK6]: LCM:  [ Start  Resource ]  [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot]
VERBOSE: [ULTRASBOOK6]: LCM:  [ Start  Test     ]  [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot]
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot] Testing configura
tion of AzureAD CA Policies
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot] Getting configura
tion of AzureAD Conditional Access Policy
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot] PolicyID was spec
ified
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot] Couldn't find exi
sting policy by ID {d34f688d-d28b-477e-9f49-fc42a906bd01}
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot] No existing Polic
y with name {MFA Pilot} were found
VERBOSE: [ULTRASBOOK6]:                            [[AADConditionalAccessPolicy]AADConditionalAccessPolicy-MFA Pilot] Current Values: A
pplicationEnforcedRestrictionsIsEnabled=False
AuthenticationContexts=()
BuiltInControls=(mfa,compliantDevice,domainJoinedDevice)
ClientAppTypes=(exchangeActiveSync,browser,other)
CloudAppSecurityIsEnabled=False
CloudAppSecurityType=
Credential=***
CustomAuthenticationFactors=()
DeviceFilterRule=
DisplayName=MFA Pilot
Ensure=Absent
ExcludeApplications=()
ExcludeExternalTenantsMembers=()
ExcludeExternalTenantsMembershipKind=
ExcludeGroups=()
ExcludeLocations=(AllTrusted)
ExcludePlatforms=()
ExcludeRoles=()
ExcludeUsers=()
GrantControlOperator=AND
Id=d34f688d-d28b-477e-9f49-fc42a906bd01
IncludeApplications=(6202c268-9265-496f-9bc6-2b857ed3f76c,2634dd23-5e5a-431c-81ca-11710d9079f4,13afac0c-7703-4e0d-8ec4-0b0c706b9466,905
fcf26-4eb7-48a0-9ff0-8dcc7194b5ba)
IncludeExternalTenantsMembers=()
IncludeExternalTenantsMembershipKind=
IncludeGroups=(MFA Test Users Pilot)
IncludeLocations=(All)
IncludePlatforms=(windows,windowsPhone)
IncludeRoles=()
IncludeUserActions=()
IncludeUsers=()
PersistentBrowserIsEnabled=False
PersistentBrowserMode=
SignInFrequencyIsEnabled=False
SignInFrequencyType=
SignInRiskLevels=(medium)
State=enabledForReportingButNotEnforced
TransferMethods=
UserRiskLevels=(high)
Verbose=True
```

**Comment by CiscoZarama** [comment]
I am having the same issue. When updating the Conditional Access Policies I receive and error and this is confirmed in the Event Log. I can find no additional information on what is causing the issue.

Microsoft 365DSC Version: 1.24.731.1

AADConditionalAccessPolicy' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
Message ID: NonTerminatingErrorFromProvider
Error Category: 7
Error Code: 1
Error Type: MI

**Comment by CiscoZarama** [comment]
I can confirm that removing the TransferMethods= "" in the mof file; does in fact correct the issue. Hoping this gets corrected moving forward.

**Comment by rick-engle** [comment]
@CiscoZarama, what a great discovery you had!  How did you figure out that those extra TransferMethods= "" lines in the .MOF were the problem?

**Comment by CiscoZarama** [comment]
@rick-engle , I read the problem in https://github.com/microsoft/Microsoft365DSC/issues/4725 and verified it impacted my code. I now remove the line via code in the MOF file prior to Start-DscConfiguration. Hoping this gets addressed moving forward.
