### ISSUE TITLE
What are the permitted values of [AADConditionalAccessPolicy]: TransferMethods ?

### ISSUE THREAD

**Issue by GeldHades27355** [microsoft/Microsoft365DSC#4961]
Hey folks, QQ: does anyone know what the permitted values are for "TransferMethods"?

The GUI has "Device code flow" and "Authentication transfer" ON | OFF on it, but that doesn't mean those are the exact strings.

And if someone knows, should we update the documentation accordingly?

**Comment by FabienTschanz** [comment]
@GeldHades27355 According to the [Graph API documentation](https://learn.microsoft.com/en-us/graph/api/resources/conditionalaccessauthenticationflows?view=graph-rest-beta), the following values are possible: 

*  none
* deviceCodeFlow
* authenticationTransfer
* unknownFutureValue

I would definitely consider adding them to the documentation, except for `unknownFutureValue`. This way, we also get syntax completion in the editor and prevent any invalid input. 

Edit: The expected input seems to be `$null` for when it's disabled, or the value itself, and if both Device code flow and Authentication transfer are selected, then both values, separated by a comma (`deviceCodeFlow,authenticationTransfer`). So I guess we can add that to the documentation, but not in the way that syntax highlighting would work.
