### ISSUE TITLE
[New-M365DSCReportFromConfiguration] Error on AADAuthenticationMethodPolicy* resources

### ISSUE THREAD

**Issue by Kierow** [microsoft/Microsoft365DSC#5064]
### Description of the issue

Hello, 

I'm not able to generate HTML/JSON/MD reports (using New-M365DSCReportFromConfigurationfrom) from several AADAuthenticationMethodPolicyXXX resources.

It seems that the error comes from ConvertFrom-CIMInstanceToHashtable	function in DSCParser --> "Invoke-Expression -Command $scriptBlock | Out-Null"  (DSCParser.psm1: line 351) 
In fact, $scriptBlock doesn't contain the necessary information because the below part of code return $null in $CIMClassObject;
"
$CIMClassObject = Get-CimClass -ClassName $CimInstanceName `
-Namespace 'ROOT/Microsoft/Windows/DesiredStateConfiguration' `
-ErrorAction SilentlyContinue
"

Here is the stacktrace:
Statcktrace:
at ConvertFrom-CIMInstanceToHashtable	 C:\Users\user\Documents\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1: line 351	
at ConvertFrom-CIMInstanceToHashtable	 C:\Users\user\Documents\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1: line 250
at ConvertTo-DSCObject	                 C:\Users\user\Documents\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1: line 673
at Initialize-M365DSCReporting	         C:\Users\user\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.24.828.1\Modules\M365DSCReport.psm1: line 1924
at New-M365DSCReportFromConfiguration	 C:\Users\user\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.24.828.1\Modules\M365DSCReport.psm1: line 615
at Export-M365TenantConfiguration	 C:\Users\user\Documents\WindowsPowerShell\Modules\Microsoft365DSCTools\Microsoft365DSCTools.psm1: line 2885

Impacted resources:
AADAuthenticationMethodPolicy
AADAuthenticationMethodPolicyAuthenticator
AADAuthenticationMethodPolicyFido2
AADAuthenticationMethodPolicySms
AADAuthenticationMethodPolicySoftware
AADAuthenticationMethodPolicyTemporary
AADAuthenticationMethodPolicyVoice
AADAuthenticationMethodPolicyX509

Do you have an idea on how to solve this issue?

Thanks in advance, I hope I could provide enough information. Let me know if you need further information.

### Microsoft 365 DSC Version

1.24.904.1 and 1.24.828.1

### Which workloads are affected

Azure Active Directory (Entra ID)

### The DSC configuration

```powershell
# Generated with Microsoft365DSC version 1.24.828.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
)

Configuration DEV-M365Tenant-AAD-AADAuthenticationMethodPolicy
{
    param (
    )

    $OrganizationName = $ConfigurationData.NonNodeData.OrganizationName

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.24.828.1'

    Node localhost
    {

        # For information on how to use this resource, please refer to:
        # https://github.com/microsoft/Microsoft365DSC/wiki/AADAuthenticationMethodPolicy
        AADAuthenticationMethodPolicy "AADAuthenticationMethodPolicy-Authentication Methods Policy"
        {
            ApplicationId               = $ConfigurationData.NonNodeData.ApplicationId;
            CertificateThumbprint       = $ConfigurationData.NonNodeData.CertificateThumbprint;
            Description                 = "The tenant-wide policy that controls which authentication methods are allowed in the tenant, authentication method registration requirements, and self-service password reset settings";
            DisplayName                 = "Authentication Methods Policy";
            Ensure                      = "Present";
            Id                          = "authenticationMethodsPolicy";
            PolicyMigrationState        = "preMigration";
            PolicyVersion               = "1.5";
            RegistrationEnforcement     = MSFT_MicrosoftGraphregistrationEnforcement{

                AuthenticationMethodsRegistrationCampaign = MSFT_MicrosoftGraphAuthenticationMethodsRegistrationCampaign{
                    SnoozeDurationInDays = 1


                    IncludeTargets = @(
                        MSFT_MicrosoftGraphAuthenticationMethodsRegistrationCampaignIncludeTarget{
                            TargetedAuthenticationMethod = 'microsoftAuthenticator'
                            TargetType = 'group'
                            Id = 'all_users'
                        }
                    )
                    State = 'default'
                }
            
            };
            SystemCredentialPreferences = MSFT_MicrosoftGraphsystemCredentialPreferences{


                IncludeTargets = @(
                    MSFT_AADAuthenticationMethodPolicyIncludeTarget{
                        Id = 'all_users'
                        TargetType = 'group'
                    }
                )
                State = 'default'
            };
            TenantId                    = $OrganizationName;
        }
    }
}

DEV-M365Tenant-AAD-AADAuthenticationMethodPolicy -ConfigurationData .\ConfigurationData.psd1
```

**Comment by FabienTschanz** [comment]
Can you update the Microsoft365DSC module using `Install-Module Microsoft365DSC -Force` in an elevated Windows PowerShell session and then also run `Update-M365DSCModule`? 

After that, please restart the session and run the report generation in an elevated session again.

**Comment by Kierow** [comment]
Hello Fabien,

Thanks for your quick answer. I just updated the modules to the last version using the commands you mentioned and unfortunately, the issue is persisting.

Here is more information ( --> the issue is still the same):

ErrorMessage:
Message: At line:1 char:63
 $typeStaticMethods = [] | gm - ...
Missing type name after '['.

 []::TryParse($subExpressi ...
Missing type name after '['.


CategoryInfo:
Category   : ParserError
Activity   : Invoke-Expression
Reason     : ParseException
TargetName :
TargetType :

Exception:
Type: System.Management.Automation.ParseException


InvocationInfo:

MyCommand             : Invoke-Expression
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 351
OffsetInLine          : 25
HistoryId             : 1
ScriptName            : C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1
Line                  :                         Invoke-Expression -Command $scriptBlock | Out-Null

PositionMessage       : At C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1:351 char:25
 Invoke-Expression -Command $scriptBlock | Out-N ...

PSScriptRoot          : C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules
PSCommandPath         : C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1
InvocationName        : Invoke-Expression
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition :


Stack traces:
* Script:
at ConvertFrom-CIMInstanceToHashtable, C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1: line 351
at ConvertFrom-CIMInstanceToHashtable, C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1: line 250
at ConvertTo-DSCObject, C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1: line 673
at Initialize-M365DSCReporting, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.904.1\Modules\M365DSCReport.psm1: line 1924
at New-M365DSCReportFromConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.904.1\Modules\M365DSCReport.psm1: line 615

* Exception:
at System.Management.Automation.ScriptBlock.Create(Parser parser, String fileName, String fileContents)
at System.Management.Automation.ScriptBlock.Create(ExecutionContext context, String script)
at Microsoft.PowerShell.Commands.InvokeExpressionCommand.ProcessRecord()
at System.Management.Automation.CommandProcessor.ProcessRecord()

Thanks for your help !

Edit: Formatting :)

**Comment by FabienTschanz** [comment]
That's the same issue some other folks have encountered when running the report generation. And honestly, I have no clue why 😢 I'll get back to you.

**Comment by Kierow** [comment]
Hi Fabien, 

Thanks for the quick answer and for the information, so we have other issues opened on that topic if I understand well ? (If yes, can we link the issues?)
Do you reproduce the issue on your side?


I add the .ps1 file generated using the last M365DSC version:

### The DSC configuration

```powershell
# Generated with Microsoft365DSC version 1.24.904.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
)

Configuration DEV-M365Tenant-AAD-AADAuthenticationMethodPolicy
{
    param (
    )

    $OrganizationName = $ConfigurationData.NonNodeData.OrganizationName

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.24.904.1'

    Node localhost
    {

        # For information on how to use this resource, please refer to:
        # https://github.com/microsoft/Microsoft365DSC/wiki/AADAuthenticationMethodPolicy
        AADAuthenticationMethodPolicy "AADAuthenticationMethodPolicy-Authentication Methods Policy"
        {
            ApplicationId               = $ConfigurationData.NonNodeData.ApplicationId;
            CertificateThumbprint       = $ConfigurationData.NonNodeData.CertificateThumbprint;
            Description                 = "The tenant-wide policy that controls which authentication methods are allowed in the tenant, authentication method registration requirements, and self-service password reset settings";
            DisplayName                 = "Authentication Methods Policy";
            Ensure                      = "Present";
            Id                          = "authenticationMethodsPolicy";
            PolicyMigrationState        = "preMigration";
            PolicyVersion               = "1.5";
            RegistrationEnforcement     = MSFT_MicrosoftGraphregistrationEnforcement{
                AuthenticationMethodsRegistrationCampaign = MSFT_MicrosoftGraphAuthenticationMethodsRegistrationCampaign{
                    SnoozeDurationInDays = 1
                    IncludeTargets = @(
                        MSFT_MicrosoftGraphAuthenticationMethodsRegistrationCampaignIncludeTarget{
                            TargetedAuthenticationMethod = 'microsoftAuthenticator'
                            TargetType = 'group'
                            Id = 'all_users'
                        }
                    )
                    State = 'default'
                }
            
            };
            SystemCredentialPreferences = MSFT_MicrosoftGraphsystemCredentialPreferences{
                IncludeTargets = @(
                    MSFT_AADAuthenticationMethodPolicyIncludeTarget{
                        Id = 'all_users'
                        TargetType = 'group'
                    }
                )
                State = 'default'
            };
            TenantId                    = $OrganizationName;
        }
    }
}

DEV-M365Tenant-AAD-AADAuthenticationMethodPolicy -ConfigurationData .\ConfigurationData.psd1
```

Many thanks for your help ! ;)

**Comment by FabienTschanz** [comment]
Don't know how I can link them, but one is #4779, on which I am working on since a longer time, but the latest things seem to be happening because of another reason. At the start, we had the same issues, they somehow sometimes resolved or came back...
Another one is  #4991, that one resolved itself. Maybe you can find try the steps from there?
And the last one is #4644, though I'm not sure if we are talking from the same things there. 

I'm currently not able to check your configuration, I will update you if I have news (since I'm investigating that stuff in my free time).

**Comment by FabienTschanz** [comment]
@Kierow Just tested your configuration, and I do get the same error just as you did. I will investigate, sounds exactly like #4644. 

Edit: There is already an open issue in the DSCParser repository... https://github.com/microsoft/DSCParser/issues/47.

**Comment by Kierow** [comment]
@FabienTschanz Sorry, I was in business trip yesterday so I couldn't test anything more. I agree, it sounds like https://github.com/microsoft/DSCParser/issues/47, https://github.com/microsoft/Microsoft365DSC/issues/4644 
And thanks for your test. :) 

I try to tag @NikCharlebois to see if he can have a look on that matter (as he is the author of DSCParser and therefore has a deep understanding of the topic) and maybe can help us.

**Comment by FabienTschanz** [comment]
@Kierow By the way, are you running PowerShell 7 oder Windows PowerShell 5.1? I think I found the issue, but I'm wrapping some things around it to make sure we absolutely have it. If I have a working example, can I give you a code snippet which you need to put at a specific place?

**Comment by Kierow** [comment]
@FabienTschanz , I'm using Windows PowerShell 5.1 (as per my understanding, PowerShell 7 is not fully supported at this time for M365DSC).

Good news if you find a lead ! You can give me the code snippet and I will perform the test. :)

**Comment by FabienTschanz** [comment]
Thanks a lot. So, in C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1, please do the following: 

* On line 153, change `ErrorAction = 'SiltentlyContinue` to `ErrorAction = 'Stop'`
* On line 176, please add the following codesnippet above te other if clause: 
```powershell
if ($_.CategoryInfo.Category -eq 'PermissionDenied')
{
    throw "The CIM class $CimInstanceName is not available or could not be instantiated. Please run this command with administrative privileges."
}
 ```

Now, if you restart the PowerShell session and run the cmdlet again, it should throw the above error message. However, if you run the cmdlet in an elevated session, it should work. 

Edit: PowerShell 7 is almost fully supported, I do a lot of my testing in it. If you want, you can try it as well and give feedback if you find an issue.

**Comment by Kierow** [comment]
@FabienTschanz Unfortunately, the report is still not generated on my side. However, I do have a different error.
_Note_: For the moment I only tried with WindowsPowerShell 5.1 as Admin (I did not try with PS7)

Please find below the error information:
```
Message: Not found
  Origin:  (runspace ID: 00000000-0000-0000-0000-000000000000)
CategoryInfo:
        Category   : ObjectNotFound
        Activity   : Get-CimClass
        Reason     : CimException
        TargetName : ROOT/Microsoft/Windows/DesiredStateConfiguration:MSFT_MicrosoftGraphregistrationEnforcement
        TargetType : String


Exception:
        Type: Microsoft.Management.Infrastructure.CimException


InvocationInfo:

        MyCommand             : Get-CimClass
        BoundParameters       : {}
        UnboundArguments      : {}
        ScriptLineNumber      : 129
        OffsetInLine          : 35
        HistoryId             : 1
        ScriptName            : C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1
        Line                  :                 $CIMClassObject = Get-CimClass -ClassName $CimInstanceName `

        PositionMessage       : At C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1:129 char:35
                                + ...          $CIMClassObject = Get-CimClass -ClassName $CimInstanceName `
                                +                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        PSScriptRoot          : C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules
        PSCommandPath         : C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1
        InvocationName        : Get-CimClass
        PipelineLength        : 0
        PipelinePosition      : 0
        ExpectingInput        : False
        CommandOrigin         : Internal
        DisplayScriptPosition :

Stack traces:
  * Script:
        at ConvertFrom-CIMInstanceToHashtable, C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1: line 129
        at ConvertTo-DSCObject, C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1: line 677
        at Initialize-M365DSCReporting, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.904.1\Modules\M365DSCReport.psm1: line 1924
        at New-M365DSCReportFromConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.904.1\Modules\M365DSCReport.psm1: line 615
  * Exception:
        at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(OperationCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult, String errorMessage, InstanceHandle errorDetailsHandle)
```

As requested, I did perform the modifications you asked me (see attached image)
![image](https://github.com/user-attachments/assets/d90b8447-e2dd-46fc-90f3-5b652ed571bc)

Thank your for you help.

**Comment by Kierow** [comment]
@FabienTschanz Unfortunately, the report is still not generated on my side.  The error message seems to be the same.
Note: For the moment I only tried with WindowsPowerShell 5.1 as Admin (I did not try with PS7)
![image](https://github.com/user-attachments/assets/69dbe44a-a3d2-4d98-b95a-e13a0a507cb1)


Please find below the error information:
```
Message: At line:1 char:63
+ ...                                        $typeStaticMethods = [] | gm - ...
+                                                                  ~
Missing type name after '['.

At line:4 char:46
+                                             []::TryParse($subExpressi ...
+                                              ~
Missing type name after '['.

CategoryInfo:
        Category   : ParserError
        Activity   : Invoke-Expression
        Reason     : ParseException
        TargetName :
        TargetType :

Exception:
        Type: System.Management.Automation.ParseException


InvocationInfo:

        MyCommand             : Invoke-Expression
        BoundParameters       : {}
        UnboundArguments      : {}
        ScriptLineNumber      : 355
        OffsetInLine          : 25
        HistoryId             : 11
        ScriptName            : C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1
        Line                  :                         Invoke-Expression -Command $scriptBlock | Out-Null

        PositionMessage       : At C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1:355 char:25
                                + ...                       Invoke-Expression -Command $scriptBlock | Out-N ...
                                +                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        PSScriptRoot          : C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules
        PSCommandPath         : C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1
        InvocationName        : Invoke-Expression
        PipelineLength        : 0
        PipelinePosition      : 0
        ExpectingInput        : False
        CommandOrigin         : Internal
        DisplayScriptPosition :

Stack traces:
  * Script:
        at ConvertFrom-CIMInstanceToHashtable, C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1: line 355
        at ConvertFrom-CIMInstanceToHashtable, C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1: line 254
        at ConvertTo-DSCObject, C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1: line 677
        at Initialize-M365DSCReporting, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.904.1\Modules\M365DSCReport.psm1: line 1924
        at New-M365DSCReportFromConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.904.1\Modules\M365DSCReport.psm1: line 615
  * Exception:
        at System.Management.Automation.ScriptBlock.Create(Parser parser, String fileName, String fileContents)
        at System.Management.Automation.ScriptBlock.Create(ExecutionContext context, String script)
        at Microsoft.PowerShell.Commands.InvokeExpressionCommand.ProcessRecord()
        at System.Management.Automation.CommandProcessor.ProcessRecord()
        
```
As requested, I did perform the modifications you asked me (see attached image)
![image](https://github.com/user-attachments/assets/596b6aa3-1eb9-4421-9c20-0b51213d44cd)


Thank your for you help.

**Comment by ricmestre** [comment]
Missed running ```winrm quickconfig```?

**Comment by FabienTschanz** [comment]
@Kierow Could you try it once without administrative privileges? What's the output then?

* Then, on line 131, please change the `SilentlyContinue` to `Continue`
* And add the command `Write-Verbose $CIMInstanceName -Verbose` on a new line after the comment on line 128

It should look like the following. This way, we get more error messages and the specific CIM instance name it can't find. 
```
# Get the CimClass associated with the current CIMInstanceName
Write-Verbose $CIMInstanceName -Verbose
$CIMClassObject = Get-CimClass -ClassName $CIMInstanceName `
                            -Namespace 'ROOT/Microsoft/Windows/DesiredStateConfiguration' `
                           -ErrorAction Continue
```

**Comment by Kierow** [comment]
@ricmestre i'm gonna try and let you know 
_Note_: I never had to use this command before and M365DSC was running smoothly on a previous version (without using that command) before. But maybe that's a new requirement and i'm just not aware :)

**Comment by ricmestre** [comment]
It's a requirement since DSCParser v2, on v1 it worked without it but now it doesn't unfortunately.

**Comment by FabienTschanz** [comment]
@ricmestre I see, `Invoke-DscResource` is inferred by DSCParser because Microsoft365DSC uses cmdlets from PSDesiredStateConfiguration v1.0 like `Get-DscLocalConfigurationManager`, which in term forces `Invoke-DscResource` to connect to the WSMan provider... 🫨 That escalated quickly.

**Comment by Kierow** [comment]
@FabienTschanz  @ricmestre I confirm that the command "Winrm quickconfig" helped ! However I do not really understand why, if you have more information, i'm interested :)

Thanks a lot for the great help guys ! I'm now able to make html/md/json report for these resources
_Note_: It seems that the HTML report randomly fail, I will take a look on that.

To finish, it would be great if this point could be added somewhere in the documentation. It's an important point and it would prevent people from disturbing you with this kind of issue :)

**Comment by FabienTschanz** [comment]
@Kierow I will check and add a documentation update where necessary. Thanks for confirming that it now works. 

> I see, `Invoke-DscResource` is inferred by DSCParser because Microsoft365DSC uses cmdlets from PSDesiredStateConfiguration v1.0 like `Get-DscLocalConfigurationManager`, which in term forces `Invoke-DscResource` to connect to the WSMan provider... 🫨 That escalated quickly.

This is why that is necessary. A bit technical stuff if you're interested: Microsoft365DSC uses the Local Configuration Manager (LCM) as the orchestrator for applying, checking and retrieving the configurations. This is done by sending the configuration via the WSMAN provider (Web Service Management) to the LCM. The WSMAN provider itself retrieves its input from the Windows Remote Management (WinRM), which is enabled by using `winrm quickconfig` (or `Enable-PSRemoting -Force -SkipNetworkProfileCheck`).

**Comment by Kierow** [comment]
@FabienTschanz Thanks for the great explanation and the time you took. It makes sense now :)

I dug a little bit more and it seems that the real problem was coming from this part of code `Invoke-DscResource @InvokeParams | Out-Null"` -> DSCParser.psm1:158 (--> but the error was nullified and then an error was triggered later in the code...)
Error message:
```
"The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests. Consult the logs and 
documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the 
destination to analyze and configure the WinRM service: "winrm quickconfig".
At C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1:158 char:25
+                         Invoke-DscResource @InvokeParams | Out-Null
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ConnectionError: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : HRESULT 0x80338012
    + PSComputerName        : localhost"
```

It matches with the solution and with your explanation. :)

**Comment by FabienTschanz** [comment]
Awesome, thank you for the digging. Swallowing exceptions isn't always great, we might need to change that. Thanks a bunch 👍

**Comment by Kierow** [comment]
You're welcome, can I close the issue?

**Comment by FabienTschanz** [comment]
Yes, you can. From my side it's ok.
