### ISSUE TITLE
Compare-M365DSCConfigurations: Different configurations produce no differences

### ISSUE THREAD

**Issue by nick-waterhouse** [microsoft/Microsoft365DSC#5065]
### Description of the issue

When attempting to compare two configurations that are known to be different, I received output that indicated that the two are identical.

Seeing verbose error messages similar to other issues (array indexing, `Invoke-Expression` etc), I ran `winrm quickconfig`, set my network to be private rather than public, and performed the comparison again. Lots of these appeared in the console:

```
Invoke-Expression : At line:1 char:63
+ ...                                        $typeStaticMethods = [] | gm - ...
+                                                                  ~
Missing type name after '['.
At line:4 char:46
+                                             []::TryParse($subExpressi ...
+                                              ~
Missing type name after '['.
At C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1:351 char:25
+ ...                       Invoke-Expression -Command $scriptBlock | Out-N ...
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : MissingTypename,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

Running `$Error` afterward I noted some extra information:

```
Importing module MSFT_AADApplication failed with error - File C:\Program
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.904.1\DscResources\MSFT_AADApplication\MSFT_AADApplication.psm1 cannot be loaded. The file C:\Program
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.904.1\DscResources\MSFT_AADApplication\MSFT_AADApplication.psm1 is not digitally signed. You cannot run this script on
the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ImportModuleFailed
    + PSComputerName        : localhost
```
What is the suggested workaround here? `Get-ExecutionPolicy` gives me `RemoteSigned`. Would it be safe to try something like `Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process` to give scripts like `MSFT_AADApplication.psm1` a chance to load?

### Microsoft 365 DSC Version

V1.24.904.1

### Which workloads are affected

other

### Verbose logs showing the problem

```powershell
Get-CimClass : Not found
At C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1:160 char:43
+ ...          $CIMClassObject = Get-CimClass -ClassName $CimInstanceName `
+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ROOT/Microsoft/...ationPermission:String) [Get-CimClass], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041002,Microsoft.Management.Infrastructure.CimCmdlets.GetCimClassCommand

Importing module MSFT_AADApplication failed with error - File C:\Program
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.904.1\DscResources\MSFT_AADApplication\MSFT_AADApplication.psm1 cannot be loaded. The file C:\Program
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.904.1\DscResources\MSFT_AADApplication\MSFT_AADApplication.psm1 is not digitally signed. You cannot run this script on
the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ImportModuleFailed
    + PSComputerName        : localhost
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22000.1.amd64fre.co_release.210604-1628
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, en-US}
```

**Comment by FabienTschanz** [comment]
@nick-waterhouse `Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass` should be enough, no reason for unrestricted. 
Could you also share a minimal reproducible configuration example? Thank you.

**Comment by nick-waterhouse** [comment]
I ran the following command:

`$delta = Compare-M365DSCConfigurations -Source "example-config-source.ps1" -Destination "example-config-dest.ps1"`

Which produced the output contained in [console-output.txt](https://github.com/user-attachments/files/17067376/console-output.txt).

Executing `$Error` afterward produced output containing lots of these:

```Get-CimClass : Not found
At C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1:160 char:43
+ ...          $CIMClassObject = Get-CimClass -ClassName $CimInstanceName `
+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ROOT/Microsoft/...ationPermission:String) [Get-CimClass], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041002,Microsoft.Management.Infrastructure.CimCmdlets.GetCimClassCommand

Importing module MSFT_AADApplication failed with error - File C:\Program
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.904.1\DscResources\MSFT_AADApplication\MSFT_AADApplication.psm1 cannot be loaded. The file C:\Program
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.904.1\DscResources\MSFT_AADApplication\MSFT_AADApplication.psm1 is not digitally signed. You cannot run this script on
the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ImportModuleFailed
    + PSComputerName        : localhost
```

Interestingly, if I execute `Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass` then perform the comparison, I still get the same errors regarding the digital signature.

**Example files:**

[example-config-source.ps1.txt](https://github.com/user-attachments/files/17067116/example-config-source.ps1.txt)
[example-config-dest.ps1.txt](https://github.com/user-attachments/files/17067117/example-config-dest.ps1.txt)

**Comment by FabienTschanz** [comment]
@nick-waterhouse I did the comparison with a fix that I pushed in https://github.com/microsoft/DSCParser/pull/53. This means that you need to run the command in an elevated PowerShell session. Can you please try that?

**Comment by nick-waterhouse** [comment]
@FabienTschanz The above output is all from an elevated PowerShell 5.1 session.

If you have pushed a fix to the DSCParser, would it be simpler to wait until Microsoft365DSC is updated to include the fixed parser? Conversely, is it possible to apply the change to the version of DSCParser I have installed locally?

**Comment by FabienTschanz** [comment]
Hmm strange. What you can do is patch the file from C:\Program Files\WindowsPowerShell\Modules\DSCParser\2.0.0.8\Modules\DSCParser.psm1 with the content of the file that's in the PR I opened at the DSCParser repository. 

I'm unsure why you receive the error regarding digitally signed. What happens if you update the ExecutionPolicy to Unrestricted  for the entire system, not only the current process?

Edit: If you go to the file properties of e.g. MSFT_AADApplication.psm1, is there any indication that it was downloaded from the web, e.g. with a note about unblocking the file?

**Comment by nick-waterhouse** [comment]
@FabienTschanz  It looks like setting the `ExecutionPolicy` to `Unrestricted` and patching the `DSCParser.psm1` file did the trick. Doing so produced differences as follows:

```
{
    "Delta":  {
                  "ResourceName":  "AADApplication",
                  "Key":  "DisplayName",
                  "KeyValue":  "TestAuthWebAPIFromTemplate1",
                  "Properties":  [
                                     {
                                         "ValueInDestination":  "Present",
                                         "ParameterName":  "_IsInConfiguration_",
                                         "ValueInSource":  "Absent"
                                     }
                                 ],
                  "ResourceInstanceName":  "AADApplication-Test2"
              }
}
```
I got there by executing `$delta = Compare-M365DSCConfigurations -Source "example-config-source.ps1" -Destination "example-config-dest.ps1"` then  `@{ Delta = $delta } | ConvertTo-Json -Depth 100 | Add-Content -Path "Diffs-temp.json"`.

This output looks good to me and matches my expectations of roughly what should happen given the input.

I checked the file properties of the `MSFT_AADApplication.psm1` file and there was no indication it was downloaded from the web.

Like I say, I did indeed patch the `DSCParser.psm1` file with your update and explored what was going on. In the `catch` block that starts on line 178, I whacked in a quick `Write-Warning "$_"` to get the exception in the console. The outcome was the same as before, referencing the digital signature as the reason for not being able to load the `MSFT_AADApplication.psm1` script. This of course went away when I set the `ExecutionPolicy` to `Unrestricted`.

**Comment by FabienTschanz** [comment]
Perfect, glad to hear you got it working. Still not sure why the ExecutionPolicy had to be set to Unrestricted, „it works on my machine“. Maybe it‘s an organization config. 

Anyway, if that‘s a solution you‘re okay with, do you agree on closing the issue?

**Comment by nick-waterhouse** [comment]
@FabienTschanz Yep, I think we can close this one. Many thanks for your help.

**Comment by FabienTschanz** [comment]
I guess there are currently no mods looking over it, do you mind closing it yourself @nick-waterhouse? There's a button at the bottom of this issue with which you can close it. Thank you 👍
