### ISSUE TITLE
AADGroup - problem getting unit-tests for licensing to work as expected

### ISSUE THREAD

**Issue by salbeck-sit** [microsoft/Microsoft365DSC#5067]
### Description of the issue

I'm in the process of updating the unit-test for AADGroup and have run into a strange issue.

Here's the Pester Context:

Context -Name "The Group exists and has been assigned the correct license. Values are already in the desired state" -Fixture {
            BeforeAll {
                $testParams = @{
                    DisplayName        = 'DSCGroup'
                    ID                 = '12345-12345-12345-12345'
                    Description        = 'Microsoft DSC Group'
                    SecurityEnabled    = $True
                    MailEnabled        = $false
                    GroupTypes         = @()
                    MailNickname       = 'M365DSC'
                    AssignedLicenses   = @(
                        (New-CimInstance -ClassName MSFT_AADGroupLicense -Property @{
                            DisabledPlans  = @()
                            SkuId          = 'AAD_PREMIUM_P2'
                        } -ClientOnly)
                    )
                    Ensure             = 'Present'
                    Credential         = $Credential
                }
                It 'Should xxxx' {
                   (...)
               }
      }
      
The issue is that when I run the tests using Invoke-TestHarness -DscTestsPath xxx -IgnoreCodeCoverage I get the following error:

[-] Context DSC Resource 'AADGroup'.The Group exists and has been assigned the correct license. Values are already in the desired state failed
 ArgumentException: Could not infer CimType from the provided .NET object.
 at <ScriptBlock>, C:\Users\P-B038744\Documents\Github\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADGroup.Tests.ps1:695
  
 The above is in and from a tests-file that hasn't (yet) been uploaded to one of my forked branches.

### Microsoft 365 DSC Version

DEV

### Which workloads are affected

Azure Active Directory (Entra ID)

### Environment Information + PowerShell Version

```powershell
I run Pester 5.4.0 in WPS 5.1 on Windows 2016 Server
```

**Comment by salbeck-sit** [comment]
Uploaded to new branch, tests in question located here: https://github.com/salbeck-sit/Microsoft365DSC/blob/AADGroup/Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADGroup.Tests.ps1

**Comment by FabienTschanz** [comment]
@salbeck-sit 
You have to change the `AssignedLicenses` property to the following: 

```powershell
AssignedLicenses   = [CimInstance[]]@(
    (New-CimInstance -ClassName MSFT_AADGroupLicense -Property @{
        DisabledPlans  = $null
        SkuId          = 'AAD_PREMIUM_P2'
    } -ClientOnly)
)
```

PowerShell can't somehow infere the type, so you gotta help him with assigning the `New-CimInstance` to a CIM instance array.

**Comment by salbeck-sit** [comment]
thanks @FabienTschanz - I've tried it (also found a similar suggestion in another thread related to DRG) but it changes nothing , the branch is updated.
I've only changed the first context that deals with licenses to hopefully spot any differences but no luck

**Comment by salbeck-sit** [comment]
Here's the output from Pester;

Running all Microsoft365DSC Unit Tests

Starting discovery in 1 files.
Discovery found 39 tests in 111ms.
Running tests.
[-] Context DSC Resource 'AADGroup'.The Group does not exist and must be created and assigned a license. Values are NOT in the desired state failed
 ArgumentException: Could not infer CimType from the provided .NET object.
 at <ScriptBlock>, C:\Users\P-B038744\Documents\Github\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADGroup.Tests.ps1:638
[-] Context DSC Resource 'AADGroup'.The Group exists and has been assigned the correct license. Values are already in the desired state failed
 ArgumentException: Could not infer CimType from the provided .NET object.
 at <ScriptBlock>, C:\Users\P-B038744\Documents\Github\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADGroup.Tests.ps1:695
[-] Context DSC Resource 'AADGroup'.The Group exists and is not assigned a license but it should be. Values are NOT in the desired state failed
 ArgumentException: Could not infer CimType from the provided .NET object.
 at <ScriptBlock>, C:\Users\P-B038744\Documents\Github\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADGroup.Tests.ps1:765
Tests completed in 2.72s
(...)

**Comment by FabienTschanz** [comment]
Got it. Did you run an export or an import / update / delete of the resource? If not, this might be why. The reason why it's failing is because `Get-CimClass -ClassName MSFT_AADGroupLicense -Namespace 'ROOT/Microsoft/Windows/DesiredStateConfiguration'` reports nothing back. For the test to work, that CIM class must be registered. 

I'm not quite sure how that's done, but I do think running `ConvertTo-DscObject -Path D:\M365TenantConfig.ps1` should be enough to make it work (in an elevated Windows PowerShell session). Could you please try that and check if the output of the `Get-CimClass` changes anything?

**Comment by FabienTschanz** [comment]
@salbeck-sit I got it figured out. The reason you're receiving the error is because in the manifest, the property `DisabledPlans` is defined as a string array `[string[]]`, but the definition in your test `@()` is an array of type object `[object[]]`. You have to do it like the following: 

```powershell
AssignedLicenses   = [CimInstance[]]@(
    (New-CimInstance -ClassName MSFT_AADGroupLicense -Property @{
        DisabledPlans  = [string[]]@() #<-- Updated type definition
        SkuId          = 'AAD_PREMIUM_P2'
     } -ClientOnly)
)
```

Like that, it will work. Yes, that is very tricky, but it does make sense. PowerShell almost doesn't care about the type because it almost always uses `System.Object` as the base type, but CIM classes and their .NET definitions certainly are not. This explains why you have to cast the array to the specific underlying .NET type.

**Comment by salbeck-sit** [comment]
@FabienTschanz that did the trick. I did play around with casting a little but didn't try the above.
I can add that '[CimInstance[]]' is no longer necessary - apparently the error was caused by the inability to match types.
The error also goes away if I omit DisabledPlans entirely - which makes sense in this case as a null/empty value means 'include everything'.
