### ISSUE TITLE
Capture DSC Traffic via Fiddler

### ISSUE THREAD

**Issue by raghuram-t** [microsoft/Microsoft365DSC#5099]
### Description of the issue
I am trying to clone Exchange Online Transport rules from one M365 tenant to another tenant.
I have exported the transport rules (near to 200) from our PROD tenant and trying to import that into my DEV tenant.
https://microsoft365dsc.com/user-guide/get-started/cloning-tenants/
I have selected to export only TransportRules component.
Using Credentials (not service principal for authentication)
The activity fails with the error : _app has been throttled by AAD due to too many requests_

PS CMD:
_Start-DscConfiguration -Path D:\DSC\PROD\Exch_Transport\M365TenantConfig\ -Wait -Verbose -Force_

### Microsoft 365 DSC Version
1.24.904.1

### Which workloads are affected
Exchange Online

### PowerShell Version
Same behavior in both Windows PS and PowerShell7
Windows PS: 5.1.17763.6292
PS 7: 7.4.5
System: Windows Server 2019 Datacenter

### Verbose logs showing the problem
Error Message:
_PowerShell DSC resource MSFT_EXOTransportRule  failed to execute Test-TargetResource functionality with error message: _Your app has been throttled by AAD due to too many requests_. To avoid this, cache your
tokens see https://aka.ms/msal-net-throttling.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost_

Error Snapshot:
![image](https://github.com/user-attachments/assets/f08de766-dfc5-43fb-9c30-d274a245ff7f)

The microsoft [document](https://aka.ms/msal-net-throttling) says the response header would have some information around when we can retry.

### Goal:
Figure out...
1. why am I being throttled in the first place? I assume, the DSC team would have included the logic to cache the tokens already?
2. Determine the retry interval so that I can define the LCM configuration retry interval accordingly?

I thought, a Fiddler capture would allow me to view the request/response headers > Get to know the retry-interval as per MS throttling document > Tweak the LCM interval accordingly.
I did set the proxy in the PowerShell.
For instance, the requests made in PowerShell via Invoke-WebRequest are captured in Fiddler trace but the DSC traffic from LCM is not captured in Fiddler. Not sure if we have to set Proxy somewhere else in order for the DSC traffic to be captured via Fiddler ?

A similar issue around throttling was logged in GitHub but not sure how was this resolved? (Using Service Principal ?)
https://github.com/microsoft/Microsoft365DSC/issues/4780

**Comment by FabienTschanz** [comment]
@raghuram-t Did you start Fiddler as an administrator? And maybe you need to set the current system proxy using `netsh winhttp` to make the system context (in which the LCM is running) aware of the proxy. I think the proxy value would be `127.0.0.1:8888`, but I'm not sure, you would need to double check that.

**Comment by raghuram-t** [comment]
> @raghuram-t Did you start Fiddler as an administrator? And maybe you need to set the current system proxy using `netsh winhttp` to make the system context (in which the LCM is running) aware of the proxy. I think the proxy value would be `127.0.0.1:8888`, but I'm not sure, you would need to double check that.

No, I am not running Fiddler as administrator.
However, Fiddler is able to capture the other requests from Powershell but not the M365 DSC traffic triggered by LCM.
Here is the snapshot of Powershell proxy config:
![image](https://github.com/user-attachments/assets/8af40eb0-0351-44a6-a1c5-b02fbef8c80a)

**Comment by FabienTschanz** [comment]
@raghuram-t I got it working. You can clear the winhttp proxy settings, you don't need them. 
You have to start the registry as the SYSTEM user, e.g. using PSEXEC from the Sysinternals tools (`psexec -i -s powershell` from an elevated prompt, then type `regedit`). Then, add the following two registry entries under `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings`: 

* Name `ProxyEnable`, DWORD, Value `1`
* Name `ProxyServer`, REG_SZ (String), Value `127.0.0.1:8888`

After that, either restart your system or run the following code in the PSEXEC window: 

```powershell
function refresh-system() {
$signature = @"
[DllImport("wininet.dll", SetLastError = true, CharSet=CharSet.Auto)]
public static extern bool InternetSetOption(IntPtr hInternet, int dwOption, IntPtr lpBuffer, int dwBufferLength);
"@
    $INTERNET_OPTION_SETTINGS_CHANGED   = 39
    $INTERNET_OPTION_REFRESH            = 37
    $type = Add-Type -MemberDefinition $signature -Name wininet -Namespace pinvoke -PassThru
    $a = $type::InternetSetOption(0, $INTERNET_OPTION_SETTINGS_CHANGED, 0, 0)
    $b = $type::InternetSetOption(0, $INTERNET_OPTION_REFRESH, 0, 0)
    return $a -and $b
}
refresh-system
```

Copied from https://forums.powershell.org/t/set-dsclocalconfigurationmanager-and-proxy-awareness/10242/18

**Comment by raghuram-t** [comment]
> @raghuram-t I got it working. You can clear the winhttp proxy settings, you don't need them. You have to start the registry as the SYSTEM user, e.g. using PSEXEC from the Sysinternals tools (`psexec -i -s powershell` from an elevated prompt, then type `regedit`). Then, add the following two registry entries under `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings`:
> 
> * Name `ProxyEnable`, DWORD, Value `1`
> * Name `ProxyServer`, REG_SZ (String), Value `127.0.0.1:8888`
> 
> After that, either restart your system or run the following code in the PSEXEC window:
> 
> ```powershell
> function refresh-system() {
> $signature = @"
> [DllImport("wininet.dll", SetLastError = true, CharSet=CharSet.Auto)]
> public static extern bool InternetSetOption(IntPtr hInternet, int dwOption, IntPtr lpBuffer, int dwBufferLength);
> "@
>     $INTERNET_OPTION_SETTINGS_CHANGED   = 39
>     $INTERNET_OPTION_REFRESH            = 37
>     $type = Add-Type -MemberDefinition $signature -Name wininet -Namespace pinvoke -PassThru
>     $a = $type::InternetSetOption(0, $INTERNET_OPTION_SETTINGS_CHANGED, 0, 0)
>     $b = $type::InternetSetOption(0, $INTERNET_OPTION_REFRESH, 0, 0)
>     return $a -and $b
> }
> refresh-system
> ```
> 
> Copied from https://forums.powershell.org/t/set-dsclocalconfigurationmanager-and-proxy-awareness/10242/18

Thank you, I will try this in a day or two.

**Comment by FabienTschanz** [comment]
@raghuram-t How did it go? Any news on this?

**Comment by raghuram-t** [comment]
> [@raghuram-t](https://github.com/raghuram-t) How did it go? Any news on this?

I tried on my office machine a week ago and It did not work.
I thought, it could be failing due to corporate proxy and their auto reset mechanisms..

So, I spin up a VM on my personal machine and tried the same.
It did work.
The trick of setting the proxy in the 'system' user account - Worked.

Also, we should not look for PowerShell generated traffic alone and instead we should look for 'everything' in Fiddler. 
So, we should 'not' forget to remove Filters in the Fiddler (if there are any).

Have attached a screenshot from Fiddler (just for reference to any others who might try the same in the future)...
![Image](https://github.com/user-attachments/assets/ad54aea7-fd0c-43cc-9eba-dca42be4247c)


Thank you @FabienTschanz so much for your assistance/guidance on this.
Also, my apologies for the delayed response.

**Comment by FabienTschanz** [comment]
Awesome, glad you got it working. Can you please close the issue if that's ok for you? Thank you.
