### ISSUE TITLE
AADConditionalAccessPolicy

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#510]

**Comment by ejazr83** [comment]
I am very keen to test this module out as we want to monitor and control changes to AAD Conditional Access policies using Microsft365DSC

Do you have some specs or code that we can review or provide some testing feedback against? Any idea of timelines on when this would be available?

Thanks,

**Comment by SebastianGoers** [comment]
I'd be really keen to test this out and implement CA policies using DSC. I have a desperate need to automate the creation of CA policies across tenants.

**Comment by NikCharlebois** [comment]
@peterabele is leading this right now. The dev branch is located here:
https://github.com/peterabele/Microsoft365DSC/tree/AADConditionalAccessPolicy

**Comment by SebastianGoers** [comment]
@peterabele, could you please help me understand what the current status of the development is? We are really keen to test the CA policy support in DSC.

**Comment by peterabele** [comment]
@SebastianGoers, the CA module is in quite good shape. It is already tested in production, no issues so far. 
I have 2 things remaining: 
1. change all the logging calls to event log instead of file based
2. write the M365DSC unit test
I'll probably finish with these by end of next week.

**Comment by SebastianGoers** [comment]
@peterabele , this sounds really promising. I'll give it a try and test your module once its available in the dev branch.
