### ISSUE TITLE
[IntuneAntivirusPolicyWindows10SettingCatalog] AccessTokens not a valid member message when creating the mof file

### ISSUE THREAD

**Issue by ericoevering** [microsoft/Microsoft365DSC#5121]
### Description of the issue

taking a snapshot and running the powershell to create the MOF file works fine for all Intune Componens except : IntuneAntivirusPolicyWindows10SettingCatalog Taking the snapshot works but when running the powershell file I get an error:

The member 'AccessTokens' is not valid. Valid members are
'allowarchivescanning', 'allowbehaviormonitoring', 'allowcloudprotection', 'allowdatagramprocessingonwinserver', 'allow
emailscanning', 'allowfullscanonmappednetworkdrives', 'allowfullscanremovabledrivescanning', 'allowintrusionpreventions
ystem', 'allowioavprotection', 'allownetworkprotectiondownlevel', 'allowonaccessprotection', 'allowrealtimemonitoring',
 'allowscanningnetworkfiles', 'allowscriptscanning', 'allowuseruiaccess', 'ApplicationId', 'ApplicationSecret', 'archiv
emaxdepth', 'archivemaxsize', 'Assignments', 'avgcpuloadfactor', 'CertificateThumbprint', 'checkforsignaturesbeforerunn
ingscan', 'cloudblocklevel', 'cloudextendedtimeout', 'companyname', 'Credential', 'daystoretaincleanedmalware', 'Depend
sOn', 'Description', 'disableaccountprotectionui', 'disableappbrowserui', 'disablecatchupfullscan', 'disablecatchupquic
kscan', 'disablecleartpmbutton', 'disabledevicesecurityui', 'disablednsovertcpparsing', 'disableenhancednotifications',
 'disablefamilyui', 'disablehealthui', 'disablehttpparsing', 'disablelocaladminmerge', 'disablenetworkui', 'DisableSshP
arsing', 'disabletlsparsing', 'disabletpmfirmwareupdatewarning', 'disablevirusui', 'DisplayName', 'email', 'enablecusto
mizedtoasts', 'enableinappcustomization', 'enablelowcpupriority', 'enablenetworkprotection', 'engineupdateschannel', 'E
nsure', 'excludedextensions', 'excludedpaths', 'excludedprocesses', 'hideransomwaredatarecovery', 'hidewindowssecurityn
otificationareacontrol', 'highseveritythreats', 'Identity', 'lowseveritythreats', 'ManagedIdentity', 'meteredconnection
updates', 'moderateseveritythreats', 'phone', 'platformupdateschannel', 'PsDscRunAsCredential', 'puaprotection', 'rando
mizescheduletasktimes', 'realtimescandirection', 'scanparameter', 'schedulequickscantime', 'schedulerrandomizationtime'
, 'schedulescanday', 'schedulescantime', 'securityintelligenceupdateschannel', 'severethreats', 'signatureupdatefallbac
korder', 'signatureupdatefilesharessources', 'signatureupdateinterval', 'submitsamplesconsent', 'tamperprotection', 'te
mplateId', 'TenantId', 'url'.

Here an example of the ps1 file:

# Generated with Microsoft365DSC version 1.24.904.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
)

Configuration IntuneAntivirusPolicyWindows10SettingCatalog-CUST
{
    param (
    )

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.24.904.1'

    Node localhost
    {
        IntuneAntivirusPolicyWindows10SettingCatalog "IntuneAntivirusPolicyWindows10SettingCatalog-Microsoft Defender Antivirus"
        {
            AccessTokens                        = $ConfigurationData.NonNodeData.AccessTokens;
            AllowArchiveScanning                = "1";
            AllowBehaviorMonitoring             = "1";
            AllowCloudProtection                = "1";
            AllowEmailScanning                  = "1";
            AllowFullScanOnMappedNetworkDrives  = "1";
            AllowFullScanRemovableDriveScanning = "1";
            AllowIntrusionPreventionSystem      = "1";
            AllowIOAVProtection                 = "1";
            AllowRealtimeMonitoring             = "1";
            AllowScanningNetworkFiles           = "1";
            AllowScriptScanning                 = "1";
            Assignments                         = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    groupDisplayName = 'All devices'
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    dataType = '#microsoft.graph.allDevicesAssignmentTarget'
                }
            );
            Description                         = "";
            DisplayName                         = "Microsoft Defender Antivirus";
            Ensure                              = "Present";
            Identity                            = "3b0048ae-9ff3-418a-a233-4ac70b03270c";
            templateId                          = "804339ad-1553-4478-a742-138fb5807418_1";
            TenantId                            = $ConfigurationData.NonNodeData.TenantId;
        }
    }
}

anybody who can point me in the right direction on how to troubleshoot this?

### Microsoft 365 DSC Version

1.24.904.1

### Which workloads are affected

Intune

**Comment by FabienTschanz** [comment]
@ericoevering Just opened a Pull Request with a fix for your issue. I hope that will be released with the next version of Microsoft365DSC.

**Comment by ericoevering** [comment]
i did your change locally and works like a charm thank you for the quick response.
