### ISSUE TITLE
TeamsUpgradeSettings DSC module feature to apply tenant wide policies

### ISSUE THREAD

**Issue by viksrini** [microsoft/Microsoft365DSC#5174]
### Description of the issue

The current version of TeamsUpgradeSettings module does not allow enforcing tenant wide policies. We are asking to implement this switch in the module or a method to apply policies globally. This is currently possible using [PowerShell](https://learn.microsoft.com/en-us/powershell/module/teams/grant-csteamsupgradepolicy?view=teams-ps).

`Grant-CsTeamsUpgradePolicy -PolicyName <policyname> -Global`

### Microsoft 365 DSC Version

1.24.1002.1 

### Which workloads are affected

Teams

### The DSC configuration

https://microsoft365dsc.com/resources/teams/TeamsUpgradePolicy/

The policy currently does not allow to apply a tenant wide upgrade policy. The users property is always a required field for any policy . As per PowerShell documentation, if we need to apply a global policy, we need to leave 'Identity' blank. This does not work for this module since Identity is a mandatory parameter. Also, it enumerates $users for each identity and throws an exception when identity is blank.

Grant-CsTeamsUpgradePolicy -PolicyName SfBOnly -Global
"To grant a policy to all users in the org (except any that have an explicit policy assigned), omit the identity parameter. If you do not specify the -Global parameter, you will be prompted to confirm the operation."

**Comment by NikCharlebois** [comment]
We will modify the logic as follow. If the Users property only contains '*', then we will call 

Grant-CsTeamsUpgradePolicy -PolicyName $Policy -Global
