### ISSUE TITLE
TeamsMeetingPolicy: missing AllowExternalNonTrustedMeetingChat

### ISSUE THREAD

**Issue by MarkLakatos** [microsoft/Microsoft365DSC#5176]
### Description of the issue

Hello everyone!
At the moment I am configurint the TeamsMeetingPolicy and i realized it is missing AllowExternalNonTrustedMeetingChat. It is a CIS standard so i think it would be a great addition for it.
Thank you:)

### Microsoft 365 DSC Version

1.24.828.1

### Which workloads are affected

Teams

**Comment by ykuijs** [comment]
Working on a PR
