### ISSUE TITLE
Random guid in M365TenantConfig.ps1 configuration nodes

### ISSUE THREAD

**Issue by jackpoz** [microsoft/Microsoft365DSC#5237]
### Description of the issue

After upgrading from 1.24.904.1 to 1.24.1016.1 , the command `Export-M365DSCConfiguration` creates a M365TenantConfig.ps1 file with random guids like `ODSettings "ODSettings-bb1c0c77-b591-4e45-840c-bd697f52ce40"` or `SPOHomeSite "SPOHomeSite-4906cb72-3067-4985-9a11-2852f36f7fd8"` instead of the previous values like `ODSettings "ODSettings"` or `SPOHomeSite "SPOHomeSite"` .

These guids are random at every run. This causes the command `Compare-M365DSCConfigurations` to report everything different as there is a mismatch between the guids.

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

SharePoint Online

### The DSC configuration

Export-M365DSCConfiguration -Components @("ODSettings", "SPOSharingSettings", "SPOAccessControlSettings", "SPOBrowserIdleSignout", "SPOHomeSite", "SPOOrgAssetsLibrary", "SPOTenantCdnEnabled", "SPOTenantCdnPolicy", "SPOTenantSettings")

Compare-M365DSCConfigurations with 2 different runs.

**Comment by ricmestre** [comment]
Noticed this too, this must be fixed

**Comment by NikCharlebois** [comment]
I understand this is a topic that came up a few times in the past. In my opinion, we should look at making the logic change in the Compare-M365DSCConfiguration cmdlets to ignore the "Identity" of the block as this is not a data point that should be compared. I will spend time looking into this further today.
