### ISSUE TITLE
TeamsProtectionPolicy: New resource proposal

### ISSUE THREAD

**Issue by MarkLakatos** [microsoft/Microsoft365DSC#5296]
### Description
With TeamsProtectionPolicy the user can modify Microsoft Teams protection policies. This can be reached through Exchange Online.
This is the link for the Powershell version: https://learn.microsoft.com/en-us/powershell/module/exchange/set-teamsprotectionpolicy?view=exchange-ps

### Proposed properties
Set-TeamsProtectionPolicy
   [-Identity] <TeamsProtectionPolicyIdParameter>
   [-AdminDisplayName <String>] # The AdminDisplayName parameter specifies a description for the policy
   [-HighConfidencePhishQuarantineTag <String>] # The HighConfidencePhishQuarantineTag parameter specifies the quarantine policy that's used for 
   messages that are quarantined as high confidence phishing by ZAP for Teams.
   [-MalwareQuarantineTag <String>] # The MalwareQuarantineTag parameter specifies the quarantine policy that's used for messages that are 
   quarantined as malware by ZAP for Teams.
   [-ZapEnabled <Boolean>] # The ZapEnabled parameter specifies whether to enable zero-hour auto purge (ZAP) for malware and high confidence 
   phishing messages in Teams messages.

I think it would be a great addition for the Teams assets. 
Thank you! :)

**Comment by ykuijs** [comment]
Working on it!
