### ISSUE TITLE
AADRoleDefinition - ENHANCEMENT - CustomRole Permissions Assignment

### ISSUE THREAD

**Issue by pangjaa** [microsoft/Microsoft365DSC#5313]
### Description of the issue

Currently, Azure Portal and DSC does not allow for custom assignment of all permissions shown in https://microsoft365dsc.com/resources/azure-ad/AADRoleDefinition/. Only permissions listed in https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/custom-available-permissions are allowed to be added to a custom role. 

The allowed permissions is a subset of all permissions and limits the ability of EntraID owners to scope down user permissions.

### Microsoft 365 DSC Version

1.24.1016.1

### Which workloads are affected

Azure Active Directory (Entra ID)

### The DSC configuration

```
 AADRoleDefinition 'AADRoleDefinition-SecurityAnalyst'{
  		     DependsOn             = @(
  		         '[AADApplication]AADApplication-Microsoft365DSC'
  		     )
  		         DisplayName                   = '[Custom Role] Security Analyst'
  		         Description                   = 'Test to see if we are able to assigned unlisted custom role permissions: https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/custom-available-permissions.'
  		         ResourceScopes                = '/'
  		         IsEnabled                     = $true 
  		         RolePermissions               =  @(      'microsoft.azure.advancedThreatProtection/allEntities/allTasks'
  		                                             )
  		         Version                       = '1.0'
  		         Ensure                        = 'Present'
  		         ApplicationId                 = $ApplicationId
  		         TenantId                      = $TenantId
  		         CertificateThumbprint         = $Thumbprint
  		 }

```

### Verbose logs showing the problem

```
[[AADRoleDefinition]AADRoleDefinition-SecurityAnalyst::[AzureAD]AzureAD_Configuration] Performing the operation 
"New-MgBetaRoleManagementDirectoryRoleDefinition_CreateExpanded" on target "Call remote 'POST 
/roleManagement/directory/roleDefinitions' operation".
##[error][Request_BadRequest] : Action 'microsoft.azure.advancedThreatProtection/allEntities/allTasks' is not supported for 
Custom Role creation.
    + CategoryInfo          : InvalidOperation: ({ Headers = , b...oleDefinition }:) [], CimException
    + FullyQualifiedErrorId : Request_BadRequest,Microsoft.Graph.Beta.PowerShell.Cmdlets.NewMgBetaRoleManagementDirect 
   oryRoleDefinition_CreateExpanded
    + PSComputerName        : localhost
VERBOSE: [LCM-USWEST2]: LCM:  [ End    Set      ]  

```

### Environment Information + PowerShell Version

```
OsName               : Microsoft Windows Server 2022 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.1.amd64fre.fe_release.210507-1500
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

**Comment by NikCharlebois** [comment]
This is bigger than DSC since the portal doesn't support it either and an official case should be opened with Microsoft to add that functionality and associated APIs.

**Comment by pangjaa** [comment]
Ack. I just tested this with graph and graph.beta

`New-MgRoleManagementDirectoryRoleDefinition : Action 'microsoft.office365.webPortal/allEntities/standard/read' is not supported for Custom Role creation.
Status: 400 (BadRequest)`

`New-MgBetaRoleManagementDirectoryRoleDefinition : Action 'microsoft.office365.webPortal/allEntities/standard/read' is not supported for Custom Role creation.
Status: 400 (BadRequest)`

**Comment by NikCharlebois** [comment]
Recommendation for this one would be to open a support case with Microsoft to request this feature to be available via the portal. If it then becomes available as part of the portal, we can integrate it in M365DSC.
