### ISSUE TITLE
ResourceName in settings.json files is not always unique

### ISSUE THREAD

**Issue by salbeck-sit** [microsoft/Microsoft365DSC#5316]
### Description of the issue

I've just issued a PR for an example of this issue. Having done so I thought that this might be something that is tested by the actions that are run as part of PR validation

### Microsoft 365 DSC Version

DEV

### Which workloads are affected

other

**Comment by salbeck-sit** [comment]
As an aside I noticed that not all json-files contain an update-scope

**Comment by salbeck-sit** [comment]
I mean, json-files that contain a graph read-scope. Not all resources do

**Comment by ykuijs** [comment]
Fixed in PR #5315
