### ISSUE TITLE
AADAccessReviewPolicy is missing required permission 'AccessReview.Read.All' for Read

### ISSUE THREAD

**Issue by mpoulson** [microsoft/Microsoft365DSC#5353]
### Description of the issue

AADAccessReviewPolicy calls Get-MgBetaPolicyAccessReviewPolicy which has a read requirement of permission 'AccessReview.Read.All' permission. 

### Microsoft 365 DSC Version

V1.24.1106.1

### Which workloads are affected

Azure Active Directory (Entra ID)

### Verbose logs showing the problem

[2024/11/06 08:09:56]
{InvalidOperation}
System.Exception: [] : Attempted to perform an unauthorized operation.
"Error during Export:"
at Get-MgBetaPolicyAccessReviewPolicy<Process>, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Beta.Identity.SignIns\2.24.0\exports\ProxyCmdletDefinitions.ps1: line 27329
at Export-TargetResource, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1106.1\DSCResources\MSFT_AADAccessReviewPolicy\MSFT_AADAccessReviewPolicy.psm1: line 268
at Start-M365DSCConfigurationExtract, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1106.1\Modules\M365DSCReverse.psm1: line 682
at Export-M365DSCConfiguration, C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1106.1\Modules\M365DSCUtil.psm1: line 1460

**Comment by NikCharlebois** [comment]
Actually, the permissions for the resource are:

"application": {
                "read": [
                    {
                        "name": "Policy.Read.All"
                    }
                ],
                "update": [
                    {
                        "name": "Policy.ReadWrite.AccessReview"
                    }
                ]
            }
