### ISSUE TITLE
Issue with groups referenced by ConvertTo- and ConvertFrom-IntunePolicyAssignment in M365DRGUtil.psm1

### ISSUE THREAD

**Issue by salbeck-sit** [microsoft/Microsoft365DSC#5362]
### Description of the issue

While refactoring a resource that utilizes Intune assignments I came across two functions in the M365DSCDRGUtil.psm1 module that proved very useful in flattening the CIM-structure of the arguments: ConvertTo- and ConvertFrom-IntunePolicyAssignment.

However, it appears that ConvertTo-IntunePolicyAssignment will silently drop assignments that reference a group that for any reason cannot be read.
I saw during my work to get unit-tests fail-free that even though I've mocked Get-MgGroup, the functions will get a 'one or more errors occurred'.
ConvertFrom-IntunePolicyAssignment will include the groupId in the output but of course won't include groupDisplayName if the group cannot be read -
BUT ConvertTo-IntunePolicyAssignment will drop the assignment altogether - in verbose-mode a message will be issued that 'Skipping assignment for the group with DisplayName *** as it could not be read, Please update...'
I would at least expect a message in the eventlog or even throwing an exception. How is this handled in other resources ?

### Microsoft 365 DSC Version

DEV

### Which workloads are affected

Intune

**Comment by salbeck-sit** [comment]
It appears that the problem with mocking that is indirectly causing the issue is a known error in WPS 5.1 as defined here: https://pester.dev/docs/usage/mocking#mocking-a-function-that-is-called-by-a-method-in-a-powershell-class
I'm not sure though how to implement the workaround in the unit-test

Anyway - the issue still stands. If an unknown groupDisplayName is specified with datatype #microsoft.graph.groupAssignmentTarget then the assignment is silently dropped.

**Comment by FabienTschanz** [comment]
@salbeck-sit That's unfortunately a restriction we have to live with. For your resource, you can use one of the other mocked assignments we are using in other resources (e.g. `IntuneFirewallRulesPolicyWindows10`). 

```powershell
Mock -CommandName Get-MgBetaDeviceManagementConfigurationPolicyAssignment -MockWith {
    return @(@{
        Id       = '12345-12345-12345-12345-12345'
        Source   = 'direct'
        SourceId = '12345-12345-12345-12345-12345'
        Target   = @{
            DeviceAndAppManagementAssignmentFilterId   = '12345-12345-12345-12345-12345'
            DeviceAndAppManagementAssignmentFilterType = 'none'
            AdditionalProperties                       = @(
                @{
                    '@odata.type' = '#microsoft.graph.exclusionGroupAssignmentTarget'
                    groupId       = '26d60dd1-fab6-47bf-8656-358194c1a49d'
                }
            )
        }
    })
}
```

It's not quite the same as one with a display name, but close enough that we can use it. 

Edit: I don't quite know why the assignment is skipped silently, but it makes sense that it is skipped because neither the Id nor the display name were found. But you're right, we could at least output a warning instead of just silently skipping it. 

Edit2: I opened the PR #5371 that switches the log type from `Write-Verbose` to `Write-Warning` for improved visibility.

**Comment by FabienTschanz** [comment]
@salbeck-sit Are you ok with closing the issue or is there something more you would like to have addressed?

**Comment by salbeck-sit** [comment]
I'm OK with closing the issue for now. In the resource I'm building I've added my own tests since I find it misleading to complete a config that isn't applied as it was written.
