### ISSUE TITLE
IntuneEndpointDetectionAndResponsePolicyWindows10: Doesn't export *ConfigurationBlob*/*ConfigurationType* and then cannot deploy

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#5377]
### Description of the issue

@FabienTschanz After you fixed my issue #5246 with #5254 it looks like it's still missing a piece of the puzzle, *ConfigurationBlob* and *ConfigurationType* seem to be null and don't get included in the export so when trying to deploy the attached configuration of course it errors out with the exception you added. Could you please check?

### Microsoft 365 DSC Version

1.24.1106.3

### Which workloads are affected

Intune

### The DSC configuration

```powershell
IntuneEndpointDetectionAndResponsePolicyWindows10 "IntuneEndpointDetectionAndResponsePolicyWindows10-IntuneEndpointDetectionAndResponsePolicyWindows10"
        {
            Assignments          = @(
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    groupDisplayName = 'DummyGroupInclude'
                    dataType = '#microsoft.graph.groupAssignmentTarget'
                    groupId = '7a4ba6e1-34c9-408e-a00b-16d7e3afd0a7'
                }
                MSFT_DeviceManagementConfigurationPolicyAssignments{
                    deviceAndAppManagementAssignmentFilterType = 'none'
                    groupDisplayName = 'DummyGroupExclude'
                    dataType = '#microsoft.graph.exclusionGroupAssignmentTarget'
                    groupId = 'eb608413-2b7d-440c-97f7-1f199816eb38'
                }
            );
            Credential           = $Credscredential;
            Description          = "IntuneEndpointDetectionAndResponsePolicyWindows10_1";
            DisplayName          = "IntuneEndpointDetectionAndResponsePolicyWindows10_1";
            Ensure               = "Present";
            Identity             = "6d16071c-23ed-48a1-9811-6eb84a377904";
            RoleScopeTagIds      = @("0");
            SampleSharing        = "1";
        }
```

### Verbose logs showing the problem

```powershell
PowerShell DSC resource MSFT_IntuneEndpointDetectionAndResponsePolicyWindows10  failed to execute Set-TargetResource functionality with error message: ConfigurationBlob is required for configurationType ''
```

### Environment Information + PowerShell Version

```powershell
Win11/PS5.1
```

**Comment by ricmestre** [comment]
@FabienTschanz The policy I have in my gold tenant is using auto from connector, then when extracting the settings with the code below I only get *SampleSharing* and *TelemetryReportingFrequency* so of course *ConfigurationType* is null and therefore *ConfigurationBlob* as well.

```powershell
[array]$settings = Get-MgBetaDeviceManagementConfigurationPolicySetting `
            -DeviceManagementConfigurationPolicyId $Identity `
            -ExpandProperty 'settingDefinitions' `
            -ErrorAction Stop
```

**Comment by FabienTschanz** [comment]
@ricmestre I'll check it a bit later, currently setting up my SCCM environment so that I can also work on resources that require an active SCCM infrastructure.

**Comment by FabienTschanz** [comment]
Can't do it today, will be in my office tomorrow. The Defender for Endpoint license is not included in my test tenant... Can't check it there unfortunately.

**Comment by ricmestre** [comment]
@FabienTschanz I said incorrectly the policy I was looking at had configuration type auto from connector but it's actually not setup, it's an old policy but you still can create new ones just like that.

I went into more detail in the other issue #5246 I reported about this, how should we handle this? Adapt the code to cope with this or change the policy to one of the available configuration types? I wonder why MS accepts creating these policies without the type where this scenario is not mentioned in [0].

[0] https://learn.microsoft.com/en-us/mem/intune/protect/endpoint-security-edr-policy

**Comment by FabienTschanz** [comment]
@ricmestre If it really is an old policy which we cannot recreate now through the UI, then it doesn't make sense to adapt the code to work with it. If it were still active and creatable, we should have done it, but this way, I doubt I can figure out how this is supposed to work. 

I guess they didn't completely disable it because the policy itself is still "supported" and they just let it run along, until they remove it in a couple of years (probably). No idea why it must take so long.

**Comment by ricmestre** [comment]
I'm clueless on this, I don't have access to any customer's tenant right now that uses this kind of policy, only our own tenant from which we create designs from and on this one the policy has configuration type set to "not configured" and like I said you can still create new ones right now that still support it.

I sent an email to my M365 colleagues asking what to do with this policy.

**Comment by FabienTschanz** [comment]
I will take a look at the other issue mentioned in #5300 with onboarding_fromconnector not working at a later date, as soon as I have access to my company tenant. Hope that will be the case tomorrow, I'm flooded with tasks right now.

**Comment by FabienTschanz** [comment]
@ricmestre The other issue with #5300 is fixed. Did you hear something from your colleagues about the policy?

**Comment by ricmestre** [comment]
@FabienTschanz We came to the conclusion that we should not have that policy since it's an onboarding policy and therefore requires a blob that can't be applied to customers, they will have their own policies/blobs instead.

I'll close this since issue is solved.
