### ISSUE TITLE
None of the Security & Compliance properties are being processed with M365DSC when building the Permissions List due to this error: Item has already been added. Key in dictionary

### ISSUE THREAD

**Issue by rick-engle** [microsoft/Microsoft365DSC#5427]
### Description of the issue

When I try and set the App permissions for the Security & Compliance modules, the Get-M365DSCCompiledPermissionList command fails to build the permissions list correctly.   Even if I just pass 1 Security module name, I get the error:
Item has already been added. Key in dictionary: 'PermissionName'  Key being added: 'PermissionName'

Code:
$PermissionsList = Get-M365DSCCompiledPermissionList -AccessType Update -ResourceNameList @("SCAuditConfigurationPolicy") -PermissionType Application
##  The M365DSC app in addition needs the Directory.Read.All permission
$PermissionsList += @{API ='Graph';PermissionName='Directory.Read.All';}

Item has already been added. Key in dictionary: 'PermissionName'  Key being added: 'PermissionName'
At line:3 char:1
+ $PermissionsList += @{API ='Graph';PermissionName='Directory.Read.All ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException

Other configuration categories like AAD and Intune work fine with the code above.

### Microsoft 365 DSC Version

1.24.1113.1

### Which workloads are affected

Security & Compliance Center

### The DSC configuration

```powershell

```

### Verbose logs showing the problem

```powershell
$PermissionsList = Get-M365DSCCompiledPermissionList -AccessType Update -ResourceNameList @("SCAuditConfigurationPolicy", "SCAutoSensitivityLabelPolicy", "SCAutoSensitivityLabelRule", "SCCaseHoldPolicy", "SCCaseHoldRule", "SCComplianceCase", "SCComplianceSearch", "SCComplianceSearchAction", "SCComplianceTag", "SCDeviceConditionalAccessPolicy", "SCDeviceConfigurationPolicy", "SCDLPCompliancePolicy", "SCDLPComplianceRule", "SCFilePlanPropertyAuthority", "SCFilePlanPropertyCategory", "SCFilePlanPropertyCitation", "SCFilePlanPropertyDepartment", "SCFilePlanPropertyReferenceId", "SCFilePlanPropertySubCategory", "SCLabelPolicy", "SCProtectionAlert", "SCRetentionCompliancePolicy", "SCRetentionComplianceRule", "SCRetentionEventType", "SCRoleGroup", "SCRoleGroupMember", "SCSecurityFilter", "SCSensitivityLabel", "SCSupervisoryReviewPolicy", "SCSupervisoryReviewRule") -PermissionType Application
##  The M365DSC app in addition needs the Directory.Read.All permission
$PermissionsList += @{API ='Graph';PermissionName='Directory.Read.All';}
####$Credential = Get-Credential
$credential = Get-Credential -UserName $SourceTenantUserName -Message "Please enter your password for $SourceTenantUserName"
Item has already been added. Key in dictionary: 'PermissionName'  Key being added: 'PermissionName'
At line:7 char:1
+ $PermissionsList += @{API ='Graph';PermissionName='Directory.Read.All ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.26100.2161
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.26100.2161
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by FabienTschanz** [comment]
@rick-engle The output of `Get-M365DSCCompiledPermissionList` is a hashtable. Since the Security & Compliance modules all only have on specific permission (`Organization.Read.All`), it will only return the hashtable. If there were multiple permissions (just like in Intune and AAD), it would return an array of hashtables. 

Now the issue you're encountering is because `+=` is an overloaded operator for a hashtable _and_ an array - For an array, it adds the new element just as you would think, but on a hashtable, it adds all of the keys of the "new" object to the existing one. 

In your example, `$PermissionsList` is a hashtable with two properties (not an array what you expected), and you want to add the two keys `API` and `PermissionName`. For your example to work, you need the following definition: `[array]$PermissionsList = Get-M365DSCCompiledPermissionList...` to force creation of an array.

**Comment by ricmestre** [comment]
I think the question is more in the sense of why is *Directory.Read.All* required, is it really? I didn't test it so I don't know but if it's required then the solution is to add to the settings.json of each resource.

**Comment by rick-engle** [comment]
@FabienTschanz that is a very helpful analysis!  That forced typing worked!
