### ISSUE TITLE
IntuneAppProtectionPolicyiOS - Cannot Bind to Argument IosManagedAppProtectionId

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#5428]
### Description of the issue

Trying to deploy a config containing the IntuneAppProtectionPolicyiOS resource throws the following errors:

 Cannot bind argument to parameter 'IosManagedAppProtectionId' because it is an empty string.
ParameterArgumentValidationErrorEmptyStringNotAllowed,Update-IntuneAppProtectionPolicyiOSAssignment

### Microsoft 365 DSC Version

V1.24.1113.1

### Which workloads are affected

Intune

### The DSC configuration

```powershell

```

### Verbose logs showing the problem

```powershell

```

### Environment Information + PowerShell Version

```powershell

```

**Comment by tashaem** [comment]
Hi Nik, I am experiencing the same error trying to deploy config of AppProtectionPolicyiOS type to Intune. How did you resolve this issue in the end?
