### ISSUE TITLE
EXOJournalRule

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#543]

**Comment by NikCharlebois** [comment]
@ahohenschuh do we have an update on this item. It was assigned to you in our backlog. Thanks

**Comment by mattckrause** [comment]
Hey @NikCharlebois and @ahohenschuh, I had assigned this to myself in the backlog and have been working on it. I have the module built out and and just working on the unit test. Need anything else from me?

**Comment by NikCharlebois** [comment]
Probably my bad when I did the original assignment @mattckrause . Simply submit your Pull Request and we will review. Thanks

**Comment by NikCharlebois** [comment]
@MattcKrause it's assigned to you now
