### ISSUE TITLE
MOF file exceeded max size limit

### ISSUE THREAD

**Issue by Thomas-Methner** [microsoft/Microsoft365DSC#5468]
### Description of the issue

Hej,

I am doing recovery test for backups of aad users (1000+ users). My envelopesize is already 128mb, but I am running into this error:
_MOF file size exceeded max size limit.
    + CategoryInfo          : ResourceBusy: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 27
    + PSComputerName        : localhost_

From some issues documented here it seems like it is proposed to break down the backups even more.
My question is, what are the actual limits for the mof files size? 
Best

### Microsoft 365 DSC Version

1.24.904.1

### Which workloads are affected

Azure Active Directory (Entra ID)

### The DSC configuration

```powershell
@{
    AllNodes = @(
        @{
            NodeName                    = "localhost"
            PSDscAllowPlainTextPassword = $true;
            PSDscAllowDomainUser        = $true;
            #region Parameters
            # Default Value Used to Ensure a Configuration Data File is Generated
            ServerNumber = "0"

        }
    )
    NonNodeData = @(
        @{
            # Tenant's default verified domain name
            OrganizationName = "xyz.onmicrosoft.com"

            # Azure AD Application Id for Authentication
            ApplicationId = "xyz"

            # The Id or Name of the tenant to authenticate against
            TenantId = "xyz.onmicrosoft.com"

            # Thumbprint of the certificate to use for authentication
            CertificateThumbprint = "xyz"

        }
    )
}
```

### Verbose logs showing the problem

```powershell
AUSFÜHRLICH: Vorgang "CIM-Methode aufrufen" mit den folgenden Parametern durchführen, "'methodName' =
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration".
AUSFÜHRLICH: An LCM method call arrived from computer vm-colli-0 with user sid
S-1-12-1-1239345608-1301440490-3343379598-3488004834.
AUSFÜHRLICH: [vm-colli-0]: LCM:  [ Start  Set      ]
AUSFÜHRLICH: [vm-colli-0]: LCM:  [ End    Set      ]
MOF file size exceeded max size limit.
    + CategoryInfo          : ResourceBusy: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 27
    + PSComputerName        : localhostAUSFÜHRLICH: Vorgang "CIM-Methode aufrufen" wurde abgeschlossen.
AUSFÜHRLICH: Die Ausführung des Konfigurationsauftrags hat 73.426 Sekunden gedauert.
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 11 Enterprise multi-session
OsOperatingSystemSKU : 175
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}

Name                           Value
----                           -----
PSVersion                      5.1.22621.4391
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.4391
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by FabienTschanz** [comment]
@Thomas-Methner You can set the `MaxEnvelopeSizeKb` in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WSMAN\Client` to a value like 1000000, which is approx. 1GB. Maybe that will work?

**Comment by Thomas-Methner** [comment]
@FabienTschanz hej. My value is about 512MB at the moment, but I will try the maximum also. I hope there is some experience here with the filesizes in general. The only other option I see is to chunk the exports right away by e.g. export groups a-c/ d-f and so on.

**Comment by FabienTschanz** [comment]
@Thomas-Methner How did it go with the max file size? Do you need to split the configurations?

**Comment by Thomas-Methner** [comment]
@FabienTschanz thats the only working solution for us so far. 

From our findings I can say:
* maximum size of the .mof is 10 MB
* changing the max size in the win registry to 20 mb is not working
* decode in utf8 lowers the size
*  # WinRM configured (execute in admin shell)
    Set-WSManQuickConfig -Force
    winrm set winrm/config "@{MaxEnvelopeSizekb=`"512000`"}"
    winrm set winrm/config "@{MaxTimeoutms=`"300000`"}"
    Set-WSManQuickConfig -Force
    Restart-Service -Name WinRM

Finally we played with filters to minimize the size of a backup and ended with a script, which splits any backup in smaller batches. 
The size limitation is due to powershell desired state configuration. We hope that DSC V3 works better for big backups.
https://learn.microsoft.com/de-de/powershell/dsc/overview?view=dsc-3.0
