### ISSUE TITLE
Running Export-M365DSCConfiguration on Azure Automation Runbook does not export files

### ISSUE THREAD

**Issue by xxwdxbg** [microsoft/Microsoft365DSC#5494]
I have updated all the dependencies in the Azure Automation account using the script provided [https://github.com/microsoft/Microsoft365DSC/issues/2050#issuecomment-1195414547](url) I verified that each module has been successfully imported and applied all the necessary API permissions to my app. Additionally, I am using a managed identity to export M365DSC. However, while running Export-M365DSCConfiguration thrugh Azure Runbook returns empty data.

I cannot check the file under $tempPath.

 ![Image](https://github.com/user-attachments/assets/13cf6553-b57e-41ad-b06f-d587812a5f9c)

The script i am using is simply,

# Parameters
$tenantId = "XXX" 
$resourceGroup =  #"XXX"
 
Connect-AzAccount -Identity
 
# Export Teams workload details with verbose output
Write-Output "Exporting Teams Meeting Policy details..."
try {
    Set-Location -Path $tempPath
    Export-M365DSCConfiguration -ManagedIdentity -Components @("TeamsMeetingPolicy") -TenantID $tenantId -Verbose
    Write-Output "Export completed successfully. Check $tempPath for generated files."
} catch {
    Write-Error "Failed to export Teams details. Error: $_"
    exit 1
}
 
# Locate the generated output file
$exportedFile = Get-ChildItem -Path $tempPath -Filter "*.ps1" | Select-Object -First 1
if (-not $exportedFile) {
    Write-Error "No exported file found in $tempPath. Verify if Export-M365DSCConfiguration is working correctly."
    exit 1
}
Write-Output "Found exported file: $exportedFile"

**Comment by FabienTschanz** [comment]
@xxwdxbg It could be the case that the worker underneath the runbook ran out of memory and therefore didn't finish the execution. Any chance you can setup a hybrid worker and run it there? This is also most likely better as soon as you're using it for more components, where the memory consumption will overshoot 400MB.

**Comment by xxwdxbg** [comment]
> [@xxwdxbg](https://github.com/xxwdxbg) It could be the case that the worker underneath the runbook ran out of memory and therefore didn't finish the execution. Any chance you can setup a hybrid worker and run it there? This is also most likely better as soon as you're using it for more components, where the memory consumption will overshoot 400MB.

Thanks Fabien, I will take your suggestion.
