### ISSUE TITLE
I keep seeing 2 versions of Microsoft365DSC installed

### ISSUE THREAD

**Issue by rick-engle** [microsoft/Microsoft365DSC#5511]
### Description of the issue

Whenever I check the version(s) of M365DSC installed I show 2 versions the current and last.  What doesn't the update process remove the n-1 version?

Get-Module Microsoft365DSC -ListAvailable | Select-Object ModuleBase, Version

ModuleBase                                                             Version    
----------                                                             -------    
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1120.1 1.24.1120.1
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1113.1 1.24.1113.1

I am using these statements to upgrade to the latest version:
Update-Module Microsoft365DSC
Update-M365DSCDependencies

### Microsoft 365 DSC Version

1.24.1120.1

### Which workloads are affected

Intune

### The DSC configuration

```powershell
Not applicable.
```

### Verbose logs showing the problem

```powershell
Not applicable.
```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows 11 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Key   : PSVersion
Value : 5.1.26100.2161
Name  : PSVersion

Key   : PSEdition
Value : Desktop
Name  : PSEdition

Key   : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}
Name  : PSCompatibleVersions

Key   : BuildVersion
Value : 10.0.26100.2161
Name  : BuildVersion

Key   : CLRVersion
Value : 4.0.30319.42000
Name  : CLRVersion

Key   : WSManStackVersion
Value : 3.0
Name  : WSManStackVersion

Key   : PSRemotingProtocolVersion
Value : 2.3
Name  : PSRemotingProtocolVersion

Key   : SerializationVersion
Value : 1.1.0.1
Name  : SerializationVersion
```

**Comment by rick-engle** [comment]
I just ran an update process for Microsoft365DSC to 1.24.1127.1 and now it shows me 3 versions installed:

Update commands:
Update-Module Microsoft365DSC
Update-M365DSCDependencies

List installed versions:
Get-Module Microsoft365DSC -ListAvailable | Select-Object ModuleBase, Version

ModuleBase                                                             Version    
----------                                                             -------    
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1127.1 1.24.1127.1
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1120.1 1.24.1120.1
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1113.1 1.24.1113.1

**Comment by FabienTschanz** [comment]
@rick-engle There is a dedicated command available that updates the Microsoft365DSC module: `Update-M365DSCModule`. This command updates the module itself and all dependencies in one go, also uninstalling all outdated versions. Can you give that a try?

**Comment by rick-engle** [comment]
@FabienTschanz Ah fantastic!! That solved everything nicely!  I wonder if any of the other issues I had were due to having multiple versions installed.

Get-Module Microsoft365DSC -ListAvailable | Select-Object ModuleBase, Version

ModuleBase                                                                             Version    
----------                                                                             -------    
C:\Users\ricke.REDMOND\Documents\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1211.1 1.24.1211.1
