### ISSUE TITLE
Get-M365DSCWorkloadsListFromResourceNames not working

### ISSUE THREAD

**Issue by PsySuck** [microsoft/Microsoft365DSC#5525]
### Description of the issue

I am trying to run Get-M365DSCWorkloadsListFromResourceNames from [doc]https://microsoft365dsc.com/user-guide/cmdlets/Get-M365DSCWorkloadsListFromResourceNames/(url)
`Get-M365DSCWorkloadsListFromResourceNames -ResourceNames AADUSer`
I got for any Resource
```
Get-M365DSCWorkloadsListFromResourceNames -ResourceNames AADUSer
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.24.1127.1\Modules\M365DSCUtil.psm1:4224 char:14
+     foreach ($resource in $ResourceNames)
+              ~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

### Microsoft 365 DSC Version

1.24.1127.1

### Which workloads are affected

other

### The DSC configuration

```powershell

```

### Verbose logs showing the problem

```powershell

```

### Environment Information + PowerShell Version

```powershell
OsName               : Microsoft Windows Server 2022 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 20348.2849.amd64fre.fe_release_svc_prod1.241101-1732
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

Name                           Value
----                           -----
PSVersion                      5.1.20348.2849
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.2849
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by FabienTschanz** [comment]
@NikCharlebois Question here. The function `Get-M365DSCWorkloadsListFromResourceNames` is supposed to return the workloads from given input resources. The example is as the @PsySuck describes: `Get-M365DSCWorkloadsListFromResourceNames -ResourceNames AADUser`. But now the caveat: Inside of the function, it's expected that the input resources contain a `Name` and a `AuthenticationMethod` property? Why is that the case? The function description doesn't contain any more information about it. 


```powershell
switch ($resource.Name.Substring(0, 2).ToUpper())
{
    'AA'
    {
        if (-not $workloads.Name -or -not $workloads.Name.Contains('MicrosoftGraph'))
        {
            $workloads += @{
                Name                 = 'MicrosoftGraph'
                AuthenticationMethod = $resource.AuthenticationMethod
            }
        }
    }
...
}
```

The call to `$resource.Name.Substring(...)` leads to the exception of the issue. In my opinion, this is an error and should be corrected.
