### ISSUE TITLE
Inconsistent behaviour due to how mofs are compiled

### ISSUE THREAD

**Issue by dannyKBjj** [microsoft/Microsoft365DSC#5546]
### Description of the issue

Unsure if this is a bug, but I believe it is because the behaviour is inconsistent.

I'm developing a module and noticed that because my export contains a class defined in the mof with some blank and some defined values, the blank values will not be compiled into the .mof. 

See "ExamplePolicy.ps1.txt" line 22-27

            contentFilterSettings    = @(
                MSFT_iosWebContentFilterSpecificWebsitesAccess{
                    blockedUrls = @('https://www.facebook.com')
                    allowedUrls = @()
                }
            );

This is compiling into localhost.mof.txt where the 'allowedUrls' value is ignored. Like so:

            instance of MSFT_iosWebContentFilterSpecificWebsitesAccess as $MSFT_iosWebContentFilterSpecificWebsitesAccess1ref
            {
            blockedUrls = {
                "https://www.facebook.com"
            };
            
            };

This means that if I then add URLs to the policy, that Test-TargetResource will still evaluate as $true. I don't believe it should, particularly when if I add an extra blockedUrl to the policy and also add an allowedURL, it will evaluate as $false (as it should), and then when I run start-dscConfiguration it will remove the allowedURL as well. 

If I fix it manually as-per localhost.-.FixedManually.mof.txt , like so

          instance of MSFT_iosWebContentFilterSpecificWebsitesAccess as $MSFT_iosWebContentFilterSpecificWebsitesAccess1ref
          {
          blockedUrls = {
              "https://www.facebook.com"
          };
           allowedUrls = {
          };
          };

then the behaviour is what I would expect. I.e. if I add an allowedURL, without changing blockedUrls, then the allowedURl will be removed. 

I think this might point to a problem with the way configurations are being compiled, although I'm unsure if there's a good reason for this behaviour that I'm missing? I can provide the module I'm working on if that is helpful...

[ExamplePolicy.ps1.txt](https://github.com/user-attachments/files/18114484/ExamplePolicy.ps1.txt)

[localhost.mof.txt](https://github.com/user-attachments/files/18114482/localhost.mof.txt)

[localhost - FixedManually.mof.txt](https://github.com/user-attachments/files/18114480/localhost.-.FixedManually.mof.txt)

### Microsoft 365 DSC Version

1.24.1127.1

### Which workloads are affected

Intune

### The DSC configuration

```powershell
# Generated with Microsoft365DSC version 1.24.1127.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
)

Configuration M365TenantConfig
{
    param (
    )

    $OrganizationName = $ConfigurationData.NonNodeData.OrganizationName

    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.24.1127.1'

    Node localhost
    {
        IntuneDeviceFeaturesConfigurationPolicyIOS "IntuneDeviceFeaturesConfigurationPolicyIOS-iOS-TestPolicy"
        {
            ApplicationId            = $ConfigurationData.NonNodeData.ApplicationId;
            Assignments              = @();
            CertificateThumbprint    = $ConfigurationData.NonNodeData.CertificateThumbprint;
            contentFilterSettings    = @(
                MSFT_iosWebContentFilterSpecificWebsitesAccess{
                    blockedUrls = @('https://www.facebook.com')
                    allowedUrls = @()
                }
            );
            Description              = "test";
            DisplayName              = "iOS-TestPolicy";
            Ensure                   = "Present";
            Id                       = "93f08fce-6565-4b7b-9887-76c1a0b378ff";
            TenantId                 = $OrganizationName;
            wallpaperDisplayLocation = @();
        }
    }
}

PolicyTest -ConfigurationData .\ConfigurationData.psd1
```

### Verbose logs showing the problem

```powershell
Not applicable.
```

### Environment Information + PowerShell Version

```powershell

```

**Comment by FabienTschanz** [comment]
@dannyKBjj Are you compiling the configuration with PowerShell 7? I get the same output just as you do when I do it with PS7, but with PS5.1, it works without issues. I believe this is an issue in the PSDesiredStateConfiguration module. Will check what's going on there.

**Comment by dannyKBjj** [comment]
Hi yes, I'm using PS7 to compile.

I can't compile in PS5 as I get a PSDesiredStateConfiguration error?

![Image](https://github.com/user-attachments/assets/a6227797-7063-462b-b4c0-f3e87d245cd0)

**Comment by FabienTschanz** [comment]
Please uninstall the `PSDesiredStateConfiguration` module in version 2.0.7 from Windows PowerShell and instead install it with PowerShell 7. It is not intended to be used with PowerShell 5.1.

**Comment by dannyKBjj** [comment]
OK, thanks, that worked.

I am pretty sure I did not explicitly install that module. I think it must've come down with the Update-Microsoft365dependencies command?

I think perhaps this could do with an update?

https://microsoft365dsc.com/user-guide/get-started/how-to-install/

**Comment by FabienTschanz** [comment]
It probably was from a previous version where the installation process was a bit confused. This was updated in the latest releases.

**Comment by dannyKBjj** [comment]
Ok thanks. I'll close the issue.

**Comment by FabienTschanz** [comment]
@dannyKBjj FYI: The issue is in the PSDesiredStateConfiguration module with version 2.0.7. I traced it back to the following check: 
```powershell
if ($targetTypeName -notmatch 'Array' -or $p.Value.Count)
{
    $p.Name + ' = ' + (stringify -value $p.Value -asArray $asArray -targetType  $targetType ) + ";`n"
}
```
`$targetType` is `StringArray`, and `$p.Value.Count` has a value of 0. The if statement evaluates to false, since the target type contains 'Array' and 0 is treated as false. That's the reason why an empty array is omitted with PS7, and different from PS5. I doubt they will change anything there and instead invest the time into DSCv3. I will add a note to the docs.
