### ISSUE TITLE
Microsoft365DSC - Guidelines -> Deploy configuration

### ISSUE THREAD

**Issue by Kierow** [microsoft/Microsoft365DSC#5576]
Hello,

We are currently using M365DSC to export several components for each workload (Graph, EXO, Teams, etc...). 
As a result, we have a .ps1 for each component and also a .ps1 for each workload. 

Now, we would like to deploy/enforce configurations using the .ps1/mof files and I'm looking for some guidelines/advices in order to implement it. 

>  What would you do / What do you do currently?
- Apply the configuration per component? 
- Apply the configuration per workload?
I would like something that is granular so I think that the component approach is the best. But is that possible using the LCM? Can we deploy several different .mof files from a single machine using the LCM?

> What is the best way to implement it? 
I would like to be able to parallelized this (like one process per workload) in order to apply the configuration faster. Is that possible with the LCM on a single machine? 

Thanks in advance for your answer. :)

Keep up the good work, M365DSC is such a great tool ! 👍 

Regards,

**Comment by ykuijs** [comment]
Hi @Kierow, This depends a little on what you want to do and how you want to manage your configurations.

From a manageability standpoint I would not use a PS1 file per component. That would mean you have hundreds of PS1 files. I would use the workload approach. It is possible to deploy multiple MOF files from one LCM, but (of course there is a but 😉) this does mean you will lose the monitoring functionality. That can be mitigated by using a script that runs a Test-DSCConfiguration and parse the output.

Have you seen our [whitepaper](https://aka.ms/m365dscwhitepaper)? That is using a framework to deploy changes using various datafiles, split into workloads.

**Comment by Kierow** [comment]
Hi @ykuijs ,

Thanks for the insights! 
This is what I was thinking regarding the monitoring part ! And I didn't think about the Test-DSCConfiguration workaround, but it's a good idea ;)

I totally forgot this whitepaper, I had a look on the first version a while ago. I see that you have updated it recently so I'm going to read it right now. 👍 

Thanks again for the quick and pertinent answer. :)

**Comment by ykuijs** [comment]
That is correct, a new big update was released two months ago. And working on another minor update right now. Hope to release it before the end of this year.

Closing this issue now, since your question has been answered.
