### ISSUE TITLE
Microsofty365DSC Module 1.0.5.39

### ISSUE THREAD

**Issue by AlanFlorance** [microsoft/Microsoft365DSC#584]
#### Details of the scenario you tried and the problem that is occurring 
Module seems to have a fixed dependancy on version 0.2.0 of Microsoft.Graph.Authentication module, once Install-M365DSCDevBranch is used to bring verion up to date, it installs 0.5.0 but still loads the previous version,

        @{
            ModuleName      = "Microsoft.Graph.Authentication"
            RequiredVersion = "0.2.0"
        },

#### Suggested solution to the issue
Updated required version to 0.5.0 of Microsoft.Graph.Authentication

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A
#### The operating system the target node is running
N/A
#### Version of the DSC module that was used ('dev' if using current dev branch)
N/A

**Comment by NikCharlebois** [comment]
We are working on a fix. We had to wait for version 0.5.1 of the MSGraph SDK to be released first. It was just released a few hours ago.
