### ISSUE TITLE
AADMSGroup

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#589]
#### Details of the scenario you tried and the problem that is occurring
Error compiling .ps1 config if two groups have the same name due to the resource's Key being identical. We can't really add ID as a key parameter because it will very often be null. We need to look at other solutions.

**Comment by NikCharlebois** [comment]
@desmay was this ever fixed? I seem to recall one of your PR was dressing this, can you confirm?

**Comment by desmay** [comment]
@NikCharlebois No still looking for suggestions. I'm certain will hit this scenario in other resources within AAD

**Comment by ThorstenLoeschmann** [comment]
I agree with Derek, we do see and will continue to see this behavior with other AAD resources :-(.

**Comment by NikCharlebois** [comment]
@ThorstenLoeschmann @desmay any updates on this?

**Comment by ThorstenLoeschmann** [comment]
Not from my side. Honestly haven't had time to look into this again.

**Comment by NikCharlebois** [comment]
Decided to handle it by recreating a second group with same name to avoid data loss.
