### ISSUE TITLE
Bug in Test-Microsoft365DscParameterState

### ISSUE THREAD

**Issue by ykuijs** [microsoft/Microsoft365DSC#595]
#### Details of the scenario you tried and the problem that is occurring
The Test-Microsoft365DscParameterState function has a bug. On the following line it is comparing the same object, which of course will always result in True:
https://github.com/microsoft/Microsoft365DSC/blob/228bdd6017c41eb3cc63300cea851dced8f7c227/Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1#L791-L792

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
The variable on line 792 should be changed to $AllDesiredValuesAsArray 

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
Great catch. Will fix it in a new PR ASAP.
