### ISSUE TITLE
Plans for EM+S apps

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#599]

**Comment by NikCharlebois** [comment]
@DeanGross  can you please elaborate on this and provide additional details? Thanks

**Comment by DeanGross** [comment]
I'm wondering if you have any plans to use this technology to get configuration settings from Intune, Azure ATP, MCAS and/or Azure AD P1/P2 features

**Comment by dcaddick** [comment]
Hi @DeanGross I've added you in the IntuneDevicePolicy thread to start with ;-)
@NikCharlebois - what level of detail do you need? I'm assuming that this is essentially based on Powershell comms at the foundational level - so if we can identify the Powershell commands or SDK's and that can help kick off things?
