### ISSUE TITLE
Multiple authentication request

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#600]

**Comment by NikCharlebois** [comment]
@DeanGross can you please provide more details as to what the issue at hand is. What operation is causing multiple authentication requests? Thanks

**Comment by DeanGross** [comment]
I entered my username and password in the M365 DSC UI, and then I got another login prompt from MS to enter my password again, and a login window popped up after I received a message about a newer version of PNP being available, another prompt came up when it got to the AppCatalog site

**Comment by NikCharlebois** [comment]
@DeanGross are you still facing this with the latest version? Thanks

**Comment by DeanGross** [comment]
No I am not. thanks for getting that minor bug resolved.
