### ISSUE TITLE
Misleading warning - version of SharePointPnPPowerShell

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#601]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

**Comment by NikCharlebois** [comment]
Hi @DeanGross could you please provide additional details as to what the issue is. The latest version of the PnP module has an issue where it tells you about a newer version even if you have it installed. Thanks
