### ISSUE TITLE
Extracting config with MFA enabled account

### ISSUE THREAD

**Issue by sijday** [microsoft/Microsoft365DSC#604]
Please could the documentation be updated to explain how to use the Export functionality with an MFA enabled account?
After lots of trial and error the only way I have still haven't been able to successfully export Teams config.

**Comment by NikCharlebois** [comment]
@sijday just want to confirm, you closing the issue mean you are now able to do the extract? Do you still require any help from the team? Thanks

**Comment by sijday** [comment]
Hi @NikCharlebois  yes all working now. It turned out that some of the PowerShell modules had not installed when I initially installed Microsoft365DSC. 
I'm now reading with interest the thread on Azure Automation as this seems very promising.
