### ISSUE TITLE
Assert-M365DSCTemplate: local template compare issue

### ISSUE THREAD

**Issue by TraneLenart** [microsoft/Microsoft365DSC#635]
## Details of the scenario you tried and the problem that is occurring
I can successfully export the config with Export-M365DSCConfiguration but when I want to compare the locally saved template to the actual config and run the Assert-M365DSCTemplate command I got an error message. (Maybe I did not get the point how this works. In my understanding I can export the actual config as a template and I can compare it against a future state.)

#### Verbose logs showing the problem
Assert-M365DSCTemplate -TemplatePath "C:\Users\...\DSC\L2\M365TenantConfig.ps1"                                      The client cannot connect to the destination specified in the request. Verify that the service on the destination is
running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the
destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the
destination to analyze and configure the WinRM service: "winrm quickconfig".
    + CategoryInfo          : ConnectionError: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : HRESULT 0x80338012
    + PSComputerName        : localhost

The environment does not match the template. The following component(s) are not in the Desired State:

![image](https://user-images.githubusercontent.com/66674712/84142435-10432780-aa55-11ea-8b94-4253c8dbab80.png)

#### Version of the DSC module that was used ('dev' if using current dev branch)
![image](https://user-images.githubusercontent.com/66674712/84142524-39fc4e80-aa55-11ea-80c3-4d24a91a8100.png)

**Comment by NikCharlebois** [comment]
Did you try running **Winrm QuickConfig** on the machine before running the Assert command?

**Comment by TraneLenart** [comment]
Thanks for the reply. I saw the error message but did not understand why it is relevant. If I could export the config why the compare needs any local settings to change? But I should not understand everything. :-)
I run the Winrm quickconfig and now the script started to process the data but after a while it throwes another error:
![image](https://user-images.githubusercontent.com/66674712/84155761-04616080-aa69-11ea-86c9-e373be6ffc74.png)
IE works on the machine. Where should I specify the UseBasicParsing parameter?

**Comment by NikCharlebois** [comment]
We've had reports that certain GPO may cause this issue on machines. Can you please refer to the following resolution and see if that fixes your issue? Thanks
https://github.com/microsoft/Microsoft365DSC/issues/637
