### ISSUE TITLE
Add support for service principal with SPO and OneDrive resources 

### ISSUE THREAD

**Issue by desmay** [microsoft/Microsoft365DSC#636]
Add ability to use service principal with SPO and OneDrive resources
### Description
Add ability to use service principal with SPO and OneDrive resources

### Proposed properties
  [Parameter()]
        [System.String]
        $ApplicationId,

        [Parameter()]
        [System.String]
        $TenantId,

        [Parameter()]
        [System.String]
        $CertificateThumbprint

**Comment by desmay** [comment]
@NikCharlebois Can you assign to me thx

**Comment by NikCharlebois** [comment]
FYI - Other Resources are using the following as the name of their parameters:

ApplicationId
TenantId
CertificateThumbprint
AppSecret

We also have a new method called New-M365DSCConnection which checks the received params to decide if we need to connect with User or Service Principals

**Comment by NikCharlebois** [comment]
Fixed with the July release
