### ISSUE TITLE
Empty reports

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#639]
the template details file is empty, what am i doing wrong?

**Comment by NikCharlebois** [comment]
Hi @DeanGross what template are we talking about here? The delta template that compares two exports?

**Comment by DeanGross** [comment]
I was trying to create an Excel or HTML report from the file that was created by the export configuration command.

**Comment by NikCharlebois** [comment]
Thanks, any chance you could share the content of the configuration file that was extracted, or at least confirm that the export is not empty (inside the "Node localhost")?

**Comment by DeanGross** [comment]
It is not empty, it has data for EXOAcceptedDomain, EXOAntiPhishPolicy, EXOAntiPhishRule and much more, the file is 250 kb,

**Comment by NikCharlebois** [comment]
Ok, when you run the New-M365DSCReportFromConfiguration cmdlet to generate the report, do you see a progress bar loading which would indicate that the parsing process is underway, or nothing happens? Is the command throwing any errors?

**Comment by DeanGross** [comment]
Yes, i see the parsing progress indicator, i just noticed this error {
	"resource": "/c:/Users/dgross/OneDrive - Insight/Scripts/Output/M365TenantConfig.ps1",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Missing closing '}' in statement block or type definition.",
	"source": "PowerShell",
	"startLineNumber": 10,
	"startColumn": 1,
	"endLineNumber": 10,
	"endColumn": 2
}

**Comment by samdouglas77** [comment]
> Yes, i see the parsing progress indicator, i just noticed this error {
> "resource": "/c:/Users/dgross/OneDrive - Insight/Scripts/Output/M365TenantConfig.ps1",
> "owner": "_generated_diagnostic_collection_name_#0",
> "severity": 8,
> "message": "Missing closing '}' in statement block or type definition.",
> "source": "PowerShell",
> "startLineNumber": 10,
> "startColumn": 1,
> "endLineNumber": 10,
> "endColumn": 2
> }
Can I ask where you see this error?

I am having similar issue when trying to export the config to Excel and HTML - but dont get an error message it just appears to hang for html and open Excel with headers (component name, property, value) but no records and I'd like to check log file to help troubleshoot.

cheers

**Comment by DeanGross** [comment]
Sam, I see that error when I opent the M365TenantConfig.ps1 file in VisualStudioCode, it shows up on the Problems tab in the PowerShell terminal screen

**Comment by samdouglas77** [comment]
Really useful, thank you.  Will try the same.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MichaelLaMontagne** [comment]
I'm also seeing the New-m365dscreportfromconfiguration seem to hang, left it running for hours with no progress but was consuming 20% CPU. Had no issue with the cmdlet on a previous version of the m365dsc module.

**Comment by twj** [comment]
I also have the same issue like MicMichaelLaMontagne. I do not get any error, the excel file was created but not filled (only header).

**Comment by NikCharlebois** [comment]
Folks, the team would need you help isolating this issue. Are you able to filter your export, one workload at a time to try to isolate what exported resource is causing issues? For example, filter the exported config to keep only the EXO components, and try to generate the report. If that works, then move on to the Security and Compliance workload, etc. Anybody willing to help investigate this? Thanks

**Comment by twj** [comment]
Hi Nik, I did exported only the SPO components, and still the excel/html reports can not be generated. The progress bar even was not shown, and it hang. 
Today, i uninstall and remove the module, and install the previous version (1.0.5.128). With the version, I can generate the report in Excel without any issues. 
I will try to update it again, and see if I am facing the same issue again. I will let you know then. Thanks!

**Comment by twj** [comment]
![2020-07-01 18_49_41-M365TenantConfig ps1 - Visual Studio Code](https://user-images.githubusercontent.com/2351883/86270725-fae09980-bbcb-11ea-850c-7ef9f2a20c00.png)

I think, I find out the problem. If I add "Import-DSCResource -ModuleName Office365DSC" in the config file, then it works!

**Comment by NikCharlebois** [comment]
Thanks @twj However, this line is already present in every export. Can you confirm if you see it (as below) when doing an export on your end? Thanks

param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $GlobalAdminAccount
    )

    if ($null -eq $GlobalAdminAccount)
    {
        <# Credentials #>
        $Credsglobaladmin = Get-Credential -Message "Global Admin credentials"
    }
    else
    {
        $Credsglobaladmin = $GlobalAdminAccount
    }

    $OrganizationName = $Credsglobaladmin.UserName.Split('@')[1]
    **Import-DscResource -ModuleName Microsoft365DSC**

    Node localhost

**Comment by MichaelLaMontagne** [comment]
I have the line: Import-DscResource -ModuleName Microsoft365DSC so @twj's fix did not resolve my issue. Unless I should also install the older Office365DSC module.

**Comment by twj** [comment]
@Michael you should change the modulename on the line with "Office365DSC" instead of "Microsoft365DSC" (in config file ps1).

**Comment by NikCharlebois** [comment]
Trying to follow-up on this. Can any of you confirm that you still have the issue in the latest version released last thursday? 1.20.716.1
Thanks

**Comment by twj** [comment]
yes, it works with the latest version. I do not have the issue any more. Thanks a lot Nik!

**Comment by DeanGross** [comment]
no luck for me, still getting an empty excel file

**Comment by twj** [comment]
Hi @DeanGross, may be you have to remove the module first and then install and import the latest version again. Pls make sure, 
that you only have the latest version.

![image](https://user-images.githubusercontent.com/2351883/88260135-123f0e00-ccc4-11ea-9a1c-1d22f6c197ce.png)

**Comment by DeanGross** [comment]
@twj Danke, that solved the problem.

**Comment by MichaelLaMontagne** [comment]
Latest version solved it here also.

**Comment by grabery** [comment]
I'd like to pick up on this issue, since I have empty reports too and still. I am using Microsoft365DSC version 1.22.406.1
The command is running without any error, but does finish within 1 second and the report is empty, while the configuration-export (ps1) isn't...
Doesn't matter if I use html, excel or json export...

**Comment by golnebo** [comment]
Yes, same here. I use version 1.22.406.1. My export completed succesfully (the .ps1 file is 1,026kb). The command is running fine: `New-M365DSCReportFromConfiguration -type html -ConfigurationPath .\M365TenantConfig.ps1 -OutputPath .\Report.html` but the report.html only contains the header.

**Comment by golnebo** [comment]
> Yes, same here. I use version 1.22.406.1. My export completed succesfully (the .ps1 file is 1,026kb). The command is running fine: `New-M365DSCReportFromConfiguration -type html -ConfigurationPath .\M365TenantConfig.ps1 -OutputPath .\Report.html` but the report.html only contains the header.

Just here to solve my own problem, and for anyone who finds this. It is about Powershell versions. I was running the command in Powershell 7.2.2. That doesn't work. If you generate the report in Powershell 5.1 (or perhaps 7.0?) the report is generated as expected.

**Comment by peteramza** [comment]
I am on version 1.22.720.1 and reports are still coming out blank. Anyone else still having this issue?

**Comment by andikrueger** [comment]
Please make sure to run the following commands:

Update-M365DSCDependencies
Uninstall-M365DSCOutdatedDependencies

This should fix your current reports

**Comment by peteramza** [comment]
That did the trick! Thank you!
