### ISSUE TITLE
prompted for parameter value

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#641]
tried to get the security and compliance center configuration information
```powershell
# insert configuration here
```
PS C:\Users\dgross\OneDrive - Insight\Scripts> Export-M365DSCConfiguration -Quiet -Workloads @("SC")

Extracting [SCAuditConfigurationPolicy]...
cmdlet Export-TargetResource at command pipeline position 1
Supply values for the following parameters:
User: dean.gross@nsitsec.com
Password for user dean.gross@nsitsec.com: ********
WARNING: Your connection has been redirected to the following URI: "https://nam11b.ps.compliance.protection.outlook.com/Powershell-LiveId?BasicAuthToOAuthConversion=true&amp;HideBannerMessage=true;PSVersion=5.1.17134.858 "
Extracting [SCCaseHoldPolicy]...
cmdlet Export-TargetResource at command pipeline position 1
Supply values for the following parameters:
User:
#### Version of the DSC module that was used ('dev' if using current dev branch)
Microsoft365DSC version 1.20.603.1

**Comment by NikCharlebois** [comment]
@DeanGross try the following to see if it makes a difference:

$creds = Get-Credential
Export-M365DSCConfiguration -Quiet -Workloads @("SC") -GlobalAdminAccount $Creds
