### ISSUE TITLE
Export-M365 OD get struck

### ISSUE THREAD

**Issue by albandrod** [microsoft/Microsoft365DSC#644]
I recentyñy updated all the modules, but when I'm trying to export the M365 current configuration everything is going fine until it takes an eternity so export OneDrive configuration, after several hours, i cancelled the export.

**Comment by desmay** [comment]
Can you confirm you have SharePointPNPOnline module 3.22.2006.1 installed?

**Comment by Husky300TX** [comment]
I have the same issue and I can confirm that SharePointPNPOnline module 3.22.2006.1 is installed.

**Comment by NikCharlebois** [comment]
@albandrod can you please make sure you try the latest version of the module from GitHub. The last version on the PowerShell Gallery still uses the SharePoint Online Management Shell to export OD settings, whereas the new version on GitHub (yet to be published to the PowerShell Gallery) now leverages PnP. Thanks

**Comment by NikCharlebois** [comment]
@Husky300TX if you have a chance to try it as well, we'd appreciate it. Thanks

**Comment by albandrod** [comment]
Hi! Still not working... I have tried installing the new m365dsc module but I'm receiving the following error: 

PowerShell DSC resource MSFT_TeamsCallingPolicy  failed to execute Test-TargetResource functionality with error
message: Exception calling "GetResponse" with "0" argument(s): "The remote name could not be resolved:
'lyncdiscover.seidorqc.com'"
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

**Comment by NikCharlebois** [comment]
@Albandrod When doing the Export, are you using a '@[...].**onmicrosoft.com** email address? If not, could you give that a try and see if it fixes your issue? Thanks

**Comment by albandrod** [comment]
Hi @NikCharlebois I try it again, but the same... I have tried with a GA account without MFA and with @domain.com 

PS C:\WINDOWS\system32> Assert-M365DSCTemplate -TemplateName "Teams-M365Business-Baseline"
PowerShell DSC resource MSFT_TeamsCallingPolicy  failed to execute Test-TargetResource functionality with error
message: Exception calling "GetResponse" with "0" argument(s): "The remote name could not be resolved:
'lyncdiscover.domain.com'"
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

The environment does not match the template. The following component(s) are not in the Desired State:

Also, If I try the other Blueprint available:

PS C:\WINDOWS\system32> Assert-M365DSCTemplate -TemplateName "SPO-M365Business-Baseline"
PowerShell DSC resource MSFT_SPOSiteGroup  failed to execute Test-TargetResource functionality with error message: The
specified site collection doesn't exist.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

The environment does not match the template. The following component(s) are not in the Desired State:

Any clue? I'm able to connect and export the configuration, but the assert I think that it is a very good feature...

**Comment by NikCharlebois** [comment]
@albandrod the Assert-M365DSCTemplate cmdlet has been deprecated in favor of the new Assert-M365DSCBlueprint cmdlet. Please refer to the following wiki page: https://github.com/microsoft/Microsoft365DSC/wiki/How-to-Create-a-M365DSC-Blueprint

Or Video: https://www.youtube.com/watch?v=UE-nRdZ4iJk

To learn more about it. Let us know if you have further questions. Thanks

**Comment by albandrod** [comment]
@NikCharlebois I tried but same luck...

PS C:\Users\user\Downloads> Assert-M365DSCBlueprint -BluePrintUrl ".\Teams-M365Business-Baseline.M365" -OutputReportPath "C:\"

cmdlet Assert-M365DSCBlueprint at command pipeline position 1
Supply values for the following parameters:
Credentials
Selected BluePrint contains (15) components to assess.
Initiating the Export of those (15) components from the tenant...
[1/15] Extracting [TeamsCallingPolicy]...Get-RTCXml : Exception calling "GetResponse" with "0" argument(s): "The remote name could not be resolved:
'lyncdiscover.domain.com'"
At C:\Program Files\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.32\MSCloudLoginAssistant.psm1:460 char:12
+     $xml = Get-RTCXml -Url $liveIdUrl
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-RTCXml], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Get-RTCXml

**Comment by NikCharlebois** [comment]
Related to #782
