### ISSUE TITLE
Cannot process argument transformation on parameter 'FreeBusyAccessScope'

### ISSUE THREAD

**Issue by alesag** [microsoft/Microsoft365DSC#645]
Hi,
On EXOOrganizationRelationship it seems that the parameter FreeBusyAccessScope is always passed even if it is not specified. I have also try to specify it with the $null value but I get the same error message:

Cannot process argument transformation on parameter 'FreeBusyAccessScope'. Cannot convert value "" to type
"Microsoft.Exchange.Configuration.Tasks.GroupIdParameter". Error: "Parameter values of type
Microsoft.Exchange.Configuration.Tasks.GroupIdParameter can't be empty. Specify a value, and try again.
Parameter name: identity"
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-OrganizationRelationship
    + PSComputerName        : localhost

This parameter is not mandatory and should be blank if you want the Organization relationship to be available for all users.

Thanks,

Aurélien

**Comment by alesag** [comment]
Many Thanks, it worked for this attribute but I in fact I had the same issue with other parameters  (MailTipsAccessScope and TargetOWAURL).
It would probably be interesting to only provision the params tables with the attributes that are set on the config file for all resources like this to prevent that kind of issue:

$NewOrganizationRelationshipParams = @{
        Confirm               = $false
    }
    if ($ArchiveAccessEnabled) {$NeworganizationRelationshipParams.ArchiveAccessEnabled = $ArchiveAccessEnabled}
    if ($DeliveryReportEnabled) {$NeworganizationRelationshipParams.DeliveryReportEnabled = $DeliveryReportEnabled}
    if ($DomainNames) {$NeworganizationRelationshipParams.DomainNames = $DomainNames}
    if ($Enabled) {$NeworganizationRelationshipParams.Enabled = $Enabled}
    if ($FreeBusyAccessScope) {$NeworganizationRelationshipParams.FreeBusyAccessScope = $FreeBusyAccessScope}
    if ($MailboxMoveEnabled) {$NeworganizationRelationshipParams.MailboxMoveEnabled = $MailboxMoveEnabled}
    if ($MailTipsAccessEnabled) {$NeworganizationRelationshipParams.MailTipsAccessEnabled = $MailTipsAccessEnabled}
    if ($MailTipsAccessLevel) {$NeworganizationRelationshipParams.MailTipsAccessLevel = $MailTipsAccessLevel}
    if ($MailTipsAccessScope) {$NeworganizationRelationshipParams.MailTipsAccessScope = $MailTipsAccessScope}
    if ($Name) {$NeworganizationRelationshipParams.Name = $Name}
    if ($OrganizationContact) {$NeworganizationRelationshipParams.OrganizationContact = $OrganizationContact}
    if ($PhotosEnabled) {$NeworganizationRelationshipParams.PhotosEnabled = $PhotosEnabled}
    if ($TargetApplicationUri) {$NeworganizationRelationshipParams.TargetApplicationUri = $TargetApplicationUri}
    if ($TargetAutodiscoverEpr) {$NeworganizationRelationshipParams.TargetAutodiscoverEpr = $TargetAutodiscoverEpr}
    if ($TargetOwaURL) {$NeworganizationRelationshipParams.TargetOwaURL = $TargetOwaURL}
    if ($TargetSharingEpr) {$NeworganizationRelationshipParams.TargetSharingEpr = $TargetSharingEpr}

    $SetOrganizationRelationshipParams = @{
        Confirm               = $false
    }
    if ($ArchiveAccessEnabled) {$SetorganizationRelationshipParams.ArchiveAccessEnabled = $ArchiveAccessEnabled}
    if ($DeliveryReportEnabled) {$SetorganizationRelationshipParams.DeliveryReportEnabled = $DeliveryReportEnabled}
    if ($DomainNames) {$SetorganizationRelationshipParams.DomainNames = $DomainNames}
    if ($Enabled) {$SetorganizationRelationshipParams.Enabled = $Enabled}
    if ($FreeBusyAccessScope) {$SetorganizationRelationshipParams.FreeBusyAccessScope = $FreeBusyAccessScope}
    if ($MailboxMoveEnabled) {$SetorganizationRelationshipParams.MailboxMoveEnabled = $MailboxMoveEnabled}
    if ($MailTipsAccessEnabled) {$SetorganizationRelationshipParams.MailTipsAccessEnabled = $MailTipsAccessEnabled}
    if ($MailTipsAccessLevel) {$SetorganizationRelationshipParams.MailTipsAccessLevel = $MailTipsAccessLevel}
    if ($MailTipsAccessScope) {$SetorganizationRelationshipParams.MailTipsAccessScope = $MailTipsAccessScope}
    if ($Name) {$SetorganizationRelationshipParams.Name = $Name}
    if ($OrganizationContact) {$SetorganizationRelationshipParams.OrganizationContact = $OrganizationContact}
    if ($PhotosEnabled) {$SetorganizationRelationshipParams.PhotosEnabled = $PhotosEnabled}
    if ($TargetApplicationUri) {$SetorganizationRelationshipParams.TargetApplicationUri = $TargetApplicationUri}
    if ($TargetAutodiscoverEpr) {$SetorganizationRelationshipParams.TargetAutodiscoverEpr = $TargetAutodiscoverEpr}
    if ($TargetOwaURL) {$SetorganizationRelationshipParams.TargetOwaURL = $TargetOwaURL}
    if ($TargetSharingEpr) {$SetorganizationRelationshipParams.TargetSharingEpr = $TargetSharingEpr}

**Comment by ahohenschuh** [comment]
Hey @alesag, thank you for your suggestions. I will incorporate them in the next fix!

**Comment by PrzemyslawKlys** [comment]
@ahohenschuh before you go ahead please visit - https://github.com/microsoft/Microsoft365DSC/issues/653 which talks about how to do it properly. It's the same issue, but this issue will be visible everywhere splat is used. 

We also need to use `[string]::IsNullOrEmpty(...)` instead of `if ($Value)` because if value would be $false or 0 it wouldn't execute. And we don't want splat to be set only in case value is missing.
