### ISSUE TITLE
A parameter cannot be found that matches parameter name 'NpsMailboxPolicy'

### ISSUE THREAD

**Issue by alesag** [microsoft/Microsoft365DSC#646]
Hi,
I am using version 1.20.603.1.
I get the following error with resource EXOOwaMailboxPolicy:

A parameter cannot be found that matches parameter name 'NpsMailboxPolicy'.
    + CategoryInfo          : InvalidArgument: (:) [], CimException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-OwaMailboxPolicy
    + PSComputerName        : localhost

The PowerShell DSC resource '[EXOOwaMailboxPolicy]46eefad0-7568-4efb-91a6-a7ebff075763' with SourceInfo
'C:\M365DSC\Exch5\M365TenantConfig.ps1::459::9::EXOOwaMailboxPolicy' threw one or more non-terminating errors while
running the Set-TargetResource functionality. These errors are logged to the ETW channel called
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

It seems that this parameter is no longer available. It also seems that the resource try to pass it even if I do not specify it.

Thanks

Aurélien

**Comment by NikCharlebois** [comment]
@ahohenschuh Can you please have a look? Thanks

**Comment by alesag** [comment]
For info I have solved the issue by making this parameter optional on the DSC resource. I only add it to the params table if the parameter exists on the config file.

**Comment by PrzemyslawKlys** [comment]
Updated MS docs: https://github.com/MicrosoftDocs/office-docs-powershell/pull/6073

Still requires a fix in Microsoft365DSC
