### ISSUE TITLE
Authentication questions

### ISSUE THREAD

**Issue by alesag** [microsoft/Microsoft365DSC#652]
Hi,
Is it planned to switch to modern authentication as MS will deprecate basic auth? It was postponed to next year but I don't think that it will be postponed again.
Additionnaly is there an option to encrypt the user's password on the mof file? It is currently in clear text which is not really safe.
Thanks
Aurélien

**Comment by NikCharlebois** [comment]
Bonjour Aurelien,

Please refer to the following video to learn how to secure your mof files. Thanks
https://www.youtube.com/watch?v=SCZv79wZNh0

We are definitively planning to switch to modern auth. We are currently dependent on the sub-modules (Exchange Online, SkypeforBusiness, etc.). Once those support Modern Auth, then we will add the support for these workloads in M365DSC as well. Currently, only Teams (core team), SharePoint and AzureAD supports authenticating with Modern Auth.

**Comment by mczerniawski** [comment]
I know this been closed for long now. Exchange also support modern auth now, yet still the release version uses old EXO module and requires basic auth to be enabled. 
I have a script that triggers the registry entry, runs the scan and reverts it back but that's not ideal:(

Any plans to adding EXO v2 to the DSC module?
