### ISSUE TITLE
System.Object[] error when creating a deleted team

### ISSUE THREAD

**Issue by CFStephenHale** [microsoft/Microsoft365DSC#659]
#### Details of the scenario you tried and the problem that is occurring
99% of the time I am unable to perform a restore of the DSC to work. I have tried from one trial tenant to the same trial tenant. From one trail tenant to another trial tenant. I have tried to and from my personal tenant to and from a trial tenant. I even tried from my personal tenant back to my personal tenant and it is failing to create a team that was deleted in the past. I even tried the Start-DSCConfiguration twice because that is a known issue and doesn’t work. This worked once a few weeks ago and the verbos logging said it found the deleted team in the recycle bin and was able to restore it. I have also tried this on 3 different computers with fresh module installs on each. I have also validated the global admin account performing the restore does not have 2fa enabled. Thank you for your help with this.

Moule version: 1.20.603.1

My process
1.	Install-Module Microsoft365DSC -Force -AllowClobber -Scope AllUsers
2.	Import-Module Microsoft365DSC -Force
3.	Set-M365DSCTelemetryOption -Enabled $False
4.	Set GPO to bypass IE first launch
5.	Made sure WinRM service was running.
6.	Export-M365DSCConfiguration -Path 'C:\DSC' -GlobalAdminAccount $Credentials -Quiet -ComponentsToExtract TeamsTeam
7.	CD C:\DSC
8.	.\M365TenantConfig.ps1
9.	Start-DscConfiguration -Wait -Verbose -Force M365TenantConfig
10.	Test-DscConfiguration -Detailed
11.	Deleted Team “TestTeamDSC”
12.	Test-DscConfiguration -Detailed #Validated no longer in DSC
13.	Start-DscConfiguration -Wait -Verbose -Force -UseExisting #Failed to Create team.

#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/67703916/86271210-1f1f8480-bb92-11ea-9429-7ae633fe0df0.png)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# Generated with Microsoft365DSC version 1.20.603.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $GlobalAdminAccount
)

Configuration M365TenantConfig
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $GlobalAdminAccount
    )

    if ($null -eq $GlobalAdminAccount)
    {
        <# Credentials #>
        $Credsglobaladmin = Get-Credential -Message "Global Admin credentials"
    }
    else
    {
        $Credsglobaladmin = $GlobalAdminAccount
    }

    $OrganizationName = $Credsglobaladmin.UserName.Split('@')[1]
    Import-DscResource -ModuleName Microsoft365DSC

    Node localhost
    {
        TeamsTeam 67f45367-3e23-4aba-b5d4-50b88be55f23
        {
            AllowAddRemoveApps                = $True;
            AllowChannelMentions              = $True;
            AllowCreateUpdateChannels         = $True;
            AllowCreateUpdateRemoveConnectors = $True;
            AllowCreateUpdateRemoveTabs       = $True;
            AllowCustomMemes                  = $True;
            AllowDeleteChannels               = $True;
            AllowGiphy                        = $True;
            AllowGuestCreateUpdateChannels    = $False;
            AllowGuestDeleteChannels          = $False;
            AllowOwnerDeleteMessages          = $True;
            AllowStickersAndMemes             = $True;
            AllowTeamMentions                 = $True;
            AllowUserDeleteMessages           = $True;
            AllowUserEditMessages             = $True;
            Description                       = "TestTeamDSC";
            DisplayName                       = "TestTeamDSC";
            Ensure                            = "Present";
            GiphyContentRating                = "moderate";
            GlobalAdminAccount                = $Credsglobaladmin;
            MailNickName                      = "TestTeamDSC";
            Owner                             = "user1@$OrganizationName";
            Visibility                        = "Private";
        }
    }
}
M365TenantConfig -ConfigurationData .\ConfigurationData.psd1 -GlobalAdminAccount $GlobalAdminAccount 

```

#### The operating system the target node is running
Brand new VM only used for this process
![image](https://user-images.githubusercontent.com/67703916/86271681-f350ce80-bb92-11ea-95ad-c9bbd441567b.png)

![image](https://user-images.githubusercontent.com/67703916/86271798-272bf400-bb93-11ea-8e6f-4bfdbb10bd3b.png)

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.20.603.1

**Comment by NikCharlebois** [comment]
@CFStephenHale Are you still able to replicate this issue using the latest version? The team has not been able to Repro unfortunately.
