### ISSUE TITLE
Unable to find "Set-M365DSCAgentCertificateConfiguration"

### ISSUE THREAD

**Issue by bubbletroubles** [microsoft/Microsoft365DSC#660]
The youtube video "Episode 016 - Securing your M365DSC Configuration" at https://www.youtube.com/watch?v=SCZv79wZNh0 talks about using the Set-M365DSCAgentCertificateConfiguration command to encrypt the mof file credentials. 

However I can't find it in the dev or master branch. Is it released yet?

**Comment by NikCharlebois** [comment]
It is in the dev branch on GitHub. 
https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1#L1466

If you can't access it, then make sure the proper version of the M365DSC module is currently loaded in your PowerShell session.

**Comment by NikCharlebois** [comment]
@bubbletroubles are you still having this issue with the latest version? Thanks
