### ISSUE TITLE
Error exporting tenant configuration with Global Reader privileges.

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#665]
When attempting to export a tenant configuration (plain vanilla, no customizations done) with 
`Export-M365DSCConfiguration -Quiet -GlobalAdminAccount $creds `
it reports "VERBOSE: Logging a new Error" on screen and several errors similar to
```
{NotImplemented}
System.NotSupportedException: The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.VerifyInternetExplorerAvailable(Boolean checkComObject)
   at Microsoft.PowerShell.Commands.InvokeWebRequestCommand.ProcessResponse(WebResponse response)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
"MSFT_EXOAcceptedDomain.psm1"
``` 
in the error log.
The use account used to create the export has no licenses assigned but Global Reader privileges.

I guess the interesting part of the error message is "The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again."

**Comment by desmay** [comment]
@SebastianGoers Take a look at this thread for fix - https://github.com/microsoft/Microsoft365DSC/issues/637

**Comment by SebastianGoers** [comment]
Many thanks @desmay . This has solved the issue.
