### ISSUE TITLE
SPO: Error exporting SPOAccessControlSettings + more.

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#666]
#### Details of the scenario you tried and the problem that is occurring
Trying to export a tenant configuration from a newly created O365 tenant as reference configuration. User account has global admin privileges, however, SPOAccessControlSettings export reports that the user is not a tenant admin.
#### Verbose logs showing the problem
```
Extracting [SPOAccessControlSettings]...
Get-PNPTenant : Current user is not a tenant administrator.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.603.1\DSCResources\MSFT_SPOAccessControlSettings\MSF
T_SPOAccessControlSettings.psm1:94 char:37
+         $SPOAccessControlSettings = Get-PNPTenant
+                                     ~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPTenant], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Admin.GetTenant
Extracting [SPOApp]...
    * App Catalog is not configured on tenant. Cannot extract information about SharePoint apps.
Extracting [SPOHomeSite]...
Get-PnPHomeSite : Current user is not a tenant administrator.
At C:\Program
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.603.1\DSCResources\MSFT_SPOHomeSite\MSFT_SPOHomeSite.psm1:40
char:24
+         $homeSiteUrl = Get-PnPHomeSite
+                        ~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPHomeSite], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Admin.GetHomeSite
Extracting [SPOHubSite]...
Get-PnPHubSite : Current user is not a tenant administrator.
At C:\Program
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.603.1\DSCResources\MSFT_SPOHubSite\MSFT_SPOHubSite.psm1:469
char:17
+     $hubSites = Get-PnPHubSite
+                 ~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPHubSite], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Admin.GetHubSite
Extracting [SPOOrgAssetsLibrary]...
Get-PnPOrgAssetsLibrary : Current user is not a tenant administrator.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.603.1\DSCResources\MSFT_SPOOrgAssetsLibrary\MSFT_SPO
OrgAssetsLibrary.psm1:262 char:18
+     $orgAssets = Get-PnPOrgAssetsLibrary
+                  ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPOrgAssetsLibrary], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Admin.GetOrgAssetsLibrary
```
#### Suggested solution to the issue
None, yet.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```N/A trying to export config with Export-M365DSCConfiguration -Quiet -GlobalAdminAccount $creds
# insert configuration here
```

#### The operating system the target node is running

OsName               :
OsOperatingSystemSKU :
OsArchitecture       :
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           :
OsMuiLanguages       :

#### Version of the DSC module that was used ('dev' if using current dev branch)
prod

**Comment by SebastianGoers** [comment]
The Dev Branch is having the same issue. 

The issue actually occures @ ODSettings after it prompts for username / password.

**Comment by desmay** [comment]
@SebastianGoers This maybe an issue with SPO PNP. Do you get same message if you do the following and connecting with the same account:

Connect-PNPOnline -url XXXX
Get-PNPTenant

**Comment by SebastianGoers** [comment]
@desmay : Trying this I get 
Connect-PNPOnline : The sign-in name or password does not match one in the Microsoft account system.
At line:1 char:1
+ Connect-PNPOnline -url https://*****.sharepoint.com
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], IdcrlException
    + FullyQualifiedErrorId : Microsoft.SharePoint.Client.IdcrlException,SharePointPnP.PowerShell.Commands.Base.Connec
   tOnline

However, I can log in to SPO using the very same account (global admin). On another tenant it seems to work just fine. Investigating the account setup ...

**Comment by NikCharlebois** [comment]
@SebastianGoers The account is MFA enabled I assume? Is this a Public Cloud account or for a different cloud? (E.g. Germany, GCC, GCCHigh) Thanks

**Comment by SebastianGoers** [comment]
Hi @NikCharlebois , this is the Public Cloud and no, the account is not MFA enabled. I will give it another try today.

**Comment by NikCharlebois** [comment]
Fixed by recent releases of the MSCloudLoginAssistant module
