### ISSUE TITLE
SCSenstivityLabel - Priority isn't set

### ISSUE THREAD

**Issue by bubbletroubles** [microsoft/Microsoft365DSC#669]
#### Details of the scenario you tried and the problem that is occurring

Using the SCSensitivityLabel resource, the priority isn't set, even though its defined in the DSC configuration. This throws an error.

#### Verbose logs showing the problem
```
2020-07-10T20:21:26.0434187Z PowerShell DSC resource MSFT_SCSensitivityLabel  failed to execute Set-TargetResource functionality with error 
2020-07-10T20:21:26.0434921Z message: SCSensitivityLabel can't set Priortity property on new label {Label1601} to 
2020-07-10T20:21:26.0435614Z System.Management.Automation.PSBoundParametersDictionary.Priority.You will need to set priority property once label is 
2020-07-10T20:21:26.0435996Z created. 
2020-07-10T20:21:26.0436331Z     + CategoryInfo          : InvalidOperation: (:) [], CimException
2020-07-10T20:21:26.0436650Z     + FullyQualifiedErrorId : ProviderOperationExecutionFailure
2020-07-10T20:21:26.0437241Z     + PSComputerName        : localhost

```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
 SCSensitivityLabel Label1
        {
            AdvancedSettings     = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'tooltip for Label1'
                    Value = 'Label1 data'
                }
            );
            Comment              = "";
            Disabled             = $False;
            DisplayName          = "Label1601am";
            Ensure               = "Present";
            GlobalAdminAccount   = $GlobalAdmin;
            LocaleSettings       = @(
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'displayName'
                    Settings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'Label1601'
                            Value = 'Label1601'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    Settings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'Label1601'
                            Value = 'Label1601'
                        }
                    )
                }
            );
            Name                 = "Label1601";
            Priority             = 1;
            Tooltip              = "Label1 data601";
        }
```

#### The operating system the target node is running

Microsoft hosted build agent, windows-2019
#### Version of the DSC module that was used ('dev' if using current dev branch)
1.20.603.1

**Comment by bubbletroubles** [comment]
Is the issue that in the file https://github.com/microsoft/Microsoft365DSC/blob/cf19a7db93c5392cb147ec19bda8efb73be0bb99/Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.psm1, the line        ` $CreationParams.Remove("Priority")`
 is present?

**Comment by desmay** [comment]
We should probably only display a message instead of throwing error when priority is passed in on creating a new label.

**Comment by bubbletroubles** [comment]
@desmay - Would the current error prevent the label from been created? With the code block above, the label is never created and I just get the error about priority.

**Comment by desmay** [comment]
@bubbletroubles  it would prevent it from being created. For a workaround you could remove Priority from configure file and it should create the label. 

@NikCharlebois assign this bug to me and I’ll fix issue

**Comment by desmay** [comment]
@bubbletroubles Can you try again with latest dev branch ?

**Comment by bubbletroubles** [comment]
@desmay I need to get the dev branch working via Azure DevOps to test - that issue is raised as #699

**Comment by NikCharlebois** [comment]
@bubbletroubles any luck installing the latest version of the tool from the gallery and confirming if it works?
