### ISSUE TITLE
Multiple versions found

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#685]
Installing the latest release version and compiling a configuration the following error occurs:
```
.\M365TenantConfig.ps1
At C:\***\M365TenantConfig.ps1:28 char:5
+     Import-DscResource -ModuleName Microsoft365DSC
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Multiple versions of the module 'Microsoft365DSC' were found. You can run 'Get-Module -ListAvailable
-FullyQualifiedName Microsoft365DSC' to see available versions on the system, and then use the fully qualified name
'@{ModuleName="Microsoft365DSC"; RequiredVersion="Version"}'.

```
Please note that I have previously removed all versions and then did a clean install.

```
 Get-Module -ListAvailable -FullyQualifiedName 'Microsoft365DSC'


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.20.716.1 Microsoft365DSC                     {Assert-M365DSCTemplate, Compare-M365DSCConfigurations, Ex...
Manifest   1.20.716.1 Microsoft365DSC                     {Assert-M365DSCTemplate, Compare-M365DSCConfigurations, Ex...


```

**Comment by SebastianGoers** [comment]
In the modules folder it looks like this:
![image](https://user-images.githubusercontent.com/59373302/87762904-20001980-c814-11ea-9eab-87b30fbb0eda.png)

**Comment by NikCharlebois** [comment]
@SebastianGoers You are getting this just by running Install-Module?

**Comment by SebastianGoers** [comment]
I installed the Module using Install-Module and then I updated to the dev branch.

**Comment by NikCharlebois** [comment]
@SebastianGoers Are you still seeing the same strange behavior with the latest version? Thanks

**Comment by Jimnar** [comment]
@NikCharlebois I'm seeing the same issue @SebastianGoers describes with respect to multiple. I tried to uninstall older versions of M365DSC, but one version refuses to uninstall.

PS C:\WINDOWS\system32> get-module -name microsoft365dsc -list


    Directory: C:\Users\jimna\onedrive\Documents\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.20.603.1 Microsoft365DSC                     {Assert-M365DSCTemplate, Compare-M365DSCConfigurations, Ex...


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.20.805.1 Microsoft365DSC                     {Assert-M365DSCBlueprint, Assert-M365DSCTemplate, Compare-...
Manifest   1.20.603.1 Microsoft365DSC                     {Assert-M365DSCTemplate, Compare-M365DSCConfigurations, Ex...
Manifest   1.20.603.1 Microsoft365DSC                     {Assert-M365DSCTemplate, Compare-M365DSCConfigurations, Ex...


PS C:\WINDOWS\system32> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...


PS C:\WINDOWS\system32> get-installedmodule microsoft365dsc

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.20.603.1           Microsoft365DSC                     PSGallery            This DSC module is used to configure a...


PS C:\WINDOWS\system32> uninstall-module microsoft365dsc
PackageManagement\Uninstall-Package : Access to the cloud file is denied
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.3\PSModule.psm1:12657 char:21
+ ...        $null = PackageManagement\Uninstall-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Package],
   Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand,Mic
   rosoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage

PS C:\WINDOWS\system32>

**Comment by Jimnar** [comment]
@NikCharlebois I'm seeing the same issue @SebastianGoers describes with respect to multiple versions found. However, when I tried to uninstall older versions of M365DSC, one version refuses to uninstall with an "Access to the cloud file is denied" error. I cannot help but think it might have something to do with OneDrive.

![image](https://user-images.githubusercontent.com/10016605/92037646-f4cf7c00-ed26-11ea-8a3e-74e64c6796e0.png)

**Comment by NikCharlebois** [comment]
@Jimnar in your case it appears that this is due to the module being installed in different locations (not sure why, but the Install-Module path should normally be set to C:\Program Files\WindowsPowerShell\Modules). @SebastianGoers your issue is caused by the Install-M365DSCDevBranch method which doesn't properly trim 0's in front of release versions. a PR is on its way to fix this :)
