### ISSUE TITLE
Exporting Teams configuration wrongly assumes tenant to be in Germany Cloud

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#686]
#### Details of the scenario you tried and the problem that is occurring
When running the tenant configuration export with a user account ending on ".de" the script wrongly assumes that the tenant is in the Germany cloud and thus it reports:
WARNING: Microsoft Teams is not supported in the Germany Cloud

Changing the UPN to tenantname.onmicrosoft.com solves the issue. 
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by NikCharlebois** [comment]
This seems like a bug in the MSCloudLoginAssistant dependency (https://GitHub.com/Microsoft/MSCloudLoginAssistant). I will investigate.

**Comment by SebastianGoers** [comment]
As a workaround I changed the UPN to its onmicrosoft.com equivalent. This solves the issue as this UPN ends on .com .

**Comment by jeff29922** [comment]
@NikCharlebois where are we with this Teams bug?

**Comment by NikCharlebois** [comment]
@jeff29922 now that we are using the new combined MicrosoftTeams module can you look at why the .onmicrosoft.com domain is still required? This may require us to use the -OverrideAdminDomain switch on the New-CSOnlineSession cmdlet.

**Comment by jeff29922** [comment]
@NikCharlebois Ok I will grab this.

**Comment by NikCharlebois** [comment]
Fixed with recent releases of the MSCloudLoginAssistant module.
