### ISSUE TITLE
EXOApplicationAccessPolicy: Can't find OU

### ISSUE THREAD

**Issue by MarinoValentino** [microsoft/Microsoft365DSC#687]
#### Details of the scenario you tried and the problem that is occurring
`Export-M365DSCConfiguration -Workloads EXO -Path $path -Quiet -GlobalAdminAccount $creds`

#### Verbose logs showing the problem
```
[7/41] Extracting [EXOApplicationAccessPolicy]...Der Vorgang konnte nicht ausgeführt werden, weil das Objekt 'OU=<tenantname>.onmicrosoft.com,OU=Microsoft Exchange Hosted
Organizations,DC=EURPR05A011,DC=PROD,DC=OUTLOOK,DC=COM\*' nicht auf 'DB7PR05A11DC004.EURPR05A011.PROD.OUTLOOK.COM'
gefunden wurde.
At C:\Users\user1\AppData\Local\Temp\tmp_dgxdysx3.z4z\tmp_dgxdysx3.z4z.psm1:8093 char:9
+         $steppablePipeline.End()
+         ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ApplicationAccessPolicy], ManagementObjectNotFoundException
    + FullyQualifiedErrorId : [Server=HE1PR0501MB2363,RequestId=10a9065c-4566-4cdf-afb5-0035e6c49a40,TimeStamp=19.07.2
   020 15:48:28] [FailureCategory=Cmdlet-ManagementObjectNotFoundException] 557A3714,Microsoft.Exchange.Management.Sy
  stemConfigurationTasks.ApplicationAccessPolicy.GetApplicationAccessPolicy
```
#### Suggested solution to the issue
N/A
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A (Export)
#### The operating system the target node is running

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-Bit
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}
#### Version of the DSC module that was used ('dev' if using current dev branch)
1.20.716.1

**Comment by NikCharlebois** [comment]
@MarinoValentino is the tenant's name ending with .com or .de? Thanks

**Comment by MarinoValentino** [comment]
@NikCharlebois no, it's "onmicrosoft.com" with some custom domains

**Comment by NikCharlebois** [comment]
This has been fixed with recent releases of the solution.
