### ISSUE TITLE
TeamsMeetingsPolicy: Invalid value combination AutoAdmittedUsers: Everyone and AllowPSTNUsersToBypassLobby: False

### ISSUE THREAD

**Issue by AzureStackNerd** [microsoft/Microsoft365DSC#689]
#### Details of the scenario you tried and the problem that is occurring
I set the the following TeamsMeetingsPolicy setting in the DSC file, compiled it to a mof and started the configuration:
AutoAdmittedUsers                          = "Everyone";
#### Verbose logs showing the problem
![image](https://user-images.githubusercontent.com/12624821/87932680-31535b00-ca8c-11ea-9ba8-129d57b8f361.png)

#### Suggested solution to the issue
Add "AllowPSTNUsersToBypassLobby" to the schema and parameters. (Tested it and it works)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
TeamsMeetingPolicy 937f818d-74bd-46ed-96ba-c2a2d1ef0ca1
        {
            AllowAnonymousUsersToStartMeeting          = $False;
            AllowChannelMeetingScheduling              = $True;
            AllowCloudRecording                        = $True;
            AllowExternalParticipantGiveRequestControl = $False;
            AllowIPVideo                               = $True;
            AllowMeetNow                               = $True;
            AllowOutlookAddIn                          = $True;
            AllowParticipantGiveRequestControl         = $True;
            AllowPowerPointSharing                     = $True;
            AllowPrivateMeetingScheduling              = $True;
            AllowSharedNotes                           = $True;
            AllowTranscription                         = $False;
            AllowWhiteboard                            = $True;
            #AllowPSTNUsersToBypassLobby                = $False;
            AutoAdmittedUsers                          = "Everyone";
            Ensure                                     = "Present";
            GlobalAdminAccount                         = $Credsglobaladmin;
            Identity                                   = "Global";
            MediaBitRateKb                             = 50000;
            ScreenSharingMode                          = "EntireScreen";
```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}
#### Version of the DSC module that was used ('dev' if using current dev branch)
Version: 1.20.716.1

**Comment by NikCharlebois** [comment]
@AzureStackNerd Thanks for the PR! We really appreciate you helping out!
