### ISSUE TITLE
EXOAcceptedDomain: response content cannot be parsed because the Internet Explorer engine is not available

### ISSUE THREAD

**Issue by Kikaider** [microsoft/Microsoft365DSC#693]
#### Details of the scenario you tried and the problem that is occurring
Extracted using workload EXO and tried to apply to a different tenant. Got several instance of the this error:

PowerShell DSC resource MSFT_EXOAcceptedDomain  failed to execute Test-TargetResource functionality with error message: The response content cannot be parsed because the Internet Explorer engine is not available, or Internet 
Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

Internet Explorer has been run before.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
TBD

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
EXOAcceptedDomain e7886da3-ab62-4e35-9373-8d4608ea4300
        {
            DomainType           = "Authoritative";
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Identity             = "people.contoso.com";
            MatchSubDomains      = $False;
            OutboundOnly         = $False;
        }

#### The operating system the target node is running
O365 GCC

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.20.603.1

**Comment by NikCharlebois** [comment]
Hi Rob,

Please refer to the following thread for a fix. 
https://github.com/microsoft/Microsoft365DSC/issues/637

**Comment by Kikaider** [comment]
That worked!

PS - my bad for searching using "is:open". Doh!
