### ISSUE TITLE
ResourceName : New install - still prompting for module update

### ISSUE THREAD

**Issue by DeanGross** [microsoft/Microsoft365DSC#697]
#### Details of the scenario you tried and the problem that is occurring
I updated the M365DSC module today and when Extracting ODSettings, i got a message that  a newer version of PnP powershell is available: 3.23.2007.1. 
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.20716.1

**Comment by NikCharlebois** [comment]
@DeanGross this is expected. It is only a warning and it's controlled by the PnP team and not the M365DSC team.
