### ISSUE TITLE
Export-M365DSCConfiguration -Quiet fails at Extracting [EXOApplicationAccessPolicy]

### ISSUE THREAD

**Issue by DavidCloudSide** [microsoft/Microsoft365DSC#702]
#### Details of the scenario you tried and the problem that is occurring

     When I run the following command, the script fails at Extracting [EXOApplicationAccessPolicy]
    Command: Export-M365DSCConfiguration -Quiet -GlobalAdminAccount $creds
    Error: Der Vorgang konnte nicht ausgeführt werden, weil das Objekt 'OU=HIDDEN.onmicrosoft.com,OU=Microsoft 
    Exchange Hosted 
    Organizations,DC=HIDDEN,DC=PROD,DC=OUTLOOK,DC=COM\*' nicht auf 
    'HIDDEN.HIDDEN.PROD.OUTLOOK.COM' gefunden wurde.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Business
OsOperatingSystemSKU : 48
OsArchitecture       : 64-Bit
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : de-DE
OsMuiLanguages       : {de-DE, en-US}

**Comment by NikCharlebois** [comment]
Are you able to run:

Connect-ExchangeOnline -Credential $creds

Do you get the same error? Thanks

**Comment by DavidCloudSide** [comment]
Good morning

Running the command ‘Connect-ExchangeOnline -Credential $creds’ doesn’t end in an error. But I get the information about more reliable cmdlets.

I had some more troubles with other Modules:
o    EXOApplicationAccessPolicy (already reported)
o    EXOInboundConnector
o    Planner --> All

This was when I run with the GUI.
I will try it with the dev-version of the module as a next step.

Kind regards
David Hürlimann

Von: Nik Charlebois <notifications@github.com>
Gesendet: Sonntag, 26. Juli 2020 14:47
An: microsoft/Microsoft365DSC <Microsoft365DSC@noreply.github.com>
Cc: David Hürlimann <david.huerlimann@cloudside.ch>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/Microsoft365DSC] Export-M365DSCConfiguration -Quiet fails at Extracting [EXOApplicationAccessPolicy] (#702)


Are you able to run:

Connect-ExchangeOnline -Credential $creds

Do you get the same error? Thanks

**Comment by SebastianGoers** [comment]
Same issue here. Running the latest prod version of M365DSC.

**Comment by JeffBor** [comment]
@DavidCloudSide Check your `winrm` settings as noted in https://docs.microsoft.com/en-us/powershell/exchange/exchange-online-powershell-v2?view=exchange-ps#install-and-maintain-the-exo-v2-module:

If you have an network adapter/connection set to Public and that's your only connection, winrm will fail with:

> Error number:  -2144108183 0x80338169
> WinRM firewall exception will not work since one of the network connection types on this machine is set to Public. Change the network connection type to either Domain or Private and try again.

Either connect to a Domain or Private network, or change Windows Defender Firewall's Windows Remote Management (HTTP-In) to Enabled - _at your own peril_.  Then `winrm quickconfig` should be good, and the EXO module should connect.
