### ISSUE TITLE
Export-M365DSCConfiguration GUI does not display properly with high display scaling

### ISSUE THREAD

**Issue by RobBiddle** [microsoft/Microsoft365DSC#730]
#### Details of the scenario you tried and the problem that is occurring
When running Export-M365DSCConfiguration the scaling seems to be derived from the console from which it was launched.  If Windows is set to use greater than 100% scaling the results are not optimal.  When going over 150% it becomes almost unusable.

#### The operating system the target node is running
OsName : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture : 64-bit
WindowsVersion : 2004
WindowsBuildLabEx : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage : en-US
OsMuiLanguages : {en-US}
#### Version of the DSC module that was used ('dev' if using current dev branch)
1.20.730.2 Microsoft365DSC pulled from master branch

**Comment by NikCharlebois** [comment]
@RobBiddle with what console are you seeing this behavior? We recommend using the following consoles in order of priority:

1 - Windows Terminal
2 - Classic PowerShell Console
3 - ISE
4 - VSCode

ISE is known to have a lot of issues rendering items

**Comment by RobBiddle** [comment]
@NikCharlebois I usually use the Windows PowerShell console. 
Testing via the new Windows Terminal (i.e. from the Windows Store) gives the same result. 

Here's what it looks like when I launch from a console currently on a monitor with 150% scaling and the GUI opens on my default monitor which is at 175% scaling.
![image](https://user-images.githubusercontent.com/4378199/92039406-0161cd80-ed43-11ea-8501-b7c6d76b83be.png)

Changing my default monitor to 100% scaling and running again causes it to display correctly.
![image](https://user-images.githubusercontent.com/4378199/92040380-b9dc4100-ed44-11ea-9136-dd2f46a09f10.png)

Then changing my default monitor back to 175% and running it again results in scaling issues and sometimes the scroll bars are lost which makes it even worse.
![image](https://user-images.githubusercontent.com/4378199/92040756-f60fa180-ed44-11ea-8915-7968650e475a.png)

**Comment by NikCharlebois** [comment]
The GUI is now all web based. Closing this issue.
