### ISSUE TITLE
AzureADPreview - The current processor architecture is: x86: Surface Pro X (ARM)

### ISSUE THREAD

**Issue by Kikaider** [microsoft/Microsoft365DSC#738]
#### Details of the scenario you tried and the problem that is occurring
When importing _Import-Module Microsoft365DSC_ in a admin PowerShell ISE or Visual Studio Code window on a Surface Pro X (ARM processor), I get the error:

The current processor architecture is: x86. The module 'C:\...AzureADPreview\2.0.2.102\AzureADPreview.psd1' requires the following architecture: Amd64.

The Microsoft365DSC module will not load and thus I cannot use my Surface Pro X for Microsoft365DSC.

I get the same error if I try _Import-Module AzureADPreview_.

My workstation is a Surface Pro X with an ARM 64-bit processor.

The $env:processor_architecture = x86 for some reason. Changing $env:processor_architecture to "Amd64" does not resolve the issue.

Note: I know this is an AzureADPreview module issue, but wanted you to know.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
TBD

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
v1.20.603.1

**Comment by NikCharlebois** [comment]
Very interesting, I never thought of this scenario. Off course it is related to AzureADPreview and there is not much we can do about it, but I appreciate you reporting it as it helps build our Knowledge base. At some point we will be revisiting all resources to have them leverage the MS Graph directly (or via the PowerShell Graph SDK), at which point this issue should be solved.
