### ISSUE TITLE
[SCFilePlanPropertyCitation] too long when exporting config

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#743]
#### Details of the scenario you tried and the problem that is occurring
Exporting tenant config with 
Export-M365DSCConfiguration -Quiet -Workloads @("O365","OD","PP","SC","SPO","TEAMS") -GlobalAdminAccount $cred

#### Verbose logs showing the problem
Extracting [SCFilePlanPropertyCitation]...Name: The length of the property is too long. The maximum length is 64 and the length of the value provided is 91.
#### Suggested solution to the issue
Use different type for variable.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```Export-M365DSCConfiguration -Quiet -Workloads @("O365","OD","PP","SC","SPO","TEAMS") -GlobalAdminAccount $cred
# insert configuration here
```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-Bit
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : de-DE
OsMuiLanguages       : {de-DE, en-US}
#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by NikCharlebois** [comment]
@SebastianGoers Are you able to successfully run:

Test-MSCloudLoginAssistant -Platform SecurityComplianceCenter
Get-FilePlanPropertyCitation

This error seems to be coming from the API and not from M365DSC unfortunately.

**Comment by NikCharlebois** [comment]
@SebastianGoers any updates on this? Thanks

**Comment by SebastianGoers** [comment]
@NikCharlebois, the first command failes with command not found (the module is installed though).
The second command is showing the same error mentioned above, so I guess you conclusion is right:

`Get-FilePlanPropertyCitation
Name: The length of the property is too long. The maximum length is 64 and the length of the value provided is 91.
    + CategoryInfo          : NotSpecified: (:) [Get-FilePlanPropertyCitation], DataValidationException
    + FullyQualifiedErrorId : [Server=DB5EUR01WS004,RequestId=865425aa-a65d-4bb5-9fcc-b8310af6477e,TimeStamp=11.09.202
   0 17:41:52] [FailureCategory=Cmdlet-DataValidationException] A0579D5B,Microsoft.Office.CompliancePolicy.Tasks.GetF
  ilePlanPropertyCitation
    + PSComputerName        : eur01b.ps.compliance.protection.outlook.com
`

**Comment by NikCharlebois** [comment]
@SebastianGoers Can you try creating a new File Plan Citation with a name long of 65 characters from the web interface and see if it accepts it? I've just confirmed that the New-FilePlanPropertyCitation cmdlet doesn't accept a name longer than 64 characters:

```
Test-MSCloudLogin -Platform SecurityComplianceCenter -CloudCredential $Global:Adminnonmfa

$longname = ""
$rand = [System.Random]::new()

for ($i = 1; $i -le 65; $i++)
{
    $longName += $rand.Next(0,9).ToString()
}
New-FilePlanPropertyCitation -Name $longName 
```

Throws:
```
Name: The length of the property is too long. The maximum length is 64 and the length of the value provided is 65.
```

**Comment by NikCharlebois** [comment]
@SebastianGoers we will be closing this one as there really is nothing from a M365DSC perspective that can be done.
