### ISSUE TITLE
MSFT_TeamsClientConfiguration is missing AllowEgnyte

### ISSUE THREAD

**Issue by Madhu-21** [microsoft/Microsoft365DSC#744]

**Comment by Madhu-21** [comment]
![image](https://user-images.githubusercontent.com/19767962/91011071-fc0bd100-e626-11ea-9d01-7b57d74fc62f.png)
![image](https://user-images.githubusercontent.com/19767962/91011156-23629e00-e627-11ea-9b14-497d4f9218af.png)

**Comment by NikCharlebois** [comment]
Thanks for reporting. A PR has been submitted which will include this new property.
