### ISSUE TITLE
"PlannerBucket?" What's a PlannerBucket, and Why Prompt For ApplicationId and CertificateThumbprint?

### ISSUE THREAD

**Issue by klawrawkz** [microsoft/Microsoft365DSC#746]
I'm a newb so apologies if my question is ... well a newbie one. After the configuration extract process runs for a while, the **_Extracting [ODSettings]..._** operation starts. At this point I'm getting prompted to insert values for:
> ApplicationId: 
> TenantId: 
> CertificateThumbprint: 

The command syntax i provide is the following:
```
Start-M365DSCConfigurationExtract -AllComponents -FileName my-env-full-export.ps1 -GenerateInfo $True -GlobalAdminAccount myadminacct@mytenant.onmicrosoft.com -Mode Full -Path "C:\my-dsc-export-folder\" -Debug -Verbose
...
...
   |---[34/36] blah blah blah
   |---[35/36] blah blah blah
   |---[36/36] blah blah blah
[53/120] Extracting [ODSettings]...✅
[54/120] Extracting [PlannerBucket]...cmdlet Export-TargetResource at command pipeline position 1
Supply values for the following parameters:
ApplicationId: 
TenantId: 
CertificateThumbprint: 
```
Providing the TenantId is east b/c I know this. On the other hand values for **_ApplicationId_** and **_CertificateThumbprint_** don't make sense to me as I don't understand the context of the request. What "Application?" Which "CertificateThumbrint?" 

I'd like to get all relevant info for the M365 tenant. What of these "PlannerBuckets?" I'm confused, as I don't understand what a "PlannerBucket" is, and I don't understand the context of the requested input values. 

My options are 1) hit enter without supplying values, or 2) cast about in search of values to input, or 3) use a more granular command that omits the "ODSettings" from the export call. None of the options are great because all seem to result in not getting complete site DSC output.

What insight can you provide?

Thanks,

Klaw

_Originally posted by @klawrawkz in https://github.com/microsoft/Microsoft365DSC/pull/640#issuecomment-679324601_

**Comment by klawrawkz** [comment]
So I may have gotten a bit further in answering the question, "What PlannerBucket?" This relates to the Microsoft "Planner" app in M365. This makes sense as Planner has "Buckets" and so on. Why are we being prompted for the Id values though? Is something misconfigured on my end?

**Comment by MattAlberga** [comment]
Hello klawrawkz

My understanding of this is:
To export Planner and its contents one needs to build a azure app with Group.ReadWrite.All "application" permissions.

I followed the above document to build the app:
https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal

Once you have the App built you then will see a application ID/ tenant ID listed in the overview of the app.
Then when you upload a certificate you will have a thumbprint value for those fields you mention.

**Comment by klawrawkz** [comment]
Thanks @MattAlberga I'll try that and see how it goes.
