### ISSUE TITLE
[EXOSharedMailbox] Mailbox aliases will not get corrected when a drift is detected

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#749]
#### Details of the scenario you tried and the problem that is occurring
When an alias is defined for a shared mailbox (e.g. in multi domain environments) but the config only contains the primary SMTP address, Get-TargetResource will report a configuration drift. This is expected. However, Set-TargetResource will not remove the alias. Thus, Test-TargetResource will always report a configuration drift.

#### Verbose logs showing the problem
There aren't any error messages, I believe this is rather a conceptional issue.
#### Suggested solution to the issue
Maybe it is an idea to have a switch like strict, telling Set-TargetResource to enforce a configuration, which would mean to remove items that are not explicitly in the tenant config.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
Release 1.20.716.1

**Comment by NikCharlebois** [comment]
Thanks @SebastianGoers to make it easier for the dev team to troubleshoot and fix, is there a way for you to provide a bogus example of a configuration that would exhibit this behavior? Thanks

**Comment by SebastianGoers** [comment]
Hi @NikCharlebois , 

sure, we have a Target Configuration like this:

```
EXOSharedMailbox e4a072f3-a181-43eb-95d7-bbc2fff014b1
        {
            Aliases              = @();
            DisplayName          = "FMB Tenant Tech Contacts";
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            PrimarySMTPAddress   = "tenant-tech-contacts@****.onmicrosoft.com";
        }
```

Let's assume we have a defined an alias for said mailbox in EXO admin:
 
![image](https://user-images.githubusercontent.com/59373302/91954493-2b46d000-ed02-11ea-9e9b-9449649ccbf5.png)

(We actually had this alias defined when renaming the mail address of the FMB to circumvent https://github.com/microsoft/Microsoft365DSC/issues/686)

The alias will be seen (and reported as not compliant) by Get-TargetResource, but Test-TargetResource or Set-TargetResource will not touch it.

Regards,

Sebastian
