### ISSUE TITLE
SCSensitivityLabel: Cannot process argument transformation on parameter 'EncryptionRightsDefinitions'.

### ISSUE THREAD

**Issue by Jimnar** [microsoft/Microsoft365DSC#758]
#### Details of the scenario you tried and the problem that is occurring
Trying to create a sensitivity that applies permissions to entire tenant, not a specific user or group. The file I used was generated using the Export-m365dscconfiguration cmdlet, compiled using target tenant creds, and deployed using Start-dscconfiguration. I made no manual edits to the file. All the sensitivity labels that used the "Assign permissions now" option in the Encryption step in the sensitivity label creation wizard failed, while other sensitivity labels were created without issue. The system appears to want to assign permissions using user@contoso.com, but contoso.onmicrosoft.com is a valid selection.

#### Verbose logs showing the problem

Cannot process argument transformation on parameter 'EncryptionRightsDefinitions'. Cannot convert value                                                                  "[{"Identity":"contoso.onmicrosoft.com","Rights":"VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,EXPORT,EDITRIGHTSDATA,OBJMODEL,OWNER"}]" to    type "Microsoft.Office.CompliancePolicy.Tasks.EncryptionRightsDefinitionsParameter". Error: "Please provide encryption rights parameter in a valid format. The           supported format is admin1@contoso.com:RIGHT1,RIGHT2;admin2@contoso.com:RIGHT3,RIGHT4."                                                                                      + CategoryInfo          : InvalidData: (:) [], CimException                                                                                                              + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-Label                                                                                                 + PSComputerName        : localhost

#### Suggested solution to the issue

N/A

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
        }
        SCSensitivityLabel f4b3b1c3-a8fc-45e9-a4c7-168d45ede340
        {
            AdvancedSettings                            = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'aiplabelversion'
                    Value = '90e364e5-0603-49e1-b41b-5b07dd74e73f'
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'color'
                    Value = ''
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'parentid'
                    Value = '20717148-69bf-41d7-bef2-a9966a1c8d8c'
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'tooltip'
                    Value = 'Confidential data that requires protection  which allows all employees full permissions. Data owners can track and revoke content.'
                }
            );
            ApplyContentMarkingFooterAlignment          = "Left";
            ApplyContentMarkingFooterEnabled            = $True;
            ApplyContentMarkingFooterFontColor          = "#000000";
            ApplyContentMarkingFooterFontSize           = 8;
            ApplyContentMarkingFooterMargin             = 15;
            ApplyContentMarkingFooterText               = "Classified as Confidential";
            Comment                                     = "";
            Disabled                                    = $False;
            DisplayName                                 = "All Employees";
            EncryptionAipTemplateScopes                 = "[]";
            EncryptionContentExpiredOnDateInDaysOrNever = "Never";
            EncryptionEnabled                           = $True;
            EncryptionOfflineAccessDays                 = 30;
            EncryptionProtectionType                    = "Template";
            EncryptionRightsDefinitions                 = "**[{`"Identity`":`"$OrganizationName`",`"Rights`":`"VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,EXPORT,EDITRIGHTSDATA,OBJMODEL,OWNER`"}]";**
            EncryptionTemplateId                        = "3c76353a-f314-4301-af60-952e474fe5a3";
            Ensure                                      = "Present";
            GlobalAdminAccount                          = $Credsglobaladmin;
            LocaleSettings                              = @(
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'displayName'
                    Settings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'All Employees'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    Settings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Confidential data that requires protection, which allows all employees full permissions. Data owners can track and revoke content.'
                        }
                    )
                }
            );
            Name                                        = "Confidential All Employees";
            ParentId                                    = "Confidential";
            Priority                                    = 5;
            Tooltip                                     = "Confidential data that requires protection, which allows all employees full permissions. Data owners can track and revoke content.";


#### The operating system the target node is running

Not sure if the target node is my Microsoft 365 instance or the machine I'm running PowerShell on. I provided the info for the machine I'm running PowerShell on if that is what is desired.

OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.20.805.1

**Comment by desmay** [comment]
@Jimnar I'll take a look at this issue

**Comment by Jimnar** [comment]
After additional troubleshooting and in looking at the error, it appears the format of this line in the script might be incorrect:

EncryptionRightsDefinitions                 = "**[{`"Identity`":`"$OrganizationName`",`"Rights`":`"VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,EXPORT,EDITRIGHTSDATA,OBJMODEL,OWNER`"}]";**

I tried to specify different values in the UI, including email addresses, and nothing worked.

**Comment by desmay** [comment]
@Jimnar When you get a chance can you please try again using the Dev branch or you can wait until next version is published to PowerShell gallery. If you want to install dev branch on a machine you can use the Install-M365DSCDevBranch cmdlet.

**Comment by Jimnar** [comment]
@desmay, I'll assume these installation issues are expected? I'll continue onto the test in an hour or so.

PS C:\WINDOWS\system32> Install-M365DSCDevBranch
WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.Administration.PowerShell' include
unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the
Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'SharePointPnPPowerShellOnline' include unapproved verbs
that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again
 with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The version '2.0.2.105' of module 'AzureADPreview' is currently in use. Retry the operation after closing the
applications.
WARNING: The version '2.0.1' of module 'ExchangeOnlineManagement' is currently in use. Retry the operation after
closing the applications.
WARNING: The version '0.9.1' of module 'Microsoft.Graph.Authentication' is currently in use. Retry the operation after
closing the applications.
WARNING: The version '0.9.1' of module 'Microsoft.Graph.Authentication' is currently in use. Retry the operation after
closing the applications.
WARNING: The version '0.9.1' of module 'Microsoft.Graph.Groups.Planner' is currently in use. Retry the operation after
closing the applications.
WARNING: The version '0.9.1' of module 'Microsoft.Graph.Authentication' is currently in use. Retry the operation after
closing the applications.
WARNING: The version '0.9.1' of module 'Microsoft.Graph.Identity.ConditionalAccess' is currently in use. Retry the
operation after closing the applications.
WARNING: The version '0.9.1' of module 'Microsoft.Graph.Authentication' is currently in use. Retry the operation after
closing the applications.
WARNING: The version '0.9.1' of module 'Microsoft.Graph.Planner' is currently in use. Retry the operation after closing
 the applications.
WARNING: The version '2.0.76' of module 'Microsoft.PowerApps.Administration.PowerShell' is currently in use. Retry the
operation after closing the applications.
WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.Administration.PowerShell' include
unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the
Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The version '1.1.4' of module 'MicrosoftTeams' is currently in use. Retry the operation after closing the
applications.
WARNING: The version '3.24.2008.1' of module 'SharePointPnPPowerShellOnline' is currently in use. Retry the operation
after closing the applications.
WARNING: The names of some imported commands from the module 'SharePointPnPPowerShellOnline' include unapproved verbs
that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again
 with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Remove-Item : Cannot remove item C:\Program
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.902.1\PSGetModuleInfo.xml: You do not have sufficient access
rights to perform this operation.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.902.1\modules\M365DSCUtil.psm1:1418 char:9
+         Remove-Item $currentVersionPath -Recurse -Confirm:$false
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (PSGetModuleInfo.xml:FileInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
Remove-Item : Directory C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.902.1 cannot be removed
because it is not empty.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.902.1\modules\M365DSCUtil.psm1:1418 char:9
+         Remove-Item $currentVersionPath -Recurse -Confirm:$false
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Program File...5DSC\1.20.902.1:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : DirectoryNotEmpty,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by NikCharlebois** [comment]
@Jimnar did you execute the command in an elevated PowerShell console (run as Admin)?

**Comment by Jimnar** [comment]
@NikCharlebois, Yes I'm an admin on the machine and opened PowerShell in Admin mode. I also did a complete reboot befor trying again. Could these errors appear because I had already installed the devbranch? Also, should the module number change? Here is what I see.

PS C:\WINDOWS\system32> get-module -name microsoft365dsc

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.20.902.1 Microsoft365DSC                     {Add-M365DSCEvent, Add-M365DSCTelemetryEvent, Assert-M365D...

**Comment by Jimnar** [comment]
@NikCharlebois and @desmay, it appears there has been some progress, but I'm now getting a different error concerning encryption templates. The issue is very easy for me to repro. Simply go into M365 compliance center and configure the system to assign permissions now, then assign a user permissions. I'm just running on a test tenant so I'm happy to provide connection info privately if that would help.

![image](https://user-images.githubusercontent.com/10016605/92639501-c0147500-f290-11ea-82f2-f2192a406594.png)


Template not found in RMS. TemplateId: '78db810d-1646-455f-ab91-737d804d823b'                                               + CategoryInfo          : NotSpecified: (:) [], CimException                                                            + FullyQualifiedErrorId : [Server=BN7NAM10WS009,RequestId=853b79ea-724a-4584-83d6-79d4a758a0da,TimeStamp=9/9/2020      5:51:55 PM] [FailureCategory=Cmdlet-RmsTemplateNotFoundException] 165299A3,Microsoft.Office.CompliancePolicy.Tasks     .NewLabel                                                                                                                 + PSComputerName        : localhost                                                                                                                                                                                                         VERBOSE: [JACKIE-PRO3]: LCM:  [ End    Set      ]  [[SCSensitivityLabel]e87cda16-6064-4cec-a0a1-3c2b3cc4f944]  in       22.4980 seconds.                                                                                                        The PowerShell DSC resource '[SCSensitivityLabel]e87cda16-6064-4cec-a0a1-3c2b3cc4f944' with SourceInfo                  'C:\Temp\Microsoft365DSC\senslabel9\M365TenantConfig.ps1::666::9::SCSensitivityLabel' threw one or more                 non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel   called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.                                           + CategoryInfo          : InvalidOperation: (:) [], CimException                                                        + FullyQualifiedErrorId : NonTerminatingErrorFromProvider                                                               + PSComputerName        : localhost

**Comment by Jimnar** [comment]
@desmay, based on your post, I tested commenting out EncryptionTemplateId from the .ps1 file and recompiling it. At first glance, it appears the labels that were not being created due to the error got created without issues. All encryption settings seem to be configured correctly, too. I'm looking forward to learning what solution you come up with and am excited about the progress thus far.

**Comment by NikCharlebois** [comment]
@Jimnar just want to confirm, this issue has now been resolved for you? If so, can you close the issue? Thanks

**Comment by Jimnar** [comment]
@NikCharlebois mannually commenting out the line containing EncryptionTemplateId from the automatically generated M365TenantConfig.ps1 file is more of a workaround rather than a fix. I will also say that I do not know what EncryptionTemplateId actually does when it comes to the label. While the label does APPEAR to be created successfully with the settings specified when commenting out the line, I fear there may be something under the covers that didn't get configured. Does that make sense? The labels I'm exporting are simply the labels generated created when using the "create default labels" option in the AIP. Nothing special [https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-default](url)

Here is the complete segment, with the EncryptionTemplateId commented out.

        SCSensitivityLabel 20edf2df-6e1d-4ed7-a662-933626466c87
        {
            AdvancedSettings                            = @(
                MSFT_SCLabelSetting
                {
                    Key   = 'aiplabelversion'
                    Value = '11e186f6-3e3b-4802-832e-fce284f997be'
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'color'
                    Value = ''
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'parentid'
                    Value = '3022d9bb-c159-49d1-a37d-61e7efc3b587'
                }
                MSFT_SCLabelSetting
                {
                    Key   = 'tooltip'
                    Value = 'Highly confidential data that allows all employees view  edit  and reply permissions to this content. Data owners can track and revoke content.'
                }
            );
            ApplyContentMarkingFooterAlignment          = "Left";
           ApplyContentMarkingFooterEnabled            = $True;
            ApplyContentMarkingFooterFontColor          = "#000000";
            ApplyContentMarkingFooterFontSize           = 8;
            ApplyContentMarkingFooterMargin             = 15;
            ApplyContentMarkingFooterText               = "Classified as Highly Confidential";
            Comment                                     = "";
            Disabled                                    = $False;
            DisplayName                                 = "All Employees";
            EncryptionAipTemplateScopes                 = "[]";
            EncryptionContentExpiredOnDateInDaysOrNever = "Never";
            EncryptionEnabled                           = $True;
            EncryptionOfflineAccessDays                 = 30;
            EncryptionProtectionType                    = "Template";
            EncryptionRightsDefinitions                 = "$($OrganizationName):VIEW,VIEWRIGHTSDATA,DOCEDIT,EDIT,PRINT,EXTRACT,REPLY,REPLYALL,FORWARD,OBJMODEL";
            # EncryptionTemplateId                        = "3a034858-a31c-4a1e-8e23-901092f52e87";
            Ensure                                      = "Present";
            GlobalAdminAccount                          = $Credsglobaladmin;
            LocaleSettings                              = @(
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'displayName'
                    Settings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'All Employees'
                        }
                    )
                }
                MSFT_SCLabelLocaleSettings
                {
                    LocaleKey = 'tooltip'
                    Settings  = @(
                        MSFT_SCLabelSetting
                        {
                            Key   = 'default'
                            Value = 'Highly confidential data that allows all employees view, edit, and reply permissions to this content. Data owners can track and revoke content.'
                        }
                    )
                }
            );
            Name                                        = "Highly Confidential All Employees";
            ParentId                                    = "Highly Confidential";
            Priority                                    = 9;
            Tooltip                                     = "Highly confidential data that allows all employees view, edit, and reply permissions to this content. Data owners can track and revoke content."; 
}

**Comment by NikCharlebois** [comment]
After further investigation, my understanding is that on the Export, we are grabbing the ID of the RMS template assigned to the Label, which is unique to the tenant we are exporting the value from. Upon trying to recreate it on another tenant, it tries to assign that ID to the label, which doesn't exist on the destination tenant. 

My recommendation is that we look at fixing this by introducing a new resource called AIPServiceTemplate which would allow us to create a new RMS Template in the destination tenant, and then to have the EncryptionTemplateId parameter point to the name of a template instead of an ID which is unique to the environment.

**Comment by NikCharlebois** [comment]
@Jimnar given that Azure Information Protection is being deprecated (https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-version-release-history#:~:text=To%20provide%20a%20unified%20and%20streamlined%20customer%20experience%2C,using%20the%20Microsoft%20Information%20Protection%20Unified%20Labeling%20platform.) my recommendation is to remove the EncryptionTemplateId parameter completely from the resource. This way it will automatically create the resource. Comments?

**Comment by Jimnar** [comment]
@NikCharlebois 

Are you proposing I remove the EncryptionTemplateID manually or are you proposing to remove it from your code that puts it into the config file?  

I was using AIP was ONLY to create the default labels since they are considered a "best practice" and it is convenient. Those labels then get automatically copied into the Information Projection solution in Microsoft 365 Compliance, which is where I'm actually using them. While I'd prefer not to, I can manually create the same label configuration in Information Protection and see if that process also produces a config file with an EncryptionTemplateID entry. Is that what you are proposing?

**Comment by desmay** [comment]
@Jimnar The latest release 923.1 has the EncyptionTemplateID removed. Sensitivity labels still use Azure RMS when encryption is enabled and everything required to build the encryption template is in the extracted properties permissions etc so no need to extract templateID

**Comment by Jimnar** [comment]
@desmay I'll be giving a try by this weekend.

Any chance you could give https://github.com/microsoft/Microsoft365DSC/issues/777 a look?

**Comment by NikCharlebois** [comment]
@Jimnar any updates? Thanks

**Comment by Jimnar** [comment]
@NikCharlebois, sorry for the delayed response. I'm working on getting a demo script complete. I'll try and give it a look over the weekend.

**Comment by Jimnar** [comment]
@NikCharlebois I finally got an opportunity to test this scenario and confirmed it is now working as expected. Thank you.
