### ISSUE TITLE
Problem with REGEX and domain names with numbers...

### ISSUE THREAD

**Issue by P3N-101** [microsoft/Microsoft365DSC#765]
<!--
    Your feedback and support is greatly appreciated, thanks for contributing!

    ISSUE TITLE:
   Cannot validate argument on parameter 'Identity'. The argument "111111.co.uk" does not match the "(?=^.{1,254}$)(^(?:(?!\d+\.|-)[a-zA-Z0-9_\-]{1,63}(?<!-)\.?)+(?:[a-zA-Z]{2,})$)" pattern

    ISSUE DESCRIPTION (this template):

    I have a domain that is numbers only when trying to run Export-M365DSCConfiguration it fails with the above error, I have tested this on regex sites and it appears the pattern checking is wrong.

It is a valid domain attached to a 365 tenant.

**Comment by NikCharlebois** [comment]
@P3N-101 can you please provide additional details and context on what the exact issue is, thanks.

**Comment by NikCharlebois** [comment]
Closing issue as we need additional details
