### ISSUE TITLE
TeamsMeetingPolicy - Update Resource to enable new parameters

### ISSUE THREAD

**Issue by jeff29922** [microsoft/Microsoft365DSC#788]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by jeff29922** [comment]
I will be adding this to Teams backlog to be fixed

**Comment by jeff29922** [comment]
In reviewing the PowerShell Cmdlet, there are quite a few parameters that need to be added to this resource.

**Comment by TedBrown-MSFT** [comment]
I am working on this currently.
