### ISSUE TITLE
Add Idle Session Timeout Property to SPOAccessControl

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#79]
#### Details of the scenario you tried and the problem that is occurring
Need to add support for Iddle Session Signout in the SPOAccess Control Resource

**Comment by NikCharlebois** [comment]
@ThorstenLoeschmann If you ever have cycles, can you please take a look at this? Thanks

**Comment by NikCharlebois** [comment]
![image](https://user-images.githubusercontent.com/2547149/55349068-c04af700-5486-11e9-9d60-04a5f5ab8bcb.png)

**Comment by NikCharlebois** [comment]
@ThorstenLoeschmann did you ever have a chance to look at this?

**Comment by ThorstenLoeschmann** [comment]
At the moment we are using PnP cmdlets for this resource (get- / set-pnpTenant). To address this property there is an SPO cmdlet (Get-SPOBrowserIdleSignOut / Set-SPOBrowserIdleSignOut) but I couldn't find a corresponding PnP alternative for it so we would have to mix and match cmdlets from the different modules. What do you think?

**Comment by Markus-Hanisch** [comment]
@ThorstenLoeschmann @NikCharlebois 
May have a look at [Azure Active Directory Configurable Token Lifetime Policies (in public preview)](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#cmdlet-reference) and its [configurable-token-lifetime-properties](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#configurable-token-lifetime-properties).
As far as I understood the documentation, these [Azure AD lifetime policies can be linked to an application](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#add-azureadapplicationpolicy) by PS Cmdlet [Add-AzureADApplicationPolicy](https://docs.microsoft.com/en-us/powershell/module/azuread/add-azureadapplicationpolicy?view=azureadps-2.0-preview#examples).

See also:
[Configure authentication session management with Conditional Access > user session sign-in frequency](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime#user-sign-in-frequency)

**Comment by ThorstenLoeschmann** [comment]
Hi @Markus-Hanisch,

thank you for bringing this up, very interesting. We currently have a few other topics where it potentially could make sense to utilize Azure AD capabilities. Currently I just dont have the capacity to work on them unfortunately. I added the AzureADApplicationPolicy to the list of topics but cannot promise when I will find the time to work on it :-(

**Comment by NikCharlebois** [comment]
@ThorstenLoeschmann can we confirm that this can be implemented via a new AAD resource? Thanks

**Comment by NikCharlebois** [comment]
Policies were implemented as part of an earlier release.
