### ISSUE TITLE
[TeamsCallingPolicy] Getting Teams Calling Policy fails with 'The remote server returned an error: (404) Not Found.'

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#790]
#### Details of the scenario you tried and the problem that is occurring
Running a Test-TenantConfiguration against a blueprint configuration recently fails on the Teams Calling policy. 

From what I have seen the DSC module for Teams is using `Test-MSCloudLogin -Platform SkypeForBusiness -CloudCredential $cred` in the background which fails with the same error using PowerShell command line. 

I have tried using `Test-MSCloudLogin -Platform MicrosoftTeams -CloudCredential $cred` which succeeds w/o issues.

Accessing the Teams admin portal with the exact same service account is showing the calling policy (Global).

#### Verbose logs showing the problem
VERBOSE: [WIN-199QNMJKU68]: LCM:  [ Start  Test     ]  [[TeamsCallingPolicy]*]
VERBOSE: [WIN-199QNMJKU68]:                            [[TeamsCallingPolicy]*] 
Testing configuration of Team Calling Policy {Global}
VERBOSE: [WIN-199QNMJKU68]:                            [[TeamsCallingPolicy]*] 
Getting the Teams Calling Policy Global
The remote server returned an error: (404) Not Found.
     + CategoryInfo          : NotSpecified: (:) [], CimException
     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness
     + PSComputerName        : localhost
VERBOSE: [WIN-199QNMJKU68]: LCM:  [ End    Test     ]  [[TeamsCallingPolicy]*] False
in 18.0890 seconds.
VERBOSE: [WIN-199QNMJKU68]: LCM:  [ *FAILED*Compare  ]     Completed processing compare operation. The operation 
returned False.
PowerShell DSC resource MSFT_TeamsCallingPolicy  failed to execute Test-TargetResource functionality with error 
message: The remote server returned an error: (404) Not Found. 
   + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
   + FullyQualifiedErrorId : ProviderOperationExecutionFailure
   + PSComputerName        : localhost
VERBOSE: Operation 'Invoke CimMethod' complete.

Test in PowerShell (errors are in German, sorry!):
```
Test-MSCloudLogin -Platform SkypeForBusiness -CloudCredential $cred
Connect-MSCloudLoginSkypeForBusiness : Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
In C:\Users\*\Documents\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.38\MSCloudLoginAssistant.psm1:167 Zeichen:13
+             Connect-MSCloudLoginSkypeForBusiness @verboseParameter
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness

New-CsOnlineSession : Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
In C:\Users\*\Documents\WindowsPowerShell\Modules\MSCloudLoginAssistant\1.0.38\Workloads\SkypeForBusiness.psm1:29 Zeichen:36
+ ... ypeSession = New-CsOnlineSession -Credential $Global:o365Credential `
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Authentifizierungsfehler: (:) [New-CsOnlineSession], WebException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession

```

```
PS C:\Users\*> Test-MSCloudLogin -Platform SkypeForBusiness -CloudCredential $cred
PS C:\Users\*>
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
TeamsCallingPolicy 3cd72b98-a2f0-4a7e-a588-83005c5364ba
        {
            AllowCallForwardingToPhone = $True;
            AllowCallForwardingToUser  = $True;
            AllowCallGroups            = $True;
            AllowDelegation            = $True;
            AllowPrivateCalling        = $True;
            AllowVoicemail             = "UserOverride";
            BusyOnBusyEnabledType      = "Disabled";
            Ensure                     = "Present";
            GlobalAdminAccount         = $Credsglobaladmin;
            Identity                   = "Global";
            PreventTollBypass          = $False;
        }
```

#### The operating system the target node is running

CICD pipeline agent Win 2019
#### Version of the DSC module that was used ('dev' if using current dev branch)
Most recent version is being installed for every DSC run. (18.09.2020)

**Comment by SebastianGoers** [comment]
I cannot reproduce the issue right now (have been able to reproduce it for > 24hrs.). Might have been related to Service incident:
ID: TM222357 
Title: Some admins may have been unable to access the Microsoft Teams admin center

**Comment by jeff29922** [comment]
Sabastian, I am looking into this.  I'll get back to you.

**Comment by SebastianGoers** [comment]
Changing the tenant default domain to the ***.onmicrosoft.com domain mitigates the issue. It is worth noticing that this behavior could only be reproduced on tenants in the non-sovereign DE region, but is not showing on tenants in AMS / DUB.

**Comment by jeff29922** [comment]
@NikCharlebois investigating. Let me test with the new release and I will post and update.

**Comment by robertreems** [comment]
Hi I've had the exact same issue and found a workaround: You need to license atleast one user with a valid Teams license. 

If you havn't done so the Teams (web) portal is not availble  thus resulting in this error.

**Comment by larbre** [comment]
> Changing the tenant default domain to the ***.onmicrosoft.com domain mitigates the issue. It is worth noticing that this behavior could only be reproduced on tenants in the non-sovereign DE region, but is not showing on tenants in AMS / DUB.

I can confirm the same behavior, after adding a custom domain without attaching any services to it the 404 errors occurred, making the onmicrosoft.com domain the default domain, the issue went away

**Comment by NikCharlebois** [comment]
This was fixed with recent releases of the MSCloudLoginAssistant, even if you set a different default domain it will still work.
