### ISSUE TITLE
Update TeamsTeam Resource to reflect new parameters

### ISSUE THREAD

**Issue by jeff29922** [microsoft/Microsoft365DSC#794]
### Description
**Get-Team** [https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps](url). This cmdlet supports retrieving teams with particular properties/information, including all teams that a specific user belongs to, all teams that have been archived, all teams with a specific display name, or all teams in the organization
### Proposed properties
[https://docs.microsoft.com/en-us/powershell/module/teams/get-team?view=teams-ps#parameters](url)

**Comment by NikCharlebois** [comment]
@jeff29922 have we confirmed the list of parameters that are missing/need to be updated in this resource?

**Comment by TedBrown-MSFT** [comment]
Looks like the only new parameter is:
-ShowInTeamsSearchAndSuggestions 

    -ShowInTeamsSearchAndSuggestions <Boolean>
        Setting that determines whether or not private teams should be searchable from Teams clients for users who do not
        belong to that team.  Set to $false to make those teams not discoverable from Teams clients.

        Required?                    false
        Position?                    named
        Default value                None
        Accept pipeline input?       False
        Accept wildcard characters?  false

**Comment by NikCharlebois** [comment]
Thanks @TedBrown-MSFT do you want to take this on?

**Comment by TedBrown-MSFT** [comment]
Sure

Thank you

Ted Brown | Senior Premier Field Engineer – Intelligent Communications
IM: edbrown@microsoft.com<mailto:edbrown@microsoft.com> | Email: Edward.Brown@microsoft.com<mailto:Edward.Brown@microsoft.com>
Office: +1-703-439-3813 x3813 | Mobile: +1-716-316-8925
