### ISSUE TITLE
[MSFT_SCFilePlanPropertyCategory] Fail to create a runspace because you have exceeded the maximum number of connections allowed : 3

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#799]
#### Details of the scenario you tried and the problem that is occurring

Performing a Test-TargetResource fails with "Fail to create a runspace because you have exceeded the maximum number of connections allowed : 3"
We are using a service account which is only being used to perform the  Test-TargetResource checks. Also we only run one  Test-TargetResource check every 24hrs.
#### Verbose logs showing the problem
```
VERBOSE: [fv-az80]: LCM:  [ *FAILED*Compare  ]     Completed processing compare operation. The operation returned 
False.
PowerShell DSC resource MSFT_SCFilePlanPropertyCategory  failed to execute Test-TargetResource functionality with 
error message: Processing data from remote server deu01b.ps.compliance.protection.outlook.com failed with the 
following error message: Fail to create a runspace because you have exceeded the maximum number of connections allowed : 3.
Please close existing runspace and try again. For more information, see the about_Remote_Troubleshooting Help 
topic. 
+ CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
+ FullyQualifiedErrorId : ProviderOperationExecutionFailure
+ PSComputerName        : localhost
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running

Using an Azure DevOps CICD agent running Win 2019.
#### Version of the DSC module that was used ('dev' if using current dev branch)
Using current prod version.

**Comment by SebastianGoers** [comment]
We moved back to version Microsoft365DSC 1.20.916.1 and found that the current release does not mention "Removed the PSSession" in the logs. Apparently the session cleanup is broken in the current release. We believe that the error originates from ExchangeOnlineManagement.psm1 in function 'Disconnect-ExchangeOnline'. It appears as if the sessions aren't correctly cleaned up. The issue occurs in ExchangeOnlineManagement version 2.0.3 whereas was still working correctly in version 2.0.1 .

**Comment by klawrawkz** [comment]
We're getting the same in GCCHIGH environment. First we do a sanity check to clean up any PSSessions. Then run Start-M365DSCConfigurationExtract targeting the "SC" Workload.

What's the workaround? Revert to _ExchangeOnlineManagement version 2.0.1?_

Thanks for your help with this.

Klaw

```
PS C:\WINDOWS\system32> Disconnect-ExchangeOnline  -Verbose -Confirm:$false
VERBOSE: Running this cmdlet clears all active sessions created using Connect-ExchangeOnline or Connect-IPPSSession.
VERBOSE: Importing cmdlet 'Clear-ActiveToken'.
Removed the PSSession ExchangeOnlineInternalSession_1 connected to outlook.office365.us
Removed the PSSession ExchangeOnlineInternalSession_2 connected to ps.compliance.protection.office365.us
Removed the PSSession ExchangeOnlineInternalSession_3 connected to ps.compliance.protection.office365.us
Removed the PSSession ExchangeOnlineInternalSession_4 connected to ps.compliance.protection.office365.us
Disconnected successfully !
 
PS C:\WINDOWS\system32> Start-M365DSCConfigurationExtract -FileName $dscConfig_SC_Export_FileName          -GenerateInfo $True -GlobalAdminAccount $userPrincipalName -Mode Full -Path $dscConfigExportPath -Workloads SC    -Debug -Verbose
[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted: 
PlannerBucket PlannerPlan
[INFO] You can perform an equivalent unattended Export operation by running the following command:
Export-M365DSCConfiguration -Quiet -ComponentsToExtract @)
[1/23] Extracting [SCAuditConfigurationPolicy]...
[2/23] Extracting [SCCaseHoldPolicy]...
[3/23] Extracting [SCCaseHoldRule]...
[4/23] Extracting [SCComplianceCase]...New-ExoPSSession : Processing data from remote server ps.compliance.protection.office365.us failed with the following error mes
sage: Fail to create a runspace 
because you have exceeded the maximum number of connections allowed : 3. Please close existing runspace and try again. For more information, see the 
about_Remote_Troubleshooting Help topic.
At C:\Program Files\WindowsPowerShell\Modules\ExchangeOnlineManagement\2.0.3\ExchangeOnlineManagement.psm1:426 char:30
+ ... PSSession = New-ExoPSSession -ExchangeEnvironmentName $ExchangeEnviro ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [New-ExoPSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSessi 
   on

PS C:\WINDOWS\system32> Disconnect-ExchangeOnline  -Verbose 
VERBOSE: Importing cmdlet 'Clear-ActiveToken'.
Removed the PSSession ExchangeOnlineInternalSession_9 connected to ps.compliance.protection.office365.us
Removed the PSSession ExchangeOnlineInternalSession_8 connected to ps.compliance.protection.office365.us
Removed the PSSession ExchangeOnlineInternalSession_7 connected to ps.compliance.protection.office365.us
Disconnected successfully !
```

**Comment by NikCharlebois** [comment]
@klawrawkz what version of Microsoft365DSC are you using? The latest version (1.20.930.1) should have reverted back to 2.0.1. This is a temporary fix

CC @navgupta1208 for visibility

**Comment by klawrawkz** [comment]
@NikCharlebois, I get it. It didn't make sense to me at the time; now it does. We updated and now we're on Microsoft365DSC version (1.20.930.1). The update _probably did revert_ ExchangeOnlineManagement back to 2.0.1.  When we updated the MSDSC we updated other related modules. Apparently we unintentionally broke the work-around, lol. We'll downgrade.

Thanks,

Klaw

**Comment by navgupta1208** [comment]
@NikCharlebois - The latest version of module allows you to open a PowerShell session to Exchange as well as Security-Compliance Center in a single instance. To enable this, we don't close any existing PS Session.

We recommend you to close the session using Disconnect-ExchangeOnline.

**Comment by klawrawkz** [comment]
@navgupta1208, are you stating that the 'end user' needs to orchestrate the Disconnect-ExchangeOnline' calls, or that the Microsoft365DSC internal logic needs to do this? If it's on the end user,  I'm not sure how we are supposed to do this as the Microsoft365DSC encapsulates all the connection requests. If it's the latter, my claim is that M365DSC is _also in the end user role_ and therefore should not be on the hook for connection management.  

Before I realized that the ExchangeOnlineManagement module (EOMM) was chewing up all the connections (for whatever reason), I wrote a workaround in EOMM that monitors connection count and does just what you say. I did this blindly b/c I didn't see any other module that managed connections. In my hack, EOMM closes connections itself before EOMM exhausts the pool.  In my opinion, if EOMM is marshaling connections, with no heed to the limitations to begin with, this is undesirable behavior.  EOMM knows the limits, and should 'control itself' so to speak. What's the rationale for any other components to take on the connection management obligations? Why does EOMM need a nanny?

Thanks,

klaw

**Comment by navgupta1208** [comment]
@klawrawkz 

Opening and closing Exchange Online PowerShell session has to be handled by user in their script. This has always been the behaviour in EXO PowerShell.

Since multiple scripts may be running in parallel in a single PowerShell window, closing any session may lead to unwanted loss of operation/data. We recommend using Disconnect-ExchangeOnline for every instance of Connect-ExchangeOnline in any PowerShell script.

In this case, M365DSC should do it. CC: @NikCharlebois

**Comment by SebastianGoers** [comment]
@NikCharlebois , the issue still persists:

```
Failed to apply dsc configuration. [PowerShell DSC resource MSFT_SCFilePlanPropertyCategory 
failed to execute Test-TargetResource functionality with error message: Processing data from 
remote server deu01b.ps.compliance.protection.outlook.com failed with the following error 
message: Fail to create a runspace because you have exceeded the maximum number of 
connections allowed : 3. Please close existing runspace and try again. For more information, see the 
about_Remote_Troubleshooting Help topic]
```

**Comment by robertreems** [comment]
Hi I seem to suffer from this issue as well. I've only experienced it while using the SCRetentionCompliancePolicy resource.

JobID                      : {75AC5ECE-45D5-11EB-975F-000D3AAAE1B1}
HostName                   : rvrWin10
Error                      : PowerShell DSC resource MSFT_SCRetentionCompliancePolicy  failed to execute Test-TargetResource functionality with error message: Processing data from remote server eur05b.ps.compliance.protection.outlook.com failed with the 
                             following error message: Fail to create a runspace because you have exceeded the maximum number of connections allowed : 3. Please close existing runspace and try again. For more information, see the 
                             about_Remote_Troubleshooting Help topic. 
Locale                     : en-US
IPV4Addresses              : {10.1.2.4, 127.0.0.1}
IPV6Addresses              : {fe80::a068:c9cd:8706:3873%5, ::2000:0:0:0, ::1, ::2000:0:0:0}
MACAddresses               : {00-0D-3A-AA-E1-B1}
LCMVersion                 : 2.0
Mode                       : PUSH
NumberOfResources          : 2
MetaData                   : Author: robert; Name: Main; Version: 2.0.0; GenerationDate: 12/24/2020 10:35:39; GenerationHost: rvrWin10;
MetaConfiguration          : MSFT_DSCMetaConfiguration
Type                       : Consistency
Status                     : Failure
StartDate                  : 12/24/2020 10:47:47 AM
DurationInSeconds          : 16
RebootRequested            : False
ResourcesInDesiredState    : {[SCRetentionCompliancePolicy]ExchangeEmailPolicy_cloudpiloot.onmicrosoft.com::[Compliance]test_configuration, [SCRetentionComplianceRule]ExchangeEmailRule__cloudpiloot.onmicrosoft.com::[Compliance]test_configuration}
ResourcesNotInDesiredState : 
PSComputerName             :

**Comment by NikCharlebois** [comment]
Several fixes to the MSCloudLoginAssistant module over the past few months have solved this.
