### ISSUE TITLE
TeamsMeetingPolicy, TeamsMessagingPolicy, TeamsMeetingBroadcastPolicy]DirectResourceAccess & TeamsCallingPolicy

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#816]
#### Details of the scenario you tried and the problem that is occurring
when trying to apply configuration for the default calling or meeting policy, the Set-CSTeams* cmdlet throw the following error:
Set or Remove host tag instance is not allowed

This is a valid error when doing the automation via Start-DSCConfiguration. The issue however is that the Export feature does export the default policies. If we can't modify them, then they shouldn't be exported.

#### Verbose logs showing the problem
Set or Remove host tag instance is not allowed

#### Suggested solution to the issue
Filter out the default policies from the Export-TargetResource function.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.20.930.1

**Comment by jeff29922** [comment]
@NikCharlebois Ok let me triage this and get a Teams Dev to investigate and fix.

**Comment by furgie** [comment]
Is there an update on this? I am unable to disable Teams spam filtering on 'Tagged' policies. I get the error "Set or remove host Tag instance is not allowed" when running ' Set-CsTeamsCalling Policy -Identity <Name of tagged policy> -SpamfilteringEnabledType "Disabled" '

**Comment by NikCharlebois** [comment]
After running several tests, it appears that this has now been fixed by the latest version of the Teams module we are using as a dependency. Closing issue.
