### ISSUE TITLE
NewResourceName: CsGroupPolicyAssignment - Support for assigning policies to groups

### ISSUE THREAD

**Issue by andrasg** [microsoft/Microsoft365DSC#819]
### Description
Please add support for creating/removing/updating policy assignments.
https://docs.microsoft.com/en-us/powershell/module/teams/new-csgrouppolicyassignment?view=teams-ps

### Proposed properties

- GroupId 
- PolicyType 
- PolicyName 

### Special considerations or limitations

- Group policy assignments not supporting all types of policies
- Updating an assignment requires recreating the assignment - remove, then new

**Comment by jeff29922** [comment]
@ndambrosio let's plan on triaging this and get this added to the Teams Development backlog.
