### ISSUE TITLE
MSFT_EXO*: All Exchange online configurations return error about 'Certificate' is ambiguous

### ISSUE THREAD

**Issue by chadif** [microsoft/Microsoft365DSC#820]
#### Details of the scenario you tried and the problem that is occurring
Exported DSC settings from Tenant A
Attempting to import settings into Tenant B

When I run the command "Start-DSCConfiguration M365TenantConfig -Wait -Verbose -Force" (using global admin with no MFA)  I get the following error on all the Exchange Online commands such as this:

PowerShell DSC resource MSFT_EXOAcceptedDomain  failed to execute Test-TargetResource functionality with error message: Parameter cannot be processed because the parameter name 'Certificate' is ambiguous. Possible matches include: -CertificateFilePath -CertificatePassword -CertificateThumbprint.

#### Verbose logs showing the problem
VERBOSE: [WS10]: LCM:  [ Start  Resource ]  [[EXOAcceptedDomain]bc6307d5-a639-4b81-9100-a5b0102f0f45]
VERBOSE: [WS10]: LCM:  [ Start  Test     ]  [[EXOAcceptedDomain]bc6307d5-a639-4b81-9100-a5b0102f0f45]
VERBOSE: [WS10]:                            [[EXOAcceptedDomain]bc6307d5-a639-4b81-9100-a5b0102f0f45] Testing configuration of Accepted Domain for xxxxxx.onmicrosoft.com
VERBOSE: [WS10]:                            [[EXOAcceptedDomain]bc6307d5-a639-4b81-9100-a5b0102f0f45] Getting configuration of Accepted Domain for xxxxxx.onmicrosoft.com
VERBOSE: [WS10]: LCM:  [ End    Test     ]  [[EXOAcceptedDomain]bc6307d5-a639-4b81-9100-a5b0102f0f45]  in 16.5730 seconds.
**PowerShell DSC resource MSFT_EXOAcceptedDomain  failed to execute Test-TargetResource functionality with error message: Parameter cannot be processed because the parameter name 'Certificate' is ambiguous. Possible matches include: -CertificateFilePath -CertificatePassword -CertificateThumbprint.**
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

VERBOSE: [WS10]: LCM:  [ Start  Resource ]  [[EXOAntiPhishPolicy]63176436-57f6-48f7-95d8-e1930f5057fa]
VERBOSE: [WS10]: LCM:  [ Start  Test     ]  [[EXOAntiPhishPolicy]63176436-57f6-48f7-95d8-e1930f5057fa]
VERBOSE: [WS10]:                            [[EXOAntiPhishPolicy]63176436-57f6-48f7-95d8-e1930f5057fa] Testing configuration of AntiPhishPolicy for Office365 AntiPhish Default
VERBOSE: [WS10]:                            [[EXOAntiPhishPolicy]63176436-57f6-48f7-95d8-e1930f5057fa] Getting configuration of AntiPhishPolicy for Office365 AntiPhish Default
VERBOSE: [WS10]: LCM:  [ End    Test     ]  [[EXOAntiPhishPolicy]63176436-57f6-48f7-95d8-e1930f5057fa]  in 3.9860 seconds.
**PowerShell DSC resource MSFT_EXOAntiPhishPolicy  failed to execute Test-TargetResource functionality with error message: Parameter cannot be processed because the parameter name 'Certificate' is ambiguous. Possible matches include: -CertificateFilePath -CertificatePassword -CertificateThumbprint.**
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        EXOAcceptedDomain bc6307d5-a639-4b81-9100-a5b0102f0f45
        {
            DomainType           = "Authoritative";
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Identity             = "$OrganizationName";
            MatchSubDomains      = $False;
            OutboundOnly         = $False;
        }
        EXOAntiPhishPolicy 63176436-57f6-48f7-95d8-e1930f5057fa
        {
            AdminDisplayName                    = "";
            AuthenticationFailAction            = "MoveToJmf";
            EnableAntispoofEnforcement          = $True;
            Enabled                             = $True;
            EnableMailboxIntelligence           = $True;
            EnableOrganizationDomainsProtection = $False;
            EnableSimilarDomainsSafetyTips      = $False;
            EnableSimilarUsersSafetyTips        = $False;
            EnableTargetedDomainsProtection     = $False;
            EnableTargetedUserProtection        = $False;
            EnableUnusualCharactersSafetyTips   = $False;
            Ensure                              = "Present";
            ExcludedDomains                     = @();
            ExcludedSenders                     = @();
            GlobalAdminAccount                  = $Credsglobaladmin;
            Identity                            = "Office365 AntiPhish Default";
            PhishThresholdLevel                 = 1;
            TargetedDomainActionRecipients      = @();
            TargetedDomainProtectionAction      = "NoAction";
            TargetedDomainsToProtect            = @();
            TargetedUserActionRecipients        = @();
            TargetedUserProtectionAction        = "NoAction";
            TargetedUsersToProtect              = @();
        }
```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.20.930.1

**Comment by NikCharlebois** [comment]
This has been fixed with one of the recent releases of MSCloudLoginAssistant.
