### ISSUE TITLE
 Start-M365DSCConfigurationExtract: TenantID Must Be In Format contoso.onmicrosoft.com Error When Using Automation Account

### ISSUE THREAD

**Issue by klawrawkz** [microsoft/Microsoft365DSC#825]
Hi,

When we run the current release version _Microsoft365DSC | 1.20.930.1_ extract using an automation applicationID, we get an error.  The **same error** is produced whether we use the automation app info in powershell, azure powershell, or in azure playbook powershell contrivance. Probably because we call the M365DSCC the same way across the board.

We use this prototype:
```
 try{ Start-M365DSCConfigurationExtract -AllComponents -FileName my-spiffy-AAD-full-export-v006.ps1 -GenerateInfo $True -TenantId 'our.spiffy.domain.name.com' -ApplicationId $servicePrincipalConnection.ApplicationId -CertificateThumbprint $servicePrincipalConnection.CertificateThumbprint -Mode Full -Verbose } catch{ Write-Error -Message $_.Exception ## throw $_.Exception }
```

The result of the operation is the follwing.
```
System.Management.Automation.RuntimeException: TenantID must be in format contoso.onmicrosoft.com + CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
``` 

_Out of pure unadulterated desperation, and throwing logic and caution to the wind,_ we have called the module using the _actual guid form_ of the **tenantID, e.g. this form: 'f2e1234d-3e45-67c8-a91e-a2d1dccdfef3'** and separately using the domain spec, e.g. **_'our.spiffy.domain.name.com'_** (tenant Id). Both, _unsurprisingly to us at this juncture,_ result in the same tired, ratty-assed error admonishing us that **_'TenantID must be in format contoso.onmicrosoft.com'._**

What's the story, what are we doing wrong, and how do we successfully run M365DTC using an automation account and _TenantId, ApplicationId, and CertificateThumbprint_ auth parameters?

Thanks,

klaw

```
<!--
    Your feedback and support is greatly appreciated, thanks for contributing!

    ISSUE TITLE:
    Please prefix the issue title with the resource name, e.g.
    'ResourceName: Short description of my issue'

    ISSUE DESCRIPTION (this template):
    Please provide information regarding your issue under each header below.
    Write N/A under any headers that do not apply to your issue, or if the
    information is not available.

    NOTE! Sensitive information should be obfuscated.

    PLEASE KEEP THE HEADERS.

    You may remove this comment block, and the other comment blocks,
    but please keep the headers.
-->
#### Details of the scenario you tried and the problem that is occurring

#### Verbose logs showing the problem

#### Suggested solution to the issue

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running

```
#### Version of the DSC module that was used ('dev' if using current dev branch)

**Comment by NikCharlebois** [comment]
Need to investigate further, but in the meantime, the MVP crew at O365EH.com came up with a blog/webcast to leverage Azure Automation Runbooks with Microsoft365DSC:
https://o365eh.com/2020/10/27/episode-74-using-microsoft-dsc-as-a-runbook-in-azure-automation/
