### ISSUE TITLE
Errors and warnings when installing the dev branch

### ISSUE THREAD

**Issue by TuomasPakkanen** [microsoft/Microsoft365DSC#826]
#### Details of the scenario you tried and the problem that is occurring

I'm trying to install the Dev branch with Install-M365DSCDevBranch cmdlet, but there are multiple warnings about modules being currently in use. Does this mean the modules are not updated correctly? How can I confirm I am running the dev branch?

Additionally an error is thrown in the end that I do not have sufficient access to remove item C:\Program
Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1007.1\PSGetModuleInfo.xml. Does this affect installing the dev version?

I have first installed the M365DSC module and then re-opened PowerShell as admin.

#### Verbose logs showing the problem

![image](https://user-images.githubusercontent.com/7880089/95825241-3a756080-0d39-11eb-9dde-3aa02a9e3d20.png)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)

Name            Version
----            -------
Microsoft365DSC 1.20.1007.1

**Comment by hapklaar** [comment]
I have the exact same issue, on multiple machines.
