### ISSUE TITLE
Update documentation on microsoft365dsc.com to include the reporting cmdlets

### ISSUE THREAD

**Issue by TuomasPakkanen** [microsoft/Microsoft365DSC#827]
The Report section nor the getting started section on https://microsoft365dsc.com/ does not include the cmdlets how to export the XLSX or HTML report out of the .ps1 files. Please include those in the documentation for easier access to new users.

Should New-M365DSCConfigurationToExcel and New-M365DSCConfigurationToHTML or New-M365DSCReportFromConfiguration be used?

**Comment by NikCharlebois** [comment]
New-M365DSCReportFromConfiguration is the Umbrella method we should be using. Documentation has been updated on the official web site.
