### ISSUE TITLE
Error action continue

### ISSUE THREAD

**Issue by TuomasPakkanen** [microsoft/Microsoft365DSC#829]
As there seems to be still many errors with the tool, it would be great to have an error action continue option or it could work like that by default. It's been quite a bit of effort running the tool due to errors in several parts (opened other issues on these). Have to uncheck specific parts and re-run, which takes a lot of time at this moment.

**Comment by NikCharlebois** [comment]
@TuomasPakkanen what version of the tool are you using? We recently updated the entire Error handling across all resources and I'd like to make sure no resources fell through the cracks. Thanks

**Comment by TuomasPakkanen** [comment]
Good to know. I have 1.20.1007.1. Latest issues I've found were with the export-M365configuration and especially the Teams part, if that helps.

**Comment by NikCharlebois** [comment]
@TuomasPakkanen Are there specific resources that are giving the errors?

**Comment by TuomasPakkanen** [comment]
> @TuomasPakkanen Are there specific resources that are giving the errors?

Especially TeamsCallingPolicy,TeamsTenantDialPlan,TeamsUpgradePolicy and TeamsVoiceRoutingPolicy if I recall correctly.
