### ISSUE TITLE
No button to start extraction

### ISSUE THREAD

**Issue by hapklaar** [microsoft/Microsoft365DSC#831]
After installing the module using the provided instructions and starting Export-M365DSCConfiguration I have no option to start the extraction. The button seems to be missing, also after entering tenant credentials.

Tried installing on 3 different machines, but see the same on all three. 

![image](https://user-images.githubusercontent.com/7703320/95861628-01051b00-0d62-11eb-8fb9-93d51a66a1c2.png)

**Comment by jeff29922** [comment]
@NikCharlebois this is the 2nd time we have gotten feedback that the extraction button is missing.

**Comment by jdevney** [comment]
As a workaround, hitting 'enter' after selecting the extraction modes kicks-off the extraction process. The button is just not visible in the GUI, but the function works.
