### ISSUE TITLE
Export-M365DSCConfiguration fails at 2/43 when scoped to only SCDLPomplianceRule extract

### ISSUE THREAD

**Issue by tolarianNZ** [microsoft/Microsoft365DSC#833]
#### Details of the scenario you tried and the problem that is occurring
Attempting to extract DLP Rules (policies work fine).

Either using the GUI to select only SCC DLP Compliance Rules, or Export-M365DSCConfiguration -Quiet -ComponentsToExtract @('SCDLPComplianceRule')).

#### Verbose logs showing the problem

PS C:\Source> Export-M365DSCConfiguration                                                                               
[INFO] You can perform an equivalent unattended Export operation by running the following command:
Export-M365DSCConfiguration -Quiet -ComponentsToExtract @('SCDLPComplianceRule')
[1/1] Extracting [SCDLPComplianceRule]...
    |---[1/43] High volume of PII content detected - Finance✅
    |---[2/43] Detect attachments⌛ Export took {201 seconds}

... and then it just finishes, requests destination, and exits.

I'm able to produce this manually using get-dlpcompliancerule - but want to be able to restore/build the policies+rules using powershell/scripts, but that proves the tenant is working at least, and seems to be an issue with this module.

Could it be length of rule name?   The rule it stops on it 62 characters long, and we have some with longer names.

Name: High volume of PII content detected - ESO - LPG - Op Integrity

M365TenantConfig.ps1 contains effectively no data:

Generated with Microsoft365DSC version 1.20.1007.1
For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
Configuration M365TenantConfig
{
    $OrganizationName = $ConfigurationData.NonNodeData.OrganizationName
    Import-DscResource -ModuleName Microsoft365DSC

    Node localhost
    {
    }
}
M365TenantConfig -ConfigurationData .\ConfigurationData.psd1

VERBOSE OUTPUT provides no extra information.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
Either using the GUI or the PS Cmdlet above produce the same output.

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}

#### Version of the DSC module that was used ('dev' if using current dev branch)

**Comment by NikCharlebois** [comment]
Cannot replicate. Please re-open if you are able to replicate on your end with the latest version of the solution.
