### ISSUE TITLE
One or more errors occurred.: authority_validation_failed: Unknown error

### ISSUE THREAD

**Issue by jdcardoso86** [microsoft/Microsoft365DSC#835]
#### Details of the scenario you tried and the problem that is occurring
The Configuration I'm trying to push is targeting the Teams Channels Policy. Microsoft DSC scripts are being executed in a server behind a proxy, nonetheless direct PowerShell connecting, i.e. Connect-MicrosoftTeams command line executiong seems to work with no issues. 
When the script Start-DSCConfiguration is executed if fails with the following error:

One or more errors occurred.: authority_validation_failed: Unknown error
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCloudLoginSkypeForBusiness
    + PSComputerName        : localhost

Looking into the verbose logs, available below, it's visible that the method Microsoft.Open.Teams.CommonLibrary.AadAuthenticationFailedException is throwing an exception.

#### Verbose logs showing the problem
Error = "{\r\n    \"Exception\":  {\r\n                      \"Message\":  \"PowerShell DSC resource MSFT_TeamsMeetingPolicy  failed to execute Test-TargetResource functionality with error message: One or more errors occurred.: authority_validation_failed: Unknown error \",\r\n                      \"Data\":  {\r\n\r\n                               },\r\n                      \"InnerException\":  {\r\n                                             \"ErrorRecord\":  \"One or more errors occurred.: authority_validation_failed: Unknown error\",\r\n                                             \"WasThrownFromThrowStatement\":  true,\r\n                                             \"Message\":  \"One or more errors occurred.: authority_validation_failed: Unknown error\",\r\n                                             \"Data\":  \"System.Collections.ListDictionaryInternal\",\r\n                                             \"InnerException\":  \"System.Management.Automation.CmdletInvocationException: One or more errors occurred.: authority_validation_failed: Unknown error ---\\u003e Microsoft.Open.Teams.CommonLibrary.AadAuthenticationFailedException: One or more errors occurred.: authority_validation_failed: Unknown error ---\\u003e System.AggregateException: One or more errors occurred. ---\\u003e Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: authority_validation_failed: Unknown error ---\\u003e Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: Service returned error. Check InnerException for more details ---\\u003e Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: Request to the endpoint timed out.

#### Suggested solution to the issue
No suggestions I'm afraid. I'm not ruling out that this is possible being caused by a local Windows Server configuration.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2848.amd64fre.rs1_release.190305-1856
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Using the version 1.20.1007.1

**Comment by jeff29922** [comment]
Obviously something going on with authentication. Let me do some testing.

**Comment by jdcardoso86** [comment]
> Obviously something going on with authentication. Let me do some testing.

Hi Jeff,
I supposed it's authentication related. What I don't quite get is the command line Export-M365DSCConfiguration works, i.e. is able to establish a PowerShell connection with Teams and retrieve the Configuration for the components requested, it is only when the Microsoft365DSC scripts are invoked through the execution of Start-DSCConfiguration that it fails.  I have already reviewed the WinRM settings, and WSMan settings, but couldn't find what could be causing the issue.

**Comment by jdcardoso86** [comment]
Hi Jeff,

Was able to overcome this issue.
Basically DSC runs under a system account, so if the server being used to run the DSC command is behind a web proxy, the Web proxy settings need to be set for the system account.
There are many ways to set web proxies, what I have done was the following:

1. Using PSExec from SysInternals I have launched Powershell under the System Account (psexec -i -s PowerShell.exe)
2. Run the following command line to set the system proxy to match IE (netsh winhttp import proxy source=ie)

Microsoft365 DSC is now fully working for me.
Anyone who comes across the same issue, check the web proxy configuration for the system account.
