### ISSUE TITLE
O365Group Keys need to Reflect Identity

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#85]
#### Details of the scenario you tried and the problem that is occurring
The O365Group resource currently uses DisplayName as the primary key, however I have recently ran into a scenario where multiple groups have the exact same display name, but different Identity. We should change the Key of the resource to rely on Identity to make sure the group is unique.

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Change the Resource's Key to be Identity

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

**Comment by NikCharlebois** [comment]
Off course the challenge is that Security Groups don't have Identities. Changing this as a question:

Should we split O365Group into 2 resources:
O365Groups
O365SecurityGroups

Pinging my EXO folks: @poiriersimon @RobBiddle @SammyKrosoft

**Comment by RobBiddle** [comment]
I agree, those should be split into separate resources.

Also, I was planning on adding a separate resource for O365 Unified Groups, which has some potential overlap with the TeamsTeam resource since a new Team creates a Unified Group if an existing one isn't specified.  We'll need to cover the caveats of configuration resource order (e.g. for things like Outlook group visibility) in the documentation.

**Comment by RobBiddle** [comment]
Another thing to consider.  Should the group related resources be able to change the group type on an existing group?

**Comment by NikCharlebois** [comment]
@RobBiddle very good point. I believe we don't want to go to the extent of allowing a Security Group to become an Office 365 Group. Under the cover those really are 2 different entities and quite honestly, having both entity type handled by the same resources gives the impression that these GroupType are interchangeable when they are not. Having them handled by two different resources will stop giving the impression that we can easily flip back and forth between types I think.

**Comment by markroloff** [comment]
Hey guys!

Anybody actively working on this? I've been using my own scripts to handle migrating groups between tenants but have been meaning to cut my teeth on writing DSC resources, as I feel like it'd work better. Happy to take a stab at it!

**Comment by jeff29922** [comment]
@markroloff I don't think anyone is actively working on this, please feel free to take a shot at it.

**Comment by NikCharlebois** [comment]
@markroloff I will actually go ahead and close this. Now that Azure AD is part of M365DSC, we have a new AADMSGroup resource that will handle this. More than happy to have your look through the backlog and pick any resource you'd like to help working on!

**Comment by markroloff** [comment]
@NikCharlebois no worries! I got stuck in a bit of analysis-paralysis and then work took a dump on me, so no big loss 😂

Will definitely be scouring the backlog for anything I think I can jump on.
