### ISSUE TITLE
M365DSCUtil is missing the Test-M365DSCObjectHasProperty function

### ISSUE THREAD

**Issue by EricHindrichsen** [microsoft/Microsoft365DSC#861]
While looking through M365DSCUtil's Test-M365DSCParameterState function and trying to understand what it does I stumbled across the following line of code:

`$CheckDesiredValue = Test-M365DSCObjectHasProperty -Object $DesiredValues -PropertyName $_`

I can't find the function 'Test-M365DSCObjectHasProperty' anywhere. Is it part of a different module?

**Comment by NikCharlebois** [comment]
Very good catch @EricHindrichsen. So a bit of a history lesson 😄, the core Util module evolved from a copy of what we're doing in SharePointDSC (cc'ing @ykuijs). The method is actually called Test-SPDscObjectHasProperty:
https://github.com/dsccommunity/SharePointDsc/blob/a821727468457269e368b222fd0986f43cb62793/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L811

I believe this was somehow lost in translation back in April when the rebranding to M365DSC happened. The method will be re-introduced in the next release (1.20.1028.1). Stay tuned for a PR coming soon.

**Comment by EricHindrichsen** [comment]
Alright, looking forward to it! The missing function didn't cause any trouble for us yet, so no rush at least from my side.
________________________________
