### ISSUE TITLE
[AADMSGroup] MailNickNames won’t be changed for existing groups.

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#863]
#### Details of the scenario you tried and the problem that is occurring
Changing a MailNickName for an existing group in AAD will have no effect. 
Assume a group exist and its confguration should get verified by DSC - the MailNickName parameter will get disregarded.
#### Verbose logs showing the problem
No output, it simply will keep reporting a configuration drift even after the configuration got successfully applied to the tenant.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
Current production branach (1.20.1021.1).

**Comment by desmay** [comment]
@NikCharlebois I'll take this issue
