### ISSUE TITLE
[SPOSharingSettings] FolderAnonymousLinkType and FileAnonymousLinkType should be ignored when Anonymous access links aren’t enabled for the organization

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#865]
#### Details of the scenario you tried and the problem that is occurring
When Anonymous access links aren’t enabled for the organization, then the DSC module should disregard FolderAnonymousLinkType and FileAnonymousLinkType. Setting these two parameters will fail if anonymous access links aren’t enabled for the organization.
#### Suggested solution to the issue
Settings for FolderAnonymousLinkType and FileAnonymousLinkType should be ignored if anonymous links aren't allowed for SPO.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```
SPOSharingSettings 123
        {
            ...
            FileAnonymousLinkType                      = "View"; Can only be set if anoyn links are enabled.
            FolderAnonymousLinkType                    = "View"; Can only be set if anoyn links are enabled.
           ...
            SharingCapability                          = "ExternalUserSharingOnly";
            ....
        }
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
Current production branach (1.20.1021.1).

**Comment by desmay** [comment]
@SebastianGoers Trying to get this resolved for next release
