### ISSUE TITLE
[SPOSharingSettings] SharingAllowedDomainList needs to be an array 

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#866]
#### Details of the scenario you tried and the problem that is occurring
We would like to configure a set of domains to be whitelisted in the SharingAllowedDomainList. When entering the domains in non-alphabetical order in the DSC configuration, then Test-DscConfiguration will always detect a configuration drift, because it is using string comparison. Get-DscConfiguration always returns the domain list in alphabetical order which is why the string comparison will fail.

#### Suggested solution to the issue
We would suggest to handle the domain list as an array. The array comparison (e.g. using Compare-Object in the Utils module) will work regardless of the order in which the domains have been provided in the config.
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
Current production branach (1.20.1021.1).

**Comment by desmay** [comment]
@SebastianGoers working on this change
