### ISSUE TITLE
Problem when automating config download

### ISSUE THREAD

**Issue by MarkBarl** [microsoft/Microsoft365DSC#891]
#### Details of the scenario you tried and the problem that is occurring
When downloading configuration from Teams if I include the -GlobalAdminAccount switch with the $creds = Get-Credential I get a warning that says "[WARNING] Based on the provided Authentication parameters, the following resources cannot be extracted: 
TeamsGuestMessagingCon
figuration TeamsM
essagingPolicy"

If I run the same command by export-M365Configuration and pick the items it runs fine.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
$creds = Get-Credential
$DateTime = get-date -f yyyy-MM-dd_hh.mm
$folder = get-date -f yyyy-MM-dd
$TargetDir = "C:\DSC\ConfigDownloads\$folder"
if( -Not (Test-Path $TargetDir ) )
{
    New-Item -ItemType directory -Path $TargetDir
    }

Export-M365DSCConfiguration -Quiet -GlobalAdminAccount $creds -ComponentsToExtract @('TeamsChannelsPolicy','TeamsClientConfiguration','TeamsGuestMeetingConfiguration','TeamsGuestMessagingCon
figuration','TeamsMeetingBroadcastConfiguration','TeamsMeetingBroadcastPolicy','TeamsMeetingConfiguration','TeamsMeetingPolicy','TeamsM
essagingPolicy') -FileName "$($DateTime)_TeamsConfig.ps1" -Path "C:\DSC\ConfigDownloads\$($folder)" -ConfigurationName "PBL365TeamsConfig"

#### Version of the DSC module that was used ('dev' if using current dev branch)
 1.20.1104.1

**Comment by NikCharlebois** [comment]
Seems like this is related to your command. TeamsMessagingPolicy is broken onto two lines in your example above. I can replicate your issue by keeping this the same. However, if I put all the Export-M365DSCConfiguration command on 1 line, then it starts working. Thanks
