### ISSUE TITLE
Setting up Microsoft 365DSC in DevOps

### ISSUE THREAD

**Issue by mdcaddic** [microsoft/Microsoft365DSC#902]
Putting this here because although the issue is with the blog people will come here to find out. 
I'm setting up Microsoft365DSC in DevOps as per Eps 74. Really nice work btw. I tried doing this all manually ages ago and gave up so I know how much effort you've been to.

https://o365eh.com/2020/10/27/episode-74-using-microsoft-dsc-as-a-runbook-in-azure-automation/
Cheers

A couple of issues tho.

For setting up the pre-reqs I copied the code and it failed on the search. When I went back to the 4bes link and copied part of that it worked.

Issue seems to be the %amp in the url.

The other thing is a typo in $CheckInsalled. I assume you mean $CheckInstalled ?
Also,
The Microsoft.Graph.Groups.Planner failed on the import the first time. Microsoft365DSC then failed but everything else worked. When I retried both plannner and M365 worked ok.

Error importing the module Microsoft.Graph.Groups.Planner. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: An error occurred during module validation. When importing the module to an internal PowerShell session, it was not able to be loaded by PowerShell. There is likely an issue with the contents of the module that results in PowerShell's not being able to load it. Please verify that the module imports successfully in a local PowerShell session, correct any issues, and then try importing again.

**Comment by hmank** [comment]
Thanks @mdcaddic for the feedback, seems to have been a copy/paste issue when we created the post. I have updated the blog post to fix the URL and also fixed the typo. I'm not sure exactly sure what the error about the Microsoft.Graph.Groups.Planner failing to import. I have just created a new azure automation account and used the script and it imported without issue.

**Comment by NikCharlebois** [comment]
Thanks folks. Now closing this.
