### ISSUE TITLE
Issue with New-M365DSCDeltaReport 

### ISSUE THREAD

**Issue by lokeshmaganti** [microsoft/Microsoft365DSC#904]
#### Details of the scenario you tried and the problem that is occurring
New-M365DSCDeltaReport -Source "D:\Folder1\SB\SBTenantExtract.ps1" -Destination "D:\Folder1\PPE\PPETenantExtract.ps1" -OutputPath "D:\Folder1\Microsoft365DSC\Delta.html"

#### Verbose logs showing the problem
Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1104.1\modules\M365DSCReport.psm1:305 char:13
+             $drift = @{
+             ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1104.1\modules\M365DSCReport.psm1:305 char:13
+             $drift = @{
+             ~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Get-IconPath : Cannot bind argument to parameter 'ResourceName' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1104.1\modules\M365DSCReport.psm1:669 char:52
+ ...         $iconPath = Get-IconPath -ResourceName $resource.ResourceName
+                                                    ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-IconPath], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-IconPath

Get-IconPath : Cannot bind argument to parameter 'ResourceName' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1104.1\modules\M365DSCReport.psm1:669 char:52
+ ...         $iconPath = Get-IconPath -ResourceName $resource.ResourceName
+                                                    ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-IconPath], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-IconPath

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
We have used the below command to generate report of existing configuration from tenant and then ran the same cmdlet for a different tenant and tried to compare the difference in configurations between both the tenants

Export-M365DSCConfiguration -Quiet -Path "D:\Folder1\" -FileName "PPETenantExtract.ps1" -ConfigurationName 
"PPETenantConfig" -Workloads @("SPO","TEAMS","OD","SC","PP","O365","EXO") -GlobalAdminAccount (Get-Credential)

# insert configuration here
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19846.amd64fre.winblue_ltsb_escrow.200923-1735
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)

Name              : Microsoft365DSC
Path              : C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1104.1\Microsoft365DSC.psd1
Description       : This DSC module is used to configure and monitor Microsoft tenants, including SharePoint Online,
                    Exchange, Teams, etc.
ModuleType        : Manifest
Version           : 1.20.1104.1

**Comment by NikCharlebois** [comment]
@lokeshmaganti any chances you could post the .ps1 so that the team can investigate? (Remove usernames and redact out whatever sensitive information). Thanks
