### ISSUE TITLE
Export-M365DSCConfiguration Memory Issues

### ISSUE THREAD

**Issue by ZanattaMichael** [microsoft/Microsoft365DSC#931]
#### Details of the scenario you tried and the problem that is occurring
When Running: Export-M365DSCConfiguration (Full) against a test tenancy (with large number of MSTeams), a large amount of memory is consumed when performing an export. Intermittent errors occur when performing the export (Exceeded Memory Limit). (My Machine has 32GB of Memory)

#### Suggested solution to the issue

1. Implementation of PSFramework and use clixml caching mechanism to free up memory.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)

Version
-------
1.20.1104.1

**Comment by NikCharlebois** [comment]
@ZanattaMichael this is not a behavior we are able to observe on our end. Can you confirm that you are using PowerShell 5.1 and running a single Export-M365DSCConfiguration command?

**Comment by ZanattaMichael** [comment]
This is a 1 single export running on PowerShell 5.1.
