### ISSUE TITLE
Cleanup of Memory After Export-M365DSCConfiguration

### ISSUE THREAD

**Issue by ZanattaMichael** [microsoft/Microsoft365DSC#932]
#### Details of the scenario you tried and the problem that is occurring

After running multiple Export-M365DSCConfiguration, memory. Also the PowerShell Session has a large amount of memory still in use.  Also CredentialProvider.Microsoft.exe still remains active in the background, causing a conhost.exe PowerShell session to remain open. By terminating the app, additional memory can be freed up.

#### Suggested solution to the issue

- Implement Function Teardown, $null all lists that are no longer being used and remove.
- Cache existing lists using PSFramework.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
Version
-------
1.20.1104.1

**Comment by NikCharlebois** [comment]
@ZanattaMichael Are you running multiple Export-M365DSCConfiguration in parallel or one after the other? Thanks

**Comment by ZanattaMichael** [comment]
As a workaround to Issue 931, I was running the export in PowerShell Job in batches of 5. Since they are running in a separate PowerShell runspaces, once the runspace is terminated the memory should be freed up.
