### ISSUE TITLE
Errors importing Exchange Policies

### ISSUE THREAD

**Issue by aoverington-cyclone** [microsoft/Microsoft365DSC#933]
### Details of the scenario you tried and the problem that is occurring
Errors when copying config to new tenant. Seems to only be impacting EXO policies

#### Verbose logs showing the problem
VERBOSE: [DESKTOP-GJP45CT]: LCM:  [ End    Test     ]  [[EXOAntiPhishPolicy]e742377c-29e3-4b17-9561-d47b860a2f26]  in   21.5240 seconds.                                                                                                        PowerShell DSC resource MSFT_EXOAntiPhishPolicy  failed to execute Test-TargetResource functionality with error         message: Parameter cannot be processed because the parameter name 'Certificate' is ambiguous. Possible matches          include: -CertificateFilePath -CertificatePassword -CertificateThumbprint.                                                  + CategoryInfo          : InvalidOperation: (:) [], CimException                                                        + FullyQualifiedErrorId : ProviderOperationExecutionFailure                                                             + PSComputerName        : localhost           

VERBOSE: [DESKTOP-GJP45CT]: LCM:  [ End    Test     ]  [[EXOAtpPolicyForO365]ca7db14c-3b55-45fd-a103-7bb16d61ab1e]  in  21.5760 seconds.                                                                                                        PowerShell DSC resource MSFT_EXOAtpPolicyForO365  failed to execute Test-TargetResource functionality with error        message: Parameter cannot be processed because the parameter name 'Certificate' is ambiguous. Possible matches          include: -CertificateFilePath -CertificatePassword -CertificateThumbprint.                                                  + CategoryInfo          : InvalidOperation: (:) [], CimException                                                        + FullyQualifiedErrorId : ProviderOperationExecutionFailure                                                             + PSComputerName        : localhost           

VERBOSE: [DESKTOP-GJP45CT]: LCM:  [ End    Test     ]                                                                   [[EXOHostedConnectionFilterPolicy]4da351cd-072c-44be-ae33-b1342f46a7f8]  in 21.7750 seconds.                            PowerShell DSC resource MSFT_EXOHostedConnectionFilterPolicy  failed to execute Test-TargetResource functionality with  error message: Parameter cannot be processed because the parameter name 'Certificate' is ambiguous. Possible matches    include: -CertificateFilePath -CertificatePassword -CertificateThumbprint.                                                  + CategoryInfo          : InvalidOperation: (:) [], CimException                                                        + FullyQualifiedErrorId : ProviderOperationExecutionFailure                                                             + PSComputerName        : localhost                

VERBOSE: [DESKTOP-GJP45CT]: LCM:  [ End    Test     ]                                                                   [[EXOHostedContentFilterPolicy]70ce3b0f-0bc1-40e7-88ce-d7f3f9b41a81]  in 21.9210 seconds.                               PowerShell DSC resource MSFT_EXOHostedContentFilterPolicy  failed to execute Test-TargetResource functionality with     error message: Parameter cannot be processed because the parameter name 'Certificate' is ambiguous. Possible matches    include: -CertificateFilePath -CertificatePassword -CertificateThumbprint.                                                  + CategoryInfo          : InvalidOperation: (:) [], CimException                                                        + FullyQualifiedErrorId : ProviderOperationExecutionFailure                                                             + PSComputerName        : localhost                                 

VERBOSE: [DESKTOP-GJP45CT]: LCM:  [ End    Test     ]  [[EXOMalwareFilterPolicy]73db8c61-c6d2-40b5-be9a-9e64b2746643]   in 10.2880 seconds.                                                                                                     PowerShell DSC resource MSFT_EXOMalwareFilterPolicy  failed to execute Test-TargetResource functionality with error     message: Parameter cannot be processed because the parameter name 'Certificate' is ambiguous. Possible matches          include: -CertificateFilePath -CertificatePassword -CertificateThumbprint.                                                  + CategoryInfo          : InvalidOperation: (:) [], CimException                                                        + FullyQualifiedErrorId : ProviderOperationExecutionFailure                                                             + PSComputerName        : localhost        

VERBOSE: [DESKTOP-GJP45CT]: LCM:  [ End    Test     ]  [[EXOMalwareFilterPolicy]b5951519-c9ea-4392-8e71-1541224f1eaf]   in 21.3000 seconds.                                                                                                     PowerShell DSC resource MSFT_EXOMalwareFilterPolicy  failed to execute Test-TargetResource functionality with error     message: Parameter cannot be processed because the parameter name 'Certificate' is ambiguous. Possible matches          include: -CertificateFilePath -CertificatePassword -CertificateThumbprint.                                                  + CategoryInfo          : InvalidOperation: (:) [], CimException                                                        + FullyQualifiedErrorId : ProviderOperationExecutionFailure                                                             + PSComputerName        : localhost             

VERBOSE: [DESKTOP-GJP45CT]: LCM:  [ End    Test     ]  [[EXOMalwareFilterRule]4ea1400e-2eac-41e6-8dbd-59366dcf0889]  in  22.7050 seconds.                                                                                                       PowerShell DSC resource MSFT_EXOMalwareFilterRule  failed to execute Test-TargetResource functionality with error       message: Parameter cannot be processed because the parameter name 'Certificate' is ambiguous. Possible matches          include: -CertificateFilePath -CertificatePassword -CertificateThumbprint.                                                  + CategoryInfo          : InvalidOperation: (:) [], CimException                                                        + FullyQualifiedErrorId : ProviderOperationExecutionFailure                                                             + PSComputerName        : localhost                                   

VERBOSE: [DESKTOP-GJP45CT]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# Generated with Microsoft365DSC version 1.20.1118.1
# For additional information on how to use Microsoft365DSC, please visit https://aka.ms/M365DSC
param (
    [parameter()]
    [System.Management.Automation.PSCredential]
    $GlobalAdminAccount
)

Configuration M365TenantConfig
{
    param (
        [parameter()]
        [System.Management.Automation.PSCredential]
        $GlobalAdminAccount
    )

    if ($null -eq $GlobalAdminAccount)
    {
        <# Credentials #>
        $Credsglobaladmin = Get-Credential -Message "Global Admin credentials"

    }
    else
    {
        $Credsglobaladmin = $GlobalAdminAccount
    }

    $OrganizationName = $Credsglobaladmin.UserName.Split('@')[1]
    Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.20.1118.1'

    Node localhost
    {
        EXOAntiPhishPolicy e742377c-29e3-4b17-9561-d47b860a2f26
        {
            AdminDisplayName                    = "";
            AuthenticationFailAction            = "MoveToJmf";
            EnableAntispoofEnforcement          = $True;
            Enabled                             = $True;
            EnableMailboxIntelligence           = $True;
            EnableOrganizationDomainsProtection = $False;
            EnableSimilarDomainsSafetyTips      = $False;
            EnableSimilarUsersSafetyTips        = $False;
            EnableTargetedDomainsProtection     = $False;
            EnableTargetedUserProtection        = $False;
            EnableUnusualCharactersSafetyTips   = $False;
            Ensure                              = "Present";
            ExcludedDomains                     = @();
            ExcludedSenders                     = @();
            GlobalAdminAccount                  = $Credsglobaladmin;
            Identity                            = "Office365 AntiPhish Default";
            PhishThresholdLevel                 = 1;
            TargetedDomainActionRecipients      = @();
            TargetedDomainProtectionAction      = "NoAction";
            TargetedDomainsToProtect            = @();
            TargetedUserActionRecipients        = @();
            TargetedUserProtectionAction        = "NoAction";
            TargetedUsersToProtect              = @();
        }
        EXOAtpPolicyForO365 ca7db14c-3b55-45fd-a103-7bb16d61ab1e
        {
            AllowClickThrough         = $False;
            BlockUrls                 = @();
            EnableATPForSPOTeamsODB   = $True;
            EnableSafeLinksForClients = $False;
            Ensure                    = "Present";
            GlobalAdminAccount        = $Credsglobaladmin;
            Identity                  = "Default";
            IsSingleInstance          = "Yes";
            TrackClicks               = $False;
        }
        EXOHostedConnectionFilterPolicy 4da351cd-072c-44be-ae33-b1342f46a7f8
        {
            AdminDisplayName     = "";
            EnableSafeList       = $False;
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Identity             = "Default";
            IPAllowList          = @();
            IPBlockList          = @();
            MakeDefault          = $False;
        }
        EXOHostedContentFilterPolicy 70ce3b0f-0bc1-40e7-88ce-d7f3f9b41a81
        {
            AddXHeaderValue                          = "";
            AdminDisplayName                         = "";
            AllowedSenderDomains                     = @();
            AllowedSenders                           = @();
            BlockedSenderDomains                     = @("badagent.com");
            BlockedSenders                           = @();
            BulkSpamAction                           = "MoveToJmf";
            BulkThreshold                            = 7;
            DownloadLink                             = $False;
            EnableEndUserSpamNotifications           = $False;
            EnableLanguageBlockList                  = $False;
            EnableRegionBlockList                    = $False;
            EndUserSpamNotificationCustomFromAddress = "";
            EndUserSpamNotificationCustomFromName    = "";
            EndUserSpamNotificationCustomSubject     = "";
            EndUserSpamNotificationFrequency         = 3;
            EndUserSpamNotificationLanguage          = "Default";
            Ensure                                   = "Present";
            GlobalAdminAccount                       = $Credsglobaladmin;
            HighConfidenceSpamAction                 = "MoveToJmf";
            Identity                                 = "Default";
            IncreaseScoreWithBizOrInfoUrls           = "Off";
            IncreaseScoreWithImageLinks              = "Off";
            IncreaseScoreWithNumericIps              = "Off";
            IncreaseScoreWithRedirectToOtherPort     = "Off";
            InlineSafetyTipsEnabled                  = $True;
            LanguageBlockList                        = @();
            MakeDefault                              = $True;
            MarkAsSpamBulkMail                       = "On";
            MarkAsSpamEmbedTagsInHtml                = "Off";
            MarkAsSpamEmptyMessages                  = "Off";
            MarkAsSpamFormTagsInHtml                 = "Off";
            MarkAsSpamFramesInHtml                   = "Off";
            MarkAsSpamFromAddressAuthFail            = "Off";
            MarkAsSpamJavaScriptInHtml               = "Off";
            MarkAsSpamNdrBackscatter                 = "Off";
            MarkAsSpamObjectTagsInHtml               = "Off";
            MarkAsSpamSensitiveWordList              = "Off";
            MarkAsSpamSpfRecordHardFail              = "Off";
            MarkAsSpamWebBugsInHtml                  = "Off";
            ModifySubjectValue                       = "";
            PhishSpamAction                          = "MoveToJmf";
            PhishZapEnabled                          = $True;
            QuarantineRetentionPeriod                = 15;
            RedirectToRecipients                     = @();
            RegionBlockList                          = @();
            SpamAction                               = "MoveToJmf";
            SpamZapEnabled                           = $True;
            TestModeAction                           = "None";
            TestModeBccToRecipients                  = @();
        }
        EXOMalwareFilterPolicy 73db8c61-c6d2-40b5-be9a-9e64b2746643
        {
            Action                                 = "DeleteAttachmentAndUseCustomAlert";
            CustomAlertText                        = "You got a message with a bad thing.
We exterminated it,
You are welcome";
            CustomNotifications                    = $False;
            EnableExternalSenderAdminNotifications = $False;
            EnableExternalSenderNotifications      = $False;
            EnableFileFilter                       = $True;
            EnableInternalSenderAdminNotifications = $False;
            EnableInternalSenderNotifications      = $False;
            Ensure                                 = "Present";
            FileTypes                              = @("ace","ani","app","docm","exe","jar","reg","scr","vbe","vbs");
            GlobalAdminAccount                     = $Credsglobaladmin;
            Identity                               = "Demo Malware Policy";
            ZapEnabled                             = $True;
        }
        EXOMalwareFilterPolicy b5951519-c9ea-4392-8e71-1541224f1eaf
        {
            Action                                 = "DeleteAttachmentAndUseCustomAlert";
            CustomAlertText                        = "You got a bad email. We saved you. You are welcome.
";
            CustomNotifications                    = $False;
            EnableExternalSenderAdminNotifications = $False;
            EnableExternalSenderNotifications      = $False;
            EnableFileFilter                       = $False;
            EnableInternalSenderAdminNotifications = $False;
            EnableInternalSenderNotifications      = $False;
            Ensure                                 = "Present";
            FileTypes                              = @("ace","ani","app","docm","exe","jar","reg","scr","vbe","vbs");
            GlobalAdminAccount                     = $Credsglobaladmin;
            Identity                               = "Default";
            ZapEnabled                             = $True;
        }
        EXOMalwareFilterRule 4ea1400e-2eac-41e6-8dbd-59366dcf0889
        {
            Ensure               = "Present";
            GlobalAdminAccount   = $Credsglobaladmin;
            Identity             = "Demo Malware Policy";
            MalwareFilterPolicy  = "Demo Malware Policy";
            Priority             = 0;
            SentTo               = @("AllanD@$OrganizationName");
        }
        ODSettings 49679a14-4dcd-48e5-887c-1f55b57661e8
        {
            BlockMacSync                              = $False;
            DisableReportProblemDialog                = $False;
            DomainGuids                               = @();
            Ensure                                    = "Present";
            ExcludedFileExtensions                    = @("swf","apk");
            GlobalAdminAccount                        = $Credsglobaladmin;
            IsSingleInstance                          = "Yes";
            NotificationsInOneDriveForBusinessEnabled = $True;
            NotifyOwnersWhenInvitationsAccepted       = $True;
            ODBAccessRequests                         = "Unspecified";
            ODBMembersCanShare                        = "Unspecified";
            OneDriveForGuestsEnabled                  = $False;
            OneDriveStorageQuota                      = 524288;
            OrphanedPersonalSitesRetentionPeriod      = 60;
        }
    }
}
M365TenantConfig -ConfigurationData .\ConfigurationData.psd1 -GlobalAdminAccount $GlobalAdminAccount

```

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, en-US, mi-NZ}

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.20.1118.1

**Comment by NikCharlebois** [comment]
Fixed with a recent release of the MSCloudLoginAssistant module
