### ISSUE TITLE
Typos and formatting on page https://microsoft365dsc.com/Pages/GettingStarted/#Install

### ISSUE THREAD

**Issue by bubbletroubles** [microsoft/Microsoft365DSC#945]
There are a few typos and formatting on the page https://microsoft365dsc.com/Pages/GettingStarted/#Install

In the ```-MaxProcesses``` table, the word ```speficy```  should be ```specify```.

In the table under the heading **Extracting Configuration from an Existing Microsoft 365 Tenant**, the **Description** box has multi-line commands rendered on one line

![image](https://user-images.githubusercontent.com/42738824/100575354-02010480-3330-11eb-8481-91530b61f3f9.png)

should be

```
$creds = Get-Credential
Export-M365DSCConfiguration -Quiet -GlobalAdminAccount $creds
```

**Comment by NikCharlebois** [comment]
Thanks for reporting. It has now been fixed.
