### ISSUE TITLE
Access Denied message on Get-DscLocalConfigurationManager

### ISSUE THREAD

**Issue by JayBarre** [microsoft/Microsoft365DSC#955]
Dear Team,

I am using M365DSC export wizard to export my current tenant policies, however at the end when I give path to save the file, I get below error. Tried different paths but issue persists. 

PS C:\Users\jp38gd\OneDrive - ING\Documents> Get-DscLocalConfigurationManager
Get-DscLocalConfigurationManager : Access denied
At line:1 char:1
+ Get-DscLocalConfigurationManager
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (MSFT_DSCLocalConfigurationManager:root/Microsoft/...gurationManager) [Get-DscLocalConfigurationManager],
   CimException
    + FullyQualifiedErrorId : HRESULT 0x80041003,Get-DscLocalConfigurationManager

**Comment by NikCharlebois** [comment]
Just to confirm, are you running the PowerShell session as an admin? Thanks

**Comment by JayBarre** [comment]
Sorry mate, it wasn't, tried by running as an admin, all good now :)

**Comment by NikCharlebois** [comment]
Yeah, that's one that bites me every now and then as well. Glad it works now!
