### ISSUE TITLE
Delta Report  command throwing errors

### ISSUE THREAD

**Issue by lokeshmaganti** [microsoft/Microsoft365DSC#957]
#### Details of the scenario you tried and the problem that is occurring

Have exported the settings for SPO, teams and OneDrive twice from the tenant between gap of an week. Below are the command used and we tried to generate delta report but have seen couple of errors in the powershell window. The report was generated but it was all empty. The export of settings was successful and have looked at ps1 and there were no errors

Export-M365DSCConfiguration -Quiet -Path "D:\Lokesh 2\SPO\Microsoft365DSC\ProdExtract\" -FileName "ProdTenantExtract1.ps1" -ConfigurationName "ProdTenantConfig1" -Workloads @("SPO","TEAMS","OD") -GlobalAdminAccount (Get-Credential)

Export-M365DSCConfiguration -Quiet -Path "D:\Lokesh 2\SPO\Microsoft365DSC\ProdExtract\" -FileName "ProdTenantExtract1_SPOOD.ps1" -ConfigurationName "ProdTenantConfig1_SPOOD" -Workloads @("SPO","TEAMS","OD") -GlobalAdminAccount (Get-Credential)

**Delta Report command**
New-M365DSCDeltaReport -Source "D:\Lokesh 2\SPO\Microsoft365DSC\ProdExtract\ProdTenantExtract1_SPOOD.ps1" -Destination "D:\Lokesh 2\SPO\Microsoft365DSC\ProdExtract\ProdTenantExtract1.ps1" -OutputPath "D:\Lokesh 2\SPO\Microsoft365DSC\ProdExtract\Delta.htm"

#### Verbose logs showing the problem

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1118.1\modules\M365DSCReport.psm1:296 char:88
+ ... lterScript {$_.ResourceName -eq $sourceResource.ResourceName -and $_. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1118.1\modules\M365DSCReport.psm1:296 char:88
+ ... lterScript {$_.ResourceName -eq $sourceResource.ResourceName -and $_. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1118.1\modules\M365DSCReport.psm1:296 char:88
+ ... lterScript {$_.ResourceName -eq $sourceResource.ResourceName -and $_. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1118.1\modules\M365DSCReport.psm1:296 char:88
+ ... lterScript {$_.ResourceName -eq $sourceResource.ResourceName -and $_. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1118.1\modules\M365DSCReport.psm1:296 char:88
+ ... lterScript {$_.ResourceName -eq $sourceResource.ResourceName -and $_. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1118.1\modules\M365DSCReport.psm1:296 char:88
+ ... lterScript {$_.ResourceName -eq $sourceResource.ResourceName -and $_. ...

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

We have used the below command to generate report of existing configuration from tenant and then ran the same cmdlet after weeks time and tried to compare the difference in configurations between both the tenants

Export-M365DSCConfiguration -Quiet -Path "D:\Lokesh 2\SPO\Microsoft365DSC\ProdExtract\" -FileName "ProdTenantExtract1_SPOOD.ps1" -ConfigurationName "ProdTenantConfig1_SPOOD" -Workloads @("SPO","TEAMS","OD") -GlobalAdminAccount (Get-Credential)

# insert configuration here
```#### The operating system the target node is running
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19846.amd64fre.winblue_ltsb_escrow.200923-1735
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
Name              : Microsoft365DSC
Path              : C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.20.1104.1\Microsoft365DSC.psd1
Description       : This DSC module is used to configure and monitor Microsoft tenants, including SharePoint Online,
                    Exchange, Teams, etc.
ModuleType        : Manifest
Version           : 1.20.1118.1

**Comment by NikCharlebois** [comment]
Major revamps of the DSCParser module were done recenlty. Please make sure your update the solution (Microsoft365DSC) to the latest version and re-open the issue if the problem persists.
