### ISSUE TITLE
Microsoft 365 DSC Export feature via GUI

### ISSUE THREAD

**Issue by Brian-Madden-60** [microsoft/Microsoft365DSC#962]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by Swampen** [comment]
Do you mean that the export button is not shown in the GUI?

**Comment by Brian-Madden-60** [comment]
Hello,

Here is snapshot of UI.

Unable to fill in the Tenant ID field because the Start Extraction button is hidden and prevents it.

[A picture containing text  Description automatically generated]

Thanks, Brian

[cid:image002.jpg@01D6CAE2.5138E0B0]
Brian T. Madden
Progressive Insurance  •  End User Experience
IT Systems Engineer Lead
W 440.395.9152  C 440.221.2823

**Comment by Swampen** [comment]
I don't think you can attach images to an email reply.
Please go to the GitHub issue and attach the image again.

**Comment by Brian-Madden-60** [comment]
Attached Word document with snapshot of image to the GitHub issue.

Thanks, Brian

[cid:image001.jpg@01D6CAE5.2704DD00]
Brian T. Madden
Progressive Insurance  •  End User Experience
IT Systems Engineer Lead
W 440.395.9152  C 440.221.2823

**Comment by Swampen** [comment]
Still can't see the image because you replied by email.
Please reply here instead: https://github.com/microsoft/Microsoft365DSC/issues/962

**Comment by Brian-Madden-60** [comment]
[MSFTDSCIssue.docx](https://github.com/microsoft/Microsoft365DSC/files/5647209/MSFTDSCIssue.docx)
Attaching file of issue.

**Comment by Swampen** [comment]
This issue is fixed in release 1.20.1118.1
Simply update the module and it will be fixed.

**Comment by Brian-Madden-60** [comment]
Hello, file has been attached it issue.

Thanks, Brian

[cid:image001.jpg@01D6CAE9.575C8440]
Brian T. Madden
Progressive Insurance  •  End User Experience
IT Systems Engineer Lead
W 440.395.9152  C 440.221.2823

**Comment by Brian-Madden-60** [comment]
Hello,

Thanks did see the current version is 1.20.1202.1 and have downloaded it, will install early next week and verify issue resolved.

Thanks, Brian

[cid:image001.jpg@01D6CAEC.A03838A0]
Brian T. Madden
Progressive Insurance  •  End User Experience
IT Systems Engineer Lead
W 440.395.9152  C 440.221.2823

**Comment by jeff29922** [comment]
@Brian-Madden-60 please let me know the results your testing.  @NikCharlebois Brian is from Progressive Insurance.

**Comment by jeff29922** [comment]
@Brian-Madden-60 I am following up to see if you had a chance to do any testing on this yet?

**Comment by Brian-Madden-60** [comment]
Hi,

First issue was resolved with the extract button has been resolved.

New issue, Attempted to do export and GUI closed, error log was created (attached).  Export failed.

Let me know who to proceed.

Thanks, Brian

[cid:image001.jpg@01D6CD4A.0BC6CBE0]
Brian T. Madden
Progressive Insurance  •  End User Experience
IT Systems Engineer Lead
W 440.395.9152  C 440.221.2823

**Comment by Brian-Madden-60** [comment]
Resolved the 407 authentication issue in the log.

During the Export, was prompted for Destination Path and entered c:\temp\dsc, 2 files were created in the destination ConfigurationData.psd1 and M365TenantConfig.ps1

Ran the M365TenantConfig.ps1 and it generated a localhost.MOF file in the C:\temp\dsc\M365TenantConfig folder.

Looking at the MOF file, it had in account and password hard coded in the file. Not a good thing.

We should probably have another working session, can you set that up?


Logging
PS C:\WINDOWS\system32> Export-M365DSCConfiguration

[INFO] You can perform an equivalent unattended Export operation by running the following command:
Export-M365DSCConfiguration -Quiet -ComponentsToExtract @('O365OrgCustomizationSetting')

[1/1] Extracting [O365OrgCustomizationSetting]...✅
⌛ Export took {39 seconds}

Destination Path: c:\temp\dsc


Thanks, Brian

[cid:image001.jpg@01D6CD4D.72162C80]
Brian T. Madden
Progressive Insurance  •  End User Experience
IT Systems Engineer Lead
W 440.395.9152  C 440.221.2823


From: Brian T Madden <brian_madden@progressive.com>
Sent: Tuesday, December 8, 2020 10:08 AM
To: microsoft/Microsoft365DSC <reply@reply.github.com>; microsoft/Microsoft365DSC <Microsoft365DSC@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Reese T Holle <REESE_T_HOLLE@progressive.com>
Subject: RE: [EXTERNAL] Re: [microsoft/Microsoft365DSC] Microsoft 365 DSC Export feature via GUI (#962)

Hi,

First issue was resolved with the extract button has been resolved.

New issue, Attempted to do export and GUI closed, error log was created (attached).  Export failed.

Let me know who to proceed.

Thanks, Brian

[cid:image001.jpg@01D6CD4D.72162C80]
Brian T. Madden
Progressive Insurance  •  End User Experience
IT Systems Engineer Lead
W 440.395.9152  C 440.221.2823

**Comment by jeff29922** [comment]
@Brian-Madden-60 give me a chance to digest what you have sent over.  I will reach out to setup another working session.
