### ISSUE TITLE
Follow-up on [TeamsTenantDialPlan] Exporting a tenant dial plan fails #951

### ISSUE THREAD

**Issue by SebastianGoers** [microsoft/Microsoft365DSC#965]
Following up on [TeamsTenantDialPlan] Exporting a tenant dial plan fails #951 as it is still open and unresolved. 

Additional info: in the event log I can see the following:

Cannot process argument transformation on parameter 'Params'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Collections.Hashtable".

**Comment by NikCharlebois** [comment]
@SebastianGoers Can you try the following and se us the details:

$config = Get-CsTenantDialPlan -Identity <id of you tenant dial plan>
$rules = $config.NormalizationRules
$i = 1
foreach ($rule in $Rules)
    {
Write-Host "-------- Rule #$i ------------"
        $ruleName = $rule.Name.Replace("Tag:", "")
        $ruleObject = Get-CsVoiceNormalizationRule | Where-Object -FilterScript { $_.Name -eq $ruleName }
       $ruleObject.GetType()
       $ruleObject
       $i++
    }

**Comment by jeff29922** [comment]
@NikCharlebois @SebastianGoers let me know what I can do to help with this.

**Comment by SebastianGoers** [comment]
Hi @NikCharlebois , we have tested the code snippet you provided and here's the conclusion:
- Get-CsVoiceNormalizationRule returns a huge list of all normalization rules on the tenant but it does not contain the rules that we provided via the Teams admin UI. This is why your code fails on our end when filtering on the name property as the result is empty:
```
 You cannot call a method on a null-valued expression.
At line:13 char:2
+  $ruleObject.GetType()
+  ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```
- $config.NormalizationRules actually contains all the properties of our custom normlization rules, except Priority, Identity.

**Comment by sheidl** [comment]
Good finding @SebastianGoers. Was investigating the same issue, you are one hour ahead ;-)

Indeed Get-CsVoiceNormalizationRule only returns the pre-defined normalization rules, not the custom ones created in TAC or using New-CsTenantDialPlan 1 -NormalizationRules.

@NikCharlebois  So I think what we should do in M365 DSC is to work with /extract the NormalizationRules that are returned by get-cstenantdialplan rather than the ones returned by Get-CsVoiceNormalizationRule.
Get in touch with me if you want to further discuss this

**Comment by SebastianGoers** [comment]
This isn't fixed yet, is it? I have had a look at the recent code changes in the module but these do not touch Get-TenantConfiguration , yet.
