### ISSUE TITLE
TeamsDialInConfiguration

### ISSUE THREAD

**Issue by bubbletroubles** [microsoft/Microsoft365DSC#973]
### Description
Has anyone looked at including the MS Teams dial in conferencing tenant settings (e.g. what can be done via Set-CsOnlineDialInConferencingTenantSettings) in M365DSC? If not, I'm happy to have a go at creating a module for it. 

### Proposed properties
Allow configuring the following via DSC

  [-EnableEntryExitNotifications <Boolean>]
   [-EntryExitAnnouncementsType <EntryExitAnnouncementsType>]
   [-EnableNameRecording <Boolean>]
   [-IncludeTollFreeNumberInMeetingInvites <Boolean>]
   [-PinLength <UInt32>]
   [-AllowPSTNOnlyMeetingsByDefault <Boolean>]
   [-AutomaticallySendEmailsToUsers <Boolean>]
   [-SendEmailFromOverride <Boolean>]
   [-SendEmailFromAddress <String>]
   [-SendEmailFromDisplayName <String>]
   [-AutomaticallyReplaceAcpProvider <Boolean>]
   [-UseUniqueConferenceIds <Boolean>]
   [-AutomaticallyMigrateUserMeetings <Boolean>]
   [-MigrateServiceNumbersOnCrossForestMove <Boolean>]
   [-EnableDialOutJoinConfirmation <Boolean>]
   [-MaskPstnNumbersType <String>]

**Comment by NikCharlebois** [comment]
@bubbletroubles if you have cycles to take this on, we are more than happy to assist in getting you started!

**Comment by jeff29922** [comment]
@bubbletroubles please reach to me if you need help getting started on this.  If you would like to take this on, please assign yourself, thank you!

**Comment by bubbletroubles** [comment]
Thanks Nik and Jeff - happy to take this on but I don't seem to be able to assign this to myself. Can you allocate it to me?

**Comment by bubbletroubles** [comment]
@NikCharlebois and @jeff29922 - the parameters below are deprecated. From a M365DSC perspective, should they be included in the module or not?

```
   [-SendEmailFromOverride <Boolean>]
   [-SendEmailFromAddress <String>]
   [-SendEmailFromDisplayName <String>]
```
from https://docs.microsoft.com/en-us/powershell/module/skype/set-csonlinedialinconferencingtenantsettings?view=skype-ps
![image](https://user-images.githubusercontent.com/42738824/102564280-339b0d80-412f-11eb-887b-fba2de3d2ceb.png)

**Comment by bubbletroubles** [comment]
One more question...

I have followed along the video as per
https://www.youtube.com/watch?v=Bax6eVshfwY&t=1748s

At the 29m 44s point in the video, it mentions to update the "M365DSCReverse.psm1" file. It seems the format of this file has changed - it seems the script now recursively finds all modules automatically. Can you confirm if I need to make any changes to M365DSCReverse.psm1?

**Comment by NikCharlebois** [comment]
@bubbletroubles that is correct, we've simplified our process and the ReverseDSC interface is now automatically generated the moment a new resource is created.

**Comment by NikCharlebois** [comment]
We should not be including deprecated parameters to answer your first question. Thanks for your help!

**Comment by bubbletroubles** [comment]
I'm still working through this and have some more questions.

What version of Pester is needed when running ```Invoke-TestHarness -IgnoreCodeCoverage```

When using the default built into Windows 2019, I get a lot of errors like the ones below

```
      RuntimeException: '-Invoke' is not a valid Should operator.
      at Get-TestResult, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\Assertions\Should.ps1: line 42
      at <ScriptBlock>, C:\repos\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADGroupsSettings.Tests.ps1: line 255
    [-] Should return true from the Test method 2.42s
      RuntimeException: '-Be' is not a valid Should operator.
      at Get-TestResult, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0\Functions\Assertions\Should.ps1: line 42
      at <ScriptBlock>, C:\repos\Microsoft365DSC\Tests\Unit\Microsoft365DSC\Microsoft365DSC.AADGroupsSettings.Tests.ps1: line 259
```

When using the latest from PowerShellGallery, I get the errors like the ones below

``` Invoke-TestHarness -IgnoreCodeCoverage

Starting discovery in 139 files.
System.Management.Automation.ParameterBindingException: A positional parameter cannot be found that accepts argument '$null'.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\pester\5.1.1\Pester.psm1: line 2903
at Invoke-File, C:\Program Files\WindowsPowerShell\Modules\pester\5.1.1\Pester.psm1: line 2912
at Invoke-BlockContainer, C:\Program Files\WindowsPowerShell\Modules\pester\5.1.1\Pester.psm1: line 2837
at Discover-Test, C:\Program Files\WindowsPowerShell\Modules\pester\5.1.1\Pester.psm1: line 1411
at Invoke-Test, C:\Program Files\WindowsPowerShell\Modules\pester\5.1.1\Pester.psm1: line 2356
at Invoke-Pester<End>, C:\Program Files\WindowsPowerShell\Modules\pester\5.1.1\Pester.psm1: line 4839
at Invoke-TestHarness, C:\repos\Microsoft365DSC\Tests\TestHarness.psm1: line 88
at <ScriptBlock>, <No file>: line 1```

**Comment by bubbletroubles** [comment]
Also another question

Do I need to build in logic if the feature requires a certain license level? E.g. the Teams Dial In Configuration needs M365 E5 or Audio Conferencing license. When I run ``` Get-CsOnlineDialInConferencingTenantSettings ``` on a tenant without these licenses, I get the output

```
PS C:\Users\user> Get-CsOnlineDialInConferencingTenantSettings
Your tenant is disabled for Online Dial-In Conferencing. You are not permitted to use this cmdlet.
    + CategoryInfo          : NotSpecified: (:) [], BvdCmdletException
    + FullyQualifiedErrorId : CmdletInvocationException
    + PSComputerName        : api.interfaces.records.teams.microsoft.com

```

**Comment by bubbletroubles** [comment]
Lastly, do I need to define the DSC resource somewhere? I keep getting the undefined error as per the screenshot, but can't work out where to define it. 

![image](https://user-images.githubusercontent.com/42738824/103242783-a3b95700-49ab-11eb-8679-7f52e104cddb.png)

**Comment by bubbletroubles** [comment]
@NikCharlebois  and @jeff29922 - any chance you can reply to the previous 3 posts to answer the questions? 👍

**Comment by francklinmg** [comment]
Has the issue in question been fixed?

I still get the error:
Command: Set-CsOnlineDialInConferencingTenantSettings -EnableDialOutJoinConfirmation $false

Error:
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsConfiguration : Your tenant is disabled for Online Dial-In Conferencing. You are not permitted to use this cmdlet.
