### ISSUE TITLE
Run-as Service Principal support

### ISSUE THREAD

**Issue by cloudignition** [microsoft/Microsoft365DSC#990]
I noticed many of the modules do not appear to have documented API permissions nor do they appear to support the necessary items to be run by an SPN (Cert Thumbprint, Tenant ID, App ID). Is support across the board for SPNs on the roadmap? I couldn't find it easily in the backlog.

Many of the Teams modules are where i began noticing they aren't present.

**Comment by desmay** [comment]
@cloudignition As the underlying API support Azure AD App authentication M365DSC will add support as well. We started documenting the SPO & OneDrive permissions here https://github.com/Microsoft/Microsoft365DSC/wiki/ODSP-Permissions

**Comment by NikCharlebois** [comment]
Microsoft365DSC depends on underlying PowerShell modules to authenticate to the various workloads. Currently the Intune, Security and Compliance and Teams (Skype for Business Online) only support authenticating using User Credentials. The resources will be updated to support Service Principal support for Authentication once the associated underlying modules start supporting it.
